### ISSUE TITLE
Updating to 3.2 breaks tailwind integration in production

### ISSUE THREAD

**Issue by razzeee** [facebook/docusaurus#10005]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

Upgrading to 3.2 broke the tailwind styling, which I've integrated according to https://medium.com/@bargadyahmed/docusaurus-a-guide-to-seamless-integration-with-tailwind-css-dd202211caac

Here I've added the `banner-preview` with the custom tailwind integration [flathub-infra/documentation@`e0dc841` (#272)](https://github.com/flathub-infra/documentation/pull/272/commits/e0dc841ab1a0bbde60af64ef07cd66972f8f75dd)

It still works fine in dev, but breaks in prod or locally - if I do `yarn build` and then `yarn serve`. Unfortunatly the production errors are not helpful.

Basically https://docs.flathub.org/banner-preview/ should be styled. Like this: 
![image](https://github.com/facebook/docusaurus/assets/5943908/6e79e3dd-e31e-4c0f-8072-23e92aeafb60)

### Reproducible demo

https://github.com/flathub-infra/documentation

### Steps to reproduce

1. Checkout repo
2. Run `yarn`
3. Run `yarn build`
4. Run `yarn serve`
5. Goto http://localhost:3000/banner-preview

### Expected behavior

The page should be styled like in the above image

### Actual behavior

The page isn't styled, presumably because tailwind isn't working, after upgrading to 3.2

### Your environment

- Public source code: https://github.com/flathub-infra/documentation
- Public site URL: https://docs.flathub.org/
- Docusaurus version used: 3.2
- Environment name and version (e.g. Chrome 89, Node.js 16.4): Shouldn't apply as it's run on github
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): Shouldn't apply as it's run on github

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by Arhell** [comment]
more example
https://github.com/open-feature/openfeature.dev/pull/489

**Comment by Airkro** [comment]
When using v3.2.0, [plugins.configurePostCss(options)](https://docusaurus.io/docs/api/plugin-methods/lifecycle-apis#configurePostCss) api not work anymore, maybe is the reason.

**Comment by SJFCS** [comment]
I encounter the same problem.
Docusaurus uses TailWindCSS NPM Start correctly, but CSS style is lost after NPM Run Build

**Comment by SJFCS** [comment]
I had the same problem when I upgraded to version 3.2  that will lost tailwind css style after npm build, I look forward to a solution to this problem

**Comment by Arhell** [comment]
> I don't have any problem with Docusaurus V2 in this sandbox following [this guide](https://dev.to/shannonajclarke/using-tailwindcss-v3-in-docusaurus-in-5-steps-5c26)
> 
> https://stackblitz.com/edit/github-fvf5eb?file=src%2Fpages%2Findex.js

Thanks for the example, but it’s not very clear why everything works in the https://openfeature.dev/ version. https://github.com/open-feature/openfeature.dev/blob/main/docusaurus.config.ts#L279


And after updating the dependencies there are no https://github.com/open-feature/openfeature.dev/pull/489

Although, as mentioned above, everything works locally, but in production, alas. https://deploy-preview-489--openfeature.netlify.app/

**Comment by Arhell** [comment]
and this is for all projects where I updated dependencies yesterday

**Comment by OzakIOne** [comment]
Oops my bad, I forgot after trying to reproduce with the base guide the problem is in production

Indeed I have the same error in the sandbox

**Comment by slorber** [comment]
Thanks for reporting, it's probably a mistake I did when refactoring things to improve performance.

I'll take a look soon and publish a fix ASAP.

**Comment by heysokam** [comment]
I've seen people report that the bug doesn't trigger on `v3.1.0`
Whatever broke it, it also fails in the same way with `v3.1.1`
I went back in history in my repository, removed cache and node_modules, and the bug still triggers

**Comment by heysokam** [comment]
Update: We were on `^3.1.1`, but it was rounding up to `3.2.0` on install.
So false alarm, it triggers on v3.2.0, and works correctly in v3.1.0

**Comment by slorber** [comment]
Can you please test canary `0.0.0-5886`? 
https://docusaurus.io/community/canary

It is the same as v3.2 (no breaking change, but this problem should be fixed)

**Comment by Arhell** [comment]
> Can you please test canary `0.0.0-5886`? https://docusaurus.io/community/canary
> 
> It is the same as v3.2 (no breaking change, but this problem should be fixed)

I checked it on all the projects that I support, everything works, only the one had problems with the plugin https://www.npmjs.com/package/docusaurus-plugin-image-zoom

but I think this is not a problem, I deleted it and everything worked, most likely it does not support the canary version or there is another problem.

Thanks for the work.

**Comment by slorber** [comment]
Great 👍 

I'll release soon

> everything works, only the one had problems with the plugin [npmjs.com/package/docusaurus-plugin-image-zoom](https://www.npmjs.com/package/docusaurus-plugin-image-zoom)

Maybe worth opening an issue on that plugin repo. I can't help if I don't know what the problem was.

> Canary seems to work for me too - but I also had to remove a dependency, cause it was expecting a docusaurus version bigger then 3.0

Which dependency? Which version are you upgrading from? 2.x?

**Comment by razzeee** [comment]
> > Canary seems to work for me too - but I also had to remove a dependency, cause it was expecting a docusaurus version bigger then 3.0
> 
> Which dependency? Which version are you upgrading from? 2.x?

3.2 to the canary

Dependency is `docusaurus-plugin-search-local`

Probably caused by https://github.com/gabrielcsapo/docusaurus-plugin-search-local/blob/main/package.json#L97

**Comment by slorber** [comment]
Ah, I see yes, it might prevent you from using a canary due to the `0.0.0` versions. I will try to figure out a solution to improve this.

**Comment by slorber** [comment]
Fix released in v3.2.1
