### ISSUE TITLE
Code block highlighting in combination with showLineNumbers not rendering correctly

### ISSUE THREAD

**Issue by khameeteman** [facebook/docusaurus#10013]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [ ] I have tried the `npm run clear` or `yarn clear` command.
- [ ] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io.
- [ ] I have read the console error message carefully (if applicable).

### Description

Using the following syntax

````
```python {2}
print("apple")
print("banana")
```

```python {2} showLineNumbers
print("apple")
print("banana")
```
````

results in the following rendering

![image](https://github.com/facebook/docusaurus/assets/73279381/576fa707-7efd-49f9-bdc3-f462382a9404)

### Steps to reproduce

See syntax in description

### Expected behavior

I would expect the behavior as documented here: https://docusaurus.io/docs/markdown-features/code-blocks#line-numbering

### Actual behavior

See image in description

### Your environment

- Docusaurus version: 3.0.1
- Chrome version: 122.0.6261.94 (Official Build) (64-bit)
- OS:  Linux 6.7.6-arch1-1

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by slorber** [comment]
Prove it with a https://docusaurus.new/stackblitz repro

https://stackblitz.com/edit/github-xza5zo?file=docs%2Fintro.md

![CleanShot 2024-04-04 at 15 34 32](https://github.com/facebook/docusaurus/assets/749374/c397fba1-1431-45d3-b8b8-291ca0016b07)
