### ISSUE TITLE
Broken anchors: page not scroll to the right section

### ISSUE THREAD

**Issue by JEricaM** [facebook/docusaurus#10028]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [ ] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io.
- [ ] I have read the console error message carefully (if applicable).

### Description

Hi to everyone.
I have a problem with anchors in my documentation.
I've updated docusaurus to version 3.2.1

```
"@docusaurus/core": "^3.2.1",
"@docusaurus/preset-classic": "^3.2.1",
"@docusaurus/module-type-aliases": "^3.2.1",
```

The problem is that if I link a subsection of my guide, for example
[https://docs.avacysolution.com/docs/avacy-saas/cookie-policy#aggiornamenti-ai-termini-della-cookie-policy](https://docs.avacysolution.com/docs/avacy-saas/cookie-policy#aggiornamenti-ai-termini-della-cookie-policy)
the page opens at the top and not at the correct section of the page. 
The link is generated from the table of content.

I don't understand why this behaviour.
My subtitles are simply like that

```
## Modalità manuale

La modalità manuale ti offre un modo flessibile e personalizzato per scrivere manualmente la tua Cookie Policy, consentendoti di definire i dettagli e le specifiche in base alle tue esigenze e conformità alle leggi sulla privacy applicabili. Puoi utilizzare l'editor di testo fornito per digitare il contenuto della tua Cookie Policy direttamente nel formato RTF, che supporta opzioni di formattazione avanzate come caratteri diversi, stili, grassetto, corsivo, elenchi puntati e numerati.

![alt_text](/images/privacy-2.png)
```

### Reproducible demo

https://docs.avacysolution.com/docs/avacy-saas/cookie-policy#aggiornamenti-ai-termini-della-cookie-policy

### Steps to reproduce

Create a docusaurus project and click on a specific link as 
https://docs.avacysolution.com/docs/avacy-saas/cookie-policy#aggiornamenti-ai-termini-della-cookie-policy 

### Expected behavior

The page opens in the specific section

### Actual behavior

The page open ignoring the link

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by AnthonyTsu1984** [comment]
Hi, probably the same issue here.
I have a Chinese site where I add anchor id manually as follows:
<img width="642" alt="image" src="https://github.com/facebook/docusaurus/assets/115786031/4fd4e066-d2e1-48e4-b428-63d4437e9e67">

But I don't know why such titles do not bear any anchor styles.

<img width="673" alt="image" src="https://github.com/facebook/docusaurus/assets/115786031/1ca352a9-df49-40b5-8616-3b9a449f73ff">

**Comment by AnthonyTsu1984** [comment]
I have checked the differences between the dependencies of a fresh-install site and my site, and it turns out that it's the fault of the dependencies. Clear your dependencies and remove conflicting and unnecessary dependencies. Everything will go smoothly then.

**Comment by fuxin967** [comment]
Also have the same issue

**Comment by AnthonyTsu1984** [comment]
> Also have the same issue

Try to clean the dependencies as I do. The update command that Docusaurus provides does not cover everything. 

<img width="874" alt="image" src="https://github.com/facebook/docusaurus/assets/115786031/bf53da66-d9b6-4b5b-9491-ba94b74f8cd9">

Check your `package.json` and make sure that you have these dependencies with the correct versions.

After cleaning my dependencies, the broken anchor warnings are gone forever.

**Comment by fuxin967** [comment]
Hi @AnthonyTsu1984 , thank you for your quick reply. Actually I tried to create a brand new project using scaffold command
`npx create-docusaurus@latest my-website classic --typescript`
which has exact the same dependencies as you pointed out, and it does not work also.
Another tried is creating a repro with https://new.docusaurus.io/, also does not work.

And the issue is not about broken anchor warnings, it's about clicking a url with an anchor and it does not scroll to the right position

**Comment by JEricaM** [comment]
@slorber thank you so much for the answer!! solved my problem :D
