### ISSUE TITLE
The <!--truncate--> line in my long blog post on the initialized website is not causing the blog post size to be limited.

### ISSUE THREAD

**Issue by ToeJammm** [facebook/docusaurus#10043]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [ ] I have tried the `npm run clear` or `yarn clear` command.
- [ ] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

When I installed the package and started the site, the long blog post page had a button for me to click to see the rest of the blog post. When I clicked it, it expanded into a long list of lorem ipsum statements. I noticed there wasn't a button to un-expand the post so I tried refreshing, re-starting, and re-installing the site, but the original blog post would not un-expand. Now it seems like when I reinstall its already expanded and the  command isn't having any affect on the post.

### Steps to reproduce

1. install using npx create-docusaurus@latest my-website classic
2. go to long blog post page and expand post
3. try to un-expand the post in any way possible

### Expected behavior

I thought If I refreshed or re-started the site it would be in its original format

### Actual behavior

it would not change from its expanded form no matter what I tried.

### Your environment

- Public source code:
- Public site URL:
- Docusaurus version used:
- Environment name and version (e.g. Chrome 89, Node.js 16.4):
- Operating system and version (e.g. Ubuntu 20.04.2 LTS):

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by Josh-Cena** [comment]
What you are seeing is not "expand". It's called "Read more", which is a link that takes you to the blog post's own page. You should use your browser's back button instead.
