### ISSUE TITLE
Multi-Instance Routes Not Working in v3.2.1

### ISSUE THREAD

**Issue by ojbravo** [facebook/docusaurus#10052]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

Running multi-instance in <= v3.1.1 works flawlessly. Upgrading to >= v3.2.0 breaks the non-default instance and displays a "Page Not Found". This occurs when the default instance has a ```routeBasePath: '/'```.

### Reproducible demo

https://stackblitz.com/edit/github-cwn3ck?file=package.json

### Steps to reproduce

1. Go to https://stackblitz.com/edit/github-cwn3ck?file=package.json
2. Notice that ```@docusaurus/core```, ```@docusaurus/preset-classic```, ```@docusaurus/module-type-aliases```, ```@docusaurus/types``` are all at ```v3.1.1``` in the ```package.json```
3. Using the main navigation on the website, click on the ```Default Instance``` and ```Second Instance``` links. Both pages should appear as expected.
4. In the ```package.json``` file, update ```@docusaurus/core```, ```@docusaurus/preset-classic```, ```@docusaurus/module-type-aliases```, ```@docusaurus/types``` to ```v3.2.1```
5. Run the following commands in the terminal:
> - ```Ctrl+C```
> - ```yarn clear```
> - ```yarn```
> - ```yarn start```
6. Using the main navigation on the website, click on the ```Default Instance``` and ```Second Instance``` links.  The ```Default Instance``` should appear as expected, but the ```Second Instance``` will display a ```Page Not Found```.

### Expected behavior

Both instances should work in v3.2.1

### Actual behavior

The ```Default Instance``` appears as expected, but the ```Second Instance``` will display a ```Page Not Found```.

### Your environment

- Public source code: https://stackblitz.com/edit/github-cwn3ck?file=package.json
- Public site URL: https://stackblitz.com/edit/github-cwn3ck?file=package.json
- Docusaurus version used: 3.1.1 and 3.2.1
- Environment name and version (e.g. Chrome 89, Node.js 16.4): Chrome 123, Node 18
- Operating system and version (e.g. Ubuntu 20.04.2 LTS):  Mac OS Ventura

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by slorber** [comment]
Thanks for reporting, it should be fixed now

You can use the latest canary until we release: https://docusaurus.io/community/canary

(it should be safe, no breaking change, really it's 3.2.1 with just a few extra retrocompatible commits)

**Comment by johnrengelman** [comment]
Confirming that this fixed this issue in my project. Looking forward to 3.2.2 to avoid issues with peerDependencies in 3rd party plugins (always end up having to manually edit lockfiles to make canaries work)
