### ISSUE TITLE
Algolia Contextual Search Generates Incorrect FaceFilters

### ISSUE THREAD

**Issue by karl-cardenas-coding** [facebook/docusaurus#10050]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

When experimenting with the Algolia Crawler, I noticed that when contextual search is enabled no results are returned. The API requests are successful (status code 200), but no hits are returned. 

I stumbled upon this Aloglia [support thread](https://discourse.algolia.com/t/no-results-with-docusaurus-contextual-search/19409) trying to understand what might be causing the issue. 

Upon closer investigation I noticed how the `facetFilter` parameter generated by Docusarus is incorrect compared to what Algolia expects. 

The Crawler’s search UI includes the following values in the searchFacets query when I enable some custom facets such as as docusaurus_tag , version, and language.

```
[["docusaurus_tag:docs-default-4.3.x"],["version:4.3.x"],["lang:en"]]"}]}
```

This returns results as expected.

Now, in Docusarus, when contextual search in enabled, here is what is provided in the API request.

```
 ["language:en",["docusaurus_tag:default","docusaurus_tag:docs-default-current","docusaurus_tag:docs-api-current"]]"}]}
```
The list value is not generated correctly.

If I re-create the API post request with this vale for the faceFilter, I get the expected results.

```
facetFilters=[["docusaurus_tag:docs-default-4.3.x"],["version:4.3.x"],["lang:en"]]"}]}
```

### Steps to reproduce

You can use this [codebox URL](https://codesandbox.io/p/devbox/dank-wind-8rrkml?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clv30oo7600083b6hm5u4zbl3%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clv30oo7500033b6haceenu66%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clv30oo7600053b6h73cf6xet%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clv30oo7600073b6h6pvnupxc%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clv30oo7500033b6haceenu66%2522%253A%257B%2522id%2522%253A%2522clv30oo7500033b6haceenu66%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clv30q0mz00023b6irav8mbj4%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A86%252C%2522startColumn%2522%253A13%252C%2522endLineNumber%2522%253A86%252C%2522endColumn%2522%253A13%257D%255D%252C%2522filepath%2522%253A%2522%252Fdocusaurus.config.js%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clv30q0mz00023b6irav8mbj4%2522%257D%252C%2522clv30oo7600073b6h6pvnupxc%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clv30oo7600063b6hgv6r8veg%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A3000%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clv30oo7600073b6h6pvnupxc%2522%252C%2522activeTabId%2522%253A%2522clv30oo7600063b6hgv6r8veg%2522%257D%252C%2522clv30oo7600053b6h73cf6xet%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clv30oo7600043b6hok3ef4va%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%257D%255D%252C%2522id%2522%253A%2522clv30oo7600053b6h73cf6xet%2522%252C%2522activeTabId%2522%253A%2522clv30oo7600043b6hok3ef4va%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D).

But or spin up a quick Docusarus project and use my Algolia config or the one included in the Algolia [issue](https://discourse.algolia.com/t/no-results-with-docusaurus-contextual-search/19409).

### Expected behavior

The expected behavior is to return the expected results using the facefilter Docusarus includes in the post request.

### Actual behavior

No results are returned.

### Your environment

- [Public source code](https://github.com/spectrocloud/librarium/blob/master/docusaurus.config.js#L359-L379).  
- Public site URL:  https://docs.spectrocloud.com
- Docusaurus version used: 3.2.1
- Environment name and version (e.g. Chrome 89, Node.js 16.4): Node.js 18, Chrome 123.0.6312.123
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): MacOS 14.4.1 (23E224) 

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by karl-cardenas-coding** [comment]
We can close this ticket. I figured out the issue. 
Check your index and make sure `language` is an exposed `facet`.

![CleanShot 2024-04-16 at 17 25 54](https://github.com/facebook/docusaurus/assets/29551334/b65ee0b4-b9d2-4e19-bcf9-e5eb47bb948e)


I'm not sure if the default Algolia crawler config is what's causing the issue but `lang` is not gonna help you. 

```json
{
      attributesForFaceting: [
        "type",
        "lang",
        "language",
        "version",
        "type",
        "docusaurus_tag",
      ]
}
```

**Comment by slorber** [comment]
Yes, you need to make sure your index match our official recommendations, otherwise it's your responsibility to make things work

The recommended config contains that "language" facetting field

https://docsearch.algolia.com/docs/templates/#docusaurus-v3-template

**Comment by slorber** [comment]
If that helps anyone stumbling on this issue, I posted this answer in a few Algolia issues, hope it helps.

https://github.com/facebook/docusaurus/issues/6693#issuecomment-2039757018

> ## No search result?
> For anyone passing by, if you don't get any Algolia search results:
> 
> * make sure that your Algolia index has the fields in the screenshot below
> * If you don't see these fields, then you have an index config problem
> * You should check your crawler config, make sure it matches the recommended one, and then delete/recreate your index based on the newly updated/fixed crawler config ([Algolia team recommendation](https://github.com/facebook/docusaurus/issues/9200#issuecomment-1667338492))
> 
> ![image](https://private-user-images.githubusercontent.com/749374/320003114-b518cfe4-6b0c-480a-ab7b-be9f098f9cd3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMzNDIzNTIsIm5iZiI6MTcxMzM0MjA1MiwicGF0aCI6Ii83NDkzNzQvMzIwMDAzMTE0LWI1MThjZmU0LTZiMGMtNDgwYS1hYjdiLWJlOWYwOThmOWNkMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxN1QwODIwNTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNWFmYjg1OWRjMjUyMTUwOGY2YTIzZGIyZDJlMTk0YmFkODE2Y2VlMzA1M2Q3YjU5ZTlmNjI0NGY2ZWY3Yjk1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.NXsn4boZ0emUgUd0Cnx9IQJPhE7Zz5zbJMD_pewkyVI)
> 
> See also: [#10007 (comment)](https://github.com/facebook/docusaurus/discussions/10007#discussioncomment-9021352)

**Comment by slorber** [comment]
@karl-cardenas-coding thanks for your proposal, but it was already on my todo list to add this index troubleshooting section so I just did it (https://github.com/facebook/docusaurus/pull/10056). 

We get many support requests about this over time so it's important to explain this thing properly so I preferred to do it myself.

**Comment by karl-cardenas-coding** [comment]
No worries 😊 @slorber  and thank you for adding the updates. That's gonna help a lot for future users.
