### ISSUE TITLE
Broken link transformation

### ISSUE THREAD

**Issue by iAdramelk** [facebook/docusaurus#10072]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

`.mdx` extension is not removed from the link if the link text is split into two lines.

### Reproducible demo

https://codesandbox.io/p/devbox/determined-northcutt-fdkm45?file=%2Fdocs%2Findex.mdx%3A5%2C1

### Steps to reproduce

Put this code in the mdx file in the `/docs/` folder (assuming that `installation.mdx file` exists in the same folder):

```
[Some
link](./installation.mdx)

[Some link](./installation.mdx)
```

### Expected behavior

I expect that both links will be transformed to `<a href="/docs/installation">Some link</a>`.

### Actual behavior

In practice, only the second link is transformed correctly. The first link is left as `<a href="/installation.mdx">Some
link</a>`.

See the attached codesandbox demo.

### Your environment

- Public source code and demo: https://codesandbox.io/p/devbox/determined-northcutt-fdkm45?file=%2Fdocs%2Findex.mdx%3A1%2C1-4%2C32
- Docusaurus version used: 3.2.1 (3.2.0 in the demo)

### Self-service

- [X] I'd be willing to fix this bug myself.

**Comment by slorber** [comment]
This is already tracked in https://github.com/facebook/docusaurus/issues/9048 and related to our linkify function

I understand you'd be willing to attempt to fix it, but this is not so easy to migrate from processing docs as strings to ASTs so I'd rather solve this myself.
