### ISSUE TITLE
Blob storage files render dynamically

### ISSUE THREAD

**Issue by AshokButra** [facebook/docusaurus#10087]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Description

I have tried of implementing blob storage files to render dynamically instead of taking files from local docs directory, however I have tried with many approaches and any of them didn't worked for me, please suggest me the approach of adding this functionality

### Motivation

I was working under some project of docusaurus where I'm building a specific website for technical doc storage for an internal project, so all the docs uploaded by user will get stored in azure blob storage and unwanted to fetch those files from there and show as docusaurus documentaion

### API design

I must and surely need this feature to be implemented to move my project forward, regarding API design I have created APIs for fetching data from blob storage using nodejs backend but then after I don't get the approach of implementation of it in docusaurus

### Self-service

- [X] I'd be willing to contribute this feature to Docusaurus myself.

**Comment by slorber** [comment]
Hey

I'm sorry but Docusaurus issues are not to provide user support. We have a discord server for that kind of community support.

We don't provide particular support for Azure, and I don't even know what blob storage is (I assume with that name it's the Azure variant of S3? 🤷‍♂️ ) 

Docusaurus is only responsible for building a static deployment. If you think Docusaurus does not do its job well, please explain why and what exactly you expect from us in terms of static file output. If you fail to host your site on Azure, then read Azure docs and contact their support for help.
