### ISSUE TITLE
DocCards incorrectly pluralise the number of elements within them when only one is present

### ISSUE THREAD

**Issue by olijeffers0n** [facebook/docusaurus#10098]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

When a categories contain only a single item, it is correctly pluralised. See https://github.com/facebook/docusaurus/blob/main/packages/docusaurus-theme-classic/src/theme/DocCard/index.tsx#L35 - There appears to be some reference to pluralisation, however i get `1 items`

### Steps to reproduce

https://github.com/PaperMC/docs Repo, and look at our Misc Project with the Tools category

### Expected behavior

1 Item

### Actual behavior

1 Items

### Your environment

- Public source code: https://github.com/PaperMC/docs
- Public site URL: https://docs.papermc.io/
- Docusaurus version used: 3.2.1
- Environment name: Chrome
- Operating system and version: Ubuntu 20.04.2

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by Josh-Cena** [comment]
Yes... I think the English version needs plural categories too.

**Comment by slorber** [comment]
Hmmm yes, I actually just noticed that as well as part of this other PR: https://github.com/facebook/docusaurus/pull/10111#pullrequestreview-2047453689

Sadly, all the theme-translation languages have a single plural form too. I'll do my best to fix them with google translate, but there will probably be mistakes for some languages.
