### ISSUE TITLE
YAML code highlighting highlights much less than prismjs demo site

### ISSUE THREAD

**Issue by o-l-a-v** [facebook/docusaurus#10094]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [ ] I have tried the `npm run clear` or `yarn clear` command.
- [ ] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io.
- [ ] I have read the console error message carefully (if applicable).

### Description

We use Docusaurus with a dark theme and the Dracula theme for code highlighting. We also use CommonMark for MD files, not MDX.

We've enabled code highlighting for some languages, including YAML.

Comparing the output Docusaurus produces vs. prismjs.com demo page ( <https://prismjs.com/test.html#language=yaml> ), it looks like Docusaurus doesn't highlight much.

_Sample YAML is a reusable workflow, I removed the reusable workflow part as it points to an internal repo of ours._

##### GitHub

```yaml
name: Analyze templates using PSrule

on:
  workflow_dispatch:
  schedule:
    - cron: "0 10 * * 0"

permissions:
  id-token: write
  contents: read
  security-events: write
  actions: read
```

##### Prismjs.com demo page using the "Twilight" theme

![image](https://github.com/facebook/docusaurus/assets/6450056/46be3675-755e-4473-8ef4-63cabe222411)

##### Docusaurus

![image](https://github.com/facebook/docusaurus/assets/6450056/9728c34c-14d2-4a31-a368-f7298f824e29)

### Steps to reproduce

1. Use provided YAML, put it inside a markdown file like so

````
```yaml
<code here>
```
````

Compare what Docusaurus outputs vs. the prismjs.com demo.

### Expected behavior

The same parts should be highlighted, but colors are decided by the theme.

### Actual behavior

Docusaurus highlight almost nothing.

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by slorber** [comment]
This is a theming issue. 

The expected class are there `token key atrule` similar to the prism playground, but no style gets applied because the theme doesn't configure style for that kind of token.

We don't maintain the Dracula theme so it's not really a Docusaurus bug. 

It works on the Docusaurus site:
https://docusaurus.io/docs/markdown-features#front-matter

![CleanShot 2024-05-02 at 15 22 24](https://github.com/facebook/docusaurus/assets/749374/0f25d1b5-aff5-41c4-8d27-9db7c896fe18)


As far as I remember we had the problem on our own website, and has to "extend" a bit the dracula theme to fix it:


```js
/**
 * Copyright (c) Facebook, Inc. and its affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

import {themes, type PrismTheme} from 'prism-react-renderer';

const baseTheme = themes.vsDark;

export default {
  plain: {
    color: '#D4D4D4',
    backgroundColor: '#212121',
  },
  styles: [
    ...baseTheme.styles,
    {
      types: ['title'],
      style: {
        color: '#569CD6',
        fontWeight: 'bold',
      },
    },
    {
      types: ['property', 'parameter'],
      style: {
        color: '#9CDCFE',
      },
    },
    {
      types: ['script'],
      style: {
        color: '#D4D4D4',
      },
    },
    {
      types: ['boolean', 'arrow', 'atrule', 'tag'],
      style: {
        color: '#569CD6',
      },
    },
    {
      types: ['number', 'color', 'unit'],
      style: {
        color: '#B5CEA8',
      },
    },
    {
      types: ['font-matter'],
      style: {
        color: '#CE9178',
      },
    },
    {
      types: ['keyword', 'rule'],
      style: {
        color: '#C586C0',
      },
    },
    {
      types: ['regex'],
      style: {
        color: '#D16969',
      },
    },
    {
      types: ['maybe-class-name'],
      style: {
        color: '#4EC9B0',
      },
    },
    {
      types: ['constant'],
      style: {
        color: '#4FC1FF',
      },
    },
  ],
} satisfies PrismTheme;

```
