### ISSUE TITLE
broken styles after build

### ISSUE THREAD

**Issue by lumi2021** [facebook/docusaurus#10113]
- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

I'm working on the new Silk.NET presentation and documentation website where i was requested to use docusaurus to do it. The library never shows any error during the debugging process and the development goes well until i need to build the website, when i noticed the problem.

Most of the styles and media queries are being broken by the CSS Minimizer plugin. It logs don't help to solve any problem because the minimize is done after all the compilation, so my CSS code is unrecognizable after this.

### Steps to reproduce

1. clone the [website repo](https://github.com/lumi2021/Silk.NET-website)
2. execute `npm run build`
3. execute `npm run serve`

### behavior
The styles should be exactly what it is during the debug (`npm run start`)

One of the best examples, the first section of the main page that is being rendered as the follow in debug:
![image](https://github.com/facebook/docusaurus/assets/94462076/6ee70312-ea5f-4844-aed5-eb3f216b99a3)

It's being rendering as it after the build process:
![image](https://github.com/facebook/docusaurus/assets/94462076/d5dadbcb-3e0b-41a1-8647-f5f2b947a476)

### environment
- Public source code: https://github.com/lumi2021/Silk.NET-website
- Public site URL: N/A
- Docusaurus version used: lib: `3.2.2`, --version: `10.4.0`
- Environment name and version: Mozilla/5.0
- Operating system and version: Win 10

**Comment by slorber** [comment]
Agree with have a bug, already tracked in https://github.com/facebook/docusaurus/issues/9303

Note CSS nesting is [not yet "widely" supported](https://caniuse.com/css-nesting). 

![CleanShot 2024-05-09 at 12 07 41@2x](https://github.com/facebook/docusaurus/assets/749374/0bb02474-1aaf-4cf4-a6b2-21bdc0ea955d)


Only 81% full support, that's maybe a bit too soon to emit CSS nesting, but maybe we could at least support it as an authoring format and emit non-nested CSS (similar to what SCSS does).

**Comment by lumi2021** [comment]
the idea of emit non nested CSS looks really good for me, but isn't so much work for docusaurus team? Like an entire css parser and etc...

**Comment by lumi2021** [comment]
> Only 81% full support, that's maybe a bit too soon to emit CSS nesting, but maybe we could at least support it as an authoring format and emit non-nested CSS (similar to what SCSS does).

the idea of emit non nested CSS looks really good for me, but isn't so much work for docusaurus team? Like an entire css parser and etc...

**Comment by slorber** [comment]
Forgot to close as duplicate

> the idea of emit non nested CSS looks really good for me, but isn't so much work for docusaurus team? Like an entire css parser and etc...

We wouldn't do this on our own but likely use PostCSS for that.

https://github.com/csstools/postcss-plugins/tree/main/plugins/postcss-nesting

Since postcss-preset-env supports browserslist, we should probably use that in the future
