### ISSUE TITLE
[Css Minimizer plugin] Build Broken after upgrading from 3.2.1 to 3.3.2

### ISSUE THREAD

**Issue by lpicchi** [facebook/docusaurus#10123]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io.
- [ ] I have read the console error message carefully (if applicable).

### Description

After upgrading my docusaurus project from 3.2.1 to 3.3.2 it fails to produce production build

### Steps to reproduce

yarn build

### Expected behavior

Project to build properly

### Actual behavior

Project fails with error

```
[INFO] [es] Creating an optimized production build...

✖ Client
  Compiled with some errors in 53.20s

✔ Server


[ERROR] Client bundle compiled with errors therefore further build is impossible.
assets/css/styles.46e78c20.css from Css Minimizer plugin
Error: Call retries were exceeded

--------------------------

assets/css/styles.97c8602a.css from Css Minimizer plugin
Error: Call retries were exceeded
```

### Your environment

- Public source code:
- Public site URL:
- Docusaurus version used:
- Environment name and version (e.g. Chrome 89, Node.js 16.4):
- Operating system and version (e.g. Ubuntu 20.04.2 LTS):

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by lpicchi** [comment]
Workaround: USE_SIMPLE_CSS_MINIFIER=true

```json
    "build": "cross-env USE_SIMPLE_CSS_MINIFIER=true docusaurus build",
```

**Comment by slorber** [comment]
If there is a bug to fix, we'd need a smaller repro to figure out what is causing the bug. If your site is not open-source, please create a public fork of it and remove everything sensitive that you can't share with us.

I'll have to close this issue because it's unactionable in its current state.
The minimizer works for us and other sites that upgraded.
