### ISSUE TITLE
Missing `:::` in Chinese translation.

### ISSUE THREAD

**Issue by SilianZ** [facebook/docusaurus#10133]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Description

![image](https://github.com/facebook/docusaurus/assets/113701655/991b72d0-f01a-4e85-878e-e9ee8f8f09d1)
![image](https://github.com/facebook/docusaurus/assets/113701655/f7011877-f989-40ad-a7a3-d25fa23585b8)
In Crowdin's Chinese Simplified Chinese (zh-Hans) translation, `:::` is missing, which causes the admonitions to not be properly terminated and the following non-admonitions content is added.

https://docusaurus.io/zh-CN/docs/next/i18n/tutorial

This is most likely due to the fact that a translator deleted `:::` while translating.

*Translated by machines.

### Self-service

- [ ] I'd be willing to address this documentation request myself.

**Comment by slorber** [comment]
Thanks, it should be better now

I had to delete a few Crowdin translated admonitions to fix it.
