### ISSUE TITLE
Trailing Slash Appended to Asset Files in Docusaurus 3.3.2

### ISSUE THREAD

**Issue by karl-cardenas-coding** [facebook/docusaurus#10139]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

We are attempting to upgrade to Docusarus 3.3.2, and we are noticing an interesting behavior with trailing slashes on asset files.  We have by default the following `baseURL` and `trailingSlash` configuration

```js
  baseUrl: "/",
  trailingSlash: true,
```

After the upgrade, if we do a `docusarus serve` we get a broken page that are missing assets.  Upon closer inspection we noticed that asset files are specified with a `/` at the end.  For example `runtime-main.d2091a86.js/` 

![image](https://github.com/facebook/docusaurus/assets/29551334/6d6145d2-4d87-443f-b011-86eb01011d90)

It's strange that not all files have this behavior.

If we change the `trailingSlash` configuration to `false` then this issue goes away. 

### Reproducible demo

We have a PR in our public  repo that can be used to test
https://github.com/spectrocloud/librarium/pull/2839.

Just make sure you set the following env values before starting any server or build

```text
ALGOLIA_APP_ID=1234567890
ALGOLIA_SEARCH_KEY=1234567890
```

### Steps to reproduce

Upgrade to Docusarus 3.3.2 and set the configuration file to have the following `baseURL` and `trailingSlash` configuration

```js
  baseUrl: "/",
  trailingSlash: true,
```

### Expected behavior

We would expect asset files to not have an extra `/` at the end.

### Actual behavior

Pages are loading with missing assets.

### Your environment

- Public source code: https://github.com/spectrocloud/librarium
- Public site URL: https://docs.spectrocloud.com
- Docusaurus version used: 3.2.0
- Environment name and version (e.g. Chrome 89, Node.js 16.4): Chrome 124.0.6367.203
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): MacOS 14.4.1 

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by slorber** [comment]
😅 sorry for that, likely a regression introduced by https://github.com/facebook/docusaurus/pull/10090

I forgot serve might not just serve HTML files 😓

**Comment by karl-cardenas-coding** [comment]
All good @slorber and thank you for validating what we seemed was a bit odd 😄
