### ISSUE TITLE
Markdown doesn't render in OgDescription (metadata)

### ISSUE THREAD

**Issue by mattkanwisher** [facebook/Docusaurus#1014]
## 🐛 Bug Report

(A clear and concise description of what the bug is)

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## To Reproduce

1. curl https://loomx.io/developers/docs/en/phaser-sdk-demo.html
2. You can see ```
<meta property="og:description" content="![Game screenshot](/developers/img/screenshot.png)"/>```
3. Source code is here https://github.com/loomnetwork/loom-sdk-documentation 

<img width="515" alt="screen shot 2018-10-02 at 3 28 39 pm" src="https://user-images.githubusercontent.com/3032/46337496-dc94e500-c657-11e8-9f01-0eb957947fa6.png">

## Expected behavior

Expected to see the image, or text of the *rendered* markdown, now the raw markdown text. 

## Actual Behavior

Og:Description has markdown in it

```
<meta property="og:description" content="![Game screenshot](/developers/img/screenshot.png)"/>
```

<img width="515" alt="screen shot 2018-10-02 at 3 28 39 pm" src="https://user-images.githubusercontent.com/3032/46337538-f504ff80-c657-11e8-98b9-4ce357fdca00.png">

## Reproducible Demo

https://loomx.io/developers/docs/en/phaser-sdk-demo.html

We are on Docasuarus hash(a6db22b6ff2f3c11c7dbbbf45d54e7e03e3557d7)  but I tested with "1.4.0", and source to repo is here https://github.com/loomnetwork/loom-sdk-documentation

Seems like i18n broke on upgrade ;( so I can't upgrade to 1.4.0 immediately without breaking out side for non English speakers, but problem does exist on newest build of docasaurus

**Comment by sinodko** [comment]
Is this issue free? I would like to look at it.

**Comment by yangshun** [comment]
@sinodko it's yours!

I've added an "issue: claimed" label so that others will know not to start work on the issue. If you change your mind about the issue, no worries! Just let me know so that I can remove the label and free it up for someone else to claim.

I'll check in with you periodically so that we can keep the task updated with the progress.

**Comment by sinodko** [comment]
> As for markdown doesnt render correctly, its indeed a bug. Accepting PR on that 😆.
> 
> We should render the markdown and not the literal markdown string here

Hello @endiliey, If I've understood you correctly, raw HTML should be rendered here instead of markdown text. Am I right? Thanks :)
