### ISSUE TITLE
'showLastUpdateTime' being rendered incorrectly when deployed through Cloudflare, Vercel...

### ISSUE THREAD

**Issue by namnguyenthanhwork** [facebook/docusaurus#10148]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Description

`showLastUpdateTime` key maybe working incorrectly when deployed through Cloudflare, Vercel... I don't update my docs, but when I deployed, all docs page updated latest date.

### Self-service

- [X] I'd be willing to address this documentation request myself.

**Comment by ilg-ul** [comment]
I don't know the specifics of your deployment method, but if the update time is computed from the git commit dates, you need to make sure you do a deep `git clone`. A shallow one (depth = 1) results in all pages having the lastUpdateTime set to the time when the clone was performed.
