### ISSUE TITLE
Last Updated Time Misleading

### ISSUE THREAD

**Issue by JoelMarcey** [facebook/Docusaurus#1015]
## 🐛 Bug Report

The last updated time is misleading and possibly wrong. We don't want to take into account versioning in last updated -- only content changes. Also, the folder move to `v1` and `v2` might have made things out of whack a bit.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## To Reproduce

1. Go to https://docusaurus.io/docs/en/installation - look at last updated time
1. Go to https://docusaurus.io/docs/en/1.0.12/installation - look at last updated time
1. They are the same. They shouldn't be in my opinion.

## Expected behavior

The correct last updated time based on content changes

## Actual Behavior

Every doc has the same last updated time.

## Reproducible Demo

https://docusaurus.io

**Comment by JoelMarcey** [comment]
@yangshun - do you agree that the times are misleading?

I am going to assign this to @fiennyangeln as part of her work on #980. She can fix this and use that same fix to put the last contributor of each document.

**Comment by yangshun** [comment]
Yes, I agree they are misleading, but they are not technically wrong, because moving a file is indeed updating it strictly speaking.

I'm not sure how else we can do better. Perhaps we can find the latest commit where it's not a movement but a modification.

**Comment by JoelMarcey** [comment]
> Perhaps we can find the latest commit where it's not a movement but a modification.

Exactly. I chatted with @fiennyangeln this morning and that is exactly what she was going to look at doing. I think that would be more useful information to someone reading the docs.

**Comment by fiennyangeln** [comment]
@yangshun I feel like currently even if it's not moved, it will show the time when we start a new version, not when the content last changed before we create the version
