### ISSUE TITLE
<span style="color:orange"> in Markdown causes build to fail 

### ISSUE THREAD

**Issue by aleenatorres** [facebook/docusaurus#10169]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [ ] I have tried the `npm run clear` or `yarn clear` command.
- [ ] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io.
- [ ] I have read the console error message carefully (if applicable).

### Description

Updating text color in the markdown file itself is causing the build to break. e.g. `<span style="color:orange">some text</span>`

### Steps to reproduce

Added this text to my Markdown file: `<span style="color:orange">some text</span>`

### Expected behavior

Text is orange

### Actual behavior

Build fails

### Your environment

- Public source code:
- Public site URL:
- Docusaurus version used:
- Environment name and version (e.g. Chrome 89, Node.js 16.4):
- Operating system and version (e.g. Ubuntu 20.04.2 LTS):

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by slorber** [comment]
This is how MDX works.

You have to use JSX style prop instead of Html inline style string.

Or you can try our common mark mode.

https://docusaurus.io/docs/markdown-features
https://docusaurus.io/docs/markdown-features/react
