### ISSUE TITLE
Invalid modification of Webpack's build configuration

### ISSUE THREAD

**Issue by yinsel** [facebook/docusaurus#10170]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [ ] I have read the console error message carefully (if applicable).

### Description

Unable to modify the output name of the image, I would like to remove the hash of the image resource

config:

```js
plugins: [
    async function myPlugin(context, options) {
      return {
        name: 'my-plugin',
        async configureWebpack(config, isServer, utils) {
          const imageRule = config.module.rules.find(rule => rule.test && rule.test.test('.png'));
          if (imageRule) {
            imageRule.use[0].options.name = "assets/images/[name].[ext]";
          }
          console.log(config.module.rules[0].use[0].options)
        },
      };
    },
  ]
```

As shown in the figure, The value of name was successfully modified, but it does not take effect：

![image](https://github.com/facebook/docusaurus/assets/91541985/000285ba-a4f5-4b80-a59e-a5ea91789b59)

### Steps to reproduce

The steps provided in the official tutorial

### Expected behavior

Output image name to remove hash

### Actual behavior

Output image name without removing hash

### Your environment

- Public source code:
- Public site URL:
- Docusaurus version used: latest
- Environment name and version (e.g. Chrome 89, Node.js 16.4): Node.js 18
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): windows 11 x64

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by slorber** [comment]
Why would you like to review move it in the first place.

It's not a bug, this hash is added on purpose for caching reasons. If you want no hash you can still put assets in the static folder

**Comment by yinsel** [comment]
> Why would you like to review move it in the first place.
> 
> It's not a bug, this hash is added on purpose for caching reasons. If you want no hash you can still put assets in the static folder

Thank you for your reply. As I would like to collaborate with OBSIDIAN to write notes, I need external link images. Without a hash, it would be very convenient. For images, my website has not received much traffic, so I can discard the image hash.

**Comment by slorber** [comment]
Can you show me a repeo

Where do you put the image, and what do you want the url to be?

**Comment by yinsel** [comment]
> Can you show me a repeo
> 
> Where do you put the image, and what do you want the url to be?

My repo has not uploaded any images yet. By placing the marked down images in the static folder, there will be a copy without a hash in the build output, which does not affect my website. However, it has given me a definite URL, making it very convenient for me to publish the markdown content to other communities or forums. All I need to do is copy the markdown content, replace the external links of the images with regular ones, and add the URL section of my website. This way, my website can also serve as a blueprint

**Comment by slorber** [comment]
I'm not sure to understand sorry 😅, is your problem solved?

**Comment by yinsel** [comment]
> I'm not sure to understand sorry 😅, is your problem solved?

Solved, sorry, my English is not very good, I am using translation software.
