### ISSUE TITLE
The "paths[1]" argument must be of type string.

### ISSUE THREAD

**Issue by codenoid** [facebook/docusaurus#10199]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [x] I have tried the `npm run clear` or `yarn clear` command.
- [ ] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io.
- [ ] I have read the console error message carefully (if applicable).

### Description

error while running dev server

```
user@users-MacBook-Pro docs.lokal.so % npm run start

> docs-lokal-so@0.0.0 start
> docusaurus start

[INFO] Starting the development server...

[ERROR] TypeError [ERR_INVALID_ARG_TYPE]: The "paths[1]" argument must be of type string. Received undefined
    at validateString (node:internal/validators:162:11)
    at Object.resolve (node:path:1101:7)
    at Object.pluginContentBlog [as plugin] (/Users/user/Documents/Business/lokal.so/docs.lokal.so/node_modules/@docusaurus/plugin-content-blog/lib/index.js:51:37)
    at initializePlugin (/Users/user/Documents/Business/lokal.so/docs.lokal.so/node_modules/@docusaurus/core/lib/server/plugins/init.js:83:61)
    at async Promise.all (index 1)
    at async initPlugins (/Users/user/Documents/Business/lokal.so/docs.lokal.so/node_modules/@docusaurus/core/lib/server/plugins/init.js:91:21)
    at async /Users/user/Documents/Business/lokal.so/docs.lokal.so/node_modules/@docusaurus/core/lib/server/plugins/plugins.js:136:36
    at async loadSite (/Users/user/Documents/Business/lokal.so/docs.lokal.so/node_modules/@docusaurus/core/lib/server/site.js:135:45)
    at async createReloadableSite (/Users/user/Documents/Business/lokal.so/docs.lokal.so/node_modules/@docusaurus/core/lib/commands/start/utils.js:50:16)
    at async Command.start (/Users/user/Documents/Business/lokal.so/docs.lokal.so/node_modules/@docusaurus/core/lib/commands/start/start.js:22:28) {
  code: 'ERR_INVALID_ARG_TYPE'
}
```

### Steps to reproduce

1. install @latest docusaurus on 5 June 2024 (GMT+7)
2. init docusaurus project with javascript
3. run npm run start

### Expected behavior

dev server running

### Actual behavior

erroring

TypeError [ERR_INVALID_ARG_TYPE]: The "paths[1]" argument must be of type string. Received undefined

### Your environment

- Public source code:
- Public site URL:
- Docusaurus version used: 3.4.0
- Environment name and version (e.g. Chrome 89, Node.js 16.4):
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): Macbook Pro M1 Max

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by lominming** [comment]
Also hitting this error today

**Comment by rossbulat** [comment]
I am getting the same error upon installing a fresh install and for current projects.

```
[ERROR] TypeError [ERR_INVALID_ARG_TYPE]: The "paths[1]" argument must be of type string. Received undefined
    at validateString (node:internal/validators:162:11)
    at Object.resolve (node:path:1101:7)
```

**Comment by decaf-dev** [comment]
I am getting this error as well. I just created a fresh project using `bunx`

```shell
bunx create-docusaurus@latest my-website classic
bun run start
```

**Comment by sapshah** [comment]
Getting the same error as well

**Comment by Merpyzf** [comment]
Getting the same error as well.

**Comment by Vincent-Tam** [comment]
I'm getting same issue when I `npm run start` either on my current project or a fresh project. Had no issues a day ago.
- Docusaurus version used: 3.3.2/3.4.0
- Node version:18.17.0
```
[INFO] Starting the development server...

[ERROR] TypeError [ERR_INVALID_ARG_TYPE]: The "paths[1]" argument must be of type string. Received undefined
    at new NodeError (node:internal/errors:405:5)
    at validateString (node:internal/validators:162:11)
    at Object.resolve (node:path:1097:7)
    at Object.pluginContentBlog [as plugin] (/Users/266/Documents/github/docusaurus_test/node_modules/@docusaurus/plugin-content-blog/lib/index.js:51:37)
```

**Comment by shochdoerfer** [comment]
Same problem this morning ;(

**Comment by webprofusion-chrisc** [comment]
`yarn build` was working for me, I pushed to github for release and the build action failed, this suggests there is a dependency that's not pinned to a version so it was ok locally and not ok when built fresh. When I then cleared my local node modules and package locks etc it also fails.

The error occurs specifically in pluginContentBlog, but this may just be the first plugin the build tries to load - I don't use the blog plugin but I do use preset-classic.

Here is an example commit triggering the error (and repo that exhibits the problem): https://github.com/webprofusion/certify-docs/commit/2d7696f6cfbdf4213d8b7915d27459074e732c5a#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519

**Comment by EaveLuo** [comment]
It broke my heart! This is my first time using it, but this project doesn't work and I can't even start it.

**Comment by alankrantas** [comment]
The source seems to come from [here](https://github.com/facebook/docusaurus/blob/main/packages/docusaurus-plugin-content-blog/src/index.ts#L104):

```js
contentPath: path.resolve(siteDir, options.path),
```

Where `options` printed out as `{ id: 'default' }`.

(I am not using the blog but I still use `@docusaurus/plugin-content-blog` to set an id `blog` for it, in order to avoid issues for building the multiple docs instances I have. So the `path` is missing and the `id` is not correct either lol

The build actually works a day before - everything is up to `3.4.0` - but after I upgraded dependencies with `yarn upgrade` it broke.)

**Comment by FredericEspiau** [comment]
Hey this is the issue: https://github.com/unjs/jiti/releases/tag/v1.21.1

I guess there were some breaking changes

**Comment by homotechsual** [comment]
> This is a non-retro compatible update in Jiti v1.21.1, the tool we use to load plugin module graphs.
> 
> [unjs/jiti#237](https://github.com/unjs/jiti/issues/237)
> 
> Reverting to Jiti v1.21.0 fixes the problem.
> 
> Make sure you don't have the problematic version of Jiti in your lock file.
> 
> yarn users can use the following:
> 
> ```json
>   "resolutions": {
>     "jiti": "1.21.0"
>   },
> ```
> 
> I'd encourage you to downgrade Jiti rather than try to find another workaround because other things might be broken as well.
> 
> Note: if you don't have a lockfile, you should really have one to prevent such issues from randomly appearing in your project. This kind of problem should only happen when you upgrade site dependencies.

The template doesn't have a lock file so any new site is getting the incompatible version. We probably need to adjust the version constraint for this?

**Comment by homotechsual** [comment]
For `npm` users you can simply add the constraint in your own `package.json` file directly as `"jiti": "1.21.0"`. Yarn users should use the resolutions fix advised by @slorber

**Comment by pi0** [comment]
Hi all. [jiti@1.21.2](https://github.com/unjs/jiti/releases/tag/v1.21.2) was released as a hotfix for this issue. You can remove the resolution and upgrade your lock file to receive the fix 🤞🏼

**Comment by homotechsual** [comment]
Confirming - I no longer see the issue on fresh installs or existing installs without the constraint or explicit dependency.

**Comment by slorber** [comment]
Thanks @pi0 !
