### ISSUE TITLE
Insecure NPM packages Detected in Docusaurus Core as a Nested Dependency

### ISSUE THREAD

**Issue by niyatimandani** [facebook/docusaurus#10207]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

The following packages are required dependencies of @docusaurus/core and have been identified as insecure. npm recommends discontinuing their use, as no secure versions are available. Additionally, a Checkmarx scan has revealed open vulnerabilities in these package versions affecting the security reports at my firm.

1. shelljs: 0.8.5
2. inflight: 1.0.6
3. express: 4.19.2
4. serve-handler: 6.1.5

I kindly request the necessary actions to be taken to address and remediate this vulnerability to ensure the security and stability of the docusaurus framework. If any further info is required, please let me know.

### Steps to reproduce

Running the npm ls 'package-name' command in project directory results in the vulnerable npm version of the package:
─┬ @docusaurus/core@3.4.0
  └── shelljs@0.8.5

└─┬ @docusaurus/core@3.4.0
  └─┬ webpack-dev-server@4.15.2
    └── express@4.19.2

└─┬ @docusaurus/core@3.4.0
  └─┬ serve-handler@6.1.5

### Expected behavior

As there is no secure version available to these packages, I request docusaurus to replace these packages with secure alternatives.

### Actual behavior

Vulnerable packages/dependencies found in @docusaurus/core package:
1. shelljs: 0.8.5
2. inflight: 1.0.6
3. express: 4.19.2
4. serve-handler: 6.1.5

### Your environment

- Docusaurus version used: 3.4.0
- Environment name and version (e.g. Chrome 89, Node.js 16.4): Node.js 21
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): Ubuntu 22.04 LTS

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by Josh-Cena** [comment]
Have you looked at what vulnerabilities they have, exactly? Can you demonstrate an actual attack vector with these vulnerabilities?

All dependencies you listed are only used during development time. The only way to hack it is if someone can change your codebase. Please read https://overreacted.io/npm-audit-broken-by-design/

**Comment by riversdev-n09** [comment]
This is the vulnerability
https://security.snyk.io/vuln/SNYK-JS-INFLIGHT-6095116

**Comment by slorber** [comment]
TLDR: you can eventually DOS yourself by committing malicious files to your own GitHub repository so that it creates a memory leak in your site build.

Solution: don't do that and ignore the warning

---

```
=> Found "inflight@1.0.6"
info Reasons this module exists
   - "@docusaurus#utils#shelljs#glob" depends on it
   - Hoisted from "@docusaurus#utils#shelljs#glob#inflight"
```

FYI in the upcoming v3.8 I'm removing shelljs, so we also get rid of inflight.

Since there's no real attack vector, the only thing it will do is remove a warning, nothing else.
