### ISSUE TITLE
Support image resize

### ISSUE THREAD

**Issue by jaune162** [facebook/docusaurus#10202]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Description

Syntax like this:

```
![](/img/img.png){width=100} 
```

In this way, we can set the width attribute of img to 100

### Motivation

Custom picture size

### Self-service

- [ ] I'd be willing to contribute this feature to Docusaurus myself.

**Comment by Josh-Cena** [comment]
Thanks for the proposal. However, we aren't looking to add more non-standard Markdown syntaxes by default. You can either use JSX + CSS, or use a Markdown plugin such as https://www.npmjs.com/package/remark-directive. If you really feel strongly about it, I suggest you post on https://docusaurus.canny.io/ instead.

**Comment by waldyrious** [comment]
> If you really feel strongly about it, I suggest you post on https://docusaurus.canny.io/ instead.

For reference, there's already a thread about this feature request there: https://docusaurus.canny.io/feature-requests/p/markdown-image-resizing
