### ISSUE TITLE
Clicking "current version" at the version dropdown redirects to the landing page of docs, which is unintuitive

### ISSUE THREAD

**Issue by axmmisaka** [facebook/docusaurus#10206]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Description

Basically title.

If I go to https://docusaurus.io/docs/next/playground and click the "Canary" besides the "English" I will be redirected to https://docusaurus.io/docs/next. This might be a feature but it is unintuitive since clicking "Canary" **in** the dropdown will result in no behaviour.

### Motivation

https://github.com/lf-lang/lf-lang.github.io/issues/235#issue-2134318398

### Have you tried building it?

Not yet, but I will try to build it tomorrow and it feels trivial.

### Self-service

- [X] I'd be willing to contribute this feature to Docusaurus myself.

**Comment by slorber** [comment]
Oh I understand what you mean now. Will have to think about it but maybe we could use the same link for both the dropdown item and the dropdown button.

This might also be confusing if users click it and nothing happens, but we'll see...

**Comment by axmmisaka** [comment]
> This might also be confusing if users click it and nothing happens

My $0.02: since it displays the current version, clicking it should lead us to the same destination as if we clicked on the current version in the dropdown, i.e. no effect.
