### ISSUE TITLE
custom import of md file into the react component files

### ISSUE THREAD

**Issue by nage1234** [facebook/docusaurus#10221]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

Hey Team,
Good Day! I am using Docusaurus for our company doc site. We are facing issue in importing of md files into our react component.
Will give u a little context on this. We have say 100s of md files in our docs folder, but, we wanted to show on click of user choosing an item under the dropdown... We are pulling the data for the dropdown from API in the plugin and we set those data in globalData of docusaurus. So, on selecting each of the item, we want the corresponding md file to be shown.
i have used import(<path to md file>).then logic, works fine in dev environment.
But when we build the whole site, it is showing as warning, and dynamic imports are not considered during build time. 
Is there any way or workaround for this to get rid off warning.
Any help would be highly appreciated.. thanks Much.. 

### Steps to reproduce

Dynamic imports of md file (any file it can be) is not working during docusaurus build process

### Expected behavior

Docusaurus should allow to import dynamic files, whether it is img or md file itself into the react component. Works fine in Dev environment and causes warning while building

### Actual behavior

Dynamic imports cause warning During build process

### Your environment

- Public source code:
- Public site URL:
- Docusaurus version used: latest version.
- Environment name and version (e.g. Chrome 89, Node.js 16.4):
- Operating system and version (e.g. Ubuntu 20.04.2 LTS):

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by slorber** [comment]
Please provide a runnable https://docusaurus.new/stackblitz sandbox showing the problem.

We can't do anything with the text above, we need to see and be able to run code that fails

Closing until a repro is provided
