### ISSUE TITLE
ws affected by a DoS when handling a request with many HTTP headers

### ISSUE THREAD

**Issue by jy95** [facebook/docusaurus#10234]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

![image](https://github.com/facebook/docusaurus/assets/9306961/ba0c6a05-6f0f-4512-9e63-cf77cfa951c3)

### Reproducible demo

https://github.com/jy95/fhir-dosage-utils/tree/main/documentation

### Steps to reproduce

- npm install
- npm audit

### Expected behavior

No CSV

### Actual behavior

![image](https://github.com/facebook/docusaurus/assets/9306961/a036ee91-75c3-47eb-8d60-7ac501112000)

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by slorber** [comment]
As explained in many other issues already, we don't plan to fix theoretical DOS vulnerabilities reported by npm audit, unless you prove how the vulnerability can be harmful to Docusaurus users. 

A docusaurus site has no runtime and does not use WS. Only the dev server does. If you try to DOS yourself through that vulnerability, we don't plan to fix that sorry 😅 

The reasons are explained here:
https://overreacted.io/npm-audit-broken-by-design/
