### ISSUE TITLE
Unable to remove self referencing hreflang tags

### ISSUE THREAD

**Issue by GeorgeLoukovitis** [facebook/docusaurus#10249]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

Self referencing hreflang tags are considered to be bad practice in SEO. The docusaurus docs state that: 

> Docusaurus adds some metadata out-of-the-box. For example, if you have configured [i18n](https://docusaurus.io/docs/i18n/introduction), you will get a [hreflang](https://developers.google.com/search/docs/advanced/crawling/localized-versions) alternate link.
<img width="558" alt="Screenshot 2024-06-25 at 5 37 35 PM" src="https://github.com/facebook/docusaurus/assets/80828296/dce2cd11-2605-405e-b557-068f4f3a41a6">

But those tags do not get removed when the i18n configuration is deleted from the docusaurus config

### Steps to reproduce

1. Run npx create-docusaurus@latest my-website classic
2. Delete the i18n configuration from docusaurus.config.js
3. Run npm start to serve the docusaurus website
4. Inspect the HTML code from the developer tools to find the hreflang tag

### Expected behavior

The hreflang tag should have been removed

### Actual behavior

The hreflang tag has not been removed

### Your environment

- Public source code:
- Public site URL:
- Docusaurus version used:
- Environment name and version (e.g. Chrome 89, Node.js 16.4):
- Operating system and version (e.g. Ubuntu 20.04.2 LTS):

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by Josh-Cena** [comment]
This has been a recurring topic. Where do you find self-referencing hreflang being an anti-pattern? See https://github.com/facebook/docusaurus/issues/6011 for a previous discussion. If you want to provide information, backed by trustable sources, please reply in https://github.com/facebook/docusaurus/issues/6075 instead.
