### ISSUE TITLE
Throw better error for missing arguments on publish script

### ISSUE THREAD

**Issue by alexdriedger** [facebook/Docusaurus#1025]
## 🐛 Bug Report

I am trying to publish my site on Windows and `yarn run publish-gh-pages` and `npm run publish-gh-pages` fail in the same place

I have push access to the repository and can push from the command line. 

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## To Reproduce

1. Initialize a new repo on windows
2. Try to publish the repository 

## Expected behavior

The site would be published

## Actual Behavior

Received this error (similar error with yarn as well)

```
 create mode 100644 sitemap.xml
error: cannot spawn sh: No such file or directory
error: cannot spawn sh: No such file or directory
error: failed to execute prompt script (exit code 255)
fatal: could not read Password for 'https://alexdriedger@github.com': No error
Error: Git push failed
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ publish-gh-pages: `docusaurus-publish`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ publish-gh-pages script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

## Reproducible Demo

(Paste the link to an example repo, including a `siteConfig.js`, and exact instructions to reproduce the issue.)

https://github.com/alexdriedger/SlayTheSpireModding

```
dowload the repo (https://github.com/alexdriedger/SlayTheSpireModding) and unzip
create a new github repo
git init
git add -A
git push -u origin master
yarn run publish-gh-pages
```

**Comment by endiliey** [comment]
Check the docs. https://docusaurus.io/docs/en/publishing#docsNav

You need to set several environment variable as well.

Example:

```bash
GIT_USER=alexdriedger CURRENT_BRANCH=master USE_SSH=true yarn run publish-gh-pages
```

**Comment by endiliey** [comment]
Will be accepting PR for this so that the correct error can be thrown.

Related files are https://github.com/facebook/Docusaurus/blob/master/v1/lib/publish-gh-pages.js

**Comment by tanhauhau** [comment]
@endiliey I would like to work on this

**Comment by yangshun** [comment]
@tanhauhau it's yours!

I've added an "issue: claimed" label so that others will know not to start work on the issue. If you change your mind about the issue, no worries! Just let me know so that I can remove the label and free it up for someone else to claim.

I'll check in with you periodically so that we can keep the task updated with the progress.

**Comment by tanhauhau** [comment]
I couldn't replicate the exact error 
```
fatal: could not read Password for 'https://alexdriedger@github.com': No error
```
but I see it's not complaining correctly by not requiring me to set `GIT_USER`
