### ISSUE TITLE
Content moderation for your Canny board (feature requests)

### ISSUE THREAD

**Issue by o-l-a-v** [facebook/docusaurus#10253]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Motivation

Your feature request / Canny board is filled with spam, with no way of reporting it. Add some content moderation if possible.

Example:

* <https://docusaurus.io/feature-requests/p/comments-in-documents-or-blogs>

<img width="415" alt="image" src="https://github.com/facebook/docusaurus/assets/6450056/e082cc8c-60f8-4b3d-9068-4d0b740809db">

### Self-service

- [ ] I'd be willing to do some initial work on this proposal myself.

**Comment by Josh-Cena** [comment]
Thank you for the report! Canny does have the feature to auto-mark things as spam. I don't know if that causes them to be hidden by default or jut flags them for moderation. I've handled all the spams. In the future, please just ping me or one of the moderators on Discord or in GitHub discussions as issues are for the code.
