### ISSUE TITLE
MDX: for JSX {children} generates extra <p> tag

### ISSUE THREAD

**Issue by baur** [facebook/docusaurus#10260]
### Description

I have a custom component

```jsx
export default function FText({ children, fontNum, quran }) {
  return (
      <div className={styles[`Font${fontNum}`]} style={{ direction: "rtl", marginTop: "10px" }}>
        {children}
      </div>
  );
}
```

However, I'm encountering inconsistent behavior with how the children are rendered:

```jsx
<FText>text</FText>
```
result: 
```html
<div>text</div>
```

```jsx
<FText>
text
</FText>
```
result: 
```html
<div><p>text</p></div>
```

The second case breaks the CSS and, in some cases, raises an HTML warning: `<div> cannot appear as a descendant of <p>`.

### Expected behavior

I would like to consistently get `<div>text</div>` regardless of how the children are provided.

### Your environment

- Docusaurus version used: 3.4
- Environment name and version (e.g. Chrome 89, Node.js 16.4): Chrome, Node.js 20
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): Win10

**Comment by Josh-Cena** [comment]
Hi! Unfortunately we can't control how MDX is parsed and transformed. Please try in the [MDX playground](https://mdxjs.com/playground/):

```mdx
<FText>text</FText>

<FText>
text
</FText>
```

Compiled output:

```js
function _createMdxContent(props) {
  const _components = {
    p: "p",
    ...props.components
  }, {FText} = _components;
  if (!FText) _missingMdxReference("FText", true);
  return _jsxs(_Fragment, {
    children: [_jsx(FText, {
      children: "text"
    }), "\n", _jsx(FText, {
      children: _jsx(_components.p, {
        children: "text"
      })
    })]
  });
}
```
