### ISSUE TITLE
Sidebar generation will run `Globby` in the `node_modules` folder

### ISSUE THREAD

**Issue by rle-mino** [facebook/docusaurus#10276]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

Hi,

I'm using Docusaurus for a monorepo where every package can have markdown files.
When adding the plugin-content-docs to a specific package, the `start` command gets stuck:
```bash
[INFO] Starting the development server...
```
without more information.

I looked into the code and found that it was an issue during sidebar generation, the entire process gets blocked running this line of code: https://github.com/facebook/docusaurus/blob/main/packages/docusaurus-plugin-content-docs/src/sidebars/index.ts#L44

It looks like Globby runs on the `node_modules` folder.
When adding `ignore: ['**/node_modules']` in the options, Docusaurus starts perfectly!

Is there any reason to look for the `_category_.*` config files in the `node_modules` folder?

### Steps to reproduce

1. Have big dependencies in your package.json
2. Run `docusaurus start`

### Expected behavior

Should starts docusaurus

### Actual behavior

gets stuck on
```bash
[INFO] Starting the development server...
```

### Your environment

- Docusaurus version used: 3.4.0
- Environment name and version (e.g. Chrome 89, Node.js 16.4): Node.js 20.15.0
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): MacOS 14.2.1

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by Josh-Cena** [comment]
Do you have `node_modules` in your content path? I don't think that's supposed to happen. Otherwise by default you would also have any Markdown files there automatically becoming doc pages, or other bad things happening. Please give us an idea of how your project is set up, at least.

**Comment by rle-mino** [comment]
> Do you have `node_modules` in your content path? I don't think that's supposed to happen. Otherwise by default you would also have any Markdown files there automatically becoming doc pages, or other bad things happening. Please give us an idea of how your project is set up, at least.

Yes, I do have a `node_modules` folder in my content path. Here's the content folder's structure:
```
monorepo-project
- node_modules/
- package.json
- packages/
- - package-a/ # Content directory
- - - node_modules/ # <- Analysed by Globby (runs for more than 5 minutes)
- - - src/ # <- Has .md and .mdx files
- - - docs/ # <- has .md and .mdx files
- - - README.md # <- Should be in the documentation
- - - package.json
- - package-b/
- - package-c/
```

So I wan't to run plugin-content-docs for the entire `package-a` folder (to avoid complex sidebar configuration).

**Comment by slorber** [comment]
Can you create a realistic repro docusaurus.new of your monorepo setup? 

It would help to see the full picture, including config files, and be able to run it easily.

**Comment by Josh-Cena** [comment]
I wouldn't recommend you setting `contentPath` to be the entire `package-a`. That would _definitely_ include `node_modules`. Instead, you should have a dummy doc in your `docs` folder that contains this:

```md
import Readme from "../README.md";

<Readme />
```

This is what we do for our own website: https://github.com/facebook/docusaurus/blob/main/website/community/3-contributing.mdx

**Comment by snikch** [comment]
Hrm, we ran into this when moving from yarn to pnpm, since we suddenly had `node_modules` directories. We end up with an OOM.

I often add entire directories like `packages` to the docs, so that I effectively get a sidebar for all my packages README's. This feels like a relatively acceptable use case imo.

```
> docusaurus start -p 3003 --host 0.0.0.0

[INFO] Starting the development server...
(node:434514) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
[SUCCESS] Docusaurus website is running at: http://localhost:3003/

● Client █████████████████████████ setup (3%)  
 watch run


<--- Last few GCs --->

[434514:0xffffb8c50000]   467764 ms: Mark-Compact 3985.5 (4128.2) -> 3940.1 (4129.4) MB, pooled: 4 MB, 1254.02 / 0.00 ms  (average mu = 0.304, current mu = 0.393) allocation failure; scavenge might not succeed
[434514:0xffffb8c50000]   469329 ms: Mark-Compact 3955.9 (4129.4) -> 3941.1 (4117.9) MB, pooled: 16 MB, 1539.21 / 0.00 ms  (average mu = 0.178, current mu = 0.016) allocation failure; scavenge might not succeed


<--- JS stacktrace --->

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
----- Native stack trace -----

 1: 0xdffa44 node::OOMErrorHandler(char const*, v8::OOMDetails const&) [node]
 2: 0x119416c v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, v8::OOMDetails const&) [node]
 3: 0x119431c v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, v8::OOMDetails const&) [node]
 4: 0x13b87ac  [node]
 5: 0x13b87dc  [node]
 6: 0x13ceb90  [node]
 7: 0x13d13bc  [node]
 8: 0x1cd08a4  [node]
Aborted
```

**Comment by Josh-Cena** [comment]
Maybe try tweaking the `include`/`exclude` settings?
