### ISSUE TITLE
CSS priorities are different between development and production environments

### ISSUE THREAD

**Issue by ony3000** [facebook/docusaurus#10274]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

Hello!

I'm building a React component library that can be used by integrating with tailwindcss. I'm trying to use docusaurus as the documentation site for my library.

This library does not build and export CSS; instead, the class name of the tailwindcss syntax is embedded in the component's `className` property. Therefore, when the end user integrates the library exports into their tailwindcss configuration, the embedded class names will be built into css.

I'm trying to add a button as a demo component to my documentation site. This button has a default background color and a different background color when hovered or activated. Among these, the hover state style includes media queries that are applied when the screen is not a touch screen. Therefore, I need to be able to check the background color of the hover state and active state respectively in the desktop browser.

This works as intended in a development environment, but in a production environment the order of hover and active styles is reversed. So I can't check the background color of the active style.

### Reproducible demo

https://github.com/ony3000-lab/docusaurus-tailwind

### Steps to reproduce

1. Clone the above repository.
2. Run `npm install`.
3. Run `npm run start`.
4. Check that the hover and active styles are applied well to the blue button on the index page.

5. Stop the development server and run `npm run clear`.
6. Run `npm run build`.
7. Run `npm run serve`.
8. Again, check that the hover and active styles are applied properly to the blue button on the index page.

### Expected behavior

The UI must be the same in both development and production environments.

### Actual behavior

The UI is different in development and production environments.

- In a development environment:  (`blue-700` color applied)
  ![development_800x600](https://github.com/facebook/docusaurus/assets/8164191/36e030ae-a782-4c91-b2ba-50826954da9d)

- In a production environment:  (`blue-600` color applied)
  ![production_800x600](https://github.com/facebook/docusaurus/assets/8164191/72cbe657-bd1d-4b8c-90f1-3ed744fda927)

### Your environment

- Public source code: https://github.com/ony3000-lab/docusaurus-tailwind
- Public site URL:
- Docusaurus version used: 3.4.0
- Environment name and version: Chrome 126, Node.js 18.18.2
- Operating system and version: Ubuntu 20.04.6 LTS (WSL)

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by Josh-Cena** [comment]
What happens if you build with `--no-minify`, or `USE_SIMPLE_CSS_MINIFIER=true`?

**Comment by ony3000** [comment]
Both methods gave me the results I expected! Thanks for your help!
