### ISSUE TITLE
plugin-content-blog: add `rejectPostsWithoutTruncate` option

### ISSUE THREAD

**Issue by felipecrs** [facebook/docusaurus#10289]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Description

An option to make the `docusaurus build` fail if some blog post is missing _truncate_.

### Motivation

It's very often that we miss this during review and only realize it after the blog post is published.

It would be awesome and timesaving to allow to catch these issues during development time to avoid having them in production.

### API design

I believe the description is self-explanatory.

### Have you tried building it?

Not yet.

### Self-service

- [ ] I'd be willing to contribute this feature to Docusaurus myself.

**Comment by Josh-Cena** [comment]
A personal +1

**Comment by eliphazb** [comment]
I'm going to work on it :)

**Comment by felipecrs** [comment]
That's awesome. By the way feel free to tweak the option name or UX if you believe it can be improved.

**Comment by slorber** [comment]
What about a more flexible option like `onUntruncatedBlogPost: "throw" | "warn" | "ignore"` like we already have some other places? 

This also gives the opportunity to eventually provide a callback with some args to apply different per-blog-post rules in the future.

If you have a better name suggestion, please let us know right now.

No PR has been sent so @OzakIOne is probably going to work on it

**Comment by felipecrs** [comment]
I think it makes a lot of sense!

**Comment by felipecrs** [comment]
Thanks a lot @OzakIOne and @slorber!
