### ISSUE TITLE
Schema.org shows webpages as breadcrumbs

### ISSUE THREAD

**Issue by lizargall** [facebook/docusaurus#10298]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [ ] I have tried the `npm run clear` or `yarn clear` command.
- [ ] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io.
- [ ] I have read the console error message carefully (if applicable).

### Description

When I run various docusaurus sites through https://validator.schema.org/ the @type property is always breadcrumbs, not website. 

Issue repros on multiple version of docusaurus, including docusaurus.io  https://validator.schema.org/#url=https%3A%2F%2Fdocusaurus.io%2Fdocs%2Fnext%2Fseo

Hopefully this is just an accuracy issue, but I worry it might impact SEO as well. 

### Reproducible demo

https://validator.schema.org/

### Steps to reproduce

1. copy a url from a docusaurus site
2. run through https://validator.schema.org/
3. Observe issue

### Expected behavior

When I run other websites through the validator @type is website

### Actual behavior

@type is breadcrumbs

### Your environment

- Public source code:
- Public site URL:
- Docusaurus version used:
- Environment name and version (e.g. Chrome 89, Node.js 16.4):
- Operating system and version (e.g. Ubuntu 20.04.2 LTS):

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by Josh-Cena** [comment]
I'm not sure: what are you expecting to see? This validator shows that it picks up one set of structured data, which is the breadcrumblist. We don't have any other structured data by default.

MDN:

<img width="1440" alt="image" src="https://github.com/user-attachments/assets/f71bb3ef-b4d9-4fc7-9fc3-5bd2806054df">

react.dev:

<img width="1440" alt="image" src="https://github.com/user-attachments/assets/245bdaa5-9217-4367-a9f8-258536734f3a">

nextjs.org:

<img width="1440" alt="image" src="https://github.com/user-attachments/assets/d6d6d0c4-389b-4098-a5c7-74af059f9edf">

**Comment by Josh-Cena** [comment]
Closing; our current behavior is correct and intended.
