### ISSUE TITLE
No CSS on Published Site to GitHub Pages

### ISSUE THREAD

**Issue by alexdriedger** [facebook/Docusaurus#1029]
## 🐛 Bug Report

I tried initializing a project and publishing it to GitHub Pages and the page has no CSS.

![image](https://user-images.githubusercontent.com/21183154/46789563-97288580-ccf1-11e8-807a-cfe89bc5abc7.png)

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## To Reproduce

Node 8.11..4
Yarn 1.9.4
Docusaurus 1.4.0
OS: Windows 10

1. Create new GitHub repo
1. Clone repo
1. `npx docusaurus-init`
1. Rename docs and blog
1. `cd website && yarn start` to verify it is working locally
1. Edit `siteConfig.js`.
    - projectName: `ModdingSlayTheSpire`,
    - organizationName: `alexdriedger`,
1. Set `GIT_USER` to `alexdriedger` as environment variable on windows
1. `yarn run publish-gh-pages`

## Expected behavior

This to be hosted on github pages:

![image](https://user-images.githubusercontent.com/21183154/46790145-136f9880-ccf3-11e8-8702-a00ce1e2b771.png)

## Actual Behavior

This is what was hosted on github pages

![image](https://user-images.githubusercontent.com/21183154/46789563-97288580-ccf1-11e8-807a-cfe89bc5abc7.png)

## Reproducible Demo

https://github.com/alexdriedger/ModdingSlayTheSpire

**Comment by endiliey** [comment]
The `baseUrl` in siteConfig should be set as `ModdingSlayTheSpire`.

Otherwise it will try to request css file from alexdriedger.github.io instead of alexdriedger.github.io/ModdingSlayTheSpire

Feel free to reopen if it doesnt work

**Comment by alexdriedger** [comment]
`baseUrl` needed to be updated to `/ModdingSlayTheSpire/` AND `url` needed to be updated to `https://alexdriedger.github.io`. I'll submit a PR to update the docs to include those changes
