### ISSUE TITLE
Pagefind plugin for local search

### ISSUE THREAD

**Issue by tisonkun** [facebook/docusaurus#10290]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Motivation

Related docs:

* https://pagefind.app/docs/ui-usage/

Other frameworks' integration API:

* https://starlight.astro.build/guides/site-search/#_top

Issue in the other side:

* https://github.com/CloudCannon/pagefind/issues/447

### Self-service

- [ ] I'd be willing to do some initial work on this proposal myself.

**Comment by slorber** [comment]
Sorry but we don't plan to provide a first-party integration with every other local search lib that exists.

A Docusaurus plugin for pathfind can be created in userland by the community, we don't plan to create it ourselves.

At best, we'll eventually provide a single offline search plugin based on the library of our choice, but it's not a top priority for us considering third-party plugins already exist.

Related: https://github.com/facebook/docusaurus/issues/776
