### ISSUE TITLE
[Enhancement] Improved code blocks

### ISSUE THREAD

**Issue by hramos** [facebook/Docusaurus#103]
In this issue I want to collect some ideas for improving our fenced code block widget. 1.0 will launch without this.

- [ ] Language toggling
       A good example of this can be found in the [Parse docs](http://docs.parseplatform.org/ios/guide/#objects).  
- [ ] Sub-language toggles
        (e.g. ES6, ES5)
- [ ] Line highlighting
       Support ```javascript{3,5-7} syntax for highlighting (#105 @rickyvetter)

(There may be other ideas for features to implement in this issue https://github.com/facebook/react/issues/10991)

**Comment by Glavin001** [comment]
What would be a good syntax for code blocks with language toggling?

![image](https://user-images.githubusercontent.com/1885333/36867298-1d940180-1d6b-11e8-8774-1640f45a03de.png)

I am very interesting in trying to make a Pull Request for this. Before I get started, I'd appreciate some collaboration on the design :).

**Comment by ForbesLindesay** [comment]
I like the idea of just having multiple code blocks, one after another, with no text between them:

<img width="174" alt="screen shot 2018-03-02 at 18 10 12" src="https://user-images.githubusercontent.com/1260646/36914367-fe0e5a88-1e44-11e8-8414-c179e71b47ec.png">

**Comment by jonathaningram** [comment]
I actually hacked together a plugin called "file tabs" to do this. I just wanted to use docusaurus to quickly prototype something, so the plugin was meant to be quick and dirty. Source is here: https://github.com/govau/platforms-alpha/blob/master/lib/shared/fileTabs.js

Install into your site like this: https://github.com/govau/platforms-alpha/blob/master/tell/website/siteConfig.js#L52

And here's how you use it in your .md file:

````md
```filetabs
file=website/blog/2018-06-13-docusaurus-file-tabs-plugin/example.cs lang=csharp label=C#
file=website/blog/2018-06-13-docusaurus-file-tabs-plugin/example.go lang=go label=Go
file=website/blog/2018-06-13-docusaurus-file-tabs-plugin/example.inline parser=md label=Java
file=website/blog/2018-06-13-docusaurus-file-tabs-plugin/example.js lang=js label=Node.js
file=website/blog/2018-06-13-docusaurus-file-tabs-plugin/example.php lang=php label=PHP
file=website/blog/2018-06-13-docusaurus-file-tabs-plugin/example.py lang=python label=Python
file=website/blog/2018-06-13-docusaurus-file-tabs-plugin/example.rb lang=ruby label=Ruby
```
````

And how it ends up looking:

![image](https://user-images.githubusercontent.com/626664/41572017-39edd26c-73b9-11e8-8c4d-7074b928b333.png)

![image](https://user-images.githubusercontent.com/626664/41572026-4125ff8c-73b9-11e8-9b43-feaafb360318.png)

**Comment by yangshun** [comment]
@jonathaningram This looks amazing! I also like that the code is stored outside of the Markdown file. We'll look into including it! 😄

**Comment by fiennyangeln** [comment]
Hi I'm interested in this issue. Is it an appropriate bug to work on?

**Comment by JoelMarcey** [comment]
@fiennyangeln - I think this is quite appropriate. Language Toggling would be great and a feature that people really have asked for. And anything else you feel could improve the code blocks too.

I will mark this issue as claimed by you 😄
