### ISSUE TITLE
Navbar dropdown can't render correctly

### ISSUE THREAD

**Issue by zhangjianrencai** [facebook/docusaurus#10303]
### Have you read the Contributing Guidelines on issues?

- [x] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

I install the latest version of Docusaurus with the following steps: 

- npx create-docusaurus@latest my-website classic --typescript

- copy intro.md under docs then rename in2.nd
![image](https://github.com/user-attachments/assets/7f1df8a6-ce51-4ae9-ae07-9256dc839664)

- modify **docusaurus.config.ts**  like this 
```
navbar: {
      title: 'My Site',
      logo: {
        alt: 'My Site Logo',
        src: 'img/logo.svg',
      },
      items: [
        {
          label: 'Module',
          type: 'dropdown',
          position: 'right',
          items: [
            {
              label: 'Community Hub',
              type: 'doc',
              docId: 'intro',
            },
            {
              label: 'Community Hub2',
              type: 'doc',
              docId: 'in2',
            },
          ],
        },
      ],
    },
```

- execute npm start. see the result like this. all the dropdown item is actived
![image](https://github.com/user-attachments/assets/cd898328-cfa2-4a0d-ad75-4f79fd954a9e)

### Steps to reproduce

I install the latest version of Docusaurus with the following steps: 

- npx create-docusaurus@latest my-website classic --typescript

- copy intro.md under docs then rename in2.nd

- modify **docusaurus.config.ts**  like this 
```
navbar: {
      title: 'My Site',
      logo: {
        alt: 'My Site Logo',
        src: 'img/logo.svg',
      },
      items: [
        {
          label: 'Module',
          type: 'dropdown',
          position: 'right',
          items: [
            {
              label: 'Community Hub',
              type: 'doc',
              docId: 'intro',
            },
            {
              label: 'Community Hub2',
              type: 'doc',
              docId: 'in2',
            },
          ],
        },
      ],
    },
```

- execute npm start. see the result like this. all the dropdown item is actived
![image](https://github.com/user-attachments/assets/cd898328-cfa2-4a0d-ad75-4f79fd954a9e)

### Expected behavior

only one item is selected. just like this 
![image](https://github.com/user-attachments/assets/0ae99056-035e-4b41-960b-c0ff915b4996)

### Actual behavior

all the item are selected 

### Your environment

- Public source code:
- Public site URL:
- Docusaurus version used:
- Environment name and version (e.g. Chrome 89, Node.js 16.4):
- Operating system and version (e.g. Ubuntu 20.04.2 LTS):

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by slorber** [comment]
This behavior is documented here: https://docusaurus.io/docs/next/api/themes/configuration#navbar-doc-link

> It will get the class navbar__link--active as long as you browse a doc of the same sidebar.

You show a React Native website screenshot, which actually leverages that behavior:

https://github.com/facebook/react-native-website/blob/main/website/docusaurus.config.js#L247

```ts
          {
            label: 'Development',
            type: 'dropdown',
            position: 'right',
            items: [
              {
                label: 'Guides',
                type: 'doc',
                docId: 'getting-started',
              },
              {
                label: 'Components',
                type: 'doc',
                docId: 'components-and-apis',
              },
              {
                label: 'APIs',
                type: 'doc',
                docId: 'accessibilityinfo',
              },
              {
                label: 'Architecture',
                type: 'doc',
                docId: 'architecture-overview',
                docsPluginId: 'architecture',
              },
            ],
          },
```

For example, you'll notice that the "API" dropdown navbar item remains highlighted for all those URLs:
- https://reactnative.dev/docs/accessibilityinfo
- https://reactnative.dev/docs/alert
- https://reactnative.dev/docs/animated

If you don't want this behavior, you can use a regular `{to: "/docs/intro"}` navbar link item instead.
