### ISSUE TITLE
Hash navigation breaks in 3.4.0 with some plugins

### ISSUE THREAD

**Issue by razzeee** [facebook/docusaurus#10307]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [ ] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io.
- [ ] I have read the console error message carefully (if applicable).

### Description

We're using https://github.com/gabrielcsapo/docusaurus-plugin-search-local and updating to 3.4.0 changes the links the search produces. 

They end up in a duplicated format like `https://docs.flathub.org/docs/for-app-authors/linter/docs/for-app-authors/linter#linter-errors` instead of `https://docs.flathub.org/docs/for-app-authors/linter#linter-errors`  

See
https://github.com/gabrielcsapo/docusaurus-plugin-search-local/issues/82

I couldn't spot a hint at a behaviour change in the changelog, but I might have overlooked it or this is a regression.

The new hashnav changes are opt in so far it seems?

### Reproducible demo

https://github.com/flathub-infra/documentation/pull/339

### Steps to reproduce

1. run `yarn`
2. `yarn build`
3. `yarn serve`
4. Go to the page
5. Search for `linter error`
6. Click the first result

### Expected behavior

It should route you to the correct path and scroll down to the hash navigation

### Actual behavior

You get a 404

### Your environment

- Public source code: https://github.com/flathub-infra/documentation/pull/339
- Public site URL: https://docs.flathub.org/
- Docusaurus version used: 3.4.0
- Environment name and version (e.g. Chrome 89, Node.js 16.4): Seems unrelated, can repro in multiple envs
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): Seems unrelated, can repro in multiple envs

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by slorber** [comment]
See my answer here: https://github.com/gabrielcsapo/docusaurus-plugin-search-local/issues/82#issuecomment-2236539091

Although we have our responsibility, Docusaurus core works fine and this is a third-party plugin bug.
