### ISSUE TITLE
Bolg post date

### ISSUE THREAD

**Issue by Broad-CanDou** [facebook/docusaurus#10326]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Description

![image](https://github.com/user-attachments/assets/dc9d7895-15cf-4475-bbca-90d2ecd43822)
I set up files in this way, but the local environment has no effect

### Self-service

- [ ] I'd be willing to address this documentation request myself.

**Comment by OzakIOne** [comment]
Please give us a minimal reproduction of your setup, without this we can't help you

**Comment by Broad-CanDou** [comment]
> Please give us a minimal reproduction of your setup, without this we can't help you
> 
> https://docusaurus.io/docs/playground

![image](https://github.com/user-attachments/assets/1881972c-5ed4-42f4-9126-e80372d99988)
![image](https://github.com/user-attachments/assets/309debb0-eb5b-4ae9-ba44-47f793c1bd3a)

**Comment by OzakIOne** [comment]
https://stackblitz.com/github/facebook/docusaurus/tree/starter?file=README.md

Please reproduce your error on this online editor and give us more information about you're error
