### ISSUE TITLE
[Feature] Does docusaurus support sub-menu

### ISSUE THREAD

**Issue by longdafeng** [facebook/docusaurus#10351]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Description

I want use docusaurus support multiple documents. 

I need to category these documents, I wish docusaurus support sub-menu. 

there are other items in the navigation bar, I don't want to put the document category name in the navigation bar. 

### Motivation

null

### Self-service

- [ ] I'd be willing to contribute this feature to Docusaurus myself.

**Comment by slorber** [comment]
It's not clear what you mean by sub-menu

We support "multiple documents", and "categories" with multiple nesting levels.

We don't support nested navbar dropdowns (tracked in https://github.com/facebook/docusaurus/issues/5938)
