### ISSUE TITLE
Admonitions & Details do not work when importing partial mdx into a React page

### ISSUE THREAD

**Issue by lukemartin** [facebook/docusaurus#10377]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

When importing partial mdx into a React page, admonitions are unstyled, and Details throw the following error:

```
Expected component `Details` to be defined
```

When viewing the same mdx page standalone, everything works as expected.

Simplified example:

```js 
// index.tsx
import MarkdownPageContent from "./markdown-page.mdx";

export default function Home(): JSX.Element {
  return (
    <Layout>
       ...
        <MarkdownPageContent />
       ...
    </Layout>
  );
}
```

```mdx
# markdown-page.mdx
---
title: Markdown page example
---

# Markdown page example

You don't need React to write simple standalone pages.

:::warning

A Quality Strategy is fundamental for achieving and maintaining high standards of product or service quality, which in turn drives customer satisfaction, business efficiency, compliance, competitive advantage, and overall organisational success.

:::
```

**Viewing /:**

<img width="528" alt="image" src="https://github.com/user-attachments/assets/321c7ca2-172a-4b0e-b8e6-21d9febcd40f">

**Viewing /markdown-page:**

<img width="529" alt="image" src="https://github.com/user-attachments/assets/026a2866-e4a2-414b-9849-2003d5fd222b">

Full reproduction available here: https://codesandbox.io/p/devbox/zealous-snowflake-vx4nwl

### Reproducible demo

https://codesandbox.io/p/devbox/zealous-snowflake-vx4nwl

### Steps to reproduce

1. Visit https://codesandbox.io/p/devbox/zealous-snowflake-vx4nwl
2. View `/` route. You will see that the admonition is unstyled
3. Click `View standalone markdown page` (or go to `/markdown-page`) and see that the admonition is styled
4. Additionally, uncomment the `<details>` usage in `markdown-page.mdx` to see the error `TypeError: Cannot convert object to primitive value`

### Expected behavior

I would expect that admonitions, details, and other components behave the same wether viewing a mdx page directly, or as an import inside another mdx/React page

### Actual behavior

Admonitions are unstyled.

Details throw the following error:

```
TypeError: Cannot convert object to primitive value
```

### Your environment

- Public source code: https://codesandbox.io/p/devbox/zealous-snowflake-vx4nwl
- Public site URL: https://codesandbox.io/p/devbox/zealous-snowflake-vx4nwl
- Docusaurus version used: 3.4.0
- Environment name and version (e.g. Chrome 89, Node.js 16.4): 
- Operating system and version (e.g. Ubuntu 20.04.2 LTS):

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by OzakIOne** [comment]
https://codesandbox.io/p/devbox/weathered-glade-pqrccg?file=%2Fsrc%2Fpages%2Findex.tsx%3A30%2C14

You need to use the component Details and Adminition in the mdx page

**Comment by Josh-Cena** [comment]
This is a limitation of how our MDX architecture works. Details are provided as [MDX components](https://docusaurus.io/docs/markdown-features/react#mdx-component-scope), and admonitions require both a Remark plugin and the MDX components provider to work. Unfortunately these Markdown infrastructure are registered independently by each content plugin, so if your MDX is not already managed by one of the content plugins, it would lack these infrastructure and therefore show up unprocessed. It would work, I think, if you move this Markdown file to your docs folder.

**Comment by lukemartin** [comment]
Thanks for the clarification.

I might make a PR to add a caveat explanation to the docs incase anyone else has this issue.

**Comment by slorber** [comment]
@Josh-Cena is right. In this case you can solve it by wrapping the partial in `<MDXComponent>` as our doc explains already.

![CleanShot 2024-08-08 at 12 35 56](https://github.com/user-attachments/assets/bb4ea0bd-1ebf-41f8-8198-388995db4462)

I don't think it's worth documenting this more for now.

---

Regarding remark plugins, in this case it's not a problem because the content is in `/pages` which by default supports admonitions. And our "fallback mdx loader" handling content at the repo root (for example `website/README.md` also has admonitions enabled by default.


But yes we should have a way to configure remark plugins globally. I'll try to solve this as part of https://github.com/facebook/docusaurus/issues/5999

**Comment by lukemartin** [comment]
@slorber The note in the docs you referenced is useful. My only suggestion is somehow linking this explanation to the [Importing Markdown](https://docusaurus.io/docs/markdown-features/react#importing-markdown) section as it's important there.

**Comment by slorber** [comment]
👍 wy not adding an extra warning there
