### ISSUE TITLE
Fail to upgrade to docusaurus3.5 with theme-search-algolia

### ISSUE THREAD

**Issue by jovezhong** [facebook/docusaurus#10383]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [ ] I have tried the `npm run clear` or `yarn clear` command.
- [ ] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io.
- [ ] I have read the console error message carefully (if applicable).

### Description

Maybe I am not alone. The 3.5 release is out and a PR is created to upgrade to the new version (from 3.4 to 3.5) but the build failed with error message

[ERROR] Client bundle compiled with errors therefore further build is impossible.
Module not found: Error: Can't resolve '@docusaurus/core/src/client/exports/useDocusaurusContext' in '/Users/jove/Dev/timeplus-io/docs/node_modules/@docusaurus/theme-search-algolia/lib/client'

You may check more details at https://github.com/timeplus-io/docs/pull/206

This can be reproduced on CI or local build.

I also tried to remove the `"@docusaurus/theme-search-algolia": "^3.5.0",` dependency but same error. Please check. Thanks.

### Steps to reproduce

Check https://github.com/timeplus-io/docs/pull/206

### Expected behavior

Upgrade from 3.4 to 3.5 smoothly

### Actual behavior

`yarn run build` failed with error for theme-search-algolia

### Your environment

- Public source code: https://github.com/timeplus-io/docs
- Public site URL: https://docs.timeplus.com
- Docusaurus version used: 3.4->3.5
- Environment name and version (e.g. Chrome 89, Node.js 16.4): Node 21.1.0
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): Mac

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by Josh-Cena** [comment]
Thanks, should be fixed by https://github.com/facebook/docusaurus/pull/10382

**Comment by slorber** [comment]
Fixed in v3.5.1 release
