### ISSUE TITLE
How to upgrade for curl get method

### ISSUE THREAD

**Issue by hexxamillion** [facebook/docusaurus#10408]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Description

The upgrade instructions seem to be limited to docker and NPX but I used the method below. How do I upgrade for the simple curl download method?

Method I use: 
```
curl http://get.nocodb.com/linux-x64 -o nocodb -L \
      && chmod +x nocodb \
      && ./nocodb
```

### Self-service

- [ ] I'd be willing to address this documentation request myself.

**Comment by Josh-Cena** [comment]
This seems unrelated to [Docusaurus](https://docusaurus.io/).
