### ISSUE TITLE
Add name of user underneath logo on users page

### ISSUE THREAD

**Issue by JoelMarcey** [facebook/Docusaurus#1040]
## 🚀 Feature

Show name of project in addition to logo on showcase page.

## Have you read the [Contributing Guidelines on issues](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## Motivation

Better user experience when reading our docs.

## Pitch

Right now we have a users' page for those projects who use Docusaurus and have asked to be or agreed to be showcased. But we only show logos. Let's show the name of the project too for better clarity.

**Comment by yangshun** [comment]
Would be good to add this feature to the generated starter project as well 🤔

**Comment by mptap** [comment]
@JoelMarcey Have raised PR for this: https://github.com/facebook/Docusaurus/pull/1043. Suggestions welcome!
