### ISSUE TITLE
Upgrade from 3.4.0 to 3.5.2 can't import { useDoc } from '@docusaurus/theme-common/internal';

### ISSUE THREAD

**Issue by zhangjianrencai** [facebook/docusaurus#10404]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

Upgrade from @docusaurus/core and @docusaurus/preset-classic  3.4.0 to 3.5.2 can't import { useDoc } from '@docusaurus/theme-common/internal';

### Steps to reproduce

Upgrade from @docusaurus/core and @docusaurus/preset-classic  3.4.0 to 3.5.2 can't import { useDoc } from '@docusaurus/theme-common/internal';

### Expected behavior

Upgrade from @docusaurus/core and @docusaurus/preset-classic  3.4.0 to 3.5.2 can't import { useDoc } from '@docusaurus/theme-common/internal';

### Actual behavior

Upgrade from @docusaurus/core and @docusaurus/preset-classic  3.4.0 to 3.5.2 can't import { useDoc } from '@docusaurus/theme-common/internal';

### Your environment

node version 18.18.0

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by OzakIOne** [comment]
Can you create a minimal repro using docusaurus.new and give us more informations about the problem so we can take a look at it ?

**Comment by zhangjianrencai** [comment]
@OzakIOne Sorry for the my missing.  I using docusaurus.new to create a new project. it seems can import { useDoc } from '@docusaurus/theme-common/internal'. so close the issue. Thank you.

**Comment by LaurenceJJones** [comment]
I am also hitting the same issue and the above was already set, seems this commit https://github.com/facebook/docusaurus/commit/026a317fc4300e6ae1817404519d229d2ca684a4 moved the `useDoc` helper to a separate package?

**Comment by slorber** [comment]
Keepo in mind that those `/internal` APIs are... internal. 

To iterate faster on Docusaurus, we reserve the right to do breaking changes on minor version releases of those internal implementation details, as documented in our release process:
https://docusaurus.io/community/release-process#public-api-surface

Now we understand that these changes can be annoying for Docusaurus users when they swizzle unsafe components, and we try to minimize those changes whenever possible.


Note that these changes are only import changes, we just moved the code to another package and you can just update the imports to fix your swizzled components.

This is mentioned in our v3.5 blog post: https://docusaurus.io/blog/releases/3.5#other-changes

![CleanShot 2024-08-15 at 11 51 13](https://github.com/user-attachments/assets/26601504-3dd2-4f9f-9621-db526da0e8bb)

**Comment by LaurenceJJones** [comment]
> Keepo in mind that those `/internal` APIs are... internal.
> 
> To iterate faster on Docusaurus, we reserve the right to do breaking changes on minor version releases of those internal implementation details, as documented in our release process: https://docusaurus.io/community/release-process#public-api-surface
> 
> Now we understand that these changes can be annoying for Docusaurus users when they swizzle unsafe components, and we try to minimize those changes whenever possible.
> 
> Note that these changes are only import changes, we just moved the code to another package and you can just update the imports to fix your swizzled components.
> 
> This is mentioned in our v3.5 blog post: https://docusaurus.io/blog/releases/3.5#other-changes and affect both docs/blog-related theme-common/internal APIs:
> 
> ```diff
> -import {useDoc} from '@docusaurus/theme-common/internal';
> +import {useDoc} from '@docusaurus/plugin-content-docs/client';
> ```
> 
> ```diff
> -import {useBlogPost} from '@docusaurus/theme-common/internal';
> +import {useBlogPost} from '@docusaurus/plugin-content-blog/client';
> ```
> 
> ![CleanShot 2024-08-15 at 11 51 13](https://private-user-images.githubusercontent.com/749374/358186247-26601504-3dd2-4f9f-9621-db526da0e8bb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM3MTY0MjUsIm5iZiI6MTcyMzcxNjEyNSwicGF0aCI6Ii83NDkzNzQvMzU4MTg2MjQ3LTI2NjAxNTA0LTNkZDItNGY5Zi05NjIxLWRiNTI2ZGEwZThiYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxNVQxMDAyMDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jZjFiOTBiMTI2N2NkYjdiNDg2YzJkYzU2ZDA3ZDBjOTZjYTE0Y2EyNGI5M2IyZTc2NTUyNTRjYTI2NDFjZWExJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.hPSH-lfF38832s9E5soNIqr858K5PX2pC-u7G6exzx4)

I agree, I missed the blog post and like you said swizzling means you will keep the component when its swizzled. 👍🏻 thank you for responding and showing the post I will read them now to see if anything else was missed by me.
