### ISSUE TITLE
Docs has wrong npm start command

### ISSUE THREAD

**Issue by arndom** [facebook/docusaurus#10411]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

Issue: The docs says the following; which doesn't work

![image](https://github.com/user-attachments/assets/bac90809-f37b-45b8-aa09-520a0834748c)

I believe it should be `npm start`

### Steps to reproduce

1. Follow the steps to create a new project
2. The issue is in the second step of the image
![image](https://github.com/user-attachments/assets/a9044aea-bc96-4c5f-a891-c866076e8462)

### Expected behavior

The app should start

### Actual behavior

![image](https://github.com/user-attachments/assets/4015685c-b642-4595-8263-f99116c96a6b)

### Your environment

- Public source code: NA
- Public site URL: NA
- Docusaurus version used: "@docusaurus/core": "3.5.2"
- Environment name and version (e.g. Chrome 89, Node.js 16.4): Node v20.9.0, Chrome 127
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): Window 11

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by Josh-Cena** [comment]
It says `npx docusaurus start`, not `npx docusaurus-start`. `npx docusaurus start` works for every package manager so we don't have to have different versions for npm, Yarn, and pnpm.

**Comment by arndom** [comment]
😓  my bad
