### ISSUE TITLE
npm2yarn converts command incorrectly for PNPM

### ISSUE THREAD

**Issue by AndreaPontrandolfo** [facebook/docusaurus#10428]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

i'm using the `@docusaurus/remark-plugin-npm2yarn`.
However even for very simple cases, it fails to correctly convert NPM commands into PNPM commands.

### Steps to reproduce

write this in any mdx file (remove the //)

```
//```bash npm2yarn
//TIMING=1 npm run eslint
//```
```

### Expected behavior

PNPM output should be `TIMING=1 pnpm eslint`

### Actual behavior

PNPM output is `TIMING=1 pnpm run eslint`

### Your environment

- Public source code: https://github.com/AndreaPontrandolfo/sheriff/blob/master/apps/docs-website/docs/performance-considerations.mdx
- Public site URL: https://www.eslint-config-sheriff.dev/docs/performance-considerations#rules-performance-benchmarking
- Docusaurus version used: 3.4.0
- Environment name and version (e.g. Chrome 89, Node.js 16.4): Node 22
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): Macos/Linux

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by slorber** [comment]
This conversion is done by a third-party dependency.

The bug should be reported here: https://github.com/nebrelbug/npm-to-yarn
