### ISSUE TITLE
Regarding plugin @docusaurus/plugin-client-redirects can't set redirection settings for other languages

### ISSUE THREAD

**Issue by Fei927** [facebook/docusaurus#10469]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

Hi, I have set up page redirects for other languages while using this plugin with the following configuration:      
    {
            to: '/zh/docs/kelly/v100/intro',
            from: '/zh/docs/kelly/v100/',
          },
``npm run build`` will report error, ``/zh/docs/kelly/v100/intro`` does not exist.
Is there any way to fix this?

[ERROR] Error: Unable to build website for locale en.
    at tryToBuildLocale (/home/f/user/node_modules/@docusaurus/core/lib/commands/build.js:54:19)
    at async /home/f/user/node_modules/@docusaurus/core/lib/commands/build.js:65:9
    at async mapAsyncSequential (/home/f/user/node_modules/@docusaurus/utils/lib/jsUtils.js:21:24)
    at async Command.build (/home/f/user/node_modules/@docusaurus/core/lib/commands/build.js:63:5) {
  [cause]: Error: You are trying to create client-side redirections to invalid paths.

  These paths are redirected to but do not exist:
  - /zh/docs/kelly/v100/intro
  - /zh/docs/kelly/v100/

### Steps to reproduce

1、Add the following to the configuration file docusaurus.config.ts.
    {
            to: '/zh/docs/kelly/v100/intro',
            from: '/zh/docs/kelly/v100/',
          },
2、npm run build

### Expected behavior

My expected result is that links in other languages can be redirected.

### Actual behavior

In fact it is not realized, because the other language routes don't seem to exist?

### Your environment

- Public source code:
- Public site URL:
- Docusaurus version used:
- Environment name and version (e.g. Chrome 89, Node.js 16.4):
- Operating system and version (e.g. Ubuntu 20.04.2 LTS):

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by slorber** [comment]
The paths your redirect from/to are always "local" to your site and should not include the locale path segment `/zh/`


If you build your site in 2 locales `en` + `zh` the 2 following redirects should be created:
- `/docs/kelly/v100/` -> `/docs/kelly/v100/intro`
- `/zh/docs/kelly/v100/` -> `/zh/docs/kelly/v100/intro`

You don't need to add 2 entries for the 2 redirects: Docusaurus will loop over your list of locales and create one redirect for each locale already.

**Comment by Fei927** [comment]
> The paths your redirect from/to are always "local" to your site and should not include the locale path segment `/zh/`
> 
> If you build your site in 2 locales `en` + `zh` the 2 following redirects should be created:
> 
> * `/docs/kelly/v100/` -> `/docs/kelly/v100/intro`
> * `/zh/docs/kelly/v100/` -> `/zh/docs/kelly/v100/intro`
> 
> You don't need to add 2 entries for the 2 redirects: Docusaurus will loop over your list of locales and create one redirect for each locale already.

I see, what you mean is that as soon as the redirection is created for the default language, then for other languages docusaurus will automatically search and apply the redirection settings.
Thank you!
