### ISSUE TITLE
`float`ing images overlap background of boxes (code boxes, admonitions, etc.)

### ISSUE THREAD

**Issue by yolpsoftware** [facebook/docusaurus#10466]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [ ] I have read the console error message carefully (if applicable).

### Description

First of all, thanks for Docusaurus. I tried it out for documentation, but maybe I will use it for many other things as well.

I know that `float: left` is not widely regarded as the latest cutting-edge technology in CSS and web design.

However, for our use case we need to place images (or videos) side-by-side with documentation text, and it would be nice if that could happen in a floating way.

Please have a look at the reproducible demo. When you have started the preview, go to "Tutorial", "Tutorial - Basics" and then "Create a document". There, I have inserted an image, and applied the `float: left` CSS property.

As you can see, the background of the following code box overlaps the image's frame. The same is true for admonitions, and possibly other widgets.

### Reproducible demo

[Code Sandbox](https://codesandbox.io/p/devbox/funny-glade-yt3gc8?workspaceId=110ebf2a-5c0f-415b-a82d-8f07cf5d811e&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clzmtoaoc00083b6m95su4x47%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clzmtoaob00033b6mw8405tar%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clzmtoaob00053b6mh2cwdwbq%2522%257D%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clzmtoaob00073b6mc3olhy7s%2522%257D%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clzmtoaob00033b6mw8405tar%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clzmtoaob00023b6m661959zu%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522cm0k0ifa100023b6m5x4dt2ih%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A6%252C%2522startColumn%2522%253A1%252C%2522endLineNumber%2522%253A6%252C%2522endColumn%2522%253A1%257D%255D%252C%2522filepath%2522%253A%2522%252Fdocs%252Ftutorial-basics%252Fcreate-a-document.md%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clzmtoaob00033b6mw8405tar%2522%252C%2522activeTabId%2522%253A%2522cm0k0ifa100023b6m5x4dt2ih%2522%257D%252C%2522clzmtoaob00073b6mc3olhy7s%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clzmtoaob00063b6mvmv5uypu%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A3000%257D%255D%252C%2522id%2522%253A%2522clzmtoaob00073b6mc3olhy7s%2522%252C%2522activeTabId%2522%253A%2522clzmtoaob00063b6mvmv5uypu%2522%257D%252C%2522clzmtoaob00053b6mh2cwdwbq%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clzmtoaob00043b6mwar33ci1%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%257D%255D%252C%2522id%2522%253A%2522clzmtoaob00053b6mh2cwdwbq%2522%252C%2522activeTabId%2522%253A%2522clzmtoaob00043b6mwar33ci1%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

### Steps to reproduce

In the demo:

go to Tutorial --> Tutorial Basics --> Create a Document.

Generally:

1. Add an image to a Docusaurus markdown page (e.g. docs). It also works with other things than images.
2. Add the CSS `float:left` to that image.
3. Make sure the image does not occupy the whole width.
4. Add an admonition or a code box after the image, such that the image gets rendered side-by-side with the box.

==> The background of the box is overlapped by the image.

### Expected behavior

The background of the box should not be overlapped by the image. It should be defined around the contents of the box.

### Actual behavior

The background of the box is overlapped by the image.

### Your environment

- Docusaurus version used: 3.5.2
- Environment name and version (e.g. Chrome 89, Node.js 16.4): Node 18.0, Chrome 128.
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): macOS Sonoma 14.6.1

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by slorber** [comment]
Yes, you can break Docusaurus theme by adding your own CSS. If you do, you are responsible 😅 

We don't do anything fancy here, it's just how HTML/CSS works with `float: left`. 

Proof:

https://stackblitz.com/edit/vitejs-vite-3zx3xp?file=src%2FApp.jsx,src%2Fmain.jsx&terminal=dev


![CleanShot 2024-09-02 at 13 53 00](https://github.com/user-attachments/assets/2a2f6c1e-668e-4b11-a963-58eb7620f8b3)

**Comment by yolpsoftware** [comment]
@slorber I see, and I understand your point.

Is there any way to render images side-by-side with normal Docusaurus content, by using the Docusaurus theme?

**Comment by slorber** [comment]
@yolpsoftware you can use CSS. But teaching you CSS is out of the scope of this project and I'm not an expert either.

Using `overflow: hidden` fixes it. Or you can use something else than float. 

![CleanShot 2024-09-02 at 16 21 08](https://github.com/user-attachments/assets/7e3caad8-5e43-4a9e-8067-cc9d9f6281c4)

**Comment by slorber** [comment]
Our theme doesn't provide that out of the box. If you want that kind of layout you can implement it yourself with MDX, JSX and CSS.

We don't provide a tutorial to help you implement all the layouts that could exist.

---

We don't add overflow by default because that's not how CSS works by default and doing so might produce side effects for users that use different layouts than yours. If you want to add CSS to create a custom layout, you are responsible for doing it correctly.

Remember it's not just those 2 elements, as my demo above shows, `<p>` also overflows, it's just that you don't see it because it doesn't have a background.

**Comment by yolpsoftware** [comment]
Right, got it.

Maybe it would make sense to add a section about "Common Layouting Pitfalls" to [Styling and Layout](https://docusaurus.io/docs/styling-layout). Seems to me, this would greatly enhance the flexibility of the Docusaurus theme.

Thanks again.

**Comment by slorber** [comment]
@yolpsoftware this is a pitfall for any dev using HTML and CSS, not just Docusaurus users.

Feel free to create a blog and document this for others. 

We don't plan to document the thousands of existing pitfalls that exist for web devs doing HTML, JS and CSS.

Similarly we don't plan to teach flexbox or CSS grid on that page. If you want to use CSS with Docusaurus to customize it, there are better resources to learn CSS than our styling page.

**Comment by yolpsoftware** [comment]
Yeah, I was more thinking of "common pitfalls with common Docusaurus use-cases", but as I'm only the second one to have this issue, this might not even be such a common use-case.
