### ISSUE TITLE
Unicode in Navlinks broken on NodeJS 22

### ISSUE THREAD

**Issue by Curve** [facebook/docusaurus#10465]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io.
- [ ] I have read the console error message carefully (if applicable).

### Description

Unicode symbols in NavLinks are broken on latest NodeJS (22.7.0):
![image](https://github.com/user-attachments/assets/ae580775-481d-44e0-8d22-2133d474208e)

Downgrading NodeJS to 18 fixes the issue.

### Reproducible demo

n/a

### Steps to reproduce

1. Use NodeJS 22
2. Run `pnpm run start` in docusaurus v3 project
3. Observe broken NavLinks

### Expected behavior

Unicode renders correctly in NavLinks.  

### Actual behavior

Unicode characters are replaced with the unicode replacement character in navlinks or rather in the generated `styles.css` file.

Interestingly, this only applies to the navlinks and breadcrumbs afaict. Unicode in the actual markdown content (of `.mdx` pages) works properly.

### Your environment

- Public source code: https://github.com/saucer/saucer.github.io/tree/v3
- Public site URL: https://saucer.github.io
- Docusaurus version used: 3.5.2
- Environment name and version (e.g. Chrome 89, Node.js 16.4): NodeJS 22.7.0, Firefox 129
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): Arch Linux

### Self-service

- [x] I'd be willing to fix this bug myself.

**Comment by davidmehren** [comment]
Looks like this bug in Node 22.7.0: https://github.com/nodejs/node/issues/54543

**Comment by Curve** [comment]
> Looks like this bug in Node 22.7.0: https://github.com/nodejs/node/issues/54543

Landed in 22.8.0

**Comment by slorber** [comment]
Thanks, let us know if you still have problems under Node 22.8
