### ISSUE TITLE
Adding `@babel/preset-react` to docusaurus does not enable "Support for the experimental syntax 'jsx'"

### ISSUE THREAD

**Issue by Zenahr** [facebook/docusaurus#10477]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

I'm getting this error:

```js
 ParseError: Support for the experimental syntax 'jsx' isn't currently enabled (62:23):

Add @babel/preset-react (https://github.com/babel/babel/tree/main/packages/babel-preset-react) to the 'presets' section of your Babel config to enable transformation.
If you want to leave it as-is, add @babel/plugin-syntax-jsx (https://github.com/babel/babel/tree/main/packages/babel-plugin-syntax-jsx) to the 'plugins' section to enable parsing.
```

when I try to execute a custom remark plugin that contains the following code:

```js
import {visit} from 'unist-util-visit';
const plugin = (options) => {
  const transformer = async (ast) => {
    visit(ast, 'inlineCode', (node) => {
      if (mapping[node.value] !== undefined) {
        node.type = 'html';
        node.value = (<div></div>);
        console.log(node)
...
```

My babel.config.js:
```js
module.exports = {
  presets: [
    require.resolve("@docusaurus/core/lib/babel/preset"),
    require.resolve("@babel/preset-env"),
    require.resolve("@babel/preset-react"),
  ],
};
```

Although I've followed the instructions found in the log messages (as of my current understanding), it didn't make the code run.

### Steps to reproduce

1. Create a remark plugin as above
2. Add the plugin to Docusaurus as described in the docs
3. Run `yarn clear`
4. Run `yarn dev`
5. Observe the behavior

### Expected behavior

Code compiling and running.

### Actual behavior

Code not compiling and not running.

### Your environment

- Docusaurus version used: 3.5.2

### Self-service

- [X] I'd be willing to fix this bug myself.

**Comment by slorber** [comment]
We don't transpile MDX components with Babel to build faster, because the output of MDX is already "runnable" by Node and browsers. 

This is a tradeoff: you can't use fancy new features in MDX files, but this should be fine most of the time and you can extract your code to another component.

That being said, this limitation doesn't seem super related to your case here. 

I can't help because I don't have a minimal repro. I don't see the full error message, the input source, the full remark plugin code, and can't investigate.

Please provide a minimal repro. Also, run your plugin in a standalone MDX playground to see what's the compiled output, and how it differs from what you expected to get. 

---

Most likely it's a bug in your remark plugin, and you shouldn't use an element of type "html"

```jsx
node.type = 'html';
node.value = (<div></div>);
```

That looks highlightly suspicious to me. Please explain what you expect this to do. And please run this outside of Docusaurus first to see if it does what you expect.

**Comment by Zenahr** [comment]
@slorber The use case I'm trying to realize here is this: dynamic conversion of inline-code elements (text within single backticks in markdown) into html markup -> the final html is supposed to output a popup element showing a description and more info on the inline-code.

The reason I'm trying to make this work automatically is to avoid cluttering the markdown with unnecessary component calls (we're talking about ~100 individual components I'd otherwise have to create and also call within markdown.). Hence the need to replace the inline-code elements with html markup. the html node type is documented here: https://github.com/syntax-tree/mdast?tab=readme-ov-file#html and seems to be the most suitable node type for me to use from my understanding.

Can you make use of this explanation? I'll more than happily provide a minimal repro as soon as I can to further explain myself.

**Comment by slorber** [comment]
Remember that MDX compiles to JSX. `html` is a valid MDAST / HAST type, but I'm not sure a type like `html` is supported by the MDX. A HTML string might not be well-formed and might not even be convertible to JSX.

What you probably want as output is `<div dangerouslySetInnerHTML={{__html: "<div>My HTML markup</div>"}}></div>`

And for that the AST is:

```json
    {
      "type": "mdxJsxFlowElement",
      "name": "div",
      "attributes": [
        {
          "type": "mdxJsxAttribute",
          "name": "dangerouslySetInnerHTML",
          "value": {
            "type": "mdxJsxAttributeValueExpression",
            "value": "{__html: \"<div>My HTML markup</div>\"}",
            "data": {
              "estree": {
                "type": "Program",
                "body": [
                  {
                    "type": "ExpressionStatement",
                    "expression": {
                      "type": "ObjectExpression",
                      "properties": [
                        {
                          "type": "Property",
                          "method": false,
                          "shorthand": false,
                          "computed": false,
                          "key": {
                            "type": "Identifier",
                            "name": "__html"
                          },
                          "value": {
                            "type": "Literal",
                            "value": "<div>My HTML markup</div>",
                            "raw": "\"<div>My HTML markup</div>\""
                          },
                          "kind": "init"
                        }
                      ]
                    }
                  }
                ],
                "sourceType": "module",
                "comments": []
              }
            }
          },
        }
      ]
    }
```

This is out of scope of Docusaurus, and more of a MDX help so I'm closing.

The best to troubleshoot this would be to run the compilation using your remark code outside of Docusaurus, until you get the JSX output you want. You should write unit tests.
