### ISSUE TITLE
Option to Alphabetically Sort Items in the Sidebar Menu

### ISSUE THREAD

**Issue by jacklaurencegaray** [facebook/docusaurus#10506]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Description

It would be handy to have a built-in option to alphabetically sort items in a sidebar menu. Maybe a field in `_category.json`.

```js
{
  "label": "Reference Guides",
  "position": 5,
  "link": {
    "type": "generated-index"
  },
  "order": "alphabetical"
}
```

### Has this been requested on Canny?

https://docusaurus.io/feature-requests/p/option-to-sort-sidebar-links-alphabetically-in-categoryjson

### Motivation

In some documentations, especially when order is not important, it is easier to retrieve sections in the sidebar when they are ordered alphabetically.

### Self-service

- [x] I'd be willing to contribute this feature to Docusaurus myself.

**Comment by jacklaurencegaray** [comment]
Closed this ticket. I just noticed how it is the default behavior for the docs' filenames.

**Comment by slorber** [comment]
Related to https://github.com/facebook/docusaurus/issues/10403

You can plug your own sorting behavior if you want, the one we provide by default might not fit all use cases but it's a good enough order in most cases.
