### ISSUE TITLE
Make auto-generated multiple sidebars exclusive by default

### ISSUE THREAD

**Issue by cseas** [facebook/docusaurus#10500]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [ ] I have read the console error message carefully (if applicable).

### Description

I'm trying to use the "Multiple Sidebars" feature since I have two categories in my documentation.
The documentation doesn't mention anything about this feature not working properly with auto-generated sidebars:
https://docusaurus.io/docs/sidebar/multiple-sidebars

When multiple autogenerated sidebars are defined, it should be default behaviour that the directories of the new sidebars should be excluded from the main first sidebar generated from the `docs` directory.

<img width="540" alt="Screenshot 2024-09-13 at 5 33 14 PM" src="https://github.com/user-attachments/assets/a0e5a567-6f83-493e-b174-c15347b64419">

It could be argued that the same behaviour could be achieved with an `exclude` option as discussed in https://github.com/facebook/docusaurus/issues/5689#issuecomment-1106746731 but the way the documentation is defined, the impression is that multiple sidebars will be exclusive by default. If not, then it should be documented that explicitly defining the structure of `docs` is necessary to omit certain directories generated as a separate sidebar as done in Docusaurus website as well.

### Reproducible demo

https://codesandbox.io/p/sandbox/young-wood-5k56n7

### Steps to reproduce

Define a new sidebar:

```tsx
// sidebars.ts

const sidebars: SidebarsConfig = {
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  api: [{type: 'autogenerated', dirName: 'api'}]
};
```

And then in docusaurus.config.ts, add the following to navbar.items:

```ts
        {
          type: 'docSidebar',
          position: 'left',
          sidebarId: 'api',
          label: 'API',
        },
```

This does generate a new link on the header with "API" label and a sidebar as expected. The problem is that the same sidebar still appears nested inside of the main "Docs" sidebar.

### Expected behavior

The `api` directory should get excluded from the main Docs sidebar as there's a separate sidebar defined for it.

### Actual behavior

The api directory is both generated as a separate sidebar and appears nested inside of the Docs sidebar.

### Your environment

- Public source code: https://codesandbox.io/p/sandbox/young-wood-5k56n7
- Public site URL: https://codesandbox.io/p/sandbox/young-wood-5k56n7
- Docusaurus version used: 3.5.2
- Environment name and version (e.g. Chrome 89, Node.js 16.4): Node v20.15.0, pnpm 9.10.0
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): MacOS 14.6.1

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by slorber** [comment]
There is no concept of "mutually exclusive"

Docusaurus lets you assemble "autogenerated sidebar slices" in various ways and doesn't do any filtering magic. If you add a sidebar slice to one sidebar, it doesn't make it disappear from another sidebar. You can add the same sidebar slice to 2 sidebars and expect the items to appear in both places.

If you want mutually exclusive autogenerated sidebars, then you'd rather create a `docs/tutorial` and `docs/api` folder. If you consider `.` to generate your tutorial sidebar, there's no reason to put the `api` folder there because you don't want to appear in your tutorial sidebar. You can solve this problem by using a dedicated folder for each sidebar, instead of having one sidebar inside another.
