### ISSUE TITLE
Hover Effect on Get Started and Try Demo Buttons

### ISSUE THREAD

**Issue by dhruvishah122** [facebook/docusaurus#10546]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Motivation

The Responsiveness and UI of the website can be better if we can add Hover effect on Try Demo and Get Started button

### Self-service

- [X] I'd be willing to do some initial work on this proposal myself.

**Comment by slorber** [comment]
Our website has hover effects on these buttons already.

I agree it could be better but it's coming from our theme classic design system Infima and changing the theme design system could be annoying for all users. 

https://infima.dev/



If you want to improve our website landing page, please open a PR and we'll consider it.
