### ISSUE TITLE
Render checkboxes

### ISSUE THREAD

**Issue by theactualmariluski** [facebook/docusaurus#10565]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Motivation

Checkboxes do not render, which isn't ideal as they are usefull

### Self-service

- [ ] I'd be willing to do some initial work on this proposal myself.

**Comment by slorber** [comment]
Please take time to open bug reports others can understand. This issue is not actionable.
