### ISSUE TITLE
HTML comments hidden in texts but displayed in DocCard

### ISSUE THREAD

**Issue by tomasdahlqvist** [facebook/docusaurus#10589]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [x] I have tried the `npm run clear` or `yarn clear` command.
- [x] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [x] I have read the console error message carefully (if applicable).

### Description

Mutli-line HTML comments are not removed from previews. The preview then contains the first line of the comment instead of the actual content. 

### Reproducible demo

https://stackblitz.com/github/facebook/docusaurus/tree/main/examples/classic-typescript?file=docs%2Ftutorial-basics%2Fcreate-a-document.md

### Steps to reproduce

1. Change the start of the tutorial page create-a-document to
---
sidebar_position: 2
---
# Create a Document

Documents are ...
2. View the card layout from the page "Tutorial - Basics"
3. The description in the card is "<!-- black"

### Expected behavior

The html comment should be ignored even if it is multi-line.

### Actual behavior

![image](https://github.com/user-attachments/assets/62dae72a-18ad-4800-8fc5-05653b46a179)

### Your environment

- Public source code:
- Public site URL:
- Docusaurus version used:
- Environment name and version (e.g. Chrome 89, Node.js 16.4):
- Operating system and version (e.g. Ubuntu 20.04.2 LTS):

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by 5AIPAVAN** [comment]
I want to work on this @tomasdahlqvist , can you please assign this to me :-)

**Comment by TRIPLE-ADE** [comment]
Can you assign this to me

**Comment by slorber** [comment]
Note HTML comments are not valid MDX syntax, and Docusaurus v3 interprets `.md` docs as MDX by default (unless you use `format: md`)

We do add back support for HTML comments as a workaround to ease the adoption of Docusaurus v3, but it's preferable to use either `format: md` or to avoid using HTML comments in the first place. You'd better choose between CommonMark or MDX, not a mix of both. In the future we might remove support for HTML comments in MDX docs.

That being said, we add back support for HTML comments through a lib: https://github.com/leebyron/remark-comment

There was a bug in multiline comments that I tried to fix in this PR: https://github.com/leebyron/remark-comment/pull/3
This official repo is not maintained anymore and the PR hasn't been merged so I published a fork that Docusaurus uses: https://www.npmjs.com/package/@slorber/remark-comment

I'm not an expert in extending Markdown syntax and it's probable that my attempt has unsupported edge cases.

**Comment by slorber** [comment]
Oh damn, I misunderstood the problem.

Indeed the card will display the comment, but not only. This is because the card description has to be a pure string and we do a best effort to extract and serialize that string to display it in that card. 

Our docs tell you the behavior:

https://docusaurus.io/docs/api/plugins/@docusaurus/plugin-content-docs

> The first line of Markdown content

This is not only used in the card, but also on SEO description metadata and eventually other places.

Unfortunately we won't really be able to solve this. The description has to be a pure string. We provide a default but if the default is not good enough to you, you should rather provide an explicit `description` front matter instead.

**Comment by tomasdahlqvist** [comment]
I found it strange that one line comments work but not multiline. Also in for example https://github.com/facebook/docusaurus/issues/9691 the  and /* */ syntax are both viable. 
Shouldn't the standard be that either no comments work or all comments work?
