### ISSUE TITLE
Import error

### ISSUE THREAD

**Issue by lixiufei** [facebook/docusaurus#10602]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Description

FALSE:
![image](https://github.com/user-attachments/assets/4a8f4069-cb92-4bc4-9e4b-75b9c69a31ff)

TRUE：
$ npm install @turf/bbox
import bbox from "@turf/bbox";
const result = bbox(...);

### Self-service

- [ ] I'd be willing to address this documentation request myself.

**Comment by Josh-Cena** [comment]
This has nothing to do with Docusaurus.
