### ISSUE TITLE
Page not being generating 

### ISSUE THREAD

**Issue by ABHISHANMG** [facebook/docusaurus#10604]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [ ] I have read the console error message carefully (if applicable).

### Description

I used "npm i docusaurus-plugin-openapi-docs" to generate API references in my docusaurus project I even after using valid yaml file it's not being generating with proper config

`plugins: [
    [
      'docusaurus-plugin-openapi-docs',
      {
        id: 'on-demand',
        docsPluginId: 'classic',
        config: {
          on_demand: {
            specPath: 'static/public/live-stream.yaml',
            outputDir: 'docs/on-demand',
            baseUrl: '/on-demand',
            sidebarOptions: {
              groupPathsBy: 'tag',
            },
          } satisfies OpenApiPlugin.Options,
        }
      },
    ],`
    
`presets: [
    [
      'classic',
      {
        docs: {
          sidebarPath: './sidebars.ts',
          routeBasePath: 'guides',
          sidebarCollapsible: false,
          sidebarCollapsed: false,
          docItemComponent: "@theme/ApiItem",
        },
        blog: {
          showReadingTime: true,
          feedOptions: {
            type: ['rss', 'atom'],
            xslt: true,
          },

          onInlineTags: 'warn',
          onInlineAuthors: 'warn',
          onUntruncatedBlogPosts: 'warn',
        },
        theme: {
          customCss: './src/css/custom.css',
        },
      } satisfies Preset.Options,
    ],
  ],
]`

 themes: [
    'docusaurus-theme-openapi-docs',
  ],
    
<img width="377" alt="Screenshot 2024-10-23 at 4 53 00 PM" src="https://github.com/user-attachments/assets/40976060-7373-4d75-a30d-9d99fdf860e0">

I'm not getting any type of errors in my console so please help me out on this

### Steps to reproduce

I used "npm i docusaurus-plugin-openapi-docs" to generate API references in my docusaurus project I even after using valid yaml file it's not being generating with proper config

`plugins: [
    [
      'docusaurus-plugin-openapi-docs',
      {
        id: 'on-demand',
        docsPluginId: 'classic',
        config: {
          on_demand: {
            specPath: 'static/public/live-stream.yaml',
            outputDir: 'docs/on-demand',
            baseUrl: '/on-demand',
            sidebarOptions: {
              groupPathsBy: 'tag',
            },
          } satisfies OpenApiPlugin.Options,
        }
      },
    ],`
    
`presets: [
    [
      'classic',
      {
        docs: {
          sidebarPath: './sidebars.ts',
          routeBasePath: 'guides',
          sidebarCollapsible: false,
          sidebarCollapsed: false,
          docItemComponent: "@theme/ApiItem",
        },
        blog: {
          showReadingTime: true,
          feedOptions: {
            type: ['rss', 'atom'],
            xslt: true,
          },

          onInlineTags: 'warn',
          onInlineAuthors: 'warn',
          onUntruncatedBlogPosts: 'warn',
        },
        theme: {
          customCss: './src/css/custom.css',
        },
      } satisfies Preset.Options,
    ],
  ],
]`

 themes: [
    'docusaurus-theme-openapi-docs',
  ],
    
<img width="377" alt="Screenshot 2024-10-23 at 4 53 00 PM" src="https://github.com/user-attachments/assets/40976060-7373-4d75-a30d-9d99fdf860e0">

I'm not getting any type of errors in my console so please help me out on this

### Expected behavior

Suppose to generated on specific outdir but it's not

### Actual behavior

Suppose to generated on specific outdir but it's not

### Your environment

- Public source code:
- Public site URL: I didn't publish yet
- Docusaurus version used: latest one
- Environment name and version (e.g. Chrome 89, Node.js 16.4): v20.17.0
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): mac

### Self-service

- [X] I'd be willing to fix this bug myself.

**Comment by slorber** [comment]
We don't maintain the open API plugin, and also only handle bugs that are reported properly, including a repro
