### ISSUE TITLE
color mode is not working on nav bar custom component during first load

### ISSUE THREAD

**Issue by hemarina** [facebook/docusaurus#10619]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

Custom button on nav bar doesn't use the right color mode on first loading. After clicking on light/dark mode button on nav bar, it shows the dark mode button.

### Steps to reproduce

1. Add a custom button following: https://github.com/facebook/docusaurus/issues/7227
2. Check the custom button on nav bar. 

### Expected behavior

Show dark mode on custom image button when first loading the page. 

### Actual behavior

Custom button on nav bar doesn't use the right color mode when first loading the pages. I confirm that color mode is under "dark".

It shows light mode like this: 
<img width="161" alt="image" src="https://github.com/user-attachments/assets/24bb8422-e755-4d9c-acb9-c5ce970bdb0b">

### Your environment

- Public source code: N/A
- Public site URL: N/A
- Docusaurus version used: 3.5.2
- Environment name and version (e.g. Chrome 89, Node.js 16.4): Microsoft Edge for Business Version 130.0.2849.52
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): Windows 11

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by slorber** [comment]
Sharing the custom button code is not optional 🤷

Most likely this is a duplicate of other well known issues related to React hydration and use of useColorMode() 

Please do a search
