### ISSUE TITLE
`format: md` front matter doesn't work

### ISSUE THREAD

**Issue by doraeric** [facebook/docusaurus#10628]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io.
- [ ] I have read the console error message carefully (if applicable).

### Description

The docs say that adding `format: md` front matter makes the doc to be CommonMark format, but it doesn't work.
After looking into the code, it should be
```md
---
mdx:
  format: md
---
```
It reads the `mdx` in front matter first
https://github.com/facebook/docusaurus/blob/a4fa4c27f1321617054d69ff930c765edcb5da7b/packages/docusaurus-mdx-loader/src/utils.ts#L99-L105
https://github.com/facebook/docusaurus/blob/a4fa4c27f1321617054d69ff930c765edcb5da7b/packages/docusaurus-mdx-loader/src/processor.ts#L266-L285

But the docs say it's `format` in front matter.
https://github.com/facebook/docusaurus/blob/a4fa4c27f1321617054d69ff930c765edcb5da7b/website/docs/guides/markdown-features/markdown-features-react.mdx?plain=1#L251
https://github.com/facebook/docusaurus/blob/a4fa4c27f1321617054d69ff930c765edcb5da7b/website/docs/guides/markdown-features/markdown-features-intro.mdx?plain=1#L44

Should it be fixed in the code or in the docs?

### Steps to reproduce

1. add `format: md` front matter in `.mdx` file
2. nothing happened

### Expected behavior

Doc changes to CommonMark syntax.

### Actual behavior

Doc stay with JSX syntax

### Your environment

- Public source code:
- Public site URL:
- Docusaurus version used: v3
- Environment name and version (e.g. Chrome 89, Node.js 16.4):
- Operating system and version (e.g. Ubuntu 20.04.2 LTS):

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by slorber** [comment]
Damn, yes you are right 😅 

> Should it be fixed in the code or in the docs?

Hmmm, I don't know. I'd like to have `format:` instead of `mdx.format` but at the same time it's possible that we add extra options under the `mdx` namespace. I think we should just fix the docs.
