### ISSUE TITLE
Blog features

### ISSUE THREAD

**Issue by hellfiremaga** [facebook/docusaurus#10622]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [ ] I have tried the `npm run clear` or `yarn clear` command.
- [ ] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

Hello everyone

I'm trying the new blog features. My author image is local, I have a baseURL for my website and even with the issue  #9577 something is still missing : if page=true, the image of the page is still missing

I also noticed that the socials:newsletter is mandatory another website. Is there any socials that could be local ? I would like to link a local page for the author.

Finally, should be a pull request (I can move it if it's better for lisibility), it could be great to re-use author tag. I'm thinking about doing an archive of mail exchanges, so something that looks like a blog but with multiple articles in one page.

### Steps to reproduce

create a new docusaurus
add page=true to the authors page
change the image to a local one
run
go to the author page

### Expected behavior

same one with the image working

### Actual behavior

image is not working

### Your environment

- Public source code: unrelevent
- Public site URL: unrelevent
- Docusaurus version used: 3.5.2
- Environment name and version (e.g. Chrome 89, Node.js 16.4): Brave up to date
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): Windows 11 up to date

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by slorber** [comment]
I'm sorry but I can't consider this a valid bug report.

If you think we have 3 bugs, please open 3 separate issues, each of them including a repro and respecting our bug reporting template.

I'm not able to take any action for this kind of issue. Please be precise, show code, and give concrete examples.
