### ISSUE TITLE
When using @docusaurus/faster: "should strip suffix" error 

### ISSUE THREAD

**Issue by Yonglin666** [facebook/docusaurus#10663]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [x] I have tried the `npm run clear` or `yarn clear` command.
- [ ] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io.
- [x] I have read the console error message carefully (if applicable).

### Description

While building my Docusaurus project, Rspack encountered a panic during the chunk ID sealing process.

### Error Message
sealing chunk ids
Panic occurred at runtime.
Message: should strip suffix
Location: crates\rspack_core\src\utils\compile_boolean_matcher.rs:255

### Steps to reproduce

1. Set up a Docusaurus project using @docusaurus/faster
2. Run the `npm start` command
3. Rspack crashes during the chunk ID sealing phase

### Expected behavior

The build should complete successfully without any panics.

### Actual behavior

sealing chunk ids
Panic occurred at runtime.
Message: should strip suffix
Location: crates\rspack_core\src\utils\compile_boolean_matcher.rs:255

### Your environment

- Public source code:
- Public site URL:
- Docusaurus version used:
- Environment name and version (e.g. Chrome 89, Node.js 16.4):
- Operating system and version (e.g. Ubuntu 20.04.2 LTS):

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by slorber** [comment]
Duplicate https://github.com/facebook/docusaurus/issues/10646
