### ISSUE TITLE
Files in `exclude` are still processed by the build system, leading to hangs

### ISSUE THREAD

**Issue by LegNeato** [facebook/docusaurus#10708]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

I have [a site](https://github.com/Rust-GPU/rust-gpu.github.io) that uses the classic preset. There is some [Rust code in one of the blog directories](https://github.com/Rust-GPU/rust-gpu.github.io/tree/main/blog/2024-11-21-optimizing-matrix-mul/code) (`blog/2024-11-21-optimizing-matrix-mul/code`). I explicitly exclude the Rust code and subdirectories from the blog config:

<details>
Snippet:

```ts
presets: [
    [
      "classic",
      {
        blog: {
          exclude: ["*/code/**"],
```

[Full config is on GitHub](https://github.com/Rust-GPU/rust-gpu.github.io/blob/main/docusaurus.config.ts)

</details>

Rust puts the `target/` output directory with intermediate and compiled artifacts in the top-level (that is, `blog/2024-11-21-optimizing-matrix-mul/code/target`). After doing a couple of Rust builds (`cargo build`) and benchmark runs (`cargo bench`) the target directory is full of many files, some large.

With a full `target/` directory, docusaurus stops building the website successfully. Both `yarn start` and `yarn build` make some progress and then stall out with node using 100% CPU. I have waited for 20 mins with no forward progress (usually builds are < 10s). Deleting the `blog/2024-11-21-optimizing-matrix-mul/code/target` directory's many files enables the build to make forward progress and succeed.

Note when I run `yarn start` and then do a Rust build in the supposedly excluded directory, I can see the client hot-reloading / compiling being kicked off as well.

I know the `exclude` entry in the config is being respected, as previously I had to put a truncate marker in `README.md` files in the Rust code (I have missing markers set to throw). After I put the exclude entry in the settings, markdown files in code were correctly not being treated as blog posts and I could remove the truncate markers.

So, it appears that something in the build process is globbing or reading/processing each file and _then_ applying the excludes.

### Reproducible demo

https://github.com/Rust-GPU/rust-gpu.github.io

### Steps to reproduce

1. Exclude files in some path in the blog plugin
2. Run `yarn start`
3. touch a file in the excude path
4. See that a build is triggered

### Expected behavior

Build completes.

### Actual behavior

Build is triggered. If there are tons of files, node goes to 100% CPU usage during `yarn build`, no progress on the build. Deleting the files in "exclude" directory allows the build to make progress and finish.

### Your environment

- Public source code: https://github.com/Rust-GPU/rust-gpu.github.io
- Public site URL: rust-gpu.github.io
- Docusaurus version used: tried 3.5 and 3.6.2 (with and without build fast, with and without all the sub build fast options turned on)
- Environment name and version (e.g. Chrome 89, Node.js 16.4): Node v23.2.0
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): macoS sequoia

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by slorber** [comment]
Can you provide a full repro branch where I can reliably reproduce the problem?

If cargo generates files, then please commit them.

**Comment by slorber** [comment]
Note, what I suspect is that your exclude overrides the default one which is:

```
  include: ['**/*.{md,mdx}'],
  exclude: [
	  '**/_*.{js,jsx,ts,tsx,md,mdx}',
	  '**/_*/**',
	  '**/*.test.{js,jsx,ts,tsx}',
	  '**/__tests__/**',
  ]
```

Maybe try appending to that exclude list. And also try with `**` instead of `*`:

```
  exclude: [
	  '**/_*.{js,jsx,ts,tsx,md,mdx}',
	  '**/_*/**',
	  '**/*.test.{js,jsx,ts,tsx}',
	  '**/__tests__/**',
	  '**/code/**',
  ]
```

**Comment by LegNeato** [comment]
I can't commit the files as they are large. Better steps:

1. Checkout https://github.com/Rust-GPU/rust-gpu.github.io
2. Run `yarn start`
3. cd `blog/2024-11-21-optimizing-matrix-mul/code/`
4. `cargo build --release`
5. See that a docusaurus rebuild keeps getting triggered every time cargo writes a file to `blog/2024-11-21-optimizing-matrix-mul/code/target`.

I'll try the other configs, but again I know the blog code at least is using that exclude.

**Comment by LegNeato** [comment]
I updated the repro, using `touch` is sufficient

**Comment by LegNeato** [comment]
It does not only affect HMR, it was affecting `yarn build` as well. HMR is just easier to see as `yarn build` doesn't error out unless there are a ton of files (or maybe big files? not sure, cargo shoves a bunch of junk in there)

**Comment by LegNeato** [comment]
I have not modified the include option, there is no `include` key set in my config.

**Comment by slorber** [comment]
Thanks, I'll take a look

Note that the problems you see with `yarn start` and `yarn build` are likely different. With the current repro I can only troubleshoot that HMR problem. 

If you have another problem with `yarn build`, I'd need another distinct repro for it.

**Comment by LegNeato** [comment]
Ok, sounds good! If I have time this week I'll poke around too.

**Comment by slorber** [comment]
I troubleshooted this and unfortunately for you, this is related to TailwindCSS (and you use it through a Docusaurus plugin)

You can reproduce this behavior on a standalone TailwindCSS v3 sandbox, for example:
- https://github.com/poornerd/tailwindcss-postcss-webpack-starter
- https://stackblitz.com/~/github.com/poornerd/tailwindcss-postcss-webpack-starter 

Creating any new file in a Tailwind `content` directory will lead to bundler recompilations, for both Webpack and Rspack.

I'm going to close because we can't do anything about it here, but I'm curious if you find an existing TailwindCSS issue about it, please let us know, or create one if needed.

Maybe TailwindCSS v4 beta is not affected by this problem.

**Comment by LegNeato** [comment]
Oh darn, sorry! I should have thought to disable plugins and not waste your time.

**Comment by slorber** [comment]
np, at least I learned something new about Tailwind 😄
