### ISSUE TITLE
v3.6.3 - Mermaid diagrams in a topic skew vertical position of linked H3 heading when called from anchor links in other topics 

### ISSUE THREAD

**Issue by yokaiichi** [facebook/docusaurus#10735]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [ ] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

Adding any type of Mermaid diagram to a topic vertically skews the behavior of anchor links (e.g., `[Link text](./target-file.mdx#heading-slug)`) from _other_ topics that point to an H3 heading in the topic. In other words, if my anchor link points to a given H3 heading in the target topic, following the link lands the reader at some point vertically _above_ the target H3 heading. The more Mermaid diagrams in the target topic, the farther the landing point is skewed upward, pushing the actual target heading quite far down below the bottom border of the browser window.

This issue seems to affect _only_ anchor links that point to H3 headings (###) within the topic. Anchor links to H2 headings seem to behave properly.

The topic where I discovered and debugged the root cause contained both `flowchart` and `gitGraph` mermaid code blocks. Removing only one or the other of these diagram types did not correct the issue. I had to remove ALL mermaid diagrams from the topic to correct the link target skew.

Note: I'm unsure whether this was a regression introduced in `"@docusaurus/theme-mermaid": "^3.6.3",` or the bug existed in earlier versions of this plugin. I didn't stumble across (notice) the issue until after my repo was upgraded to v3.6.3.

### Reproducible demo

Unable to set up playground for reproducible demo because cannot install mermaid in playground sandbox

### Steps to reproduce

(Unable to link to actual site because protected content. Also unable to set up playground codesandbox because unable to use npm to install `@docusaurus/theme-mermaid` there.)

## Step 1
Set up Mermaid diagram support per instructions in v3.6.3 doc here: [https://docusaurus.io/docs/markdown-features/diagrams](https://docusaurus.io/docs/markdown-features/diagrams)

## Step 2
Create two `.md` or `.mdx` topics (the bug is identical in both types of Markdown file): `source.mdx` and `target.mdx`. In the target file, create a variety of H2 (`##`) and H3 (`###`) sections. Basically, just copy some already populated file with a mixture of H2 and H3 sections from somewhere.

## Step 3
In the target file, add some `mermaid` fenced code blocks with valid diagram code, scattered throughout several of the first five sections. Tip: you can copy the two diagrams from [https://docusaurus.io/docs/markdown-features/diagrams](https://docusaurus.io/docs/markdown-features/diagrams) and paste them in a handful of times.

## Step 4
In the source file, create an anchor link to some H3 (`###`) section that appears far down in the target topic (below where you've pasted all the mermaid diagrams). For example `[Link to H3](./target.mdx#h3-heading-slug)`

## Step 5
run `npm run start` and test the `Link to H3` in the source file. You'll see that when it opens the target file, the target H3 section is far below the bottom of the browser window. Note that the same issue appears in real builds, too (`npm run build`).

### Expected behavior

When I follow an anchor link to an H3 section in a target topic, I should always land on a page view where the target H3 heading is sitting at the top of the current browser window, fully visible, with the H3 section contents immediately beneath the H3 heading.

### Actual behavior

When I follow an anchor link to an H3 section in a target topic, the target H3 section is far below the bottom of the browser window. The reader is now disoriented because the anchor link has taken them to the entirely wrong location in the target file, and the reader has lost context.

### Your environment

- Public source code: Unavailable. This is a private doc repo.
- Public site URL: Unavailable. This is a private doc site.
- Docusaurus version used: v3.6.3
- Environment name and version (e.g. Chrome 89, Node.js 16.4): Chrome 130, Node.js 20.18.0
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): MacOS Sonoma 14.6.1

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by slorber** [comment]
Mermaid diagrams are rendered client-side and produce layout shifts

This is a known issue due to that library's lack of SSR/Node support, tracked in https://github.com/facebook/docusaurus/issues/8299

Also reported in https://github.com/facebook/docusaurus/issues/9940
