### ISSUE TITLE
Docusaurus 3.6.3: Typescript cannot find module @theme

### ISSUE THREAD

**Issue by jackw** [facebook/docusaurus#10733]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [ ] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

Updating docusaurus from 3.6.0 to 3.6.3 appears to break type aliasing (at least in our mono-repo). I cannot track this down but anything that imports from `@theme` doesn't resolve to what should be `theme-classic` types anymore. I can fix it by adding the following to `tsconfig.json` which seems a bit strange for a minor update.

```diff
  "compilerOptions": {
    "baseUrl": ".",
+    "types": ["@docusaurus/theme-classic"]
  },
```
I've tried bumping TS, removing global.d.ts, scaffolding a fresh docusaurus website with `npx create-docusaurus@latest docusaurus-website classic --typescript` and comparing files but I cannot figure it out.

### Reproducible demo

https://github.com/grafana/plugin-tools/pull/1312

### Steps to reproduce

1. clone [grafana/plugin-tools](https://github.com/grafana/plugin-tools)
2. check-out branch `renovate/docusaurus-dependencies`
3. run `npm i` to install deps
4. run `npm typecheck`
5. See lots of `error TS2307: Cannot find module '@theme/*' or its corresponding type declarations.` errors

### Expected behavior

For the type aliases to resolve correctly.

### Actual behavior

Type aliases don't resolve resulting in lots of `error TS2307: Cannot find module '@theme/*' or its corresponding type declarations.` errors.

### Your environment

- Public source code: https://github.com/grafana/plugin-tools
- Public site URL: https://grafana.com/developers/plugin-tools/
- Docusaurus version used: 3.6.3
- Environment name and version (e.g. Chrome 89, Node.js 16.4): N/A
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): N/A

### Self-service

- [X] I'd be willing to fix this bug myself.

**Comment by ahnpnl** [comment]
I have the same issue

**Comment by slorber** [comment]
Thanks for reporting, this is related to https://github.com/facebook/docusaurus/pull/10694#discussion_r1846941638

I'll study your Grafana tools repo and see if I can find a better setup that doesn't break sites.

@ahnpnl it can help if you also share a repro

**Comment by jackw** [comment]
> Thanks for reporting, this is related to [#10694 (comment)](https://github.com/facebook/docusaurus/pull/10694#discussion_r1846941638)
> 
> I'll study your Grafana tools repo and see if I can find a better setup that doesn't break sites.


Thanks for the info and the link @slorber. So the current workaround would be the following in the websites tsconfig (as that is how it was previously):

```
"types": [
  "node",
  "@docusaurus/module-type-aliases",
  "@docusaurus/theme-classic"
],
```

**Comment by slorber** [comment]
I still think the change we did was right: our base TS config shouldn't explicitly restrict types, and keep TS default behavior.

However, removing `types` made it break your sites. It's because of a specific reason: since nowhere in your code there is any `import XYZ from '@docusaurus/theme-classic'`, then TS doesn't know that it has to load ambient theme types provided by this package.

There are multiple solutions, such as:
- adding a `types` field yourself (but this comes with the side-effect of whitelisting the types, not just including the ones we need)
- a triple-slash direct at the very top of a `.d.ts`: `/// <reference types="@docusaurus/theme-classic" />`
- an import of `@docusaurus/theme-classic` anywhere in your code

---

But to me the root of the problem is due to the half-typed setup of your sites, mostly because you use JS for your config files instead of TS.

By default, our init template imports theme/preset types automatically: https://github.com/facebook/docusaurus/blob/main/examples/classic-typescript/docusaurus.config.ts

In particular: 

`import type * as Preset from '@docusaurus/preset-classic';`

As soon as you properly type your config file according to the preset you use, all the necessary ambient theme files will become available for typechecking.

**Comment by slorber** [comment]
Note, if you want to keep a JS config file, you can get the same benefit with JSDoc, that is now provided by default in our init template:

```js
/** @type {import('@docusaurus/types').Config} */
const config = {
  ...generalConfig,
  url: 'https://grafana.com/',
  baseUrl: 'developers/plugin-tools/',
  plugins,
  presets: [
    [
      'classic',
      /** @type {import('@docusaurus/preset-classic').Options} */
      ({
        docs: {
          ...presetsDocs,
          routeBasePath: '/',
        },
        theme: presetsTheme,
        blog: false,
      }),
    ],
  ],
}
```

Important: make sure to wrap the option object with extra `()` otherwise the type doesn't get applied properly and the ambient types are not loaded.

**Comment by slorber** [comment]
@ahnpnl same for you even if your config is in TS, you should import/use the preset type:

```ts
import type {Config} from '@docusaurus/types';
import type * as Preset from '@docusaurus/preset-classic';

const config: Config = {
  title: 'My Site',
  presets: [
    [
      'classic',
      {
        docs: {
          
        },
        blog: {
          
        },
      } satisfies Preset.Options,
    ],
  ],
};
```

**Comment by jackw** [comment]
>I think we should keep the current base TS setup, and instead you should improve your site's typesafety. So unless there's a good reason, I'm going to close this issue. Please let me know if this works for you.

I see no reason not to move our configs to `.ts` files. Thanks for taking the time to write up such a detailed reply with a selection of solutions to the problem. 👍

**Comment by gordonlau** [comment]
> import type * as Preset from '@docusaurus/preset-classic';

Putting this in the `docusaurus.config.ts` fixes the weird type error. Thank you @slorber !

**Comment by sneko** [comment]
Coming from the v2, I may have missed something during the migration steps but ended with the same errors. The solution for me was to have as `tsconfig.json`:

```json
{
  "extends": "@docusaurus/tsconfig",
  "compilerOptions": {
    "types": ["@docusaurus/preset-classic"]
  }
}
```

**Comment by slorber** [comment]
@sneko importing the TS preset types would be a better solution: https://github.com/facebook/docusaurus/issues/10733#issuecomment-2520960063

We probably didn't explain this enough, but it's kinda mentioned in the v3 release notes: https://docusaurus.io/blog/releases/3.0#typescript
