### ISSUE TITLE
plugin-client-redirects cannot redirect correctly when the 'from' path of the plugin contains version information

### ISSUE THREAD

**Issue by shuashuai** [facebook/docusaurus#10738]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

plugin-client-redirects cannot redirect correctly to the target address when the value of from in the plugin configuration item contains version (eg: 1.10.1) information.
eg:
```
redirects: [
          {
            from: '/blog/2021/10/14/welcome-1.10.1-release',  //  Contains 1.10.1, so it cannot be redirected to , blog/welcome
            to: '/blog/welcome'
          },
          {
            from: '/blog/2021/10/14/welcome-1-10-1-release', //  This situation can handle correctly
            to: '/blog/welcome'
          }
        ],
```

### Reproducible demo

https://github.com/shuashuai/docusaurus-redirect

### Steps to reproduce

1. Install @docusaurus/plugin-client-redirects plugin
2. Add the following configuration to  docusaurus.config.ts
```
   plugins: [
    [
      '@docusaurus/plugin-client-redirects',
      {
        redirects: [
          {
            from: '/blog/2021/10/14/welcome-1.10.1-release',
            to: '/blog/welcome'
          },
          {
            from: '/blog/2021/10/14/welcome-1-10-1-release',
            to: '/blog/welcome'
          }
        ],
      },
    ],
  ]
```
3.  pnpm build
4. pnpm serve run the project
5. Accessing `/blog/2021/10/14/welcome-1.10.1-release` cannot be correctly redirected to `/blog/welcome`
6. Visiting `/blog/2021/10/14/welcome-1-10-1-release` can be correctly redirected to `/blog/welcome`

### Expected behavior

Correctly redirects to the target address when accessing a path with version information

eg: /blog/2021/10/14/welcome-1.10.1-release can correctly redirect to /blog/welcome

### Actual behavior

visit：` /blog/2021/10/14/welcome-1.10.1-release`

Path is not redirected to ` /blog/welcome-1.10.1-release`
![image](https://github.com/user-attachments/assets/f1e19e6b-d2c2-4d4d-b958-fef046fcbe98)

### Your environment

- Public source code: https://github.com/shuashuai/docusaurus-redirect
- Public site URL:
- Docusaurus version used: v3.6.3
- Environment name and version (e.g. Chrome 89, Node.js 16.4): Chrome 130.0.6723.117, Node.js 20
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): Ubuntu 20.04.2 LTS

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by slorber** [comment]
This is not a redirect plugin bug. The expected static client-side redirect file is properly generated.

The problem is `docusaurus serve` does not serve that file. This shouldn't affect other hosts and CDNs. Note that we don't particularly recommend using `docusaurus serve`, it's better to use a proper CDN instead.

The problem is in a dependency we use:
- https://github.com/vercel/serve/issues/446
- https://github.com/vercel/serve-handler/issues/133

You can reproduce with:

```bash
mkdir test
cd test

mkdir -p blog/foo.bar
echo "TEST" >> blog/foo.bar/index.html

mkdir -p blog/foo-bar
echo "TEST" >> blog/foo-bar/index.html

npx serve
```

Unfortunately, we can't really do anything about it from our side. I'm going to close, and hope that the dependency will fix the bug.
