### ISSUE TITLE
SQL block does not support block magic comments

### ISSUE THREAD

**Issue by babyfish-ct** [facebook/docusaurus#10748]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

I write sql code block like this

```sql
insert into BOOK(
    ID, NAME, EDITION, PRICE, STORE_ID
) values(?, ?, ?, ?, ?)
/* batch-0: [100, SQL in Action, 1, 59.9, 2] */
/* highlight-next-line */
/* batch-1: [7, LINQ in Action, 3, 49.9, 2] */
```

I used `/* highlight-next-line */` to highlight the last line, but it is actually not highlighted

This magic comment works normally for all languages except sql.

### Steps to reproduce

Just write a code block

- Language is SQL
- Use `highlight-next-line`

### Expected behavior

The next lien should be highlighted

### Actual behavior

The next line is not highlighted

This bug only appears when language is SQL

### Your environment

OS: Mac-M1
Docusaurus: 3.6.3
Node version: 22.2.0

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by slorber** [comment]
Looks like we don't support multi-line comments for SQL, only single-line `--` syntax.

This works:

````md
```sql
insert into BOOK(
    ID, NAME, EDITION, PRICE, STORE_ID
) values(?, ?, ?, ?, ?)
/* batch-0: [100, SQL in Action, 1, 59.9, 2] */
-- highlight-next-line
/* batch-1: [7, LINQ in Action, 3, 49.9, 2] */
```
````

![CleanShot 2024-12-10 at 11 28 52](https://github.com/user-attachments/assets/d602943b-3e32-4c9b-ab6d-cbf25b289cf0)

I think it should be pretty easy to add SQL multi-line comments, if anyone from the community want to contribute that in `packages/docusaurus-theme-common/src/utils/codeBlockUtils.ts`

**Comment by Rajvardhan222** [comment]
I want to contribute to this is it still open ?

**Comment by slorber** [comment]
You can submit a PR directly

**Comment by Rajvardhan222** [comment]
i made the changes but how i test those by viewing them to confirm

**Comment by Josh-Cena** [comment]
https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#development

**Comment by Rajvardhan222** [comment]
i am not sure how to view it even after changes it looks it is not taking effect
here is what i tried
 added a new comment pattern
` sql:{start:'/*',end:'*/'}, ` 

created a seprate case for sql inside getAllMagicCommentDirectiveStyles function
```
 case 'sql':
      return getCommentPattern(['sql','lua'], magicCommentDirectives);
```

**Comment by slorber** [comment]
We can't help you without seeing a PR including all your code and how it renders in the Netlify preview sorry. Please submit a draft PR and we'll review your attempt.
