### ISSUE TITLE
Allow React 19 in peerDependencies in Docusaurus v3

### ISSUE THREAD

**Issue by tats-u** [facebook/docusaurus#10750]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Motivation

React 19 was stabilized.
#9985 will be fixed once you update React to 19.
#10079 was fixed in Docusaurus 3.3, but are there any remaining problems preventing Docusaurus from combined with React 19?

### Self-service

- [ ] I'd be willing to do some initial work on this proposal myself.

**Comment by tats-u** [comment]
If we don't allow React 19 in Docusaurus 3.x, we will have to clarify "You may have to patch react-dom to prevent it from mixing NUL into output HTML." in the migration guide from 2.x.

**Comment by Jordaneisenburger** [comment]
I think it will take a while before we get react 19 support unfortunately: https://github.com/facebook/docusaurus/pull/10745

**Comment by tats-u** [comment]
I'm glad to know it but it's disappointing that React 19 is going to be supported only by Docusaurus v4.

**Comment by Jordaneisenburger** [comment]
> Considering the low amount of changes required to support React 19, I think it should be possible to support both React 18 and React 19 in Docusaurus v3.
> 
> I'd see if we can allow React 19 in Docusaurus v3.7. If possible and for dogfooding, I'd like new initialized sites and our own website to also use React 19 asap.
> 
> The breaking change for Docusaurus v4 is to **require** React 19, so that we can start using new features that are not available in v18.

That would be amazing, main reason for me is that we use Docusaurus in a NX repo and get a bunch of peerdep headaces from Docusaurus atm as we're upgrading our other apps to React 19
