### ISSUE TITLE
use an npm package react-quill, and then docusaurus build fails

### ISSUE THREAD

**Issue by maqi1520** [facebook/docusaurus#10757]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

use an npm package react-quill, and then docusaurus build fails
![image](https://github.com/user-attachments/assets/96784d54-e250-49a7-a63f-10ee17609720)

npm start is successful

### Reproducible demo

 https://stackblitz.com/edit/github-zmmadx4y?file=src%2Fcomponents%2FHomepageFeatures%2Findex.tsx,package.json

### Steps to reproduce

npm run build

### Expected behavior

docusaurus build success

### Actual behavior

docusaurus build fails

### Your environment

- Public source code:
- Public site URL: https://stackblitz.com/edit/github-zmmadx4y?file=src%2Fcomponents%2FHomepageFeatures%2Findex.tsx,package.json
- Docusaurus version used:
- Environment name and version (e.g. Chrome 89, Node.js 16.4):
- Operating system and version (e.g. Ubuntu 20.04.2 LTS):

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by maqi1520** [comment]
const ReactQuill = typeof window === 'object' ? require('react-quill') : () => null;

**Comment by slorber** [comment]
https://docusaurus.io/docs/advanced/ssg#browseronly
