### ISSUE TITLE
add jpegxl support

### ISSUE THREAD

**Issue by joskezelensky** [facebook/docusaurus#10765]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Motivation

jpeg-XL is a cutting-edge new image codec that is faster, better at lossy compression than any other image codec and has faster image decompression. Webp is unreliable and jpeg can have a lot of artifacts
So why is jpeg-xl not supported? maybe because it isn't supported by chromium, but hey. If docosaurus supports jpeg-xl before chromium does again, it will be already implemented.

### Self-service

- [ ] I'd be willing to do some initial work on this proposal myself.

**Comment by slorber** [comment]
What does it mean for Docusaurus to support jpegxl according to you?

What prevents you from implementing a Docusaurus plugin to add this support on your own?

We use Webpack image loader to allow `require("./img.png")` syntax:


```ts
    images: () => ({
      use: [loaders.url({folder: 'images'})],
      test: /\.(?:ico|jpe?g|png|gif|webp|avif)(?:\?.*)?$/i,
    }),
```

If you just want us to add support for `.jsx` extensions, we could do that easily.
But is it what you actually want? I don't know. 🤷

**Comment by joskezelensky** [comment]
> What does it mean for Docusaurus to support jpegxl according to you?
> 
> What prevents you from implementing a Docusaurus plugin to add this support on your own?
> 
> The goal of Docusaurus is not to support everything out of the box: we rely on the community and our plugin ecosystem for that and only include the most common, well-supported things in the core repo/packages. If something is not supported in all browsers yet, it's unlikely we encourage usage of it by creating something custom to support it.
> 
> We use Webpack image loader to allow `require("./img.png")` syntax:
> 
> ```ts
>     images: () => ({
>       use: [loaders.url({folder: 'images'})],
>       test: /\.(?:ico|jpe?g|png|gif|webp|avif)(?:\?.*)?$/i,
>     }),
> ```
> 
> If you just want us to add support for `.jxl` extensions, we could do that easily.
> 
> But is it what you actually want? I don't know. 🤷

i put out an issue too soon
it was a warning, so it wasn't even a problem, and i mindlessly put out an issue
and your solution is really simple, so that should fix the warning, thanks!
