### ISSUE TITLE
--host 0.0.0.0 Operation does not work

### ISSUE THREAD

**Issue by lixumin-zai** [facebook/docusaurus#10772]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [x] I have read the console error message carefully (if applicable).

### Description

I tried to use "npm run start -- --host 0.0.0.0" or "npx docusaurus start --host 0.0.0.0", but it didn't work
![image](https://github.com/user-attachments/assets/c2d7ec67-2dd2-4475-8816-3faf3e775ed5)

node: v18.20.5
docusaurus: 3.6.3

### Steps to reproduce

1. npx create-docusaurus@latest my-website classic
2. cd my-website
3. npm start -- --host 0.0.0.0  or  npx docusaurus start --host 0.0.0.0

### Expected behavior

I want other machines to be able to access the website as well

### Actual behavior

He's still starting in localhost

### Your environment

- Public source code: No
- Public site URL: No
- Docusaurus version used: 3.6.3
- Environment name and version (e.g. Chrome 89, Node.js 18.20.5):
- Operating system and version (e.g. Ubuntu 20.04.2 LTS):

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by slorber** [comment]
`0.0.0.0` isn't what gets printed to the console, but it's technically working:

![CleanShot 2024-12-19 at 11 53 21](https://github.com/user-attachments/assets/692264ca-e103-4665-8488-c56bb2627804)


We use this package that apparently prints `localhost` for `0.0.0.0`, wondering is this a big deal and worth fixing.

https://github.com/facebook/create-react-app/blob/main/packages/react-dev-utils/WebpackDevServerUtils.js#L24C10-L24C21

**Comment by lixumin-zai** [comment]
0.0.0.0 indicates that other clients should also be able to access the services of the server, but this doesn't work. I can use it normally on the server. However, when I try to access the IP address of the server where it is started (followed by port 3000) from other machines, the page I get is blank.

**Comment by lixumin-zai** [comment]
So I had to do port forwarding

**Comment by slorber** [comment]
Sorry but I'm not able to understand what you are trying to achieve, what is your exact setup and what are the computers involved, your current network topology.

`npm start` is only meant to be used in dev locally, not exposed through the internet
