### ISSUE TITLE
Problem with internationalization of bottom navigation on docs page

### ISSUE THREAD

**Issue by huangj17** [facebook/docusaurus#10794]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [ ] I have tried the `npm run clear` or `yarn clear` command.
- [ ] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io.
- [x] I have read the console error message carefully (if applicable).

### Description

![image](https://github.com/user-attachments/assets/6c35b772-886a-4c7f-8e9d-614e90df232a)
In the first page with subpages, the internationalization of the parent page title displayed at the bottom does not display properly

### Steps to reproduce

1. Open the official link: https://docusaurus.io/zh-CN/docs/docs-introduction.
2. Slide to the bottom.
3. View the title of "Previous".
4. ![image](https://github.com/user-attachments/assets/6c35b772-886a-4c7f-8e9d-614e90df232a)

### Expected behavior

Expected bottom navigation, normal display of internationalized title

### Actual behavior

![image](https://github.com/user-attachments/assets/b675c7d1-46c4-4511-a297-5803b36bac80)

### Your environment

- Public source code:
- Public site URL:
- Docusaurus version used:
- Environment name and version (e.g. Chrome 89, Node.js 16.4):
- Operating system and version (e.g. Ubuntu 20.04.2 LTS):

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by slorber** [comment]
This is a known issue of i18n and generated index pages.

Let's track it here: https://github.com/facebook/docusaurus/issues/8996

This has also been discussed here: https://github.com/facebook/docusaurus/issues/10753

And a previous PR attempt: https://github.com/facebook/docusaurus/pull/8123
