### ISSUE TITLE
🌟Help us feature more Docusaurus users!

### ISSUE THREAD

**Issue by yangshun** [facebook/Docusaurus#1080]
**Tip: This is a beginner level Docusaurus task that requires almost no coding and is more targeted at newcomers to the project and Open Source.**

## 📚 Documentation

We want to feature more Docusaurus users and we need your help!

Docusaurus has a [users page](https://docusaurus.io/en/users) where we showcase projects using Docusaurus. This has the benefits of giving projects recognition and also lets the community and new users reference the creative ways of using Docusaurus. For example, Babel implemented the "copy code" button which we copied into our code, Reason has a full-width doc page and Prettier has a playground.

Here's a list of projects that we want to feature, in no particular order.

- [ ] https://github.com/express-validator/express-validator (@arijitthehacker)
- [ ] https://github.com/wix/Detox (@Alquimista3301)
- [ ] https://github.com/twitchtv/twirp (@co16353sidak) 
- [ ] https://loonajs.com/ (@NishealJ)
- [x] https://testing-library.com/ (@hongarc)
- [ ] https://microsoft.github.io/just (@co16353sidak)
- [ ] https://github.com/almond-sh/almond (@hongarc)
- [ ] https://github.com/lusakasa/sqorn (@hongarc)
- [ ] https://github.com/tipsi/tipsi-stripe (@hongarc)
- [ ] https://react-fns.netlify.com (@hongarc)
- [ ] https://github.com/mbasso/asm-dom (@hongarc)
- [ ] https://nervjs.github.io/taro/ (@hongarc)
- [ ] https://callstack.github.io/react-native-testing-library/ (@hongarc)
- [x] https://github.com/qiu8310/minapp (@qiu8310 + @NishealJ)

Done:

- [x] https://github.com/reduxjs/react-redux/ (@wgao19)
- [x] https://github.com/jaredpalmer/formik (@shahednasser)
- [x] https://github.com/node-serialport/node-serialport (@mikeattara)
- [x] https://github.com/facebook/react-360 (@sunitasen)
- [x] https://github.com/callstack/haul (@ellereeeee)
- [x] https://github.com/19majkel94/type-graphql (@19majkel94)
- [x] https://github.com/zamotany/react-slate (@andrewShillito)
- [x] https://github.com/hemerajs/hemera (@alexperez)
- [x] https://github.com/Cretezy/Noderize (@Rajekevin)
- [x] https://github.com/react-native-sensors/react-native-sensors (@mikeattara)
- [x] https://github.com/Khan/KaTeX (@haoqiang)
- [x] https://github.com/PaulLeCam/react-leaflet (@zakariaharti)
- [x] https://github.com/reduxjs/redux (@YifanM) 
- [x] https://github.com/scalameta/scalafmt (@ahtee)
- [x] https://github.com/apache/pulsar (@NishealJ)
- [x] https://github.com/boyney123/mockit (@NishealJ)

The process of adding users goes like this:

1. Comment below with the project you're interested in helping and make sure it's not already claimed.
1. Check if the project has a logo. If it doesn't have a logo, we could ask them to create one. If not, then we can't feature it as we don't have a way to feature projects without logos at the moment. Sorry about that.
1. Make an issue on the GitHub project, asking about featuring their project on Docusaurus (most people would be okay with that).
1. Get a reasonable-sized version of their logo (SVG preferred) and add it to `website-1.x/static/img/users/<project-name-in-lower-snake-case>.{svg/png/jpg}` not exceeding 512x512. Look into their website directory or project directory for the logo image file. Try to compress the logo first if possible using Photoshop or some online tools.
1. Modify `website-1.x/data/users.js` and add the project into the JS file, sorted alphabetically by caption:

```
{
  caption: 'The Project Name',
  image: '/path/to/image',
  infoLink: 'www.example.com', // Website. Can be GitHub repo URL if website doesn't exist
  fbOpenSource: false,
  pinned: false,
},
```

4. Run the Docusaurus website locally and see that the users page loads fine and shows the new user!
1. Run `yarn lint` and `yarn prettier` before submitting the PR.
1. Use the PR title - `docs: showcase user <project name>`.
1. In the PR summary, add a link to the PR where you've asked the project for permissions to include their logo
1. Submit your PR!

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

**Comment by shahednasser** [comment]
I'm interested in working on Formik

**Comment by yangshun** [comment]
@shahednasser Thanks, have updated the description with your name.

**Comment by Rajekevin** [comment]
Hello @yangshun , 
I am interested in working on Noderize

**Comment by yangshun** [comment]
@Rajekevin Thanks, have updated the description with your name.

**Comment by sunitasen** [comment]
I am interested in react-360

**Comment by yangshun** [comment]
@sunitasen It's yours! React-360 doesn't need permission because it's by FB. Go ahead and create the PR!

**Comment by andrewShillito** [comment]
@yangshun Hello.  I'm interested in working on react-slate.

**Comment by yangshun** [comment]
@andrewShillito Go ahead. Thank you!

**Comment by andrewShillito** [comment]
@yangshun Ok thank you! They have a couple of assets [here](https://github.com/zamotany/react-slate/blob/master/website/static/img/react_slate_icon.png) and [here](https://github.com/zamotany/react-slate/blob/master/website/static/img/react_slate_logo.png) that I was thinking might work. I'll check in with them, make a PR and if it works out cool and if not I'll select another project.

**Comment by yangshun** [comment]
@andrewShillito By all means! Go ahead!

**Comment by alexperez** [comment]
Hello @yangshun
I’m interested in working on hemera.

**Comment by yangshun** [comment]
@alexperez It's yours!

**Comment by wgao19** [comment]
Hey @yangshun can I pick up React-Redux?

**Comment by yangshun** [comment]
@wgao19 definitely! I guess you don't need to ask for approval from React-Redux since you work on it 😉 Feel free to send us a PR anytime!

**Comment by ymschaap** [comment]
@yangshun I made this for [Babel](https://build.new/your-company/babel). It allows them to just fill out a form (instead of a fork, change file, add image, test, commit, PR), which will create a valid PR like [this](https://github.com/ymschaap/website/pull/11). Interested if I make the same feature available for Docusaurus?

**Comment by arijitthehacker** [comment]
Hi, I'm interested in working on express-validator.

**Comment by JoelMarcey** [comment]
> Hi, I'm interested in working on express-validator.

It's yours. 😄

**Comment by yangshun** [comment]
@ellereeeee it's yours!

I'll check in with you periodically so that we can keep the task updated with the progress.

**Comment by yangshun** [comment]
@arijitthehacker Go ahead!

**Comment by yangshun** [comment]
@ymschaap I'm unable to access the first link you provided, it leads to an error page. Based on what you are suggesting, it sounds awesome and we'd love to include it! Fill free to create a PR!

**Comment by ymschaap** [comment]
@yangshun @JoelMarcey my bad, that is my own localhost I linked to. The url is:
> https://build.amsterdam/your-company/babel

**Comment by zakariaharti** [comment]
hello @yangshun 
i'm interested in React-Leaflet

**Comment by yangshun** [comment]
@zakariaharti it's yours!

**Comment by ellereeeee** [comment]
https://github.com/facebook/Docusaurus/pull/1130

**Comment by ellereeeee** [comment]
https://github.com/facebook/Docusaurus/issues/1080#issuecomment-437898837

**Comment by ellereeeee** [comment]
@yangshun My pull request was merged.

Help us feature more Docusaurus users! #1080

**Comment by yangshun** [comment]
@ellereeeee Thanks, it has been updated

**Comment by mikeattara** [comment]
Hello @yangshun I would love to work on node-serialport

**Comment by yangshun** [comment]
@mikeattara It's yours!

**Comment by mikeattara** [comment]
@yangshun I would like to take up react-native-sensors
I am also working on adding a better logo for gulp

**Comment by 19majkel94** [comment]
@yangshun 
I've added myself 😄 (19majkel94/type-graphql)
https://github.com/facebook/Docusaurus/pull/1174

**Comment by yangshun** [comment]
@micksatana go ahead, thank you!

**Comment by yangshun** [comment]
@19majkel94 That's amusing. Thank you too 🎉

**Comment by haoqiang** [comment]
Happy New Year ~  

I'll take https://github.com/Khan/KaTeX then.  

Interestingly there's an issue created by them already, but since I don't see KaTex in the user page, I'll just proceed. ref: https://github.com/KaTeX/KaTeX/issues/1753

**Comment by Alquimista3301** [comment]
Hello @yangshun ,
I am interested in working on Detox :)

**Comment by yangshun** [comment]
@Alquimista3301 It's yours! Thanks!

**Comment by ahtee** [comment]
@yangshun 
I'd like to take 
* https://github.com/scalameta/scalafmt
I'm assuming this would use the `scalameta` logo (.png)

**Comment by yangshun** [comment]
@ahtee Go ahead!

**Comment by ahtee** [comment]
@yangshun here's the approval. Ill go ahead and make the pr

**Comment by ahtee** [comment]
@yangshun in my pr #1250, some of the images arent showing up:

<img width="900" alt="screen shot 2019-02-26 at 12 29 17 pm" src="https://user-images.githubusercontent.com/5076085/53433432-5ab8a600-39c2-11e9-913f-504ebde20e68.png">

**Comment by ahtee** [comment]
thanks for covering that linting :)

**Comment by ahtee** [comment]
another addition could be https://microsoft.github.io/just/ 💯

**Comment by yangshun** [comment]
Thanks, updated with Just 😄

**Comment by co16353sidak** [comment]
@yangshun 
Would like to work on adding twitch's `twirp`, I find that it is not taken by anyone at the moment and could be a good addition to the user's page.

**Comment by yangshun** [comment]
@co16353sidak It's yours!

**Comment by co16353sidak** [comment]
@yangshun I have received the green light to use the Twirp logo, although we cannot use the twitch logo as that would require some serious permissions being a complete company and all.
But we can use the Twirp logo which seems to me as sufficient for doing this.
What do you say?

**Comment by co16353sidak** [comment]
Okay creating a PR for this.

**Comment by yangshun** [comment]
@co16353sidak Yes please go ahead. TIL that Twirp had a logo. Would be good for them to show it somewhere on their docs page.

**Comment by ahtee** [comment]
threads like this sometimes cascade into other pr's for other projects TIL!

**Comment by co16353sidak** [comment]
yeah, @ahtee added another issue 🎉 💯 but this rarely happens.

**Comment by co16353sidak** [comment]
@yangshun @ahtee  would like to take up `just` as well, hopefully if I am allowed to take up another project. 🥇

**Comment by yangshun** [comment]
@co16353sidak Sorry for the late reply. By all means!

**Comment by NishealJ** [comment]
Hi @yangshun , I've taken up apache pulsar Thanks !

**Comment by Hongarc** [comment]
@yangshun I created some issue to ask permission add showcase.

Can I create PR to update image?(add logo to this project instead of they image)

**Comment by yangshun** [comment]
@Hongarc go ahead!

**Comment by Hongarc** [comment]
> @Hongarc go ahead!

Your mean is pull request for new showcase or update image for existed showcase?

**Comment by yangshun** [comment]
Sorry I'm not understanding your question well. Let's follow the usual flow mentioned above. Feel free to message me on Discord, we can discuss there.

**Comment by Hongarc** [comment]
@yangshun Can I create PR others Docusaurus user, example https://openzeppelin.org/

**Comment by NishealJ** [comment]
Hi @arijitthehacker , can you please raise a PR for express-validator ?

**Comment by yangshun** [comment]
Closing this task and creating a [part 2 issue](https://github.com/facebook/Docusaurus/issues/1080) to prevent noise to existing subscribers. Thank you for all your efforts thus far!
