### ISSUE TITLE
Renaming the website folder

### ISSUE THREAD

**Issue by noraj** [facebook/Docusaurus#1082]
## 📚 Documentation

In the config file there is an optional `customDocsPath` to allow costuming of the doc folder name.
As the `website/` directory is the base directory, it can be renamed as we want, for example if conflicting with another folder because you put the docusaurus project inside your real software project.

So the documentation should say that we can rename it.

- [x] I have read the [Contributing Guidelines on issues](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

**Comment by andrewShillito** [comment]
@noraj I was thinking that the pictured section (under bullet 2) at [docusaurus installation page](https://docusaurus.io/docs/en/installation.html) would be a good place to add a note that the website folder name can be changed in the config file.  Does that sound like what you are looking for? 
![img](https://user-images.githubusercontent.com/34523587/48137569-5ed48280-e270-11e8-83e3-d5bdd25cd83e.png)

**Comment by noraj** [comment]
@andrewShillito I think it will be better fitted in [getting-started-preparation.md](https://github.com/facebook/Docusaurus/blob/master/docs/getting-started-preparation.md) than in [getting-started-installation.md](https://github.com/facebook/Docusaurus/blob/master/docs/getting-started-installation.md). Maybe in the section **Preparation Notes**.

**Comment by yangshun** [comment]
PRs are welcome for this 😄

**Comment by noraj** [comment]
@andrewShillito Thanks for you PR but you added information about `customDocsPath` (that's not a bad thing) that allows to modify the name of the folder named `docs` by default (that is documented here https://docusaurus.io/docs/en/site-config#customdocspath-string).
But my issue was talking about the ability to rename the `website` folder that is undocumented right now. I'll make a PR when I will have time.

**Comment by yangshun** [comment]
Thanks for fixing this @noraj !

**Comment by andrewShillito** [comment]
@noraj Sorry I misunderstood that!  I will make sure to double check I'm not misunderstanding the issue before contributing next time.  Thanks.

**Comment by noraj** [comment]
@andrewShillito Actually not a problem because your contribution is good too.
