### ISSUE TITLE
Option switch to choose if minifying or not

### ISSUE THREAD

**Issue by noraj** [facebook/docusaurus#1083]
## 🚀 Feature

Adding a new param in the config file to choose if we want to minify the code during building or not.

- [x] I have read the [Contributing Guidelines on issues](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

## Motivation

Code is always minified so he is ugly and unreadable.
Unminified code is not a problem for low traffic websites where the bandwidth will not be a problem if serving unminified code.

## Pitch

See **motivation**. Reading the optional param in the config file, instead of blindly minifying.

**Comment by endiliey** [comment]
Try filing this on https://v2.docusaurus.io/feedback
