### ISSUE TITLE
Collapsus - The Collapsible Menu

### ISSUE THREAD

**Issue by clearwaterstream** [facebook/Docusaurus#1084]
## 🚀 Feature

Collapsible menu . Sub-categories will get collapsed under the main categories. Examples: https://reactjs.org/docs/getting-started.html or https://docs.gitbook.com/getting-started

## Have you read the [Contributing Guidelines on issues](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes I have

## Motivation

We have a sizable amount of content and having a large (expanded) menu would overwhelm a user upon visiting our documentation area. Those with weaker nerves may get spooked and run away from our site.

## Pitch

We have an "enterprise" level product which comes with sizable documentation. I am sure we are not the only ones. I think having this feature would attract other companies who have similar documentation requirements. Let the Collapsus out!

Thanks!!

**Comment by eliyasbaby** [comment]
> ## 🚀 Feature
> Collapsible menu . Sub-categories will get collapsed under the main categories. Examples: https://reactjs.org/docs/getting-started.html or https://docs.gitbook.com/getting-started
> 
> ## Have you read the [Contributing Guidelines on issues](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?
> Yes I have
> 
> ## Motivation
> We have a sizable amount of content and having a large (expanded) menu would overwhelm a user upon visiting our documentation area. Those with weaker nerves may get spooked and run away from our site.
> 
> ## Pitch
> We have an "enterprise" level product which comes with sizable documentation. I am sure we are not the only ones. I think having this feature would attract other companies who have similar documentation requirements. Let the Collapsus out!
> 
> Thanks!!

Yes.this is indeed.this would be an awesome feature.I also want to show a huge list of content in the side bar.without  the expand collapse option the huge list would be ugly

**Comment by tsmrachel** [comment]
@endiliey @yangshun 

Are there any plans to consider using React to add interactivity? Or should this be worked on using script injection?

https://github.com/facebook/Docusaurus/issues/582#issuecomment-382488782
>Docusaurus uses React mainly to render the components statically into HTML on the server, so your code wouldn't work. There's no React library being sent to the client to hydrate the markup and add interactivity.

**Comment by endiliey** [comment]
@tsmrachel that's our plan for Docusaurus v2

You can read on https://github.com/facebook/Docusaurus/issues/789 or https://docusaurus.io/blog/2018/09/11/Towards-Docusaurus-2

Instead of pure static HTML, during build time we will create a server-rendered version of the app and render the corresponding HTML. A Docusaurus site will be essentially an isomorphic/universal application. This approach is heavily inspired by Gatsby.

**Comment by markerikson** [comment]
I could see this being useful for Redux as well.

**Comment by yangshun** [comment]
This has been released in 1.7.1.

**Comment by clearwaterstream** [comment]
Awesome, much thanks!!!
