### ISSUE TITLE
Use sidebar_label in pagination buttons.

### ISSUE THREAD

**Issue by maxaggedon** [facebook/Docusaurus#1085]
## 🚀 Feature

Display `sidebar_label` (if existing) of the previous and next docs instead of the `title` in bottom pagination buttons.

## Have you read the [Contributing Guidelines on issues](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

yes

## Motivation

If it has been set, `sidebar_label` is meant to be used for navigation (it could even be renamed `nav_label`). And it will certainly be shorter than `title` which will prevent some ugly UI cases...

## Pitch

As a user I thought it would be the case. Why would I set an explicit label for navigation purposes and not see it in pagination?
**I would be glad to work on a PR if the idea is accepted =)**

**Comment by huguestennier** [comment]
Should be fixed in [v1.5.1](https://github.com/facebook/Docusaurus/releases/tag/v1.5.1).

See related PR : https://github.com/facebook/Docusaurus/pull/1079

**Comment by maxaggedon** [comment]
@huguestennier the PR you mention fixes a bug where the buttons always displays *previous* and *next*. With this fix, it displays the articles' `title` if existing. (Please correct me if I am wrong)

What I suggest is to display `sidebar_title` instead of `title`.
