### ISSUE TITLE
Livereload not working on second try

### ISSUE THREAD

**Issue by yangshun** [facebook/Docusaurus#1091]
## 🐛 Bug Report

The local server does not livereload anymore after the first livereload.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes.

## To Reproduce

1. Start the webserver
1. Edit anything v1/website/pages/index.js. See that the page refreshes.
1. Edit the same file again.

## Expected behavior

Page should refresh regardless of how many times.

## Actual Behavior

The page does not refresh. The reason is because the livereload script is not being sent down to the client after the first refresh. In `liveReloadServer.js`, the second call of `getReloadScriptUrl` returns  `undefined`. The module is probably unloaded and loaded again, causing the local `reloadScriptUrl` variable to lose its value. We probably shouldn't be storing local values within modules.

**Comment by kahkhang** [comment]
I'd like to attempt solving this issue! :)

**Comment by yangshun** [comment]
@kahkhang it's yours!

I've added an "issue: claimed" label so that others will know not to start work on the issue. If you change your mind about the issue, no worries! Just let me know so that I can remove the label and free it up for someone else to claim.

I'll check in with you periodically so that we can keep the task updated with the progress.
