### ISSUE TITLE
Document that Docker is optional?

### ISSUE THREAD

**Issue by ablakey** [facebook/docusaurus#1110]
## 📚 Documentation

Following the Getting Started documentation led me to a pretty great starting point for building my own documentation site. However it didn't mention that I would be getting a bunch of Docker-related files. These are great, but not always useful. Would it be a good idea to report somewhere that these files will exist and that they're optional and can be cleaned up if unwanted?

I'm happy to take a crack at writing it if this is a fair assessment.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Sure have, coach!

**Comment by yangshun** [comment]
@ablakey Yes that's reasonable. Feel free to submit a PR for this!

**Comment by ablakey** [comment]
Great. Glad to see I understand the situation. I'll tackle this next time I'm working on docs.

**Comment by EricPonvelle** [comment]
I created this pull request to clarify the text - https://github.com/facebook/docusaurus/pull/1848
