### ISSUE TITLE
Show a warning message when links are broken

### ISSUE THREAD

**Issue by gianlucadonato** [facebook/Docusaurus#1111]
## 🚀 Feature

Show a warning message in the console (maybe flaggable in the options) that outputs a log when a link inside the documentation is broken. 

## Have you read the [Contributing Guidelines on issues](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes.

## Motivation

It can happen to have brokens links in the documentation that are caused by a change in the file id/path (e.g. a file is renamed, moved or simply there's a typo in the link) and then forgetting to update the link that points to it.
It's a pain discovering where they are in the docs and fix it.

## Pitch

It would be nice to introduce a check when running ```docusaurus start``` or ```docusaurus build``` that shows a warning message if a link in the markdown has an unresolved path.

**Comment by manojbadam** [comment]
@gianlucadonato @endiliey - we want to make use of this functionality in our CI tests, before publishing the website we want to fail the CI tests if there are any broken links and not publish. Any tips to achieve that?, parsing logs is one option, is there any better approach ?

**Comment by renatovieiradesouza** [comment]
> @gianlucadonato @endiliey - queremos usar essa funcionalidade em nossos testes de IC, antes de publicar o site, queremos reprovar nos testes de CI se houver links quebrados e não publicar. Alguma dica para conseguir isso ?, analisar os logs é uma opção, existe uma abordagem melhor?

you can use bcl for this, install by npm. https://www.npmjs.com/package/broken-link-checker

**Comment by prestonvanloon** [comment]
We would also like this to be part of our CI. I am not sure how bcl is relevant for a presubmit check since it seems to require a live site to function.
