### ISSUE TITLE
The translated documentation pages do not show the left ToC

### ISSUE THREAD

**Issue by hsluoyz** [facebook/Docusaurus#1112]
## 🐛 Bug Report

The translated documentation pages do not show the left ToC (table of contents).

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## To Reproduce

English: https://docusaurus.io/docs/en/installation
Chinese: https://docusaurus.io/docs/zh-CN/installation

## Expected behavior

https://docusaurus.io/docs/zh-CN/installation should show the left ToC just like: https://docusaurus.io/docs/en/installation

## Actual Behavior

The left ToC doesn't show up.

## Reproducible Demo

No need.

**Comment by endiliey** [comment]
Thanks a lot for reporting @hsluoyz 

![image](https://user-images.githubusercontent.com/17883920/48761618-12635b00-ece4-11e8-8d79-e8a363b5633d.png)

**Comment by hsluoyz** [comment]
Thanks for the fix, @endiliey.

BTW, when is the next release? Or is there a way to use the latest commit without a release? Thanks.
