### ISSUE TITLE
Static files in `blog/assets` is not working

### ISSUE THREAD

**Issue by tconnally** [facebook/Docusaurus#1114]
## 📚 Documentation

The following location location in the docs indicates what is possibly an incorrect procedure for adding graphics to a blog post. It says to create an "assets" folder in the /blog directory. This is apparently not working, and graphics should apparently live in /static/img, and use a path of /img/image-name.png. But this didn't seem to work in the testing I just did. 

https://docusaurus.io/docs/en/doc-markdown#linking-to-images-and-other-assets

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

(yes.

**Comment by endiliey** [comment]
We should replace all string occurrences of `assets/XXX` in all blog markdown just like in docs

Notice how we replace it in `docs.js` but not in `blog.js`

https://github.com/facebook/Docusaurus/blob/beca1697ffe733b1c13caacc4189e25264c828a2/v1/lib/server/docs.js#L128-L129

https://github.com/facebook/Docusaurus/blob/beca1697ffe733b1c13caacc4189e25264c828a2/v1/lib/server/docs.js#L108-L119

`server/blog.js`
We should modify the content at this line
https://github.com/facebook/Docusaurus/blob/beca1697ffe733b1c13caacc4189e25264c828a2/v1/lib/server/blog.js#L59
