### ISSUE TITLE
`npm run version` generates broken sidebars when subcategories exist

### ISSUE THREAD

**Issue by aeneasr** [facebook/Docusaurus#1115]
## 🐛 Bug Report

Running `npm run version <x>` generates broken sidebars on version **1.5.1**. 
### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yup

## To Reproduce

Sidebar definition `sidebar.json`

```

    "ORY Hydra": [
      "hydra/hydra-index",
      {
        "type": "subcategory",
        "label": "Getting Started",
        "ids": [
          "hydra/hydra-5min-tutorial"
        ]
      },
      {
        "type": "subcategory",
        "label": "Guides",
        "ids": [
          "hydra/hydra-oauth2",
          "hydra/hydra-jwks",
          "hydra/hydra-configure-deploy",
          "hydra/hydra-advanced",
          "hydra/hydra-debugging",
          "hydra/hydra-production",
          "hydra/hydra-integration"
        ]
      },
      {
        "type": "subcategory",
        "label": "SDK",
        "ids": [
          "hydra/hydra-sdk-sdk/hydra-sdk-index",
          "hydra/hydra-sdk-sdk/hydra-sdk-api",
          "hydra/hydra-sdk-sdk/hydra-sdk-go",
          "hydra/hydra-sdk-sdk/hydra-sdk-js"
        ]
      },
      {
        "type": "subcategory",
        "label": "Further Reading",
        "ids": [
          "hydra/hydra-limitations",
          "hydra/hydra-dependencies-environment",
          "hydra/hydra-security-architecture",
          "hydra/hydra-faq",
          "hydra/hydra-appendix"
        ]
      }
    ],
```

yields after running `npm run version oryOS.9` in `./versioned_sidebars/version-oryOS.9-sidebar.json`

```
{
  "version-oryOS.9-docs": {
    // ...
    "ORY Hydra": [
      "version-oryOS.9-hydra/hydra-index",
      "version-oryOS.9-[object Object]",
      "version-oryOS.9-[object Object]",
      "version-oryOS.9-[object Object]",
      "version-oryOS.9-[object Object]"
    ],
    // ...
```

## Expected behavior

The sidebar should not contain broken links.

## Actual Behavior

The sidebar contains broken links.

## Reproducible Demo

1. `git clone https://github.com/ory/docs.git`
2. `cd docs`
2. `git checkout dd96ee81cf315284ee88dd7d2fe5cb10c60be67d -b reproduceme2`
3. `cd website`
4. `npm i`
7. `npm run version oryOS.9`
7. `cat ./website/versioned_sidebars/version-oryOS.9-sidebars.json`

**Comment by endiliey** [comment]
This is related to incomplete PR of subcategories feature. We should update the logic for https://github.com/facebook/Docusaurus/blob/master/v1/lib/version.js
