### ISSUE TITLE
the website is not running correct  , just show messy code (not readable)

### ISSUE THREAD

**Issue by yishuiliunian** [facebook/Docusaurus#1121]
## 🐛 Bug Report

(A clear and concise description of what the bug is)

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

yes

## To Reproduce

1. add some docs
1. edit the sidebars.json
1. run with `npm start`

## Expected behavior

website running correct, show my docs

## Actual Behavior

![2018-11-20 9 31 45](https://user-images.githubusercontent.com/846525/48776791-ba404f00-ed0b-11e8-9d53-57e294bdc6e3.png)

## Reproducible Demo
[demo.zip](https://github.com/facebook/Docusaurus/files/2599922/demo.zip)

**Comment by JoelMarcey** [comment]
That output looks like nothing that Docusaurus would output.

Did you run `docusaurus-init` to see if the sample site would run correctly?

**Comment by endiliey** [comment]
Checked locally and unable to reproduce. Could be local issue

Try following https://docusaurus.io/docs/en/installation
