### ISSUE TITLE
Error on adding docusaurus package using yarn.

### ISSUE THREAD

**Issue by nutann3** [facebook/Docusaurus#1142]
## 🐛 Bug Report

I'm unable to add docusaurus package using yarn on Mac

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## To Reproduce

`yarn global add docusaurus`

## Actual Behavior

I got following output

![image](https://user-images.githubusercontent.com/11704747/49563943-f39dcf00-f947-11e8-9c6f-99c3fb974549.png)

**Comment by endiliey** [comment]
this is due to : https://blog.npmjs.org/post/180565383195/details-about-the-event-stream-incident

to solve the issue, add the following to your package.json file :



```
  "resolutions": {
    "**/event-stream": "^4.0.1"
  }
```
