### ISSUE TITLE
Embedding videos into markdown or pages or blogs

### ISSUE THREAD

**Issue by amimas** [facebook/Docusaurus#1165]
## 🚀 Embeddable video

Since Markdown format doesn't yet support video format, It would be a really nice feature if Docusaurus could support embedding videos. Right now, I'm trying to embed a YouTube video to the homepage (`index.js`), but there isn't any straight-forward way of doing that as far as I've seen. I think this could be useful even in the Markdown files that are used for serving documentations.

## Have you read the [Contributing Guidelines on issues](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## Motivation

You can use a short video in the home page for introduction or other promotional pitches. Sometimes a video of certain task is much easier to follow than reading through a lot of steps in a documentation. So, being able to embed a video would be a good addition to this tool.

## Pitch

This feature could probably be somehow implemented if the following existing feature request is implemented which would embedding react components into markdown. I haven't searched yet, but I'm sure there are components available that can show video from an external source. 

https://github.com/facebook/Docusaurus/issues/489

Not sure how this is going to work in other areas (i.e. pages, blog, etc.). If Docusaurus can provide a way of embedding video that can be used everywhere it would be really good.

**Comment by endiliey** [comment]
this can be done easily if react component can be embedded in markdown. 

The good news is this is super easy in v2, the bad news is we wont implement it in v1 for now due to architecture constraint. 

i will be closing this issue since #489 has a similar nature

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by mx3coding** [comment]
I stumble with this issue recently, if someone needs help to add a video try this: https://stackoverflow.com/a/69193176/5734097
