### ISSUE TITLE
Documentation for "core" layout components

### ISSUE THREAD

**Issue by alexkrolick** [facebook/Docusaurus#1167]
## 📚 Documentation

The default `index.js` uses several layout components from the hidden "core" folder. It would be nice to have a better guide on what these components are and what props they accept.

For example, I'd like to know if the GridLayout can center an image while keeping the text in the opposite grid left-aligned.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

yes

**Comment by amimas** [comment]
There are some info available in the following page of the docs.

https://docusaurus.io/docs/en/api-pages#provided-components

I think it'd be more useful if they are posted as separate page

**Comment by JoelMarcey** [comment]
Definitely willing to look at a PR to make the docs more useful here.

**Comment by endiliey** [comment]
Closing due to stale activity. It's not really a high priority issue as well. Bugs are more prioritized in the issue tracker.

If anyone wanted to send PR for the documentation, welcome :)
