### ISSUE TITLE
More generic default project

### ISSUE THREAD

**Issue by alexkrolick** [facebook/Docusaurus#1172]
## 🚀 Feature

The default examples contain lots of inline paths to things like `/img/docusaurus.svg` which have to be manually replaced. It would be easier to get up and running if the places where a default image like the project logo are likely to be used referenced either a config variable or a more generic path like `/img/logo-large.png`.

There are also a few Facebook branding things like the FB Open Source logo which have to be deleted 90% of the time.

## Have you read the [Contributing Guidelines on issues](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

yes

## Motivation

To make it less tedious to customize the homepage, footer, etc.

**Comment by tanaypratap** [comment]
I think this can help docusaurus to be used by more and more people. I would like to take this up. Please assign if you(@endiliey ) feel a PR to this issue can be merged.

**Comment by endiliey** [comment]
Sure @tanaypratap, feel free to take this up. We are definitely accepting for this kind of PR.

Few reasons:
1. Its not breaking anything
2. All the motivation above.

**Comment by tanaypratap** [comment]
That's cool. Expect the PR anytime next week. You can assign it to me or set assigned tag on it. I had to go through so many `good first issue` to find an issue which no one is working on.

**Comment by endiliey** [comment]
Still working on it @tanaypratap ? By the way let's move to https://github.com/facebook/Docusaurus/issues/1196

It seems to be related. Generic (no branded) default project
