### ISSUE TITLE
Document PrismJS theming

### ISSUE THREAD

**Issue by alexkrolick** [facebook/Docusaurus#1173]
## 📚 Documentation

Hihglight.js hasn't made progress on support for JSX in over two years, so a lot React-based projects will need to use Prism for highlighting instead. It seems like Prism understands the `highlight.theme` config option but it's unclear where it gets its themes - they don't have the same names as the Highlight.js ones except in a few cases like "default", and even then they look different.

```js
{
  // Highlight.js doesn't work well with JSX
  // pass an array of languages to use Prism, or true for all
  // usePrism: ['jsx'],
  usePrism: true,

  highlight: {
    // Highlight.js theme to use for syntax highlighting in code blocks.
    // Need to pass a value here that also works with Prism
    // theme: 'gruvbox-dark',
    theme: "default",
    defaultLang: "javascript"
  },
}
```

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

**Comment by endiliey** [comment]
In v1 we don't really use prismjs themes. It's a default prismjs css with hljs theme.

Understand that it's kinda weird, but had to do it because we want to support both syntax highlighting at v1 back then. The theme files might clash
