### ISSUE TITLE
Docs sidebar should be configuration less

### ISSUE THREAD

**Issue by solo474** [facebook/Docusaurus#1178]
## 🚀 Feature

In a simple case, docs sidebar should to derived without the sidebars.json configuration file. by following a convention on directory structure and file naming.  

## Have you read the [Contributing Guidelines on issues](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

(Write your answer here.)

## Motivation

Reduce the configuration required. Allow users to add a documentation page without touching multiple files. 

## Pitch

if docs property is not present in sidebars.json then assume each directory inside a docs folder is a category and each folder contain files in PascalCase so `pascal-case` will be URL slug. and `Pascal Case` will be a title.

**Comment by yangshun** [comment]
This approach involves quite a big of magic (reminds me of Rails) which makes Docusaurus usage less obvious and becomes harder to understand. I think being explicit is better. 

Another issue with this approach is the ordering of the files within a category. How would you define the ordering if you don't have the `sidebars.json`? Alphabetical ordering is usually not what users will want.

**Comment by endiliey** [comment]
Remind me of webpack. Too much configuration. I think this is quite a good idea, but definitely not a high priority for now (we should focus on v2 :( )

If anyone want to implement this, we’ll be happy
