### ISSUE TITLE
Save Page to Disk Option

### ISSUE THREAD

**Issue by JoelMarcey** [facebook/Docusaurus#1194]
## 🚀 Feature

Have the ability to save a page locally to a disk.

## Have you read the [Contributing Guidelines on issues](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## Motivation

via @jordwalke

Useful for reading offline.

## Pitch

Sometimes you know you will not have access to a network (e.g., plane) and would like to read some docs still

**Comment by amimas** [comment]
I *think* using service worker and making the site/app PWA compliant will achieve this.

**Comment by amimas** [comment]
@JoelMarcey - I think this is duplicate of #458. Would you agree?

**Comment by JoelMarcey** [comment]
@amimas - you are right 👍 Sometimes I lose track of which issues have been filed 😄
