### ISSUE TITLE
Missing doc on managing sidebar when translation is enabled

### ISSUE THREAD

**Issue by amimas** [facebook/Docusaurus#1197]
## 📚 Documentation

I've enabled translation on a site and I can browse to different locales of docs from `/website/translated_docs/<locale>/` directory. Although I have the contents translated, the sidebar remains in English.

Maybe it's a bug or missing feature, but based on the doc, I could find information on how to get the sidebar translation. I think there should be different copies of `sidebar.json` for each locales similar to **versioned docs**, but I'm not sure what the current mechanism is.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

**Comment by amimas** [comment]
I may have found out what I need to do to get the sidebar translated. I believe I will need to use `sidebar_label` in the front-matter of markdown files and have that value translated for translated files. I haven't tried it yet, but I think this should resolve it. It just wasn't clear from the documentation on what should be done.

**Comment by endiliey** [comment]
I am assuming you are not using Crowdin, (in which we recommend and suggest). The sidebar translation is done via `.json` file. Example: if you are using a chinese language/ `zh-CN`, crowdin-download will pull out a `zh-CN.json`.

You can look at this as an example https://github.com/loomnetwork/loom-sdk-documentation/tree/master/website/i18n

**Comment by amimas** [comment]
You're right. I'm not using Crowdin. I personally do like it but I don't think it's free (please correct me if I'm wrong). I think we need a little bit more flexibility with translation so that we can manage translation even without crowdin.

I thought I had raised a feature request for this, but can't seem to find it now.

**Comment by endiliey** [comment]
From my understanding, crowdin is free only for open source project. Well, technically not using crowdin is possible, but the user need vast understanding of how docusaurus v1 works. I strongly does not recommend managing translation without crowdin in the current version.

I was on leave up until recently, but I'll keep this in mind when we're developing v2 to allow user managing translation without crowdin

**Comment by JoelMarcey** [comment]
Yes, Crowdin is free for open source projects, which is part of the reason why we chose them as a partner for Docusaurus. https://crowdin.com/page/open-source-project-setup-request
