### ISSUE TITLE
Enhance error message for build failures

### ISSUE THREAD

**Issue by amimas** [facebook/docusaurus#1198]
## 🚀 Useful details for errors for failures

I had commented out couple of mandatory fields in `siteConfig.js`. For example, I skipped `projectName` and `organizationName` because I hadn't setup the remote git repository yet.

Although the site was working fine on the dev server, I could not build the site. I kept getting an error like this:

```
yarn run v1.12.3
warning package.json: No license field
$ docusaurus-build
generate.js triggered...
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at assertPath (path.js:39:11)
    at join (path.js:1152:7)
    at join (/Users/.../doc-site/website/node_modules/docusaurus/lib/server/generate.js:68:20)
    at tryCatch (/Users/.../doc-site/website/node_modules/regenerator-runtime/runtime.js:62:40)
    at Generator.invoke [as _invoke] (/Users/.../doc-site/website/node_modules/regenerator-runtime/runtime.js:288:22)
    at Generator.prototype.(anonymous function) [as next] (/Users/.../doc-site/website/node_modules/regenerator-runtime/runtime.js:114:21)
    at asyncGeneratorStep (/Users/.../doc-site/website/node_modules/docusaurus/lib/server/generate.js:3:103)
    at _next (/Users/.../doc-site/website/node_modules/docusaurus/lib/server/generate.js:5:194)
    at /Users/.../doc-site/website/node_modules/docusaurus/lib/server/generate.js:5:364
    at new Promise (<anonymous>)
error Command failed with exit code 1.
```

After a lot of debugging, I found the root cause and I enabled those 2 mandatory fields with dummy data. Then I was able to build the site locally.

## Have you read the [Contributing Guidelines on issues](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## Motivation

The error message is not very useful and it's difficult to know what cause the failure. We could probably organize the contents in `siteConfig.js` a little bit better too so that it's clear what's mandatory and what's not. However, the important thing is end user can always make mistakes. That's why the error messages need to be user-friendly and tell us why certain line failed to execute.

## Pitch

This will improve developer experience in case they make silly mistakes somewhere and will also save a lot of time.

**Comment by dhuber23b** [comment]
A related problem with error messages occurs if there is an error in one of the js files needed to run the local server.  

I accidentally introduced a syntax error into help.js.  Here is the error message that I got:

$ yarn start
yarn run v1.12.3
warning package.json: No license field
$ docusaurus-start
LiveReload server started on port 35729
Failed to start Docusaurus server: SyntaxError: Unexpected token (38:2)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

It would be better if the filename of the offending error were listed in the error message.

**Comment by FabianTe** [comment]
This happened for me too. The error message should me more clear

**Comment by endiliey** [comment]
I think this issue is very open ended (errors could always appear at certain place and so on).
Instead of keeping this issue open, we'll gradually accept PRs to enhance the error message better.

We will also try our best to enhance the error experience in v2.
