### ISSUE TITLE
Docusaurus v1.7.0 Fails to Build 

### ISSUE THREAD

**Issue by mrchess** [facebook/Docusaurus#1200]
## 🐛 Bug Report

Docusaurus fails to build.

## To Reproduce

```
$ mkdir test-docu
$ cd test-docu
$ npm install docusaurus
$ docusaurus-init
$ cd website
$ npm install
$ npm run build
```

## Expected behavior

It should build.

## Actual Behavior

```
> docusaurus-build

{ Error: Cannot find module 'imagemin'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:594:15)
    at Function.Module._load (internal/modules/cjs/loader.js:520:25)
    at Module.require (internal/modules/cjs/loader.js:650:17)
```

**Comment by jakebolam** [comment]
We're seeing this across all of our projects too:
https://github.com/tophat/yvm/issues/297 see the [build reference](https://circleci.com/gh/tophat/yvm/3018?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link)
https://github.com/tophat/RichTextView/issues/87
https://github.com/tophat/jenkins-timeline-plugin/issues/67
https://github.com/tophat/with-immutable-props-to-js/issues/42
https://github.com/tophat/codewatch/issues/98

**Comment by JoelMarcey** [comment]
https://github.com/facebook/Docusaurus/pull/1201 should fix the issue. I will get another release out with this fix in it.

**Comment by JoelMarcey** [comment]
https://github.com/facebook/Docusaurus/pull/1202

**Comment by JoelMarcey** [comment]
v1.7.1 published to npm - please let us know if is working now.

Closing this.

**Comment by JoelMarcey** [comment]
@mrchess Have you tried v1.7.1 to see if this issue was resolved?

**Comment by jakebolam** [comment]
Looking good for us now
