### ISSUE TITLE
Control Meta tags

### ISSUE THREAD

**Issue by iRoachie** [facebook/Docusaurus#1206]
Is it possible right now to add additional meta tags that affect **all pages**?

I'd like to set `og:image` that's different from the favicon/logo. 

I saw in the blog post for [v2](https://docusaurus.io/blog/2018/09/11/Towards-Docusaurus-2) that you use react helmet to set these internally. How might this be done that it would affect all pages (blog/docs included)

**Comment by endiliey** [comment]
Going to assume this is a question. The answer is **no, it's not possible right now on current version**

Gonna close this issue, if you want to file a feature request, please use this template 😄 

https://github.com/facebook/Docusaurus/issues/new/choose
