### ISSUE TITLE
Include CI publish instructions for Azure Pipelines in docs

### ISSUE THREAD

**Issue by kyldvs** [facebook/docusaurus#1208]
## 📚 Documentation

It would be nice if the instructions for publishing via CI included instructions for Azure Pipelines as well: https://docusaurus.io/docs/en/publishing#automating-deployments-using-continuous-integration

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

**Comment by thewhitewolf17** [comment]
I'm interested in contributing, could you give me more info?

**Comment by kristofferjalen** [comment]
Any updates?

**Comment by ayan-b** [comment]
I would like to work on this issue.

**Comment by slorber** [comment]
Thanks @ayan-b  for your PR

doc for v1 is done, but keep this issue open as it's not yet done for v2

**Comment by slorber** [comment]
FYI, we are going to clean up our existing Docusaurus docs deployment page in favor of a GitHub discussions category. 

This means your platform won't appear anymore on this page: https://docusaurus.io/docs/deployment

If you want your hosting / CI / CDN platform to remain documented for Docusaurus users, please submit an entry at: https://github.com/facebook/docusaurus/discussions/categories/deployment-platforms

This will be your responsibility to keep it up to date over time.
