### ISSUE TITLE
Live reload not working when changing the title of doc file

### ISSUE THREAD

**Issue by yangshun** [facebook/Docusaurus#1213]
## 🐛 Bug Report

https://stackoverflow.com/questions/53939348/live-reload-not-working-when-changing-the-title-of-doc-file

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## To Reproduce

Refer to SO post.

## Expected behavior

Refer to SO post.

## Actual Behavior

Refer to SO post.

## Reproducible Demo

Refer to SO post.

**Comment by mikeattara** [comment]
@yangshun I will take it on

**Comment by yangshun** [comment]
@mikeattara it's yours!

I've added an "issue: claimed" label so that others will know not to start work on the issue. If you change your mind about the issue, no worries! Just let me know so that I can remove the label and free it up for someone else to claim.

I'll check in with you periodically so that we can keep the task updated with the progress. 

Please do try to reproduce the error first. You might want to check out https://github.com/facebook/Docusaurus/issues/713 and see if it's similar.

**Comment by 0xc0d3r** [comment]
@yangshun @mikeattara Any update on this?

**Comment by saranshkataria** [comment]
I can pick it up if nobody else is working on it

**Comment by endiliey** [comment]
Anyone can work on this. Feel free to send PR 😉

**Comment by tusharf5** [comment]
Just submitted a PR for this @ [#1507](https://github.com/facebook/Docusaurus/pull/1507)
