### ISSUE TITLE
Language-specific Code Tabs (Code blocks) broke referenced links

### ISSUE THREAD

**Issue by bruno-alencar** [facebook/Docusaurus#1215]
## 🐛 Bug Report

Hi,

I'm using some referenced links and I've had a problem, to use the new feature Coding blocks.

Referenced markdown links:
![markdown-links-issue](https://user-images.githubusercontent.com/13769562/52080698-92792d00-257f-11e9-9f3c-b65428fa8501.png)

I've tried to use the Language-specific Code Tabs

![markdown-code-issue](https://user-images.githubusercontent.com/13769562/52080937-1d5a2780-2580-11e9-95f3-e8d8f621b5b1.png)

After that, my links have been broken.

![markdown-broken](https://user-images.githubusercontent.com/13769562/52082779-d3c00b80-2584-11e9-8031-88d3d162621d.png)

## To Reproduce
1. Add the example page on docusaurus docs

https://raw.githubusercontent.com/bruno-alencar/issue-docusaurus/master/test.md

2. Remove comments (DOCUSAURUS_CODE_TABS,  JavaScript, END_DOCUSAURUS_CODE_TABS)

and the link `[Link][test-link]` will work.

## Expected behavior

If you put directly the link without reference.

![expected](https://user-images.githubusercontent.com/13769562/52082480-061d3900-2584-11e9-90aa-e97256dcf5f4.png)

## Actual Behavior

If you put link code after the comment block, the links broke.

![error](https://user-images.githubusercontent.com/13769562/52082541-3533aa80-2584-11e9-8bdc-21179d7d99d1.png)

## Reproducible Demo

https://github.com/bruno-alencar/issue-docusaurus/blob/master/test.md

**Comment by cuddergambino** [comment]
I'm also getting the same issue.

Only way I've found to workaround (other than manually link all references) is to include the link reference before and after the code block.

Example:
```
[test-link]: https://github.com "Github page"

<!--DOCUSAURUS_CODE_TABS-->
<!--JavaScript-->
<!--END_DOCUSAURUS_CODE_TABS-->

[test-link]: https://github.com "Github page"

```

**Comment by blemelin** [comment]
Same here. I have multiple `DOCUSAURUS_CODE_TABS` section on the same doc. When I remove the last one, everything is fine.

**Comment by yangshun** [comment]
@fiennyangeln Do you have time to look into this?

**Comment by fiennyangeln** [comment]
I will take a look at it tonight 😄

**Comment by yangshun** [comment]
@cuddergambino I think as long as the link is above the code tab it is ok, so the link below the code tab can be removed, as @blemelin mentioned.
