### ISSUE TITLE
Consistent links based on `cleanUrl` setting

### ISSUE THREAD

**Issue by amimas** [facebook/Docusaurus#1218]
## 💥 Proposal

When `cleanUrl` setting is used, it works great but if this option is **not enabled**, every page shows ".html" at the end of the url. But, the "home" link (near the top-left corner of navigation bar) still points to the site url as "http://example.com/". Can it be made as "http://example.com/index.html" to be consistent? There might be similar links in the footer.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

**Comment by yangshun** [comment]
There was a similar issue and fix brought up here - #1146. Many sites that do not have clean URLs still have their logo link as the clean version. Example:

- https://reactjs.org/docs/getting-started.html
- http://docs.vulcanjs.org/nutshell.html

So we prefer to stick with this convention.

**Comment by amimas** [comment]
Thank you for your reply. I'm sorry I cannot yet follow the logic behind sticking with this convention.

Since there is a configuration for clean url, in my opinion its usage should be consistent. Also, as it was already explained in #1146, this is needed for the situations where directory listing/indexing is not supported or does not automatically redirect to `/index.html`. Here's my current issue.

I'm hosting the static site built using docusaurus, in aws s3 bucket. However, I needed to host it in a subdirectory of the bucket instead of at the root. If I enable website hosting option for the bucket, everything is okay but I cannot use ssl. I needed to use aws cloudfront cdn for effecient distribution and also ssl. Because the site is hosted in a subdirectory of the s3  bucket, automatic redirection to the `index.html` file of the site's root has been challenging (with and without the website hosting option at s3 bucket). As you know, aws s3 is not a traditional web server. So, currently in my doc site hosted in aws s3 and served by aws cloudfront, clicking on the site logo/title fails.

Anyways, besides my current issue, I believe current functuonality is somewhat inconcsistent with regards to the configuration option of the site.

**Comment by amimas** [comment]
> Many sites that do not have clean URLs still have their logo link as the clean version.

I just understood now what you meant here and why you want to stick with this convention.

I do see your point. I personally prefer to use the clean url but unfortunately I haven't been able to use it in my case because of the issues I encountered in aws s3. I believe this is one of the many popular choices for hosting static site.

**Comment by amimas** [comment]
Thought I'd add some updates here. I have been trying to add some work-around in aws based deployment. Just for clarification, this is not an issue if you deploy to the root of the s3 bucket. Aws Cloudfront (used as a cdn for s3 bucket as source) has a setting to default to `index.html` if the client requested a url without specifying it. But, this only works if you deploy/upload built static files to the root of your s3 bucket.

In my case, since I needed to deploy to subdirectories, I'm adding Lamda@Edge function to the cloudfront to handle this issue. So incoming requests are intercepted and redirected to `/index.html` file.

Thinking about this whole issue, even if you add `/index.html` to the logo href as I had suggested, it would solve or help avoid broken link when browsing within the site but there will still be an issue in another case. What if users point to the site without ending in `/`.

For example: http://example.com/docusaurus-site

In this case, 'docusaurus-site' is the subdirectory in s3 bucket that holds the static site. In this case, aws cloudfront will fail unless I take care of redirecting to following url using lamda function.

http://example.com/docusaurus-site/index.html

**Comment by endiliey** [comment]
This just caught my attention. Just read #1146 as well

I implemented the `cleanUrl` feature so I might be able to give more context on that. The backstory of `cleanUrl` setting is that we don't want to see any `.html` extension anymore. I think the convention here is slightly different.

**Comment by endiliey** [comment]
We will stick with current convention :)
