### ISSUE TITLE
Visual indication of external links

### ISSUE THREAD

**Issue by amimas** [facebook/Docusaurus#1219]
## 💥 Proposal

A visual indicator for each links that will open in new window. For an end user, it's a good experience to know that clicking on certain links will open up a new window.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

**Comment by endiliey** [comment]
Actually this can be done in Docusaurus easily just by overriding your docusaurus `custom.css`

For example

``` css
a{ color : blue }
a:[target=_blank]{ color : green}
```

You might prefer different color, but some people might not. I personally prefer not having any difference between link that open in a new tab or not. I just prefer it blue.
