### ISSUE TITLE
Large table of contents gets cut off

### ISSUE THREAD

**Issue by nmoinvaz** [facebook/Docusaurus#1220]
## 🐛 Bug Report

When you have a large table of contents with many items, some of them get cut off at the bottom of the page. A user visiting the site might not know there are additional items in the table of contents. 

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Sort of.

## To Reproduce

1. Create a markdown page that has lots of h1/h2 tags with different names. 
2. View the table of contents on the right hand side 
3. Scroll down in Chrome and view that some of them are cut off.

## Expected behavior

It should automatically show a scrollbar in the table of contents if there are too many items.

## Actual Behavior

The table of content items gets cut off. You are able to scroll it, if you place your mouse over the table of contents and use the mouse scroll wheel to scroll down. However, that is not transparent to the user that they can do that or that there are more items in the table of contents.

## Reproducible Demo

![image](https://user-images.githubusercontent.com/1364432/52319159-0e5ae700-297d-11e9-928b-53942fe7064f.png)

I have attached doc2.md in [doc2.zip](https://github.com/facebook/Docusaurus/files/2834770/doc2.zip). On the right of the table of contents you can see Test 4 items are missing.

## Possible Fix

I think max-height and overflow-y should added to toc-headings.

**Comment by akinariobi** [comment]
I'd like to work on this.

**Comment by yangshun** [comment]
@akinariobi it's yours!

I've added an "issue: claimed" label so that others will know not to start work on the issue. If you change your mind about the issue, no worries! Just let me know so that I can remove the label and free it up for someone else to claim.

I'll check in with you periodically so that we can keep the task updated with the progress.
