### ISSUE TITLE
npx docusaurus init error - No siteConfig.js file found

### ISSUE THREAD

**Issue by o-t-w** [facebook/Docusaurus#1222]
I ran `npx docusaurus init` and got the following messages:
```
  ✔ gifsicle pre-build test passed successfully
  ✔ jpegtran pre-build test passed successfully
  ✔ optipng pre-build test passed successfully
Error: No siteConfig.js file found in website folder!
```
When I do `ls` it shows that the directory is empty.

**Comment by amimas** [comment]
You have a typo/mistake in your command. It should be `npx docusaurus-init`. Notice the **-** (hyphen) in the command.

**Comment by yangshun** [comment]
Thanks @amimas for helping to debug!
