### ISSUE TITLE
I have trouble when publishing my website, it looks like the css is not working, please help me

### ISSUE THREAD

**Issue by miftahrahmat** [facebook/Docusaurus#1223]
## 📚 Documentation

(A clear and concise description of what the issue is.)

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

(Write your answer here.)

**Comment by yangshun** [comment]
@miftahrahmat Please, please read the contributing guidelines before creating an issue: https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues
