### ISSUE TITLE
Add setting to prevent publish script from deleting CNAME file

### ISSUE THREAD

**Issue by kyldvs** [facebook/Docusaurus#1226]
## 🚀 Feature

Add setting to prevent publish script from deleting CNAME (and potentially other) files.

## Have you read the [Contributing Guidelines on issues](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## Motivation

When setting up gh-pages with a custom domain name I need to add a CNAME file (It's also possible my website setup is wrong...but it works). Every time I publish the gh-pages gets completely rewritten and I have to add back the CNAME file in a separate commit. It would be nice if this didn't happen.

Here's an example where I keep having to add it back: https://github.com/facebookexperimental/reason-native/commits/gh-pages

## Pitch

Let's people use docusaurus with custom domains easier

**Comment by JoelMarcey** [comment]
Hmmm.. Here is `gh-pages` for Docusaurus - https://github.com/facebook/Docusaurus/tree/gh-pages

The CNAME file hasn't changed in a year.

I wonder if something is missing in the way you are running this.

cc @yangshun

**Comment by yangshun** [comment]
@kyldvs Try using the `cname` [field](https://docusaurus.io/docs/en/site-config.html#cname-string) in `siteConfig.js` rather than adding your own CNAME file. Difference being we'll generate the CNAME file for you during build and you don't have to provide your own file.

We do that for [Docusaurus](https://github.com/facebook/Docusaurus/blob/master/v1/website/siteConfig.js#L18).

That should help you do what you need.

**Comment by JoelMarcey** [comment]
Oh - I thought he was using that :) yeah, that should fix it

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by kyldvs** [comment]
Perfect I will try this. I would recommend adding a brief mention of this option to the "publishing your site docs" so it is more discoverable. Probably near the end of this section: https://docusaurus.io/docs/en/publishing#using-github-pages

Where custom domains are mentioned: "(but it can also be accessed via https://docusaurus.io/ because of a CNAME),"

**Comment by yangshun** [comment]
I'll do that. Thanks for the suggestion 😄
