### ISSUE TITLE
Prettier output for init script

### ISSUE THREAD

**Issue by JoelMarcey** [facebook/Docusaurus#123]
See internal Docusaurus post from @caabernathy

**Comment by endiliey** [comment]
I think this is closed by #665

I saw prettier init script when docusaurus-examples are executed
<img width="475" alt="ghjk" src="https://user-images.githubusercontent.com/17883920/41189560-526ced64-6c02-11e8-910a-06f0cb05b4bd.PNG">

**Comment by yangshun** [comment]
Yes, nice catch. Thanks!
