### ISSUE TITLE
Allow icon to be changed for navToggle

### ISSUE THREAD

**Issue by mrchess** [facebook/Docusaurus#1230]
## 🚀 Feature

Currently the `navToggle` is a 4-arrow icon. This causes confusion for a lot of my users as they are used to a more traditional hamburger icon. Everyone who I have showed the page to had no idea that is how you navigate, or see the table of contents.

## Have you read the [Contributing Guidelines on issues](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes.

## Motivation

To make Docsaurus page navigation more intuitive for the web.

## Pitch

It would just be more intuitive to navigate around.

**Comment by denismcdonald** [comment]
Yes, from my viewpoint, this is a major usability issue.
