### ISSUE TITLE
Support for customBuildPath in siteConfig.js

### ISSUE THREAD

**Issue by bennmapes** [facebook/Docusaurus#1232]
## 🚀 Feature

It would be convenient to include a `customBuildPath` (similar to the `customDocsPath`) property to the `siteConfig.js` file. This would allow developers to specify the build directory they want the site copied to.

## Motivation

The reason for this is that sometimes docusaurs will be nested inside a project and you might want to pull out the build files to a separate directory for build assets.

## Pitch

This feature would be an easy win that would prevent people having to build/run their own scripts to manage moving build assets.

**Comment by endiliey** [comment]
i prefer not having it on siteConfig as to not bloat it more. Maybe as a cli arg is better. Example: yarn build —outdir=buildPath



<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
