### ISSUE TITLE
AUTOGENERATED_TABLE_OF_CONTENTS does not work with translations

### ISSUE THREAD

**Issue by jakebolam** [facebook/Docusaurus#1234]
## 🐛 Bug Report

AUTOGENERATED_TABLE_OF_CONTENTS does not work with translations enabled

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?
Yes

## To Reproduce

1. Enable translations
1. Add a doc page with some h3
1. Add AUTOGENERATED_TABLE_OF_CONTENTS 

# Expected behavior
Generated for all languages

(Write what you thought would happen.)

## Actual Behavior

(Write what happened. Add screenshots, if applicable.)

## Reproducible Demo

(Paste the link to an example repo, including a `siteConfig.js`, and exact instructions to reproduce the issue.)

**Comment by jakebolam** [comment]
On phone will update description when on PC.

Here's an example: https://allcontributors.org/docs/ko/cli/usage#%EC%BD%94%EB%A9%98%EB%93%9C%EB%93%A4

**Comment by jakebolam** [comment]
Reported here https://github.com/all-contributors/all-contributors/issues/196

**Comment by jakebolam** [comment]
Also issue number 1234 :tada:

**Comment by jakebolam** [comment]
Looks like [`insertTOC`](https://github.com/facebook/Docusaurus/blob/487fd573e529b922cc7073879cc642af6b611ffc/v1/lib/server/docs.js#L108) needs to be called during [`write-translations`](https://github.com/facebook/Docusaurus/blob/487fd573e529b922cc7073879cc642af6b611ffc/v1/lib/write-translations.js#L59), but we can't write back to the same file 🤔 

I'm not sure of the best approach here. @yangshun any thoughts?

**Comment by endiliey** [comment]
Interesting bug happening on docusaurus own website 😄 

![image](https://user-images.githubusercontent.com/17883920/54473920-60631800-4819-11e9-9b50-d253f3cce815.png)

The cause is due to how crowdin deals with `<var>` string like `<TEST_WORD>`, `<AUTOTEST_STRING>`

`<AUTOGENERATED_TABLE_OF_CONTENTS>` somehow got transformed into its lowercase part `<autogenerated_table_of_contents>` and hence https://github.com/facebook/Docusaurus/blob/93e2b7dab3779f22eb08ef4cb8060945bf023945/v1/lib/core/toc.js#L60-L71 fails because it's **CASE SENSITIVE**

**Comment by vikrantsinghthakur** [comment]
Can I take this up as my first issue if no one else is already working on it?

**Comment by endiliey** [comment]
@vikrantsinghthakur yes 😄 Will be waiting for your PR

**Comment by vikrantsinghthakur** [comment]
@endiliey So I was thinking, as a solution for this bug, the insertTOC function should add table for lowercase token too(which we are getting from crowdin) in rawContent. Would that be a correct fix?

**Comment by jakebolam** [comment]
@vikrantsinghthakur put up the PR and I can test it?

**Comment by vikrantsinghthakur** [comment]
@jakebolam Thanks, done.

**Comment by endiliey** [comment]
This is now fixed on master branch. Unfortunately we're one step too late to release it along v1.7.3

![image](https://user-images.githubusercontent.com/17883920/54680451-d979ac80-4b44-11e9-8151-932646642140.png)

Probably v1.7.4 !
