### ISSUE TITLE
css break when hover algolia logo

### ISSUE THREAD

**Issue by sinchang** [facebook/Docusaurus#1239]
## 🐛 Bug Report

(A clear and concise description of what the bug is)

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

(Write your answer here.)

## To Reproduce

(Write your steps here:)

1. visit https://docusaurus.io/docs/en/installation
2. search anything 
3. hover algolia logo

## Expected behavior
show logo as usual

(Write what you thought would happen.)

## Actual Behavior
![image](https://user-images.githubusercontent.com/3297859/53152323-32aafa80-35f0-11e9-8a43-7d83c7dfcb60.png)

(Write what happened. Add screenshots, if applicable.)

## Reproducible Demo

(Paste the link to an example repo, including a `siteConfig.js`, and exact instructions to reproduce the issue.)

**Comment by jakebolam** [comment]
cc @s-pace

**Comment by jakebolam** [comment]
@sinchang I can't reproduce this on chrome here?:
<img width="1303" alt="screen shot 2019-02-21 at 8 30 55 pm" src="https://user-images.githubusercontent.com/3534236/53213619-a44a6f00-3617-11e9-8cdf-a747d3553d26.png">

**Comment by yangshun** [comment]
@jakebolam You have to hover over the "Search by Algolia" button/link at the bottom to see it.

**Comment by jakebolam** [comment]
Ahh yes, can reproduce!
<img width="1154" alt="screen shot 2019-02-21 at 8 38 04 pm" src="https://user-images.githubusercontent.com/3534236/53213908-a06b1c80-3618-11e9-892b-a862e97fb2ae.png">
