### ISSUE TITLE
Document how to find CSS elements to override

### ISSUE THREAD

**Issue by JoelMarcey** [facebook/Docusaurus#1246]
## 📚 Documentation

https://docusaurus.io/docs/en/api-pages#styles talks about overriding default styles with custom styles, but it does not mention where to go to look for the default styles.

They are in `main.css` which can be inspected in one of three places:

1. `website/node_modules/docusaurus/lib/static/css/main.css` after doing a `docusaurus-init` or `yarn install` to start developing your site.
2. https://github.com/facebook/Docusaurus/blob/master/v1/lib/static/css/main.css
3. Or you can use your browsers Developer Tools to inspect elements directly to see the name of what to override.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes. I helped write them 😄

**Comment by ael-mas** [comment]
I'm interested in working on this issue if it is still up for grabs.

**Comment by JoelMarcey** [comment]
Thanks @ael-mas.

We've added an `issue: claimed` label so that others will know not to start work on the issue. If you change your mind about the issue, no worries! Just let us know so that we can remove the label and free it up for someone else to claim.

We will check in with you periodically so that we can keep the task updated with the progress.

**Comment by yangshun** [comment]
Fixed in #1266
