### ISSUE TITLE
`npm install` throws error on `highlight.js`

### ISSUE THREAD

**Issue by JoelMarcey** [facebook/Docusaurus#1247]
## 🐛 Bug Report

`npm install` within a `website` directory throws an error around `highlight.js`. `yarn install` actually works.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## To Reproduce

(Write your steps here:)

1. `cd website`
1. `rm -rf node_modules`
1. `npm install`

## Expected behavior

Everything is all good so I can run `npm start`.

## Actual Behavior

```
[joelm@joelm-mbp:~/dev/redex-joel/website]  (master) $ npm install
npm WARN deprecated coffee-script@1.12.7: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@3.0.11: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm WARN deprecated minimatch@1.0.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated hoek@0.9.1: The major version is no longer supported. Please update to 4.x or newer
npm WARN website No repository field.
npm WARN website No license field.

npm ERR! path /Users/joelm/dev/redex-joel/website/node_modules/highlight.js/tools/build.js
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall chmod
npm ERR! enoent ENOENT: no such file or directory, chmod '/Users/joelm/dev/redex-joel/website/node_modules/highlight.js/tools/build.js'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/joelm/.npm/_logs/2019-02-25T23_21_29_309Z-debug.log
```

## Reproducible Demo

Clone https://github.com/facebook/redex and try `npm install` in the `website` directory there. I was using node v8.11.1.

**Comment by jpwain** [comment]
More information here: https://github.com/highlightjs/highlight.js/issues/1984

**Comment by JoelMarcey** [comment]
@jpwain Thank you!

**Comment by JoelMarcey** [comment]
This has been fixed in highlight.js. 

cc: @int3

**Comment by yangshun** [comment]
Thanks for the tip @jpwain! @JoelMarcey I think the problem should be non-existent as highlight js has published a new version and `npm install` will pick that up.

**Comment by JoelMarcey** [comment]
Yep - I tested again on Redex and it was fine.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
