### ISSUE TITLE
how to start the docusarus app permentely?

### ISSUE THREAD

**Issue by madhu6759** [facebook/Docusaurus#1248]
## 📚 Documentation

(A clear and concise description of what the issue is.)

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

(Write your answer here.)

**Comment by yangshun** [comment]
@madhu6759 Sorry, please describe the problem clearer by updating the description. Feel free to reopen.
