### ISSUE TITLE
BrowserslistError: Unknown browser query 'dead'

### ISSUE THREAD

**Issue by dfadev** [facebook/Docusaurus#1251]
## 🐛 Bug Report

Site fails to start due to dependency issue

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## To Reproduce

```bash
npx docusaurus-init && yarn --cwd website start
```

## Expected behavior

Site runs

## Actual Behavior

An exception is thrown:

```
BrowserslistError: Unknown browser query `dead`.
```

## Reproducible Demo

```bash
npx docusaurus-init && yarn --cwd website start
```

**Comment by yangshun** [comment]
@dfadev Did you figure out the issue? Mind providing some insight?

**Comment by dfadev** [comment]
No.  I wasn't able to repro on another machine.  Are you getting the same exception?

**Comment by sailor27** [comment]
Hi, I am having the same exception when running `npm start` in the website directory.

**Comment by julians300** [comment]
I am getting the same issue. Anyone have an idea why this is?
`BrowserslistError: Unknown browser query 'dead'`

**Comment by JoelMarcey** [comment]
Are you getting this issue only with `npm start`? Does `yarn start` work? I know that `yarn --cwd website start` was causing an issue. I am wondering if `cd website; yarn start` works?

**Comment by twhite96** [comment]
Getting the same error. `yarn start` and `npm start` give the same error.

**Comment by twhite96** [comment]
There is a `BroswerList` object in your `package.json` in the main part of whatever app your docs live in. I deleted that and got it to work. Try that and see if it works for you.

**Comment by JoelMarcey** [comment]
cc @yangshun @endiliey ^

**Comment by endiliey** [comment]
Is it correct to assume that this bug only occurs if your docusaurus app lives inside another app with another package.json ? 👍

**Comment by dfadev** [comment]
@twhite96 is correct, thank you! -- I am able to repro this on multiple machines by placing the following `package.json` in my home directory:

```
{
  "browserslist": [
    ">0.2%",
    "not dead",
    "not ie <= 11",
    "not op_mini all"
  ]
}
```

**Comment by dfadev** [comment]
Am closing this because according to [Browerslist docs](https://github.com/browserslist/browserslist#queries), it's the expected behavior to search for a `browerslist` key in `package.json` in current **and parent directories.**

You can resolve this error by adding a `browerslist` key to `website/package.json`.
