### ISSUE TITLE
Use a doc page as homepage

### ISSUE THREAD

**Issue by o-t-w** [facebook/Docusaurus#1253]
I do not require a landing page for my website. I would like the home page to be a page I have in the docs e.g. /docs/about/

My feature request (maybe it is already possible?) is to forego having the default homepage. 

This way the use can get directly at what they came for - the documentation. My site won't offer much else, so it seems logical to go straight there. I wouldn't even know what to put on the homepage.

**Comment by JoelMarcey** [comment]
This can be done. Other sites that use Docusaurus have done it. See:

https://docs.reactioncommerce.com/docs/intro.html

There are a couple of others on the users page - https://docusaurus.io/en/users

**Comment by JoelMarcey** [comment]
See the documentation for this here: https://docusaurus.io/docs/en/site-creation#docs-landing-page

**Comment by amimas** [comment]
> 
See the documentation for this here: https://docusaurus.io/docs/en/site-creation#docs-landing-page

I've used that example in one of my doc site also. I think it would be useful if we could simply have a configuration for it. For example, if we set `disableLandingPage: true` in the configuration, docusaurus will automatically generate the site with a `/index.html` that redirects to `/docs/index.html`.

Thoughts?

**Comment by yangshun** [comment]
@amimas We're prioritizing v2 work now and for v1 we will refrain from adding features and focus on doing bug fixes. I don't think this redirect is highly used so perhaps we should add it in v2 instead.

**Comment by amimas** [comment]
@yangshun completely agree. This isn't a priority for current version.

Btw, do you have any estimate on v2 release date? Not sure how much of the targetted features have been added to v2 already.

**Comment by yangshun** [comment]
> Btw, do you have any estimate on v2 release date?

Unfortunately it's not going as fast we would like it to be due to manpower constraints - one of our members is taking leave due to health, and I'm really swamped with my core work (Docusaurus is my side project). We hope to release a beta in the second half of the year. Follow the progress on the issue https://github.com/facebook/Docusaurus/issues/789

> Not sure how much of the targetted features have been added to v2 already.

I really should do better on providing visibility on it. We have a basic set of features live on https://munseo-preview.netlify.com/, but have yet to implement versioning and translations.

**Comment by grenade** [comment]
for anyone who experiences 404 errors using the index.html workaround described above, you can also modify `src/pages/index.js` to contain only a redirect instead of the landing page. eg:
```jsx
import React from 'react';
import  { Redirect } from 'react-router-dom';

export default function Home() {
  return <Redirect to='/docs/intro' />;
}
```

**Comment by sporritt** [comment]
^^^ This is a useful tip.  Just wanted to mention that I ran into an issue building the site with this exact snippet, as I have a custom base URL. In the resulting output I did not get `/mybaseurl/docs/into` but instead `/docs/intro`, which failed to load. So I removed the leading slash:

```
import React from 'react';
import  { Redirect } from 'react-router-dom';

export default function Home() {
  return <Redirect to='docs/intro' />;
}
```

**Comment by slorber** [comment]
Note: the above trick is not really a good solution, as the redirect will be "slow" (requires loading/hydrating React). 
A server redirect is always better than a heavy client-side redirect.

We have a "docs-only" to handle that specific usecase:
https://docusaurus.io/docs/docs-introduction#docs-only-mode

**Comment by sporritt** [comment]
Doesnt the docs only mode preclude the inclusion of other pages, though? Having a docs page as the landing page does not necessarily mean that you dont want pages such as the original index page, does it?

**Comment by symbolpunk** [comment]
@slorber is there any way to use [docs-only mode](https://docusaurus.io/docs/docs-introduction#docs-only-mode) while retaining a descriptive slug for the "landing page" doc?

I'd like to default a docs site to a particular doc (no landing page) while retaining a descriptive slug for SEO. `docs.foo.com` should redirect to `docs.foo.com/intro-somekeyword` and then other docs routes should look like `docs.foo.com/other-doc`. Is this possible?

**Comment by slorber** [comment]
@symbolpunk this is best achieved by a server redirect. GitHub Pages does not support it, but others usually do.
