### ISSUE TITLE
Warning: Each child in an array or iterator should have a unique "key" prop. when using Code Tabs

### ISSUE THREAD

**Issue by vieira** [facebook/Docusaurus#1255]
## 🐛 Bug Report

Getting a warning: Each child in an array or iterator should have a unique "key" prop. when opening a page that uses [Language-specific Code Tabs](https://docusaurus.io/docs/en/doc-markdown), version 1.7.2.

## To Reproduce

Note: In the example below I added some spaces between ` to avoid breaking the style. In the markdown file I am using there are no such spaces.

```markdown
<!--DOCUSAURUS_CODE_TABS-->
<!--JavaScript-->
` ` `js
// some js code
}
` ` `
<!--Python-->
` ` `python
# some python code
` ` `
<!--END_DOCUSAURUS_CODE_TABS-->
```

Run `docusaurus-start` and visit the page.

## Expected behavior

No warnings are printed in the console.

## Actual Behavior

The following warnings are logged:
```
$ docusaurus-start
LiveReload server started on port 35729
Docusaurus server started on port 3000
Warning: Each child in an array or iterator should have a unique "key" prop.

Check the top-level render call using <article>. See https://fb.me/react-warning-keys for more information.
    in MarkdownBlock
    in Doc
    in div
    in div
    in Container
    in div
    in div
    in body
    in html
    in Site
    in DocsLayout
Warning: Each child in an array or iterator should have a unique "key" prop.

Check the top-level render call using <div>. See https://fb.me/react-warning-keys for more information.
    in div
    in MarkdownBlock
    in article
    in div
    in Doc
    in div
    in div
    in Container
    in div
    in div
    in body
    in html
    in Site
    in DocsLayout
```

## Reproducible Demo

Problem can be seen in the `docs/webhooks/examples.html` and `docs/webhooks/start.html` pages.

* Public Repository: https://gitlab.com/guuru/devsite

**Comment by endiliey** [comment]
cc @fiennyangeln

**Comment by yangshun** [comment]
This should be quite an easy fix. Anyone is free to take it up 😄

**Comment by oneuptim** [comment]
@yangshun I'd like to scoop this one up!

**Comment by yangshun** [comment]
@oneuptim it's yours!

I've added an "issue: claimed" label so that others will know not to start work on the issue. If you change your mind about the issue, no worries! Just let me know so that I can remove the label and free it up for someone else to claim.

I'll check in with you periodically so that we can keep the task updated with the progress.

**Comment by oneuptim** [comment]
Sounds good! Thanks!
