### ISSUE TITLE
static asset images doesn't support versioning

### ISSUE THREAD

**Issue by sunpeinju** [facebook/Docusaurus#1257]
## 🐛 Bug Report

I have a document which need to display some images, which are put under 'docs/assets' folder, and reference in the .md file like `![sample](assets/image1.png)`. Just followed the ![guide](https://docusaurus.io/docs/en/doc-markdown.html#linking-to-images-and-other-assets)

Next, I want to create a new version of the document and need to use an updated version of the image. I executed `docusaurus-version` and old version .md files are backed up, but the 'docs/assets` folder isn't backed up to 'versioned_docs'. So two versions of md files reference to same one 'docs/assets' folder. I can't replace the image in the folder directly, since it impacts old document.

I think static assets of each version also need to be backed up by `docusaurus-version`. Current behavior looks like to be a bug.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

yes

## To Reproduce

(Write your steps here:)

1. put image under docs/assets folder
1. write md file to reference this image
1. run docusaurus-version to back up current version of documents
1. .md file is backed up, but the asset folder isn't.

## Expected behavior

(Write what you thought would happen.)

## Actual Behavior

(Write what happened. Add screenshots, if applicable.)

## Reproducible Demo

(Paste the link to an example repo, including a `siteConfig.js`, and exact instructions to reproduce the issue.)

**Comment by yangshun** [comment]
Unfortunately, this is one of the known limitations of versioning. We will address this fix in #789 when we rethink how we're implementing versions. You're welcome to send a patch for this bug 😄

**Comment by sunpeinju** [comment]
@yangshun thank you!

**Comment by ataft** [comment]
I see that versioning has been added to Docusaurus v2 now (https://v2.docusaurus.io/docs/versioning). However, it doesn't appear that this issue has been addressed.

Should this issue be re-opened?
