### ISSUE TITLE
OOTB Mermaid code block

### ISSUE THREAD

**Issue by amimas** [facebook/docusaurus#1258]
## 🚀 Feature

[mermaidjs](https://mermaidjs.github.io/) seems to be a pretty neat tool that allows drawing diagrams using markdown. It'd be nice if Docusaurus can be integrated with that.

## Have you read the [Contributing Guidelines on issues](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

yes

## Motivation

Most documentation needs to show diagrams. The current method involves using some external tool and then create an image (i.e. png, svg, jpg, etc). You'll need to manage those diagrams yourself separate from the content.

## Pitch

Draw diagrams in the markdown along with the actual content where they are going to be used. This will make it a lot easier to maintain document (contents + diagrams) all in one place.

**Comment by leonardfactory** [comment]
Non sure if the plugin is still updated but there is [remarkable-mermaid](https://github.com/Joe-Barber/remarkable-mermaid). I’m interested in this too but I haven’t found the time to test it

**Comment by endiliey** [comment]
Gonna state it here, this is best left to markdown parser plugins.

**Comment by hassanfarid** [comment]
This should be really good addition to support product technical documentation in Docusaurus.

**Comment by endiliey** [comment]
After much consideration, this is indeed best left to markdown plugin

https://github.com/temando/remark-mermaid on v2
and remarkable-mermaid on v1

**Comment by ntsd** [comment]
@endiliey anyone doing it yet? or I can help.

**Comment by ntsd** [comment]
@endiliey  

Hey did anyone did it yet?

Maybe I can help contribute?

**Comment by eugenenelou** [comment]
Hey did anyone did it on version 1?
remarkable-mermaid is not even on npm and I cannot make it work as is.

**Comment by ericfourrier** [comment]
any update on this ?

**Comment by 18dew** [comment]
Nope i dont think so any one has writen any code over this yet ...

**Comment by chmelevskij** [comment]
With the current version it's pretty straightforward to integrate:
```javascript
// siteConfig.js
    scripts: [
        'https://cdnjs.cloudflare.com/ajax/libs/mermaid/8.4.4/mermaid.min.js',
        '/init.js',
    ],
    markdownPlugins: [ (md) => {
        md.renderer.rules.fence_custom.mermaid = (tokens, idx, options, env, instance) => {
            return `<div class="mermaid">${tokens[idx].content}</div>`;
        };
    }],
```
Then in init simply
```javascript
/* eslint-disable */
window.addEventListener('load', function() {
    mermaid.initialize({startOnLoad:true});
});
```
Usage:
```
\`\`\`mermaid
graph TB
    a-->b'
\`\`\`
```

**Comment by bodiam** [comment]
Hi @chmelevskij , thanks for sharing. Is there any way to get this to work on Docusaurus 2?

**Comment by arganaphangquestian** [comment]
> Hi @chmelevskij , thanks for sharing. Is there any way to get this to work on Docusaurus 2?

Hy @bodiam , Here the code for v2
```
// docusaurus.config.js
{
....
scripts: [
    "https://cdnjs.cloudflare.com/ajax/libs/mermaid/8.4.4/mermaid.min.js",
    "/init.js"
  ],
....
}
```

```
// init.js
mermaid.initialize({startOnLoad: true});
```

```
// doc1.md
...

<div className="mermaid">
graph LR;
  A["Start"]-->B["Stop"];
</div>

...
```

**Comment by bodiam** [comment]
<img width="523" alt="image" src="https://user-images.githubusercontent.com/46468/76157313-3823a600-615b-11ea-888a-416521f91a59.png">

Thank you so much!! That's easier than I thought!

**Comment by mbykovskyy** [comment]
> After much consideration, this is indeed best left to markdown plugin
> 
> https://github.com/temando/remark-mermaid on v2
> and remarkable-mermaid on v1

@endiliey, is there away to specify a `data.destinationDir` on a currently processed MD vFile? Without such configuration `remark-mermaid` writes SVGs into the same directory as the MD file.

**Comment by tobyhede** [comment]
The component technique above doesn't seem to work with 2.0.0-alpha.56

**Comment by gasolin** [comment]
since mdx support react compoennt, in v2 import than write react component just works

```
import Mermaid from 'react-mermaid2';

<Mermaid chart={`
	graph LR;
		A-->B;
		B-->C;
		B-->D[plop lanflz eknlzeknfz];
`}/>
```

**Comment by papanito** [comment]
@ghost I did as suggested but it complains

```
Module not found: Can't resolve '@theme/Mermaid' in '/home/papanito/my-website/blog'./blog/2020-11-10-demo.md?truncated=true
Module not found: Can't resolve '@theme/Mermaid' in '/home/papanito/my-website/blog'./blog/2020-11-10-demo.md
Module not found: Can't resolve 'url-loader' in '/home/papanito/my-website/blog'./blog/2020-11-10-demo.md?truncated=true
Module not found: Can't resolve 'url-loader' in '/home/papanito/my-website/blog'
```

**Comment by lucaslz2020** [comment]
> > Hi @chmelevskij , thanks for sharing. Is there any way to get this to work on Docusaurus 2?
> 
> in v2, you can make your own Component an import it into your markdown.
> 
> 1. install mermaid `yarn add mermaid`
> 2. create file in your `src/theme/Mermaid.js`
> 3. Mermaid.js
> 
> ```js
> import React, { useEffect } from "react";
> import mermaid from "mermaid";
> 
> mermaid.initialize({
> 	startOnLoad: true
> });
> 
> const Mermaid = ({ chart }) => {
> 	useEffect(() => {
> 		mermaid.contentLoaded();
> 	}, []);
> 	return <div className="mermaid">{chart}</div>;
> };
> 
> export default Mermaid;
> ```
> 
> 1. doc1.md
> 
> ```lisp
> import Mermaid from '@theme/Mermaid';
> ...
> <Mermaid chart={`
> 	graph LR;
> 		A-->B;
> 		B-->C;
> 		B-->D[plop lanflz eknlzeknfz];
> `}/>
> ...
> ```

This way is still more troublesome

```mermaid
graph
A --> B
```

**Comment by sjwall** [comment]
I have taken the Mermaid component [example given above](https://github.com/facebook/docusaurus/issues/1258#issuecomment-894600014) and bundled it in a package [mdx-mermaid](https://www.npmjs.com/package/mdx-mermaid)

The package also includes a remark plugin so that it can be used with code blocks

There are setup instructions and examples [here](https://sjwall.github.io/mdx-mermaid/docs/intro/)

If you run into problems, please raise an issue on the [github repo](https://github.com/sjwall/mdx-mermaid/)

**Comment by slorber** [comment]
Thanks for creating a package @sjwall ! btw you can add it there: https://docusaurus.io/community/resources

**Comment by botteroxom** [comment]
> I have taken the Mermaid component [example given above](https://github.com/facebook/docusaurus/issues/1258#issuecomment-894600014) and bundled it in a package [mdx-mermaid](https://www.npmjs.com/package/mdx-mermaid)
> 
> The package also includes a remark plugin so that it can be used with code blocks
> 
> There are setup instructions and examples [here](https://sjwall.github.io/mdx-mermaid/docs/intro/)
> 
> If you run into problems, please raise an issue on the [github repo](https://github.com/sjwall/mdx-mermaid/)

@sjwall 
Is it possible to set the theme dark when it is used in docusaurus? In a way it would update when the theme is switched on the interface

**Comment by sjwall** [comment]
@botteroxom The enhancement to the plugin to follow the docusaurus theme is being tracked here https://github.com/sjwall/mdx-mermaid/issues/4

**Comment by SimenB** [comment]
Since GH is adding support natively (https://github.com/github/roadmap/issues/372), any chance of docusaurus having native support as well? Not a huge issue adding the above plugin of course, but more feature parity out of the box sounds like a win to me 😀

**Comment by wooorm** [comment]
Thanks for the ping. Will likely depend on how they do it.

With footnotes, they didn’t bother to update the GFM spec, but it’s a syntax extension to their parser, so it is a de-facto part of GFM.

I’m assuming that mermaid will be implemented at a different level, similar to say, syntax highlighting code. That’s not part of GFM, but part of what github.com does on their site.

So, likely, it’d would be a different project.

**Comment by slorber** [comment]
Thanks 👍 

Let's wait and see then ;)

**Comment by felipecrs** [comment]
It's live now:

https://github.blog/2022-02-14-include-diagrams-markdown-files-mermaid/

Native support for Mermaid in Docusaurus would be nice. :)

**Comment by Josh-Cena** [comment]
Has anyone experimented with [remark-mermaid](https://github.com/temando/remark-mermaid) and checked if it works with Docusaurus? Does it have to be built-in?

**Comment by Josh-Cena** [comment]
Going to re-open. I think it would be very helpful to have this out-of-the-box.

**Comment by Josh-Cena** [comment]
VS Code has also added support for Mermaid: https://twitter.com/mattbierner/status/1522003140777701376

Many Markdown renderers also support it. I see a general trend to make this available out-of-the-box. If anyone wants to try their hands at a remark plugin, PRs are welcome.

**Comment by sjwall** [comment]
@Josh-Cena I am looking at merging in mdx-mermaid, should hopefully have a PR together this week

**Comment by jpadams** [comment]
Super excited to see this land! Thanks for all of the hard work!

**Comment by jonit-dev** [comment]
docusaurus v3 has this implementation:

yarn add @docusaurus/theme-mermaid

then, in your docusaurus.config.ts

const config = {

  markdown: {
    mermaid: true,
  },
  themes: ['@docusaurus/theme-mermaid'],

... rest of the code

};

Now write down mermaid code normally as it is (no need to be .mdx)
