### ISSUE TITLE
`sidebar_label` and `title` is incorrect for the first doc after creating the initial version

### ISSUE THREAD

**Issue by amimas** [facebook/Docusaurus#1259]
## 🐛 Bug Report

I have multiple directories with markdown documents. After creating the initial version by running `yarn run version 1.0.0`, the very first page/doc has incorrect title and sidebar label.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## To Reproduce

(Write your steps here:)

1. Create multiple directories in `docs`
1. Each subdirectory has a `index.md` (including the root `docs` directory) file and each of them has `id: index` as the frontmatter yml value and set the `sidebar_label` and `title` to be different from each other
1. Configure your sidebar to show documents from each of those index files. The `docs/index.md` should be the first page

Everything should be working as expected at this point.

Now, create a new version by running `yarn run version 1.0.0`.

Now, the very first page of the doc has the title of the of the `index.md` file from one of the subdirectory that is configured as the first item in the sidebar. The `sidebar_label` is also changed accordingly. However, the contents of the pages are coming from `docs/index.md` as expected.

Checked the behaviour in latest docs (i.e. `docs/next/`) and that is working properly.

Checked the behaviour of other pages in latest version (i.e. `docs/`) and those seem to be accurate.

## Expected behavior

(Write what you thought would happen.)

The title and sidebar label of the first page of the docs for the versioned docs are accurate.

## Actual Behavior

(Write what happened. Add screenshots, if applicable.)

The first page has incorrect title and sidebar label

## Reproducible Demo

(Paste the link to an example repo, including a `siteConfig.js`, and exact instructions to reproduce the issue.)

https://github.com/amimas/docusaurus-1259

**Comment by amimas** [comment]
I've just created a reproducible demo. Link to the repo is: https://github.com/amimas/docusaurus-1259

After the new version was created, the sidebar for `/docs/` shows "A doc". But if you go to `/docs/next/`, you'll see that it says "Main Page". The contents are correct. Somehow the sidebar label and the title of the page in the "released version" of the doc is incorrect.

**Comment by amimas** [comment]
Thanks so much for the quick fix!! Can't wait to try it out.

**Comment by endiliey** [comment]
You can try it out locally. A very naive & easy way to test it out is to copy the changes https://github.com/facebook/Docusaurus/pull/1265/files into your node_modules/docusaurus
