### ISSUE TITLE
Code Tabs do not allow HMTL comments within code blocks

### ISSUE THREAD

**Issue by Glavin001** [facebook/Docusaurus#1260]
## 🐛 Bug Report

Language-specific Code Tabs creates a new tab for HTML comments within code blocks.

Related to:
- https://github.com/facebook/Docusaurus/issues/103
- https://github.com/facebook/Docusaurus/pull/1063 
- https://github.com/Unibeautify/website/pull/211

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## To Reproduce

1. Use the following Markdown: https://gist.github.com/Glavin001/88acfd445ecdd013b129a412fd180b75
2. Run Docusaurus and view page.

## Expected behavior

Should have `HTML` tab:

![image](https://user-images.githubusercontent.com/1885333/53770484-99b09500-3eb5-11e9-9b1b-3437d89df530.png)

## Actual Behavior

Should have `HTML` tab and **not** have a tab for the HTML comment:

![image](https://user-images.githubusercontent.com/1885333/53770323-0ecf9a80-3eb5-11e9-9876-1c7dbca2661e.png)

![image](https://user-images.githubusercontent.com/1885333/53770332-14c57b80-3eb5-11e9-8e71-287e868ea2a0.png)

## Reproducible Demo

See https://github.com/Unibeautify/website/pull/211#issuecomment-469108660

**Comment by fiennyangeln** [comment]
I think this is due to our syntax choice for the CodeTabs and can be fixed by changing the syntax. However, we need to think of what syntax to use such that it doesn't overlap with any language syntax. E.g adding DOCUSAURUS in the syntax?

**Comment by endiliey** [comment]
@fiennyangeln That's a very easy and clean fix. Another fix is to not include those on codeblocks as part of tab. 

Sometimes I wonder if these kind of feature should've best been left as a markdown parser plugin.

Wanna send a PR ? 😄

**Comment by yangshun** [comment]
I found a Remarkable plugin that does something similar - https://www.npmjs.com/package/remarkable-codegroup

**Comment by fiennyangeln** [comment]
yeah but it requires jQuery and bootstrap as mentioned [here](https://github.com/facebook/Docusaurus/pull/1249) and [here](https://github.com/lwhiteley/remarkable-codegroup#description) so idk if it's ok to use it. What do you all think?

**Comment by DiegoFelipe** [comment]
I'm not using comments in html but I got the same problem if I put a comment like this:

<!--- a comment ---!>

is a markdown file, docusaurus don't work anymore after this comment, If I remove the comment it works again.
