### ISSUE TITLE
Random selection of colors when using docusaurus-init

### ISSUE THREAD

**Issue by JoelMarcey** [facebook/Docusaurus#1269]
## 💥 Proposal

Right now we have one color patten when `docusaurus-init` is used. A green-ish color. How about we randomly select a color pattern? Either totally random or based on a set of good, visually appealing colors.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

**Comment by amimas** [comment]
I'm not so sure about random/different colour pattern. I'm just not seeing any value in that since everyone will most likely modify the `siteConfig.js` to use their own colour scheme.

**Comment by JoelMarcey** [comment]
It's not a high priority feature, for sure. Something that would be a nice to have, possibly. And also allow folks to dive into the codebase to learn about Docusaurus and implement something.

**Comment by murray-b** [comment]
Hi @JoelMarcey ! I'd like to take this one if possible. Looking to get my feet wet with open source contributions and this seems a good place to start :)

**Comment by yangshun** [comment]
@murray-b it's yours!

I've added an "issue: claimed" label so that others will know not to start work on the issue. If you change your mind about the issue, no worries! Just let me know so that I can remove the label and free it up for someone else to claim.

I'll check in with you periodically so that we can keep the task updated with the progress.

**Comment by murray-b** [comment]
Hey!

Thanks for letting me have this one.

I had a quick question actually. If I were to be making a change to the
examples/basics/siteConfig.js file in docusaurus-1.x, how do I go about
seeing those changes reflected when I try and run Docusaurus locally? I
tried running npm examples from within the website-1.x directory to recopy
all of the files, but it only added a few extra files and didn't update the
siteConfig.

Hopeully that made sense!

Enjoy the rest of your day,
Murray

**Comment by murray-b** [comment]
Considering ```primaryColor``` is used not only for the header background color (with a white text color), but also for buttons, sidebars, etc., the randomly selected color pattern should probably be limited only to a set of darker colors, correct?
