### ISSUE TITLE
Links to other documents in markdown files not resolved to html when versioning is enabled

### ISSUE THREAD

**Issue by parthpp** [facebook/Docusaurus#1271]
## 🐛 Bug Report

Links from one document in `docs` to the document in `docs` that are written in markdown syntax are not converted to html links when versioning is enabled.

Please refer to the following project and follow its readme to reproduce the bug : https://github.com/parthpp/Docusaurus-Broken-Links

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?
Yes

## Reproducible Demo

Please clone the following repository and follow the steps mentioned in its read me file to reproduce the bug :  https://github.com/parthpp/Docusaurus-Broken-Links

**Comment by parthpp** [comment]
I think the problem is due to the [`metadata.mdToHtml`](https://github.com/facebook/Docusaurus/blob/master/v1/lib/server/metadataUtils.js#L73-L75) file returning prematurely when the metadata has `metadata.original_id`. Since all the versioned documents will have `metadata.original_id`, but since the method returns prematurely mdToHtml will not have links from md to html for these versioned documents.
CC: @yangshun @endiliey

**Comment by endiliey** [comment]
Seems to be relative path problem on v1. This issue won't happen on v2. 

Easy workaround for your case now is to do it like this: (Refer it with the subdirectory)

```md
Please refer to [consumption](api/consumption.md).  
```

Fix is coming on #1281
