### ISSUE TITLE
Support for absolute customDocsPath 

### ISSUE THREAD

**Issue by frangio** [facebook/Docusaurus#1277]
Setting an absolute path as the `customDocsPath` doesn't work. This was unexpected to me as a user.

In many places `path.join` is being used (or even plain string concatenation), where I think `path.resolve` should be used, which would correctly work with an absolute path.

https://github.com/facebook/Docusaurus/blob/2da59ed4af381c905addabadac3aee7a0e45ef72/v1/lib/version.js#L118

**Comment by yangshun** [comment]
That's a good point. We're more mindful of this in v2 and do use `path.resolve()` where we are aware. 

Feel free to submit a PR to fix this in the meanwhile!

cc @endiliey

**Comment by vishnureddy17** [comment]
I would like to work on this.

**Comment by vishnureddy17** [comment]
Unfortunately, I have become busy recently and I will no longer be able to work on this issue. If anyone else wants to take it up, the information the open pull request might come in handy.

**Comment by AndrewMayer** [comment]
I'd be interested in working on this.

**Comment by yangshun** [comment]
@AndrewMayer thanks for your interest! But given the complexity of this task I think it wouldn't be worth the time and effort to implement this in v1. We're focusing our efforts on v2 instead now 😄

**Comment by endiliey** [comment]
Wontfix in v1. Done via CLI in v2
