### ISSUE TITLE
Code tabs break numbered lists and cannot be indented

### ISSUE THREAD

**Issue by emanic** [facebook/Docusaurus#1279]
## 🐛 Bug Report

I cannot currently nest the code tabs inside a numbered list. Normally, to nest something like a code block in a numbered list, you insert about three spaces in the Markdown. It shows up as an unnumbered paragraph in the HTML. Unfortunately, this does not work with Docusaurus and prevents use of the code tabs inside a numbered list. 

In addition, unindented code tabs break the autonumbered list.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes.

## To Reproduce

**Example #1:**

<pre><code>
1. Do this
&lt;!--DOCUSAURUS_CODE_TABS--&gt;
&lt;!--tab1--&gt;
```
some code
```
&lt;!--tab2--&gt;
```
some other code
```
&lt;!--END_DOCUSAURUS_CODE_TABS--&gt;
1. Do that
</code></pre>

**Example #2**

<pre><code>
1. Do this
   &lt;!--DOCUSAURUS_CODE_TABS--&gt;
   &lt;!--tab1--&gt;
   ```
   some code
   ```
   &lt;!--tab2--&gt;
   ```
   some other code
   ```
   &lt;!--END_DOCUSAURUS_CODE_TABS--&gt;
1. Do that
</code></pre>

## Expected behavior

**Example #1:** 
Expected "Do that" to be #2

**Example #2:** 
Expected code tabs to be properly indented and nested inside the numbered list.

## Actual Behavior

**Example #1:** 
"Do that" is #1
<img width="839" alt="Screen Shot 2019-03-13 at 10 45 58 AM" src="https://user-images.githubusercontent.com/9090088/54377233-fd6b5880-4641-11e9-80f8-fe6d08cf12d9.png">

**Example #2:** 
No code tabs, just two indented code blocks. 
<img width="807" alt="Screen Shot 2019-03-13 at 10 42 37 AM" src="https://user-images.githubusercontent.com/9090088/54377281-1247ec00-4642-11e9-9843-b163532f9815.png">

## Reproducible Demo

Sorry I cannot make a public repo for you right now. Our repo is private.

**Comment by jamesgeorge007** [comment]
@emanic @endiliey I would love to work on this :tada: I'm new here and am not that aware of the codebase. It would be great if you could throw light into what is to be done specifically (Preferably including code pointers) :clap:

**Comment by endiliey** [comment]
Hey awesome @jamesgeorge007 🎉, thank you for the interest. I'm sorry for the late response, sometimes I missed the notification.

I could point out where this code is. The logic is mainly here
https://github.com/facebook/Docusaurus/blob/866f66241b15f3a0b287010e25f5df39319610f8/packages/docusaurus-1.x/lib/core/Doc.js#L60-L82

There is also another bug issue related to it https://github.com/facebook/Docusaurus/issues/1260

**Comment by jamesgeorge007** [comment]
@endiliey It would be great if you could throw light on what is to be done specifically :smiley:

**Comment by jamesgeorge007** [comment]
@endiliey Also, what about having a `follow on twitter` badge within the `Readme` file. Your thoughts?

**Comment by jamesgeorge007** [comment]
@endiliey Can you nail it down throwing light on what is to be done specifically within the chunk of code as linked up above :thinking:

**Comment by jamesgeorge007** [comment]
@endiliey Can you nail it down throwing light on what is to be done specifically with the chunk of code :thinking:

**Comment by endiliey** [comment]
Technically you'd want to do something like https://github.com/facebook/Docusaurus/pull/1369 to fix this problem. I don't think #1369 address this yet, but you would want to fix the way we parse the code. 

I suggest working after that PR is merged

**Comment by zachbadgett** [comment]
I have an idea on how to fix this specific issue. We would have a different regex matching that checks for the indentation (can probably just add an optional group `(\t|\s{4})?`), if it matches that we pass a prop settings to the function that splits it indicating we started as an indent.

**Comment by endiliey** [comment]
#1369
