### ISSUE TITLE
Adding new item to sidebar of the `next` release shows the wrong "sidebar_label"

### ISSUE THREAD

**Issue by amimas** [facebook/Docusaurus#1295]
## 🐛 Bug Report

I am creating a new page in a docusaurus repository where versioning is enabled. I added a new page for the "next" release docs and want to include it in the sidebar. The new page does appear with proper content but the sidebar label is incorrect.

I currently running on version 1.7.3.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## To Reproduce

Make sure you are working on a docusaurus repository with versioning enabled

1. Create a new page under `/docs/` directory with proper front matter (i.e. `id`, `title`, `sidebar_label`)
1. Add the new page to the `website/sidebar.json` file

## Expected behavior

I expected to see the new page rendered in my dev server as well as the sidebar updated while previously released version docs are unchanged.

## Actual Behavior

The new page is rendered as html with proper title and contents. The sidebar has been updated but it has the wrong "label". It seems the sidebar label for this new page is using the "last" page's sidebar_label for that particular category

An example of the sidebar for the "released version" doc:

![image](https://user-images.githubusercontent.com/16211767/54771093-f6f95580-4bda-11e9-9eea-fa0ac02bb326.png)

An example of the sidebar for the "next release" docs. Notice that highlighted label is same as the last item in that same category.

![image](https://user-images.githubusercontent.com/16211767/54771106-fcef3680-4bda-11e9-9634-060dad563b44.png)

## Reproducible Demo

(Paste the link to an example repo, including a `siteConfig.js`, and exact instructions to reproduce the issue.)

Don't have reproducible demo/repo yet. I will try to prepare one and post back here.

**Comment by endiliey** [comment]
Reproducible repo will be nice

**Comment by amimas** [comment]
Agreed. I tried to reproduce it in a simple setup, but that was unsuccessful. I will try create a similar setup/config or doc structure where I ran into the issue.

**Comment by amimas** [comment]
I cannot seem to be able to reproduce this issue again. Closing it. Sorry for the noise.

**Comment by endiliey** [comment]
Sure. I suspect it could be because of live reload issue on v1. Sometimes when you add new document/ editing frontmatter and not restarting the server, this kind of bug can appear.

**Comment by amimas** [comment]
Thanks. I'll keep that in mind.
