### ISSUE TITLE
Incorrect anchor link including an underscore character

### ISSUE THREAD

**Issue by ybiquitous** [facebook/Docusaurus#1307]
## 🐛 Bug Report

When an underscore character (`_`) is included in an anchor link, Docusaurus converts the underscore to a hyphen (e.g. `#foo_bar` → `#foo-bar`).

This behavior is different from GitHub's one, so it's very confusing. 😓 

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes. 👍 

## To Reproduce

1. Run `git clone https://github.com/ybiquitous/docusaurus-sandbox` on your terminal.
1. Run `cd docusaurus-sandbox/website`.
1. Run `yarn install`.
1. Run `yarn run start`.
1. Open <http://localhost:3001/docs/doc1> page on your browser.
1. Click `foo_bar` link on the page.

## Expected behavior

Jump to the `#foo_bar` section.

## Actual Behavior

Not Jump to the `#foo_bar` section.

[![Image from Gyazo](https://i.gyazo.com/5b95072d438e1d2a33ddff59f1fce482.gif)](https://gyazo.com/5b95072d438e1d2a33ddff59f1fce482)

## Reproducible Demo

https://github.com/ybiquitous/docusaurus-sandbox

Environment:
- Node `10.15.3`
- Yarn `1.15.2`
- Docusaurus `1.7.3`

**Comment by ybiquitous** [comment]
Here is a GitHub's behavior:

[![Image from Gyazo](https://i.gyazo.com/e37de4dc469cc5f7b54739d6184d154f.gif)](https://gyazo.com/e37de4dc469cc5f7b54739d6184d154f)

I hope Docusaurus would behave as same. 🙏

**Comment by endiliey** [comment]
What a tricky bug !

I made some test of headings https://gist.github.com/endiliey/f5256045e80c1c10436c6bdfce9c5961
Seems that it replaces all special characters except `_` to `-`
Docusaurus only replaces all special characters to `-`

**Comment by ybiquitous** [comment]
Thank you so much for the quick fix! 😂
