### ISSUE TITLE
Generated Pages of different languages have different content

### ISSUE THREAD

**Issue by Keith-CY** [facebook/Docusaurus#1332]
## 🐛 Bug Report

The [generated page of en-US](https://github.com/cryptape/citahub-docs/blob/gh-pages/en-US/0.21/cita/system/amend/index.html) has content, but the [generated page of zh-CN](https://github.com/cryptape/citahub-docs/blob/gh-pages/zh-CN/0.21/cita/system/amend/index.html) doesn't.

And the source code of this document is [here](https://github.com/cryptape/citahub-docs/blob/master/docs/cita/system/amend.md)

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## To Reproduce

1. clone [this repo](https://github.com/cryptape/citahub-docs)
2. install dependencies
3. build the page
4. check the built pages in **build/citahub-docs/zh-CN/cita/system/amend/index.html**

## Expected behavior

The page mentioned above should have the same content as which located in **build/citahub-docs/en-US/cita/system/amend/index.html**.
[generated page of en-US](https://github.com/cryptape/citahub-docs/blob/gh-pages/en-US/0.21/cita/system/amend/index.html)

But obviously there are less content in the zh-CN document.
[generated page of zh-CN](https://github.com/cryptape/citahub-docs/blob/gh-pages/zh-CN/0.21/cita/system/amend/index.html)

## Reproducible Demo

[siteConfig.js](https://github.com/cryptape/citahub-docs/blob/master/website/siteConfig.js)

**Comment by endiliey** [comment]
@keith-CY

The crowdin downloded docs seems to be wrong due to configuration

Instead of
‘’’yaml
source: '/docs/**/*.md'
    translation: '/website/translated_docs/%locale%/%original_file_name%'
‘’’

it should be

‘’’yaml
source: '/docs/**/*.md'
    translation: '/website/translated_docs/%locale%/**/%original_file_name%'
‘’’

Otherwise the subdirectory files wont be supported and crowdin download wont get that file.

let me know if it works

**Comment by Keith-CY** [comment]
@endiliey Thank you and I'll have a try(this config confused me a long time too).

I've checked the source code and found something leading to this problem.

The [code here](https://github.com/facebook/Docusaurus/blob/master/packages/docusaurus-1.x/lib/server/docs.js#L136) takes <code>!metadata.permalink.includes(`${docsPart}en`)</code> as a condition.

In my case, the `docsPart` is empty, and unluckily the **id** is **amend**, which hits <code>en</code>. With them the **Redirect** Component is rendered by `renderToStaticMarkupWithDoctype`

Hope my analysis helps.

**Comment by endiliey** [comment]
I just checked through your repo. It seems that the lead problem is due to current version of Docusaurus not being able to set non-english language as default language. See #938 #586 

Apology for this !

However, the good news is that we are looking to fix this on the next major version. An overview can be seen at https://docusaurus.io/blog/2018/09/11/Towards-Docusaurus-2#translation
> For Docusaurus 2, we will not assume English is the default language

**Comment by Keith-CY** [comment]
Awesome, I will update once it's published.
