### ISSUE TITLE
Redux docs next page link not working

### ISSUE THREAD

**Issue by yangshun** [facebook/Docusaurus#1344]
## 🐛 Bug Report

Docusaurus generates a 404 link in Redux docs.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## To Reproduce

(Write your steps here:)

1. Go to https://redux.js.org/faq
1. Go to the bottom of the page and click on "General"

## Expected behavior

Go to the [General page](https://redux.js.org/faq/general).

(Write what you thought would happen.)

## Actual Behavior

404

## Reproducible Demo

Go to https://redux.js.org/faq

I think the problem is because the FAQ page has an ambiguous ID that is also a dir within `docs`. If I change the `FAQ.md` id to `faq-index` it'll be fine, but the URL will be ugly. Perhaps we should support a field to allow overriding of the URL, instead of just using the front matter id.

**Comment by alzaar** [comment]
Hey I am new to contributing on github. Can I take this issue ? Or is it taken?

**Comment by yangshun** [comment]
@alzaar it's yours!

I've added an "issue: claimed" label so that others will know not to start work on the issue. If you change your mind about the issue, no worries! Just let me know so that I can remove the label and free it up for someone else to claim.

I'll check in with you periodically so that we can keep the task updated with the progress.

**Comment by alzaar** [comment]
Thanks! Could explain a bit more about the issue? I cloned the repo and am messing around with the code to see how it works.

**Comment by yangshun** [comment]
Hi @alzaar, I didn't do too much investigation into the bug, but I wrote down what I think could be the cause at the bottom of the issue. Did you manage to reproduce the bug?

**Comment by alzaar** [comment]
I am going to work on it and see if I can find the bug. But I will keep you posted!

**Comment by joybhallaa** [comment]
@alzaar  are you working on this? If not I'll be happy to work on it.

**Comment by alzaar** [comment]
Hey @joybhallaa! Yes I am. I will let you know in case I am not able so you can work on it.

**Comment by joybhallaa** [comment]
@alzaar, okay! No problem!

**Comment by endiliey** [comment]
@alzaar, Still working on it ?

I'll free it up now for anyone else who wanted to work on it. Let me know if you are still working on it
