### ISSUE TITLE
Collapsible links under subcategories in sidebar

### ISSUE THREAD

**Issue by byq77** [facebook/Docusaurus#1352]
## 🚀 Feature

Would it be possible to make links under subcategories also collapsible like in case of categories in sidebar?

I would like the code:
```json
{
  "docs": {
    "Category 1": [
      {
        "type": "subcategory",
        "label": "Subcategory 1",
        "ids": [
          "link1",
          "link2"
        ]
      },
      {
        "type": "subcategory",
        "label": "Subcategory 2",
        "ids": [
          "link3",
          "link4"
        ]
      },
    ],
  }
}
```

to generate something like this:

```
Category 1         v
   Subcategory 1   v
      - link1
      - link2
   Subcategory 2   v
      - link3
      - link4
```

Now option `docsSideNavCollapsible: true` in `siteConfig.js` makes only links under categories collapsible.

**Comment by yangshun** [comment]
@bvq77 This will be available in v2. Example here - http://yangshun.im/infima/

**Comment by endiliey** [comment]
Wontfix in v1
