### ISSUE TITLE
wrong property type for separateCss

### ISSUE THREAD

**Issue by pkowaluk** [facebook/Docusaurus#1357]
## 📚 Documentation

In the docs for `siteConfig.js`, it says that `separateCss` takes a "string" argument, but it actually should be "array". You can verify by testing, or look at the `isSeparateCss()` function - the second argument is an array that is used in the `for` function below.

The `isSeparateCss()` function is called like this: `isSeparateCss(normalizedFile, siteConfig.separateCss)`, so the second argument is taken from `siteConfig`.

If you set `separateCss` with a "string" argument, it does not do anything.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

**Comment by yangshun** [comment]
Thanks @pkowaluk, would you like to submit a PR to fix it?
