### ISSUE TITLE
Black background on some browsers

### ISSUE THREAD

**Issue by HendrikMennen** [facebook/Docusaurus#1405]
## 🐛 Bug Report | No css background property by default

On some browsers (like the steam browser) the background is set to black if there is no background property in the css code.

This is what it looks like in steam browser:
![Steam browser](https://i.imgur.com/Qyxdqhg.png "Steam browser")

To fix this you can add "background: #FFF" to body in custom.css:
```css
body{
    background: #FFF;
}
```

After that it looks like it should.
![Chrome](https://i.imgur.com/01NpVjf.png "Chrome")

This issue exists on many docusaurus websites even the official docusaurus.io.

**Comment by prayeo** [comment]
good 👍

**Comment by NishealJ** [comment]
Hi, anyone working on this ?

**Comment by yangshun** [comment]
@NishealJ if you're interested, it's yours!
