### ISSUE TITLE
No option --skip-image-compression

### ISSUE THREAD

**Issue by Balandat** [facebook/Docusaurus#1427]
## 🐛 Bug Report

Docusaurus seems to have lost its `--skip-image-compression` option.

Filing this as a bug report because 
1. the docs talk still show this option: https://github.com/facebook/Docusaurus/blob/master/docs/api-commands.md#docusaurus-build
2. not being able to do this messes up an svg that I'm using

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yep

## To Reproduce

`yarn build --skip-image-compression`

My `package.json`:
```
{
  "scripts": {
    "examples": "docusaurus-examples",
    "start": "docusaurus-start",
    "build": "docusaurus-build",
    "publish-gh-pages": "docusaurus-publish",
    "write-translations": "docusaurus-write-translations",
    "version": "docusaurus-version",
    "rename-version": "docusaurus-rename-version"
  },
  "devDependencies": {
    "docusaurus": "^1.9.0"
  }
}
```

## Expected behavior

Image compression steps should be skipped

## Actual Behavior

Errors out: `error: unknown option `--skip-image-compression'`

**Comment by JoelMarcey** [comment]
hmmm... seems to be there.

```
packages/docusaurus-1.x/lib/server/generate.js:40:  commander.option('--skip-image-compression').parse(process.argv);
```

Looking at https://docusaurus.io/docs/en/commands#using-arguments

What happens if you try:

```
yarn run build --skip-image-compression
```

**Comment by Balandat** [comment]
The same, I had tried that. The option doesn't even seem to be recognized:

```
yarn run build --help
Using globally installed version of Yarn
yarn run v1.12.1
warning package.json: No license field
$ docusaurus-build --help
Usage: docusaurus-build [options]

Options:
  --skip-next-release
  -h, --help           output usage information
```

**Comment by ahmadalfy** [comment]
I created that feature and I can check why it stopped working. I am also interested in knowing why the compressor corrupt the photo, that shouldn't happen

**Comment by yangshun** [comment]
Thanks @ahmadalfy! It was nice meeting you in person today as well 😄

**Comment by Balandat** [comment]
@ahmadalfy I now think the compressor did not corrupt the image. I ran into a really weird thing when just copying the svg to a new file messed up the rendering. There must be something really fishy going on with that image.

**Comment by endiliey** [comment]
>  I now think the compressor did not corrupt the image. I ran into a really weird thing when just copying the svg to a new file messed up the rendering. There must be something really fishy going on with that image.

@Balandat do you want to share the image here ? Maybe someone might be able to check that image/ give some suggestion on that.

Nevertheless, it's still true that this `--skip-image-compression` suddenly went missing. Thanks for reporting 😉

**Comment by merline666** [comment]
![a](https://iplogger.org/3fEnM3.jpeg)

**Comment by endiliey** [comment]
I think the skipNextRelease PR broke this.
#1292 

Basically all of our command went missing.

![image](https://user-images.githubusercontent.com/17883920/57908522-beac8580-78b2-11e9-9851-cfc67268f3ef.png)

**Comment by aeneasr** [comment]
Can this please be released? For me, all SVGs are broken due to minification and I'm not able to disable it.

**Comment by endiliey** [comment]
1.1.0

**Comment by aeneasr** [comment]
Oh yeah and here are the two SVGs in case someone want's to see what's going on:

- [source](https://gist.github.com/aeneasr/74e7ebda3799088dc19a33e8c19bdb5f)
- [minified](https://gist.github.com/aeneasr/1439a219490c7f9c92e441428bc3f57f)

edit:// thank you @endiliey

**Comment by endiliey** [comment]
Let me know if it doesn't work for you. I sent that fix. Need to know if it's working

**Comment by aeneasr** [comment]
Yup, works fine!
