### ISSUE TITLE
show f8 quick start video on how to use docusaurus

### ISSUE THREAD

**Issue by endiliey** [facebook/docusaurus#1433]
## 📚 Documentation

Some people might prefer a quick start video rather than reading the docs. 

@yangshun presented during F8
https://developers.facebook.com/videos/2019/using-docusaurus-to-create-open-source-websites/

We might be able to showcase it ? :O

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

**Comment by NishealJ** [comment]
Hi @yangshun , can we go ahead ? :D

**Comment by endiliey** [comment]
@NishealJ feel free to send the PR !
