### ISSUE TITLE
🌟 Help us feature more Docusaurus v1 users! (Part 2)

### ISSUE THREAD

**Issue by yangshun** [facebook/docusaurus#1437]
**Tip: This is a beginner level Docusaurus task that requires almost no coding and is more targeted at newcomers to the project and Open Source.**

## 📚 Documentation

We want to feature more Docusaurus users and we need your help!

*This is a follow up of https://github.com/facebook/Docusaurus/issues/1080 where we had around 20 new projects featured.*

Docusaurus has a [users page](https://docusaurus.io/en/users) where we showcase projects using Docusaurus. This has the benefits of giving projects recognition and also lets the community and new users reference the creative ways of using Docusaurus. For example, Babel implemented the "copy code" button which we copied into our code, Reason has a full-width doc page and Prettier has a playground.

Criteria for adding a project/user

- The project uses Docusaurus in creative ways/styling that looks different from the default
- The project has gained significant popularity (e.g: >500 stars on GitHub, or ~1,000 subscribers on reddit, etc)
- The project's Docusaurus website is already live

Here's a list of projects that we want to feature, in no particular order.

- [ ] [botpress/botpress](https://github.com/botpress/botpress)
- [ ] [webdriverio/webdriverio](https://github.com/webdriverio/webdriverio)
- [ ] [adazzle/react-data-grid](https://github.com/adazzle/react-data-grid)
- [ ] [kmagiera/react-native-gesture-handler](https://github.com/kmagiera/react-native-gesture-handler)
- [ ] [finos/perspective](https://github.com/finos/perspective)
- [ ] [apifytech/apify-js](https://github.com/apifytech/apify-js)
- [ ] https://github.com/wix/Detox
- [ ] https://github.com/twitchtv/twirp
- [ ] https://loonajs.com/
- [ ] https://microsoft.github.io/just
- [ ] https://github.com/almond-sh/almond
- [ ] https://github.com/lusakasa/sqorn
- [ ] https://github.com/tipsi/tipsi-stripe
- [ ] https://react-fns.netlify.com
- [ ] https://github.com/mbasso/asm-dom
- [ ] https://graphql-code-generator.com
- [x] https://nervjs.github.io/taro/ (@hongarc)
- [x] https://callstack.github.io/react-native-testing-library/ (@hongarc)
- [x] https://github.com/express-validator/express-validator (@hongarc)

The process of adding users goes like this:

1. Comment below with the project you're interested in helping and make sure it's not already claimed.
1. Check if the project has a logo. If it doesn't have a logo, we could ask them to create one. If not, then we can't feature it as we don't have a way to feature projects without logos at the moment. Sorry about that.
1. Make an issue on the GitHub project, asking about featuring their project on Docusaurus (most people would be okay with that).
1. Get a reasonable-sized version of their logo (SVG preferred) and add it to `website-1.x/static/img/users/<project-name-in-lower-snake-case>.{svg/png/jpg}` not exceeding 512x512. Look into their website directory or project directory for the logo image file. Try to compress the logo first if possible using Photoshop or some online tools.
1. Modify `website-1.x/data/users.js` and add the project into the JS file, sorted alphabetically by caption:

```
{
  caption: 'The Project Name',
  image: '/path/to/image',
  infoLink: 'www.example.com', // Website. Can be GitHub repo URL if website doesn't exist
  fbOpenSource: false,
  pinned: false,
},
```

4. Run the Docusaurus website locally and see that the users page loads fine and shows the new user!
1. Run `yarn lint` and `yarn prettier` before submitting the PR.
1. Use the PR title - `docs: showcase user <project name>`.
1. In the PR summary, add a link to the PR where you've asked the project for permissions to include their logo.
1. Submit your PR!

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

**Comment by Hongarc** [comment]
`react-native-testing-library` and `taro`
And you have 2 lines `graphql-code-generator.com`

**Comment by yangshun** [comment]
@Hongarc would you like to take over Express Validator? It has been approved.

**Comment by nickbui729** [comment]
Are there anymore projects that are up for grabs? First time contributor hear and would like to try one if any are up!

**Comment by endiliey** [comment]
> Are there anymore projects that are up for grabs? First time contributor hear and would like to try one if any are up!

I think the best way going forward for this issue is like this:

1. Find a popular project that use Docusaurus. We prefer **highly known** project or a docusaurus site with **lot of customization** (not just using default template)

You can try to find it in here: https://github.com/facebook/Docusaurus/network/dependents
There are 2,300+ public repositories on GitHub that installs docusaurus.
![image](https://user-images.githubusercontent.com/17883920/57930889-b02d9080-78e9-11e9-99ac-2d93378909f2.png)

1. Comment below with the project you're interested in helping and make sure it's not already claimed.
1. Follow the step above defined in the issue

Example: https://docs.openzeppelin.org/docs/get-started.html
You can send the PR for this @nickbui729

**Comment by joybhallaa** [comment]
Hey @yangshun , can I take the Just (https://microsoft.github.io/just/) library?

**Comment by yangshun** [comment]
@joybhallaa Yes go ahead

**Comment by joybhallaa** [comment]
Okay, thank you!

**Comment by Hongarc** [comment]
List recommend(I don't claim it):
- [reduxjs/redux-devtools](https://github.com/facebook/reduxjs/redux-devtools)
- [botpress/botpress](https://github.com/botpress/botpress)
- [OpenZeppelin/openzeppelin-solidity](https://github.com/OpenZeppelin/openzeppelin-solidity)
- [webdriverio/webdriverio](https://github.com/webdriverio/webdriverio)
- [umijs/umi](https://github.com/umijs/umi)
- [wix/Detox](https://github.com/wix/Detox)
- [adazzle/react-data-grid](https://github.com/adazzle/react-data-grid)
- [vincentriemer/react-native-dom](https://github.com/vincentriemer/react-native-dom)
- [Codeception/CodeceptJS](https://github.com/Codeception/CodeceptJS)
- [kmagiera/react-native-gesture-handler](https://github.com/kmagiera/react-native-gesture-handler)
- [mbasso/asm-dom](https://github.com/mbasso/asm-dom)
- [facebookresearch/Horizon](https://github.com/facebookresearch/Horizon)
- [finos/perspective](https://github.com/finos/perspective)
- [apifytech/apify-js](https://github.com/apifytech/apify-js)

**Comment by yangshun** [comment]
@Hongarc Thanks for the list! I noticed there are some in the list that do not really qualify because:

- They have Docusaurus in the repo but the site is not live (e.g. redux-devtools)
- Not using Docusaurus at all (e.g. facebookresearch/Horizon)

I'll make those criteria clearer in the issue. Can you help filter them out?

**Comment by ericbuss** [comment]
@Hongarc @yangshun I went ahead and filtered that list out. Some were duplicates, claimed already, or like mentioned, not live. I'll contact these projects about featuring them on Docusaurus as well.

-  [botpress/botpress](https://github.com/botpress/botpress)
-  [webdriverio/webdriverio](https://github.com/webdriverio/webdriverio)
-  [umijs/umi](https://github.com/umijs/umi)
-  [adazzle/react-data-grid](https://github.com/adazzle/react-data-grid)
-  [Codeception/CodeceptJS](https://github.com/Codeception/CodeceptJS)
-  [kmagiera/react-native-gesture-handler](https://github.com/kmagiera/react-native-gesture-handler)
-  [finos/perspective](https://github.com/finos/perspective)
-  [apifytech/apify-js](https://github.com/apifytech/apify-js)

**Comment by yangshun** [comment]
Nice work @ericbuss! Many thanks 😍

**Comment by co16353sidak** [comment]
> cc @co16353sidak who currently owns it.
> 
> @joybhallaa You can go ahead if @co16353sidak doesn't respond.

Sorry, been swamped with other work.
I have already submitted an issue onto just's repo for the necessities, they are yet to design (or decide on) a logo.

@yangshun I guess I never left the issue it is just on hold from the other end.
@joybhallaa let me sort this one out while you can take up another one.

(unless the mods think otherwise)

**Comment by steric85** [comment]
Hey! Can I take  https://graphql-code-generator.com/ ?

**Comment by Hongarc** [comment]
> Hey! Can I take https://graphql-code-generator.com/ ?

It has been approved in dotansimha/graphql-code-generator#1821

I think you can help @NishealJ to create PR.

**Comment by kenning** [comment]
I'm using docusaurus for a social media video game i'm making. It's a work in progress, but i'm planning on open-sourcing the code to allow the users to contribute. 

It's not going to have over 500 stars, but we have 2000 subscribers to our subreddit... https://reddit.com/r/collectivecg 

I thought it might be an interesting way for you to show that the project is versatile enough to be used for purposes other than open source software development. What do you think?

**Comment by endiliey** [comment]
@kenning it looks awesome. We’ll be happy to showcase it :)

**Comment by kenning** [comment]
Thanks!! I'll get back to you when it's done.

**Comment by kenning** [comment]
@endiliey We've put the site up, you can find it here: https://www.collective.gg/library/welcome/

There's a public github repo where people can make changes, it also has a good README to introduce the game and why it's on github: https://github.com/collectivecardgame/library

**Comment by endiliey** [comment]
send pr :) looks great

**Comment by kenning** [comment]
oh duh haha

**Comment by iamandrewluca** [comment]
https://vector.dev/
https://uniforms.tools/

https://github.com/facebook/docusaurus/issues/789#issuecomment-557779238

**Comment by yangshun** [comment]
Those are Docusaurus 2 sites and have already been added to the Docusaurus
2 showcase.

**Comment by Alquimista3301** [comment]
Hey! Can I take React data grid ? 🙂

**Comment by Hongarc** [comment]
> Hey! Can I take React data grid ? 🙂

@ericbuss take it https://github.com/adazzle/react-data-grid/issues/1687

We need wait to accept from `adazzle`

**Comment by Alquimista3301** [comment]
Hello I would like to support, what projects are available? 🖖

**Comment by yangshun** [comment]
Everything here is up for grabs :)

**Comment by hong4rc** [comment]
> Hello I would like to support, what projects are available? 🖖

You can use `gh-dependents` to know dependents project

```js
const gd = require('gh-dependents');
 
gd('facebook/docusaurus').then(console.log);
```

and check it has ready in user showcase

**Comment by yangshun** [comment]
As we're moving towards D2, we'd like to focus our efforts there and not make further changes to D1 website. Thanks everyone for their efforts thus far in adding D1 projects to our showcase!
