### ISSUE TITLE
Highlight table of content item based on sections being viewed

### ISSUE THREAD

**Issue by amimas** [facebook/Docusaurus#1448]
## 💥 Proposal

It's very useful if the table of content item is highlighted based on the section user is currently viewing or scrolling up/down a long page.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

**Comment by endiliey** [comment]
Lets move this to https://docusaurus-2.netlify.com/feedback/ to get more feedback !

Its also low priority for us as we are working on the next major version.
