### ISSUE TITLE
Heading doesn't check if content contains anchor when generating anchor link

### ISSUE THREAD

**Issue by pshrmn** [facebook/Docusaurus#1455]
## 🐛 Bug Report

When a heading contains an anchor tag (for specifying a custom hash), the anchor link generated by Docusaurus (in [this module](https://github.com/facebook/Docusaurus/blob/1edbeecbe565cbbbc0a6e6532c7c2d0c58d78807/packages/docusaurus-1.x/lib/core/anchors.js)) doesn't inherit the hash from the anchor tag. Instead, the generated hash includes the anchor tag's content (attributes included).

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## To Reproduce

(Write your steps here:)

1. Visit https://redux.js.org/api/store#dispatch
2. Hover over the chain SVG for the `dispatch` heading and the content jumps

![ohno](https://user-images.githubusercontent.com/1127037/57628499-ac9faf80-755f-11e9-88a0-9f160b43b630.gif)

The markdown for this file is here: https://github.com/reduxjs/redux/blob/master/docs/api/Store.md#dispatchaction

and the actual markdown looks like this:

```markdown
### <a id='dispatch' class='anchor'></a>[`dispatch(action)`](#dispatch)
```

## Expected behavior

The expected behavior is that the heading will see its child anchor and inherit the hash (`id`) from it instead of using its text content to generate the hash.

## Actual Behavior

The headings entire text content is used to generate the hash. For the above markdown, this results in the hash `a-id-dispatch-class-anchor-a-dispatchaction-dispatch`.

## Reproducible Demo

The issue exists on the [Redux](https://github.com/reduxjs/redux/tree/master/website) documentation site.

## Thoughts

I see that Docusaurus is working on v2 right now, so I'm not sure that making any changes to v1 is a priority. I believe that [this module](https://github.com/facebook/Docusaurus/blob/master/packages/docusaurus-mdx-loader/src/linkHeadings.js) is v2's equivalent for generating heading links. I haven't run the code, but it looks like v2 has the same issue.

I'm not actually sure if this is something that you want Docusaurus to look for, or if applications should avoid using anchors in headings. They allow for "prettier" hashes, but scanning for them might have weird edge cases, e.g.

```markdown
## <a id="uh">uh</a> <a id="oh">oh</a>
```

**Comment by endiliey** [comment]
```md
### <a id='dispatch' class='anchor'></a>[`dispatch(action)`](#dispatch)
```

To be honest, doing above is quite a weird behavior for me. 

If you want prettier hash, maybe do something like
```md
### `dispatch(action)`
```

wdyt ?

**Comment by pshrmn** [comment]
I agree that it is odd; I guess that the reason for it is to preserve hashes from a previous documentation builder. Moving the empty tag with the old hash to the line below should be good enough for preserving the old hash, so I think that Redux can handle this without any changes to Docusaurus.

As for a general solution, I think that the logic for having a heading search for an `id` to use is probably ripe with possible bugs, so it is probably better to not try than to have a half baked solution. For that reason, I'll go ahead and close the issue.
