### ISSUE TITLE
Table of content does not render special characters and anything in between them

### ISSUE THREAD

**Issue by amimas** [facebook/Docusaurus#1457]
## 🐛 Bug Report

I have some headers that has special characters ('<', '>'). Although the headers are rendered fine, the table of content does not render anything in between those characters.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## To Reproduce

(Write your steps here:)

1. Create a doc with header like this

    ```markdown
    ### `/<context>/status`
    ```

1. Start the dev server and check the table of content

## Expected behavior

Table of content should render that header as `/<context>/status`

(Write what you thought would happen.)

## Actual Behavior

Table of content renders the header as `//status`

![image](https://user-images.githubusercontent.com/16211767/57712630-ebf0fd80-763e-11e9-88a5-a45be05befab.png)

(Write what happened. Add screenshots, if applicable.)

## Reproducible Demo

I think this issue is clearly explained and straight-forward to be able to reproduce. If you still need me to create a separate repo with the issue reproduced, please let me know.

**Comment by amimas** [comment]
@endiliey - Thanks a lot for looking into this so quickly. Is there any chance that this bug fix can be released as version `1.9.1`? Not sure if there are any other bug fixes that can also be released at the same time. I could really use this particular fix right now.

**Comment by endiliey** [comment]
@amimas you can use 2.0.0-alpha.16 if you want temporarily. Available on `next` tag of `docusaurus` npm package.

Docusaurus 2 is published under separate package, `@docusaurus/core` so there won't be any breaking changes on that npm package.
