### ISSUE TITLE
Livereload not working on 1.10.0 build

### ISSUE THREAD

**Issue by Triskae** [facebook/Docusaurus#1508]
## 🐛 Bug Report

When I run wpm start (or even yarn start) the live reload server start but when I try to modify something inside the website folder, the page reloads but nothing is update. It seems like chnages on the files triggered the live reload but nothing is rebuilt.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## To Reproduce

1. npm install --global docusaurus-init
2. npm start inside the website folder

## Expected behavior

The server is suposed to start, and when I do changes inside the website folder, the webpage is suposed to reload with the new changes.
e.g When I change a label on the headerLinks section, changes are suposed to be visible.

## Actual Behavior

The server starts well, but when a modify something, the page relaod, but the changes are not visible. I need to CTRL+C the npm start process to restart it to see the changes.

## Reproducible Demo

You can try to reproduce the this issue on my repo: 
https://github.com/Triskae/Messosaurus

**Comment by endiliey** [comment]
That's due to #267 bug of siteconfig not being able to reload.

**Comment by Triskae** [comment]
Ok thanks, I saw that you fix this bug right ?

**Comment by endiliey** [comment]
yeah #1509

**Comment by malek0512** [comment]
Hello @endiliey Livereoload does not work on 1.14.4 version.
Was there any fix delivered for this issue ?
