### ISSUE TITLE
docusaurus-init does not copy examples correctly when using npm

### ISSUE THREAD

**Issue by kaicataldo** [facebook/Docusaurus#1515]
## 🐛 Bug Report

Hi! First off, thanks to the maintainers for this tool. I am in the process of trying to migrate an existing Jekyll site to Docusaurus and was following the [Installation instructions](https://docusaurus.io/docs/en/installation) in the Getting Started section of the site.

When Yarn is installed, it all works as described by the instructions. However, if Yarn isn't present (and I only use npm), `docusaurus-init` correctly works, but the npm script `examples` in `website/package.json` seems to be a no op. Manually running `npm run examples` exhibits the same behavior. Running `npx docusaurus-examples` or `./node_modules/.bin/docusaurus-examples` *does* work, however, and is the workaround I'm using.

This may be a bug in `npm` rather than Docusaurus (looking at the code, I don't see why it wouldn't work), but I thought I should report it in case others are running into it as well.

Node version: v12.3.1
npm version: 6.9.0

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## To Reproduce

Without Yarn installed (when Yarn is installed, it defaults to using Yarn for the underlying commands). Note that both the following sets of steps exhibit the same behavior:

1. `npm i -g docusaurus-init`
1. `mkdir test-site`
1. `cd test-site`
1. `docusaurus-init`

or

1. `mkdir test-site`
1. `cd test-site`
1. `npx docusaurus-init`

## Expected behavior

The `docusaurus-examples` script should copy the config files (listed in the docs [here](https://docusaurus.io/docs/en/installation#verifying-installation)):

```
root-directory
├── Dockerfile
├── README.md
├── docker-compose.yml
├── docs
│   ├── doc1.md
│   ├── doc2.md
│   ├── doc3.md
│   ├── exampledoc4.md
│   └── exampledoc5.md
└── website
    ├── blog
    │   ├── 2016-03-11-blog-post.md
    │   ├── 2017-04-10-blog-post-two.md
    │   ├── 2017-09-25-testing-rss.md
    │   ├── 2017-09-26-adding-rss.md
    │   └── 2017-10-24-new-version-1.0.0.md
    ├── core
    │   └── Footer.js
    ├── package.json
    ├── pages
    ├── sidebars.json
    ├── siteConfig.js
    └── static
```

## Actual Behavior

The following directory structure is created:

```
root-directory
└── website
    ├── node_modules/
    ├── package-lock.json
    └── package.json
```

## Reproducible Demo

Happy to create one, but I don't think it's particularly helpful in this case.

**Comment by kaicataldo** [comment]
Related (closed) issue: https://github.com/facebook/Docusaurus/issues/1330#issuecomment-494267617

**Comment by yangshun** [comment]
What OS are you on? Are you able to reproduce this issue on a different OS?

**Comment by kaicataldo** [comment]
Sorry, I should have mentioned that in the original post. This is on macOS 10.14.5. I also confirmed the same behavior on Ubuntu 19.04.

Upon further testing, it looks like this is actually because I have `ignore-scripts=true` in my `.npmrc`. I'll go ahead and close this issue (and sorry for not catching that sooner!). 

However it would be nice to not have to rely on running npm scripts under the hood (I know that creating programmatic APIs for all the underlying packages isn't trivial, though, and that this might not be doable right now).

Thanks again for working on this tool!
