### ISSUE TITLE
Show the moon-sun symbols on dark mode toggle

### ISSUE THREAD

**Issue by rosatamarindus** [facebook/Docusaurus#1523]
## 💥 Proposal

Docusaurus v2 has a new feature to switch dark and light mode. However, currently, the dark mode toggle uses the correct-wrong symbols instead of the moon-sun symbols. It's not good user experience. Therefore, it should change the symbols in order to be a more intuitive design.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

**Comment by endiliey** [comment]
open for contribution ? anyone can send a PR

**Comment by wgao19** [comment]
Hey @rosatamarindus I have a PR to change the toggle, let me know if you like it? 

And thanks for the proposal! Because we're all happier with emojis 🌞🌛
