### ISSUE TITLE
docusaurus opencollective reminder

### ISSUE THREAD

**Issue by endiliey** [facebook/Docusaurus#1527]
## Have you read the [Contributing Guidelines on issues](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## Motivation

Docusaurus has an opencollective at https://opencollective.com/docusaurus

It will be nice to remind people that we have such opencollective so that they can show some ❤️ to Docusaurus

With these fund, we can fund contributors, hire designers and improve Docusaurus

## Pitch

Something like this
![image](https://user-images.githubusercontent.com/17883920/58547474-ffed4f80-8239-11e9-8ec9-a4dc8c63c8b9.png)

https://www.npmjs.com/package/opencollective-postinstall can be useful

**Comment by jwandrews99** [comment]
I would be interested in doing this.  I'll see how i get on

**Comment by endiliey** [comment]
PR welcome 😉

**Comment by jwandrews99** [comment]
Pull request added

**Comment by endiliey** [comment]
With recent drama on core-js postinstall sponsoring and github sponsor button being available now.

Lets revisit this issue again in the future.
https://github.com/zloirock/core-js/issues/548
