### ISSUE TITLE
Sidebar on v2 website needs a background color

### ISSUE THREAD

**Issue by jaredpalmer** [facebook/Docusaurus#1530]
## 🐛 Bug Report

See screenshot. Using chrome latest.

<img width="1179" alt="Screenshot 2019-05-29 16 51 26" src="https://user-images.githubusercontent.com/4060187/58590424-0aa3e680-8232-11e9-9a00-0f0c906368a4.png">

**Comment by yangshun** [comment]
Thanks for the report Jared! While adding a background color works, it'll be more work to have it play nicely with dark mode and potentially a non-default background as well. Probably the better fix will be to tweak the CSS a `.sidebar` and remove the hardcoded `width: 20rem`. Will fix this!

**Comment by jaredpalmer** [comment]
Nice! My other suggestion would be to hide / move the secondary nav in the situation in the above screenshot

**Comment by yangshun** [comment]
Fixed in #1535 and #1562

**Comment by bhakti24-create** [comment]
How can add different background color for different sidebar. Suppose I have two navbar links. On one link click should show orange background color to sidebar and on another link click should show yellow background color to sidebar.
