### ISSUE TITLE
docs: handling-pull-requests link in CONTRIBUTING.md does not exist.

### ISSUE THREAD

**Issue by YoshinoriN** [facebook/Docusaurus#1544]
## 📚 Documentation

The [what to expect from maintainers](https://github.com/facebook/Docusaurus/blame/7ca66cb79e96d0dbe27b1d6da1dc15c322c5bb8a/CONTRIBUTING.md#L159) link in [CONTRIBUTING.md](https://github.com/facebook/Docusaurus/blob/7ca66cb79e96d0dbe27b1d6da1dc15c322c5bb8a/CONTRIBUTING.md#what-happens-next) does not exist. 

### Have you read the [Contributing Guidelines on issues]

Yes.

**Comment by yangshun** [comment]
Thanks for the issue. PR welcome!

**Comment by yangshun** [comment]
Fixed in https://github.com/facebook/Docusaurus/commit/9feb7b2c6422bfc2018e372d9debc2f3f1fdd54e
