### ISSUE TITLE
autogenerate table of contents for Docusaurus 2

### ISSUE THREAD

**Issue by endiliey** [facebook/Docusaurus#1549]
## Have you read the [Contributing Guidelines on issues](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

yes

## Motivation

In v1, we have `<AUTOGENERATED_TABLE_OF_CONTENTS>.` syntax that generates table of content for us

https://docusaurus.io/docs/en/doc-markdown#generating-table-of-contents

However, we haven't implemented it back in v2 because we use MDX instead of remarkable now. If anyone from the community is interested to work on this, PR is welcome.

## Requirement

1. Write a [remark plugins](https://github.com/remarkjs/remark/blob/master/doc/plugins.md) that convert `<AUTOGENERATED_TABLE_OF_CONTENTS>.` to a generated list of table of content
2. Add the remark plugins here: https://github.com/facebook/Docusaurus/tree/master/packages/docusaurus-mdx-loader/src
3. Add tests for it
4. Add that remark plugin to our jmdx-loader default remarkPlugins option
5. Test locally with v2 website that it can transform the syntax to autogenerated toc

Let's say this is our markdown file
```md
<AUTOGENERATED_TABLE_OF_CONTENTS>

### `docusaurus.function(a, b)`

Text describing my function

### `docdoc(file)`

Text describing my function
```

The remark manual test could be
```js
var vfile = require('to-vfile')
var remark = require('remark')
var toc = require('../path/to/your/remark/plugin')

remark()
  .use(toc)
  .process(vfile.readSync('example.md'), function(err, file) {
    if (err) throw err
    console.log(String(file))
  })
```

Result
```md
- `docusaurus.function(a, b)`
- `docdoc(file)`

### `docusaurus.function(a, b)`

Text describing my function

### `docdoc(file)`

Text describing my function
```

**Comment by yangshun** [comment]
Would recommend checking out MDX and see if they have first-class support for this - The [docs](https://mdxjs.com/guides/table-of-contents) is currently WIP but this might mean they've already built it out.

**Comment by endiliey** [comment]
but we still need custom plugin because our autogenerated_table_of_contents syntax is unique.

**Comment by yangshun** [comment]
We'll change our syntax then. It's not too big of a deal to search and replace. This is a major update after all.

**Comment by endiliey** [comment]
Checked their source code. They don't have it. They are just manually typing Table of Contents.

They recommend usinjg `remark-toc` which has a different behavior with our TOC

**Remark-toc**
```markdown
## Table of Contents

## Bravo

### Charlie

## Delta
```

become
```markdown
## Table of Contents

-   [Bravo](#bravo)

    -   [Charlie](#charlie)

-   [Delta](#delta)

## Bravo

### Charlie

## Delta
```

**Docusaurus**

```markdown
## Options
<AUTOGENERATED_TABLE_OF_CONTENTS>

## Bravo

### Charlie

## Delta
```

become

```markdown
## Options

-   [Bravo](#bravo)

    -   [Charlie](#charlie)

-   [Delta](#delta)

## Bravo

### Charlie

## Delta
```

I personally feel ours is more flexible because we can just write any headings we like, unlike remark-toc that has fixed "Table of contents" name. One good use is See https://jaredpalmer.com/formik/docs/api/withformik#options

![image](https://user-images.githubusercontent.com/17883920/59015124-d606df00-8870-11e9-9926-669707a1d085.png)

But its indeed wrong to mark this as difficulty:starter. I'm going to assign myself

It's also nicer to make it backward compatible as possible

**Comment by wgao19** [comment]
This is probably more suited for a future discussion, but would like to throw in an opinion that maybe we would like to consider the following two types of table of contents.

Hoping @endiliey to consider these use cases when designing the API :)))) So that we can implement those variations as themes in the future.

1. A book-style ToC on top of the main page like [RequireJS](https://requirejs.org/docs/jquery.html)

This will be useful when the page content is rather rich and each page is relatively separate with one another

![image](https://user-images.githubusercontent.com/2055384/59020866-66e3b780-887d-11e9-9415-28a99aa6a959.png)

2. Extend the sidebar like docz

This counts as ToC because the headers of the extended section are the headers from that page's content.

![image](https://user-images.githubusercontent.com/2055384/59021025-aad6bc80-887d-11e9-90ef-a73421c6ae86.png)

**Comment by endiliey** [comment]
Sorry for the confusion. We actually have two types of toc. One is the right side 
It generates table of content for the current  document

![image](https://user-images.githubusercontent.com/17883920/59025080-effeec80-8885-11e9-99ef-ce2994d0f753.png)

User can swizzle Docitem and modify it as their wish, you can show the table of contents on the left, bottom or even inside the page.

https://github.com/facebook/Docusaurus/blob/f0d5313d488fcb3264286ab46fdabdb2c92a88d8/packages/docusaurus-theme-classic/src/theme/DocItem/index.js#L56-L62

However this one is referring to another type of special syntax by Docusaurus. It is some kind of TOC, but more of a partial one.

This might explain better
![image](https://user-images.githubusercontent.com/17883920/59025303-73204280-8886-11e9-869a-63697ffdc4f8.png)

**Comment by amimas** [comment]
The overall TOC of the entire page on the right hand side is great!! I'd really love to see the ability to auto generate a partial TOC for a particular section only as shown by @endiliey in the above comment's last screenshot. I don't believe we can do that right now in V1.

**Comment by endiliey** [comment]
@amimas actually that's what `<AUTOGENERATED_TABLE_OF_CONTENTS>` in v1 do

See https://github.com/jaredpalmer/formik/blame/next/docs/api/withFormik.md#L65-L68

![image](https://user-images.githubusercontent.com/17883920/59043311-97901500-88ae-11e9-9331-888199898356.png)

**Comment by amimas** [comment]
> @amimas actually that's what `<AUTOGENERATED_TABLE_OF_CONTENTS>` in v1 do

Actually I find the current implementation a bit limited. Here's why and let me know what your thoughts  are. Maybe it can be more flexible in V2.

- Current implementation in V1 requires a specific pattern: an H2 heading that has one or more H3 headings that is wrapped in backticks

    This limits the potential of having partial table of content for a specific section. Requiring backticks in H3 headings means I cannot have a partial toc for a section that might not necessarily refer to any command/functions/methods (these may be in the details of the corresponding sections)

    Requiring H2 followed by H3 also limits the usage of partial toc. I may want a partial toc of a H3 headings followed by several H4 headings and so on.

- In V1 the syntax, `<AUTOGENERATED_TABLE_OF_CONTENTS>`, seems to generate a TOC of the entire page that follows the pattern: H2 followed by several H3, each of which are wrapped in backticks

    This does not seem to work for partial toc. For example: I have multiple H2 headings. Each of those has several H3 headings wrapped in backticks. If I add `<AUTOGENERATED_TABLE_OF_CONTENTS>` to the first H2 heading, it generates a TOC for all the H3 headings instead of only those that are within the scope of the first H2 heading where I added `<AUTOGENERATED_TABLE_OF_CONTENTS>`.

    I'm not sure if that was intended feature or if it's a bug.

**Comment by endiliey** [comment]
@amimas you are right ! I just went to re-read https://github.com/facebook/Docusaurus/blob/1aa0ea1152b0133830d127d11b123fcea261deb4/packages/docusaurus-1.x/lib/core/toc.js#L60-L71 and it seems that it's what really happening under the hood. That feature was implemented way before i joined the team, so i'm not really sure of the intention. 
It seems to be intended ...

To keep backward compatibility, i'll implement it like v1 for this feature. 

Technically in v2 you can just write remark plugins to do this and pass it to the `plugin-docs` option.

**Comment by endiliey** [comment]
Or maybe we should really discuss. Whether to deprecate this weird behavior or not. Backward compatibility isn't the highest priority because we're doing major version after all.

Since we allow passing remark plugins in v2, I am not even sure if we should add this too v2.

I am more towards deprecating this `<AUTOGENERATED_TABLE_OF_CONTENTS>` that seems to be weird. It increases parsing time and slow down the build process.

**Comment by yangshun** [comment]
Since this will be part of a major upgrade, I would opt for doing the right
thing over preserving non-ideal backwards compatibility.

**Comment by endiliey** [comment]
I think the right thing here is quite subjective for that part.

It isn't clear whether that feature is intended or not. The industry standard is to have table of contens for the whole page, which we already did in the right side. 
![image](https://user-images.githubusercontent.com/17883920/59119709-042a1300-8986-11e9-81d7-d01b14d3896d.png)

If they don't want it in the right side, they can swizzle and put it in tthe midde like this.

Here, i swizzled and moved the toc abit
![image](https://user-images.githubusercontent.com/17883920/59119915-a21ddd80-8986-11e9-9fbd-adc9fcc1bf9d.png)

**Comment by endiliey** [comment]
If we were to stick to industry standard, https://github.com/remarkjs/remark-toc is also another solution

It add a Table of Contents to a Markdown document. You can specify depth too (not just h2 or h3 like v1. Adding it to v2 is also as simple as passing remark plugins to v2 docs options.

I'm going to close this issue out as I feel we should do the right thing. If there is a need for `<AUTOGENERATED_TABLE_OF_CONTENTS>.` open up a new issue. If many are in favor, we will implement it

**Comment by amimas** [comment]
I personally think having an auto generated toc for the entire page like what we have in V1 is the right thing to do and it should be part of the core instead of removing it entirely in V2. The location of this overall TOC is subjective but I like the current implementation of having it on the right side out of the box; it gives a clear distinction between the right sidebar and the overall toc for a given page without cluttering the sidebar on the left side.

The `<AUTOGENERATED_TABLE_OF_CONTENTS>` is also another useful feature for generating partial toc for a particular section only. Perhaps it can be renamed to be something else. If we want that to be done using a plugin, that sounds okay too but that's also something I think a lot of users will benefit from. So, maybe this can be part of the core too and have a clear documentation explaining the usage/intention.

**Comment by endiliey** [comment]
> I personally think having an auto generated toc for the entire page like what we have in V1 is the right thing to do and it should be part of the core instead of removing it entirely in V2

Its not removed, check https://v2.docusaurus.io

The thing is, adding a feature like partial toc in markdown by default will slow down the markdown parsing time. For site like jest which has thousands of pages, it can increase dev time a lot (every seconds saved is valuable)

It should be an opt-in, and anyway it can be added easily by adding few lines of code in your config. I know how to do it with remark-toc. Perhaps I will add that to documentation in the future when we release v2 and teach people about it.

**Comment by wgao19** [comment]
Will add to docs #1578
2019年6月8日 12:52 +0800、Endi <notifications@github.com>のメール:

**Comment by endiliey** [comment]
Did this get updated to docs ? @wgao19 

I think we need to show its deprecated somehow

**Comment by wgao19** [comment]
@endiliey do you mind adding the guide in #2036?

**Comment by endiliey** [comment]
I think simply pointing it to this issue for reasoning is more sensible since the conversation above can explain it well.

**Comment by wcauchois** [comment]
Would it be possible to add some more instructions to the blurb at https://v2.docusaurus.io/docs/migrating-from-v1-to-v2/#remove-autogenerated_table_of_contents? It directed me to this issue but it's unclear to me how to add remark-toc to my "remarkPlugins" configuration (that's not in the default docosaurus.config.js - where do I put that key?) or use it. Any simple explanation or pointer to a simple example would be super appreciated.

**Comment by frank-lam** [comment]
@endiliey Hi, I am want to to generate the toc of h4/h5/h6 . Now just display the h2/h3. Is there any config parms to achive this feasure.

**Comment by slorber** [comment]
inline table of contents inside md docs (full or partial) will be possible thanks to https://github.com/facebook/docusaurus/pull/3904
