### ISSUE TITLE
v2 secondary mobile nav?

### ISSUE THREAD

**Issue by jaredpalmer** [facebook/Docusaurus#1563]
Is this implemented yet? Can I implement this on my own? I want something like v1 for mobile. I would settle for a select input tbh.

**Comment by endiliey** [comment]
@jaredpalmer coming soon #1562 

![image](https://user-images.githubusercontent.com/17883920/58958053-968ab500-87d4-11e9-95f3-6707936f231a.png)

See it here https://deploy-preview-1562--docusaurus-2.netlify.com/docs/introduction/

If you want to customize, swizzle is an option later on
