### ISSUE TITLE
Feedback: Swizzle/decentralized css variables

### ISSUE THREAD

**Issue by jaredpalmer** [facebook/Docusaurus#1564]
This might be an informa issue, but anyways...

The workflow for changing colors is quite difficult right now. Or at least, undocumented. Right now, you have to figure out the css variable name via devtools, and then the name of the component that is responsible for the css variable, open `@docusaurus` in node_modules, figure out where that component came from, then swizzle it.....it's a lot of work to just change a border-color. Furthermore, it's not immediately obvious what will happen in dark mode (but I will open a separate issue for that).

Anyways, I understand the thinking of keeping css variables localized to the component as it maintains encapsulation and, thanks to swizzle, it allows the maintainers to iterate on components without impacting existing customized sites. I am just venting that it is kind of a lot of work right now when all you want to do is change the primary color.

**Comment by endiliey** [comment]
Sorry for this. We'll make it easier for user in the next version. 

We just added a way to override css variables easily.

1. Create custom.css
https://github.com/facebook/Docusaurus/blob/ec69460b4fa56814aeedbf9f9f09c0d89b2f36db/website/css/custom.css#L1-L16

2.  Point the custom css location to preset-classic
https://github.com/facebook/Docusaurus/blob/ec69460b4fa56814aeedbf9f9f09c0d89b2f36db/website/docusaurus.config.js#L97-L111

3. It will override the variables

Does this work for you ?

**Comment by endiliey** [comment]
@jaredpalmer  Sorry for this. We'll make it easier for user in the next version. 

We just added a way to override css variables easily.

1. Create custom.css
https://github.com/facebook/Docusaurus/blob/ec69460b4fa56814aeedbf9f9f09c0d89b2f36db/website/css/custom.css#L1-L16

2.  Point the custom css location to preset-classic
https://github.com/facebook/Docusaurus/blob/ec69460b4fa56814aeedbf9f9f09c0d89b2f36db/website/docusaurus.config.js#L97-L111

3. It will override the variables

Does this work for you ?

**Comment by wgao19** [comment]
I’m thinking of a temporary solution to be writing a file that declares some of the more important css variables under Docusaurus’s theme layout. The file may as well serve as a future reference for what variables are more frequently customized than others.

A final approach regarding the build step of the library styles to Docusaurus is still to be discussed @yangshun

Best Regards,
ᴡᴇɪ
Sent from 📱
2019年6月5日 19:46 +0800、Jared Palmer のメール:

**Comment by endiliey** [comment]
2.0.0.alpha-19 released

rough changelog .18 -> .19 is here
https://github.com/facebook/Docusaurus/blob/master/packages/docusaurus/CHANGELOG.md#200-alpha19
