### ISSUE TITLE
copy code button for Docusaurus 2

### ISSUE THREAD

**Issue by endiliey** [facebook/docusaurus#1587]
## Have you read the [Contributing Guidelines on issues](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

yes

## Motivation

Support copy codeblock button for Docusaurus 2

## Where to start

Start docusaurus 2 website
1. Clone this repository
2. Read https://github.com/facebook/Docusaurus/tree/master/website and start website
3. Go to any docs url with codeblock. maybe http://localhost:3000/docs/installation
![image](https://user-images.githubusercontent.com/17883920/59119305-0c358300-8985-11e9-8a38-b0df1a39dc43.png)

Modify here to test in Docusaurus 2 to add the copy code button
https://github.com/facebook/Docusaurus/blob/1aa0ea1152b0133830d127d11b123fcea261deb4/packages/docusaurus-theme-live-codeblock/src/theme/CodeBlock/index.js#L33-L53

Also make sure to duplicate the change to https://github.com/facebook/Docusaurus/blob/master/packages/docusaurus-theme-classic/src/theme/CodeBlock/index.js

Send PR !!

**Comment by AlokTakshak** [comment]
Hi @endiliey  I want to give it a try, and if you could guide me how we want to implement it like button or icon for copy that would be really helpful

**Comment by endiliey** [comment]
@AlokTakshak feel free to propose a design. Best if we have 0 dependency for the icon

**Comment by hugofovargue** [comment]
@endiliey Made a PR #1606. I tried to implement a similar style to the legacy copy button.

**Comment by bvego** [comment]
Hi there. I saw that hugofovargue closed his PR so I wanted to give it a go!

PR #1643 

Feel free to close it if not applicable anymore I guess 😄
