### ISSUE TITLE
Customer Chat SDK in siteConfig.js

### ISSUE THREAD

**Issue by thiagopov** [facebook/docusaurus#1590]
## 💥 Proposal

Customer Chat SDK in siteConfig.js

**Comment by yangshun** [comment]
Thanks for the issue! Please provide more information and follow the Proposal template given. It'll be hard for us to know what exactly you want when the description is pretty brief.

**Comment by thiagopov** [comment]
https://developers.facebook.com/docs/messenger-platform/discovery/customer-chat-plugin/sdk/ in siteConfig.js

**Comment by endiliey** [comment]
wonr add new feature on siteconfig.js foe v1 as we get to v2
