### ISSUE TITLE
Sticky sidebars don’t stick in desktop safari

### ISSUE THREAD

**Issue by brainkim** [facebook/docusaurus#1597]
## 🐛 Bug Report
![Screen Shot 2019-06-10 at 6 06 44 PM](https://user-images.githubusercontent.com/2996754/59230152-8eeb5780-8baa-11e9-945f-de9c66e4cdfe.png)

The sidebars on the docs pages don’t stick in desktop safari (Safari Version 12.1, MacOS Version 10.14.4 Mojave).

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

yis

## To Reproduce

1. Open https://channel.js.org/docs/quickstart in safari
1. Scroll down

## Expected behavior

Sidebas exhibit the same scroll behavior they do in Chrome

(Write what you thought would happen.)

## Actual Behavior

They don’t

(Write what happened. Add screenshots, if applicable.)

## Reproducible Demo

no thanks!

**Comment by brainkim** [comment]
May be related to https://github.com/facebook/Docusaurus/issues/1241

**Comment by brainkim** [comment]
Duplicate of https://github.com/facebook/Docusaurus/issues/877

**Comment by yangshun** [comment]
Thanks @brainkim, this is a legit issue I discovered as well. The issues you've linked earlier are v1 issues hence they're not duplicates. The reason is because we're not including autoprefixer in the CSS webpack config and safari needs `-webkit-sticky` instead of just `sticky`.

**Comment by shakcho** [comment]
@yangshun I would like to work on it, I just want to know do I need to autoprefixer or just need to update the css.

**Comment by yangshun** [comment]
@shakcho it's yours! Let's do autoprefixer as it's the more futureproof way. Please look at Create React App and we can emulate their webpack config for autoprefixing.

**Comment by shakcho** [comment]
@yangshun I also thinking the same.  I will raise Pull Request ASAP.

**Comment by endiliey** [comment]
#1605
