### ISSUE TITLE
Footer missing from docs pages in v2

### ISSUE THREAD

**Issue by brainkim** [facebook/Docusaurus#1598]
## 🐛 Bug Report

Footer is missing from docs pages in v2

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

🌞

## To Reproduce

1. Visit https://v2.docusaurus.io/docs/introduction
2. Scroll to the bottom

## Expected behavior

The footer renders consistently across all pages.

## Actual Behavior

It’s missing from docs pages.

(Write what happened. Add screenshots, if applicable.)

## Reproducible Demo

(Paste the link to an example repo, including a `siteConfig.js`, and exact instructions to reproduce the issue.)

**Comment by yangshun** [comment]
This is actually intentional. The sticky stuff on the page might not play well with a Footer underneath so we chose to leave it out. If someone is keen on the Footer, they can swizzle `@theme/DocPage` and add it.
