### ISSUE TITLE
New content does not appear in the side menu

### ISSUE THREAD

**Issue by wescley** [facebook/docusaurus#1620]
## 🐛 Bug Report

(A clear and concise description of what the bug is)

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?
No
## To Reproduce

(Write your steps here:)

1. I installed docusaurus and tried to create new content, but it is not appearing in the side menu.
## Expected behavior

(Write what you thought would happen.)

## Actual Behavior

(Write what happened. Add screenshots, if applicable.)

## Reproducible Demo

(Paste the link to an example repo, including a `siteConfig.js`, and exact instructions to reproduce the issue.)

**Comment by yangshun** [comment]
Please provide more information and links to repo if possible.

**Comment by AdrianoCahete** [comment]
Left sidebar? If yes, you need to manually include on `sidebar.json`;

**Comment by endiliey** [comment]
@AdrianoCahete was correct. You have to manually include on sidebars. Docusaurus dont know whether certain docs should be put in a sidebar or not.

Please be more specific when reporting the issue too, we have a strict guideline on the issue template
