### ISSUE TITLE
"undraw_operating_system" SVG has a wrong background

### ISSUE THREAD

**Issue by AdrianoCahete** [facebook/docusaurus#1624]
## 🐛 Bug Report

The `undraw_operating_system.svg`file has a wrong color background.  
Today, we have a fill color of `#3f3d56`, giving the background almost the same color of items in foreground.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes.

## To Reproduce

1. Start a new doc
2. Open `website/static/img/undraw_operating_system.svg`.

## Expected behavior

![image](https://user-images.githubusercontent.com/37474/59981504-9b27d980-95da-11e9-8742-bc47f95a684b.png)

## Actual Behavior

![image](https://user-images.githubusercontent.com/37474/59981494-77649380-95da-11e9-9591-c9d01c4347dd.png)

## Reproducible Demo
--

**Comment by yangshun** [comment]
I'm afraid this is not something we can control. The original unDraw illustration uses such a dark color for the background as seen from https://undraw.co/search (search for operating system). The theme colors upon init are randomly generated and it's possible that you ended up with a color which doesn't display well with unDraw's. If you go to unDraw.co and use the same purple color, you'll get the same result.

I recommend you tweaking the fill color yourself which you seem to have done so.

cc @anges244 regarding the Operating System illustration's original colors.
