### ISSUE TITLE
Docusaurus2: Better favicon support

### ISSUE THREAD

**Issue by nebrelbug** [facebook/docusaurus#1625]
## 🚀 Feature

Support for adding multiple favicons/icons to a Docusaurus site. Ideally, a site should have different PNG icon sizes, a .ico favicon, and Apple Touch Icons, while Docusaurus only allows you to add one favicon file to your site.

## Have you read the [Contributing Guidelines on issues](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## Motivation

Sites should look good on all platforms. Having different sizes of icons, as well as icons for things such as Desktop Shortcuts and website downloads, is important to a well-developed site.

## Pitch

This isn't an absolutely necessary feature, and I'm not sure it should be included in the Docusaurus Core, but it would be good for SEO and UI.

**Comment by nebrelbug** [comment]
I would love to create a plugin, based on https://realfavicongenerator.net, that takes a config object and a user-provided icon and automatically generates multiple different icons for different browsers and platforms, and includes them in the HTML head.

**Comment by endiliey** [comment]
move it to https://v2.docusaurus.io/feedback

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
