### ISSUE TITLE
`GridBlock` component does not display image on mobile if alignment is not set to `top` or `bottom`

### ISSUE THREAD

**Issue by amimas** [facebook/docusaurus#1627]
## 🐛 Bug Report

Not too sure if this is a bug or intentional, but it seems like something that might have been overlooked.

On the main page of Docusaurus (https://docusaurus.io/en/), the `GridBlock` components don't seem to display images if `imageAlign` is **not** set to `top` or `bottom`, if you're viewing the page on mobile.

For example, this is what the "Quick Setup" and "Develop and Deploy" section looks like in mobile:

![image](https://user-images.githubusercontent.com/16211767/60114336-a9dcd080-9741-11e9-95f1-3b316d9d222c.png)

But, if the `imageAlign` is set to `top` (or `bottom`), they do show even in the mobile devices, for example, the "Document Search" section:

![image](https://user-images.githubusercontent.com/16211767/60114430-cf69da00-9741-11e9-878e-e4103e383c5d.png)

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## To Reproduce

Check the main page of docusaurus in mobile view

## Expected behavior

I expected the the layout to be responsive enough so that the even if `imageAlign` is not set to `top` or `bottom`, it would still appear on the display.

## Actual Behavior

The images don't show in mobile view if `imageAlign` is not set to `top` or `bottom`

## Reproducible Demo

https://github.com/facebook/docusaurus

**Comment by endiliey** [comment]
This seems intentional to me. I recommend overriding the default docusaurus css as a better workaround.
