### ISSUE TITLE
Docs Update Request : page not found after moving `pages` directory to `src`

### ISSUE THREAD

**Issue by medmin** [facebook/docusaurus#1642]
## 📚 Documentation

(A clear and concise description of what the issue is.)

According to the current github repo, the v2 website has its `pages` located in the `src`, which is nice. However, there is no configuration in the `docusaurus.config.js` to indicate the settings.

I tried to do the same thing, i.e., move `pages` to `src` directory, and I got `Page not found`.

I have searched the docs thoroughly, but I've got nothing.

 Would you please help me and add some documentation ? Thanks

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?
Yes.
(Write your answer here.)

**Comment by yangshun** [comment]
Sorry about that, we have yet to publish a new version. For now you'll have to add `path: 'src/pages'` to the `docusaurus.config.js`:

```diff
  presets: [
    [
      '@docusaurus/preset-classic',
      {
        pages: {
+          path: 'src/pages'path: 'src/pages',
        },
        ...
      },
    ],
  ],
```

**Comment by medmin** [comment]
Thanks for help!

**Comment by endiliey** [comment]
need to update docs before alpha.'20
