### ISSUE TITLE
[v2] Headings have low contrast on feedback page in dark mode.

### ISSUE THREAD

**Issue by prvnbist** [facebook/docusaurus#1656]
## 📚 Documentation

UX Issue: In the feedback page, title of feedback's have very low contrast in dark mode and is causing readability issues. 

![2019-07-13_221038](https://user-images.githubusercontent.com/17105682/61174299-d1de8780-a5bb-11e9-88a5-8b5ce610cca6.png)

**Comment by endiliey** [comment]
Good catch. We are actually aware of this too. PR is welcome 😍

**Comment by alexperez** [comment]
Hey I would like to work on this.

**Comment by endiliey** [comment]
@alexperez feel free to try sending a PR

**Comment by endiliey** [comment]
The relevant source code for that page is here https://github.com/facebook/docusaurus/blob/master/website/src/pages/feedback/index.js

But it is an iframe/ canny.io embed so it can be challenging :O to hack the contrast. Feel free to propose a solution
![image](https://user-images.githubusercontent.com/17883920/61522147-f7481700-aa3b-11e9-9699-8395e1d59dc7.png)

**Comment by alexperez** [comment]
It seems rather tricky to add custom CSS to an iframe, perhaps someone with more experience with this should look into it. 👍

**Comment by yangshun** [comment]
> It seems rather tricky to add custom CSS to an iframe

It's not possible to affect the CSS within an iframe. That'll be a security vulnerability.

Since Canny doesn't have support for dark mode, the solution here (IMO) is to add a white background to the container of the <iframe> so that that iframe always renders its dark text on a white background.

Not the prettiest UX on dark mode but that's still better than not being able to read.

**Comment by shakcho** [comment]
@endiliey @yangshun @wgao19  I tried this, but in Dark mode, it will not look that great.
My solution looks something like this as shown in the image below.
<img width="1677" alt="Screenshot 2019-08-04 at 11 45 22 PM" src="https://user-images.githubusercontent.com/9992559/62427541-3485f780-b712-11e9-9a1f-0551762adc2d.png">

One other solution I can think of if Canny support window.postmessage and if we can write some Javascript in canny then it can be solved in a better way.

**Comment by yangshun** [comment]
@shakcho this solution you have here is the best we have IMO. We could use that.

> One other solution I can think of if Canny support window.postmessage and if we can write some Javascript in canny then it can be solved in a better way.

It'll be a security risk for Canny and I see little reason as to why they would allow that.

**Comment by shakcho** [comment]
@yangshun you may need to close this issue

**Comment by yangshun** [comment]
@shakcho Thanks for catching. You can also add "Fixes #1656" to the PR in future so that the issue will be closed when the PR is merged. More info: https://help.github.com/en/articles/closing-issues-using-keywords
