### ISSUE TITLE
[v2] blog tag list do not support cjk

### ISSUE THREAD

**Issue by wenerme** [facebook/docusaurus#1669]
## 🐛 Bug Report

https://github.com/facebook/docusaurus/blob/f0d5313d488fcb3264286ab46fdabdb2c92a88d8/packages/docusaurus-theme-classic/src/theme/BlogTagsListPage/index.js#L26

tag list do not support cjk

![image](https://user-images.githubusercontent.com/1777211/61404634-72a9ab80-a90a-11e9-861a-57479228a1f7.png)

### Have you read the [Contributing Guidelines on issues]

Yes

## To Reproduce

1. add a cjk tag to blog
1. visit /blog/tags

## Expected behavior

show tag list

## Actual Behavior

![image](https://user-images.githubusercontent.com/1777211/61404634-72a9ab80-a90a-11e9-861a-57479228a1f7.png)
blank screen

## Reproducible Demo
NA

**Comment by yangshun** [comment]
Thanks for the report! I think a possible way to handle non-ascii characters will be to just dump them into a new unlabelled category.

**Comment by wenerme** [comment]
w h y
