### ISSUE TITLE
TOC show html tag like raw text on website but localhost does not

### ISSUE THREAD

**Issue by leavesster** [facebook/docusaurus#1671]
## 🐛 Bug Report

When I write this on docs markdown
```markdown
## Referencing Site Documents <span id="jump">
```

It always shows `Referencing Site Documents` in `h2` tag in the main text.
But it has some problem with TOC(table of Content) on a real website.

On the preview (run on http://localhost:3000 or http://192.168.0.12:3000), it just shows `Referencing Site Documents` Table of Content.
but when it runs on a real website, the Table of Content just show `<span id="jump">` like raw text:

```html
Referencing Site Documents <span id="jump">
```

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## To Reproduce

(Write your steps here:)

1. write `### Referencing Site Documents<span id='jump'>`
1. build and run on the website
1. see the category

macOS Chrome and Safari both have this problem.

## Expected behavior

just show `Referencing Site Documents`
![image](https://user-images.githubusercontent.com/11785335/61420432-0001f580-a935-11e9-8e83-6085dcba15bd.png)

and not show `<span id="jump">` part when on real website.

## Actual Behavior

```html
Referencing Site Documents <span id='jump'>
```

## Reproducible Demo

(Paste the link to an example repo, including a `siteConfig.js`, and exact instructions to reproduce the issue.)

[fork demo](https://github.com/leavesster/docusaurus/commit/89789b45f6d568b09ea5bb7fbfa5c60ade1f0e99)

I didn't have a real website domain to show this. But you can just see the fork demo what I changed.

I think it maybe some js works differently when it on reviews?

**Comment by endiliey** [comment]
Sorry but using your fork demo, Any docs change is reflected on `next` version of docs if you have versioned docs enabled.

http://localhost:3000/docs/en/next/navigation
![image](https://user-images.githubusercontent.com/17883920/61454196-65cc9c80-a98a-11e9-91c1-ef1d388b1a46.png)

http://localhost:3000/docs/en/navigation
![image](https://user-images.githubusercontent.com/17883920/61454227-83016b00-a98a-11e9-8b50-010379ddc9e1.png)

**Comment by leavesster** [comment]
I didn't create multiple version.

And My issue is when `docusaurus` runs on localhost, it didn't show `<span id="jump">` but when on the real website show `<span id="jump">`. 

I think maybe when `http://localhost:3000/docs/en/navigation` run on the real website. It will also show `<span id="jump">`.

I feel weird that preview is not the same as it shows on real website ……
And could I make TOC show subtitle as it shows on the preview, hiding the HTML tag?

**Comment by endiliey** [comment]
Its most likely i18n caching issue on dev.
Delete any i18n/**! files

Its hard for us to debug if you didn't have a real website domain to show this. But using the fork demo you mentioned, everything seems to be working fine

**Comment by leavesster** [comment]
It seems to delete all files in i18n doesn't help. 
But I create a totally new docusaurus project, it actually reflects as `next` version shows on dev. 

But it still weird the TOC doesn't show the text as same as it looks like on the h2 tag.

**Comment by leavesster** [comment]
I found how to make TOC content the same as HTML tag. 

just change this [code](https://github.com/facebook/docusaurus/blob/1edbeecbe565cbbbc0a6e6532c7c2d0c58d78807/packages/docusaurus-1.x/lib/core/nav/OnPageNav.js#L28)
from 
`<Link hashLink={heading.hashLink} content={heading.content} />` 
to 
`<Link hashLink={heading.hashLink} content={heading.rawContent} />`

It will be nice and intuitive that Docusaurus show TOC content as it shows on HMTL H2, H3 tags.
