### ISSUE TITLE
[v2] Mobile navbar is cut in small viewport

### ISSUE THREAD

**Issue by endiliey** [facebook/docusaurus#1697]
**Tip: This task is targeted towards potential contributor to Docusaurus project.**

## 🚀 Motivation

See https://v2.docusaurus.io/feedback/p/resposive-top-bar for context

![image](https://user-images.githubusercontent.com/17883920/61776407-26d49600-ae25-11e9-86a2-e88f5d0ad759.png)

# Where to start

1. Fork [the repository](https://github.com/facebook/docusaurus) and create your branch from `master`.
1. Clone the repository
1. Read [instruction on how to run Docusaurus 2 website](https://github.com/facebook/docusaurus/blob/master/website/README.md)
1. The related codes for the NavBar is https://github.com/facebook/docusaurus/tree/master/packages/docusaurus-theme-classic/src/theme/Navbar
1. Propose a fix and send a Pull Request :)

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

**Comment by shirshendubhowmick** [comment]
Fix 1: Moving search to a new line i.e. below the logo
Fix 2: Opening a small modal popup on focus of the search input box
Fix 3: Replace search box with a search icon, on tap of the icon expand it to search box and hide the "Docusaurus" text beside the logo, it will remain hidden while the search box is expanded.

Also may i know the min view port width that needs to be supported ?

**Comment by endiliey** [comment]
wdyt @yangshun @wgao19 ?

i think fix 3 can be nice. any recommendation on the min view port that needs to be supported ?

**Comment by shirshendubhowmick** [comment]
Can we limit it to 320px width ? I believe this will enough to support devices that pretty old like iPhone 5.

**Comment by endiliey** [comment]
was thinking of 320px too. lets go ahead

send PR :)

**Comment by wgao19** [comment]
thanks for the actionable suggestions @shirshendubhowmick @endiliey im also ok with 3 with 320px as min width, lets fix this :)

**Comment by shirshendubhowmick** [comment]
@endiliey Need little help, where can i find the current search icon ?

**Comment by endiliey** [comment]
@shirshendubhowmick 

https://github.com/facebook/docusaurus/blob/95ace0e4eba1f5b2bc0f9ced8ec703e01aa73d0a/packages/docusaurus-theme-classic/src/theme/Navbar/index.js#L152-L157

https://github.com/facebook/docusaurus/blob/master/packages/docusaurus-theme-search-algolia/src/theme/SearchBar/index.js

the css is from https://infima-dev.netlify.com/

**Comment by shirshendubhowmick** [comment]
#1741

**Comment by shirshendubhowmick** [comment]
PR #1741
