### ISSUE TITLE
[v2] blog rss feed

### ISSUE THREAD

**Issue by endiliey** [facebook/docusaurus#1698]
**Tip: This task is targeted towards potential contributor to Docusaurus project.**

## 🚀 Motivation

We need to generate blog rss feed in v2

# Where to start

1. Fork [the repository](https://github.com/facebook/docusaurus) and create your branch from `master`.
1. Clone the repository
1. yarn install in the root of the repo
1. The related codes for the blog plugin is https://github.com/facebook/docusaurus/tree/master/packages/docusaurus-plugin-content-blog
1. To run docusaurus 2 website, run `yarn start` at root
1. To build docusaurus 2 website, run `yarn build` at root
1. Propose a fix and send a Pull Request :)

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

**Comment by faelribeiro22** [comment]
@endiliey This issue is still open?

**Comment by endiliey** [comment]
@faelribeiro22 yep it is. wanna work on it ? 😉

**Comment by moozzyk** [comment]
Is the idea here to pretty much follow the logic used in the plugin-content-blog but instead of pushing posts to paginated results create an RSS feed (potentially using rss or feed package)?

**Comment by endiliey** [comment]
yep. @moozzyk

**Comment by moozzyk** [comment]
I will try to tackle this then.
