### ISSUE TITLE
doc request for info about publish-gh-pages

### ISSUE THREAD

**Issue by italicize** [facebook/docusaurus#1725]
## 📚 Documentation

Where is documentation for the `publish-gh-pages` script, such as prerequisites and a short description its actions? I couldn't find documentation on the Docusaurus site or the NPM site, <https://www.npmjs.com/package/publish-gh-pages>.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

**Comment by endiliey** [comment]
That npm package is unrelated to our project. 

our docs on the script is defined here https://docusaurus.io/docs/en/publishing#using-github-pages

if you think anything is missing, submit a pr on docs

**Comment by italicize** [comment]
Sorry, I assumed publish-gh-pages was a Facebook script. The script is currently unpopular (only 4 weekly downloads). Is it still a good script for Facebook to recommend, or are more people using a different script?

**Comment by endiliey** [comment]
Hmm i personally dont recommend that package. However, if it is a Docusaurus project and you want it to be published to GitHub pages, using Docusaurus own publish script is the best. The steps needed is mentioned in https://docusaurus.io/docs/en/publishing#using-github-pages

**Comment by italicize** [comment]
@endiliey When you said Docusaurus' own publish script, did you mean `publish-gh-pages` or something else? The link you sent uses the `publish-gh-pages` script.

**Comment by endiliey** [comment]
The link i sent had the same name `publish-gh-pages` but its docusaurus own script.
Code is https://github.com/facebook/docusaurus/blob/master/packages/docusaurus-1.x/lib/publish-gh-pages.js

https://www.npmjs.com/package/publish-gh-pages is unrelated but had same name. Code is https://github.com/poychang/publish-gh-pages

Anyway, just follow https://docusaurus.io/docs/en/publishing#using-github-pages if u r publishing docusaurus site

**Comment by italicize** [comment]
Thanks, @endiliey, for explaining that Docusaurus has a script named `publish-gh-pages`, which isn't the same as the unpopular script at npmjs.com with the same name.
