### ISSUE TITLE
Restrict CSS from static folder to css folder

### ISSUE THREAD

**Issue by rhythnic** [facebook/docusaurus#1732]
## 🐛 Bug Report

The CSS bundle, `main.css`, seems to include all css files from the static folder.  It should only include CSS from the css folder.  My use case is that I would like to put a complete static site into a folder within the `static` folder, and then render it into an iFrame on a custom page.  The problem is that the css is getting bundled into the main CSS file and causing the Docusaurus site to render incorrectly.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## To Reproduce

(Write your steps here:)

1. Create a folder `/website/static/foo`
2. Create a `.css` file within `/website/static/foo`
3. Start the development server
4. Confirm that the CSS bundle contains the css content from `/website/static/foo` 

## Expected behavior

I expected that only CSS files from the `css` folder would be included in the CSS bundle.

## Actual Behavior

The CSS bundle includes all CSS files within the static folder.  In my case, the Bootstrap CSS file was included.

### UI CSS Glitch
![ui-bug](https://user-images.githubusercontent.com/8162640/62232926-66573100-b395-11e9-9308-0a7e01f34714.png)

### CSS File

![css-bootstrap](https://user-images.githubusercontent.com/8162640/62232945-75d67a00-b395-11e9-88a7-c2b549e1ab57.png)

## Reproducible Demo

https://gitlab.com/rhythnic/lpwan-site-revamp

**Comment by endiliey** [comment]
use https://docusaurus.io/docs/en/site-config#separatecss-array

**Comment by rhythnic** [comment]
Thank you.  There's a discrepancy in the Docusaurus docs.  The API reference page uses `separateCSS`, but the correct propery, referenced in the Custom Pages documentation, is `separateCss`.
