### ISSUE TITLE
Markdown is retained in page descriptions

### ISSUE THREAD

**Issue by duckdotapk** [facebook/docusaurus#1739]
## 🐛 Bug Report

The `og:description` meta tag will contain raw markdown if the sentence it's derived from contains any.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes.

## To Reproduce

Create a page wherein the first sentence contains markdown. Here's an example from my site:

```md
---
id: hack-support
title: Hack Support
---

**This hack is [always enabled](all-hacks.md#always-enabled-hacks) when using the Mod Launcher.**
```

## Expected behavior

I believe that Docusaurus should strip markdown out of page descriptions when generating them.

## Actual Behavior

When this page is generated (via `yarn start` or `yarn build`), the `og:description` field will contain similar markdown to the original file (with links resolved) as showcased below:
```html
<meta property="og:description" content="**This hack is [always enabled](/docs/lucasmodlauncher/hacks/all-hacks#always-enabled-hacks) when using the Mod Launcher.**"/>
```

I initially noticed this when I shared one of the pages with this issue via Discord and the embed contained markdown:

![actual behaviour showcase](https://dl.dropboxusercontent.com/s/tyds1d7jwluptp5/Discord_2019-08-03_12-23-41.png)

## Reproducible Demo

I initialised a brand new site with `npx docusaurus-init` and uploaded it [here](https://github.com/duckdotapk/docusaurus-issue-demo) to demonstrate this issue.

I decided to use a new site for this as the example documents `doc1.md` and `doc2.md` both contain markdown within their first sentence which is sufficent for demonstrating it.

To replicate it yourself, simply run `yarn start` to start the site or `yarn build` to build the site and inspect the page's HTML (example from `doc1`):
```html
<meta property="og:description" content="Check the [documentation](https://docusaurus.io) for how to use Docusaurus."/>
```

**Comment by endiliey** [comment]
Its intended since 1.x. We dont render the html part because #1066 

If we strip it out, its hard to tell which to remove
```
**This hack is [always enabled](/docs/lucasmodlauncher/hacks/all-hacks#always-enabled-hacks) when using the Mod Launcher.**"
```
or

```
This hack is always enabled when using the Mod Launcher
```

or

```
This hack is [always enabled](/docs/lucasmodlauncher/hacks/all-hacks#always-enabled-hacks) when using the Mod Launcher
```
There are many edge cases that can even cause more headache

**Comment by duckdotapk** [comment]
My proposal was to render the description separately from the rest of the page and in that process remove any markdown that isn't actually text displayed to the end user such as the URL. 

Basically like how it would ultimately be displayed on the page minus any hyperlinks or formatting.

Though the proposal that other fella made on having a description field next to the pages URL and title would also probably be a sufficent and arguably better solution (since you could customise it to not be exactly the same as the first sentence).

**Comment by duckdotapk** [comment]
My last response was written on a phone so I wasn't able to be as detailed but to be clear I mean like the first example you gave, so this:

```md
**This hack is [always enabled](all-hacks.md#always-enabled-hacks) when using the Mod Launcher.**
```

Would resolve as this:
```
This hack is always enabled when using the Mod Launcher.
```

**Comment by endiliey** [comment]
A better solution is to allow description frontmatter like in v2. If not defined, we still go with current behavior

To be honest as a user i’d prefer rendering the markdown as the meta description. I might be wrong but this meta description has been like this since a year ago.

I will close this issue as wontfix. We will accept PR on the description as frontmatter though
