### ISSUE TITLE
Yarn cannot run the version script

### ISSUE THREAD

**Issue by italicize** [facebook/docusaurus#1743]
## 🐛 Bug Report

`yarn version` doesn't run in Git Bash or at the Windows command prompt. (I don't know whether it runs on Mac.) By contrast, `npm run version` runs fine.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## To Reproduce

1. In Git Bash or at the Windows command prompt, `cd` to the website directory of a Docusaurus project. 
1. Run `yarn examples versions`.
1. Attempt to run `yarn version n.n.n` where n.n.n is a version number. (It fails.)
1. Attempt to run `yarn version --new-version n.n.n` where n.n.n is a version number. (It fails.)
1. Run `npm run version n.n.n` where n.n.n is a version number. (It works.)

## Expected behavior

Versioned docs are saved by `yarn version`.

## Actual Behavior

Versioned docs aren't saved by `yarn version`. Error messages appear. See attached images. 

![docusaurus-version-with-yarn-at-windows-command-prompt](https://user-images.githubusercontent.com/19557158/62483761-52cd1100-b76d-11e9-98eb-51fdf5866de4.png)
![docusaurus-version-with-yarn-in-git-bash](https://user-images.githubusercontent.com/19557158/62483760-52347a80-b76d-11e9-928b-7a382566a383.png)

## Reproducible Demo

Test `yarn version` with any repository. I was using the sample repository from the Docusaurus tutorial, <https://github.com/italicize/docusaurus-tutorial>.

**Comment by endiliey** [comment]
It should be yarn run version instead. Yarn version actually runs yarn own native version and docusaurus-version

anyway did u make sure running

 npm run examples versions

**Comment by endiliey** [comment]
Its a documentation mistake

instead of “yarn version” it should be “yarn run version”

**Comment by endiliey** [comment]
Anyway #1744 removed that
