### ISSUE TITLE
Not trim start trailing spaces in code blocks

### ISSUE THREAD

**Issue by chengtie** [facebook/docusaurus#1748]
Hello,

I want to write code blocks with Excel formules (it seems that at the moment there is not syntax highlighting for it). And one case is to write code re-factoring like the follows:

![Screenshot 2019-08-08 at 04 43 04](https://user-images.githubusercontent.com/774409/62656558-0a913700-b997-11e9-8c60-f5ad13e4e188.png)

It returns the following layout, we could notice that the spaces in the first line have been removed.

![Screenshot 2019-08-08 at 04 35 07](https://user-images.githubusercontent.com/774409/62656324-83dc5a00-b996-11e9-9638-1cdf73d2df7c.png)

Does anyone know if there is workaround to not systematically trim the spaces in the first line.

**Comment by endiliey** [comment]
swizzle CodeBlock component and remove the .trim() function
