### ISSUE TITLE
publish-gh-pages doesn't run at a Windows command prompt

### ISSUE THREAD

**Issue by italicize** [facebook/docusaurus#1749]
## 🐛 Bug Report

The [publish-gh-pages](https://github.com/facebook/docusaurus/blob/master/packages/docusaurus-1.x/lib/publish-gh-pages.js) script doesn't run at a Windows command prompt, with or without `USE_SSH=true`. The script runs in Git Bash. Why won't it run at a Windows command prompt?

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## To Reproduce

At the Windows command prompt:
1. `cd` to the website directory of a Docusaurus repository.
1. Type `GIT_USER=githubusername CURRENT_BRANCH=master USE_SSH=true npm run publish-gh-pages` replacing `githubusername` and press Enter. (It fails on my system.)
1. Type `GIT_USER=githubusername CURRENT_BRANCH=master npm run publish-gh-pages` replacing `githubusername` and press Enter. (It fails on my system.)

In Git Bash:
1. `cd` to the website directory of a Docusaurus repository.
1. Type `GIT_USER=githubusername CURRENT_BRANCH=master USE_SSH=true npm run publish-gh-pages` replacing `githubusername` and press Enter. (It fails on my system.)
1. Type `GIT_USER=githubusername CURRENT_BRANCH=master npm run publish-gh-pages` replacing `githubusername` and press Enter. (It runs on my system.)

## Expected behavior

Files in the build directory are copied to GitHub. 

## Actual Behavior

Files aren't copied to GitHub. An error message says, `'GIT_USER' is not recognized as an internal or external command, operable program or batch file.` See the screen images.

SSH and HTTPS fail at the Windows command prompt:

![publish-gh-pages-at-the-windows-command-prompt](https://user-images.githubusercontent.com/19557158/62646345-ff8cc700-b902-11e9-9623-f71ae70834f3.png)

SSH fails in Git Bash:

![publish-gh-pages-in-git-bash-ssh](https://user-images.githubusercontent.com/19557158/62646349-00255d80-b903-11e9-99c5-77d00b4b56e3.png)

HTTPS runs in Git Bash:

![publish-gh-pages-in-git-bash-html-start](https://user-images.githubusercontent.com/19557158/62646347-00255d80-b903-11e9-8825-ee1e6cd42053.png)
. . .
![publish-gh-pages-in-git-bash-html-end](https://user-images.githubusercontent.com/19557158/62646346-ff8cc700-b902-11e9-9c10-6167caac5c31.png)

## Reproducible Demo

Test `publish-gh-pages` with any repository. My repository was from the Docusaurus tutorial. I copied the files in my local repository to this branch, <https://github.com/italicize/doc-tutorial/tree/source>.

**Comment by chenhaihong** [comment]
Same with u.

**Comment by endiliey** [comment]
Accepting PR on the docs. The instruction was meant for Linux command line. The way environment variable works in window is different

**Comment by dylmye** [comment]
I'll have a look at this today! :)
