### ISSUE TITLE
Double matches in Algolia search box with cleanUrl:true

### ISSUE THREAD

**Issue by cameron-elliott** [facebook/docusaurus#1750]
## 🐛 Bug Report

When using algolia search, and enabling cleanUrl, most results show up twice in matches.

### Have you read the [Contributing Guidelines on issues]
Yes

## To Reproduce
1. Go to https://docusaurus.io type 'cleanurl' in search box, click first search match, which
will be:
https://docusaurus.io/docs/en/site-config#cleanurl-string

2. Go to https://docusaurus.io type 'cleanurl' in search box, click second search match, which
will be:
https://docusaurus.io/docs/en/site-config.html#cleanurl-string

The gist of this issue, is that it doesn't seem algolia should show search matches twice for the exact same material, even though they have two urls. (with html and without)

The same issue can also be seen with the 'icon' search string as of today 8/7/19

## Expected behavior
I would hope when I type cleanurl, the matching page would show up only once, it is confusing to me as a newish user why I see double matches. Without exploring I asked "are they the same documents/copy?"

## Actual Behavior
Type in 'cleanurl' in the search box, you wont' see the sole document on it once, but you will see two matches.
![2019-08-07 14_54_05-siteConfig js · Docusaurus](https://user-images.githubusercontent.com/868689/62660589-48ed0e80-b923-11e9-863f-ac7c7368afcf.png)

**Comment by endiliey** [comment]
When docusaurus was first launched, all url came with .html prefix

Then after few months, cleanUrl option in siteConfig was added. 

So if the url is previously /foo.html
We generate foo/index.html to make the url accessible as /foo

However, since cleanurl was a new feature back then, we still generate the html. So foo.html and foo/index.html is created which causes these two search result

This however doesnt happen in v2 (in alpha now).

**Comment by cameron-elliott** [comment]
Does v2 have the ability to wrap static pages with header/footer like the v1 'wrapPagesHTML' flag enables?
That would enable me to try v2 and see if it could work for me.

**Comment by cameron-elliott** [comment]
@endiliey If I wanted to try to stop the generation of .html files and submit a PR, where do you suggest I look first? Thanks.

**Comment by wgao19** [comment]
@cameron-elliott in v2 you can [swizzle](http://docusaurus-2.netlify.com/docs/using-themes#swizzling-theme-components) the footer component. The idea is that the swizzled component will replace the original component and you can customize it from then on. Does this sound like will fit your needs?

**Comment by cameron-elliott** [comment]
@wgao19 thanks for the heads up, let me check it out.
