### ISSUE TITLE
[v2] use primary color for highlighted items in table of contents 

### ISSUE THREAD

**Issue by banli17** [facebook/docusaurus#1752]
v2 use primary color for highlighted items in table of contents
![1](https://user-images.githubusercontent.com/12556069/62781204-088bbd00-baea-11e9-8904-d32e7e701991.png)

**Comment by wgao19** [comment]
I think highlighting table of content isn't implemented in v2 yet. There is a related v1 PR #1524.
Would you like to work on this?

**Comment by banli17** [comment]
i make it local，but i dont know  put js where, i put css and other in website dir, but if js put in theme dir , it's strange

**Comment by wgao19** [comment]
I would create a component under packages/docusaurus-theme-classic/src/theme and use it in packages/docusaurus-theme-classic/src/theme/DocLegacyItem/, not sure if @endiliey or @yangshun would suggest anywhere else?

**Comment by yangshun** [comment]
Correction - this issue is not related to #1871 (got misled by #1871's inaccurate description). #1896 is the fix in the right direction.
