### ISSUE TITLE
--host and --port doesn't work correctly

### ISSUE THREAD

**Issue by cameronelliott** [facebook/docusaurus#1753]
## Summary
Simple issue where live reload doesn't really work correctly when --host=nnn.nnn.nnn.nnn is supplied as an argument to 'npm start', I have found work around,but not being a JS programmer, I don't know how to do a high-quality fix.
The work-around I show below causes parsing of 'program.argv' on each page reload, but a cleaner fix would cause the state/objects created by parsing program.argv to be saved and reused each time 'getReloadScriptUrl()' is called. 
If a JS programmer will tell me how to save the state of the 'program' object so it I doesn't need to be re-created on each pass-through I will implement and submit PR

### Have you read the [Contributing Guidelines on issues]?
Yes

## To Reproduce
1. you must know and use your default IP address for this reproduction, I suggest a machine with an IPv4 address:  'a.b.c.d' 
2. use one or both of the following commands: 'ip route get 8.8.8.8' or 'ip a' to determine your local ethernet ip address
3. start version 1.12.0 using and substitute your host ip addr for 111.222.333.444 below
$ npm  start -- --host=111.222.333.444 
4. if a browser window opens (most platforms) then view source, and see this at the end:
<script src="http://111.222.333.444:35729/livereload.js"></script>
5. reload the page, then view source, you will see at the end:
<script src="http://127.0.0.1:35729/livereload.js"></script>

## Expected behavior
the requested host ip address should persists after reloads, this is important for live reload to work.

## Actual Behavior
the requested ip on the command line, does not persist after the first reload

## Reproducible Demo
this is reproducible with the actual Docusaurus site, or the default test site.

## Gross Workaround
[Original code link without workaround](https://github.com/facebook/docusaurus/blob/0568ad49922be8012907e5578d09200b717d08f6/packages/docusaurus-1.x/lib/server/liveReloadServer.js#L30)

## Workaround code
```js
const getReloadScriptUrl = () => {
  // hacked in
  program
  .option('--port <number>', 'Specify port number')
  .option('--no-watch', 'Toggle live reload file watching')
  .option('--host <host>', 'use specified host (default: localhost)')
  .parse(process.argv);

  // hacked in
  program.parse(process.argv)

  const port = process.env.LIVERELOAD_PORT;
  const host = program.host || 'localhost';

  return `http://${host}:${port}/livereload.js`;
};
```

**Comment by yangshun** [comment]
v2's hot reloading is not custom built and is unlikely to face the same issue. Any reason why you have to specify a host and not use the default?

**Comment by cameron-elliott** [comment]
Yeah, the default is 127.0.0.1, which doesn't work on pixelbooks, which is my dev system. 
I added a comment asking for JS programmer advice on how to convert the ugly work around function to something cleaner.

**Comment by cameron-elliott** [comment]
Also, in my situation I sometimes need to do some editing on a remote production system, in which case 127.0.0.1 also will not work.

**Comment by slorber** [comment]
The Docusaurus team is actively working on Docusaurus v2.

After a very long alpha, Docusaurus v2 is [now in beta](https://docusaurus.io/blog/2021/05/12/announcing-docusaurus-two-beta).
We believe that the v2 beta is already better than v1, and v2 is ready for maintstream adoption.

Apart from critical issues and security fixes, we don't plan to invest much time on Docusaurus v1 anymore.

We are all closing v1 issues. 
Maybe the current issue is already fixed in Docusaurus v2.
Please try to upgrade, and if the issue is still there on Docusaurus v2, open a new issue.
