### ISSUE TITLE
Travis time-out during sitemap.js execution

### ISSUE THREAD

**Issue by RoiArthurB** [facebook/docusaurus#1760]
## 🐛 Bug Report

When [Travis try to compile the website](https://travis-ci.org/gama-platform/gama-platform.github.io/builds), it froze at the final step and is time-out by Travis because there's no output since 10 min

```
$ docusaurus-publish
HEAD
https://github.com/gama-platform/gama-platform.github.io.git
generate.js triggered...
sitemap.js triggered...

No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#build-times-out-because-no-output-was-received

The build has been terminated
```

The strange point is that the same code was compiling before and does not anymore (even with a `git reset` + `git push -f` to have strictly the same content)

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## To Reproduce

1.  Setup Travis to compile Docusaurus project
2. Make a normal commit
3. Wait until sitemap.js is trigger
4. Wait until Travis time-out the commit

## Expected behavior

As before, having the `docusaurus-publish` command terminating properly and commit new website on the repo !

## Actual Behavior

Travis time-out the process after 12 min

## Reproducible Demo

(Paste the link to an example repo, including a `siteConfig.js`, and exact instructions to reproduce the issue.)

Here's the [Github Repo of the project](https://github.com/gama-platform/gama-platform.github.io/tree/sources) and here's the [Travis build](https://travis-ci.org/gama-platform/gama-platform.github.io/builds)

**Comment by endiliey** [comment]
Pls reopen if issue still persist. Seems ok now from travis log ?

**Comment by RoiArthurB** [comment]
I've finded a workaround to fix it : 

I'm running the `docusaurus-publish` command in background, and echo a message every 10 minutes to avoid the travis' timeout

**Comment by endiliey** [comment]
Its actually due to the build taking some time. What's interesting is ur travis timed out too fast if there's no log.

**Comment by RoiArthurB** [comment]
I don't really know/understand what you mean by "too fast"... 

I'm using the default free travis-ci.org which timeout every build after 10 minutes without console output...

**Comment by endiliey** [comment]
My bad, my definition of "too fast" is that 10 mins seems too short. I guess i'm on travis education so thats why im not seeing it.

Netlify free timeout is 30 mins
Circleci free is also longer, >= 30 mins

Anyway im glad there's a workaround
