### ISSUE TITLE
docusaurus-build generates a broken website

### ISSUE THREAD

**Issue by stavalfi** [facebook/docusaurus#1761]
## 🐛 Bug Report

# (I did **not** change anything in the website/configurations)

![image](https://user-images.githubusercontent.com/12954665/63160032-70c82a80-c025-11e9-83eb-41bc9e5195a7.png)

![image](https://user-images.githubusercontent.com/12954665/63160255-fe0b7f00-c025-11e9-961d-244b7efb3cae.png)

## Reproducible Demo

https://github.com/stavalfi/docusaurus-broken-build

nothing was changed in `siteConfig.js`.

---

node v: v8.11.3 (later tested with 10.10.3 as well - same results).
yarn v: 1.16.0
mac v: mojave 10.14.3

**Comment by endiliey** [comment]
Build is not broken. You are probably serving the build dir from wrong folder.

What command did you run to serve the build locally ?
Send screencast ..

**Comment by stavalfi** [comment]
@endiliey I opened the index.html with chrome.. isn't it what I should have done? (I do it when creating bundles with webpack).

**Comment by yangshun** [comment]
Try starting a local web server with `python -m SimpleHTTPServer 8000` in the `build` dir and go to `http://localhost:8000/<baseUrl>`. You should see it.

**Comment by stavalfi** [comment]
@yangshun I it's working locally. But what should I do to make it work in Netlify?

**Comment by astrotim** [comment]
I'm seeing this as well. Any URL without a trailing slash redirects to localhost:8000

**Comment by LLejoly** [comment]
> python -m SimpleHTTPServer 8000

I faced the same issue. and running an http server to access the build folder works. This extra step should be mentioned in the official documentation.

**Comment by slorber** [comment]
@LLejoly there's ongoing work to provide an official "docusaurus serve" command: https://github.com/facebook/docusaurus/issues/3062

This is a jamstack SPA project, not all http servers will work perfectly with it, so we'd rather recommend one.
