### ISSUE TITLE
How is infima actually working?

### ISSUE THREAD

**Issue by yankeexe** [facebook/docusaurus#1763]
Using v2, I deleted the "custom.css" which contained the Infima variables. But when I inspect the styles on the home page, infima variables are still injected,  `--ifm-hero-background-color`.

I looked at the v2 documentation which linked to the [Infima website](https://infima-dev.netlify.com/) but nothing is clear there, descriptions still have Lorem Ipsum. I am kind of confused on how to style the site. 

Help :)

**Comment by wgao19** [comment]
D2 site by default uses the infima stylesheets. For basic customization, you may change the variables in `custom.css`. We do not include all the css variables there, but you can add more (those variables you hope to change when you inspect).

Infima not yet a public project and the docs are work in progress, we'll prolly need a bit of geeky spirit for now and learn the variable names by ourselves.

**Comment by yankeexe** [comment]
> Infima not yet a public project and the docs are work in progress, we'll prolly need a bit of geeky spirit for now and learn the variable names by ourselves.

What I am doing right now is, inspecting the [Infima site](https://infima-dev.netlify.com/) and figuring out the class names. Is that the way to go? :sweat_smile:  If there are any WIP docs on Infima, can you link them? I tried looking at npm and GitHub but couldn't find one.

**Comment by wgao19** [comment]
> What I am doing right now is, inspecting the Infima site and figuring out the class names. Is that the way to go?

Unfortunately that is probably the best way to go atm 😅

It sounds to me that you are looking into more customized styling than tweaking Infima variables, in which case you can check out my [personal no-style starter](https://github.com/wgao19/docusaurus-template-no-style), or learn from there how to customize your site.

**Comment by yankeexe** [comment]
Thank you @wgao19 :slightly_smiling_face:

**Comment by binarylogic** [comment]
> Infima not yet a public project and the docs are work in progress, we'll prolly need a bit of geeky spirit for now and learn the variable names by ourselves.

Thanks. Is there any reason this project is private? What are the downsides of making it public while it's being developed?
