### ISSUE TITLE
How to implement sticky footer on new pages in v2?

### ISSUE THREAD

**Issue by yankeexe** [facebook/docusaurus#1764]
Created a new page and imported Navbar and Footer from theme 
```javascript
import Navbar from "@theme/Navbar";
import Footer from "@theme/Footer";
```
Footer is not sticky: 
![Non-sticky footer](https://i.imgur.com/bbNb5AM.png)

Found, #637 fixing this issue. But couldn't locate the file that is changed here https://github.com/facebook/docusaurus/commit/b220ec2f23632d9e21334012cfea0abaca0f52d.

**Comment by wgao19** [comment]
Sticky footer is not implemented in v2. However, you may customize your site’s footer by [swizzling](http://docusaurus-2.netlify.com/docs/using-themes#swizzling-theme-components) the default footer. You may try putting in the v1 footer and tweak it to work with your site.

**Comment by yankeexe** [comment]
Adding contents enough to fill the screen does the trick, for now, will look into making it sticky for all pages later on.
