### ISSUE TITLE
Where is CompLibrary?

### ISSUE THREAD

**Issue by chasm** [facebook/docusaurus#1769]
I am trying to follow the [Docusaurus tutorial](https://docusaurus.io/docs/en/tutorial-create-new-site). The generated application is describe as having the following file structure, which is what is actually generated when I run the init command:

```
├── Dockerfile
├── docker-compose.yml
├── docs
│   ├── doc1.md
│   ├── doc2.md
│   ├── doc3.md
│   ├── exampledoc4.md
│   └── exampledoc5.md
└── website
    ├── README.md
    ├── blog
    │   ├── 2016-03-11-blog-post.md
    │   ├── 2017-04-10-blog-post-two.md
    │   ├── 2017-09-25-testing-rss.md
    │   ├── 2017-09-26-adding-rss.md
    │   └── 2017-10-24-new-version-1.0.0.md
    ├── core
    │   └── Footer.js
    ├── package.json
    ├── pages
    │   └── en
    │       ├── help.js
    │       ├── index.js
    │       └── users.js
    ├── sidebars.json
    ├── siteConfig.js
    ├── static
    │   ├── css
    │   │   └── custom.css
    │   └── img
    │       ├── docusaurus.svg
    │       ├── favicon
    │       │   └── favicon.ico
    │       ├── favicon.png
    │       └── oss_logo.png
    └── yarn.lock
```

But in [the next step](https://docusaurus.io/docs/en/tutorial-create-pages), we are provided with the following `HelloWorld` page code:

```jsx
const React = require('react');

const CompLibrary = require('../../core/CompLibrary.js');

const Container = CompLibrary.Container;
const GridBlock = CompLibrary.GridBlock;

function HelloWorld(props) {
  return (
    <div className="docMainWrapper wrapper">
      <Container className="mainContainer documentContainer postContainer">
        <h1>Hello World!</h1>
        <p>This is my first page!</p>
      </Container>
    </div>
  );
}

module.exports = HelloWorld;
```

**There is no `CompLibrary.js` in the `/website/core/` folder.** Am I missing something?

**Comment by endiliey** [comment]
Nodejs require in docu v1 case will start from docusaurus own folder in node_modules/

Its kinda time consuming to explain, but short answer is above

**Comment by Alexander-Linkov** [comment]
@endiliey It does not help at all. I do steps in tutorial and gets an error:
`Error: Cannot find module '../../core/CompLibrarary.js'`

And I do not know how to fix it.

**Comment by cdaringe** [comment]
removed in 2.x sounds like. unsure if there will be another provider for the `<Markdown>in _jsx_</Markdown>`

**Comment by AdamBebko** [comment]
I'm also wondering how to restore this functionality

**Comment by slorber** [comment]
I have many things to backport in the migration cli/doc, including a solution for the comp library migration.

In the meantime, you can copy the comps here and use them in place of the v1 components: https://github.com/facebook/jest/tree/v27.0.0-next.5/website/src/components/v1

For simple cases, you can use the new `<Interpolate>` component  instead of `<MarkdownBlock>`, as shipping a full MD parser client-side adds more weight to your site
