### ISSUE TITLE
https://validator.w3.org

### ISSUE THREAD

**Issue by incecumali** [facebook/docusaurus#1770]
## 🐛 Bug Report

there are lots of errors by validator.w3.org  and all errorrs are almost same:
`Element p not allowed as child of element span in this context.`
[Errors are here ](https://validator.w3.org/nu/?doc=https%3A%2F%2Fdocusaurus.io%2Fdocs%2Fen%2Fapi-pages)

https://validator.w3.org/nu/?doc=https%3A%2F%2Fdocusaurus.io%2Fdocs%2Fen%2Fapi-pages

**Comment by endiliey** [comment]
is this a major issue ? I personally feel this is quite trivial and doesnt affect end user. 

 there's no easy way to fix this on docu because the html is generated by markdown lib - Remarkable.  The generated markup includes a <p> element inside a <span> and that this is not allowed.

Wontfix

**Comment by incecumali** [comment]
Thank you for clarification, 
I have no idea about majority of issue just  informed you about error to contribute your project.
