### ISSUE TITLE
Set a different default language

### ISSUE THREAD

**Issue by MakcStudio** [facebook/docusaurus#1772]
Hello everyone, tell me how to set another default language? I write documentation in Russian and I want it to be translated into English and Chinese, but I do not understand how I should set up my project for this

**Comment by MakcStudio** [comment]
I understand this was not implemented, I would certainly like to automatically receive the translation of all files from Russian to other languages, but I can do it manually. But I definitely need to default language of the user who first came to the site was Russian. How can I do that?

**Comment by endiliey** [comment]
Can't do it now. This will be part of v2 instead. Close as #938 duplicate
