### ISSUE TITLE
Sidebar Not Showing in New Docs if doc id is not "doc*"

### ISSUE THREAD

**Issue by wdavisf** [facebook/docusaurus#1773]
## 🐛 Bug Report

When adding new documents to the documentation, the sidebar does not show up if the id of the new document isn't `doc1`, `doc2`, ..., `doc*`.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## To Reproduce

(Write your steps here:)

1. Create a new document
1. Write an id different to `doc*`
1. Witness how the sidebar doesn't show up.

## Expected behavior

The sidebar should be present in any new document created.

## Actual Behavior

The sidebar doesn't show up.

## Reproducible Demo

(Paste the link to an example repo, including a `siteConfig.js`, and exact instructions to reproduce the issue.)

**Comment by endiliey** [comment]
I dont think this is true. Pls provide reproducible repository. Even https://docusaurus.io own doc id is not always `doc*`.

There is no sidebar for newly added doc because you didnt add it to your sidebars.json

**Comment by wdavisf** [comment]
Hey @endiliey, I just took a look at another issue and found my answer: https://github.com/facebook/Docusaurus/issues/1296

I was trying to have the sidebar showing in documents which *are not* in the sidebar, and it's a built in feature that the sidebar doesn't show up in documents not present in the sidebar.

Therefore, I'm closing this ticket. Thanks!
