### ISSUE TITLE
Missing active class on the header links

### ISSUE THREAD

**Issue by vjeux** [facebook/Docusaurus#178]
I want to highlight the header section which is currently active but there's no indication right now.

Example on the RN website:
![image](https://user-images.githubusercontent.com/197597/31976446-79020f6e-b8ec-11e7-880c-686b644d19db.png)

**Comment by wulucxy** [comment]
@rickyvetter do you have any plan to get this feature done? I think this is something need to be done as soon as posible

**Comment by JoelMarcey** [comment]
https://github.com/facebook/Docusaurus/pull/463 should fix this. I will review that soon.
