### ISSUE TITLE
react-loadable module in v2.0, failed in ie11 with Object doesn't support property or method 'assign'

### ISSUE THREAD

**Issue by BurdenBear** [facebook/docusaurus#1784]
## 🐛 Bug Report

(A clear and concise description of what the bug is)

react-loadable module in docusaurus V2.0 failed in ie11 with exception:
Object doesn't support property or method 'assign'

![image](https://user-images.githubusercontent.com/5682650/64909933-4fea1680-d744-11e9-8211-8fbc2a11e22a.png)

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

yes

## To Reproduce

1. create a project with docusauras
2. start the project and visit the index page

## Expected behavior
the index page is rendered properly
![image](https://user-images.githubusercontent.com/5682650/64910121-11edf200-d746-11e9-912d-36f9c3d23481.png)

## Actual Behavior
the index page was not rendered, and there is a exception report in debug console.

![image](https://user-images.githubusercontent.com/5682650/64910192-3b0e8280-d746-11e9-8d1a-6a0d85fad79b.png)

## Reproducible Demo
online demo:  https://www.10studio.tech
which is power by docusaurus V2.0

## Question
There are some package to provide ie compatibility such like `core-js`, but I don't know how to properly add it in docusaurus v2.0

**Comment by Tranced** [comment]
@endiliey I was just wondering if I could take this on!

**Comment by endiliey** [comment]
sure thing @Tranced

**Comment by andresmanelli** [comment]
@Tranced  @BurdenBear I added #1808 to try to resolve this, maybe you can take a look. Thanks!
