### ISSUE TITLE
DocSearch meta missing from the new released version

### ISSUE THREAD

**Issue by s-pace** [facebook/docusaurus#1792]
## 🐛 Bug Report

I am part of the team from [algolia/Docsearch](https://github.com/algolia/docsearch) which features search for Docusaurus. We [rely on meta tags to pick up the right version from the pages generated](https://community.algolia.com/docsearch/required-configuration.html#introduces-global-information-as-meta-tags) by Docusaurus. The v2 does not include these meta tags anymore. The Algolia search experience will be broken due to duplicates for every websites we crawl

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

yes
## To Reproduce

(Write your steps here:)

1. Go on https://v2.docusaurus.io/docs/introduction or any website generated thanks to the latest v2 version of docusaurus
2. Inspect the DOM
3. Search for these meta tags within the DOM
```html
<meta name="docsearch:language" content="en" />
<meta name="docsearch:version" content="2.0.0" />
```
3. None of these variables are available

## Expected behavior

Docusaurus should include these meta tags

Same as https://github.com/facebook/docusaurus/commit/0eb6612b58a6ee93d5de715f87201eb9fabc82c2

My guess is that this issue is due to the latest release of Docusaurus.

Happy to provide more details if needed.

cc @endiliey @JoelMarcey

**Comment by JoelMarcey** [comment]
HI @yangshun - did we decide to remove these meta tags purposely or just not implemented yet?

**Comment by yangshun** [comment]
I think it's more of the latter. We will need them back eventually.

**Comment by nebrelbug** [comment]
@yangshun would it help if I put together a pull request? I'd really like to have these merged so I can add search on my site :smile:

**Comment by yangshun** [comment]
@nebrelbug Sure but I don't exactly know what the correct fix should be (because I'm not familiar with Algolia). I initially thought this wasn't necessary because v2 doesn't have versioning yet, so there cannot be multiple versions of Algolia for a site.

cc @endiliey

**Comment by nebrelbug** [comment]
Ah, right. @s-pace what needs to be done to fix this?

Also @yangshun, do you have a rough estimate of when versioning will be added?

**Comment by s-pace** [comment]
We need a page of version `x` and language `lang` to include the following meta tags:

```html
<meta name="docsearch:language" content="lang" />
<meta name="docsearch:version" content="x" />
```

This should be implemented at the same time as versioning then :)

**Comment by endiliey** [comment]
Will leave this open for now to serve as reminder

**Comment by endiliey** [comment]
its done like this however https://v2.docusaurus.io/docs/docusaurus-core#head-
