### ISSUE TITLE
Add canonical meta data to avoid duplicate content when versioning

### ISSUE THREAD

**Issue by aeneasr** [facebook/docusaurus#1793]
## 🚀 Feature

Right now, multiple versions will cause duplicate content which is an issue for most search engines. The solution is to provide a canonical URL in the head section as described [here](https://support.google.com/webmasters/answer/139066?hl=en). This would tell the search engine to always link to this page.

The canonical link should always link to the current master.

To prevent documents that actually have changed to have canonical links, Docusaurus should only mark those pages with canonical that have actually changed.

## Have you read the [Contributing Guidelines on issues](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

yes

## Motivation

Improve searchability, SEO, and link developers to the most recent docs version when coming from a search engine.

## Pitch

This is an important and trivial change. It does not introduce any backwards compatibility issues and it will help search engines in returning better search results. It will help website providers by improving their SEO (duplicate content is a no-no) and it will also help users because they will never land on an outdated or older version of the documentation.

**Comment by endiliey** [comment]
But if the content is different, its a misnomer to link to the master version.

**Comment by aeneasr** [comment]
So what other strategy would you suggest? For our domain www.ory.sh/docs we have 219 affected pages and that is very visibly hurting our SERPs.

**Comment by endiliey** [comment]
I cant give perfect solution, but I can say that if this is implemented, it can lead to wrong search result. Example:

There are version 1 and 2 of docs "siteconfig"

in v1, field "blogsidebarcount" exist
in v2, that field is deprecated.

If we use canonical url, those that searched blogsidebarcount might got linked to v2 docs and its a misnomer.

**Comment by endiliey** [comment]
Furthermore, the algolia search might have inaccurate result. Notice that currently it can search based on version. Canonical url will make it link to wrong url

**Comment by aeneasr** [comment]
Is Algolia respecting canonical in the HTML search result? I thought it works different by indexing the raw content directly.

**Comment by aeneasr** [comment]
This could also be an opt-in feature by the way. Or even better, docusaurus could detect (it does that already) what documents have changed and only add canonical link to those that have actually changed. I don't really see how this could not be a good idea?

**Comment by endiliey** [comment]
> Is Algolia respecting canonical in the HTML search result? I thought it works different by indexing the raw content directly.

yes algolia respect canonical meta tag. 

Currently, without canonical url i can be specific on version search through google.
![image](https://user-images.githubusercontent.com/17883920/65156008-7d8ed280-da58-11e9-97aa-f8d4f55f0f1c.png)

I personally feel google's way of grouping similar content is not that bad though
![image](https://user-images.githubusercontent.com/17883920/65156339-1e7d8d80-da59-11e9-8bb7-f5e36ee079cd.png)

> docusaurus could detect (it does that already) what documents have changed and only add canonical link to those that have actually changed. I don't really see how this could not be a good idea?

It can be opt-in, PR welcome 😉.

**Comment by aeneasr** [comment]
I will unfortunately not be able to provide a PR in the near future.

I agree with your sentiment on version search, but I think linking to the most recent version if no changes have been made. The posted screenshots are actually a good example - see the duplicate result in your second screen? That's something that google and other search engines like to penalize. I'm not sure what has caused this exactly (the urls seem to be identical) but this is something that can happen when there's lots of duplicate content.

**Comment by endiliey** [comment]
Sorry, but we're not going forward with this.
