### ISSUE TITLE
Broken links moving files on versioned documentation

### ISSUE THREAD

**Issue by defio** [facebook/docusaurus#1794]
## 🐛 Bug Report

Using the versioning. When a file is moved from one directory to another in all past versions the links to that file are broken 

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

yes

## To Reproduce

1.  docusaurus-init
2. add a folder `sub1` with two files `inner1.md` and `inner2.md`
```
root-directory
├── Dockerfile
├── README.md
├── docker-compose.yml
├── docs
│   ├── sub1
│   │  ├── inner1.md
│   │  └── inner2.md
│   ├── doc1.md
│   ├── doc2.md
│   ├── doc3.md

... the rest of the tree is the same of the https://docusaurus.io/docs/en/installation#verifying-installation
```
3. in `doc1.md` link to `inner1.dm` and `inner2.md`

doc1.md:
```
---
id: doc1
title: Latin-ish
sidebar_label: Example Page
---

Go to [inner 1](sub1/inner1.md)

Go to [inner 2](sub2/inner2.md)
```

inner1.md:
```
---
id: inner-1
title: Inner1
---

Hi, I'm in the sub1 dir
```

inner2.md:
```
---
id: inner-2
title: Inner2
---

Hi, I'm in the sub1 dir
```

4. make a version 
```
cd website
yarn examples versions
yarn run version 1.0.0
```

5. move `inner2.md` in a new folder `sub2`
```
root-directory
├── Dockerfile
├── README.md
├── docker-compose.yml
├── docs
│   ├── sub1
│   │  └── inner1.md
│   ├── sub2
│   │  └── inner2.md
│   ├── doc1.md
│   ├── doc2.md
│   ├── doc3.md
```

## Expected behavior

I expect that clicking on "Go to inner2" from http://localhost:3000/docs/doc1 will open the inner2 page, just like on http://localhost:3000/docs/next/doc1

## Actual Behavior

clicking on "Go to inner2" from http://localhost:3000/docs/doc1 I got a bad link:

`Cannot GET /docs/sub1/inner2.md`

## Reproducible Demo

https://github.com/defio/docusaurus-broken-link

1. check-out the repo
2. `cd website`
3. `yarn start`
4. click on "example link" (central button) or go to http://localhost:3000/docs/doc1.html
5. click on "Go to inner 2"
6. 💥 `Cannot GET /docs/sub1/inner2.md`

**Comment by endiliey** [comment]
I think there's some inaccuracy here.

According to
https://raw.githubusercontent.com/defio/docusaurus-broken-link/master/website/versioned_docs/version-1.0/doc1.md

the content was

```md
---
id: version-1.0-doc1
title: Latin-ish
sidebar_label: Example Page
original_id: doc1
---

Go to [inner 1](sub1/inner1.md)

Go to [inner 2](sub1/inner2.md)
```

Notice that its not `Go to [inner 2](sub2/inner2.md)` as you've described

https://raw.githubusercontent.com/defio/docusaurus-broken-link/master/docs/doc1.md

**Comment by endiliey** [comment]
Well actually that doesn't matter much but the reproduce step isnt accurate.

This is related to https://github.com/facebook/docusaurus/issues/845#issuecomment-404787152
Marking as duplicate. See more on that for details

There is no easy fix for this, I suggest maintaining the structure of the docs that has same id in different version
