### ISSUE TITLE
click on the title in the sidebar to expand and hide.

### ISSUE THREAD

**Issue by prasathsekar** [facebook/docusaurus#1799]
How to Expand and hide title of sidebar in docusaurus v2.

I have installed docusaurus V2. And the sidebar has 2- 3 categories. 

But when i go to next category still the existing category list is opened.

I need a menu in the sidebar category section like expand and hide.

Check the images uploaded.

The first image is what i had done.

But i need like a second image.

**Comment by endiliey** [comment]
not implemented. Swizzle sidebar component if u want to customize it on ur own

**Comment by endiliey** [comment]
Closed b
