### ISSUE TITLE
'autoreconf' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by kristofferjalen** [facebook/docusaurus#1804]
Installation fails due to gifsicle requiring `autoreconf` not available on Windows.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes.

## To Reproduce

`npm install docusaurus`

## Expected behavior
Installation succesful.

## Actual Behavior

```
...
> gifsicle@4.0.1 postinstall C:\temp\docusaurus\node_modules\gifsicle
> node lib/install.js

  ‼ self signed certificate in certificate chain
  ‼ gifsicle pre-build test failed
  i compiling from source
  × Error: Command failed: C:\WINDOWS\system32\cmd.exe /s /c "autoreconf -ivf"
'autoreconf' is not recognized as an internal or external command,
operable program or batch file.
...
```

**Comment by endiliey** [comment]
I couldn't reproduce. From the log, its most likely environment problem, we can't do anything from our side to fix it. 

You should open an issue with gifsicle if you think they are doing something incorrectly.

**Comment by endiliey** [comment]
What is your environment ? try `npx envinfo` and copy the result.

**Comment by kristofferjalen** [comment]
This seems to be related to #1758. I'm behind a corporate proxy, which seems block a process in the postinstallation script of gifsicle in which something is downloaded from GitHub. As a fallback gifsicle then compiles from source instead, throwing an error because it uses an executable that not exists on Windows. 

I realize it's not for docusaurus to fix, but maybe it could be an idea to review if this dependency is actually needed? Because as of now docusaurus can't be installed by users behind corporate proxys, at least not by me.

References:
- https://github.com/imagemin/gifsicle-bin/issues/52
- https://github.com/imagemin/gifsicle-bin/issues/79
- https://github.com/imagemin/gifsicle-bin/issues/102

**Comment by endiliey** [comment]
You might consider a fork to remove imagemin. We definitely need it to optimize the image. Removing it would mean breaking changes.

**Comment by kristofferjalen** [comment]
Ok, I understand. I close the ticket then. Thanks.

**Comment by xianghongai** [comment]
gifsicle pre-build test failed

```bash
[4/4] Building fresh packages...
[-/6] ⠠ waiting...                                                                                                                                                      [6/6] ⠠ optipng-bin                                                                                                                                                     [-/6] ⠐ waiting...                                                                                                                                                      [4/6] ⠐ gifsicle                                                                                                                                                        error D:\ctms\node_modules\gifsicle: Command failed.
Exit code: 1
Command: node lib/install.js
Arguments:
Directory: D:\ctms\node_modules\gifsicle
Output:
‼ read ECONNRESET
  ‼ gifsicle pre-build test failed
  i compiling from source
  × Error: Command failed: C:\WINDOWS\system32\cmd.exe /s /c "autoreconf -ivf"
'autoreconf' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���
```

![gifsicle](https://user-images.githubusercontent.com/2075006/74698218-0a240380-5238-11ea-9709-4e48bb56d413.png)

**Comment by oo10** [comment]
I have the same problem. How can you solve it?

**Comment by Lumersgo** [comment]
In my case, 3 steps  solved this problem.
- set http_proxy=http://127.0.0.1:1080
set https_proxy=http://127.0.0.1:1080
- add 199.232.4.133 raw.githubusercontent.com to hosts files.
- cmd.exe  ipconfig/flushdns

**Comment by Hanhan93** [comment]
> 就我而言，只需3个步骤即可解决此问题。
> 
> * 设置http_proxy = http://127.0.0.1:1080 
>   设置https_proxy = http://127.0.0.1:1080
> * 将199.232.4.133 raw.githubusercontent.com添加到主机文件。
> * cmd.exe ipconfig / flushdns

能具体说说每步要执行的命令吗，新手，万分感谢

**Comment by Hanhan93** [comment]
> In my case, 3 steps solved this problem.
> 
> * set http_proxy=http://127.0.0.1:1080
>   set https_proxy=http://127.0.0.1:1080
> * add 199.232.4.133 raw.githubusercontent.com to hosts files.
> * cmd.exe  ipconfig/flushdns

Can you tell me the specific commands to be executed in each step？thank you very much

**Comment by z970445720** [comment]
You can try to use cnpm of Taobao mirror：
1、npm install -g cnpm --registry=https://registry.npm.taobao.org
2、cnpm i -g gifsicle

**Comment by Lumersgo** [comment]
> > In my case, 3 steps solved this problem.
> > 
> > * set http_proxy=http://127.0.0.1:1080
> >   set https_proxy=http://127.0.0.1:1080
> > * add 199.232.4.133 raw.githubusercontent.com to hosts files.
> > * cmd.exe  ipconfig/flushdns
> 
> Can you tell me the specific commands to be executed in each step？thank you very much

- First step use command.exe

**Comment by laoxubuer** [comment]
install automake for windows resolve this problem for me
[http://gnuwin32.sourceforge.net/packages/automake.htm](url)
