### ISSUE TITLE
Can't find a "Create minimal site" command

### ISSUE THREAD

**Issue by tomcam** [facebook/docusaurus#1807]
` docusaurus-init` creates sample website/blog with a complete tree sample markdown files, blog source, and so on. I imagine there's some way to ` docusaurus-stub` that would output the minimum `/website directory`, empty `/website/README.md`, , minimum `package.json`, minimum `siteConfig.js` and so forth. What is that command?

Or if it doesn't exist am I simply expected to run ` docusaurus-init` and just delete what I don't need?

**Comment by endiliey** [comment]
Run the Docusaurus installation script: `npx docusaurus-init`

 or if you prefer to install Docusaurus globally, run `yarn global add docusaurus-init` or `npm install --global docusaurus-init` After that, run `docusaurus-init`

**Comment by tomcam** [comment]
Is there an option to create a minimal site?

**Comment by endiliey** [comment]
None.

**Comment by endiliey** [comment]
None.

**Comment by tomcam** [comment]
OK thanks.

**Comment by yangshun** [comment]
@tomcam There aren't too many files to delete and they will help you understand the structure better in case you need them in future. Let us know if we can be of any assistance!

**Comment by tomcam** [comment]
Really appreciate it, Yangshun Tay. Thanks tons!
