### ISSUE TITLE
CleanUrl Small Suggestion

### ISSUE THREAD

**Issue by lexaBear42** [facebook/docusaurus#1824]
## 📚 Documentation

A small suggestion: I am using Docusaurus to create a static documentation page for work. Because it will ultimately not be hosted I have run into a couple issues trying to use the built site statically. My suggestion is simply to add a clarification to the documentation (https://docusaurus.io/docs/en/site-config#cleanurl-boolean) that lets users know to set the cleanUrl variable to false if they plan to use the site offline. Currently cleanUrl true will break page links in your site, only taking users to the parent folder of the linked page.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes.

**Comment by EricPonvelle** [comment]
I created this pull request, but I am waiting for the team to validate my contribution - https://github.com/facebook/docusaurus/pull/1847

Until then, can you review and let me know if that's clear enough? This is a great edge case.

**Comment by lexaBear42** [comment]
@EricPonvelle This looks great! Thanks so much for addressing it ^.^
