### ISSUE TITLE
Code block with language tabs

### ISSUE THREAD

**Issue by murugancmi** [facebook/docusaurus#1825]
I am using docusaurus V2.

My project consists of four programming languages like python, php, java, nodejs.

If use Language-specific Code Tabs 

![2](https://user-images.githubusercontent.com/25261553/66539259-0cb57480-eb45-11e9-900a-098e6b5e690c.png)

I am getting the following output shown in the image.

![1](https://user-images.githubusercontent.com/25261553/66539094-944eb380-eb44-11e9-8e1b-1a24e8ea4d6a.png)

i cannot able to use multi-language tab.

Is there any other way to add the multi-language tab.

**Comment by yangshun** [comment]
We haven't built out that feature yet. We'll be working on it.

**Comment by endiliey** [comment]
See #1836
