### ISSUE TITLE
Unable to add custom url to logo

### ISSUE THREAD

**Issue by prasathsekar** [facebook/docusaurus#1827]
Hi i am using docusaurus v2.

i am having an issue in forwarding the custom url to the logo.

When clicking the logo at the top left corner it is always forwarded to the home page.

But i need a custom url to forward.

i have used the following code in docusaurus.config.js

logo: {
        alt: 'logo',
        src: 'img/logo.svg',
      }, 

Tell is there any other way to forward my custom url in the logo

**Comment by endiliey** [comment]
Not doable。Swizzle your navbar for your own custom behavior. Note that our issue tracker is not a help forum, use the right channel like Discord instead.

Closed because not following issue template
