### ISSUE TITLE
[v2] make https://v2.docusaurus.io/showcase/ nicer

### ISSUE THREAD

**Issue by endiliey** [facebook/docusaurus#1850]
**Tip: This task is targeted towards potential contributor to Docusaurus project.**

## 🚀 Motivation

Prerequisites
- Reactjs
- HTML
- CSS
- JavaScript

Currently, our showcase https://v2.docusaurus.io/showcase/ show the landing page preview of our v2 user, but I think its not a good idea because landing page of our user can keep changing. Example:

https://uniforms.tools/ looks like this in our showcase

![image](https://user-images.githubusercontent.com/17883920/66977044-6df1c080-f0ce-11e9-8b15-f73405cb00f6.png)

but its no longer the case
![image](https://user-images.githubusercontent.com/17883920/66977054-7b0eaf80-f0ce-11e9-8acf-3f13fa570a1e.png)
 
I think it will be nice to make the site nicer

# Where to start

1. Fork [the repository](https://github.com/facebook/docusaurus) and create your branch from `master`.
1. Clone the repository
1. yarn install in the root of the repo
1. To run docusaurus 2 website, run `yarn start` at root
1. Edit https://github.com/facebook/docusaurus/tree/master/website/src/pages/showcase
1. Propose a fix and send a Pull Request :)

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

**Comment by jyangchisyan** [comment]
Hi @endiliey Could I pick up this issue? :)

**Comment by endiliey** [comment]
@jyangchisyan sure thing. Just send a PR, we will take a look later on and merge it if its looking good.

**Comment by endiliey** [comment]
@jyangchisyan how do you plan to revamp it ? we might not want it to be logo, we just want it to be nicer.

**Comment by endiliey** [comment]
Sorry for the confusion. We are not going ahead to change it to logo after some internal discussion. No need to work on it anymore

**Comment by jyangchisyan** [comment]
> Sorry for the confusion. We are not going ahead to change it to logo after some internal discussion. No need to work on it anymore

It's fine, hope the project better : )
