### ISSUE TITLE
Hash link not properly generated / encoded

### ISSUE THREAD

**Issue by pedroscaff** [facebook/docusaurus#1877]
## 🐛 Bug Report

If a doc page with a `<h1>` tag that contains, for example, a `&` character, the hash link (`href`) is not properly generated in the right-side bar.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes.

## To Reproduce

1. Doc page with a
```markdown
## Pause & Resume
...
```

## Expected behavior

The generated `href` matches and works when clicked.

## Actual Behavior

In the generated `<h2>` tag:

`<a href="#pause-resume" aria-hidden="true" class="hash-link">...</a>`

In the right-side bar:

`<a href="#pause-amp-resume">Pause &amp; Resume</a>`

## Reproducible Demo

I found out the issue when opening this [PR](https://github.com/tulios/kafkajs/pull/530), it can be seen in https://kafka.js.org/docs/consuming#pause-amp-resume.

**Comment by parvezakkas** [comment]
This issue can also been seen in docusaurus site right now. Try the following link:

https://docusaurus.io/docs/en/publishing#tips-amp-tricks

The above link is generated by the table of content on the right side. The correct link is:

https://docusaurus.io/docs/en/publishing#tips-tricks
