### ISSUE TITLE
Configurable syntax highlighting languages

### ISSUE THREAD

**Issue by bravo-kernel** [facebook/docusaurus#1879]
I am creating this ticket for v2 after discussing with @endiliey to start the discussion (ping @langpavel).

## 🚀 Feature

Extend `docusaurus.config.js` so users can easily add/remove prismjs syntax highlighting languages. 

## Motivation

Currently:
- docusaurus ships with a hard-coded set of 32 languages (out of 192) enforced by [prism-react-renderer](https://github.com/FormidableLabs/prism-react-renderer/blob/master/src/vendor/prism/includeLangs.js)
-  the solution makes it hard to add additional languages, see:
    - install prismjs package
    - swizzle CodeBlock component
    - update code as described in these [docs](https://v2.docusaurus.io/docs/markdown-features#syntax-highlighting)

## Pitch

Should be implemented so that:
- Docusaurus can be used for documenting all-the-things
- the Docusaurus project can control the list of default languages, possibly even decreasing the default bundle size

## Pre-discussed

The solution could be something like:

- add prismjs to `package.json`
- only add languages that are present in the configuration file to the build/bundle
- because the `CodeBlock` component already falls back to "plain" if the language is not available, possibly no changes needed there

**Comment by bravo-kernel** [comment]
Closing this request based on received feedback; will not be implemented as swizzling the code block is a proper alternative.

**Comment by bravo-kernel** [comment]
Wow, I had no idea this was being worked on. Amazing surprise 🎉

**Comment by yangshun** [comment]
All thanks to @lex111 who does all the amazing work!
