### ISSUE TITLE
Interactive Demo

### ISSUE THREAD

**Issue by itelo** [facebook/docusaurus#1881]
## 🚀 Feature

The interactive demo lets users explore the visual results of the different props passed, like [Material-ui Grid](https://material-ui.com/components/grid/#interactive)

![image](https://user-images.githubusercontent.com/11433064/67534525-ddeee080-f6a4-11e9-8d85-ee7e7fa4f428.png)

## Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?
yes

## Pitch

In React Native documentation, at [Layout with Flexbox](https://facebook.github.io/react-native/docs/flexbox#flex-direction) section, we have the perfect example of why this is important. Although the documentation is great we have screenshots of possible states, It would be nicer if we have the interactive demo that allows the user to change that and see in the difference in real-time.

**Comment by endiliey** [comment]
You can already import JSX in Markdown for v2, so this is already achievable. Its all up to user's creativity :)

For example:
https://uniforms.tools/docs/examples-custom-fields
https://uniforms.tools/docs/examples-custom-fields/#imagefield

**Comment by itelo** [comment]
hey @endiliey, based on the examples you give to me I created this: 
![image](https://user-images.githubusercontent.com/11433064/68296388-42ca1380-0073-11ea-85c6-110170048429.png)

In mdx, the code is:

![image](https://user-images.githubusercontent.com/11433064/68296559-a6ecd780-0073-11ea-8da5-1b0fb869f8d8.png)

Is it interesting as a plugin or something like that to docusaurus? if so I could work on it.

**Comment by endiliey** [comment]
Hmm well its not really a plugin i think. Its just normal jsx import :)
