### ISSUE TITLE
doc(v2): Package useBaseUrl is documented while not available

### ISSUE THREAD

**Issue by s-pace** [facebook/docusaurus#1886]
## 📚 Documentation

The [v2 documentation](https://v2.docusaurus.io/docs/static-assets/#jsx-example) states that one can import the following package `@docusaurus/useBaseUrl`. This package is not publicly available.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?
Yes

I have checked if this package is available from yarn. It seems that this package is missing.

Any ETA regarding this package to be publicly available?

Thank all for this amazing project 🚀

**Comment by endiliey** [comment]
@s-pace it's actually an alias to https://github.com/facebook/docusaurus/blob/master/packages/docusaurus/src/client/exports/useBaseUrl.js

For alpha <=27 its named `withBaseUrl`

I suggest updating to alpha.30 and `Watch for releases` in our repository
https://github.com/facebook/docusaurus/releases
https://github.com/facebook/docusaurus/blob/master/CHANGELOG-2.x.md

**Comment by s-pace** [comment]
Thanks @endiliey
