### ISSUE TITLE
Multiple block quotes don't have line breaks

### ISSUE THREAD

**Issue by shinxi** [facebook/docusaurus#1897]
## 🐛 Bug Report

There's no line break between 2 block quotes.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## To Reproduce

```md
> 1st block quotes
> 2rd block quotes
```

## Expected behavior

> 1st block quotes
> 2rd block quotes

## Actual Behavior

![image](https://user-images.githubusercontent.com/1262296/67630048-33e9a100-f8bc-11e9-9c30-2047f950342a.png)

**Comment by parvezakkas** [comment]
I don't think this is a docusaurus issue. I believe this is how the markdown parser underneath that's generating this result. Try your sample markdown in the following markdown renderer by remarkable:

https://jonschlinkert.github.io/remarkable/demo/

You'll notice that you get the same result as the screenshot in your "Actual Behaviour"

**Comment by endiliey** [comment]
Report to remarkable if you think it's a bug. I think it's indeed expected behavior
