### ISSUE TITLE
Redirect to docs from index page. 

### ISSUE THREAD

**Issue by marujart** [facebook/docusaurus#1932]
Since I don't have a landing page, I would like to redirect to the main doc page `docs/main`
I tried to follow the instructions: https://docusaurus.io/docs/en/site-creation#docs-landing-page
from v1, but they dont seem to work for v2. 
Can someone please give me instructions on how to accomplish this? 
I have very limited experience with React. 
THANK YOU!

**Comment by wgao19** [comment]
One way I think of doing this is to imperatively redirect in `pages/index.js`:

```jsx
function Home() {
  React.useEffect(() => {
    window.location.href = '/docs/main';
  }, []);
  return null;
}
```

**Comment by yangshun** [comment]
Be sure to add the `baseUrl` via `useBaseUrl` just to be more robust.

Alternatively, use the `<Redirect>` component: https://v2.docusaurus.io/docs/docusaurus-core#redirect-

**Comment by endiliey** [comment]
The best way is to actually create `index.html` file in `static` folder that redirect like https://docusaurus.io/docs/en/site-creation#docs-landing-page

Above approach works well but will require you to download all the JS first (including React)
