### ISSUE TITLE
amp anchor conversion in sidebar

### ISSUE THREAD

**Issue by sundowndev** [facebook/docusaurus#1939]
## 🐛 Bug Report

The following markdown header in docs : `## Tips & Tricks` renders an anchors like `#tips-tricks`. But the same title in the generated sidebar renders an anchors like `#tips-amp-tricks`.

## To Reproduce

Example

https://docusaurus.io/docs/en/publishing#tips-tricks

**Comment by parvezakkas** [comment]
This is a duplicate of issue #1877

**Comment by sundowndev** [comment]
Never mind, thank you for pointing this out!
