### ISSUE TITLE
Docs index page and navbar highlighting

### ISSUE THREAD

**Issue by binarylogic** [facebook/docusaurus#1941]
## 🐛 Bug Report

Note, this is for V2.

Currently, the `themeConfig.navbar.links` array requires that the `"Docs"` refer to an individual document. While this works there are 2 problems:

1. Users navigating to just `/docs` get a 404.
2. The `"Docs"` navbar item does not remain highlighted if the user navigates around to other pages with in the Docs section.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## To Reproduce

(Write your steps here:)

1. Go here: https://v2.docusaurus.io/docs/
1. Notice when you change pages the "Docs" navbar item is not "active". Ex: https://v2.docusaurus.io/docs/contributing

## Expected behavior

1. `/docs` should render `docs/index.md` or redirect to a specificed document.
2. The navbar item remains active as long as you are in the `/docs` sectiono.

## Actual Behavior

See above.

## Reproducible Demo

See above

**Comment by endiliey** [comment]
I don't think its a bug. The thing is, `themeConfig.navbar.links` is just a helper for you to link to internal pages, and "Docs" is just a **Label**.

In docusaurus, it is possible to have multiple sidebars. See https://v2.docusaurus.io/docs/sidebar
Example:
```js
// sidebars.js
module.exports = {
  docs: {
    Docusaurus: ['introduction', 'design-principles', 'contributing'],
    'Getting Started': ['installation', 'configuration'],
  },
  "API": {
    'API Reference': [
      'cli',
      'docusaurus-core',
      'docusaurus.config.js',
      'lifecycle-apis',
    ],
  },
};
```

I could change my  `themeConfig.navbar.links` to
```js
// docusaurus/config.js
module.exports = {
  themeConfig: {
    navbar: {
      links: [
        {to: 'docs/introduction', label: 'Introduction', position: 'left'},
        {to: 'docs/cli', label: 'API', position: 'left'},
        // ... other links
      ],
    }
}
```

Which yields accessing /docs/introduction
<img width="958" alt="1" src="https://user-images.githubusercontent.com/17883920/68274736-7c634480-009c-11ea-99e1-55659012eab1.PNG">

/docs/cli
<img width="955" alt="2" src="https://user-images.githubusercontent.com/17883920/68274737-7cfbdb00-009c-11ea-9f27-f829f77e652c.PNG">

It's gonna be weird if i go to /docs/cli, both Navbar `introduction` and `API` is highlighted

**Comment by binarylogic** [comment]
Thanks. I understand your example but is anyone actually doing that? It seems like you're favoring an edge case at the expense of sacrificing the commonly desired behavior. A _much_ better solution to your example would be a sub-menu under docs. Ex:

```
- Docs (/docs)
   - Introduction (/docs/introduction)
   - API (/docs/api)
```

It appears [Infima supports this](https://infima-dev.netlify.com/), and I noticed it is a [feedback request](https://v2.docusaurus.io/feedback/p/navbar-item-dropdown-support).

It's typically best practice for the navigation organization to follow the URL structure.

Does that make sense? Do you agree?

**Comment by binarylogic** [comment]
Oh, and it's still not clear how I can enable the `/docs` route, even if that's just redirecting to another page. Having `/docs` `404` is a pretty poor user experience.

**Comment by endiliey** [comment]
I guess the main problem is more on **how to create** `/docs` route. 

Because if `/docs` exist.
```js
{to: 'docs', label: 'Docs', position: 'left'},
```

Will always be highlighted when you are in `/docs/introduction` for example. Our navbar highlighting is powered by react-router NavLink.

You might want to wait https://github.com/facebook/docusaurus/pull/1946 to land first before you can actually create `/docs` on your own even if its a redirect
