### ISSUE TITLE
Custom prism theme is overridden by theme-live-codeblock

### ISSUE THREAD

**Issue by muwenzi** [facebook/docusaurus#1949]
## 🐛 Bug Report

custom prism theme configured in `docusaurus.config.js `will be overridden by theme-live-codeblock.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## To Reproduce

in `docusaurus.config.js`: 

```
themes: ['@docusaurus/theme-live-codeblock'],
themeConfig: {
   prism: {
      theme: require('prism-react-renderer/themes/nightOwl')
    }
}
```

## Expected behavior

The theme of code blocks should be `nightOwl`

## Actual Behavior

The theme of code blocks including live code block will be overridden by the internal theme of theme-live-codeblock.

**Comment by endiliey** [comment]
Upgrade your theme-live-codeblock version to alpha.33 

alpha.32 still uses the old `prismTheme`
