### ISSUE TITLE
Lifecycle API documentation missing getBabelLoader utility function

### ISSUE THREAD

**Issue by jamiedavenport** [facebook/docusaurus#1960]
## 📚 Documentation

At https://v2.docusaurus.io/docs/lifecycle-apis/#utils, the documentation has `getCacheLoader` twice as arguments passed to `configureWebpack` and `getBabelLoader` is missing.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

I'd be happy to open a PR for this small fix.

**Comment by lex111** [comment]
> I'd be happy to open a PR for this small fix.

We look forward to your PR!

**Comment by lex111** [comment]
Resolved in #1970
