### ISSUE TITLE
tagline and favicon should not be required fields

### ISSUE THREAD

**Issue by endiliey** [facebook/docusaurus#1969]
## 💥 Proposal

Consider making https://v2.docusaurus.io/docs/docusaurus.config.js#tagline and https://v2.docusaurus.io/docs/docusaurus.config.js#favicon as part of themeConfig and not as required fields

In v1, it has to be required field because a lot of the React components need it and all the UI is locked-in. This is no longer the case in v2, i think its very coupled to theme-classic and this can make the config smaller.

P.S this is breaking change but should be fine ??? Thoughts ?

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

yes

**Comment by krishnanunnir** [comment]
Can I work on this issue?

**Comment by endiliey** [comment]
what do you think of this @yangshun @wgao19 @lex111 ? before we move forward

**Comment by lex111** [comment]
@endiliey I would make favicon a required field, and tagline - optional, but not both of them.

**Comment by wgao19** [comment]
im not sure about favicon, but i agree tagline should be optional.
