### ISSUE TITLE
Update Brand Tagline

### ISSUE THREAD

**Issue by ericcarboni** [facebook/docusaurus#1972]
## 💥 Proposal
Per [this comment](https://github.com/facebook/docusaurus/pull/1961#pullrequestreview-315184185) on a recent PR (https://github.com/facebook/docusaurus/pull/1961), I'm proposing we update the main Docusaurus tagline to make it more inclusive for the entire community. While I agree that it is easier to build pages with Docusaurus, the language could make people feel frustrated or isolated when they see those references, especially if they are facing or have faced issues before. 

>Docusaurus makes it easy to maintain Open Source documentation websites.

I think it would be great if we could come up with something more inclusive for v2 🤘 

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes 🦖

**Comment by yangshun** [comment]
In D2, we thought of dropping documentation from the tagline, because D2 is now a platform and can be used to build very generic websites, not just documentation.

Some similar taglines for inspiration:

> Gatsby is a free and open source framework based on React that helps developers build blazing fast websites and apps

> Production grade React applications that scale. The world’s leading companies use Next.js to build server-rendered applications, static websites, and more.

My proposal:

> Docusaurus helps you to build websites fast, allowing you to focus on your content.

cc @JoelMarcey

**Comment by ericcarboni** [comment]
Interesting! What about--

>Docusaurus helps you to build **powerful** websites quickly, **enabling** you to focus on your content

Bolded changes

**Comment by JoelMarcey** [comment]
I am good with something along the lines of the proposals from @yangshun or @ericcarboni

**Comment by yangshun** [comment]
I like "Docusaurus helps you to build powerful websites quickly, enabling you to focus on your content". Thoughts? @endiliey @wgao19 @lex111

**Comment by endiliey** [comment]
i like “Docusaurus helps you to build powerful websites quickly, enabling you to focus on your content” but after some thinking, what do we mean by “powerful”. Calling website “powerful” sounds weird to me 😆

“maintainable” or “stable” could be right (but the word isnt fancy enough)

how about “effective” or “efficient” 😱😅😅😅🤣🤣

**Comment by endiliey** [comment]
long-lasting :)

**Comment by yangshun** [comment]
I think let's go with something like "optimized websites"?
