### ISSUE TITLE
Cannot link directly to doc in sidebar

### ISSUE THREAD

**Issue by flaurida** [facebook/docusaurus#1993]
## 🐛Cannot link directly to doc in sidebar

I am trying to link to a doc directly in the sidebar per the [v2 documentation](https://v2.docusaurus.io/docs/sidebar#doc). 

## To Reproduce

(Write your steps here:)

1. Add doc link in `sidebars.js` code

```js
module.exports = {
  docs: [
    {
      type: "category",
      label: "Get Started",
      items: ["get_started"]
    },
    { 
     type: "doc",
     id: "api"
    }
  ]
};
```

2. Run `npm run start`

## Expected behavior

No compile errors, we see the link directly to the doc in the sidebar.

## Actual Behavior

It will not compile, see this error in console:

`Error: Unknown sidebar item keys: id. Item: {"type":"doc","id":"api"}`

**Comment by endiliey** [comment]
You can't do that.

First level of a sidebar name `docs` must be category

```js
// sidebars.js
module.exports = {
  docs: [
    {
      type: 'category',
      label: 'Getting Started',
      items: ['greeting'],
    },
    {
      type: 'category',
      label: 'Docusaurus',
      items: ['doc1'],
    },
  ],
};
```

We should update the docs or at least do better in the error handling i guess

**Comment by flaurida** [comment]
Oh OK, thanks for clarifying!

**Comment by endiliey** [comment]
Thank you. We'll warn it to user better in #1994

**Comment by flaurida** [comment]
Appreciate the quick follow up 🎉

**Comment by binarylogic** [comment]
I actually disagree with this behavior. Why can't a category be a page? A side effect of this is that parent URLs don't work. Ex:  `/docs/category/child`, the URL `/docs/category` returns a 404.

Related general URL issues: https://github.com/facebook/docusaurus/issues/1941 and https://github.com/facebook/docusaurus/issues/1973

**Comment by endiliey** [comment]
See https://github.com/facebook/docusaurus/pull/2032
