### ISSUE TITLE
cannot escape character within backtick within a table

### ISSUE THREAD

**Issue by rbalet** [facebook/docusaurus#2004]
## 🐛 Bug Report
when using backtick within a table, the `pipe` `|` wont be espace by the `backslash` `\`

## To Reproduce
try this code within a docusaurus md file
```md
| Test                            | x        | x   |
| ------------------------------- | -------- | --- |
| `this pipe \| should be espace` | and this | not |
```

## Expected behavior
escaping the `|` when using `\`

## Actual Behavior
Create a new column

**Comment by yangshun** [comment]
See here: https://stackoverflow.com/a/49834158/1751946

**Comment by parvezakkas** [comment]
Actually, this is not a "Docusaurus" bug. It's coming from the remarkable markdown parser. Try your sample markdown here:

https://jonschlinkert.github.io/remarkable/demo/

This is how it is rendered:

![image](https://user-images.githubusercontent.com/2721901/69083957-26ce5680-0a11-11ea-900a-df63b7451399.png)

This issue should be raised in the remarkable repository, if one doesn't exist already:

https://github.com/jonschlinkert/remarkable

**Comment by rbalet** [comment]
Thx @parvezakkas, the Issues didn't existed before, I open a new one here https://github.com/jonschlinkert/remarkable/issues/368.   
I'll post a new comment when it's done on their side (or if it will be).

**Comment by endiliey** [comment]
Upstream bug.

**Comment by rbalet** [comment]
If somebody is looking for a quick fix. If found [here](https://stackoverflow.com/a/17320389/11135174) this solution.
`| <code>this pipe &#124; should be espace</code> | and this | not |`
