### ISSUE TITLE
docusaurus-start doesn't work with projects that contain "pages" in their path

### ISSUE THREAD

**Issue by mbykovskyy** [facebook/docusaurus#2016]
## 🐛 Bug Report

Dev server crashes on file copy of files that contain `pages` in their path.

```bash
❯ yarn start
yarn run v1.19.1
warning package.json: No license field
$ docusaurus-start
LiveReload server started on port 35729
Docusaurus server started on port 3000
Error: ENOENT: no such file or directory, copyfile '/some_project/gitlab-pages/website/pages/en/index.js' -> '/some_project/gitlab-pages/website/node_modules/docusaurus/lib/pages/website/'
    at Object.copyFileSync (fs.js:1801:3)
    at copyFile (/some_project/gitlab-pages/website/node_modules/fs-extra/lib/copy-sync/copy-sync.js:68:8)
    at onFile (/some_project/gitlab-pages/website/node_modules/fs-extra/lib/copy-sync/copy-sync.js:53:25)
    at getStats (/some_project/gitlab-pages/website/node_modules/fs-extra/lib/copy-sync/copy-sync.js:48:44)
    at startCopy (/some_project/gitlab-pages/website/node_modules/fs-extra/lib/copy-sync/copy-sync.js:38:10)
    at handleFilterAndCopy (/some_project/gitlab-pages/website/node_modules/fs-extra/lib/copy-sync/copy-sync.js:33:10)
    at Object.copySync (/some_project/gitlab-pages/website/node_modules/fs-extra/lib/copy-sync/copy-sync.js:26:10)
    at /some_project/gitlab-pages/website/node_modules/docusaurus/lib/server/server.js:286:10
    at Layer.handle [as handle_request] (/some_project/gitlab-pages/website/node_modules/express/lib/router/layer.js:95:5)
    at next (/some_project/gitlab-pages/website/node_modules/express/lib/router/route.js:137:13)
```

`server.js` grabs an incorrect path:

```js
      // copy into docusaurus so require paths work
      const userFileParts = userFile.split(`pages${sep}`);
      let tempFile = join(__dirname, '..', 'pages', userFileParts[1]);
      tempFile = tempFile.replace(
        path.basename(file),
        `temp${path.basename(file)}`,
      );
      mkdirp.sync(path.dirname(tempFile));
      fs.copySync(userFile, tempFile);
```

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## To Reproduce

1. mkdir -p bug/gitlab-pages
1. cd bug/gitlab-pages
1. npx docusaurus-init
1. cd website
1. yarn start

## Expected behavior
Dev server should start successfully.

## Actual Behavior
Dev server doesn't start.

**Comment by Boluwatifeh** [comment]
hi @endiliey i'm facing this issue, how do i fix it??

**Comment by slorber** [comment]
@Boluwatifeh unfortunately he won't answer: https://v2.docusaurus.io/blog/2020/01/07/tribute-to-endi

I'm working on v2, which is not far from a stable release, so it's worth considering migrating. i18n, the last missing feature for beta/RC/GA, is coming soon.

**Comment by Boluwatifeh** [comment]
Ohh @slorber I'm deeply sorry about what happened. So there's no fix for the issue until a beta us being released?

**Comment by slorber** [comment]
I think this should work in v2 and you shouldn't wait for v2 beta to try using it as it's quite stable already.

v1 do not receive many bugfixes atm as I'm working only v2. If you want this fixed on v1 soon, the best way is likely to send a PR.

**Comment by Boluwatifeh** [comment]
@slorber I'm facing the issue with v2. I tried running npm start after following the instructions from the docusaurus v2 website. I got the error "LiveReload server started on port 35729
Docusaurus server started on port 3000

**Comment by slorber** [comment]
So you should open a separate issue with v2, and proper repro steps and error messages.

This issue was for v1, so if you have it with v2, I need at least the error message from v2.

**Comment by Boluwatifeh** [comment]
Okay, I'd do that right away. Thanks
