### ISSUE TITLE
Side navbar (TOC) doesn't display content in escaped angle brackets

### ISSUE THREAD

**Issue by ayush000** [facebook/docusaurus#2021]
## 🐛 Bug Report

TOC generated in side navbar doesn't honor escaping of angular brackets. Instead all content within angular brackets gets stripped.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## To Reproduce

Add `### function1 [array\<string>]` as `h3` in a markdown file (note the backslash)

## Expected behavior

Both AUTOGENERATED_TABLE_OF_CONTENTS, and side navbar render it correctly as `function1 [array<string>]`

## Actual Behavior

AUTOGENERATED_TABLE_OF_CONTENTS renders it correctly as `function1 [array<string>]` but side navbar renders it as `function1 [array]` instead. Side navbar generation doesn't 
![image](https://user-images.githubusercontent.com/1942688/69266252-d3b2fa00-0bf0-11ea-9e3b-5d7bda82bd6c.png)

## Reproducible Demo
1. Clone [my fork of jest repo](https://github.com/ayush000/jest)
2. checkout branch `patch-1`
3. cd into website folder
4. Run `yarn && yarn start`
5. Go to http://localhost:3000/docs/en/configuration#coveragepathignorepatterns-arraystring

The [corresponding markdown](https://github.com/ayush000/jest/blob/patch-1/website/versioned_docs/version-24.9/Configuration.md#coveragepathignorepatterns-arraystring) is generated differently for AUTOGENERATED_TABLE_OF_CONTENTS and sidebar. Angle brackets are missing in generated side navbar contents.

**Comment by ayush000** [comment]
This is an issue with v1.14.0

**Comment by yangshun** [comment]
Try using `&lt;` and `&gt;`? It's rendered as HTML.

**Comment by ayush000** [comment]
Thanks @yangshun ! Using `&lt;` and `&gt;` fixes the problem.

I am keeping the issue open because using angle brackets should also output the same result in both TOC and sidebar nav.
