### ISSUE TITLE
Deploy should only push if there is an actual change

### ISSUE THREAD

**Issue by omry** [facebook/docusaurus#2041]
## 🚀 Feature

Running yarn deploy pushes the a version to the gh-pages branch even if there are no changes to the website.

## Motivation

Pushing the website even if there are no changes have a few bad side effects:
1. doubling the number of commits in the repo.
2. polluting git log output with irrelevant records
3. possibly increases the size of the repo (as force push it used).

The user can work around it in circleci config, but it's tricky.
Here is an example such workaround:

https://github.com/facebookresearch/hydra/pull/308/files

**Comment by amimas** [comment]
To me, this sounds like CI/CD related. I'm not sure if Docusaurus should really be responsible for this (even though it has built-in commands to publish to github pages). There are a lots of ways a static site can be deployed. Github page is just one of many of those options.

My perception is that Docusaurus is a static site generator that helps to build and maintain techincal docs site quickly. It should be focused on that only. Adding any other responsibilities can make it too complicated and/or take away focus from that core function.

**Comment by yangshun** [comment]
I agree with @amimas. It could be a helpful Docusaurus plugin that adds a smart deploy command but then again it's not specific to Docusaurus so maybe it can just be a cli tool?

**Comment by omry** [comment]
It looks like docusaurus already owns  this responsibility as evidenced by the the yarn deploy command.

I agree that it would make sense to move this responsibility to a different tool or plugin(s).

**Comment by endiliey** [comment]
Its not easy to work this out as the new plugin system will let you pull out data sources from elsewhere. Example: I can fetch from a realtime API and so every yarn deploy means I want to use the data from that current time I ran the command.

As suggested, this is indeed CI related and docusaurus should not try to handle everything with such limited manpower.

**Comment by endiliey** [comment]
And yeah, actually yarn deploy to gh pages was there due to legacy reason of v1. In fact it can be moved as a plugin with “extendCli” hooks. But well, maybe something to revisit in future.
