### ISSUE TITLE
Docusaurus swallow errors inside of siteConfig.js

### ISSUE THREAD

**Issue by vjeux** [facebook/Docusaurus#205]
If there's a syntax error (and I believe it anything throws) in siteConfig.js, then the error is completely swallowed:

```js
yarn start
Using globally installed version of Yarn
yarn run v1.2.0
warning package.json: No license field
$ docusaurus-start --port 8082
Checking if port 8082 is free...
Starting Docusaurus server on port 8082...
✨  Done in 1.60s.
```

would be nice to not swallow them, it makes for a bad developer experience :)

**Comment by JoelMarcey** [comment]
@vjeux I believe https://github.com/facebook/Docusaurus/commit/a49787a56e31790f11faf47f12cd496af73fc878 fixes your original issue.

And we have another feature request issue re: reloading automatically.

Please reopen if you find this is not the case.
