### ISSUE TITLE
Slow to load embedded forms(like Microsoft forms) in markdown [v2]

### ISSUE THREAD

**Issue by raviy0807** [facebook/docusaurus#2058]
## 🐛 Bug Report

I am trying to embedded the microsoft forms in markdown pages.
In version 1, the form loading was quick. However, I face issue when embedding form in version 2.

## To Reproduce

(Write your steps here:)

1. Create a Microsoft form
2. Click on share button, it will provide the embedded code
3. Paste the coed in .md file

## Expected behavior

It should load the form quickly.

## Actual Behavior

It is taking almost 1 min to load the page and nothing shows up.

(Write what happened. Add screenshots, if applicable.)

@endiliey @yangshun 
Could you please look into  #it?

  Thanks for helping us help you!
-->

**Comment by endiliey** [comment]
Please create reproducible repo, screenshots, and screencast if possible. Not everyone know what is `Create a Microsoft form`. 

Creating a minimal repro removes most extraneous moving pieces, improving the signal to noise ratio, enabling the real problem to be seen.

**Comment by raviy0807** [comment]
i was able to resolve by putting the <iframe> syntax inside div in mdx file.

**Comment by yangshun** [comment]
Thanks but the repro steps will still be helpful. If it's too hard to add
the steps, maybe add a link to external documentation showing the steps? @_@
