### ISSUE TITLE
Math Jax integration

### ISSUE THREAD

**Issue by drnazmulalam** [facebook/docusaurus#2078]
## 📚 Documentation

(Hi, I am writing mathematical equations using Latex, but not rendered properly. I would like to know the way I can write math in the markdown blog or page files and will be displayed on my web pages. )

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

(yes)

**Comment by imbsky** [comment]
@drnazmulalam 

```jsx
export const Math = ({ code }) => (
  <img
    src={`https://math.now.sh?from=${encodeURIComponent(
      code
    )}&color=mediumslateblue`}
    style={{ height: "100%", verticalAlign: "middle" }}
  />
);
```

```md
<Math code="\LaTeX" />
```

**Comment by endiliey** [comment]
You’ll have to find a markdown plugin for this. This is out of scope of docusaurus imo.

**Comment by endiliey** [comment]
If you are on v1, you can use katex https://github.com/Khan/KaTeX

They have remarkable-katex plugin which lets u write latex on markdown

**Comment by braco** [comment]
@endiliey and how about for 2.0?

**Comment by yangshun** [comment]
In v2 you can add your own plugins to do this, so definitely not in v2.

**Comment by Ir1d** [comment]
Hi @yangshun , 
I don't think there's support for remark + mathjax.
I tried to use `remark-math` for remark + katex, and added js and css of katex in docusaurus.config.js, but it doesn't render the proper math formulas. Any hint on this?

<details>
<summary>Details</summary>
presets: [
    [
      '@docusaurus/preset-classic',
      {
        docs: {
          sidebarPath: require.resolve('./sidebars.js'),
          editUrl:
            'https://github.com/facebook/docusaurus/edit/master/website/',
          remarkPlugins: [require.resolve('remark-math'), require.resolve('rehype-katex')],
        },
        theme: {
          customCss: require.resolve('./src/css/custom.css'),
        },
      },
    ],
  ],
  scripts: [
    // "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-MML-AM_CHTML"
    // "https://polyfill.io/v3/polyfill.min.js?features=es6",
    // {
    //   src: "https://cdn.jsdelivr.net/npm/mathjax@3.0.0/es5/tex-mml-chtml.js",
    //   async: true
    // }
  ],
  stylesheets: [
    "https://cdn.jsdelivr.net/npm/katex@0.11.0/dist/katex.min.css"
  ]

</details>

**Comment by sivakon** [comment]
@Ir1d Could you please highlight where you managed to keep those plugin list in v2 docusaurus?

**Comment by Ir1d** [comment]
[update]: `remark-math` + `rehype-mathjax` also works. Thank you.
@sivakon https://github.com/Ir1d/oi-wiki-ng/blob/docusaurus/docusaurus.config.js#L84

**Comment by sivakon** [comment]
@Ir1d I get this error

```
./docs/doc2.md
Error: Expected usable value, not `/oi-wiki-ng/node_modules/remark-math/index.js`
    at Array.forEach (<anonymous>)
 @ ./.docusaurus/registry.js 1:3120-3161 1:3015-3098
 @ ./node_modules/@docusaurus/core/lib/client/exports/ComponentCreator.js
 @ ./.docusaurus/routes.js
 @ ./node_modules/@docusaurus/core/lib/client/clientEntry.js
 @ multi ./node_modules/react-dev-utils/webpackHotDevClient.js ./node_modules/@docusaurus/core/lib/client/clientEntry.js./docs/doc3.md
Error: Expected usable value, not `/oi-wiki-ng/node_modules/remark-math/index.js`
    at Array.forEach (<anonymous>)
 @ ./.docusaurus/registry.js 1:3301-3342 1:3198-3279
 @ ./node_modules/@docusaurus/core/lib/client/exports/ComponentCreator.js
 @ ./.docusaurus/routes.js
 @ ./node_modules/@docusaurus/core/lib/client/clientEntry.js
 @ multi ./node_modules/react-dev-utils/webpackHotDevClient.js ./node_modules/@docusaurus/core/lib/client/clientEntry.js./docs/mdx.md
Error: Expected usable value, not `/oi-wiki-ng/node_modules/remark-math/index.js`
    at Array.forEach (<anonymous>)
 @ ./.docusaurus/registry.js 1:3478-3518 1:3378-3457
 @ ./node_modules/@docusaurus/core/lib/client/exports/ComponentCreator.js
 @ ./.docusaurus/routes.js
 @ ./node_modules/@docusaurus/core/lib/client/clientEntry.js
 @ multi ./node_modules/react-dev-utils/webpackHotDevClient.js ./node_modules/@docusaurus/core/lib/client/clientEntry.js./docs/xd/doc1.md
Error: Expected usable value, not `/oi-wiki-ng/node_modules/remark-math/index.js`
    at Array.forEach (<anonymous>)
 @ ./.docusaurus/registry.js 1:3672-3716 1:3559-3647
 @ ./node_modules/@docusaurus/core/lib/client/exports/ComponentCreator.js
 @ ./.docusaurus/routes.js
 @ ./node_modules/@docusaurus/core/lib/client/clientEntry.js
 @ multi ./node_modules/react-dev-utils/webpackHotDevClient.js ./node_modules/@docusaurus/core/lib/client/clientEntry.js
```

**Comment by Ir1d** [comment]
@sivakon Im not developing that branch any more. And I'm not familiar with this error msg

**Comment by hhk7734** [comment]
@sivakon
solved it by writing the code below.

```javascript
const remarkMath = require("remark-math");
module.exports = {
...
  presets: [
    [
      "@docusaurus/preset-classic",
      {
        docs: {
          remarkPlugins: [
            remarkMath,
          ],
...
```

**Comment by geekodour** [comment]
@hhk7734 where did you put this and which version did you try this on?

**Comment by hhk7734** [comment]
@geekodour 

docusaurus.config.js
https://github.com/hhk7734/wiki.loliot.net/blob/8c7e503e930a47a0f470c880f1ac77e8420b01d3/docusaurus.config.js#L111-L116

package.json
https://github.com/hhk7734/wiki.loliot.net/blob/8c7e503e930a47a0f470c880f1ac77e8420b01d3/package.json#L14-L16

example page
https://wiki.loliot.net/docs/etc/project/ahrs/ahrs-quaternions-rotations

**Comment by geekodour** [comment]
thanks. got it working :)
