### ISSUE TITLE
V1 Example Page/Index.js ProjectTitle Component Does Not Have Props

### ISSUE THREAD

**Issue by FeynmanDNA** [facebook/docusaurus#2082]
https://github.com/facebook/docusaurus/blob/82ded54b1ae8c88c4aba2da642e8c3b7c90a996a/packages/docusaurus-1.x/examples/basics/pages/en/index.js#L38

I think the `ProjectTitle` component should have a `props` passed to it to be able to read `siteConfig`.

Otherwise this function is misleading (even though it is scoped under the `class HomeSplash`.)

**Comment by endiliey** [comment]
Its probably a typo here in https://github.com/facebook/docusaurus/blob/82ded54b1ae8c88c4aba2da642e8c3b7c90a996a/packages/docusaurus-1.x/examples/basics/pages/en/index.js#L65

We can just not pass props to it. Welcoming PR. This doesnt break anything anyway :)
