### ISSUE TITLE
Scaffolding a fresh v2 won't compile on windows

### ISSUE THREAD

**Issue by davidhagg** [facebook/docusaurus#2090]
## 🐛 Bug Report

I cannot get a clean fresh scaffolding to work on Windows 10.
Tried using both cmder and powershell

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## To Reproduce

1.Run
`npx @docusaurus/init@next init payments classic`

2.Then run
`yarn start`

## Expected behavior

The website to start with a predefined template. No errors.

## Actual Behavior

An error occurs stating:
"Octal literal in strict mode"

## Reproducible Demo

![image](https://user-images.githubusercontent.com/1506085/70266315-8449fd80-179c-11ea-84aa-1a3452525437.png)

**Comment by yangshun** [comment]
Will be fixed in https://github.com/facebook/docusaurus/pull/2086

**Comment by endiliey** [comment]
We'll send a release soon. Sorry
