### ISSUE TITLE
Image Zoom on Click

### ISSUE THREAD

**Issue by ataft** [facebook/docusaurus#2091]
## 🚀 Feature

I created a plugin (https://github.com/ataft/plugin-image-zoom) for zooming in on images when you click them, using the `medium-zoom` module. 

I'm afraid that I did this incorrectly and was hoping for someone to either fix it or guide me in the right direction. My goal is to call the MediumZoom module after page loads. I found an undocumented Lifecycle API function called `onRouteUpdate` and used that to make it work.

You can see what the current plugin looks like at:
https://learn.flexitanalytics.com/docs/getting-started

I made a comment a couple weeks ago in https://docusaurus-2.netlify.com/feedback/p/allow-large-image-preview-on-click too...

## Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## Motivation

Image zooming is a critical part of documentation

## Pitch

Image zooming is one of the most important features of online documentation. Nearly every product has this feature, for good reason.

**Comment by endiliey** [comment]
Hmm there's many way to do this. And some approach might be more efficient but requires more steps.

Your approach looks quite OK. Another approach is to build a remark plugin that replaces all image with an image component that has medium-zoom attached to it. Another way is to replace the Image component replaced by MDX & add medium-zoom to it, and many many other ways.

I feel this scope is too open-ended and it should be left as plugin. Docusaurus (undermanpowered as it is) 2 is still in alpha so we want to focus more on the general use case. I personally am not too in favor of this feature though, it just add extra few kBs on client bundle
