### ISSUE TITLE
v2 Documentation on modifying webpack config

### ISSUE THREAD

**Issue by equinusocio** [facebook/docusaurus#2097]
## 📚 Documentation

This example showed in the v2 documentation ([here](https://v2.docusaurus.io/docs/lifecycle-apis#configurewebpackconfig-isserver-utils)) doesn't work and it throws an error:

```js
// docusaurus-plugin/src/index.js
module.exports = function(context, options) {
  return {
    name: 'docusaurus-plugin',
    configureWebpack(config, isServer, utils) {
      const {getCacheLoader} = utils;
      config.modules.rules.push({
        test: /\.foo$/,
        use: [getCacheLoader(isServer), 'my-custom-webpack-loader'],
      });
      return config;
    },
  };
};
```

> ./blog/2019-05-28-hola.md
Module build failed (from ./node_modules/babel-loader/lib/index.js):
SyntaxError: /Users/equinusocio/Repositories/Oval/docus/blog/2019-05-28-hola.md: Identifier 'React' has already been declared (7:275)

**Comment by endiliey** [comment]
Ah.. Of course it wont work. There is no such “my-custom-webpack-loader” ... Its just to indicate that you can add your webpack loader there/ you can modify your config.

But your error seems unrelated though ✌️ 
Did you import React in blog ⭕️

**Comment by equinusocio** [comment]
What I posted above is the **example** from the documentation. i just created a project with the classic template and added this:

**plugins/cusotm-webpack-plugin/index.js**

```js
// docusaurus-plugin/src/index.js
module.exports = function(context, options) {
  return {
    name: 'cusotm-webpack-plugin',
    configureWebpack(config, isServer, utils) {
      const {getCacheLoader} = utils;
      config.modules.rules.push({
        test: /\.pcss$/,
        use: getStyleLoaders(isServer, {importLoaders: 1, modules: true}),
      });
      return config;
    },
  };
};
```

The first error is: config.**module**.rules.push and not config.**modules**.rules.push like in the example. `config.modules` is undefined. The second error, after fixing this is what i posted above, the duplicated `React` import. Without doing anything else.


What works for me is:

```js
module.exports = function() {
  return {
    name: 'custom-webpack-plugin',
    configureWebpack(_config, isServer, utils) {
      const {getStyleLoaders} = utils;
      return {
        module: {
          rules: [
            {
              test: /\.pcss$/,
              use: getStyleLoaders(isServer, {importLoaders: 1, modules: true})
            }
          ],
        },
      };
    },
  };
}
```

PS I need to do this because the most commond postcss file extension is `.pcss` and i compile a components library that use css modules (with .pcss) without the `.module` notation.

**Comment by endiliey** [comment]
PR welcome :)

**Comment by equinusocio** [comment]
Of course, the problem here it's that is not clear which is the correct way to do that. I don't know webpack very well.

**Comment by endiliey** [comment]
Hmm ok so you can actually direct modify the config like this

```js
// docusaurus-plugin/src/index.js
module.exports = function(context, options) {
  return {
    name: 'cusotm-webpack-plugin',
    configureWebpack(config, isServer, utils) {
      config.entry.output.filename = "new.bundle.js"
    },
  };
};
```

Or you return a partial config. This one will be merged with [webpack-merge](https://github.com/survivejs/webpack-merge)
```js
// docusaurus-plugin/src/index.js
module.exports = function(context, options) {
  return {
    name: "cusotm-webpack-plugin",
    configureWebpack(config, isServer, utils) {
      return {
        output: {
          filename: "new.bundle.js"
        }
      };
    }
  };
};

```

**Comment by endiliey** [comment]
Example https://github.com/algolia/docsearch-website/blob/master/plugins/my-loaders/index.js

**Comment by equinusocio** [comment]
Ok, as per https://github.com/facebook/docusaurus/issues/2084 should we mention that v2 use postcss under the hood?

**Comment by BobLamarley** [comment]
> Example https://github.com/algolia/docsearch-website/blob/master/plugins/my-loaders/index.js

How does this work, i've done the same as you : 
Added plugins/my-loaders folder as dependencies
![image](https://user-images.githubusercontent.com/7857364/71015730-6792bb80-20f4-11ea-869d-c13ff9cdd81d.png)
Then, write my plugins/my-loaders/index.js content : 
![image](https://user-images.githubusercontent.com/7857364/71015874-97da5a00-20f4-11ea-9289-e7e5bef56976.png)
Then 'npm start' 
![image](https://user-images.githubusercontent.com/7857364/71015927-acb6ed80-20f4-11ea-8963-5a9550eb83bc.png)

I got this error, even if i do a 'npm install', my project stay broken, no luck :cry:

**Comment by EthanSK** [comment]
How did you get this working? It's not working for me. I've followed what's been done in the sample project that was linked...I just need image loaders to work for png

**Comment by SunXinFei** [comment]
> How did you get this working? It's not working for me. I've followed what's been done in the sample project that was linked...I just need image loaders to work for png. I get the same problem as @BobLamarley
> 
> EDIT: for future ppl I fixed it, my script name had a typo. Also need to make an empty package.json where the index.js is in the example https://github.com/algolia/docsearch-website/blob/master/plugins/my-loaders/index.js . Need to also set `plugins: ['my-loaders']` in docusaurus.config.js.

yes , this is right, need make an package.json where the index.js is in the example https://github.com/algolia/docsearch-website/blob/master/plugins/my-loaders/index.js 
```html
{
  "name": "my-loaders",
  "version": "0.0.0",
  "private": true
}

```
and run` npm install` will be ok
