### ISSUE TITLE
Example Site in Install Instructions Failing on Windows

### ISSUE THREAD

**Issue by brettpalmberg** [facebook/docusaurus#2098]
## 🐛 Bug Report

Example site fails to compile on Windows

**SyntaxError: C:\projects\mysite\.docusaurus\registry.js: Octal literal in strict mode (9:103)**

Node Version: 12.13.1

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## To Reproduce

I followed the installation instructions here: https://v2.docusaurus.io/docs/installation/
1. npx @docusaurus/init@next init mysite classic
2. cd mysite
3. npm start

## Expected behavior

Example site compiles and content can be viewed at localhost:3000

## Actual Behavior

Example site compiles with errors and site content is not displayed at localhost:3000/ .

**SyntaxError: C:\projects\mysite\.docusaurus\registry.js: Octal literal in strict mode (9:103)**

![image](https://user-images.githubusercontent.com/29417036/70345389-90c46980-1821-11ea-9a49-5c83a81bc989.png)

## Reproducible Demo

1. npx @docusaurus/init@next init mysite classic

![image](https://user-images.githubusercontent.com/29417036/70345465-c5382580-1821-11ea-838b-cd6ceb39ebb0.png)

**Comment by endiliey** [comment]
Thanks for reporting. We'll release a fix soon

**Comment by brettpalmberg** [comment]
Thank you @endiliey.  I am really enjoying Docusaurus2.
