### ISSUE TITLE
Wrong path to sidebars.json in generated readme

### ISSUE THREAD

**Issue by nickmccurdy** [facebook/docusaurus#2107]
## 🐛 Bug Report

`docusaurus-init` will currently generate a `website/README.md` that references `website/sidebar.json`, which does not exist. It seems like it should be `website/sidebars.json`.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## To Reproduce

1. `docusaurus-init`

## Expected behavior

`website/README.md` refers to `website/sidebars.json`

## Actual Behavior

`website/README.md` refers to `website/sidebar.json`

## Reproducible Demo

Clone https://github.com/testing-library/testing-library-docs and open `website` directory

**Comment by nickmccurdy** [comment]
I'll submit a PR if someone can please explain how to edit the template for both 1.x and 2.x

**Comment by yangshun** [comment]
@nickmccurdy try searching for the string "sidebar.json" in the repo? Alternatively, look at the existing READMEs, identify some distinctive strings in the README and search the repo for that string.

**Comment by nickmccurdy** [comment]
I have, but I don't know how to contribute to both 1.x and 2.x. Can I just edit both files, or do I need to be on different branches with multiple pull requests?

**Comment by yangshun** [comment]
Just edit in one shot on master :)

**Comment by nickmccurdy** [comment]
Seems like it was just 1.x
