### ISSUE TITLE
[v2]: CompLibrary documentation is out of date

### ISSUE THREAD

**Issue by joeldenning** [facebook/docusaurus#2112]
## 📚 Documentation

[The v1 -> v2 migration guide](https://github.com/facebook/docusaurus/blob/55e676cb2544af00c49b5d95d23fb68aca82a7af/website/versioned_docs/version-2.0.0-alpha.37/migrating-from-v1-to-v2.md#pages) says that CompLibrary is removed in v2. But [the docs for v2](https://github.com/facebook/docusaurus/blob/master/docs/api-pages.md) still say you can use them.

Which one is correct?

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yeah

**Comment by endiliey** [comment]
I think you're misconfusing v1 and v2 docs ~.~ 

https://github.com/facebook/docusaurus/tree/master/website/docs is v2
https://github.com/facebook/docusaurus/blob/master/docs is v1

I believe we have never mentioned thats the v2 docs....
Even v1 and v2 site is different https://docusaurus.io/ https://v2.docusaurus.io/

**Comment by joeldenning** [comment]
Ah I was looking at [the `next` version](https://docusaurus.io/docs/en/next/installation) on https://docusaurus.io! Wasn't on https://v2.docusaurus.info. Thanks for the clarification
