### ISSUE TITLE
Add Full Support For TypeScript

### ISSUE THREAD

**Issue by EvanDarwin** [facebook/docusaurus#2120]
## 🚀 Feature

The ability to run docusaurus in a TypeScript environment

## Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## Motivation

I would personally like to see this because myself and likely others prefer TypeScript to writing pure Node.js, and I believe it is a relatively small change.

## Pitch

There are already 7 upvotes on the TypeScript suggestion by Zihua Wu on the Docusaurus 2 feedback website.

- It would require no new dependencies
- I am willing to work on a PR
- Modify how docusaurus loads files for rendering the website:
  * `require()` files without providing a specific extension
  * Support processing `.ts` and `.tsx` file extensions

**Comment by endiliey** [comment]
Can you be more specific ? I think you didnt mean the node.js file, but rather the "web" js file as in `website/pages/index.tsx` instead of `website/pages/index.js` right ?

**Comment by EvanDarwin** [comment]
Correct, the actual React JSX templates.

**Comment by EvanDarwin** [comment]
I would additionally like to have the capability to support loading a `siteConfig.ts` file. It would allow for the possibility to have both a type-checked `siteConfig` export, and look something like this:

```ts
const siteConfig: Docusuarus.Config = { /* ... */ };
export default siteConfig;
```

I'm going to start working on an example pull request.

**Comment by EvanDarwin** [comment]
Is there any documentation about how to set up a Docusaurus 2.x project? It is hard to test my changes when it is loading `docusaurus` instead of `@docusaurus/core`.

**Comment by EvanLovely** [comment]
https://v2.docusaurus.io/docs/migrating-from-v1-to-v2

I'd love this too BTW!

**Comment by SleepWalker** [comment]
> Can you be more specific ? I think you didnt mean the node.js file, but rather the "web" js file as in website/pages/index.tsx instead of website/pages/index.js right ?

@endiliey it would be even better to be able to import `typescript`/`flow-type` from `mdx` files. Is such a feature acceptable?

**Comment by sarunast** [comment]
I managed to get it work with TSX. Here is the example from my project:
https://github.com/sarunast/german-grammar/blob/master/webpackConfigPlugin/index.js

After that, you load it as a plugin. I guess it would be best if someone could create an actual plugin package.

**Comment by EvanDarwin** [comment]
@sarunast Your PR looks great, and is a simple change like I imagined.

@SleepWalker I think you will want to make a separate issue for Flow support, if that's what you're looking to do.
