### ISSUE TITLE
Navbar line break in create react app docusaurus site

### ISSUE THREAD

**Issue by andriijas** [facebook/docusaurus#2121]
## 🐛 Bug Report

There's a strange styling bug, potentially from infima that makes the header on the docusaurus site for create react app line break in Safari (no other browser).

I tried to reproduce it on other sites without success.

I tried to fix it naively in https://github.com/facebook/create-react-app/pull/7831  but that would cause other issues as described in the comments. 

## To Reproduce

Open safari
go to https://create-react-app.dev

## Expected behavior

Navbar header title in one line

## Actual Behavior

Navbar header title line breaks

![66916348-51e11700-f01b-11e9-9133-06dabbf36bea](https://user-images.githubusercontent.com/33141/70782288-ee5b3780-1d86-11ea-866a-703ad193ac00.png)

**Comment by elharony** [comment]
We can fix it by removing `flex: 1 0 0;` from `.navbar .navbar__items`. Not sure where to contribute it! 🤔

**Comment by esvyridov** [comment]
@andriijas Hi. I found a solution how we could make it looks like in Chrome. Does it look good to you? If so I'll do a PR for CRA
![image](https://user-images.githubusercontent.com/46542370/73939610-e63cf580-48fa-11ea-8e0b-4df5b35713d7.png)

**Comment by andriijas** [comment]
@esvyridov If you have better fix than this: https://github.com/facebook/create-react-app/pull/7831    - yeah!   Thanks!

**Comment by esvyridov** [comment]
@andriijas pr is ready - https://github.com/facebook/create-react-app/pull/8437

**Comment by andriijas** [comment]
Okay lets get that in for now. The underlaying CSS framework of docusaurus isn't open source I think. Hopefully will get notified from this issue if it changes :D
