### ISSUE TITLE
The `Redirect` component does not respond with a 3XX

### ISSUE THREAD

**Issue by binarylogic** [facebook/docusaurus#2131]
## 🐛 Bug Report

We've followed the advice described [here](https://v2.docusaurus.io/docs/docusaurus-core/#redirect) for redirects, and the problem with this approach is that crawlers do not recognize this as a redirect since the server responds with a `200`. I could be wrong, but this negatively affects how the site is indexed for search engines.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## To Reproduce

```bash
curl -v -s https://vector.dev/releases/ > /dev/null
```

Notice that the `200` response is received, but if you go to the URL directly:

https://vector.dev/releases/

You'll be redirected accordingly. This seems to deviate from basic HTTP semantics.

## Expected behavior

For the URL to return a `301` permanent redirect.

**Comment by yangshun** [comment]
Unfortunately this is a client-side redirect and I don't think we can set the HTTP response on the client side. Your best bet would be to configure it on the server, which I don't think GitHub pages supports. If you use Netlify for hosting, you can add a `_redirects` file (https://docs.netlify.com/routing/redirects/), which will give the correct HTTP code.

**Comment by binarylogic** [comment]
Thanks! We'll go with the netlify approach.
