### ISSUE TITLE
If a file name ends with html.md, server could not load the URL

### ISSUE THREAD

**Issue by saibonala** [facebook/docusaurus#2133]
## 🐛 Bug Report

If a file name ends with html.md, the server could not load the URL. It is throwing an error 
Cannot read property '1' of null at /docusaurus/lib/server/server.js:251:24

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes.

## To Reproduce

1. Create a file with html.md in the documentation
1. Run the docusaurus server
1. Open html.md with the docusaurus server
1. Observe the error 
Cannot read property '1' of null at /docusaurus/lib/server/server.js:251:24

## Expected behavior

It should open the link without errors

## Actual Behavior

html.md link is not opening, throwing the above error.

## Reproducible Demo
It is easily reproducible who is running docusaurus server. No need for DEMO.

**Comment by Tarektouati** [comment]
@endiliey Can I work on this?

**Comment by yangshun** [comment]
Yes go ahead.

**Comment by yangshun** [comment]
Actually I can't even reproduce this issue. Can you give more detailed repro instructions?

**Comment by saibonala** [comment]
@yangshun, You can reproduce the issue by naming your md file with just 'html' (eg. html.md). It should not prefix with any other string.

**Comment by yangshun** [comment]
@saibonala I've tried it. I wasn't able to reproduce it. What does "Open html.md with the docusaurus server" mean? Could you provide a URL for us to try? The repro instructions are not clear.

**Comment by saibonala** [comment]
I mean to say after creating html.md file, open it with URL http://localhost:3000/html.md. This gives the mentioned error.

**Comment by yangshun** [comment]
But creating an `html.md` file does not allow you to access http://localhost:3000/html.md. That's not Docusaurus-intended behavior, so an error is acceptable. Creating a file `docs/html.md` will create a route at `docs/html/`.

This is not a bug.

**Comment by saibonala** [comment]
We have a route like '/learn/app-development/widgets/basic/html'. When we access with localhost:3000, it is giving error. What is the problem with this route?

**Comment by yangshun** [comment]
Please provide an *repro with clear instructions*. The best repro would be your current repo. Many things could go wrong:

- There's a misunderstanding of how Docusaurus works
- `siteConfig.js` was misconfigured
- `sidebars.json` was misconfigured

I'm not able to help unless you give clearer steps.

**Comment by saibonala** [comment]
Repo URL: https://github.com/wavemaker/docs
FilePath: /learn/app-development/widgets/basic/html
