### ISSUE TITLE
[v2] Sitemap contains links that result in 302s

### ISSUE THREAD

**Issue by binarylogic** [facebook/docusaurus#2134]
## 🐛 Bug Report

Hi. This isn't necessarily a bug report, but it is typically bad SEO practice for the sitemap to contain redirects. This is due to the fact that the URLs contained do not end with a `/`. This is a wider spread problem with linking in general across docusaurus, so I'm curious to hear what you think.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## To Reproduce

1. Open https://vector.dev/sitemap.xml
2. Notice that `https://vector.dev/blog` is contained.
3. Notice accessing the URL results in a 302:

    ```curl
    curl -v -s https://vector.dev/blog > /dev/null
    ```
4. The destination is `https://vector.dev/blog/`

## Expected behavior

For the sitemap to point to the final URL.

---

It's possible that this does not affect SEO at all, but I wanted to bring it your attention in the event it does.

**Comment by lex111** [comment]
I think it depends more on the static site hosting provider. Or __maybe not__, because without trailing slash, this is about working with client navigation, so we really can safely add a slash at the end of the links.

**Comment by endiliey** [comment]
Its because we're using client side navigation and during HTML rendering phase, it will render `/test` as `/text/index.html`. 

However, depending on site hosting provider, it could request `/test/index.html` or `/test.html` when accessing `/test` for first page load (before client nav takes over)`. 

Its a hard call to be honest :( not sure whats the best approach

**Comment by yangshun** [comment]
Seems like vector.dev uses a custom sitemap plugin that fixes this issue. [Plugin src here](https://github.com/timberio/vector/tree/master/website/plugins/sitemap).

I think we should standardize and make all the internal routes end with trailing slashes, for docs, sitemaps, and stuff. cc @lex111 @slorber

**Comment by slorber** [comment]
I'm not against but don't really know the potential impact of such change, as it's related to how host providers serve files, and I'm not familiar with all that we currently support :)

**Comment by slorber** [comment]
The next release includes a `trailingSlash: true` config option to force a trailing slash in links, URLs, canonical URLs, hreflang metas...

See https://github.com/facebook/docusaurus/issues/3372

Use https://github.com/slorber/trailing-slash-guide to understand how your hosting provider behaves when serving the historical filename pattern `/path/index.html` (file created for `/path`).

Some hosts won't add any redirect / trailing slash, like Netlify (pretty URLs disabled) or Vercel, while others (Github Pages, Netlify with pretty URLs enabled) will redirect to a trailing slash

So you can upgrade and use `trailingSlash`, or change host
