### ISSUE TITLE
Speed of getting started is truly remarkable (no action needed)

### ISSUE THREAD

**Issue by veeral-patel** [facebook/docusaurus#2140]
Hi - I didn't have a feature request but wanted to thank you for creating this tool!

In particular, it really only takes 15-20 minutes to go from "sketch in my mind for a documentation site" to a fully functioning, nice looking documentation site that has the features I need (header/sidebar customization, search, ability to add/remove landing page). And that's the first time using the tool!

Please keep up the great work!

**Comment by yangshun** [comment]
Hey @veeral-patel thank you for the kind words! That's our aim - to get you started really quickly. Try out Docusaurus 2, which provides even more customizability.

For future reference, you could also tweet at us at [@docusaurus](https://twitter.com/docusaurus) to give feedback! 😄

**Comment by veeral-patel** [comment]
@yangshun actually, if you don't mind me asking, how can I enable a dark theme toggle on my documentation site?

I found it on your personal site here: https://yangshun.im/
As well as in this GitHub issue: https://github.com/facebook/docusaurus/issues/1995

I'm using Docusaurus 1 btw but I'm open to upgrading if necessary.

**Comment by yangshun** [comment]
It's a Docusaurus 2-only feature
