### ISSUE TITLE
Certain CSS styles not loading in Docusaurus 2

### ISSUE THREAD

**Issue by yangshun** [facebook/docusaurus#2141]
## 🐛 Bug Report

Certain CSS modules styles are not loading. E.g. the theme toggle, the navbar styles.

This is caused by `style-loader@1.1.0` https://github.com/webpack-contrib/style-loader/issues/445 which causes overriding of the styles if the name of the CSS module files are the same.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes.

## To Reproduce

Initialize a new Docusaurus 2 website

## Note from Maintainers

We might publish a new Docusaurus 2 alpha version which locks down the version of style-loader to `1.0.2`.

**Comment by endiliey** [comment]
style loader is only used in dev though. This affect prod as well ?

https://github.com/facebook/docusaurus/blob/8b26d92a397dea5cf41ceb6e54fa609f47c37a64/packages/docusaurus/src/webpack/utils.ts#L39

**Comment by bravo-kernel** [comment]
I can confirm that this is only happening locally, the Netlify preview shows as expected

**Comment by rayronvictor** [comment]
Running `yarn run build` works as expected
