### ISSUE TITLE
Header position bug

### ISSUE THREAD

**Issue by popuguytheparrot** [facebook/docusaurus#2143]
## 🐛 Bug Report

Header position fixed break side nav panel

![image](https://user-images.githubusercontent.com/19804652/71326332-3c500800-250a-11ea-9b02-d46065f8a3dc.png)

## To Reproduce

(Write your steps here:)

1. npx @docusaurus/init@next init docs classic
2. yarn start
3. on site go to Docs

## Expected behavior

Header position fixed break side nav panel

## Actual Behavior

Header position fixed dont break layout

## Reproducible Demo

zero project from npx

**Comment by bravo-kernel** [comment]
@endiliey this is another side-effect of the other effects of https://github.com/facebook/docusaurus/issues/2141. Also only local.

**Comment by popuguytheparrot** [comment]
@endiliey same in gitpod
![image](https://user-images.githubusercontent.com/19804652/71342964-58d25b80-256f-11ea-90a9-85c77b2bb6fc.png)
