### ISSUE TITLE
highlighting swift code 

### ISSUE THREAD

**Issue by Jafar-Khoshtabiat** [facebook/docusaurus#2144]
## 🐛 Bug Report

I have swift code in markdown. I mean something like this:

```swift
/// some swift code here
```

opened in vcode, vcode highlights this code correctly. but when rendered with docusaurus, it doesn't get highlighted and shows all the code in one color. same for ruby and objective-c code.
because markdown understands swift code, I thought it could be some issue in docusaurus.

how to produce:

write a markdown that contains swift code block.

## Expected behavior

I expect that when docusaurus renders docs, it display swift code as highlighted.

## Actual Behavior

after rendering markdown with swift code, it does not highlights swift code and show all of the code with same purple color.

**Comment by endiliey** [comment]
Which docusaurus version are you in. 

Please send a reproducible repo or at least actual working markdown example with proper language meta. https://componentkit.org/docs/composite-components is using objecive-c and properly highlighted.

**Comment by mentrena** [comment]
This is still happening. Like Jafar mentioned it can be reproduced by just trying to write swift code in a markdown file.

[Here](https://mentrena.github.io/SyncKit/RealmAPI/classes/RealmAdapter) is an example, all those code snippets should be highlighted.

**Comment by slorber** [comment]
Works for me

![image](https://user-images.githubusercontent.com/749374/111447117-67290c00-870d-11eb-8b43-79007bf0d2fa.png)

You likely read the docs too fast:

![image](https://user-images.githubusercontent.com/749374/111447265-8de74280-870d-11eb-84f2-ca5d546ffc33.png)

**Comment by mentrena** [comment]
You're very right, thank you!
