### ISSUE TITLE
[V2] Configure multiple docs

### ISSUE THREAD

**Issue by rayronvictor** [facebook/docusaurus#2151]
## ❓ Questions and Help

Is it possible to configure multiple documentation routes?

My motivation is that I need a doc route for 'Guidelines', another for 'API Documentation' and so on.

I'm trying to configure multiple `@docusaurus/plugin-content-docs` plugins but this error occur:

`Identifier 'React' has already been declared (21:133)`

My config:
```js
{
  ...
  presets: [
    [
      '@docusaurus/preset-classic',
      {
        blog: {...},
        theme: {...},
        docs: {
          sidebarPath: require.resolve('./sidebars.js'),
        },
      },
    ],
  ],
  plugins: [
    ['@docusaurus/plugin-content-docs', {
      path: 'docs2',
      routeBasePath: 'docs2',
      sidebarPath: require.resolve('./sidebars2.js'),
    }],
  ],
  ...
}
```

**Comment by rayronvictor** [comment]
I found that the v2 documentation has a topic about this.

**Comment by jwitz** [comment]
@rayronvictor I know this was ages ago, but do you remember how you ended up fixing this? I don't see anything related on the linked doc, and now I'm running into the same problem even as I follow these steps exactly: https://docusaurus.io/docs/docs-multi-instance

**Comment by krossekrabbe** [comment]
@jwitz In my case it was because the docs were actually included two times. Make sure the path of your second docs plugin config does not point to a subdirectory of the docs folder.

Or try deactivating the preset docs plugin and configure everything manually:

```js
  presets: [
    [
      '@docusaurus/preset-classic',
      /** @type {import('@docusaurus/preset-classic').Options} */
      ({
        docs: false,
        theme: {
          customCss: require.resolve('./src/css/custom.css'),
        }
      }),
    ],
  ],

  plugins: [
    ['@docusaurus/plugin-content-docs', {
      path: 'docs1',
      routeBasePath: 'docs1',
      sidebarPath: './sidebars1.js'
    }],
    ['@docusaurus/plugin-content-docs', {
      id: 'docs2',
      path: 'docs2',
      routeBasePath: 'docs2',
      sidebarPath: './sidebars2.js',
    }]
  ],
```

**Comment by mx3coding** [comment]
If someone is still in need for multiple documents, check this: https://stackoverflow.com/a/68162605/5734097

**Comment by slorber** [comment]
This is officially documented here: https://docusaurus.io/docs/docs-multi-instance
