### ISSUE TITLE
[V2] Parse error occur when heading contains `<` in mdx

### ISSUE THREAD

**Issue by Kimi-Gao** [facebook/docusaurus#2157]
## 🐛 Bug Report

My docs site has broken since `2.0.0-alpha.40`, if the heading(h1, h2, ...) contains `<`, `<=` in mdx , it will break when run `yarn build` but it works fine in the development environment.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## To Reproduce

1. Add this line in mdx:

```md
## node < 8
....
```

or

```md
## node &lt; 8
....
```

2. Run `yarn build`

## Expected behavior

build success

## Actual Behavior

![image](https://user-images.githubusercontent.com/12554487/71557420-e25abf80-2a80-11ea-9566-269978e08d58.png)

![image](https://user-images.githubusercontent.com/12554487/71557410-b8090200-2a80-11ea-834e-185bf95eb13c.png)

## Reference

https://github.com/facebook/docusaurus/pull/2116

**Comment by endiliey** [comment]
Alpha40 introduced a html parser that validates HTML.

Adding https://github.com/facebook/docusaurus/blob/428e087eb7324374b367215d84006a44c7fad89a/packages/docusaurus/src/client/serverEntry.js#L87   

```diff
    minifyJS: true,
+ continueOnParseError: true,
``` 
will let it the build pass, but its quite weird that this shows as parse error. Any help is appreciated 😉 

Maybe previously we're never HTML spec compliant

**Comment by edwandr** [comment]
After investigation i think it was related to the way EJS template was written : by using an escaped HTML tag instead of unescaped (cf https://github.com/tj/ejs#features) the build passed with a special character in title.

I've created a [pull request](https://github.com/facebook/docusaurus/pull/2214), @endiliey do you think it's a good solution ?
