### ISSUE TITLE
[v2] Proposal: set custom_edit_url to 'null' to disable `Edit this Page` button

### ISSUE THREAD

**Issue by bravo-kernel** [facebook/docusaurus#2159]
Proposing this feature after approval for filing by @yangshun.

### Proposal

Add a frontmatter boolean to allow **per-page disabling** of the `Edit this Page` button. E.g.

```yml
no_edit_button: true
```

> Default value would be `false`

### Why?

It's not always possible to generate a correct `custom_edit_url` like in this real-life example from the Pester website 

1. additional markdown is  generated from a remote source
2. for these pages the global `editUrl` setting cannot be used
3. not all of these remote sources can be edited/resolved
4. it is therefore impossible to create a page-specific `custom_edit_url`
5. leading to 404 errors when pressing the `Edit this Page` button for these type of pages

> The current IRL workaround is to disable all edit buttons, very suboptimal

### How would this solve it?

Users would be able to disable the `Edit this Page` button on a per-page basis.

This should also cover all future use-cases.

**Comment by endiliey** [comment]
Since its a frontmatter and UI stuff. You can already do it without touching the docs plugin. Swizzle out the docpage component, if frontmatter is “set”, just hide it.

**Comment by yangshun** [comment]
I just thought of something - What if we use a convention of setting `custom_edit_url: null` to hide the edit URL? That would be much less work and we can reuse the existing front matter.

**Comment by endiliey** [comment]
yeah null works well too. Try to avoid modifying docs plugin

**Comment by bravo-kernel** [comment]
Thanks for thinking about this. I would personally prefer to NOT use swizzling for this and make this (the `null` suggestion) a core feature. This way we can benefit of future releases without any changes.

I will ask for a PR, thanks ❤️

**Comment by endiliey** [comment]
PR welcome.
