### ISSUE TITLE
bug(v2): search bar loses focus after clicking on it after initial load

### ISSUE THREAD

**Issue by yangshun** [facebook/docusaurus#2175]
## 🐛 Bug Report

On a side note, loading the JS + style when user clicks on the search bar causes a re-render and the focus is lost. It has happened to me a few times on laptop but I didn't know why. But because of this PR I tried the search bar on mobile and it became very obvious what is happening.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## To Reproduce

1. Load page (load on mobile to make it even more obvious)
1. Click on search bar
1. See that focus is lost and you have to reclick on the search bar

## Expected behavior

Search bar stays in focus.

## Actual Behavior

Search bar loses focus.

![demo)](https://user-images.githubusercontent.com/1315101/71704678-aaec6a00-2e16-11ea-9031-963e31e191d4.gif)

## Reproducible Demo

(Paste the link to an example repo, including a `siteConfig.js`, and exact instructions to reproduce the issue.)

**Comment by divyanshu-rawat** [comment]
@yangshun I can work on this what do you say?

**Comment by yangshun** [comment]
@divyanshu-rawat I've started working on this in #2178 but it still doesn't work on mobile so this task cannot be closed. Since you wanna work on it, I'll merge #2178 and you can try to make it work on mobile as a continuation.

**Comment by cybulskimateusz** [comment]
Hey, iI'd love to try to fix it if it's no closed yet
