### ISSUE TITLE
Extra padding/white space in Safari on some pages (v2)

### ISSUE THREAD

**Issue by dima** [facebook/docusaurus#2182]
## 🐛 Bug Report

In Safari on Mac OS X some v2 pages render with extra padding below the footer. This is not the case in Chrome on the same OS.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## To Reproduce

Navigate to https://v2.docusaurus.io/showcase/ and scroll down. Same problem can be observed at: https://v2.docusaurus.io/versions and https://v2.docusaurus.io/blog

## Expected behavior

Safari and Chrome should render pages the same (without any extra white space/padding).

## Actual Behavior

Safari and Chrome render pages differently. (Safari screenshot attached, Chrome behaviour is normal).

<img width="1383" alt="Screen Shot 2020-01-02 at 6 01 14 PM" src="https://user-images.githubusercontent.com/9495/71703623-7df27580-2d8a-11ea-91f9-86e52dcbd07c.png">

<img width="1072" alt="Screen Shot 2020-01-02 at 6 11 57 PM" src="https://user-images.githubusercontent.com/9495/71703779-6d8eca80-2d8b-11ea-8d6e-d61b679607f9.png">

**Comment by yangshun** [comment]
It's probably not extra padding, it's because the footer is not rendered stickily on certain browsers, likely due to flexbox bugs/inconsistencies.

**Comment by dima** [comment]
@yangshun there are plenty of working flexbox sticky footer examples that work fine in all the browsers. E.g. https://philipwalton.github.io/solved-by-flexbox/demos/sticky-footer
I wouldn't say it's a flexbox problem per se, but maybe docusaurus sticky footer implementation can be improved.

**Comment by lex111** [comment]
@dima could you provide more information for reproduce? Safari version, screen size?

**Comment by dima** [comment]
@lex111 Safari version 13.0.5 (likely others too), Screen size 1024x768 and up. Just go to docusaurus home page at https://v2.docusaurus.io, https://v2.docusaurus.io/showcase or https://v2.docusaurus.io/blog and you should be able to scroll past the footer (= it's not fixed/sticky)

**Comment by lex111** [comment]
@dima thanks for the input, however I still cannot reproduce this bug :(

Perhaps this is due to some kind of extension or something else adds space after the footer?

**Comment by dima** [comment]
@lex111 @yangshun Apologies for wasting your time on this. I tracked this down to an extension in Safari (Pocket). I have the same extension in Chrome with no side-effects of this kind. I will make sure to double check with other people before I report a UI issue again. 

Thanks a lot for all your work on this project, it's a pleasure working with it.

**Comment by yangshun** [comment]
No worries, thank you very much!
