### ISSUE TITLE
Add page ratings

### ISSUE THREAD

**Issue by JoelMarcey** [facebook/Docusaurus#219]
Stars? Something to get info on how a page is doing.

**Comment by ForbesLindesay** [comment]
I'd think a better option would be a way of providing feedback on pages. Some combination of a link to edit the page on GitHub/crowdin and maybe some kind of comments system (although that creates the nightmare of out of date comments/moderation/etc.).

**Comment by Glavin001** [comment]
@ForbesLindesay : I've seen https://disqus.com/ before, would this work for a comments system? Any others you would recommend?

**Comment by Glavin001** [comment]
This is what I did to add Disqus to every docs page: https://github.com/Unibeautify/website/pull/76/commits/a25dc1321d44cdcbf1c1626d86f0048031474589
Hope it helps someone else!

**Comment by endiliey** [comment]
Let's not bloat the siteConfig.js for now and stick to v2 roadmap to let user extends the layout itself / whether they want to add page rating or not

**Comment by dandv** [comment]
@Glavin001: is that still the recommended way to add Disqus, 5 years later?

I found this [feature request for a commenting system](https://docusaurus.io/feature-requests/p/comment-system-support-eg-disqus), but no clear recommendation of what to do in the meantime.

Someone [blogged about how to add Disqus](https://madrus4u.com/blog/blog-comments), and @slorber got involved in the Disqus comments there. Looks like the solution in the blog post there is the best interim?

**Comment by slorber** [comment]
It's not only an interim solution: we recommend swizzling for any UI customization that requires dom structure changes.

The swizzling system is generic enough to solve many use cases, not just comments/ratings. We can't document officially all these possible customizations. At best we can create recipes for some of them but it would be impossible to be exhaustive.
