### ISSUE TITLE
Lint TypeScript files

### ISSUE THREAD

**Issue by codemonkey800** [facebook/docusaurus#2192]
## 🐛 Bug Report

I'm not sure if this was intentional or not, but I noticed that the `lint` command is not even running on TypeScript files:
https://github.com/facebook/docusaurus/blob/188b150503294279f3fef42e1b5257cd8815ad65/package.json#L21

It's also not being ran in staging:
https://github.com/facebook/docusaurus/blob/188b150503294279f3fef42e1b5257cd8815ad65/package.json#L67-L76

Running `eslint '**/*.ts` reveals `161` linting errors:
```
...
/Users/jasuncion/projects/oss/docusaurus/packages/docusaurus-plugin-sitemap/src/createSitemap.ts
  28:9  error  Parsing error: Unexpected token, expected ","

  26 |         changefreq: options.changefreq,
  27 |         priority: options.priority,
> 28 |       } as SitemapItemOptions),
     |         ^
  29 |   );
  30 |
  31 |   return sitemap.createSitemap({

/Users/jasuncion/projects/oss/docusaurus/packages/docusaurus-plugin-sitemap/src/index.ts
  10:29  error  Unable to resolve path to module './types'                          import/no-unresolved
  11:27  error  Unable to resolve path to module './createSitemap'                  import/no-unresolved
  12:1   error  `@docusaurus/types` import should occur before import of `./types`  import/order
  22:9   error  'Partial' is not defined                                            no-undef

/Users/jasuncion/projects/oss/docusaurus/packages/docusaurus-types/src/index.d.ts
  96:15  error  Parsing error: Unexpected token, expected ":"

  94 | export interface Plugin<T> {
  95 |   name: string;
> 96 |   loadContent?(): Promise<T>;
     |               ^
  97 |   contentLoaded?({
  98 |     content,
  99 |     actions,

/Users/jasuncion/projects/oss/docusaurus/packages/docusaurus-utils/src/__tests__/index.test.ts
  20:8  error  Unable to resolve path to module '../index'  import/no-unresolved

/Users/jasuncion/projects/oss/docusaurus/packages/docusaurus-utils/src/index.ts
  190:7  error  Assignment to property of function parameter 'file'  no-param-reassign

✖ 161 problems (161 errors, 0 warnings)
  18 errors and 0 warnings potentially fixable with the `--fix` option.

```

Although, the current eslint isn't configured with `@typescript-eslint/eslint-plugin`, so I'm not sure how many of these errors are actual linting errors or because of the lack of the plugin.

Still, we should try to add linting for TypeScript, especially since docusaurus v2 is being written entirely in TypeScript.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yas

## To Reproduce

(Write your steps here:)

1. Run `eslint '**/*.ts`

**Comment by codemonkey800** [comment]
I would love to create a PR eventually, but if anyone more familiar with the codebase or with more bandwidth could look into this, it would be wonderful 😄

**Comment by lex111** [comment]
@codemonkey800 PR would be great, especially since we already have TS support https://github.com/facebook/docusaurus/pull/2221

**Comment by strtw** [comment]
Hi @lex111 I'm working on this, happy to be assigned.

**Comment by lex111** [comment]
@strtw you got it! :smiley:

**Comment by strtw** [comment]
@lex111 Cool thanks! I submitted a PR
