### ISSUE TITLE
allow docsUrl in v2

### ISSUE THREAD

**Issue by callil** [facebook/docusaurus#2193]
Looks like `docsUrl` is no longer supported in v2. Would love to be able to have more control over how these pages are presented. 

My use-case: I have two top level areas called Guides and Docs within my sidebars. I would like to have the urls be `my-site.com/docs` and `my-site.com/guides` - right now each have to be pre-pended with `docs/docs/` or `docs/guides/`.

**Comment by wgao19** [comment]
it is supported in docs config field `routeBasePath`

```
// docusaurus.config.js
module.exports = {
  // ...
  presets: [
    [
      '@docusaurus/preset-classic',
      {
        docs: {
          routeBasePath: '/',
        },
      },
    ],
  ],
};
```

**Comment by yangshun** [comment]
Yeah what @wgao19 said. See the migration guide here - https://v2.docusaurus.io/docs/migrating-from-v1-to-v2#customdocspath-docsurl-editurl-enableupdateby-enableupdatetime

**Comment by KishaniKandasamy** [comment]
> it is supported in docs config field `routeBasePath`
> 
> ```
> // docusaurus.config.js
> module.exports = {
>   // ...
>   presets: [
>     [
>       '@docusaurus/preset-classic',
>       {
>         docs: {
>           routeBasePath: '/',
>         },
>       },
>     ],
>   ],
> };
> ```

The docs link is broken when I add  routeBasePath: '/', .Is there any solution to solve this ?

**Comment by slorber** [comment]
Fix the broken docs link
