### ISSUE TITLE
Problem using nodejs 8.9.4 & npm 5.6.0

### ISSUE THREAD

**Issue by trustyoo86** [facebook/docusaurus#2198]
## 💥 Proposal

Update documentation in getting started > installation.
My node version is 8.9.4, npm version is 5.6.0.
When I run command `docusaurus-init` in my environment, there is no `doc` folder, and only package.json file in the website folder.

So, Looks like it need to modify documentation.
It is run well in over node.js 9.0 version.

Thank you ✋ 

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)? 

👌 Yes

**Comment by lex111** [comment]
PR is welcome :hand:

**Comment by trustyoo86** [comment]
Thx, I'll fix `getting started` documentation typo from `Node >=8` to `Node >=9`, And Pull request. Thank you!! 👍

**Comment by yangshun** [comment]
We will support Node >=10, not Node 9. Anyway let's only close this after the PR is merged.

**Comment by trustyoo86** [comment]
Okay. I understand. (compatible for current Node.js LTS versions)
Thank you ✋
