### ISSUE TITLE
[CLI]: 🔔Notify users if they're using an older version

### ISSUE THREAD

**Issue by jamesgeorge007** [facebook/docusaurus#2199]
[update-notifier](https://www.npmjs.com/package/update-notifier) serves the purpose here. As from the tagline, `Inform users of your package of updates in a non-intrusive way`.

**Comment by strtw** [comment]
Hi @yangshun I've been [working on this in my fork](https://github.com/strtw/docusaurus/commit/c2529230765fc14c23f1a5f57397783daca8ebec) and have had some success getting the notification to display in testing for v 1.x. when I hard code the old version per [update-notifier's testing instructions](https://github.com/yeoman/update-notifier/blob/master/example.js). I'd be glad to be assigned the issue to implement this feature. 

<img width="567" alt="Screen Shot 2020-02-09 at 6 25 23 PM" src="https://user-images.githubusercontent.com/11788126/74116995-d592b680-4b6a-11ea-8554-259748fe8e0c.png">

**Comment by jamesgeorge007** [comment]
@strtw are you still working on this?

**Comment by yangshun** [comment]
This would be a really cool feature to add!

**Comment by strtw** [comment]
@jamesgeorge007 Haven't since my last post but would be glad to be assigned and continue working on it

**Comment by lex111** [comment]
@strtw go for it! Although before it would be nice to bring to completion of your previous PR https://github.com/facebook/docusaurus/pull/2282

**Comment by yangshun** [comment]
We'd love to have this feature! @strtw is this something you're still working on?

**Comment by jamesgeorge007** [comment]
@strtw if you're caught up, I can take it up.

**Comment by strtw** [comment]
@jamesgeorge007 Yah of course! Here's a link to the draft PR I submitted in case it helps. https://github.com/facebook/docusaurus/pull/2890

**Comment by teikjun** [comment]
I'll work on this for v2 :)
