### ISSUE TITLE
Does the picture support magnification?

### ISSUE THREAD

**Issue by gyl-coder** [facebook/docusaurus#2217]
## ❓ Questions and Help

Does the picture support magnification?

**Comment by wgao19** [comment]
if I understand this correctly, you may be thinking about zooming image on click, as similarly as #2091

as [replied by endi](https://github.com/facebook/docusaurus/issues/2091#issuecomment-562818757) this is recommended to be implemented as a plugin instead of a Docusaurus feature

**Comment by gyl-coder** [comment]
@wgao19 Thanks，this is exactly what i want.
