### ISSUE TITLE
Active link in navbar loses highlight when you click on sidebar items (v2 only)

### ISSUE THREAD

**Issue by robinzimmermann** [facebook/docusaurus#2222]
## 🐛 Bug Report

This bug applies to v2. v1 seems to work correctly.

When you click a link in the navbar and the page renders, the navbar item is highlighted so the user has context to what area they are in. That highlight will disappear when you click around the sidebar, unless you click on the first link in the sidebar.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## To Reproduce

This happens in my project, but it can be reproduced using Docusaurus's own doc page.

1. Go the Docusaurus website: https://v2.docusaurus.io/

1. Click the *Docs* link in the navbar, which takes you to https://v2.docusaurus.io/docs/introduction

1. Notice that the *Docs* item in the navbar is highlighted in green

1. Click on any other sidebar item. At the time of writing this bug, the second item was *Design Principles*

1. Notice that *Docs* in the navbar is no longer highlighted

1. Click back on the first item in the sidebar, *Introduction*, and *Docs* is once again highlighted in the navbar

If you go the v1 site, this doesn't occur:

1. Go to https://docusaurus.io/en

1. Click *Docs* in the navbar and notice it's highlighted (though subtly)

1. Click on another item in the sidebar and notice *Docs* continues to stay highlighted.

## Expected behavior

While clicking around the sidebar, I expect the navbar item to stay highlighted so the user has context to what section they are in.

## Actual Behavior

The navbar item only highlights if the first item in the sidebar is the current page.

![image](https://user-images.githubusercontent.com/725660/72576018-45bb5e80-3883-11ea-833f-ba68b9ed3106.png)

![image](https://user-images.githubusercontent.com/725660/72576040-57046b00-3883-11ea-8543-c6b0e17d8791.png)

 My guess is that it's coming from `docusaurus.config.js`:

```js
module.exports = {
  themeConfig: {
    navbar: {
      links: [
        {
          to: "introduction",
          label: "Introduction",
          position: "left"
        },
        { ... },
        { ... }
      ]
    }
  }
}
```

i.e. The highlight in the navbar is only occurring if the current sidebar item matches the above setting in your config file.

In my `sidebar.js`, I even specified the `type` as `doc`:

```js
module.exports = {
  someSidebar: {
    Introduction: [
      { type: "doc", id: "doc1" },
      { type: "doc", id: "doc2" }
    ]
  }
};
```

But it had no noticeable effect.

## Reproducible Demo

No demo needs to be included to reproduce this, as it can be reproduced live on Docusaurus's own website. I hope that suffices. But if needed, I can upload a minimal project that reproduces the issue.

**Comment by lex111** [comment]
@robinzimmermann That's right, in the config website D2 for the [Docs link](https://github.com/facebook/docusaurus/blob/master/website/docusaurus.config.js#L96), the URL is specified as `docs/`introduction, not `docs/`, so this is the correct behavior. We use React Router for nav bar, so from the point of view of this router, these are different paths and therefore the link should not be highlighted.

**Comment by robinzimmermann** [comment]
Thanks @lex111

That leads me to ask:

1. This is different behavior than Docusaurus v1, where the navbar item stayed highlighted. Is it intended that this is not backward compatible? Or do I have a misconfiguration?

1. Is there a way to get the same behavior as v1? If a user lands on any of the documentation pages, for example, I'd like the **Documentation** navbar item to be highlighted so the user knows which part of the site they're on.

**Comment by lex111** [comment]
@robinzimmermann fair enough! I did the PR https://github.com/facebook/docusaurus/pull/2243

**Comment by robinzimmermann** [comment]
That's great, @lex111, thank you very much. I look forward to trying it in the next release!

**Comment by robinzimmermann** [comment]
(Oh, what's the process: should I close this ticket?)

**Comment by lex111** [comment]
@robinzimmermann no, this issue will automatically close after accepting the PR.
