### ISSUE TITLE
Document directory structure goes to the bottom （v2 only）

### ISSUE THREAD

**Issue by gyl-coder** [facebook/docusaurus#2223]
## 🐛 Bug Report

![image](https://user-images.githubusercontent.com/33021341/72606731-13306500-395a-11ea-8052-299a69de660f.png)

I added a table to the document，but the table is too wide. 

Document directory structure should be on the right，but now it  ran to the bottom.

Is there any way to solve it？

**Comment by da-kami** [comment]
This also happens for wide code-blocks. In my opinion Docusaurus should add a scroll-bar to wide objects instead of breaking the design.

**Comment by lex111** [comment]
This will be fixed in PR #224, please be patient. cc @yangshun
