### ISSUE TITLE
Typo in docs

### ISSUE THREAD

**Issue by DmitryOlkhovoi** [facebook/docusaurus#2228]
In the example code under https://v2.docusaurus.io/docs/lifecycle-apis#utils section, there is a typo in webpack configuration.

`config.modules.rules.push` -> `config.module.rules.push`

**Comment by bravo-kernel** [comment]
Seems valid based on the webpack documentation.

https://webpack.js.org/configuration/module/#modulerules

**Comment by DmitryOlkhovoi** [comment]
`.module` not `.moduleS`

**Comment by DmitryOlkhovoi** [comment]
```
// docusaurus-plugin/src/index.js
module.exports = function(context, options) {
  return {
    name: 'docusaurus-plugin',
    configureWebpack(config, isServer, utils) {
      const {getCacheLoader} = utils;
      config.modules.rules.push({ // <- TYPO
        test: /\.foo$/,
        use: [getCacheLoader(isServer), 'my-custom-webpack-loader'],
      });
      return config;
    },
  };
};
```

**Comment by bravo-kernel** [comment]
@DmitryOlkhovoi exactly but.... why not just put in a PR ?

**Comment by lex111** [comment]
@DmitryOlkhovoi thanks, fixed in https://github.com/facebook/docusaurus/commit/f2137bb872b5ec54b7118b7046cdc88613f7fef6

**Comment by bravo-kernel** [comment]
👍🏼
