### ISSUE TITLE
Internet Explorer 11 support is poor with Docusaurus V2

### ISSUE THREAD

**Issue by krillboi** [facebook/docusaurus#2230]
## 🐛 Bug Report

Navigating to v2.docusaurus.io using Internet Explorer 11 (in my case version 11.1565.16299.0) does not yield good results. I first discovered this about a week ago where doing so would yield a semi-broken site (not being able to open sidebar categories, many visual elements not displaying correctly etc.) but trying it just now, I actually just get a bunch of HTML displayed instead of any site (see picture below).

IE support is important for me personally, so better IE support would definitely be great.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes.

## To Reproduce

1. Open IE 11
2. Navigate to v2.docusaurus.io
3. No site is displayed

## Expected behavior

Internet Explorer should work somewhere near the same as any other browser (Chrome, Edge etc.).

## Actual Behavior

The image below displays the HTML I get instead of the site.

![docusaurus_ie_bug](https://user-images.githubusercontent.com/59022282/72725308-b31e0680-3b85-11ea-8f92-5306959d0dfd.PNG)

## Reproducible Demo

Reproducible on Docusaurus V2 live site, so I have not attached any demo.

**Comment by cmfcmf** [comment]
I tested this as well; the IE developer console shows that IE chokes on `Object.assign`, which it does not support.

**Comment by krillboi** [comment]
Fast response, thanks for that! :) 

I can see that IE now is up again (probably after #2231 was fixed), though it is back in the "semi-broken" state I described earlier, so I'd say the support for the browser is still not great:

![docusaurus_ie_support](https://user-images.githubusercontent.com/59022282/72786421-d4d2c880-3c2d-11ea-9119-b5996478585a.PNG)

**Comment by lex111** [comment]
@krillboi Unfortunately, it is unlikely that D2 will have full support for IE11, it is already a very outdated browser. Therefore, either use a modern browser, or use D1.

**Comment by krillboi** [comment]
@lex111 Thanks for the info :)

**Comment by lex111** [comment]
Closes in favor of #2657
We'll only have one issue to track it.
