### ISSUE TITLE
v2.docusaurus.io flashes raw HTML before loading site correctly when using Chrome

### ISSUE THREAD

**Issue by krillboi** [facebook/docusaurus#2231]
## 🐛 Bug Report

Opening v2.docusaurus.io in Chrome (currently I'm using version 78.0.3904.97) gives me some weird flash of raw HTML before the site is loaded correctly. See my gif below. Might be related to another issue I've recently reported: #2230. 

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes.

## To Reproduce

1. Open Google Chrome
2. Navigate to v2.docusaurus.io
3. Observe the flashing HTML

## Expected behavior

Site loads normally without any interruptions.

## Actual Behavior

![docusaurus_chrome_bug](https://user-images.githubusercontent.com/59022282/72728837-8cb09900-3b8e-11ea-9801-426a554940ae.gif)

## Reproducible Demo

Reproducible on Docusaurus V2 live site, so I haven't attached any demo.

**Comment by yangshun** [comment]
You're right. The preview for that PR has this issue too. I'll revert it.
