### ISSUE TITLE
Custom react components and versioning

### ISSUE THREAD

**Issue by ramiel** [facebook/docusaurus#2234]
## 🐛 Bug Report

I can include react component in MDX files by referring to them with relative imports

```js
import Component from '../components/AmazingComponent';
```

But when I create a new version of the docs with `docusaurus docs:version` the reference is lost. Is there a way to use absolute imports instead?

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

I have

## To Reproduce

1. import a component using a relative import
2. create a new version of the website

## Expected behavior

There should be some configured folder that can be referred to with absolute imports or it should be configurable.

## Actual Behavior

I could not find any documentation on how to achieve this.

**Comment by yangshun** [comment]
Yep, it's mentioned in the docs - https://v2.docusaurus.io/docs/versioning#use-absolute-import-within-the-docs

**Comment by ramiel** [comment]
Perfect. Sorry, I dug into the website before asking and somehow I missed it!
