### ISSUE TITLE
When using "window.addEventListener" the build fails for server side

### ISSUE THREAD

**Issue by prma85** [facebook/docusaurus#2247]
## 🐛 Bug Report

When building the doc website, the build is failing for the server if there is a use for the `window` since it doesn't exist in the server.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

(Write your answer here.)

## To Reproduce

(Write your steps here:)

1. Create a custom page
2. Add an event using `window.addEventListener`
3. Run `npm run build` or `yarn build`

## Expected behaviour

The build is completed with success.

## Actual Behavior

The build fails for the server (but it is completed for the client and it works fine with `npm run start`

## Reproducible Demo

Code used for the custom page

```js
import React, { useRef } from "react";
import Layout from "@theme/Layout";
import useBaseUrl from "@docusaurus/useBaseUrl";

const Page = props => {
  const { location, history } = props;

  const iframeSrc = useBaseUrl("storybook-frame") + location.search;
  const title = useRef("Storybook");

  window.addEventListener("message", onMessage, false);
  function onMessage(message) {
    if (message.data.source === "CUSTOM_IFRAME") {
      title.current = message.data.kind
        .replace(/-/gi, " ")
        .replace("  ", " - ");
      history.pushState("", title.current, "?path=/story/" + message.data.kind);
    }
  }

  return (
    <Layout title={title.current}>
      <main id="storybook-frame" style={{ width: "100%", height: "calc(100vh - 100px)", position: "relative" }}>
        <iframe 
          src={iframeSrc}
          title="Storybook"
          style={{ width: "100%", height: "100%", border: 0, position: "absolute", overflow: "hidden" }}
          sandbox="allow-modals allow-forms allow-popups allow-scripts allow-same-origin"
        />
      </main>
    </Layout>
  );
};

export default Page;
```

**Comment by lex111** [comment]
<details>
 <summary>Use `useEffect` hook like this</summary>


```js
import React, {useRef, useEffect} from 'react';
import Layout from '@theme/Layout';
import useBaseUrl from '@docusaurus/useBaseUrl';

const Page = props => {
  const {location, history} = props;

  const iframeSrc = useBaseUrl('storybook-frame') + location.search;
  const title = useRef('Storybook');
  useEffect(() => {
    window.addEventListener('message', onMessage, false);
    function onMessage(message) {
      if (message.data.source === 'CUSTOM_IFRAME') {
        title.current = message.data.kind
          .replace(/-/gi, ' ')
          .replace('  ', ' - ');
        history.pushState(
          '',
          title.current,
          '?path=/story/' + message.data.kind,
        );
      }
    }
  }, []);
  return (
    <Layout title={title.current}>
      <main
        id="storybook-frame"
        style={{
          width: '100%',
          height: 'calc(100vh - 100px)',
          position: 'relative',
        }}>
        <iframe
          src={iframeSrc}
          title="Storybook"
          style={{
            width: '100%',
            height: '100%',
            border: 0,
            position: 'absolute',
            overflow: 'hidden',
          }}
          sandbox="allow-modals allow-forms allow-popups allow-scripts allow-same-origin"
        />
      </main>
    </Layout>
  );
};

export default Page;
```

</details>

**Comment by yangshun** [comment]
There's no `window` on the server, naturally it will fail. You should add some checks before running the code, e.g.:

```
if (typeof window !== 'undefined') {
  ...
  // Use window here.
}
```

Anyway what @lex111 said is right, you should put it within a `useEffect()`. If you put it directly in the main render path, events will be added on every call of the function and that's unlikely what you want. You will end up with too many even listeners.

**Comment by prma85** [comment]
Thanks @yangshun and @lex111 
I tried it with the check but I still got the failing. I will try the use effect.

**Comment by prma85** [comment]
Didn't work with the `useEffect` since it gives me the same error when building. Even with the `if (typeof window !== 'undefined') {`

Doing the code in an external js file and loading it in the config inside of the `scripts` did the job 👍 
The only additional thing was since there is no `window.onload` when changing between pages, I needed to extend the pushState to fire an event that I could check with the listener

```js
const pushState = history.pushState;
history.pushState = function () {
    pushState.apply(history, arguments);
    var event = new Event('pushState');
    dispatchEvent(event, arguments);
};
```

**Comment by yangshun** [comment]
You need to use both useEffect() AND the window check within it.

**Comment by prma85** [comment]
> You need to use both useEffect() AND the window check within it.
Oh yeah, I mean, I did it, but I got an error from server build, but since it is minified I am assuming that the error came from the same file. BTW, is there a way to build without minification? Like `docusaurus build --development`?

**Comment by maksnester** [comment]
> There's no window on the server, naturally it will fail. 

It's also an issue for me. I tried to create some live demo by using jsx components. And my component has an import of some component that has an import of browser-only code. 

```
// some.mdx
import MyFancyDemo from './MyFancyDemo'

<MyFancyDemo />
```

```
// MyFancyDemo.jsx
import problem from 'browser-only-library'
```

How to overcome that? I'm fine with having JSX components not being server-rendered. cc @yangshun
