### ISSUE TITLE
[v2] in-line css doesn't work for HTML tags

### ISSUE THREAD

**Issue by terrafrost** [facebook/docusaurus#2252]
## 🐛 Bug Report

In-line CSS doesn't work for HTML tags. It works in Docusaurus v1 but not v2.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## Create demo.md with the following contents:

```
---
id: demo
title: Demo
---

## Section

hello world

<pre style="background: black">zzz</pre>
```

## Expected behavior

I'd expect the page, complete with the nav, to render - see see "hello world" and to see a `<pre>` tag with zzz in it.

## Actual Behavior

I see nothing. Not "hello world", not zzz. Not even the nav is present.

## Reproducible Demo

https://codesandbox.io/s/frosty-fog-9gg0z
https://9gg0z.sse.codesandbox.io/docs/demo

**Comment by yangshun** [comment]
Docusaurus 2 uses MDX, so the HTML tags are JSX, and you should define them as 

```
<pre style={{background: 'black'}}>zzz</pre>
```

instead.

We probably should document this better.

**Comment by lex111** [comment]
Solved in https://github.com/facebook/docusaurus/pull/2257
