### ISSUE TITLE
[v2] Navbar Dropdown Menu

### ISSUE THREAD

**Issue by tkdrahn** [facebook/docusaurus#2269]
## 🚀 Feature

It would be nice to have the ability to configure a header/navbar item that turns into a dropdown menu.  This would allow quick navigation to multiple pages under one header item without taking up the entire horizontal navBar.  It could function much that way the "Language" dropdown looks, and would be configured in siteConfig.js

## Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## Motivation

I am using docusaurus and we have a lot of pages we want to provide quick navigation to via the header/navBar.  We are running out of horizontal space.  Some of our pages could be logically grouped together under a single navBar dropdown item if that feature was available

## Pitch

I am using docusaurus and we have a lot of pages we want to provide quick navigation to via the header/navBar.  We are running out of horizontal space.  Some of our pages could be logically grouped together under a single navBar dropdown item if that feature was available.  

It seems like it would be fairly simple to implement, as the language dropdown already basically works the way I want.  It just needs to be made configurable in the siteConfig.js

**Comment by yangshun** [comment]
Yep, I'm supposed to work on this. Making it show up on desktop is not hard, the main blocker here is the current Infima nav dropdown is not mobile-friendly. Will prioritize this.

**Comment by tkdrahn** [comment]
Thanks! Looking forward to it

**Comment by tkdrahn** [comment]
hi - any update on this one or ETA when u think it will be done?

**Comment by mingrammer** [comment]
+1

**Comment by tkdrahn** [comment]
hello - any ETA on this ticket?

**Comment by yangshun** [comment]
It will be in our next release

**Comment by RossMurr4y** [comment]
@yangshun I'm unable to get this one to work. Other than upgrading to alpha 49 is anything else required? I've copy/pasted the updated example in the documentation and thrown in some test urls but the dropdown never appears.
