### ISSUE TITLE
Renaming version doesn't update the sidebars.json file

### ISSUE THREAD

**Issue by caabernathy** [facebook/Docusaurus#227]
Steps to reproduce in your website:

```
$ cd website
$ yarn run version 1.1.0
$ yarn run rename-version 1.1.0 2016.1.1.0
```

Result from checking the folders, files:

```
$ ls versioned_docs/
version-2016.1.1.0
$ ls versioned_sidebars/
version-1.1.0-sidebars.json
$ more versions.json 
["2016.1.1.0"]
```

Note that `version-1.1.0-sidebars.json` wasn't renamed to `version-2016.1.1.0-sidebars.json`.

So when running:

```
$ yarn run start
```

One gets this error:

```
Error: No sidebar file available to use for version 2016.1.1.0. Verify that 'version-2016.1.1.0-sidebars.json' exists.
    at sidebarVersion (/Users/caabernathy/Facebook/OpenSource/MakeItOpen/MyPRs/makeitopen/website/node_modules/docusaurus/lib/server/versionFallback.js:280:9)
```

Workaroud:

```
$ cd versioned_sidebars/
$ mv version-1.1.0-sidebars.json version-2016.1.1.0-sidebars.json
$ vi version-2016.1.1.0-sidebars.json
```

Then change all occurrences of `version-1.1.0` to `version-2016.1.1.0` in the file.

**Comment by rupeshparab** [comment]
Hi @caabernathy 
I would like to work on this issue
My initial impression is that the filename expected by the current script ends with '-sidebar.json', but in the directory it ends with '-sidebars.json'
https://github.com/facebook/Docusaurus/blob/master/lib/rename-version.js#L120

**Comment by endiliey** [comment]
@rupeshparab it's yours

I've added an "issue-claimed" label so that others will know not to start work on the issue. If you change your mind about the issue, no worries! Just let me know so that I can remove the label and free it up for someone else to claim.

I'll check in with you periodically so that we can keep the task updated with the progress.

**Comment by rupeshparab** [comment]
@endiliey 
I have raised a PR for fixing this issue, do let me know if I need to make any changes in the PR
