### ISSUE TITLE
Allow to pass the copyright property as a function.

### ISSUE THREAD

**Issue by esvyridov** [facebook/docusaurus#2270]
## 💥 Proposal
Copyright is a common place where we usually put a current year. If a site was built before New Year then after New Year the site still has an old year. To update the year a developer should rebuild the site. We could do that by allowing to put function or string to the **copyright** property.

For example if we take a look at home CRA page (02/06/20) we see 2019.

![image](https://user-images.githubusercontent.com/46542370/73940328-4f713880-48fc-11ea-80be-880a4607eb23.png)

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

yes

**Comment by elviswolcott** [comment]
I think it makes sense to have it as is. How I understand it the copyright date doesn't specify what year the copyright is valid, it specifies when you are making the claim (and lasts for the next 70 years). Thus, if I publish my website in 2019 and then the copyright date updates to 2020, my copyright notice is saying "In 2020, I copyrighted this work". That means someone who copied my work in 2019 could potentially argue they copied it before the copyright was in place. Admitted, I doubt such an argument would hold up given that you could provide a commit history showing when you made the changes and that the copyright was dynamic, but I'm not a lawyer. Whether it's a legal loophole or not, it doesn't seem correct to auto update copyright notices without content changes.

[Stackoverflow post discussing updating copyrights](https://stackoverflow.com/questions/2390230/do-copyright-dates-need-to-be-updated)

**Comment by esvyridov** [comment]
@elviswolcott Oh, I didn't know about that. Thanks a lot for the explanation.
