### ISSUE TITLE
[V2] Potential code block improvements

### ISSUE THREAD

**Issue by markerikson** [facebook/docusaurus#2271]
## 🚀 Feature

v2 code blocks currently have the ability to highlight specific line numbers, like this:

```
```jsx {1,4-6,11}
```

However, highlighting lines based on line numbers is somewhat difficult to use.

The `gatsby-remark-prismjs` plugin has the ability to highlight individual lines by putting a `// highlight-next-line` comment in front, or [highlight ranges of lines](https://www.gatsbyjs.org/packages/gatsby-remark-prismjs/#line-highlighting) using `// highlight-start` and `// highlight-end` pairs.  It looks like the logic is implemented in this [`directives.js` file](https://github.com/gatsbyjs/gatsby/blob/c542f4f8f3f3a8cd6df73bd7baf8382f97da178f/packages/gatsby-remark-prismjs/src/directives.js).

This would be a great addition to the Docusaurus Prism plugin.

In addition, I've seen that many docs websites have code snippets that include a filename in front of the block, such as [Gatsby (example)](https://www.gatsbyjs.org/tutorial/part-two/#-build-a-new-page-using-css-modules) and [Ember (example)](https://guides.emberjs.com/release/tutorial/part-1/orientation/#toc_working-with-html-css-and-assets-in-an-ember-app).

Gatsby's Markdown for this looks like:

```markdown
```javascript:title=src/pages/about-css-modules.js
import React from "react"
// highlight-next-line
import styles from "./about-css-modules.module.css"
import Container from "../components/container"

// highlight-next-line
console.log(styles)
```

## Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## Motivation

Easier line highlights and filenames would be very useful, especially as part of tutorials that are telling users what to edit.

**Comment by yangshun** [comment]
Sounds very useful indeed!

**Comment by elviswolcott** [comment]
I've built these features out for an internal site on docusaurus v1 before. I'll take a stab at implementing it with this syntax sometime next week if no one takes it before then.

**Comment by elviswolcott** [comment]
It looks life @KohheePeace has the code titles figured out. I can take a stab at the code highlight comments.

**Comment by markerikson** [comment]
Looks like the filename title PR is almost done.  @elviswolcott , are you still looking at doing the code highlighting comments feature?

**Comment by elviswolcott** [comment]
Yeah, lost track of this with everything going on the last few weeks. I'll get a PR together in the next few days.

**Comment by elviswolcott** [comment]
My PR implements `highlight-next-line`, `highlight-start`, and `highlight-end`.

The linked Gatsby plugin also includes a `highlight-range` comment which I did not implement, as it doesn't seem particularly useful. It is somewhat more useful than the current method (e.g. highlighting relative to a function declaration) but it seems that `highlight-next-line`, `highlight-start`, and `highlight-end` will always be more readable and maintainable.

If anyone thinks it should be added, I can throw it in.

**Comment by markerikson** [comment]
Looks like both the requested features are in https://github.com/facebook/docusaurus/releases/tag/v2.0.0-alpha.49 , so I'll close this.  Thanks!

**Comment by yangshun** [comment]
Thank you @KohheePeace and @elviswolcott!
