### ISSUE TITLE
[v2] add a way to exclude components from SSR within JSX

### ISSUE THREAD

**Issue by equinusocio** [facebook/docusaurus#2273]
## 🚀 Feature

Add a way to exclude components from SSR in JSX. Maybe somethin like `<NoSSR></NoSSR>`.

## Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?
yes

## Motivation

Right now, each time we use a react lib that doesn't support SSR we have to put this check `{typeof window !== 'undefined' && .... }` everywhere inside `js` and `mdx files.`

## Pitch

Tools like Next js and nuxt provide a way to exclude components from the SSR within the markup. To avoid errors during the build phase we should be able to do se same in a better way than using `{typeof window !== 'undefined' && .... }` or `{typeof document !== 'undefined' && .... }`.

**Comment by yangshun** [comment]
I created https://github.com/facebook/docusaurus/pull/2296 which can be used as a convenient API instead of a component. Do you have examples of the API in Next and Nuxt which I can take a look at?

**Comment by equinusocio** [comment]
New Nuxt version has these components to handle check the environment from the template:
https://nuxtjs.org/api/components-client-only/

```html
<client-only placeholder="Loading...">
      <!-- this component will only be rendered on client-side -->
      <comments />
</client-only>
```

Nextjs has a `ssr: false` option to use with dynamic imports:
https://nextjs.org/docs/advanced-features/dynamic-import#with-no-ssr


```js
import dynamic from 'next/dynamic'

const DynamicComponentWithNoSSR = dynamic(
  () => import('../components/hello3'),
  { ssr: false }
)
```

**Comment by lex111** [comment]
@yangshun I would add a similar component just because then we can insert code directly into JSX instead of using useEffect, for example, [for our Feedback page](https://github.com/facebook/docusaurus/blob/master/website/src/pages/feedback/index.js#L18-L25), we could do this:

```js
function Feedback() {
  return (
    <Layout
      permalink="/feedback"
      title="Feedback"
      description="Docusaurus 2 Feedback page">
      <div
        className={classnames(
          'container',
          'margin-vert--xl',
          styles.feedbackBackground,
        )}
        data-canny
      />
      
      <NoSSR>
        window.Canny('render', {
            boardToken: BOARD_TOKEN,
            basePath: '/feedback',
        });
      </NoSSR>
    </Layout>
  );
}
```

**Comment by yangshun** [comment]
Ok I think we can add that, but it is better named `<ClientOnly>`/`<ClientRenderedOnly>`

**Comment by lex111** [comment]
Fine, I wrote it on my todo list :notebook_with_decorative_cover:

**Comment by lex111** [comment]
@equinusocio can you please give a specific example (or use case) when a similar component could be useful? Maybe the new API will help with this, could you look? https://github.com/facebook/docusaurus/pull/2296

**Comment by equinusocio** [comment]
@lex111 I don't have a public example available, but recently at @OvalMoney we used this react [data table component ](https://github.com/jbetancur/react-data-table-component#readme) which don't works inside docusaurus v2 mdx files because it's client-only and when running the build process, docusaurus throw an error about `missing window object` during the server building.

We had to wrap it inside a custom `<NoSRR>` component to make the build working

**Comment by lex111** [comment]
@equinusocio but could you give me a piece of code? I ask this more for documentation purposes, it would be nice to give a real-world example. This tiny component, so no problem with adding it to the core, but I want to get more information on its possible using, as previously I had a wrong idea about in which cases it can be used.

**Comment by equinusocio** [comment]
I don't if this is what you need, but this our case:


**data-table.mdx**
```jsx

Once you import it, you can use the `<DataTable>` element inside your JSX template.

<NoSSR>
    <DataTable
      columns={[{
        name: 'First column',
        selector: 'someKey',
        sortable: true,
      }, {
        name: 'Second column',
        selector: 'anotherKey',
        sortable: true,
      }]}
      data={[{
        id: 1,
        someKey: 'Some data to print',
        anotherKey: 'Another key data',
        anyOtherKey: 'Any other key data'
      }, {
        id: 2,
        someKey: 'Some data to print 2',
        anotherKey: 'Another key data 2',
        anyOtherKey: 'Any other key data 2'
      }]}
    />
</NoSSR>
```

We had to exclude the component from the build process because it search for the `window` object.

**Comment by equinusocio** [comment]
Sorry i forgot to mention that the table component is this one
https://www.npmjs.com/package/react-data-table-component

**Comment by lex111** [comment]
> We had to exclude the component from the build process because it search for the window object.

@equinusocio oddly, I tried using the example above, and did not get any build errors. Are you sure that the error was in this component?

```jsx
import DataTable from 'react-data-table-component';

<DataTable
  columns={[{
    name: 'First column',
    selector: 'someKey',
    sortable: true,
  }, {
    name: 'Second column',
    selector: 'anotherKey',
    sortable: true,
  }]}
  data={[{
    id: 1,
    someKey: 'Some data to print',
    anotherKey: 'Another key data',
    anyOtherKey: 'Any other key data'
  }, {
    id: 2,
    someKey: 'Some data to print 2',
    anotherKey: 'Another key data 2',
    anyOtherKey: 'Any other key data 2'
  }]}
/>
```

**Comment by equinusocio** [comment]
The componet listed for `window` resize when the `hide` props is used:
https://www.npmjs.com/package/react-data-table-component#columns

**Comment by lex111** [comment]
@equinusocio thanks, I added `hide` prop but still build is going to build successfully, what other options are there how to make build fail?

```js
import DataTable from 'react-data-table-component';

<DataTable
  columns={[{
    name: 'First column',
    selector: 'someKey',
    sortable: true,
    hide: 'md',
  }, {
    name: 'Second column',
    selector: 'anotherKey',
    sortable: true,
    hide: 'md',
  }]}
  data={[{
    id: 1,
    someKey: 'Some data to print',
    anotherKey: 'Another key data',
    anyOtherKey: 'Any other key data'
  }, {
    id: 2,
    someKey: 'Some data to print 2',
    anotherKey: 'Another key data 2',
    anyOtherKey: 'Any other key data 2'
  }]}
/>
```

**Comment by equinusocio** [comment]
@lex111 Sorry for the late response, i've checked again and i can confirm that one of the data table component cause the issue. Here the error we get during building by removing our custom `<NoSSR>` that wrap the table inside the mdx file:

```shell
ReferenceError: document is not defined
(undefined) ReferenceError: document is not defined
    at index_es_Ee (main:2775:30551)
    at Ht (main:2775:60546)
    at d (main:29456:498)
    at Za (main:29459:16)
    at a.b.render (main:29464:476)
    at a.b.read (main:29464:18)
    at Object.renderToString (main:29474:364)
    at render (main:69344:252)
```

Here are the table props we're using:

```
columns
data
progressComponent
onRowClicked
subHeader
progressPending
expandableRowsComponent
pagination
highlightOnHover
pointerOnHover
responsive
fixedHeader
noHeader
paginationPerPage
striped
noDataComponent
theme
customStyles
```

A side note, we'are also using the component `createTheme` function to customize the table, and this may be the cause. Here the code of the theme, and we assign it to the table `theme` property like so `theme: 'ODS'`

```js
import { createTheme } from 'react-data-table-component';

createTheme('ODS', {
  text: {
    primary: `hsl(${Tokens['secondary-80']})`,
    secondary: `hsl(${Tokens['primary-100']})`,
  },
  background: {
    default: 'transparent',
  },
  context: {
    background: 'transparent',
  },
  button: {
    default: `hsl(${Tokens['secondary-80']})`,
    hover: `hsl(${Tokens['secondary-40']})`,
    disabled: `hsl(${Tokens['secondary-70']})`,
  },
  selected: {
    default: `hsl(${Tokens['secondary-50']})`,
    text: `hsl(${Tokens['secondary-90']})`,
  },
  sortFocus: {
    default: `hsl(${Tokens['secondary-80']})`,
  },
  divider: {
    default: 'transparent',
  },
  highlightOnHover: {
    default: `hsl(${Tokens['secondary-50']})`,
    text: `hsl(${Tokens['secondary-80']})`,
  },
  striped: {
    default: `hsl(${Tokens['secondary-40']})`,
    text: `hsl(${Tokens['secondary-80']})`,
  },
});

export const customStyle = {
  subHeader: {
    style: {
      padding: 0,
      marginBottom: Tokens['space-24-px'],
    },
  },
  rows: {
    style: {
      minHeight: '64px', // override the row height
    },
  },
  headRow: {
    style: {
      borderBottom: `4px solid hsl(${Tokens['secondary-50']})`,
    },
  },
  headCells: {
    style: {
      fontWeight: Tokens['font-weight-bold'],
      textTransform: 'uppercase',
      fontSize: Tokens['font-size-16-rem'],
      color: `hsl(${Tokens['secondary-90']})`,
    },
    activeSortStyle: {
      color: `hsl(${Tokens['primary-100']})`,
    },
  },
  cells: {
    style: {
      fontSize: `${Tokens['font-size-16-rem']}`,
    },
  },
  pagination: {
    style: {
      color: `hsl(${Tokens['secondary-90']})`,
    },
  },
};

```
