### ISSUE TITLE
Copying build assets failed when trying to deploy

### ISSUE THREAD

**Issue by pfongkye** [facebook/docusaurus#2274]
## 🐛 Bug Report

When trying to deploy a freshly built website on GitHub pages, I'm getting an error when the `deploy` script tried to copy `server.bundle.js` file to destination folder.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

yes

## Environment

Windows 10

## To Reproduce

1. Follow installation guide
2. Follow deployment guide, particularly the part on deploying to GitHub Pages 

## Expected behavior

The `deploy` command should run to completion and deploy the assets to GitHub Pages.

## Actual Behavior

The following error occured ([code](https://github.com/facebook/docusaurus/blob/b7a2ad29042c07cf11d6e58daa2bdac5dd0fe108/packages/docusaurus/src/commands/deploy.ts#L145) which threw) :
```code
<project-path>\node_modules\@docusaurus\core\lib\commands\deploy.js:106
                throw new Error(`Error: Copying build assets failed with error '${error}'`);
                ^

Error: Error: Copying build assets failed with error 'Error: ENOENT: no such file or directory, stat '<project-path>\build\server.bundle.js''
```

When I commented out the [code](https://github.com/facebook/docusaurus/blob/b7a2ad29042c07cf11d6e58daa2bdac5dd0fe108/packages/docusaurus/src/commands/build.ts#L119) in `build` command script which does the removal of `server.bundle.js`, the `deploy` command runs to completion

## Version of Docusaurus

`2.0.0-alpha.40`

**Comment by lex111** [comment]
@pfongkye sorry for the long wait, could you please reproduce this bug on the latest version (2.0.0-alpha.49)?

**Comment by pfongkye** [comment]
hello @lex111 
no problem. I'll take a look and will keep you updated.

**Comment by pfongkye** [comment]
Hello @lex111 
I've tested with version `2.0.0-alpha.50` and it deployed correctly.

**Comment by lex111** [comment]
Great, thanks for the confirmation!
