### ISSUE TITLE
Cannot use useEffect hook inside of a custom page (v2 only)

### ISSUE THREAD

**Issue by prma85** [facebook/docusaurus#2276]
## 🐛 Bug Report

When creating custom pages inside of `src/pages/something.js` I am not able to use the `useEffect` hook there.

I can use other hooks like `useBaseUrl` and `useRef` but the `useEffect` creates an error of `Error: Invalid hook call`

## To Reproduce

1. Create a custom page
1. Add the useEffect hook
1. Set a menu to access it
1. See the error in the console

## Expected behavior

The page will open without errors

## Actual Behavior

Nothing is rendered (not even the react error page) and you need to check the console to see the error

## Reproducible Demo

No demo, but there is the code used.

```tsx
const Page = props => {
  const { location } = props;
  const iframeSrc = useRef(useBaseUrl(`storybook_frame`));
  useEffect(() => iframeSrc.current = useBaseUrl(`storybook_frame${location.search}`), [location.search]);

  return (
    <Layout title={"Storybook"}>
      <main style={{ width: "100%", height: "calc(100vh - 100px)", position: "relative" }}>
        <iframe
          src={iframeSrc.current}
          id="storybook-frame"
          title="Storybook"
          style={{ width: "100%", height: "100%", border: 0, position: "absolute", overflow: "hidden" }}
          sandbox="allow-modals allow-forms allow-popups allow-scripts allow-same-origin"
        />
      </main>
    </Layout>
  );
};

export default Page;
```

**Comment by lex111** [comment]
This is not a Docusaurus bug - you cannot call a hook (useBaseUrl) **inside** another hook (useEffect), this is described in the hook rules here -> https://reactjs.org/docs/hooks-rules.html#only-call-hooks-from-react-functions

**Comment by prma85** [comment]
I was thinking of the `useBaseUrl` as a function and not a hook. Good catch @lex111 
Thank you :)
