### ISSUE TITLE
Is there a way to restrict sending text for translation to Crowdin? (Docusaurus)

### ISSUE THREAD

**Issue by MIhailsPopovs** [facebook/docusaurus#2278]
In Docusaurus there is a great translation system (using Crowdin). But there seems to be no way to translate specific pages without sending page content text to Crowdin. Some texts might have sensitive information that can't be sent to Crowdin

**Comment by comradekingu** [comment]
Adding stuff to potfiles.in is the gettext way to do it. Crowdin is a spying and tracking platform, and a lackluster tool for translation. Don't subject your translators to that. Use Weblate instead.

**Comment by slorber** [comment]
I didn't see such option in Crowdin to obfuscate a specific part of a markdown doc, however you have the possibility to ignore specific docs and files that are sensitive (see their cli config).


I've created an issue for any discussion related to Crowdin + Docusaurus here: https://github.com/facebook/docusaurus/discussions/4052

**Comment by slorber** [comment]
@comradekingu we need markdown support, so Weblate is not an option for any Docusaurus user (https://github.com/WeblateOrg/weblate/issues/3106)

Crowdin is a good fit for Docusaurus mostly because of its decent markdown support (it could be better but it's a hard problem to solve).
