### ISSUE TITLE
Versions HTML page not created

### ISSUE THREAD

**Issue by caabernathy** [facebook/Docusaurus#228]
I ran the versions script to create a snapshot version.

When I run `yarn run start`, I see my website with a new link at the top for versions. Clicking that link leads to a page not found.

<img width="443" alt="screen shot 2017-11-15 at 12 49 49 pm" src="https://user-images.githubusercontent.com/691109/32851642-81a97e86-ca03-11e7-986d-a2c023b0b852.png">

Upon checking the `website/pages/en` folder, I don't see a `versions.html` file.

**Comment by JoelMarcey** [comment]
We should probably check for a `versions.js` file  and do not run the server if it doesn't exist. We may do that already, I will need to check.
