### ISSUE TITLE
[v2] Unable to reuse content plugins

### ISSUE THREAD

**Issue by binarylogic** [facebook/docusaurus#2280]
## 🐛 Bug Report

Hi, we're attempting to add additional sections to our Docusaurus site powered by the `@docusaurus/plugin-content-blog` plugin. For example:

```
// docusaurus.config.js
// ...
 plugins: [
    '@docusaurus/plugin-content-blog',
    {
      path: 'components',
      routeBasePath: 'components'
    },
  ],
// ...
```

However, when we start the site we're presented with a bunch of syntax errors:

```
SyntaxError: /path/to/website/blog/2020-01-07-blog-post.md: Identifier 'React' has already been declared (36:122)
```

It appears that this markdown file is being double processed, even though the above plugin definition targets the `componens` folder (not the `blogs` folder).

I'm wondering how we can successfully reuse components like this to power other sections with markdown?

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## To Reproduce

(Write your steps here:)

1. Add the above `plugins` definition.
1. Start docusaurus.
1. :( errors.

## Expected behavior

For a new `/components` section to become available, powered by `.md` files in the `components` folder.

## Actual Behavior

I received the above error.

**Comment by lex111** [comment]
```
      path: 'components',
      routeBasePath: 'components'
```

This will not create a new section, but will modify the existing one (blog). That is, `routeBasePath` indicates which root path the blog posts are available for (defaults to `blog`) and `path` is the place in the file system where the blog posts themselves are located (in MD).

In the current implementation, you are limited to docs and a blog, you can change the base URL paths, but you won’t be able to create something new.

**Comment by binarylogic** [comment]
Got it. That would be a really great feature though. It seems odd that a plugin can't be reused with different parameters. I don't fully understand how it all works, but I'm curious if it's possible with a small amount of work?

**Comment by lex111** [comment]
I realized that you want to define your own sections, roughly speaking, a page with a list of elements and a page with a specific element (similar to a blog), right? Currently this is not possible, plugins implement specific goals. But here's the question: how will you define your own template for new sections? I can’t even think of how it should be implemented conveniently and expandable for the user. If you have thoughts on this, write how you see it.

**Comment by binarylogic** [comment]
Sure.

> how will you define your own template for new sections?

I was hoping that I could customize [these options](https://github.com/facebook/docusaurus/blob/master/packages/docusaurus-plugin-content-blog/src/index.ts#L33-L45) and pass my own custom components.

I'm happy to simply copy this plugin and rename it, but that seems like a lot of duplication.

**Comment by lex111** [comment]
The fact of the matter is that in this way you will override the options of the current  plugin. We need to think about how to do this most simply and conveniently for the user.

**Comment by binarylogic** [comment]
Got it. I'll close then.
