### ISSUE TITLE
[V2] .md extensions not stripped when linking to other documents

### ISSUE THREAD

**Issue by yosriady** [facebook/docusaurus#2283]
## 🐛 Bug Report

When referencing other .md files, Docusaurus generates the HTML link `/dir/B.md` instead of `/dir/B`, returning Markdown instead of HTML.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes.

## To Reproduce

Within `/docs`, create the following directory structure:

<img width="164" alt="Screenshot 2020-02-13 at 12 19 13 PM" src="https://user-images.githubusercontent.com/1084226/74401069-17697880-4e5b-11ea-979d-e95229bf56f2.png">

```
# A.md

Going to [B](dir/B.md)
```

```
# B.md

**This is B!**
```

1. `npm run start`
2. Navigate to `/docs/A`
3. Click link to `B`. 

## Expected behavior

We should arrive at `/docs/dir/B`.

<img width="526" alt="Screenshot 2020-02-13 at 12 20 56 PM" src="https://user-images.githubusercontent.com/1084226/74401182-7929e280-4e5b-11ea-9139-a7b5a0b3c37d.png">

## Actual Behavior

<img width="554" alt="Screenshot 2020-02-13 at 12 20 46 PM" src="https://user-images.githubusercontent.com/1084226/74401164-6ca58a00-4e5b-11ea-9dae-ec71a4fabd5d.png">

We arrive at `/docs/dir/B.md` instead of `/docs/dir/B`. The browser displays raw Markdown instead of HTML.

## Reproducible Demo

https://github.com/yosriady/docusaurus-2283

**Comment by lex111** [comment]
I can not reproduce this :man_shrugging: 

![screencast-localhost_3000-2020 02 13-08_07_09](https://user-images.githubusercontent.com/4408379/74403352-fd6a6e80-4e37-11ea-8ca3-a95dfdc8c1c8.gif)
