### ISSUE TITLE
[DOC] Adding Automating Deployments with Travis CI in Docusaurus V2

### ISSUE THREAD

**Issue by mohamedsgap** [facebook/docusaurus#2286]
## 📚 Documentation
When I tried to use Travis CI with Docusaurus V2, I didn't find any steps for automating deployments using CI with Travis CI or even Circle CI. 

So I jumped back to Docusaurus V1 and I made a some update to Travis CI script to be suitable with Docusaurus V2.

I gonna fill a PR to update Docusaurus V2 Doc with  Automating Deployments steps with Travis CI.

**Comment by mohamedsgap** [comment]
so @yangshun  what do you think ? I gonna add my pull request ASAP :)

**Comment by yangshun** [comment]
Saw the PR before I could reply. Thanks!

**Comment by mohamedsgap** [comment]
I really appreciate that,
