### ISSUE TITLE
[V2] Docusaurus project generation fails during installation

### ISSUE THREAD

**Issue by DimaSerhin** [facebook/docusaurus#2290]
## 🐛 Bug Report
`npx --ignore-existing @docusaurus/init@next init test classic` fails during installation of dependencies but the result is shown as successful project generation.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes.

## To Reproduce
Environment: OSX, node v12.15.0, yarn 1.22.0, npm 6.13.4, docusaurus - 2.0.0-alpha.41

1. Run `npx --ignore-existing @docusaurus/init@next init test classic`.
2. Run `cd ./test`
3. Run `yarn start`

## Expected behavior
yarn.lock file is generated, @docusaurus/utils dependency is resolved correctly, docusaurus project is bootstrapped.

## Actual Behavior

1. Yarn logs `error Couldn't find any versions for "@docusaurus/utils" that matches "*"` during docusaurus project bootstrap.
2. After finishing installation error is not thrown and generation phase is logged as `Success! Created test
Inside that directory, you can run several commands:...`
<img width="1377" alt="Screen Shot 2020-02-17 at 5 37 58 PM" src="https://user-images.githubusercontent.com/10065317/74697831-b6220c00-51b0-11ea-8597-bac37611c9a4.png">
3. `node_modules` folder is missing in generated project.
<img width="435" alt="Screen Shot 2020-02-17 at 5 45 19 PM" src="https://user-images.githubusercontent.com/10065317/74697875-d2be4400-51b0-11ea-90ce-574218299fe7.png">

## Reproducible Demo

Used only `npx` command, `node_modules/yarn.lock` was not generated, nothing specific about the setup to create a demo.

**Comment by andreyhammer** [comment]
seems issue here:
`"@docusaurus/theme-classic@2.0.0-alpha.41" is missing a bundled dependency "@docusaurus/utils". This should be reported to the package maintainer.
`

**Comment by lex111** [comment]
We release bug fix for this, so please use `2.0.0-alpha.43`. Sorry about that.
