### ISSUE TITLE
Release v2.0.0-alpha.41 / v2.0.0-alpha.43 on npm

### ISSUE THREAD

**Issue by deniaz** [facebook/docusaurus#2297]
## 🐛 Bug Report

v2.0.0-alpha.41 and v2.0.0-alpha.43 releases have been created on Github but not actually been released on npm. Since alpha.41 brings quite a few interesting features it would be great to ave it available.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## To Reproduce

(Write your steps here:)

1. Check releases on Github https://github.com/facebook/docusaurus/releases
2. Check releases on npm https://www.npmjs.com/package/docusaurus

## Expected behavior

Releases are available on npm so they can easily be installed.

## Actual Behavior

Releases are not on npm ;)

**Comment by yangshun** [comment]
They've been released on npm. See [here](https://www.npmjs.com/package/@docusaurus/core). We have users who upgraded to alpha.43 and said that it fixed bugs for them.

Try manually upgrading to alpha.43 in your `package.json` or use the `@docusaurus/core@next` tag.

**Comment by deniaz** [comment]
Ah, yeah I've realised the scoped packages have been released. The https://www.npmjs.com/package/docusaurus package and missing releases there confused me. Sorry about that.

**Comment by yangshun** [comment]
No problem, that's the v1 package and you're not the only one confused by it (I get confused sometimes as well). Thanks for the initiative!
