### ISSUE TITLE
docs: Update documentation to mention how to conditionally apply styles including media queries only to a specific Markdown page

### ISSUE THREAD

**Issue by ltfschoen** [facebook/docusaurus#2301]
## 📚 Documentation

The documentation mentions that we can add global CSS in the .css file within website/static/css/ folder, but those styles apply to all the Markdown files in the doc/ directory

If you want to apply styles only to a specific Markdown file in the doc/ directory, but not any others, you can use HTML in the Markdown file itself (i.e. just add your styles within these tags i.e. `<style> * { background: red } </style>`).

For example, I'm using Docusaurus 1.14.4, and when you have a Markdown file it generates the Table of Contents (TOC) automatically on the right hand side when you have headings like `## MyHeading`. But when you reduce the page to a smaller viewport, the TOC disappears, and is **not** replaced with a hamburger menu containing it. 

To get it to show the hamburger menu, you have to add that document/page in the sidebars.json file, so that a left sidebar appears. But you may not actually want the left sidebar to be shown at all especially because it takes up 30% of the left side of the screen, but you need it to show the TOC. 
i.e. If you hide it with the following, then `docsNavContainer` won't be available to show the hamburger menu when you reduce the screen to a smaller viewport.
```
.docsNavContainer {
    display: none !important;
  }
```

So I found the solution was to just add the following in the Markdown file where I wanted it to apply, and to only apply to large viewports. See example of my code in implementation here https://github.com/DataHighway-DHX/documentation/commit/3eac910f3be4db89e2014c1e95c2e04046338826#diff-718701abdd0f5227caa410839157b020R16, and in production here https://dev.datahighway.com/docs/en/whitepaper
```
<style>
@media only screen and (min-width: 1024px) {
  .docsNavContainer {
    display: none !important;
  }
}
</style>
```

I think we should mention in the Docusaurus documentation how users can apply styles (i.e. media queries, etc) only to a specific Markdown file this way.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

**Comment by yangshun** [comment]
Thank you for the detailed report. IMO this is pretty common knowledge and not really a pitfall. If you don't want the doc to have a sidebar, the easiest way is to not add it into the `sidebars.json` file. A Markdown file within the `docs` directory (`docs/my-unlisted-file.md`) will result in a path created for it under `/docs/my-unlisted-file/`
