### ISSUE TITLE
[v2] Bug with dark mode logo

### ISSUE THREAD

**Issue by prma85** [facebook/docusaurus#2308]
## 🐛 Bug Report

Based on the PR https://github.com/facebook/docusaurus/pull/2261

When using the dark logo option, it will work only for the switch button. The default logo will always the loaded, even if the first render is dark mode.

Using version 2.0.0-aplha.43

## To Reproduce

1. Define you logo and dark logo in the `docusaurus.config.js`
```js
navbar: {
  logo: {
    alt: "iQmetrix - Hub.Docs",
    src: "img/logo-black.svg",
    srcDark: "img/logo-white.svg"
  }
}
```
1. Load you site, and it should work
1. Switch to dark mode, use the site and close it
1. Open the site again, it will open the site in the dark mode, and you will see the default logo and not the dark option one

## Expected behavior

Docusaurus would always check which theme the user is using to select the right logo and not only when using the switch button.

## Actual Behavior

Docusaurus always load the default logo at the first load, and don't check if you are using dark theme or not.

## Reproducible Demo

(Paste the link to an example repo, including a `siteConfig.js`, and exact instructions to reproduce the issue.)

https://iqmetrix.github.io/hub.docs/

**Comment by ismailvtl** [comment]
I added the following CSS as quick fix :)

`html[data-theme='dark'] .navbar .navbar__logo {
  content: url(/img/dark-node-logo.svg)
}`

**Comment by prma85** [comment]
> I added the following CSS as quick fix :)
> 
> `html[data-theme='dark'] .navbar .navbar__logo { content: url(/img/dark-mode-logo.svg) }`

This is fixed now!!!
