### ISSUE TITLE
[V2] docusaurus build becomes idle instead of throwing an error

### ISSUE THREAD

**Issue by monapasan** [facebook/docusaurus#2311]
## 🐛 Bug Report

`docusaurus build` doesn't throw an error on a failing build which results in high idle time.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

yes

## To Reproduce

(Write your steps here:)

1. Clone the repo https://github.com/monapasan/docusaurus-idle-when-error
2. run `npm run build`

## Expected behavior

I would expect an error to be thrown and build to be finished.

## Actual Behavior
You will see that docusaurus can't resolve a module in mdx file:
```
./docs/mdx.md
Module not found: Can't resolve '../../build/components' 
```
This then results in idle time

## Reproducible Demo

https://github.com/monapasan/docusaurus-idle-when-error

**Comment by yangshun** [comment]
Thanks for reporting
