### ISSUE TITLE
Document how to produce a "json feed" containing all content as single JSON file

### ISSUE THREAD

**Issue by trauts2** [facebook/docusaurus#2312]
## 📚 Documentation

Similar to [Hugo's index.json](https://xdeb.org/post/2017/06/11/make-hugo-generate-a-json-search-index-and-json-feed/).  I would like to know how to make a JSON output representing all site content and metadata.  Like this:

https://www.screencast.com/t/a3spUYaU1J0

This supports a variety of downstream transformations of site content, such as building a custom Algolia index, transforming to other output formats, etc.

Could someone document or suggest how to do this?

Thanks!

Stu

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

yes

**Comment by yangshun** [comment]
We don't have a good way to do that at the moment as we don't aggregate the data model during the bootstrap process into one single data structure, unlike Gatsby. Contents and data fetched within each plugin is scoped to that plugin. The only overall site-wide data we have is the routes, which is used by `docusaurus-plugin-sitemap` to create `sitemap.xml`. 

But what you have proposed is a step in the right direction. In future, we would try to have similar APIs to  build data models in plugins which can be processed downstream in subsequent plugins.

**Comment by slorber** [comment]
The `contentLoaded` attribute now accept a "allContent" attribute that permits to access the content loaded by all the plugins.

` async contentLoaded({actions: {createData, addRoute}, allContent}) {`

Take a look at the official debug plugin for inspiration, as it access the data of all the plugins: https://docusaurus.io/__docusaurus/debug/content

**Comment by kesor** [comment]
Migrated from v2 to v3 ... and there is no longer `allContent` available :(

**Comment by slorber** [comment]
@kesor this is something we never documented because I wasn't sure it was a good idea. 

We later refactored it to another lifecycle method you can try `allContentLoaded`. Again, still undocumented, we might not make it a public API surface and may need to refactor it if we find a better API design. But the "feature" should stay because we need it ourselves for the debug plugin: https://docusaurus.io/__docusaurus/debug/content
