### ISSUE TITLE
[V2] Adding "Draft" header option for Blog

### ISSUE THREAD

**Issue by tomtongue** [facebook/docusaurus#2314]
## 🚀 Feature
Draft post mode for Blog such as `draft: true`
This option enable to avoid publishing a post if the post has `draft: true` in the Header option.

Currently, Header options for Blog does not support "draft" tag such as that of Jekyll; [Posts | Jekyll • Simple, blog-aware, static sites](https://jekyllrb.com/docs/posts/#drafts), as shown in [Blog | Docusaurus](https://v2.docusaurus.io/docs/blog#header-options).

## Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes.

## Motivation
Docusaurus enables us to create one of the most beautiful and useful documentation and blog site. However, when we use this as a Blog site and try to create a new blog post, we need to create a (or some) new branch(es) and then merge the master branch (as one of the example). It need more steps, compared with Jekyll. This functionality should help many users.

## Pitch
Draft mode provides more easily to use it by blog user, team and so on.
* Providing more easy publish
* More easy to manage posts
* Possibly avoiding to create many branches

**Comment by lex111** [comment]
You can create any directory (for example, `drafts`) in the directory with the blog posts (`blog`) and move posts there that should not be published yet (`blog/drafts/post.md`).

**Comment by yangshun** [comment]
I think they want to be able to preview drafts during dev as well. I remember trying to implement drafts before but wasn't too successful due to how the tags data was processed. Not against this idea and following the Jekyll convention would be good.

**Comment by tomtongue** [comment]
Thank you! Yes, currently, I'll create `drafts` directory and put drafts on the directory. Do you think  it is needed to add the current document? If needed, I'll send pull request for this.
