### ISSUE TITLE
[V2] Issues with relative url links in production

### ISSUE THREAD

**Issue by hasan1501** [facebook/docusaurus#2317]
## 🐛 Bug Report

When refreshing a page that has relative URL links, the URL links are broken.

**Note - Works fine on the local environment. Issues when in production**

Using version 2.0.0-aplha.43

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes.

## To Reproduce

(Write your steps here:)

1. Add a relative URL link in a file. Example:
```js
The broadcast() method expects an object of type [BroadcastInput](../models/broadcast-input).
```
2. Build and deploy the documentation.
3. Go to the page that has the relative link.
4. Refresh/Hard Refresh the page and check the relative link again.

## Expected behavior

The URL links should not change on refreshing the page.

## Actual Behavior

1. Go to https://docs.convai.dev/docs/node-sdk/methods/merge-users
2. Move to any other page and come back to the Merge Users page (Don't use the back button for this. Kindly proceed by actually clicking the pages).
3. Click on the MergeUsersRequest link. The link will be - https://docs.convai.dev/docs/node-sdk/models/merge-users-request/ (Correct)
![image](https://user-images.githubusercontent.com/28281598/75193003-02260100-571b-11ea-9ded-fee18595b6a3.png)
4. Go back to the Merge Users page and do a hard refresh. Click again on the MergeUsersRequest link. The link will be - https://docs.convai.dev/docs/node-sdk/methods/models/merge-users-request (Incorrect)

## Reproducible Demo

Github repo - https://github.com/datomar-labs-inc/documentation-convai-platform

**Comment by lex111** [comment]
@hasan1501 for the links to other documents to work correctly, you need to specify the file extension (md/mdx), see https://v2.docusaurus.io/docs/markdown-features/#referencing-other-documents
