### ISSUE TITLE
bug (v2) html files with underscore prefix returning 404

### ISSUE THREAD

**Issue by amilajack** [facebook/docusaurus#2332]
## 🐛 Bug Report

HTML files in `static` dir with underscore prefix are not resolved. Page shows `Page Not Found`. Only resolves underscores when running `docusaurus start`.

<img width="1024" alt="Screen Shot 2020-02-26 at 11 14 25 AM" src="https://user-images.githubusercontent.com/6374832/75378783-29024580-5889-11ea-9b61-f8268779501d.png">

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## To Reproduce

1. Create a new project with docusaurus
2. add `_foo.html` to `static` dir
3. publish to github pages

## Expected behavior

`_foo.html` page should be resolved. Behavior should be consistent between dev and prod builds.

## Actual Behavior

`_foo.html` page shows `Page Not Found`

<img width="1024" alt="Screen Shot 2020-02-26 at 11 14 25 AM" src="https://user-images.githubusercontent.com/6374832/75378783-29024580-5889-11ea-9b61-f8268779501d.png">

## Your Environment

- Docusaurus version used: latest v2
- Environment name and version consistent across all browsers, node 13.2.0
- Operating system and version (desktop or mobile): macOS desktop

## Reproducible Demo

https://github.com/amilajack/my-website

*this works*
https://github.com/amilajack/my-website/foo.html

*this does not work*
https://github.com/amilajack/my-website/_foo.html

**Comment by lex111** [comment]
This is not a Docusaurus bug, if you add the `.nojekyll` file to the `gh-pages` branch, this error will disappear.

See:
- https://lex111.ru/my-website/_foo.html
- https://github.com/lex111/my-website/commit/268ad5549793b257bad16fcbffb59682474f12c9

**Comment by amilajack** [comment]
@lex111 thanks! Also do you think docusarus should add the `.nojekyll` file by default?

**Comment by lex111** [comment]
@amilajack no, I don’t think so, because this is an issue that applies only to GitHub Pages (in this case), and we should not care about this, since our task as a static site generator is to generate the proper build of website.

**Comment by yangshun** [comment]
This is interesting! While it's not a Docusaurus bug, I recommend we document these weird behaviors down in a new FAQ page or something - maybe https://v2.docusaurus.io/docs/faq? I can think of more stuff to add into it (e.g. some prerendering-related issues).

@amilajack would you be interested in creating one?

**Comment by amilajack** [comment]
I’d love to document this. I was wondering what the correct place to document this was. I was thinking of adding it to the “publishing with GitHub pages” section. What are your recommendations?

**Comment by lex111** [comment]
I like this idea, it will be more convenient and predictable for users than creating a separate section (FAQs) for this. Although maybe in the future it might be worth writing something like that.

**Comment by yangshun** [comment]
Adding it to the "Publishing with GitHub pages" section sounds good!
