### ISSUE TITLE
[v2] links: nav & footer links (href) without target="_blank"

### ISSUE THREAD

**Issue by LukasGentele** [facebook/docusaurus#2339]
## 🚀 Feature
Currently, I can set `href` for nav and footer links in `docusaurus.config.js` for the classic-theme but they always render with `target="_blank"`. It would be great if that could be disabled/changed, so that the link will open in the current browser tab rather than opening a new one. 

## Have you read the [Contributing Guidelines on issues]
Yes

## Motivation
I think it is such an essential thing that it should be part of the classic-theme. I mean I could eject the header and footer and just do it myself but that would disconnect me from the theme which seems a little overpowered for such a small change.

## Pitch
There could be a config option next to `href` to control the target, e.g. `linkTarget` with a default value of `_blank` or an option `targetBlank` with default value `true`.

**Comment by lex111** [comment]
You can add the `target` attribute, and thereby override the default value, eg:

```
{
  href: 'https://github.com/facebook/docusaurus',
  label: 'GitHub',
  position: 'right',
  target: '_self',
},
```

**Comment by LukasGentele** [comment]
Thanks, @lex111. Any way this is possible for the `navbar.logo` option as well? Adding `target` does not seem to do anything for the logo option.

**Comment by lex111** [comment]
Is it really necessary for a logo? I mean, do you really want external link to open in the current tab when you click on the logo? FYI was [recently](https://github.com/facebook/docusaurus/pull/2253) allowed to add an external link to `logo.href`, in which case it will open in a new tab (as expected).
If you mean that the internal link in the logo opens in a new tab, then this is also a rather strange behavior and is not familiar to most users.
We focus on the expected UX - this is when external links open in a new tab, and all the rest in the current one.

**Comment by LukasGentele** [comment]
Got it but in my case it is expected actually and currently, it is very strange from a UX perspective. You can see what I mean here: https://devspace.sh/cli/docs/introduction

To explain what happens here: I have a website hosted on netlify and I only proxy the /docs/* routes to the docusaurus page => That means the / route is **not** made with docusaurus. However, using a `to` link, would load the wrong site using javascript. So, I need an `href` link but with `target=_self`.

**Comment by lex111** [comment]
Hmm, aha, if you set `href` as '/' then this will not work, there will be a 404 error. This is actually not a common use case. But it seems to me, we can add the ability to set the `target` attribute for logo url :thinking:.

**Comment by LukasGentele** [comment]
Yes, exactly. I got the 404 with to:/, so I switched to using href. Having logo.target would be great. Let me know if you want a PR for this.
