### ISSUE TITLE
Feature: Live-reload

### ISSUE THREAD

**Issue by ericnakagawa** [facebook/Docusaurus#234]
Allow editing files and reloading the pages automatically during development. @mitermayer

**Comment by Kikobeats** [comment]
Because internally docusaurus uses express, it could be done using [svr](https://github.com/Kikobeats/svr).

The only prerequisite is separate the express routes into a separate file.

**Comment by yanivnis** [comment]
+1 for this feature. It can make the development process much easier.

**Comment by JoelMarcey** [comment]
cc @wulucxy

**Comment by codering** [comment]
+1

**Comment by No1illuminati** [comment]
What?

**Comment by zbycz** [comment]
You may use nodemon tool:
```
cd website
nodemon --watch ../docs/ ./node_modules/.bin/docusaurus-start
```

**Comment by amyrlam** [comment]
👋 I'm working on this issue! 

Try a hard refresh for now, making sure to be on the `/next` URL to see docs changes in local development, e.g. http://localhost:3000/docs/en/next/doc1.html re: https://docusaurus.io/docs/en/versioning.html.

**Comment by JoelMarcey** [comment]
@amyrlam So excited to see you working on this ❤️
