### ISSUE TITLE
Changing the language for one code tab should automatically change all code tabs to that language.

### ISSUE THREAD

**Issue by ram-nad** [facebook/docusaurus#2349]
## 🚀 Feature

(A clear and concise description of what the feature is.)

## Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

It would be helpful, if on changing a language tab for one code block, automatically changes the language on all code tabs. For sites having many such code blocks user might feel irritated if it needs to switch language manually for each code block.

## Pitch

This feature would be helpful for sites that need documentation for multiple languages, For example: [Casbin](https://casbin.org/) (This is were I got the idea from). It is also very much required from UX point of view.

**I would be interested in solving this issue if required.**

### Proposed Solution
Initially, we can simply switch languages for all tabs in a single page, and then we can add a session storage variable to keep track of users favoured language which will be loaded by default from future page reloads.

**Comment by hsluoyz** [comment]
Thanks for bring it up! We really need this feature!

**Comment by yangshun** [comment]
Yeah this would be really nice to have. We can do it in a similar fashion as the `ThemeProvider` and `useTheme`, but it would be `ProgrammingLanguageProvider` and `useProgrammingLanguage` in this case.

**Comment by yangshun** [comment]
Assigned to @SamChou19815. Thanks Sam!

**Comment by hsluoyz** [comment]
BTW, will this feature be available on 1.x? We are still using Docusaurus 1.11.1 because we need the translation functionality.

**Comment by yangshun** [comment]
@hsluoyz we'll not be adding new features to v1. We'll be working on v2 translations this half so you can migrate to it then. However this is not hard to do in v1 given that you can hack together some scripts to be injected into the page.

**Comment by yangshun** [comment]
Closed by #2366

**Comment by hsluoyz** [comment]
Thanks! We will absorb this feature when v2 translation is ready.
