### ISSUE TITLE
Bug - after docusaurus-init, yarn start prints misleading error message

### ISSUE THREAD

**Issue by ericnakagawa** [facebook/Docusaurus#235]
When a new site is created using `docusuaurus-init` the example docs folder isn't moved to `/docs`. With the files not accessible to Docusuaurus, Running `yarn start` results in an error message about localization. This is incorrect.

**Comment by JoelMarcey** [comment]
We should verify that this is still indeed true.

**Comment by endiliey** [comment]
I've tried running new site & not moving example docs to /docs
<img width="859" alt="test" src="https://user-images.githubusercontent.com/17883920/40871307-db7cad02-666b-11e8-993d-9d80ecfd6f82.PNG">

Correct error messages. Closing this
