### ISSUE TITLE
Is there any way to create a nested dropdown sidebar

### ISSUE THREAD

**Issue by chandankumar4** [facebook/docusaurus#2350]
## 🚀 Feature

(A clear and concise description of what the feature is.)

In the sidebar how can we create a nested dropdown menu items, Like the structure below
```
Experiments
├── coredns
│   └── coredns-pod-delete
├── Generic
│   ├── container-kill
│   ├── disk-fill
│   ├── disk-loss
│   └── pod-delete
├── kafka
│   ├── broker-disk-failure
│   └── broker-pod-failure
└── openebs
    ├── pool-pod-failure
    ├── target-container-failure
    └── target-network-delay

```

## Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

yes

## Pitch

This requirement came from the [here](https://docs.litmuschaos.io/)

**Comment by benClmnt** [comment]
Hi, i think it is possible to do so in v2. 

An example would be the [docusaurus sidebar page](https://v2.docusaurus.io/docs/markdown-features).

Here is in sidebars.js
```
module.exports = {
  docs: {
    Docusaurus: ['introduction', 'design-principles', 'contributing'],
    'Getting Started': ['installation', 'configuration'],
    Guides: [
      'creating-pages',
      'styling-layout',
      'static-assets',
      {
        type: 'category',
        label: 'Docs',
        items: ['markdown-features', 'sidebar', 'versioning'],
      },
      'blog',
      'search',
      'deployment',
      'migrating-from-v1-to-v2',
    ],
    'Advanced Guides': ['using-plugins', 'using-themes', 'presets'],
    'API Reference': [
      'cli',
      'docusaurus-core',
      'docusaurus.config.js',
      'lifecycle-apis',
      'theme-classic',
    ],
  },
};
```

**Comment by yangshun** [comment]
It's already possible as per what @benclmnt  said. Checkout `website/sidebars.js` for an example.

**Comment by chandankumar4** [comment]
Thanks @benclmnt, I'll check this out
