### ISSUE TITLE
How do I customize blog styles？

### ISSUE THREAD

**Issue by liushooter** [facebook/docusaurus#2353]
>![](https://user-images.githubusercontent.com/1235106/75837012-94569500-5dfe-11ea-92c2-6f04bc792615.png)

I want to change docusaurus-v2 blog title style, 
find this information in `@docusaurus/theme-classic/src/theme/BlogPostItem/styles.module.css` :

```
.blogPostTitle {
  font-size: 3rem;
}
```

I change `src/css/custom.css`  following，no effect :

```
.blogPostTitle {
  font-size: 1rem;
}
```

Help me，How do I customize blog styles？

**Comment by liushooter** [comment]
https://stackoverflow.com/a/58519684

**Comment by fakela** [comment]
@liushooter I had similar issue too, this does not have any effect because it's not properly referenced. It's actually best to style the blog using the styles.module.css and use this **src/css/custom.css**  for styles you want to be available globally. This is what I figured out when trying to style my blog

@yangshun should be able to give a more detailed explanation

**Comment by KohheePeace** [comment]
@fakela

1. Run the below command in `terminal` to swizzle default theme
```sh
yarn swizzle @docusaurus/theme-classic BlogPostItem
```

It generates `src/theme/BlogPostItem` in your website.

You can overwrite your custom style in `src/theme/BlogPostItem/styles.module.css`


Sorry if this is different answer what you want!

**Comment by fakela** [comment]
@KohheePeace thank you alot for this 
I used a different approach 
I had to copy the files and paste them in my website

This is a lot easier . Thanks

**Comment by rafaelrdealmeida** [comment]
Hi,

I'm trying to change the blog layout. But I am not finding the place to customize the layout. Can you indicate that?

the current layout is this:
![Captura de tela de 2020-11-03 16-49-51](https://user-images.githubusercontent.com/18035347/98033873-e2d88b00-1df4-11eb-8b3f-e75cae877b28.png)

I'm trying to alteral to:

![Captura de tela de 2020-11-03 17-02-30](https://user-images.githubusercontent.com/18035347/98034852-6646ac00-1df6-11eb-91cf-3d8b4035a74e.png)

**Comment by slorber** [comment]
hi @rafaelrdealmeida , all the blog components are in the classic theme

![image](https://user-images.githubusercontent.com/749374/98123213-d8c89200-1eb1-11eb-821e-61caabfbb47c.png)


The one displayed in your screenshot looks like the BlogPostList component, that you can swizzle

**Comment by zRains** [comment]
npm version:
```bash
npm run swizzle @docusaurus/theme-classic [component] -- --danger
```
