### ISSUE TITLE
[v2] Alternative way for handling code tabs or add docs preprocessing hook

### ISSUE THREAD

**Issue by doup** [facebook/docusaurus#2355]
## 💥 Proposal

It would be nice to have an alternative way of defining code-tabs that doesn't rely on MDX `Tabs/TabItem`. This is specially interesting for teams that don't have MDX knowledge or that don't want to use it (for portability, readability…).

E.g. if one or more code blocks are next to each other convert them into code-tabs:

```markdown
    ```kotlin
    // Some code
    ```

    ```typescript
    // Some code
    ```
```

👆 In this case there should be a way also to map code-block language hint to tab name. e.g. `typescript` => `TypeScript`.

Alternatively, there could be a way to hook to the markdown loading step so that the developers could modify the markdown content programatically. e.g. search via regex and add the required `Tabs/Tabitem` code.

```
[load markdown] => [hook modifies markdown content] => [render]
```

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes.

**Comment by yangshun** [comment]
> E.g. if one or more code blocks are next to each other convert them into code-tabs

Hard to tell if code blocks should be grouped together. One possible way is to add in metadata into the first line to define the group.

But overall I'm not very keen on adding more syntax if MDX can do the job. If you're going to have a new syntax, MDX can be that syntax. MDX is easy to use and is very expressive.

**Comment by amimas** [comment]
Agree with @yangshun that it can be difficult to tell if code blocks should be grouped or tabbed. Someone else might want them as individual code blocks without tabs.

This feels like getting into the territory of markdown parser and that's not what Docusaurus is for/does.

**Comment by doup** [comment]
What about adding a hook to be able to pre-process docs? The idea would be that before generating the docs it could pass through the hook, this would modify the content and then it goes to rendering.

**Comment by amimas** [comment]
Not sure I understand the proposal on hooks. But it still doesn't answer the fact that not everyone may not want consecutive code blocks as tabs. They could be a series of code samples that needs to be presented/executed sequentially.

I'm also a bit worried about the this tool modifying the actual markdown content behind the scene. Again, this tool is not meant to be a markdown parser, as far as I understand.

**Comment by lex111** [comment]
> What about adding a hook to be able to pre-process docs?

For this purpose, you can write your own plugin for Remark (Markdown processor, which is used in D2) and then include it to the config file.
