### ISSUE TITLE
Why not support ruby code highlighting？

### ISSUE THREAD

**Issue by liushooter** [facebook/docusaurus#2356]
Ruby have been born for 25 years  😢 

![](https://user-images.githubusercontent.com/1235106/75866105-84ab7080-5e3f-11ea-9a46-4e023be0c726.png)

**Comment by KohheePeace** [comment]
Ruby is not imported by this library https://github.com/FormidableLabs/prism-react-renderer/issues/42#issuecomment-536218440

But you can import "ruby"
1. **Swizzling theme components**

```bash
yarn run swizzle @docusaurus/theme-classic CodeBlock
```
https://v2.docusaurus.io/docs/using-themes/#swizzling-theme-components

2. **Import prism-ruby**
```js
// src/theme/CodeBlock/index.js
import Prism from 'prism-react-renderer/prism';
(typeof global !== 'undefined' ? global : window).Prism = Prism;
require('prismjs/components/prism-ruby');
```
https://github.com/FormidableLabs/prism-react-renderer/issues/42#issuecomment-536218440

**Comment by liushooter** [comment]
@KohheePeace  Thank you, I've learned.
