### ISSUE TITLE
npm version?

### ISSUE THREAD

**Issue by imSrbh** [facebook/docusaurus#2358]
## ❓ Questions and Help

 docusaurus-init
Website folder created!

Installing latest version of Docusaurus in website.

WARN engine sitemap@3.2.2: wanted: {"node":">=6.0.0","npm":">=4.0.0"} (current: {"node":"8.10.0","npm":"3.5.2"})
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
npm WARN deprecated coffee-script@1.12.7: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)
npm WARN deprecated gulp-header@1.8.12: Removed event-stream from gulp-header

**Comment by yangshun** [comment]
What's your question? We require npm 10 and above.
