### ISSUE TITLE
Component in MDX using hooks in separate package breaks rendering

### ISSUE THREAD

**Issue by jugglingcats** [facebook/docusaurus#2360]
## 🐛 Bug Report

We're trying to document a component library that exists as a separate package (separate to the docusaurus project). Naturally some of these components use hooks, the most important being `useState`. However we're seeing the following error on rendering:

```
Uncaught (in promise) Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
```
The same component, if copied directly into the docusaurus project works fine. Am struggling to understand why this would be.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## To Reproduce

Note that the example project below is using Lerna. This is just to make the repro easier -- our actual project doesn't use Lerna but exhibits the same behaviour.

1. Download / clone https://github.com/jugglingcats/docusaurus-repro
2. `lerna bootstrap`
3. `cd docusaurus-site`
4. `npm start`
5. Navigate to default doc page (mdx.md)
6. See page render okay
7. Edit `mdx.md` and uncomment `<MyComponentFromPackage />`
8. See page does not render

## Expected behavior

I expect to be able to document components that are outside the docusaurus project. I thought this would "just work".

## Actual Behavior

The hooks error is confusing, because why should it make a difference where the component is coming from?

Perhaps this is an underlying mdx-js issue but it seems it has a significant impact on docusaurus, hence this report.

## Your Environment

The docusaurus-site project was created using `2.0.0-alpha.43`.

- Docusaurus version used: 2.0.0-alpha.43
- Environment name and version (e.g. Chrome 78.0.3904.108, Node.js 10.17.0):
- Operating system and version (desktop or mobile): Windows 10

## Reproducible Demo

https://github.com/jugglingcats/docusaurus-repro

See above for detailed steps.

**Comment by yangshun** [comment]
Yeah beats me, weird behavior indeed. We do load external components in our docs but haven't faced such issues :/

**Comment by jugglingcats** [comment]
Is there a project I can look at where you're doing this successfully, or are they internal? Maybe I can spot what's different... Tx

**Comment by theosherry** [comment]
Hey @jugglingcats . Changing React and React-dom to a peer-dependency in your `example-lib` package will fix this. The problem must be 2 copies of React/React-dom are being loaded.

**Comment by jugglingcats** [comment]
Thanks @theosherry that makes sense, should have realised.

For others here is some more info: https://reactjs.org/warnings/invalid-hook-call-warning.html
