### ISSUE TITLE
Cannot load local images in CSS

### ISSUE THREAD

**Issue by Noah-Silvera** [facebook/docusaurus#2365]
## 🐛 Bug Report

If you use the React/Webpack import css style where css files are imported into js files like `import styles from "./index.module.css";` then background images loaded by URL's fail for **local** images such as png's, svgs, and jpgs.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

yes

## To Reproduce

1. Load a css file via an import into a JS file (the `styles.module.css` file for the `index.js` landing page works nicely)
1. Use a `background-image: url('<some-local-file>.png|jpg|svg')` type tag on an imported class
1. Try to load docusaurus

## Expected behavior

Docusaurus loads the png image and other common types (jpg, svg, etc) via the css

## Actual Behavior

Docusaurus fails to load the background image with an error like so.

![2020-03-06 11_24_57-DevTools - localhost_3001_](https://user-images.githubusercontent.com/8933450/76115766-a28ee780-5f9d-11ea-9bd9-24f3561dc9dd.png)

## Your Environment

I've made no modifications to the webpack config that ships with `docusaurus-init`

- Docusaurus version used: 2.0.0-alpha.43
- Chrome 80.0.3987.132, Node.js 10.16.3):
- Desktop

## Reproducible Demo

I've modified `src/pages/index.js` and `src/pages/styles.module.css` to load a `background-image` URL tag with a local png (`static/img/docusaurus.png`). Run yarn start to see the error. 

https://github.com/Noah-Silvera/docusaurus-png-load-bug

**Comment by Noah-Silvera** [comment]
I think this just needs an update to the webpack loader to support some basic image types.

**Comment by lex111** [comment]
>   background-image: url('../../static/img/docusaurus.png')

Use absolute path like this `background-image: url('/img/docusaurus.png')`

**Comment by apurvaojas** [comment]
@lex111 

The absolute path will not work if we have a different baseURL (i.e other than '/') in a production environment.

> > background-image: url('../../static/img/docusaurus.png')
> 
> Use absolute path like this `background-image: url('/img/docusaurus.png')` (same as `static/img/docusaurus.png`)

@lex111 
The absolute path will not work if we have a different baseURL in the production environment. 
In that case, we need to use a relative path, which is breaking for SVG images.

![image](https://user-images.githubusercontent.com/6194485/103261158-6d3d0580-49c6-11eb-9a12-636729e90c8f.png)
