### ISSUE TITLE
[v2] Module not found: Can't resolve 'prismjs/components'

### ISSUE THREAD

**Issue by cmfcmf** [facebook/docusaurus#2385]
## 🐛 Bug Report

After upgrading to alpha 44 (and installing `@babel/preset-typescript` manually), I get this error when running `yarn start`:

```
./node_modules/@docusaurus/theme-classic/src/prism-include-languages.js
Module not found: Can't resolve 'prismjs/components' in '/home/cmfcmf/dev/OpenWeatherMap-PHP-Api/docs/node_modules/@docusaurus/theme-classic/src'
```

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes.

## To Reproduce

1. Upgrade site to alpha 44
2. `yarn add @babel/preset-typescript`
3. Try to build/start site

## Expected behavior

Building / developing the documentation works without error.

## Actual Behavior

Both `yarn start` and `yarn build` fail with:

```
./node_modules/@docusaurus/theme-classic/src/prism-include-languages.js
Module not found: Can't resolve 'prismjs/components' in '/home/cmfcmf/dev/OpenWeatherMap-PHP-Api/docs/node_modules/@docusaurus/theme-classic/src'
```

## Your Environment

- Docusaurus version used: 2.alpha 44
- Environment name and version (e.g. Chrome 78.0.3904.108, Node.js 10.17.0): Node 10
- Operating system and version (desktop or mobile): Ubuntu 18.04

## Reproducible Demo

The site in the docs folder on the `docusaurus-issue` branch can be used to reproduce this behavior: https://github.com/cmfcmf/OpenWeatherMap-PHP-API/tree/docusaurus-issue/docs

**Comment by lex111** [comment]
Thank you for the report. Fixed in [v2.0.0-alpha.48](https://github.com/facebook/docusaurus/releases/tag/v2.0.0-alpha.48). Sorry about that.
