### ISSUE TITLE
Markdown Header Anchor Links do not work on page load

### ISSUE THREAD

**Issue by Noah-Silvera** [facebook/docusaurus#2399]
## 🐛 Bug Report

Each markdown header has a targeted anchor link which corresponds to a URL.
i.e. http://<hostname>/docs/mobile/doc1#header1

If you click on the headers in the right sidebar when the documentation is loaded, the page scrolls to the header that is the anchor link target as expected.

**But,** if you copy a link to one of the headers with a anchor `#` in it, and paste it into a new tab, the page does not scroll to the appropriate header on page load. 

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

yes

## To Reproduce

1. Create a new site using npx @docusaurus/init@next init test-site classic
1. `yarn start`
1. Open http://localhost:3000/docs/doc1#admonitions

## Expected behavior

The page `doc1` is opened and scrolled to the admonitions header

## Actual Behavior

The page `doc1` is opened **but not** scrolled to the admonitions header
## Your Environment

- Docusaurus version used:
    "@docusaurus/core": "^2.0.0-alpha.48",
    "@docusaurus/preset-classic": "^2.0.0-alpha.48",
- Chrome Version 80.0.3987.132
- Windows 10 Desktop

## Reproducible Demo

This repo is an unmodified `npx @docusaurus/init@next init test-site classic` but including for completeness
https://github.com/Noah-Silvera/docusaurus-anchor-links-bug

**Comment by lex111** [comment]
Is there a similar bug on the builded website? This should be relevant only in development mode.

**Comment by Noah-Silvera** [comment]
No there is no similar bug in prod. It only affects development mode.

**Comment by lex111** [comment]
In dev mode, we do not use SSR, so this issue occurs. I do not think this is a serious bug, since there is no such thing in the production build. This may not be very comfortable, although it is unlikely that you will often use anchors links in dev mode :man_shrugging:.

**Comment by Noah-Silvera** [comment]
Should we just close this issue then? Seems very minor if it only affects dev mode.
Might be worth documenting under https://v2.docusaurus.io/docs/markdown-features#markdown-headers?

**Comment by Mauriceac** [comment]
I have this bug even after building.

Any workaround (other than refreshing, which effectively works)?

**Comment by jsphstls** [comment]
I see the same bug for builds with `"@docusaurus/core": "2.0.0-beta.4"`

**Comment by jsphstls** [comment]
I found a cross-page anchor link that is working on the current Docusaurus site. See the “multi-instance plugins” link under [https://docusaurus.io/docs/blog#multiple-blogs](https://docusaurus.io/docs/blog#multiple-blogs).

**Comment by k8w** [comment]
Still have this problem, latest version

**Comment by Mauriceac** [comment]
> Still have this problem, latest version
@k8w, me too. You might want to follow [issue 3081](https://github.com/facebook/docusaurus/issues/3081). It explains the problem, although no solution has been given yet.
