### ISSUE TITLE
[Docs] Document how links to other pages should be formatted

### ISSUE THREAD

**Issue by hramos** [facebook/Docusaurus#240]
Should clients update all their links?

React Native's links are in the following format: 

```
[Tutorial](docs/tutorial.html)
```

This is resulting in broken links to docs/docs/tutorial.html.  I fixed it by updating the link to

```
[Tutorial](Tutorial.md)
```

This is sort of documented in the `basics` example, in doc2.md, but it could be more obvious (maybe as part of Preparing your Site).

**Comment by ppatel221** [comment]
Hey I'm a student in an open source development class. Can i help with this bug?

**Comment by JoelMarcey** [comment]
@ppatel221 Hi! Absolutely. Please send a pull request. We would be happy to review it.

**Comment by JoelMarcey** [comment]
...and if afterwards (or in parallel) you want something code related and related to this issue, there is https://github.com/facebook/Docusaurus/issues/257 as well.

**Comment by ppatel221** [comment]
I can also take a look at that bug!  Can you help me get started with this? What would be my first step

**Comment by JoelMarcey** [comment]
@ppatel221 I wold start by reading the [contributing documentation](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md). That should help you get oriented on how to generally make pull requests for this project.

**Comment by ppatel221** [comment]
I've requested PR for one of the links I updated. Are there more places that need these updates?
https://github.com/facebook/Docusaurus/pull/366

**Comment by ppatel221** [comment]
Ive requested a PR here as well https://github.com/reactjs/reactjs.org/pull/478

**Comment by alexkrolick** [comment]
@ppatel221 ReactJS doesn't use Docusaurus, I think you may have intended to update the React Native docs.
