### ISSUE TITLE
[Feature Request] Add a copy to clipboard button for Color Scheme

### ISSUE THREAD

**Issue by Naturalclar** [facebook/docusaurus#2400]
## 🚀 Feature

Adding a `copy to clipboard` button for each hex value generated by the color generator.

<img width="674" alt="Screen Shot 2020-03-11 at 7 32 01 PM" src="https://user-images.githubusercontent.com/6936373/76407952-880aa300-63cf-11ea-8c59-e7444531e542.png">

## Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## Motivation

Adding a `copy to clipboard` button for each hex value to make the work easier for those who want to set up their color scheme.

## Pitch

This feature will save some time when trying to migrate from docusaurus 1 to docusaurus 2 and getting the desired color scheme of the docusaurus 2 website.

It reduces the number of time user needs to enter `Command + C` and the user can focus on `Command + V`

**Comment by lex111** [comment]
Better add this button to code block, right?

![image](https://user-images.githubusercontent.com/4408379/76409394-5d085b00-639f-11ea-8c39-db6b2446ab87.png)

**Comment by Naturalclar** [comment]
@lex111 oh wow, I didn't even realize that code block was also being generated 🤣 
yes, a copy button in the generated code block would be awesome.

**Comment by yangshun** [comment]
If you want to copy the individual colors, just double click on the hex code. I don't think it's worth adding the copy button to each row. Copy button is more useful when users have to copy multiple lines of code.
