### ISSUE TITLE
MDX does not render correctly

### ISSUE THREAD

**Issue by maxarndt** [facebook/docusaurus#2402]
## 🐛 Bug Report

MDX does not render correctly.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

yes

## To Reproduce

1. Setup a fresh docusaurus v2 project: `npx @docusaurus/init@next init docu-test classic`
1. Replace content of `docs/mdx.md` with the raw content of the following [gist](https://gist.github.com/maxarndt/ebe535523b7e2fc84d2ba7a4bf0a7c3e).
1. `npm start`
1. Open the docs page `http://localhost:3000/docs/mdx` with the browser of your choice.

## Expected behavior

The value of my constant `myVar` should be rendered for all three expressions.

## Actual Behavior

![mdx_rendered](https://user-images.githubusercontent.com/8988283/76502591-89c27e00-6444-11ea-8937-80a9548d81ea.png)

## Your Environment

- Docusaurus version used: `"2.0.0-alpha.43"`
- Environment name and version:
  - Node.js: `v10.16.3`
- Operating system and version: MacOS 10.15.3

## Reproducible Demo

Here you can find a working demo of this issue: https://github.com/maxarndt/docusaurus-v2-broken-mdx-demo

**Comment by yangshun** [comment]
Repro case attached here for easier reference:

```
export const myVar = 'hello mdx';

<strong>{myVar}</strong> is the var. MyVar: <strong>{myVar}</strong>

My var is <strong>{myVar}</strong>
```

I don't think this is something to do with Docusaurus. Might want to file on the MDX repo instead. Anyway one easy work-around for you is to wrap the line which doesn't render properly with a `<div>`, which "turns on JSX mode" for that line.

**Comment by maxarndt** [comment]
My bad! The [mdx docs](https://mdxjs.com/getting-started#jsx) explicitly say:
> Any line that start with the < characters starts a JSX block.
