### ISSUE TITLE
Documentation-only sites do not work if baseUrl is not `/`

### ISSUE THREAD

**Issue by rlamana** [facebook/docusaurus#2404]
## 🐛 Bug Report

A docusaurus site (v2) without a landing page and documentation as the index page does not work if `baseUrl` is other than `/`.

It seems like `@docusarus-utils`.`normalizeUrl` is generating double forward slashes when `routeBasePath` is set to a single '/' in the docs plugin configuration.

For a `baseUrl: 'metro/'` and `docs.routeBasePath: '/'` the generated routes are:

```
...
/metro//2.0.0-alpha.43/using-plugins
/metro//2.0.0-alpha.43/using-themes
/metro//2.0.0-alpha.43/versioning
/metro//next/blog
/metro//next/cli
/metro//next/configuration
/metro//next/contributing
/metro//next/creating-pages
...
```

When navigating to `/metro/next/blog`, react-router finds no match and the "Page not found" message is loaded instead.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes.

## To Reproduce

Using docusaurus' `website/` in the repository as an example:

1. Set `baseUrl` to `/metro/` in your `docusaurus.config.js`.
1. Set `routeBasePath ` to `/` in  the `@docusaurus/preset-classic.docs` section of your `docusaurus.config.js`.
1. Run `yarn start` 
1. Navigate to `https://localhost:3000/metro/introduction`
1. "Page not found: is displayed.

## Expected behavior

`https://localhost:3000/metro/introduction` should have loaded the Introduction page (in docs/introduction.md), just like `https://localhost:3000/docs/introduction` loads it when baseUrl and routeBasePath have their default values.

## Your Environment

- Docusaurus version used: 2.0.0-alpha.48
- Environment name and version (e.g. Chrome 78.0.3904.108, Node.js 10.17.0): Node.js v10.19.0
- Operating system and version (desktop or mobile): MacOS X Catalina 10.15.2

**Comment by yangshun** [comment]
Sorry our previous docs-only instructions were incorrect. We've updated it but have yet to publish it - https://v2.docusaurus.io/docs/next/configuration/#docs-only-mode

**Comment by tnir** [comment]
As I've got lost multiple times during several month to find this modification, I would like to add a note: as of 2.0.0-beta.0 (and 2.0.0-beta.1), the URL is at https://docusaurus.io/docs/docs-introduction#docs-only-mode

**Comment by joe-bell** [comment]
I'm also experiencing this issue locally with the setup above/in the docs:

```js
module.exports = {
  baseUrl: "/docs/",
  presets: [
    [
      "@docusaurus/preset-classic",
      {
        docs: {
          sidebarPath: require.resolve("./sidebars.js"),
          path: "docs",
          routeBasePath: "/",
        },
        blog: false,
        theme: {
          customCss: require.resolve("./src/css/custom.css"),
        },
      },
    ],
  ],
```

Which works completely fine in development, but with `build && serve` will output

<img width="430" alt="Screenshot 2021-06-07 at 20 49 04" src="https://user-images.githubusercontent.com/7349341/121065782-ce68d080-c7d1-11eb-8cdb-07f3223c0728.png">

**Comment by slorber** [comment]
@joe-bell this is a bug: https://github.com/facebook/docusaurus/issues/3291

To fix it locally you could probably move `build` to `build/docs` and run `docusaurus serve` again

**Comment by joe-bell** [comment]
Thanks for the quick response @slorber – this workaround seems to do the trick for now

**Comment by sanamhub** [comment]
I'm getting the same error at: https://blc-bit.github.io/notes/

Can anyone help?

GitHub repo: https://github.com/blc-bit/notes

**Comment by Josh-Cena** [comment]
@sanamhub Your site is working perfectly. What's the error? What's your desired effect?

Please don't necropost under a super-old issue. It's obviously resolved and irrelevant to your issue.

**Comment by sanamhub** [comment]
> @sanamhub Your site is working perfectly. What's the error? What's your desired effect?
> 
> Please don't necropost under a super-old issue. It's obviously resolved and irrelevant to your issue.

I fixed it, thanks anyway!

**Comment by sanamhub** [comment]
> how did you fix it?

I can't recall as of now 😞

**Comment by haixuanTao** [comment]
Just for people facing the same issue. Deleting `baseUrl`, building and putting back, removed the issue for me, lol.

Maybe a cache error somewhere.
