### ISSUE TITLE
Support custom build path

### ISSUE THREAD

**Issue by joe223** [facebook/docusaurus#2410]
## 🚀 Feature

Add a new configuration of docusaurus `output` with default value `build`

## Have you read the [Contributing Guidelines on issues]yes

Yes

## Motivation

We can build static web site to specific directory directly with any other actions. That would be more convenient.

## Pitch

Just likes:

```javascript
// docusaurus.config.js
module.exports = {
  // ...
  output: '../docs' // default value: build
```
If we execute `npm run build`, the build assets are save at `../docs` directory.

**Comment by yangshun** [comment]
Sure, we don't mind accepting such a flag.

Alternatively, if you want to unblock yourself, you could also modify your `package.json`'s `build` command and add a [`mv`](https://shapeshed.com/unix-mv/) after it:

```
{
  "scripts": {
    "build": "docusaurus build && mv build <new directory>",
    ...
  },
  ...
```

**Comment by joe223** [comment]
@yangshun Thanks for the advise, that is what I did so far.  I don't need to ensure the new directory is empty in case the build command break off if we got `output` configuration. 😁

**Comment by yangshun** [comment]
Ok then do `docusaurus build && rm -rf <new directory> && mv build <new directory>`

**Comment by joe223** [comment]
Thanks again! @yangshun

**Comment by yangshun** [comment]
@jsjoeio I heard from @JoelMarcey you would like to work on some ramp up tasks. Would you be interested in this?

**Comment by jsjoeio** [comment]
Hi @yangshun! That's right. This one sounds good to me, sure!

**Comment by cangSDARM** [comment]
Is it just not comprehensive enough in the build command? We want to change this output directory when running `docusaurus start`

**Comment by cangSDARM** [comment]
The static file directory doesn't seem to support relative directories either, which is needed in our project (a project that generates documentation dynamically)

**Comment by hrumhurum** [comment]
The build command option does not cover the desired use case as we need to run `npm run serve` command as well and it should use the right build directory.

This means that the output directory should be specified in `docusaurus.config.js` file in order to be universally useful.

**Comment by slorber** [comment]
Both build/serve commands take an output dir option, and there's even a `--build` option on the serve command. We don't plan to add output dir to the config sorry

**Comment by horse-world** [comment]
> 构建命令选项不涵盖所需的用例，因为我们还需要运行`npm run serve`命令，并且它应该使用正确的构建目录。
> 
> 这意味着应该在`docusaurus.config.js`文件中指定输出目录以便通用。

have you solven this problem?

**Comment by martian17** [comment]
> Both build/serve commands take an output dir option, and there's even a `--build` option on the serve command. We don't plan to add output dir to the config sorry

Command option is prone to error, as you need to change each command carefully when you make changes to the out-dir. That's why we need a single place were the config is handled. In other libraries, configurations often mirror command line options, so it should be for docusaurus as well.
