### ISSUE TITLE
Broken some CSS tags from Docusaurus CSS stylesheet

### ISSUE THREAD

**Issue by raisty** [facebook/docusaurus#2414]
## 🐛 Bug Report

`html, body, div, span, applet, object, iframe, h1, h2, h3, h4, h5, h6, p, blockquote, pre, a, abbr, acronym, address, big, cite, code, del, dfn, em, img, ins, kbd, q, s, samp, small, strike, strong, sub, sup, tt, var, b, u, i, center, dl, dt, dd, ol, ul, li, fieldset, form, label, legend, table, caption, tbody, tfoot, thead, tr, th, td, article, aside, canvas, details, embed, figure, figcaption, footer, header, hgroup, menu, nav, output, ruby, section, summary, time, mark, audio, video` shouldn't have defined margin: 0 and vertical-align: baseline

It can cause a problem with for example: `<sup>`, `<sub>`, `<dl>`, etc.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

👍

## To Reproduce

(Write your steps here:)

1. Start Docusaurus
1. Define in doc/page element like `<sup>` etc.

## Expected behavior

Correct initial CSS.

## Actual Behavior

Broke CSS for some tags.

(Write what happened. Add screenshots, if applicable.)

## Your Environment

- Docusaurus version used: 1.14.4
- Environment name and version (e.g. Chrome 78.0.3904.108, Node.js 10.17.0): Node.js v10.15.3
- Operating system and version (desktop or mobile): MacOS Catalina

## Reproducible Demo

Initial install only create `<sup>`, `<sub>` or `<dl>` in some file and follow result.

**Comment by yangshun** [comment]
We use a CSS reset in v1 and that's the point of a CSS reset. To reset the default browser styling. You'd have to add your own styling for those elements.

**Comment by raisty** [comment]
Sure, this is best solution to reset. Unfortunately there are not correct defined some elements...
I can give you some fixes, if you want.
But seems better will be release v2... 🐐
