### ISSUE TITLE
Console error in IE 11

### ISSUE THREAD

**Issue by hotlong** [facebook/docusaurus#2418]
## 🐛 Bug Report

SCRIPT438: Object does not support "assign" attribute or method.
main.2d92dee9.js (2,45516)

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

(Write your answer here.)

## To Reproduce

(Write your steps here:)

1. Open IE 11
1. navigate to https://v2.docusaurus.io/docs/introduction/

## Expected behavior

no error

## Actual Behavior

SCRIPT438: Object does not support "assign" attribute or method.
main.2d92dee9.js (2,45516)

## Your Environment

- Docusaurus version used: v2.alpha.48
- Environment name and version (e.g. Chrome 78.0.3904.108, Node.js 10.17.0): IE 11.719.18362.0
- Operating system and version (desktop or mobile): Win 10

## Reproducible Demo

(Paste the link to an example repo, including a `siteConfig.js`, and exact instructions to reproduce the issue.)
https://github.com/facebook/docusaurus

**Comment by RDIL** [comment]
Hi!  I'd love to help.  The translation of the error looks to be `SCRIPT438: Object does not support "assign" attribute or method`.  

Can you please attach the file `main.2d92dee9.js` from your site build?

**Comment by hotlong** [comment]
Thanks RDIL，To reproduce this error, Open IE 11,
navigate to https://v2.docusaurus.io/docs/introduction/
You can see the page has lot of bugs, and debug console has some error messages.

**Comment by lex111** [comment]
Unfortunately, IE11 support is unlikely to improve in the future. It's pretty hard to maintain this old browser.

**Comment by lex111** [comment]
To avoid duplication of this problem, we leave only one issue is #2657 and close current one.
We also explicitly noted on the v2 site about the current status support of IE11, so that people know about it.
Any help is appreciated as always.

![image](https://user-images.githubusercontent.com/4408379/80687658-4d6dde80-8ad3-11ea-9cfb-d2cc4a996055.png)
