### ISSUE TITLE
Adding class to markdown header puts class name in URL

### ISSUE THREAD

**Issue by adamstevens87** [facebook/docusaurus#2419]
Example: 

`### My Great Heading {#custom-id}`

Output URL: 
http://someurl.com#my-great-heading-custom-id

Expected output URL: 
http://someurl.com#my-great-heading

I am adding a custom class to my header to add styling as needed. However, this impacts the URL of the header in an unexpected (and unwanted) way.

I also tried: 

`### <span class="class-name"> Title </span> `

but this output is even worse! :)

**Comment by lex111** [comment]
This syntax is used to define a custom ids for the headings, see https://www.markdownguide.org/extended-syntax/#heading-ids for details.

So when you use this code:

```
### My Great Heading {#custom-id}
```

URL will be like this: http://someurl.com#custom-id

However, I think we can add support for this feature in v2. @yangshun agree with this?

* * *

But in fact, this does not apply to the topic of this issue. 

@adamstevens87 you just need to use the explicitly appropriate HTML tag to make it possible to style it:

```html
<h3 class="class-name"> Title </h3>
```

**Comment by adamstevens87** [comment]
Hi @lex111 - thanks for you answer - I reaslie the title was misleading, but I also tried: 

## <span class="faq-header"> General </span> 

And the output URL is: 

https://dosomeutl.com#span-classfaq-header-general-span

I wanted to use the ## notation so the title was added to the sidebar. 

Is there something I am missing?

**Comment by lex111** [comment]
@adamstevens87 I see, then when generating slug we will not consider any HTML, and in the end slug will be clean (just `general` in your case).

**Comment by adamstevens87** [comment]
Thanks for confirming.
