### ISSUE TITLE
[Docs] Document how static assets (such as images) should be handled

### ISSUE THREAD

**Issue by hramos** [facebook/Docusaurus#242]
See https://github.com/facebookexperimental/Docusaurus/blob/master/lib/server/generate.js#L183

It looks like we automatically handle converting 'assets/' references to 'docs/assets'.

Does that mean I should create an 'assets' folder in my docs folder for all my images? Will Docusaurus copy images from that assets folder to the right place?

**Comment by zhaozhiming** [comment]
Yes. The example as bellow should be change to `![alt-text](assets/doc-image.png)`.   
And it seems have been changed already.

![image](https://user-images.githubusercontent.com/1436694/34077349-df935ac4-e33c-11e7-9b2e-94d96a27cc8f.png)

**Comment by longility** [comment]
I believe this issue can be closed.

**Comment by JoelMarcey** [comment]
@longility Did we document this? Sometimes I forget 😄

**Comment by longility** [comment]
@JoelMarcey I by no means have tested what this documentation says. I'm just helping close some issues so I may not be too familiar with this.  

After a little more investigation, the generated doc from [gh-pages](https://github.com/facebook/Docusaurus/blob/75d4655416f776529b9c99871b0b028ff2262e0d/docs/en/doc-markdown.html#L63) does not reflect the [markdown source](https://github.com/facebook/Docusaurus/blob/master/docs/api-doc-markdown.md#linking-to-images-and-other-assets). Not sure why as I would expect it to have already been deployed as it has been more than seven months.

**Comment by endiliey** [comment]
@longility: Changes to docs/ are reflected in the next "master" version.

I am closing this issue. It is documented at
https://docusaurus.io/docs/en/doc-markdown.html#linking-to-images-and-other-assets
