### ISSUE TITLE
Files with extension '.markdown' are not detected by our plugin of docs

### ISSUE THREAD

**Issue by fanny** [facebook/docusaurus#2422]
## 🐛 Bug Report

I'm trying to build the watchman doc using the docusaurus v2, and to reuse some files of the older structure, I decided to move all old markdown files, to my new project. But, when i tried to build the site with the `.markdown` extension I didn't have success. Only when I change to `.md` file

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes
## To Reproduce

Put an file on docs folder with `.markdown` extension

## Expected behavior

Render my page as usual

## Actual Behavior

Page Not Found screen is rendered.

## Your Environment

- Docusaurus version used: 2.0.0-alpha.48
- Environment name and version (e.g. Chrome 78.0.3904.108, Node.js 10.17.0):
- Operating system and version (desktop or mobile): MacOs 13-inch 2019

## Reproducible Demo
[imgur](https://imgur.com/onIB9g9)

(Paste the link to an example repo, including a `siteConfig.js`, and exact instructions to reproduce the issue.)

**Comment by yangshun** [comment]
Older Jekyll templates use `.markdown` extensions whereas these days Markdown files commonly use `.md`. It's not tough to support `.md` but we think it's unnecessary given that it's extremely rare now. We can close this.
