### ISSUE TITLE
Navbar hideOnScroll: true shows light mode logo in dark mode

### ISSUE THREAD

**Issue by nicholas-ochoa** [facebook/docusaurus#2430]
## 🐛 Bug Report

I have the following settings configured:

```
themeConfig.navbar.hideOnScroll = true
themeConfig.navbar.logo.src = 'logo.png'
themeConfig.navbar.logo.srcDark = 'logo_dark.png'
```

When I scroll down the page in dark mode, the nav bar disappears as expected but the logo above the sidebar is the normal logo and not the logo specified in `srcDark`.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## To Reproduce

(Write your steps here:)

1. Configure a dark mode logo that differs from the normal logo
1. Set hideOnScroll to `true`
1. Scroll a page in dark mode

## Expected behavior

Dark mode logo should be displayed above side bar.

## Actual Behavior

Default (light mode) logo is displayed incorrectly above sidebar when scrolling. Navbar has the correct logo.

## Your Environment

- Docusaurus version used: 2.0.0-alpha.48
- Environment name and version (e.g. Chrome 78.0.3904.108, Node.js 10.17.0): Node 12.13.0
- Operating system and version (desktop or mobile): Windows 10

**Comment by lex111** [comment]
Oops, good catch, thanks, this will be fixed in the next release (end of March)!
