### ISSUE TITLE
[v2] yarn build hangs forever after build is completed successfully

### ISSUE THREAD

**Issue by avkonst** [facebook/docusaurus#2431]
## 🐛 Bug Report

Docs for my project can not be built non-interactively as 'yarn-build' hangs forever.

### Have you read the [Contributing Guidelines on issues]
yes

## To Reproduce

> git clone https://github.com/avkonst/hookstate
> cd hookstate/hookstate.js.org/docs2
> yarn build

## Expected behavior

Build is finished and process exists

## Actual Behavior

Build is successful (according to logs), but the process does not exit.

## Your Environment

- Docusaurus version used: 2 alpha 48
- Operating system and version (desktop or mobile): see it on linux (netlify automated build) and windows (my working desktop)

## Reproducible Demo

See above how to reproduce

**Comment by tomByrer** [comment]
I got the same hung issue, even though on the same system running the basic template (`npx @docusaurus/init@next init my-website classic`) ran fine.

Perhaps something with your config?  I do not get the following errors installing the template:

```bash
git clone https://github.com/avkonst/hookstate
cd hookstate/hookstate.js.org/docs2
yarn build
yarn install v1.22.1
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@2.1.2: The platform "win32" is incompatible with this module.
info "fsevents@2.1.2" is an optional dependency and failed compatibility check. Excluding it 
from installation.
info fsevents@1.2.11: The platform "win32" is incompatible with this module.
info "fsevents@1.2.11" is an optional dependency and failed compatibility check. Excluding it
 from installation.
[3/4] Linking dependencies...
warning " > @babel/preset-typescript@7.8.3" has unmet peer dependency "@babel/core@^7.0.0-0".
warning " > @docusaurus/preset-classic@2.0.0-alpha.48" has incorrect peer dependency "@docusa
urus/core@^2.0.0".
warning "@docusaurus/preset-classic > @docusaurus/plugin-content-blog@2.0.0-alpha.48" has inc
orrect peer dependency "@docusaurus/core@^2.0.0".
warning "@docusaurus/preset-classic > @docusaurus/plugin-content-docs@2.0.0-alpha.48" has inc
orrect peer dependency "@docusaurus/core@^2.0.0".
warning "@docusaurus/preset-classic > @docusaurus/plugin-content-pages@2.0.0-alpha.48" has in
correct peer dependency "@docusaurus/core@^2.0.0".
warning "@docusaurus/preset-classic > @docusaurus/plugin-google-analytics@2.0.0-alpha.48" has
 incorrect peer dependency "@docusaurus/core@^2.0.0".
warning "@docusaurus/preset-classic > @docusaurus/plugin-google-gtag@2.0.0-alpha.48" has inco
rrect peer dependency "@docusaurus/core@^2.0.0".
warning "@docusaurus/preset-classic > @docusaurus/plugin-sitemap@2.0.0-alpha.48" has incorrec
t peer dependency "@docusaurus/core@^2.0.0".
warning "@docusaurus/preset-classic > @docusaurus/plugin-sitemap@2.0.0-alpha.48" has incorrec
t peer de peer dependency "@docusaurus/core@^2.0.0".
pendency "@docusaurus/core@^2.0.0".
warning "@docusaurus/preset-classic > @docusaurus/theme-classic@2.0.0-alpha.48" has incorrec
t peer depwarning "@docusaurus/preset-classic > @docusaurus/theme-search-algolia@2.0.0-alpha.48" has in
                                                                                                                            wwarning "@docusaurus/preset-classic > @docusaurus/theme-search-algolia@2.0.0-alpha.48" has incorrect peer dependency "@docusaset-classic > @docusaurus/theme-classic@2.0.0-alpha.48" has unmet peer dependency "webp  ack@^4.41.2".                    aur dependency "@docusaurus/core@^2.0.0".
warning "@docusaurus/preset-classic > @docusaurus/theme-classic > react-toggle@4.1.1" has unmet peer dependency "prop-types@^15.3.0 
|| ^16.0.0".
[4/4] Building fresh packages...
success Saved lockfile.
Done in 30.49s.
```

**Comment by lex111** [comment]
Resolved in #2443.

**Comment by jmlopez-rod** [comment]
I think this bug is back in 3.6.0, the build is successful but the process never exits. Not sure if it's worth opening another issue given that this is the exact issue I'm experiencing right now.

**Comment by slorber** [comment]
@jmlopez-rod yes it's mentioned in the release notes:

> We [removed a process.exit(0)](https://github.com/facebook/docusaurus/pull/10410) that can hide memory leaks in your own code and third-party plugins

Adding this code was a bad idea that hides problems on your own site. You should figure out the problem on your site and the build will terminate.

At best, I'm ok to add a CLI option `--force-terminate`, or a secret env variable. But it has to be opt-in, and not the default, because we really want you to be aware and fix the leaks you have on your site.

Please join the conversation at https://github.com/facebook/docusaurus/pull/10410, I can help troubleshoot it if you provide a repro.
