### ISSUE TITLE
Markdown code block does not correctly render \$

### ISSUE THREAD

**Issue by bravo-kernel** [facebook/docusaurus#2441]
## 🐛 Bug Report

Inside a markdown code block, `\$` is presented as `$`.

## To Reproduce

1. create a new docs page (`.md` or `.mdx`)
2. add the following markdown code block:

     ```markdown
    $here = Split-Path -Parent $MyInvocation.MyCommand.Path
    $sut = (Split-Path -Leaf $MyInvocation.MyCommand.Path) -replace '\.Tests\.', '.'
    . "$here\$sut"
     ```
3. view rendered page

## Expected behavior

We expect to see `$here\$sut` on rendered page

## Actual Behavior

We see `$here$sut` on rendered page

![image](https://user-images.githubusercontent.com/230500/77249025-86967180-6c3e-11ea-8c63-da336dbd5a60.png)

## Your Environment

- D2
- all browsers, all OSes

## Reproducible Demo

- Incorrectly rendered output at https://pester.dev/docs/quick-start#creating-a-pester-test
- Markdown source file https://github.com/pester/docs/blob/master/docs/quick-start.mdx#creating-a-pester-test

❤️

**Comment by yangshun** [comment]
It's actually an MDX bug. We previously reported it at https://github.com/mdx-js/mdx/issues/902.

**Comment by bravo-kernel** [comment]
@yangshun thanks for confirming this one, I looked for two hours but could not find anything. Let's await their fix 👍

**Comment by bravo-kernel** [comment]
for future reference: does this mean mdx-js is used for both `.md` and `.mdx` file rendering?

**Comment by yangshun** [comment]
@bravo-kernel I doubt this bug is a serious one and it's unlikely to get prioritized. It might never be fixed.

Yes MDX is being used for both `.md` and `.mdx`

**Comment by bravo-kernel** [comment]
Thanks for confirming 💯. Maybe I can motivate someone to fix this one.

**Comment by yangshun** [comment]
Addressed in https://github.com/mdx-js/mdx/pull/991

**Comment by bravo-kernel** [comment]
🎉
