### ISSUE TITLE
Prettier breaks `remark-admonitions`

### ISSUE THREAD

**Issue by elviswolcott** [facebook/docusaurus#2452]
## 🐛 Bug Report

`yarn prettier-docs` breaks the formatting of `remark-admonitions`

I believe it may be related to, but am not that familiar with prettier's rules to be sure.
https://prettier.io/docs/en/options.html#prose-wrap

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## To Reproduce

Evidence of broken admonitions due to format:

1. `mkdir repro-prettier-format && cd repro-prettier-format`
1. `npx @docusaurus/init@next init website classic`
1. `cd website && npm start`

## Expected behavior

The admonitions should not be flattened to a single line.

## Actual Behavior

Prettier flattens admonitions to a single line.

i.e.

```
:::tip
This is a tip
:::
```
becomes
```
:::tip This is a tip :::
```

Example:
https://github.com/facebook/docusaurus/commit/756c83aad8ee4e0bfc3df6725c22b4bd01b85c91

## Your Environment

N/A: Not an issue with docusaurus 😄 

## Reproducible Demo

Just `yarn prettier-docs` with an admonition in any file and it will happen.
Happening on the `master` branch of [elviswolcott/docusaurus](https://github.com/elviswolcott/docusaurus) in `website/docs/deploying.md` and `website/docs/deployment.md` and `website/docs/using-plugins.md`.

**Comment by yangshun** [comment]
I'm not sure of a good way around this. What we've done here in Docusaurus v2 website is to add extra empty lines around the content so that Prettier respects the line breaks.

```
:::tip

This is a tip

:::
```

**Comment by elviswolcott** [comment]
That seems like a workable solution for the time being. I'll update the templates for `@docusaurus-init` to be formatted that way (and anywhere in the docs that prettier is trying to change right now).
