### ISSUE TITLE
Unable to set C# for code styling

### ISSUE THREAD

**Issue by adamstevens87** [facebook/docusaurus#2459]
Example: 

```cs
private void DoSomeStuff() {

    // Stuff
}

private void DoSomeMoreStuff() {
    
    // More Stuff
}
```
![image](https://user-images.githubusercontent.com/16194236/77404273-5e775180-6da9-11ea-8023-e5768d8e14fa.png)

However, js does apply styling. Example:

```js
function myFunction(p1, p2) {
  return p1 * p2;   // The function returns the product of p1 and p2
}
```

![image](https://user-images.githubusercontent.com/16194236/77404402-95e5fe00-6da9-11ea-80ec-90cd10d5a8a9.png)

**Comment by yangshun** [comment]
You might need to add it into the additional supported languages - https://v2.docusaurus.io/docs/markdown-features/#syntax-highlighting

**Comment by adamstevens87** [comment]
Oh, yes that worked. I added csharp as a language - sorry for the unnecessary 'bug'. 

I would have expected cs to be common enough to be default!
