### ISSUE TITLE
feat(v2): add time prediction in the description of a post blog

### ISSUE THREAD

**Issue by fanny** [facebook/docusaurus#2467]
## 🚀 Feature

In our blog plugin, it can be in interesting adds a time prevision of blog post.

## Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

yes
## Motivation

Its very common in modern web blogs(some examples are: medium; dev.to and etc), to have the time prediction in the description

## Pitch

(Please explain why this feature should be implemented and how it would be used.)

It's a factor that many readers, consider it before deep dive in a blog post, so would it be nice to have here in docusaurus.

**Comment by yangshun** [comment]
Yes! Sounds good, this can be an option on the blog plugin 😄

**Comment by lex111** [comment]
@yangshun do we really want to include this in core? Or will it be done as a plugin?

**Comment by yangshun** [comment]
It'll be in the blog plugin, not Docusaurus core. We don't have a good way of augmenting data to plugins at the moment.

**Comment by fanny** [comment]
Yeah, I was thinking in a extension for `@docusaurus-plugin-content-blog`

**Comment by JoseRenan** [comment]
Hi! I'm a first-time contributor on docusaurus, could I work on this issue?
