### ISSUE TITLE
Built-in Flow support

### ISSUE THREAD

**Issue by yangshun** [facebook/docusaurus#2468]
## 🚀 Feature

Docusaurus supports TypeScript out of the box now but it'd be cool if we had Flow support out of the box without having to modify/extend the Babel config.

## Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

**Comment by fanny** [comment]
I was thinking if can be a plugin. 

It would be interesting if the developer adds a field in the `.babelrc`, enabling the typescript or flow config, like:
`{
  "presets": [['@babel-react', { types: {"flow": true}}]]
}`

or 
`{
  "presets": [['@babel-react', { types: {"typescript": true}}]]
}`

and you make this setup depending of the option.

**Comment by fanny** [comment]
I also saw something similar of my idea in CRA [see](https://github.com/facebook/create-react-app/tree/master/packages/babel-preset-react-app)

**Comment by slorber** [comment]
@yangshun going to close this, as it's likely the community will adopt TS in priority over Flow, considering the recent announcements https://medium.com/flow-type/clarity-on-flows-direction-and-open-source-engagement-e721a4eb4d8b

It probably does not make sense to add Flow support by default.
Eventually, we can add it to the Facebook template, but not even sure it's too useful, as we now have a `babel.config.js` in the template, it should be easy to add support for Facebook projects that want to use Flow.  In practice, do you know of any project using Flow with Docusaurus?

**Comment by yangshun** [comment]
I think Docusaurus sites won't need that much Flow support (or even types) if it's mostly content. Agree we can close this.
