### ISSUE TITLE
Easier way to support redirects

### ISSUE THREAD

**Issue by ericnakagawa** [facebook/docusaurus#248]
Perhaps a bulk method for managing these -- especially helpful for an existing site migrating to Docusaurus.

"Docusaurus is pretty limited on where pages can go. For all of our sites, it's required adding a bunch of redirects to keep links working. I'd like to have an easier (automatic?) way to generate these other than copying and pasting a bunch of files in pages."

**Comment by azu** [comment]
I want to get this feature.
My site([almin](https://almin.js.org/https://github.com/textlint/textlint/issues/346#issuecomment-352193883)) use a workaround that embed redirect script in `404.html`

- https://github.com/almin/almin/blob/c2c676825b979b810bab6e431f115d897ac6a3fd/website/pages/en/404.js#L29-L79

For example, 

- [jekyll-redirect-from](https://github.com/jekyll/jekyll-redirect-from "jekyll-redirect-from") allow to use `redirect_from:` and `redirect_to:` directive.
- GitBook's [bulk redirects](https://github.com/getgauge-contrib/gitbook-plugin-bulk-redirect "bulk redirects") plugin allow to define `redirects.json`
- Netlify allow to defined [Redirect & Rewrite rules](https://www.netlify.com/docs/redirects/ "Redirect &amp; Rewrite rules | Netlify") (It is server side redirect)

**Comment by endiliey** [comment]
This is now possible with powerful v2 plugin system.

Example: someone created it programatically to redirect
https://github.com/CanopyTax/single-spa.js.org/blob/46b46c97e0dee70b2c65c2c41484422fe399e6eb/website/src/plugins/docusaurus-plugin-redirects/src/index.js

**Comment by yangshun** [comment]
@endiliey should we make that plugin by @lex111 a core plugin?

**Comment by endiliey** [comment]
I prefer not, if we're to maintain it, we need to make it very general. That one is still hardcoded and havent support a config for `from` and `to` redirect yet, Maybe not at this point, maybe on release.

It's like how wgao tried to create another theme-no-style, thankfully its not in docusaurus repo, there's been quite some breaking change on theme implementation alrd (eg: metadata, themeconfig, etc).

Less is better before we start to add more
