### ISSUE TITLE
docs(v2): document about allowing multiple blogs

### ISSUE THREAD

**Issue by uanaoeng** [facebook/docusaurus#2481]
## 🚀 Feature

I want to use docusaurus to organize my blog posts, which have different categories.

If I put these blog posts under the docs folder, I will need to manually add these blog posts to the sidebar, that would be a burdensome task.

If there is only one blog folder, I will not be able to sort these blog posts well.

## Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?
Yes.

**Comment by hotlong** [comment]
+1

**Comment by yangshun** [comment]
Is this for v2 or v1? It's not that obvious, but in v2 you can have multiple blogs as long as you specify your own blog plugin under the plugin section. Maybe we should be documenting this instead.

**Comment by yangshun** [comment]
I just tested it and it works

```js
plugins: [
    // ...
    [
      '@docusaurus/plugin-content-blog',
      {
        routeBasePath: 'my-blog',
        editUrl:
          'https://github.com/facebook/docusaurus/edit/master/website/my-blog',
        postsPerPage: 2,
        feedOptions: {
          type: 'all',
          copyright: `Copyright © ${new Date().getFullYear()} Facebook, Inc.`,
        },
      },
    ],
  ],
],
```

**Comment by uanaoeng** [comment]
> Is this for v2 or v1? It's not that obvious, but in v2 you can have multiple blogs as long as you specify your own blog plugin under the plugin section. Maybe we should be documenting this instead.

Hi, yangshun, thanks for your reply.

This is for v1. 

And in addition, I've find out that the TOC (Table Of Content), which is a important feature for me, is not available by default in v2, is this also can to be achieved by specifying the plugin?

**Comment by fanny** [comment]
> I just tested it and it works
> 
> ```js
> plugins: [
>     // ...
>     [
>       '@docusaurus/plugin-content-blog',
>       {
>         routeBasePath: 'my-blog',
>         editUrl:
>           'https://github.com/facebook/docusaurus/edit/master/website/my-blog',
>         postsPerPage: 2,
>         feedOptions: {
>           type: 'all',
>           copyright: `Copyright © ${new Date().getFullYear()} Facebook, Inc.`,
>         },
>       },
>     ],
>   ],
> ],
> ```
> 
> So what we have to do here is to document how to add another blog under `/docs/blog/`

Is basically provide other object like: 
```js
plugins: [
    // ...
    [
      '@docusaurus/plugin-content-blog',
      {
        routeBasePath: 'my-blog',
        editUrl:
          'https://github.com/facebook/docusaurus/edit/master/website/my-blog',
        postsPerPage: 2,
        feedOptions: {
          type: 'all',
          copyright: `Copyright © ${new Date().getFullYear()} Facebook, Inc.`,
        },
      },
     {
        routeBasePath: 'my-blog2',
        editUrl:
          'https://github.com/facebook/docusaurus/edit/master/website/my-blog2',
        postsPerPage: 2,
        feedOptions: {
          type: 'all',
          copyright: `Copyright © ${new Date().getFullYear()} Facebook, Inc.`,
        },
      },
    ],
  ],
],
```
And can we route for both things?
