### ISSUE TITLE
Background and foreground colours do not have a sufficient contrast ratio

### ISSUE THREAD

**Issue by gedenata** [facebook/docusaurus#2484]
## 🐛 Bug Report

Contrast — These are opportunities to improve the legibility of your content. Low-contrast text is difficult or impossible for many users to read.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## To Reproduce

* `<section className="copyright"></section>`. In the development, already changes the css `color` by **!important** in `/website/static/css/custom.css` to force the `color: rgba(255, 255, 255, 0.4);` and it's good but when deploy it to the production still no effect.

```bash
.nav-footer .copyright {
    color: #ffffff !important;
}
```

<img width="368" alt="Screen Shot 2020-03-30 at 16 23 12" src="https://user-images.githubusercontent.com/1158185/77891348-64869a00-72a3-11ea-8ebd-d623597d65cf.png">

## Expected behavior

* In development should same as production

## Your Environment

* Docusaurus version used: "docusaurus": "^1.14.4"
* Google Chrome Version 80.0.3987.149 (Official Build) (64-bit)
* macOS Mojave V.10.14.6

**Comment by yangshun** [comment]
PRs welcome!

**Comment by psjishnu** [comment]
@yangshun So is the issue the text color of footer 
![screen](https://user-images.githubusercontent.com/33541774/84107101-73739080-aa3a-11ea-8018-3a58617e1e9c.jpg)

**Comment by slorber** [comment]
@AARYAN-MAHENDRA I'm not totally sure to understand what you want to do.

The copyright and links of v1 footer are not very readable?

I'm not against using alpha 0.6 for copyright, and up to 0.8 for non-hovered links.

For example, in main.css:

from
```
.nav-footer .copyright {
  color: rgba(255, 255, 255, 0.4);
  text-align: center;
}
```

to 

```
.nav-footer .copyright {
  color: rgba(255, 255, 255, 0.6);
  text-align: center;
}
```

**Comment by slorber** [comment]
@gedenata also not sure what you mean by "in development same as production" and about using !important. to me updating main.css in docusaurus v1 seems to work fine.

**Comment by alexkrolick** [comment]
I am not sure if this was meant to be a catch-all for contrast issues, but there are a few other areas that need more contrast:

- Link/Primary color: #25c2a0 fails at every size
- Sidebar/Secondary color: #606770 marginal at smaller sizes

---

<img width="663" alt="Screen Shot 2021-01-05 at 12 25 26 PM" src="https://user-images.githubusercontent.com/1571667/103696034-84459f80-4f52-11eb-9b6c-949403c23f2e.png">

---

<img width="220" alt="Screen Shot 2021-01-05 at 12 25 31 PM" src="https://user-images.githubusercontent.com/1571667/103695643-d4703200-4f51-11eb-8a0d-85864a65799b.png">

**Comment by slorber** [comment]
The Docusaurus team is actively working on Docusaurus v2.

After a very long alpha, Docusaurus v2 is [now in beta](https://docusaurus.io/blog/2021/05/12/announcing-docusaurus-two-beta).
We believe that the v2 beta is already better than v1, and v2 is ready for maintstream adoption.

Apart from critical issues and security fixes, we don't plan to invest much time on Docusaurus v1 anymore.

We are all closing v1 issues. 
Maybe the current issue is already fixed in Docusaurus v2.
Please try to upgrade, and if the issue is still there on Docusaurus v2, open a new issue.

**Comment by alexkrolick** [comment]
@slorber the contrast ratios are still inaccessible in v2

**Comment by slorber** [comment]
@alexkrolick I suggest opening a dedicated issue with screenshots of what elements are inaccessible

It's likely that we'll always have at least some minor accessibility issues. I don't feel that we should have one big accessibility GitHub issue to report all problems in a messy way and that we'll keep open forever. But rather have 1 distinct issue per concrete problem that will be closed every time such problem is fixed.
