### ISSUE TITLE
v2: blog-only mode blog post link is broken

### ISSUE THREAD

**Issue by SamChou19815** [facebook/docusaurus#2493]
## 🐛 Bug Report

The link of blog post is prefixed with an additional `/`

<img width="936" alt="Screen Shot 2020-04-01 at 13 05 55" src="https://user-images.githubusercontent.com/4290500/78165815-e26cb180-7419-11ea-8324-2621722f3fde.png">

Even if I manually type the correct URL, it will say page not found.

<img width="1651" alt="Screen Shot 2020-04-01 at 13 11 24" src="https://user-images.githubusercontent.com/4290500/78166120-4f804700-741a-11ea-8511-0a3388a65a1c.png">

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## To Reproduce

(Write your steps here:)

1. Clone facebook/docusaurus repo
1. remove `website/src/pages/index.js `
1. Enable blog only mode by adding `routeBasePath: '/',` to `docusaurus.config.js` > presets > blog

## Expected behavior

URL is not prefixed with additional `/`

## Actual Behavior

URL prefixed with additional `/`

## Your Environment

- Docusaurus version used: v2-alpha-49
- Environment name and version (e.g. Chrome 78.0.3904.108, Node.js 10.17.0): Chrome 80, Node 12
- Operating system and version (desktop or mobile): macOS 10.15.3

## Reproducible Demo

(Paste the link to an example repo, including a `siteConfig.js`, and exact instructions to reproduce the issue.)

**Comment by yangshun** [comment]
Oops our blog-only instructions are outdated. It's updated for docs-only - https://v2.docusaurus.io/docs/next/configuration/#docs-only-mode where the `routeBasePath` should be `''`.

But I think we can try to dedupe the slashes indeed. Thanks for the PR 😄
