### ISSUE TITLE
feat(v2): add edit link to blog posts

### ISSUE THREAD

**Issue by yangshun** [facebook/docusaurus#2501]
## 🚀 Feature

Just like we have the "Edit on GitHub" link for docs, we want the same for blog posts.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## Motivation

More convenient way to edit blog posts.

**Comment by yangshun** [comment]
@fanny this issue might help you gain familiarity with the Docusaurus v2 plugins 😄

**Comment by fanny** [comment]
> @fanny this issue might help you gain familiarity with the Docusaurus v2 plugins 😄

For sure, I'll take. Can you assign for me?
