### ISSUE TITLE
feat(v2): home page for docs

### ISSUE THREAD

**Issue by yangshun** [facebook/docusaurus#2507]
## 🚀 Feature

> When I navigate to https://v2.docusaurus.io/docs, I see empty page, not even a sidebar on the left. It would be great if we have a way to define content for this page e.g. docs/index.md

Refer to https://v2.docusaurus.io/feedback/p/home-page-for-docs

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## Pitch

This can be specified via an option on the docs plugin.

**Comment by mohamedsgap** [comment]
I think we should make a list with the latest 5 versions of docs, so it will be easy to navigate between them, and also write an introduction about the whole doc, and some feature of the last shipped version of the doc too

**Comment by yangshun** [comment]
Not every docs have versioning. People can already built it themselves like how we do it on https://v2.docusaurus.io/versions

**Comment by mohamedsgap** [comment]
oh okay, just let me know what we need to render on this page, and I gonna take this issue and submit the PR asap @yangshun

**Comment by smyrick** [comment]
Maybe instead it should just redirect to the "real" home page https://v2.docusaurus.io/docs/introduction

**Comment by vinibalbino** [comment]
Hello everybody, what do you guys think about creating a custom page with the currents docs that have in the website instead a dropdown button?

**Comment by vinibalbino** [comment]
![Layout](https://user-images.githubusercontent.com/37583954/79644252-0f40f880-817e-11ea-8c24-f4b475a78f79.PNG)

I created this simple design thinking of being the home page for the docs page. for the user to select the version he wants to use. could it be a solution?
