### ISSUE TITLE
Search not working on docusaurus v2 website

### ISSUE THREAD

**Issue by ianschmitz** [facebook/docusaurus#2511]
## 📚 Documentation

Wanted to give you the heads up that the search doesn't appear to be working any more on https://v2.docusaurus.io/

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

**Comment by yangshun** [comment]
Thanks for reporting! It was not working indeed. I triggered a local rebuild and it's working fine again o.o

cc @s-pace

**Comment by lex111** [comment]
I think crawler Algolia needs some time to index new docs. Therefore, the docs will not be available for search after immediately the new release.
