### ISSUE TITLE
404 not found :the sidebar-item page not found

### ISSUE THREAD

**Issue by netroby** [facebook/docusaurus#2514]
https://v2.docusaurus.io/docs/sidebar.md#sidebar-item

**Comment by lex111** [comment]
This page is now available at the new link -> https://v2.docusaurus.io/docs/docs#sidebar

**Comment by netroby** [comment]
![Snipaste_2020-04-03_16-05-49](https://user-images.githubusercontent.com/278153/78338278-0f10fc80-75c5-11ea-83d7-d1df91e16679.png)
This link broken
