### ISSUE TITLE
navbar links opening in new tab

### ISSUE THREAD

**Issue by awalias** [facebook/docusaurus#2515]
### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

yes

## To Reproduce

1. go to https://supabase.io/docs/about and click any of the links under Docs > 
2. note that the same urls in the sidebar open in the same tab
3. source is available [here](https://github.com/supabase/supabase/tree/master/web)

## Expected behavior

Link would open in the same tab

## Actual Behavior

Link opens in new tab

## Your Environment

- Docusaurus version used: 2.0.0-alpha.50
- Environment name and version (Firefox latest):
- Operating system and version (Mac OSX):

## Reproducible Demo

https://supabase.io/docs/about
https://github.com/supabase/supabase/tree/master/web

We love this project ❤️ thanks for all the hard work

**Comment by lex111** [comment]
@awalias please use `to` field instead of `href` for internal links. Then the link will open in the current tab.

https://github.com/supabase/supabase/blob/master/web/docusaurus.config.js#L49

**Comment by sedghi** [comment]
@lex111 is it possible to open an external link in the current tab without opening a new one?

**Comment by slorber** [comment]
@sedghi you can provide a target to navbar links

```js
{
          href: 'https://facebook.com',
          label: 'FB',
          target: '_self',
          position: 'left',
        },
```

**Comment by sedghi** [comment]
@slorber thanks again for your help
