### ISSUE TITLE
v2: Sitemaps are not always generated

### ISSUE THREAD

**Issue by SamChou19815** [facebook/docusaurus#2516]
## 🐛 Bug Report

`sitemap.xml` is not always generated. It might be caused by #2443 and #2496 does not fix the issue for sitemap generation.

Here is the code that writes the sitemap file.

https://github.com/facebook/docusaurus/blob/6935b3315e72503ebcac6925e038d195fa6979d1/packages/docusaurus-plugin-sitemap/src/index.ts#L38-L43

Writing the file is async, and the process might already be killed before it was able to write the file. To confirm my hypothesis, I changed `writeFile` to `writeFileSync` and the problem seems to go away with my blog repo.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes.

## To Reproduce

The bug is not reproducible on every repo. I cannot reproduce it on the docusaurus v2 project, but I managed to reliably reproduce it for my blog repo (at least on my machine).

1. Clone https://github.com/SamChou19815/website
1. `yarn`
1. `yarn workspace blog build`
1. Observe `packages/blog/build/sitemap.xml` The file is empty.

## Expected behavior

`sitemap.xml` is reliably generated.

## Actual Behavior

`sitemap.xml` is not reliably generated.

## Your Environment

- Docusaurus version used: v2-alpha.50
- Environment name and version (e.g. Chrome 78.0.3904.108, Node.js 10.17.0): Node 12
- Operating system and version (desktop or mobile): macOS 10.15.4

## Reproducible Demo

(Paste the link to an example repo, including a `siteConfig.js`, and exact instructions to reproduce the issue.)

**Comment by lex111** [comment]
@yangshun so do we use synchronous write to sitemap file?

**Comment by yangshun** [comment]
Let's do that if we aren't already

**Comment by lex111** [comment]
@SamChou19815 you don't want to do it?

сб, 4 апр. 2020 г. в 11:42, Yangshun Tay <notifications@github.com>:

**Comment by SamChou19815** [comment]
My concern is that the implementation detail of terminating the process has been leaked into the userland.

Let's imagine an example: suppose a user creates a plugin that generates a `robots.txt` file that includes all paths of docs but excludes everything else. If the user implements it in the same way we did currently (use `writeFile` with callback), then it will run into the same situation that the generation sometimes works and sometimes not.

I would be down to quickly switch `writeFile` to `writeFileSync`, but I think we need to think deeper about its broader implications.
