### ISSUE TITLE
unable to get local issuer certificate

### ISSUE THREAD

**Issue by AlbertDavid94** [facebook/docusaurus#2517]
## 🐛 Bug Report

I am getting an error saying the following 

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## To Reproduce

(Write your steps here:)

1. Have a virtual machine on a windows stationary behind a corporate firewall
2. Attempt to install docusaurus
3. Fail at it, miserably

## Expected behavior

I thought it would install Docusaurus

## Actual Behavior

The installation process informed me as following:
```
Website folder created!

Installing latest version of Docusaurus in website.

yarn add v1.22.4
warning package.json: No license field
info No lockfile found.
warning No license field
[1/4] Resolving packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/docusaurus: unable to get local issuer certificate".
info If you think this is a bug, please open a bug report with the information provided in "/home/albert/Documents/website/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
Docusaurus installed in website folder!

yarn run v1.22.4
warning package.json: No license field
$ docusaurus-examples
/bin/sh: 1: docusaurus-examples: not found
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

## Your Environment

Virtual machine with Linux Ubuntu
Corporate Firewall

**Comment by lex111** [comment]
This is not a Docusaurus bug, however, this issue seems to be easily resolved.

https://stackoverflow.com/questions/40124008/error-unable-to-get-local-issuer-certificate-while-running-yarn-command
https://github.com/yarnpkg/yarn/issues/841

**Comment by AlbertDavid94** [comment]
How do I update a package.json that isn't there? It is happening upon executing `docusaurus-init`

**Comment by lex111** [comment]
As I understand it, you cannot install packages due to SSL restrictions, so there is no `docusaurus-examples` command.

I therefore provided links where you need to run the command like the one below to install all the required packages:
```
yarn config set "strict-ssl" false
```

Doesn't this fix the issue?

**Comment by AlbertDavid94** [comment]
Again, there is **no** package.json.
