### ISSUE TITLE
Codeblock Copy button styling broken in "classic" template

### ISSUE THREAD

**Issue by Noah-Silvera** [facebook/docusaurus#2523]
## 🐛 Bug Report

The copy button styling for the codeblock in the "classic" template is broken. The "copy" text is  dark against a dark background

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## To Reproduce

1.Initialize a new docusaurus project using the create script and "classic" template
    * https://v2.docusaurus.io/docs/installation#scaffold-project-website
2. Add a code block
3. Hover over the code block

## Expected behavior

The copy button is activated, with the "copy" text clearly visible

![copy-button-working](https://user-images.githubusercontent.com/8933450/78400524-bda84380-75ab-11ea-9d8b-b71cfd7b3766.png)

## Actual Behavior

The copy button text is dark against a dark background, so you cannot see the purpose of the button.

![copy-button-bug](https://user-images.githubusercontent.com/8933450/78400551-cdc02300-75ab-11ea-9967-bdab96e6c159.png)

## Your Environment

Docusaurus 2.0.0-alpha.50
Chrome Version 80.0.3987.149 (Official Build) (64-bit)

## Reproducible Demo

https://github.com/Noah-Silvera/docusaurus-code-block-bug

**Comment by dalexhd** [comment]
I also had the same issue. Currently we will need to wait until next release. https://github.com/facebook/docusaurus/pull/2502#issuecomment-608570006_

**Comment by lex111** [comment]
Sorry about this, as a workaround (temporary) solution, you can [define your own Prism theme for dark mode as done on v2](https://github.com/facebook/docusaurus/blob/master/website/docusaurus.config.js#L69).
