### ISSUE TITLE
[v2] RSS feed generation seems broken

### ISSUE THREAD

**Issue by Celeborn2BeAlive** [facebook/docusaurus#2539]
## 🐛 Bug Report

The rss.xml and atom.xml files are empty after building.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## To Reproduce

1. Create a new docusaurus 2 project with `npx @docusaurus/init@next init exploring_docusaurus2 classic`
2. Add blog entry to docusaurus.config.js as described here https://v2.docusaurus.io/docs/blog#feed
3. Build the website with `npm run build`
4. Check files rss.xml and atom.xml in build/blog/, they are both empty.

## Expected behavior

A rss.xml/atom.xml file in build/blog/ containing the RSS feed of the 3 example blog posts.

## Actual Behavior

RSS files are empty.

## Your Environment

- Docusaurus version used: 2.0.0-alpha.50
- Environment name and version: node v13.11.0
- Operating system and version: Windows 10

## Reproducible Demo

Clone, run `npm install` and `npm run build` on this repository:
https://github.com/Celeborn2BeAlive/exploring_docusaurus2

**Comment by kanoshin** [comment]
When is this going to be released?
