### ISSUE TITLE
Mobile safari nav header vertically misaligned

### ISSUE THREAD

**Issue by chenglou** [facebook/docusaurus#254]
![img_15cf1519af9f-1](https://user-images.githubusercontent.com/1909539/33514920-41eb3220-d710-11e7-9f15-39bc5cad15d7.jpeg)

See the vertical alignment for the word BuckleScript vs the search

**Comment by xyclos** [comment]
I'd like to work on this.

**Comment by richardzcode** [comment]
Just tried with my phone. Looks good now, with icon. Maybe the misalignment was from empty icon

**Comment by JoelMarcey** [comment]
@chenglou - are you still seeing the issue?

**Comment by chenglou** [comment]
I can still see it. Not in chrome inspector, but in safari's inspector (Develop -> Responsive Design Mode)

**Comment by richardzcode** [comment]
Now I see it. It can be reproduced in Chrome as well, but not on phone. Basically screen width need to be pretty small ( < 376px ) to make the icon go away then we can see the misalignment.

The CSS on navigation is kind of complicated. Luckily seems found a good fix.

I was going to make a PR but noticed there are differences between bucklescript.github.io and current example, in HTML and CSS. So no PR needed.

For bucklescript.github.io, just modify `main.css` file, add css for `.wrapper` in mediaquery of max 375px

```
@media (max-width: 375px) {
  .logo {
    display: none;
  }

  .headerTitle {
    font-size: 17px;
  }

  .wrapper {
    padding: 0 10px;
  }
}
```

The padding was '0 20px', just change it to '0 10px'

**Comment by chenglou** [comment]
Thanks for diagnosing this! Ideally the custom.css file in ReasonReact and BuckleScript can completely disappear (we do have site-specific css file, but the custom.css are downstream fixes). So I think a PR to fix this in docusaurus is valuable. It also happens to the docusaurus website itself

**Comment by richardzcode** [comment]
<img width="268" alt="docusaurus" src="https://user-images.githubusercontent.com/1006903/34222564-d885de60-e570-11e7-922f-b92ddd81f62f.png">

Docusaurus site look fine on my Safari, not as misaligned as in BuckleScript

I see BuckleScript and Docusaurus sites had already diverged on HTML and CSS. I assume new websites wouldn't have the problem.

Also, I just realized I was trying to fix the alignment between BuckleScript and Docs, actually not the issue stated here :p

Maybe you can try to get latest docusaurus layout and see if problem still remains.

**Comment by chenglou** [comment]
I've tested without custom styles at all and still saw the misalignment. This is what I see on iOS11:

<img width="375" alt="pasted graphic" src="https://user-images.githubusercontent.com/1909539/34241764-9f5e4986-e5cc-11e7-86f3-0b9692f5aa7f.png">

**Comment by JoelMarcey** [comment]
Since the height is different on Chrome than Safari, I think fixing an absolute value of a CSS property isn't the answer. There is some underlying difference in how Safari is rendering the search box relative to the top vs. Chrome. We need to figure out why that is.

**Comment by haraldur12** [comment]
I am tackling the issue. I mean I am trying. I think it has not been fixed yet I assume.

**Comment by danphamus304** [comment]
https://github.com/facebook/Docusaurus/labels/Starter%20Task

**Comment by JoelMarcey** [comment]
I assume this issue still exists, but would love if someone can confirm it.

**Comment by chenglou** [comment]
Still is for docusaurus.io

**Comment by JoelMarcey** [comment]
cc @html5cat

**Comment by yangshun** [comment]
Some preliminary findings - `li.navSearchWrapper` has a computed height of 30px on iOS devices but 22px on Android devices. Probably due to some inconsistency in flexbox.

**Comment by endiliey** [comment]
Is this still happening ? Don't have an iOS devices :cry:

**Comment by html5cat** [comment]
Yes. There's also a 1 px gap between the nav bars now:
https://photos.app.goo.gl/ouZdT6FvVAvUKjTY6

**Comment by endiliey** [comment]
@ahmadalfy still working on it ? 😉
