### ISSUE TITLE
docs(v2): add team member profile

### ISSUE THREAD

**Issue by yangshun** [facebook/docusaurus#2546]
## 💥 Proposal

This task isn't really involve coding, it is more about familiarizing with markdown and getting to know the people involved in the project (past and present).

- Add member profiles to the "Team" and "Honorary Alumni" section on https://v2.docusaurus.io/docs/next/team. Reach out to the various people and get them to provide a profile. Similar to https://reactjs.org/community/team.html
- Add links of the acknowledgements to their GitHub profiles

Feel free to break up the two tasks into individual PRs.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

**Comment by fanny** [comment]
Great suggestion! I would like to work on this! Also, In the suggested template, there are some phrases, after the photos. Can you guys left your description here?

@lex111 @JoelMarcey  @yangshun

**Comment by yangshun** [comment]
cc @wgao19 as well

**Comment by fanny** [comment]
I was thinking if isn't better create a component to render this, the visual that is applied for each member is equal, we can have a .json with the members info, like, the github, twitter, and a brief description about the person.

**Comment by yangshun** [comment]
Components are ok, but it's also ok to hardcode this. I've made the page use card components similar to the showcase. Closed via c117a6fe7.
