### ISSUE TITLE
Codeblocks breaking layout on iPads (horizontal scrolling)

### ISSUE THREAD

**Issue by Dannyholt** [facebook/docusaurus#2548]
## 🐛 Bug Report

Code blocks appear to cause horizontal scrolling on landscape iPads (not tried other tablets), but this also appears on Chromes emulator.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yep

## To Reproduce

1. Visit any doc which have code blocks e.g. [Markdown Features](https://v2.docusaurus.io/docs/markdown-features) on iPad (landscape).

2. You'll see the layout has horizontal scrolling.

## Expected behavior

No horizontal scrolling.

## Actual Behavior

Horizontal scrolling on docs with code blocks.

https://share.getcloudapp.com/JruW0n51

https://share.getcloudapp.com/8LuJX9lj

If the code block(s) are removed there is no issue.

## Your Environment

- Docusaurus version used: ^2.0.0-alpha.50
- Operating system and version (desktop or mobile): Mobile

## Reproducible Demo

Visit any doc with code blocks on landscape iPad - https://v2.docusaurus.io/docs/introduction

**Comment by lex111** [comment]
@Dannyholt I can't reproduce it, which iPad do you use?
It seems that this bug has already been fixed, can you confirm this on your side?

**Comment by Dannyholt** [comment]
@lex111 

I've just checked again, cleared browser history etc... and I'm still seeing the issue. I'm using an iPad Pro (2018) and is happening in all browsers (Chrome, Safari and FF), but only in Landscape.

I also had a colleague check on his iPad Mini and he gets the same horizontal scrolling.

**Comment by lex111** [comment]
@Dannyholt thanks for the confirmation, try to fix it.
