### ISSUE TITLE
[v2] document the programmatic navigation API

### ISSUE THREAD

**Issue by francoischalifour** [facebook/docusaurus#2562]
## 🚀 Feature

A programmatic way to navigate through pages.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes.

## Motivation

Docusaurus v2 exposes a [`Link` component](https://v2.docusaurus.io/docs/docusaurus-core/#link) but doesn't seem to support a **programmatic way to navigate through pages**. This is unfortunate when creating Docusaurus themes.

I'm working on a brand new version of Docsearch for our Docusaurus integration, but we cannot leverage the Docusaurus navigation experience via keyboard without refreshes, which unnecessarily **slows down the experience**. These refreshes also means that **we cannot leverage the underlying search client cache** that caches the queries, to speed up the experience.

![DocSearch preview](https://user-images.githubusercontent.com/6137112/78797967-b5d80d00-79b8-11ea-86cd-3930eb63805d.png)

## Pitch

An API similar to [Gatsby's `navigate` API](https://www.gatsbyjs.org/docs/gatsby-link/#how-to-use-the-navigate-helper-function) would be perfect to leverage the Link API from keyboard navigation.

**Comment by yangshun** [comment]
We do something similar for our Algolia theme component - https://github.com/facebook/docusaurus/blob/master/packages/docusaurus-theme-search-algolia/src/theme/SearchBar/index.js#L47

We use React Router as the underlying router.

**Comment by francoischalifour** [comment]
Yep that's perfect, I missed that one for some reason—thank you!

(It'll be a nice addition to the documentation)

**Comment by hacktivist123** [comment]
What help do you need with this @yangshun, can you explain better?

**Comment by rjpsingh** [comment]
I would love to help but need some assistance.

**Comment by rjpsingh** [comment]
I would love to help but need some guidance.

**Comment by yangshun** [comment]
Basically we just want to add some docs to https://v2.docusaurus.io/docs/docusaurus-core to tell people they can import `'@docusaurus/router'` which is a re-export of React Router.

**Comment by ackvf** [comment]
So just plain old `window.location.href`? Is that how `<Link to=""/>` also works internally?
