### ISSUE TITLE
Ability to set dark mode as default

### ISSUE THREAD

**Issue by hammadj** [facebook/docusaurus#2565]
## 🚀 Feature

I would like to set the default theme of my Docusaurus website to be in dark mode instead of light mode

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## Motivation

The branding for my project is more dark, so I would like the website to default to dark mode to fit the brand

## Pitch

To give developers the choice for what the website looks like on first visit.

**Comment by fanny** [comment]
Good proposal. Maybe we can have a opt-in config in the `docusaurus.config.js` file to activate and deactivate this feature.
