### ISSUE TITLE
Allow marking a documentation page as the landing page

### ISSUE THREAD

**Issue by jcomack** [facebook/docusaurus#2567]
## 🚀 Feature

Allow maintainers to configure a documentation page as their landing page.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## Motivation

Currently, Docusaurus allows users to setup in a 'docs only' mode, which requires setting your `routeBasePath` to an empty string and redirecting visitors by altering the `/src/pages/index.js` file so it points to your desired destination.

However, this means you're (needlessly) redirecting a visitor to a different URL and thus are leaving the original 'landing page' that you'd expect to see when visiting `https://myawesomedocs.com/`, for example. Manually recreating the layout of your documentation pages in the `index.js` file is also an option, but seems cumbersome.

## Pitch

Allowing maintainers to mark a particular documentation page as their landing page, would get rid of having to change the settings/files I mentioned before and make it easier for people to get a 'docs only' site up and running. Additionally, I believe it could also benefit in terms of SEO, as you aren't redirecting people "for no reason".

**Comment by yangshun** [comment]
We could add an option to the `@docusaurus/plugin-content-docs` to specify the root route to map to another doc route.
