### ISSUE TITLE
bug(v2): href links in Footer append a leading slash to mailto: links

### ISSUE THREAD

**Issue by xgp** [facebook/docusaurus#2568]
## 🐛 Bug Report

Using the preset-classic theme, when you add a link to the `footer` element of the `themeConfig` using an `href`, it automatically appends a leading slash if the content of the `href` doesn't start with an `http`. This breaks `mailto:` links.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes.

## To Reproduce

1. Follow installation instructions to install docusaurus v2 with the classic theme. E.g. `npx @docusaurus/init@next init my-website classic`
1. Edit the generated `docusaurus.config.js` to include a `mailto:` link in the `footer` element of the `themeConfig`. E.g.
```
module.exports = {
  ...
  themeConfig: {
    footer: {
      style: 'dark',
      links: [
        {
          title: 'Demo',
          items: [
	    {
	      label: 'foo@bar.com',
	      href: 'mailto:foo@bar.com'
	    }
          ],
        },
      ],
      copyright: `Copyright © ${new Date().getFullYear()} Bar, Inc.`,
    },
```
1. Run `yarn start` and click on the `foo@bar.com` link in the footer

## Expected behavior

When clicking the `foo@bar.com` link, I expected it to open a mail app.

## Actual Behavior

It actually tries to open `http://<root_url>/mailto:foo@bar.com`.

## Your Environment

- Docusaurus version used: 2.0.0-alpha.50
- Environment name and version:
  - Chrome version 80.0.3987.163 (Official Build) (64-bit)
  - node v13.12.0
- Operating system and version (desktop or mobile):
  - MacOS Catalina 10.15.4

**Comment by yangshun** [comment]
Indeed, we failed to account for such a use case and assumed all href values are browser URLs

**Comment by xgp** [comment]
Thanks. Should I try to fix it and submit a PR? Do you think the correct entry point is to update `@docusaurus/Link` to take a new prop (e.g. mailto)?
