### ISSUE TITLE
feat(v2): allow `activeBasePath` to be a Regular Expression

### ISSUE THREAD

**Issue by nebrelbug** [facebook/docusaurus#2574]
## 🚀 Feature

Currently,`activeBasePath` can only be a string. Allowing it to be a Regular Expression would solve use cases

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## Motivation

On https://eta.js.org, I have several "sections" of documentation pages. "Docs" contains API and syntax docs, "About" contains information about Eta, and "Learn" has tutorials and resources.

"Docs" should be highlighted if the path starts with `/docs/get-started`, `/docs/syntax`, or `docs/api`. Currently my sidebars are configured so they all appear within the correct sidebar, but it's not possible to get it to highlight correctly (I can't set `activeBasePath` to `docs/`, because then it highlights "About" and "Learn" as well).

## Pitch

Allow `activeBasePath` to be a RegExp that would be tested against the current URL path.

I'd love to open a PR for this.

**Comment by yangshun** [comment]
Sounds reasonable. Let's support both `String` and `RegExp` types.

**Comment by nebrelbug** [comment]
@yangshun I'm working on this right now, I'll submit a PR sometime today :)

**Comment by yangshun** [comment]
Thank you :)

**Comment by nebrelbug** [comment]
See #2683! I just need to do a little more testing, then I'll change it from a draft PR to a ready-to-merge PR.

**Comment by lex111** [comment]
Implemented in #2690.
