### ISSUE TITLE
Link to resources is not correct

### ISSUE THREAD

**Issue by ArielGueta** [facebook/docusaurus#2575]
I'm using `v2.0.0-alpha.50`, and when I run the `build` command I get the wrong path for the resources inside the `build/index.html` file, for example:

```html
<script src="/projectName/styles.69478405.js"></script>

<script src="/projectName/runtime~main.eeb130fd.js"></script>
```

Where it should be:

```html
<script src="/styles.69478405.js"></script>

<script src="/runtime~main.eeb130fd.js"></script>
```

I can't find any option in the docs to change this.

**Comment by lex111** [comment]
You probably specified custom `baseUrl`, we need your website config so that we can help you.
https://v2.docusaurus.io/docs/docusaurus.config.js#baseurl

**Comment by ArielGueta** [comment]
```json
{
  baseUrl         : '/',
  url: '',
  favicon         : 'img/favicon.ico',
  organizationName: 'myorg',
  projectName     : 'project',
}
```

**Comment by lex111** [comment]
We need a full real config or best of all the repository in which it is possible to reproduce this issue.

**Comment by ArielGueta** [comment]
Sorry, a stupid mistake from my end. Thanks for the quick support, and this awesome tool!
