### ISSUE TITLE
Changing the plugin context values

### ISSUE THREAD

**Issue by ghominejad** [facebook/docusaurus#2581]
I have tried to change the context values but it doesn't seem to be possible inside the plugin :
```
module.exports = function (context, options) {
    context.siteConfig.presets....docs.sidebarPath = ...;
}
```

**Comment by lex111** [comment]
What do you want to achieve? Please fill out the issue strictly according to the opened [template](https://github.com/facebook/docusaurus/issues/new?labels=feature%2C+needs+triage&template=feature.md), only this way we will help you.
