### ISSUE TITLE
Correct approach to load external libraries and undertake operations upstream to Docusaurus and ensure the correct order of loading files

### ISSUE THREAD

**Issue by chengtie** [facebook/docusaurus#2594]
Hello,

I guess it happens often that we may need to load external libraries and undertake some operations in the very beginning of our Docusaurus website, I'm wondering what's the correct and common way to do so. The follows is our try, which did not work quite well.

------------------------------

I'm taking over [a website](https://www.10studio.tech/docs/verificatorResearch/) by [V2 Docusaurus](https://v2.docusaurus.io/). 

One particularity of our website is that we need to load [office.js](https://appsforoffice.microsoft.com/lib/1/hosted/office.js) and [css-vars-ponyfill.min.js](https://unpkg.com/css-vars-ponyfill@2/dist/css-vars-ponyfill.min.js), and do some operations in the very beginning. So the previous developer decided to use the following approach.

In every `.mdx.md` page, he wrapped the content by a component `MainWrapper`:

```
    <MainWrapper>
        ... ...
        Real content
        ... ...
    </MainWrapper>
```

`MainWrapper/index.js` is defined as follows

```
    import React from 'react';
    import Head from '@docusaurus/Head';
    import CssvarsWrapper from '../CssvarsWrapper';
    
    function MainWrapper(props) {
        return (<>
            <Head>
                <script 
                    src="/lib/patches.js" 
                    onload="(function(){console.log('patches.js fully loaded 1')}).call(this)" >
                </script>
            </Head>
            <CssvarsWrapper patchOnly={true}></CssvarsWrapper>
            {props.children}
        </>)
    }

    export default MainWrapper;
```

`CssvarsWrapper/index.js` is defined as follows

```
    import React from 'react';
    import Head from '@docusaurus/Head';
    
    function CssvarsWrapper(props) {
        console.log("CssvarsWrapper > index.js > CssvarsWrapper(props) 1")
        return (<>
            <Head>
                <script 
                    src="/lib/patches.js"
                    onload="(function(){console.log('patches fully loaded 2')}).call(this)">
                </script>
                {console.log("CssvarsWrapper > index.js > CssvarsWrapper(props) 2")}
                <script
                    src="https://unpkg.com/css-vars-ponyfill@2/dist/css-vars-ponyfill.min.js"
                    onload="(function(){
                        console.log('css-vars-ponyfill.min.js fully loaded'); 
                        onCssVarsPonyfillLoad()}).call(this) ">
                </script>
            </Head>
            {props.children}
        </>)
    }
    
    export default CssvarsWrapper;
```

`lib/Patches.js` contains real operations:

```
    console.log("in patches")
    ... ...
    
    function onCssVarsPonyfillLoad() {
        console.log("patches.js > onCssVarsPonyfillLoad()")
        cssVars({
            onlyLegacy: false,
            onComplete: function (cssText, styleElms, cssVariables, benchmark) {
                // reCssVarsPonyfillLoad(cssVariables);
            }
        });
    }
```

However, my test showed that this implementation cannot always respect a correct order of loading of files. For example, as the following screenshot shows, `css-vars-ponyfill.min.js fully loaded` was before `patches.js fully loaded 2`, as a consequence `onCssVarsPonyfillLoad` was not ready when it was called.

Actually, we should ensure that **`patches.js` is always loaded before `css-vars-ponyfill.min.js`**. Does anyone know how to ensure that?

Additionally, is this approach (i.e., wrapping a component around content of every page to do some operations upstream) correct?

[![enter image description here][1]][1]

  [1]: https://i.stack.imgur.com/PBM3x.png

**Comment by lex111** [comment]
Sorry for late response.

I do not think this applies to Docusaurus directly. If this approach works for you, then you to go this way. It is up to you, we do not have a clear opinion on this.
