### ISSUE TITLE
improvement(v2): customizable code snippet copy button

### ISSUE THREAD

**Issue by kripod** [facebook/docusaurus#2599]
## 🚀 Feature

Currently, the background color of the code snippet copy button is [not customizable](https://github.com/facebook/docusaurus/blob/ea8c916528d448b2d0684597158a9506fb40fa98/packages/docusaurus-theme-classic/src/theme/CodeBlock/styles.module.css#L33).

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes.

## Motivation

Some prism-react-renderer themes [use a darker background](https://github.com/FormidableLabs/prism-react-renderer/blob/078596ea53e0852dfe120a37aea30b33ae480603/src/themes/nightOwl.js#L10), on which the copy button is barely visible.

**Comment by kripod** [comment]
It looks like that #2526 has fixed this problem. However, it'd be great to make other aspects customizable (e.g. uppercased letters for "COPY").

**Comment by lex111** [comment]
> (e.g. uppercased letters for "COPY").

For these purposes, you need to swizzle the CodeBlock component, these are very special cases to make them customizable.
