### ISSUE TITLE
Bug (v2): Meta description outputting MDX import statements

### ISSUE THREAD

**Issue by jcomack** [facebook/docusaurus#2601]
## 🐛 Bug Report

MDX import statements which are required to be placed on the first line of a doc (i.e. after the doc header section), are being used in meta descriptions.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## To Reproduce

1. Create a new doc item.
1. Write the necessary header section.
1. Directly after the header section, add an import statement such as `import MyComponent from '../src/components/MyComponent';`.
1. Add some text below the import statement.
1. Visit the new doc item in your browser.
1. View the page source and see that the meta descriptions all use the import statement and not the 'actual' text you wrote in your doc file.

## Expected behavior

I expected to see the first line of my text in de meta descriptions.

## Actual Behavior

The import statement is being used in the meta descriptions.

## Your Environment

- Docusaurus version used: v2.0.0-alpha.50
- Environment name and version (e.g. Chrome 78.0.3904.108, Node.js 10.17.0): Firefox 74.0.1, Node.js v10.19.0
- Operating system and version (desktop or mobile): MacOSX High Sierra 10.13.6 (desktop)

## Reproducible Demo

(Paste the link to an example repo, including a `siteConfig.js`, and exact instructions to reproduce the issue.)

https://github.com/Yoast/developer-site combined with https://github.com/yoast/developer-docs/

**Comment by lex111** [comment]
I tried to fix it in [this PR](https://github.com/facebook/docusaurus/pull/2380), but @yangshun did not approve of it. Unfortunately, in the current architecture, it is difficult to come up with something else.
@yangshun so can we give this PR another chance?

**Comment by yangshun** [comment]
The fix might also fix https://github.com/facebook/docusaurus/issues/2607. A few suggestions I have:

- Compile the Markdown/MDX into just text form before extracting the description. This will incur a performance cost but would eliminate the issue entirely
- Add a description front matter field to override the automatic extraction of the description. This is troublesome for users but might be useful to have either way
- Last resort - do the naive removal as proposed by @lex111 in #2380

**Comment by yangshun** [comment]
@lex111 let's go with your previous PR. It's better than having a buggy result now. Maybe we can also filter out require statements to make it more robust.
