### ISSUE TITLE
Don't include the 404 route in XML sitemaps

### ISSUE THREAD

**Issue by jdevalk** [facebook/docusaurus#2605]
## 🐛 Bug Report

When testing the XML sitemaps I found that the first URL in it on our site was the 404 route:

```xml
<url>
    <loc>https://developer.yoast.com/404.html</loc>
    <changefreq>weekly</changefreq>
    <priority>0.5</priority>
</url>
```

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## To Reproduce

(Write your steps here:)

1. I guess: open any DocuSaurus v2 XML sitemap.

## Expected behavior

The XML sitemap should only contain URLs that should return a `200` status code.

## Actual Behavior

As shown above, the `404.html` file was included, which should not be indexed.

## Your Environment

- Docusaurus version used: v2

**Comment by yangshun** [comment]
Seems legit. PRs welcome!

**Comment by RDIL** [comment]
I opened a PR to fix this issue.

**Comment by jdevalk** [comment]
Awesome. I've asked @jcomack to test it :)

**Comment by jcomack** [comment]
I checked the instance that was spun up for the PR and that looked good to me :)
