### ISSUE TITLE
Meta description not formatting/removing markdown

### ISSUE THREAD

**Issue by watzon** [facebook/docusaurus#2607]
## 🐛 Bug Report

I don't know if this is 100% a bug or not, but the meta description created for blog posts includes unformatted markdown.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## To Reproduce

Write a blog post where markdown is used in the section that will become the meta description.

## Expected behavior

I'd expect markdown to be stripped out.

## Actual Behavior

Markdown does not get stripped out.

## Your Environment

- Docusaurus version used: 2.0.0-alpha.50
- Environment name and version (e.g. Chrome 78.0.3904.108, Node.js 10.17.0): Firefox 74.0.1
- Operating system and version (desktop or mobile): Arch Linux (desktop)

## Reproducible Demo

https://github.com/protoncr/tourmaline

You can also open https://tourmaline.dev/blog/another-day-another-release and check the meta description tag using the inspector. You'll see that the link is formatted as markdown still.

**Comment by yangshun** [comment]
Potentially could use the same solutions as #2601
