### ISSUE TITLE
Standard way to embed a video that occupies 100% of the width

### ISSUE THREAD

**Issue by chengtie** [facebook/docusaurus#2610]
I would like to know if there is a standard way to embed in a page of Docusaurus a video that occupies 100% of the width.

----------------- 

I'm building [a website](https://www.10studio.tech/docs/prettyFormula/) by [V2 Docusaurus](https://v2.docusaurus.io/).

I want to embed a youtube video into the page. I want the width of the frame to be `100%` of the page. I tried a lot of solutions, but they don't seem to work with Docusaurus. At the moment, i'm using the following code:

```
<iframe width="675" height="380" src="https://www.youtube.com/embed/_AQXQDjw7Y8" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen>
</iframe>
```

It works well in desktop, but i realize that it does not work well in phone:

[![enter image description here][1]][1]

Does anyone have any idea?

  [1]: https://i.stack.imgur.com/ctKtu.png

**Comment by yangshun** [comment]
> `<iframe width="675"`

You're hardcoding a width value which is larger than on most mobile, so that's expected. See how the [Flux docs](https://facebook.github.io/flux/docs/in-depth-overview) does it in https://github.com/facebook/flux/blob/master/docs/In-Depth-Overview.md.
