### ISSUE TITLE
@docusaurus/router

### ISSUE THREAD

**Issue by nainardev** [facebook/docusaurus#2615]
## 📚 Documentation

https://v2.docusaurus.io/docs/docusaurus-core/#redirect

```jsx
import React from 'react';
import {Redirect} from '@docusaurus/router';

function Home() {
  return <Redirect to="/docs/test" />;
}
```

But no such package exists

**Comment by benmccann** [comment]
The redirect works for me

The file `@docusaurus/core/lib/client/exports/router.js` just re-exports `react-router-dom`. I'm not sure why this exists rather than just using `react-router-dom` directly though

**Comment by yangshun** [comment]
Please reopen using the bug template and provide repro instructions? What package manager and version are you using? Certain `@docusaurus/...` imports don't exist and are added as webpack aliases. So I'm not sure why it's not working for you.

> The file @docusaurus/core/lib/client/exports/router.js just re-exports react-router-dom. I'm not sure why this exists rather than just using react-router-dom directly though

The router is an implementation detail and we don't want to expose that to the users.
