### ISSUE TITLE
v2: doc page description is not inferred properly when the first line is an import statement

### ISSUE THREAD

**Issue by kripod** [facebook/docusaurus#2618]
## 🐛 Bug Report

While transcluding a markdown file from an MDX file like below:

```mdx
---
title: Code of Conduct
---

import CodeOfConduct from '../../../CODE_OF_CONDUCT.md';

<CodeOfConduct />
```

The following metadata gets generated into `.docusaurus/docusaurus-plugin-content-docs/site-docs-code-of-conduct-mdx-59f.json`:

```jsonc
{
  "id": "code-of-conduct",
  "title": "Code of Conduct",
  "description": "import CodeOfConduct from '../../../CODE_OF_CONDUCT.md';",
  "source": "@site/docs\\code-of-conduct.mdx",
  // ...
}
```

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes.

## To Reproduce

1. ```npx @docusaurus/init@next init my-website classic```

2. Create `my-website/docs/test.mdx`:

   ```mdx
   ---
   title: Code of Conduct
   ---

   import CodeOfConduct from '../CODE_OF_CONDUCT.md';

   <CodeOfConduct />
   ```

3. Create `my-website/CODE_OF_CONDUCT.md`:

   ```md
   # Code of Conduct

   Lorem ipsum...
   ```

## Expected behavior

The `description` should become something like `Code of Conduct: Lorem ipsum...`.

## Actual Behavior

`my-website/CODE_OF_CONDUCT.md` cannot even be imported, as `docusaurus-plugin-content-docs` [only includes files placed at `my-website/docs/*.md(x)`](https://github.com/facebook/docusaurus/blob/ea5a50c4de616144786e7a636349c8e3b6cce39e/packages/docusaurus-plugin-content-docs/src/index.ts#L412).

## Your Environment

- Docusaurus version used: 2.0.0-alpha.50

**Comment by yangshun** [comment]
Tracking in #2601

**Comment by kripod** [comment]
Thank you for the response, and sorry for duplicating by mistake.

**Comment by yangshun** [comment]
No worries, that's the responsibility of the maintainer. If you don't mind you could add more details to #2601 which you think could be helpful.
