### ISSUE TITLE
theme-classic(v2): navbar shows with no links

### ISSUE THREAD

**Issue by benmccann** [facebook/docusaurus#2623]
## 🚀 Feature

My `themeConfig.navbar` config has no `links`. This looks fine on desktop. However, on mobile it shows a hamburger menu, which when pressed slides out an empty side panel. I'd like for this hamburger menu not to appear since there's no value to having the empty panel

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## Motivation

I don't have anything compelling to put in `links`. Also, even when I did have something there, I got user feedback that it was confusing to have two hamburger menus on mobile (i.e. the navbar and the sidebar).

## Pitch

There are multiple ways this could be implemented:
* Detect that `links` is empty and render different HTML as a result
* Add a new section which allows users to specify a `title` and `logo` and then make the `navbar` section optional
* I found https://github.com/facebook/docusaurus/issues/2220 which would make this unnecessary and actually sounds like an even better solution to me. However, without being very familiar with the theme code, that solution sounds possibly much harder to implement. I'm filing this issue as a potentially easier improvement. I also think that the two are not mutually independent. Even if the other solution is implemented it probably still makes sense not to show an empty hamburger menu if either the sidebar or table of contents is empty

**Comment by yangshun** [comment]
Good catch, PRs welcome!

**Comment by benmccann** [comment]
I probably don't know enough React or have enough time to fix this myself, but thanks for triaging!

**Comment by yangshun** [comment]
No worries, not asking you to fix it yourself, it's up for grabs by the community :)
