### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by hramos** [facebook/Docusaurus#263]
Better late than never, lets add some tests to catch regressions.

- [x] Test `lib/build-files.js`
- [ ] Test `lib/version.js` 
- [ ] Test `lib/write-translations.js` 
- [ ] Test `lib/start-server.js` 
- [ ] Test `lib/publish-gh-pages.js` 
- [ ] Test `lib/generate-feed.js` 
- [ ] Test `lib/copy-examples.js`

**Comment by JoelMarcey** [comment]
First test added by #259

**Comment by wszgxa** [comment]
I want to take on `lib/version.js`
