### ISSUE TITLE
Code Tab Examples

### ISSUE THREAD

**Issue by fishcharlie** [facebook/docusaurus#2632]
## 📚 Documentation

On [this page](https://v2.docusaurus.io/docs/markdown-features#tabs) there is no information about code based tab examples. There should be some information about how to use tabs with different code snippets. Especially for different languages this would be really helpful.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

**Comment by fishcharlie** [comment]
Oh sorry. Found it [here](https://v2.docusaurus.io/docs/markdown-features#multi-language-support-code-blocks). Was expecting it to be under the `Tabs` header. Not sure if that is just me or if it should be moved.

**Comment by yangshun** [comment]
There's nothing special about code tabs because it's just an example of how to use the Tabs for code. The tabs section is use-case agnostic and can be left as such.
