### ISSUE TITLE
Feature(V2): Support assets directory for docs- and blog-specific assets

### ISSUE THREAD

**Issue by jcomack** [facebook/docusaurus#2633]
## 🚀 Feature

Support assets directory for blog- and docs-specific assets (i.e. `docs/assets`), such as images, video and other media.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## Motivation

The reason for this feature request, is that this seems to be [supported in V1](https://docusaurus.io/docs/en/doc-markdown#linking-to-images-and-other-assets), but not in V2.

Currently in V2 you only have the `static` directory that is used for everything.

## Pitch

This feature would be of great use for setups where there is a very distinct separation between assets that are used site-wide and assets that are tailored to only be used in the docs and blog.
A good use case would be a situation where you have your 'core' Docusaurus code split from the docs, allowing for a kind of 'admin vs authors' setup where authors can update their docs, including images. Currently, an author would also have to contact the 'admin' and request them to upload the image, which isn't necessarily a productive way of writing docs.

**Comment by slorber** [comment]
Hi,

We have added the ability to colocate images to their markdown usage file here, supporting relative image paths:
https://v2.docusaurus.io/docs/markdown-features#images

With versioning, it also allows to have one different asset per version, which enable you to version assets alongside the docs

Please open another issue if this is not good enough, but to me it is different yet more powerful than v1 system
