### ISSUE TITLE
Python syntax highlighting in a code block is inconsistent

### ISSUE THREAD

**Issue by omry** [facebook/docusaurus#2655]
## 🐛 Bug Report

Python syntax highlighting in a code block is inconsistent

## To Reproduce
Add this block:
```python
@dataclass
class MySQLConfig:
    host: str = "localhost"
    port: int = 3306

@dataclass
class Config:
    db: MySQLConfig = MySQLConfig()
    verbose: bool = True

cfg_store = ConfigStore.instance()
cfg_store.store(name="config", node=MyConfig)

@hydra.main(config_name="config")
def my_app(cfg: MyConfig) -> None:
    # Python knows that the type of cfg.db is MySQLConfig without any additional hints
    print(f"Host: {cfg.db.host}, port: {cfg.db.port}")

if __name__ == "__main__":
    my_app()
```

## Expected behavior
Syntax highlighting is applied consistently.

## Actual Behavior
See screen shot, only the first @dataclass annotation is highlighted.

![image](https://user-images.githubusercontent.com/376455/80247812-8d404c00-8623-11ea-8ca2-344ad8ef819e.png)

## Your Environment
Ubuntu 18.

- Docusaurus version used:
[package.json](http://paste.ubuntu.com/p/pBxTFd822P/)

**Comment by lex111** [comment]
This is probably because `prism-react-renderer` uses an older version of `prismjs`, in which decorator syntax highlighting has not yet been fixed.

https://github.com/PrismJS/prism/pull/2018/files#diff-e99f677a9aaad5549db82df4b410cb1fR47
https://github.com/PrismJS/prism/blob/master/CHANGELOG.md#1180-2020-01-04

**Comment by omry** [comment]
cool, what is the path to get this dependency upgraded?

**Comment by lex111** [comment]
If I understand correctly, then we need to bump to latest version of prismjs in prism-react-renderer, however that dependency seems to be abandoned (its author @kitten does not accept PRs very well :disappointed:).

**Comment by omry** [comment]
Did this break again?
I tried to upgrade prism-react-renderer with `yarn upgrade prism-react-renderer` but I am still on 1.10.0 for some reason.

```
$ rg prism 
yarn.lock
1143:    prism-react-renderer "^1.1.0"
1144:    prismjs "^1.20.0"
7386:prism-react-renderer@^1.1.0:
7388:  resolved "https://registry.yarnpkg.com/prism-react-renderer/-/prism-react-renderer-1.1.1.tgz#1c1be61b1eb9446a146ca7a50b7bcf36f2a70a44"
7391:prismjs@^1.20.0:
7393:  resolved "https://registry.yarnpkg.com/prismjs/-/prismjs-1.20.0.tgz#9b685fc480a3514ee7198eac6a3bf5024319ff03"

```
![image](https://user-images.githubusercontent.com/376455/84582153-40fcc700-ad9d-11ea-84f6-6584cc151a13.png)
