### ISSUE TITLE
How to make Docusaurus support IE?

### ISSUE THREAD

**Issue by chengtie** [facebook/docusaurus#2657]
Previously, my developer succeeded to add `react-app-polyfill` to a version of Docusaurus such that it supports Edge and IE. Here is the modification: https://github.com/BurdenBear/docusaurus/compare/78159f6..f5c6ffd.

I tried to do the same thing to v2.0.0 of Docusaurus: https://github.com/chengtie/docusaurus/compare/1262c68..fcf89d0, but it did not work.

Here is the error is IE:

![Screenshot 2020-04-25 at 11 48 33](https://user-images.githubusercontent.com/774409/80276731-d9a28f00-86ea-11ea-9e2b-4c36b2704324.png)
![Screenshot 2020-04-25 at 11 48 25](https://user-images.githubusercontent.com/774409/80276733-ddceac80-86ea-11ea-877b-828b48051bd0.png)

Does anyone know how to make Docusaurus work with IE? What polyfill may fix the error?

  [1]: https://i.stack.imgur.com/1xHYp.png

* * *

Related issues (closed at the moment to avoid duplication):

- https://github.com/facebook/docusaurus/issues/2230
- https://github.com/facebook/docusaurus/issues/2418

**Comment by lex111** [comment]
I think more polyfills and other dependencies are needed to make D2 work on IE11. In any case, this requires a lot of effort, especially since we do not have a active core developer who uses Windows.

Any help is highly appreciated, but at the moment we cannot help, sorry.

**Comment by chengtie** [comment]
Thanks for your reply.

Adding `react-app-polyfill` did make commit `1262c68` work on IE and Edge, you confirmed that it is expected that this action is largely not enough for the current version?

**Comment by chengtie** [comment]
Otherwise, do you remember since which commit you started to support [scripts:](https://github.com/facebook/docusaurus/blob/master/docs/api-site-config.md#stylesheets-array), maybe I could add polyfills to that version and maybe that could work.

**Comment by lex111** [comment]
I have not tested proposed fix, but we are using CSS features that are not supported in IE11 (you can see the issue #2230 for details).

> Otherwise, do you remember since which commit you started to support scripts:? Maybe I could add polyfills to that version and maybe that could work.

This option has existed for a very long time, but better use the latest version.

**Comment by lex111** [comment]
Since we will definitely not support IE11 in the future, I'm closing this issue.
