### ISSUE TITLE
Add Filter Textbox upon docs left sidebars

### ISSUE THREAD

**Issue by XavierNV** [facebook/docusaurus#2658]
## 🚀 Feature

Add Filter Textbox upon docs sidebars to filter the sidebar navigation and keep only item matching the filter

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## Pitch

It' a kind of basic search box based on items title. Not based on an external service... Maybe not too hard to implement...
Example documentation using it  : 
https://docs.microsoft.com/en-us/dotnet/standard/net-standard
https://markdownmonster.west-wind.com/docs/

Regards
Xavier

**Comment by yangshun** [comment]
While possible, I think it's better to use Algolia search which lets you search the entire site, not just docs headings.
