### ISSUE TITLE
Must use import to load ES Module when creating a new project

### ISSUE THREAD

**Issue by jz222** [facebook/docusaurus#2662]
## 🐛 Bug Report

I tried to create a new project with `npx @docusaurus/init@next init my-website classic` but it failed without creating a folder that includes basic project data.

## Expected behavior

I expected it to create a folder `my-website` with project data as described in the docs.

## Actual Behavior

Got the the following error message:

```
npx: installed 60 in 6.575s
Must use import to load ES Module: /Users/user/.npm/_npx/6114/lib/node_modules/@docusaurus/init/node_modules/is-promise/index.js
require() of ES modules is not supported.
require() of /Users/user/.npm/_npx/6114/lib/node_modules/@docusaurus/init/node_modules/is-promise/index.js from /Users/user/.npm/_npx/6114/lib/node_modules/@docusaurus/init/node_modules/run-async/index.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename /Users/user/.npm/_npx/6114/lib/node_modules/@docusaurus/init/node_modules/is-promise/index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /Users/user/.npm/_npx/6114/lib/node_modules/@docusaurus/init/node_modules/is-promise/package.json.
```

## Your Environment

NodeJS: v12.16.1
NPM: 6.13.4

Thank you.

**Comment by lex111** [comment]
This is related with `is-promise`. https://github.com/then/is-promise/issues/13

**Comment by lex111** [comment]
This is already fixed, I successfully installed the new Docusaurus website on Node.js v12.16.1 https://github.com/then/is-promise/commit/ca22483a69980369c8d7eb6573aa1c157eff727d
