### ISSUE TITLE
Carousel Feature in docusaurus

### ISSUE THREAD

**Issue by sriramgroot** [facebook/docusaurus#2674]
## 🚀 Feature

Carousel or Slider feature to be implemented in docusaurus

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes and I thought of having this feature in docusaurus versions

## Motivation

I we are using the docusaurus for creating a new or changing existing blog webpage

## Pitch

1. We can have the featured blog in the home page and in the required places
2. This feature will help the blog writers focus and it will make the their burden a little bit.

**Comment by fanny** [comment]
Great suggestion! Current, we are working in a new theme based on bootstrap, probably will be easier integrate with it than in the classic theme.

**Comment by yangshun** [comment]
This will unlikely be part of Docusaurus scope. More of our UI library maybe.

**Comment by sriramgroot** [comment]
> This will unlikely be part of Docusaurus scope. More of our UI library maybe.

Hi Yangshun,
Thanks for replying me immediately, May i know if there is any carousel feature that can be imported into the docusaurus app

**Comment by yangshun** [comment]
Closing this as we won't put it in core. You could install your own React component libraries and import them where you need it.

**Comment by zire** [comment]
This feature would be a huge help for many blog writers there, who very often also need to show case their photo galleries.
