### ISSUE TITLE
Integrate prettier into our PR workflow

### ISSUE THREAD

**Issue by ericnakagawa** [facebook/Docusaurus#268]
Let's standardize on a single prettier config so we can... move fast!

**Comment by roryokane** [comment]
It looks like this issue can be closed: [`.prettierrc`](https://github.com/facebook/Docusaurus/blob/deafdbde0416d9884c9c01788f2bda39c6e39608/.prettierrc), [`package.json` scripts using Prettier](https://github.com/facebook/Docusaurus/blob/deafdbde0416d9884c9c01788f2bda39c6e39608/package.json#L17-L23)

**Comment by prescottprue** [comment]
Might also be nice to use something like [husky](https://github.com/typicode/husky) to add a `prepush` hook that runs `npm run prettier`. That way lint can be caught before pushing as opposed to through the CI build failing.

**Comment by JoelMarcey** [comment]
@prescottprue Yes, I think that was part of the creation of this issue too, because you are right, we catch the failures after we push and thus have to patch with an updated fix if there is a failure.
