### ISSUE TITLE
Search on v2.docusaurus.io is currently broken

### ISSUE THREAD

**Issue by nebrelbug** [facebook/docusaurus#2681]
## 🐛 Bug Report

Typing in a query results in "No results found for query"

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yep

## To Reproduce

Go to https://v2.docusaurus.io and search for something

## Expected behavior

Search works

## My Guess

Perhaps Algolia just hasn't indexed the current version?

**Comment by yangshun** [comment]
It's probably something to do with Algolia. We experienced similar issues on our previous release.

**Comment by lex111** [comment]
cc @s-pace

**Comment by s-pace** [comment]
Needed a new fresh crawl for the release. Fixed now

**Comment by yangshun** [comment]
@s-pace will this happen every time we release a new version? What can we do to reduce the downtime here?

**Comment by s-pace** [comment]
The downtime will be less than 24h. You can ping me so that I trigger it. We are working on making a crawl on demand remotely. Stay tune.

**Comment by lex111** [comment]
@s-pace thank you! I think we can close this issue then.

**Comment by lex111** [comment]
@s-pace please re-run your crawler again.
