### ISSUE TITLE
Blog only breaks post links

### ISSUE THREAD

**Issue by afking** [facebook/docusaurus#2685]
## 🐛 Bug Report

Setting `routeBasePath: "",`  as part of the blog preset breaks links to content.
https://v2.docusaurus.io/docs/blog/#blog-only-mode

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

(Write your answer here.)

## To Reproduce

1. Set `routeBasePath: "",`
2. Visit base page
3. Click blog post link redirect to `/blog/<blog-id>`

## Expected behavior

Expect `/blog/<blog-id>` to return the page contents.

## Actual Behavior

Returns blog feed.

## Your Environment

- Docusaurus version used: 2.0.0-alpha.53
- Environment name and version (e.g. Chrome 78.0.3904.108, Node.js 10.17.0): Chrome 81.0.4044.122
- Operating system and version (desktop or mobile): desktop

## Reproducible Demo

I deployed my blog to demo: https://afking.github.io/
Development branch `blog`

**Comment by lex111** [comment]
@afking there was a mistake in the docs, we fixed it now, sorry for misleading! https://github.com/facebook/docusaurus/commit/f8f6478c3652f375604d9ff8dd1c85ef4204475f
