### ISSUE TITLE
Swizzling theme-classic broken on latest release

### ISSUE THREAD

**Issue by davekover** [facebook/docusaurus#2686]
## 🐛 Bug Report

Unable to swizzle theme-classic components on v2.0.0-alpha.53

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes.

## To Reproduce

1. Start fresh and install v2.0.0-alpha.53
    (npx @docusaurus/init@next init my-website classic)
2. Run example swizzle command 
    (yarn run swizzle @docusaurus/theme-classic Footer)

## Expected behavior

After running, swizzled component would appear in project folder.

## Actual Behavior

Command errors out.

![Screen Shot 2020-04-27 at 4 02 51 PM](https://user-images.githubusercontent.com/5530580/80430191-ce925f00-88a2-11ea-8d28-165d9307efd0.jpg)

## Your Environment

- Docusaurus version used: v2.0.0-alpha53
- Environment name and version: yarn v1.22.4, Node.js v13.10.0
- Operating system and version (desktop or mobile): macOS 10.15.1 (19B88)

**Comment by lex111** [comment]
@davekover this issue should be fixed in v2.0.0-alpha.54. Please use that version (or install new fresh website). Sorry for that!

**Comment by davekover** [comment]
Thanks for the quick fix!
