### ISSUE TITLE
Footer background color can't be customized

### ISSUE THREAD

**Issue by jz222** [facebook/docusaurus#2692]
## 🐛 Bug Report

I would like to set the footer background color through the `custom.css` file. I set the variable `--ifm-footer-background-color` to my desired color but it gets not picked up.

I found out, that the footer background color is, in contrast to the other variables, hardcoded. This seems to overwrite the variable I set in `custom.css`.

```
.footer.footer--dark {
    --ifm-footer-background-color: #303846;
    --ifm-footer-color: var(--ifm-footer-link-color);
    --ifm-footer-link-color: var(--ifm-color-secondary);
    --ifm-footer-title-color: var(--ifm-color-white);

    background-color: var(--ifm-footer-background-color);
    color: var(--ifm-footer-color)
}
```

## To Reproduce

I'm using a device with dark mode enabled. However, I would like the docs to only be available in a light colored version. That's why I set `disableDarkMode: true` in the config. Then, I set the `--ifm-footer-background-color` in `custom.css` to my desired color.

## Expected behavior

I would like the footer background color to be set to the color provided in `custom.css`.

## Actual Behavior

The footer background color remains the one provided by the classic theme.

## Your Environment

Chrome 81

**Comment by lex111** [comment]
For the `themeConfig.footer.style` field in your config file, set the value to "light" or completely remove this field, then you can override the background footer.

```css
:root {
  --ifm-footer-background-color: red;
}
```

**Comment by elugens** [comment]
You need to got to the src/css/custom.css and use this code. 

```
html[data-theme='dark'] footer {
  background-color: black;
}
```

try it out it works... You need to prepend `html[data-theme='dark']` or `html[data-theme='light']` in order to target specifice elements, classes, and ids.

**Comment by aatmmr** [comment]
@elugens snippet works, however, if you like to change the main footer only, use

```css
html[data-theme='light'] footer.footer--light {
  background-color: red;
}

html[data-theme='dark'] footer.footer--dark {
  background-color: black;
}
```

Adding `.footer-dark` will prevent any page footer, such as, "Edit this page" to change as well.

**Comment by drwelby** [comment]
Something is amiss here - `--ifm-footer-background-color` is getting defined in `styles.css` on line 2184:

```css
.footer--dark {
    --ifm-footer-background-color: #303846;
```

And doing the standard overrides in `custom.css` doesn't seem to be able to take precedence over this value.

**Comment by erzz** [comment]
@lex111 Can we reopen this please?

See the same issue using classic themes

Other overides are working as expected such as `--ifm-footer-link-hover-color: #ffdb02;` - it is soley the `--ifm-footer-background-color` which can not be overridden

**Comment by robmoffat** [comment]
yep seeing this too

**Comment by alexfornuto** [comment]
Same issue with `--ifm-background-color`. It seems like the ifm values already present in `custom.css` are the only ones that can be changed?

**Comment by pabl-o-ce** [comment]
guys the trick is on the `docusaurus.config.ts`: 

```json
themeConfig: {
  ....
    footer: {
      style: 'dark',
    }
}
```
just remove `style: 'dark'` from there and all good
