### ISSUE TITLE
alpha-54: Site title no longer wraps - search box moves

### ISSUE THREAD

**Issue by TomBrien** [facebook/docusaurus#2699]
## 🐛 Bug Report

In alpha-0.49 and previous (I believe but I'm struggling to get these to build now), longer site titles would wrap at the search in the header bar. This was especially important on mobile browsers where the width is obviously limited. As of alpha-54, the title is not wrapping and search box is being pushed out of the header.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## To Reproduce
1. Install Docusaurus and set up with a multi-word site title (total length more than 12 characters or so)
2. Enable the search plug in
3. Visit site on a mobile browser

## Expected behavior

Words should wrap to ensure proper placement of search box

## Actual Behavior

Title is shown on one line and search is moved
iOS:
![IMG_0993](https://user-images.githubusercontent.com/12411302/80699694-557a4e00-8ad4-11ea-8a63-d88bf07c97d1.PNG)

Pixel 4 (on BrowserStack)
![image](https://user-images.githubusercontent.com/12411302/80700409-9b83e180-8ad5-11ea-9b46-27efeab71389.png)

## Your Environment

- Docusaurus version used: alpha-54
- Environment name and version: Chrome and Safari on iOS, 
- Operating system and version (desktop or mobile): iOS on iPhone XS. Using browser stack I see it on other devices, including android, depending on screen size/resolution

**Comment by yangshun** [comment]
There's no good way around this as the site title can be potentially very long. I think as a lasting solution we could make the search as an icon-only on mobile, and focusing on it will expand and fill the whole bar.

**Comment by TomBrien** [comment]
An icon that expands (on top of title) when tapped would be a really nice solution. Or on mobile move the search into the hamburger menu

**Comment by marcosvega91** [comment]
Hi the only thing to do is to change the media query of the search-bar class.
Now the icon is shown under 360px. I think that we need to change it
