### ISSUE TITLE
Adding theme-live-codeblock makes prism.darkTheme stop working

### ISSUE THREAD

**Issue by mharsat** [facebook/docusaurus#2705]
## 🐛 Bug Report

When adding `theme-live-codeblock` to `themes`, `prism.darkTheme` has no effect.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

yes

## To Reproduce

1. Set different light and dark themes under prism, for example:
```js
prism: {
	theme: require("prism-react-renderer/themes/github"),
	darkTheme: require("prism-react-renderer/themes/vsDark"),
},
```
2. Add `theme-live-codeblock` to `themes`
```js
themes: ["@docusaurus/theme-live-codeblock"]
```
3. `yarn start` and set dark mode

## Expected behavior

Code blocks should follow `prism.theme` in light mode and `prism.darkTheme` in dark mode

## Actual Behavior

Code blocks use light theme in dark mode (`prism.darkTheme` is never used)

![Screen-Recording-2020-04-30-at-23 11 07](https://user-images.githubusercontent.com/12008392/80754815-5cd34300-8b38-11ea-8108-ee9840a7a41b.gif)

Removing `theme-live-codeblock` solves the issue

## Your Environment

- Docusaurus version used: 50 & 54
- Environment name and version - Chrome 81.0.4044.129
- Operating system and version - desktop

**Comment by lex111** [comment]
Strange, we at our website v2 use a [separate theme for dark mode](https://github.com/facebook/docusaurus/blob/master/website/docusaurus.config.js#L71), but it works for us, you can see it yourself (eg. https://v2.docusaurus.io/docs/docs)

**Comment by mharsat** [comment]
I created a minimal repo with the steps I wrote and it doesn't reproduce. Might be some other condition I'm missing. The issue can be closed if others don't experience this.

**Comment by llldar** [comment]
I had the same problem, I figured out the reason, it's because the version of @docusaurus/theme-live-codeblock is not the same as @docusaurus/core. I managed to fix the problem by making them all the same version.
