### ISSUE TITLE
useBaseUrl description a tad confusing

### ISSUE THREAD

**Issue by techieshark** [facebook/docusaurus#2706]
## 📚 Documentation

`useBaseUrl` is described as a "React hook to automatically append baseUrl to a string automatically."

Pedantic, but I think it actually *prepends* `baseUrl` to the supplied string. (Reporting here since this confused me a bit, not because I'm trying to be pedantic.)

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

### Steps to reproduce:

View the core docs for `useBaseUrl` [here](https://github.com/facebook/docusaurus/blob/af89a926284eba7c03d2a8838e72be37b432be54/website/docs/docusaurus-core.md#usebaseurl). See that the word used is "append". Expect instead to have seen "prepend".

### Discussion

Alternatively, perhaps the docs should read as follows. (Note I'd also take out the second "automatically".

```
React hook to automatically append a string to the baseUrl.
```

**Comment by yangshun** [comment]
You're totally right. It's a blind spot for us because we know what it does and didn't notice that it doesn't really mean what it does. We'll fix it if nobody beats us to it!
