### ISSUE TITLE
Allow custom pages to use docs sidebar and table of contents

### ISSUE THREAD

**Issue by chetanmajithiya** [facebook/docusaurus#2712]

**Comment by fanny** [comment]
Can you clarify a little bit?

**Comment by chetanmajithiya** [comment]
if i'm creating custom page,
then how to use docusaurus sidebar (left, right side for inner page link) in the page,
like docs page.

**Comment by chetanmajithiya** [comment]
@fanny

**Comment by yangshun** [comment]
Not possible now as we don't expose the docs data model to external plugins. Gatsby will allow you to do that via GraphQL.

**Comment by jacksonmgoode** [comment]
Just a follow up question, sidebars don't recognize header html tags, but only markdown header tags. Is there anyway to have the sidebars look for html header tags? Or perhaps convert html to markdown (within a .mdx file)?

**Comment by jacksongoode** [comment]
With some recent updates, would a custom sidebar toc be possible? In my case, I am rendering through MDX for a step by step tutorial component.

**Comment by slorber** [comment]
Hi,

The sidebars is currently highly coupled with the Docs plugin.

What do you want to display exactly in this sidebar?
You said "sidebar TOC", but we have both sidebar (left) and TOC (right), are we sure to talk about the sidebar here?

Have you tried using a secondary sidebar or a secondary docs plugin instance? If so, can you explain why this did not work for your usecase?

If we decoupled the sidebar component from our Docs plugin, are you ok to provide the exhaustive sidebar tree as props yourself? Do you expect the sidebar state (like collapsed categories) to be controlled or uncontrolled?
