### ISSUE TITLE
Lookup of css and static source files invalid when deploying into subdirectory (self-hosted)

### ISSUE THREAD

**Issue by Zenahr** [facebook/docusaurus#2715]
## 🐛 Bug Report

Placing the build files into a subdirectory does yields broken css and js.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes.

## To Reproduce

1. npx docusaurus-init
2. cd website
3. yarn build
4. put built files into subdirectory on website via ftp
5. visit page

You can see for yourself by visiting this site:
zenahr.com/docs/unreal-engine
That's where I've put my docosaurus built files into.

## Expected behavior

Look for css and js resources inside root-directory, not via global domain name.

## Actual Behavior

On local environment it works fine, but when opening up dev-tools on the hosted version you see the following:

![image](https://user-images.githubusercontent.com/47085752/80892463-9dfb5c80-8cca-11ea-87b4-40211233e4d3.png)

This is for the url http://www.zenahr.com/docs/unreal-engine/

## Your Environment

- Docusaurus version used: 1.14.4

## Reproducible Demo

http://www.zenahr.com/docs/unreal-engine/

(Screenshot of deployed site) (tested with chrome and firefox, same result)

![image](https://user-images.githubusercontent.com/47085752/80892517-12360000-8ccb-11ea-9817-450df88acf8e.png)

(Screenshot of local-dev version)

![image](https://user-images.githubusercontent.com/47085752/80892544-4c070680-8ccb-11ea-8ea6-56b9a43bdb30.png)

**Comment by Zenahr** [comment]
Found the cause.

I didn't test it yet but I guess I need to change the baseUrl variable inside siteConfig.js in order for it to work properly.

Would be nice to add this tip to the deployment wiki when deploying on own servers.

**Comment by kinxiel** [comment]
Having the same issue. Also trying to serve the static files in a simple FTP server. Tried messing around with `baseUrl`, but I only seem to get as far as loading the images and logo on the home page correctly with baseUrl: './', but none of the docs load properly. Were you able to find a fix for this problem? Thanks
