### ISSUE TITLE
Add Toc to blog posts

### ISSUE THREAD

**Issue by donaldboulton** [facebook/docusaurus#2717]
## 💥 Proposal

(A clear and concise description of what the proposal is.)

Docusarus v2 -54
How to add a Table Of Contents to Blog Posts like docs have.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

(Write your answer here.)

**Comment by yangshun** [comment]
Swizzle the components.

**Comment by skychx** [comment]
> Swizzle the components.

sorry, I don't understand the meaning of "Swizzle the components"。

I read the  V2 documentation and it seems that only Docs has TOC, but V1's blog supports TOC

**Comment by skychx** [comment]
> Swizzle the components.
![image](https://user-images.githubusercontent.com/24872439/87222168-3afe0400-c3a4-11ea-90d2-dd0e947095ce.png)

![image](https://user-images.githubusercontent.com/24872439/87222163-333e5f80-c3a4-11ea-841f-ba423842d158.png)

**Comment by skychx** [comment]
> > Swizzle the components.
> > ![image](https://user-images.githubusercontent.com/24872439/87222168-3afe0400-c3a4-11ea-90d2-dd0e947095ce.png)
> 
> ![image](https://user-images.githubusercontent.com/24872439/87222163-333e5f80-c3a4-11ea-841f-ba423842d158.png)

Finally, I use 
```bash
yarn run swizzle @docusaurus/theme-classic
```
change `src/theme/BlogPostPage/index.js` add the Toc

**Comment by slorber** [comment]
Yes @skychx you can swizzle the blog post page, it should have a property "rightToc" assigned to it, and you can reuse the Headings comp of the classic theme to render it.

Do you think we should provide this feature out of the box for blog posts too?

**Comment by skychx** [comment]
> Yes @skychx you can swizzle the blog post page, it should have a property "rightToc" assigned to it, and you can reuse the Headings comp of the classic theme to render it.
> 
> Do you think we should provide this feature out of the box for blog posts too?

YES! I think this is a very useful feature to clearly show the structure of the article.

**Comment by muhsatrio** [comment]
> > Swizzle the components.
> > ![image](https://user-images.githubusercontent.com/24872439/87222168-3afe0400-c3a4-11ea-90d2-dd0e947095ce.png)
> 
> ![image](https://user-images.githubusercontent.com/24872439/87222163-333e5f80-c3a4-11ea-841f-ba423842d158.png)

may I shot PR for adding the "Recent Post" section on v2 docusaurus? @slorber

**Comment by slorber** [comment]
Recent posts and TOC seems like useful things PR welcome 👌

**Comment by amy-lei** [comment]
I would love to work on the TOC feature! 😃

**Comment by slorber** [comment]
yes @amy-lei thanks

**Comment by certainlyNotHeisenberg** [comment]
Is it possible to do this at this point (add a table of contents to a `blog` page, like is the default for `docs` pages)? I tried
```
yarn run swizzle @docusaurus/theme-classic
```
as suggested above, but I got loads of `unsafe` warnings, so I stopped.
