### ISSUE TITLE
Target blank in header link of siteconfig.js

### ISSUE THREAD

**Issue by sriramgroot** [facebook/docusaurus#2721]
## 🐛 Bug Report

How to add support for `target='_blank'` in headerlink of siteconfig.js file

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## To Reproduce
Tried to have external link in header segment
`{href: 'https://github.com', label: 'Github', target: '_blank'}`

## Expected behavior

It should be redirect the user to that particular site, once they click the link 

## Actual Behavior

After rendering it is displayed below mentioned screenshot

## Your Environment

- Docusaurus version used: ^1.14.4
- Environment name and version (e.g. Chrome 78.0.3904.108, Node.js 10.17.0): Version 81.0.4044.129 (Official Build) (64-bit)

- Operating system and version (desktop or mobile): macOS mojave (Version 10.14.6)

## Reproducible Demo

https://gist.github.com/sriramgroot/093b67699a57bdff0308857e9fbfc11e

**Comment by amimas** [comment]
I don't think it's a bug. If anything, it's probably a feature request. Based on the docs, I don't think it's currently possible to set a header link to open in a new tab.

**Comment by sriramgroot** [comment]
> I don't think it's a bug. If anything, it's probably a feature request. Based on the docs, I don't think it's currently possible to set a header link to open in a new tab.

Hi @amimas ,
Really thanks for the reply. Whether it is possible in Version 1 of **["Docusaurus"](https://docusaurus.io/)**. If there is not possible in Version1 can you please add them as Version2 of **["Docusaurus"](https://v2.docusaurus.io/)**

**Comment by lex111** [comment]
This is already possible in v2, but I am not sure if it will be added in v1.

**Comment by sriramgroot** [comment]
> This is already possible in v2, but I am not sure if it will be added in v1.

Hi @lex111,
How can we add this as a feature in upcoming version release of **[Docusaurus V1](https://docusaurus.io/)**

**Comment by yangshun** [comment]
Pull requests welcome.

**Comment by taylorallen0913** [comment]
@yangshun Is this solved already?

**Comment by slorber** [comment]
Hey, this exists in v1 since 2017, just wasn't documented 🤪 

```
  { href: "https://github.com/", label: "GitHub", external: true },
```

=> #3011
