### ISSUE TITLE
Mixed content warning

### ISSUE THREAD

**Issue by benmccann** [facebook/docusaurus#2722]
### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## To Reproduce

Load https://www.chartjs.org/docs/next/

## Expected behavior

Everything is loaded over https

## Actual Behavior

I get the following in the Chrome dev console:
>Mixed Content: The page at 'https://www.chartjs.org/docs/next/getting-started/README' was loaded over HTTPS, but requested an insecure resource 'http://www.chartjs.org/docs/next/getting-started/README/'. This request has been blocked; the content must be served over HTTPS.

## Your Environment

- Docusaurus version used: 2.0.0-alpha.53
- Environment name and version (e.g. Chrome 78.0.3904.108, Node.js 10.17.0): Chrome 80.0.3987.149
- Operating system and version (desktop or mobile): Ubuntu desktop

## Reproducible Demo

https://github.com/chartjs/Chart.js/tree/master/docs

**Comment by lex111** [comment]
@benmccann is this error still relevant? I do not see it in my browser (Chrome). Moreover, this kind of error can hardly be associated with Docusaurus.

**Comment by benmccann** [comment]
Hmm, I just tried again and it still is happening for me. It's simply Docusaurus docs deployed to GitHub pages and I do not have "http" anywhere in my config, so I'm not sure where it would be coming from.

One weird thing that I just noticed - If I open up the Chrome developer console and then go to https://www.chartjs.org/docs/next/ it doesn't happen. If I go to https://www.chartjs.org/docs/next/ and then open up the Chrome developer console I do see the issue

**Comment by lex111** [comment]
Now I see this error, although it is strange to me. As I understand it, the matter is in a redirect

![image](https://user-images.githubusercontent.com/4408379/81113713-56264080-8f29-11ea-9578-b130a0ba2cdc.png)

https://github.com/chartjs/Chart.js/blob/2851a94b9206a37a238f91a8d364f75df17d4d14/docs/src/pages/index.js#L7

But how can this internal redirect might cause such an error? Maybe @yangshun will help sort this out.

FYI will soon you not need to manually specify a redirect and create a separate page in general for this purpose, I made it possible to set document as a home page (see [this PR](https://github.com/facebook/docusaurus/pull/2652) for more details).

**Comment by benmccann** [comment]
Oh, awesome. I will subscribe to that issue. I'll test it out when it's done and see if it fixes this

**Comment by lex111** [comment]
> Oh, awesome. I will subscribe to that issue. I'll test it out when it's done and see if it fixes this

It is available since `v2.0.0-alpha.55`.

**Comment by benmccann** [comment]
I've upgraded my project to `2.0.0-alpha.55`. However, I've been unable to set `homePageId`

My project is here: https://github.com/chartjs/Chart.js/tree/master/docs

I've tried setting it to `index` and to `docs/VERSION/index` (i.e. including `baseUrl`) and I get "Page Not Found"

I also tried leaving it unset and renaming `index.md` to `_index.md` and then I get React errors:

> Uncaught TypeError: Cannot read property 'find' of undefined

**Comment by lex111** [comment]
You need to specify exactly the _document id_ (`id`) from the front matter file. Only the document id is accepted. In the case of versioning, it is assumed that this file will be exist (in other words, you cannot define another id for versioned docs)

**Comment by benmccann** [comment]
[Isn't the document id the file name without the extension?](https://v2.docusaurus.io/docs/docs-introduction/#document-id). In that case I don't see what I'm doing wrong and I would expect `homePageId: 'index'` to work or also my other attempted solution of renaming `index.md` to `_index.md`. (btw, I think `homePageId` is confusing casing because "homepage" is most typically one word)

(btw, if you look at my `docusaurus.config.js` you might be a bit confused by our use of `VERSION`. we're not using Docusaurus's versioning. we're just building the docs as a single version but swapping out `VERSION` with our build script before building)

**Comment by lex111** [comment]
Hi @benmccann this bug fixed in [.56](https://github.com/facebook/docusaurus/releases/tag/v2.0.0-alpha.56), I just checked it on my local copy of Chart.js, the docs home page feature works as expected. Sorry for long wait.

**Comment by benmccann** [comment]
Thanks @lex111 !  I'm running into an error with `.56` unfortunately though:

```
Error: Cannot find module '@docusaurus/plugin-google-analytics'
Require stack:
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:797:15)
    at Function.resolve (internal/modules/cjs/helpers.js:80:19)
    at node_modules/@docusaurus/core/lib/server/plugins/init.js:40:67
    at Array.map (<anonymous>)
    at Object.initPlugins (node_modules/@docusaurus/core/lib/server/plugins/init.js:22:10)
    at Object.loadPlugins (node_modules/@docusaurus/core/lib/server/plugins/index.js:47:28)
    at Object.load (node_modules/@docusaurus/core/lib/server/index.js:57:62)
    at start (node_modules/@docusaurus/core/lib/commands/start.js:45:34)
    at node_modules/@docusaurus/core/bin/docusaurus.js:29:5
    at Command.<anonymous> (node_modules/@docusaurus/core/bin/docusaurus.js:97:23)
    at Command.listener (node_modules/commander/index.js:370:29)
    at Command.emit (events.js:210:5)
    at Command.parseArgs (node_modules/commander/index.js:892:12)
    at Command.parse (node_modules/commander/index.js:642:21)
    at Object.<anonymous> (node_modules/@docusaurus/core/bin/docusaurus.js:120:5)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
```

I upgraded all the dependencies in `Chart.js/docs/package.json` to `.56`:
```
    "@docusaurus/core": "^2.0.0-alpha.56",
    "@docusaurus/plugin-google-analytics": "^2.0.0-alpha.56",
    "@docusaurus/preset-classic": "^2.0.0-alpha.56",
    "@docusaurus/theme-live-codeblock": "^2.0.0-alpha.56",
```

**Comment by lex111** [comment]
![image](https://user-images.githubusercontent.com/4408379/83074149-5de58a80-a07a-11ea-9111-14b6e1f7d867.png)

:)

**Comment by benmccann** [comment]
I can confirm everything's working now. Thank you so much for the help!

**Comment by yangshun** [comment]
Thank you for the quick feedback!
