### ISSUE TITLE
Specify input build for deployment

### ISSUE THREAD

**Issue by krillboi** [facebook/docusaurus#2723]
## 🚀 Feature

We would like to be able to specify an input for deployment - that is a folder with the whole documentation site built. This is because we would like to be able to:

* Build the documentation
* Then run some validation on that build
* Supply this build for deployment instead of the deploy script building the documentaion again

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes.

## Motivation

Speed up our deployment steps.

## Pitch

Would open up the deployment script more. Could be used like `yarn deploy --input "path/to/build"`.

**Comment by lex111** [comment]
The `docusaurus deploy` command already has an option for this purpose, isn't that what you need? https://v2.docusaurus.io/docs/cli#docusaurus-deploy

**Comment by krillboi** [comment]
I might be misunderstanding something, but isn't that option just what the folder for the output should be?

What I would like is for there to be an input option, so you're effectively skipping the build step of the deploy script because you're supplying a build yourself.

**Comment by lex111** [comment]
Fine, then we need a new option something like `yarn deploy --skip-build`, right?

**Comment by krillboi** [comment]
Yeah that would work as well.
