### ISSUE TITLE
Integrate with github wiki

### ISSUE THREAD

**Issue by Atiladanvi** [facebook/docusaurus#2725]
## 🚀 Feature

Integrate docusaurus with github wiki

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

yes

## Motivation & Pitch

  The github wiki tools is a way very simple for write docs for applications because they has a dynamic versionament system without git wrapper. Its a easy way to manage docs with a history of modifications. In this way i think the docusaurus can be able read too by  and show the pages and menu from github wiki in a simple way only configure the url of a git hub wiki.

**Comment by amimas** [comment]
Do you mean just presenting github wiki differently? That's really not the purpose of this tool. It's a static site generator. Maybe I misinterpreted the proposal.

**Comment by yangshun** [comment]
I think what @Atiladanvi means is to use GitHub wiki as a source of the docs content. This should be possible using plugins.

**Comment by amimas** [comment]
Ahh... Source of docs from github wiki. Thanks for clarifying it.

**Comment by amimas** [comment]
It still feels a bit outside of Docusaurus purpose - creating technical docs site. 

Sourcing docs from another source like headless cms (i.e. contentful) might make sense. What would be the point of sourcing from github wiki? That's just presenting wiki content differently than how github does it.

**Comment by yangshun** [comment]
Yeah, agreed. I think this is out of scope of Docusaurus.

**Comment by Atiladanvi** [comment]
Thanks for explanation. I will write a plugin to implement this feature

**Comment by meleu** [comment]
hey @Atiladanvi (a 🇧🇷 fellow here :wave:).

Have you created such plugin? Is it open-source? I'm interested in the very same thing.

I'm the maintainer of <https://docs.retroachievements.org/> and currently I use [mkdocs](https://www.mkdocs.org/) with some [shell script tricks](https://github.com/RetroAchievements/docs/blob/master/generate-docs.sh) to get the input files come from [the wiki](https://github.com/RetroAchievements/docs/wiki). But I'm willing to migrate to Docusaurus, as a more modern platform with some nice features.

**Comment by Atiladanvi** [comment]
Hello @meleu. I was think to write this. But i'm waiting a big idea to start. As a you can see the @vanbasten17  created a issue about this and i'm watch. In that issue has explaned ways how implements that functionalitie. If you wanna do this now let's work.

**Comment by vanbasten17** [comment]
Hi @Atiladanvi , sorry for not updating the state in the issue, I didn't find time any more. I finally came up with something simple that covered our needs atm, but I think it would be very necessary to source external content to feed the site. I have created a script to automate some of these steps as you can see here: https://github.com/hubtype/botonic/blob/master/docs/website/scripts/update-plugins-docs/index.ts. As an idea, you could automate the following steps:
1. Creation of a directory inside the directory storing the markdown files.
2. Fetch the content from github or any other pullable site (for releases I used this [simple solution](https://www.npmjs.com/package/fetch-repo-dir)). You can also pull some contents with this API from Github https://docs.github.com/en/free-pro-team@latest/rest/reference/repos#contents.
3. Generate a header for each .md file.
4. Bump there the content.
5. Update necessary sidebars/localization references.

I hope it helps!
