### ISSUE TITLE
Docs editURL assumes `docs/` base path

### ISSUE THREAD

**Issue by KimBurgess** [facebook/docusaurus#2731]
## 🐛 Bug Report

The `editUrl` built as part of [doc metadata](https://github.com/facebook/docusaurus/blob/5e664a1f26fc980033bb3b25a80bdc6cb1edd2c2/packages/docusaurus-plugin-content-docs/src/metadata.ts#L93) assumes that the base path for the docs source matches the local paths (e.g. always processed with `docs/`). This may not always be the case if the content is coming from a separate repo.

As an example: [placeos/docs](https://github.com/PlaceOS/docs), which then maps into [place-technology/website](https://github.com/place-technology/website) as a submodule. Setting `editUrl` in the config to `https://github.com/placeos/docs/edit/master/` results in all edit links generating `https://github.com/placeos/docs/edit/master/docs/` as the base path.

*edit: cross-repo dependency in linked example is now via npm for better build support, but same issue still exists.*

In v2 there does not look to be a way to override this behaviour. What seems to be the [old behaviour](https://v2.docusaurus.io/docs/migrating-from-v1-to-v2/#customdocspath-docsurl-editurl-enableupdateby-enableupdatetime) seems preferable for flexibility.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

yes

**Comment by fanny** [comment]
Hey @KimBurgess thanks to the report, What do you mean with "old behaviour seems preferable for flexibility"? the v2 config seems equal to v1 https://v2.docusaurus.io/docs/using-plugins#docusaurusplugin-content-docs, I mean with the same fields, but with different names.

If you try to change the `editUrl` and `path` doesn't work?

**Comment by KimBurgess** [comment]
Hey @fanny, the limitation is that it tightly binds the docs source and website repos.

Here's an example config:
```javascript
        docs: {
          path: 'node_modules/placeos-docs',
          sidebarPath: require.resolve('./sidebars.js'),
          editUrl: 'https://github.com/placeos/docs/edit/master/',
        },
```
(from [here](https://github.com/place-technology/website/blob/master/docusaurus.config.js#L142-L146))

The docs repo is just a set of markdown files that can be separately maintained. This allows them to be used as part of the site, but also in other distribution channels.

Using an `editUrl` that allows for specifying the full base path enables this style of setup.

**Comment by infotexture** [comment]
Ran into this too today. 

Looks like the `routeBasePath` specified in `@docusaurus/preset-classic` [configuration](https://v2.docusaurus.io/docs/api/plugins/@docusaurus/plugin-content-docs#configuration) should be appended to the `editUrl` value when calculating the edit link target — but even when the docs  `routeBasePath` is set to something other than `docs`, the edit URLs still append the hard-coded `docs/` value.

**Comment by slorber** [comment]
Let's close in favor of https://github.com/facebook/docusaurus/issues/3152

@infotexture I don't believe it's true that we append a "docs" to all edit URLs.
See for example on Docusaurus v2 website, this page does not have any `docs` in its editUrl: https://v2.docusaurus.io/community/support

But agree that this editUrl system must be made more flexible to suit all usecases

**Comment by infotexture** [comment]
@slorber Thanks for the quick response, I missed #3152 earlier when searching for related issues.

I see that it works in the link you shared above.

Perhaps the behavior I see is related to my custom config. I'll add a comment to #3152 and follow along over there…

**Comment by infotexture** [comment]
@slorber Found the answer in https://github.com/facebook/docusaurus/issues/3152#issue-667570288

>  "Edit this page" links for content docs are generated by joining the `editUrl` with the `path` setting.

I had modified the `routeBasePath`, but not the `path` setting, which explains where `docs` was coming from.

I updated my comment above and will send a PR later to clarify the docs.

**Comment by slorber** [comment]
thanks :)
