### ISSUE TITLE
Line highlight is not working in D2

### ISSUE THREAD

**Issue by omry** [facebook/docusaurus#2733]
## 🐛 Bug Report

Line highlight is not working in D2,

## To Reproduce

(Write your steps here:)

code block:
```jsx {3}
function HighlightSomeText(highlight) {
  if (highlight) {
    return 'This text is highlighted!';
  }

  return 'Nothing highlighted';
}
```

## Expected behavior
line 3 should be highlighted in the rendered codeblock.

## Actual Behavior
![image](https://user-images.githubusercontent.com/376455/81506617-7731bd00-92ac-11ea-81aa-0dc3a414c3d2.png)

## Your Environment

- Docusaurus version used:
2.0.0-alpha.50

- Environment name and version (e.g. Chrome 78.0.3904.108, Node.js 10.17.0):
Google Chrome 81.0.4044.138-1

- Operating system and version (desktop or mobile):
Linux desktop

**Comment by yangshun** [comment]
Can we see this code block live on hydra.cc?

Btw did you follow this?

> To accomplish this, Docusaurus adds the docusaurus-highlight-code-line class to the highlighted lines. You will need to define your own styling for this CSS, possibly in your src/css/custom.css with a custom background color which is dependent on your selected syntax highlighting theme. The color given below works for the default highlighting theme (Palenight), so if you are using another theme, you will have to tweak the color accordingly.

**Comment by omry** [comment]
Ah, I missed that.I was expecting to to work out of the box.

once I add the css block to my custom.css it works:
![image](https://user-images.githubusercontent.com/376455/81507184-6420ec00-92b0-11ea-9637-9b1efb07cb2c.png)

**Comment by yangshun** [comment]
We added this line to the default `custom.css` in one of the recent versions but you didn't get updates for it.

Closing this out since not really a bug!

**Comment by omry** [comment]
sounds good.
"didn't get updates for it" meaning it's just being delayed?

a related question:
I remember seeing something about specifying a filename for a codeblock in previous release notes. but I can't find it in the docs.
I am able to find title though. Is this the same feature?

![image](https://user-images.githubusercontent.com/376455/81507361-bf9fa980-92b1-11ea-8375-42766949638f.png)

**Comment by yangshun** [comment]
> "didn't get updates for it"

Nope, this file is cloned on init.

> I am able to find title though. Is this the same feature?

Yes

**Comment by omry** [comment]
> > "didn't get updates for it"
> Nope, this file is cloned on init.

Does it mean that if I recreate my website it would work?

**Comment by yangshun** [comment]
Yes kinda, if you ran the init command again and moved all your contents there. But I wouldn't advise to do that. This is probably the only change that we made to the skeleton `custom.css`.
