### ISSUE TITLE
Add support deploy to Gitlab pages

### ISSUE THREAD

**Issue by limkinZero** [facebook/docusaurus#2736]
## 🚀 Feature

Add support deploy to Gitlab pages

## Motivation

To add more functionality 

## Pitch

I consider that you can give more facilities to projects that use this repository. It should be something similar to what already exists for Github pages.

**Comment by amimas** [comment]
I always felt this tool shouldn't have github publishing commands baked in. There are so many ways a static site can be deployed in so many hosting providers.

You don't really need a special command for deploying to gitlab pages. The key is building the site in GitLab CI and then saving the build result following Gitlab docs.

**Comment by yangshun** [comment]
Yeah you have a `build` directory now and it's hosting provider-agnostic, so GitLab integration will be low priority.

**Comment by rafaelrdealmeida** [comment]
Hi, eu tentei fazer o deploy do docusaurus v2 no gitlab pages. O site esta no ar mas aparentemente só com o html tem alguma coisa que falta no build?

Em minha maquina local funciona perfeitamente e todos os arquivos do build/ local e gitlab-pages são iguais. Você saberia me dizer  o que houve?

```
site: 
https://unesp-labri.gitlab.io/docs/idocs/

yml:
https://gitlab.com/unesp-labri/docs/idocs/-/blob/master/.gitlab-ci.yml

job artifacts:
https://gitlab.com/unesp-labri/docs/idocs/-/jobs/788974678
```


cheers

**Comment by rafaelrdealmeida** [comment]
Hi, I tried to deploy docusaurus v2 on gitlab pages. The site is live but apparently only with html is there anything missing in the build?

On my local machine it works perfectly and all the files in build / local and gitlab-pages are the same. Could you tell me what happened?

site:
https://unesp-labri.gitlab.io/docs/idocs/

yml:
https://gitlab.com/unesp-labri/docs/idocs/-/blob/master/.gitlab-ci.yml

job artifacts:
https://gitlab.com/unesp-labri/docs/idocs/-/jobs/788974678


cheers

**Comment by limkinZero** [comment]
Check your path and url attributes in config file.

Test with:

url: 'https://unesp-labri.gitlab.io/docs/idocs/',
baseUrl: '/',

**Comment by rafaelrdealmeida** [comment]
Hi, I just tested, the problem remains

https://gitlab.com/unesp-labri/docs/idocs/-/blob/master/docusaurus.config.js

**Comment by rafaelrdealmeida** [comment]
Hi,

Continue testing here and below follow my conclusions.

To deploy docusaurus on Gitlab Pages as things are currently structured, it is necessary that the project is not within a group or subgroup. The creation of groups and subgroups is an interesting feature of GitLab and when you create a static website within a group it becomes a subdomain.

For example, the users "Slash" have a group called "Docusaurus" and within the group we have the project "docs" the url that gitlab generates for the project "docs" is **https://docusaurus.gitlab.io/docs**

In my specific case the project was within a subgroup that we have here (general-group / subgroup-docs / project-with-dunosaurus)

I believe that module.exports does not handle this subgroup issue well and ends up breaking css and javascript. I did not get any adjustments to resolve this by specifying the url, baseUrl, organizationName and projectName tags.


Now if you upload Docusaurus at the "user root" (outside of any group) everything works fine! Just follow the same github setup instruction for docusaurus.config.js. In addition to the official doc, this video helped me: [Deploy Docusaurus 2 on GitHub pages](https://youtu.be/NiHFqziyvyk).

And configure **gitlab-ci.yml** as below:

```yml
image: node:14.13.1
pages:
    stage: deploy
    script:
      - yarn install
      - yarn run build
      - mv build public
    artifacts:
        paths:
          - public
    only:
      - master

# see: https://about.gitlab.com/blog/2016/04/07/gitlab-pages-setup/
```

After that, just push the gitlab and the docusaurus goes on the air!


Is there anything we can do to address this issue of gitlab groups and subgroups?

cheers

**Comment by slorber** [comment]
@rafaelrdealmeida you are overcomplicating things.  Your site is https://unesp-labri.gitlab.io/docs/idocs/, you should just use baseurl = /docs/idocs/ so that our js/css URLs use this pathname prefix as well.

This is totally unrelated to groups, subgroups or whatever, it's just related to what is the pathname prefix of your homepage.

Closing this issue because I don't think we should provide a detailed user guide for all service providers. I don't particularly like to be biased towards GH pages (which IMHO is not the best Docusaurus hosting solution) and don't think Gitlab is either a great choice as a hosting solution.

**Comment by rafaelrdealmeida** [comment]
Hi @slorber , 

thanks for the reply, your indication to adjust the baseurl=/docs /idocs/ worked and the site is live, thanks! With the few lines in gitlab-ci.yml the site works.

I was going to do a pull resquest in the documentation to put delploy through gitlab pages (would that be a bad idea?). But I understand your indication that other hosts are more suitable for this (Netlify, Vercel, Surge, Render etc ...).

Although I think that github and gitlab are an important gateway to the use of Docusaurus

cheers

**Comment by slorber** [comment]
Great @rafaelrdealmeida 

For the baseurl problem, this problem appears very frequently (no matter the host), and I decided we should do something about it: https://github.com/facebook/docusaurus/issues/3584

About deployment docs, I don't really like the idea that we bias towards Github, or Gitlab, particularly when they are not the best deployment options.

I'm not familiar with Gitlab much so can't tell if your doc will be helpful, but hope the issue above should fix the baseurl problem once for all for all hosts.

Do you see other things important to consider for Gitlab?

**Comment by rafaelrdealmeida** [comment]
HI @slorber,

It will be really good to adjust this baseurl question (it creates some confusion)

I agree with you about Deploying to GitHub/GitLab. I tested it on the render and the deployment went well. I believe that this point could be highlighted in the excellent documentation of docusaurus.

https://sitelabri-teste01.onrender.com/
https://www.novo2.labriunesp.org/

But I still think that services outside of Github can be an entry barrier to the use of docusaurus. For use in small and medium github/gitlab projects, I believe it should prevail.

Do you have any metrics of services used by users to deploy docusaurus?

Regarding Gitlab Pages I put the domain name and everything works fine. I had to adjust url and baseurl. Would you know to tell me if it is possible in addition to the domain name to keep the address generated by gitlab active (I tried to adjust some things in docusaurus.config.js but without success)? I wanted the two addresses below working:

https://novo.labriunesp.org
https://unesp-labri.gitlab.io/site

The points I would highlight from GitLab Pages would be:

* Easy deploy (basically configure gitlab-ci.yml and docusaurus.config, js as indicated above)
* Possibility of having docusaurus working in closed repositories (this is well used even for open source projects that are structuring documentation before opening the repository)

**Comment by amimas** [comment]
I also don't think the docs should include deployment instructions for github/gitlab or anything else.

Having said that, it might be helpful for someone to have a blog post about very specific deployment process or strategy. Not sure if docusaurus would like the blog on their site.

**Comment by slorber** [comment]
@rafaelrdealmeida 

> It will be really good to adjust this baseurl question (it creates some confusion)

What do you mean by "adjust"?  What should we do exactly to make it clearer apart showing. a big error message with help instructions (see https://github.com/facebook/docusaurus/issues/3584). Should we do something else? 

> Do you have any metrics of services used by users to deploy docusaurus?

We don't have that. I believe Github deployment is much more common than Gitlab though, and we documented GH pages better. Not sure Gitlab usage is superior to Netlify or Vercel.


> Would you know to tell me if it is possible in addition to the domain name to keep the address generated by gitlab active

I don't understand what you mean at all sorry. I can't access your Gitlab URLs.

About documenting Gitlab deployment, isn't the Gitlab documentation good enough? What added value can we add? 
I can't create/maintain myself the doc of all hosting solutions (particularly those I don't know/use), so do you want to write such doc, and maintain it over time to keep it up to date?  Don't you feel it would be simpler if users read the Gitlab doc on how to deploy a static site in the first place?

**Comment by slorber** [comment]
@amimas I wouldn't be against publishing a blog tutorial on how to deploy Docusaurus on Gitlab. As a blog post posted at a given time, we don't really have to "maintain it"

**Comment by L-U-C-K-Y** [comment]
> @rafaelrdealmeida
> 
> > It will be really good to adjust this baseurl question (it creates some confusion)
> 
> What do you mean by "adjust"? What should we do exactly to make it clearer apart showing. a big error message with help instructions (see #3584). Should we do something else?
> 
> > Do you have any metrics of services used by users to deploy docusaurus?
> 
> We don't have that. I believe Github deployment is much more common than Gitlab though, and we documented GH pages better. Not sure Gitlab usage is superior to Netlify or Vercel.
> 
> > Would you know to tell me if it is possible in addition to the domain name to keep the address generated by gitlab active
> 
> I don't understand what you mean at all sorry. I can't access your Gitlab URLs.
> 
> About documenting Gitlab deployment, isn't the Gitlab documentation good enough? What added value can we add?
> I can't create/maintain myself the doc of all hosting solutions (particularly those I don't know/use), so do you want to write such doc, and maintain it over time to keep it up to date? Don't you feel it would be simpler if users read the Gitlab doc on how to deploy a static site in the first place?

We would also be happy to be able to deploy Docusaurus on Gitlab as we could public internal docs with GitLab access control.

As @rafaelrdealmeida states, deploying in root works, but having it in sub-projects does not properly display the docs. For us, it would be quite difficult to have all Docusaurus repos in the root directory exclusively.

**Comment by amimas** [comment]
Is the `baseUrl` property set? I think it defaults to root and configuring that to match the expected site root should take care of it. I think @slorber   already mentioned that above.

Did that not work?
