### ISSUE TITLE
Include SVG logo directly to the code

### ISSUE THREAD

**Issue by raisty** [facebook/docusaurus#2737]
## 🚀 Feature

SVG images should be inserted directly to code. This will provide manipulation of the logo in case - for example, a dark theme. Currently, is SVG linked to img tag.
`<img class="navbar__logo" src="/img/docusaurus_keytar.svg" alt="Docusaurus Logo">`

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

👍 

## Motivation

We should manipulate SVG logos when we are changing the theme.

## Pitch

The best will be recognized SVG image from settings and then insert it directly to code. This will secure possibility to manipulate image directly from CSS, SASS, etc.

**Comment by lex111** [comment]
Use the `srcDark` option to set the logo for dark mode. https://v2.docusaurus.io/docs/theme-classic/#navbar-title--logo
I think this option will be enough. If not, please give another real-world example.

**Comment by raisty** [comment]
Acceptable answer: **Yes**
Ideal solution: **No**
_"Real-World" example_: We have in design manual transformations based on color. My proposal will do the job without uploading a new image. Another advancement will be applying all portfolio of CSS transformations for special events - like Christmas, Easters, etc.

**Comment by yangshun** [comment]
This can be done by using your own webpack plugin - to inject the svg or base64 representation into the code. Will not be done in core.
