### ISSUE TITLE
Spacing around H1 headers that are not the title of the page

### ISSUE THREAD

**Issue by JoelMarcey** [facebook/Docusaurus#274]
Check the middle of https://facebook.github.io/relay/docs/en/mutations.html

<img width="1055" alt="screenshot 2017-12-11 16 31 14" src="https://user-images.githubusercontent.com/3757713/33861084-b8f1b7fe-de90-11e7-9562-ce6db4255fa6.png">

**Comment by Ethan-Arrowood** [comment]
Can i snag this one? I'd love to get familiarized with this project source code 😄

**Comment by JoelMarcey** [comment]
@Ethan-Arrowood Absolutely. Let us know if you have any questions!

**Comment by Ethan-Arrowood** [comment]
They seem to have updated their docs. Can't find an example of this issue

**Comment by JoelMarcey** [comment]
@kassens Did you work around the H1 header issue on relay?

**Comment by neilsutcliffe** [comment]
They have changed it as part of this commit

[Commit: Update mutation docs](https://github.com/facebook/relay/commit/6ad8b246540427df91458b0f86fb7105b8cca6e3#diff-9b5621142c64f09dec2594f1e9619e23)

To reproduce, just go into your devtools and change it to a H1. I can see if I can get to the bottom of this though.

**Comment by neilsutcliffe** [comment]
So the H1 at the top of the page is actually from the header section of the markdown file, so it is formatted differently.

You should never really have more than one header on a page, but if you wanna be all punk-rock, then #306 should solve the problem.

**Comment by JoelMarcey** [comment]
@neilsutcliffe I do agree in general that no more than one H1 should be on a page. I try to adhere to that as much as possible myself. But, of course, there are always exceptions. I am glad you have a PR to support it.

**Comment by JoelMarcey** [comment]
Closed by #306
