### ISSUE TITLE
v2 cli expects siteConfig.js and sidebars.json to exist

### ISSUE THREAD

**Issue by Morriz** [facebook/docusaurus#2740]
## 🐛 Bug Report

v2 cli expects siteConfig.js and sidebars.json to exist

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

yes

## To Reproduce

(Write your steps here:)

1. `npm install -g docusaurus@^2.0.0-alpha`
2. `docusaurus-build`

## Expected behavior
The build to continue

## Actual Behavior

Errors about missing files (old names from v1 it seems):

`Error: No siteConfig.js file found in website folder!'

When I then copy `docusaurus.config.js` to `siteConfig.js` and run again I get:

`{ Error: Cannot find module '.../sidebars.json' ...`

## Your Environment

- Docusaurus version used: 2.0.0-alpha54
- Environment name and version (e.g. Chrome 78.0.3904.108, Node.js 10.17.0): v11.15.0
- Operating system and version (desktop or mobile): osx catalina

## Reproducible Demo

Not needed. It's an obvious mistake and probably known.

**Comment by yangshun** [comment]
You're still installing v1. V2 package is called @docusaurus/core. Please
refer to the exact installation instructions.

**Comment by Morriz** [comment]
Tnx. Can you tell me where to look? I thought I followed them

**Comment by Morriz** [comment]
I feel really stupid, but can't find anything related to @docusaurus/core. Maybe the v2 docs are missing the part in installation about the cli.

**Comment by yangshun** [comment]
Starting from scratch - https://v2.docusaurus.io/docs/installation

Migrating from v1 - https://v2.docusaurus.io/docs/migrating-from-v1-to-v2#packagejson

**Comment by Morriz** [comment]
You do see my point, right? There is no clear documentation on how to install the cli...

**Comment by Morriz** [comment]
I just installed the 2 packages mentioned (core and presets) but still get an error when using cli:
```
Error: Cannot find module '@docusaurus/plugin-content-docs'
```

**Comment by Morriz** [comment]
I guess I will keep adding the missing packages until no errors occur. But would be nice to just offer docs for this.

**Comment by yangshun** [comment]
The preset should already include those modules you'll need as dependency. What cli are you talking about?

**Comment by Morriz** [comment]
Maybe not on a global install? I have no clue why it won't find them. After installing like this:
```
npm install -g @docusaurus/core@next @docusaurus/preset-classic@next
```
And then doing `docusaurus build` I get the errors about all those missing plugins, starting with:
```
Error: Cannot find module '@docusaurus/plugin-content-docs'
```
After explicitly installing that one it starts complaining one by one about the others. So far I explicitly installed:
```
@docusaurus/plugin-content-docs@next
@docusaurus/plugin-content-blog@next
@docusaurus/plugin-content-pages@next
@docusaurus/plugin-sitemap@next
@docusaurus/theme-classic@next
```
But still getting errors...

**Comment by Morriz** [comment]
I don't have a clear head, my NODE_PATH is probably not correct. Using nvm. Weird...

**Comment by yangshun** [comment]
Don't use global installs. You should be adding them to your `package.json` and running `npm install` or `yarn install`.

**Comment by Morriz** [comment]
I can't as I am building a docker image that I wish to use the cli version in, as it's used in a workflow/pipeline that injects the sources to work with. So I can't depend on local `node_modules`
