### ISSUE TITLE
Search not finding text on page

### ISSUE THREAD

**Issue by benmccann** [facebook/docusaurus#2741]
## 🐛 Bug Report

Search can't find the text "autoSkipPadding". It does find some other text on the site though, so is not completely broken

Is it because it's in backticks or because it's in a table? https://raw.githubusercontent.com/chartjs/Chart.js/master/docs/docs/axes/cartesian/index.md

@s-pace do you have any ideas why Algolia only finds some text on the site?

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## To Reproduce

1. Go to https://www.chartjs.org/docs/master
2. Search for "autoSkipPadding"

## Expected behavior

It should find https://www.chartjs.org/docs/master/axes/cartesian/index#tick-configuration

## Actual Behavior

No results

## Your Environment

- Docusaurus version used: 2.0.0-alpha.53
- Environment name and version (e.g. Chrome 78.0.3904.108, Node.js 10.17.0): Chrome 80.0.3987.149

## Reproducible Demo

Code is here: https://github.com/chartjs/Chart.js/tree/master/docs

**Comment by s-pace** [comment]
Should be good now :)

**Comment by benmccann** [comment]
thanks!
