### ISSUE TITLE
<kbd> does not work.

### ISSUE THREAD

**Issue by geekodour** [facebook/docusaurus#2742]
## 🐛 Bug Report

```
<kbd>something</kbd>
```
<kbd>something</kbd>

I have docs full of `kbd` tags from v1 that used to work and now none of them work in v2. Any migration steps for `kbd` tags?

This does not work with `"@docusaurus/core": "^2.0.0-alpha.54"` I've tried remark plugins https://www.npmjs.com/package/remark-kbd it does not seem to help either :/

**Comment by yangshun** [comment]
What does "won't work" mean? Doesn't appear or no styling added?

**Comment by geekodour** [comment]
See the `kitty` section. 
![2020-05-13-131113_1365x767_scrot](https://user-images.githubusercontent.com/12918431/81784701-e3b1f380-951a-11ea-865b-4be06946c584.png)

The markdown for that part is:
```
## kitty
- Increase font size: <kbd>Ctrl</kbd>+<kbd>+</kbd>
- Decrease font size: <kbd>Ctrl</kbd>+<kbd>-</kbd>
- Input unicode: <kbd>Ctrl</kbd>+<kbd>U</kbd>
```

**Comment by yangshun** [comment]
So that's just a different styling, not that it doesn't work. If you see, the styling is still present. It's unlikely we're gonna add the styling in, so for now you can add it into your own website.

**Comment by geekodour** [comment]
[](url)
![2020-05-13-131615_1365x767_scrot](https://user-images.githubusercontent.com/12918431/81785214-a6019a80-951b-11ea-9251-73d1902852ab.png)

@yangshun the markdown is not rendered aswell. What could be causing this.

```
<kbd>[Link to post](LINK HERE)</kbd>
```

**Comment by geekodour** [comment]
I'd expect this to work without any styling.

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/kbd

eg. `<button>` tag works, why not `<kbd>`

**Comment by yangshun** [comment]
> I'd expect this to work without any styling.

`<kbd>` *is styled*, just not the way GitHub does it. It's using monospaced font.

> the markdown is not rendered aswell. What could be causing this

You can't mix JSX and Markdown on the same line. You can do this instead:

```
<kbd>

[my link](...)

</kbd>
```

and it should work

**Comment by geekodour** [comment]
Thanks for the help @yangshun , I applied [these styles](https://www.rgagnon.com/jsdetails/js-nice-effect-the-KBD-tag.html) and it seem to work as expected now. :)

**Comment by lex111** [comment]
I think we can stylize this tag in Infima if @yangshun doesn't mind?

**Comment by yangshun** [comment]
I had it last time but I removed it because I felt that it was quite a rare use case. Idm adding it back I guess.
