### ISSUE TITLE
hide_table_of_contents: true does not expand column to page width

### ISSUE THREAD

**Issue by MichaelBaj** [facebook/docusaurus#2744]
## 🐛 Bug Report

Adding the front matter tag `hide_table_of_contents: true` does not expand column to page width.

## To Reproduce

1. Create any page with content, preferably with headings >2.
2. Observe right hand TOC and formatting
3. Add meta tag `hide_table_of_contents: true`
4. Observe the right hand TOC is no longer present, yet the contents are still fixed at 75% page width

## Expected behavior

I expected the contents to expand to the row width, which would have been 100% of the remaining space, as is depicted in the original feature request on their CONTRIBUTING page: https://github.com/facebook/docusaurus/pull/2012

## Actual Behavior

Removing TOC kept the page width the same as can be seen in this example:
https://docs.128technology.com/docs/api_rest_4.2.0

## Your Environment

- Docusaurus version used: `2.0.0-alpha.54`
- Environment name and version: `Chrome 81.0.4044.138`, `Node.js 13.8.0`
- Operating system and version: `macOS 10.15.4`

## Reproducible Demo

You can see the results https://docs.128technology.com/docs/api_rest_4.2.0

**Comment by yangshun** [comment]
I think this is a regression in the UI when @lex111 was tweaking it to make the code block width work. The test plan of #2012 showed that it was working.

**Comment by slorber** [comment]
@ysulyma then create a repro and show screenshots of expected VS actual behavior. Your comment is not really actionable for us

To me it works as intended

<img width="1914" alt="CleanShot 2022-08-24 at 11 12 38@2x" src="https://user-images.githubusercontent.com/749374/186379677-907e6142-b6b2-43fa-a241-7179dbca7cb5.png">


<img width="1914" alt="CleanShot 2022-08-24 at 11 12 12@2x" src="https://user-images.githubusercontent.com/749374/186379599-937b34cf-6989-4113-9b9d-24a3978bbf9d.png">
