### ISSUE TITLE
(v2) Results from tests vs client differ

### ISSUE THREAD

**Issue by jcomack** [facebook/docusaurus#2748]
## 🐛 Bug Report

In some cases, test output differs from the output on the client-side. 

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## To Reproduce

(Write your steps here:)

1. Place https://gist.github.com/jcomack/688851466b0deebaef419a52e3a4cc26 in a `formatUrl.ts` file, in the `/packages/docusaurus/src/client/exports/` directory.
1. Place https://gist.github.com/jcomack/f00ff888e1aa7ba69f296d6edd17f4f6 in a `formatUrl.ts` file, in the `/packages/docusaurus/src/client/exports/__tests__` directory.
1. Run the tests. See that they all pass
1. Build Docusaurus, implement the function in a particular theme file, such as `DocItem` with the following: `formatUrl('https://foo.com?a=1')` and make sure to log the output of the function somewhere.
1. Check the outputted result. It should be `https://foo.com/?a=1` as per the result of the written test.

## Expected behavior

I expected the results to be the same between tests and the client-side.

## Actual Behavior

The results differ (i.e. the test results _do_ contain the additional `/` whereas the client-side doesn't)

## Your Environment

- Docusaurus version used: v2.0.0-alpha.50
-  Environment name and version (e.g. Chrome 78.0.3904.108, Node.js 10.17.0): Firefox 74.0.1, Node.js v10.19.0
- Operating system and version (desktop or mobile): MacOSX High Sierra 10.13.6 (desktop)

## Reproducible Demo

(Paste the link to an example repo, including a `siteConfig.js`, and exact instructions to reproduce the issue.)

**Comment by yangshun** [comment]
What is the "client side" here?

**Comment by jcomack** [comment]
Hey @yangshun, step 4 is what I mean with "client side". So trying to call the function in one of the theme files (i.e. DocItem in this case) on a an URL yields a different result than calling the same function in the tests.

**Comment by slorber** [comment]
@jcomack I understand that this might be unexpected, but I don't understand why you report it as a Docusaurus bug.

We don't provide a `src/client/exports/formatUrl` file and you are not supposed to add it (at least not in core).

It is possible that the NodeJS and browser implementation of URL is slightly different for some reason.

Please upgrade your versions, and also double-check first if you can't reproduce this bug outside of Docusaurus. If you can prove the bug is in Docusaurus, please re-open an issue
