### ISSUE TITLE
Mobile nav does not close when expanding width

### ISSUE THREAD

**Issue by oriooctopus** [facebook/docusaurus#2750]
## To Reproduce

(Write your steps here:)

1. Reduce size of screen to mobile size (<~1000px)
2. Open mobile nav (bottom right button)
3. Expand screen to desktop size.
4. The nav is not closing, this is what it looks like on the docusaurus official site

<img width="1426" alt="Screen Shot 2020-05-15 at 5 57 45 AM" src="https://user-images.githubusercontent.com/20331238/82047867-c727cf80-9670-11ea-995e-f3fbde70de30.png">

**Comment by yangshun** [comment]
It's a bug indeed, but low priority. We likely won't ever fix this. Why would you do such a thing as a user?

**Comment by oriooctopus** [comment]
True

**Comment by yangshun** [comment]
We can leave it open for interested contributors to try it out :)

**Comment by themilanfan** [comment]
Looks to be an issue within theme-classic, its styling needs to be corrected however I'm not sure where that is located.

**Comment by eKhattak** [comment]
I would love to take this issue and fix it, a good start of MLH Fellowship.
@yangshun  If you can please tell me where is the CSS file located. I couldn't find it.

**Comment by slorber** [comment]
@eKhattak I don't think this is CSS only. Look at `DocSidebar`.

```
  const [showResponsiveSidebar, setShowResponsiveSidebar] = useState(false);
```

```
      <div
        className={clsx('menu', 'menu--responsive', styles.menu, {
          'menu--show': showResponsiveSidebar,
          [styles.menuWithAnnouncementBar]:
            !isAnnouncementBarClosed && scrollY === 0,
        })}>
```

What you could do, is have a hook `useWindowSize` that listen for window resize events and return `"mobile" | "desktop" | undefined` (undefined is for server/SSR in node, on which we can't know ahead of time the size of the screen)

Then an effect that would `setShowResponsiveSidebar(false)` if the window size changes.

Note: we have the problem on the docs sidebar, but it also affects the main sidebar: an overlay is added and stays visible.

Going from mobile<->desktop should rather reset the sidebars state.

**Comment by slorber** [comment]
Released in https://github.com/facebook/docusaurus/releases/tag/v2.0.0-alpha.58
