### ISSUE TITLE
Algolia DocSearch Dark Mode

### ISSUE THREAD

**Issue by fishcharlie** [facebook/docusaurus#2754]
## 🚀 Feature

There should be support for the dark mode for the Algolia DocSearch.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## Motivation

Almost everything in Docusaurus has support for dark mode, except for the Algolia DocSearch.

## Pitch

There should be support for dark mode for the Algolia DocSearch.

**Comment by aianshume** [comment]
how to toggle dark mode manually
