### ISSUE TITLE
Configurable Babel Plugins

### ISSUE THREAD

**Issue by Huxpro** [facebook/docusaurus#2772]
Posted in v2 feedback as well : https://docusaurus-2.netlify.app/feedback/p/configurable-babel

## 🚀 Feature

Being able to configure/add babel plugins such as optional chaining and Flow.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## Motivation

I'm not sure if it's not supported or just not documented (I looked up both v1/v2 doc but wasn't able to find it). I didn't even find what exact babel presets are used from the docs and have to look into the source code.

It just doesn't feel right that Babel is used but not configurable. It's been a norm for JS developers tweaking this very fundamental tooling. 

This also help with people asking for Flow support since they can just do it on their own. I found TS has been added as part of the default presets via #2310, which means people not using TS w/ docusaurus is wasting their time/space for this.

**Comment by yangshun** [comment]
This is definitely something we want to add support for, it should work similar to [Next.js' Babel config](https://nextjs.org/docs/advanced-features/customizing-babel-config)
