### ISSUE TITLE
"feat(v2): allow home page for docs" not working correctly

### ISSUE THREAD

**Issue by maximousblk** [facebook/docusaurus#2776]
## 🐛 Bug Report

I tried out alpha.55 and there seems to be a problem with the `feat(v2): allow home page for docs` feature.

I have `about.md` in the `docs/` directory. I have set `homePageId: 'about'` in `docusaurus.config.js` and have `Info: ["about", ...]` in `sidebars.js` . When I go to `http://localhost:3000/docs/` or `http://localhost:3000/docs/about` I get a 404 Page. But if I go to any other page, It works as usual.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## To Reproduce

1. setup the project using `npx @docusaurus/init@next init alpha55 classic`
2. Create `docs/about.md`
3. Set `homePageId: 'about'` in `docusaurus.config.js`
4. Set `Docusaurus: ['about', 'doc1', 'doc2', 'doc3'],` in `sidebars.js`

## Expected behavior

When I visit `http://localhost:3000/docs/` I should see the contents of `about.md` along with the left sidebar.

## Actual Behavior

When I go to `http://localhost:3000/docs/` or `http://localhost:3000/docs/about` I get a 404 Page. But if I go to any other page, It works as usual.

## Your Environment

- Docusaurus version used: v2.0.0-alpha.55
- Environment name and version (e.g. Chrome 78.0.3904.108, Node.js 10.17.0): 
  - Chrome: 81.0.4044.138
  - Node: v12.16.2
  - Yarn: v1.22.4
- Operating system and version (desktop or mobile): Microsoft Windows [Version 10.0.18363.836]

## Reproducible Demo

Demo project will be posted soon.

**Comment by lex111** [comment]
Actually this basic use case should work. I just checked on the local website. Could you please provide a repo to reproduce?

**Comment by kedarv** [comment]
I get a similar issue upon cloning docusaurus and using the default bootstrap. navigating to /docs works, but going to `docs/doc1` 404s.
