### ISSUE TITLE
Progressive Web App

### ISSUE THREAD

**Issue by fishcharlie** [facebook/docusaurus#2805]
## 🚀 Feature

It would be amazing if there was functionality in Docusaurus v2 to have the website be a Progressive Web App (https://developers.google.com/web/progressive-web-apps/) with Service Workers.

This would allow the site to be loaded on offline or low-quality networks.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## Motivation

Being able to access my docusaurus deployed website without internet connection.

## Pitch

Adding support for the exported site to be a Progressive Web App would allow offline access to the site.

**Comment by lex111** [comment]
FYI we already have a PR (oldest from actives ones) for that, but it is under review.
https://github.com/facebook/docusaurus/pull/2205

Another reminder for @yangshun :)

**Comment by yangshun** [comment]
I'm not familiar enough with PWAs to help review the PR :(

Could @lex111 or @slorber help with reviewing that?

**Comment by lex111** [comment]
Already merged and ready for use.
