### ISSUE TITLE
Search Keyboard Shortcut

### ISSUE THREAD

**Issue by fishcharlie** [facebook/docusaurus#2808]
## 🚀 Feature

Search Shortcut (ex. `s` key or `/` key) functionality for DocSearch search bar to automatically put the cursor in the search bar. This would be similar to how you can hit `s` or `/` to select the GitHub search bar.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## Motivation

Make it easier to access the website search.

## Pitch

This feature would make it easier for users navigating the site to search the page by keeping their hands on the keyboard with a shortcut vs having to use the mouse to click on the search bar.

**Comment by krillboi** [comment]
+1 for this! Though I have heard that DocSearch is releasing a new version soon that should be the one they are using on https://docsearch.algolia.com/ (where you hit Ctrl + K), so maybe Docusaurus just needs to implement this new theme when it releases?

**Comment by yangshun** [comment]
Maybe we can add keyboard support as a core feature to Docusaurus 2.

How it works - plugins can register keyboard shortcuts which Docusaurus will attach as a global event listener and show a list of all supported shortcuts on the website when the user types <kbd>?</kbd>, like Reddit:

<img width="1552" alt="Screen Shot 2020-06-05 at 7 55 28 PM" src="https://user-images.githubusercontent.com/1315101/83873532-8f3f1400-a766-11ea-9182-01500db687ea.png">
