### ISSUE TITLE
(V2) Option to skip next release docs during build

### ISSUE THREAD

**Issue by amimas** [facebook/docusaurus#2813]
## 🚀 Feature

In V1, the build command can be given an option so that next release docs are skipped/ignored when the site is built. This helps with the following use case.

Next release docs are not publicly available until actual release . However, we can continue to make content changes to both next release or versioned docs in the meantime.

The build command can accept an option, `skip-next-release`,  and it will skip those contents accordingly and a site be built with only the versioned docs and an appropriate sitemap.

It's been a very useful feature in V1 related to versioning. It'd be great if this can be added to V2.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## Motivation

This feature is needed for some of my docs sites that cannot have next release docs available. Having this feature is needed for migrating to V2.

## Pitch

It's already implemented in V1. Theoretically, implementing this in V2 would be simpler since the versioning logic is much simpler than before.

**Comment by lex111** [comment]
@amimas will you like it if this option is set in the config file instead the CLI command? When running dev server next release docs will be included, but they will not be during building website. This is not as convenient as passing the flag to the `build` command, but in a our modular architecture this option is more feasible.

**Comment by amimas** [comment]
@lex111  - thanks for looking into it.

In my case, I'm currently building the site twice (using V1). Once the site is built with the skip option enabled and another build without that option. The first build is published publicly and the 2nd build is published somewhere for internal consumption.

Making this option available through CLI would probably be ideal but I think making it available as a configuration should be fine. I think in I can dynamically set this option in the CI build; please correct me if that's not the case.

**Comment by amimas** [comment]
I think what's important, regardless of how that option is set, the site is built with/without the next release docs and the sitemap is generated accordingly.

**Comment by lex111** [comment]
Actually, in our current architecture, the option in config file is the only possibility to change behavior a plugin.

> I think in I can dynamically set this option in the CI buil

- Yon can use environment variables via `process.env`:

```
In config: "skipNextRelease: process.env.SKIP_NEXT_RELEASE"
In terminal: SKIP_NEXT_RELEASE= rue yarn build
```

-   Or you can add placeholder (see Chart.js  example  
 https://github.com/chartjs/Chart.js/blob/master/scripts/docs-config.sh#L30

Fine we will add such config option then.

**Comment by slorber** [comment]
Hey all,  this is feature is now released!
If you like it, don't forget to retweet 😄 
https://twitter.com/docusaurus/status/1286715187983048704

**Comment by Mixermachine** [comment]
If somebody searches this feauture:
The toggle was renamed multiple times.
It is now called **includeCurrentVersion**.
Set this to false to exclude the "next" version.

Have a look here on how to apply that setting:
[https://docusaurus.io/docs/versioning#configuring-versioning-behavior](https://docusaurus.io/docs/versioning#configuring-versioning-behavior)
