### ISSUE TITLE
Example Travis CI script fails with Sharp error in v2

### ISSUE THREAD

**Issue by euanmillar** [facebook/docusaurus#2823]
## 🐛 Bug Report

The TravisCI example deploy script [here](https://v2.docusaurus.io/docs/deployment#triggering-deployment-with-travis-ci) fails with the following error:

```ERR! sharp 'darwin-x64' binaries cannot be used on the 'linux-x64' platform. Please remove the 'node_modules/sharp/vendor' directory and run 'npm install'.```

The problem is related to [https://github.com/lovell/sharp/issues/1459](https://github.com/lovell/sharp/issues/1459)

If the TravisCI script is changed from:

```- yarn && GIT_USER="${GH_NAME}" yarn deploy```

To:

```- npm install && GIT_USER="${GH_NAME}" yarn deploy```

Then the error goes away, but it's no longer using Yarn cache.  So if someone wants a quick fix, then leaving this here.

**Comment by slorber** [comment]
We regularly do updates, it may be fixed already, let us know if it's not in the docusaurus beta.0
