### ISSUE TITLE
Adding docs home page to the sidebar

### ISSUE THREAD

**Issue by ark120202** [facebook/docusaurus#2830]
## 🐛 Bug Report

Trying to include a home page in the sidebar makes it point to a non-existing original URL.

Note: previously I have added is as a href link, however sidebar presence on the home page wasn't stable, and it never appears in 2.0.0-alpha.56 (apparently because of #2785).

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## To Reproduce

1. Create a `docs/introduction.md` page
1. Configure @docusaurus/plugin-content-docs with `homePageId: 'introduction'`
1. Add `"introduction"` to the sidebars file

## Expected behavior

Add an `Introduction` element to the sidebar, that points to the `routeBasePath`.

## Actual Behavior

The link is created, however it points to `/introduction` page, which doesn't exist.

## Your Environment

- Docusaurus version used: 2.0.0-alpha.56
- Environment name and version (e.g. Chrome 78.0.3904.108, Node.js 10.17.0): Chrome 81.0.4044.138, Node.js 14.3.0
- Operating system and version (desktop or mobile): Arch Linux

## Reproducible Demo

1. Clone https://github.com/ark120202/moddota.github.io
1. Checkout `docusaurus-issue-home-page-sidebar` branch
1. Run `npm ci`
1. Run `npm run start` and go to http://localhost:3000/
1. Click on the `Introduction` label in the sidebar

**Comment by lex111** [comment]
Could not reproduce this issue, try removing `node_modules` and `.docusaurus` dirs, and then re-build the site.

**Comment by ark120202** [comment]
Thanks, after removing `.docusaurus` directory the page started working. However the link in sidebar still points to `/introduction`, it would be nice if it would point to the canonical home url. It also doesn't seem to work with the default home page id (sidebar points to `http://127.0.0.1:3000/_index`, but it's not found)

**Comment by lex111** [comment]
Actually this was done intentionally, do you think we do not need to create a separate route for the document, which is used as a home docs page?

**Comment by ark120202** [comment]
Looks like Google recommends to avoid duplicating pages without specifying one as a canonical - https://support.google.com/webmasters/answer/139066

**Comment by lex111** [comment]
Yep, I only now realized that I had missed this point, but maybe we should not create a route for such a document at all? I'm not exactly sure.

**Comment by ark120202** [comment]
Yeah, I think it makes sense to have no non-canonical route at all. Even if sidebar would include only canonical url, it still might be linked manually, making Google still index it

**Comment by lex111** [comment]
Fine, thus, for example, the document id of `introduction`  is set as the docs home page (`homePageId: 'introduction'`), then the route for it will not be generated (`docs/introduction`), and its contents will be available by the docs home page route (`/docs`).
I will try to ship it to the next release.
