### ISSUE TITLE
Pages don't pick up HTML files in 2.0

### ISSUE THREAD

**Issue by apsdehal** [facebook/docusaurus#2833]
## 🐛 Bug Report

`@docusaurus/plugin-content-pages` doesn't pick up HTML pages in 2.x.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)? Yes

(Write your answer here.)

## To Reproduce

1. Create a new website using Facebook template.
2. Create a folder under `src/pages`, let's say `api`
3. Create a new file under `src/pages/api`  index.html and fill it with dummy HTML and lorem ipsum text.
4. Build the website

## Expected behavior

Like in 1.0, the plugin should pick up html pages.

(Write what you thought would happen.)

## Actual Behavior

404, didn't pick up the html file.

## Your Environment

- Docusaurus version used:2.0.0-alpha.56
- Environment name and version (e.g. Chrome 78.0.3904.108, Node.js 10.17.0): Node version: v12.17.0
- Operating system and version (desktop or mobile): Ubuntu 16.04

**Comment by yangshun** [comment]
I think we missed porting this feature to v2. We currently only look at JS files. Ideally we support both markdown and JS files for the pages plugin.

**Comment by apsdehal** [comment]
Is there a way around this? I am trying to replicate BoTorch's setup with Sphinx API docs. This is a requirement for doing that.

**Comment by yangshun** [comment]
If those pages are entirely standalone, you could add them to the `static` folder and serve them as static files.

**Comment by lex111** [comment]
Since we removed the `useLogo` hook (see #3730), this issue is no longer relevant, so I'm closing it.
