### ISSUE TITLE
docs: update ZEIT to Vercel

### ISSUE THREAD

**Issue by yangshun** [facebook/docusaurus#2834]
## 📚 Documentation

ZEIT has been renamed to Vercel, and [ZEIT Now](https://zeit.co/now) seems to now be the core offering of [Vercel](https://vercel.com/).

We need to update the [instructions](https://v2.docusaurus.io/docs/deployment/#deploying-to-zeit-now ) related to deploying to ZEIT Now/Vercel service. 

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

**Comment by Nishikoh** [comment]
Hi! I'll try to tackle that :)

**Comment by yangshun** [comment]
Sure thing, thank you!
