### ISSUE TITLE
Sidebar hidden when using new docs `homePageId` feature

### ISSUE THREAD

**Issue by aeneasr** [facebook/docusaurus#2836]
## 🐛 Bug Report

The sidebar is hidden when I'm at the page for `homePageId`.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## To Reproduce

Happy to provide an example if required.

## Expected behavior

I would like to have the sidebar shown when browsing the Docs homepage.

## Actual Behavior

The sidebar is not shown

## Your Environment

- Docusaurus version used: `2.0.0-alpha.56`
- Environment name and version (e.g. Chrome 78.0.3904.108, Node.js 10.17.0): all
- Operating system and version (desktop or mobile): all

## Reproducible Demo

Happy to provide if required

**Comment by lex111** [comment]
If you use reserved doc id for this feature, then this is intentional behavior (see https://github.com/facebook/docusaurus/pull/2785)
If this is not your case, we need a reproducible repo/demo.

**Comment by aeneasr** [comment]
Ok I see, so if I was to rename this to e.g. `"homePageId": "index"` this should work - I'll try that out!
