### ISSUE TITLE
alpha.56 broke theme-search-algolia

### ISSUE THREAD

**Issue by aeneasr** [facebook/docusaurus#2837]
## 🐛 Bug Report

The new `require.resolve` requirement broke `theme-search-algolia`. The docs do no longer start:

```
./node_modules/@docusaurus/theme-search-algolia/src/theme/SearchBar/index.js
Module not found: Can't resolve './styles.css' in '/Users/x/go/src/github.com/ory/kratos/docs/node_modules/@docusaurus/theme-search-algolia/src/theme/SearchBar'
```

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

yes

## To Reproduce

_docusaurus.config.js_

```
  themes: [
    [
      require.resolve("@docusaurus/theme-classic"),
    ], [
      require.resolve("@docusaurus/theme-search-algolia")
    ]
  ],
```

_package.json_

```

  "dependencies": {
    "@docusaurus/core": "2.0.0-alpha.56",
    "@docusaurus/preset-classic": "2.0.0-alpha.56",
    "classnames": "2.2.6",
    "mermaid": "^8.5.1",
    "node-fetch": "2.6.0",
    "react": "16.8.4",
    "react-dom": "16.8.4"
  },
  "devDependencies": {
    "json-schema-faker": "0.5.0-rcv.25",
    "json-schema-ref-parser": "8.0.0",
    "prettier": "2.0.2",
    "ramda": "0.27.0",
    "remark-admonitions": "1.2.1",
    "yaml": "1.8.3"
  }
```

## Expected behavior

It should not end in an error.

## Actual Behavior

```
./node_modules/@docusaurus/theme-search-algolia/src/theme/SearchBar/index.js
Module not found: Can't resolve './styles.css' in '/Users/x/go/src/github.com/ory/kratos/docs/node_modules/@docusaurus/theme-search-algolia/src/theme/SearchBar'
```

## Your Environment

- Docusaurus version used: 2.0.0-alpha.56
- Environment name and version (e.g. Chrome 78.0.3904.108, Node.js 10.17.0): all
- Operating system and version (desktop or mobile): all

## Reproducible Demo

Can create one upon request

**Comment by lex111** [comment]
`docusaurus/preset-classic` preset already includes Algolia, you do not need to declare it anywhere or in config life.

If you are not using classic preset, then you need to install all the necessary presets manually. From your snippets, I can't figure out what the error is. Please, whenever you create a bug report, give a link to a reproducible repo

**Comment by aeneasr** [comment]
Ah ok I see, that's what I kinda figured was happening, because `require` resolves transient / indirect dependencies very well while `require.resolve` doesn't. Thanks!

**Comment by aeneasr** [comment]
Nope, still an issue even when required directly. Here's a repro repo: https://github.com/ory/hydra/pull/1884

```
git clone git@github.com:ory/hydra.git
git checkout docusaurus56alpha
cd docs
npm i
npm start
```

**Comment by lex111** [comment]
>     "@docusaurus/theme-search-algolia": "^2.0.0-alpha.32",

Bump to .56 please, it is important.

**Comment by aeneasr** [comment]
Thank you, I included plugin-sitemap. For some reason, npm always adds `^2.0.0-alpha.32` per default for some reason. I bumped it now, also deleted `.docusaurus`, but the issue persists. :/

**Comment by lex111** [comment]
I have no errors when running `yarn start` :man_shrugging: .

**Comment by lex111** [comment]
Ha ha no problem!
