### ISSUE TITLE
Deployed links sometimes start in dark mode

### ISSUE THREAD

**Issue by oriooctopus** [facebook/docusaurus#2840]
## 🐛 Bug Report

On the first time a user has visited the staging link I have deployed, they sometimes see dark mode enabled

## To Reproduce

Go to this link https://lips.oriooctopus.now.sh/

Hopefully it shows you dark mode first. In the case of this site, we disabled dark mode in the config (I have temporarily reenabled it for demo purposes), but on another site where it is toggleable, users have reported having the site start on dark mode. This includes a situation where I deploy a new staging site with a fresh url, so I doubt the problem is a user setting it and then forgetting

## Expected behavior

The default theme (light/dark) should be consistent

**Comment by yangshun** [comment]
It repros for me - it does show dark mode first. I think we might be ignoring the website dark mode config before calling the match media.

Weird that https://draftjs.org/ also disabled dark mode and it works fine.

**Comment by lex111** [comment]
> I think that's because some users use dark mode as their system default theme. So the bug is that we might be ignoring the website dark mode config and still using the match media to query the user's system default theme and setting the theme based on that.

If dark mode is disabled, then we do not take into account user preferences at all.

The link https://lips.oriooctopus.now.sh/ shows that the dark mode is enabled, so if the end-user uses a dark system theme, then dark mode will be activated automatically on the site.
This is a normal behavior, so I do not understand what we need to fix in this case.

**Comment by oriooctopus** [comment]
That makes sense. I did not take into account that some users would have a dark mode system default
