### ISSUE TITLE
(v2) Automatic redirect of old docs

### ISSUE THREAD

**Issue by amimas** [facebook/docusaurus#2843]
## 🚀 Feature

Able to set redirect if docs are deleted or renamed.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## Motivation

As documentation evolves, it's normal for certain docs to become irrelevant. In that case that doc maybe deleted. It's also possible for docs markdown files to be renamed/restructured for better content organization.

This is an issue for SEO because now certain links are broken, if docs have to change. It can also break someone's bookmark.

It'd be very helpful if the generated site can redirect to the new url with a proper redirect status code, if there are cases where docs structure have to change.

## Pitch

One possible implementation comes to mind is providing additional configuration. This new config file will contain an array of objects that has reference to old url and new url. This will need to be populated by the maintainer. Docusaurus will generate an empty html file for the old url at that location, which will redirect to the new url. The config could have additional option so that the redirect happens instantly or after a few seconds so that end user is made aware of url changes.

This will help keep the seo ranking of the old url and also won't cause broken site.

**Comment by lex111** [comment]
@slorber is it possible to take this into account in the redirect plugin that you are developing?

**Comment by slorber** [comment]
@lex111 yes that should be covered:

```tsx
    [
      '@docusaurus/plugin-client-redirects',
      {
        createRedirects: (path) => {
           if ( path === "/newDocPath"
           return ["/oldDocPath" ,"legacyDocPath"];
        },
      },
    ],
```

@amimas check this PR:

https://github.com/facebook/docusaurus/pull/2793

> It'd be very helpful if the generated site can redirect to the new url with a proper redirect status code, if there are cases where docs structure have to change.

Server-side redirects would require deeper integration with the hosting provider, and as far as I know we don't want to do that (+ it's simply not possible on some providers like github pages etc).

You can do server redirects yourself with hosting provider config (for example _redirects in Netlify, now.json on Vercel etc...)

> The config could have additional option so that the redirect happens instantly or after a few seconds so that end user is made aware of url changes.

Currently we didn't implement any delay in the redirection, do you think this is really important?

**Comment by amimas** [comment]
Thanks @slorber  for the info.

I haven't spent enough time on the changes of that PR or that plugin code. I only reviewed it quickly. It looked like the `cleanUrl` feature from the V1.

I understand your point about server side redirect. Yes, we can't set 301 status code on the "old doc". But I think javascript redirect from old doc to new doc will still be useful. Below is an article from a test on this topic. Looks like Google search is now able to consume javascript redirect and adjust ranking/index accordingly.

https://www.merkleinc.com/blog/how-well-does-google-crawl-javascript-pretty-darn-well

I think this would be very useful because it'll simplify dealing with docs structure change a lot easier. That's why I was suggesting creating html file for the old doc with necessary redirect to the new doc (relative redirect).

As for delay for redirect, it's probably not critical but I can see how it can useful in some cases.

**Comment by slorber** [comment]
@amimas , the doc of the plugin is here:
https://deploy-preview-2793--docusaurus-2.netlify.app/docs/next/using-plugins#docusaurusplugin-client-redirects

It's not totally clear to me: do you think it covers your need, or you see something missing?

> As for delay for redirect, it's probably not critical but I can see how it can useful in some cases.

If it's not something that someone can express a concrete usecase for this delay, I think we should not add it. Afaik it has not been requested before.

**Comment by amimas** [comment]
Hi @slorber  - thanks for the link to the doc. It seems very useful and I think it covers the redirect I'm referring to in this feature request.

As for the option to be able to add delay to the redirect, I will leave it to others to chime in. I don't think it's critical/blocker. I might not even use it. I only brought it up as a suggestion.

Just a thought about that plugin's implementation. In the current form, would it be possible for me to setup a redirect based on regular expression? For example, if an entire directory structure has has changed (i.e. moved everything from `docs/dir1` to `docs/category1/dir1`), maybe a regex based redirect instead of manually declaring every redirect?

**Comment by slorber** [comment]
Hi @amimas 

The `createRedirects` option should cover your need:

```js
[
  "@docusaurus/plugin-client-redirects",
  {
    createRedirects: path => {
      if ( path.startsWith("/docs/dir1") ) {
        return [path.replace("/docs/dir1","/docs/dir1/category1")];
      }
    }
  }
];
```

**Comment by Guddu0799** [comment]
Hello! 
The redirect link is not working for me. Please help

I tried with both code and it didn't worked. I don't know what mistake I am doing.
<img width="398" alt="image" src="https://user-images.githubusercontent.com/108795464/220376186-50f58fde-7c3a-4aad-abc6-31b203d108d9.png">

<img width="370" alt="image" src="https://user-images.githubusercontent.com/108795464/220376566-2a63b061-403f-461a-9723-655af991735e.png">

<img width="947" alt="image" src="https://user-images.githubusercontent.com/108795464/220375933-b53a0e85-cb29-488d-a483-910719208dca.png">
