### ISSUE TITLE
deployment failure (but local serving works)

### ISSUE THREAD

**Issue by pdimens** [facebook/docusaurus#2847]
## 🐛 Bug Report

(A clear and concise description of what the bug is)
Local serving with `yarn start` works fine and shows everything, but when deploying to `gh-pages` using `GIT_USER=pdimens USE_SSH=true yarn deploy`, the result is a broken site without css formatting, broken images, incorrect links.
### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

yes

## To Reproduce
 `GIT_USER=pdimens USE_SSH=true yarn deploy` in the directory of https://github.com/pdimens/PopGen.jl/tree/documentation

## Expected behavior

![image](https://user-images.githubusercontent.com/19176506/83335104-03158400-a270-11ea-8341-8d85e59f9885.png)
![image](https://user-images.githubusercontent.com/19176506/83335108-0c065580-a270-11ea-8620-2c1fa6b08427.png)

## Actual Behavior

![image](https://user-images.githubusercontent.com/19176506/83335115-19234480-a270-11ea-8982-14b38696a73d.png)

![image](https://user-images.githubusercontent.com/19176506/83335121-23ddd980-a270-11ea-95f8-d112c31bf7d8.png)

## Your Environment

- Docusaurus version used: 2.0.0-alpha.56
- Environment name and version (e.g. Chrome 78.0.3904.108, Node.js 10.17.0): Node 14.2.0
- Operating system and version (desktop or mobile): Desktop Arch Linux

## Reproducible Demo
`docusaurus.config.js` file: https://github.com/pdimens/PopGen.jl/blob/documentation/docusaurus.config.js

**Comment by yangshun** [comment]
Since your final URL is https://pdimens.github.io/PopGen.jl/, you need to set `baseUrl` to be `/PopGen.jl/` in `docusaurus.config.js`.
