### ISSUE TITLE
docusaurus start fails on Linux environment with only Chromium and Brave

### ISSUE THREAD

**Issue by bradsk88** [facebook/docusaurus#2848]
## 🐛 Bug Report

When I attempt to run `docusaurus start` as an npm script on my machine, I'm met with the following error message:
```
$ docusaurus start
Starting the development server...

● Client █████████████████████████ compiling (0%)  
 

ℹ ｢wds｣: Project is running at http://localhost:3000/
ℹ ｢wds｣: webpack output is served from /
ℹ ｢wds｣: Content not from webpack is served from /home/bradsk88/Projects/developers.home-assistant
ℹ ｢wds｣: 404s will fallback to /index.html
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: spawn /usr/bin/firefox ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:246:12)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## To Reproduce

(Write your steps here:)

1. Install Manjaro Linux OS.  Install Chromium and Brave browser.  Uninstall Firefox.
1. Check out the [home assistant developer docs Github project](https://github.com/home-assistant/developers.home-assistant)
1. Run npm install
1. Run npm run start (which triggers docusaurus start)

## Expected behavior

Should launch Chromium or Brave, or show a message indicating that a supported browser was not found.

## Actual Behavior

An error is output: `Error: spawn /usr/bin/firefox ENOENT`

## Your Environment

- Docusaurus version used: 2.0.0 Alpha 56
- Environment name and version (e.g. Chrome 78.0.3904.108, Node.js 10.17.0): Brave Browser 81.1.10.60, Node.js v10.20.1
- Operating system and version (desktop or mobile): Manjaro (Kernel version 5.4.40-1-+MANJARO)

## Reproducible Demo

https://github.com/home-assistant/developers.home-assistant

### Workaround Steps

This bug can be worked around on linux by adding a symbolic link to "pretend" that you have firefox installed

```
ln -s /usr/bin/brave /usr/bin/firefox
```

**Comment by lex111** [comment]
Use `npm run start --no-open` command as workaround, apparently this error is related to https://github.com/sindresorhus/open

**Comment by lex111** [comment]
After a bit of investigate, I found out that it is possible to set the `BROWSER` environment variable so you can use it in npm script like this:

```
export BROWSER=chrome npm run start
```

But I am closing this issue because there is insufficient data to further fix it.
