### ISSUE TITLE
Importing md file to homepage should use md settings

### ISSUE THREAD

**Issue by klis87** [facebook/docusaurus#2849]
## 🚀 Feature

When importing md/mdx file to React components, like in homepage, it would be cool to use md settings which are used in docs.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## Motivation

Imagine I have 
```js
    prism: {
      theme: require('prism-react-renderer/themes/nightOwl'),
    },
```
in `docusaurus.config.js` file.

Now lets say I do `import Motivation from '../../docs/getting-started/motivation.md';` in `src/pages/index.js`. I can use this as `<Motivation />` component, but unfortunately this won't use `nightOwl` theme. Not sure about other things, but for now I checked that theme is not picked up.

## Pitch

Often it would be nice to reuse md files in single pages, like homepage, about etc. Importing them is possible, but for consistency it would be great to have the same appearance like for docs pages.

**Comment by yangshun** [comment]
This will be probably be tackled as part of https://github.com/facebook/docusaurus/issues/2882

**Comment by klis87** [comment]
@yangshun ok thx! so if you would like, we could close this issue, I will observe #2882
