### ISSUE TITLE
can use relative image path?

### ISSUE THREAD

**Issue by banli17** [facebook/docusaurus#2850]
## ❓ Questions and Help

i make a dir    /doc/imgs/  directory,   and doc/1.md  link  a image:

```
[](imgs/1.png)
```
but it not work , i see npm run build result, the imgs director does not copy to。

**Comment by fanny** [comment]
You can try use the `static` folder. Check out our [doc - static assets](https://v2.docusaurus.io/docs/static-assets)

**Comment by banli17** [comment]
it's not very convenient，may below is ok
```
- docs
    - ios
        - imgs
       -  x.md
       - y.md
    - android
       - imgs
      - x.md
      - y.md
```

**Comment by yangshun** [comment]
Alternatively you can use `<img src={require('relative/path/to/image')}>`. Putting the docs relative path there wouldn't work because the paths aren't processed by our Markdown parser and the images within the docs directories aren't copied into the `build` folder, so the paths will be referencing a non-existent file.

**Comment by adrianmcli** [comment]
Why can't we colocate our images with the Markdown files they belong to?

This means that I can't use the regular Markdown syntax for images (`![hello](./myImage.png)`) unless I put every image in the `static` folder? This is not very scalable if my docs site has many screenshot-heavy tutorials.

**Comment by slorber** [comment]
=> https://github.com/facebook/docusaurus/issues/3057

we should make this possible

**Comment by slorber** [comment]
Hey all,  this is feature is now released!
If you like it, don't forget to retweet 😄 
https://twitter.com/docusaurus/status/1286715187983048704

**Comment by gazcn007** [comment]
@slorber this is awesome! retweeted :)
