### ISSUE TITLE
Css is not loading properly in build 

### ISSUE THREAD

**Issue by alexakasanjeev** [facebook/docusaurus#2853]
## 🐛 Bug Report

I want to deploy the build folder, but the build folder css is all messed up. The pages has no styling. When I'm running in `development` mode the pages are loading fine, but in `build` mode, pages are not loading properly. Please see attached photos 

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?
Yes

## To Reproduce

1. Clone the repo
 `git clone https://github.com/react-native-bootstrap/react-native-bootstrap`
2. cd into website folder
`cd website`
3. Start development server and see website is working fine
`yarn start`
4. Not build the static website & open `index.html` in build folder
`yarn build`
 
## Expected behavior

The website should have looked like this

![Screenshot_2020-05-31 React Native Bootstrap React Native Bootstrap(1)](https://user-images.githubusercontent.com/13250741/83359643-2e47c280-a399-11ea-90eb-b7bda24b21df.png)

Running `index.html` file from build folder should have worked fine, so that I can deploy it on github pages

## Actual Behavior

Website looks like this after deploying build folder in `gh-pages`

![Screenshot_2020-05-31 React Native Bootstrap React Native Bootstrap](https://user-images.githubusercontent.com/13250741/83359639-212ad380-a399-11ea-8a53-3585d355e984.png)

## Your Environment

- Docusaurus version used: 2.0.0-alpha.56
- Firefox 76.0.1 (64-bit)
- Node.js v10.15.3
- Operating system and version (desktop or mobile): Ubuntu 18.04 

## Reproducible Demo

The entire code is present here https://github.com/react-native-bootstrap/react-native-bootstrap/tree/master/website

**Comment by yangshun** [comment]
Make sure the baseUrl in docusaurus.config.js is not empty if your website
has one.

**Comment by alexakasanjeev** [comment]
Hi @yangshun I don't have a website, I just want to deploy the website on github pages at url `react-native-boostrap.io`, could you help me with configuration

**Comment by yangshun** [comment]
You need a CNAME file as well in `static` with the contents `react-native-boostrap.io`

**Comment by alexakasanjeev** [comment]
@yangshun I ran `yarn deploy` it created a build folder at my local computer, I'm trying to run `index.html` file from that local build folder, that is also not rendering properly, you can see yourself, i have provided the repo.

Also I tried, creating a CNAME file in static folder, and redeploying it, still same effect

**Comment by yangshun** [comment]
Are you using a local webserver to run the files? You can start one using Python. If you just double click and open the files it would not work.

**Comment by alexakasanjeev** [comment]
No I just opened the `index.html file` on browser

Ok I understand it won't work without local server, but why it is not working on github pages, I have created a CNAME file in static folder whose content is `react-native-bootstrap.io`

and this is my **docusaurus.config.js**

```js
module.exports = {
  title: 'React Native Bootstrap',
  tagline: 'Bootstrap components built for React Native',
  url: 'https://react-native-bootstrap.github.io',
  baseUrl: '/',
  favicon: 'img/rnb.png',
  organizationName: 'react-native-bootstrap', // Usually your GitHub org/user name.
  projectName: 'react-native-bootstrap', // Usually your repo name.
  themeConfig: { ...}
};

**Comment by yangshun** [comment]
Did you enable GitHub pages from your repo settings?

**Comment by alexakasanjeev** [comment]
![Screenshot from 2020-06-01 13-57-02](https://user-images.githubusercontent.com/13250741/83390646-dac48b80-a40f-11ea-86a4-77244a5ec85b.png)

**Comment by tsuz** [comment]
Just FYI, I couldn't touch the CNAME so I resolved this by setting `--out-dir` in [`docusaurus build`](https://v2.docusaurus.io/docs/cli/#docusaurus-build). The command was

```
yarn build --out-dir build/<subdirectory>
```

**Comment by Tesla-Atoz** [comment]
> 
> 
> ![Screenshot from 2020-06-01 13-57-02](https://user-images.githubusercontent.com/13250741/83390646-dac48b80-a40f-11ea-86a4-77244a5ec85b.png)

You need to use CNAME file only if you have custom domain linked to your website. If there is no such thing, then configuring package.json file would work fine.

**Comment by iamadityac** [comment]
Hi @sanjeevyadavIT ,

I have the same issue as you,
Have you got any solution to it?

Also Just want to know, After running `yarn build` can we run a static website through a browser without running any server?

**Comment by Tesla-Atoz** [comment]
> 
> 
> Hi @sanjeevyadavIT ,
> 
> I have the same issue as you,
> Have you got any solution to it?
> 
> Also Just want to know, After running `yarn build` can we run a static website through a browser without running any server?

Hello @iamadityac 

yes, it is possible to run a static website through a browser. 
Also mention your problem clearly so we can help u

**Comment by jnikhila** [comment]
I am also facing the same issue. When I use npm start or box docusurus start the localhost:3000 shows the css rendering. However, when I do nom run build followed by nom run serve the css is not rendering. Could you please help with this?

**Comment by slorber** [comment]
It is impossible to help without seeing your live site with the exact URL it's being served on. 

As stated above it is likely a baseUrl configuration issue, but can be many different things in practice

**Comment by dtcMLOps** [comment]
I have the same problem

**Comment by Cristy94** [comment]
I have the same problem, npm start shows correct css, on build it looks like this.
There are no JS or network errors live.

## Local:

![Image](https://github.com/user-attachments/assets/16b01c9a-8082-4737-a161-1f9861dfa57a)

## Live:

![Image](https://github.com/user-attachments/assets/103d3b79-6707-42dc-9700-9a74654421d9)

**Comment by Cristy94** [comment]
Fixed it by setting this in the config:

```
  future: {
    v4: true,
    experimental_faster: true, <-- ADDED THIS
  },
```

Added some details regarding [CSS not loading on Docosaurus 3.8 here](https://softuts.com/css-not-loading-docusaurus-3-8/).

**Comment by AymaneHrouch** [comment]
@Cristy94 Thank you so much for sharing!!

**Comment by slorber** [comment]
It is unlikely that `experimental_faster: true` fixes such CSS error. If you see that happening, this may hide a deeper problem. Please submit a runnable repro so that we can take a look.

**Comment by AymaneHrouch** [comment]
Hello @slorber,

The error comes from running "npx create-docusaurus@latest my-website classic", without any changes other than updating the config to deploy.

I have pushed a repository that has this error so you can check: https://github.com/AymaneHrouch/docusaurus-website
it's deployed here: https://aymanehrouch.github.io/docusaurus-website/

Thanks

**Comment by slorber** [comment]
Thanks @AymaneHrouch , that's really weird because your GitHub Actions deployment doesn't contain any of the CSS rules of our Infima.dev CSS framework 🤔 

Are you able to reproduce this locally too? Or does it only happen when deploying to GitHub pages?

How did you configure your GitHub Pages deployment?

**Comment by AymaneHrouch** [comment]
Hello @slorber, it does happen in my local when I do `npm run build` then `npm run serve`, but with `npm start` it works normally.

For the Github Pages deployment I created an empty branch using these steps:

```bash
git checkout --orphan gh-pages
git rm -rf .
echo "Initial gh-pages branch" > README.md
git add README.md
git commit -m "Initialize gh-pages branch"
git push origin gh-pages
```

and deployed using `GIT_USER=aymanehrouch npm run deploy`

**Comment by slorber** [comment]
@AymaneHrouch I can't reproduce this. Maybe it's something on your env that produces the bug, but hard to know what exactly (specific node version, npm version, OS, unusual setup...). Maybe try running the same thing on another computer and see if you can still reproduce?

**Comment by AymaneHrouch** [comment]
@slorber I tried it in my other computer and couldn't reproduce it as well. The only thing I have figured out is that the issue is coming from the .css file, I copied the css file content from my working machine to the machine with the bug, and the issue disappeared! 

You can check in [this link](https://www.diffchecker.com/4lJiu8oP/) the two css files, the working one is the one on the left. I hope this can give you some insights.

I tried different npm and node versions, tried the same versions on both computers, nothing worked.
The working machine is an Ubuntu 24.04.1 LTS.
The machine with bug is a Windows 11.

**Comment by MohammadArk96** [comment]
i am facing this issue too with windows 11, can you tell me which css file is the problem? and where to find the correct one ?

**Comment by AymaneHrouch** [comment]
@MohammadArk96 as a workaround you can use [this solution above](https://github.com/facebook/docusaurus/issues/2853#issuecomment-2925323487) it worked fine for me.

**Comment by slorber** [comment]
This is weird.

Can you try to init a site with older versions of Docusaurus?

```
npm init docusaurus@3.7.0

npm init docusaurus@3.6.3
```

Can you try on 3.8 with the `siteConfig.v4 = false` flag? This might be related to CSS cascade layers https://docusaurus.io/blog/releases/3.8#css-cascade-layers

Maybe this only happens on Windows, are you both on Windows?

**Comment by AymaneHrouch** [comment]
Hello @slorber 

the two versions you mentioned work perfectly fine (on Windows). 

> Can you try on 3.8 with the siteConfig.v4 = false flag? 

I'm not sure I understand what you mean, if you mean like this
```js
  future: {
    v4: false, // Improve compatibility with the upcoming Docusaurus v4
  }
```

when I try it it doesn't build and give me a long error, see below the head of the error:

![Image](https://github.com/user-attachments/assets/49ebfdef-c561-49a9-a568-a138474d114c)

**Comment by MohammadArk96** [comment]
I had this issue fixed by setting v4 to false
    v4: false, // Improve compatibility with the upcoming Docusaurus v4


and downgrading nodejs to v20.14.0

**Comment by slorber** [comment]
@AymaneHrouch can you please create a repro? If you have a `my-website/postcss.config.js`, it's quite hard for me to troubleshoot anything without seeing the whole setup. Your [Docusaurs repro here](https://github.com/AymaneHrouch/docusaurus-website) doesn't contain this file and doesn't contain any reference to "private medical insurance" so I guess it's not the repro that produced that error message. That's probably a different issue. Can you create a new issue dedicated issue so that we can investigate that problem separately?

---

Thanks @MohammadArk96. Can you just turn off CSS Cascade Layers and keep the former Node.js version?

For example use Node 22/24 with:

```js
    future: {
      v4: {
        useCssCascadeLayers: false,
        removeLegacyPostBuildHeadAttribute: true,
      },
   }
```

This problem looks related to using CSS Cascade Layers for Windows users. It's not really the same issue as the original one (CSS is not loading), but rather a new issue (CSS is loading, but it doesn't contain the expected CSS rules). This is probably related to posix paths vs Windows paths, I'll look into it asap.

**Comment by mukhtarrex12** [comment]
> [@AymaneHrouch](https://github.com/AymaneHrouch)можете ли вы создать репродукцию? Если у вас есть `my-website/postcss.config.js`, мне довольно сложно устранять неполадки, не видя всей настройки. Ваша [репродукция Docusaurs здесь](https://github.com/AymaneHrouch/docusaurus-website) не содержит этого файла и не содержит никаких ссылок на «частное медицинское страхование», поэтому я полагаю, что это не репродукция выдала это сообщение об ошибке. Вероятно, это другая проблема. Можете ли вы создать новую специализированную проблему, чтобы мы могли исследовать эту проблему отдельно?
> 
> Спасибо[@MohammadArk96](https://github.com/MohammadArk96). Можно ли просто отключить каскадные слои CSS и оставить прежнюю версию Node.js?
> 
> Например, используйте узел 22/24 с:
> 
>     future: {
>       v4: {
>         useCssCascadeLayers: false,
>         removeLegacyPostBuildHeadAttribute: true,
>       },
>    }
> Эта проблема, похоже, связана с использованием каскадных слоев CSS для пользователей Windows. Это не совсем та же проблема, что и исходная (CSS не загружается), а скорее новая проблема (CSS загружается, но не содержит ожидаемых правил CSS). Вероятно, это связано с путями posix и путями Windows, я разберусь с этим как можно скорее.

Today, I installed version 3.8.0 for the first time and encountered missing styles in Docusaurus on Windows 11. I needed to deploy this application on Windows Server 2019 IIS, where this issue persisted. Your solution restored the styles to working condition.

**Comment by samchan6** [comment]
I encounter a similar problem as well, in which the hot reload in `npm start` works fine. But when I do `npm build` and serve the files through an express server, it gives undesirable styling as well. It is able to retain the `src/css/custom.css` content, but not the base css.

It would be missing some variables from the `:root` like `--ifm-font-size-base: 100%;`, causing the 
```css

html {
 ....
    font: var(--ifm-font-size-base) / var(--ifm-line-height-base) var(--ifm-font-family-base);
}
```

to be using undefined var, and my fonts are not displaying properly.


I am running the hot reload and express server method both on Win 11 local, with the later trying to simulate production deployment.

I have tried the solution of adding the `experimental_fast: true`, and it works.
I also tried the 
```
    v4: {
      useCssCascadeLayers: false,
      removeLegacyPostBuildHeadAttribute: true
    },
```
which also works.

I would like to know why and what the best practice is now.

**Comment by slorber** [comment]
I was able to get a Windows laptop, and also added a new Windows CI job that reproduces the problem (https://github.com/facebook/docusaurus/pull/11231)

In both cases, I get a CSS minimizer console warning. Do you also get it?


```
Warning:  {"file":"assets/css/styles.fa270c62.css","message":"assets/css/styles.fa270c62.css from Css Minimizer plugin\nInvalid character(s) '0 2px 4px 0 #0000001a;--ifm-z-index-dropdown:100;--ifm-z-index-fixed:200;--ifm-z-index-overlay:400;--ifm-container-width:1140px;--ifm-container-width-xl:1320px;--ifm-code-background:#f6f7f8;--ifm-code-border-radius:var(--ifm-global-radius);--ifm-code-font-size:90%;--ifm-code-padding-horizontal:0.1rem;--ifm-code-padding-vertical:0.1rem;--ifm-pre-background:var(--ifm-code-background);--ifm-pre-border-radius:var(--ifm-code-border-radius);--ifm-pre-color:inherit;--ifm-pre-line-height:1.45;--ifm-pre-padding:1rem;--ifm-heading-color:inherit;--ifm-heading-margin-top:0;--ifm-heading-margin-bottom:var(--ifm-spacing-vertical);--ifm-heading-font-family:var(--ifm-font-family-base);--ifm-heading-font-weight:var(--ifm-font-weight-bold);--ifm-heading-line-height:1.25;--ifm-h1-font-size:2rem;--ifm-h2-font-size:1.5rem;--ifm-h3-font-size:1.25rem;--ifm-h4-font-size:1rem;--ifm-h5-font-size:0.875rem;--ifm-h6-font-size:0.85rem;--ifm-image-alignment-padding:1.25rem;--ifm-leading-desktop:1.25;--ifm-leading:calc(var(--ifm-leading-desktop)*1rem);--ifm-list-left-padding:2rem;--ifm-list-margin:1rem;--ifm-list-item-margin:0.25rem;--ifm-list-paragraph-margin:1rem;--ifm-table-cell-padding:0.75rem;--ifm-table-background:#0000;--ifm-table-stripe-background:#00000008;--ifm-table-border-width:1px;--ifm-table-border-color:var(--ifm-color-emphasis-300);--ifm-table-head-background:inherit;--ifm-table-head-color:inherit;--ifm-table-head-font-weight:var(--ifm-font-weight-bold);--ifm-table-cell-color:inherit;--ifm-link-color:var(--ifm-color-primary);--ifm-link-decoration:none;--ifm-link-hover-color:var(--ifm-link-color);--ifm-link-hover-decoration:underline;--ifm-paragraph-margin-bottom:var(--ifm-leading);--ifm-blockquote-font-size:var(--ifm-font-size-base);--ifm-blockquote-border-left-width:2px;--ifm-blockquote-padding-horizontal:var(--ifm-spacing-horizontal);--ifm-blockquote-padding-vertical:0;--ifm-blockquote-shadow:none;--ifm-blockquote-color:var(--ifm-color-emphasis-800);--ifm-blockquote-border-color:var(--ifm-color-emphasis-300);--ifm-hr-background-color:var(--ifm-color-emphasis-500);--ifm-hr-height:1px;--ifm-hr-margin-vertical:1.5rem;--ifm-scrollbar-size:7px;--ifm-scrollbar-track-background-color:#f1f1f1;--ifm-scrollbar-thumb-background-color:silver;--ifm-scrollbar-thumb-hover-background-color:#a7a7a7;--ifm-alert-background-color:inherit;--ifm-alert-border-color:inherit;--ifm-alert-border-radius:var(--ifm-global-radius);--ifm-alert-border-width:0px;--ifm-alert-border-left-width:5px;--ifm-alert-color:var(--ifm-font-color-base);--ifm-alert-padding-horizontal:var(--ifm-spacing-horizontal);--ifm-alert-padding-vertical:var(--ifm-spacing-vertical);--ifm-alert-shadow:var(--ifm-global-shadow-lw);--ifm-avatar-intro-margin:1rem;--ifm-avatar-intro-alignment:inherit;--ifm-avatar-photo-size:3rem;--ifm-badge-background-color:inherit;--ifm-badge-border-color:inherit;--ifm-badge-border-radius:var(--ifm-global-radius);--ifm-badge-border-width:var(--ifm-global-border-width);--ifm-badge-color:var(--ifm-color-white);--ifm-badge-padding-horizontal:calc(var(--ifm-spacing-horizontal)*0.5);--ifm-badge-padding-vertical:calc(var(--ifm-spacing-vertical)*0.25);--ifm-breadcrumb-border-radius:1.5rem;--ifm-breadcrumb-spacing:0.5rem;--ifm-breadcrumb-color-active:var(--ifm-color-primary);--ifm-breadcrumb-item-background-active:var(--ifm-hover-overlay);--ifm-breadcrumb-padding-horizontal:0.8rem;--ifm-breadcrumb-padding-vertical:0.4rem;--ifm-breadcrumb-size-multiplier:1;--ifm-breadcrumb-separator:url('data:image/svg+xml;utf8,<svg xmlns=\"[http://www.w3.org/2000/svg\](http://www.w3.org/2000/svg/)" x=\"0px\" y=\"0px\" viewBox=\"0 0 256 256\"><g><g><polygon points=\"79.093,0 48.907,30.187 146.72,128 48.907,225.813 79.093,256 207.093,128\"/></g></g><g></g><g></g><g></g><g></g><g></g><g></g><g></g><g></g><g></g><g></g><g></g><g></g><g></g><g></g><g></g></svg>');--ifm-breadcrumb-separator-filter:none;--ifm-breadcrumb-separator-size:0.5rem;--ifm-breadcrumb-separator-size-multiplier:1.25;--ifm-button-background-color:inherit;--ifm-button-border-color:var(--ifm-button-background-color);--ifm-button-border-width:var(--ifm-global-border-width);--ifm-button-color:var(--ifm-font-color-base-inverse);--ifm-button-font-weight:var(--ifm-font-weight-bold);--ifm-button-padding-horizontal:1.5rem;--ifm-button-padding-vertical:0.375rem;--ifm-button-size-multiplier:1;--ifm-button-transition-duration:var(--ifm-transition-fast);--ifm-button-border-radius:calc(var(--ifm-global-radius)*var(--ifm-button-size-multiplier));--ifm-button-group-spacing:2px;--ifm-card-background-color:var(--ifm-background-surface-color);--ifm-card-border-radius:calc(var(--ifm-global-radius)*2);--ifm-card-horizontal-spacing:var(--ifm-global-spacing);--ifm-card-vertical-spacing:var(--ifm-global-spacing);--ifm-toc-border-color:var(--ifm-color-emphasis-300);--ifm-toc-link-color:var(--ifm-color-content-secondary);--ifm-toc-padding-vertical:0.5rem;--ifm-toc-padding-horizontal:0.5rem;--ifm-dropdown-background-color:var(--ifm-background-surface-color);--ifm-dropdown-font-weight:var(--ifm-font-weight-semibold);--ifm-dropdown-link-color:var(--ifm-font-color-base);--ifm-dropdown-hover-background-color:var(--ifm-hover-overlay);--ifm-footer-background-color:var(--ifm-color-emphasis-100);--ifm-footer-color:inherit;--ifm-footer-link-color:var(--ifm-color-emphasis-700);--ifm-footer-link-hover-color:var(--ifm-color-primary);--ifm-footer-link-horizontal-spacing:0.5rem;--ifm-footer-padding-horizontal:calc(var(--ifm-spacing-horizontal)*2);--ifm-footer-padding-vertical:calc(var(--ifm-spacing-vertical)*2);--ifm-footer-title-color:inherit;--ifm-footer-logo-max-width:min(30rem,90vw);--ifm-hero-background-color:var(--ifm-background-surface-color);--ifm-hero-text-color:var(--ifm-color-emphasis-800);--ifm-menu-color:var(--ifm-color-emphasis-700);--ifm-menu-color-active:var(--ifm-color-primary);--ifm-menu-color-background-active:var(--ifm-hover-overlay);--ifm-menu-color-background-hover:var(--ifm-hover-overlay);--ifm-menu-link-padding-horizontal:0.75rem;--ifm-menu-link-padding-vertical:0.375rem;--ifm-menu-link-sublist-icon:url('data:image/svg+xml;utf8,<svg xmlns=\"[http://www.w3.org/2000/svg\](http://www.w3.org/2000/svg/)" width=\"16px\" height=\"16px\" viewBox=\"0 0 24 24\"><path fill=\"rgba(0,0,0,0.5)\" d=\"M7.41 15.41L12 10.83l4.59 4.58L18 14l-6-6-6 6z\"></path></svg>');--ifm-menu-link-sublist-icon-filter:none;--ifm-navbar-background-color:var(--ifm-background-surface-color);--ifm-navbar-height:3.75rem;--ifm-navbar-item-padding-horizontal:0.75rem;--ifm-navbar-item-padding-vertical:0.25rem;--ifm-navbar-link-color:var(--ifm-font-color-base);--ifm-navbar-link-hover-color:var(--ifm-color-primary);--ifm-navbar-link-active-color:var(--ifm-link-color);--ifm-navbar-padding-horizontal:var(--ifm-spacing-horizontal);--ifm-navbar-padding-vertical:calc(var(--ifm-spacing-vertical)*0.5);--ifm-navbar-shadow:var(--ifm-global-shadow-lw);--ifm-navbar-search-input-background-color:var(--ifm-color-emphasis-200);--ifm-navbar-search-input-color:var(--ifm-color-emphasis-800);--ifm-navbar-search-input-placeholder-color:var(--ifm-color-emphasis-500);--ifm-navbar-search-input-icon:url('data:image/svg+xml;utf8,<svg fill=\"currentColor\" xmlns=\"[http://www.w3.org/2000/svg\](http://www.w3.org/2000/svg/)" viewBox=\"0 0 16 16\" height=\"16px\" width=\"16px\"><path d=\"M6.02945,10.20327a4.17382,4.17382,0,1,1,4.17382-4.17382A4.15609,4.15609,0,0,1,6.02945,10.20327Zm9.69195,4.2199L10.8989,9.59979A5.88021,5.88021,0,0,0,12.058,6.02856,6.00467,6.00467,0,1,0,9.59979,10.8989l4.82338,4.82338a.89729.89729,0,0,0,1.29912,0,.89749.89749,0,0,0-.00087-1.29909Z\" /></svg>');--ifm-navbar-sidebar-width:83vw;--ifm-pagination-border-radius:var(--ifm-global-radius);--ifm-pagination-color-active:var(--ifm-color-primary);--ifm-pagination-font-size:1rem;--ifm-pagination-item-active-background:var(--ifm-hover-overlay);--ifm-pagination-page-spacing:0.2em;--ifm-pagination-padding-horizontal:calc(var(--ifm-spacing-horizontal)*1);--ifm-pagination-padding-vertical:calc(var(--ifm-spacing-vertical)*0.25);--ifm-pagination-nav-border-radius:var(--ifm-global-radius);--ifm-pagination-nav-color-hover:var(--ifm-color-primary);--ifm-pills-color-active:var(--ifm-color-primary);--ifm-pills-color-background-active:var(--ifm-hover-overlay);--ifm-pills-spacing:0.125rem;--ifm-tabs-color:var(--ifm-font-color-secondary);--ifm-tabs-color-active:var(--ifm-color-primary);--ifm-tabs-color-active-border:var(--ifm-tabs-color-active);--ifm-tabs-padding-horizontal:1rem;--ifm-tabs-padding-vertical:1rem' at assets/css/styles.fa270c62.css:1:4933. Ignoring.","compilerPath":"client"}
```


---

Edit: The bug is related to clean-css that is unmaintained and discards `@layer` declarations.

https://github.com/clean-css/clean-css/issues/1272

It only happens on Windows due to a bug (no layer applied). By forcing the bug to happen on macOS, I can reproduce it locally. I'm looking at how to fix it, but it doesn't seem easy without plainly disabling clean-css.

Going to fix this in https://github.com/facebook/docusaurus/pull/11241 and release it in the next patch

**Comment by slorber** [comment]
CSS cascade layers bug on Windows fixed in the latest release https://github.com/facebook/docusaurus/releases/tag/v3.8.1

**Comment by surajsibi** [comment]
doing this works for me

 future: {
    v4: false, // Improve compatibility with the upcoming Docusaurus v4
  },

just turn it off
