### ISSUE TITLE
(v2) Can't enable light mode by default

### ISSUE THREAD

**Issue by EthanSK** [facebook/docusaurus#2871]
## 🐛 Bug Report

I cannot enable light mode by default, even though I have both 
`  disableDarkMode: false,
    defaultDarkMode: false
`
I have tried playing around with both options. No luck.

**Comment by lex111** [comment]
Can you provide more details? Demo or repo? Steps to reproduce?

**Comment by slorber** [comment]
Hi @EthanSK 

Can you also verify that your computer/browser does not indicate a color scheme preference? 

This per-user preference overrides the Docusaurus default.

You can know if you prefer the dark mode by running: `window.matchMedia('(prefers-color-scheme: dark)').matches `

**Comment by yangshun** [comment]
Please reopen after providing the repo steps. The issue templates were created to help us help you, please do not ignore it.

**Comment by EthanSK** [comment]
> window.matchMedia('(prefers-color-scheme: dark)').matches

Ah! Didn't even know this existed. My system theme was dark, so it was going dark despite `defaultDarkMode: false` or `disableDarkMode: true` in the docusaurus config. 

Maybe it might be confusing/unwanted behaviour to have this, because there is currently no way to enforce either a default theme, or a theme full stop.

For example, if my Mac's system settings are on dark mode, I cannot with the current system have it light by default, or light only (without the option to switch) I really think there should be more options in the docusaurus config to overwrite prefers-color-scheme, or just change the behaviour

**Comment by slorber** [comment]
@EthanSK I agree there's something not totally ok with current settings and some things might be impossible

What do you want exactly? You want to setup a default theme to light or dark (which one?), even if user has a default preference?

**Comment by EthanSK** [comment]
@slorber For me specifically, I would like to set up a default theme to light, even if the user has a default dark system preference.

But I can imagine some other people might want it the other way round - default to dark even if user has a default light system preference. 

I think the way it should be done is both `defaultDarkMode` and `disableDarkMode` should completely ignore the system preferences, and the developer has to explicitly enable somethnig like `prioritizeSystemTheme` to be able to use that.

**Comment by slorber** [comment]
@EthanSK  what do you think of this PR?

https://github.com/facebook/docusaurus/pull/2939

**Comment by EthanSK** [comment]
> @EthanSK what do you think of this PR?
> 
> #2939

lgtm, thanks!

**Comment by slorber** [comment]
Hey all,  this is feature is now released!
If you like it, don't forget to retweet 😄 
https://twitter.com/docusaurus/status/1286715187983048704
