### ISSUE TITLE
RFC: validate plugin options with Yup

### ISSUE THREAD

**Issue by slorber** [facebook/docusaurus#2878]
## 💥 Proposal

The client-redirects plugin uses Yup to validate user inputs. 

In case user options do not match what's expected by the plugin (and the TypeScript types), it fails fast with an actionable error message.

@lex111 mentioned [here](https://github.com/facebook/docusaurus/pull/2793#issuecomment-638387485) that this is not really consistent with the behavior of the other plugins that do not really validate the user options, and maybe we should revisit the development process of plugins to follow what has been done in the client redirects plugin.

I discussed this with @yangshun, and he liked the idea to validate user inputs early with Yup.

He proposed a `validateOptions()` plugin lifecycle, where the user could just provide a Yup schema.

We also need to think about "option normalization", ie the process of transforming partial user-provided options into a convenient option type (ie, often adding default values to "complete" the user object)

---

What do you think of this idea of generalizing user input validation everywhere?

**Comment by lex111** [comment]
I completely agree with this, maybe we should draw up some guidelines for the development of plugins (and not only for them).
