### ISSUE TITLE
Docs homepage bugs

### ISSUE THREAD

**Issue by slorber** [facebook/docusaurus#2879]
Hi,

This latest PR about docs homepage had some side-effects: https://github.com/facebook/docusaurus/pull/2861

- https://v2.docusaurus.io/docs/ has canonical url = https://v2.docusaurus.io/docs/introduction (which does not exist anymore, bad for SEO)
- this behavior conflicts with the new slug doc frontmatter (https://github.com/facebook/docusaurus/pull/2771)

Sites like Watchman have expressed the need to add `.html` extensions to their docs, this is why we created the slug frontmatter

For example, they want their first doc to be:
- https://facebook.github.io/watchman/docs/install.html 
instead of: 
- https://facebook.github.io/watchman/docs/install

The canonical url of such doc should be with html extension as well (as it's the url they had before, and they want to keep it)

----

**Question**: it's not clear to me what the behavior should be, if Watchman wants to use this "install" page as docs homepage, yet ensure that the canonical url of the page is, as requested, `https://facebook.github.io/watchman/docs/install.html`.

It could be safer to have a duplicate index page, with the canonical url being the one requested by the user with the `slug` option? 

We could redirect the /docs root to the canonical page

Or we could forbid the usage of a slug on the document root, considering that the canonical url is always `/docs` (sites like Watchman wouldn't be able to use document root)

--- 

@lex111 to handle the `/docs/introduction` -> `/docs` you asked me [here](https://github.com/facebook/docusaurus/pull/2793#issuecomment-638387485), I think we should figure out the final behavior we want first.

**Comment by lex111** [comment]
> https://v2.docusaurus.io/docs/ has canonical url = https://v2.docusaurus.io/docs/introduction (which does not exist anymore, bad for SEO)

Oh, good catch, this is really bad.


I actually don’t know which option is better. One of our users said that it is better to do without duplicating the page, or to set the canonical url, in the end I did the first one.

**Comment by lex111** [comment]
I guess this is no longer a relevant issue, so I will close it.
