### ISSUE TITLE
ReAligning the netlify logo

### ISSUE THREAD

**Issue by singhaditya28** [facebook/docusaurus#2881]
🚀 Feature
The current footer section of https://v2.docusaurus.io/ looks like this on the PC:-

![image](https://user-images.githubusercontent.com/66196917/83760598-ca701300-a692-11ea-957c-752378c8f42f.png)

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

**Yes**, I have read all the Guidelines for contributing and I agree upon those.

## Motivation

**I want to improve Docusaurus to my fullest** as I am a high-spirited open-source contributor and want to make more and more contributions so that I gain more and more knowledge from variety of projects.

## Pitch

Clearly, here, the netlify logo seems misaligned and awful. I know we cannot remove the link to their website but we can realign it to make our website look good to all the users. Below is the solution I want to add to Docusaurus so that it progresses with a better layout.

Below are the screenshots after I aligned the netlify logo over different devices:-

Laptop/PC:
![CaptureLaptop](https://user-images.githubusercontent.com/66196917/83761613-2edfa200-a694-11ea-8bf9-0e3e66550818.PNG)

Tablet/iPad:
![CaptureiPad](https://user-images.githubusercontent.com/66196917/83761702-47e85300-a694-11ea-983e-112508d294dd.PNG)

Android/iPhone:
![Capture](https://user-images.githubusercontent.com/66196917/83761768-5e8eaa00-a694-11ea-8c44-aadb8b0823db.PNG)

**Comment by slorber** [comment]
Hi,

Currently, the logo is a single field of the themeConfig:

```
      logo: {
        alt: 'Facebook Open Source Logo',
        src: 'img/oss_logo.png',
        href: 'https://opensource.facebook.com',
      },
```

We could accept an array, and rename the field to logos (with retro compatibility to `logos = [themeConfig.logo]`)

Do you want to write a PR, or is this issue a suggestion?

**Comment by yangshun** [comment]
Hmm I think this might go against our brand guidelines. cc @JoelMarcey

**Comment by singhaditya28** [comment]
> Hmm I think this might go against our brand guidelines. cc @JoelMarcey

Why @yangshun ? You want your advertisement, right? You surely want to appear it on the footer section as well , so, what is the problem in realigning it to a better place beside the official "FaceBook Open Source" icon. I'm not suggesting any removal of link to your website but just postioning the misaligned button. Hope you understand :smile:

**Comment by singhaditya28** [comment]
@slorber I surely want to create a PR. I am well versed with HTML5. So, can you modify the index.js file for the footer section if I provide you the HTML code?

**Comment by lex111** [comment]
In order to reduce staled issues, I am closing this issue, but feel free to open it again if needed.
