### ISSUE TITLE
Markdown support for pages

### ISSUE THREAD

**Issue by chaitanya1248** [facebook/docusaurus#2882]
## 🚀 Feature

Allow markdown support for pages.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

yes

## Motivation

I started trying out docusaurus v2 and it worked out great for technical documentation. Everyone on the team loved how clean it looks, easy to maintain. 

We would like to take one more step forward to add more useful info related to our app.

## Pitch

- Being able to use markdown eliminates the overhead styling and it is easier to maintain.

- non technical people on team can also contribute.

**Comment by slorber** [comment]
Hi,

So, to understand, you want to use MD/MDX for something else than docs/blog?

Currently, these releases/help pages etc are build with static JSX, but it could be possible to create pages with MD/MDX too. 

In such case, those md pages would probably apply automatically the site's main layout, and center the markdown content.

Is this what you have in mind?


---

Note: what you want to do is probably already possible by implementing your own plugin, but this is likely more work on your side than having official markdown pages support ^^

**Comment by chaitanya1248** [comment]
Yes, that is exactly what I'm looking for. As per following [Stackoverflow](https://stackoverflow.com/questions/62183134/adding-new-tab-to-docusaurusv-v2-navbar/62188099#62188099) any additional tabs can have content from src/pages only.

**Comment by amimas** [comment]
I was confused when I read this feature request. I think the description is misleading. It really has nothing to do with navigation or tabs. It's about being able to create regular "pages" (other than docs/blogs) using Markdown.

**Comment by yangshun** [comment]
@amimas that is correct. I think @chaitanya1248 was confused over what the navbar was doing and achieving. 

@chaitanya1248 For clarity, the navbar only serves to display links to other pages. What you are asking here is to allow **writing markdown to create new routes** so that they can be referenced in the navbar.

I've edited the issue description to make it clearer.

**Comment by yangshun** [comment]
Anyway if anyone is interested, I roughly got it to work in https://github.com/facebook/docusaurus/tree/yangshun/pages-mdx and had a PR #1610 which wasn't merged. I can't remember exactly why but Endilie mentioned that there were implicit dependencies on some markdown-related packages that I should have added. I might revisit this.

**Comment by slorber** [comment]
will take a look next week

**Comment by slorber** [comment]
here's a first draft PR if you want to take a look:
https://github.com/facebook/docusaurus/pull/2947
