### ISSUE TITLE
[v2]: fallback for tab choice (groupId)

### ISSUE THREAD

**Issue by LukasGentele** [facebook/docusaurus#2885]
## 🚀 Feature
When setting `groupId` on `Tabs`, it switches the tab selection for all tabs in this group and also stores the state in localStorage which is great. However, if there is a tab where one option is missing and this option is the selected one by using another tabs object of the same group with more choices, it looks kind of weird if no tab is selected. (see Motivation below for a real-world example)

Just falling back to the first `TabItem` would be one option. Alternatively, there could be a property for `Tabs` called `fallbackTab` or so which could reference `TabItem.value`. Yet another option would be to use the value of `Tabs.defaultValue`.

I would have opened a PR but I'm not sure which option the maintainers may prefer.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

y

## Motivation

Example use case: You have a docs site where you show how to do things with UI, API and CLI. You are using tabs, so users can switch between UI, API and CLI. Some features however, are not available in the UI for example, i.e. there are tabs with all 3 options and some with only API and CLI.

## Pitch

(Please explain why this feature should be implemented and how it would be used.)

**Comment by yangshun** [comment]
PRs welcome :)

**Comment by SamChou19815** [comment]
I put up a fix in #2893 that avoids updating a local choice is the chosen one is missing. @LukasGentele does that look good to you?

**Comment by LukasGentele** [comment]
@SamChou19815 This is definitely the easiest solution. Great idea. Thanks for fixing this so quickly.
