### ISSUE TITLE
Error boundaries

### ISSUE THREAD

**Issue by slorber** [facebook/docusaurus#2889]
## 💥 Proposal

There's no `getDerivedStateFromError` or `componentDidCatch` in Docusaurus v2. 

Errors might not happen very often, particularly most of them would simple make the build fail. 

But it might still be useful to add a default global error boundary in case the code of the user produces a runtime error. Some people might introduce buggy code in pages that might crash at runtime.

**Comment by spyke01** [comment]
I'll take a look into this.
