### ISSUE TITLE
Automatically add a .nojekyll file to the `static` directory when Docusaurus is installed

### ISSUE THREAD

**Issue by JoelMarcey** [facebook/docusaurus#2892]
## 🚀 Feature

We give guidance to add a `.nojekyll` file - https://v2.docusaurus.io/docs/next/static-assets/#caveats - but let's codify it.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## Motivation

Automation of a thing many people will do manually.

## Pitch

It will be used when sites have custom docs - like APIs - that should render correctly. See https://github.com/facebook/docusaurus/pull/2887#issuecomment-639220398

**Comment by yangshun** [comment]
This could be added to our templates within `packages/docusaurus-init/templates`.
