### ISSUE TITLE
Firefox dark-theme "below the fold" colours inverted

### ISSUE THREAD

**Issue by pwujek** [facebook/docusaurus#2894]
## 🐛 Bug Report
**Which package?**
I don't know - I reported this problem to FormatJS and they requested I file a bug report here (see https://github.com/formatjs/formatjs/issues/1701).

**Where is the problem found**
All pages on http://formatjs.io.

**Describe the bug**
The area below the initial view is displayed in inverted colours on a dark background.

**To Reproduce**
1. Go to https://formatjs.io
2. Scroll down

**Expected behaviour**
Colours should not be inverted.

**Screenshots**
![image](https://user-images.githubusercontent.com/1900015/83931935-6e2df180-a76d-11ea-9d90-934ac7165ab5.png)

**Environment - Desktop**
OS: Ubuntu 12.04
Browser: Firefox
Version: 76.01
Preferences - extensions: dark-theme enabled

- Docusaurus version used: not known - please ask the FormatJS team.

## Reproducible Demo
see above
-->

**Comment by lex111** [comment]
In fact, in my browser Firefox I do not observe a similar problem. Perhaps the matter is in the included extensions, or something like that.
