### ISSUE TITLE
/docs/ redirect should work correctly

### ISSUE THREAD

**Issue by JoelMarcey** [facebook/Docusaurus#290]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md)?

Yes

### Environment

N/A

### Steps to Reproduce

1. Go to https://docusaurus.io/docs/

### Expected Behavior

Should redirect to https://docusaurus.io/docs/{lang}/installation.html  ({lang} defaults to en)

### Actual Behavior

404

### Reproducible Demo

N/A

**Comment by neilsutcliffe** [comment]
To be fair, https://docusaurus.io/docs/en/ does not work either.

Is there the concept of a default docs page ATM, as the header and landing page link is just a link to a specific page?

**Comment by ashleytqy** [comment]
hi! can i try to work on this?

**Comment by neilsutcliffe** [comment]
Sure. Knock yourself out. I don’t really have time to work on stuff outside work at the moment

**Comment by JoelMarcey** [comment]
@ashleytqy Thank you!

**Comment by neilsutcliffe** [comment]
Sorry. Was a bit short. Thanks for helping out. Let me know if you have any questions. :)

**Comment by endiliey** [comment]
@ashleytqy, are you still working on this?

@joelmarcey, actually i am not really sure on the right behavior of this bug. 

Should it be redirected to  https://docusaurus.io/docs/{lang}/installation.html? 
What determines the default docs page (I believe that there is no concept of `default docs` page in Docusaurus) ?
What if its in another site (not docusaurus).

How about redirecting it to landing page ? ☺
#goodfirstissue

**Comment by ashleytqy** [comment]
Hi, sorry I’m no longer working on this!

**Comment by rstaib** [comment]
Is this issue fixed or not? Otherwise you will find [here](https://chillicream.com/blog/2018/11/07/docusaurus-docs-redirect) a solution.
