### ISSUE TITLE
Cannot move to another page's anchor 

### ISSUE THREAD

**Issue by shinout** [facebook/docusaurus#2901]
## 🐛 Bug Report

Cannot move to another page's anchor when clicking the link.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

yes

## To Reproduce
1. Add a page named "doc1" with the following contents
  ```markdown
  ## foo
  here require large contents enough to scroll
   ...
   ...
   ...
   ...
   ...

  ## bar
  some contents
  ```
1. Add a page named "doc2" with the following contents
  ```markdown
    [link to another page's anchor](doc1#bar)
  ```
1. Build the pages and open the browser
1. Click the link at the page "doc2"

## Expected behavior
Move to the "bar" on the page "doc1"

## Actual Behavior
Just move to the page "doc1", but the scroll position is incorrect (=top).

## Your Environment
- Docusaurus version used: ^2.0.0-alpha.55
- Environment name and version (e.g. Chrome 83.0.4103.97, Node.js 12.14.0):
- Operating system and version (desktop):

## Reproducible Demo
https://shinout.github.io/docusaurus-incorrect-anchor-move-repro/docs
* Click the link `doc1#Images` at Document Number 2(doc2)

**Comment by teikjun** [comment]
This should work as intended if you use lowercase, i.e. `doc1#images` instead of `doc1#Images`

**Comment by yangshun** [comment]
Indeed! Anchor links are slugified hence will become lower case. Thanks Teik Jun! Hi there fellow 🇸🇬 -ean!

**Comment by teikjun** [comment]
Hi Yangshun! :D

**Comment by shinout** [comment]
Thank you for your help.
Then I'm wondering how to link multibyte strings. I use Japanese and this happens when an anchor contains some Japanese characters. It won't work well.

**Comment by slorber** [comment]
Hi @shinout, if you think we should reopen, can you make a repro please?

**Comment by teikjun** [comment]
I've made a repro for the issue mentioned by @shinout

**To Reproduce:**
1. Visit https://docusaurus-anchor-repro.now.sh/docs/doc2
2. Click "go to a header written in japanese" link

It goes to the start of the page instead of the header 

**Reproducible Demo:**
Repo: https://github.com/teikjun/docusaurus-anchor-repro

**Comment by yangshun** [comment]
@teikjun Thank you for that! Btw are you an MLH fellow? Just wondering about the increased interaction here 😃

**Comment by teikjun** [comment]
Yup, I'm an MLH Fellow! I heard about the fellowship from your tweet 😄

**Comment by yangshun** [comment]
Oh that's great! Look @JoelMarcey I hired a fellow without knowing 🎉

**Comment by shinout** [comment]
@teikjun Thank you for preparing reproduction!
@yangshun Thanks for reopen the issue.

Should I add to the title of this issue `when using multibyte string` ?
