### ISSUE TITLE
Anchor links go to a scroll position that is slightly lower

### ISSUE THREAD

**Issue by teikjun** [facebook/docusaurus#2907]
## 🐛 Bug Report

Anchor links move to a scroll position that is slightly lower. 

**When using the url directly:**
(e.g. Directly access https://docusaurus-anchor-repro.now.sh/docs/doc1#images)
![image](https://user-images.githubusercontent.com/46853051/84062937-b742a780-a9f2-11ea-8a76-24630152416f.png)

**When using anchor link:**
(e.g. Click the "go to images" link on https://docusaurus-anchor-repro.now.sh/docs/doc2)
![image](https://user-images.githubusercontent.com/46853051/84063086-04267e00-a9f3-11ea-9521-f084fc5acc19.png)
The link also references `doc1#images`. However, we end up at a lower position. It is lower by the width of a navbar. 

## To Reproduce

1. Create a docusaurus site using the classic template 
1. In doc2, add a link to any anchor (e.g. `doc1#images`) in doc1
1. Start the website and click the link you added

## Expected behavior

After clicking the anchor link, I should go to the same scroll position as I would if I used the direct url (like the first screenshot above)

## Actual Behavior

After clicking the anchor link, I go to a scroll position that is lower by the width of a navbar.
The header is hidden by the navbar. (like the second screenshot above)

## Your Environment

- Docusaurus version used: 2.0.0-alpha.56
- Environment name and version (e.g. Firefox 77.0.1, Node.js 13.11.0):
- Operating system and version (desktop or mobile): Desktop Windows Build 2004

## Reproducible Demo
Repo: https://github.com/teikjun/docusaurus-anchor-repro
Website: https://docusaurus-anchor-repro.now.sh/docs/doc2

## Additional Remarks
This is not an issue if auto-hide sticky navbar is enabled

**Comment by slorber** [comment]
Something I also noticed: when the sidebar is collapsible and we use the docs internal anchor links on the right, we scroll to the anchor but the anchor title is actually hidden by the collapsible navbar, leading to some weird UX as it's not obvious that it actually scrolled to the correct position (sometimes it works fine, when the navbar collapses).

![image](https://user-images.githubusercontent.com/749374/84150205-d3316200-aa61-11ea-972d-3927492375ee.png)

cc @lex111 it does not seem your PR handle that case

**Comment by adrianmcli** [comment]
What @slorber pointed out above still seems to be an issue. @yangshun could we re-open this issue? Or should there be a new issue opened?

**Comment by claudiopro** [comment]
I am noticing the same issue on the React Docs website, likely cause the BLM header increased the expected size of the navbar.

cc @rachelnabors 
<img width="1392" alt="Screen Shot 2020-07-16 at 9 39 25 PM" src="https://user-images.githubusercontent.com/860099/87714958-dd572680-c7ac-11ea-9b22-a5c00d8a39c8.png">

**Comment by slorber** [comment]
@claudiopro I think reactjs website is a Gatsby site, not a Docusaurus site

**Comment by TomPeirs** [comment]
This is still an issue.
If the auto-hide sticky navbar is disabled then anchor links will jump slightly to far.

If the auto-hide sticky navbar isn't enabled (which is default behavior), then the scrolling offset should be changed.

**Comment by TomPeirs** [comment]
Hey @slorber ,
The fix  #3724,  does not fix the issue described here.
I tested out the deployment in the related issue  https://deploy-preview-3724--docusaurus-2.netlify.app
-> Clicking on something in the Table Of Contents scrolls to that location however, the header itself is hidden under the toolbar.

**Comment by slorber** [comment]
agree, there is still a probleme to solve

**Comment by aaryanporwal** [comment]
This is still an issue for us, any idea what might be causing this?

When using anchor link, it works well:
(e.g. Click the "HTTP Request" link on https://docs.fused.io/workbench/udf-builder/code-editor/ )

When using the url directly, it scrolls a bit above the actual heading:
(e.g. Directly access https://docs.fused.io/core-concepts/run-udfs/run-small-udfs/#http-requests)
