### ISSUE TITLE
Invalid `@docusaurs/core` peer dep on packages in alpha

### ISSUE THREAD

**Issue by vjpr** [facebook/docusaurus#2911]
## 🐛 Bug Report

Invalid peer dep. `^2.0.0` doesn't match `2.0.0-alpha.56`

```
WARN  @docusaurus/preset-classic: @docusaurus/plugin-content-blog@2.0.0-alpha.56 requires a peer of @docusaurus/core@^2.0.0 but version 2.0.0-alpha.56 was installed.
```

_@docusaurus/preset-classic/package.json_

```
  "peerDependencies": {
    "@docusaurus/core": "^2.0.0",
```

### Have you read the [Contributing Guidelines on issues]

Yep.

## To Reproduce

Warnings appeared for me in a pnpm monorepo.

```
npx @docusaurus/init@next init my-website classic
```

## Your Environment

- Docusaurus version used: Version: 2.0.0-alpha.56
- Environment name and version (e.g. Chrome 78.0.3904.108, Node.js 10.17.0):
- Operating system and version (desktop or mobile):

**Comment by yangshun** [comment]
This will keep happening until we launch v2.0.0 proper (out of alpha and beta).
