### ISSUE TITLE
[bug] isDarkTheme from useThemeContext always returns false

### ISSUE THREAD

**Issue by apsdehal** [facebook/docusaurus#2912]
## 🐛 Bug Report

In the default template for docusaurus, I am trying to use theme context to get `isDarkTheme`'s value. It is always set to false, even when I change to dark theme and then reload.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?
Yes
## To Reproduce

(Write your steps here:)

1. Use `const {isDarkTheme} = useThemeContext()
2. add console.log for isDarkTheme 
3. turn on dark theme and reload

## Expected behavior

Should provide true when dark theme is set

## Actual Behavior

isDarkTheme is false even when dark them is on

## Your Environment

- Docusaurus version used:2.0.0-alpha.56
- Environment name and version (e.g. Chrome 78.0.3904.108, Node.js 10.17.0): Node version: v12.17.0
- Operating system and version (desktop or mobile): Ubuntu 16.04

**Comment by SamChou19815** [comment]
See #2646. It might be caused by the same issue.

**Comment by apsdehal** [comment]
@SamChou19815 Thanks a lot. This does fix the issue. Maybe it needs to be documented better.

**Comment by slorber** [comment]
docs has been updated here by @Drewbi : https://github.com/facebook/docusaurus/pull/2934

still think it would be cool if the code did actually warn the user in case of using the hook without a provider (could throw with a link to the docs)
