### ISSUE TITLE
[Infima] Breadcrums not visible on dark theme

### ISSUE THREAD

**Issue by RDIL** [facebook/docusaurus#2918]
## 🐛 Bug Report

Pretty easy bug to fix, 

light theme (proper behavior):
![Screenshot 2020-06-10 at 10 04 25 PM](https://user-images.githubusercontent.com/34555510/84336927-6227a280-ab66-11ea-96ae-81116582afef.png)

dark theme (barely visible due to black color):
![Screenshot 2020-06-10 at 10 04 54 PM](https://user-images.githubusercontent.com/34555510/84336958-74a1dc00-ab66-11ea-8bce-2ae7ac6b80dc.png)

NOTE: I would open this issue in the infima repo but it seems *all the links to it are dead??*

**Comment by yangshun** [comment]
The links are not dead, just not public. Thanks for reporting, we didn't prioritize it since breadcrumbs aren't used on Docusaurus at the moment.

**Comment by RDIL** [comment]
@yangshun what do you mean not public?  Why not?

By definition, the links are dead if they aren't public.

**Comment by yangshun** [comment]
> By definition, the links are dead if they aren't public.

Sure

> What do you mean not public? Why not?

I haven't made it ready for very broad open source consumption. It still needs to go through a round of internal reviews.

**Comment by RDIL** [comment]
Okay
