### ISSUE TITLE
(v2) Make version switching to be aware of the current page

### ISSUE THREAD

**Issue by amimas** [facebook/docusaurus#2923]
## 🚀 Feature

I really like the ability to switch version from the top header without going into another page. It'd be great if switching to another version would go to the same page of the target version as the source page (where I'm currently switching from).

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## Motivation

This will make the UX to be much more intuitive. Right now switching version automatically goes to the root/main docs page. But, because of the version drop-down menu from the header, I can select a different version from any page, as show below:

<img width="790" alt="image" src="https://user-images.githubusercontent.com/16211767/84418938-dce3d280-abe5-11ea-97a2-be16e46bc118.png">

But, switching version while in that page, changes my context because I'm taken to the first doc page.

## Pitch

(Please explain why this feature should be implemented and how it would be used.)

Since we know the current page from the address bar when switching version, I think we should be able to easily go to the corresponding page in the target version.

Of course there are some edge cases where this would not work. For example, the page may not exist in the target version because doc did not exist or had changed it's filename/path. For the first iteration of this feature, it might make sense to follow the existing process (go to the first doc). In that case, it would be nice if the user can be notified via the notification bar at the top. The notification will advise that the file/doc/path does not exist in the currently selected version.

**Comment by slorber** [comment]
This is not easy, mostly because the navbar is "global" and decoupled from the docs system.

But it seems to be a feature that multiple issues are asking so I think we should support this. I have some idea on how to do it.

Related:
https://github.com/facebook/docusaurus/pull/2916
https://github.com/facebook/docusaurus/issues/2492#issuecomment-642738159

**Comment by slorber** [comment]
Here's a first preview of what it could look like: https://deploy-preview-2971--docusaurus-2.netlify.app/

Interested by your feedback

**Comment by slorber** [comment]
Hey all,  this is feature is now released!
If you like it, don't forget to retweet 😄 
https://twitter.com/docusaurus/status/1286715187983048704
