### ISSUE TITLE
v2 pages should receive siteConfig as props

### ISSUE THREAD

**Issue by slorber** [facebook/docusaurus#2925]
v1 pages did receive a `config` props (containing the `siteConfig` object).

I think v2 should receive it as well, otherwise, it complicates v1->v2 migration.

Particularly, users not used to React might need to refactor classes to functional components + `useDocusaurusContext()` hook. 

noticed this when helping this user migrate his site: https://github.com/substrate-developer-hub/substrate-developer-hub.github.io/pull/563

**Comment by anshulrgoyal** [comment]
@slorber should we just provide `config`  to pages or all the components like `docs`, `blogs`, and `pages`. 

I am thinking of two approaches:
1. In `ComponentCreator` (it will provide it to every component)
2. In `addRoute` in `contentLoaded` hook for pages plugin.

**Comment by anshulrgoyal** [comment]
or creating wrapper like `withConfig(Component)` might work.

**Comment by slorber** [comment]
@anshulrgoyal this is only for pages, because this is what we often need to modify for v1/v2 migration. 

v1 are usually using classes, and v2 we recommend SFC + hooks, so this can make the migration more complex if the user is not very familiar with React (+ the migrate cli cannot always easily transform class to SFC + hooks in an automated way)

**Comment by anshulrgoyal** [comment]
@slorber ok I will add config to pages only
