### ISSUE TITLE
Allow custom path for docs non-relative to website directory

### ISSUE THREAD

**Issue by Zenahr** [facebook/docusaurus#2937]
🚀 Feature

As of now it is only possible to set a custom path to the docs folder when the custom folder resides beside the website directory.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes.

## Motivation

More customizability when it comes to storing and managing docs documents.

## Pitch

This would allow developers to set up local servers for let's say companies (without paying hosting fees) and also allow other (non-technical) team members to make changes to the markdown files on the fly and in a centralized way.

**Comment by slorber** [comment]
Hi @Zenahr 

I'm sorry but I don't understand what you want to do exactly, or how is this related to #2890 

Is it v1 or v2?

Can you show an example configuration you would like to see working?

As the config is a js file, can't you use `path.relative(from,to)` as a workaround?

https://nodejs.org/api/path.html#path_path_relative_from_to

**Comment by Zenahr** [comment]
@slorber Thanks for your quick reply. Actually this is exactly what I needed. It is not related to #2890 that was a sloppy mistake by me.

This feature wouldn't be needed since `path.relative(from,to)` would work well.

**Comment by Zenahr** [comment]
The workaround does not work.
Docusaurus will still try to find the docs folder on the same level as `website` no matter where you set the customDocsPath to.

The only thing customDocsPath allows you to do is set the path of the docs folder only on the same level of `website`.

https://docusaurus.io/docs/en/site-config#customdocspath-string

I couldn't find the code snippet responsible for this. I mean responsible for looking inside the `website` folder for the `docs` folder. Changing the path there would resolve the issue.

**Comment by Zenahr** [comment]
> 
> 
> Hi @Zenahr
> 
> I'm sorry but I don't understand what you want to do exactly, or how is this related to #2890
> 
> Is it v1 or v2?
> 
> Can you show an example configuration you would like to see working?
> 
> As the config is a js file, can't you use `path.relative(from,to)` as a workaround?
> 
> https://nodejs.org/api/path.html#path_path_relative_from_to

This is in regards to V1.

**Comment by Zenahr** [comment]
### Example Configuration

Docusaurus source folder location: `C:\Docusaurus-Source-Folder`
Docs folder location: `D:\Documentation\docs`

**Comment by slorber** [comment]
Hi,

I tried using `customDocsPath: '/Users/sebastienlorber/Desktop/docs'` and it didn't work

Had an error like this:

```
Error: You have 'doc' in your headerLinks, but no '/Users/sebastienlorber/Desktop/docs' folder exists one level up from 'website' folder. Did you run `docusaurus-init` or `npm run examples`? If so, make sure you rename 'docs-examples-from-docusaurus' to 'docs'.
    at forEach (/Users/sebastienlorber/Desktop/projects/docusaurus/packages/docusaurus-1.x/lib/core/nav/HeaderNav.js:253:15)
```


----

I tried the following on D1 website, and it did actually work fine:

```
const path = require('path');

const customDocsPathAbsolute = '/Users/sebastienlorber/Desktop/someOtherFolder/docs'

const customDocsPath = path.relative(
  path.join(__dirname, '..'),
  customDocsPathAbsolute,
);
console.log('customDocsPath', customDocsPath);
```

--- 

To make it work, you have to ensure the relative path you provide makes this path exist: `${CWD}/../${readMetadata.getDocsPath()}/`

**Comment by slorber** [comment]
Hi @Zenahr , I'm closing due to heart reaction and no news, assuming it's solved
