### ISSUE TITLE
Default Prism theme de-emphasises comments

### ISSUE THREAD

**Issue by Vinnl** [facebook/docusaurus#2938]
## 🐛 Bug Report

The default Prism theme used shows comments in a faded colour. Now, I'd argue that this is already not great with regular code, but for documentation sites in particular comments are often meant to clarify code and to help the reader understand it - so it's extra important that it actually stands out rather than fades away, I think.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

You mean the one that says to fill out this template? :P

## To Reproduce

1. Visit https://v2.docusaurus.io/docs/static-assets#markdown-example
1. Look for the instructions on where to place import statements.
1. Notice that it's in a comment with a contrast ratio of 2.71, not meeting the WCAG standards for accessible text.

(This is not actually the default theme, but it shows the same issue.)

## Expected behavior

For code comments to be easily readable or actually stand out in the default Prism theme.

## Actual Behavior

The comments are hard to read, especially if your screen is not that bright and/or you have visual impairments.

![image](https://user-images.githubusercontent.com/4251/84654107-e5eae180-af0e-11ea-9ab2-4cbb101ac2c6.png)

## Your Environment

- Docusaurus version used: v2.0.0-alpha.56
- Environment name and version (e.g. Chrome 78.0.3904.108, Node.js 10.17.0): Firefox 77
- Operating system and version (desktop or mobile): Ubuntu 20.04 Desktop

## Reproducible Demo

https://github.com/Vinnl/docusaurus-issue-reproduction

See `/docs`.

**Comment by slorber** [comment]
Hi,

> By default, the Prism [syntax highlighting theme](https://github.com/FormidableLabs/prism-react-renderer#theming) we use is [Palenight](https://github.com/FormidableLabs/prism-react-renderer/blob/master/src/themes/palenight.js). You can change this to another theme by passing `theme` field in `prism` as `themeConfig` in your docusaurus.config.js.


I kind of agree, but not sure we want to actually create our own theme setup.

Maybe this accessibility concern should rather be reported to the Palenight theme directly?

**Comment by Vinnl** [comment]
I'll report it there, but it might be a harder sell for general syntax highlighting, whereas it is more clearly relevant to code snippets in documentation. Maybe let's await what they say there first: https://github.com/FormidableLabs/prism-react-renderer/issues/86

**Comment by Vinnl** [comment]
> But overall, I’m confident that the themes are a good baseline that people can customise since they’re just small configs ♥️
