### ISSUE TITLE
[v2] Author name is always same for all of the pages

### ISSUE THREAD

**Issue by apsdehal** [facebook/docusaurus#2952]
## 🐛 Bug Report

Whenever an update is made using GitHub action to the website using `yarn build` and then deploy to gh pages, the author is always the same for all of the pages.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## To Reproduce

1. Have a look https://mmf.sh/docs

## Expected behavior

Author should be the actual person who last updated the docs

## Actual Behavior

The author is same and the person who made the recent commit

(Write what happened. Add screenshots, if applicable.)

## Your Environment

Docusaurus version used:2.0.0-alpha.56
Environment name and version (e.g. Chrome 78.0.3904.108, Node.js 10.17.0): Node version: v12.17.0
Operating system and version (desktop or mobile): MacOS 10.14.6 (desktop and mobile both)

## Reproducible Demo

(Paste the link to an example repo, including a `siteConfig.js`, and exact instructions to reproduce the issue.)

https://mmf.sh/docs

Seems somewhat related to #2798

**Comment by yangshun** [comment]
Agreed. Seems like a GitHub actions thingy. Local deployment should work fine.

**Comment by slorber** [comment]
afaik Github Pages deployment need to commit to a gh-pages branch to deploy, and we read the github history to know which doc has been updated by which git user last

https://github.com/facebookresearch/mmf/commits/gh-pages

as you can see, reading this history could only lead to the github bot :(


Honnestly I'm not fan of using github pages anymore. Options like Netlify are free, much simpler to setup and do not need to commit anything to the repo.

**Comment by slorber** [comment]
I've opened a doc issue here: https://github.com/facebook/docusaurus/issues/2953

@apsdehal wonder if you could try to host on Netlify or Vercel, and give me feedback on how simple it was compared to Github actions?

**Comment by Jason-2020** [comment]
See the comment for solution. https://github.com/facebook/docusaurus/issues/2798#issuecomment-636602951
It's not only v2 or Github thing. It's just behaviour of your CI environment.

**Comment by slorber** [comment]
thanks @Jason-2020 

@apsdehal can you tell if this works great for your usecase?

**Comment by slorber** [comment]
@apsdehal I'm closing as I think @Jason-2020 gave a solution.

**Comment by praveenkumar6722** [comment]
I still see the issue, my code already has depth configured.

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

**Comment by ntucker** [comment]
For vercel you'll need to setup github actions yourself as their integration doesn't allow non-zero fetch-depth: https://github.com/vercel/vercel/discussions/5737#discussioncomment-4113364
