### ISSUE TITLE
versions.html doesn't seem to be generated

### ISSUE THREAD

**Issue by ndelangen** [facebook/Docusaurus#297]
### Is this a bug report?

YES

### Have you read the [Contributing Guidelines](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md)?

YES

### Environment

(OS: MacOS, Node: `8.8.1`, npm: `5.4.2` , yarn: `1.3.2`)

### Steps to Reproduce

I'm trying to add docusaurus to [Storybook](https://github.com/storybooks/storybook) see [branch](https://github.com/storybooks/storybook/tree/docusaurus) [diff](https://github.com/storybooks/storybook/compare/release/3.3...docusaurus) 

1. I've added docusaurus using the CLI
2. I've moved the example docs and blog markdown-files
3. I've created a version `1.0.0`
4. I've created a version `1.0.1` (both using the CLI)
5. I ran `yarn start`
6. I clicked on the version in the header
7. This results in a `404`
8. I've also tried to build a static version, There I also get a 404.

### Expected Behavior

I'm expecting some list of version in a page of some kind

### Actual Behavior

When using `yarn start`:
![screen shot 2017-12-15 at 16 29 51](https://user-images.githubusercontent.com/3070389/34048773-3ebad736-e1b5-11e7-888d-8deaf5e99fde.png)
![screen shot 2017-12-15 at 16 29 59](https://user-images.githubusercontent.com/3070389/34048772-3ea63c22-e1b5-11e7-998d-e6ee8ca85636.png)

A static build (served using the `serve` package:
![screen shot 2017-12-15 at 16 27 57](https://user-images.githubusercontent.com/3070389/34048701-f6289e22-e1b4-11e7-956c-2548af18b375.png)

### Reproducible Demo

(Paste the link to an example project and exact instructions to reproduce the issue.)
I uploaded a static version to now:
https://build-xnwonsjllj.now.sh/

And the code is here: [branch](https://github.com/storybooks/storybook/tree/docusaurus)

**Comment by ndelangen** [comment]
duplicate of https://github.com/facebook/Docusaurus/issues/228

**Comment by JoelMarcey** [comment]
Hi @ndelangen Thanks for filing this issue. I am going to make some time to look at this today. I am hoping we are just omitting some step here since I believe the workaround from @caabernathy helped her get around this.

**Comment by ndelangen** [comment]
Yes, I got a `versions.html` file generated too. Might just need a docs change to fix?

**Comment by JoelMarcey** [comment]
@ndelangen Hi! 

So I did find a pretty crucial error in the docs.

I assume you went to https://docusaurus.io/docs/en/versioning.html and followed the instructions there to create versions.

When you did, it said:

<img width="1024" alt="screenshot 2017-12-16 16 41 55" src="https://user-images.githubusercontent.com/3757713/34075591-25d8e84a-e280-11e7-9f30-8f95a55cab56.png">

That is very wrong! :)

We want versions, not translations.

So I changed the docs to say:

<img width="1024" alt="screenshot 2017-12-16 16 43 14" src="https://user-images.githubusercontent.com/3757713/34075594-3b7868ec-e280-11e7-9f29-74a7fb439649.png">

That is correct. 

Then I followed your steps and was able to get a `versions.html` automatically.

<img width="1294" alt="screenshot 2017-12-16 16 44 42" src="https://user-images.githubusercontent.com/3757713/34075618-70bb7f58-e280-11e7-94ae-f0a1664202dc.png">

<img width="1308" alt="screenshot 2017-12-16 16 44 32" src="https://user-images.githubusercontent.com/3757713/34075620-74a06750-e280-11e7-8f8c-0314852b323e.png">

Does that help you solve your problem?

**Comment by ndelangen** [comment]
Yes, that helped, thanks 🙇
