### ISSUE TITLE
Validate baseURL

### ISSUE THREAD

**Issue by slorber** [facebook/docusaurus#2978]
## 🐛 Bug Report

Using baseUrl without a trailing slash lead to site that does not really work.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

yes

## To Reproduce

D2 website with `baseUrl: '/build'`

It builds but the site does not work once hosted (try to modify `yarn serve:v2` script), due to expecting a trailing /

## Expected behavior

Should work (normalized to a trailing /), or throw config validation error (requiring user to provide a trailing /)

## Actual Behavior

Broken site

---

@anshulrgoyal as it's related to the validation maybe you could do this later

**Comment by anshulrgoyal** [comment]
We can include it using regex in current pr

**Comment by anshulrgoyal** [comment]
I think validation error makes more sense since there might be some changes in the future and normalize would be done silently, which could result in bugs.

**Comment by slorber** [comment]
Yes agree, validation is fine. Normalization should rather be used only for "shortcuts", but we should expect users to provide a valid config and be strict about it.
