### ISSUE TITLE
Enabling superscript and/or subscript doesn't work.

### ISSUE THREAD

**Issue by joeplaa** [facebook/docusaurus#2979]
## 🐛 Bug Report

Enabling superscript and/or subscript doesn't work.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## To Reproduce

(Write your steps here:)

1. Install and initialize docusaurus 1.14 (`npx docusaurus-init`)
2. Enable sup and sub in remarkable (`siteconfig.js`) as described in docs: [https://docusaurus.io/docs/en/site-config](https://docusaurus.io/docs/en/site-config).

```javascript
markdownPlugins: [
  function foo(md) {
    md.inline.ruler.enable(['sub', 'sup']);
  },
],
```

3. Add page with <sup>1</sup> tag or ^1^ (doc2 in demo)

## Expected behavior

The 1 character or "st" should be rendered to html superscript

## Actual Behavior

The 1 character and "st" are rendered as regular text in html.

## Your Environment

- Docusaurus version used: 1.14
- Environment name and version (e.g. Chrome 78.0.3904.108, Node.js 10.17.0): Chromium 83.0.4103.106, Node.js 12.16.2
- Operating system and version (desktop or mobile): Windows 10 1909

## Reproducible Demo

[https://github.com/jodibooksHQ/docusaurus-bug-2979](https://github.com/jodibooksHQ/docusaurus-bug-2979)

**Comment by lex111** [comment]
Sorry for such a long delay, but since this issue is from v1, it's hard to say when this will be fixed.
We are focused on working on v2, so maybe you can make the upgrade to the new version of Docusaurus?

**Comment by joeplaa** [comment]
@lex111 this is quite a coincidence. I'm migrating to v2 as we speak. Not because of this issue by the way.

**Comment by naddeoa** [comment]
Not to derail this too much, but how should people be using plugins like this in v2? The best resource I could find in the docs is the [manual migration page](https://docusaurus.io/docs/next/migration/manual) which mentions that the `markdownPlugins` option has been replaced with `remarkPlugins` because remarkable isn't used anymore but the latest version of docusaurus throws if you attempt to supply `remarkPlugins` in the config and there is no mention of it in the [config validation code](https://github.com/facebook/docusaurus/blob/master/packages/docusaurus/src/server/configValidation.ts#L111-L165) at all.

**Comment by joeplaa** [comment]
@naddeoa I ran into the same issue with the documentation about plugins being (still) a bit vague. Hopefully they will be improved soon, now that v2 is out of alpha. I don't have a straight answer for you as I'm also "just" a Docusaurus user, but maybe this will help you along.

- The current document about how to use plugins: [https://docusaurus.io/docs/next/markdown-features/plugins](https://docusaurus.io/docs/next/markdown-features/plugins). 
- And this is indeed how I've done it in v2, see example below on how I implemented/use KaTeX. 
- By the way, the superscript and subscript worked out of the box for me in v2.

1. import / require plugins at the top of `docusaurus.config.js`: 
```js
const remarkMath = require('remark-math');
const rehypeKatex = require('rehype-katex');
```
2. now also in `docusaurus.config.js` add to `presets` (not `plugins` !?):
```js
presets: [
        [
            `@docusaurus/preset-classic`,
            {
                blog: {},
                docs: {
                    showLastUpdateAuthor: true,
                    showLastUpdateTime: true,
                    path: `docs`,
                    remarkPlugins: [remarkMath],
                    rehypePlugins: [rehypeKatex],
                    sidebarPath: require.resolve('./sidebars.json')
                },
                sitemap: {
                    changefreq: 'weekly',
                    priority: 0.5,
                    trailingSlash: false
                },
                theme: {
                    customCss: [require.resolve(`./src/css/custom.css`)]
                }
            }
        ]
    ],
```

**Comment by slorber** [comment]
> the latest version of docusaurus throws if you attempt to supply remarkPlugins in the config

This is plugin option config, not global site config (also why it's not in the global config validation logic)

Added documentation for Katex today: https://docusaurus.io/docs/next/markdown-features/math-equations

If you want to enable extra md features on v2, you can pass remark plugins as documented (not in the migration guide)

Going to close as we likely won't do anything for v1
