### ISSUE TITLE
plugin-client-redirects does not respect baseurl

### ISSUE THREAD

**Issue by smazanek** [facebook/docusaurus#2980]
## 🐛 Bug Report

Tried all kind of combinations but did not get plugin-client-redirects to consider the baseurl set for the project. My expectation would be that the following works if baseurl is set (in my case to baseUrl: '/pages/teamabc/website/public/'), but build step fails complaining that the "to" path is not valid:
    [
      '@docusaurus/plugin-client-redirects',
      {
        redirects: [
          {
            to: 'docs/ec2/overview', 
            from: ['/docs/ec2/'],           
          }
        ],
      },
    ],
I further tried to specify redirect using full URL (but it is complaining that it only expects a path, not URL) and also tried for "to:" with "baseurl + docs/ec2/overview", this is building but it is then duplicating the baseurl when I try to access the link in the website, i.e. it is redirecting to /pages/teamabc/website/public/pages/teamabc/website/public/docs/ec2/overview

## Your Environment

- Docusaurus version used: Version: 2.0.0-alpha.58
- Environment name and version (e.g. Chrome 78.0.3904.108, Node.js 10.17.0): Chrome
- Operating system and version (desktop or mobile): Desktop

**Comment by slorber** [comment]
Hey, you are absolutely right. 

There has been a fixed merged to master already for fromExtension / toExtension, but it does not apply to `redirects` or `createRedirect`. 

Opened this issue to track the problem so I'm going to close this one: https://github.com/facebook/docusaurus/issues/2982

This should be fixed for next release
