### ISSUE TITLE
client-redirects plugin should not be baseUrl sensitive

### ISSUE THREAD

**Issue by slorber** [facebook/docusaurus#2982]
## 🐛 Bug Report

Discussed here:
https://github.com/facebook/docusaurus/pull/2969#issuecomment-647671257

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## To Reproduce

- Use D2 website
- build it with `baseUrl: '/build'`
- serve the /website folder (modify package script: `"serve:v2": "serve website",`
- go to http://localhost:5000/build/
- the redirect from `/docs/versionX/introduction` to `/docs/versionX/` that the plugin setup should work like it does without a baseUrl (http://localhost:5000/build/docs/introduction)

The conf is currently:

```
    [
      '@docusaurus/plugin-client-redirects',
      {
        fromExtensions: ['html'],
        createRedirects: function (path) {
          // redirect to /docs from /docs/introduction,
          // as introduction has been made the home doc
          if (allDocHomesPaths.includes(path)) {
            return [`${path}/introduction`];
          }
        },
      },
    ],
```

## Expected behavior

Using a baseUrl should not require the user to reconfigure the plugin

Here we need to modify the behavior of `createRedirects`, becase the path argument includes the baseUrl.

For the extensions it has been fixed in https://github.com/facebook/docusaurus/pull/2969

## Actual Behavior

`createRedirects` is baseUrl sensitive

---

# What we should probably do?

The postBuild hook receives props.routePaths, but these paths includes the baseUrl, and we forward these paths to other plugin methods:

```javascript
    async postBuild(props: Props) {
      const pluginContext: PluginContext = {
        routesPaths: props.routesPaths,
        ...
      };
   // ...
}
```

We should probably instead make these paths relative to the baseUrl so that the plugin config is not baseUrl sensitive. 

```javascript
    async postBuild(props: Props) {
      const pluginContext: PluginContext = {
        relativeRoutesPaths: props.routesPaths.map(path => removePrefix(path,props.baseUrl)),  
        ...     
      };
   // ...
}
```

(this probably requires reverting some changes from #2969 , as passing the baseUrl as arg to some methods would not be needed anymore)

**Comment by teikjun** [comment]
I observed two related issues while reproducing this issue. 

1. **`baseUrl` field fails validation when there is no ending slash**
While building with `baseUrl: /build`,  I receive Validation Errors from the client-redirects plugin.
To resolve this, we can add a slash at the end. i.e. `baseUrl: /build/` works. However, I'm not sure if this is the intended behavior.

1.  **No redirects even when using default `baseUrl`**
Even when we use `baseUrl: '/'`, no redirection occurs when we visit http://localhost:5000/docs/introduction (or https://v2.docusaurus.io/docs/introduction)
To resolve this, we need to add an ending slash to every element in allDocHomePaths. (e.g For the link above to work in particular, we should append a slash to `/docs`) 
``` js
// append an ending slash to all array elements like this
const allDocHomesPaths = [
  '/docs/', 
  '/docs/next/',
  ...versions.slice(1).map((version) => `/docs/${version}/`),
];
```

I will make a PR to resolve the website redirection issue in point 2 together with the original issue.
