### ISSUE TITLE
Home page with docs-only mode does not show sidebar

### ISSUE THREAD

**Issue by tuler** [facebook/docusaurus#2985]
## 🐛 Bug Report

The home page does not show the sidebar when we follow the [documentation instructions](https://v2.docusaurus.io/docs/docs-introduction/#docs-only-mode).

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## To Reproduce

1. `npx @docusaurus/init@next init docusaurus-docs-only classic`
2. Modify `docusaurus.config.js` according to [instructions](https://v2.docusaurus.io/docs/docs-introduction/#docs-only-mode) as I did [here](https://github.com/tuler/docusaurus-docs-only/commit/479ce5479d1f651a205f17e5d8ab9167b22801aa)
3. `yarn start`

## Expected behavior

Home page should also show sidebar.

## Actual Behavior

Sidebar doesn't show up.

<img width="1121" alt="Screen Shot 2020-06-23 at 11 48 08 AM" src="https://user-images.githubusercontent.com/73850/85425990-e5260100-b547-11ea-92a8-9b3d9f133ca4.png">

## Your Environment

- Docusaurus version used: 2.0.0-alpha.58
- Environment name and version: Node.js v14.4.0
- Operating system and version (desktop or mobile): macOS 10.15.5

## Reproducible Demo

https://github.com/tuler/docusaurus-docs-only

**Comment by slorber** [comment]
Thanks @tuler 

Actually found the problem, the quickfix is simply to delete the `src/pages/index.js` file.

it's an annoying internal issue we have where when 2 pages are created for the same url ("/" in this case), the props of the pages are somehow "merged" silently, and we end up in a weird state. Related to 2917

Until I have a proper fix for this problem, will add a warning and document docs only mode better

**Comment by charlax** [comment]
I have the same issue with a similar setup (docs-only mode). What did you do to find the fix? Not sure how to debug, and I have deleted the `src/pages/index.js`

**Comment by slorber** [comment]
@charlax newest versions shouldn't have this problem anymore
