### ISSUE TITLE
Live editor render twice times on page first mount

### ISSUE THREAD

**Issue by cncolder** [facebook/docusaurus#2986]
## 🐛 Bug Report

Live editor render component twice times

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

yes

## To Reproduce

1. Paste code below into .mdx file

```
	```jsx live
	function Demo() {
    	React.useEffect(() => console.log('mount'), [])
    	return null
	}
	```
```

## Expected behavior

<!--
  How did you expect your project to behave?
  It’s fine if you’re not sure your understanding is correct.
  Write down what you thought would happen.
-->

log 'mount' one time

## Actual Behavior

<!--
  Did something go wrong?
  Is something broken, or not behaving as you expected?
  Describe this section in detail, and attach screenshots if possible.
  Don't only say "it doesn't work"!
-->

```
mount
mount
```

## Your Environment

<!-- Include as many relevant details about the environment you experienced the bug in -->

- Docusaurus version used: 2.0.0-alpha.58
- Environment name and version: Chrome 83
- Operating system and version (desktop or mobile): macOS

## Reproducible Demo

(Paste the link to an example repo, including a `siteConfig.js`, and exact instructions to reproduce the issue.)

<!--
  What happens if you skip this step?

  Someone will read your bug report, and maybe will be able to help you,
  but it’s unlikely that it will get much attention from the team. Eventually,
  the issue will likely get closed in favor of issues that have reproducible demos.

  Please remember that:

    * Issues without reproducible demos have a very low priority.
    * The person fixing the bug would have to do that anyway. Please be respectful of their time.
    * You might figure out the issues yourself as you work on extracting it.

  Thanks for helping us help you!
-->

**Comment by slorber** [comment]
Hi,

That seems right, but this only happens on initial mount (hydration), not on navigation. 

It is due to a key that was added on the Playground:

```jsx
        <Playground
          key={isClient}
```

Added in commit: refactor(v2): add @theme-init alias to give access to initial components (#2464)

@lex111 do you remember why this was needed?

**Comment by cncolder** [comment]
If someone want to explain how to implement useMount by react hook. e.g. author of react-use. People will ask “why mount trigger two times”

**Comment by 9oelM** [comment]
I will work on this issue

**Comment by 9oelM** [comment]
Well I've been inspecting this, and after an hour of hopeless digging, I even got to the point where I omitted almost every prop fed to <Playground /> component.

I was doing something like:

```ts
const PlaygroundTest = memo((props) => {
  console.log(props)
  
  return <Playground {...props} />
}, (a, b) => {
  console.log(a, b)

  return false;
})

withLiveEditor = ((Component) => {
  const WrappedComponent = (props) => {
    // const {isClient} = useDocusaurusContext();
    // const prismTheme = usePrismTheme();

    console.log(props.live)
    if (props.live) {
      return (
        <PlaygroundTest
          // key={isClient}
          scope={ReactLiveScope}
          // theme={prismTheme}
          // {...props}
        />
      );
    }

    return <Component {...props} />;
  };

  return WrappedComponent;
});
```

to just test `React.memo` works. However, the `areEqual` function as the second argument does not ever get called. I don't know what I'm doing wrong there.

Any idea?

**Comment by slorber** [comment]
@9oelM I think this is due to a similar key being on the doc:

```
    <Layout
      key={isClient}
```

I don't know exactly why we need this key here, it is here for a long time, but I'd be happy to remove it if it does not produce any weird side-effect

**Comment by 9oelM** [comment]
I tried that too but it didn't work.. :(
I struggled for like an hour, still haven't found a clear walkthrough

**Comment by 9oelM** [comment]
Seems like some other issue other than the key.. hmm

**Comment by 9oelM** [comment]
actually, i will try again

**Comment by SunXinFei** [comment]
same issue
constructor and componentDidMount will run twice in markdown file.
