### ISSUE TITLE
Add option to compile a "versionless" site when using `docusaurus start`

### ISSUE THREAD

**Issue by krillboi** [facebook/docusaurus#2988]
## 🚀 Feature

Often when previewing your site using `docusaurus start` you want to check that the newest doc in development is correct and don't really care about old versions of the doc. Therefore to speed up compilation time, it would be nice to have an option to "turn off" versioning, such that only the documents located in the `docs` folder is compiled (basically compile the site as if it wasn't using versioning).

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes.

## Motivation

Faster compilation times when previewing a site that uses versioning.

## Pitch

Our amount of docs is quite big (~360 .mdx files per version) and as such the compilation time has started to become long after introducing versioning. I have plans on a workaround to do this kinda thing myself (keeping the versioning related stuff in a separate folder such that it doesn't get compiled, then copying those folder into the project when deploying), but having an official, simple option from Docusaurus would be favourable and would probably please other developers as well :)

**Comment by slorber** [comment]
Hi @krillboi 

Actually I wanted this too, so here it is: https://github.com/facebook/docusaurus/pull/2989

**Comment by krillboi** [comment]
@slorber Fantastic!
