### ISSUE TITLE
Docusaurus `deploy` deletes .circleci/config.yml

### ISSUE THREAD

**Issue by BurntBrunch** [facebook/docusaurus#2990]
## Docusaurus delete .circleci/config.yml on gh-pages

CircleCI needs a no-op config on gh-pages or else it fails on every commit with "missing config.yml". 

I added such a config for facebookincubator/profilo in [this commit](https://github.com/facebookincubator/profilo/commit/4bee4f643eda28e0b0dc76f42734cc4dca83ce3e). As you can see, the builds went green.

However, the [subsequent docusaurus push](https://github.com/facebookincubator/profilo/commit/39d2ce5cfdbb7a902d742281aeaea2ae55b1e8dc) ([just `yarn run deploy` from master](https://github.com/facebookincubator/profilo/blob/master/.circleci/config.yml#L77)) deleted the config.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes.

## Steps to reproduce

1. Add a file to the gh-pages branch that Docusaurus doesn't know about (e.g. .circleci/config.yml)
2. Run a deployment of the site

## Expected behavior

Docusaurus should preserve things on the branch that it doesn't understand. At the very least, it should preserve dot files and folders or at least known CI configs (.circleci, .travis.yml, whatever github actions uses, etc)

## Actual Behavior

Docusaurus removed a CI config, making Circle fail on gh-pages commits again.

**Comment by SamChou19815** [comment]
In your use case, you can put the dummy circle ci config in the static folder to unblock yourself. See https://v2.docusaurus.io/docs/deployment/#docusaurusconfigjs-settings for a similar use case for `CNAME` file.

Ideally, there could be a mode where `docusaurus deploy` doesn't try to wipe every single file in previous deployments.

**Comment by slorber** [comment]
Hi

So what I understand is that CircleCI fails to build your `gh-pages` branch. CircleCI should probably not run in this branch in the first place. Isn't there a way to tell the CI to ignore this branch, outside of this configuration file?

It seems we could also use a specific commit message to skip the CI but this is proprietary to CircleCI: https://discuss.circleci.com/t/cant-ignore-the-gh-pages-branch/2002/2


One solution could be to copy your conf to the `build` folder.

```
yarn --non-interactive --cache-folder ~/.cache/yarn build && cp -R .circleci build
```

**Comment by BurntBrunch** [comment]
Sorry for dropping this thread.

> Isn't there a way to tell the CI to ignore this branch, outside of this configuration file?

Nope, I had a pretty lengthy chat with Circle support and that's just not how Circle works anymore. You need a config on each branch or each commit to the branch will trigger a _failing_ build (as it won't find the config).

> you can put the dummy circle ci config in the static folder to unblock yourself

That's not a bad idea. Is there a recommended CI setup anywhere in the docs? It sounds like this would be a common gotcha for Circle users and we should maybe document it somewhere?

**Comment by slorber** [comment]
> Is there a recommended CI setup anywhere in the docs?

Afaik there is not. We already document many deployment solutions, it's hard to document as well all the CI solutions, as it would lead to some kind of expensive matrix to maintain. This problem is related to using CircleCI + GH pages specifically, not so related do Docusaurus ^^ you have to understand the tools you choose for CI and deployment by reading their doc.

> It sounds like this would be a common gotcha for Circle users and we should maybe document it somewhere?

Doc PRs are welcome if you feel this part should be improved

**Comment by BurntBrunch** [comment]
Nothing else to do here, thanks everyone!
