### ISSUE TITLE
Refactor `help` component in basics example to maintain consistency

### ISSUE THREAD

**Issue by taylorallen0913** [facebook/docusaurus#2995]
## 💥 Proposal

All React components in the basics example template are class components except for Help. Can we refactor the Help component into a class component to maintain consistency throughout all of the components? I'm not sure if there was a specific reason behind using a functional component there, but if not, I don't see why refactoring it into a class component will hurt. I can send a PR if this seems like a reasonable fix.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?
Yes

**Comment by yangshun** [comment]
In fact we want to encourage using functional components instead of classes as you can use hooks in them. So we'd wanna go the opposite direction instead.

**Comment by taylorallen0913** [comment]
@yangshun Would you want to migrate all of the components to functional components? If so I could work on this :)

**Comment by yangshun** [comment]
Are you talking about v1 or v2? Sure but let's do one component at a time

**Comment by taylorallen0913** [comment]
It's up to you, but I can start on v1.

**Comment by slorber** [comment]
Almost all the v2 code is using functional components already.

Not sure it's really worth to convert v1, as we are in maintainance mode and want to move all users to v2 soon.

**Comment by yangshun** [comment]
Yeah I'd say not to bother with v1 code anymore.
