### ISSUE TITLE
What would be the best way to integrate Google Analytics?

### ISSUE THREAD

**Issue by lipis** [facebook/Docusaurus#300]
Maybe it would make sense to have some sort of setting for it to just be able to add the Google Analytics Tracker ID..

**Comment by rickyvetter** [comment]
It should work with `gaTrackingId` in your siteConfig. http://docusaurus.io/docs/en/site-config.html#siteconfig-fields

**Comment by lipis** [comment]
Maybe :) hehe... next time I should spend more time RTFM 😃 thabks
