### ISSUE TITLE
How to create /404.html?

### ISSUE THREAD

**Issue by azu** [facebook/Docusaurus#301]
### Is this a bug report?

Yes, or feature request.

GItHub pages and Netlify treat `404.html` as special url.

- <https://help.github.com/articles/creating-a-custom-404-page-for-your-github-pages-site/>
- <https://www.netlify.com/docs/redirects/#custom-404>

Current docusaurus can not output `/404.html`.

### Have you read the [Contributing Guidelines](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md)?

Yes

### Environment

- OS: macOS 10.12.6
- Node: v9.2.1
- npm: 5.5.1
- docusaurus: 1.0.3

### Steps to Reproduce

1. Create `/website/pages/404.js`
2. Put following content

```jsx
const React = require("react");
class Index extends React.Component {
    render() {
        return <div>>404</div>;
    }
}
module.exports = Index;
```

3. `npm run build`

Throw following error:

```
/Users/azu/.ghq/github.com/almin/almin/website/node_modules/docusaurus/lib/server/generate.js:360
      var langParts = match[1].split('/');
                           ^

TypeError: Cannot read property '1' of null
    at /Users/azu/.ghq/github.com/almin/almin/website/node_modules/docusaurus/lib/server/generate.js:422:25
    at Array.forEach (<anonymous>)
    at execute (/Users/azu/.ghq/github.com/almin/almin/website/node_modules/docusaurus/lib/server/generate.js:401:9)
    at Object.<anonymous> (/Users/azu/.ghq/github.com/almin/almin/website/node_modules/docusaurus/lib/build-files.js:31:1)
    at Module._compile (module.js:641:30)
    at Object.Module._extensions..js (module.js:652:10)
    at Module.load (module.js:560:32)
    at tryModuleLoad (module.js:503:12)
    at Function.Module._load (module.js:495:3)
    at Function.Module.runMain (module.js:682:10)
```

### Expected Behavior

Create `build/<site>/404.html`

### Actual Behavior

Throw error.

> TypeError: Cannot read property '1' of null

**Comment by azu** [comment]
Ah, I've noticed that docusaurus create from `en/404.js` to `build/<site>/404.html` if default lang is `en`.

![404 js almin 2017-12-16 22-43-32](https://user-images.githubusercontent.com/19714/34071013-c2a833ba-e2b2-11e7-97aa-b5cd4852cd9c.png)

This issue has been resolved. I'm close this issue.

**Comment by JoelMarcey** [comment]
@azu Thank you for the detailed issue description.

Another option is to put a raw HTML page (e.g., `404.html`)  into the `website/static` directory as well. And that file will get copied over to the root of the site upon build/generation.

**Comment by thiagopov** [comment]
bo teta de resolver:
crie o arquivo 404.js nas pages
copie e cole o conteudo do help.js
build e seja feliz
