### ISSUE TITLE
Fix `Edit this page` links to lead on original resource (not generated)

### ISSUE THREAD

**Issue by sidoruk-sv** [facebook/docusaurus#3019]
## 🐛 Bug Report

For now the link `Edit this page` leads to the editing of `/versioned_docs/version-N.x/page.md`.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## To Reproduce

(Write your steps here:)

1. Got to https://v2.docusaurus.io/docs/migrating-from-v1-to-v2
1. Click on `Edit this page`
1. https://github.com/facebook/docusaurus/edit/master/website/versioned_docs/version-2.0.0-alpha.58/migrating-from-v1-to-v2.md will be opened

## Expected behavior

`Edit this page` link should lead to the original source of the page, not versioned_docs (generated) content.
https://github.com/facebook/docusaurus/blob/master/website/docs/migrating-from-v1-to-v2.md

## Actual Behavior

For now `Edit this page` link leads to `versioned_docs`:
https://github.com/facebook/docusaurus/blob/master/website/versioned_docs/version-2.0.0-alpha.58/migrating-from-v1-to-v2.md

## Your Environment

- Docusaurus version used: `"@docusaurus/core": "^2.0.0-alpha.50",`
- Environment name and version (e.g. Chrome 78.0.3904.108, Node.js 10.17.0): irrelevant
- Operating system and version (desktop or mobile): irrelevant

## Reproducible Demo

Docusaurus docs also have such problem:
https://github.com/facebook/docusaurus/tree/master/website

**Comment by slorber** [comment]
Hi @sidoruk-sv 


You are not totally right, the behavior is correct, it's just confusing:
- Your page is not the "next" version, it is the "latest version", (ie the one at the top of the versions.json file. Editing it lead to the correct versioned github file.
- If you browse the "next" version (https://v2.docusaurus.io/docs/next/ ), you will see that the edit link do lead to the website/docs folder

Related: it has been already requested to somehow make the "next" version (ie /docs) be the "current version". (https://github.com/facebook/docusaurus/issues/2302)

We need to support these 2 cases:
- You officially release v1 (/versioned/v1), and then move directly to v2 (/docs), yet, v1 remains the "current version", despite v2 being in active work in the /docs folder (current behavior)
- You have released v1, (/versioned/v1), and you now work on v2. You release v2, but consider it's still in active development, so you don't yet run the versioning command of docusaurus and keep working on v2 using the /docs folder, until you need to start working on v3 (in which case you'd have to create the /versioned/v2 folder, and have /docs for v3)

Is it clear?

**Comment by sidoruk-sv** [comment]
@slorber yep, shed some light on that. Thanks for your explanations!)
