### ISSUE TITLE
infima github link broken

### ISSUE THREAD

**Issue by techieshark** [facebook/docusaurus#3028]
## 🐛 Bug Report

This may belong in the infima repo but... that's the issue.

From the website:

https://facebookincubator.github.io/infima/

if you click on Github
<img width="966" alt="image" src="https://user-images.githubusercontent.com/1072292/86712750-b0926900-c060-11ea-93aa-50f55208429b.png">

you will see a 404 error. Is that because the repo isn't actually public?

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

yes

## To Reproduce

(Write your steps here:)

1. Open incognito / private tab.
1. Visit https://facebookincubator.github.io/infima/
1. Scroll to bottom.
1. Click on Github link (to https://github.com/facebook/infima)

## Expected behavior

Opens GitHub repo

## Actual Behavior

Displays 404

<img width="903" alt="image" src="https://user-images.githubusercontent.com/1072292/86712951-e8011580-c060-11ea-8b10-e8880a6a48dd.png">

**Comment by anshulrgoyal** [comment]
Infima is actually in a private repo

**Comment by techieshark** [comment]
Thanks @anshulrgoyal.  

Do you know if the plans are to open source it? (I assume that's the plan, since the footer says "Facebook Open Source".)  

Otherwise, maybe this doesn't need fixing, depending on the outcome of  #2961 ?

**Comment by slorber** [comment]
Hi

We'll try to publish Infima soon

**Comment by hugo-vrijswijk** [comment]
Any updates on this? It's a little weird to have an essentially closed-source dependency

**Comment by slorber** [comment]
Still in discussions 🤪 

Let's track it here: https://github.com/facebook/docusaurus/issues/3575
