### ISSUE TITLE
URI avatar in blog is not visible with "more" option

### ISSUE THREAD

**Issue by michelcourbon** [facebook/docusaurus#3031]
## 🐛 Bug Report

avatar URI like "img/img-perso.jpg" works fine in blog page, and isn't visible in "read more" page

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?
yes of course

## To Reproduce

in blog directory, md file with this parameter :
- author_url: https://perso.univ-st-etienne.fr/courbon/
- author_image_url: img/img-perso.jpg
in docusaurus config js file  url with configuration
- url: 'https://perso.univ-st-etienne.fr/',
-  baseUrl: '/courbon/',

## Actual Behavior

(Write what happened. Add screenshots, if applicable.)

## Your Environment

- Docusaurus version used :  docusaurus v2.0.0.58
- Environment name and version developpement VScode (error same in firefox, chrome, Node 12.13.1, npm 6.12.1):
- Operating system windows 10 pro version 2004 used for developp, nginx for deploiement

## Reproducible Demo
see demo at https://perso.univ-st-etienne.fr/courbon/ 

  Please remember that:

    * Issues without reproducible demos have a very low priority.
    * The person fixing the bug would have to do that anyway. Please be respectful of their time.
    * You might figure out the issues yourself as you work on extracting it.

  Thanks for helping us help you!
-->
greetings

**Comment by anshulrgoyal** [comment]
I think `author_image_url: /img/img-perso.jpg` this is correct

**Comment by michelcourbon** [comment]
more complement to add the resolution of the bug...

hello.. i'm impressive.. quick reponse.. I try it.. but some problems
with your proposition  author_image_url: /img/img-perso.jpg no image is present in pages "blog" or "http://localhost:3000/courbon/blog/Bienvenue"
I try the 2 other possibilities :

    author_image_url: ../img/img-perso.jpg image is visible in page "http://localhost:3000/courbon/blog/Bienvenue" but not in blog..
    author_image_url: ./img/img-perso.jpg image is not visible in page "http://localhost:3000/courbon/blog/Bienvenue" but no problem in page blog....

If you have any idea..

best regards, and thanks

**Comment by michelcourbon** [comment]
hello, try it offline during vacation !! the problem is the same.. unable to use local uri..  like ./img  !!! the /img proposed create error in the 2 pages of the blog.. thanks

**Comment by slorber** [comment]
Hi,

The problem is due to using relative paths. 

![image](https://user-images.githubusercontent.com/749374/90506268-3cb1a900-e154-11ea-91ff-3eebf1cf7752.png)


These paths are resolved against the current URL the user is browsing, so they can work on one page, and fail on another.

It is indeed working if you use non-relative paths including the baseUrl: `/courbon/img/img-perso.jpg`

**Comment by michelcourbon** [comment]
thanks a lot !! great work... and now it works fine !! so you can complete example with such detail
