### ISSUE TITLE
Warn when routes override each others

### ISSUE THREAD

**Issue by slorber** [facebook/docusaurus#3041]
## 🚀 Feature

If 2 plugins try to register the same route, we should warn the user.

This often happens when enabling things like docs/blog-only mode, and not deleting the /pages/index.js file

To be done just before the routesLoaded lifecycle

On D2 site, using / for docs home should lead to 3 overrides, as far as I remember there's:
- `/`
- `/search` (we have a docs/search + a page/search)
- `/?` can't remember the last one

@teikjun can you work on this?

Related to https://github.com/facebook/docusaurus/issues/3039

**Comment by teikjun** [comment]
Yes, I'll work on it! :)
