### ISSUE TITLE
antlr4 syntax.

### ISSUE THREAD

**Issue by omry** [facebook/docusaurus#3046]
## 🐛 Bug Report

While antlr4 is a supported syntax in [prism](https://prismjs.com/examples.html), it does not look like it's supported in D2.
This is likely due to the syntax not being included with D2. If this is the case, what is the best course of action?

## To Reproduce

Enter this antlr4 snippet and use antlr4 or g4 per the prism instructions as the language:
```antlr4
grammar JSON;

json
   : value
   ;

obj
   : '{' pair (',' pair)* '}'
   | '{' '}'
   ;
```

## Expected behavior
![image](https://user-images.githubusercontent.com/376455/87215209-0aa55f80-c2e9-11ea-8e77-c932fd96e451.png)

## Actual Behavior
![image](https://user-images.githubusercontent.com/376455/87215215-185ae500-c2e9-11ea-86d1-42b7e029acf9.png)

## Your Environment

packages.json
```json
{
  "name": "website",
  "version": "0.0.0",
  "private": true,
  "scripts": {
    "docusaurus": "docusaurus",
    "start": "docusaurus start",
    "build": "docusaurus build",
    "swizzle": "docusaurus swizzle",
    "deploy": "docusaurus deploy"
  },
  "dependencies": {
    "@docusaurus/core": "^2.0.0-alpha.58",
    "@docusaurus/preset-classic": "^2.0.0-alpha.58",
    "classnames": "^2.2.6",
    "docusaurus-plugin-internaldocs-fb": "^0.3.3",
    "react": "^16.8.4",
    "react-dom": "^16.8.4"
  },
  "resolutions": {
    "prism-react-renderer": "1.1.0"
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  }
}
```

**Comment by slorber** [comment]
https://v2.docusaurus.io/docs/markdown-features/#syntax-highlighting

You need to swizzle and have the file here, as documented: `src/theme/prism-include-languages.js`. 

It's not the case here: https://github.com/facebookresearch/hydra/tree/master/website/src/theme

**Comment by omry** [comment]
Awesome, thanks!

**Comment by omry** [comment]
Looks like there is no need to swizzle anything.
[This](https://github.com/facebookresearch/hydra/pull/801/files) did the trick.

**Comment by slorber** [comment]
ah yeah, this is surprising because it's not in the defaultly supported languages: https://github.com/FormidableLabs/prism-react-renderer/blob/master/src/vendor/prism/includeLangs.js

maybe you'll get a better support by using swizzle, and have partial/decent support now?

**Comment by omry** [comment]
Reading the docs, swizzle is to be used when I add my own language support. I am trying to use an existing language supported by prism here.

> If you want to add highlighting for languages not yet supported by **Prism**, you can swizzle prism-include-languages

**Comment by slorber** [comment]
ah you are probably right maybe just turning on the lang is enough

**Comment by omry** [comment]
it is enough, not sure if prism somehow brings the language syntax at runtime or if it's comes packages with all of them after all.
it's small enough (1.17K).
