### ISSUE TITLE
Google Tag Manager - Doesn't recognize blog page change

### ISSUE THREAD

**Issue by kirtan403** [facebook/docusaurus#3047]
### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## To Reproduce

(Write your steps here:)

1. Setting up a blog only website (Mentioned here: https://v2.docusaurus.io/docs/blog#blog-only-mode)
2. Adding google tag manager
``` 
gtag: {
      trackingID: 'GTM-OOOOOO',
      // Optional fields.
      anonymizeIP: true, // Should IPs be anonymized?
    },
```
3. It only logs the first page of the landing when the tag manager is loaded. After that if I nevigate to other blog posts or back to the home page, no page views are being tracked in the Google Analytics with Google Tag Manager.

## Expected behavior

It should track all the pages being visited, not only the one on which the page was initially loaded. 

## Actual Behavior

It only tracks the first page's URL. 

## Your Environment

- Docusaurus version used: v2.0.0-alpha.58
- Environment name and version (e.g. Chrome 83.0.4103.116, Node.js v14.5.0):
- Operating system and version (desktop or mobile): Desktop

## Reproducible Demo

Will not be able to share the google analytics account details and a hosted website here. If you really want, I would setup on sample repo and share the screenshot or screen recording.

**Comment by slorber** [comment]
Hi,

I'm not familiar with GTM, but there's this page to integrate in SPAs: https://developers.google.com/analytics/devguides/collection/gtagjs/single-page-applications

On navigate, we do something like:

```
gtag('config', 'UA-1234567-89', {'page_path': '/new-page.html'});
```

> After you've added the new value for page_path, all subsequent events sent to that property will use that new value.



Maybe we should fire such an event on navigate, so that it shows up on your GTM dashboard?

Maybe something like this?

```
gtag('config', 'UA-1234567-89', {'page_path': '/new-page'});
gtag('event', 'navigate', {'page_path': '/new-page'});
```

???

**Comment by kirtan403** [comment]
Yes, probably. To be honest, I'm not familiar with how it actually works, but based on your links, it looks like that is the right thing to do

**Comment by slorber** [comment]
@kirtan403 I don't use GTM myself, can you please open a PR? At least, try to test these changes on your site locally, and confirm that the proposed changes are what you are looking for.
