### ISSUE TITLE
Detect internal broken links during build

### ISSUE THREAD

**Issue by omry** [facebook/docusaurus#3048]
## 🚀 Feature
A website should fail to build if it has internal broken links.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Not relevant for feature requests, is it?

## Motivation

While building the website, it's all to easy to change the page filename and forget or miss incoming internal links.

## Pitch
It will help create higher quality websites and reduce the churn of "easy" incoming pull requests fixing minor issues in the docs.

**Comment by slorber** [comment]
agree, this is definitively something we need

**Comment by slorber** [comment]
check #3059

**Comment by omry** [comment]
awesome, that was quick!
