### ISSUE TITLE
Syntax Highlighting Does not Work Following Documentation Example

### ISSUE THREAD

**Issue by FA5I** [facebook/docusaurus#3049]
## 📚 Documentation

Hi all, I am having a bit of issue with the highlighting stuff. I followed the tutorial here:

https://docusaurus.io/docs/en/site-creation

Now according to the docs, I can use highlightjs or prism to do syntax highlighting in a block.

My siteConfig.js file looks like this:

```
highlight: {
    // Highlight.js theme to use for syntax highlighting in code blocks.
    theme: 'default',
  },

  usePrism: ['scala'],
```

My react component on the front page of the site is just a modified version of the one created by the tutorial (index.js):

```
const FeatureCallout = () => (
      <div align="center">
        <h2>Simple API</h2>
        <MarkdownBlock>
          code goes here
        </MarkdownBlock>
      </div>
    );
```

However this just gives me:

![image](https://user-images.githubusercontent.com/56031768/87233051-d484e000-c3bb-11ea-891d-b9d82d41465c.png)

As you can see there is no syntax highlighting. I followed the docs but nowhere does it explain how to get around this issue.

Is there something missing from the docs? Forgive me I am new to docosaurus and want to use it for the lib im building.

**Comment by slorber** [comment]
Hi,

Do you think we should make the doc clearer? What was your issue in the end?

**Comment by acse-fk4517** [comment]
Hi @slorber, The issue for me seems to persist. What happened was the following. If I put say Scala code inside the MarkdownBlock that is generated for the Index.js page when I initialise Docusaurus, I get no Syntax highlighting inside it. This is despite the docs saying syntax highlighting is enabled.

So I guess this means syntax highlighting only works for actual markdown files, and not a MarkdownBlock right? The syntax highlighting works in my .md files, but nowhere else.

**Comment by slorber** [comment]
You are using v1?

**Comment by acse-fk4517** [comment]
Yes, following the docs here:

[https://docusaurus.io/docs/en/installation](https://docusaurus.io/docs/en/installation)

**Comment by slorber** [comment]
It's unlikely we'll do much work on v1, as we try to ship a stable version of v2.

Do you use versioning or i18n in v1? if not I'd recommend you to migrate to v2. We can help, and are working on a cli to automate this process

**Comment by acse-fk4517** [comment]
@slorber - ok thanks, Ill try and migrate to v2 for my project

**Comment by slorber** [comment]
great

We are going to do a release very soon, you will be able to try the migration cli. Get in touch on Discord if this does not work or need help

**Comment by slorber** [comment]
The Docusaurus team is actively working on Docusaurus v2.

After a very long alpha, Docusaurus v2 is [now in beta](https://docusaurus.io/blog/2021/05/12/announcing-docusaurus-two-beta).
We believe that the v2 beta is already better than v1, and v2 is ready for maintstream adoption.

Apart from critical issues and security fixes, we don't plan to invest much time on Docusaurus v1 anymore.

We are all closing v1 issues. 
Maybe the current issue is already fixed in Docusaurus v2.
Please try to upgrade, and if the issue is still there on Docusaurus v2, open a new issue.
