### ISSUE TITLE
Sidebar category deep linking

### ISSUE THREAD

**Issue by omry** [facebook/docusaurus#3051]
The sidebar of [hydra.cc](https://hydra.cc/docs/next/intro):
![image](https://user-images.githubusercontent.com/376455/87235822-72b17f80-c395-11ea-9ff8-a42b09a0d088.png)

A link to a doc page looks like : https://hydra.cc/docs/next/advanced/overriding_packages

however, linking to https://hydra.cc/docs/next/advanced/ ends up with an 404.

It would be great to create some surface to somehow show the content of the toolbar instead.

**Comment by slorber** [comment]
Hi,

What do you mean by "the content of the toolbar instead". I don't think I see how this should work, and what to display exactly 🤪 

Why do you want to link to a specific sidebar category?

**Comment by omry** [comment]
Yes, actually I  think that the sidebar category should have a page.

That page can be auto generated from the sidebar items.
Extra points if you allow the user to customize it.
In some cases I actually manually created such a landing page, but I would really prefer that it would be associated with the category itself and not a page in it.

Example:
https://hydra.cc/docs/next/tutorials/intro

Not sure about discoverability, it's a good point.
However, in many cases I find myself wanting to link to a category and not to the first page in it. an example is a tutorial.

**Comment by slorber** [comment]
That's an interesting. 

How would you see the api for customizing this page working?

What do you want on this page by default? 
A flat list of docs?  
Or should it show nested categories?

**Comment by omry** [comment]
Let me start by specifying a few requirements I think exists to make this useful:

1. The API should allow me to fully specify my own page at minimum (manually, like I am doing in that intro link).
2. It should allow me to iterate on the sidebar list I am rendering the page for.
3. For each item in the list, it should provide a convenient way to access the metadata of the page:
```
---
id: logging
title: Logging
sidebar_label: Logging
---
```
## Initial API proposal:

```text
module.exports = {
    Docs: {
        About: [
            'intro',
            'terminology',
        ],
     ...
```
Let's customize the About category.
I am going to put down some half-pseudo code, half-copy-page abomination.
I don't know enough react to make it valid.

website/src/pages/sidebar/About.jsx
```jsx
import Sidebar from '@docusaurus/Sidebar';
Some user header
<ul>
  for value in Sidebar.getCategory("About")) {
    <li>{value.name} : {value.title}</li>
  }
</ul>
Some user footer
```

**Comment by omry** [comment]
ideally we would have something better to name the file after than the text in the sidebar, but I don't think sidebar items has an id right now.

**Comment by slorber** [comment]
This issue seems related to https://github.com/facebook/docusaurus/issues/2643

**Comment by slorber** [comment]
closing as https://github.com/facebook/docusaurus/issues/2643 is enough to track this
