### ISSUE TITLE
Trailing slash breaks images

### ISSUE THREAD

**Issue by tvvignesh** [facebook/docusaurus#3061]
Hi. I am using docusaurus v2. While everything works great, trailing slash is breaking images.

I have a markdown syntax like this where I am storing myimage in the same folder as the markdown file

```
[![IMAGE ALT TEXT](./myimage.png)](https://www.example.com "My Image description")
```

It fails because of the trailing slash. If I fix in the website by maybe adding `../` it will not render in Github. Is there any way to make it work both in Github and the website as well?

Screenshot below:

![Screenshot from 2020-07-15 09-34-55](https://user-images.githubusercontent.com/1165845/87502163-83f0d980-c67e-11ea-817b-72d69ecb1111.png)

Directory structure:

![Screenshot from 2020-07-15 09-37-43](https://user-images.githubusercontent.com/1165845/87502305-e0ec8f80-c67e-11ea-855b-e59f09008506.png)

I guess the same path logic you guys are using for generating html out of `.md` and rewriting paths can be used for images as well.

Thanks in advance.

**Comment by tvvignesh** [comment]
If I put it in static folder and try to access it that way, it will work in the website but will break when rendering in the Github repo. Was wondering what to do.

**Comment by slorber** [comment]
Hi,

Currently we don't support well using  relative md images, so it's hard to support both github + website at the same time.

This is something I want to solve in https://github.com/facebook/docusaurus/issues/3057

**Comment by tvvignesh** [comment]
@slorber Thanks for the clarification. Will use the absolute url till then. Feel free to close this issue if you want.

**Comment by anshulrgoyal** [comment]
#3069 this solve relative images

**Comment by slorber** [comment]
Hey all,  this is feature is now released!
If you like it, don't forget to retweet 😄 
https://twitter.com/docusaurus/status/1286715187983048704
