### ISSUE TITLE
Support activeBasePath and activeBaseRegex for Navbar dropdowns

### ISSUE THREAD

**Issue by adrianmcli** [facebook/docusaurus#3066]
## 🚀 Feature

Allow setting of `activeBasePath` and `activeBaseRegex` on dropdown items for the navbar so the dropdown becomes highlighted when the user is in that particular section of the docs.

## Motivation

`activeBasePath` and `activeBaseRegex` are very useful for signalling to the user what section of the docs they are on. 

However, this doesn't work for dropdowns. This reduces the immediate helpfulness when moving from a flat navbar structure to a slightly more nested one. See example:

Before: 
<img width="373" alt="Screen Shot 2020-07-15 at 2 52 22 PM" src="https://user-images.githubusercontent.com/943555/87584034-dd6efd80-c6aa-11ea-8d37-91658153c37f.png">

After:
<img width="450" alt="Screen Shot 2020-07-15 at 2 52 32 PM" src="https://user-images.githubusercontent.com/943555/87584035-de079400-c6aa-11ea-96f4-529359488ced.png">

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## Pitch

If we implemented this feature, then the user will have a clear signal as to what section of the docs they are on, regardless of whether or not they were hovering over a specific dropdown. Of course, you can simply opt-out of this feature by not using `activeBasePath` and `activeBaseRegex` in the dropdown.

Example usage:

```js
{
  label: "The Protocol",
  position: "left",
  activeBaseRegex: "(synthetic-tokens|oracle/|governance/)",
  items: [
    {
      to: "synthetic-tokens/explainer",
      label: "Synthetic Tokens",
      activeBasePath: "synthetic-tokens",
    },
    {
      to: "oracle/tech-architecture",
      label: "Oracle (DVM)",
      activeBaseRegex: "(oracle/|governance/)",
    },
  ],
},
```

**Comment by slorber** [comment]
Hi,

Afaik this is already working and documented:
https://v2.docusaurus.io/docs/theme-classic/#navbar-links

Look at Docusaurus v2 website, and its config:

```
        {
          label: 'Docs',
          to: 'docs', // "fake" link
          position: 'left',
          activeBaseRegex: `docs/(?!next/(support|team|resources))`,
          items: [
            {
              label: versions[0],
              to: 'docs/',
              activeBaseRegex: `docs/(?!${versions.join('|')}|next)`,
            },
            ...versions.slice(1).map((version) => ({
              label: version,
              to: `docs/${version}/`,
            })),
            {
              label: 'Master/Unreleased',
              to: 'docs/next/',
              activeBaseRegex: `docs/next/(?!support|team|resources)`,
            },
          ],
        },
```

**Comment by adrianmcli** [comment]
@slorber good to know that this is supported. Can you help me figure out why this doesn't work?

I need some help w/ my `activeBaseRegex` regex for my dropdown. The dropdown is not getting highlighted, but the child items are. I've trimmed out some irrelevant properties but this is what I have in my config:
```js
{
  activeBaseRegex: "(synthetic-tokens|oracle|governance)",
  items: [
    { activeBasePath: "synthetic-tokens" },
    { activeBasePath: "oracle" },
    { activeBasePath: "governance" },
    },
  ],
},
```
My doc files have the ID of `synthetic-tokens/doc1`, `oracle/doc2`, and `governance/doc3` for example.

**Comment by slorber** [comment]
@adrianmcli without a repro it's hard to tell, but as I said you, without the "to" attribute it's unlikely to work as of current code

**Comment by adrianmcli** [comment]
@slorber 
Sorry, this is the actual code in the repo: https://github.com/UMAprotocol/docs/blob/master/config/navbar.js#L20-L41

**Comment by slorber** [comment]
@adrianmcli as I said, you absolutely need a to element on the parent item here

![image](https://user-images.githubusercontent.com/749374/89905338-58fc9580-dbea-11ea-871c-20c6e673201e.png)

even if it's useless and is like link `to: '/'` it will make the code use the ReactRouter NavLink. That's bad but it should work temporarily.

**Comment by slorber** [comment]
no `to` means `activeBaseRegex` gets ignored

**Comment by adrianmcli** [comment]
@slorber thanks so much for the clarification! perhaps it should be documented better, but I really appreciate you taking the time 😊

**Comment by slorber** [comment]
np 👍 

i'd like to improve all that as it's not idiomatic at all

keeping this undocumented also helps to see how many users are struggling with this kind of issues :)
