### ISSUE TITLE
Lack of instructions on how to run the site locally

### ISSUE THREAD

**Issue by aadsm** [facebook/Docusaurus#307]
On https://docusaurus.io/docs/en/site-preparation.html it says: 

> With a few changes, you can verify that Docusaurus was installed correctly by running the site locally.

Some information is missing here:
1) What are the few changes needed?
2) How to run the site locally?

**Comment by JoelMarcey** [comment]
Hi @aadsm, there should probably be a link for "verify" pointing to the bottom of that same page. I can add that, or if you want to send a PR, that would be good too.

https://docusaurus.io/docs/en/site-preparation.html#verifying-installation

Sorry for the confusion.

**Comment by aadsm** [comment]
Oh I see, what if we just put the Verifying Installation at the top, instead of the initial paragraph?
I'm happy to put a PR for this.

**Comment by JoelMarcey** [comment]
Or you could just move that sentence to just after the first sentence in the Verifying Installation section? 

> Running the Docusaurus initialization script, docusaurus-init, produces a runnable, example website to base your site upon. With a few changes, you can verify that Docusaurus was installed correctly by running the site locally.

I liked the Directory Structure as an introduction to folks to give them some context of what is going on after they run the `docusaurus-init` script.

What do you think?

**Comment by aadsm** [comment]
If you have a strong opinion on that structure then my recommendation is to remove the "With a few changes, you can verify that Docusaurus was installed correctly by running the site locally.".
From a personal point of view I like to see things up and running once I've installed them, just to make sure everything is fine. Then I read the docs.

For instance, when I read `The website/pages folder contains example top-level pages for the site.` I was not sure what it meant until I saw those links on the top.
I wonder if the file tree structure could be explained by following the different parts of the UI instead of following the directory structure.
I'm a very visual person so I prefer to look at something up and running and then understand how each part is built, not everyone is like that of course. Happy to chat more though, we sit close to each other.

**Comment by JoelMarcey** [comment]
We move the verifying installation instructions - https://docusaurus.io/docs/en/installation.html#verifying-installation

Reopen if you feel that does not close the issue.
