### ISSUE TITLE
Syntax highlighting for Protocol Buffers

### ISSUE THREAD

**Issue by mingrammer** [facebook/docusaurus#3071]
## 🚀 Feature

(A clear and concise description of what the feature is.)

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes.

## Motivation

We're using Protocol Buffers, but Docusaurus's markdown engine doesn't support syntax highlighting for protobuf language.

## Pitch

Someone like me may need the protobuf highlighting.

**Comment by slorber** [comment]
v1 or v2?

Do you have an open-source site?

Have you read the doc, and added the required v2 configuration?
https://v2.docusaurus.io/docs/markdown-features/#syntax-highlighting

**Comment by mingrammer** [comment]
I'm using v2.

I found a list of default languages Docusaurus supports now: https://github.com/FormidableLabs/prism-react-renderer/blob/master/src/vendor/prism/includeLangs.js in that documentation link.

So I added this config to support protobuf. Thank you for help.

```js
prism: {
    additionalLanguages: ['protobuf'],
}
```

p.s. I think Protocol Buffers is also commonly used language, what do you think about adding the protobuf to the default language list? I can send a PR for this.

**Comment by slorber** [comment]
Great to see it works for you.

Protobuf is commonly used but we don't necessarily want to include it by default, for bundle size reasons. 

There are so many commonly used languages we could support by default, it's probably not a very good idea to include all of those. 

The most we could do is make it more easy to include additional languages (I mean, being just a config, not using swizzle), but it's not high priority as current system works fine for now.
