### ISSUE TITLE
Only HTML is loaded using github pages

### ISSUE THREAD

**Issue by psyycker** [facebook/docusaurus#3075]
## 🐛 Bug Report

By following the documentation written in Docusaurus, I'm trying to deploy using the gh-pages branch.
Problem being that only the HTML is loaded, the whole javascript etc is not loaded throwing 404 or content security issues

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## To Reproduce

- Clone the repo https://github.com/Vident/vident and cd into the `documentation` folder
- Yarn and yarn build
- Open the index.html in the browser and only the html content will appear. It's doing the same on the gh-pages

You can find the whole configuration on the following repo: https://github.com/Vident/vident
And the result here: https://vident.github.io/vident/

## Expected behavior

Render the styled page

## Actual Behavior

Renders HTML only and cannot load other pages

## Your Environment

- Docusaurus version used: 2.0.0-alpha.58
- Environment name and version (e.g. Chrome 78.0.3904.108, Node.js 10.17.0): Chrome Version 83, NodeJS version 12.18.1, yarn version 1.22.4
- Operating system and version (desktop or mobile): Macos 11 beta 2

## Reproducible Demo

Already described in the steps to reproduce. You can find how it renders to this link: https://vident.github.io/vident/
The whole configuration is in the repo which is public: https://github.com/Vident/vident

**Comment by slorber** [comment]
Hi,

You need to set a baseurl if you are not hosting the site at the root of your domain (`/vident`), like it is documented.

=> https://github.com/Vident/vident/pull/3
