### ISSUE TITLE
`projectName` doesn't have description in siteConfig.js

### ISSUE THREAD

**Issue by aadsm** [facebook/Docusaurus#308]
`url` and `baseUrl` are kind of self-explanatory and have a description.
I also recommend naming this property to what it means: `githubProjectName`.

**Comment by JoelMarcey** [comment]
Yeah, we have a `TODO` in `generate.js` about this. 

https://github.com/facebook/Docusaurus/blob/master/lib/server/generate.js#L102

I need to think about this some more. But, regardless, we should have it documented.

**Comment by aadsm** [comment]
Interesting, I'm happy to talk about this too, if you need someone to bounce ideas at.

**Comment by JoelMarcey** [comment]
We documented `projectName` - https://docusaurus.io/docs/en/site-config.html#mandatory-fields

We can put the rename in a different issue.
