### ISSUE TITLE
Integrate with Contentful

### ISSUE THREAD

**Issue by zhaozhiming** [facebook/Docusaurus#310]
### Is this a bug report?

No

### Have you read the [Contributing Guidelines](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md)?

Yes

### Expected Behavior

Docusaurus can integrate with [Contentful](https://www.contentful.com/).
For example, my product site have many docs to maintenance and the maintenance people don't know `markdown` syntax. If Docusaurus can integrate with Contentful then it would be better.

### Actual Behavior

No yet.

**Comment by endiliey** [comment]
Feel free to re-open a new one
