### ISSUE TITLE
[v2] how can i create a version

### ISSUE THREAD

**Issue by DyncMark** [facebook/docusaurus#3100]
![image](https://user-images.githubusercontent.com/15116881/88273659-1ba09880-cd0d-11ea-921d-6e7ea6ee2b04.png)

**Comment by teikjun** [comment]
I'm able to reproduce the same error with npm, but it works fine with yarn. I'll try looking into this soon.
In the meantime, you should be able to create a version with `yarn run docusaurus docs:version 1.1.0`.

**Comment by DyncMark** [comment]
thanks for reply.  i have created a version with `yarn run docusaurus docs:version 1.1.0`.  but I have new error when I install `@docusaurus/plugin-client-redirects`, I tried `npm` and `yarn`, but I was unable to complete the installation.

**Comment by teikjun** [comment]
Just to double check, did you use `yarn add @docusaurus/plugin-client-redirects` to add the plugin?
Also, could you post a screenshot of the error and link us to your code (if possible)?

**Comment by DyncMark** [comment]
> Just to double check, did you use `yarn add @docusaurus/plugin-client-redirects` to add the plugin?
> Also, could you post a screenshot of the error and link us to your code (if possible)?

There are no errors,  always in the pending state. It's probability a network problem, cause I'm in China.

**Comment by slorber** [comment]
@DyncMark you are right, but where did you see in docs to run `npm run docusaurus` ?

![image](https://user-images.githubusercontent.com/749374/88310894-830c1780-cd10-11ea-98a8-569356f41c6a.png)

As far as I know npm can only run registered scripts in package.json, so it does not work


But if I add this script: `"docusaurus": "docusaurus",` it now works:

![image](https://user-images.githubusercontent.com/749374/88311008-a931b780-cd10-11ea-881c-d0e5ed7cbd1f.png)

Will add this script in the templates as it will be more convenient for npm users. 

@teikjun in the migration cli PR, can you add it as well?

---- 

About the redirects plugin, I don't think it's related to the plugin. Anyway this plugin only works on the production build so it should have no impact if you start the site in dev mode.

**Comment by slorber** [comment]
if you have an error with the redirect plugin, please verify your connexion and open another issue with a detailed bug report

**Comment by teikjun** [comment]
@slorber I have added it to the migration PR! :)
The instructions that say `npm run docusaurus ...` came from here: https://v2.docusaurus.io/docs/versioning/#tagging-a-new-version. The docs are correct now that we have added the scripts.

**Comment by DyncMark** [comment]
> @DyncMark you are right, but where did you see in docs to run `npm run docusaurus` ?
> 
> ![image](https://user-images.githubusercontent.com/749374/88310894-830c1780-cd10-11ea-98a8-569356f41c6a.png)
> 
> As far as I know npm can only run registered scripts in package.json, so it does not work
> 
> But if I add this script: `"docusaurus": "docusaurus",` it now works:
> 
> ![image](https://user-images.githubusercontent.com/749374/88311008-a931b780-cd10-11ea-881c-d0e5ed7cbd1f.png)
> 
> Will add this script in the templates as it will be more convenient for npm users.
> 
> @teikjun in the migration cli PR, can you add it as well?
> 
> About the redirects plugin, I don't think it's related to the plugin. Anyway this plugin only works on the production build so it should have no impact if you start the site in dev mode.

Thanks very much. It works fine now.
![image](https://user-images.githubusercontent.com/15116881/88354255-f191b980-cd92-11ea-94c4-1e2329ab8c2f.png)


I saw the document on [docusaurus2](https://v2.docusaurus.io/docs/versioning/#tagging-a-new-version) website and then I check out the  [docusaurus2 project](https://github.com/facebook/docusaurus/tree/master/website) from GitHub, but undefined the `docusaurus ` scripts in the `package.json`.

**Comment by slorber** [comment]
great :) thanks
