### ISSUE TITLE
Incorrect section link behavior

### ISSUE THREAD

**Issue by teikjun** [facebook/docusaurus#3110]
## 🐛 Bug Report

The section links go to an incorrect route when targeting a section on the same page. The relative link is appended to the baseUrl instead of the current url.
For example: On https://v2.docusaurus.io/docs/configuration, `[site-metadata](#site-metadata)`  links to 
https://v2.docusaurus.io/#site-metadata instead of https://v2.docusaurus.io/docs/configuration#site-metadata

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## To Reproduce

1. Go to https://v2.docusaurus.io/docs/configuration
1. Click a section link e.g Site metadata (or any of the following links)
![image](https://user-images.githubusercontent.com/46853051/88329323-541b9300-cd5c-11ea-800b-957dfa7bdb82.png)

1. The link directs to https://v2.docusaurus.io/#site-metadata, which is incorrect.

## Expected behavior

 The link directs to https://v2.docusaurus.io/docs/configuration#site-metadata.

## Actual Behavior
The link directs to https://v2.docusaurus.io/#site-metadata. 

## Your Environment

- Docusaurus version used: -
- Environment name and version (e.g. Chrome 78.0.3904.108, Node.js 10.17.0): Firefox 
- Operating system and version (desktop or mobile): Windows

## Reproducible Demo
https://v2.docusaurus.io/docs/configuration

## Remarks
I think this issue might be a side-effect of the changes made in #3093

**Comment by slorber** [comment]
😔 Thanks will check tomorrow
