### ISSUE TITLE
Accessibility: CodeBlock theme-classic

### ISSUE THREAD

**Issue by NikitaIT** [facebook/docusaurus#3119]
Code block should be `code` or `pre`. 
**The simplest example of why:** use a translator or a reader.
**Expected:** The code section should not be translated.

https://github.com/facebook/docusaurus/blob/0eb9c207cf57a29dbd1f319a69eac6e71d77bd70/packages/docusaurus-theme-classic/src/theme/CodeBlock/index.tsx#L212

**Comment by McZenith** [comment]
I gat this...

**Comment by iamrubayet** [comment]
can i work on this ????

**Comment by slorber** [comment]
Yes @iamrubayet 

Note that someone already tried to work on this here:  https://github.com/facebook/docusaurus/pull/3178

**Comment by sidsharma22** [comment]
Hey, Is this is still an active bug right? I went through the #3178 comments to get a hang of it.

**Comment by slorber** [comment]
I think it's still a valid bug, but not sure as I don't know how to use a screen reader 😅
