### ISSUE TITLE
Add docusaurus.config.js override to the cli

### ISSUE THREAD

**Issue by Steven-Harris** [facebook/docusaurus#3122]
## 🚀 Feature

I have a couple of different environments I manage for development and I would like to be able to pass a config.js to the `docusaurus build` command to overrride the default path of docusaurus.config.js

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

yes.

## Motivation

fixability when building for different environments

## Pitch

`docusaurus build --config docusaurus-prod.config.js`

**Comment by slorber** [comment]
Hi

We could support this but you already can do something similar easily by
using environment variables.

In this config file you can run any node code including things like
process.env.MY_CONFIG_FILE

Le ven. 24 juil. 2020 à 22:50, Steven Harris <notifications@github.com> a
écrit :

**Comment by Steven-Harris** [comment]
Awesome! Thank you so much @slorber :D
