### ISSUE TITLE
PWA plugin - TypeError: Cannot read property 'debug' of null

### ISSUE THREAD

**Issue by hobadams** [facebook/docusaurus#3129]
## 🐛 Bug Report

I'm running `2.0.0-alpha.59` and have just added your PWA plugin.

I'm getting the following error:

```
sw.js:1 Uncaught (in promise) TypeError: Cannot read property 'debug' of null
    at VM3 sw.js:1
```

My docusaurus config looks like this:

```
plugins: [
    [
      "@docusaurus/plugin-pwa",
      {
        offlineModeActivationStrategies: ["always"],
        pwaHead: [
          {
            tagName: "link",
            rel: "icon",
            href: "/img/logo-512.png",
          },
          {
            tagName: "link",
            rel: "manifest",
            href: "/manifest.json",
          },
          {
            tagName: "meta",
            name: "theme-color",
            content: "#26642c",
          },
        ],
      },
    ],
  ],
```

I get the error regardless of passing `debug` as an option or not.

Have you see this?

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## To Reproduce

1. `yarn add @docusaurus/plugin-pwa`
2. Add the plugin to the docusaurus config
3. Create an icon + manifest.json and add to `static` directory
4. Build the app
5. Run the app

## Expected behavior

The service worker to not throw this error and install correctly

## Actual Behavior

The service worker throws an error and doesn't work.

<img width="474" alt="Screenshot 2020-07-27 at 11 10 50" src="https://user-images.githubusercontent.com/9551929/88530811-d7a5e000-cff9-11ea-9493-b5338a268444.png">

## Your Environment

- Docusaurus version used: 2.0.0-alpha.59
- Environment name and version (e.g. Chrome 78.0.3904.108, Node.js 10.17.0): Version 84.0.4147.89 (Official Build) (64-bit),
- Operating system and version (desktop or mobile): MacBook, MacOS Catalina 10.15.3, Desktop

Served locally or using Netlify

## Reproducible Demo

https://deploy-preview-41--deity-docs-prod.netlify.app/

**Comment by slorber** [comment]
🤪 this made me crazy for the last 2 hours

Your site tries to register the service worker himself already in the file src/ServiceWorker.js, which messes up totally with what our pwa plugin is doing.

You have to remove that registration code.

Noticed this non-blocking error too, will see how to fix it:

```
(undefined) ./node_modules/@docusaurus/plugin-pwa/src/sw.js 27:27-60
Critical dependency: the request of a dependency is an expression
(undefined) EnvironmentPlugin - PWA_SW_CUSTOM environment variable is undefined.
```

**Comment by hobadams** [comment]
@slorber - thank you and apologies!
