### ISSUE TITLE
Incorrect link of documentation in CONTRIBUTING.md

### ISSUE THREAD

**Issue by geekyd** [facebook/Docusaurus#313]
### Is this a bug report?
Yes.

Currently the link to the documentation is incorrect. The current link is `http://docusaurus.io/docs/` which gives Error 404. The link must be replaced with the correct url i.e `https://docusaurus.io/docs/en/installation.html`

(write your answer here)

### Have you read the [Contributing Guidelines](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md)?
Yes
(Write your answer here.)

### Environment
MacOs, node: v7.0, npm: 5.6.0, yarn 1.3.2 
(OS, Node, npm, yarn)

### Steps to Reproduce

(Write your steps here:)

1. Open contributing.md(https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md)
2. Click on Docusaurus docs in the Get involved section.

### Expected Behavior
The Url for docs should be `https://docusaurus.io/docs/en/installation.html`

(Write what you thought would happen.)

### Actual Behavior
Currently the link to the documentation is incorrect. The current link is `http://docusaurus.io/docs/`

(Write what happened. Add screenshots, if applicable.)

### Reproducible Demo

(Paste the link to an example project and exact instructions to reproduce the issue.)

**I would like to correct the url in contributing.md**

**Comment by neilsutcliffe** [comment]
Is this fixed in 2bc5438?

**Comment by neilsutcliffe** [comment]
Another issue. My bad. Will look into it

**Comment by geekyd** [comment]
@neilsutcliffe Can I send a PR for the Issue?

**Comment by neilsutcliffe** [comment]
I'm not working on it ATM so go right ahead. :)

**Comment by JoelMarcey** [comment]
@geekyd Awesome. I was just about to fix this, but I will wait for you. Thanks for the detailed issue, btw, even for a documentation fix. Much appreciated.

**Comment by geekyd** [comment]
Closing this via #314
