### ISSUE TITLE
ValidationError: "navbar.items.target" is not allowed

### ISSUE THREAD

**Issue by OctavianUrsu** [facebook/docusaurus#3139]
## 🐛 Bug Report

The following problem was encountered when upgrading to 2.0.0-alpha.59:

ValidationError: "navbar.items[1].target" is not allowed

I cannot add a target to the navbar link. The default is "_blank", but I would like the links to be "_self".

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## To Reproduce

(Write your steps here:)

1. Upgrade to  2.0.0-alpha.59
2. Attempt to start dev server with a navbar.item.target value on a href link.

## Expected behavior

Link gets target value of "_self"

## Actual Behavior

Getting this error:
ValidationError: "navbar.items[1].target" is not allowed

## Your Environment

Docusaurus version used: 2.0.0-alpha.59
Environment name and version (e.g. Chrome 78.0.3904.108, Node.js 10.17.0): Chrome 84.0.4147.89
Operating system and version (desktop or mobile): Mac OSX 10.15.5

**Comment by slorber** [comment]
Thanks,

That will be fixed in https://github.com/facebook/docusaurus/pull/3140

Can you tell me exactly what is the config of your navbar item?

**Comment by OctavianUrsu** [comment]
Thank you! This is my navbar item config:

{
    href: "https://github.com/OctavianUrsu",
    label: "GitHub",
    position: "right",
  },

**Comment by slorber** [comment]
Thanks, it should be possible to add a target as soon as we release

**Comment by slorber** [comment]
released in https://github.com/facebook/docusaurus/releases/tag/v2.0.0-alpha.60
