### ISSUE TITLE
BrowserOnly causes React error

### ISSUE THREAD

**Issue by ianschmitz** [facebook/docusaurus#3144]
## 🐛 Bug Report

The `BrowserOnly` component [returns `undefined` instead of `null`](https://github.com/facebook/docusaurus/blob/4247fc4bb13a628bc8229297af0467708aa83bbe/packages/docusaurus/src/client/exports/BrowserOnly.tsx#L19), which causes React to throw an error during a production build: 

> Error: Minified React error #152; visit https://reactjs.org/docs/error-decoder.html?invariant=152&args[]=BrowserOnly for the full message or use the non-minified dev environment for full errors and additional helpful warnings.Error: Minified React error #152; visit https://reactjs.org/docs/error-decoder.html?invariant=152&args[]=BrowserOnly for the full message or use the non-minified dev environment for full errors and additional helpful warnings.

This was changed in https://github.com/facebook/docusaurus/pull/2976.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## To Reproduce

Use `BrowserOnly` as suggested:

```tsx
<BrowserOnly>{() => <Foo {...props} />}</BrowserOnly>
```

and run a production build of docusaurus.

## Your Environment

- Docusaurus version used: 2.0.0-alpha.59
- Environment name and version (e.g. Chrome 78.0.3904.108, Node.js 10.17.0): Node 12.18.0
- Operating system and version (desktop or mobile): macOS 10.15.6

**Comment by slorber** [comment]
Thanks, totally agree: https://github.com/facebook/docusaurus/pull/3149
