### ISSUE TITLE
Be resilient to Swizzle case typos

### ISSUE THREAD

**Issue by slorber** [facebook/docusaurus#3148]
## 🐛 Bug Report

![image](https://user-images.githubusercontent.com/749374/88700540-22fae400-d109-11ea-93fd-89845ca4caf6.png)

![image](https://user-images.githubusercontent.com/749374/88701045-cb10ad00-d109-11ea-8e8a-907b08f6f022.png)

Swizzling a comp with bad casing lead to a component swizzled with a bad name.

Webpack aliases we use for themes are case-sensitive, so we should either:
- find a way to make webpack aliases not case-sensitive
- never create swizzled comps/folders with wrong case
- reject if user does a case-sensitive typo and suggest it the correct name

I thnk 2 and 3 are simpler options.

In any case I think it's not a very good idea to create a `theme/nAVbAR` folder, even if it's the case the user used.

Related: https://github.com/facebook/docusaurus/issues/3135
Related test: https://github.com/facebook/docusaurus/pull/3147

**Comment by FocalChord** [comment]
I will try work on this issue!

**Comment by FocalChord** [comment]
Any idea why I get this error?

![Screen Shot 2020-07-29 at 9 08 38 AM](https://user-images.githubusercontent.com/31643423/88722305-1dd67d00-d17b-11ea-8f8a-c47d862a94b1.png)

**Comment by slorber** [comment]
Thanks,

You have this error because of double VV, in addition to weird casing you have an additional letterr

**Comment by FocalChord** [comment]
Hmm, why does nAVbaR work but not nAVVbAr?

**Comment by anshulrgoyal** [comment]
@slorber My pr on swizzle should be merged first to avoid conflicts I think

**Comment by anshulrgoyal** [comment]
This is my pr for swizzle cli #3021

**Comment by slorber** [comment]
Yes we'll merge it first

> Hmm, why does nAVbaR work but not nAVVbAr?

@FocalChord this is expected, there's an additional letter here. You can't swizzle a component that does not exist in the first place, but you should be able to swizzle it if letters are ok but with an incorrect case

**Comment by FocalChord** [comment]
@slorber Hi, can we get Anshuls pull request merged in please

**Comment by slorber** [comment]
will try to review it asap, but this bug has higher priority: https://github.com/facebook/docusaurus/issues/3199

**Comment by slorber** [comment]
merged @FocalChord

**Comment by anshulrgoyal** [comment]
@FocalChord  are u still woking on it?

**Comment by FocalChord** [comment]
@anshulrgoyal yes

@slorber Hi, as seen in the screenshot below, I get this error now

![Screen Shot 2020-08-13 at 10 44 12 AM](https://user-images.githubusercontent.com/31643423/90075609-edcdd300-dd51-11ea-9b8d-c8bb9bb54d98.png)

**Comment by slorber** [comment]
@FocalChord I merged the PR of @anshulrgoyal that address this issue
