### ISSUE TITLE
v2: facebook template not working

### ISSUE THREAD

**Issue by yangshun** [facebook/docusaurus#3159]
## 🐛 Bug Report

Unable to start a website using the Facebook template via `@docusaurus/init`

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## To Reproduce

Both public and internal methods aren't working:

```
npx @docusaurus/init@next init website facebook
```

```
cd packages/docusaurus-init/templates/facebook && yarn start
```

## Expected behavior

Site runs

### Public

```
$ docusaurus build
Creating an optimized production build...
A validation error occured.
The validation system was added recently to Docusaurus as an attempt to avoid user configuration errors.
We may have made some mistakes.
If you think your configuration is valid and should keep working, please open a bug report.
ValidationError: "footer.links[3].items[0].target" is not allowed
error Command failed with exit code 1. 
```

### Internal

```
Starting the development server...
Error: The field(s) 'onBrokenLinks' are not recognized in docusaurus.config.js.
If you still want these fields to be in your configuration, put them in the 'customFields' attribute.
```

## Your Environment

v2.0.0-alpha.60

## Reproducible Demo

Refer to above.

This is because the footer links are still contains `target` and `rel` which are not allowed in the Joi schema. The error for the internal case is probably another related schema issue.

**Comment by yangshun** [comment]
This was reported by @brianjo internally. I told him to remove the offending fields in his `docusaurus.config.js` for now. Based on what I'm seeing in the theme footer implementation, not allowing users to customize `target` and `rel` is intended. So maybe we just have to update the template.

**Comment by slorber** [comment]
I don't think it's true, as we spread the props:

```
function FooterLink({to, href, label, prependBaseUrlToHref, ...props}) {
  const toUrl = useBaseUrl(to);
  const normalizedHref = useBaseUrl(href, {forcePrependBaseUrl: true});

  return (
    <Link
      className="footer__link-item"
      {...(href
        ? {
            target: '_blank',
            rel: 'noopener noreferrer',
            href: prependBaseUrlToHref ? normalizedHref : href,
          }
        : {
            to: toUrl,
          })}
      {...props}>
      {label}
    </Link>
  );
}
```

as we add _blank and noopener by default, it can be removed from the template, but I think we should allow users to override these defaults if he wants to.

Some users have recently reported wanting to use _self in the navbar for example, I wouldn't be surprised if the need exists for the footer too.

**Comment by yangshun** [comment]
> but I think we should allow users to override these defaults if he wants to.

Then we should add it to the Joi schema, it's currently preventing people from using those fields.
