### ISSUE TITLE
Image not loaded

### ISSUE THREAD

**Issue by leoigel** [facebook/docusaurus#3160]
## 🐛 Bug Report

The image of Polymatch network company not loaded
On user area (https://docusaurus.io/en/users) the image not loaded
## Expected behavior
The behavior i expected is to see the logo or at least some image

## Actual Behavior
![polyimage](https://user-images.githubusercontent.com/29859021/88884832-1036fb00-d240-11ea-99bd-b9be3988ef01.JPG)

## Your Environment

  This problem  occur on Chome and FireFox also occur on Desktop and Mobile

## Reproducible Demo

(Paste the link to an example repo, including a `siteConfig.js`, and exact instructions to reproduce the issue.)

**Comment by anshulrgoyal** [comment]
Hi
```
  {
    caption: 'Polymath Network',
    image: 'https://developers.polymath.network/img/text.svg',
    infoLink: 'https://developers.polymath.network',
    fbOpenSource: false,
    pinned: false,
  },

```
This the config provided by Polyamath. I checked image link it doesn't exists. You can provide an image or link we will add it.

**Comment by slorber** [comment]
If someone can submit a PR so that we self-host all images here, that would be more reliable than using images from other domains

**Comment by leoigel** [comment]
@slorber  you may explain in deep exactly you self-host all images?

**Comment by slorber** [comment]
I mean images are not on other domains, they are hosted within the Docusaurus site itself, put in the /static folder or something

**Comment by leoigel** [comment]
Ok, i will be glad to work on this.

**Comment by jhalak27** [comment]
@slorber I am new here, can I work on this?

**Comment by slorber** [comment]
Hi

@leoigel already claimed this issue.

If it's not handled this week, you can take it @jhalak27

**Comment by amrtachaurasia** [comment]
@slorber I have figured out the entire error, changes are ready and want to work on this

**Comment by slorber** [comment]
@amrtachaurasia I'm sorry but we don't need help anymore on this issue, as there is already a PR here https://github.com/facebook/docusaurus/pull/3200
