### ISSUE TITLE
Versions cannot be pinned as expected

### ISSUE THREAD

**Issue by BuckyMaler** [facebook/docusaurus#3161]
## 🐛 Bug Report

Pinning the versions of `@docusaurus/core` and `@docusaurus/preset-classic` results in different versions of `@docusaurus` packages being installed. I believe this is because of the version ranges specified in each package. For [example](https://github.com/facebook/docusaurus/blob/master/packages/docusaurus/package.json#L48).

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## To Reproduce

1. `npx @docusaurus/init@next init my-website classic`
2. In `package.json` change the versions of `@docusaurus/core` and `@docusaurus/preset-classic` to `2.0.0-alpha.59`
3. `yarn`
4. Peer into your `node_modules` or `yarn.lock`

## Expected behavior

Pinning the versions of `@docusaurus/core` and `@docusaurus/preset-classic` results in all `@docusaurus` packages being the same version.

## Actual Behavior

Pinning the versions of `@docusaurus/core` and `@docusaurus/preset-classic` results in different versions of `@docusaurus` packages.

If I'm not missing something and this isn't expected, then I'd be happy to open a PR. I'm eager to make my first contribution.

**Comment by slorber** [comment]
Hi

I'm not sure what we can do about this.

Isn't it a package manager potential bug instead?

Can you upload your attempt to a repo? That's a more reliable repro case

Le jeu. 30 juil. 2020 à 08:09, Bucky Maler <notifications@github.com> a
écrit :

**Comment by BuckyMaler** [comment]
@slorber I just opened a PR because I think it's as easy as pinning the versions inside of each package's `package.json`. I don't think it's a package manager bug.
