### ISSUE TITLE
How to custmize the message in PWA update

### ISSUE THREAD

**Issue by araczkowski** [facebook/docusaurus#3167]
## ❓ Questions and Help

I would like to change this message:

https://github.com/facebook/docusaurus/blob/0e0b219a549ff222632f17c30ccea9b7ca4783b4/packages/docusaurus-plugin-pwa/src/theme/PwaReloadPopup/index.js#L19

any hint how to do this correctly? Thx

**Comment by slorber** [comment]
Hi, for now we don't offer a way to customize this component with configuration, but you can swizzle it to change the design or wording
