### ISSUE TITLE
Allow defining which version is "unmaintained" on the banner

### ISSUE THREAD

**Issue by eriveltonelias** [facebook/docusaurus#3169]
## Motivation

After this PR https://github.com/facebook/docusaurus/pull/2916 every version that isn't the latest one, is considered as unmaintained ( which is cool ), but on react navigation we still maintaining two versions **v4** and **v5** 

## Pitch

 will be nice to define which version still maintained or unmaintained ( it will solve this use case ), maybe on docusaurus config or versions ?

**Comment by slorber** [comment]
There's a DocVersionSuggestions for that banner, you can probably swizzle it and make sure it displays nothing for a specific version.

If you feel we should provide a config option, curious to know what kind of api you have in mind exactly?

**Comment by eriveltonelias** [comment]
> There's a DocVersionSuggestions for that banner, you can probably swizzle it and make sure it displays nothing for a specific version.

Could you explain a little bit more about the DocVersionSuggestions? 

if we swizzle it, the changes will be global for every type of banner? or it is flexible to change only the "unmaintained"? ( because this banner seems hardcoded )
> 
> If you feel we should provide a config option, curious to know what kind of api you have in mind exactly?
> 
I have two in mind:

1. add it to `versions.json` and it could be something like this:
```js
[
    "2.0.0-alpha.60",
    "2.0.0-alpha.58",
     {
        version:   "2.0.0-alpha.56",
        unmaintained: true // it will make to show the banner
     },
     ...
 ]
```

2. add it on `themeConfig` 
```js
unmaintained: [  
  "2.0.0-alpha.56",
  "2.0.0-alpha.55",
  "2.0.0-alpha.54" 
]
```

I don't like the first option because it will be a huge breaking change and it will be required to do unnecessary changes and mix of types in here will not be good. 

but the second option will be simpler to implement since we'll get this info directly from the config.

**Comment by eriveltonelias** [comment]
@slorber definitely swizzle `DocVersionSuggestions` solve the problem and I don't think is really necessary this config since is so flexible, thanks!

**Comment by slorber** [comment]
Great to know

The problem with Swizzle is that the API surface is less clear and we might do breaking changes on updates,  but this shouldn't be too hard to handle by reswizzling and comparing diffs
