### ISSUE TITLE
Links to sections in other pages

### ISSUE THREAD

**Issue by rauanmayemir** [facebook/Docusaurus#317]
### Is this a bug report?

I'm not sure if this is a bug-report or a feature-request, somewhat both.

### Have you read the [Contributing Guidelines](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md)?

Yes.

### Environment

`docusaurus@1.0.3`
`node@v.8.9.1`
`yarn@1.3.2`

### Steps to Reproduce

If I add a link in one docs page to another, let's say, in `configuration.md` I'll write
```
See the [environment](environment.md).
```

The link in the markdown chunk above will perfectly be translated into `/docs/en/environment.html`.

But if I use

```
See the [environment](environment.md#variable-substitution-syntax).
```

The link will direct not to the `environment.html`, but to `/docs/en/configuration.html#variable-substitution-syntax`. I.e hashes are breaking the parser.

### Reproducible Demo

https://github.com/rauanmayemir/esy.github.io/blob/source/docs/configuration.md#esybuild (the link in the end of the section.)

**Comment by rauanmayemir** [comment]
This is reproducible on the latest `docusaurus@1.0.3`.

**Comment by rauanmayemir** [comment]
I'm sorry, there were two instances of that link in the text and I was looking at the wrong one.

**Comment by JoelMarcey** [comment]
Thanks @rauanmayemir for filing the issue with such detail even though it didn't end up being an issue. I was worried for a bit there because I thought we had supported links to anchors like that.
