### ISSUE TITLE
Deprecated dependencies in V1

### ISSUE THREAD

**Issue by amimas** [facebook/docusaurus#3170]
## 🐛 Bug Report

I'm doing a fresh installation of Docusaurus V1. Running `yarn install` produces following warnings about some of the dependencies that are deprecated.

```text
warning docusaurus > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
warning docusaurus > crowdin-cli > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
warning docusaurus > @babel/polyfill > core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
warning docusaurus > request > har-validator@5.1.5: this library is no longer supported
warning docusaurus > markdown-toc > gray-matter > coffee-script@1.12.7: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)
warning docusaurus > react-dev-utils > fork-ts-checker-webpack-plugin > chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
warning docusaurus > markdown-toc > remarkable > autolinker > gulp-header@1.8.12: Removed event-stream from gulp-header
warning docusaurus > react-dev-utils > fork-ts-checker-webpack-plugin > chokidar > fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
warning docusaurus > react-dev-utils > fork-ts-checker-webpack-plugin > micromatch > snapdragon > source-map-resolve > urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
warning docusaurus > react-dev-utils > fork-ts-checker-webpack-plugin > micromatch > snapdragon > source-map-resolve > resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
```

I understand that most of the deprecation is coming from transitive dependencies. If those direct dependencies have been updated already, it'd be good to update Docusaurus V1 to use the latest version.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## To Reproduce

Follow regular install/setup process for Docusaurus V1 as per documentation.

## Expected behavior

No warnings about deprecated libraries

## Actual Behavior

Seeing warnings about some of the libraries being used but have been deprecated already.

## Your Environment

- Docusaurus version used: V1
- Environment name and version (e.g. Chrome 78.0.3904.108, Node.js 10.17.0):
- Operating system and version (desktop or mobile):

OS: CentOS Linux release 7.4.1708 (Core)
Node: 12.14.1
Yarn: 1.21.1

Since V2 of Docusaurus is still in alpha stage, I'm not able to upgrade yet. I still need to use V1 because that's the only "production ready" version currently available. It'd be great if V1 could still be maintained a littte bit by applying various bug-fixes.

**Comment by slorber** [comment]
@amimas , are these warnings annoying you in practice?

I agree that it is annoying to see these warnings, however we can't always easily do something about it. See related issue: https://github.com/facebook/docusaurus/issues/3095

v1 is still maintained but it's not our primary focus to invest too much time in it. If you feel these problems are important to you, please send a pull request and help us solve

v2 is stable enough to use it in production, we keep alpha flag mostly because there is not a 100% feature parity with v1 (i18n) and because there might still be a few breaking changes here and there about versioning.

I'm closing, but PRs to solve this problem are welcome

**Comment by amimas** [comment]
Thanks @slorber  for looking into it. It's not really a matter of annoyance. I like to make sure my tools have up-to-date dependencies. It's a good practice I'm sure you'll agree.

I'm really glad to hear that V1 is still maintained. I'll be happy to send a PR when I'm back online again.
