### ISSUE TITLE
Algolia search does not find code in code blocks?

### ISSUE THREAD

**Issue by slorber** [facebook/docusaurus#3172]
## 🐛 Bug Report

Search for beforeDefaultRemarkPlugins

This term exist here in a code block: https://v2.docusaurus.io/docs/using-plugins/#docusaurusplugin-content-blog

**Comment by slorber** [comment]
@francoischalifour any idea?

**Comment by anshulrgoyal** [comment]
the code block is not scrapped by default

**Comment by anshulrgoyal** [comment]
u need to add it scrap config

**Comment by s-pace** [comment]
👋 @slorber and @anshulrgoyal,

I am part of the DocSearch team.

Usually [we do not recommend indexing code samples](https://docsearch.algolia.com/docs/faq/#can-you-index-code-samples). These samples are often very similar and duplicated along your documentation such as examples. It introduces noise to the user experience. Displaying matching code would require to enlarge the snippeting to give the context of the matching token.
There is also room for improvement in the way we handle special characters such as dot and dash that can’t be interpreted as separators yet. This is an improvement that we’re investigating on.

**Comment by anshulrgoyal** [comment]
Hi @s-pace, 
I  am trying to build an offline search feature for docusaurus. Here is the PR https://github.com/facebook/docusaurus/pull/3153 and https://deploy-preview-3153--docusaurus-2.netlify.app are deployed link. It would be great if u can give some feedback.

**Comment by slorber** [comment]
Hi @s-pace 

Wonder if you have an idea to index correctly API items that are only found in code-block? Do we rather document everything outside of code blocks too?

**Comment by s-pace** [comment]
I would definitely recommend to document all API items outside of code-block. It enables a better UX to redirect end users with scrolling to the exact matching item. It also helps to give the context of the matching item when the search query is matching the description of the API item. Last but not least, the relevancy would be better since [matching a `lvl3` / `<h3/>` element](https://github.com/algolia/docsearch-configs/blob/master/configs/docusaurus-2.json#L19) has a stronger impact on the ranking formula.

**Comment by slorber** [comment]
Thanks

Closing this, but we'll need to document better some attributes that are only found in code blocks

**Comment by s-pace** [comment]
👋 @slorber 
Just a follow up that thanks to algolia/docsearch-configs@cfc57386b1e8845231468b5206ca55829ba0d263 we are now indexing CLI options such as `--skip-build`
![image](https://user-images.githubusercontent.com/32097720/89278888-fa15aa00-d646-11ea-8fca-3bd9190da66d.png)

**Comment by slorber** [comment]
thanks

wonder what you can do for the original usecase I had ^^ (beforeDefaultRemarkPlugins)

**Comment by s-pace** [comment]
👋  @slorber 

`beforeDefaultRemarkPlugins` is too much present within the page. Elements matching `[class^='codeBlockContent_']` selector are too similar and it degrades the search experience. Last but not least, we [recommend that selectors match small piece of text to enhance the relevancy](https://docsearch.algolia.com/docs/required-configuration/#use-the-right-classes-as-selectors). These code blocks are too long.
