### ISSUE TITLE
src/page/_myComponent => do not create page

### ISSUE THREAD

**Issue by slorber** [facebook/docusaurus#3173]
## 🚀 Feature

Currently when we put any js/jsx/ts/tsx/md/mdx in src/pages, it creates a page, which encourage the users to create very large files and not split in subcomponents.

We should provide a way to create components in src/pages without creating pages, just so that they can be imported in pages.

I have often seen _ being used as a prefix to say that a file is a "partial" (another term somehow for component).

I don't have a good link but you'll find this term in the LESS community: https://github.com/FortAwesome/Font-Awesome/issues/4907

I think we should adopt it (or a similar convention), and make sure that the following do not create pages:

- `src/pages/_myComponent.jsx`
- `src/pages/_components/Button.jsx`
- `src/pages/_components/buttons/PrimaryButton.jsx`

It is also useful for markdown pages (https://github.com/facebook/docusaurus/pull/3158) because afaik one markdown file can import another markdown, which permits to slice a document in multiple parts:

- `src/pages/_firstChapter.md`
- `src/pages/_partials/chapters/firstChapter.md`

---

We can define a rule like:

```
const shouldCreatePage = ![...getFolders(filepath),getFilename(filepath)].some(str => str.startsWith("_")
```

**Comment by anshulrgoyal** [comment]
I will take it.

**Comment by Tundeh** [comment]
Can i work on this?

**Comment by anshulrgoyal** [comment]
I forget to attach the PR @Tundeh it is already fixed

**Comment by Tundeh** [comment]
Ok
