### ISSUE TITLE
The validation system prevents my website from starting after upgraded to 2.0.0-alpha.59

### ISSUE THREAD

**Issue by Kimi-Gao** [facebook/docusaurus#3174]
## 🐛 Bug Report

I used `swizzle  component` to customize my Footer and also added some special configuration in `docusaurus.config.js`. However, the validation system prevents my website from starting after upgraded to 2.0.0-alpha.59

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## Actual Behavior

![image](https://user-images.githubusercontent.com/12554487/88990415-7b500280-d310-11ea-916d-235aea7b3526.png)

## Your Environment

- Docusaurus version used: 2.0.0-alpha.59
- Environment name and version (e.g. Chrome 78.0.3904.108, Node.js 10.17.0): -
- Operating system and version (desktop or mobile): -

**Comment by anshulrgoyal** [comment]
It is not a bug. You should use `customField` instead of `footer` to add `icp` field.

**Comment by Kimi-Gao** [comment]
@anshulrgoyal thanks, it works.
