### ISSUE TITLE
Allow Search page to be swizzled

### ISSUE THREAD

**Issue by martavis** [facebook/docusaurus#3176]
## 🚀 Feature

Add the ability to swizzle the Search page created by `@docusaurus/theme-search-algolia`.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## Motivation

Personal motivation comes from the need to wrap an auth component around search functionality, and not wanting/needing to change the overall feel of the page.

## Pitch

Similar to DocPage, Search has wonderful functionality but may need to be tweaked to fit certain requirements of the dev, such as authentication, filters, and other components to make a custom solution.

**Comment by Ako92** [comment]
I can work on this

**Comment by slorber** [comment]
OK 👍

**Comment by Ako92** [comment]
Swizzle?? Can yo explain it more please?

**Comment by martavis** [comment]
Swizzling: https://v2.docusaurus.io/docs/using-themes#swizzling-theme-components

**Comment by slorber** [comment]
Basically this is just moving the SearchPage comp to the ./theme folder so that the swizzle cli can swizzle it

**Comment by Ako92** [comment]
Is this what I have to do?

![image](https://user-images.githubusercontent.com/24778140/89736380-3c434f00-da7e-11ea-973e-8258aa2809fc.png)

**Comment by slorber** [comment]
yes, and very that swizzling actually works (I may be wrong, you have to test the workflow)

**Comment by anshulrgoyal** [comment]
I will take it. If nobody is working on it. I will refactor it a bit in smaller components so it can be swizzled easily

**Comment by Ako92** [comment]
Pull Request:
https://github.com/facebook/docusaurus/pull/3280
