### ISSUE TITLE
After opening the dropdown menu from nav with keyboard, it doesn't collapse back if I click anywhere else by mouse.

### ISSUE THREAD

**Issue by mdfaizan7** [facebook/docusaurus#3177]
## 🐛 Bug Report

After opening the dropdown menu from nav with keyboard, it doesn't collapse back if I click on anywhere else by mouse

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## To Reproduce

1. Use the Tab key to open the dropdown menu on the nav.
2. Click on the screen outside the menu.

## Expected behavior
When mouse key is pressed outside the dropdown menu, the menu should have collapsed.

## Actual Behavior
The dropdown menu did not collapse and stayed opened. Even if I again clicked the menu with my mouse, it did not collapse.

## Your Environment

- The bug shows up on both https://v2.docusaurus.io/docs and a locally installed Docusaurus v2
- Laptop Windows 10
- This issue was reproducible on both Firefox and Chrome.

## Reproducible Demo

You can see this bug in the <a href="https://v2.docusaurus.io/docs/">documentation</a> itself.

![2020-07-31 14-40-13](https://user-images.githubusercontent.com/42090492/89021573-65593680-d33e-11ea-89a1-a1bdff6aaab7.gif)

**Comment by slorber** [comment]
thanks, definitively a bug to fix

**Comment by Ako92** [comment]
I want to Handle this problem. can you assign it to me?

**Comment by slorber** [comment]
Yes, thanks 😜

**Comment by Ako92** [comment]
I'm working on it
What is the expected behavior? There is two options:
1. Remove the tab key press functionality on DropDown
2. Add eventListener on window to toggle className "dropdown--show" if exists!

If  you have any other solution please share it with me.

**Comment by slorber** [comment]
Thanks for working on this.

I'm not very comfortable with the current code that mutates the dom directly. Would be cool to refactor this and add some proper React state. 

We should be able to use the dropdown without a mouse for accessibility, so the 2nd solution looks better to me. I've used such libs successfully in the past: https://github.com/Andarist/use-onclickoutside

**Comment by Ako92** [comment]
https://github.com/facebook/docusaurus/pull/3240 Pull request Link.
This is my first pull request on open source community. If there's any problem, let me know.
Thanks

**Comment by mdfaizan7** [comment]
Thank You for the pull request @Ako92. It looks like this bug is fixed. Good Job 👍

**Comment by Ako92** [comment]
Problem Fixed  and merged.
You can close issue!
