### ISSUE TITLE
Render the tabs only once

### ISSUE THREAD

**Issue by Mihonarium** [facebook/docusaurus#3181]
## 🚀 Feature

To render all the TabItems instead of rendering just the default one, so click on a tab label just changes what tab is visible instead of triggering the rendering of the tab in the runtime of users' browsers.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes.

## Motivation

With a large code block under a tab, there's a lag between clicking on a tab and the tab being shown. 

## Pitch

If all the tabs are being rendered and clicking on a label just changes what tab is visible instead of rendering a new tab, it would:
- allow search engines to access the content of the tab (currently, only the content of the default tab is rendered in HTML),
- get rid of noticeable and annoying time between the tab being clicked and being shown when the tab rendering takes some time (e.g. if there's a large code block).

**Comment by slorber** [comment]
A problem is: rendering all tabs ahead of time can also introduce a lag when we navigate to a large page with a lot of tabs in it :)  

Maybe we could have an option to make them render more lazily, but not sure this would play well with server-side rendering, SEO and hydratation...

**Comment by lex111** [comment]
Implemented in #3706.

**Comment by Mihonarium** [comment]
> Implemented in #3706.

Good job, thanks!
