### ISSUE TITLE
Improve details about Travis CI deployment in docs

### ISSUE THREAD

**Issue by LittleboyHarry** [facebook/docusaurus#3189]
## 📚 Documentation

I followed the Travis CI deployment steps:

https://v2.docusaurus.io/docs/deployment/#triggering-deployment-with-travis-ci

The problem is that **you have to allow more permissions scopes in personal access token** for successful building, otherwise build fail:

![image](https://user-images.githubusercontent.com/13063376/89113870-ec2a2280-d4a8-11ea-8e2f-57eea3cd7378.png)

Edit my token access permission in GitHub: (**Maybe less permissions** also work successfully)

![image](https://user-images.githubusercontent.com/13063376/89113903-40350700-d4a9-11ea-9e2c-5ae56d70225c.png)

![image](https://user-images.githubusercontent.com/13063376/89113916-580c8b00-d4a9-11ea-9e15-18b643ebd064.png)

Passed!

**I think it is necessary to explain this clearly in the docs.**

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

**Comment by slorber** [comment]
Hi,

Agree we could do a better job here, can you help us improve this part of the doc by submitting a PR?

Maybe we could create a full section about github token creation, as it's also used on the Azure deployment doc (looks like a copy/paste)

**Comment by jordanliu** [comment]
@LittleboyHarry need help with the PR?
