### ISSUE TITLE
Binary distribution / build step without needing to install node

### ISSUE THREAD

**Issue by steveklabnik** [facebook/docusaurus#319]
Hey there! Thanks for Docusaurus, it looks great!

This is sort of a non-time sensitive feature request. Is there any good solution, or plans, to distribute a Docusaurus binary?

I have an environment where a Node dependency is, well, maybe not an *absolute* dealbreaker, but a big 👎 in the overall decision. This is really about just the build step. I would rather not try to re-implement it, of course 😄  *using* node isn't the problem here, it's requiring people to install the node runtime.

I completely appreciate if this is outside of the scope of the project.

**Comment by JoelMarcey** [comment]
@steveklabnik That's a good question. We haven't thought about a pre-built Docusaurus binary for our launch, but I suppose it is something we could consider. Let me talk to some other folks on the team about this.

**Comment by amimas** [comment]
I'm currently trying out Docusaurus and if I end up using this, I'd probably use Gradle as the actual build tool. There are node plugin available for Gradle so that users/developers/contributors/CI-environments don't need node installed and you can execute all the npm/yarn commands.

**Comment by SimenB** [comment]
Just https://github.com/zeit/pkg?
