### ISSUE TITLE
Github delpoy not workig

### ISSUE THREAD

**Issue by AlexaCodex** [facebook/docusaurus#3190]
Deployed website using Version: 2.0.0-alpha.61 , page is getting rendered like below:

![image](https://user-images.githubusercontent.com/4513589/89134650-824c6000-d51e-11ea-95b2-ed7ac6952fab.png)

What setting should be used now that github pages are on : username.github.io?

**Comment by slorber** [comment]
Hi,

Please provide more information, it's hard to do anything with such a bug report. A link to a public github repo, or an URL to the site is the minimum

**Comment by AlexaCodex** [comment]
Hi @slorber this is the link : https://alexacodex.github.io/exampledocusau/docs/

**Comment by kyfelipe** [comment]
@AlexaCodex The request for static files is wrong, correct `baseUrl` for '/repo_name' . In your case, place baseUrl: '/exampledocusau/' in docusaurus.config.js

**Comment by AlexaCodex** [comment]
@kyfelipe thanks for suggestion. Unfortunately, it's still broken after baesurl change.

**Comment by slorber** [comment]
@AlexaCodex you don't make my life easy, I had to find your source code (that I asked you to provide) myself: 
https://github.com/AlexaCodex/exampledocusau

This is clearly a baseUrl issue.

We can see that you changed the baseUrl on master, but you didn't redeploy to the gh-branch according to commit dates.
