### ISSUE TITLE
Migrate ReactNative website to Docusaurus v2

### ISSUE THREAD

**Issue by slorber** [facebook/docusaurus#3195]
## 💥 Proposal

Migrate the ReactNative website ([repo](https://github.com/facebook/react-native-website)) to Docusaurus v2.

This site is a complex versioned site, but has no i18n, so we can normally migrate it today.

It is a good test to try the new migration cli, and see if Docusaurus v2 has good enough feature parity with v1.

I'd like the Major League Hacking community folks to work on this migration.

---

Rachel Nabors (@rachelnabors) and  Bartosz Kaszubowski (@Simek here and on Discord) are helping to maintain the v1 site.

Some important things to consider:

- v1 has many (too much) versions, and a long build time in the CI (30-90min). We don't need to support all these versions, we can only keep versions from 0.60 and "archive" older versions as a standalone v1 site
- there's a requirement to generate all the missing pages, for all the versions (???)
- custom Prism setup and SnackPlayer (see [remarkable plugins](https://github.com/facebook/react-native-website/blob/master/website/core/RemarkablePlugins.js))
- custom JS files [here](https://github.com/facebook/react-native-website/tree/master/website/static/js)
- static files to redirects moved/renamed docs ([here](https://github.com/facebook/react-native-website/tree/master/website/static/docs)) => should be easy to handle with the client side redirect plugin.

---

The ReactNative docs are actively edited, so for this migration, we should not focus our initial efforts on fixing the content related issues (md -> MDX), but rather try to focus our efforts on the infrastructure, and handle the changes on the content/docs only once the rest is handled.

**Comment by teikjun** [comment]
I'll work on this :) 
@darshkpatel is interested to help too!

**Comment by slorber** [comment]
thanks :) can you open a draft/PR branch asap so that we can track/review progress?

**Comment by teikjun** [comment]
We're keeping track of the migration here: https://github.com/MLH-Fellowship/react-native-website/pull/37
