### ISSUE TITLE
Static assets doc on 2 pages

### ISSUE THREAD

**Issue by slorber** [facebook/docusaurus#3198]
## 📚 Documentation

The static assets doc from there: 
https://v2.docusaurus.io/docs/markdown-features#assets

Should probably be merged into:
https://v2.docusaurus.io/docs/static-assets/#jsx-example

(this is not a doc-only feature btw)

Anyone interested to do this merge and improve our doc?

**Comment by teikjun** [comment]
Yes, I'll work on this :)

**Comment by anshulrgoyal** [comment]
MDX feature page is getting quite big. We should split it and create a new category. We can move it out of Docs catogory also since now Pages also support MDX.

**Comment by anshulrgoyal** [comment]
Creating a new MDX category should be noce for users searching reading docs.

**Comment by slorber** [comment]
Yes I agree, but we shouldn't use a page for that because the mdx features are version-dependant.

A new sidebar category would be nice. We need a clear distinction of what md features are general, and which ones are doc-related (docs have additional features around linking using .md file paths, relative linking advised so that linking still work once the docs are versioned etc...)

**Comment by anshulrgoyal** [comment]
Yeah, making more categories help in organizing docs.

**Comment by BogdanDor** [comment]
Section assets was moved to https://docusaurus.io/docs/markdown-features/assets in https://github.com/facebook/docusaurus/pull/3975. 
Maybe this issue not actual anymore and could be closed.

**Comment by Josh-Cena** [comment]
We still have https://docusaurus.io/docs/static-assets and https://docusaurus.io/docs/markdown-features/assets. I don't think it's very problematic considering the logic behind them, but the issue is still valid.

**Comment by slorber** [comment]
Moving everything to markdown-features/assets probably doesn't make sense, considering assets can also be handled in React/pages.

We should probably move all markdown-related things out of https://docusaurus.io/docs/static-assets, and just link the 2 pages together
