### ISSUE TITLE
Let Algolia to index text in `` code quoted blocks

### ISSUE THREAD

**Issue by avkonst** [facebook/docusaurus#3203]
## 🚀 Feature

I have followed the best practice and included all variables, CLI options, and all other technical words and text snippets into a singe or triple code quotes:

```
`example_variable`
```

Later I have enabled Algolia search and discovered that text in code blocks is not indexed by Algolia at all. Here is the example page from docusaurus docs https://v2.docusaurus.io/docs/cli/#docusaurus-build. Try to search by 'swizzleComponent' or 'bundle-analyzer' or any other text in code quotes => and watch that Algolia misses the related results.

I am not sure if it is something Docusaurus can do... However, I have not found a way to workaround it. Support from Algolia Docsearch recommended to move the text out of code block quotes, but it is not possible as code formatted / styled blocks exist for a valid purpose.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## Motivation

Enable better docs search

## Pitch

If this feature is implemented, it will enable results for a search by variable / function names, which are frequently code-quoted in technical docs.

**Comment by slorber** [comment]
Hi

Recently opened a similar issue here: https://github.com/facebook/docusaurus/issues/3172

But Algolia does not recommend it: https://docsearch.algolia.com/docs/faq/#can-you-index-code-samples

We should definitively make all things searchable, but it looks like indexing code blocks is not the solution

**Comment by slorber** [comment]
If you really want this and come up with a PR with an opt-in option to index code blocks, I could merge this, but not confortable making this a default when it's not recommended

**Comment by avkonst** [comment]
I think the code in single quotes does not cause a problem as the recommendation was likely provided for the multi-line code blocks. Single quote inline code strings are usually used for styling purposes and not for the purpose to provide comprehensive examples.

Multi-line code blocks could have per block opt-in option, for example `searchable`:

```js searchable
function sum(arg1, arg2) {
    return arg1 + arg2;
}
```

Makes sense?

**Comment by slorber** [comment]
@avkonst the Docusaurus v2 algolia config is open-source: https://github.com/algolia/docsearch-configs/blob/master/configs/docusaurus-2.json

Feel free to submit a PR if you think it can improve the indexation, or discuss with @s-pace from Algolia. 

Unfortunately, I'm not very familiar with all that, and can't dedicate too much time on this, as I need to work on i18n support

**Comment by avkonst** [comment]
Thanks. I have found a config for my project too, but do not understand it
too. I guess I will workaround it somehow.
