### ISSUE TITLE
PWA offline mode does not work

### ISSUE THREAD

**Issue by Kimi-Gao** [facebook/docusaurus#3208]
## 🐛 Bug Report

PWA offline mode does not work after being installed from chrome url

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## Reproducible Demo

```
offlineModeActivationStrategies: ['appInstalled', 'queryString'],
```

![v2=bug](https://user-images.githubusercontent.com/12554487/89305140-dbdc9800-d6a0-11ea-977b-929592a31dfb.gif)
![Xnip2020-08-04_21-16-39](https://user-images.githubusercontent.com/12554487/89305168-e6972d00-d6a0-11ea-9dc5-7193c1eeeaf0.jpg)

**Comment by slorber** [comment]
Hi,

Have you tri
![image](https://user-images.githubusercontent.com/749374/89308104-28f54580-d672-11ea-8c97-e42989fda959.png)

Why is it written "trying to install" here?

Can you try again, but make sure that the new service worker that is setup after installing the app is fully installed. Maybe the service worker didn't have time to download all the assets locally, and you put it offline before?

**Comment by Kimi-Gao** [comment]
@slorber Thanks for your answering. 

I agree that offline mode sometimes does not work because the app is not fully installed.

Here is what I have met. When I installed the app and first opened it, there was an error on the console:
![image](https://user-images.githubusercontent.com/12554487/89312544-f7986c00-d6a9-11ea-876a-edc1a4106f6f.png)
and offline didn't work, but when refreshed, all the assets can be downloaded locally and offline mode worked fine(sometimes easy to download sometimes not, especially put it offline before).

So my question is: what we can do to make sure it can be fully installed as soon as possible? Is it due to my network issue? Thanks.

**Comment by slorber** [comment]
Can you turrn debugging on in the PWA plugin options? And give me some more verbose console output?

**Comment by Kimi-Gao** [comment]
@slorber  FYI
![image](https://user-images.githubusercontent.com/12554487/89436777-47923400-d779-11ea-8645-1c79c8b7bc97.png)
![image](https://user-images.githubusercontent.com/12554487/89436863-6395d580-d779-11ea-90fe-20b99fdc8267.png)

**Comment by slorber** [comment]
@Kimi-Gao having the link to your site deployment / repo would also be helpful

**Comment by Kimi-Gao** [comment]
@slorber  https://deploy-preview-347--thinkbucket.netlify.app  see more at this [PR](https://github.com/ThinkBucket/docsite/pull/347)

**Comment by slorber** [comment]
Thanks for the detailed infos, really helpful.

Will take a look next week
