### ISSUE TITLE
open the browser on latest instead of last release on `docusaurus start`

### ISSUE THREAD

**Issue by zepatrik** [facebook/docusaurus#3212]
## 💥 Proposal

When running `docusaurus start` the browser should open the latest tag instead of the last release. For people working only from time to time with docusaurus it is confusing that they don't see their changes and they spend time debugging why the change is not there.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

yes

**Comment by zepatrik** [comment]
Btw I'm happy to contribute this proposal is accepted.

**Comment by slorber** [comment]
Hi @zepatrik . I totally agree and it's a chance I've planned to do as part of other things to change about docs/versioning.

As it's already something I have in mind, I'd prefer to work on this myself so that the API of all the features look consistent

**Comment by slorber** [comment]
@zepatrik can you tell me what you think of this RFC? 

https://github.com/facebook/docusaurus/issues/3212

**Comment by Josh-Cena** [comment]
Docusaurus uses this:

```js
lastVersion: process.env.NODE_ENV === 'development' ? 'current' : undefined,
```

This looks quite extensible and should be practiced

**Comment by zepatrik** [comment]
So if I run `NODE_ENV='deveolpement' docusaurus start`, it will open the latest unreleased page?

**Comment by Josh-Cena** [comment]
Well, you don't even need to—`docusaurus start` sets `NODE_ENV='development'` by default
