### ISSUE TITLE
[Chore] version released without/before changelog

### ISSUE THREAD

**Issue by noraj** [facebook/docusaurus#3217]
Seems a version 1.14.6 is out and released on npmjs

https://app.renovatebot.com/package-diff?name=docusaurus&from=1.14.5&to=1.14.6

https://www.npmjs.com/package/docusaurus

![image](https://user-images.githubusercontent.com/16578570/89435715-8908ec00-d745-11ea-920c-d81b404bbe32.png)

But not github release, no git tag, not changelog entry yet.

https://github.com/facebook/docusaurus/releases
![image](https://user-images.githubusercontent.com/16578570/89435785-9d4ce900-d745-11ea-8d93-c22401309826.png)

![image](https://user-images.githubusercontent.com/16578570/89435826-adfd5f00-d745-11ea-961a-2754af94e8d0.png)

So automatic update helpers like dependabot or renovate bot will raise a new update notification.

![image](https://user-images.githubusercontent.com/16578570/89435885-c5d4e300-d745-11ea-9d8e-3f389c6e8475.png)

But not changelog it available so one doesn't not what the new update will bring without reading the commits themselves.

**Comment by slorber** [comment]
Hi, I'm sorry, there is a delay between the changelog / Github release and the publication, because the release PR did include some update to the publication guide: https://github.com/facebook/docusaurus/pull/3218

Now it is ok, and the interval without available changelog would be shorter on next release.

The process can be enhanced, but I don't think we can atomically publish + push the changelog + create the GitHub release all at the exact same time :)

**Comment by noraj** [comment]
> The process can be enhanced, but I don't think we can atomically publish + push the changelog + create the GitHub release all at the exact same time :)

Usually many projects publish the changelog update in the same PR or even as part of the commit. So when the feature PR is merged the associated documentation & changelog is merged as well.
What is the interest of separating documentation and changelog update of the feature update in different PRs?

The most important thing is that the changelog is available when the new release is spread, but to go farther it's easy to push the the git tag (not the github release) at the same time:

```
$ git tag -a vx.x.x
$ git push --follow-tags
```

> I think it is better to publish the release first, and then the changelog / Github Release, than the opposite where users could get a github release notification yet the code is not published yet

I agree, Publishing the changelog before the feature doesn't make sense. But why not pushing it at the same time?
Actually I'm used to see projects that push code + doc/changelog + git tag/github release but have several days of delays before publishing the new release on package website like nmpjs, rubygems, pypi etc.
It's often more complicated to have the release pushed on those platforms automatically or quickly than pushing the chore stuff on git as part of the update. But here the npmjs release is out even before the upstream github release was created.

**Comment by slorber** [comment]
> But why not pushing it at the same time?

"at the same time": unfortunately I can't guarantee 0sec there.

The changelog came a bit later for this release, because I was also updating the publish doc in the release PR (which I maybe shouldn't have do). 

Next releases the interval will be smaller, like 5 or 10 minutes after, that seems acceptable to me. Also, many people are notified on new releases through github releases. I think it's unusual to be notified of an npm release as afaik npm does not have any built-in way to be notified.


If you feel you can improve the release process, I'm ok to get your PR on this file: https://github.com/facebook/docusaurus/blob/master/admin/publish.md
I would try this process on next v1 release and if it's better I'll merge the PR.

But please note that v1 is not very actively maintained, and we don't plan to do many more v1 releases. I need to dedicate my time on v2, and the v1 release process looks good enough to me for the time we'll be using it.

**Comment by noraj** [comment]
> The changelog came a bit later for this release, because I was also updating the publish doc in the release PR (which I maybe shouldn't have do).

Yeah I understand for this specific case.

> Next releases the interval will be smaller, like 5 or 10 minutes after, that seems acceptable to me.

I'm not here to blame, what I'm trying to understand is why (what is the advantage of) doing it in a separate PR?

> But please note that v1 is not very actively maintained, and we don't plan to do many more v1 releases. I need to dedicate my time on v2, and the v1 release process looks good enough to me for the time we'll be using it.

Yeah it's true that v1 EOL is soon and the are only rare update to fix some bugs.

> Also, many people are notified on new releases through github releases. I think it's unusual to be notified of an npm release as afaik npm does not have any built-in way to be notified.

I'm not trying to argue here, but I think this is totally wrong. I think among devs using npm packages a minority is notified of an update of one of their dependencies via github release notification. In facts in devops pipeline people will use various tools to frequently check updates of their dependencies (eg. npm-check-updates) or use security tools to alert of updates only when the dependency is vulnerable (eg. with snyk) or use an external bot to check dependencies and get automatic PR/MR (eg. WhiteSource Renovate, OWASP Dependency-Track, Depfu, dependabot, etc.).
But not so long ago, GitHub acquired dependabot (see https://github.blog/2020-06-01-keep-all-your-packages-up-to-date-with-dependabot/) so now dependabot is natively integrated to GitHub and sometimes enabled by default depending of repos.
Some company also do some manual review of their dependencies from time to time. In reality the vast majority of dev will be notified of a npm package update by another mean than github release notification (not including dependabot) so having the npm release out before the github release is a real issue even for the v2.

**Comment by slorber** [comment]
> I'm not here to blame, what I'm trying to understand is why (what is the advantage of) doing it in a separate PR?

We restricted commits to master (on purpose, to prevent me from committing to master by mistake), so any publish has to go through a PR, on which we need to bump package dependencies etc...

I try to find a workflow that does not involve opening 2 PRs for the same release (like 1st for the changelog, 2nd for bumping the version)

I think the most I could do, is to first merge the PR with the updated version number, and only then publish the release. Maybe it makes more sense to bump the deps in code first, and only publish after the changelog and new version is already merged to master.

---

Thanks for letting me know. 

I find your renovatebot diff quite convenient to inspect third party dependency changes. This should be a github default imho

**Comment by noraj** [comment]
> We restricted commits to master (on purpose, to prevent me from committing to master by mistake), so any publish has to go through a PR, on which we need to bump package dependencies etc...

There is no issue with using a PR, on the contrary it's a good practice.

> I try to find a workflow that does not involve opening 2 PRs for the same release (like 1st for the changelog, 2nd for bumping the version)

That's exactly what I'm trying to say. Why not having having only 1 PR including changelog, feature change, bumping version, doc change, etc. whatever there is 1 or 10 commits in the PR. But I understand it's already the case and we are just not udnerstand each other :laughing:. It's just that the "feature change" here seems to be distributed among many PR's (which is not a problem either) because tehre are various big changes.
The only issue here was `npm publish` before merging  #3218. Nothing else is a problem and the actual workflow is pretty neat :smiley:

**Comment by slorber** [comment]
will try to improve it on next release
