### ISSUE TITLE
54 -> 61 no longer supports spaces in Doc Folder names

### ISSUE THREAD

**Issue by metasaver** [facebook/docusaurus#3223]
## 🐛 Bug Report

After upgrading to 61, my folder names with spaces in them no longer work:

@xxx-docs/documentation-internal: Error: Unable to resolve valid document slug. Maybe your slug frontmatter is incorrect? Doc id=-1.intro / dirName=ea/guides/Documentation Site / frontmatterSlug=undefined => bad result slug=/ea/guides/Documentation Site/-1.intro

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## To Reproduce

(Write your steps here:)

1. Add a folder that contains a space, my test case is: /docs/apps/Enterprise Libraries/Configuration/xxx.md
1. run build, get error form above.
1. Remove space in folder name
1. run build, error is gone

## Expected behavior

Folder names with spaces should work like they did in 54

## Actual Behavior

docusaurus build throws an error:

@xxx-docs/documentation-internal: Error: Unable to resolve valid document slug. Maybe your slug frontmatter is incorrect? Doc id=-1.intro / dirName=ea/guides/Documentation Site / frontmatterSlug=undefined => bad result slug=/ea/guides/Documentation Site/-1.intro

## Your Environment

@xxx-docs/documentation-internal: Error: Unable to resolve valid document slug. Maybe your slug frontmatter is incorrect? Doc id=-1.intro / dirName=ea/guides/Documentation Site / frontmatterSlug=undefined => bad result slug=/ea/guides/Documentation Site/-1.intro

## Reproducible Demo

Easily reproducible in 1 minute by adding a folder and a page to build 61

**Comment by slorber** [comment]
Thanks, will be fixed by #3262

**Comment by metasaver** [comment]
thanks
