### ISSUE TITLE
ESOCKETTIMEDOUT for @algolia/client-common dependency during installation / update

### ISSUE THREAD

**Issue by JulianGerhard21** [facebook/docusaurus#3224]
## 🐛 Bug Report

Currently it is not possible to successfully run `npm install` because of a SOCKET Timeout for the dependency `@algolia/client-common`. I tried to update from alpha version 58 to 61 as proposed on the documentation guidelines.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## To Reproduce

1. Follow the *Get Started* Guidelines from the [website](https://v2.docusaurus.io/docs/installation)

## Actual Behavior

```
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@algolia%2fclient-common - Not found
npm ERR! 404
npm ERR! 404  '@algolia/client-common@4.3.1' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'algoliasearch'
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
```

## Your Environment

- Docusaurus version used: 2.0.0.-alpha.59
- Environment name and version (e.g. Chrome 78.0.3904.108, Node.js 10.17.0): NodeJS v10.16.0
- Operating system and version (desktop or mobile): Windows 10 Enterprise

**Comment by andrui** [comment]
https://github.com/npm/cli/issues/1624

**Comment by slorber** [comment]
thanks

https://status.npmjs.org/

We can't do anything about it
