### ISSUE TITLE
Support sub-directories in docs/

### ISSUE THREAD

**Issue by steveklabnik** [facebook/Docusaurus#323]
I believe this is a feature request. If not, it's a request for docs 😄 

I believe that currently, all docs files must live in the root of `docs`. I'd like to be able to group them together with subfolders.

Currently, it seems that directories inside of docs are simply ignored.

**Comment by hramos** [comment]
Right now Docusaurus expects all files to be on a flat `docs/` folder. I believe this is a decision made to simplify internationalization support where `docs/` would contain multiple sub-directories (one per language).

We can leave this open as a feature request in case someone wants to take a stab at implementing this.

**Comment by JoelMarcey** [comment]
@steveklabnik Hi! What @hramos says is basically correct. But, I wanted to correct one thing in your initial issue comment and his response:

> I believe that currently, all docs files must live in the root of docs.
> Right now Docusaurus expects all files to be on a flat docs/ folder

We implemented that you can put the docs in any directory you want. But the files have to be flat still.

See `customDocsPath` here: https://docusaurus.io/docs/en/site-config.html#optional-fields

**Comment by steveklabnik** [comment]
Gotcha! Thanks for the quick response :)

To be honest, I'm more concerned about the urls than I am about the directory structure. I'm experimenting with some API docs, and `/api/foo/bar/baz.html` is much nicer than `api-foo-bar-baz.html`. If there was a way to do this, while still keeping the flat structure, I'd be okay with that as well.

**Comment by JoelMarcey** [comment]
@steveklabnik We have a feature request (probably should be one of our top ones) to support custom permalinks. https://github.com/facebook/Docusaurus/issues/101

That would help you sorta solve that problem too, right, assuming we don't get to non-flat doc structures first?

**Comment by steveklabnik** [comment]
I think so! Will comment over there too 👍

**Comment by viktorsmari** [comment]
I would also very much like to see the non-flat folder structure, allowing subfolders for better organization. 
I have a large markdown codebase with subfolders I would like to migrate to Docusaurus. 
I also have non technical people editing the files on Github and they know how basic folder structure works and maps to real urls.

**Comment by kirtan403** [comment]
I think when markdown base increases, It would be hard to maintain it in a flat file structure. Just allowing sub-directories would be a very nice feature really. I am migrating to Docusaurus from gitbook and I think it will make it easy to maintain..

**Comment by pharophy** [comment]
I would also like to see subfolder support!

**Comment by endiliey** [comment]
Hello everyone who wanted sub-directories support in Docusaurus. I have submitted PR #705 for it, please help me to test it if you want to see it shipped 😂 

I've personally tested this subdirectories in docs/ directly on my test site.

This is a doc located like this
```
docs/
├── docusaurus
│   └── introduction.md
```

https://endiliey.com/docs/ko/docusaurus/introduction.html
<img width="922" alt="korean" src="https://user-images.githubusercontent.com/17883920/40887059-369a1f62-6775-11e8-9679-5757d10be1c3.PNG">

**Comment by JoelMarcey** [comment]
Hi @endiliey - You may have answered part of this in https://github.com/facebook/Docusaurus/pull/709#issuecomment-394222833, but our concern re: this change was always around how it would affect translations and versioning. You think translations still work well - that's great! Have you test with versioning too?

**Comment by endiliey** [comment]
Yes i have tested site with
1. Just versioning
2. Versioning & translation
3. Just translation

**Comment by zack9433** [comment]
Hi @endiliey 

I think versioning is broken on **v1.3.2** when I run `yarn run version  1.0.0` and create `versioned_docs` `versioned_sidebars`, `versions.json` correctly. After created version, I run `yarn start` and shows some error message

```
Error: Processing the following `doc` field in `headerLinks` within `siteConfig.js`: 'edge/intro'. Check the spelling of your `doc` field. If that seems sane, and a document in your docs folder exists with that `id` value,
then this is likely a bug in Docusaurus. Docusaurus thinks one or both of translations (currently set to: false) or versioning (currently set to: true) is enabled when maybe they should not be.
Thus my internal id for this doc is: 'version-1.0.0-edge/intro'. Please file an issue for this possible bug on GitHub.
```

**Comment by endiliey** [comment]
@zack9433 mind giving a reproducible repo?

**Comment by zack9433** [comment]
@endiliey seems like it's my settings problem and versioning is good right now. thx

**Comment by ishanmihir19** [comment]
@zack9433 Can you point which settings you changed to fix this issue. I seem to have run into the same issue. 

> Error: Processing the following `doc` field in `headerLinks` within `siteConfig.js`: 'designer-guide/introduction'. Check the spelling of your `doc` field. If that seems sane, and a document in your docs folder exists with that `id` value, 
then this is likely a bug in Docusaurus. Docusaurus thinks one or both of translations (currently set to: false) or versioning (currently set to: true) is enabled when maybe they should not be. 
Thus my internal id for this doc is: 'version-1.4-designer-guide/introduction'. Please file an issue for this possible bug on GitHub.

**Comment by Danon** [comment]
If I have a directory structure like this
```
docs/
├── application
│   ├── about.md
│   └── introduction.md
```
Then in my `sidebars.json`, I need to put links like so:
```json
{
  "docs": {
    "Application": [
      "application/about",
      "application/introduction"
    ],
```
which is fine for me.

My question is, what should `id`s of those `about.md` and `introduction.md` be? Can they be duplicated, each within different subdirectory? For example `Feature1/about` and `Feature2/about`?

**Comment by endiliey** [comment]
@Danon yup. Because internally at Docusaurus their id will be `Feature1/about` and `Feature2/about`. So the id is namespaced.

Feel free to ping us on discord instead since GH issue reply might not be as fast

**Comment by Danon** [comment]
What's your discord?

**Comment by yangshun** [comment]
@Danon https://discordapp.com/invite/docusaurus

**Comment by amimas** [comment]
Does this only support one level of sub-directory under `/docs`? Can I have a directory structure like `/docs/projectA/category1`? If yes, what should the configuration be in `sidebars.json`? It seems I cannot add multiple layers in the sidebar

**Comment by robbiet480** [comment]
@zack9433 So I and other users are having this issue but you didn't provide a fix. Can you tell us what you had to change to get this working again so everyone benefits? Thanks!

**Comment by robbiet480** [comment]
Fix can be found at https://github.com/facebook/Docusaurus/issues/1395 for those experiencing this in the future.

**Comment by potatodepaulo** [comment]
> Does this only support one level of sub-directory under `/docs`? Can I have a directory structure like `/docs/projectA/category1`? If yes, what should the configuration be in `sidebars.json`? It seems I cannot add multiple layers in the sidebar

Any news on this? Do multiple nested subtrees work?
