### ISSUE TITLE
Unable to access document added in docs folder

### ISSUE THREAD

**Issue by sri1980** [facebook/docusaurus#3231]
I am adding document in docs folder with extension .md .  Unable to access this document, getting 404. 

Can you please help me do i need to make any config changes after adding doc-1.md in docs folder?

    Here is my project structure

             website
                  ---  docs
                              - doc-1.md

   
          **doc-1.md**
                  
                 ---
                 id: page1
                 title: Getting Started
                 ---

          **index.js**   

                <Button href={docUrl("page1.html")}>Page1</Button>

        Getting error  `Cannot GET /docs/page1.html` when i click on button.

**Comment by anshulrgoyal** [comment]
Are u using D2 or D1?

**Comment by sri1980** [comment]
I am using D1

**Comment by slorber** [comment]
Can you please create a repo? this kind of issue is hard to debug without it. 

Did you try browsing `/docs/page1` instead of adding the HTML suffix? (see cleanUrl config option)

**Comment by sri1980** [comment]
Here is the repo url

https://github.com/sri1980/website


I tried with 'docs/page1' also, it's not working.

**Comment by slorber** [comment]
Do you have the site online somewhere? That would help win some time debugging the problem

**Comment by slorber** [comment]
Repro is broken. It's not clear if you want docusaurus v1 or v2 as the FS structure looks a bit to melt the 2. You'd rather use v2 and init a brand new fresh v2 site, as documented
