### ISSUE TITLE
migration cli uses absolute paths instead of relative paths for customCss and sidebarPath

### ISSUE THREAD

**Issue by darshkpatel** [facebook/docusaurus#3239]
## 🐛 Bug Report

The migration CLI uses absolute paths instead of relative paths for `customCss` and `sidebarPath`
Discovered while working on https://github.com/MLH-Fellowship/react-native-website/pull/37
### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?
yes

## To Reproduce
0. Create a v1 site `npx docusaurus-init`
1. Use the migration CLI for migrating a website from v1 to v2 `docusaurus-migrate migrate website website-v2`
2. Open `website-v2/docusaurus.config.js`
3. Look for `sidebarPath` and `customCss`

## Expected behavior

The paths should be relative / should use `require.resolve()`

## Actual Behavior

Absolute paths are written in `docusaurus.config.js`

## Your Environment

- @docusaurus/migrate 2.0.0-alpha.59
- Environment name and version: macOS Catalina 

## Example Repo

https://github.com/darshkpatel/docusaurus-migrationcli-bug

Lines:
https://github.com/darshkpatel/docusaurus-migrationcli-bug/blob/768810e484cd0ccbb21fd33656e74ba944ccf654/website-v2/docusaurus.config.js#L32-L38

**Comment by teikjun** [comment]
Thanks, I'm on it! :)

**Comment by PalAditya** [comment]
Hi, this seems like a nice issue to get started with this project. May I work on this please?

**Comment by slorber** [comment]
hi @PalAditya yes definitively.

Note there is a `test:v1Migration:migrate` command at the root of the monorepo that might help :)
