### ISSUE TITLE
Confusing interaction between sidebar_label and title

### ISSUE THREAD

**Issue by steveklabnik** [facebook/Docusaurus#324]
As https://docusaurus.io/docs/en/doc-markdown.html says:

> title: The title of your document. If this field is not present, the document's title will default to it's id.
>
> sidebar_label: The text shown in the document sidebar for this document. If this field is not present, the document's sidebar_label will default to it's title.

I'm trying to use these two together. Here's a concrete example:

I have `foo.md`. It has this as its header:

```yaml
---
title: A Foo
---
```

This works great. But, this means I have "A Foo" in the sidebar, and I'd like it to be Foo. So I set the sidebar_label:

```yaml
---
title: A Foo
siebar_label: Foo
---
```

And now, my page title is back to `Foo`, rather than `A Foo`.

**Comment by JoelMarcey** [comment]
@steveklabnik Hi! Interesting. Let me make sure we are on the same page here. The example documentation that comes with `docusaurus-init` or `npm run examples` has a file called `doc1.md` that looks something like:

```
---
id: doc1
title: Latin-ish
sidebar_label: Example Page
---

Check the [documentation](https://docusaurus.io) for how to use Docusaurus.

## Lorem

```

When I run the site, I get:

<img width="1345" alt="screenshot 2017-12-19 15 31 19" src="https://user-images.githubusercontent.com/3757713/34183845-ae82ad18-e4d1-11e7-9870-1e21cd3bdd66.png">

**Comment by steveklabnik** [comment]
Hm, okay. So I have:

```yaml
---
title: the future
sidebar_label: future
---

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed accumsan lectus ac ornare consectetur. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Integer ac sem malesuada, pretium dui sed, dignissim massa. Nulla facilisi. In mattis neque nec sem interdum pretium. Quisque gravida neque ac libero auctor cursus. Etiam tempor laoreet libero, quis hendrerit libero gravida ac. Sed enim elit, tincidunt a elit vel, commodo sagittis ex. Quisque nec erat lobortis, vehicula libero ac, rutrum libero. Aliquam rhoncus sit amet odio nec posuere. 

```

I get this:

![future1](https://user-images.githubusercontent.com/27786/34184044-cb67cfd4-e4eb-11e7-9fcd-372da972d076.png)

If I remove the sidebar label

```yaml
---
title: the future
---

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed accumsan lectus ac ornare consectetur. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Integer ac sem malesuada, pretium dui sed, dignissim massa. Nulla facilisi. In mattis neque nec sem interdum pretium. Quisque gravida neque ac libero auctor cursus. Etiam tempor laoreet libero, quis hendrerit libero gravida ac. Sed enim elit, tincidunt a elit vel, commodo sagittis ex. Quisque nec erat lobortis, vehicula libero ac, rutrum libero. Aliquam rhoncus sit amet odio nec posuere. 

```

I get this: 

![future2](https://user-images.githubusercontent.com/27786/34184107-07df2c1e-e4ec-11e7-9901-dd35f3b5b1b2.png)

This is true if I set `id` explicitly as well.

I was mulling over what's different between your example and mine, and it hit me: my `id` and `sidebar_label` are the same, but yours are different. And sure enough, if I make `sidebar_label` something different than the `id`, it works.

Tricky!

**Comment by JoelMarcey** [comment]
@steveklabnik Good reproduction. Thanks! I will look into this.

**Comment by marcosvega91** [comment]
@steveklabnik I think that the problem is in write-translation.js file 
```
   translations['localized-strings'][metadata.localized_id] = metadata.title;

   if (metadata.sidebar_label) {
      translations['localized-strings'][metadata.sidebar_label] =
      metadata.sidebar_label;
   }
```
If localized_id=id is the same as sidebar_label inside the if  sidebar_label value replaces the localized_id one

Maybe a possibile solution can be moving sidebar and id translations under different keys inside 'localized-strings'. What do you think @JoelMarcey ?
