### ISSUE TITLE
Duplication of Code in generate.js and server.js

### ISSUE THREAD

**Issue by neilsutcliffe** [facebook/Docusaurus#325]
### Is this a bug report?

No. Technical Debt

### Have you read the [Contributing Guidelines](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md)?

Yes

### Steps to Reproduce

Look at the `/lib/server/server.js` file and `/lib/server/generate.js` and notice that we have two code paths that do the same task. Specifically the reading of documents (and to a lesser degree pages and blogs)

### Expected Result

I'd expect that core logic such as how to do translations to a file exist only in one place.
I have been examining and documenting this code, and improved it's readability (as well as translation issues). It's an ambitious pull-request, but I may just cherry pick my changes for these two files.

**Comment by JoelMarcey** [comment]
Yes, we have known about this for a little while. Glad you brought it up in an issue as I don't think we have put that in a public issue yet. I agree, refactor and de-dupe should be done though.

**Comment by richardzcode** [comment]
Making a first step attempt

**Comment by neilsutcliffe** [comment]
@richardzcode 

I'm heading off. Check my repo for an example of the getPage.js.

I haven't touched the blogs at all.

Also I pulled in your render.js as it is much better than mine was.

I'm concerned that having all the render methods in one file will be massive though. Can we get them in multiple files, or do they have too many common dependencies?

Would the following structure be 'standards compliant'? I've done a lot of JS, but not much node stuff TBH?

- render/index.js
- render/page.js
- render/docs.js
- render/css.js

And inside the index.js
```
import {renderDocsHtml, renderDocsJs } from './docs.js'
export default { renderPage, renderDocsHtml, renderDocsJs, renderCss }
```

**Comment by richardzcode** [comment]
@neilsutcliffe I think that is a good structure. Eventually probably evolves to this structure, just takes time, step by step.

I think for this size of refactoring, the concern is not only on correctness, but also on how comfortable the team feels about when and how. Because at end of the day if anything goes wrong, it is the team taking blames. I am taking a pause on more changes right now. I think we have already dumped good amount of workload to the team, so just wait :)

**Comment by JoelMarcey** [comment]
@neilsutcliffe @richardzcode Thank you both for this discussion. Sorry, I got a bit sidetracked today on some other work. I will try to look at the PR and this issue tomorrow and provide my thoughts.

**Comment by neilsutcliffe** [comment]
I'd wait until the weekend. I'm splitting the generate.js file into multiple files.

The output of build should be relatively easy to check right? It should give the exact same file structure/content as your master, unless I make some improvements along the way?

I'd suggest getting the split in place like follows

![download](https://user-images.githubusercontent.com/13319277/34314653-1860cd86-e776-11e7-91c3-78083e4af1bf.png)

At the moment the code is duplicated, so there is no harm in making an intermediate change that only changes the generate.js function. I'm tackling a PR at the moment for Windows support, which seems to fit together nicely.

As for a PR review, I don't think I need one just let. This will be seperate PR with just the new Windows compatible generation code. I'm thinking I'm going to test it with the Jest documentation to ensure I get proper language support working too.
