### ISSUE TITLE
Can't reference links to docs from Blog

### ISSUE THREAD

**Issue by Danon** [facebook/docusaurus#3250]
## 🐛 Bug Report

After update to 2.0-alpha61, the "broken links" util (which I find very helpful), said my link to doc from Blog was broken:

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## To Reproduce

(Write your steps here:)

0. Add docs file, e.g. `file.mdx`.
1. Add blog post
2. Add link to your doc in Blog post with extension (e.g. `file.mdx`, like me)
3. Build the application

## Expected behavior

The link should be considered a valid link.

## Actual Behavior

"Broken links" complain it's broken. It will only be considered valid, if it doesn't contain an extension. It's inconsitent, since link in docs to docs can have extensions.

Kinda looks like links in `/docs` can point to files, but links in blog point to URL? It's really unintuitive.

```
Error: Broken links found!

- Page path = /blog:
   -> link to ../../docs/filter.mdx#filter-by-keys (resolved as: /docs/filter.mdx)


- Page path = /blog/2019/08/31/super-duper-stargazers:
   -> link to ../../docs/filter.mdx#filter-by-keys (resolved as: /blog/2019/docs/filter.mdx)

Note: it's possible to ignore broken links with the 'onBrokenLinks' Docusaurus configuration.
```

## Your Environment

- Docusaurus version used: 2.0-alpha61
- Operating system: Windows

**Comment by slorber** [comment]
Hi @Danon 

Linking using md file paths only works for docs, it's not possible to link from/to blog this way, because the fs path to URL resolution system is plugin dependant (slug frontmatter etc...)

It is pretty sure that this link was not reported before, but it was actually broken in practice, so this new system likely catched a bug on your site :)

**Comment by Danon** [comment]
@slorber Yes, you're right. Sorry to have taken your time.
