### ISSUE TITLE
Minimal scaffold for init

### ISSUE THREAD

**Issue by SanketDG** [facebook/docusaurus#3255]
## 💥 Proposal

The current scaffold for init produces a lot of files in the scaffold, this may be overwhelming for someone who has never played with SSGs and similar systems before.

Someone may just want to show a bunch of markdown files that they already have in a well presented layout.

**Can we have a scaffold/theme where a minimal set of files are present for running Docusarus?**

To scratch my own itch, I created [tinysaurus](https://github.com/SanketDG/tinysaurus), where I removed a lot of parts from the default scaffold:

- Landing Page (I can create my own page if I need to)
- Blog (Again, I will add this if I need to)
- Footer Items

The preview's [here](https://sanketdg.github.io/tinysaurus/). I am still finishing up the documentation!

I removed what _I felt I do not need_, but I want to ask the community at large if this is something that's wanted, then I can definitely create a _theme?_ for this! The initial idea was a theme, but I felt there was little to no documentation on creating themes, so I just went ahead and modified the default scaffold.

**Comment by slorber** [comment]
Hey @SanketDG 

Personally I don't see the value of such a minimal scaffold. It's easier to get more files and delete the useless ones, than to start from scratch and add the useful things one by one.

Is it really just a pain to have to delete a few files?

With your minimal scaffold, what's left exactly? 
You could remove the preset classic, and only have no page at all, which would mean the 404 would always be displayed.

Your scaffold seems to be biased toward using docs, because it seems it's the only thing you didn't remove. This is opiniated, some users would prefer to only have blogs, and no docs, some will only want pages, and no docs/blog...


If the community really wants this, why not, and feel free to gather feedback on this, poll the community on Discord etc, but I'm closing for now.

**Comment by SanketDG** [comment]
@slorber 

> Personally I don't see the value of such a minimal scaffold. It's easier to get more files and delete the useless ones, than to start from scratch and add the useful things one by one.

I will expand a bit on why I went ahead and did this. If you are coming from the whole "single page Github pages theme", Docusaurus is a little bit over the top. Most projects don't have a logo or a dedicated landing page, they just want to make sure they start with introducing the project and what it does, _in text_.

> Is it really just a pain to have to delete a few files?

One definitely has to go through a few pages of the documentation and get yourself familiar with Docusaurus to be able to make just the "docs" work.

> If the community really wants this, why not, and feel free to gather feedback on this, poll the community on Discord etc, but I'm closing for now.

Apologies, it seems like you have misunderstood me. Yes, this was probably not the right place to post this, but my bottomline was that I wanted to create a theme or a scaffold based on this, is something like this possible right now?

**Comment by slorber** [comment]
You can create both a theme (which is just the UI), a preset (which is plugins + themes), a boilerplate... 

We could accept whatever you build as long as the community finds it useful (is there is more than 2 or 3 people that want it), and it's not too painful to maintain for us.

But again I think what you want to build is biased toward your usecase. Why not a scaffold with just a homepage? Just a blog?
Do we want to maintain in core one scaffold per possibility? Or should we provide a scaffold just for docs, as it's one of the major Docusaurus feature?

I don't know, but I feel that can live outside of the main repo. If you want to build something related to Docusaurus and think others will like it, go ahead on your own Github repo. and the github stars will say if people like it or not ;)

**Comment by slorber** [comment]
Note, we have a community page here, if you build something we can add what you build on this page: https://v2.docusaurus.io/community/resources
