### ISSUE TITLE
Open and close the dropdown

### ISSUE THREAD

**Issue by leoigel** [facebook/docusaurus#3256]
## 🚀 Feature

(A clear and concise description of what the feature is.)
Usually when dropdown is open the user can be able to close clicking on the page, this behavior not happen here, the user can close the dropdown just by clicking on one place. 
### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?
Yes
(Write your answer here.)
Change the behavior  of dropdown.

## Motivation
Improve the UI, instead the user need to browser to menu to close the dropdown, he able to click anywhere on the page to close the dropdwon.
(Please outline the motivation for the proposal.)

## Pitch

(Please explain why this feature should be implemented and how it would be used.)
feature should be implemented to improve the ui need to implement some conditions, for example if(languagesDropDown.className = "visible") {
...do something
}

**Comment by leoigel** [comment]
if this issue is acceptable i would like to make pr!

**Comment by slorber** [comment]
Hey, I think this is fixed by https://github.com/facebook/docusaurus/pull/3240

**Comment by leoigel** [comment]
Sorry if i'm not clean but this is the actual behavior :

![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/29859021/89942233-dcd37380-dc24-11ea-8b03-90760a949e3f.gif)

but i expect to this behavior : 
![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/29859021/89942814-e27d8900-dc25-11ea-9f1a-3d0f3bf01a3f.gif)

**Comment by slorber** [comment]
this is v1 site, and we are not investing too much in v1.
I'd accept a PR to solve this but not really willing to invest time in this fix myself
