### ISSUE TITLE
Typing mis-match in `index.js` generated from docusaurus-init 

### ISSUE THREAD

**Issue by huan** [facebook/docusaurus#3257]
The following code [`alt={title}`](https://github.com/facebook/docusaurus/blob/master/packages/docusaurus-init/templates/facebook/src/pages/index.js#L57) will call a `String(title)` and then get a `object: Object` string back.

The reason for that is because `title` is a [Fragements](https://reactjs.org/docs/fragments.html) we defined at [here: `title: <>Easy to Use</>`](https://github.com/facebook/docusaurus/blob/master/packages/docusaurus-init/templates/facebook/src/pages/index.js#L20).

**Comment by slorber** [comment]
sorrry but I don't understand the problem. How all this is affecting you exactly? Do you have a live site with the bug being visible?

**Comment by huan** [comment]
Yes, I found a live site with this bug being visible.

<https://wechaty.js.org/docs/> is the current site that I'm working on, and it is using the default template from the `docusaurus-init`.

If you use the chrome inspect tool to inspect the image above "Easy to Use" text, you can find that the `alt` property of that image is `alt="[object Object]"`, which is expected to be "Easy to Use".

![image](https://user-images.githubusercontent.com/1361891/89889390-1cd62e80-dc04-11ea-93bd-b7f6876ce69f.png)

I hope this can help me to explain this issue clearly.

**Comment by slorber** [comment]
Thanks, will be fixed by #3258

**Comment by huan** [comment]
Thank you very much for the quick fix!
