### ISSUE TITLE
dependency warning on "serialize-javascript"

### ISSUE THREAD

**Issue by aimaj-anz** [facebook/docusaurus#3268]
## 🐛 Bug Report

doing a clean yarn install of latest version, and yarn audit returns some vulnerability warnings:
https://www.npmjs.com/advisories/1548

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?
yes

## To Reproduce

1. create new project
2. yarn install @docusaurus/core^2.0.0-alpha.61 and/or @docusaurus/preset-classic^2.0.0-alpha.61
3. yarn audit
4. view warnings

## Expected behavior

No audit warnings

## Actual Behavior

6 audit warnings

![image](https://user-images.githubusercontent.com/65322050/89959748-8431c400-dc80-11ea-9468-367ebe46154e.png)

## Your Environment

- mac OS
- "@docusaurus/core": "^2.0.0-alpha.61"
- "@docusaurus/preset-classic": "^2.0.0-alpha.61"

## Reproducible Demo

N/A

**Comment by slorber** [comment]
Thanks, will take a look at this soon.

**Comment by slorber** [comment]
fixed by https://github.com/facebook/docusaurus/pull/3265

**Comment by temannin** [comment]
@slorber , does #3265 fix the issue? The audit report deals with copy-webpack-plugin and not terser-webpack-plugin.

**Comment by dschaller** [comment]
There is an additional update needed for `webpack` and `copy-webpack-plugin`. The minimum version of webpack required to patch the vulnerability is 5 which requires updating a few other dependencies who have a peer dependency on webpack@4. 

It looks like the following packages all have a peer dependency of webpack@4:
```bash
warning " > webpack-dev-middleware@3.7.2" has unmet peer dependency "webpack@^4.0.0".
warning " > cache-loader@4.1.0" has unmet peer dependency "webpack@^4.0.0".
warning " > optimize-css-assets-webpack-plugin@5.0.3" has unmet peer dependency "webpack@^4.0.0".
```

**Comment by slorber** [comment]
Hey, I'm upgrading the copy plugin here: #3282 to solve this issue.

We also have to upgrade the workbox-build package in the pwa plugin, when they upgrade here: https://github.com/GoogleChrome/workbox/issues/2601 (but this is less likely to affect many D2 users)

@dschaller I don't understand why you think we need to upgrade to Webpack 5?

**Comment by slorber** [comment]
Let's keep it open until we are sure it is really fixed + the pwa plugin is also fixed

**Comment by dschaller** [comment]
@slorber I recall seeing some of the updated packages having a peer dependency of >webpack@5. I could have misread that though.
