### ISSUE TITLE
Updating content without refresh page after clicking links on the left sidebar

### ISSUE THREAD

**Issue by uanaoeng** [facebook/docusaurus#3288]
## 🚀 Feature
Updating content without refresh page after clicking links on the left sidebar

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?
Yes

## Motivation
Improve reading experience

## Pitch

(Please explain why this feature should be implemented and how it would be used.)

**Comment by slorber** [comment]
Sorry but I don't understand 😅
