### ISSUE TITLE
The serve command does not respect baseUrl

### ISSUE THREAD

**Issue by Satyam** [facebook/docusaurus#3291]
## 🐛 Bug Report

If a site config has `baseUrl` set to anything but `'/'` such as when a site is meant for GitHub, the `docusaurus serve` command won't work since `build` will add the `baseUrl` to links, but `serve` does not respond to it. 

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## To Reproduce

1. Pick any project meant for deployment as a GitHub page that has a `baseUrl` set to some folder other than root, for example: `baseUrl: '/docusaurus/'`
1. Check your `package.json` scripts to ensure you have the script entry `"serve": "docusaurus serve"`.
1. Run `npm run serve -- --build`.  This will ensure you are building a fresh copy on every serve.
1. Open your browser in the URL shown on the console by the previous command

## Expected behavior

Site should open as it would when deployed

To see what should be expected, 

1. change the site config `baseUrl` to `baseUrl: '/'`
1. run  `npm run serve -- --build`.

## Actual Behavior

The html for the initial page is displayed (or any page if you use the full address of the page) but all resources linked to from that page fail as they contain the `baseUrl` path.  No CSS, images or scripts.  Links don't work.

## Your Environment

From `package.json`:
```json
  "dependencies": {
    "@docusaurus/core": "^2.0.0-alpha.61",
    "@docusaurus/preset-classic": "2.0.0-alpha.59",
    "clsx": "^1.1.1",
    "react": "^16.10.2",
    "react-dom": "^16.10.2"
  }
```
Chrome: Version 84.0.4147.125 (Official Build) (64-bit)
(browser is not particularly relevant since you can see the `buildUrl` value inserted in the `index.html` anyway)
nodeJS: v14.7.0
Ubuntu 20.04.1 LTS

## Reproducible Demo

It is easier to pick any project the tester is familiar with than going through the trouble of setting up another one.  Either add a subfolder to `baseUrl` to a project that doesn't have one, or use one that does have it set.

## Suggested fix:

Ensure `serve` command reads the  `baseUrl` setting and strip it off the requests it gets. 

Thanks

**Comment by slorber** [comment]
Thanks @anshulrgoyal 

I don't see any option in the [serve](https://github.com/vercel/serve-handler#options) package that fit this need unfortunately :/ 

Maybe we can use a trick with symlinks: https://github.com/vercel/serve-handler#symlinks-boolean

like create a symlink in /build/baseUrl

@Satyam for now the best is to move the /build folder to /build/baseUrl , and serve build, so that you can access the files at /baseUrl

**Comment by anshulrgoyal** [comment]
@slorber I found rewrites and it works.

**Comment by anshulrgoyal** [comment]
```js
 rewrites: [
        {source: `${props.baseUrl}:path`, destination: '/:path'},
      ],

```

**Comment by Satyam** [comment]
@slorber , as an interim solution it works. My npm script now has 
```
"serve": "docusaurus build --out-dir build/myDocs && docusaurus serve"
```
Just an additional warning:  when it finishes the `serve` command announces that you can check the site at `- Local: http://localhost:3000`, which is misleading and confusing since it usually picks some build left over by some previous `build` that doesn't work with `serve`.  The actual address to be used is `- Local: http://localhost:3000/myDocs`

**Comment by anshulrgoyal** [comment]
@Satyam I have fixed but am not sure it is ideal solution or not.

**Comment by slorber** [comment]
@anshulrgoyal we likely won't be able to find a best solution unless serve implement something, so a good enough solution not requiring to move the build folder will be useful

You could also add a redirect like:

```
 rewrites: [
        {source: `${props.baseUrl}:path`, destination: '/:path'},
      ],

 redirects: [
        {source: `/`, destination: props.baseUrl},
      ],
```

so that a user trying to open http://localhost:4000 will be redirected automatically to the http://localhost:4000/baseUrl

**Comment by anshulrgoyal** [comment]
@slorber Images don't work with rewrites

**Comment by anshulrgoyal** [comment]
I treid this and it works fine:

```js
req.url = Url.format({
      ...url,
      pathname: url.pathname?.replace(new RegExp(`^${props.baseUrl}`), ''),
    });

```

**Comment by slorber** [comment]
@anshulrgoyal was wondering if you did a PR already to fix this issue, or should I create one?

**Comment by glowingblue** [comment]
I would love to see a solution to this issue. My current workaround has been to use the custom npm script that @Satyam proposed.

**Comment by SuperOleg39** [comment]
Hi!

Try to update `2.0.0-beta.3` version, `publicPath` not supported againt!

Working nice at `2.0.0-beta.2` version :)

**Comment by slorber** [comment]
@SuperOleg39 beta.3 does not exist yet so what you say is surprising

> publicPath not supported against!

? What is `publicPath`?

**Comment by SuperOleg39** [comment]
> @SuperOleg39 beta.3 does not exist yet so what you say is surprising
> 
> > publicPath not supported against!
> 
> ? What is `publicPath`?

Oh, sorry, i mean `baseUrl`!

Too much looking at Webpack config today)

**Comment by slorber** [comment]
@SuperOleg39 Please open a dedicated issue if you have a problem. 

beta.3 does not exist and beta.2 didn't change much compared to beta.1 so please test again and report this appropriately with a repro

**Comment by SuperOleg39** [comment]
About `beta.3` - i saw this version at documentation, replace `beta.2` at package.json.

Now, looking in lock file - and see `beta.ff31de0ff` at resolved version.

Sorry for wasting your time (

**Comment by SuperOleg39** [comment]
> Please open a dedicated issue if you have a problem.

No, package manager just resolve last canary version, because `beta.3` not exist
https://www.npmjs.com/package/@docusaurus/core/v/2.0.0-beta.ff31de0ff

**Comment by slorber** [comment]
np

![image](https://user-images.githubusercontent.com/749374/123682787-c093f180-d84b-11eb-805e-357801ddd351.png)

This canary version is quite old and does not contain the fix ;)

**Comment by SuperOleg39** [comment]
And this version have abnormally many downloads, looks like `semver` package select this version in cases as my)

**Comment by slorber** [comment]
Yes I think our canary release name is not well-understood by npm somehow and using a semver range ^ might lead you to download a specific release

That's why I recommend not using a ^ when using canary releases on the dedicated page I created recently: https://docusaurus.io/community/canary

Not sure how to fix that
