### ISSUE TITLE
catch invalid version in versions.json at build time

### ISSUE THREAD

**Issue by joshribakoff** [facebook/docusaurus#3292]
## 🚀 Feature

Handle invalid/missing versions

## Motivation

Better DX

## Pitch

If you have an invalid version, eg you assume you can hand edit the file, the build passes & the app throws some runtime error(s) when you try to run it

**Comment by slorber** [comment]
Sorry but I'm totally unable to understand what you are talking about 🤪

**Comment by joshribakoff** [comment]
Edit `versions.json` and put a bad version in there, try to build, the build passes only to crash at runtime when trying to load the site.

**Comment by slorber** [comment]
This is handled in this big docs refactor PR: https://github.com/facebook/docusaurus/pull/3245

**Comment by joshribakoff** [comment]
Ah weird it's handled in a docs refactor ;)

Thanks!
