### ISSUE TITLE
Space missing in HTML

### ISSUE THREAD

**Issue by joshribakoff** [facebook/docusaurus#3298]
## 🐛 Bug Report

Weird behavior w/ spaces being lost.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

yes

## To Reproduce

I have a index.js page:

![Screen Shot 2020-08-17 at 9 15 21 AM](https://user-images.githubusercontent.com/4021306/90419003-c127fd00-e06a-11ea-8d15-15470e5e46a2.png)

The HTML I put renders correct when pasted into a test.html & opened:

![Screen Shot 2020-08-17 at 9 15 47 AM](https://user-images.githubusercontent.com/4021306/90419006-c2592a00-e06a-11ea-90a6-5a7ec7862c38.png)

However its rendered w/o the space in the docs:

![Screen Shot 2020-08-17 at 9 15 26 AM](https://user-images.githubusercontent.com/4021306/90419009-c38a5700-e06a-11ea-9d45-0fe447ad8bc4.png)

## Expected behavior

Match the test.html example

## Actual Behavior
Space is lost

## Your Environment

version "2.0.0-alpha.61"
macOS
Chrome 84
node 12.13.1

## Reproducible Demo

n/a

**Comment by slorber** [comment]
This is likely a JSX/React issue, we can't change anything to that. If you think it's specific to Docusaurus we might reopen

Just put {' '} to force a space where you need it

**Comment by joshribakoff** [comment]
Yes it happens if pasting that into Create React App as well. Thanks!
