### ISSUE TITLE
[v2] npm install --save @docusaurus/plugin-ideal-image no response

### ISSUE THREAD

**Issue by chudongvip** [facebook/docusaurus#3300]
![image](https://user-images.githubusercontent.com/16483109/90469209-cbb9c380-e14a-11ea-888e-f84b539beb55.png)

PS: install with VPN, and I can visit the Google web site.

**Comment by chudongvip** [comment]
Please follow the steps below to reproduce it

- git clone https://github.com/facebook/docusaurus.git
- cd website
- npm i

**Comment by slorber** [comment]
The plugin is there as you can see: https://www.npmjs.com/package/@docusaurus/plugin-ideal-image

If you can't fetch it, it's definitively not our fault and we can't do anything about it
