### ISSUE TITLE
https mode not working due to missing WDS option

### ISSUE THREAD

**Issue by mattmillerart** [facebook/docusaurus#3301]
## 🐛 Bug Report

According to the docs (actually, not sure if this is in the docs) setting `process.env.HTTPS=true` should start webpack dev server in https mode. This does not work because a missing option in the webpack dev server config. 

Here is the webpack dev server docs showing the `https` option: https://webpack.js.org/configuration/dev-server/#devserverhttps 

Here is the Docusaurus config which does not use this option: https://github.com/facebook/docusaurus/blob/master/packages/docusaurus/src/commands/start.ts#L131-L132

Adding this line I was able to get it working as expected

```
https: process.env.HTTPS === 'true',
```

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## To Reproduce

(Write your steps here:)

1. Create new docs from 2.0.0-alpha.61  
2. Modify yarn start to be `HTTPS=true yarn start`
3. Notice the browser opens the expected https `https://localhost:3000/` but the page does not load.
4. Notice the console logs `http` in ` ｢wds｣: Project is running at http://localhost:3000/` 

## Expected behavior

Https opens AND site is running on https. 

## Actual Behavior

Https opens BUT site is running on http

## Your Environment

- Docusaurus version used: Using 2.0.0-alpha.61 
- Environment name and version (e.g. Chrome 78.0.3904.108, Node.js 10.17.0): Chrome, Mac, Node 12
- Operating system and version (desktop or mobile): Desktop

## Reproducible Demo

The issue is simple enough I don't believe it warrants a demo. The steps to reproduce are minimal and include spinning up a new project and running a yarn command. If the team still believes a demo is needed or can't repro the issue I can provide one.

**Comment by facultymatt** [comment]
Related, Docusaurus should probably mirror the options of CRA for setting custom certs: https://create-react-app.dev/docs/using-https-in-development/ to keep things consistent

**Comment by slorber** [comment]
Thanks, agree we should fix that.

Someone willing to submit a PR?

**Comment by arcvats** [comment]
Can I take this one?

**Comment by slorber** [comment]
yes thanks ;)

**Comment by facultymatt** [comment]
Thanks for the fix! Opened a new issue as suggested for the custom cert config: https://github.com/facebook/docusaurus/issues/3445
