### ISSUE TITLE
V2: blog "draft" frontmatter

### ISSUE THREAD

**Issue by slorber** [facebook/docusaurus#3305]
## 🚀 Feature

v1 has `draft: true` frontmatter for blog posts so that the page of the blog post exists but does not appear

https://github.com/facebook/docusaurus/pull/1396

Let's not forget to port it to v2.

It's an easy feature so if someone wants to give it a try :)

Note: we should ensure that the created page for the blog post does not appear in the sitemaps, otherwise that draft blog post could be indexed by Google. That part might be more complicated.

**Comment by slorber** [comment]
Thanks @imskr you can work on this

**Comment by imskr** [comment]
@slorber Thanks since I am new here. Just to confirm, I have to make changes [here](https://github.com/facebook/docusaurus/blob/master/packages/docusaurus-plugin-content-blog/src/blogUtils.ts) right?

**Comment by slorber** [comment]
Hey @imskr yes it's the place.

Seems like it's actually already implemented: https://github.com/facebook/docusaurus/blob/master/packages/docusaurus-plugin-content-blog/src/blogUtils.ts#L126

Maybe only the docs is missing, can you double-check and add the doc please?

Also curious, can you check the sitemaps plugin behavior regarding this draft frontmatter? (we can track/fix this in a separate issue, not sure what's the solution yet)

**Comment by imskr** [comment]
@slorber Yeah sure let me check!

**Comment by imskr** [comment]
@slorber Please review the PR
