### ISSUE TITLE
Mobile dark mode is not respected

### ISSUE THREAD

**Issue by samhatoum** [facebook/docusaurus#3315]
## 🐛 Bug Report

Docusaurus is not respecting mobile dark mode on load, but it does detect it when it's switched dynamically if the page is open. It does not detect it when the mobile dark mode is flipped and the page is not visible.

(A clear and concise description of what the bug is)

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## To Reproduce

*Scenario 1: Browser is open with the Docusaurs site visible*
1. Set mobile to dark mode
1. Open a Docusarus site on and the site shows in light mode.
1. Toggle mobile from light to dark and back again
1. Now the site switches to dark mode
1. Refresh the site page, it returns to light mode

*Scenario 2: Browser is in the background*
1. Set mobile to light
1. Open a Docusarus site on and the site shows in light mode.
1. Send the browser to the background by going to the home screen
1. Toggle mobile from light to dark
1. Open the browser again
1. Docusaurus shows in light mode

## Expected behavior

The Docuaurus site should detect the mobile's dark mode in both scenarios.

## Actual Behavior

The Docuaurus site only changes its light/dark mode when the mobile mode is toggled AND the site page is open. 

## Your Environment

- Docusaurus version used: 2.0.0-alpha.61
- Environment name and version (e.g. Chrome 78.0.3904.108, Node.js 10.17.0): Chrome 84.0.4147.125
- Operating system and version (desktop or mobile): Android 10 / Pixel 4 XL Build/QQ3A.200805.001

## Reproducible Demo

Site: https://www.chimpjs.com
Repo: https://github.com/xolvio/chimp/tree/master/documentation

**Comment by slorber** [comment]
Hi,

as documented, you need to enable an option:

https://v2.docusaurus.io/docs/theme-classic/#color-mode---dark-mode

![image](https://user-images.githubusercontent.com/749374/90774994-9357e800-e2f8-11ea-814e-940dc9452e5c.png)

Maybe the default to disabled surprise you, but if we defaulted to true, this has also been confusing for some users.


Also, is this really related to mobile at all? Do you see a different desktop behavior? The site you link to does not even show me a toggle button on mobile, only on desktop 🤪

**Comment by samhatoum** [comment]
Thanks for the super prompts response. You're right, I somehow missed that. Sometimes I miss big callout cautions like this: 😂 
<img width="585" alt="Screen Shot 2020-08-20 at 9 41 33 AM" src="https://user-images.githubusercontent.com/2021955/90777389-59bbb880-e2c9-11ea-8134-260131cfd3ac.png">

So about the toggle. How does one enable it on mobile? 

Please feel free to close this issue

**Comment by slorber** [comment]
:) 

The toggle appears in the sidebar on mobile:

![image](https://user-images.githubusercontent.com/749374/90794484-2438be80-e30d-11ea-8c7b-7fd08bf86b9f.png)

I don't know exactly how you made it disappear but the initial template should normally have it.
