### ISSUE TITLE
Bootstrap template not rendering 

### ISSUE THREAD

**Issue by davidjsteele** [facebook/docusaurus#3329]
## 🐛 Bug Report

Creating new OOB starter project using npx command with experimental Bootstrap template.

![image](https://user-images.githubusercontent.com/7621977/91026678-014f2880-e5f3-11ea-99d9-c5ada5412eaf.png)

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

yes

## To Reproduce

1. Run npx @docusaurus/init@next init my-website bootstrap
2. cd my-website
3. yarn start

## Expected behavior

Expect site to render as per screengrab here.
https://github.com/facebook/docusaurus/pull/2557

## Actual Behavior

Not rendering correctly.
![image](https://user-images.githubusercontent.com/7621977/91026415-9dc4fb00-e5f2-11ea-92da-a8c8fb53eba9.png)

## Your Environment

- Docusaurus version used: **2.0.0-alpha.61**
- Environment name and version (e.g. Chrome 78.0.3904.108, Node.js 10.17.0): **84.0.4147.125**
- Operating system and version (desktop or mobile): **Windows 10**

## Reproducible Demo

Haven't uploaded an example as can be re-created by running startup commands.

**Comment by slorber** [comment]
Thanks

Yes the bootstrap theme is still a work in progress and not totally usable yet.

I don't have much time to work on it currently, if someone wants to improve it please do

**Comment by ketangupta34** [comment]
> Thanks
> 
> Yes the bootstrap theme is still a work in progress and not totally usable yet.
> 
> I don't have much time to work on it currently, if someone wants to improve it please do

can you provide a bit more information bout the same

**Comment by ketangupta34** [comment]
@slorber I would like to start working on this. some more information regarding the issue would be helpful.

**Comment by mohamedsgap** [comment]
hey @slorber, Can I take this one ?

**Comment by slorber** [comment]
Yes thanks, I can't dedicate any time to the bootstrap template currently, so any help to improve it would be welcome. I guess we are open to any kind of contribution as long as it becomes better ;)

**Comment by 93lykevin** [comment]
Hi @slorber, can I take this if it is still open? This will be my first open source contribution if merged.

**Comment by slorber** [comment]
Hi @93lykevin, thanks for your help.

For now I'd rather not ask you to contribute to this task, as we are currently figuring out what we want for the "theme gallery".  Also @fanny is already working on this theme and it's likely that we'll ask an intern from MLH to work on our theme gallery. For now I'll remove the "help wanted" label here

**Comment by slorber** [comment]
even going to close for now so that we can create more helpful issues for instructions on what shuld be done on the bootstrap theme
