### ISSUE TITLE
(v2) Metadata isn't included in build

### ISSUE THREAD

**Issue by martavis** [facebook/docusaurus#3330]
## 🐛 Bug Report

There is no metadata other than `title` showing in the build.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## To Reproduce

1. Install v2 alpha 61
1. Add metadata to docusuarus config
1. Run build

## Expected behavior

I expected to see meta tags `title`, `description`, `<meta og:..>` in the source code of each page.

## Actual Behavior

Only `<title>` is present.

## Your Environment

- Docusaurus version used: v2 alpha 61
- Environment name and version (e.g. Chrome 78.0.3904.108, Node.js 10.17.0): Microsoft Edge (Chromium)
- Operating system and version (desktop or mobile): Desktop

## Reproducible Demo

View the source code of https://answers.equityforhire.com.

## Other Tests

I first noticed this issue while attempting to share the URL above on Facebook. No metadata showed. Then I visited https://developers.facebook.com/tools/debug/ to scrape the data and no metadata was fetched.

Here is my `docusaurus.config.js`:

![image](https://user-images.githubusercontent.com/47053705/91104207-273ff180-e622-11ea-981f-45386b089348.png)

Then I attempted to add the `<Head>` component on my home page to force React Helmet as shown below:

![image](https://user-images.githubusercontent.com/47053705/91104332-640be880-e622-11ea-95ba-79a0b48235c0.png)

Unfortunately, still no metadata.

**Comment by slorber** [comment]
Hey @martavis , on Docusaurus v2 website it works for me:

![image](https://user-images.githubusercontent.com/749374/91423592-08777000-e859-11ea-8fa1-fc8f7a17d600.png)

![image](https://user-images.githubusercontent.com/749374/91423562-00b7cb80-e859-11ea-9b42-103708916db0.png)

2 ways I can help you:
- you submit a PR on d2 website so that I can see the issue in the deploy preview (we won't merge it)
- have access to your site's source code

**Comment by slorber** [comment]
closing for now

**Comment by martavis** [comment]
I finally got a chance to check this out again. I had major issues breaking my builds. 

It turns out that this was a user error. I have a higher-order component wrapping my pages to check for a public vs private page and it block the `Head` component from rendering. Everything works.
