### ISSUE TITLE
Opening a pdf link shows page not found

### ISSUE THREAD

**Issue by albin-joseph-wiznet** [facebook/docusaurus#3337]
## 🐛 Bug Report

# Opening a pdf link shows page not found

## To Reproduce

1. Step 1. head to (https://doc.wiznet.io/docs/Product/iEthernet/W5500/datasheet)
2. Step 2.. hit any of the following links 
- W5500 Datasheet v1.0.9 - English
- W5500 Datasheet v1.0.9 - Korean
3. Step 3... Reload the page makes it work fine

## Expected behavior

open the pdf in the same window similar to target"_self" without reload 

## Actual Behavior
 

Page not found 

<img width="2560" alt="Screenshot 2020-08-26 at 10 08 23 AM" src="https://user-images.githubusercontent.com/60734163/91256120-21fab800-e784-11ea-9da1-f95026873ff2.png">
<img width="2560" alt="Screenshot 2020-08-26 at 10 08 32 AM" src="https://user-images.githubusercontent.com/60734163/91256125-2626d580-e784-11ea-9cbd-4a6f6e4e4315.png">

**Comment by albin-joseph-wiznet** [comment]
edit

**Comment by fasolens** [comment]
I think it is because:
https://v2.docusaurus.io/docs/static-assets/#caveats
point 2.
I have the same issue and I set to open pdf links in new tab to workaround this.

**Comment by slorber** [comment]
Hmmm yes we should handle this better. Actually we have already merged #3096 that should improve this but it's not yet released (probably next week).

In the meantime you can use this:

https://v2.docusaurus.io/docs/markdown-features/#common-assets

Note you can require a pdf file in static folder (no relative path needed) with `require("@site/static/myPDF.pdf").default`.

**Comment by slorber** [comment]
Actually it was'nt exactly working as I thought, so this pr should fix it: https://github.com/facebook/docusaurus/pull/3347
