### ISSUE TITLE
Spelling Mistake 

### ISSUE THREAD

**Issue by iamshouvikmitra** [facebook/docusaurus#3338]
https://github.com/facebook/docusaurus/blob/306d3afc0a79340999a8e8bb2568c4965611a555/packages/docusaurus-theme-classic/src/theme/hooks/useAnnouncementBar.ts#L20

should have been 
```
themeConfig: {announcementBar: {id = 'announcement-bar'} = {}} = {},
```

**Comment by slorber** [comment]
thanks, will be fixed in https://github.com/facebook/docusaurus/pull/3343

also related: https://github.com/facebook/docusaurus/issues/334
