### ISSUE TITLE
Add spell checking to CI flow

### ISSUE THREAD

**Issue by JoelMarcey** [facebook/Docusaurus#334]
### Is this a bug report?

No. Enhancement.

Ref: https://github.com/facebook/Docusaurus/pull/327

### Have you read the [Contributing Guidelines](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md)?

Yes.

### Environment

N/A

### Steps to Reproduce

N/A

### Expected Behavior

N/A

### Actual Behavior

N/A

### Reproducible Demo

N/A

**Comment by neilsutcliffe** [comment]
Can we add accidental variable names into this as well? Stuff like the following?

- docusuarus
- langauges

And similar variations there-of.

**Comment by endiliey** [comment]
I think we should leave linting stuff to user.
