### ISSUE TITLE
Cleanup themes default/fallback values

### ISSUE THREAD

**Issue by slorber** [facebook/docusaurus#3342]
![image](https://user-images.githubusercontent.com/749374/91417254-cc401180-e850-11ea-94f4-789d962df003.png)

https://twitter.com/jaredpalmer/status/1298332787792109570

With the new theme validation/normalization, default values are applied ahead of time.

We should cleanup every piece of code that defines default/fallback values in the views unnecessarily because we don't want these fallback values to be duplicated everywhere, and it pollutes the code uselessly.

```jsx
const {
  siteConfig: {
    themeConfig: { announcementBar: { id = "annoucement-bar" } = {} } = {}
  } = {}
} = useDocusaurusContext();
```

Here, we know that there's always a siteConfig, a themeConfig, and maybe an announcement bar, so it's not necessary to use `= {}` each time.

Also, we should strive to have proper TypeScript support. It is possible to have no announcementBar config, but I don't think we should destructure that config, falling back to {} just to ensure a runtime error.

In such case, the correct code should rather be:

```jsx
const { announcementBar } = useDocusaurusContext().siteConfig.themeConfig;
if (announcementBar) {
  const {id,content} = announcementBar;
}
```

This announcementBar case has been fixed with https://github.com/facebook/docusaurus/issues/3338

But there are many other places where such cleanup should be done.

I suggest we should also:
- Add more config normalization tests (as Joi is not always so idiomatic)
- Add a `useThemeConfig` hook to reduce a bit boilerplate

**Comment by imskr** [comment]
@slorber I would like to start working on this!

**Comment by slorber** [comment]
Please do @imskr  :)

**Comment by imskr** [comment]
@slorber I have made a PR #3394
