### ISSUE TITLE
Inconsistent `Redirect` component behavior

### ISSUE THREAD

**Issue by marikaner** [facebook/docusaurus#3351]
## 🐛 Bug Report

Running docusaurus with redirects locally and on Github Pages produces different results. I have a markdown file that is supposed to redirect to another page:
```md
---
id: redirect-to-a
---

import {Redirect} from '@docusaurus/router';

<Redirect to='a' />
```

When running locally requesting `<path>/redirect-to-a` in a browser redirects me to `<path>/a` which is exactly what I want. On Github Pages it (sometimes) redirects me to `<path>/redirect-to-a/a` which gives me a 404. I have had multiple occasions where this worked for one page, but not the other.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

yes

## To Reproduce

1. For a local version I ran `docusaurus start`.
2. For the remote version I understand that `docusaurus deploy` is used.

## Expected behavior

Local and remote redirect behavior is the same.

## Actual Behavior

Local and remote redirect behavior differ.

## Your Environment

- Docusaurus version used: 2.0.0-alpha.61
- Environment name and version (e.g. Chrome 78.0.3904.108, Node.js 10.17.0): Chrome 84.0.4147.135 (Official Build) (64-bit) (although we also tried other browsers), 
- Operating system and version (desktop or mobile): macOS 10.15.6

## Reproducible Demo

I will give my best to provide this soon. I am a total newbie to docusaurus, so it will take me some more time to be able to reproduce this. In the mean time, maybe somebody has an idea as is.

One more thing that I tried was running `docusaurus build` and then `docusaurus serve` but it seems that this does not help me understand the issue because the resulting site did not have any css and redirects didn't redirect anywhere.

## Workaround

Btw, I also found a workaround that might be helpful to other encountering this, although I am not 100% happy with it, because I need to know the `<path>` for it:
```
---
id: redirect-to-a
---

import {Redirect} from '@docusaurus/router';
import useBaseUrl from '@docusaurus/useBaseUrl';

<Redirect to={useBaseUrl('<path>/a')} />
```

**Comment by slorber** [comment]
Hi,

It is not clear to me if you are using baseUrl or not, but docusaurus serve should work if you don't use any baseUrl. 

There is an issue to support baseUrl out of the box in docusaurus serve here: https://github.com/facebook/docusaurus/issues/3291

First thing would be to remove any baseUrl and check if the problem still happen without any baseUrl.
Also worth checking if the issue is not related to trailing slashes that can be added automatically by some hosts.

The URL of a Github Pages hosted website + the source code would help to debug this.

**Comment by marikaner** [comment]
Hey @slorber,

thanks I already made some progress based on your suggestions above. I am now able to locally run build + serve with the pages looking as expected. Redirection in this mode however does not work.

Anyways, this is the code for our documentation: https://github.com/SAP/cloud-sdk/tree/documentation and those are the Github pages: https://sap.github.io/cloud-sdk.

It seems to be indeed a trailing slash issue - https://sap.github.io/cloud-sdk/docs/js/features/odata/odata-v2-client is automatically being forwarded to https://sap.github.io/cloud-sdk/docs/js/features/odata/odata-v2-client/ I just don't understand why, yet.

**Comment by marikaner** [comment]
So after investigating this a bit, I am pretty sure that this is related to these existing issues:  https://github.com/facebook/docusaurus/issues/2654, https://github.com/facebook/docusaurus/issues/2394, https://github.com/facebook/docusaurus/issues/2134. Therefore I'll close this as a duplicate and hope that these issues will be addressed 😊

**Comment by slorber** [comment]
This behavior is proprietary to the hosting solution.

I also think it may be related to the file system structure we use: `./odata-v2-client/index.html` and not `./odata-v2-client.html`

Maybe we could change that, but that seems like a risky change and not sure to understand all the implications of this.

If we allow this, I'd rather make it opt-in somehow.

This behavior is provided by a deps: https://github.com/markdalgleish/static-site-generator-webpack-plugin/blob/master/index.js#L169

**Comment by slorber** [comment]
I've opened a dedicated issue: https://github.com/facebook/docusaurus/issues/3372
