### ISSUE TITLE
False reporting broken link when link is an email

### ISSUE THREAD

**Issue by thanasis00** [facebook/docusaurus#3353]
## 🐛 Bug Report

In a .md file I have a link with an email:

```
Contact [support@test.com](support@test.com)
```

and when I build the website I get the error: Broken links found!

as it tries to resolve the email link to an actual internal url, but it's not a website url.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## To Reproduce

1. Add `[support@test.com](support@test.com)` in any md page
2. Run `yarn build`

It will yield the broken link error

## Expected behavior

I expected the build process to not process the email link as an internal link.

## Actual Behavior

Docusaurus build process tried to validate the email link, and failed to do so as it's not an internal url.

## Your Environment

- Docusaurus version used: 2.0.0-alpha.61
- Environment name and version: Chrome Version 84.0.4147.135, Nodejs v12.18.2
- Operating system and version: OSX 10.15.6 (19G2021) desktop

## Reproducible Demo

Easily reproducible locally

**Comment by slorber** [comment]
Hi,

```
Contact [support@test.com](support@test.com)
```

this is not a valid link and will lead to the 404 page as we try to navigate to it: http://localhost:3000/docs/next/support@test.com

You should use the `mailto:` protocol:


```
Contact [support@test.com](mailto:support@test.com)
```
