### ISSUE TITLE
[v2.0.0-alpha.62] Can't build using docusaurus-plugin-sass

### ISSUE THREAD

**Issue by martavis** [facebook/docusaurus#3361]
## 🐛 Bug Report

On build, I receive this error pertaining to `docusaurus-pluging-sass`.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes
## To Reproduce

(Write your steps here:)

1. Install Docusaurus v2.0.0-alpha.62
1. Install and add `docusaurus-plugin-sass`
1. Build Docusaurus

## Expected behavior

Build without errors as with `alpha.61`.

## Actual Behavior

I received this error: 
```
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
ValidationError: Invalid options object. Sass Loader has been initialized using an options object that does not match the API schema.
 - options has an unknown property 'id'. These properties are valid:
   object { implementation?, sassOptions?, prependData?, sourceMap?, webpackImporter? }
```

## Your Environment

- Docusaurus version used: v2 alpha 62
- Environment name and version (e.g. Chrome 78.0.3904.108, Node.js 10.17.0): Node.js 10.16.2
- Operating system and version (desktop or mobile): Desktop

## Reproducible Demo

Simplified `docusaurus.config.js`:

```
module.exports = {
  ...siteOptions,
  ...presets,
  plugins: [
    require.resolve('docusaurus-plugin-sass'), 
    [
      require.resolve('docusaurus2-dotenv'), 
      { 
        path: './.env',
        systemvars: true
      }
    ],
    [
      require.resolve('@docusaurus/plugin-client-redirects'),
      {
        fromExtensions: ['html'],
      },
    ],
  ],
};

```

**Comment by slorber** [comment]
Thanks, submitted a fix to the plugin:
https://github.com/rlamana/docusaurus-plugin-sass/pull/5

**Comment by martavis** [comment]
Thanks!

**Comment by theodorDiaconu** [comment]
Thanks @slorber . We wait for release of the plugin creator.

**Comment by lex111** [comment]
In order to reduce staled issues, I am closing this issue, but feel free to open it again if needed.
