### ISSUE TITLE
onBrokenLinks: false positive

### ISSUE THREAD

**Issue by bravo-kernel** [facebook/docusaurus#3364]
## The Bug:

`onBrokenLinks` should not flag/parse below markdown as a broken link.
```md
-- Path [string] (required): Specifies a test to run.
```

## Why?

As can be seen above, it is not a link, because there is a space between `[]` and `()`

## To Reproduce

1. Insert above markdown into a Docusaurus page
2. Run `yarn build`
3. See that file updated in step 1 is flagged for containing a broken link

## Your Environment

Docusaurus alpha62, node 10.16.0, Win10 Desktop

## Reproducible Demo

https://github.com/pester/docs/pull/54

**Comment by slorber** [comment]
Hi,

It is likely that you actually have a link to /required somewhere.

onBrokenLinks does not do anything at the markdown level, it catches paths from rendered links, so there is a link somewhere

**Comment by slorber** [comment]
@bravo-kernel closing for now as I think it's an error on your site. 

If you think it's on Docusaurus side, please give me the code, the md doc path, the exact broken link error message, and a deploy preview
