### ISSUE TITLE
Versioned index.html not executed

### ISSUE THREAD

**Issue by bravo-kernel** [facebook/docusaurus#3365]
## 🐛 Bug Report

We have a live site using file `docs/index.html` to redirect users to the first actual page of our docs (`quick-start`).

That `index.html` file was created following the advice given by Endi in [issue 1932](https://github.com/facebook/docusaurus/issues/1932#issuecomment-549144816).

We made a version cut:

- and named it `v4`
- that cut now contains `index.html` (full path thus `versioned_docs/v4/index.html`)

The issue: when browsing to `docs/v4`, the `index.html` file inside `versioned_docs` is not executed.

## To Reproduce

Follow above steps or 

1. clone this [external Pull Request](https://github.com/pester/docs/pull/54)
2. browse to `http://localhost:3000/docs/quick-start` (to see working `index.html` inside root `docs` folder redirecting to the `quick-start` page)
3. then browse to `http://localhost:3000/docs/v4` (to see `index.html` inside that version is not working, user not being redirected but sees a 404 instead).

## Expected behavior

Execute the `index.html` file inside `versioned_docs/v4`

## Your Environment

D2 alpha62, nodejs 10.16.0, Win10, Desktop

## Alternative solution?

If replacing the `index.html` file with an `index.js` file (using the redirect component) is the advized solution, that is viable as a full/complete solution as well.

**Comment by slorber** [comment]
Hi,

Adding html and js files inside /docs or /versioned-docs folders won't do anything, and it's not the advise of Endi which was to put this file in /static

You should just use the redirect plugin for such usecase. Or use server-side redirects (preferably).

What we can do is to redirect automatically /docs/ to /docs/quick-start, if you don't use any "home doc", I think it makes sense by default.

**Comment by slorber** [comment]
Closing, see also this proposal feature: https://github.com/facebook/docusaurus/issues/3407

**Comment by bravo-kernel** [comment]
Thank you, that proposal is awesome.
