### ISSUE TITLE
Proposal: docusaurus clear command

### ISSUE THREAD

**Issue by slorber** [facebook/docusaurus#3370]
## 🚀 Feature

Having a clear command can be helpful, because sometimes errors are related to caching.

I think this clear command could just be a shortcut for:

```
rm -rf .docusaurus
rm -rf build
rm -rf node_modules/.cache/cache-loader
```

We should recommend users to try this command before reporting bugs, and also after upgrading Docusaurus version.

**Comment by abadon7** [comment]
Hi @slorber, I would like to work on this. I suppose the idea is to have a "yarn clear", am I right?

**Comment by abadon7** [comment]
@slorber, I already see in package.json a "clear" command: `"clear": "yarn rimraf website/.docusaurus && rimraf -rf website/node_modules/.cache && yarn lerna exec 'yarn rimraf lib' --ignore docusaurus"`
The only thing that I see missing is the `rm -rf build`. Please guide me and let me know what you have in mind. Thanks.

**Comment by slorber** [comment]
Hi

This clear command is for our own repo. What we must provide is a cli for all repos, should be added to packages/docusaurus using commander

**Comment by abadon7** [comment]
Hi.

:sweat_smile: Thanks. Now I get it. I haven't worked with commander yet, but I think I can do it with some of help.
