### ISSUE TITLE
normalizeUrl bug leads to routeBasePath issues

### ISSUE THREAD

**Issue by slorber** [facebook/docusaurus#3374]
## 🐛 Bug Report

The "normalizeUrl" pure utility function looks like to it has a bug.

https://github.com/facebook/docusaurus/blob/master/packages/docusaurus-utils/src/index.ts#L281

Tried to add the following test cases:

```
// ok
      {
        input: ['/'],
        output: '/',
      },

// fail      
      {
        input: ['', '/'],
        output: '/',
      },
      {
        input: ['/', ''],
        output: '/',
      },
```

And the 2 and 3 test cases failing seems unexpected to me

I think this is the reason why blog/docs option `routeBasePath: ''` fail, while `routeBasePath: '/'` works.

I'm going to disallow `routeBasePath: ''` as a fix for now (https://github.com/facebook/docusaurus/pull/3375).

But still think we should solve the normalizeUrl issue even if the `routeBasePath: ''` is fixed.

The function is not very easy to understand, but is totally pure, so if someone wants to try providing a fix that would be very helpful ;)

**Comment by ayshiff** [comment]
@slorber Can I grab this one ? 👍

**Comment by slorber** [comment]
yes @ayshiff thanks ;)
