### ISSUE TITLE
Swizzled SearchPage is not respected

### ISSUE THREAD

**Issue by martavis** [facebook/docusaurus#3379]
## 🐛 Bug Report

After swizzling Search component from `@docusaurus/theme-search-algolia`, the swizzled component is not rendered.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## To Reproduce

1. Install alpha 62
1. Create new project
1. Add Algolia settings
1. Swizzle `SeachPage` component/page
1. Modify the new `SearchPage` component/page
1. Start app
1. Visit localhost:3000/search

## Expected behavior

I expected to see the changes made in the swizzled SearchPage component/page.

## Actual Behavior

No changes were rendered.

## Your Environment

- Docusaurus version used: alpha 62
- Environment name and version (e.g. Chrome 78.0.3904.108, Node.js 10.17.0): Microsoft Edge (Chromium), latest (Aug 31, 2020)
- Operating system and version (desktop or mobile): Windows, desktop

## Reproducible Demo

Repo that includes Algolia settings and swizzled `SearchPage`: 
https://github.com/martavis/docusaurus-test-alpha62

**Comment by slorber** [comment]
Can confirm something weird is happening. 
Unfortunately I have no idea why it does not work. 

Probably related to webpack aliases ordering or something.

**Comment by martavis** [comment]
If that's correct, I want to reference #3211 to be thorough.

**Comment by slorber** [comment]
Thanks for your analysis @martavis 

I won't have time to work on this short term unfortunately, but if you or someone help find the cause that would be :)

**Comment by martavis** [comment]
Just checking in to see if anyone can help?
