### ISSUE TITLE
Error: Please set the GIT_USER environment variable!

### ISSUE THREAD

**Issue by novoselovaleksandr** [facebook/docusaurus#3389]
## 🐛 Bug Report

I can not deploy my docusaurus site. I try:
 cmd /C "set "GIT_USER=novoselovaleksandr" USE_SSH=true && yarn deploy"
and i get an error:
![image](https://user-images.githubusercontent.com/28715828/91964652-d9657080-ed28-11ea-82dd-82dcdc68cf06.png)
This is a part of my docusaurus.config.js
![image](https://user-images.githubusercontent.com/28715828/91964763-00bc3d80-ed29-11ea-8fa0-031194b09b3b.png)
what am I doing wrong?

[my repository](https://github.com/novoselovaleksandr/novoselovaleksandr.github.io)

**Comment by slorber** [comment]
Hi,

I don't know enough about windows nor have a windows computer to test this, but maybe you could try to use `echo % GIT_USER%` or something in the command to verify that the env variable is set correctly?

I guess the syntax may also depend on the Windows kind of shell you use.

You'd rather ask for help to the community on discord, I'm pretty sure you'll find someone that is able to deploy from Windows here

**Comment by jeremyhager** [comment]
I've had a similar issue before where I needed to change the quotes - so for your example you may need to do the following:

`cmd /C "set 'GIT_USER=novoselovaleksandr' USE_SSH=true && yarn deploy"`  
Notice the single quotes vs. double.

I will say I just ran `cmd /C "set "GIT_USER=jeremyhager" && yarn deploy"` within command prompt and it seemed to work just fine. However PowerShell will treat quotes differently, which is how I am assuming this is being deployed in your environment:
![image](https://user-images.githubusercontent.com/47301461/92122885-db731200-edb0-11ea-89ee-8663119822ff.png)

The differences here are that PowerShell sees the quotes in `"set "` as the command to run, but when switching for single-quotes PowerShell now recognizes the full command. Perhaps working on a request to update the Windows documentation is in order.

**Comment by slorber** [comment]
Thanks, can you try again with simple quotes @novoselovaleksandr ?

Also, any help to improve windows doc is welcome ;)

**Comment by arifszn** [comment]
Faced same error. Switching to window's default cmd worked.

**Comment by lex111** [comment]
Resolved in #3459

**Comment by talkohavy** [comment]
This also happened to me on Macos, so I can confirm it's not a Windows thing.

**Comment by Riversruntothesea** [comment]
配置环境变量
GIT_USER
值是你的GitHub名称

**Comment by Ajay-Dhangar** [comment]
I'm also facing this issue

```pwsh
PS F:\personal-sites\code-harbor-hub> npm run deploy

> code-harbor-hub@0.0.0 deploy
> docusaurus deploy

[WARNING] When deploying to GitHub Pages, it is better to use an explicit "trailingSlash" site config.
Otherwise, GitHub Pages will add an extra trailing slash to your site urls only on direct-access (not when navigation) with a server redirect.
This behavior can have SEO impacts and create relative link issues.

[INFO] Deploy command invoked...

Error: Please set the GIT_USER environment variable, or explicitly specify USE_SSH instead!
    at Command.deploy (F:\personal-sites\code-harbor-hub\node_modules\@docusaurus\core\lib\commands\deploy.js:70:19)

[INFO] Docusaurus version: 3.1.1
Node version: v20.10.0
PS F:\personal-sites\code-harbor-hub> 
```

**Comment by shay-ff** [comment]
> I'm also facing this issue
> 
> PS F:\personal-sites\code-harbor-hub> npm run deploy
> 
> > code-harbor-hub@0.0.0 deploy
> > docusaurus deploy
> 
> [WARNING] When deploying to GitHub Pages, it is better to use an explicit "trailingSlash" site config.
> Otherwise, GitHub Pages will add an extra trailing slash to your site urls only on direct-access (not when navigation) with a server redirect.
> This behavior can have SEO impacts and create relative link issues.
> 
> [INFO] Deploy command invoked...
> 
> Error: Please set the GIT_USER environment variable, or explicitly specify USE_SSH instead!
>     at Command.deploy (F:\personal-sites\code-harbor-hub\node_modules\@docusaurus\core\lib\commands\deploy.js:70:19)
> 
> [INFO] Docusaurus version: 3.1.1
> Node version: v20.10.0
> PS F:\personal-sites\code-harbor-hub>

In the config: Config = {
      trailingSlash: false,
}
just add this and it will be fine.
