### ISSUE TITLE
When using windows line endings ( CRLF ) sidebar and docs aren't rendered correctly.

### ISSUE THREAD

**Issue by nelKorajkic** [facebook/Docusaurus#339]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md)?

Yes

### Environment

Windows 10, Node 8.9.3, NPM 5.5.1, VS Code 1.19.0, Running locally through 'npm run start'

### Steps to Reproduce

1. Install docusaurus-init through npm and run 'docusaurus-init'.
2. Change the names docs-examples and website/blog-examples as specified in "Getting Started."
3. Open docs/doc1.md.
4. Change line endings from LF to CRLF.
5. Change into the website directory.
6. Run 'npm run start'.
7. Open http://localhost:3000.
8. Click 'Docs' in the navbar, on the top right

### Expected Behavior

I was expecting the same behavior that occurs when using Unix styled line endings ( LF ).
I was expecting the side bar that is associated with doc1 to have the sidebar_label value that is defined in doc1.md. This by default is "Example Page." 
I was also expecting when the title value which by default is "Latin-ish" to be styled as an H1.

### Actual Behavior

The sidebar label that is associated with doc1.md does not get the expected sidebar_label of "Example Page." When opening doc1 you can see it renders out the header fields that are located at the top of the .md file directly within the HTML. Refer to screenshot below.
![capture](https://user-images.githubusercontent.com/24925489/34237429-a7e42b5e-e5ca-11e7-868d-ccd8acb92e7d.PNG)

### Reproducible Demo

This can be reproduced using the starter files from the [Installation](http://docusaurus.io/docs/en/installation.html) instructions as I described in the steps to reproduce.
If this is not acceptable I can always make a new repository but it might just be easier for you to run 'docusaurus-init'!

**Comment by JoelMarcey** [comment]
Hi @nelKorajkic Thanks for your issue. I think this //may// be fixed (at least partly) in the upcoming 1.0.4 Docusaurus package, which I may be pushing tomorrow. 

See this commit: https://github.com/facebook/Docusaurus/commit/21cbece838706992a6aac5d4c32e780b29cf7485

**Comment by JoelMarcey** [comment]
cc @neilsutcliffe who sent that commit via pull request.

**Comment by neilsutcliffe** [comment]
It does indeed fix that. It fails to split out the header correctly when it sees windows style line endings.

So instead the id falls back to the filename

**Comment by nelKorajkic** [comment]
@JoelMarcey Thank you for the information! I'll be on the lookout for 1.0.4. 
@neilsutcliffe I did actually look through your issue for the 'npm run build' on Windows, which is what I was originally gonna report, but I only briefly glanced at your PRs. Great work on fixing those bugs!

This can be closed now, thanks a lot!

**Comment by JoelMarcey** [comment]
Hi @nelKorajkic - I just wanted to make sure your issue here was resolved. Did the fix work as you expected?

**Comment by nelKorajkic** [comment]
@JoelMarcey Yup the issue is resolved with [21cbece](https://github.com/facebook/Docusaurus/commit/21cbece838706992a6aac5d4c32e780b29cf7485)

Thanks for all the help @JoelMarcey and @neilsutcliffe .
