### ISSUE TITLE
[v2.0.0-alpha.63] Inline <code> element background-color incorrect in light mode

### ISSUE THREAD

**Issue by kyle-wilson** [facebook/docusaurus#3402]
## 🐛 Bug Report

Hi, v2.0.0-alpha.63 has introduced a bug with inline code elements (produced by single backticks in markdown) such that it always uses the dark mode color scheme, even in light mode. For reference, I believe the standard light mode code element background-color is supposed to be `#ebedf0`.

For example, see [the current docusaurus v2 site](https://v2.docusaurus.io/docs/docusaurus.config.js) in light mode.

It looks like there is a style overriding the light mode style (maybe [here, in this file](https://github.com/facebook/docusaurus/blob/master/packages/docusaurus-plugin-debug/src/theme/DebugLayout/styles.module.css) from the newly-released `@docusaurus-plugin-debug`?). I am also unable to override this style with my own in `custom.css`.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## To Reproduce

1. Create or open any `.md` or `.mdx` file in a Docusaurus project.
2. Add an inline code element with single backticks to the document. (e.g. \`myVar\`).
3. Serve the project.
4. Make sure light mode is ON.
5. See the inline code element's styling is fixed in the dark mode styling.

## Expected behavior

The expected behavior is that the inline code element will have a light background color and dark text color when in light mode, and a dark background color and light text color when in dark mode.

## Actual Behavior

The colors for inline code elements stay fixed in the dark mode color scheme (dark background, light text) in light mode. Here is a screenshot from the v2 Docusaurus site:

![image](https://user-images.githubusercontent.com/13631007/92198881-65ab8c80-ee2a-11ea-921e-a2243d01d77f.png)

## Your Environment

- Docusaurus version used: v2.0.0-alpha.63
- Environment name and version (e.g. Chrome 84, Node.js 12.18.1):
- Operating system and version (desktop or mobile): macOS 10.15.4

## Reproducible Demo

Visit any document with an inline code element on the current v2 Docusaurus site, such as [this one](https://v2.docusaurus.io/docs/docusaurus.config.js) with light mode on.

**Comment by slorber** [comment]
Thanks, you are right there's something wrong here.

Older PRs (like https://deploy-preview-3207--docusaurus-2.netlify.app/build/docs/next/docusaurus.config.js) do not have this problem, and indeed the debug plugin `code {}` css should rather be scoped

**Comment by slorber** [comment]
We'll get this fixed for the next release, in the meantime you can just turn the debug plugin off by using {debug: false} in the classic theme (it enables it in dev by default). Does this workaround work for you?

**Comment by kyle-wilson** [comment]
Yes, that workaround works. Thanks!
