### ISSUE TITLE
Inline HTML break markdown formatting

### ISSUE THREAD

**Issue by TomBrien** [facebook/docusaurus#3403]
## 🐛 Bug Report

Using inline HTML (i.e. `<img ... />`) causes further markdown formatted script to fail. Possibly related to #3402 

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## To Reproduce

1. Create a simple page containing, for example:
    ```html
    <img src='https://companion.home-assistant.io/assets/apple.svg' />Hello, world. `code`.
    ````
2. Build site

## Expected behavior

Expect the image to render inline and "code" to be formatted as inline code. The code can be rendered by including to line breaks between the HTML and the rest but this of course breaks the inline image. This gives:

![image](https://user-images.githubusercontent.com/12411302/92218402-f917a880-ee90-11ea-8a69-b1dd709616e2.png)

## Actual Behavior

Inline code not rendered. 

![image](https://user-images.githubusercontent.com/12411302/92218344-deddca80-ee90-11ea-88e1-483e7c09e0a5.png)

## Your Environment

- Docusaurus version used: 2.0.0-alpha63
- Environment name and version: Chrome  85.0.4183.83, yarn 1.22.4, node.js 12.16.1
- Operating system and version (desktop or mobile): Both

## Reproducible Demo

<https://github.com/home-assistant/companion.home-assistant/tree/fix-dark-logos> Should just need building that

See this PR home-assistant/companion.home-assistant#323
And the associated preview here: <https://deploy-preview-323--home-assistant-companion-docs.netlify.app/docs/core/sensors#activity-sensor>.

**Comment by slorber** [comment]
Hi,

This is the behavior of the MDX parser that we use.

You can test it here: https://mdxjs.com/playground

![image](https://user-images.githubusercontent.com/749374/92230354-44d74b80-eeab-11ea-88d7-566d5c6fa073.png)

You should report such issues to MDX directly

Note: MDX 2 could solve it already?

**Comment by TomBrien** [comment]
Just to update, `MDX@2` apparently fixes this. Is there a plan to update Docusaurus 2.0 to use MDX 2?

**Comment by slorber** [comment]
I guess we want to keep up to date with mdx but not sure we want to be early adopters at this point, so maybe worth waiting a bit for the 2.0 release, initial fixes, and proper migration documentation.
