### ISSUE TITLE
/docs/ should redirect to /docs/myFirstDoc ?

### ISSUE THREAD

**Issue by slorber** [facebook/docusaurus#3407]
## 🚀 Feature

Supposing we use docs without any "home doc" (ie there is no doc at path `/docs/`).

I think it make sense to redirect `/docs/` to `/docs/myFirstDoc`, using a client side redirect.

By "first doc", the existing heuristic is "first doc found in the first sidebar"

I guess it could also make sense to redirect `/docs/unknownDoc` to `/docs/myFirstDoc` instead of showing the 404 page? Not sure but curious to have your opinion.

**Comment by pkosiec** [comment]
That would be awesome. Also, for every subdirectory in `/docs`, it would be also great to redirect to a first doc there in the sidebar.

For example:
redirect `/docs/cli` to `/docs/cli/first-doc-under-cli-subdirectory`, assuming that in the `/docs/cli` there is `first-doc-under-cli-subdirectory.md` file, which is the very first link in the sidebar.

**Comment by slorber** [comment]
> Also, for every subdirectory in /docs, it would be also great to redirect to a first doc there in the sidebar.

There is not a strict correlation between a subfolder and a subpath. 2 docs in the same subfolder might be in different sidebars, different sidebar categories, and at very different URLs (using the slug frontmatter).

There is also no way to assign a URL path segment to a sidebar category currently. 

What you are probably looking for is the ability to have a category index doc, cf https://github.com/facebook/docusaurus/issues/2643

This can be seen as a way to bind a category to a given URL, but it requires to create a doc (ie, we should be able to display something at that URL but in practice you would be able to use a `<Redirect>` component in that doc through MDX if you really want to)

**Comment by Josh-Cena** [comment]
Building an API for this is not worthwhile IMO, since we can always use `slug` or the client-side redirect plugin with some very simple configuration or even `<Redirect>`. The API is going to disrupt the predictability of the docs plugin behavior and just makes the plugin take up work it shouldn't care about in the first place (client-side redirects).
