### ISSUE TITLE
Bad error when trying to swizzle a theme component

### ISSUE THREAD

**Issue by slorber** [facebook/docusaurus#3408]
## 🐛 Bug Report

Run `yarn workspace docusaurus-2-website swizzle @docusaurus/theme-classic Layout` on this repo

![image](https://user-images.githubusercontent.com/749374/92251752-97296400-eecd-11ea-80ed-9c2a2c8418cb.png)

The error is expected as it's an internal theme component, not necessarily recommended for swizzling (at your own risks).

But this message seems unexpected to me.

> Component "Layout" doesn't exists. "Layout" is swizzled instead of "Layout".

**Comment by compojoom** [comment]
I just ran into the same thing. The message is rather confusing, but what is even more confusing is that the suggested `--danger` flag doesn't work. 

I can make component swizzling work only for the provided example in the docs - `Footer` - for anything else it fails to find the component.

```
> docusaurus swizzle "@docusaurus/theme-classic" "NavbarItem"

Component "NavbarItem" doesn't exists. "NavbarItem" is swizzled instead of "NavbarItem".
Error: NavbarItem is an internal component, and have a higher breaking change probability. If you want to swizzle it, use the "--danger" flag.

```

**Comment by compojoom** [comment]
Well, actually I was running this with `yarn run swizzle` -> which in terms calls `docusaurus swizzle, but the arguments I was passing `--danger` was not passed over.

**Comment by slorber** [comment]
@compojoom yes this is confusing, we'll fix this.

Afaik older npm/yarn might need `-- --danger`, the `--` permit to pass  extra args.

**Comment by covalentbond** [comment]
hey @slorber I also faced this error "`${INTERNAL_COMPONENT}` is an internal component, and have a higher breaking change probability. If you want to swizzle it, use the "--danger" flag."

I think we could bring more clarity in the Error message by saying something like "If the error still exists, `try -- --danger`.
If yes, I would like to file a PR for the same.

**Comment by slorber** [comment]
I'm not sure what you mean @covalentbond . 
"If the error still exists" does not look like correct to me.
About `-- --danger`, the double `--` is needed for npm only, not yarn, but would be happy, to adapt to  the user's package manager automatically
