### ISSUE TITLE
Typo in markdownPageExample.md

### ISSUE THREAD

**Issue by jaguarondi** [facebook/docusaurus#3410]
## 📚 Documentation

Markdown import example in `website/src/pages/examples/markdownPageExample.md` imports the wrong chapter, see this comment:
https://github.com/facebook/docusaurus/commit/f234c407f1f279a76ab388df2bab4f33e8eadf85#r42067403

**Comment by slorber** [comment]
thanks @jaguarondi . Why not submitting a PR directly? you can just press the "edit" button on the source file :)
