### ISSUE TITLE
swizzle no working

### ISSUE THREAD

**Issue by EloFran** [facebook/docusaurus#3411]
## 📚 Documentation
**the function does not work:**
from: [https://v2.docusaurus.io/docs/using-themes](https://v2.docusaurus.io/docs/using-themes)
yarn run swizzle @docusaurus/theme-classic Footer

**Error:**
```
yarn run swizzle @docusaurus/theme-classic
yarn run v1.22.5
$ docusaurus swizzle @docusaurus/theme-classic
No component to swizzle
```

**Comment by slorber** [comment]
Hi, can you give more context about your env please?

Do you have a published opensource site to give us?

In which folder are you? OS? Does the folder contain spaces or special chars or whatever? 

Every detail is important to help solve this bug, as running this same command on Docusaurus 2 site itself does work.

**Comment by atomicpages** [comment]
I ran into an issuer early on as well while trying to swizzle `@docusaurus/theme-live-codeblock`. I was able to solve it by using the current `next` version of docusaurus.

Here's a snipped of the command running fine on macOS Catalina and `docusaurus@2.0.0-alpha.64`

```
yarn run swizzle @docusaurus/theme-classic Footer                                          
yarn run v1.22.5
$ docusaurus swizzle @docusaurus/theme-classic Footer

Success! Copied @docusaurus/theme-classic Footer to src/theme/Footer.

✨  Done in 4.88s.
```

**Comment by slorber** [comment]
Great to know, let's close it then
