### ISSUE TITLE
Show stack traces

### ISSUE THREAD

**Issue by joshribakoff** [facebook/docusaurus#3412]
## 💥 Proposal

Show stack traces on any error

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes.

Example:

I'm developing a plugin, when I try to run the CLI I just get this, which doesn't tell me where the error is, I now have to basically add `console.log` everywhere to try to bisect the problem, which is poor developer experience.

```
Starting the development server...
The "path" argument must be of type string. Received type undefined
```

Edit: just noticed it *sometimes* shows stack traces. The instance where it did not show it was when there was an error in the top level function exported by the plugin function eg `path.resolve(undefined)`

Edit 2: I think whether or not it shows a stack trace actually depends if the code throwing the error is called into from an async callback vs synchronously by docusaurus?

**Comment by slorber** [comment]
Are you on latest docusaurus version alpha 63?

Also can you tell me how to produce this error, if you where able to find out?
