### ISSUE TITLE
Duplicate menu items don't get unmounted, corrupted sidebar

### ISSUE THREAD

**Issue by joshribakoff** [facebook/docusaurus#3414]
## 🐛 Bug Report

Duplicate menu items don't get unmounted

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

yes

## To Reproduce

Put two items with the same name in a sidebar
![Screen Shot 2020-09-06 at 5 10 35 PM](https://user-images.githubusercontent.com/4021306/92338247-fde08600-f063-11ea-89e1-0de419eeb874.png)

When clicking between two docs pages that use sidebars, one of the items does not get unmounted
https://www.youtube.com/watch?v=OZsxQXXqJgs

## Expected behavior

fail the build, or unmount both items on transition

## Actual Behavior

build silently passes, weird mysterious behavior when browsing the site later on

## Your Environment

- Docusaurus version used: 2.0
- Environment name and version: Chrome 84
- Operating system and version (desktop or mobile): mac

## Reproducible Demo

https://github.com/rx-store/rx-store/tree/5028da4e162d91329b8d90de451a3036e9951496/apps/rx-store-website

**Comment by slorber** [comment]
Oh, this is weird 🤪 

It happens only in prod or also in dev too?

I've made a PR here that should fix it for alpha 62. Please report me if alpha 64 does not fix this problem.
https://github.com/facebook/docusaurus/pull/3418
