### ISSUE TITLE
Deploy on render failed with command not found

### ISSUE THREAD

**Issue by plusmultiply0** [facebook/docusaurus#3419]
I follow the guide on document to deploy my site on Render but it failed with<code>docusaurus-build: not found</code>.
I don't know why I got this. Please help me! Thanks!

here is the **log** from Render

Sep 7 09:15:41 PM  ==> It looks like we don't have access to your repo, but we'll try to clone it anyway.
Sep 7 09:15:41 PM  ==> Cloning from https://github.com/plusmultiply0/docSite...
Sep 7 09:15:41 PM  ==> Checking out commit 906b11fea65ee40c41d8c564e4dbcd4a067ccf81 in branch master
Sep 7 09:15:43 PM  ==> Detected Node version 12.16.1
Sep 7 09:15:45 PM  ==> Detected Node version 12.16.1
Sep 7 09:15:47 PM  ==> Running build command 'cd website; yarn install; yarn build;'...
Sep 7 09:15:47 PM  yarn install v1.22.4
Sep 7 09:15:47 PM  info No lockfile found.
Sep 7 09:15:47 PM  [1/4] Resolving packages...
Sep 7 09:15:47 PM  [2/4] Fetching packages...
Sep 7 09:15:47 PM  [3/4] Linking dependencies...
Sep 7 09:15:47 PM  [4/4] Building fresh packages...
Sep 7 09:15:47 PM  success Saved lockfile.
Sep 7 09:15:47 PM  Done in 0.04s.
Sep 7 09:15:47 PM  yarn run v1.22.4
Sep 7 09:15:47 PM  $ docusaurus-build
Sep 7 09:15:47 PM  /bin/sh: 1: docusaurus-build: not found
Sep 7 09:15:47 PM  error Command failed with exit code 127.
Sep 7 09:15:47 PM  info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Sep 7 09:15:47 PM  ==> Build failed 😞

and here is my **package.json**
{
  "license":"MIT",
  "scripts": {
    "examples": "docusaurus-examples",
    "start": "docusaurus-start",
    "build": "docusaurus-build",
    "publish-gh-pages": "docusaurus-publish",
    "write-translations": "docusaurus-write-translations",
    "version": "docusaurus-version",
    "rename-version": "docusaurus-rename-version"
  }
}

and my project address is [here](https://github.com/plusmultiply0/docSite)

**Comment by slorber** [comment]
Hi

I don't know specifically Render, but you can't run `docusaurus-build` command directly. It's either `yarn build` or `npm run build`

**Comment by slorber** [comment]
If you don't succeed running these commands with npm/yarn, you can also see if you have a file here: `website/node_modules/.bin/docusaurus-build`.

If that's the case you should be able to run it directly: `./website/node_modules/.bin/docusaurus-build`

**Comment by plusmultiply0** [comment]
@slorber 
Thanks. But, I have upgraded my site to v2.0 and it succeeds deploying on Render.

**Comment by slorber** [comment]
good choice, great to know :)
