### ISSUE TITLE
v2: allow overriding default remark plugins in `content-docs`

### ISSUE THREAD

**Issue by lunelson** [facebook/docusaurus#3437]
## 🚀 Feature

I would like to override the default remark plugins in the [`content-docs`](https://v2.docusaurus.io/docs/using-plugins/#docusaurusplugin-content-docs) plugin: for example, to have control over the markup generated by `remark-admonitions`. Perhaps we could have an option to turn the default ones on/off?
 
Or alternatively: the `content-blog` plugin allows the options `beforeDefaultRemarkPlugins` and `beforeDefaultRehypePlugins`, which if they were supported in docs-content (the docs say they are, but they are not) would allow me to insert my own plugin to process remark before the default one can be run

**Comment by slorber** [comment]
Make sense, we should have an option like beforeDefaultRemarkPlugins for all plugins supporting remark to make all this uniform (blog + docs + pages)

**Comment by ayshiff** [comment]
Can I work on it @slorber ?

**Comment by slorber** [comment]
Yes thanks 😉

Le sam. 19 sept. 2020 à 11:22, Rémi Doreau <notifications@github.com> a
écrit :
