### ISSUE TITLE
Can we make documentation website about documentation?

### ISSUE THREAD

**Issue by damusix** [facebook/docusaurus#3442]
## 💥 Proposal

I would like to politely and respectfully propose we keep politics out of our work environments. I'm all for showing support for what you believe in, but it would be nice if we could keep code docs about code docs and not politics. Not everyone agrees with the principles or political views of BLM and it's a bit annoying / triggering / distracting to see my favorite tools constantly spamming me political messages while I am working. Please consider removing political messages from site's banner.

**Comment by slorber** [comment]
seems the BLM banner has been removed by @JoelMarcey so closing
