### ISSUE TITLE
v2: Add support for key, cert, ca when using https

### ISSUE THREAD

**Issue by facultymatt** [facebook/docusaurus#3445]
## 🚀 Feature

When using https it's common to provide your own key, cert, and ca. These options can be configured in webpackDevServer but need to be supported by Docusaurus `start` command to make them work. This feature request is for supporting these options, and doing so the same way Create React App does to keep the experience consistent. 

Here are the docs: https://webpack.js.org/configuration/dev-server/#devserverhttps

Here is some relevant code form CRA: https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/config/getHttpsConfig.js#L57-L58

Here is the documentation in CRA: https://github.com/facebook/create-react-app/blob/master/docusaurus/docs/using-https-in-development.md#custom-ssl-certificate

Here is where this would need to be added in Docusaurus: https://github.com/arcvats/docusaurus/blob/89a70622a6e48ac71b94369e6e0056270ebf46d2/packages/docusaurus/src/commands/start.ts#L132

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

yes

## Motivation

https is important to support, and keeping a consistent experience with CRA makes it easier for developers to get started.

## Pitch

SSL all the things! 🤓

## Related 

https://github.com/facebook/docusaurus/issues/3301

**Comment by ThakurKarthik** [comment]
@lex111 @slorber I want to work on this.Here is what i think I will be doing, I will be changing this line https://github.com/arcvats/docusaurus/blob/89a70622a6e48ac71b94369e6e0056270ebf46d2/packages/docusaurus/src/commands/start.ts#L145 to the return value of the [getHttpsConfig](https://github.com/facebook/create-react-app/blob/d5c0fe287a6bc24c60ee52ca768bdf3a10b937e1/packages/react-scripts/config/getHttpsConfig.js#L57-L58). So if ssl certs are given through the cli it will return the object else it will be the value as before `HTTPS === 'true';`

**Comment by slorber** [comment]
Thanks @ThakurKarthik , that makes sense to me.

Also having some doc on how to run the site locally under https would be nice, maybe some links to how to generate the certs etc. Would also make it easier for me to review ;)
