### ISSUE TITLE
Launching Docusaurus V2 as installed PWA on Windows just shows manifest.json instead of the site

### ISSUE THREAD

**Issue by krillboi** [facebook/docusaurus#3447]
## 🐛 Bug Report

After installing `v2.docusaurus.io` as a PWA on Windows through Chrome and then relaunching it, I am just greeted with the `manifest.json` file. See gif below:

![pwa-bug](https://user-images.githubusercontent.com/59022282/93068429-b918a880-f67c-11ea-9166-5a41ce701b0e.gif)

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes.

## To Reproduce

1. Navigate to `v2.docusaurus.io` through Chrome.
2. Press the `+` button to install the site as a PWA.
3. Close the app.
4. Launch the app.
5. `manifest.json` appears.

## Expected behavior

The app should show the site and not just the `manifest.json` file.

## Actual Behavior

The `manifest.json` file is shown.

## Your Environment

- Docusaurus version used: alpha.64.
- Environment name and version: Chrome Version 83.0.4103.61.
- Operating system and version (desktop or mobile): Windows 10 Version 10.0.17763 Build 17763

## Reproducible Demo

Can be tested through `v2.docusaurus.io`.

**Comment by ashscodes** [comment]
I've test this in the new Microsoft Edge on Windows 10 and in Chrome/Microsoft Edge on MacOS and it's doing the same thing. Our personal app is working. I suspect it might be an issue in the `manifest.json` file here [manifest.json#L7](https://github.com/facebook/docusaurus/blob/9bf4dfb2759759c14d99df6daebbacf833109d78/website/static/manifest.json#L7). I _think_ the _scope_ and _start_url_ should both be _"/"_.

**Comment by slorber** [comment]
Thanks, you are right.

Tried to find a solution here so that our deploy preview under baseurl still work to install/test the PWA setup: https://deploy-preview-3438--docusaurus-2.netlify.app/classic/

But apparently this broken both after you relaunch the app 😅
