### ISSUE TITLE
[v2]: Add option to skip dependency install when initializing new Docusaurus project

### ISSUE THREAD

**Issue by facultymatt** [facebook/docusaurus#3450]
🚀 Feature

When initializing a new Docusaurus project, a user might wish to skip the dependency install and handle it later on their own. This would be done by passing a flag such as `npx @docusaurus/init@next init [name] [template] --skip-install `. This is supported in other React ecosystem libraries such as Storybook, and there is an open issue on Create React App for this feature, too: https://github.com/facebook/create-react-app/issues/7568

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## Motivation

This feature would be especially useful when installing Docusarus as one of many packages in a project and wanting to install all dependencies at one time at the end to help avoid conflicts and speed up each individual install. A Lerna project or Yarn Workspace comes to mind.

## Pitch

Run `npx @docusaurus/init@next init [name] [template] --skip-install` and get work done faster!

**Comment by facultymatt** [comment]
This change would wrap the following lines in a conditional based on the flag: https://github.com/facebook/docusaurus/blob/master/packages/docusaurus-init/src/index.ts#L154-L164

**Comment by slorber** [comment]
@facultymatt I'm not against, but do you actually plan to use this feature? 
I wonder if it's useful to add an option if nobody feels the need for using it right now, as it seems a particularly niche usecase and our userbase is likely smaller than CRA/Storybook. Any option that we provide and is never used is cluttering the project.

If so, as you have a good idea of how to implement it, are you interested to submit a PR?

**Comment by alexnaiman** [comment]
Hello! Can I try to tackle this issue for the Hacktoberfest2020? If so, can you assign it to me?

**Comment by facultymatt** [comment]
Hello, we have a branch what fixes this, just waiting on our company to
address the CLA to open the PR.

I’d suggest tackling something else for the hack event! 👍👍

**Comment by slorber** [comment]
Thanks, waiting for your PR @facultymatt 

Still interested to know: do you actually need this feature? I'm not 100% sure to understand in which case I'd use it. Do yu often init a new docusaurus project at the same time as you bootstrap a monorepo?

**Comment by facultymatt** [comment]
Thanks @kumaraditya303 for the PR. Yes @slorber we do this quite frequently - we always use Docusaurus for the landing page / docs and then create react app for the application. Testing out the new flag now. Thanks again!
