### ISSUE TITLE
[v2]: Not require GIT_USER when using ssh

### ISSUE THREAD

**Issue by isy** [facebook/docusaurus#3454]
## 💥 Proposal

GIT_USER environment variable is required for deploying, but in case of SSH, I think there is no problem without GIT_USER.

If USE_SSH is true, I'd like to fix it so that GIT_USER is not needed. Is there any problem with this?

https://github.com/facebook/docusaurus/blob/6e43c9bd34fc3afbde07da52f91220de0582d204/packages/docusaurus/src/commands/deploy.ts#L29-L32

https://github.com/facebook/docusaurus/blob/6e43c9bd34fc3afbde07da52f91220de0582d204/packages/docusaurus/src/commands/deploy.ts#L75-L79

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

👍

**Comment by slorber** [comment]
Hi,

I'm not using GH pages. Have you tested these changes locally and it works fine without GIT_USER and with USE_SSH?

Any help to setup and document carefully the GH deployment workflow is welcome, it's very likely we can improve those.
