### ISSUE TITLE
Add a config option to allow custom version to be shown first

### ISSUE THREAD

**Issue by JoelMarcey** [facebook/Docusaurus#346]
### Is this a bug report?

No. Feature request

### Have you read the [Contributing Guidelines](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md)?

Yes.

### Environment

N/A

### Steps to Reproduce

N/A

### Expected Behavior

Add a `siteConfig.js` option that allows you to explicitly specify a valid version to show by default and then just check for that option when rendering.

Use case:

> I looked at the version support of Docusaurus and I think for Relay, we would prefer to have an archived version of the old APIs and latest to make sure doc updates are visible quickly. Currently, when opting in to versions, the latest released version is the default. Could we add an option to make master the default version?

### Actual Behavior

N/A

### Reproducible Demo

N/A

**Comment by iRoachie** [comment]
Jumping on this band wagon.

Use case:
> We have both a stable and beta version on npm at same time. Running `npm install` will give the user the stable version. However since the versioning in Docusaurus is chronological, then the default version when viewing the docs would be the beta version. Ideally it would be best to show the stable version as the default and then beta users have the option to change.

**Comment by iRoachie** [comment]
Hey @JoelMarcey what would I need to do to enable this functionality?

**Comment by JoelMarcey** [comment]
Hey @iRoachie - good to hear from you again. Are you saying enable in terms of creating a PR?

**Comment by iRoachie** [comment]
If it's something I can fix sure. Can you at least point me in the right direction?

**Comment by JoelMarcey** [comment]
@iRoachie Can you try this PR out on your site - https://github.com/facebook/Docusaurus/pull/554

Let me know if you get good behavior.

Just add

```
defaultVersionShown: 'xxxx',
```

to your `siteConfig.js` where `xxxx` is a valid version number for you.

Thanks.

**Comment by JoelMarcey** [comment]
The PR is an RFC, btw. If it is reasonable, we will want to make some more changes, including maybe checks to make sure the version given for `defaultVersionShown` is valid, etc.

**Comment by iRoachie** [comment]
Works great @JoelMarcey. I've had no issues. I even tried running a version(`yarn version 1.xx`) and the links and everything work as they should

**Comment by iRoachie** [comment]
Not yet published, but I just added the [commit](https://github.com/react-native-training/react-native-elements/commit/276b346c4ccef1a9b330de8bf9c7cd727724b2cd) over at react-native-elements/next.

I have it on a slightly modified [fork](https://github.com/iRoachie/Docusaurus/tree/default-version) of Docusaurus that also includes `prismjs` markdown rendering instead of the default renderer.
