### ISSUE TITLE
Enhance documentation about adding Docusaurus in an existing repository

### ISSUE THREAD

**Issue by felipecrs** [facebook/docusaurus#3463]
1. You might want to add an example of the folder structure to make it very clear how it would look like (mentioning the parent folder), such as:

```
- src/ # Project's source folder
- website/ # Docusaurus root
  - docs/
  - package.json # Docusaurus'
- package.json # Project's
```

2. I also see that some projects, even with docusaurus v2, prefers to use the docs folder in the root directory rather than in the site's directory. Personally, I also prefer that and I believe that it makes much more sense, since the `docs` are much more tied with the source code rather than with the `website` (you can switch the website provider for example without having to change the `docs` at all). So, this can be mentioned in the documentation as well.

**Comment by slorber** [comment]
Thanks for the suggestions.

Where should we put such docs exactly? Can you submit a PR?

**Comment by PatelN123** [comment]
@Josh-Cena Is this like what I am now doing? Would I be able to claim this?

**Comment by Josh-Cena** [comment]
Yes, for sure :) It's tricky to write—don't write a lot about monorepos, just a few sentences showing what the repo structure would be like is fine.

**Comment by PatelN123** [comment]
👍🏽

**Comment by PatelN123** [comment]
What category would you like it adding to @Josh-Cena?

**Comment by Josh-Cena** [comment]
I tried adding it in Installation. I think that's the only place that makes sense. We have a site structure rundown, just put the instructions immediately after that

**Comment by PatelN123** [comment]
PR is opened here: https://github.com/facebook/docusaurus/pull/6297
