### ISSUE TITLE
docusaurus docs:version overwrite option

### ISSUE THREAD

**Issue by maksnester** [facebook/docusaurus#3478]
## 🚀 Feature

Add some `--force` or `--overwrite` flag to `docusaurus docs:version` command. 

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Sure.

## Motivation

Currently, the `docusaurus docs:version` command fails if a version is already exists, but for version range like 1.x, it might be convenient to simply replace the whole 1.x content with the `next` version.

**Comment by slorber** [comment]
Hi

I think I answered on Discord already but you don't need to version 1.x,
you can rename /next to /v1.x instead

**Comment by slorber** [comment]
I think I answered you on Discord already.

Tell me if this does not work for you, but it should.

![image](https://user-images.githubusercontent.com/749374/94460861-a2fd0300-01b9-11eb-88ca-c32b164c0889.png)

**Comment by slorber** [comment]
See in particular https://v2.docusaurus.io/docs/versioning/#figure-out-the-behavior-for-the-current-version

**Comment by fflaten** [comment]
Sorry for reviving an old topic, but could we reconsider this? This is useful when you use current as canary/preview and want to promote to a stable or versioned major/minor.

Example scenario incl. workaround: https://github.com/maester365/maester/blob/5dc57219f18452153ab06e63cb55967adfbe9752/.github/workflows/update-stable-docs.yaml#L34-L39

**Comment by slorber** [comment]
@fflaten can you explain better, giving a concrete example, using concrete version numbers?

You want a single "Stable" version docs that will change name over time? (2.0 => 2.1 => 2.2 etc?)

As far as I understand your commit is not deployed on https://maester.dev/ so it's hard to understand the outcome you want to achieve.

**Comment by fflaten** [comment]
No name change, just overwrite content. You can find the full example here: https://github.com/fflaten/maester/tree/docs-preview
<img width="212" height="128" alt="Image" src="https://github.com/user-attachments/assets/ab74702b-4e9a-49ec-8cf5-ceabfc4cc46c" />

The idea is to use versions for major versions only or in this case just Stable (latest GA) vs Preview. You write docs to current during previews, like Canary on docusaurus.io, and when there's a release we simply overwrite the statically named `Stable` (GA) or latest major like `v2` versioned-docs to make it official. We expect users to use the latest version for support, so minor/patch changes are labeled in content with badges/pills etc.

Goal is to reduce versions to a minimum per [best practice](https://docusaurus.io/docs/versioning#version-your-documentation-only-when-needed) and avoid separate preview.website.com deployments. No reason to make minor/patch versions when it's 99% duplicate.

Feels like a minor ask for major gain in flexibility for the versions-feature. 🙂 Just a `--force-overwrite` flag and maybe mention it in the "version already exists" error

**Comment by slorber** [comment]
Ok makes sense

Accepting PRs for an `--overwrite` option
