### ISSUE TITLE
"yarn run publish gh-pages" not picking up CSS files under website/static directory

### ISSUE THREAD

**Issue by divya-mohan0209** [facebook/docusaurus#3482]
## 🐛 Bug Report

I am using docusaurus v1.14.5 to host static content generated & styled by Sphinx. The workflow looks like this:

RST & .py files (Python) -> HTML + CSS + JS files  --> This is done by Sphinx & I've placed this under the website/static folder.

I then made modifications to the siteConfig.js per this documentation - https://docusaurus.io/docs/en/publishing & deployed to GH-pages.

Before deploying on  to GH-pages, I tested locally and the content seemed to be rendered fine.

However, after deploying the css/fonts files seem to not be pushed to the gh-pages branch. 

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

YES

## To Reproduce

(Write your steps here:)

Steps: 
1. Place content (HTML + CSS) in static folder
2 . Test content locally: yarn run build OR npm run build --> The local rendering will be okay.
3.  Publish content to gh-pages using steps mentioned in https://docusaurus.io/docs/en/publishing. The CSS files under website/static will not be pushed to GH-pages.

## Expected behavior

This is the expected behavior after UPLOADING CSS content to the github repo: https://divya-mohan0209.github.io/docusaurus-current-theme/rucio/

(Write what you thought would happen.)

## Actual Behavior

The actual behaviour prior to uploading of the CSS files was that there was NO styling for this page.

## Your Environment

- Docusaurus version used: docusaurus v1.14.5
- Environment name and version (e.g. Chrome 78.0.3904.108, Node.js 10.17.0): Chrome(85.0.4183.121), Microsoft Edge(85.0.564.51),  Mozilla Firefox, NodeJs(v10.19.0), NPM (6.14.4), Yarn (1.22.5)
- Operating system and version (desktop or mobile):  Windows 10 (Desktop), Android (Mobile)

## Reproducible Demo
N/A

**Comment by jmk-developer** [comment]
Hey, I'm having the same issue.
I think the issue is that the site is looking in the wrong place for stylesheets. 
For example, on my site everything is here: sitename.github.io/website including the HTML and CSS.

sitename.github.io/website/index.html works, but it's looking for something like sitename.github.io/style.css instead of sitename.github.io/website/style.css.

No idea how to fix this.

**Comment by divya-mohan0209** [comment]
I think I figured this out, you need to pass the paths where your
customized css files to the separateCss:[] directive in the siteConfig.js
file.

This helped me. Hope it works for you too!

Regards,
Divya

**Comment by jmk-developer** [comment]
Hello. I found a different solution, but thanks for the help. Have a nice day.

**Comment by slorber** [comment]
great to know it works fine for you :)
