### ISSUE TITLE
Navbar logo is broken in Firefox (both V1 and V2)

### ISSUE THREAD

**Issue by sambeckingham** [facebook/docusaurus#3484]
## 🐛 Bug Report

I first noticed this issue working on the [Yew](https://yew.rs) docs.  Upon attempting to fix it, it appears it's not coming from Docusaurus but rather from the styles provided by Infima.

I cannot verify this of course, because Infima appears to have removed its [git repo](https://github.com/facebook/infima). However, I can't see anywhere in the Docusaurus repo that would implement the offending style.

### Examples:

Yew:
![image](https://user-images.githubusercontent.com/48661226/94271744-f6611e00-ff39-11ea-85ce-2ad4f7454f53.png)

Infima:
![image](https://user-images.githubusercontent.com/48661226/94271927-3d4f1380-ff3a-11ea-9d58-77810a0378a0.png)

Docusaurus:
![image](https://user-images.githubusercontent.com/48661226/94271971-4d66f300-ff3a-11ea-8d1a-11fa5ff2cb7c.png)

This behaviour does not exist in MS Edge.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## To Reproduce

1. Open any docusaurus site in Firefox
  - [Docusaurus](https://docusaurus.io/)
  - [Docusaurus 2](https://v2.docusaurus.io/)
  - [Yew](https://yew.rs)

## Expected behavior

I would expect the logos to maintain their aspect ratio and not break the layout of the header text.  This can easily be fixed by changing the `height: 100%` style to `max-height: 100%`, for example in the Docusaurus 2 styles:

```css
.navbar__logo {
    height: 100%;
    margin-right: 0.5rem;
}
```

Would become
```css
.navbar__logo {
    max-height: 100%;
    margin-right: 0.5rem;
}
```

Result:
![image](https://user-images.githubusercontent.com/48661226/94272686-4c829100-ff3b-11ea-904b-af468f3c00fb.png)

## Actual Behavior

See first section.

## Your Environment

- Docusaurus version used: Latest v1/v2
- Environment name and version (e.g. Chrome 78.0.3904.108, Node.js 10.17.0):
- Operating system and version: Windows Desktop

## Reproducible Demo

Go to the Docusaurus site!

My main reason for raising this issue is more of a concern with the apparently no longer open source dependency with Infima and how it can seemingly break sites using Docusaurus, outside of the control of the Docusaurus repo.

**Comment by lex111** [comment]
@sambeckingham which version of Firefox are you using? I cannot reproduce this.

**Comment by slorber** [comment]
Not able to reproduce either.

@sambeckingham will re-open if you provide a specific version of firefox with which it can be reproduced. 

Note v1 does not use Infima, so it does not look like it's related to Infima to me, but rather a bug in a specific Firefox version.
