### ISSUE TITLE
Please support Language-specific Code Tabs in Markdown!!!!

### ISSUE THREAD

**Issue by kehuo** [facebook/docusaurus#3486]
## 🚀 Feature

In the [version1 document](https://docusaurus.io/docs/zh-CN/doc-markdown#language-specific-code-tabs), I saw Markdown supports Language-specific Code Tabs.

But in v2 document, i didn't see this feature.

## Pitch
Reason:
I plan to use docusaurus to build my self-learning website. In my markdown content, there are many codes needs to be displayed, I need to compare the difference between 2 different programming lang such as Java / Python. So I needs to use tabs.

Please let me know how I can use it in v2 docusaurus, thanks!

**Comment by lex111** [comment]
This feature is actually supported in v2, here's [example in our docs](https://github.com/facebook/docusaurus/blob/master/website/versioned_docs/version-2.0.0-alpha.64/deployment.md#deploy):

![image](https://user-images.githubusercontent.com/4408379/94332312-d7679800-ffdc-11ea-9cc9-7936b530035a.png)

**Comment by slorber** [comment]
Feature is documented here: https://v2.docusaurus.io/docs/markdown-features/#multi-language-support-code-blocks

It's just not the same syntax as v1
