### ISSUE TITLE
[V2] Versioning Dropdown doesn't show "Next" version

### ISSUE THREAD

**Issue by greghesp** [facebook/docusaurus#3487]
## 🐛 Bug Report

`type: 'docsVersionDropdown', position: 'left'` is not showing as a dropdown with `Current Version` and `Next`

 This produced by 3.x.x documents fine, and when i `yarn start` they show u

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## To Reproduce

1. Run `docusaurus docs:version 3.x.x` - 3.x.x folders, sidebars and versions.json created
2. Modify `/docs` for in development version
3. Run `docusaurus start` 
4. Check Navigation bar for dropdown

## Expected behavior

Expected dropdown to be in Navbar
![image](https://user-images.githubusercontent.com/768908/94343506-97baa380-0010-11eb-9440-21a2eebf008b.png)

## Actual Behavior

Navigation bar only shows the latest version with no dropdown.
![image](https://user-images.githubusercontent.com/768908/94343499-8b364b00-0010-11eb-8df4-53a3c73869fc.png)

URLs to the next documentation however work

/docs/next/introduction - shows documentation with the unreleased documentation warning. Shows `Next` in place of dropdown

/docs/introduction - shows versioned documentation with version tag. Shows version in place of dropdown

## Your Environment

- Docusaurus version used: 2.0.0-alpha.64
- Environment name and version (e.g. Chrome 78.0.3904.108, Node.js 10.17.0): Chrome 85.0.4183.121, Node 10.15.1
- Operating system and version (desktop or mobile): MacOS 10.15.7

## Reproducible Demo

https://assistantrelay.com/
https://github.com/greghesp/assistant-relay/tree/doc-src

**Comment by lex111** [comment]
Already fixed in #3472 but thank you for the report.

**Comment by greghesp** [comment]
Ah so it is!  Thanks, will wait for `.65`

**Comment by slorber** [comment]
thanks @lex111 👍 

In the meantime you can try swizzling the DocsVersionDropdownNavbarItem component to backport the fix if you can't wait for next release

**Comment by greghesp** [comment]
I did try to swizzle it, however it seems to throw errors on every attempt
```
Component "DocsVersionDropdownNavbarItem" doesn't exists. "DocsVersionDropdownNavbarItem" is swizzled instead of "DocsVersionDropdownNavbarItem".
Error: Component DocsVersionDropdownNavbarItem not found.No component to swizzle
```

**Comment by slorber** [comment]
Thanks for reporting @greghesp , seems quite similar to https://github.com/facebook/docusaurus/issues/3466

**Comment by greghesp** [comment]
@lex111 Did this make it into .65?  I've upgraded but still not got the dropdown

**Comment by lex111** [comment]
@greghesp is this still relevant to you? I just opened your website that uses .65 https://assistantrelay.com/, and I see that dropdown is displayed correctly. Or is it something else wrong here?

**Comment by greghesp** [comment]
Ah i wonder if there was some caching or something.  All looks to be working on my end now too!

**Comment by lex111** [comment]
It may well be, I suppose. But great that this issue was resolved anyway!
