### ISSUE TITLE
versioned sidebar is not getting created while releasing a version

### ISSUE THREAD

**Issue by uditgaurav** [facebook/docusaurus#3488]
## 🐛 Bug Report

I'm creating a new release but the versioned sidebars are not getting created. I'm using the following commands:
```bash
cd website
npm install
npm run version 1.9.0 
```

This creates the versioned_docs but not the versioned_sidebar.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

yes

## To Reproduce
```
# clone the repository
1. git clone https://github.com/litmuschaos/litmus-docs.git
# Make some changes under the docs section like version update
2. find ./ -type f -exec sed -i -e 's/api\/chaos\/1.8.1?file=charts/api\/chaos\/1.9.0?file=charts/g' {} \;
# create a new release that is 1.9.0
3.  | cd website
       npm install
       npm run version 1.9.0 
```
## Expected behavior

Along with versioned docs, the versioned sidebar should also get created
## Actual Behavior

The versioned sidebar is not getting created:

![Screenshot from 2020-09-27 01-31-36](https://user-images.githubusercontent.com/35391335/94349447-0ecc5800-0062-11eb-872e-008feacf4723.png)

(Write what happened. Add screenshots, if applicable.)

## Your Environment

- node version - v8.10.0 
npm version:
{ npm: '6.14.5',
  ares: '1.14.0',
  cldr: '32.0.1',
  http_parser: '2.7.1',
  icu: '60.2',
  modules: '57',
  nghttp2: '1.30.0',
  node: '8.10.0',
  openssl: '1.0.2n',
  tz: '2017c',
  unicode: '10.0',
  uv: '1.18.0',
  v8: '6.2.414.50',
  zlib: '1.2.11' }

- yarn version v1.21.1

- Operating system and version (desktop or mobile): ubuntu18.04

## Reproducible Demo

(Paste the link to an example repo, including a `siteConfig.js`, and exact instructions to reproduce the issue.)

**Comment by slorber** [comment]
Hi, this is a v1 bug and I'm not very familiar with its codebase as I mostly work on v2.

I can see you have a lot of versioned sidebars here: https://github.com/litmuschaos/litmus-docs/tree/master/website/versioned_sidebars

How comes it worked before and it does not work anymore now? Did you change anything? Did you update Docusaurus and think there is a regression?

It seems this 13 days old PR did successfully create the versioned sidebars, so you may ask @ksatchit how he did?
https://github.com/litmuschaos/litmus-docs/pull/356

**Comment by uditgaurav** [comment]
@slorber we matched the versions:
- node: v8.10.0
- npm: 3.5.2
- platform: ubuntu:18.04
- docusaurus: 1.13.0
- sharing same repo

It works fine for Karthik but not for me. Any other env or parameter we should match?

**Comment by slorber** [comment]
Can you double check the exact command you run, from which folder, and both of you share your env?

I don't have a clue why it does not work just for you. As your colleague is able to version the docs and we really want to progress on v2 release, I'm not sure we should work on this (unless it affects more than 1 user).

**Comment by slorber** [comment]
The Docusaurus team is actively working on Docusaurus v2.

After a very long alpha, Docusaurus v2 is [now in beta](https://docusaurus.io/blog/2021/05/12/announcing-docusaurus-two-beta).
We believe that the v2 beta is already better than v1, and v2 is ready for maintstream adoption.

Apart from critical issues and security fixes, we don't plan to invest much time on Docusaurus v1 anymore.

We are all closing v1 issues. 
Maybe the current issue is already fixed in Docusaurus v2.
Please try to upgrade, and if the issue is still there on Docusaurus v2, open a new issue.
