### ISSUE TITLE
🐛 bug: `Edit this page` not linked

### ISSUE THREAD

**Issue by tusharnankani** [facebook/docusaurus#3494]
## 🐛 Bug Report

(A clear and concise description of what the bug is)

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes!

## To Reproduce

(Write your steps here:)

1. Opened on [RunMe](https://runme.io/build?build_id=61e071bb-86d7-4e6d-92c7-9ed17595dacb)
1. When clicked on <kbd>Edit this page</kbd>, it leads us to a 404 not found GitHub page.

![Screenshot (597)](https://user-images.githubusercontent.com/61280281/94477484-98f5f700-01ef-11eb-81ee-b5a5cd3b6055.png)

![Screenshot (599)](https://user-images.githubusercontent.com/61280281/94479361-508c0880-01f2-11eb-8a38-e3c85161dd30.png)

- This behavior happens for all <kbd>Edit this page</kbd>, on all pages.

## Expected behavior

- Since it was valid, just for 10 minutes, for experimenting and using it, I actually thought, when clicked on it, it would open a live editor for testing purposes, and how it looks on the website.

(Write what you thought would happen.)

## Actual Behavior

- It leads to a 404 Page.
    - Screenshots added above.

(Write what happened. Add screenshots, if applicable.)

## Your Environment

- Docusaurus version used: v2
- Environment name and version (e.g. Chrome 78.0.3904.108, Node.js 10.17.0): Chrome 85.0.4183.121
- Operating system and version (desktop or mobile): Windows 10.0.18362

Regards,
[Tushar Nankani](https://github.com/tusharnankani)

**Comment by slorber** [comment]
You likely did not put the correct editUrl here: https://v2.docusaurus.io/docs/using-plugins/#docusaurusplugin-content-doc as you are pointing these edit links to docusaurus repo, and doc2 indeed does not exist in docusaurus repo.
