### ISSUE TITLE
Error running the docusaurus site

### ISSUE THREAD

**Issue by Boluwatifeh** [facebook/docusaurus#3495]
## 🐛 Bug Report

(A clear and concise description of what the bug is)

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## To Reproduce

(Write your steps here:)

1. Install the docusaursus init command (npm install --global docusaurus-init)...
2. Scaffold the site(docusaurus-init)..
3. Run cd website to go into the website directory....
4. Run npm start

## Expected behavior

  A browser window was suppose to open up at http://localhost:3000.

## Actual Behavior
got this error in the command line

LiveReload server started on port 35729
Docusaurus server started on port 3000

## Your Environment

- Docusaurus version used: 1.14.6
- Environment name and version (e.g. Chrome 85.0.4183.121, Node.js 12.18.4):
- Windows OS:

## Reproducible Demo

(https://docusaurus.io/docs/en/tutorial-setup)

**Comment by slorber** [comment]
Is the v1 site not working, or it's just the browser window that does not open automatically?

For me it works, so maybe it's your env that makes it unable to get the browser opened?

Do you have the issue with v2 as well?


It's v1 and seems not critical to me, unless many others also have the issue?

**Comment by Boluwatifeh** [comment]
This is my first time setting it up and after running npm start, the browser refuses to open automatically on the port 3000 as specified in the setting up guide

**Comment by slorber** [comment]
You are right that the doc page says:

> By default, a browser window will open at http://localhost:3000.

We are not coding this feature ourselves, it comes from a dependency: `"react-dev-utils": "^10.2.1",` that comes from create-react-app.

Can you run this node script locally and see if it works for you?

```js
import openBrowser from 'react-dev-utils/openBrowser';
openBrowser("http://localhost:3000");
```

If it does not work, then it's either a problem on your computer, or on this lib

**Comment by lex111** [comment]
In order to reduce staled issues, I am closing this issue, but feel free to open it again if needed.
