### ISSUE TITLE
Localization page should be updated for CircleCI 2.0 + best practices

### ISSUE THREAD

**Issue by Daniel15** [facebook/Docusaurus#350]
Currently, the page at https://docusaurus.io/docs/en/translation.html explains how to configure the older CircleCI 1.0 system. CircleCI 2.0 changes the config system a little bit, and has first-class support for Docker.

These changes should be made:
 - `circle.yml` is now `_circleci/config.yml`
 - Dependencies such as `default-jre` and `crowdin` should be installed as part of a Docker image, not as part of the build. This improves build time as they only need to be installed once (when the Docker image is built), rather than separately for every single build.
 - `crowdin` should be installed via `apt-get` rather than directly downloading the .deb file.

I don't know if CrowdIn have a prebuilt Docker image - Maybe we should create a Docusaurus Docker image with all the dependencies (Node.js + JRE + CrowdIn) preinstalled.

**Comment by JoelMarcey** [comment]
We should probably update all of our docs and Docusaurus itself to use Circle 2.0.

**Comment by Daniel15** [comment]
I can create a Docker image with all the prerequisites if you like.

**Comment by JoelMarcey** [comment]
Would definitely love that if it is not too much trouble.

cc: @ericnakagawa

**Comment by chenglou** [comment]
Just ran into this too!

**Comment by JoelMarcey** [comment]
I just updated the translation docs for CircleCI 2.0.

https://docusaurus.io/docs/en/next/translation

I won't close this issue yet in case we want to do the Docker image (or we can move that to another issue).

**Comment by Daniel15** [comment]
Yeah, ideally we should use Docker instead of installing the dependencies on every single build. I forgot about this issue and guess I never got around to doing this :(

**Comment by endiliey** [comment]
Let's move that to another issue
