### ISSUE TITLE
Cli --port option reports "something is already running on port ${number}" 

### ISSUE THREAD

**Issue by arinthros** [facebook/docusaurus#3505]
## 🐛 Bug Report

When running the command `npm run serve -- --port 3000`, the system reports `Something is already running on port 3000`. The same behavior is exhibited for any port, both in local and CI environments. When running just `npm run serve` it boots up on port 3000 with no issues.

I have tested and confirmed this issue exists on a vanilla Docusaurus 2 installation.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## To Reproduce

1. `npx @docusaurus/init@next init docusaurus-repro classic`
1. `cd docusaurus-repro`
1. `npm run build`
1. `npm run serve -- --port 3000` (or any port)

## Expected behavior

`npm run serve -- --port 3000` should boot the app on port 3000.

## Actual Behavior

`npm run serve -- --port 3000` gives the notice `Something is already running on port 3000`. When selecting `no` to run on another port, the app boots into `http://localhost:null`.

![Screen Shot 2020-09-30 at 11 00 03 AM](https://user-images.githubusercontent.com/6694199/94710292-4827f080-030c-11eb-8024-b07aaf5f7f1f.png)

## Your Environment

- Docusaurus version used: 2.0.0-alpha.64
- Environment name and version: Node LTS (12.18.4)
- Operating system and version: MacOS 10.15.6
- CI environment: node:lts docker image

## Reproducible Demo

https://github.com/arinthros/docusaurus-repro
See [To Reproduce](#to-reproduce)

**Comment by slorber** [comment]
thanks, looks like a good first issue for hacktoberfest :)

**Comment by UmairKamran** [comment]
Hi, @slorber. First timer here. May I take this issue for hacktoberfest?

**Comment by slorber** [comment]
Hi @UmairKamran and welcome.

Yes please give it a try and also read comments on https://github.com/facebook/docusaurus/pull/3514 :)

**Comment by UmairKamran** [comment]
Hey @slorber and @arinthros, I've opened the PR #3531 to fix this issue. Hope you get the chance to review it soon. :)
