### ISSUE TITLE
Templating page elements for commonly re-used elements

### ISSUE THREAD

**Issue by Southclaws** [facebook/docusaurus#3518]
## 🚀 Feature

In our wiki, we have many pages with the same warnings on.

```
:::warning
This function was added in version 1.2.3 and will not work in previous versions.
:::
```

For example.

We would like to template this to make it easier to add (and maybe update in future) just like MediaWiki.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes.

## Motivation

To save time.

## Pitch

It's a neat way to save time when using the same constructs everywhere.

We tried to do it with MDX and building a component but couldn't seem to figure out how to export an admonition.

**Comment by slorber** [comment]
Hi,

Is this what you are looking for?

https://v2.docusaurus.io/docs/markdown-features/#calloutsadmonitions

**Comment by Southclaws** [comment]
No I mean I want to take one of these and template it. We have the same text in 100 pages, authors either copy paste or write again (which leads to slightly different admonitions). Templates would allow us to write one commonly used admonition (or any other type of markup) and place it everywhere (presumably using MDX).

MediaWiki has this feature, it's called templates too https://www.mediawiki.org/wiki/Help:Templates

**Comment by slorber** [comment]
Hi,

You could write a Remark plugin to transform the input MDX to whatever you want.

For example:

```
# markdown title

markdown text

:::versionWarning
```

Would become

```
# markdown title

markdown text

import VersionWarning from '@site/src/VersionWarning'

<VersionWarning/>
```

But at the end of the day, your MD document ends up being transpiled to JSX, so you could as well write it in the 2nd form directly.

Note: you can import one MDX from the other too, see for example https://v2.docusaurus.io/examples/markdownPageExample#import-mdx-and-md-files

**Comment by slorber** [comment]
See also a simple remark plugin to do that for you:

https://github.com/angeloashmore/gatsby-remark-find-replace

(looks to me it can be used  without Gatsby)

**Comment by Southclaws** [comment]
Oh, that cross-mdx import is probably what I want, thanks!

**Comment by slorber** [comment]
please let me know if this works for you, and if we can close this issue ;)

**Comment by Southclaws** [comment]
It looks like it works well! Thanks!
