### ISSUE TITLE
v2: Add themeConfig.noIndex option

### ISSUE THREAD

**Issue by slorber** [facebook/docusaurus#3528]
## Feature

v1 had a noIndex option: https://docusaurus.io/docs/en/site-config#noindex-boolean

Let's add it to v2 too!

Also need to:
- edit the migration doc: https://v2.docusaurus.io/docs/migrating-from-v1-to-v2/#removed-fields
- edit the migration cli to migrate correctly this config

There are scripts to easily test the migration cli, look at scripts `yarn test:v1Migration:migrate && yarn test:v1Migration:start`

**Comment by imskr** [comment]
I can fix this! @slorber

**Comment by slorber** [comment]
Yes @imskr thanks
