### ISSUE TITLE
Change default port behavior

### ISSUE THREAD

**Issue by ThomasG77** [facebook/Docusaurus#353]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md)?

Yes

### Environment

* Ubuntu 16.04 64 bits
* Node 8.4.0
* npm 5.6.0

### Steps to Reproduce

When I run `npm run start` from step 4 of https://docusaurus.io/docs/en/site-preparation.html#verifying-installation, I encounter following message (as I have another server running on 3000)
```
Checking if port 3000 is free...
Port 3000 is in use
```
I tried to do `PORT=3001 npm run start` and it fails.

I've seen that I can set port using `--port 3001` at https://github.com/facebook/Docusaurus/blob/master/lib/start-server.js#L34

### Expected Behavior

I would expect that if port 3000 is not available, it would automatically switch to PORT number + 1 (like `http-server` does)
I would also expect `PORT=3001 npm run start` should not fail.

### Actual Behavior

The command line does not switch port automatically
Environment variable PORT is not supported but it should IMO  as I consider that it's default setting in most Node projects.

**Comment by richardzcode** [comment]
@ThomasG77 it is because you are adding parameter to npm not its script `docusaurus-start`

To let npm pass arguments to script, you'll need to add a `--` in between.

Like this: `npm run start -- --port 3001`

**Comment by ThomasG77** [comment]
Thanks @richardzcode for the answer but it's not the issue: I already mentioned your solution in the issue description.

I do not care about option `--port 3001`. I just want the usual environment variable with PORT=3001.
It don't want to be a replacement just an alternative as on every project I use and see in the Node landscape, changing port is about `PORT=3001 node myservercode.js`

**Comment by neilsutcliffe** [comment]
Is this generally what people expect to happen. Does create-react-app fall-up to 3001 when 3000 is used?

**Comment by ThomasG77** [comment]
@neilsutcliffe FYI https://github.com/facebookincubator/create-react-app/blob/master/CONTRIBUTING.md#heuristics

**Comment by JoelMarcey** [comment]
@ThomasG77 Hi. I think this is more a feature request than a bug since you can accomplish the same thing with the command line option. But I see your point in allowing an environment variable as well.

**Comment by yangshun** [comment]
Closed in #516
