### ISSUE TITLE
Enable Hacktoberfest Topic

### ISSUE THREAD

**Issue by aakhtar3** [facebook/docusaurus#3537]
## 💥 Proposal

Can an admin add a new topic for the repo?
This will need to be added for contributors to get credit for Hacktoberfest.

![95018156-d3b2c180-062b-11eb-9f04-3e5e2a7bc534](https://user-images.githubusercontent.com/16447834/95037296-87519b00-0698-11eb-95c0-30922e201ce1.png)

![95018159-dc0afc80-062b-11eb-91ba-287a8161ae62](https://user-images.githubusercontent.com/16447834/95037300-8ae52200-0698-11eb-9453-5a3e4cb5bbb2.png)

**Comment by slorber** [comment]
I've pinged @JoelMarcey as I don't think I can enable this myself. 

Related link of the Hacktoberfest opt-in thing: https://hacktoberfest.digitalocean.com/hacktoberfest-update

**Comment by lex111** [comment]
Done.
