### ISSUE TITLE
[v2] Blog home page support different meta title

### ISSUE THREAD

**Issue by ywtsang** [facebook/docusaurus#3542]
## 🚀 Feature

In the blog home page, the meta title is hardcoded as `Blog | {site title}`. 

This may not be a problem if we just have a single blog, but when we are setting multiple blogs, it would be confusing to see the meta title (from the browser tab) to be "Blog" when switching between different blogs.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes.

## Motivation

Better support for multiple blogs.

## Pitch

The multiple blogs feature in v2 is very useful and we are using 2nd blog for changelog purpose. But show Blog for the changelog section creates confusion that we would like to avoid.

**Comment by slorber** [comment]
agree.

I thought this pr from @zxuqian added support for this: https://github.com/facebook/docusaurus/pull/2359

But it seems to only handle the description.

Adding support for title config option should be easy, inspired by the PR above, while keeping retro compatibility.

**Comment by DeadEnglish** [comment]
Hey, I'd love to take this issue if possible?

**Comment by slorber** [comment]
yes @DeadEnglish thanks ;)

**Comment by dopecodez** [comment]
@DeadEnglish do give a heads-up if you're unable to raise a PR at this time, I'll take a look at this in case you are not solving this.

**Comment by slorber** [comment]
Let's say we expect news from @DeadEnglish in the next 7 days, after it gets reassigned to the next candidate ;)
