### ISSUE TITLE
<table> are ugly

### ISSUE THREAD

**Issue by vjeux** [facebook/Docusaurus#356]
### Steps to Reproduce

https://prettier.io/docs/en/options.html

![image](https://user-images.githubusercontent.com/197597/34329864-b1563af8-e910-11e7-8e39-4f32802d61a3.png)

### Expected Behavior

They should look better :)

**Comment by neilsutcliffe** [comment]
I agree. 

I am not advocating a full on UI framework here, just offering options of how it should look.

For comparison here is **Semantic UIs**

![image](https://user-images.githubusercontent.com/13319277/34381443-c9e6857e-eb08-11e7-94f8-e179bd1f2f17.png)

**Bootstrap**

![image](https://user-images.githubusercontent.com/13319277/34381464-e9a1f95c-eb08-11e7-928b-6361c277feb4.png)

**Picnic CSS** (very minimal would match Docusaurus styling quite well)

![image](https://user-images.githubusercontent.com/13319277/34381480-fcecd716-eb08-11e7-9166-b4c14dbdf94b.png)

**Pure CSS**

![image](https://user-images.githubusercontent.com/13319277/34381523-54a3b6b4-eb09-11e7-8f46-9547420efa84.png)

Which elements do you like and why?

**Comment by vjeux** [comment]
My preference would be the first one, but honestly anything different than the current one would do :p
