### ISSUE TITLE
JSON parse fails after updating to 2.0.0-alpha.64

### ISSUE THREAD

**Issue by nicolas-actyx** [facebook/docusaurus#3561]
## 🐛 Bug Report

I got this error after I updated the docusaurus version from 2.0.0-alpha.48 to 2.0.0-alpha.64.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

yes.

## To Reproduce

1. Download this example repository: 
[test-docs.zip](https://github.com/facebook/docusaurus/files/5353148/test-docs.zip)
2. run `npm i`
3. run `npm run start` 
4. see JSON parse error as seen in the screenshots
5. comment out line 6 in docs/home/home.md
6. see error disappear

## Expected behavior

The project should start and build as it was before updating to the new docusaurus version (2.0.0-alpha.64)

## Actual Behavior

When running `npm run start` or `npm run build` I get errors related to the JSON parserin webpack (see screenshots)

<img width="1326" alt="Screenshot 2020-10-09 at 09 23 41" src="https://user-images.githubusercontent.com/23658611/95563643-f541ed80-0a1d-11eb-89e0-e6f8a50e84f2.png">
<img width="1042" alt="Screenshot 2020-10-07 at 17 04 25" src="https://user-images.githubusercontent.com/23658611/95481488-5a013780-098d-11eb-9282-34029b58b8ca.png">

## Your Environment

- Docusaurus version used: 2.0.0-alpha.64
- Environment name and version (e.g. Chrome 78.0.3904.108, Node.js 10.17.0): Chrome Version 85.0.4183.121 (Official Build) (64-bit)
- Operating system and version (desktop or mobile): macOS Mojave 10.14.6

**Comment by slorber** [comment]
Hi,

You upgraded Docusaurus and likely many other deps were upgraded too in this process, so it's hard to know the problem and  if it's our fault without a repro. If you can try to create the minimal repro case that would be great.

I don't even know what is the content of this json file, and how/where it is consumed, so it's hard to solve.

**Comment by nicolas-actyx** [comment]
Hi, 

Thanks for the quick feedback. I updated the bug report descriptions and added an example repository. Hope this helps!

**Comment by slorber** [comment]
Thanks @nicolas-actyx 

It seems we try to load your json file as a static asset like we do for images. Probably make sense. to do so but I suspect there is a conflict between assets loader (file. loader) and code loader (babel loader).

I suggest you use the `pathname://` prefix as an escape hatch for such case

```
[This is what causes the JSON parse error](pathname:///schemas/os/node-settings.schema.json)
```

**Comment by nicolas-actyx** [comment]
Thanks a lot for the quick help, just tried it and it works!
