### ISSUE TITLE
Sidebar won't show up in docs-only mode + home page not included in sidebar

### ISSUE THREAD

**Issue by charlax** [facebook/docusaurus#3562]
## 🐛 Bug Report

If the sidebar object does not include the home page, the sidebar won't be included.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes.

## To Reproduce

1. Activate docs-only mode
1. Create a `sidebar.js` file without including the home page.

## Expected behavior

The sidebar should show up.

## Actual Behavior

The sidebar does not show up.

## Your Environment

- Docusaurus version used: "2.0.0-alpha.65", "@docusaurus/preset-classic": "2.0.0-alpha.65",
- Environment name and version (e.g. Chrome 78.0.3904.108, Node.js 10.17.0): N/A
- Operating system and version (desktop or mobile): desktop but N/A

## Reproducible Demo

This file won't work:

```js
module.exports = {
    docs: [
        {
            type: "category",
            label: "UserGuide",
            items: ["user-guide/other-page"],
        }
    ],
};
```

This fixes the issue:

```js
module.exports = {
    docs: [
        { type: "doc", id: "index" },  // NEW
        {
            type: "category",
            label: "UserGuide",
            items: ["user-guide/other-page"],
        }
    ],
};
```

## Root cause

I think the issue happens here in `src/theme/DocPage/index.tsx`:

```typescript
function DocPageContent({
  currentDocRoute,
  versionMetadata,
  children,
}: DocPageContentProps): JSX.Element {
  const {siteConfig, isClient} = useDocusaurusContext();
  const {permalinkToSidebar, docsSidebars, version, isLast} = versionMetadata;
  const sidebarName = permalinkToSidebar[currentDocRoute.path];
  const sidebar = docsSidebars[sidebarName];

```

When on the home page, `currentDocRoute.path` evaluates to "/" and `permalinkToSidebar` looks like `{'user-guide/other-page': 'docs'}`. Not sure what this `permalinkToSidebar` object is supposed to be for, but it seems like it should include the home page by default.

**Comment by slorber** [comment]
@charlax this is a feature, not a bug.

All docs pages that are not in a sidebar appear without any sidebar.

Remember that we can have multiple sidebars. In such case, which sidebar would we decide to show?

**Comment by charlax** [comment]
Should this be mentioned in the v2 docs? https://v2.docusaurus.io/docs/docs-introduction/#sidebar

Or perhaps I missed it?

**Comment by slorber** [comment]
Our doc is not perfect yet, if it's not clear and you have a good idea where to mention that behavior, please send a PR :)

**Comment by slorber** [comment]
Probably not good enough but found this

![image](https://user-images.githubusercontent.com/749374/95554459-7e522800-0a10-11eb-83ea-f1ed58fd010f.png)

**Comment by CMCDragonkai** [comment]
Oh man, I just hit this problem, was very confusing why the sidebars disappeared.

**Comment by slorber** [comment]
> Oh man, I just hit this problem, was very confusing why the sidebars disappeared.

What can we do to make it less confusing @CMCDragonkai ?

> Is it possible to show a side bar if you don't put the page onto the sidebar?

Yes, there's a `displayed_sidebar` frontmatter for that: https://docusaurus.io/docs/api/plugins/@docusaurus/plugin-content-docs#displayed_sidebar
