### ISSUE TITLE
 key word  “fs”  is  declared    in   node_modules\@types\node\fs.d.ts  file, this   cause  Node.js file system ‘ fs’     not work   。

### ISSUE THREAD

**Issue by ywjr** [facebook/docusaurus#3564]
## 👉 [Please follow one of these issue templates](https://github.com/facebook/docusaurus/issues/new/choose) 

👈

 
fs is  declared    in   node_modules\@types\node\fs.d.ts  file,

this   cause  Node.js file system ‘ fs’     not work   。

const FS = require('fs');

![fs](https://user-images.githubusercontent.com/62584887/95534530-b198b500-0a18-11eb-9c0a-92b34a2f09ba.png)

**Comment by slorber** [comment]
Sorry but I'm not able to understand anything about this issue, please give more infos about what you want, and we'll reopen.
