### ISSUE TITLE
[v2]tag style must be object even though file extension is .md

### ISSUE THREAD

**Issue by huntye1** [facebook/docusaurus#3570]
I write my doc file in Typora that can custom tags style by inline style. like this:
```html
<img src="https://raw.githubusercontent.com/huntye1/gallery/master/image-20201010160924980.png" alt="this is a pic" style="zoom:50%;margin:auto" />
```
but when i run my site, I got an Error ` Error: The `style` prop expects a mapping from style properties to values, not a string.`

I read the doc said that I must change my inline style syntax into object style that using in jsx.

Is there some way to config this action or disable it  in .md extension file ?

**Comment by slorber** [comment]
Hi @huntye1 , this JSX object syntax is required by the MDX parser that we currently use.

There's already an issue about the current parser limitations regarding compatibility with existing MD ecosystem, so I'm closing this one.

https://github.com/facebook/docusaurus/issues/3018
