### ISSUE TITLE
Stable unreleased alpha with no release notes

### ISSUE THREAD

**Issue by breyed** [facebook/docusaurus#3572]
## 📚 Documentation

The [versions](https://v2.docusaurus.io/versions) page shows 2.0.0-alpha.66 as a stable unreleased alpha, which seems like a contradiction. Improved terminology or at least some explanation on the page would be helpful to avoid confusion. I was hoping the [Release Notes](https://github.com/facebook/docusaurus/releases/tag/vcurrent) would clear things up, but the link 404s.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

**Comment by lex111** [comment]
Agree, I think we need to explicitly separate versions page, something like this:

```
Dev (upcoming) version
----
Latest (current) version
----
Past versions
```

Or dev/latest versions need to inverted?

**Comment by slorber** [comment]
Hi,

The alpha 66 (unreleased) means it's what will be in next release.

We use this version by default as it nudges users to contribute docs to the ./docs folder (via the edit button). 

Not totally satisfied with this solution either, have some ideas to improve current setup.

If you have any ideas on how to make it clear that one version of the dropdown is the "work in progress" (ie code from master branch,  docs from ./docs folder), please let me know.

How can we improve terminology?

**Comment by lex111** [comment]
@slorber I think it would be enough for now to change only the versions page, I suggested how this can be done in my previous comment.

**Comment by slorber** [comment]
@lex111 yeah why not first modifying this version page.

Note that "current" is now the name for the version of the `./docs` folder, so it's more dev/current, latest/alpha65.
See also https://v2.docusaurus.io/docs/versioning/#figure-out-the-behavior-for-the-current-version

Do you want to submit a PR?

In the future, I'd like the docs plugin to generate it, as many docusaurus sites have such page and it very often looks the same.
