### ISSUE TITLE
Open Source Infima framework

### ISSUE THREAD

**Issue by Simek** [facebook/docusaurus#3575]
## 💥 Proposal

Currently the Docusurus styling is based on the [Infima](https://facebookincubator.github.io/infima/) framework which is a FB Incubator project (currently closed source). 

> Infima is not yet ready for production use and is being developed alongside Docusaurus 2

I acknowledge this statement, but Infima is used in default theme, most of Docusaurus V2 websites are based on `theme-classic` package and they are already running "in production": https://v2.docusaurus.io/showcase

Since V2 is getting more popular and users are migrating to the new version it would be nice to have an access to the core theme files, so bug fixing or improving the theme would be easier. Currently users had to overwrite the Infima variables and fix encountered bugs or issues with Infima styling in their own CSS/SASS/SCSS files ([example ](https://github.com/facebook/docusaurus/blob/master/website/src/css/custom.css#L66)form the Docusaurus V2 website). There is also no place to report the problems or submit PRs.

If it is not possible to open source the project, the theme based on Infima should not be a default or a recommended choice for the V2 users (because of limited accessibility and customizability) and Facebook Open Source logo and GitHub link should be removed from the Infima website to avoid users confusion.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

**Comment by yangshun** [comment]
Apologies for the delay. I'm working on making the repo public just to give more visibility into the source code. Will do so by the end of the week.

**Comment by Simek** [comment]
@yangshun Friendly bump 😉 What's the current status of OSing Infima?

**Comment by Simek** [comment]
@yangshun Another issue emerges - https://github.com/facebook/docusaurus/pull/3739#issuecomment-730417696...

**Comment by yangshun** [comment]
@Simek We're done with the necessary checks in the internal repo, just need one final step of squashing the commit history before the Open Source team can make the repo public. As this week is an off-week for FB employees, we estimate that the repo will only be officially made public early next week. Thanks for your patience!

**Comment by yangshun** [comment]
The repo is public! - https://github.com/facebookincubator/infima/

Thank you for your patience thus far
