### ISSUE TITLE
Urgent Help needed regarding plugin support.

### ISSUE THREAD

**Issue by harsh599** [facebook/docusaurus#3581]
https://github.com/lelouchB/final-space-api/issues/33

kindly visit the link you will better understand the issue

**Comment by slorber** [comment]
I'm sorry but if you want me to invest time in helping you, please invest first your time to create a proper issue, with all the relevant infos summarized.

If you have a bug related to ideal image plugin, please explain what you tried, what you expected, and what you got, for each of your attempts.
