### ISSUE TITLE
Document i18n contribution process 

### ISSUE THREAD

**Issue by leeyspaul** [facebook/docusaurus#3582]
## 📚 Documentation

There doesn't exist documentation on how to contribute to localization/translation efforts related to #3526.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

(Write your answer here.)

It would be helpful to document the i18n process formally so new contributors who would like to help with the process can more easily contribute to the translation efforts. I am not too sure what this would look like but the Kubernetes community has some great localization documentation for various languages. I don't think it has to be as heavy handed but perhaps some more documentation would be helpful in spurring on contributions.

**Comment by slorber** [comment]
@leeyspaul we can't contribute to translations before there's an actual translation system in place. 

I'll write the I18n contribution process as part of this PR, but it's not figured out yet: https://github.com/facebook/docusaurus/pull/3325

**Comment by leeyspaul** [comment]
Great, thank you!

**Comment by yaseerhee** [comment]
How is it going the Spanish translate doc ??

**Comment by slorber** [comment]
The translation process is described here https://github.com/facebook/docusaurus/issues/3526
