### ISSUE TITLE
DX: show big help message when baseurl problems

### ISSUE THREAD

**Issue by slorber** [facebook/docusaurus#3584]
## 💥 Proposal

Not configuring the baseurl properly is the most common Docusaurus error, and lead to site deployments such as:

![image](https://user-images.githubusercontent.com/749374/95964651-53e5dd80-0e09-11eb-9a8d-d7e849a10a41.png)
 

It's very often asked on issues or Discord why a site does not work after deployment, and the answer is always the same:  baseurl.

---

I suggest that:
- We inline (HTML + JS + CSS) a big error message at the top of the homepage of a docusaurus site
- We recommend to use `baseUrl = document.location.pathname` (can be computed from the inlined JS script)
- We hide this message in the first remotely-loaded CSS file, as it proves that baseurl setting is correct

This way, the user can figure it out himself.

This should rather be made theme-agnostic, and be in core only.

To test this, run in the monorepo: `yarn build:v2` and then `yarn serve website` and open `http://localhost:5000/build/` => should show a broken site.

The idea is to get something like:

![image](https://user-images.githubusercontent.com/749374/95965930-d15e1d80-0e0a-11eb-804b-4c7d7d7f97dc.png)

But without any flashing or whatever: if the site works fine, then the user should never see this.

Drawback: if for some weird reasons the baseurl is correct, the HTML loads, but not the CSS (network error for example), the user would still see this error message. That does not seem a big deal to me, as it should be quite rare, and he'll see a broken site anyway...

**Comment by jcs98** [comment]
@slorber I would love to take a shot at this
Can you please guide me with a starting point?

**Comment by jcs98** [comment]
Thank you! I will try this :+1:

**Comment by mpsq** [comment]
This feature is causing CSP rules to fail in production when `unsafe-inline` is not set. Although this is a nice to have, should we keep this feature only for dev mode and remove it for the production build?
Let me know, if you guys agree with this, I am happy to work on it.

**Comment by slorber** [comment]
I see

@mpsq most issues happen when users try to deploy to their prod env imho, so I'd rather give you an option to disable this option, but keep it enabled by default.

What should we do to pass that unsafe-inline rule? just remove the banner with inline style?

**Comment by mpsq** [comment]
Thanks for you super quick answer.

Inline styles are an issue yes, but more importantly, the following snippet:

```
<script type="text/javascript">
            {`
document.addEventListener('DOMContentLoaded', function () {
  var baseUrlSuggestion = document.getElementById(
    '${BaseUrlSuggestionContainerId}',
  );
  if (baseUrlSuggestion) {
    var actualHomePagePath = window.location.pathname;
    var suggestedBaseUrl = actualHomePagePath.substr(-1) === '/'
        ? actualHomePagePath
        : actualHomePagePath + '/';
    baseUrlSuggestion.innerHTML = suggestedBaseUrl;
  }
});
`}
</script>
```

[Source](https://github.com/MLH-Fellowship/docusaurus/blob/e053743707631994822adfff225608ad5f12ef20/packages/docusaurus/src/client/baseUrlSuggestionWarning/BaseUrlSuggestionWarning.tsx#L32)

Is causing "even more" trouble since it means enabling `unsafe-inline` for `script-src`. Although inline styles can be fixed easily, do you believe this script can also be somehow reworked to not be inlined? A flag to disable this feature would also work :).

**Comment by slorber** [comment]
We'll add a flag to disable then.

This inlining is required, because the banner has to be displayed when the js/css assets can't load, so we can't un-inline them 😅

**Comment by slorber** [comment]
will be fixed by https://github.com/facebook/docusaurus/pull/3802

**Comment by slorber** [comment]
https://github.com/facebook/docusaurus/releases/tag/v2.0.0-alpha.69

let me know if this works for you

**Comment by mpsq** [comment]
Yes, it is all good now, no more CSP issues :tada:
Thanks Seb!

**Comment by slorber** [comment]
great :) 👍

**Comment by luxurystorecc1** [comment]
Mastering the Global Playbook: Where Status Meets PerformanceIntroduction: The Evolution of Professional IdentityThe traditional definition of "professional attire" has undergone a profound shift. Today, status is often signaled through "Performance Luxury"—a blend of technical athleticism and elite tailoring. This article explores how items like the [Air Jordan 1 retro high-top shoes](https://www.airjordan-1.com/) and high-end sports apparel have become the new playbook for global style.  Footwear: A Statement of Culture and TechFootwear is a potent tool for communicating cultural and technical literacy. The [Jordan 1s high-performance basketball shoes](https://www.jordan1s.com/) remain an essential statement piece, representing a legacy of excellence. As enthusiasts look for modern comfort, the [retro Jordan 1 limited editions](https://www.jordan1s.com/) are highly sought after for their blend of historical narrative and updated construction.  This focus on innovation is equally present in the [adidas Yeezy boost performance series](https://www.yeezyboost-350.com/collections/adidas-yeezy), providing technical solutions for the mobile individual. The desire for extreme comfort has even elevated casual items, with [comfortable Yeezy slides and foam runners](https://www.yeezyboost-350.com/) becoming a standard for travel among the global elite.  The Global Reach of Sports MerchandiseSports gear has become a major driver of the global fashion economy. For NFL fans, finding [cheap NFL jerseys with high-quality embroidery](https://www.nflshopofficialonline-store.com/) is an essential part of game-day culture. Authenticity is key, making the [official NFL shop online](https://www.nflshopofficialonline-store.com/) the most trusted resource for international fans.  Personalization is another key trend, with the [customized replica NFL jersey](https://www.nflshopofficialonline-store.com/collections/custom-nfl-jersey) providing a unique way to show team dedication. Beyond the NFL, [NFL headwear and official team caps](https://www.cheapnfl-jerseys.com/collections/headwear-nfl-headwear) are essential streetwear accessories, while hockey fans look to the [NHL official site for jerseys](https://www.custombaseball-jerseys.com/) for professional-grade gear.High-Performance Luxury: The Peter Millar AestheticFor the modern woman who values both fashion and function, [Peter Millar women's golf outerwear](https://www.peter-milla.com/collections/golf-women-s-golf-outerwear) provides an elegant solution for on-course performance. These garments provide technical protection while maintaining a sophisticated silhouette. The broader [Peter Millar apparel collection](https://www.peter-milla.com/) continues to set the pace for luxury leisurewear.  Celebrating Occasions with EleganceLife's major milestones demand clothing that rises to the occasion. For wedding guests attending autumn ceremonies, [fall wedding guest dresses](https://www.swim-outlet.com/collections/wedding-fall-wedding-guest) offer a stylish way to handle the season's variable weather. For those who want to make a bold statement at a formal event, [elegant red evening dresses](https://www.swim-outlet.com/collections/dresses-red) remain a powerful choice.  The fashion industry's commitment to diversity ensures that [plus size evening gowns for formal events](https://www.cheapdressesformal.com/) are more accessible than ever. Whether it is for a high school prom—where [designer prom dresses online](https://www.cheapdressesformal.com/collections/prom) are highly prized—or a corporate gala, the focus is on high-quality design.  Conclusion: The Power of AuthenticityWhether you are sourcing from a [high-performance swim outlet](https://www.swim-outlet.com/) or selecting [national team soccer jerseys](https://www.soccerjerseysstore.com/collections/national-teams), the ultimate goal is to find authentic pieces that reflect your identity. In a globalized world, quality is the universal standard.
