### ISSUE TITLE
Add ability to configure docs page metadata

### ISSUE THREAD

**Issue by Simek** [facebook/docusaurus#3592]
## 💥 Proposal

Currently the docs pages metadata is hardcoded and there is no option to customize it. It is not a separate component, but it is a part of `DocItem` file which makes the swizzle a bit risky. There are also no dedicated CSS class names which will help the users to customize the appearance of metadata.

**What would be nice to see:**
* docs page metadata extracted to the separate component
* unique CSS class by default for those who don't want to swizzle, but want to tweak the design a bit
* ability to specify maximum number of last contributors from 1 to 5 (hardcoded: 1)
* ability to specify the handle by which user is represented (hardcoded: name + surname)
  * as possible value it would be nice to have GitHub username, email or one of names used alone
* ability to display user avatar or profile picture from GitHub (or Gravatar) with a nice fallback
* ability to customize the date format, including the relative formatting (hardcoded: DD/MM/YYYY)

Ideally it would be good to have customizability at the level which allow to create the similar solution to the one used by GitBook, few examples (you need to scroll to the bottom of the pages):
* https://developer.helium.com/
* https://docs.gitbook.com/accounts/export-or-delete-your-data (example with more than the max allowed count of contributors)

Originally reported in: https://github.com/react-native-website-migration/react-native-website/issues/37

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

**Comment by Josh-Cena** [comment]
Closing in favor of #6218. We'll likely expose an API to bring your own way to retrieve authors data
