### ISSUE TITLE
Make an array of filenames based on a folder to dynamically render a table

### ISSUE THREAD

**Issue by iamterryclark** [facebook/docusaurus#3597]
I would like to collect all filenames with .zip types in a folder and have them render a table in Docusaurus. I am currently able to use jsZip to see inside the zip files and pull out information.

I am having issues using `fs`, as it is not s its not a module found inside Docusaurus node modules even if I directly install this with `npm install --save fs`. And also I cannot use `require.context` to pull back the filename within a folder when I upload the site to a server.

Does Docusaurus have some tools that could help? I have also tried to put these files in to static assets folder but not able to useBaseUrl correctly. Is there was a way to reference a folder and pull back an array of filenames inside based on type?

**Comment by slorber** [comment]
Hi @iamterryclark 

I can't help you for the inability to use Node fs API unfortunately, it's not really related to Docusaurus.

There are multiple technical ways you can provide the generated table data to Docusaurus (custom fields, custom webpack loader, remark plugin...)

It is a bit out of the scope of Docusaurus to provide such a feature, but you have the building blocks to implement it yourself.

---

One simple way could be to read the folder and generate all the data you need, and put it in the configuration here: https://v2.docusaurus.io/docs/docusaurus.config.js/#customfields

Here's an example:


```js
const fs = require('fs'); 
  
const zipfilenames = fs.readdirSync("./myZipFolder").filter(filename => filename.endsWith(".zip"))

module.exports = {
  customFields: {
    myTableData: {
      zipfilenames,
    },
  },
};
```

Then you can build a React component that renders the data:

```jsx
export default function MyZipTable() {
 const myTableData = useDocusaurusContext().siteConfig.customFields.myTableData
 return (<div>
  {myTableData.zipfilenames.map(zipfilename => <div>{zipfilename}</div>}
</div>
) 
}
```

Then you use it in MDX:

```md 
# MD title

some text

import  MyZipTable from "@site/src/components/MyZipTable"

<MyZipTable />
```


--- 

Note: using the customFields will provide the table data to all your app's page, so this data should rather be lightweight. If you have  a lot of table data to render, you should rather  explore building a Remark plugin, like putting some marker in MD, and get it processed by a remark node process.
