### ISSUE TITLE
Docs-only mode still pointing to an inexistant index.js

### ISSUE THREAD

**Issue by jumpersdevice** [facebook/docusaurus#3598]
Hello, thanks for this software. I followed the instructions https://v2.docusaurus.io/docs/docs-introduction/#home-page-docs
but it's still pointing to an inexistant ./src/pages/index.js and get 404.
I recreate that file and the 404 error is gone. I want introduction.md to be the index, can anybody help me please?

when I try to put slug:/ it will show an error and wont let me compile, saying / is invalid in slug. my introduction.md:

---
slug: introduction
title: Introduction
---

## text

thanks

**Comment by slorber** [comment]
Hi

You are right: you should both delete the src/pages/index.js and use slug: /

We do use slug: / on our own website and it works

![image](https://user-images.githubusercontent.com/749374/96271738-87716500-0fcd-11eb-99ed-44c6c3a0178d.png)

> when I try to put slug:/ it will show an error and wont let me compile, saying / is invalid in slug. my introduction.md:

you don't give us the exact error message, and the md you added to the issue does not even have slug: / 

Please give the exact md document you use (with slug: /), the exact error message you get with that config. Also please provide your full config, the docusaurus versions used (package.json), ideally a repro public Github repository so that we can inspect everything.

**Comment by jumpersdevice** [comment]
hi, thanks for your answer, please check the error: 

`Starting the development server...
Error: Document slug cannot include "/".
    at Object.processMetadata [as default] (/root/docs/node_modules/@docusaurus/plugin-content-docs/lib/metadata.js:88:15)
    at async /root/docs/node_modules/@docusaurus/plugin-content-docs/lib/index.js:122:34
    at async Promise.all (index 6)
    at async Promise.all (index 0)
    at async Object.loadContent (/root/docs/node_modules/@docusaurus/plugin-content-docs/lib/index.js:157:13)
    at async /root/docs/node_modules/@docusaurus/core/lib/server/plugins/index.js:56:16
    at async Promise.all (index 0)
    at async Object.loadPlugins (/root/docs/node_modules/@docusaurus/core/lib/server/plugins/index.js:52:34)
    at async Object.load (/root/docs/node_modules/@docusaurus/core/lib/server/index.js:57:46)
    at async start (/root/docs/node_modules/@docusaurus/core/lib/commands/start.js:45:19)
error Command failed with exit code 1.
`

this is when I set up my introduction.md to:

`---
id: introduction
title: Introduction
slug: /
---`

my docusaurus.config.js:

`presets: [
    [
      "@docusaurus/preset-classic",
      {
        docs: {
          routeBasePath: "/",
          path: "src",
          sidebarPath: require.resolve("./sidebars.js"),
        },`

**Comment by slorber** [comment]
I also need the docusaurus version, as I suspect you are on an older one (in which case try to upgrade)

**Comment by jumpersdevice** [comment]
What is the easiest way to check that? thanks

**Comment by slorber** [comment]
You can see versions in package.json, your lock file or node modules, looking for @docusaurus/core.

If you did not upgrade in the last months, please upgrade.

**Comment by jumpersdevice** [comment]
2.0.0-alpha.58 is what im using. ill upgrade and let you know if it works
thanks

**Comment by lex111** [comment]
In order to reduce staled issues, I am closing this issue, but feel free to open it again if needed.
