### ISSUE TITLE
package.json repository/directory metadata incomplete

### ISSUE THREAD

**Issue by rarkins** [facebook/docusaurus#3612]
## 🐛 Bug Report

The `package.json` files within packages/* contain incomplete metadata for source repo and source directory. e.g. as according to this advice from [npm's `package.json` documentation](https://docs.npmjs.com/files/package.json):

![image](https://user-images.githubusercontent.com/6311784/96551414-8cc2fe00-12b2-11eb-877e-419e05eaeaa8.png)

### Have you read the [Contributing Guidelines on issues]

Yes

## To Reproduce

View any `package.json` within `packages/*`. I think all are missing the `directory` field and some are also missing the source repository information altogether (e.g. [@docusaurus/preset-classic](https://github.com/facebook/docusaurus/blob/master/packages/docusaurus-preset-classic/package.json))

## Expected behavior

Monorepo `package.json` files should all contain a valid `repository` object including `directory` field.

I can try correcting this if you agree to receive a PR.

## Actual Behavior

N/A

## Your Environment

N/A

## Reproducible Demo

N/A

**Comment by lex111** [comment]
> I can try correcting this if you agree to receive a PR.

Yes, of course, it would be great!

**Comment by slorber** [comment]
Is this something new related to npm 7 support for workspace?

Or is it something that could improve the npm package links? for example on this page? https://www.npmjs.com/package/@docusaurus/core

**Comment by rarkins** [comment]
@slorber it wasn't related to npm 7 specifically. I help run the [Renovate Bot](https://github.com/renovatebot/renovate) and correct source URLs help us with both automated grouping as well as changelog retrieval. An example of one which is missing source links is https://www.npmjs.com/package/@docusaurus/preset-classic

**Comment by slorber** [comment]
Thanks, I see. PR welcome ;)

Are you able to retrieve easily the changelogs, as we have v1 and v2 changelogs at the root?
We don't have a changelog per package.

We have an issue about Renovate Bot here, will have to check that and see how Docusaurus can benefit from it.
https://github.com/facebook/docusaurus/issues/3552

**Comment by rarkins** [comment]
@slorber happy to help on that aspect too. Anyway, for now please see the linked PR #3613
