### ISSUE TITLE
Internationalization support

### ISSUE THREAD

**Issue by jcayzac** [facebook/docusaurus#3618]
## 🚀 Feature

Support internationalization.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## Motivation

Because it's mentioned in the introduction, I assumed V2 would already have support for internationalization. From deeper inspection it appears I was wrong and it's still lacking.

## Pitch

Documentation sites are often available in multiple locales. A prominent example is [MDN](https://developer.mozilla.org/en-US/docs/Web/API/PaymentRequest), where docs are located at `<base-url>/<locale>/<path>` and the end-user can switch between the different languages a document is available in using a control on the page:

![Language selection on MDN Page](https://user-images.githubusercontent.com/106682/96702091-5d081900-13cc-11eb-8c9b-fd7e61cb3e9c.png)

**Comment by jcayzac** [comment]
I see there's some complicated brainstorming going on at https://github.com/facebook/docusaurus/issues/3317 about translation services. All our organization needs right now is a way to map doc content paths to languages, like on MDN, and this is a deal breaker forcing us not to use Docusaurus for our public docs for now.

**Comment by jcayzac** [comment]
Closing since implementation seems to be coming in #3325

**Comment by slorber** [comment]
Yes, the first part is handled, working on the 2nd part right now ;)
