### ISSUE TITLE
The code generator has deoptimised the styling of undefined as it exceeds the max of 500KB.

### ISSUE THREAD

**Issue by Southclaws** [facebook/docusaurus#3625]
## 🐛 Bug Report

It's not _super_ important it's just odd because there's no description of exactly where this warning is coming from, and the presence of `undefined` indicates something's not working quite right. It doesn't appear to break anything (though, our wiki is pretty huge so I haven't checked every single page!)

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes.

## To Reproduce

I can't seem to get it to happen on a fresh Docusaurus installation but it happens with https://github.com/openmultiplayer/wiki/ so you can grab this and `npm start` or `npm build` it and it occurs. There are also some build logs here: https://vercel.com/openmultiplayer/wiki/43t1kdte8 (I think this is publicly accessible)

## Your Environment

- Docusaurus version used: "2.0.0-alpha.54"
- Environment name and version (e.g. Chrome 78.0.3904.108, Node.js 10.17.0): latest stable node
- Operating system and version (desktop or mobile): happens on windows and the build environment on vercel, which I assume is linux

**Comment by lex111** [comment]
First of all try updating to the latest version of Docusaurus, you are currently using a very old and unmaintained Docusaurus version.

**Comment by Southclaws** [comment]
Oh, it didn't seem that old, I tried going up to .66 but that didn't seem to build at all so I went back.

**Comment by lex111** [comment]
Regardless of this issue, you are better off using the latest version of Docusaurus.
