### ISSUE TITLE
Scrollbar style: blog sidebar != docs sidebar

### ISSUE THREAD

**Issue by slorber** [facebook/docusaurus#3628]
## 🐛 Bug Report

We should make the sidebar scrollbar styles consistent.

![image](https://user-images.githubusercontent.com/749374/97005303-8c3e9780-153e-11eb-993c-46f3583dbe27.png)

Reported by @Simek on RN website, as it leads to declaring these styles manually: https://github.com/react-native-website-migration/react-native-website/blob/dev/website/src/css/customTheme.scss#L1254

**Comment by nategiraudeau** [comment]
@slorber, can I work on this issue?

**Comment by slorber** [comment]
yes thanks :)
