### ISSUE TITLE
Runme demo link in README.md does not work

### ISSUE THREAD

**Issue by allc** [facebook/docusaurus#3629]
## 📚 Documentation

In README.md, the demo link to Rumme (https://runme.io/run?app_id=0dd80306-47bb-4e80-95dc-dc95eb05d3fd) does not work.

Instead of linking to the demo, it links to a page saying "No app has been found with ID "0dd80306-47bb-4e80-95dc-dc95eb05d3fd." and suggests to regenerate a new button.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

**Comment by slorber** [comment]
Thanks for reporting.

@belokonm as you implemented this in https://github.com/facebook/docusaurus/pull/2811, do you know why it does not work anymore now?

Note, we'll likely have a codesandbox template soon: https://github.com/facebook/docusaurus/issues/1699

**Comment by slorber** [comment]
> !! Service will be shutdown and become unavailable from 01.12.2020 !!

https://runme.io/

We should rather just remove that badge

**Comment by belokonm** [comment]
Thank you, @slorber, for fixing this so quickly.
