### ISSUE TITLE
Error: Plugin docusaurus-plugin-google-analytics is used 2 times with id=default.

### ISSUE THREAD

**Issue by Southclaws** [facebook/docusaurus#3632]
## 🐛 Bug Report

I upgraded to the latest version and got this

```
Error: Plugin docusaurus-plugin-google-analytics is used 2 times with id=default.
To use the same plugin multiple times on a Docusaurus site, you need to assign a unique id to each plugin instance.
```

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?
Yes

## To Reproduce

Install google analytics plugin on a docusaurus instance (it might happen with other plugins but we only use the GA one)

Try it here https://github.com/openmultiplayer/wiki/ using commit `2b2321341d32121ff3195fc801d0831b1693ce10`

I fixed it by giving the GA plugin an explicit ID: https://github.com/openmultiplayer/wiki/commit/6fada686d8a85fab6cf6b94cb8f5734e29d77a1e

## Your Environment

- Docusaurus version used: v2 alpha 66
- Environment name and version (e.g. Chrome 78.0.3904.108, Node.js 10.17.0): latest stable node
- Operating system and version (desktop or mobile): windows and vercel, so linux I think

**Comment by slorber** [comment]
Hi,

If you use the classic preset with `googleAnalytics` themeConfig, you already use the google analytics plugin, as it's included in the preset.

So you actually have 2 instances of the google analytics plugin running on your site, which is likely not something you want right?

I'll improve the error message to make this clearer

**Comment by Southclaws** [comment]
Ah, I didn't know it was added by default now. Thanks1

**Comment by slorber** [comment]
it is added only when your preset classic has the googleAnalytics config attribute

**Comment by gulien** [comment]
Hello @slorber,

Sorry to comment on this closed issue, but I wonder where to put exactly the `googleAnalytics` config with preset classic?

I've tried:

```js
presets: [
    [
      '@docusaurus/preset-classic',
      {
        themeConfig: {
          googleAnalytics: {
            trackingID: 'G-ZGCNWVF92C',
            // Optional fields.
            anonymizeIP: true, // Should IPs be anonymized?
          },
        },
      },
    ],
  ],
```

And:

```js
presets: [
    [
      '@docusaurus/preset-classic',
      {
        googleAnalytics: {
          trackingID: 'G-ZGCNWVF92C',
          // Optional fields.
          anonymizeIP: true, // Should IPs be anonymized?
        },
      },
    ],
  ],
```

And:

```js
module.exports = {
  themeConfig: {
    googleAnalytics: {
      trackingID: 'G-ZGCNWVF92C',
      // Optional fields.
      anonymizeIP: true, // Should IPs be anonymized?
     },
  },
}
```

But no success so far 😄 

Version: `2.0.0-alpha.69`

Thank you for your help!

**Comment by slorber** [comment]
https://v2.docusaurus.io/docs/api/plugins/@docusaurus/plugin-google-analytics/#configuration

this one should work:


```
module.exports = {
  themeConfig: {
    googleAnalytics: {
      trackingID: 'XXX',
      // Optional fields.
      anonymizeIP: true, // Should IPs be anonymized?
     },
  },
}
```

Note: it is only enabled on the production build, so you'll have to use docusaurus build && docusaurus serve to test that

**Comment by gulien** [comment]
Thanks @slorber for the quick answer. 😉 

The "working" solution was the one I tried first but alas it did and still do not work.

I'm using a GitHub workflow to deploy my documentation on the `gh-pages` branch. It runs the following instructions at the end:

```bash
yarn install --frozen-lockfile
yarn deploy
```

So either:

* There is a bug (I doubt it)
* I did not configure my Google Analytics correctly (I doubt it)
* It cannot work with GitHub hosting?
* Should I configure gtag too? (https://v2.docusaurus.io/docs/api/plugins/@docusaurus/plugin-google-gtag/)

Thanks for your time! 😄

**Comment by slorber** [comment]
@gulien I will only be able to help you if you provide me a repro using the config I gave you + a live deployment where I can indeed see it does not work.

**Comment by gulien** [comment]
My bad the documentation source code is located here:
https://github.com/thecodingmachine/symfony-boilerplate/tree/master/docs

And the documentation is available here: https://thecodingmachine.github.io/symfony-boilerplate/

**Comment by slorber** [comment]
This works, as you can see

![image](https://user-images.githubusercontent.com/749374/102504488-33443900-4081-11eb-8987-a20c1448da48.png)

**Comment by gulien** [comment]
Ok so GA do not show anything, so I guess I actually did not configura GA correctly on my side...
Sorry for that, have a nice day :)

**Comment by slorber** [comment]
that's probably it yes :) afaik it works on RN website

**Comment by adsazad** [comment]
I am using @docusaurus/preset-classic, in my case, it is not collecting data. I tried to google analytics as well as gtag method but neither one is working.

**Comment by slorber** [comment]
@adsazad there were changes recently on this (config was moved from themeConfig to plugin options), and we can't help if you don't provide your docusaurus version and provide more context

If you follow the official doc of your exact docusaurus version (not production doc), you should be able to make it work and see GA requests in the network tab

Also note that Google launched Google Analytics 4, to progressively replace all the former analytics generations, and we don't support that yet. There's an issue to support it here: https://github.com/facebook/docusaurus/issues/7221
