### ISSUE TITLE
Indicate blog customization in the documentation

### ISSUE THREAD

**Issue by rafaelrdealmeida** [facebook/docusaurus#3643]
## 📚 Documentation

Hello, the docusaurus documentation is very good, congratulations to the contributors.

But I have some difficulty understanding the files and settings to personalize the blog.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

yes

Does docusaurus v2 not point to the possibility of inserting configuration parameters in docusaurus.config.js (postsPerPage, blogSidebarCount, blogSidebarTitle) has something else? and the right sidebar of the post page is also possible to be removed, but this is not indicated.

```js

     blog: {
          showReadingTime: true,
          postsPerPage: 3,
          blogSidebarCount: 2,
          blogSidebarTitle: 'Posts recentes',
          // Please change this to your repo.
          editUrl:
            'https://github.com/facebook/docusaurus/edit/master/website/blog/',
        },

```
BlogListPage
BlogListPaginator
BlogPostItem
BlogPostPage
BlogSidebar
BlogTagsListPage
BlogTagsPostsPage

In addition, through the` yarn swizzle @ docusaurus / theme-classic <blog ...> --danger` it is possible to customize a large part of the blog. Wouldn't it be worth explaining the documentation the function of each part of the theme below to indicate the possibilities of the blog?

see:

- https://github.com/facebook/docusaurus/issues/2353
- https://github.com/facebook/docusaurus/issues/2717

**Comment by slorber** [comment]
Hi,

We can definitively improve the documentation, if you have suggestions don't hesitate to send PRs directly.
I'd like to re-org everything in this doc, but that will be done later.

**Comment by rafaelrdealmeida** [comment]
Hi @slorber ,

I am writing down the points that I feel could be added to the documentation. Next week we should finish adjusting our docusaurus. After that I did PRs.

Do you have any guidance or requests regarding documentation that I can help with?

**Comment by slorber** [comment]
Not much guidance, we have undocumented things, and documenting them will definitively be better than not :)
Just try to put the doc in the correct place. Also code blocks are not searchable easily so. we'd rather have all searchable content documented outside of codeblocks as well.

Once I ship i18n I'll reorg the docs. We need something better before translation our own website :)

**Comment by stnor** [comment]
I don't understand how to translate or override the blogSidebarTitle för the default blog. Any hints would be appreciated.

**Comment by slorber** [comment]
@stnor it looks like you are right and it's not possible. 

Just reported it here alongside other items that are not translatable: https://github.com/facebook/docusaurus/issues/4542#issuecomment-833631403

**Comment by stnor** [comment]
Thanks!
Related i18n q: The Search Modal. Is that customizable or translatable?

**Comment by slorber** [comment]
The search modal is from Algolia. Afaik for now it not, and they only merged my PR to allow translating the search input

**Comment by stnor** [comment]
It seems like their react-library can handle i18n ```react-instantsearch-dom```
https://www.algolia.com/doc/guides/building-search-ui/widgets/customize-an-existing-widget/react/

Whereas ```@docsearch/react``` doesnt seem to have i18n for some reason.
