### ISSUE TITLE
git clone failed when running npm run publish-gh-pages

### ISSUE THREAD

**Issue by niks3089** [facebook/docusaurus#3659]
## 🐛 Bug Report

Following the tutorial 
When I try and run `GIT_USER=user CURRENT_BRANCH=master npm run publish-gh-pages`, 
I see the following error: 

```
> docusaurus-publish

master
git@github.com:repo/docs.git
generate.js triggered...
feed.js triggered...
feed.js triggered...
sitemap.js triggered...
Site built successfully. Generated files in 'build' folder.
f6ab0b98e79cdd2fd08ad37ae4a8f754b82a88b7
fatal: Too many arguments.
Error: git clone failed
```
The issue is same as https://github.com/facebook/docusaurus/issues/2258
However, this is seen on Mac and the workaround mentioned there doesn't work. 

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?
Yes

## To Reproduce

(Write your steps here:)

1. Follow the documentation: https://docusaurus.io/docs/en/tutorial-publish-site
2. Run `GIT_USER=niks3089 CURRENT_BRANCH=master npm run publish-gh-pages`  

## Expected behavior

The site should be live on github pages

(Write what you thought would happen.)

## Actual Behavior

The deployment failed

(Write what happened. Add screenshots, if applicable.)

## Your Environment

 
-  Node v10.22.1
-  MacOs 10.15.5

**Comment by slorber** [comment]
Hi

This part. look suspicious to me: `git@github.com:repo/docs.git`

are you sure your config file has the required fields? 
Otherwise we might try to clone a bad  repo, we can't guess the repo URL to clone if we don't have the  needed config  infos

**Comment by niks3089** [comment]
Closing the issue since the repo was private. Changing to public fixed the problem.
