### ISSUE TITLE
Proposal: upgrade Remark to v13.0.0

### ISSUE THREAD

**Issue by TheodoreChu** [facebook/docusaurus#3668]
## 💥 Proposal: upgrade Remark to v13.0.0

It looks like the mdx-loader is using Remark v12.0.0: https://github.com/facebook/docusaurus/blob/master/packages/docusaurus-mdx-loader/package.json#L39

Remark v13.0.0 was released in mid-October. The release notes explain that "It replaces the 5+ year old internals with a new low-level parser: [`micromark`](https://github.com/micromark/micromark).": https://github.com/remarkjs/remark/releases/tag/13.0.0

Reasons to upgrade:
* The latest versions of many remark plugins do not work with versions of Remark less than v13.0.0

Concerns:
* Not all Remark plugins are compatible with v13. For example, `remark-admonitions` (used in packages such as [`docusaurus-plugin-content-docs`](https://github.com/facebook/docusaurus/blob/master/packages/docusaurus-plugin-content-docs/package.json#L45)) does not yet work with v13. This may mean that we may need to wait for all of the remark plugins to be updated before we upgrade Remark. We can track whether various Remark plugins are compatible with v13 here: https://github.com/remarkjs/remark/blob/main/doc/plugins.md#list-of-plugins
* I am unaware of the difficulties of upgrading Remark from v12 to v13

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

**Comment by slorber** [comment]
Thanks, we'll look into upgrading to Remark 13 but probably a bit later

**Comment by lex111** [comment]
> It looks like the mdx-loader is using Remark v12.0.0:

Not exactly true, we are using Remark 12 to execute tests. To render MD content, we use `@mdx-js/mdx`, which in turn uses Remark 12. But as far as I understand, it's quite difficult to migrate to the new remark in mdx-js. Therefore, this upgrade does not depend on us at this time.

**Comment by TheodoreChu** [comment]
Great, thanks for the clarification @lex111.

**Comment by wooorm** [comment]
We spoke a while back about separating markdown from mdx, e.g., `.md` is markdown, `.mdx` is MDX. If that’s implemented, then it should be possible to upgrade to remark@13 for the markdown part, leaving MDX to using remark@12 (or, what’s it on? I think MDX is on an older version) for now?

**Comment by alexkreidler** [comment]
See also https://github.com/mdx-js/mdx/pull/1367, recently merged, for progress on integrating Remark 13 into MDX (`@mdx-js/mdx`).

**Comment by lunelson** [comment]
I stated this in the other issues but FWIW _[xdm](https://github.com/wooorm/xdm) is always in sync with the latest remark_, and for that matter every other package in the unified ecosystem 🙄

**Comment by slorber** [comment]
@wooorm said recently that he's backporting xdm in mdx so we should be able to keep using mdx too

**Comment by Josh-Cena** [comment]
Going to close this in favor of #4029. I originally kept this open because I planned to parse Markdown on the server with Remark (see #6261), but due to performance and ROI reasons, I eventually decided that regex is still the best solution. Therefore, the only blocking issue is migration to MDX v2.
