### ISSUE TITLE
[v2] Failed to deploy: window is not defined

### ISSUE THREAD

**Issue by mdhsl** [facebook/docusaurus#3670]
## 🐛 Bug Report

Got an error while compiling the project into 'production' mode. 

I found several workarounds on Google but none of them were satisfying.

I am using a custom plugin  to allow the use of external libs injected via npm like Leaflet or OpenLayers as well as my own project (osh-js) located at a different level of the current directory.

You can get any details into the directory https://github.com/opensensorhub/osh-js/tree/improve-documentation/documentationV2

Important: it is working fine in DEV mode

The problem occurs only in Production mode. 

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## To Reproduce

run:

```sh
$ yarn install && yarn build
```

## Expected behavior

build production site into *build* directory without error

## Actual Behavior

Get an error in the middle of the process: *Error: Failed to compile with errors.*

![image](https://user-images.githubusercontent.com/6577027/97791192-ec34de00-1bcf-11eb-9db6-160ae2e21752.png)

## Your Environment

- Docusaurus version used: 2.0.0-alpha.66
- Yarn: 1.22.5
- Node: v10.20.1
- Operating system and version (desktop or mobile): Arch linux 5.4.72-1-lts

## Reproducible Demo

1. Checkout the repo at the branch: https://github.com/opensensorhub/osh-js
2. checkout the branch improve-documentation/documentationV2
3. go to the directory: documentationV2
2. yarn install && yarn build

Or Do the following commands:

```sh
$ git clone https://github.com/opensensorhub/osh-js.git
$ cd osh-js
$ checkout improve-documentation
$ cd documentationV2
$ yarn install && yarn build
```

**Comment by JanCizmar** [comment]
I am facing the same issue. Is there any way to disable building of the server part?

**Comment by mdhsl** [comment]
I have found a workaround (or maybe it is juste the right thing to do!) from [here](https://www.gatsbyjs.com/docs/mdx/importing-and-using-components/#lazy-loading-components)

Lazy loading seems to fix this issue

**Comment by slorber** [comment]
Hi,

You can't acces window on the server.

The workaround is the right thing to do, we even have a core component to solve this problem :) 
https://v2.docusaurus.io/docs/docusaurus-core/#browseronly

Will see if we can improve the error message and link to that page

**Comment by mdhsl** [comment]
OK for closing the issue but browseonly does not fix the problem.
The problem happens while importing the component such like:

import LeafletView from "../../source/osh/ui/view/map/LeafletView";

only this cause the error. But the lazyLoading can help for that. just to clarify ;).

Thx

**Comment by slorber** [comment]
Yes you have to lazy load that lib like I suggest here: https://github.com/mac-s-g/react-json-view/issues/121#issuecomment-670431408

**Comment by huy-lv** [comment]
Hi, are there any official fix for this problem?

**Comment by slorber** [comment]
@huy-lv there is no official fix because this is not a Docusaurus problem in the first place, it's a problem in your code, or your integration with a lib that does not support server-side rendering. 

You would have the exact same problem with any static site generator like Gatsby, Next, Nuxt, Gridsome...

The only possible solution is to either use a lib that support SSR, or to make the integration compatible with Docusaurus (ie render the lib only on the client cf https://github.com/mac-s-g/react-json-view/issues/121#issuecomment-670431408)

**Comment by SiegeSailor** [comment]
> OK for closing the issue but browseonly does not fix the problem. The problem happens while importing the component such like:
> 
> import LeafletView from "../../source/osh/ui/view/map/LeafletView";
> 
> only this cause the error. But the lazyLoading can help for that. just to clarify ;).
> 
> Thx

This exactly fixed my issue.

I had some `*.test.ts` files in my `src/helper/`, and I used `import something from './index'` to import my SUT. Changing the path did make my `npm run build` work again.

Thank you
