### ISSUE TITLE
include external sourced files into build

### ISSUE THREAD

**Issue by vanbasten17** [facebook/docusaurus#3672]
## 🚀 Feature

Be able to pull plain text information from external sources and build it up with docusaurus build.

Example: Retrieving an external markdown file to be injected into a specific route. 

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?
Yes

## Motivation
We would like to source github's READMEs and build them with `docusaurus build` for our project documentation ([botonic](https://github.com/hubtype/botonic/)).
I have seen a related issue here: https://github.com/facebook/docusaurus/issues/2725 , but couldn't find the mentioned plugin in docusaurus docs.

## Pitch
I think it's pretty common for open-source projects to have several plugins in order to add extra functionalities to them. In our situation, every plugin is documented itself in its corresponding README in github which serves as the main documentation as for example [Gatsby does with their plugins](https://www.gatsbyjs.com/plugins/gatsby-plugin-react-helmet/?=), so this is the main reason of being implemented. This is our current [plugins library](https://botonic.io/docs/plugins/plugin-dialogflow).
To do so, maybe it would be useful to have a list of urls (pointing to an url with the corresponding .md in this case) and mapping them into desired routes in the project.

Many thanks! 😊  You have an awesome ongoing project!

**Comment by slorber** [comment]
Hi, this is something I'd like to support.

However, keep in mind that Github README is commonmark, and we are using MDX. The implementation diverge on the HTML elements, so you'll have to avoid using such elements if you want the readme file to work in both Docusaurus and Github pages.

Unfortunately, for now MDX is not 100% compatible with commonmark (https://github.com/mdx-js/mdx/issues/1125), but it'd like to make it easier to use a commonmark compatible mode, in particular for these usecases (related to https://github.com/facebook/docusaurus/discussions/3009 as well)

**Comment by vanbasten17** [comment]
Hi @slorber , thanks for your time! Would you mind sharing with me some guidelines to create a plugin to support this? I'll try to do this if I can invest some time. Thanks

**Comment by slorber** [comment]
@vanbasten17 the best is to read the docs (https://v2.docusaurus.io/docs/lifecycle-apis/), understand the lifecycles to read FS data, create pages etc...
The "pages" plugin is likely easier to get some inspiration. 

But you'll have to figure out how to replace MDX by a regular MD parser/renderer. It's not something I ever did so I can't really help you more than that.

**Comment by Josh-Cena** [comment]
You can now import external MD files: https://github.com/facebook/docusaurus/blob/main/website/community/5-changelog.md

**Comment by benlongo** [comment]
Unfortunately that link appears to be dead now.
