### ISSUE TITLE
renderReloadPopup.js 6:554-564 Critical dependency: the request of a dependency is an expression

### ISSUE THREAD

**Issue by DsCodeStudio** [facebook/docusaurus#3677]
## 🐛 Bug Report

```sh
$ docusaurus build
Creating an optimized production build...

√ Client
  Compiled successfully in 1.26m

√ Server
  Compiled successfully in 1.48m

(undefined) ./node_modules/@docusaurus/plugin-pwa/src/renderReloadPopup.js 6:554-564
Critical dependency: the request of a dependency is an expression
```

I want to add PWA to my site. but something went wrong and I'm not sure if it's a bug or not.

At the same time I configured Algolia to provide document search, but after almost a week, it doesn't work, and I don't see any indexing information in the Algolia Dashboard, is this something I need to add indexing manually? I configured apiKey, appId, indexName, but it didn't work.

Here's my project [DsCodeStudio-Docs](https://github.com/DsCodeStudio/DsCodeStudio-Docs)

1. I want add PWA support
2. I want add algolia docs search

**Comment by slorber** [comment]
Hi,

I don't know about the PWA

For Algolia DocSearch,  I see you have indexName: "prod_env".
I can't see your config, but it may be a config issue.

@shipow was wondering what's the DocSearch story for those that manage their own Algolia appId like it seems to be the case here? Shouldn't we recommend to use the docusaurus-2.json config or something?

**Comment by DsCodeStudio** [comment]
The Algolia DocSearch issue is already being addressed, Algolia DocSearch hasn't synced the key to me yet, and they say they'll take care of it soon!

So now the problem is PWA, I'm not particularly sure how to integrate the docusaurus-pwa plugin in docusaurus. I configured it according to the docs and this problem came up, not sure if it's my configuration or a bug, but removing the plugin made the error report disappear!

**Comment by slorber** [comment]
Create a branch with Docusaurus + PWA in your repo and I'll look at it when I have time

**Comment by DsCodeStudio** [comment]
wow~, All I could say is--thanks. 😊

**Comment by DsCodeStudio** [comment]
I created this branch

https://github.com/DsCodeStudio/DsCodeStudio-Docs/tree/Docusaurus+PWA

**Comment by DsCodeStudio** [comment]
I fixed all the bugs. I'm going to close this Issues.

**Comment by slorber** [comment]
Great.

@DsCodeStudio do you mind sharing how you solved the renderReloadPopup issue?

**Comment by DsCodeStudio** [comment]
My problem is caused by a path, my custom path does not work, the error message says the icon file was read from the img directory.

After testing PWA on all platforms with no problems, this bug was ignored. I'm still testing other features.

When I comment renderReloadPopup.js, it still compiles correctly, with no errors!

so, I didn't completely fix this bug,It still exists.

renderReloadPopup may need to be rewritten.
