### ISSUE TITLE
URL hash collide when different subsections have the same title

### ISSUE THREAD

**Issue by chenglou** [facebook/Docusaurus#368]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md)?

Yes

### Environment

Doesn't matter

### Steps to Reproduce

Try any markdown file

```md
# foo
## baz

# bar
## baz
```

Maybe `baz-1`. for the second one is good enough? No way to guarantee the titles from not clashing, since you might actually have a title called `baz 1`
  
### Expected Behavior

Not sure

### Actual Behavior

In this case, both `baz` will render to html with anchor `baz`, so `my-page#baz` points to the first one always.

**Comment by JoelMarcey** [comment]
@chenglou We fixed this in the nuclide.io docs with the old template. We can see what we can do here. Thanks!

**Comment by SleepWalker** [comment]
Hi, all

@JoelMarcey, is there any updates with this issue? I would like to try to submit a PR with fixes.
What kind of fix was on nuclide.io? I've noticed, that an anchor also inherits the anchor of a parent title, e.g.:

```
# Foo -> #foo
## Bar -> #foo-bar
```

This behavior will fix the bug from issue description, but will not help in rare case, when user will have two same headers on the same level, e.g.:

```
# Foo -> #foo
## Bar -> #foo-bar
## Bar -> #foo-bar
```

Probably the second one should be named `#foo-bar-1`?

---

Another issue (this is why I so interested in anchor related issues) is handling of cyrillic characters:

```
# Привет из Украины -> #(empty string)
```

I think, the correct anchor should be `#привет-из-украины`
