### ISSUE TITLE
Syntax highlighting uses inline styles, making it difficult to use Content Security Policy

### ISSUE THREAD

**Issue by charleskorn** [facebook/docusaurus#3688]
## 🐛 Bug Report

(A clear and concise description of what the bug is)

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## To Reproduce

1. Set a Content Security Policy for your site that includes `style-src 'self';` with either a `<meta>` tag or HTTP header, eg.
  
    ```html
    <meta http-equiv="Content-Security-Policy" content="default-src 'self'; style-src 'self';">
    ```

2. Add a code block on a documentation page, eg.

    ````markdown
    ```shell
    echo "Hello world"
    ```
    ````

## Expected behavior

Code block is highlighted correctly and no CSP violations are reported

## Actual Behavior

Code block appears to be highlighted correctly, but a large number of CSP violations are reported, eg.

```
Refused to apply inline style because it violates the following Content Security Policy directive: "style-src 'self'". Either the 'unsafe-inline' keyword, a hash ('sha256-sDIENtrZwmox3spLJOzzFKFmi3ELZ0v+EkEB+J8SMrA='), or a nonce ('nonce-...') is required to enable inline execution.
```

It's not feasible to add hashes for each of the possible styles - from a simple code block I already have eight different hashes to add.

## Your Environment

- Docusaurus version used: 2.0.0-alpha.66
- Environment name and version (e.g. Chrome 78.0.3904.108, Node.js 10.17.0): Chrome 86.0.4240.183, Node 15.0.1
- Operating system and version (desktop or mobile): macOS 10.15.7 desktop

## Reproducible Demo

(see instructions above)

**Comment by slorber** [comment]
What do you suggest to fix this?
What other sites are doing for syntax highlighting?
What are you trying to achieve with your CSP in the first place?

**Comment by lex111** [comment]
In order to reduce staled issues, I am closing this issue, but feel free to open it again if needed.
