### ISSUE TITLE
Better error message when missing versions.js file

### ISSUE THREAD

**Issue by JoelMarcey** [facebook/Docusaurus#369]
### Is this a bug report?

 No

### Have you read the [Contributing Guidelines]

Yes

### Environment

N/A

### Steps to Reproduce

See https://github.com/facebook/Docusaurus/pull/333#issuecomment-353166152

### Expected Behavior

Better error message telling user that they might be missing `versions.js` file.

### Actual Behavior

404 for versions.html missing

### Reproducible Demo

https://github.com/facebook/Docusaurus/pull/333#issuecomment-353166152

**Comment by sujono91** [comment]
@JoelMarcey 

Hi Joel, I'm interested to work in this issue. Could u give me the right direction of how to solve this issue? (such as message format, etc) 😄

**Comment by JoelMarcey** [comment]
Hi @sujono91, thanks for taking this on.

I think there are a couple of ways to tackle this:

1. You can create a `console` message in https://github.com/facebook/Docusaurus/blob/master/lib/version.js if a `versions.js` file does not exist in the `pages` directory. This would solve the problem if someone ran the `version` script before creating the `versions.js` page (like is done when someone follows the instructions [here](https://docusaurus.io/docs/en/versioning.html) and runs `yarn examples versions` first).

2. You can do something in https://github.com/facebook/Docusaurus/blob/master/lib/core/nav/HeaderNav.js and check to see if `env.versioning.enabled` is `true` and if so, and there is no `versions.js` page, then something happens like an error in the log and/or a message in the header nav or something.

Does this help you get started?

**Comment by sujono91** [comment]
@JoelMarcey Ok, I'll try it right now. Will let u know if i've any concern

**Comment by endiliey** [comment]
Hi @JoelMarcey ,
Won't it be better to enforce not running the server & show the warning if `versions.js` doesn't exist ? If we only show warning on `version` script, they might still got the error

I see that there are other similar unclosed issue #228 #297 where versions HTML page are not being created.

**Comment by sujono91** [comment]
@JoelMarcey I think we can close this issue

**Comment by yangshun** [comment]
Yes you're right! For future reference, you can also add "Fixes #369" in your PR and when your PR is merged, the issue will be closed automatically 😄
