### ISSUE TITLE
Code blocks is failed

### ISSUE THREAD

**Issue by rocosen** [facebook/docusaurus#3690]
## 📚 Documentation

Code blocks is failed。

![微信截图_20201105142435](https://user-images.githubusercontent.com/49807007/98205493-3cff5a80-1f73-11eb-8dde-914951c51a34.png)
![微信截图_20201105142639](https://user-images.githubusercontent.com/49807007/98205498-3ec91e00-1f73-11eb-9ea8-42ad3379f9e8.png)
![微信截图_20201105142651](https://user-images.githubusercontent.com/49807007/98205500-3ffa4b00-1f73-11eb-8f14-5f87723c84be.png)

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

(yes)

**Comment by rocosen** [comment]
Code highlight and copy button disappear

**Comment by rocosen** [comment]
I upgraded the version and did not update node_modules .

**Comment by HonkingGoose** [comment]
Wild guess incoming, did you perhaps update to `@mdx-js/react v1.6.20` or `@mdx-js/react v1.6.21`?
I'm having problems with my code blocks not working also, and it also affects things like Git syntax highlighting, so it's not just JavaScript highligting that's broken.

See https://github.com/mdx-js/mdx/issues/1320 for more on the possible `@mdx-js/react` breakage.
