### ISSUE TITLE
Providing static-assets directory from Configuration

### ISSUE THREAD

**Issue by apurvaojas** [facebook/docusaurus#3692]
## 🚀 Static Assets Directory from configuration

Users should be able to provide `staticAssetsPath` from the `docusaurus.config.js`.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## Motivation

To have freedom, to choose directory structure of project.

## Pitch

Currently user are bound to follow the directory structure `root-folder/static/` for the static content. It is difficult to follow this structure in lots of many cases in which user is working on mono repo structure or any custom directory structure.
Users should have freedom to choose the directory structure of their own choice.

**Comment by Josh-Cena** [comment]
Closing in favor of #3983
