### ISSUE TITLE
Live Editor: HTML code not working

### ISSUE THREAD

**Issue by jumpersdevice** [facebook/docusaurus#3710]
Hello guys, hope you're doing good.

I've successfully implemented the Live editor plugin with npm as recommended in https://v2.docusaurus.io/docs/markdown-features/#interactive-code-editor
It's working perfectly, however, i'm trying to create a live example of a simple html page and isn't working. Is this the default setting? only javascript and some other languages work.

Thanks

**Comment by slorber** [comment]
Hi,

We use react-live, so I suspect it's mostly useful for React and JS code, not really HTML or CSS
https://github.com/FormidableLabs/react-live

**Comment by lex111** [comment]
In order to reduce staled issues, I am closing this issue, but feel free to open it again if needed.
