### ISSUE TITLE
Anchor tabs when changing focus (or otherwise compensate for a changing page length)

### ISSUE THREAD

**Issue by allanaaa** [facebook/docusaurus#3728]
## 🚀 Feature

As per https://docusaurus-2.netlify.app/feedback/p/scroll-updown-when-switching-synced-tabs-with-different-content-heights-to-follo
+1. We are finding this unwieldy. (See https://github.com/OpenRefine/OpenRefine/issues/3309). 

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## Motivation

We're currently using tabs for operating systems as well as different installation instructions. Users might not switch between operating systems much, but switching e.g. to the "Mac via Homebrew" tab here really messes with the page length. https://docs.openrefine.org/manual/installing/#install-or-upgrade-openrefine

## Pitch

You should implement this so people don't get frustrated reading documentation. It's already off-putting even when executed well. Thanks!

**Comment by lex111** [comment]
Agree, this is a really unpleasant thing, we will try to fix it.

**Comment by slorber** [comment]
Weird, if you scroll a little bit,  this does not happen anymore and the browser is able to figure out how to keep the scroll position (at least Chrome, Firefox seems to struggle even more)

**Comment by allanaaa** [comment]
I forgot to ask: Do you have any quick fixes or workarounds for the time being?

**Comment by lex111** [comment]
Perhaps disabling tab choices syncing will help in your case?

**Comment by Radolumbo** [comment]
I don't think this should be closed ... it's nice that if a switch moves the tab totally out of your viewport, it at least readjusts the window to include it

But I think the actual behavior should be that the scroll adjusts such that the tab stays in the same RELATIVE position within your window. Even just having the tab pushed down or up in your window when you make a switch is really annoying and jarring.

**Comment by slorber** [comment]
The tab has a different height so it can't technically "stay in the same position".

The most we could do is keep the tab top stay at the same position, but the tab bottom position will still change.

This may be harder to implement and the ROI is not huge, so I suggest adding this to Canny / feature requests

**Comment by Radolumbo** [comment]
Yeah, I meant the top of the tab, since that's what matters in terms of creating that "jarring" effect where suddenly your window position changes. 

But, fair enough, I can make this a feature request instead.
