### ISSUE TITLE
Selecting a search result does not pull up the corresponding anchor link

### ISSUE THREAD

**Issue by beeradley** [facebook/docusaurus#3735]
## 🐛 Bug Report

On production https://v2.docusaurus.io, when you select a header anchor from the search results, you're navigated to the correct page—but not to the correct anchor. This bug occurs on desktop Safari, but not iOS Safari.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## To Reproduce

- Navigate to https://v2.docusaurus.io in Safari 14.0 on macOS 10.15.7
- Open the docs, and navigate to the "Introduction" page.
- Search for "Project Structure" (which is an anchor about halfway down the "Installation" page):

<img width="554" alt="search" src="https://user-images.githubusercontent.com/46536855/99028483-1b7f0f80-252d-11eb-85a6-d2bd3c0b0738.png">

- Use the arrow keys to navigate down to the "Project Structure" search result, and hit enter.
- Notice that you're navigated to the top of the page, not the anchor link for "Project Structure"

## Expected behavior

Selecting an anchor result from the search list actually navigates you to that anchor.

## Actual Behavior

- On the desktop, you're navigated to the top of the page where the anchor is found, but not to the selected anchor.
- On mobile Safari on iOS 14.2, you are navigated to the header, as expected.

## Your Environment

- Safari 14.0
- macOS 10.15.7

## Reproducible Demo

- https://v2.docusaurus.io

**Comment by slorber** [comment]
It may be only on Safari, because Chrome seems to work fine

**Comment by beeradley** [comment]
@slorber Hmm, I'm seeing it intermittently on Chrome, too... and, actually, it looks like it occasionally works on Safari, too—but not all the time. If you navigate around a bit in the left sidebar, land on some doc, and then run the "project structure" search, sometimes it takes you to the anchor, but the majority of the time it does not.

Inspecting the search results, I'm seeing this link for that specific result:

<a href="/docs/installation/#project-structure">

It seems to work more consistently if I manually remove the slash before the the anchor link.

**Comment by slorber** [comment]
Was wondering: why do you have a trailing slash in the first place?

I think this might be related to if the bundles of the target page are already prefeteched or not, but hard to be sure

**Comment by beeradley** [comment]
Yeah, I'm not sure—I agree it looks suspect.

**Comment by beeradley** [comment]
I took a look at this — it looks as though the search results come back with the hashtag after the slash. Not sure if that somehow impacts the routing, etc.

**Comment by beeradley** [comment]
@slorber I can't seem to repro this anymore. I wonder if [this commit](https://github.com/facebook/docusaurus/commit/915f949c25844c247d03937feb5df72481ce8d46) fixed it? Thanks!

**Comment by slorber** [comment]
yes this is likely @beeradley 

let's close this but let me know if you still see this issue

**Comment by slorber** [comment]
afaik the issue was if we pressed "enter" instead of clicking, maybe it's what you encountered as well?
