### ISSUE TITLE
I wanted to add the ability to hide the document sidebar, but it didn't work.

### ISSUE THREAD

**Issue by DsCodeStudio** [facebook/docusaurus#3736]
I wanted to add the ability to hide the document sidebar, but it didn't work.

From this https://github.com/facebook/docusaurus/pull/3615

I found that the online website works, and downloading the source code test revealed that there is no integrated feature to hide the document sidebar.

This would be extremely helpful to improve the online reading experience for users.

Is it not officially online yet?

**Comment by slorber** [comment]
This is unreleased, will be released soon

**Comment by DsCodeStudio** [comment]
OK, thank you!

**Comment by emilnewel** [comment]
@slorber can you give us an estimate on how soon is soon? 😄

**Comment by slorber** [comment]
The next release, very likely this week

**Comment by tesla809** [comment]
Has this been released yet? I am trying to use the `themeConfig.docs.sidebar.hideable` option, but it seems not to be working.

**Comment by slorber** [comment]
Create a repro detailing what doesn't work exactly with the actual/expected behavior and we'll look into it

**Comment by gchatz22** [comment]
Agreed with @tesla809, attempted this config in `docusaurus.config.js` and sidebar cannot be hidden
```
docs: {
          routeBasePath: "/",
          sidebarPath: require.resolve("./sidebars.js"),
          sidebar: {
            sidebarCollapsible: true,
            sidebarCollapsed: false,
            hideable: true,
          },
```
according to https://docusaurus.io/docs/sidebar#hideable-sidebar

**Comment by Josh-Cena** [comment]
@gchatz22 This should be in `themeConfig`, not `presets`.

**Comment by gchatz22** [comment]
Okay still not functional unfortunately
```
themeConfig:
    /** @type {import('@docusaurus/preset-classic').ThemeConfig} */
    ({
      sidebar: {
        sidebarCollapsible: true,
        sidebarCollapsed: false,
        hideable: true,
      },
```

**Comment by Josh-Cena** [comment]
The doc says the shape is:

```js
module.exports = {
  themeConfig: {
    docs: {
      sidebar: {
        hideable: true,
      },
    },
  },
};
```

So you are missing a `docs: {}` nesting there.

**Comment by gchatz22** [comment]
Thank you although a bit confusing, it worked

**Comment by wgruszczyk** [comment]
@slorber I was trying the approach for secondary docs:
`  presets: [
    [
      "classic",
      {
        docs: {
          id: "glossary",
          path: "glossary",
          routeBasePath: "glossary",
          sidebarPath: require.resolve("./sidebars.js"),
          remarkPlugins: [math],
          rehypePlugins: [katex],
        },`

and in this case the hideable sidebar is ignored.

**Comment by slorber** [comment]
need a repro if you want help @wgruszczyk

**Comment by wgruszczyk** [comment]
> need a repro if you want help @wgruszczyk

hi @slorber 
I managed to put a bug-proof together - you can find it in [this repo](https://github.com/wgruszczyk/sidebar-bug-proff-docusaurus)

just `npm start` it and the docs (available in top menu) will not have collapsible side menu.

Thank you!

**Comment by slorber** [comment]
@wgruszczyk as documented the `sidebar.hideable` is nested under a `docs` attribute

<img width="1013" alt="CleanShot 2022-12-09 at 10 29 29@2x" src="https://user-images.githubusercontent.com/749374/206670043-1d3fa418-2b5e-48f7-9d00-fa6028d5186f.png">


It works fine once you configure it properly:

<img width="1037" alt="CleanShot 2022-12-09 at 10 28 25@2x" src="https://user-images.githubusercontent.com/749374/206669969-381968ed-8487-4b18-95db-5ccda3595ec1.png">

**Comment by wgruszczyk** [comment]
Thank you! Apparently, I was looking at it for way too long. Works like a charm!
