### ISSUE TITLE
#3394 appears to have broken swizzle

### ISSUE THREAD

**Issue by taylorreece** [facebook/docusaurus#3747]
## 🐛 Bug Report

#3394 added a reference to `../../utils/useThemeConfig`. That's fine if components are in `@docusaurus/theme-classic`, but if you swizzle a component you cannot reference that module.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## To Reproduce

```bash
$ npx @docusaurus/init@next init my-website classic
$ cd my-website
$ npx docusaurus swizzle @docusaurus/theme-classic Footer
Success! Copied @docusaurus/theme-classic Footer to src/theme/Footer.
$ npm run start
Module not found: Can't resolve '../../utils/useThemeConfig' in '/Users/treece/Desktop/my-website/src/theme/Footer'
```

## Expected behavior

I'd expect the website to start, with a swizzled Footer

## Actual Behavior

Site fails to start; `Module not found: Can't resolve '../../utils/useThemeConfig' in '/Users/treece/Desktop/my-website/src/theme/Footer'`

## Your Environment

- Docusaurus version used: 2.0.0-alpha.66
- Environment name and version: Nodejs v12.16.2
- Operating system and version (desktop or mobile): MacOS

**Comment by slorber** [comment]
yes that's bad, we'll fix that asap

**Comment by slorber** [comment]
This will be fixed by moving the utils in a new `@docusaurus/theme-common` package.

https://github.com/facebook/docusaurus/pull/3775
