### ISSUE TITLE
[Question] How to add access control option?

### ISSUE THREAD

**Issue by inix** [facebook/docusaurus#3748]
## ❓ Questions and Help
Dear developers,I know this is a static site generator, but I want to add access based control option, which I can expose site doc pages to register users.
I want to integrated with a dynamic cms such as Wordpress.
How to config it?
Thanks

**Comment by slorber** [comment]
We don't support protected routes out of the box, but it does not mean it's not possible.

The protected routes of your side should only be rendered client-side, fetch the protected data using the cookie, and render it. It's the same technique for all SSGs, so you can reuse the existing Gatsby knowledge for example.

We have a browser only component here: https://v2.docusaurus.io/docs/docusaurus-core#browseronly

And we use ReactRouter under the hood, so you can render client-only routes using ReactRouter API.
https://v2.docusaurus.io/docs/docusaurus-core#redirect

**Comment by lex111** [comment]
You may find it helpful to read this issue https://github.com/facebook/docusaurus/issues/2769
Since we cannot implement this in any way, I close the question.
