### ISSUE TITLE
Allow use of gtag.js Google Analytics script

### ISSUE THREAD

**Issue by j-f1** [facebook/Docusaurus#375]
### Is this a bug report?

No

### Have you read the [Contributing Guidelines](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md)?

Yes.

### Environment

OS: macOS 10.12.3 (16D32)
Node: v9.0.0
npm: 5.5.1
Yarn: 1.3.2

### Steps to Reproduce

1. Add a `gaTrackingId` to the site config.
1. In a file added to the `scripts` config option, add this code:
   ```js
   gtag('event', 'login')
   ```
3. Open your website

### Expected Behavior

The `login` event would be reported to Google Analytics via the [`gtag.js`](https://developers.google.com/analytics/devguides/collection/gtagjs/) API.

### Actual Behavior

```
ReferenceError: Can't find variable: gtag
```

### Reproducible Demo

[Code](https://github.com/j-f1/docusaurus-ga-demo) • [Website](https://j-f1.github.io/docusaurus-ga-demo/)

**Comment by yangshun** [comment]
Has been fixed in #601 thanks to @ramiel!
