### ISSUE TITLE
[v2] Fails to build if markdown image alt-text has double quotes

### ISSUE THREAD

**Issue by garrettjstevens** [facebook/docusaurus#3751]
## 🐛 Bug Report

If the alt-text for an image in a markdown file has double quotes, docusaurus will not build.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## To Reproduce

1. Create docusaurus page with classic template
1. To any markdown file, add an image with double quotes in the alt text, like this:
`![alt text with "quotes"!](../static/img/logo.svg)`

## Expected behavior

The page builds.

## Actual Behavior

The site will not build. The error looks like:

```
./docs/doc1.md
SyntaxError: /sandbox/docs/doc1.md: Unexpected token, expected "}" (65:57)

> 65 | <p>{`Has quotes in alt text: `}<img alt={"alt text with "quotes"!"} src={require("!url-loader?limit=10000&name=assets/images/[name]-[hash].[ext]&fallback=file-loader!./../static/img/logo.svg").default}  /></p>
     |                                                          ^
```

It looks to me like the double quotes are not getting escaped.

## Your Environment

- Docusaurus version used: `2.0.0-alpha.66`
- Environment name and version: Chrome 86.0.4240.198, Node.js 10.21.0
- Operating system and version: Linux Mint

## Reproducible Demo

Reproducible codesandbox: https://codesandbox.io/s/suspicious-brattain-1g5k4?file=/docs/doc1.md:2219-2294

**Comment by slorber** [comment]
Thanks, you are right, our remark plugins should escape those quotes properly
