### ISSUE TITLE
All official @docusaurus/* packages should have the exact same version as @docusaurus/core

### ISSUE THREAD

**Issue by Morriz** [facebook/docusaurus#3755]
## 🐛 Bug Report

@docusaurus/plugin-ideal-image versioning does not move with core. It's last published package is `2.0.0-alpha.37`, and npm start now throws an error:
```
Module not found: Can't resolve '@theme/IdealImage' in 'xxxxxxx/src/pages'
Bad docusaurus-plugin-ideal-image version 2.0.0-alpha.39.
All official @docusaurus/* packages should have the exact same version as @docusaurus/core (2.0.0-alpha.66).
Maybe you want to check, or regenerate your yarn.lock or package-lock.json file?
```

**Comment by Morriz** [comment]
Same goes for @docusaurus/plugin-content-docs ;(

**Comment by Morriz** [comment]
Ok, I figured out that if I install it @next it will pick up the core version:
```
npm install -S @docusaurus/plugin-ideal-image@next
```

Can this be added to your docs?

**Comment by Morriz** [comment]
Re-opening as this is problematic and should be looked at. If this can only be solved by adding docs, then please do so. I just added a request for that as well.

**Comment by slorber** [comment]
Hi @Morriz 

I think one issue is enough for this.
If you know a good place where to document this, please let us know (we accept docs PRs)
