### ISSUE TITLE
Document installing plugin@next

### ISSUE THREAD

**Issue by Morriz** [facebook/docusaurus#3756]
## 📚 Documentation

It took me some time to figure out that installing a plugin as documented was giving me errors (See #3755 ) because the version would not match core. Example:
```
npm install -S @docusaurus/plugin-ideal-image
```
This would install the latest published version of the plugin, which was `2.0.0-alpha.37` at the time of writing.

It turns out that installing a plugin `@next` somehow does install it at core version, which I did not see documented here: https://v2.docusaurus.io/docs/using-plugins/

Example:
```
npm install -S @docusaurus/plugin-ideal-image@next
```
After doing that I see version `2.0.0-alpha.66` of the plugin installed (which is strange as it is not published).

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

**Comment by slorber** [comment]
We indeed want to align versions, the error is on-purpose fail-fast behavior to avoid more nasty issues due to incompatible versions.

According to you, what changes should be made to the docs to make this clearer? 
Would you mind submitting a PR doing this update?

**Comment by Morriz** [comment]
"NOTICE: To circumvent npm errors due to incompatible versions installed between core and plugins, we advise to install all packages at version "next". Example:

`npm install -S @docusaurus/core@next @docusaurus/plugin-ideal-image@next`"

Maybe something like this?

**Comment by slorber** [comment]
Hi

Last release used the latest tag

We're going to remove @next refs from the doc

Can you confirm it works better for you now?

Le mar. 17 nov. 2020 à 18:52, Maurice Faber <notifications@github.com> a
écrit :

**Comment by slorber** [comment]
It looks like it work as expected now, you don't need the next tag anymore to get latest packages
