### ISSUE TITLE
Failed to start Docusaurus server on an `exFAT` drive

### ISSUE THREAD

**Issue by thanh-vinh** [facebook/docusaurus#3773]
## 🐛 Bug Report

Failed to start Docusaurus server on an `exFAT` drive on Windows. It doesn't happen on MacOS.

## To Reproduce

1. Create new project on an `exFAT` drive

```
npx @docusaurus/init@next init my-website classic
```

2. Start project

```
cd my-website
yarn start
```

## Expected behavior

The server start successfully

## Actual Behavior

Compiled with some errors

```
yarn run v1.22.10
$ docusaurus start
Starting the development server...
Docusaurus website is running at: http://localhost:3000/

× Client
  Compiled with some errors in 3.48s

i ｢wds｣: Project is running at http://localhost:3000/
i ｢wds｣: webpack output is served from /
i ｢wds｣: Content not from webpack is served from D:\_test\my-website
i ｢wds｣: 404s will fallback to /index.html


./node_modules/@docusaurus/theme-classic/lib/theme/NavbarItem/index.js
Module not found: Can't resolve '@theme/NavbarItem/DocsVersionDropdownNavbarItem' in 'D:\_test\my-website\node_modules\@docusaurus\theme-classic\lib\theme\NavbarItem'
```

## Your Environment

- Docusaurus version used: `2.0.0-alpha.66`
- Environment name and version: Node v14.13.1, Yarn v1.22.10
- Operating system and version (desktop or mobile): Windows 10 v20H2 Desktop

## Reproducible Demo

See above

**Comment by Josh-Cena** [comment]
We now have Windows tests, so these issues shouldn't happen again.
