### ISSUE TITLE
npm ERR! notarget No matching version found for @docusaurus/init@next

### ISSUE THREAD

**Issue by TomPeirs** [facebook/docusaurus#3780]
## 🐛 Bug Report

Tonight I tried to create a docusaurus instance on my windows machine.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## To Reproduce

(Write your steps here:)

1. Have node installed Node.js version >= 10.15.1
 --> I currently run node v14.15.0
2. Install Yarn Yarn version >= 1.5
--> I run yarn version 1.22.5
3. Scaffold your website: npx @docusaurus/init@next init my-website classic
**(The following simply works as expected -> npx @docusaurus/init@2.0.0-alpha.68 init my-website classic)**

## Expected behavior

A folder structure is scaffolded.

## Actual Behavior

npm ERR! notarget No matching version found for @docusaurus/init@next

Windows Powerrshell logs
`PS C:\dev> npx @docusaurus/init@next init my-website classic
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @docusaurus/init@next.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Harry\AppData\Roaming\npm-cache\_logs\2020-11-18T21_15_38_608Z-debug.log
Install for [ '@docusaurus/init@next' ] failed with code 1`

Logs
`0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '@docusaurus/init@next',
1 verbose cli   '--global',
1 verbose cli   '--prefix',
1 verbose cli   'C:\\Users\\Harry\\AppData\\Roaming\\npm-cache\\_npx\\25584',
1 verbose cli   '--loglevel',
1 verbose cli   'error',
1 verbose cli   '--json'
1 verbose cli ]
2 info using npm@6.14.8
3 info using node@v14.15.0
4 verbose npm-session a310fba5fd179568
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 http fetch GET 304 https://registry.npmjs.org/@docusaurus%2finit 271ms (from cache)
8 silly registry:manifest no matching version for @docusaurus/init@next in the cache. Forcing revalidation.
9 http fetch GET 200 https://registry.npmjs.org/@docusaurus%2finit 1488ms
10 silly fetchPackageMetaData error for @docusaurus/init@next No matching version found for @docusaurus/init@next.
11 timing stage:rollbackFailedOptional Completed in 1ms
12 timing stage:runTopLevelLifecycles Completed in 1793ms
13 verbose type tag
14 verbose stack @docusaurus/init: No matching version found for @docusaurus/init@next.
14 verbose stack     at pickManifest (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-pick-manifest\index.js:122:13)
14 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\pacote\lib\fetchers\registry\manifest.js:43:18
14 verbose stack     at tryCatcher (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\util.js:16:23)
14 verbose stack     at Promise._settlePromiseFromHandler (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:517:31)
14 verbose stack     at Promise._settlePromise (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:574:18)
14 verbose stack     at Promise._settlePromise0 (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:619:10)
14 verbose stack     at Promise._settlePromises (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:699:18)
14 verbose stack     at _drainQueueStep (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\async.js:138:12)
14 verbose stack     at _drainQueue (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\async.js:131:9)
14 verbose stack     at Async._drainQueues (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\async.js:147:5)
14 verbose stack     at Immediate.Async.drainQueues [as _onImmediate] (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\async.js:17:14)
14 verbose stack     at processImmediate (internal/timers.js:461:21)
15 verbose cwd C:\dev
16 verbose Windows_NT 10.0.19041
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "@docusaurus/init@next" "--global" "--prefix" "C:\\Users\\Harry\\AppData\\Roaming\\npm-cache\\_npx\\25584" "--loglevel" "error" "--json"
18 verbose node v14.15.0
19 verbose npm  v6.14.8
20 error code ETARGET
21 error notarget No matching version found for @docusaurus/init@next.
22 error notarget In most cases you or one of your dependencies are requesting
22 error notarget a package version that doesn't exist.
23 verbose exit [ 1, true ]
`

## Your Environment

Docusaurus version @next
Node v14.15.0
Operating system : windows 10 Home 

## Reproducible Demo

No demo sorry ;-)

**Comment by camiluc** [comment]
same issue using npm@7.0.12 and node@15.2.1 on windows 10 home 2004
tom's workaround works fine ❤

**Comment by slorber** [comment]
Hi,

Yesterday's release changed a bit the way we use npm dist tags: we don't use @next anymore now, and all v2 packages are published with "latest" tag.

I'm in the process to remove all `@next` refs from the doc, it's only a temporary doc  issue ;)

**Comment by ledtest** [comment]
Hello everyone，I met this issue too.And I use this command `sudo npx @docusaurus/init@2.0.0-alpha.68 init my-website classic` solved my problem.

**Comment by slorber** [comment]
@ledtest we don't document anymore to use `@next`. If you follow the updated doc it should work.
