### ISSUE TITLE
Dart Code is not colorizing in browser.

### ISSUE THREAD

**Issue by yahu1031** [facebook/docusaurus#3782]
## 🐛 Bug Report

\```dart title="main.dart"
import 'dart:html';

void main() {
  var header = querySelector('#header');
  header.text = "Hello, World!";
}
\```
This doesn't recognize dart language, where as if I make it as `java` it does give the code colors.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

yes

## To Reproduce

(Write your steps here:)

1. Write some dart code and check the code with dart and java code block
    <img src="https://user-images.githubusercontent.com/35523357/99597426-f94e2b80-2a1d-11eb-9224-a12a767836d4.png" height=200/>
    <img src="https://user-images.githubusercontent.com/35523357/99597623-4500d500-2a1e-11eb-980b-89d900668414.png" height=200/>
2. Check in the browser.

## Expected behavior

I want that code to be colored when I use **\```dart**.

## Actual Behavior

<img src="https://user-images.githubusercontent.com/35523357/99597832-9ad57d00-2a1e-11eb-801b-9bf090caf402.png" height=200/>
<img src="https://user-images.githubusercontent.com/35523357/99597835-9c06aa00-2a1e-11eb-9e33-bcaa44ba6da6.png" height=200/>

## Your Environment

- Docusaurus version used:
    ```json
    "dependencies": {
      "@docusaurus/core": "2.0.0-alpha.66",
      "@docusaurus/preset-classic": "2.0.0-alpha.66",
      "@mdx-js/react": "^1.5.8",
      "clsx": "^1.1.1",
      "react": "^16.8.4",
      "react-dom": "^16.8.4"
    },
    ```
- Environment name and version (e.g. Chrome 78.0.3904.108, Node.js 10.17.0): 
    #### Microsoft Edge is up to date. ####
    Version 86.0.622.69 (Official build) (64-bit)
      > As microsoft edge is developed on chromium, hoping chrome or Edge doesn't make difference.
    #### Node JS ####
    v14.15.0

- Operating system and version (desktop or mobile):
    
    **Edition**	Windows 10 Pro
    **Version**	20H2
    **Installed on**	‎18-‎11-‎2020
    **OS build**	19042.630
    **Experience** 	Windows Feature Experience Pack 120.2212.31.0

## Reproducible Demo

<img src="https://user-images.githubusercontent.com/35523357/99599150-c5c0d080-2a20-11eb-8a17-41bcce0d212f.gif" height=300/>

**Comment by Simek** [comment]
Hi @yahu1031, 

you need to add Dart to the Prism `additionalLanguages` configuration field:

```  
themeConfig: {
    prism: {
      additionalLanguages: ['dart'],
    },
}
```
You can read more about syntax highlighting features and configurtation in the docs:
* https://v2.docusaurus.io/docs/markdown-features/#syntax-highlighting

### Result
<img width="620" alt="Screenshot 2020-11-19 121659" src="https://user-images.githubusercontent.com/719641/99659504-3ee01800-2a61-11eb-9764-260c424f72a7.png">

**Comment by yahu1031** [comment]
@Simek Thanks for the help ❤️
