### ISSUE TITLE
[v2] link checker cli command

### ISSUE THREAD

**Issue by aeneasr** [facebook/docusaurus#3792]
## 🚀 Feature

The very useful feature which checks if links are working is currently only exposed via `docusaurus build` or `docusaurus start`. It would be great to have `docusaurus lint` (or check or whatever) which would run the link checking without executing a build / compile.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

yes

## Motivation

We want to run this check as part of the CI. Because the build (plus install) is really slow it would be great to have this functionality as a separate command.

## Pitch

See above!

**Comment by slorber** [comment]
If you have a page with `<Link to={`/docs/${docSlug}`}>`, we can't check if this link is broken without evaluating the code (ie building the site).

The link checker currently collects all the links that are statically rendered and compare them to existing routes, which permits to detect all the broken links reliably.

Having a link checker that works ahead of time would be a completely different implementation, that would work for a majority of usecases, but not all. The links would have to be statically evaluable, like `<Link to="/staticString">`, for this to work

We'll probably add this someday, as it's convenient to have a faster link checker, however it's only a convenience and require some work to get it done, so it's not a high priority.

**Comment by aeneasr** [comment]
I see, thank you for the explanation! Is there any other way to speed up the build time?

**Comment by slorber** [comment]
After i18n it's likely that we'll focus on perf. 
The Webpack 5 migration is likely to improve things significantly according to some feedback from NextJS.

**Comment by Josh-Cena** [comment]
Closing because... all we can do is actually building the site
