### ISSUE TITLE
Can't start a new project

### ISSUE THREAD

**Issue by willianhf** [facebook/docusaurus#3798]
## 🐛 Bug Report

When I try to scaffold a new project with `@docusaurus/init` it's giving me the following error:
```
Couldn't find an alternative telinit implementation to spawn.
```

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## To Reproduce

1. Open the terminal and run `npx @docusaurus/init init my-website classic`

## Expected behavior

The project should be created.

## Actual Behavior

![image](https://user-images.githubusercontent.com/19766657/99906155-45b29900-2cb4-11eb-87cf-9bb6ed33f3d4.png)

## Your Environment

- Docusaurus version used: v2.0.0-alpha.69
- Environment name and version: Node v12.18.3, yarn v1.22.5
- Operating system and version: WSL v2 Ubuntu-18.04

**Comment by slorber** [comment]
Hi,

You can't be on alpha 69 because it's not released yet 😅 

Can you run `npx @docusaurus/init --version` ?

Are you using Docker ou Kubernetes? Your error seems related to these technologies  according to Google.

**Comment by slorber** [comment]
Might be related to https://github.com/facebook/docusaurus/issues/3799

Can you try `npx @docusaurus/init@latest init my-website classic` ?

**Comment by willianhf** [comment]
> Hi,
> 
> You can't be on alpha 69 because it's not released yet 😅
>
> Can you run `npx @docusaurus/init --version` ?
> 
> Are you using Docker ou Kubernetes? Your error seems related to these technologies according to Google.

Sorry, I didn't saw the unreleased tag 😑.
Not using either.


> Might be related to #3799
> 
> Can you try `npx @docusaurus/init@latest init my-website classic` ?

That worked for me, thanks!
