### ISSUE TITLE
fix(v2): wrap code blocks on print not working anymore

### ISSUE THREAD

**Issue by Beluk** [facebook/docusaurus#3814]
fix(v2): wrap code blocks on print not working anymore in 2.0.0-alpha.69.

**Comment by slorber** [comment]
Hi,

I'm sorry but I'm not able to understand what you are talking about. 

Can you write a proper bug report with details please?

What is expected behavior, what is actual behavior?

@lex111 do you understand?

**Comment by lex111** [comment]
Actually, it works, you can make sure this by following the [link](https://v2.docusaurus.io/docs/typescript-support) and then pressing Ctrl + P to print this page. Long lines in code blocks are wrapped.

![image](https://user-images.githubusercontent.com/4408379/100215954-bf4fbe80-2f22-11eb-8924-1d1ea8e6d5f4.png)

**Comment by Beluk** [comment]
Right, on 2.0.0-alpha.70 (unreleased) it looks working again. I did not test this version.

**Comment by slorber** [comment]
@Beluk alpha 69 was released yesterday and we didn't change anything related to this on master

**Comment by Beluk** [comment]
Well, that's really strange. I'll try to explain what i did:

In 2.0.0-alpha.66 i edited locally the CodeBlock\styles.modules.css and add the lines
```
@media print {
  .codeBlockLines {
    white-space: pre-wrap;
  }
}
```
After that i did
`yarn build`
`yarn serve`

and after that visiting my page and press print, the code block was wrapped fine.

Then i changed the package.json and replaced  the number 66 to 69

    "@docusaurus/core": "2.0.0-alpha.69",
    "@docusaurus/preset-classic": "2.0.0-alpha.69",

and run

`yarn install`
`yarn build`
`yarn serve`

After that the code block are not wrapped on print. But when visiting the example page mentioned above it wraps the code.

Any hints what could be the reason of the different behaviour?

**Comment by slorber** [comment]
@Beluk it's hard to debug your problem if we don't have access to your site source code nor live deployment.

**Comment by Beluk** [comment]
Ok i found out that i did not update the mdx-js/react version. After chaning the following line the code wrap on print works fine.

![image](https://user-images.githubusercontent.com/10911904/100231090-d7294180-2f26-11eb-8ee8-ecac9cb2a657.png)

Thanks for your support.

**Comment by slorber** [comment]
Why do you add mdx as a dependency?

We already declare that dependency with a newer version, so declaring a mother version on your site means you are using 2 mdx versions on the same site?

**Comment by Beluk** [comment]
I did not add it, it was added automatically the first time i used:

`npx @docusaurus/init@next init test classic`

Then i followed the update guide and increased only the two mentioned version number.
https://v2.docusaurus.io/docs/installation/

What would be the best way for handling the mdx regarding future updates?

PS: I'm using a virtual machine only running docusaurus.

**Comment by slorber** [comment]
it was maybe a mistake in past versions, you should not need to add it as a site dependency unless you plan to use it in your site's pages directly.

**Comment by Beluk** [comment]
ok, thanks for the information.
