### ISSUE TITLE
Conflict of docs's paths

### ISSUE THREAD

**Issue by tomchen** [facebook/docusaurus#3818]
## 🐛 Bug Report

If there are multiple 'docs', any starting string of any path of 'docs' cannot be exact match of path of another 'docs'. E.g. if there is a 'docs' with the path 'community', you can't set up another 'docs' with the path 'community2'.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## To Reproduce

1. Take Docusaurus 2's official website source as an example. Use `git@github.com:facebook/docusaurus.git`'s `website` folder, `yarn` to install dependencies

1. duplicate the folder `community` and rename the second `community` folder to `abc`. Also duplicate `sidebarsCommunity.js` and rename the second one to `sidebarsAbc.js`

1. In docusaurus.config.js, in the `plugins`, add `abc` section after the `community` section:
```js
    [
      '@docusaurus/plugin-content-docs',
      {
        id: 'community',
        path: 'community',
        editUrl: 'https://github.com/facebook/docusaurus/edit/master/website/',
        routeBasePath: 'community',
        sidebarPath: require.resolve('./sidebarsCommunity.js'),
        showLastUpdateAuthor: true,
        showLastUpdateTime: true,
      },
    ],
    [
      '@docusaurus/plugin-content-docs',
      {
        id: 'abc',
        path: 'abc',
        editUrl: 'https://github.com/facebook/docusaurus/edit/master/website/',
        routeBasePath: 'abc',
        sidebarPath: require.resolve('./sidebarsAbc.js'),
        showLastUpdateAuthor: true,
        showLastUpdateTime: true,
      },
    ],
```

4. `yarn start`. It works, no problem.

4. **change `path: 'abc',` to `path: 'community2',` (or `communityb`, `community-2`, etc.), also change the folder name, then `yarn start` again, this time it can't run. (see [#issuecomment-733845905](#issuecomment-733845905) for the error message)**

4. if you change 'abc' to '2community', 'bcommunityb', 'communities', etc., it works fine.

## Your Environment

- Docusaurus version used: 2.0.0-alpha.69
- Environment name and version: Node v12.18.1, Yarn v1.19.1
- Operating system and version: Windows 10

**Comment by slorber** [comment]
> this time it can't run.

What do you mean exactly? 
Site can't start due to a stacktracek? 
Site behaves unexpectedly?

---

Will have to check ReactRouter behavior, but maybe this route declaration also catch `/community-2` path?

```
  {
    path: '/community',
    component: ComponentCreator('/community', 'c8a'),
    routes: [...],
  },
```

**Comment by tomchen** [comment]
I mean `yarn start` fails (it actually freezes at 69%), showing:
```
i ｢wds｣: Project is running at http://localhost:3001/
i ｢wds｣: webpack output is served from /
i ｢wds｣: Content not from webpack is served from C:\Users\Chen\website
i ｢wds｣: 404s will fallback to /index.html
(node:16464) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open 'C:\Users\Chen\website\.docusaurus\docusaurus-plugin-content-doc
s\community\site-community-2-resources-md-70c.json'
(node:16464) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a cat
ch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unh
andled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:16464) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate
the Node.js process with a non-zero exit code.
(node:16464) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open 'C:\Users\Chen\website\.docusaurus\docusaurus-plugin-content-doc
s\community\site-community-2-support-md-2dd.json'
(node:16464) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a cat
ch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unh
andled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:16464) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open 'C:\Users\Chen\website\.docusaurus\docusaurus-plugin-content-doc
s\community\site-community-2-team-mdx-cbf.json'
(node:16464) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a cat
ch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unh
andled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
```

**Comment by slorber** [comment]
Thanks for the report, was able to get this fixed. It's an edge case due to webpack loader `include: '/community'` catching docs of the 2nd instance too (`'/community-2/myDoc.mdx'`)

Adding a trailing slash to the webpack loader include pattern ensure better sandboxing of the 2 docs mdx webpack loaders
