### ISSUE TITLE
Top nav could be pushed to the next row in some screen width

### ISSUE THREAD

**Issue by tomchen** [facebook/docusaurus#3820]
## 🐛 Bug Report

If the top nav bar has too many items / too much text, it could be pushed to the next row on tablet / old desktop screen that is around 1024px wide, which is wider than the threshold the top nav bar is shrunk into a hamburger button.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?
Yes

## Real-life Demo

Width: 1024px

https://v2.docusaurus.io/docs/

![docusaurus](https://user-images.githubusercontent.com/529949/100264246-e02e0900-2f4e-11eb-81a6-539911a3f633.png)

https://reactnative.dev/docs/getting-started

![react-native](https://user-images.githubusercontent.com/529949/100264264-e58b5380-2f4e-11eb-9be6-8c3b486cc49a.png)

https://react-redux.js.org/introduction/quick-start

![react-redux](https://user-images.githubusercontent.com/529949/100264279-ea500780-2f4e-11eb-8012-449ba78e34a4.png)

https://redux.js.org/introduction/getting-started

![redux](https://user-images.githubusercontent.com/529949/100264295-ef14bb80-2f4e-11eb-9531-dbd0cd6cf828.png)

(Good for Redux, it looks like they fixed it. However, there is a minor problem: the viewport is not fit and is wider than the screen, showing the horizontal scrollbar)

## Comment

Maybe get the the top bar's real width after it is loaded, then make some calculation and change the threshold screen width the top nav is shrunk?

## Your Environment

- Docusaurus version used: V2
- Environment name and version: Chrome 86 and Firefox 82
- Operating system and version: Windows 10 Desktop

**Comment by slorber** [comment]
Yes this is an issue we should figure out. The simplest solution for now is to reduce the number of navbar items 😅 (or label lengths, we mostly have the issue due to the "unreleased" label)

> Maybe get the the top bar's real width after it is loaded, then make some calculation and change the threshold screen width the top nav is shrunk?

Any JS-based solution would produce flickering on page load, as the layout will update just after React hydration, which wouldn't be a good UX

**Comment by Simek** [comment]
Hi @tomchen, after the latest CSS tweaks the React Native website should now look like this on your device:

<img width="768" alt="Untitled2" src="https://user-images.githubusercontent.com/719641/100613231-7ded5380-3314-11eb-9cc2-79f1d87ede22.png">

Please confirm that the overflow issue has been fixed for you and remember to reset the local cache (Ctrl+Shift+R). 🙂

**Comment by tomchen** [comment]
> Yes this is an issue we should figure out. The simplest solution for now is to reduce the number of navbar items 😅 (or label lengths, we mostly have the issue due to the "unreleased" label)
> 
> > Maybe get the the top bar's real width after it is loaded, then make some calculation and change the threshold screen width the top nav is shrunk?
> 
> Any JS-based solution would produce flickering on page load, as the layout will update just after React hydration, which wouldn't be a good UX

Actually a JS-based solution should work with CSS, it would fix the problem only when there is a problem: the vast majority of the user with a non tablet screen will be unaffected, the tablet user who has the problem, will indeed see the flickering before seeing the correct page, but "flickering then seeing the correct page" is better than showing the ugly misplaced top nav menu. And it's SPA, user only see the flickering once at the beginning, not once "every page".

The solution could be something like:  
If `document.getElementsByClassName('navbar__items--right')[0].getBoundingClientRect().top` is 7.5, 8, 8.5 or something, then it's all good. If it's 42, 45 or something like that big, then the top nav should shrunk and show a hamburger button.

Docusaurus can also leave a threshold width variable or something in config file that's strongly recommended to set by Docusaurus user. Yes, this is always better and reliable than the JS solution. The flickering runtime JS solution is just a fail-safe.

**Comment by tomchen** [comment]
> Hi @tomchen, after the latest CSS tweaks the React Native website should now look like this on your device:
> ...
> Please confirm that the overflow issue has been fixed for you and remember to reset the local cache (Ctrl+Shift+R). 🙂

@Simek Yes thank you, React Native website is good now.
