### ISSUE TITLE
Version `next` for package `@docusaurus/core` could not be found

### ISSUE THREAD

**Issue by yahu1031** [facebook/docusaurus#3821]
## 🐛 Bug Report

Hello there, 

When i used to use `2.0.0-alpha.66`, Everything was good. But, when i have upgraded to `2.0.0-alpha.68` manually, then this issue started. This issue didn't effect my project. But, IDK this will give me a major issue or not but as a perfectionist 🤣 i would like to run my app without any errors. And this continues to `2.0.0-alpha.69` too. I though this will get a fix on next update but didn't. So I would like to raise an issue. Please do close and if this is a duplication, cause I couldn't able to find any issue similar to this.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

yes

## To Reproduce

1. manually change version from`2.0.0-alpha.66` to `2.0.0-alpha.66+`
```json
"dependencies": {
  "@docusaurus/core": "^2.0.0-alpha.69",
  "@docusaurus/preset-classic": "^2.0.0-alpha.69",
  //…//
}
```
2. Remove node_modules folder and run `npm i`
3. Run the project `F5`(VSCode). terminal looks obsoletely fine. But, not the debug console. Here is that looks like(I'm pointing the issue)

```console

> free-learn@1.0.0 start D:\Programs\JavaScript\NodeJS\Free Learn
> docusaurus start

c:\Program Files\NodeJS\node_modules\npm\node_modules\npm-lifecycle\index.js:255
Starting the development server...
node_modules/@docusaurus/core/lib/commands/start.js:34

<--- From Here --->
VersionNotFoundError: Version `next` for package `@docusaurus/core` could not be found
    at packageJson (d:\Programs\JavaScript\NodeJS\Free Learn\node_modules\package-json\index.js:87:23)
    at processTicksAndRejections (<node_internals>/internal/process/task_queues.js:93:5)
    at async lastestVersion (d:\Programs\JavaScript\NodeJS\Free Learn\node_modules\latest-version\index.js:5:20)
    at async UpdateNotifier.fetchInfo (d:\Programs\JavaScript\NodeJS\Free Learn\node_modules\update-notifier\index.js:105:18)
    at async D:\Programs\JavaScript\NodeJS\Free Learn\node_modules\update-notifier\check.js:13:17 {name: 'VersionNotFoundError', stack: 'VersionNotFoundError: Version `next` for pack…n\node_modules\update-notifier\check.js:13:17', message: 'Version `next` for package `@docusaurus/core` could not be found'}
<--- Till Here --->

node_modules/update-notifier/check.js:26
Docusaurus website is running at: http://localhost:3000/
node_modules/@docusaurus/core/lib/commands/start.js:46
i ｢wds｣: Project is running at http://localhost:3000/
node_modules/webpack-log/src/loglevel/PrefixFactory.js:55
i ｢wds｣: webpack output is served from /
node_modules/webpack-log/src/loglevel/PrefixFactory.js:55
i ｢wds｣: Content not from webpack is served from D:\Programs\JavaScript\NodeJS\Free Learn
node_modules/webpack-log/src/loglevel/PrefixFactory.js:55
i ｢wds｣: 404s will fallback to /index.html
```

## Expected behavior

```console

> free-learn@1.0.0 start D:\Programs\JavaScript\NodeJS\Free Learn
> docusaurus start

 c:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js
Starting the development server...            node_modules/@docusaurus/core/lib/commands/start.js
Docusaurus website is running at: http://localhost:3000/          node_modules/@docusaurus/core/lib/commands/start.js
i ｢wds｣: Project is running at http://localhost:3000/            node_modules/webpack-log/src/loglevel/PrefixFactory.js
i ｢wds｣: webpack output is served from /                               node_modules/webpack-log/src/loglevel/PrefixFactory.js
i ｢wds｣: Content not from webpack is served from D:\Programs\JavaScript\NodeJS\Free Learn                  node_modules/webpack-log/src/loglevel/PrefixFactory.js
i ｢wds｣: 404s will fallback to /index.html                          node_modules/webpack-log/src/loglevel/PrefixFactory.js
```

App must run without that error.

## Actual Behavior

But the app still runs with that error.

## Your Environment

- Docusaurus version used: 2.0.0-alpha.69
- Environment name and version (e.g. Chrome 78.0.3904.108, Node.js 10.17.0): Microsoft Edge V-87.0.664.47, node - v14.15.1
- Operating system and version (desktop or mobile): Windows 10 Home Single Language (20H2 update)

## Reproducible Demo

[Video link Here](https://drive.google.com/file/d/1nSx-hS4rjmJEUyJ-ZOeDrTVXIUBOakhe/view?usp=sharing), 
[docusaurus.config.js](https://sourceb.in/eSsrsl0r4R)

Regards.

**Comment by slorber** [comment]
Thanks, will be fixed by https://github.com/facebook/docusaurus/pull/3824
