### ISSUE TITLE
Search on v2.docusaurus.io returns no results

### ISSUE THREAD

**Issue by beeradley** [facebook/docusaurus#3826]
## 🐛 Bug Report

On https://v2.docusaurus.io, run a search. No results come back.

### Have you read the [Contributing Guidelines on issues]

Yes

## To Reproduce

- Visit https://v2.docusaurus.io.
- Search for "markdown"
- No results come back

## Expected behavior

Results come back

<img width="588" alt="Screen Shot 2020-11-26 at 10 23 23 AM" src="https://user-images.githubusercontent.com/46536855/100379159-a94d0700-2fd1-11eb-8d23-53216890b348.png">

## Actual Behavior

No results come back

## Your Environment

- macOS 10.15.7
- Tried in Safari, Chrome, and Firefox

## Reproducible Demo

Search on https://v2.docusaurus.io

**Comment by tomchen** [comment]
Yes me too I found the search completely unusable today. And I think it worked well yesterday.

**Comment by slorber** [comment]
thanks, should be fixed very soon
