### ISSUE TITLE
Missing doctype on pages

### ISSUE THREAD

**Issue by Tonours** [facebook/Docusaurus#383]
### Is this a bug report?

Yes, when markdown files are generated to html one we expect that it will include a doctype for the generated file.

### Environment

**OS:** OSX 10.12.6
**Node:** 8.9.3
**Npm:** 5.5.1
**Yarn:** 1.3.2

### Steps to Reproduce

1. Clone Docusaurus repository
2. Go to `./website` run `yarn install && yarn build`
3. Go to `./website/build/*.html`  

### Expected Behavior

When build markdown to html files, html files should have a doctype.

### Actual Behavior

When markdown files are generated to html one we expect that it will include a doctype for the generated file.

### Reproducible Demo

Go to [https://docusaurus.io/](https://docusaurus.io/) and view source.

**Comment by Tonours** [comment]
Hi ! 
As i have time today, i have made a pull-request for this #382 :-)

**Comment by JoelMarcey** [comment]
@Tonours Hi. I debated whether to call this a bug or feature request -- called it a bug. I know your PR has been sitting around for a while, but I am still debating whether there is a cleaner way we can accomplish it. But, maybe we just have to go with it.

**Comment by yangshun** [comment]
Closed by #566
