### ISSUE TITLE
Markdown Header Anchor Links do not work for Unicode chars

### ISSUE THREAD

**Issue by alexk111** [facebook/docusaurus#3843]
## 🐛 Bug Report

Markdown headers have an anchor link for navigating to that specific header via URL.

It does work when the header consists of English letters. However it stops working if you type it in Russian and try to navigate to the header from another docs page. Navigation via the TOC works without issues. It only happens when navigating between docs pages.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## To Reproduce

1. Create two pages:
    - page1.md:
        ```markdown
        PUT
        SOME
        TEXT
        HERE

        ## Редактор

        PUT
        MORE
        TEXT
        HERE
        ```
    - page2.md:
        ```markdown
        [Click here](./page1#редактор) to navigate to a header on another page
        ```
2. Open the `page2` page
3. Click the `Click here` link

## Expected behavior

The page page1 is opened and scrolled to the header

## Actual Behavior

The page page1 is opened but **not** scrolled to the header

## Your Environment

- Docusaurus version used:
    - "@docusaurus/core": "2.0.0-alpha.66"
    - "@docusaurus/preset-classic": "2.0.0-alpha.66"
- Environment name and version (e.g. Chrome 78.0.3904.108, Node.js 10.17.0):
    - Tried in Chrome, Firefox, Opera
- Operating system and version (desktop or mobile):
     - desktop

**Comment by lex111** [comment]
This should be fixed in 2.0.0-alpha.**68**, please try this version and then let us know if it helped you.

**Comment by alexk111** [comment]
Updated to the latest 2.0.0-alpha.69. Seems fixed, but now it doesn't show the `#` links when hovering the headers inside a page. And TOC stopped highlighting items. Is there some new mode added to Docusaurus 2?

**Comment by lex111** [comment]
Weird, do you encounter these problems on https://v2.docusaurus.io/ (it uses latest version)? It would be nice to have a reproducible repo or live demo. Try also running `yarn clear` before building the site after upgrading to newest version.

**Comment by alexk111** [comment]
Hm. No problems on the v2.docusaurus website. Will try `yarn clear` and research the issue, then either post an update on what was the source of the issue or provide a reproducible repo.

**Comment by alexk111** [comment]
I have "react" and "react-dom" in deps. `yarrn upgrade --latest` upgraded them from `^16.8.4` to `^17.0.1` and solved the issue.

@lex111 Thanks for your help!
