### ISSUE TITLE
Ascidocs support

### ISSUE THREAD

**Issue by wtrocki** [facebook/docusaurus#3845]
## 🚀 Feature

Would docusaurus support Ascidocs in the near future? 
There are a couple of rendering engines available that could make ascidocs working alongside markdown engnes. Would the core team consider external contributions to support ascidocs?

Creating for general context.

**Comment by slorber** [comment]
Hi,

I'm not familiar with AsciiDoc,

Can you explain more about how this would work, and what benefits it would bring to Docusaurus?

**Comment by wtrocki** [comment]
Generally, it is yet another format for writing documentation. Supported by github as well. 
Ascidocs has more rich schema giving developers more options to properly represent some items. 

More info here:
https://asciidoctor.org/docs/asciidoc-vs-markdown/#graduating-to-asciidoc

This request is not about replacing markdown with ascidocs but more about seeing if there is actually a possibility to add it to the core (as it is possible to hack it outside the docusaurus at the moment.

**Comment by slorber** [comment]
> Ascidocs has more rich schema giving developers more options to properly represent some items.

Do you have specific examples in mind, that for you are not possible to achieve with the plain power of MDX or remark plugins?

> more about seeing if there is actually a possibility to add it to the core

Actually, I wanted you to explain me about that 😅 

How do you see us using AsciiDoc exactly? What would the system/workflow/api look like in an ideal world for you?

**Comment by wtrocki** [comment]
The general idea for docusaurus is that it works with Markdown files put into doc folder than later can be processed using MDX etc.
There is no obvious functional problem with markdown itself and adding ascidocs would be more like adding additional language support etc.

There are specialized documentation engines for asciidocs out there. 
For example https://antora.org

**Comment by slorber** [comment]
@wtrocki I understand that, but if you feel you can achieve anything you currently want using MD/MDX/remark, why do you push for this particular solution exactly? Would you actually use it if we build it, and why?

We can support many things out of the box, but it adds a maintenance burden to Docusaurus, so if we add such things, we should rather be sure in the first place that users will actually use it, and that it permits new things that are currently not possible to achieve.

For this work to be prioritized, we'd rather have an exhaustive list of AsciiDoc features that are not supported (or hard to achieve) by Docusaurus in the first place to see if there's a possible return on investment.

**Comment by wtrocki** [comment]
I will check MDX/remark and see how much effort will be required to put ascidocs support. 
It is good to close issue from my side.

**Comment by slorber** [comment]
Let's close for now, but if you can formulate better what you expect Docusaurus to do and why, let's revisit this in the future.
