### ISSUE TITLE
Nested items in sidebar (make more accessible)

### ISSUE THREAD

**Issue by filippo-fonseca** [facebook/docusaurus#3855]
## 💥Nested Sidebar Items Proposal

Integrate the ability to easily house nested sub-menus in the sidebar on Docusaurus. Although this is already a possibility, it is not yet easily accessible in my point of view and must be addressed.

An example is being able to make a nested object in `sidebars.js` and for the sidebar to automatically create a new, nested menu item that can hold sub-items. Think of it like a code folder structure: You can have a main folder, such as `src`, and within it have files. Besides files, however, you can have folders for respective subtopics that themselves are reasonable large.

**Example on Docusaurus (of how it could potentially look like on someone's site):**

```js
module.exports = {
  someSidebar: {
    Setup: ["doc1", "getting-started"],
    Documentation: [
      "perfsquare",
      "diffofsquares",
      "sine",
      "cosine",
      "tangent",
      "number-exponent",
      "circcalc",
      "degtorad",
      "radtodeg",
      "data",
      NestedObject: {
         "file",
         "file-2",
      }
    ],
    Resources: ["discord-server", "github-md"],
  },
};
```

Once again, it may be that this is already possible, I've just not found it to be available this way. Let me know if I'm wrong! 👍 

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes. 👍

**Comment by slorber** [comment]
Hi,

We already support nested sidebars (resursively), see on our own website: https://v2.docusaurus.io/docs/docs-introduction

![image](https://user-images.githubusercontent.com/749374/100768599-5c1acc00-33fb-11eb-91e1-59582f106f7d.png)


I'm sorry but I don't understand what you mean at all by "easily accessible".

Note: the sidebars file is a regular nodejs file, if you want to generate the sidebars dynamically (by reading folders/files etc) you can already do this by using FS apis. Might be related to https://github.com/facebook/docusaurus/issues/3464 ?

**Comment by filippo-fonseca** [comment]
@slorber Thank you! That's exactly what I was looking for.

In regards to "easily accessible", I think I meant maybe making it clearer in the tutorial out-of-the-box, that's all. Seeing. that it's in the website, however, that might not be necessary.

**Comment by slorber** [comment]
great
if you feel that we can improve this doc, don't hesitate to submit a PR
https://v2.docusaurus.io/classic/docs/docs-introduction/#sidebar

**Comment by filippo-fonseca** [comment]
Will get on that @slorber. Thanks 🙏

**Comment by tisonkun** [comment]
@slorber I don't find how many nested levels is valid for sidebar items. Could you guide me to the correct page? At least 3 levels seem work.

**Comment by slorber** [comment]
We don't have a max nesting level, but make sure to not nest too much otherwise the UI could look weird.
If you tweak the UI to reduce/remove indentation you could support more levels.
