### ISSUE TITLE
Improve SEO

### ISSUE THREAD

**Issue by azz** [facebook/Docusaurus#387]
### Is this a bug report?

`enhancement`.

### Have you read the [Contributing Guidelines](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md)?

👍 

### Issue

Google search results for Prettier could do with some improvement.

#### Short listing

![image](https://user-images.githubusercontent.com/1297597/34756286-ccd38834-f61d-11e7-9556-dffae3ec6dbd.png)

#### Long listing (Requires searching for "prettier.io")

![image](https://user-images.githubusercontent.com/1297597/34756416-cbccb9dc-f61e-11e7-837a-1c28245aa393.png)

I'm not an expert on SEO, but I think there should be an option to set:

* `<meta name="description" content="...">`
* Sitemap (maybe using https://github.com/algolia/algolia-sitemap?)

### Reproducible Demo

Search: https://google.com/search?q=prettier.io
Repo: https://github.com/prettier/prettier
Site: https://prettier.io

**Comment by j-f1** [comment]
> let num = Math.floor (Math.random() * 1E+7).toString().replace ...

That’s definitely not what we’re looking for to describe the playground.

**Comment by JoelMarcey** [comment]
Ok, I am convinced with the random code snippet for the playground 😄

**Comment by amyrlam** [comment]
I'll work on this with @jason-maier. He's new to Docusaurus, but has some SEO experience from his past career!

**Comment by endiliey** [comment]
I think this has been fixed 😄 

You can set your own description meta
`<meta name="description" content="...">`

Refer to https://docusaurus.io/docs/en/api-pages#description-for-pages

Example:
```js
// pages/index.js

const React = require('react');

class Index extends React.Component {
  render() {
    // ... your rendering code
  }
}

Index.description = 'Endilie is an undergraduate student at Nanyang Technological University (2019). He likes to write & code in his free time';
module.exports = Index;
```

Google's result:

<img width="491" alt="google-test" src="https://user-images.githubusercontent.com/17883920/42885385-60c582aa-8ad3-11e8-9fa5-ebdc31da8c1b.PNG">

I'm closing this. Feel free to re-open / create a new issue if needed
