### ISSUE TITLE
Deploy fails with "ERROR: Repository not found." after build.

### ISSUE THREAD

**Issue by TheCynosure** [facebook/docusaurus#3875]
## 🐛 Bug Report

(A clear and concise description of what the bug is)
When I deploy my docusaurus site onto my organizations github I get the following error: 

```
~/catkin_ws/src/nautilus_stack/docs (master) $ GIT_USER=TheCynosure USE_SSH=true yarn deploy
yarn run v1.22.5
$ docusaurus deploy
Deploy command invoked ...
master
git@github.com:ut-amrl/nautilus_stack.git
c737eaac6ff35dcb8b304438cf9897a5900095e0
Creating an optimized production build...

✔ Client
  Compiled successfully in 4.90s

✔ Server
  Compiled successfully in 6.91s


Success! Generated static files in build.

Cloning into 'nautilus_stack-gh-pages'...
ERROR: Repository not found.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Error: Error: git clone failed
    at build_1.build.then (/home/jack/catkin_ws/src/nautilus_stack/docs/node_modules/@docusaurus/core/lib/commands/deploy.js:79:19)
    at process._tickCallback (internal/process/next_tick.js:68:7)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## To Reproduce

1. Create a docusaurus repository inside a subfolder of another repository (Organization repository). For example mine is located  [here.](https://github.com/ut-amrl/nautilus_stack/tree/master/docs)
1. Deploy the site using the command: ```GIT_USER=<Your username> USE_SSH=true yarn deploy```

## Expected behavior

I thought the site would be successfully deployed.

## Actual Behavior

Failure to deploy because of missing repository for cloning into (if I could also get an explanation on what this means then maybe that could shed light on the bug source).

## Your Environment

- Docusaurus version used: 2.0.0-alpha.54
- Environment name and version: Firefox 83, Node v10.19.0
- Operating system and version: Ubuntu 20.04, Desktop.

### Instructions
Listed in To Reproduce section, but if you want to use my repository (you of course cannot deploy to this organization but...)
1. Clone the below repo.
1. ```cd docs```
1. ```yarn```
1. ```GIT_USER=<user> USE_SSH=true yarn deploy```

My repository: [repo]( https://github.com/ut-amrl/nautilus_stack)

More notes that might help:
- __I was able to successfully deploy these docs to my own account__ using a different repository. I simply copied the repository from my private version (the one I was able to deploy) to my new repo and then tried to redeploy (changing the docusaurus.config.js siteName, URL, and baseUrl as needed).
- I have access rights to all repositories on this organization.
- I have tried creating this nautilus_stack-gh-pages repo in the organization, didn't work. Also have created gh-pages branches in the original repo to see if that would help. Lastly, I have tried recopying the site many times but each time it hasn't worked. I properly change the remote URL and delete old git leftovers from the old repo if you were wondering.

**Comment by slorber** [comment]
Hi,

Your organization name looks bad to me. We use this to clone your repo.

![image](https://user-images.githubusercontent.com/749374/101166596-d6845f80-3638-11eb-83ad-0dd4c98240b0.png)

It should be ut-amrl instead
