### ISSUE TITLE
plugin-client-redirects fails on Windows

### ISSUE THREAD

**Issue by saydo17** [facebook/docusaurus#3886]
## 🐛 Bug Report

When building on Windows, the Client Redirect plugin creates an invalid url for the redirect. `/` becomes `%5C`

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## To Reproduce

1. configure redirect from /doc/old to /docs/something/else
1. `yarn build` on windows from powershell
1. Navigate to the `from` route

## Expected behavior

Should redirect to /docs/something/else

## Actual Behavior
 
Redirects to /docs%5Csomething%5Celse/ which does not exist.

## Your Environment

- Docusaurus version used: 2.0.0-alpha.69
- plugin-client-redirect version: 2.0.0-alpha.69
- Environment name and version (e.g. Chrome 78.0.3904.108, Node.js 10.17.0): Node v12.18.0
- Operating system and version (desktop or mobile): Windows 10 Pro 2004, Powershell 5.1.19041.610

## Reproducible Demo

[example repo](https://github.com/saydo17/redirectBug)

**Comment by saydo17** [comment]
Issue seems to be at this call [here ](https://github.com/facebook/docusaurus/blob/08f6734bff3878a0b1e8424c814c1c8a02185f71/packages/docusaurus-plugin-client-redirects/src/writeRedirectFiles.ts#L41)

**Comment by slorber** [comment]
Thanks for reporting

I don't have windows so any help to fix this is welcome 😅
