### ISSUE TITLE
GITHUB PAGES - Deploy Issue

### ISSUE THREAD

**Issue by ashu231083** [facebook/docusaurus#3887]
## 🐛 Bug Report

(A clear and concise description of what the bug is)

### Have you read the [Contributing Guidelines on issues]fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Error: Error: git clone failed
    at runDeploy (/home/runner/work/xxxxxx/xxxxxx/xxxxxx/node_modules/@docusaurus/core/lib/commands/deploy.js:86:19)
Error: Process completed with exit code 1.

**Comment by ashu231083** [comment]
I have fixed issue Deploy in local machine to GIT PAGES.
Change manually deploy.js file and Deploy with below command. 
GIT_USER=<GITHUB_USERNAME> yarn deploy

Change in deploy.js
*OLD*
const nonSshRemoteBranch = `https://${gitCredentials}@${githubHost}/${organizationName}/${projectName}.git`; 
*NEW*
const nonSshRemoteBranch = `https://${githubHost}/${organizationName}/${projectName}.git`;

**Comment by slorber** [comment]
Hi,

You can either submit a PR with your change, or use patch-package to temporarily patch your issue with Docusaurus in your own repo.

Not sure yet, but this code works for many users, so I think it's strange if it fails only for you.

Have you actually replaced the github username with your real one?

You are not supposed to run `GIT_USER=<GITHUB_USERNAME> yarn deploy`, but run `GIT_USER=ashu231083 yarn deploy` instead.

**Comment by slorber** [comment]
Note: I  added more logs to the deploy command recently.  It's not released yet but if you use docusaurus@canary you should get the new code  running locally

**Comment by OverloadedOrama** [comment]
I am receiving the same error in my [repository](https://github.com/Orama-Interactive/Pixelorama-Docs). I followed the steps from the [docs](https://v2.docusaurus.io/docs/deployment#triggering-deployment-with-github-actions) for the SSH key. Is this a bug in Docusaurus or am I doing something wrong?

**Comment by lex111** [comment]
@ashu231083 @OverloadedOrama apparently this was fixed in #4263, so I'm going to close this issue. But feel free to write about deployment issues if they arise.
