### ISSUE TITLE
How to bind a sidebar to a given top nav section

### ISSUE THREAD

**Issue by ArtFlag** [facebook/docusaurus#3893]
## 📚 Documentation

We lack documentation on how to bind new sidebars to new top nav sections.

For example, the docusaurus v2 docs have `docs` and `API` in the top nav. Each has a sidebar of its own. 
How to bind `sidebar for docs` to `docs` and `sidebar for API` to `API`?

I managed to make mine work but I'm not sure how.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

yes

**Comment by slorber** [comment]
Hi,

You don't bind a sidebar to the navbar, you bind a doc, but this doc is part of a sidebar, and we add a class when the doc's sidebar is browsed to give it a tab-like behavior.

It's documented here:

https://v2.docusaurus.io/docs/api/themes/configuration/#navbar-doc-link

If you feel we can improve the API/doc for that feature, don't hesitate to send a PR

**Comment by ArtFlag** [comment]
I see! That was not obvious to me, thanks for clarifying. 

I'll send out a PR during the week to give more visibility to the `Sidebar` section (it doesn't appear in the sidebar of the current docs, which a is a bummer because TOCs are essential in docs) and I'll rework the content to make things clearer.
