### ISSUE TITLE
How to link a static HTML file not generated by Docusaurus

### ISSUE THREAD

**Issue by ArtFlag** [facebook/docusaurus#3894]
## 📚 Documentation

The docs mention how to link to a page (js/md), a blog, etc, but not how to link to static HTML page that was not generated by Docusaurus. 

Is there a way to do this?

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

**Comment by slorber** [comment]
Hi,

If you use an absolute url, it will use regular HTML server-side navigation (no html5 `history.push()` used by SPA routers).

For internal URLs that are not part of the SPA, for example a HTML page put in /static/myPage.html you can use the `pathname://` protocol, like `[myPage](pathname:///myPage)` or `<Link to="pathname:///myPage">`

The `pathname://` protocol is not documented on purpose as it's an escape hatch. It's not a std solution and I'm not sure yet it's the final API we want to use to solve this usecase.

Does it answer your question?

**Comment by ArtFlag** [comment]
Yes, thanks a lot!

**Comment by henrycity** [comment]
> `pathname://` protocol

I am not sure if I get what you mean. I am trying to serve a static website with docusaurus and the file path is `/static/admin/index.html`. What should I do in this case?

I want the `admin/index.html` to load when I try to navigate to `https://mywebsite.com/admin`.

**Comment by slorber** [comment]
@henrycity  

> I am not sure if I get what you mean. I am trying to serve a static website with docusaurus and the file path is /static/admin/index.html. What should I do in this case?
> I want the admin/index.html to load when I try to navigate to https://mywebsite.com/admin.


You don't have to do anything in principle, this should work automatically for most hosting solutions and is not really related to Docusaurus. Docusaurus is only responsible for creating HTML files, not serving them. 

Docusaurus copies `website/static/admin/index.html` to `website/build/admin/index.html`

We provide `docusaurus serve` for convenience, and it would serve `website/build/admin/index.html` at `/admin`. Other hosting solutions should have similar behavior, and might eventually add an extra trailing slash (take a look at https://github.com/slorber/trailing-slash-guide). 

---

We have an example in production on a test page here:

- Source page: https://docusaurus.io/tests/pages/markdown-tests#linking-to-non-spa-page-hosted-within-website
- Link target: https://docusaurus.io/dogfooding/javadoc
- Link: `[link](pathname:///dogfooding/javadoc)`
- Static file: `docusaurus/website/static/dogfooding/javadoc/index.html`

---

Now if you want all routes `/admin/*` to serve `/admin/index.html`, this is a totally different story, and you'll have to configure rewrite rules on your host (each has a different config to do so, and you'll have to refer to their doc). 

On Netlify it would require using a `_redirects` file with a rule like:

```
/admin/*         /admin           200
```

**Comment by henrycity** [comment]
> @henrycity
> 
> > I am not sure if I get what you mean. I am trying to serve a static website with docusaurus and the file path is /static/admin/index.html. What should I do in this case?
> > I want the admin/index.html to load when I try to navigate to https://mywebsite.com/admin.
> 
> You don't have to do anything in principle, this should work automatically for most hosting solutions and is not really related to Docusaurus. Docusaurus is only responsible for creating HTML files, not serving them.
> 
> Docusaurus copies `website/static/admin/index.html` to `website/build/admin/index.html`
> 
> We provide `docusaurus serve` for convenience, and it would serve `website/build/admin/index.html` at `/admin`. Other hosting solutions should have similar behavior, and might eventually add an extra trailing slash (take a look at https://github.com/slorber/trailing-slash-guide).
> 
> We have an example in production on a test page here:
> 
> * Source page: https://docusaurus.io/tests/pages/markdown-tests#linking-to-non-spa-page-hosted-within-website
> * Link target: https://docusaurus.io/dogfooding/javadoc
> * Link: `[link](pathname:///dogfooding/javadoc)`
> * Static file: `docusaurus/website/static/dogfooding/javadoc/index.html`
> 
> Now if you want all routes `/admin/*` to serve `/admin/index.html`, this is a totally different story, and you'll have to configure rewrite rules on your host (each has a different config to do so, and you'll have to refer to their doc).
> 
> On Netlify it would require using a `_redirects` file with a rule like:
> 
> ```
> /admin/*         /admin           200
> ```

Thanks for the detailed answer. I actually use AWS S3 to host it and manage to deploy it.
