### ISSUE TITLE
That does not seem good enough to me, it looks like you forgot to add an example after the `:` ?

### ISSUE THREAD

**Issue by somsen1988** [facebook/docusaurus#3897]
That does not seem good enough to me, it looks like you forgot to add an example after the `:` ?

_Originally posted by @slorber in https://github.com/facebook/docusaurus/pull/3888#r537580261_

**Comment by slorber** [comment]
???

**Comment by Kampoz825** [comment]
> That does not seem good enough to me, it looks like you forgot to add an example after the `:` ?
> 
> _Originally posted by @slorber in [#3888 (comment)](https://github.com/facebook/docusaurus/pull/3888#r537580261)_
