### ISSUE TITLE
Feature request: translatable siteConfig.tagline

### ISSUE THREAD

**Issue by chenglou** [facebook/Docusaurus#390]
### Is this a bug report?

Yes and no

### Have you read the [Contributing Guidelines](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md)?

Yes

### Expected Behavior

siteConfig's key `tagline` should be translatable

### Actual Behavior

It's not (I think).

**Comment by JoelMarcey** [comment]
@chenglou Hi. Agree, most any string should be translatable.

**Comment by endiliey** [comment]
Hi 😁,

I think tagline is being translated as of now.
Related code:
https://github.com/facebook/Docusaurus/blob/f33d977d1aa3bfc12296bf6522b1676e02adc1ca/lib/write-translations.js#L39-L43

Googled reasonml.github.io in which the title is `title ● tagline`. We can see that it's translated

![screenshot_20180618-144922](https://user-images.githubusercontent.com/17883920/41522293-e2fb03be-7307-11e8-80e4-03d064d445f1.png)

I am closing this. Feel free to re-open or Let me know if you need assistance 😀
