### ISSUE TITLE
Usage of SVGO breaks SVG output in my docs.

### ISSUE THREAD

**Issue by Dudrie** [facebook/docusaurus#3901]
## 🐛 Bug Report

Upgrading from `alpha.66` to `alpha.69` does break my SVG icons (as mentioned in https://github.com/facebook/docusaurus/pull/3691#issuecomment-734921324). 

With `alpha.66` the SVG output that got produced was:

```html
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="24" height="24" viewBox="0 0 24 24">...</svg>
```

However, with the version `alpha.69` the output is:

```html
<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24">...</svg>
```

The SVG icons are used "inline" (through a custom JSX component).

The code inside the `mdx` file for the above (extracted from the real file and added line breaks to make it readable inside this issue block):

```mdx
import IconInText from '../../src/components/icon-in-text/IconInText';
import MenuIcon from './assets/icons/dots-vertical.svg';

## Overview

The overview page shows all students saved in the system and their current schein status. 
As an adminstrator you can edit or delete students by clicking on the menu button <IconInText icon={MenuIcon} /> and selecting the desired option. 
You can access the [_Student info page_](./student_info) by clicking on the "Information" button. 
Furthermore, you can search for a specific student by using the search bar at the top. 
For more information see the [_Student Management page_](./student_management).
```

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes 😀

## To Reproduce

1. Update to `alpha.69`.
1. Start dev-server and open the documentation on localhost.
1. Visit a page with one of the icons.
1. See that the icons are miss aligned.

## Expected behavior

The new version should show the icons in the same way as the old one did.

## Actual Behavior

Icons / generated SVG are broken. More precisely: While the container (circle) is scaled properly to match the text that SVG icons itself are not affected by the scaling due to the missing `viewBox` attribute (even though the SVG files them self contained this attribute).

|alpha66|alpha69|
|---- |----|
| ![alpha 66](https://user-images.githubusercontent.com/17962500/101686829-e00f2c80-3a69-11eb-9b77-89c1fbacb653.png)|![alpha 69](https://user-images.githubusercontent.com/17962500/101686834-e1405980-3a69-11eb-9757-1c816251153a.png)|

## Your Environment

- Docusaurus version used: 2.0.0-alpha.69
- Environment name and version: Chrome (87.0.4280.88), Node.js (v14.13.1)
- Operating system and version (desktop or mobile): Win10, desktop

## Reproducible Demo

The actual code lives in a monorepo inside the `docs` folder: https://github.com/Dudrie/Tutor-Management-System/tree/update-docusaurus/docs

The selected branch of the link is the one if the `alpha.69` version used. If necessary I can extract the docs from the monorepo and move it to a different repository it that is easier for you.

**Comment by slorber** [comment]
Thanks

I don't see this file in your site:

```
import MenuIcon from './assets/icons/dots-vertical.svg';
```

Can you give me the link, so that I can see the real/exact SVG content? (probably useless but still better to have a 100% reprocase, just in case)

**Comment by slorber** [comment]
Related to https://github.com/facebook/docusaurus/pull/3691

**Comment by slorber** [comment]
As far as I understand:
- We can pass Webpack loader options as querystring: https://blog.johnnyreilly.com/2017/01/webpack-configuring-loader-with-query.html
- The options are the ones of SVGR: https://react-svgr.com/docs/webpack/

What I suggest:
- Extract this SVGR loader from core and create a SVGR plugin
- Let the user pass his own config as an object 
- Apply existing querystring config by default for retrocompatibility
- Add this svgr plugin to the themes by default, with a svgr attribute for configuring it


This would allow you to opt-out of SVGO using `{svgr: {svgo: false}}` on the classic theme config


        {
          test: /\.svg$/,
          use: '@svgr/webpack?-prettier,+svgo,+titleProp,+ref![path]',
        },

**Comment by Dudrie** [comment]
> Thanks
> 
> I don't see this file in your site:
> 
> ```
> import MenuIcon from './assets/icons/dots-vertical.svg';
> ```
> 
> Can you give me the link, so that I can see the real/exact SVG content? (probably useless but still better to have a 100% reprocase, just in case)

Link to the file:

https://github.com/Dudrie/Tutor-Management-System/blob/update-docusaurus/docs/docs/handbook/assets/icons/dots-vertical.svg
