### ISSUE TITLE
Feature: Arrow keys to navigate

### ISSUE THREAD

**Issue by robertopc** [facebook/Docusaurus#391]
Arrow left to previous page.
Arrow right to next page.

**Comment by brentvatne** [comment]
imo this isn't worth adding to docusaurus itself. you can implement this pretty easily with just adding a custom script to your page

**Comment by JoelMarcey** [comment]
@robertopc Thank you for the feature request. But I agree that this may be getting way to specific of a use case that may not be of general use to the Docusaurus users. Adding this as a custom script is a good idea.

I will say that I can see a more generalized implementation around accessibility that could be set in `siteConfig.js`, but not just this alone.
