### ISSUE TITLE
Add Additional Indentation Levels beyond H3

### ISSUE THREAD

**Issue by eightbit** [facebook/docusaurus#3910]
I appreciate this great app!
Please consider adding the capability to add additional indentation levels beyond H3. I've seen this issue addressed in other comments/issues. In our case we'd simply need a global setting for the depth.

FWIW, when I write documentation, which I've been doing in MS Word for many years, I reserve the use of Headers for building a navigable outline of a document. Other semantic elements are handled by non-outline-related styles.

Thanks for your consideration!

**Comment by slorber** [comment]
Hi

closing as duplicate of https://github.com/facebook/docusaurus/issues/2700
