### ISSUE TITLE
[v2] Keeping or replacing routesLoaded lifecycle

### ISSUE THREAD

**Issue by jonthomp** [facebook/docusaurus#3918]
## 🚀 Feature

Keep, or replace, the deprecated `routesLoaded` lifecycle event

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## Motivation

`routesLoaded` provides plugins with data not available in the previous lifecycles.

## Pitch

I have been using the `routesLoaded` lifecycle event to create an Algolia (but not DocSearch) search implementation.

From what I have found this is the only way to get an array of all routes, find and then parse their raw markdown files into Algolia indexable objects.

**Comment by slorber** [comment]
Thanks for letting me know

Is your implementation of Algolia open-source, or can you share it to me somehow so that I understand how you use it?

**Comment by slorber** [comment]
@jonthomp as you did not provide better explanations on your use-case, this lifecycle is being removed by @Josh-Cena here: https://github.com/facebook/docusaurus/pull/7257

Note that `postBuild` also receives the Docusaurus routes, so this should work fine for your use-case

Now is the best time to come up with a great rationale to keep this API and explain why `postBuild` couldn't work

**Comment by slorber** [comment]
@jonthomp without any sign of life and feedback, this feature is being removed
