### ISSUE TITLE
[Feature Request] Root Provider support

### ISSUE THREAD

**Issue by dayhaysoos** [facebook/docusaurus#3919]
https://docusaurus-2.netlify.app/feedback/p/feature-request-root-provider-support

## 🚀 Feature

It would be great to support wrapping providers around the docs site. I would like to use a library called use-shopping-cart and wrap the site in a <CartProvider /> so that state is persisted throughout the entire app.

## Pitch

With the ability to wrap whole providers around the site, you'll be able to share state across the entire docs site which could be really useful as far as interactivity and displaying your libraries features.

For example: use-shopping-cart is a lib that helps with all shopping-cart logic and state. An ideal e-commerce experience would be having the entire shopping cart state available at any given moment, especially for something like displaying cart data and such. Not only would you go to my docusaurus site to read how the lib works, you get to actually interact with it the same way you would any e-commerce site.

**Comment by slorber** [comment]
Will be solved by https://github.com/facebook/docusaurus/pull/3932
