### ISSUE TITLE
redirects plugin adds trailing slash

### ISSUE THREAD

**Issue by Morriz** [facebook/docusaurus#3925]
## 🐛 Bug Report

Redirects with `to:` path NOT containing a trailing slash get a trailing slash appended.

### Have you read the [Contributing Guidelines on issues]
yes

## To Reproduce

1. install `@docusaurus/plugin-client-redirects` plugin
2. add a page `/docs/bla`
3. add this redirect to `docusaurus.config.js`:

```js
    [
      '@docusaurus/plugin-client-redirects',
      {
        [{
          from: ['/docs/blaa'],
          to: '/docs/bla',
        }]
      },
    ],

```

4. `npm run build && npx docusaurus serve`
5. go to `/docs/bla` > no slash appended
6. go to `/docs/blaa` > see the slash appended resulting in `/docs/bla/`

## Expected behavior

the redirect to NOT add a slash

## Actual Behavior

redirect adds a slash

## Your Environment

- Docusaurus version used: 2.0.0-alpha.69
- Environment name and version: Chrome 87.0.4280.88, Node.js 14.15.0:
- Operating system and version (desktop or mobile): OSX

**Comment by slorber** [comment]
Removed the trailing slash as part of https://github.com/facebook/docusaurus/pull/3903
