### ISSUE TITLE
build should fail when broken links found

### ISSUE THREAD

**Issue by Morriz** [facebook/docusaurus#3926]
## 🚀 Feature

I would expect `npm run build` to break upon broken links found, but it just exits with code `0`.

### Have you read the [Contributing Guidelines on issues]
yes

## Motivation

It would not allow publication of broken docs (doh!)

## Pitch

Self explanatory

**Comment by Morriz** [comment]
I think this should throw an error code when `CI=true`

**Comment by slorber** [comment]
That's already the case and we even have config for that.

https://v2.docusaurus.io/docs/docusaurus.config.js/#onbrokenlinks

100% sure it works if you use latest Docusaurus 2 versions.

**Comment by Morriz** [comment]
Pfff...totally overlooked. Thanks!
