### ISSUE TITLE
Adaptive Navbar docsVersionDropdown for multi-SDK doc websites

### ISSUE THREAD

**Issue by sidvenu** [facebook/docusaurus#3930]
## 🚀 Feature

If a Docusaurus project has documentation for 2 or more SDKs (which is supported in the latest releases thanks to multi-doc-plugin support - see https://github.com/facebook/docusaurus/issues/2528#issuecomment-674112728), the Navbar `docsVersionDropdown` should have the ability to display the versions of the SDK page the user is currently in.

Suppose the user is in the page of Android SDK Docs. The Navbar should display versions of Android SDK. If they go to iOS docs, the navbar should now display versions of iOS SDK.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes.

## Motivation

We are a company that has multiple tiers of SDKs that has different versioning timelines.

## Pitch

Having a multi-doc website with a navbar version dropdown that doesn't change according to the SDK you select confuses many people.

The structure of Navbar dropdown right now: `{type: "docsVersionDropdown", docsPluginId: "ios"}`
We can have something similar to: `{type: "docsVersionDropdown", defaultDocsPluginId: "ios", dynamicVersioningChange: true}` for enabling dynamic versioning change according to the SDK docs the user is currently viewing. The `defaultDocsPluginId` can be used for knowing what plugin version to display in non-docs pages like Home, Blogs etc.

## Future Scope

An 'override' parameter in each plugin for choosing which pluginId versioning has to be displayed in the navbar.

**Comment by sidvenu** [comment]
@slorber as discussed in Discord. What do you think of the proposal?

**Comment by slorber** [comment]
What about adding `multiInstance: true` in config so that it adapts?
The `docsPluginId  option` can serve as the default instance if multi-instance support is enabled?

**Comment by sidvenu** [comment]
That makes sense. However, I feel the name `docsPluginId` alone does not explain how it behaves when it is in `multiInstance`. A better name like `defaultDocsPluginId` would give an insight into how it behaves in both cases.

**Comment by StanGirard** [comment]
@sidvenu Have you found any workaround for now to get it working?

**Comment by slorber** [comment]
if anyone has an existing site online with the UX problem, that would likely help to understand better what a solution could look like

**Comment by slorber** [comment]
FYI some idea I have that could also solve this issue: https://github.com/facebook/docusaurus/issues/4389#issuecomment-797522687

**Comment by StanGirard** [comment]
@slorber That is exactly what we are looking for. Thanks for being so pro-active.

**Comment by ngaer** [comment]
Currently could be solved using custom NavbarItem (`src/theme/NavbarItem.js`)
```js
import React from 'react';
import OriginalNavBarItem from '@theme-original/NavbarItem';
import { useLocation }  from '@docusaurus/router';

export default function NavbarItem(props) {
  const { docsPluginId, type } = props
  const { pathname } = useLocation()

  if (type === 'docsVersionDropdown' && pathname.search(new RegExp(`^/${docsPluginId}/`, 'g')) === -1) {
    return null
  }

  return (
    <>
      <OriginalNavBarItem {...props} />
    </>
  );
}
```

**Comment by slorber** [comment]
Thanks @ngaer , looks like a nice temporary workaround

**Comment by iamayushdas** [comment]
> ```js
> docsPluginId
> ```

can you help me in using this

**Comment by Josh-Cena** [comment]
Closing in favor of #4389.

**Comment by randomJoe211** [comment]
> Currently could be solved using custom NavbarItem (`src/theme/NavbarItem.js`)
> 
> ```js
> import React from 'react';
> import OriginalNavBarItem from '@theme-original/NavbarItem';
> import { useLocation }  from '@docusaurus/router';
> 
> export default function NavbarItem(props) {
>   const { docsPluginId, type } = props
>   const { pathname } = useLocation()
> 
>   if (type === 'docsVersionDropdown' && pathname.search(new RegExp(`^/${docsPluginId}/`, 'g')) === -1) {
>     return null
>   }
> 
>   return (
>     <>
>       <OriginalNavBarItem {...props} />
>     </>
>   );
> }
> ```

Hi @ngaer, thank you so much for the workaround! 💐  It really helped. 
One question is that after applying the workaround, the docsVersionDropdown of doc instances that are versioned also disappeared. How can I get them out, and only hide the docsVersionDropdown for the doc instances that are not versioned?

**Comment by randomJoe211** [comment]
Thank you slorber! You are right about creating the if condition that makes sense for my project. I adjusted the condition as follows and it is working well:

```js
if (type === 'docsVersionDropdown'){
  const paths = pathname.split('/')
  if(paths[1]==='myPluginId') {
  return null
  }
}
```

As a workaround, this is good enough. Still, I look forward to a standard feature to resolve this issue.

**Comment by aneesha178** [comment]
> Currently could be solved using custom NavbarItem (`src/theme/NavbarItem.js`)
> 
> ```js
> import React from 'react';
> import OriginalNavBarItem from '@theme-original/NavbarItem';
> import { useLocation }  from '@docusaurus/router';
> 
> export default function NavbarItem(props) {
>   const { docsPluginId, type } = props
>   const { pathname } = useLocation()
> 
>   if (type === 'docsVersionDropdown' && pathname.search(new RegExp(`^/${docsPluginId}/`, 'g')) === -1) {
>     return null
>   }
> 
>   return (
>     <>
>       <OriginalNavBarItem {...props} />
>     </>
>   );
> }
> ```

Hi @ngaer / @randomJoe211 / @slorber , I seem to have a similar requirement. The only difference is I want the Navbar dropdown items to change with the versions. I was wondering if you could help me with the logic here?

I want to customize my Navbar in such a way that, say when versions 1.2.0 and below are viewed, only Dropdown A should be visible. When versions 1.3.0 and above are viewed, Dropdown B or more must be visible.

For clear understanding:
Navbar when browsing version 1.3.0 and above:

![image](https://user-images.githubusercontent.com/78480431/211166923-1c9920cb-2f7e-4849-ac5b-a91d1ce7c5be.png)

Navbar when browsing version 1.2.0 and below:

![image](https://user-images.githubusercontent.com/78480431/211166948-82cb2659-a19d-491a-81d1-2cd61dacf1c9.png)

**Comment by slorber** [comment]
@aneesha178 track https://github.com/facebook/docusaurus/issues/4389 for an upcoming official solution to solve this problem through config files.

Until then I suggest taking a look at CSS classes that we add to the top-level `<html>` element of your Docusaurus site, those classes should help you create CSS selectors that hide/show relevant items depending on context.

`<html class="plugin-docs plugin-id-default docs-version-2.2.0">`

You could for example create selectors like this:

```css
html:not(.docs-version-2.2.0) .myNavbarItem {
  display: none;
}
```

You'd have to assign a custom class like `.myNavbarItem` to the element you want to hide for v2.2.0, this can be provided through navbar item themeConfig className
