### ISSUE TITLE
Passing a plain function as a plugin is ignored silently

### ISSUE THREAD

**Issue by vjpr** [facebook/docusaurus#3934]
## 🐛 Bug Report

Plugins must be paths. If they are functions they are just ignored silently.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes.

## To Reproduce

```js

plugins.push(customWebpackPlugin)

function customWebpackPlugin(context, options) {
  console.log('hi')
  return {
    name: 'custom-webpack-plugin',
    configureWebpack(config, isServer, utils) {
		return {}
    },
  }
}

```

## Expected behavior

`hi` should be printed or a warning shown.

## Actual Behavior

Its not, and there is no warning.

## Your Environment

- Docusaurus version used: 2.0.0-alpha.69
- Environment name and version (e.g. Chrome 78.0.3904.108, Node.js 10.17.0):
- Operating system and version (desktop or mobile):

## Reproducible Demo

(Paste the link to an example repo, including a `siteConfig.js`, and exact instructions to reproduce the issue.)

**Comment by 9oelM** [comment]
Well I'm not sure if something to be validated, but if it needs to be, I guess some improvement could be done at https://github.com/facebook/docusaurus/blob/ad31facb32e1d0645a5c5b3ffad7a8b45ab9e73f/packages/docusaurus/src/server/plugins/init.ts#L54-L61 because this is where Docusaurus initializes plugins. Any thoughts?

**Comment by slorber** [comment]
Agree, that would be more convenient to create a local site plugin.

@9oelM yes that looks like the correct location, probably just need to test if the plugin item is a function and in such case avoid calling require() on it

**Comment by slorber** [comment]
Also, instead of silently ignoring things, it would be better to fail fast and throw an explicit error

**Comment by 9oelM** [comment]
I'll be able to work on this too

**Comment by slorber** [comment]
Let's keep it open because what we want is this:

```js
function MyPlugin() {
  return {name: "my-plugin"}
}

module.exports {
  plugins: [
    MyPlugin,
   [MyPlugin,{}],
  ],
}
```

**Comment by 9oelM** [comment]
Oh. I totally misunderstood. Sorry 😅 I will write another PR.

**Comment by 9oelM** [comment]
@slorber wait, so let me get this right. Sorry about not being able to understand fully on the first grasp. You mean we need to support writing a plugin as a function?

**Comment by sibelius** [comment]
what is the proper way to create a plugin inside a docusaurus project?

right now I have this structure:

- docs
- src/pages

where should I put my custom plugin and how to include in the docusuarus config?

**Comment by slorber** [comment]
You can create `website/sitePlugin.js` and use it in your config `plugins: ['./sitePlugin.js']`

Good example on the RN website: https://github.com/facebook/react-native-website/blob/master/website
