### ISSUE TITLE
Incorrect navbar style with light mode and dark navbar

### ISSUE THREAD

**Issue by LoicPoullain** [facebook/docusaurus#3937]
## 🐛 Bug Report

I noticed some styling issues when using the dark navbar with the light mode. I don't know if some are on purpose.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes.

## To Reproduce

Use this configuration in `docusaurus.config.js`:
```js
module.exports = {
  // ...
  themeConfig: {
    // ...
    colorMode: {
      defaultMode: 'light',
      disableSwitch: true,
      respectPrefersColorScheme: false,
    },
    navbar: {
      // ...
      style: 'dark',
    }
  }
}
```

## Expected / Actual behaviors

**Issue 1: navbar background color**
The navbar background color is not the same one that is being used in the dark mode. Is it on purpose?

_Expected:_

![Capture d’écran 2020-12-16 à 16 22 19](https://user-images.githubusercontent.com/13604533/102594978-3ab62180-4117-11eb-89f8-d1b11150dcd5.png)
Expected color to be `#242526` like `--ifm-background-surface-color` in dark mode.

_Actual:_

![Capture d’écran 2020-12-16 à 16 21 56](https://user-images.githubusercontent.com/13604533/102594985-3ee23f00-4117-11eb-97d1-d73a3500986f.png)

![Capture d’écran 2020-12-18 à 09 57 02](https://user-images.githubusercontent.com/13604533/102595617-2aeb0d00-4118-11eb-94df-5be65b0d0a38.png)

_Current workaround in global CSS file:_
```scss
.navbar--dark {
  --ifm-navbar-background-color: #242526;
}
```

**Issue 2: bad link colors**

Some links are not colored in white when browser the site with a small screen (mobile mode): the menu button and the version dropdown.

![Capture d’écran 2020-12-16 à 16 21 56](https://user-images.githubusercontent.com/13604533/102596210-23783380-4119-11eb-8add-f84c8fb3dbc3.png)
![Capture d’écran 2020-12-16 à 16 22 04](https://user-images.githubusercontent.com/13604533/102596211-2410ca00-4119-11eb-8126-a07005354780.png)

## Your Environment

- Docusaurus version used: 2.0.0-alpha.70 (same issues with alpha.69)
- Environment name and version: Firefox 83.0, Node.js v12.19.1
- Operating system and version: Desktop

## Reproducible Demo

Repo and directory: https://github.com/FoalTS/foal/tree/master/docs
Online website: https://foalts.org

**Comment by LoicPoullain** [comment]
@slorber I tested the changes in beta.1.

The background color has been properly fixed, but the color of the links are still incorrect on mobile (black on black). Could we re-open the issue?

Thank you!

PS: docusaurus is great, keep it up 👍

**Comment by slorber** [comment]
Thanks,re-opened.

**Comment by lex111** [comment]
This is actually fixed, but not work since you specified own color for menu link in your custom styles.

https://github.com/FoalTS/foal/blob/4e755045f96219ff463cfd45038736208696443b/docs/src/css/custom.scss#L104

If you remove this CSS declaration, then link color is correct.

**Comment by slorber** [comment]
@LoicPoullain please try the solution mentioned by @lex111 , we'll re-open again if it still doesn't work but make sure to test with all your customizations removed to be sure it's a Docusaurus issue

**Comment by Josh-Cena** [comment]
This issue is _not_ resolved. On a freshly installed site, the logo title on hover still becomes black, and the "back to main menu" is black as well:

![Test](https://user-images.githubusercontent.com/55398995/135452168-d6aea3cf-7c43-45f6-bd6b-0acaa1b6bd7a.gif)

**Comment by lex111** [comment]
Thanks for reporting this, will be fixed in https://github.com/facebookincubator/infima/pull/179
