### ISSUE TITLE
style guidelines

### ISSUE THREAD

**Issue by wibed** [facebook/docusaurus#3955]
## 📚 Documentation

~~there are infima variables, which are neither documented, nor in the global css file~~
Does the project follow theming guidelines? If so which are these?

example:
--ifm-font-color-base
defines the font color in relation to the theme, not to be found in the documentation nor in the global css file
yet used in default components.

EDIT:
after sorting few of these css variables, it quickly shows that there is not a clear guideline on how
these configurations relate to each other or the project in general.

- naming and with it hierarchy 
which entry has the most prevalence? 
is it footer | background | color?
```
--ifm-color-primary
--ifm-background-color
--ifm-footer-background-color -> --ifm-background-color-footer
```

related issues:
#3522 
#2961

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

yes

**Comment by wibed** [comment]
maybe my shell powers are underwhelming

`find ./docusaurus -type f -exec grep -o '\-\-ifm\(\-[a-z]*\)*' {} \; | sort -u`

but I found 50 unique variables so far.
some of those are chopped up, others are not complete. I am not able to tell the difference so I won't try

--ifm-
--ifm-background-color
--ifm-background-surface-color
--ifm-button-background-color
--ifm-code-font-size
--ifm-color-black
--ifm-color-content
--ifm-color-content-inverse
--ifm-color-content-secondary
--ifm-color-emphasis-
--ifm-color-feedback-background
--ifm-color-primary
--ifm-color-primary-dark
--ifm-color-primary-darker
--ifm-color-primary-darkest
--ifm-color-primary-light
--ifm-color-primary-lighter
--ifm-color-primary-lightest
--ifm-color-secondary
--ifm-color-secondary-darkest
--ifm-color-secondary-lighter
--ifm-color-white
--ifm-container-width
--ifm-font-base-color
--ifm-font-base-color-inverse
--ifm-font-color-base
--ifm-font-color-base-inverse
--ifm-font-color-secondary
--ifm-font-family-base
--ifm-font-family-monospace
--ifm-font-size-base
--ifm-font-weight-bold
--ifm-footer-background-color
--ifm-global-border-width
--ifm-global-radius
--ifm-global-spacing
--ifm-h
--ifm-leading
--ifm-leading-desktop
--ifm-navbar-height
--ifm-navbar-padding-horizontal
--ifm-pre-line-height
--ifm-pre-padding
--ifm-spacing-horizontal
--ifm-tabs-color-active
--ifm-toc-border-color
--ifm-toc-link-color
--ifm-transition-fast
--ifm-transition-timing-default
--ifm-z-index-fixed

**Comment by wibed** [comment]
most confusing are these entries:

```
--ifm-font-base-color
--ifm-font-base-color-inverse
--ifm-font-color-base
--ifm-font-color-base-inverse
```

which seem to describe the same thing but differently

**Comment by wibed** [comment]
updating the command to include numbers

`find ./docusaurus -type f -exec grep -o '\-\-ifm\(\-[a-z0-9]*\)*' {} \; | sort -u`

--ifm-
--ifm-background-color
--ifm-background-surface-color
--ifm-button-background-color
--ifm-code-font-size
--ifm-color-black
--ifm-color-content
--ifm-color-content-inverse
--ifm-color-content-secondary
--ifm-color-emphasis-100
--ifm-color-emphasis-200
--ifm-color-emphasis-400
--ifm-color-emphasis-600
--ifm-color-emphasis-900
--ifm-color-feedback-background
--ifm-color-primary
--ifm-color-primary-dark
--ifm-color-primary-darker
--ifm-color-primary-darkest
--ifm-color-primary-light
--ifm-color-primary-lighter
--ifm-color-primary-lightest
--ifm-color-secondary
--ifm-color-secondary-darkest
--ifm-color-secondary-lighter
--ifm-color-white
--ifm-container-width
--ifm-font-base-color
--ifm-font-base-color-inverse
--ifm-font-color-base
--ifm-font-color-base-inverse
--ifm-font-color-secondary
--ifm-font-family-base
--ifm-font-family-monospace
--ifm-font-size-base
--ifm-font-weight-bold
--ifm-footer-background-color
--ifm-global-border-width
--ifm-global-radius
--ifm-global-spacing
--ifm-h2-font-size
--ifm-h3-font-size
--ifm-leading
--ifm-leading-desktop
--ifm-navbar-height
--ifm-navbar-padding-horizontal
--ifm-pre-line-height
--ifm-pre-padding
--ifm-spacing-horizontal
--ifm-tabs-color-active
--ifm-toc-border-color
--ifm-toc-link-color
--ifm-transition-fast
--ifm-transition-timing-default
--ifm-z-index-fixed

**Comment by slorber** [comment]
Hi @wibed 

We should definitively improve our Infima docs. 
Unfortunately, I'm not really able to answer all these questions right now, but maybe another contributor would.

Can you please open an issue on Infima repo, as it's now open-sourced?

https://github.com/facebookincubator/infima

**Comment by wibed** [comment]
aware about the close relationships between infima and Docusaurus, I deem the poor documentation on infimas side a
whole different story. 

this issue was meant to gather knowledge about all the variables used not the ones available.

**Comment by paulrberg** [comment]
I don't think the list of colors in @wibed's message from above is up-to-date anymore. There are other variables now, such as `ifm-link-color`, which are not there.

Beside looking at the source code, is there another way to find out all the overridable colors in Infima?

**Comment by Josh-Cena** [comment]
@paulrberg for now you can only look at source code or through browser DevTools. In fact I don't even think a lot of the non-global colors are stable.

**Comment by dsousa12** [comment]
Any way to change this variables using sass?

**Comment by CMCDragonkai** [comment]
It is intended for the user to override these colours by creating a custom CSS file with something like:

```
:root {
  --ifm-color-primary: #02243e;
  --ifm-color-primary-light: #78effb;
  --ifm-code-font-size: 95%;
  --ifm-navbar-background-color: #02243e;
  --docusaurus-highlighted-code-line-bg: rgba(0, 0, 0, 0.1);

  --ifm-navbar-link-color: #fff;
  --ifm-navbar-link-hover-color: #fff;

  --ifm-footer-link-hover-color: #fff;
  --ifm-link-hover-decoration: none;

  --ifm-font-family-base: 'Open Sans', sans-serif;
}
```

If so, how does one know which variables to change and which are stable?

**Comment by slorber** [comment]
It's hard for us to document and guarantee all these variables will remain stable, as well as it's hard to guarantee your custom CSS selectors will keep working forever. We need to be able to do changes. 

Whatever is not documented can change someday, and whatever is documented can change in major releases. 
If things change sometimes, it doesn't mean you can't use them.

**Comment by 0ptim** [comment]
Chiming in here. In my opinion, we this topic needs more clarity and I think it would be very beneficial to have a better plan on how to further customize Docusaurus websites. For now, it feels like I have to do quite a bit of reverse engineering whenever I want to adjust styling. Or maybe I'm just missing something?

**Comment by slorber** [comment]
To be clear, we know it's a problem for users and acknowledge it. It doesn't mean we can do something in the short term, we are not a huge team and there are other priorities to work on.

In the meantime, please consider that all undocumented Infima CSS vars are implementation details. You can retro-engineer those to apply customizations, but it's your responsibility to do so. We can't document every single impl detail and make it a public API, otherwise we can't move fast anymore. S

imilarly, we don't publicly document all the DOM structures we use and all the classNames, and your custom CSS selectors can break unless we document them as stable.

**Comment by 0ptim** [comment]
Thank you so much for the work you're doing. Am really loving Docusaurus and have used it already for 3 projects. 🚀

**Comment by slorber** [comment]
Not all env variables have to be documented. Some are internal implementation details. If your document them the doc might become stale over time and it's also confusing for users. Internal implementation details are hard to customize on purpose.

**Comment by wibed** [comment]
> Not all env variables have to be documented. Some are internal implementation details. If your document them the doc might become stale over time and it's also confusing for users. Internal implementation details are hard to customize on purpose.

it might not be practical to document static values. 
but maybe a command to fetch them easily could be useful.
