### ISSUE TITLE
docs(v2): Docusaurus 2 structure differs in different docs

### ISSUE THREAD

**Issue by covalentbond** [facebook/docusaurus#3956]
## 📚 Documentation

As in `Migration docs` the [Docusaurus V2 Structure](https://v2.docusaurus.io/docs/migration/#docusaurus-2-structure) is suggested to move the `docs` folder into the `website` folder.

![image](https://user-images.githubusercontent.com/53327173/103168486-9c823400-4859-11eb-9b7b-0ec395d16910.png)

But in the [Manual migration docs](https://v2.docusaurus.io/docs/migration/manual/#test-your-site), the `docs` folder is outside the `website` folder and in the `project directory`. It is causing confusion. I would suggest it to be same in both the docs and the structure suggested to be same in [Manual migration docs](https://v2.docusaurus.io/docs/migration/manual/#test-your-site) as it is in [Docusaurus V2 Structure](https://v2.docusaurus.io/docs/migration/#docusaurus-2-structure)

![image](https://user-images.githubusercontent.com/53327173/103168505-bface380-4859-11eb-945b-7740102ffc99.png)

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?
(Yes.)

**If approved I would like to submit a pull request for the same**

**Comment by slorber** [comment]
thanks, let me know if this PR looks good to you

https://github.com/facebook/docusaurus/pull/3962
