### ISSUE TITLE
Docusaurus 2: Uncaught TypeError: parse_numeric_range__WEBPACK_IMPORTED_MODULE_5___default.a.parse

### ISSUE THREAD

**Issue by caiiiycuk** [facebook/docusaurus#3961]
## 🐛 Bug Report

I have documentation site that used Docusraurs 2.
Sources: https://github.com/caiiiycuk/js-dos/tree/gh-pages/v7
I updated dependencies from:
```
    "@docusaurus/core": "^2.0.0-alpha.66",
    "@docusaurus/plugin-google-analytics": "^2.0.0-alpha.66",
    "@docusaurus/preset-classic": "^2.0.0-alpha.66",
```
to
```
    "@docusaurus/core": "^2.0.0-alpha.67",
    "@docusaurus/plugin-google-analytics": "^2.0.0-alpha.67",
    "@docusaurus/preset-classic": "^2.0.0-alpha.67",
```
When I do `yarn start` and trying to navigate to docs page, I have this error:
```
Uncaught TypeError: parse_numeric_range__WEBPACK_IMPORTED_MODULE_5___default.a.parse is not a function
    default index.js:194
    React 11
        renderWithHooks
        mountIndeterminateComponent
        beginWork
        callCallback
        invokeGuardedCallbackDev
        invokeGuardedCallback
        beginWork$1
        performUnitOfWork
        workLoopSync
        performSyncWorkOnRoot
        flushSyncCallbackQueueImpl
    unstable_runWithPriority scheduler.development.js:653
    React 6
    shouldComponentUpdate PendingNavigation.js:48
```

Reverting back to 66 does not help, only checkout yarn.lock help to solve the issue.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## To Reproduce

1. Checkout  https://github.com/caiiiycuk/js-dos/
2. Switch to gh-pages
3. cd to `v7`
4. fix package.json to 2.0.0-alpha-67
5. run `yarn start`
6. Open `http://localhost:3000/v7/build/docs/` in browser

## Expected behavior
Documentation rendered noramlly

## Actual Behavior
Page is not rendered, many errors in console.

## Your Environment

- Docusaurus version used: 2.0.0-alpha-67
- Environment name and version: FF, Chrome, etc
- Operating system and version (desktop or mobile): Ubuntu 20.04

## Reproducible Demo

N/A

**Comment by slorber** [comment]
Hi

Can you please upgrade to latest version and see if the problem is still there?

**Comment by caiiiycuk** [comment]
Sorry, I also tried 69 and 70, have same issues. I think something wrong with deps.

**Comment by caiiiycuk** [comment]
I also have ejected theme/CodeBlock maybe it should be fixed in someway I don't know...

**Comment by slorber** [comment]
> Sorry, I also tried 69 and 70, have same issues. I think something wrong with deps.

Then if that does not change anything you should rather use latest version, so that your bug repro is up to date

> only checkout yarn.lock help to solve the issue.

Not sure what you mean by that.
But you should commit the yarn lock.

You can try to delete/regenerate it after upgrading to latest version, it may help.
Also there is a "yarn docusaurus clear" command that you can run.

**Comment by caiiiycuk** [comment]
I found the reason. As I said I ejected CodeBlock and it have `rangeParser` in imports:
```
import rangeParser from 'parse-numeric-range';
```

So, when I comment this import then everything works. But how I can use it, even if I install `parse-numeric-range` package docusaurus 2 is not working with same error.
