### ISSUE TITLE
Does not build with an apostrophe in filenames

### ISSUE THREAD

**Issue by gaelle-csg** [facebook/docusaurus#3963]
## 🐛 Bug Report

I started to use docusaurus for an existing documentation which has apostrophes in filenames sometimes.
When I build my project, I always have the following error:

```
SyntaxError: docusaurus2/.docusaurus/routes.js: Unexpected token, expected ","
{
  path: '/docs/Wiki/Project's-Guide',
  component: ComponentCreator('/docs2/Wiki/Project's-Guide','efe'),
  exact: true,
},
```

### Have you read the [Contributing Guidelines on issues]
I couldn't find anything related to this issue, after searching 'apostrophe'

## To Reproduce
Install Docusaurus
Create a filename such as docs/Project's-Guide.md

## Expected behavior
I would expect to find in router.js, something like:
component: ComponentCreator('/docs/Wiki/**Project\\'s-Guide**','efe'),

## Actual Behavior
For now, I have:
component: ComponentCreator('/docs2/Wiki/**Project's-Guide**','efe'),
And I'm not able to complete 'npm run build'

## Your Environment
I'm on MacOS using docusaurus version 2.0.0-alpha.70.

Is it something that could be fixed or do I have to write a workaround on my side to change the filenames and also the documents links ? 
Thank you for your help!

**Comment by slorber** [comment]
thanks, that looks like we should fix this by escaping the string

You can probably fix it by using the `slug` frontmatter  so that the URLs do not contain any '

**Comment by gaelle-csg** [comment]
Thanks for the suggestion @slorber. I'm pretty new to font matter. Did you mean that it should work if I put the following in the beginning of my file: 
```
---
title: Projects Guide (no apostrophe)
---
```
I tried that but it didn't work. It takes the filename instead :/

**Comment by slorber** [comment]
You can use

```
---
slug: /Wiki/Projects-guide-whatever-url-I-want
---
```

**Comment by Alucard17** [comment]
Hey @slorber can take thsi issue

**Comment by slorber** [comment]
Sure thanks 😉
