### ISSUE TITLE
Snack Player

### ISSUE THREAD

**Issue by gHashTag** [facebook/docusaurus#3966]
## 🐛 Bug Report

Does not work Snack Player

1. `yarn add remark-snackplayer`
2.  Added SnackPlayer code

```SnackPlayer name=Hello%20World description=This%20is%20a%20description
import React from 'react';
import { Text, View } from 'react-native';

const YourApp = () => {
    return (
    <View style={{ flex: 1, justifyContent: "center", alignItems: "center" }}>
        <Text>
        Try editing me! 🎉
        </Text>
    </View>
    );
}

export default YourApp;
```

Expecting a Snack Player window, but it's not there.

<img width="853" alt="Снимок экрана 2020-12-29 в 15 13 16" src="https://user-images.githubusercontent.com/6774813/103276451-62936800-49e8-11eb-9be8-29a135652bee.png">

 "@docusaurus/core": "2.0.0-alpha.70",
 "@docusaurus/preset-classic": "2.0.0-alpha.70",
  "remark-snackplayer": "^0.0.3",

**Comment by slorber** [comment]
Hi,

The remark-snackplayer on npm is a test that our MLH intern did publish, it's not a package officially maintained by Docusaurus

Currently, the snack player is hosted locally on ReactNative website repo, not on NPM.

We will likely move it to https://github.com/expo/snack later so that other RN Docusaurus sites can use it, but in the meantime your best bet is to copy the RN snackplayer code and try to look at how it's integrated on the RN website.

**Comment by gHashTag** [comment]
1. Created a file snackPlayerInitializer.js similar to facebook/react-native-website https://github.com/facebook/react-native-website/blob/master/website/snackPlayerInitializer.js
2. I connected it to docusaurus.config.js 
clientModules: [require.resolve ('./ snackPlayerInitializer.js')],

Snackplayer did not appear. Where am I going wrong?

**Comment by slorber** [comment]
You likely need this line too: 
https://github.com/facebook/react-native-website/blob/master/website/docusaurus.config.js#L17

And use the proper snack player code blocks, as seen on RN website

**Comment by gHashTag** [comment]
Yes! Works. Thanks 🙏🏻

**Comment by gHashTag** [comment]
Another question is how to fix the styles? And then the player window is very small.

<img width="840" alt="Снимок экрана 2020-12-29 в 20 24 40" src="https://user-images.githubusercontent.com/6774813/103294595-faf31200-4a13-11eb-8baf-c71610072e43.png">

**Comment by gHashTag** [comment]
Done ✅

/* Snack Player */

.snack-player {
  height: 505px;
  width: 100%;
  overflow: hidden;
  margin-bottom: 24px;
  border: 1px solid var(--ifm-table-border-color);
  border-radius: var(--ifm-global-radius);
}

**Comment by gHashTag** [comment]
Is it possible to insert into this player the project of the site https://snack.expo.io/@playra/hello-world
I have a project ID: data-snack-id = "@playra/hello-world"
