### ISSUE TITLE
The `imgAlignSide` component only has a `margin-right`

### ISSUE THREAD

**Issue by cyan33** [facebook/Docusaurus#397]
### Is this a bug report?
bug

(write your answer here)

### Have you read the [Contributing Guidelines](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md)?

(Write your answer here.)
Yes

### Expected Behavior

I found this issue originally in the `jest` website. And after some discussion we figured that it would be ideal to fix this issue in the upstream.

If you look at the website of docusaurus, when the text is on the right side, the `blockImage` has a right `margin` in between, which is a `margin-right`:

![image](https://user-images.githubusercontent.com/13282699/34907596-3736a1a6-f84f-11e7-824b-a3eff6ec5c58.png)

However, when the text is on the left side, the `blockImage` doesn't fit this margin to a `margin-left`, which leaves no space in between the image and block text:

![image](https://user-images.githubusercontent.com/13282699/34907608-5df61de4-f84f-11e7-8dfd-5c635d325be0.png)

And in the `jest` website, it looks ugly when the boundary is obvious to note this issue:

![image](https://user-images.githubusercontent.com/13282699/34907616-7ccb5fea-f84f-11e7-8f51-c3b8d33a7015.png)

I think it would be ideal to add a parameter to the component to specify where should be the `margin` added, like `left` or `right`.

**I'd love to fix this issue and submit a PR if it is recognized.** 😄

**Comment by JoelMarcey** [comment]
@cyan33 Sorry I didn't respond to this sooner. I would, of course, have loved a PR. I appreciate any PRs to fix bugs :)

We will go with https://github.com/facebook/Docusaurus/pull/398
