### ISSUE TITLE
How to start the docusaurus with /docs

### ISSUE THREAD

**Issue by prasathsekar** [facebook/docusaurus#3973]
When i start docusaurus using npm start

The Page is opening with baseURL /, How do I change it to /docs

For Example:

When I start docusaurus using npm start 

The page should directly land in http://localhost:3000/docs/

How do I do it ??

**Comment by slorber** [comment]
It would be better to explain why you want to do that, and particularly why is this important in dev?

You can create an index page, use ReactRouter `<Redirect to="/docs"/>` component (exposed as `@docusaurus/router`)

You can also create a static HTML file in `/static/index.html` on which you perform a HTML redirect using JS

You can also setup the redirect only in your production env by using a server-side redirect on your host provider config (best solution)
