### ISSUE TITLE
<script> tag not executed in docusaurus v2

### ISSUE THREAD

**Issue by DianaKoenraadt** [facebook/docusaurus#3980]
## 🐛 Bug Report

If I add <script type="text/javascript">alert('blah!!!');</script> to my docusaurus MDX file, it's not executed when I open the page. The alert does not show.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## To Reproduce

Add <script type="text/javascript">alert('blah!!!');</script> to MDX. 

## Expected behavior

Scripts added to the DOM are executed.

## Actual Behavior

Script is added to DOM, but not executed.

## Your Environment

- Docusaurus version used :2.0.0-alpha.70
- Environment name and version (e.g. Chrome 78.0.3904.108, Node.js 10.17.0): Chrome 87.0.4280.88, Node.js v12.18.1
- Operating system and version (desktop or mobile): Desktop

## Reproducible Demo

-

**Comment by DianaKoenraadt** [comment]
Let me clarify.

I want to do `<script src="https://some.url.com/assets/my-javascript-hosted-somewhere.js"></script>` and have docusaurus run whatever is in that script.

How can I do this?

**Comment by slorber** [comment]
https://v2.docusaurus.io/docs/next/docusaurus.config.js/#scripts

**Comment by slorber** [comment]
note, if you want to use a script for a single MDX doc, then I don't think you can just embed a script element, React will not allow this.

You'll find various solutions online like 
https://www.npmjs.com/package/react-inline-script
https://usehooks.com/useScript/

**Comment by CrashLaker** [comment]
react-helmet worked for me
thanks
