### ISSUE TITLE
[v2] Emit asset manifests

### ISSUE THREAD

**Issue by RDIL** [facebook/docusaurus#3981]
## 🚀 Feature

It would be cool if either the core or an official plugin existed to generate asset manifests, like create react app does.  

This allows for extensibility, as well as supporting some non-static forms of servers.  Plus, it can help with debugging. 

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

yes

## Motivation

I’m trying to link my infrastructure together, and if a manifest was emitted it would save a lot of backend logic to discover the files needing to be served. 

## Pitch

Either use the same webpack plugin as create-react-app, or spin up a simple solution that just emits a json file containing the needed content.

**Comment by slorber** [comment]
Is this closed by https://github.com/facebook/docusaurus/pull/4021 or should we emit a custom Docusaurus manifest?

**Comment by RDIL** [comment]
#4021 adds what I need to complete a plugin with this, but I'll close it here.
