### ISSUE TITLE
Source static resources from multiple directories

### ISSUE THREAD

**Issue by oriooctopus** [facebook/docusaurus#3983]
## 🚀 Feature

Right now the static directory from which resources are sourced is hardcoded as /static ... I would like to be able to source from both /static and another folder.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## Motivation

This will be useful to me because I have an npm module that has shared components between two of my docusaurus sites. I would like to put shared images and fonts there so that I don't have to update them individually on both of the sites and can just do it in one place

## Pitch

This increases the maintainability of docusaurus sites that have shared code such as mine. Right now it is pretty tedious to have to update shared images in two places instead of one, especially given the rapid rate at which docs sites change.

I believe the changes necessary are in the configureWebpack call of plugin-content-docs/blog/pages, but I'm not 100% sure

**Comment by oriooctopus** [comment]
@slorber if this is not an existing feature, I would be willing to implement it myself!

**Comment by slorber** [comment]
Thanks @oriooctopus , that would be great.

We even have the usecase for this in the Docusaurus site itself, as the blog markdown files are shared between the v1 and v2 websites, and we have to actually duplicate blog post assets in both sites:
- https://github.com/facebook/docusaurus/tree/master/website/static/img
- https://github.com/facebook/docusaurus/tree/master/website-1.x/static/img

In such case, it would have been simpler to just tell Docusarus 2 to use `website-1.x/static/img` as a secondary assets folder.

Let me know if you need help implementing this, as it might involve changes in multiple locations, including the mdx loader (`remark/transformImage/index.js`).

To dogfoog, you can directly use this feature on the Docusaurus 2 website mentioned above :)

**Comment by Josh-Cena** [comment]
Implemented in #4095
