### ISSUE TITLE
How to have different Color with Dark mode

### ISSUE THREAD

**Issue by natac13** [facebook/docusaurus#3985]
## 📚 Documentation

When i was trying to implement dark mode using different colors for light and dark to get contrasting right, I struggled a bit to figure out how. 
Can a section like [this](https://docs.theochu.com/docusaurus/styling/#dark-mode) be add to the [Styling](https://v2.docusaurus.io/docs/styling-layout) section of the documentation to be a bit more clear?

**Comment by slorber** [comment]
Hi,

It's not totally clear to me what you want to be added. 
Is it mostly the `html[data-theme='dark']` that you want to add?

Why not submit a PR directly with the edits you would find useful to add?

**Comment by natac13** [comment]
Hey, 
Sorry for not being more clear, however you are correct with the `html[data-them='dark']`

>Why not submit a PR directly with the edits you would find useful to add?
Our doc is certainly not perfect and any contribution is welcome

I would love to! I get on this today. Thanks for the reply!
