### ISSUE TITLE
Footer logo doesn't allow srcDark

### ISSUE THREAD

**Issue by rluders** [facebook/docusaurus#3989]
## 🐛 Bug Report

I can't use the `srcDark` as in the navbar to the logo at the footer.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

(Write your answer here.)

## To Reproduce

(Write your steps here:)

1. Edit the `docusaurus.config.js`
1. Find the footer logo, and add the `srcDark` property to it
1. Try to run it, validator will complain about the property.

## Expected behavior

It should allow the footer logo to support both image formats.

## Actual Behavior

(Write what happened. Add screenshots, if applicable.)

## Your Environment

- Docusaurus version used:
- Environment name and version (e.g. Chrome 78.0.3904.108, Node.js 10.17.0):
- Operating system and version (desktop or mobile):

## Reproducible Demo

(Paste the link to an example repo, including a `siteConfig.js`, and exact instructions to reproduce the issue.)

**Comment by slorber** [comment]
Agree we should support this

Marked as good first issue as this should be easy to add for someone willing to contribute

**Comment by rluders** [comment]
Probably it is just a line missing [here](https://github.com/facebook/docusaurus/blob/d2d2872646bbc9180197a598763964b6ea659855/packages/docusaurus-theme-classic/src/validateThemeConfig.js#L267). I don't have time right now to change it and test. But, definilly a good first issue.

**Comment by natac13** [comment]
I was looking at this and:
1. Would you change [`FooterLogo`](https://github.com/facebook/docusaurus/blob/d2d2872646bbc9180197a598763964b6ea659855/packages/docusaurus-theme-classic/src/theme/Footer/index.tsx#L38-L40) from `img` to `ThemeImage`? Like [`Logo`](https://github.com/facebook/docusaurus/blob/d2d2872646bbc9180197a598763964b6ea659855/packages/docusaurus-theme-classic/src/theme/Logo/index.tsx#L34-L47) but then I see a problem with getting the image centered again as the styles get applied to the `img` inside the `div`
2. I was also having issues with eslint and typescript which I did not figure out. I tried to update the definitions in theme-common with no luck. 

If I could get a bit of direction I think I can finish the PR
