### ISSUE TITLE
Releases page support

### ISSUE THREAD

**Issue by montogeek** [facebook/Docusaurus#399]
Hello!

This is a great project that solves every author/maintainer problem: My library/framework website documentation.

Is there any plan to support a Releases page? This is extremely important in any library/framework website, show your users what changes were done in each release.

It could pull a CHANGELOG.md file or even Releases GH page info through the API to build a nice, eye candy page.

Of course, CHANGELOG.md or Releases notes could be written in so many ways, but after defining a standard for Docusaurus, every project would use it.

Please let me know your ideas, I could contribute it :)

**Comment by JoelMarcey** [comment]
@montogeek Hi! Sorry it took me a while to get back to you. 

So, you could theoretically create a `releases.js` under `website/pages`. But it seems like you are asking for a page built in that comes with Docusaurus, similar to the `users.html` or `index.html` pages.

I would be interested in your thoughts around this.

**Comment by montogeek** [comment]
@JoelMarcey Yes, it should be created by Docusaurus, not by its users.

**Comment by JoelMarcey** [comment]
@montogeek Could you provide an idea of what such a page might look like - or even better, propose a `.js` template that may fit into our `pages` directory with the other built in pages Docusaurus provides?

**Comment by endiliey** [comment]
This should be left to user though because we don't want to dictate the look/ layout of the pages.
