### ISSUE TITLE
TailwindCSS v2 support instruction in Docs?

### ISSUE THREAD

**Issue by natac13** [facebook/docusaurus#3994]
Could I add the following instructions to the Styling section of the docs to add TailwindCSS Support? Or would you rather not?

https://github.com/facebook/docusaurus/issues/2961#issuecomment-735355912

**Comment by kvnxiao** [comment]
The instructions from the comment I wrote above is still a workaround, and while I'm not affiliated with the project I would still like to interject with my opinion that if anything is to be currently added to the docs please advertise it as such (a workaround). I'm hoping Docusaurus supports it natively sometime in the future without anyone having to fiddle with additional plugin config files.

**Comment by natac13** [comment]
So the PR you would be looking for is to create a new [theme folder](https://github.com/facebook/docusaurus/tree/master/packages/docusaurus-theme-classic/src/theme) except all styling done with tailwindcss?

**Comment by slorber** [comment]
Yes, and the goal is that switching themes should be easy, and they'd share the same config and UX.
https://github.com/facebook/docusaurus/issues/3522

**Comment by vjpr** [comment]
Another option for tailwind support is [`twin.macro`](https://github.com/ben-rogerson/twin.macro). Very easy to setup. Only one minor issue for content plugins https://github.com/facebook/docusaurus/issues/4035.
