### ISSUE TITLE
overview page about all categories

### ISSUE THREAD

**Issue by szaimen** [facebook/docusaurus#3999]
## 🚀 Feature

I hope I haven't missed it but it would be great if there was a way to show the whole category tree on one page with embedded links so that a user can see an overview about all available items and directly navigate to them.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes, I have read them.

## Motivation

Currently, there is no built-in way to get an overview page about all available categories and items, afaik. Yes, all categories are visible on the left side but you only get an overview about all items if you first unfold all categories and they are in this case still not embedded on a page, so especially on mobile not really in focus this way

## Pitch

It should be implemented, because without it, it makes it for new users hard to get an overview about all available categories and items.

**Comment by RDIL** [comment]
By categories, what do you mean?  Docs?  Blog posts?  Pages?  All of them?

**Comment by slorber** [comment]
I'm not sure to understand either.

Can you draw a mockup of what it would look like exactly the Docusaurus website itself?

Note we have 2 docs plugin instances (regular docs + community docs),  and the docs has 2 sidebars (docs + API)

What would be the URL of such page, the configuration option, and is there even a single page of this kind per site?

**Comment by szaimen** [comment]
I guess this screenshot explains it a bit better:
![image](https://user-images.githubusercontent.com/42591237/103809652-1c7a7c00-505a-11eb-8ee5-220c2a64a4bc.png)
It would be great if there was a way to automatically generate an index page based on the sidebar with the exact same structure like the sidebar and links to each docs. Currently I must create the index page manually by copying the title and creating the links to each doc manually.

**Comment by RDIL** [comment]
Isn't that.. the exact purpose of the sidebar?

Personally I think this would need to be like a series of tiles.

**Comment by szaimen** [comment]
> Personally I think this would need to be like a series of tiles.

Sounds good to me! 👍 
A series of tiles is most likely a better idea than just showing a list on this page (like the sidebar already does).

**Comment by slorber** [comment]
That looks weird to me in both case

How do you represent a deeply nested hierarchy with tiles?

Who does that? Have you seen this UX anywhere?

**Comment by RDIL** [comment]
Maybe something like what gatsby does on their docs page?
https://www.gatsbyjs.com/docs/

**Comment by szaimen** [comment]
Here is a mockup:
<details><summary>Click here to expand</summary>
When opening the index page: (you will see only the first layer/lavel. All levels below are collapsed (look at the docs tile on the right side)

![Zeichenfläche 1](https://user-images.githubusercontent.com/42591237/103825843-e64af580-5075-11eb-8065-ee27b366c14d.png)

When you click on the docs tile, it expands and shows the embedded docs:

![1Zeichenfläche 1](https://user-images.githubusercontent.com/42591237/103825847-ea771300-5075-11eb-84d4-b663d0ad79a8.png)

</details>
Sry for the colors 😅

What do you think?

**Comment by slorber** [comment]
That looks like a quite opinionated design 😅 maybe something a bit more sober will fit more user usecases?

I'm not sure your design proposal works great for nesting.
Also, how are we supposed to choose the colors here? 😅 

My opinion is: as you can create such a page in userland today (manually), please do. If you build a successful page that shows great UX and that can be generalized for other Docusaurus users, we'll integrate this feature. [Do things that don't scall](http://paulgraham.com/ds.html) first, somehow 😅

**Comment by RDIL** [comment]
> 
> 
> That looks like a quite opinionated design 😅 maybe something a bit more sober will fit more user usecases?
> 
> I'm not sure your design proposal works great for nesting.
> Also, how are we supposed to choose the colors here? 😅
> 
> My opinion is: as you can create such a page in userland today (manually), please do. If you build a successful page that shows great UX and that can be generalized for other Docusaurus users, we'll integrate this feature.
> 
> [Do things that don't scall](http://paulgraham.com/ds.html) first, somehow 😅

I totally agree.  This sounds good.

**Comment by szaimen** [comment]
Hey, thanks for the reply!

Unfortunately, I am not experienced in coding in React and this is too much for me to handle. But I am able to create mockups. ;)

I've thought about your points, especially those:

> I'm not sure your design proposal works great for nesting.
> Also, how are we supposed to choose the colors here? 😅

And I've changed the mockup to address those points:
<details><summary>Click here to expand</summary>

## When opening the index page: (you will see only the first layer/level. All levels below are collapsed (look at the docs tile on the right side)
![1Zeichenfläche 1](https://user-images.githubusercontent.com/42591237/104213171-4fe05080-5436-11eb-8533-2fd50ad95550.png)

## When you click on the docs tile, it opens a popup and shows the embedded docs:
![1Zeichenfläche 5](https://user-images.githubusercontent.com/42591237/104213206-55d63180-5436-11eb-9e53-99876f90c584.png)

---

## If Versioning had some embedded docs, it would be closed by default:
![1Zeichenfläche 6](https://user-images.githubusercontent.com/42591237/104213225-5a024f00-5436-11eb-813c-a6c7979f29e4.png)

## And if you click on Versioning it would show the embedded docs:
![1Zeichenfläche 7](https://user-images.githubusercontent.com/42591237/104213251-5ec70300-5436-11eb-9d05-171f11c93da9.png)

</details>

What do you think about the new mockups? :)

**Comment by slorber** [comment]
I personally wouldn't want such kind of UX on my Docusaurus site 😅 
Maybe the navigation shouldn't be "nested" and we should just show the top-level elements of the sidebar (categories and docs).

I think it's not necessarily a good idea to diverge too much from what OS / FS explorers do: display top-level files, or display a tree structure. Navigation patterns using nested modals seems unusual and too fancy for me.

Note, this feature is quite related to https://github.com/facebook/docusaurus/issues/2643, as each category may need to have an overview page. We could just display top-level elements of a given sidebar, and from there link to the top-level element of each categories), this way nesting does not have to be handled and navigation looks more similar to the OS one.

**Comment by szaimen** [comment]
I'm closing this since the better idea was proposed in https://github.com/facebook/docusaurus/issues/2643#issuecomment-773146441
