### ISSUE TITLE
What is Chrome stable release M93 ???

### ISSUE THREAD

**Issue by DsCodeStudio** [facebook/docusaurus#4000]
Chrome tell me: Site cannot be installed: Page does not work offline. The page will not be regarded as installable after M93, stable release August 2021.

How to fix it ?

My site is : https://www.dscode.top

**Comment by DsCodeStudio** [comment]
I'm use Chrome 89, PWA it works, but Chrome tell me this warnning. and this problem also exists in https://v2.docusaurus.io/ 

![image](https://user-images.githubusercontent.com/61904318/103659511-72421c00-4fa7-11eb-9948-8d20143489c4.png)

**Comment by DsCodeStudio** [comment]
![image](https://user-images.githubusercontent.com/61904318/103659876-e7155600-4fa7-11eb-8507-fc8c12447385.png)
![image](https://user-images.githubusercontent.com/61904318/103659985-07451500-4fa8-11eb-94c0-bc525e203d9a.png)
Why ?

**Comment by kidwm** [comment]
@slorber You can browse the site with Google Chrome Canary (currently M89) to check the warning message

**Comment by slorber** [comment]
@kidwm if this warning message only appears in Chrome canary release, why not ask the Google Chrome team about that? Maybe they have a bug or will be able to provide insights.

I don't see what I can do myself with this error message, apart from hoping that when Chrome 89 is released this does not happen anymore.

Have you tried installing other websites on this version of Chrome for which you don't have this message?

**Comment by kidwm** [comment]
@slorber FYI, https://javascript.plainenglish.io/your-pwa-is-going-to-break-in-august-2021-34982f329f40
`plugin-pwa` may need to update to make it install as PWA by default configs.
