### ISSUE TITLE
[v2] logo `img` randomly reload and resize while switching page.

### ISSUE THREAD

**Issue by katopz** [facebook/docusaurus#4008]
## 🐛 Bug Report

When click through each menu on https://v2.docusaurus.io/
The logo `img` will randomly reload and appear width 0px while loading logo and resize to 32px when loaded.
This make whole Navbar menu move back and forth while this happen.

![image](https://user-images.githubusercontent.com/97060/103877968-5bffa180-5108-11eb-9d5c-1601d4218f7c.png)

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

yes

## To Reproduce

1. goto https://v2.docusaurus.io/
1. Try click through each menu randomly.

## Expected behavior

`img` not reload and/or resize

## Actual Behavior

`img` resize from width 0px to 32px (happen randomly)

## Your Environment

- Docusaurus version used: v2
- Environment name and version (e.g. Chrome 78.0.3904.108, Node.js 10.17.0): Chrome Version 87.0.4280.88 (Official Build) (x86_64)
- Operating system and version (desktop or mobile): macOS 10.15.7

## Reproducible Demo

https://v2.docusaurus.io/

## Work around
- Add custom css (This will stop flicker from width 0 to with 32px but logo img still reload)
```css
.navbar__brand > img {
  width: 32px;
}
```
- Use defined size `div` with `background-url` instead.

## IMHO
It should be not rerender whole Navbar an its elements (img logo in this case) whenever possible.

**Comment by natac13** [comment]
Just wanted to add my observation trying to reproduce this issue. I was only able to see the issue as described when the devtools where open. With them closed I did not see the flickering. And even then it is not ever time. Here is a video.

https://user-images.githubusercontent.com/10660283/103918310-a4a16580-50dc-11eb-8893-27748e6fcfc9.mp4

**Comment by katopz** [comment]
@natac13 You are right! I leave devtools open for debugging css there. I'll close this issue in case end user won't open devtools anyway. Thanks for head up!

**Comment by natac13** [comment]
@katopz Maybe we should see if the maintainers still want this addressed and leave the issue open?

**Comment by katopz** [comment]
@natac13 OK, Cool. I'll reopen it for now, just in case. :)

**Comment by slorber** [comment]
Hi,

This is related to layout unmount/remount on navigation (tracked as https://github.com/facebook/docusaurus/issues/2891)

The image reloads because it's part of the layout, and it unmounted/remounted and the devtools open generally disable the image cache to make this problem more visible.

I'll fix the unmount/remount issue when I find a good solution to this problem.
