### ISSUE TITLE
Remove "Edit this page" for older versions of the docs

### ISSUE THREAD

**Issue by allanaaa** [facebook/docusaurus#4013]
## 🚀 Feature

1) I'd like to be able to toggle the "Edit this page" button at the bottom of each page off/on.
2) I'd like to be able to display "Edit this page" only on the latest version of the docs, not the older versions.

I'm not sure if 1 already exists in the code somewhere, but I could use some help figuring out how to do 2. If it's not currently possible, consider this a feature request. Thanks!

**Comment by slorber** [comment]
Hi,

For 1 I think you can use `custom_edit_url: null` as frontmatter.

For 2, it's currently not possible but wonder what's your usecase for this exactly?
The next version has an `editCurrentVersion: true` config (unreleased but you can install with `@canary` tag).
This enables to avoid receiving doc update PRs to older branches, can it work for your usecase?
https://v2.docusaurus.io/docs/next/api/plugins/@docusaurus/plugin-content-docs

**Comment by fernandoxhds** [comment]
Muito bom

**Comment by slorber** [comment]
FYI the `@canary` npm dist tag and upcoming release allows to provide an editUrl function.

https://v2.docusaurus.io/docs/next/api/plugins/@docusaurus/plugin-content-docs

You can do  `if (version === "1.0.0" ) return undefined;` or whatever you want.
