### ISSUE TITLE
LaTex integration 

### ISSUE THREAD

**Issue by linyuxuanlin** [facebook/docusaurus#4017]
## 📚 Documentation

Hello~ I'm meeting a situation that LaTex is not rendered properly in Docusaurus v2.0.0-alpha.70.  I've tried the solution provided by @hhk7734 in #2078 but it wasn't working (still not rendered properly).  I think it's caused by the version of Docusaurus. Does anybody have an idea to use LaTex normally in Docusaurus? 

Thanks!

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

yes

**Comment by slorber** [comment]
Hi,

"it is not working" is not very actionnable for other users to help you solve your problem.

Please provide much more details,like full repro case of what you tried and a clear description of what you expected, and what you got.

**Comment by slorber** [comment]
@TheodoreChu has a page about this: https://docs.theochu.com/docusaurus/latex/

**Comment by TheodoreChu** [comment]
Yup 👍🏼 
As a another example, you can see https://github.com/standardnotes/docs

- package.json: https://github.com/standardnotes/docs/blob/main/package.json#L29-L30
- hosted css: https://github.com/standardnotes/docs/tree/main/static/katex/v0.12.0
- remark/rehype plugins in docusaurus.config.js: https://github.com/standardnotes/docs/blob/main/docusaurus.config.js#L255-L256
- stylesheets in docusaurus.config.js: https://github.com/standardnotes/docs/blob/main/docusaurus.config.js#L232-L238
- source of a doc with KaTeX: https://github.com/standardnotes/docs/blob/main/docs/usage/markdown-math.md#katex ([raw](https://raw.githubusercontent.com/standardnotes/docs/main/docs/usage/markdown-math.md))
- how the doc is rendered: https://docs.standardnotes.org/usage/markdown-math#katex

**Comment by slorber** [comment]
thanks, that looks like a great example

We should figure out a place to add such examples in Docusaurus doc somehow

**Comment by linyuxuanlin** [comment]
thanks! it works perfectly!

**Comment by pranabdas** [comment]
@slorber how about we create a new doc page under **Docs** → **Guides** → **Markdown Features** → **Math Equations** for this?
