### ISSUE TITLE
Add a shorthand for making alternative named anchors

### ISSUE THREAD

**Issue by flying-sausages** [facebook/docusaurus#4023]
## 🚀 Feature

Some nice shorthand for easily defining alternate anchor names for otherwise long headings

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yup

## Motivation

I like to use quite verbose headings, and I'd like to make shorter anchors so I can link to them easier. Each word in the heading makes the URI for it longer, and sometimes it's nice to use "codewords" for them.

## Pitch

The other alternative is adding a line like this just above the heading

```md
<a class="anchor enhancedAnchor_node_modules-@docusaurus-theme-classic-lib-theme-Heading-" tabindex="-1" name="logs"></a>

## Retrieving logs from the toolset

```

It would be nice to have some sort of mechanism to add these dynamically into the generated DOM instead of having to paste this quite long line in there.

For example adding it to the heading line such as this and ensre the same CSS is applied to it so that there isn't extra space added above or below the heading, and so that the heading does not get hidden behind the site header when the anchor link is clicked.

`## Retrieving logs from the toolset <a  name="logs"></a>`

An alternative could be adding some `<anchor>` object which would get styled the same way the headings do, and would not conflict with the rendering. I would not know how to make a module like that in a way which it wold not interfere with the spacing above/below the headings, and end up inside the `<h2>` tag for example

**Comment by slorber** [comment]
Hi,

There's already an issue for this: https://github.com/facebook/docusaurus/issues/3322

It's needed for i18n support, as we don't want anchor links to break when headings get translated.
