### ISSUE TITLE
BaseUrl banner: make the message configurable please Google/SEO/indexers

### ISSUE THREAD

**Issue by Morriz** [facebook/docusaurus#4028]
## 🚀 Feature

Currently this message is indexed (google it) on ALL sites using docusaurus:

"Your Docusaurus site did not load properly."

It would be nice to let us configure that message so that we at least have some control over our crawl presence on the web.

### Have you read the [Contributing Guidelines on issues]

yes

**Comment by slorber** [comment]
Thanks for reporting this.

Can you explain how this affects your site exactly? 

I mean, no one is googling for "Your Docusaurus site did not load properly.", so how did you find it was a problem, and how customizing the message will solve it?

Maybe we should also add an opt-in option to remove it?

**Comment by Morriz** [comment]
I see a lot of docusaurus doc sites be indexed by google that way, probably since it is hosted as static only.

I was just offering you to search for that exact string so you can see the scale of the problem.

Maybe crawlers can be told to ONLY index meta description instead of that message, but I am not very deep into html specs any more...

**Comment by slorber** [comment]
https://www.google.com/search?q=%22Your+Docusaurus+site+did+not+load+properly.%22&rlz=1C5CHFA_enFR749FR749&oq=%22Your+Docusaurus+site+did+not+load+properly.%22&aqs=chrome.0.69i59.4303j0j7&sourceid=chrome&ie=UTF-8

I do agree that these Docusaurus 2 sites get indexed in an unexpected way, and we should likely offer a way to disable that.

I just wonder why specifically it is a problem for you and your users? 
How does it impact your business/SEO in a concrete way?
What did a regular user type, and why was he disappointed?

It is very unlikely that a user will type such a string on Google, and when searching for "Docusaurus 2" 

![image](https://user-images.githubusercontent.com/749374/104497499-b7cf9c00-55da-11eb-97ea-109938d43de1.png)

I'm just trying to understand better your motivations to figure out the best way to do something about it.

Maybe by default we could write "your site www.xyz.com did not load properly" or something?

Does a new config option really solve the problem? As many site owners wouldn't even be aware of that option?

**Comment by Morriz** [comment]
Look, I really don't care what REAL people see that have javascript turned off (I regard them as weirdos and not part of our target population), so I'd rather cater to the CRAWLERS, and get a nice message on google et al.

**Comment by Morriz** [comment]
I found our site to be indexed with that message, so it's not about how and via what route I found out about that. Only then did I do an extra search for that string, to reveal the scale of this.

**Comment by Morriz** [comment]
I have to say I am not aware anymore of what I searched for, but it was the day of a media announcement and was generating some keyword combos and then saw it indexed like that. I just tried some again but can't reproduce.

**Comment by slorber** [comment]
I understand. 
Will try to find a solution, not sure I can totally prevent it to be indexed but at least it should be possible to disable/customize it.

**Comment by Morriz** [comment]
Thanks for being so sweet. Sorry about my hammering. It's no prio.

**Comment by kkhoury38** [comment]
Same problem with us (https://atman-iot.com)

Our site was built on docusaurus 2.

If you search on google for "atman iot" you will see the following snipet: 

Your Docusaurus site did not load properly. A very common reason is a wrong site baseUrl configuration. Current configured baseUrl = / (default value). 

At the same time the page loads properly from my pc. Any ideas?

**Comment by slorber** [comment]
Hey,

Totally forgot about this, but it's already possible to disable this message 😅 

https://v2.docusaurus.io/docs/next/docusaurus.config.js/#baseurlissuebanner

Still trying to find a solution, will attempt a few things to make the message not indexed by default, but not sure about the Google Crawler behavior :

**Comment by slorber** [comment]
https://github.com/facebook/docusaurus/pull/4125

This PR will ensure that the help banner is not server-rendered anymore. This should prevent the google indexation.

As it is possible to disable this banner with config, and it should normally not be indexed anymore, I don't think it's worth it to be able to customize that message.

Going to close this for now, but we'll check if the message is still indexed or not soon.

**Comment by kkhoury38** [comment]
The message is a helpful pointer for new users but in general I think it
could be omitted. By searching online for the exact message, there is a
number of docusaurus pages that have the issue so my opinion is that it
creates more problems that the problems it solves.

An idea could be to disable it by default on anything except localhost.

Anyway, thanks a lot for your response!

**Comment by slorber** [comment]
But if it was disabled by default it would not have any effect 😅 users
generally have this problem when they first try to deploy their site in
production.

Not sure what to do if my latest attempt does not work. Hope it will work!
😄

Le ven. 29 janv. 2021 à 20:42, kkhoury38 <notifications@github.com> a
écrit :

**Comment by slorber** [comment]
Searching for `site:v2.docusaurus.io + "your docusaurus site did not load properly."` does not show any result with that exact string, so it should be fixed in next release
