### ISSUE TITLE
`checkSidebarsDocIds` should print the location of the sidebar file

### ISSUE THREAD

**Issue by vjpr** [facebook/docusaurus#4037]
## 🚀 Feature

(A clear and concise description of what the feature is.)

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## Motivation

If an id used in a sidebar file is missing I get this message:

```
Error: Bad sidebars file.
These sidebar document ids do not exist:
- readme-template`,

Available document ids=
- assets/readme
- docs-shared/readme
- docs/readme
- readme
    at Object.checkSidebarsDocIds (/xxx/node_modules/.pnpm/@docusaurus/plugin-content-docs@2.0.0-alpha.69_react-dom@16.14.0+react@16.14.0/node_modules/@docusaurus/plugin-content-docs/lib/sidebars.js:194:19)
```

I have many docs plugins in my codebase and it doesn't give me any hint as to which one contains the problem.

**Comment by slorber** [comment]
Agree, that error should give more details and help figure out how to fix the problem.

I'd also like to make this error configurable, like `onUnknownSidebarDocId: 'warn'` or something, as this kind of error is not critical to solve.

**Comment by slorber** [comment]
fixed by https://github.com/facebook/docusaurus/pull/4969
