### ISSUE TITLE
Incorrect HTTP code in places.

### ISSUE THREAD

**Issue by mitchellurgero** [facebook/Docusaurus#404]
### Is this a bug report?

yes.

### Have you read the [Contributing Guidelines](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md)?

Yes.

### Environment

Ubuntu 16.04, Node 8.9, Lastest (As of this post) Docusaurus from npm.

### Steps to Reproduce

Viewing pages that do not exist return error code 200, but should be returning 404.

### Expected Behavior

Return HTTP code 404.

### Actual Behavior

Returns HTTP code 200.
![image](https://user-images.githubusercontent.com/4168998/35165248-37c5c714-fd13-11e7-9120-c7a8661a4c6a.png)

### Reproducible Demo

Can be reproduced literally on any docusaurus installation: https://urgero.org

**Comment by JoelMarcey** [comment]
@mitchellurgero Hi. Thanks for filing this issue. 

Interesting...

I went to your website: https://urgero.org (thanks for using Docusaurus, btw).

I tried https://urgero.org/opos/index.html -- and I got a 404.

I tried https://urgero.org/opos - and I get what you pasted in your screenshot.

I wonder if this has to do more with [express.js](https://expressjs.com/) than the Docusaurus core? Needs investigating.

**Comment by JoelMarcey** [comment]
Probably have to do some additional routes or checking in `server.js`.

**Comment by mitchellurgero** [comment]
Hey @JoelMarcey ! Thanks for fixing so quickly! Idk what you mean by that. I am using the latest package from npm (npm install Docusaurus-init)

**Comment by JoelMarcey** [comment]
@mitchellurgero Sorry for not being clear -- what I am asking is your website https://urgero.org running on GitHub Pages (e.g., did you use `docusaurus-publish`)? Or is it running somewhere else using the built-in Docusaurus server?

**Comment by mitchellurgero** [comment]
I am using docusaurus via it's server.js (using nodeJS and apache2 to proxy.

**Comment by JoelMarcey** [comment]
Perfect. That makes sense, because you would only get those errors running the Docusaurus server. GitHub Pages would give you different messages, etc. on those routes.
