### ISSUE TITLE
docker-compose section needs --host flag

### ISSUE THREAD

**Issue by tomsfernandez** [facebook/docusaurus#4042]
## 📚 Documentation

The Docker and Docker-Compose section does not specify that the `--host 0.0.0.0` option as part of the `docusaurus-start` command is needed. If the option is not provided then the website will not be available if accessed from the host (served by the container of course)

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Add a short sentence to remind the user to add that flag in the `package.json`

**Comment by slorber** [comment]
Hi,

As far as I understand it is for Docusaurus v1. 
We now recommend users to upgrade to v2, as v1 is in low-maintainance mode.

If you feel that doc addition to v1 would be useful, what about directly submitting a PR by editing this file? 
https://github.com/facebook/docusaurus/edit/master/website-1.x/docs/getting-started-docker.md

**Comment by tomsfernandez** [comment]
Hi! It's also in the v2 docs: https://docusaurus.io/docs/en/next/docker

I'll make a PR in both

**Comment by slorber** [comment]
thanks.

The v2 doc is here: http://v2.docusaurus.io/ and it does not mention docker

**Comment by tomsfernandez** [comment]
🤦  I was looking at: https://docusaurus.io/docs/en/next/docker. What is the difference between v2 and next in the docs?

**Comment by slorber** [comment]
v1/next is the upcoming docusaurus v1 release (ie 1.14.7 if we ever release it)

**Comment by tomsfernandez** [comment]
Closing this issue as it all has been merged. Thanks!
