### ISSUE TITLE
algolia is never instructed to reindex after content changes

### ISSUE THREAD

**Issue by Morriz** [facebook/docusaurus#4044]
## 🐛 Bug Report

It seems algolia is never instructed to reindex after content changes. We have the same stale data from the beginning. Is there any documentation on how to trigger a re-index? I am thinking about changing the name of the index every time with the version.

### Have you read the [Contributing Guidelines on issues]

yes

## Expected behavior

With every content change deployment I would expect algolia to be notified to reindex.

## Actual Behavior

Index never changes.

## Your Environment

- Docusaurus version used: 2.0.0-alpha.70
- Environment name and version (e.g. Chrome 78.0.3904.108, Node.js 10.17.0): Node.js 14

**Comment by slorber** [comment]
Hi,

@shipow and @francoischalifour would be able to answer that better than me as it's not directly related to Docusaurus but rather Docsearch

Algolia DocSearch runs the Crawler every 24h:
https://docsearch.algolia.com/docs/scraper#when
Afaik there are working on something to trigger a crawl after changes but not sure it's currently active.

If it does not update after 24h, you can contact them.

If you need to run the crawler more often, you can run it yourself.

**Comment by Morriz** [comment]
Thanks for all the pointers. It was an indexing issue and Algolia fixed it.
