### ISSUE TITLE
Debounce reload

### ISSUE THREAD

**Issue by vjpr** [facebook/docusaurus#4050]
## 🐛 Bug Report

In `core/src/commands/start.ts` the reloader is not debounced and triggers reload for simultaenous file changes.

https://github.com/facebook/docusaurus/blob/3166fab307220df5e644d86402d3475406d60031/packages/docusaurus/src/commands/start.ts#L102-L113

This is happening to me when I add a new package as `node_modules` is being (probably mistakenly) watched somewhere. Still, a [simple debounce in chokidar](https://github.com/paulmillr/chokidar/issues/68) should solve it.

```
Docusaurus website is running at: http://localhost:4000/
Docusaurus website is running at: http://localhost:4000/
Docusaurus website is running at: http://localhost:4000/
Docusaurus website is running at: http://localhost:4000/
Docusaurus website is running at: http://localhost:4000/
Docusaurus website is running at: http://localhost:4000/
Docusaurus website is running at: http://localhost:4000/
Docusaurus website is running at: http://localhost:4000/
```

**Comment by slorber** [comment]
Yes I noticed that already, also happens when you pull from git etc...

We'll add a debounce
