### ISSUE TITLE
`@docusaurus/plugin-content-docs-types` missing from `plugin-content-docs/package.json`

### ISSUE THREAD

**Issue by vjpr** [facebook/docusaurus#4057]
https://github.com/facebook/docusaurus/blob/83c5e2ae34765fbd3838432e93048d7eac5fbb25/packages/docusaurus-plugin-content-docs/src/index.ts#L41

**Comment by Ako92** [comment]
What should done here? 
I can handle it if no one working on it.
I think i just have to add `'@docusaurus/plugin-content-docs-types'` to package.json. is it right?

**Comment by vjpr** [comment]
Yep.

**Comment by rajrajhans** [comment]
Hey @vjpr, if this is still pending, I'd love to get it done.

**Comment by slorber** [comment]
still pending @rajrajhans 👍 just one ine to add :p

**Comment by rajrajhans** [comment]
Yep, just needed some clarification. I couldn't find any package named `@docusaurus/plugin-content-docs-types`. However, I did find that `PermalinkToSidebar` is being exported from [here](https://github.com/facebook/docusaurus/blob/41ef333e47bd8985a6cbd82e9f2650b0fc75ec97/packages/docusaurus-plugin-content-docs/src/plugin-content-docs.d.ts#L11). Considering this, shall I still proceed adding `@docusaurus/plugin-content-docs-types` as a dependency in `package.json` or should I change [index.ts](https://github.com/facebook/docusaurus/blob/83c5e2ae34765fbd3838432e93048d7eac5fbb25/packages/docusaurus-plugin-content-docs/src/index.ts#L41) to import it from [here](https://github.com/facebook/docusaurus/blob/41ef333e47bd8985a6cbd82e9f2650b0fc75ec97/packages/docusaurus-plugin-content-docs/src/plugin-content-docs.d.ts#L11)?

PS: I'm a novice in TypeScript, so do let me know if I'm making any mistake : )

**Comment by xtlmnz** [comment]
Hi I have made the changes and created a pull request please review it.
First timer here :)

**Comment by xtlmnz** [comment]
https://github.com/facebook/docusaurus/pull/4149

**Comment by xtlmnz** [comment]
https://github.com/facebook/docusaurus/pull/4150

**Comment by slorber** [comment]
I'm sorry, I finally think there's nothing to be done here.

`@docusaurus/plugin-content-docs-types` is not a package but an ambient TS declaration, not sure what you want to be done @vjpr , please re-open a new issue with better context, as I'm not able to figure out what we should do

**Comment by vjpr** [comment]
I wanted to fork the docs-plugin. I copied the folder to my monorepo. Then it fails to build because it cannot find this package which is required for building.

If a package is referenced from a file it should be included in the package.json. Even if it is just types.

**Comment by slorber** [comment]
@vjpr but there is no such package 😅 it's TS declaration here: docusaurus-plugin-content-docs/src/plugin-content-docs.d.ts

**Comment by vjpr** [comment]
How does it get resolved? Is it an alias or some configuration of tsc
maybe. Sorry I am on phone and cannot look at code myself right now.

Maybe I got around it in a different way.

**Comment by rajrajhans** [comment]
@slorber @vjpr  It is failing to build because it is imported from that package which doesn't actually exist. Instead, it should be imported from [this file](https://github.com/facebook/docusaurus/blob/41ef333e47bd8985a6cbd82e9f2650b0fc75ec97/packages/docusaurus-plugin-content-docs/src/plugin-content-docs.d.ts#L11)

**Comment by vjpr** [comment]
Ah, okay - this is where the module is being defined. I was unfamiliar with this ambient creation of type data.

```
declare module '@docusaurus/plugin-content-docs-types' { <---
  export type PermalinkToSidebar = {
    [permalink: string]: string;
  };
```

@slorber Is this a common pattern in TS? Why would you not just export the types without wrapping them in this "virtual" package.

`@docusaurus/plugin-content-docs/types` or something like that.

**Comment by slorber** [comment]
I agree that there is something weird in our current TS setup. 

Unfortunately, I don't have much time to fix these issues right now, but yeah I'd rather have regular imports than ambient TS defs. 

The thing is I'd like content plugins to expose both server/node code and browser code APIs, both with proper typedefs (not handwritten ones). We are not there yet 😅
