### ISSUE TITLE
Anchor Links not working when switching Docusaurus version

### ISSUE THREAD

**Issue by liriz002** [facebook/docusaurus#4070]
## 🐛 Bug Report

Anchor Links stop appearing when switching to a newer version of Docusaurus (it's still from v2 to a newer v2). By Anchor Link, I mean the "#" that appears when hovering over a heading.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## To Reproduce

We have a project that was on 2.0.0-alpha.66, where everything was working. Then:

1. I updated these 3 libraries to latest:
a) @docusaurus/core
b) @docusaurus/preset-classic
c) @docusaurus/module-type-aliases

which brought them up to version 2.0.0-alpha.70

2. In this version, hovering over headings does not make the "#" next to them appear for some reason.

## Expected behavior

When updating versions, the Anchor Links feature should still be working. However, it does work if I revert back to 2.0.0-alpha.66, so the issue seems to be related to the version.

## Actual Behavior

The Anchor Links do not appear when hovering over a heading.

If it helps, when I inspect the header elements, they have an `id` property set themselves, but not anchor link.

## Your Environment

- Public source code: Local project
- Public site url: Local project
- Docusaurus version used: 2.0.0-alpha.70
- Environment name and version (e.g. Chrome 78.0.3904.108, Node.js 10.17.0): Chrome Version 87.0.4280.141, Node 12.12.0, React 17.0.1
- Operating system and version (desktop or mobile): Desktop macOS Catalina (10.15.7)

## Reproducible Demo

Unfortunately I can't reproduce this live or with a new project. I even tried creating a new Docusaurus project locally and it works fine. However, my project is the one having issues with this latest version. Like I mentioned, If I revert back to 2.0.0-alpha.66, it works again.

Please let me know if I can answer any other question. Thanks!

**Comment by slorber** [comment]
Hi,

It is most likely a local caching issue. 
I suspect your TOC on the right does not appear either?

After upgrading, run `npm run docusaurus clear`.
https://v2.docusaurus.io/docs/next/cli/#docusaurus-clear

If this does not work, removing your lockfile and re-generating it can help.

A `docusaurus upgrade` cli command could be useful to prevent these caching issues, let's track it here: https://github.com/facebook/docusaurus/issues/4075

**Comment by benradstone** [comment]
Just in case it might help someone else:

I also encountered this problem and, in addition to running `rpm run docusaurus clear` and deleting the `package-lock.json`, I had to delete the `node_modules` directory to get the anchors working again.
