### ISSUE TITLE
Remind to clear cache before building after upgrade

### ISSUE THREAD

**Issue by HonkingGoose** [facebook/docusaurus#4078]
## 🚀 Feature

Before `docusaurus build` or `docusaurus start` runs, it checks if the current version of Docusaurus equals the previous version of Docusaurus.

If the versions are not equal, it prints to the console something like this:
"You've updated Docusaurus, run `docusaurus clear` to clear the cache, and try again."

User runs `docusaurus clear`, and then `docusaurus start`/`docusaurus build` will work.

Maybe Docusaurus leaves some some kind of version number in a file in the cache folders that we could use to compare versions?

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes.

## Motivation

Users can run into trouble when the Docusaurus cache is outdated.
Users should run `docusaurus clear` to clear the cache after upgrading the packages, but it's easy to forget.
Therefore we should prompt users when they're building/starting docusaurus locally.

## Pitch

I know @slorber proposed a really similar feature at #4075.
This proposal only works properly when a user runs the proposed `docusaurus upgrade` command and upgrades docusaurus manually.
But a user can also rely on a dependency management bot (Dependabot, Renovate bot, Depfu) to update their packages.
So I think it's good to also add a proper check into the Docusaurus program.

**Comment by Josh-Cena** [comment]
After the Webpack 5 migration, we already have a cache invalidation system that seems to work between releases.
