### ISSUE TITLE
Always show stack traces to source code on webpack errors

### ISSUE THREAD

**Issue by vjpr** [facebook/docusaurus#4087]
## 🐛 Bug Report

There are some errors that do not show stack traces in the terminal. Any place that it is possible for an error to be shown, the original stack trace to the source code (not just the `.docusaurus/` built code) should be shown.

### E.g. Module not found

```
/xxx/repos/live/readme.md
Module not found: Can't resolve 'file-loader' in '/xxx/repos/live'
```

_/xxx/repos/live/readme.md_

```
# Foo

- [cli](packages/cli/package.json)
```

I mistakenly linked to a `package.json` file instead of a `readme.md` file but the error gives me no clues to track down what is causing it.

### E.g. Rehype/Remark plugins show stack trace to build dir

```
/xxx/repos/live/readme.md
TypeError: Cannot read property 'start' of undefined
 @ ./.docusaurus/registry.js 1:13670-13717 1:13549-13642
 @ /xxx/node_modules/.pnpm/@docusaurus/core@2.0.0-alpha.70_react-dom@16.14.0+react@16.14.0/node_modules/@docusaurus/core/lib/client/exports/ComponentCreator.js
 @ ./.docusaurus/routes.js
 @ /xxx/node_modules/.pnpm/@docusaurus/core@2.0.0-alpha.70_react-dom@16.14.0+react@16.14.0/node_modules/@docusaurus/core/lib/client/clientEntry.js
 @ multi /xxx/node_modules/.pnpm/react-dev-utils@10.2.1/node_modules/react-dev-utils/webpackHotDevClient.js /xxx/node_modules/.pnpm/@docusaurus/core@2.0.0-alpha.70_react-dom@16.14.0+react@16.14.0/node_modules/@docusaurus/core/lib/client/clientEntry.js
```

### E.g. UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open 

```
(node:62198) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open '/xxx/repos/live/packages/apps/docs/.docusaurus/docusaurus-plugin-content-docs/xxx/site-brag-packages-apps-web-docs-doc-1-md-44e.json'
(Use `node --trace-warnings ...` to show where the warning was created)
```

---

This error is caused by a remark plugin I wrote that tries to access a property of undefined. The problem is that the stack trace makes it very difficult to track it down. Can remark plugin execution be wrapped in try/catch? Or maybe there is another plugin external to Docusaurus that is causing the original error to be silenced.

## To Reproduce

TODO

**Comment by slorber** [comment]
Agree with should try to improve stacktraces and error logs. 

Apparently it seems complicate to have stacktrace on async and FS-related code in NodeJS (https://stackoverflow.com/questions/32235848/getting-at-error-native-instead-of-actual-node-js-stacktrace-despite-using-e), so we should probably add a lot of try/catch a bit everywhere and log or add contextual information to catched errrors.

Ideally I'd also have to introduce some kind of logging framework with different log levels, so that even in case the stacktrace.

Also related to "error cause" proposal, already at stage-2: https://github.com/tc39/proposal-error-cause

**Comment by armano2** [comment]
few notes, issue is actually trivial to fix as we are can easily get stacktrace from webpacks by changing formatter 

https://github.com/facebook/docusaurus/blob/9bdb9eb6305af6b661c90ede7837ba4c7b670bce/packages/docusaurus/src/webpack/plugins/LogPlugin.js#L20-L25

**Comment by armano2** [comment]
issue is actually located in 

```js
  // Remove leading newline
  if (lines.length > 2 && lines[1].trim() === '') {
    lines.splice(1, 1);
  }
```

https://github.com/facebook/create-react-app/blob/5fc8350c89ff730cdfd067bbd86a90dab393d21b/packages/react-dev-utils/formatWebpackMessages.js#L58-L61

if there are more than one 2 lies in error message, all other error lines are getting stripped from it

**Comment by Josh-Cena** [comment]
Closing as wontfix because we don't control the stack traces... We will try to catch the async operations to get meaningful stack traces, but as @armano2 pointed out, if it's coming from the dev utils, there's nothing we can do
