### ISSUE TITLE
Problem with google indexing

### ISSUE THREAD

**Issue by kkhoury38** [facebook/docusaurus#4094]
Hi,

We have a problem with the way we are indexed by google. 

If you search for our site, under the title you will get as a description the following:

"Your Docusaurus site did not load properly. A very common reason is a wrong site baseUrl configuration. Current configured baseUrl = / (default value)."

While if you go on the actual site, it works properly.

The problem is that it most probably affects our SEO

Search keywords: "atman iot"
site: https://atman-iot.com
Google cache - text only: http://webcache.googleusercontent.com/search?q=cache:Xg50wKk0YbgJ:https://atman-iot.com/&client=ubuntu&hl=en&gl=gr&strip=1&vwsrc=0

Dependencies: 
@docusaurus/core: 2.0.0-alpha.69
@docusaurus/preset-classic: 2.0.0-alpha.69

Any ideas?

Thank you in advance!

**Comment by kkhoury38** [comment]
The issue with the description was solved by itself (page was re indexed). The Docusaurus error still appears on the text only cached page but for now it doesn't seem to affect the search results.

**Comment by slorber** [comment]
Hi @kkhoury38 

Will still try to find a solution to this problem as part of https://github.com/facebook/docusaurus/issues/4028

Can you tell me how does this "text-only" thing work exactly?

**Comment by kkhoury38** [comment]
Hi Sebastien,

Thanks for your reply.

Check this link:
http://webcache.googleusercontent.com/search?q=cache:Xg50wKk0YbgJ:https://atman-iot.com/&client=ubuntu&hl=en&gl=gr&strip=1&vwsrc=0

If this doesn't work, please search for "atman iot" and then view the
cached page. One of the three tabs is the "Text-only version".

Here is a print screen just in case.

Please don't hesitate to contact me if you have any questions.

With regards,

Khalil Khoury

**Comment by slorber** [comment]
thanks ;) that's enough for me
