### ISSUE TITLE
Relative link can break when current URL contains hash to a section

### ISSUE THREAD

**Issue by otakustay** [facebook/docusaurus#4099]
## 🐛 Bug Report

(A clear and concise description of what the bug is)

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## To Reproduce

1. Open https://ecomfe.github.io/reskript/docs/getting-started
2. Click "第一个应用" under "应用开发" on the left (sorry for these Chinese text), notice current URL is https://ecomfe.github.io/reskript/docs/app/quick-start

    ![image](https://user-images.githubusercontent.com/639549/105698657-23056080-5f41-11eb-9ef1-391bcadb96aa.png)

3. Refresh this page, now URL becomes https://ecomfe.github.io/reskript/docs/app/quick-start/, notice the ending `/`
4. Click "快速上手", a relative link referecing `../getting-started`

    ![image](https://user-images.githubusercontent.com/639549/105698981-a6bf4d00-5f41-11eb-86e8-80810b5cfef3.png)

5. Page goes 404

## Expected behavior

Back to previous page, reclick "第一个应用" under "应用开发", this will remove the ending `/` from URL. then click that relative link works as expected.

## Actual Behavior

It seems refreshing page in Chrome will add an ending `/` to URL, which breaks relative links.

## Your Environment

- Public source code: https://github.com/ecomfe/reskript (under `docs` branch, `site` folder)
- Public site url: https://ecomfe.github.io/reskript
- Docusaurus version used: 2.0.0-alpha.70
- Environment name and version (e.g. Chrome 78.0.3904.108, Node.js 10.17.0): Chrome 88.0.4324.96
- Operating system and version (desktop or mobile): macOS 11.1

**Comment by slorber** [comment]
Hi,

This trailing slash issue is related to your host provider that does not support static files such as `./getting-started/index.html` but prefers `./getting-started.html`

Unfortunately GH pages does not have any option to configure that at the host level. Netlify would allow you to disable the "pretty URL" option and get this solved.

I'm trying to figure out a solution as part of https://github.com/facebook/docusaurus/issues/3372 (so I'm closing this one), but it requires studying the behavior of all static hosting providers.

In the meantime here's how I fixed this issue on ReactNative website (also hosted on GH pages): https://github.com/facebook/react-native-website/pull/2297
