### ISSUE TITLE
When using multiple docs plugins, if the `path` is a prefix of the `path` of another plugin it will cause errors

### ISSUE THREAD

**Issue by vjpr** [facebook/docusaurus#4102]
Solution is to add a trailing slash to the `include` rule here: https://github.com/facebook/docusaurus/blob/ae45b11bbb32513a8cb44da163f096c00868a21d/packages/docusaurus-plugin-content-docs/src/index.ts#L347

This caused me the error outlined here: https://github.com/facebook/docusaurus/issues/4101

E.g.

If you have a plugin with `path: clis/cli` and then a `path: clis/cli-foo`, the first plugin will attempt to process the second plugins mdx files and it will mess with the mdx metadata code. See https://github.com/facebook/docusaurus/issues/4101.

```
{ include: 'clis/cli' }

{ include: 'clis/cli-foo' }
```

**Comment by slorber** [comment]
Thanks, this has been fixed already by https://github.com/facebook/docusaurus/pull/3970

Will be in next release
