### ISSUE TITLE
PWA Lighthouse start_url issues

### ISSUE THREAD

**Issue by slorber** [facebook/docusaurus#4108]
The Lighthouse PWA audit report some errors on Docusaurus v2 site itself, that we should figure out how to fix.

![image](https://user-images.githubusercontent.com/749374/106004425-7eeff680-60b3-11eb-89c1-b801cba19bf2.png)

This may be because the PWA offline support is only enabled with an "activation strategy": https://v2.docusaurus.io/docs/next/api/plugins/@docusaurus/plugin-pwa/#offlinemodeactivationstrategies

So by default, the site homepage does not really have any offline support?

**Comment by Josh-Cena** [comment]
Should be fixed already by #4377🤔 The only issue Lighthouse reports right now is the icon not being maskable
