### ISSUE TITLE
Github Pages + Cloudflare Custom Domain Error

### ISSUE THREAD

**Issue by massoudmaboudi** [facebook/docusaurus#4111]
## 🐛 Bug Report

Because of my preference, I decided to deploy my website on Github pages. Also, I want to add my custom domain to it.
Unfortunately, my domain provider doesn't allow me to add A or CNAME record. so, I decided to use Cloudflare to help me with it.
It means I will add my website to Cloudflare, then I will configure my CNAME and A records. Then I will provide me 2 DNS records and I will put them in my domain provider. The expected behavior is to see the website goes live, but nope. It shows a baseurl error.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## To Reproduce

If possible, use https://new.docusaurus.io to create a CodeSandbox reproducible demo of the bug.

1. A working local website is needed to be there.
2. Setting the setting of the `docusaurus.config.js` like below:

```
  url: 'https://massoudmaboudi.github.io',
  baseUrl: '/datagit_v2.docusaurus/',
  organizationName: 'massoudmaboudi',
  projectName: 'datagit_v2.docusaurus',
```

3. Use `GIT_USER=massoudmaboudi yarn deploy` to deploy the website to Github pages. Now the website is accessible via `https://massoudmaboudi.github.io/datagit_v2.docusaurus/` which works perfectly.
4. Create an account in `cloudflare.com` and add the website with the below DNS configuration:

![image](https://user-images.githubusercontent.com/18216265/106105900-b1672580-617f-11eb-977f-8680cec5995c.png)

5. Add the custom domain to the Github Pages like below:

![image](https://user-images.githubusercontent.com/18216265/106105984-cfcd2100-617f-11eb-9b6a-3172a44972c4.png)

## Expected behavior

To see the working website on datagit.ir

## Actual Behavior

It shows the error of the baseurl like below:

![image](https://user-images.githubusercontent.com/18216265/106106186-1e7abb00-6180-11eb-865b-2e61451369be.png)

I tried the suggestion to change the baseurl to `/` instead of `/datagit_v2.docusaurus/` but didn't work.

_**I should mention that when we use Cloudflare, there is no need to have a CNAME inside the `static` folder based on the search I did.**_

## Your Environment

- Public source code: https://github.com/massoudmaboudi/datagit_v2.docusaurus
- Public site url:datagit.ir
- Docusaurus version used: 2.0.0-alpha.70
- Environment name and version (e.g. Chrome 78.0.3904.108, Node.js 10.17.0): Node.js v15.6.0 Chrome Version 88.0.4324.96 (Official Build) (arm64)
- Operating system and version (desktop or mobile): macOS Big Sur v11.1

**Comment by massoudmaboudi** [comment]
I changed the setting of the docusaurus.config.js like below:

```
  url: 'https://massoudmaboudi.github.io',
  baseUrl: '/',
  organizationName: 'massoudmaboudi',
  projectName: 'datagit_v2.docusaurus',
```

and the problem solved.

**Comment by slorber** [comment]
great

> I tried the suggestion to change the baseurl to / instead of /datagit_v2.docusaurus/ but didn't work.

so using the suggestion '/' did work right? 

The CNAME file is required for Github Pages, not for Cloudflare
