### ISSUE TITLE
Incorrect path for relative links in truncated blog post

### ISSUE THREAD

**Issue by ianschmitz** [facebook/docusaurus#4119]
## 🐛 Bug Report

This appears to be somewhat related to #3250. 

Links in truncated posts can be broken if they are relative to the post. Perhaps the post links should be massaged to match the expected path based on the final post slug?

Similarly there's no obvious way to construct a relative link from the post to a docs page. The best I could come up with was to convert the blog post to `.mdx` and use `<Link>` instead.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## To Reproduce

https://codesandbox.io/s/wonderful-hill-ri0fe?file=/blog/2019-05-30-welcome.md

1. Navigate to blog posts page
1. Click on link in truncated post
1. Notice it tries to navigate to a header on the `/blog` page which doesn't exist

## Expected behavior

Links work in both the truncated post and in the full post.

## Actual Behavior

The header link works in the full blog post, but doesn't work in the truncated post.

## Your Environment

- Public source code:
- Public site url:
- Docusaurus version used: `2.0.0-alpha.70`
- Environment name and version (e.g. Chrome 78.0.3904.108, Node.js 10.17.0):
- Operating system and version (desktop or mobile):

**Comment by slorber** [comment]
I understand the problem, and we don't do any "magic" to fix the link.

> Links in truncated posts can be broken if they are relative to the post. 

If you use a relative link (including an anchor link like `[link](#anchor)`, it is your responsibility to ensure that it will work everywhere it will be rendered.

> Perhaps the post links should be massaged to match the expected path based on the final post slug?

We could, but this feels like magic to me, as an anchor link becomes magically a real non-anchor link depending on where it's rendered.

This would add little value and is probably not so simple, add maintenance burden for us, and there is not just the blog post list, also the tags pages etc...

My reco would rather be to recommend:
- to avoid links in summary text
- or to use only links with absolute paths, such as `[link](/blog/my-blog-post#anchor)` if you really want the link to appear in the summary, as it will render fine consistently

Such issues can be caught by the broken link checker (preventing bad deploys), and there is a good workaround, so I don't think we should implement anything.

> Similarly there's no obvious way to construct a relative link from the post to a docs page. The best I could come up with was to convert the blog post to .mdx and use <Link> instead.

In the same way, you should use absolute paths. There is no need for mdx/Link to solve this problem.

----

Let me know if my suggestions work for your usecase

**Comment by ianschmitz** [comment]
Agreed with everything you said.

> In the same way, you should use absolute paths. There is no need for mdx/Link to solve this problem

My understanding was Link and useBaseUrl took into account the configured baseUrl of the project? I guess the link checker would catch this too if baseUrl was changed?

**Comment by slorber** [comment]
Actually I'm not a fan of `useBaseUrl` and would like to deprecate it.

I made it so that all absolute links are not baseurl sensitive (ie useBaseUrl is applied automatically), so it's basically useless in most cases.

**Comment by ianschmitz** [comment]
> I made it so that all absolute links are not baseurl sensitive (ie useBaseUrl is applied automatically), so it's basically useless in most cases.

Ah this is news to me! Is this a recent change? I have used it in quite a few places so would love to remove if it's no longer necessary. This would also be the case for blog posts i assume?

I'll close this as i believe you've answered my original issue.

**Comment by slorber** [comment]
As long as you use markdown links or `<Link/>` Docusaurus will try to prefix all absolute paths with the baseUrl (not relative ones, not fully qualified links including the protocol) 

Will document this behavior better right now. Not sure about all the impacts of removing `useBaseUrl` but at least I'd rather deprecate it and see if users complain

**Comment by slorber** [comment]
https://github.com/facebook/docusaurus/pull/4126
