### ISSUE TITLE
Replace NodeJS "path" with "upath": normalize paths to posix style

### ISSUE THREAD

**Issue by slorber** [facebook/docusaurus#4124]
## 💥 Proposal

https://www.npmjs.com/package/upath#why

It could be less painful to ensure Windows support if all paths where using posix style (`/` separator) instead of being platform dependent. 

Windows/NodeJS is able to understand both `/` and `\\` so it would be nice to normalize on all paths on posix style.

This could prevent issues we often see after committing, when the CI (build or tests) fails but only on Windows, such as:

![image](https://user-images.githubusercontent.com/749374/106281132-17ff4880-623f-11eb-9bed-bf8e93a7574b.png)

My idea would be to:
- Use "upath" everywhere
- Use `upath.normalize()` everywhere instead of our custom `posixPath()` fn.
- Prevent "path" from being imported with an ESLint rule

**Comment by armano2** [comment]
you don't need some custom package for this as node supports this out of the box, 

eg. instead of `path.join` just use `path.posix.join` 
https://nodejs.org/api/path.html#path_path_posix

**Comment by slorber** [comment]
Looks like @armano2 you mentioned `path.posix` instead of `upath` and deleted that comment?

Both can be a solution, but apparently, they do not have the exact same behavior: https://github.com/anodynos/upath/issues/26

**Comment by armano2** [comment]
that's why i deleted my comment :)

**Comment by slorber** [comment]
Not sure we need upath, we don't often get windows path issues anymore after the problem has been understood
