### ISSUE TITLE
Allow using extension-less URLs

### ISSUE THREAD

**Issue by julen** [facebook/Docusaurus#413]
### Is this a bug report?

No.

### Have you read the [Contributing Guidelines](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md)?

Yes.

### Environment

Any.

### Expected Behavior

Since [Docusaurus has been designed to work well with GitHub Pages](https://docusaurus.io/docs/en/publishing.html#using-github-pages), it would be ideal if the links it generates via markdown references also supported extension-less URLs.

Note GitHub supports this out-of-the box: simply remove the `.html` suffix from any published pages and it just works.

### Actual Behavior

Docusaurus always creates links with the `.html` extension appended, and there is no way to change that.

In practical terms, this means there's no chance of using GitHub Pages' feature of removing file extension suffixes from URLs without sacrificing consistency.

### Reproducible Demo

Example:
* https://prettier.io/docs/en/install.html
* https://prettier.io/docs/en/install

As a side note, also note how `index.html` can also be removed (which in conjunction with #323 would allow for _clean_ URLs):
* https://prettier.io/docs/en/index.html
* https://prettier.io/docs/en/

**Comment by JoelMarcey** [comment]
Hi @julen - I agree we should support this. Thanks!

**Comment by InternetExplorer7** [comment]
Hi, I think I've addressed this issue in the referenced issue above! Please feel free to take a look!

**Comment by InternetExplorer7** [comment]
For some reason, http://localhost:3000/blog/.../introducing-docusaurus/index.html
gives a page with a response code of 200 and a blank page is rendered. Any idea why that may be returning a 200 response?

Other than that, every page still works the same with extensions, and every page (except this /blog one) works without the .html extension!

**Comment by yangshun** [comment]
Re-post of my comment in #515 in case anyone wants to take this up in future:

> Changing the routing in the server only works in development mode when the pages are being served via Express. In production, the site is built as static files and is served like a file directory server. After the build command is ran, th extensionless URLs wouldn't work because there's no `/path/index.html` file present when you try to access `/path`.
>
> Try running `yarn build` and running a local webserver in the `build` directory and see for yourself. For example, for `/path/installation.html` you would need to generate the following directories and files:

```
├── path
│   ├── installation.html
│   └── installation
│       └── index.html
```

> so that the web server will serve `/path/installation/index.html` when someone tries to access `/path/information`. Generating `/path/installation.html` is for preserving backward compatibility.
>
> GitHub Pages serves `/path/installation.html` if a user tries to access `/path/installation` when `/path/installation/index.html` does not exist, so if we are only targeting GitHub pages hosting, this is a non-issue. But since we want to support any static file hosting service, this support is necessary.

**Comment by endiliey** [comment]
Hi, I wanted to try working on this. But I have few questions:
1. Am I correct to assume that we need this feature more on the `production` site ?
2. Do we generate the cleanUrl file on demand only, or every build will have both files? (when `cleanUrl` is `true` in `siteConfig.js`)
```
├── path
│   ├── installation.html
│   └── installation
│       └── index.html
```
