### ISSUE TITLE
Docker build is crash in setp `yarn install`

### ISSUE THREAD

**Issue by yishuiliunian** [facebook/docusaurus#4131]
## 🐛 Bug Report

Docker build is crash in setp `yarn install`

log is :

```
error An unexpected error occurred: "ENOENT: no such file or directory, lstat '/app/website/node_modules/gifsicle/\u0001\f3@@@�'".

```
### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

yes

## To Reproduce

If possible, use https://new.docusaurus.io to create a CodeSandbox reproducible demo of the bug.

(Write your steps here:)

1. use an docker in resperry
2. run docker build .

## Expected behavior

docker build success

## Actual Behavior

Docker build is crash in setp `yarn install`

log is :

```
error An unexpected error occurred: "ENOENT: no such file or directory, lstat '/app/website/node_modules/gifsicle/\u0001\f3@@@�'".

```

## Your Environment

- Public source code: https://cocoadepot.github.io/
- Public site url: https://cocoadepot.github.io/
- Docusaurus version used: 
- Environment name and version (e.g. Chrome 78.0.3904.108, Node.js 10.17.0):
- Operating system and version (desktop or mobile): ubuntu (resperry)

**Comment by slorber** [comment]
Hi,

It seems you are using v1 right?

We encourage users to migrate to v2.

This is a problem related to Gifsicle, which apparently is used in v1 to resize gifs. And it seems to fail to install, which is somehow outside the scope of Docusaurus but should rather be reported on Gifsicle repos. What I would try is to use another Docker image, or re-generate my yarn.lock file
