### ISSUE TITLE
About gitignore

### ISSUE THREAD

**Issue by balancelove** [facebook/Docusaurus#415]
Hi, I have a question about `.gitignore`.
When I init my project, `.gitignore` in `website/`,but in this file, ignore list is `website/yarn.lock`,I think this should be `yarn.lock`. `website/yarn.lock` match file like this `website/website/yarn.lock`.

**Comment by JoelMarcey** [comment]
@balancelove Hi. I think there is a bug in the creation of the `.gitignore` when you run `docusaurus-init`. Is that what you ran to get that bad `.gitignore` file?

**Comment by yangshun** [comment]
Just confirmed this bug. Refer to the following screenshot

<img width="575" alt="screen shot 2018-04-07 at 11 54 03 am" src="https://user-images.githubusercontent.com/1315101/38459103-796111d6-3a5a-11e8-961c-d1faf0217306.png">

**Comment by JoelMarcey** [comment]
@yangshun, @yykamei - see #533 for a fix (I hope 😄)
