### ISSUE TITLE
opensearch.xml template does not respect `baseUrl` option

### ISSUE THREAD

**Issue by lunelson** [facebook/docusaurus#4151]
On sites which are built using [the `baseUrl` option](https://v2.docusaurus.io/docs/docusaurus.config.js/#baseurl), the `<link rel="search">` tag in the `head` is generated correctly, and the `opensearch.xml` file is generated in _the right location_ wrt the supplied `baseUrl`, but __the contents of `opensearch.xml` file are incorrect__.

Consider [Facebook Metro](https://facebook.github.io/metro/), which is cited in the docs as an example of a `baseUrl` deployment. The `link` tag on those pages is correct...

```html
<link rel="search" type="application/opensearchdescription+xml" title="Metro" href="/metro/opensearch.xml">
```

...but the `opensearch.xml` contents are not. The `Image`, `Url` and `moz:SearchForm` tags all fail to include the `baseUrl` as part of their urls, which breaks the function, and/or causes browsers to register an incorrect search URL for the entire domain `facebook.github.io`.

```xml
<OpenSearchDescription xmlns="http://a9.com/-/spec/opensearch/1.1/" xmlns:moz="http://www.mozilla.org/2006/browser/search/">
<ShortName>Metro</ShortName>
<Description>Search Metro</Description>
<InputEncoding>UTF-8</InputEncoding>
<Image width="16" height="16" type="image/x-icon">https://facebook.github.io/img/favicon.png</Image>
<Url type="text/html" method="get" template="https://facebook.github.io/search?q={searchTerms}"/>
<Url type="application/opensearchdescription+xml" rel="self" template="https://facebook.github.io/opensearch.xml"/>
<moz:SearchForm>https://facebook.github.io</moz:SearchForm>
</OpenSearchDescription>
```

In the case of [Facebook Metro](https://facebook.github.io/metro/), the `opensearch.xml` file should look like this:

```xml
<OpenSearchDescription xmlns="http://a9.com/-/spec/opensearch/1.1/" xmlns:moz="http://www.mozilla.org/2006/browser/search/">
<ShortName>Metro</ShortName>
<Description>Search Metro</Description>
<InputEncoding>UTF-8</InputEncoding>
<Image width="16" height="16" type="image/x-icon">https://facebook.github.io/metro/img/favicon.png</Image>
<Url type="text/html" method="get" template="https://facebook.github.io/metro/search?q={searchTerms}"/>
<Url type="application/opensearchdescription+xml" rel="self" template="https://facebook.github.io/metro/opensearch.xml"/>
<moz:SearchForm>https://facebook.github.io</moz:SearchForm>
</OpenSearchDescription>
```

**Comment by lunelson** [comment]
thanks @slorber 🙏🏻

**Comment by slorber** [comment]
thank @lex111  :)
