### ISSUE TITLE
Controlling the Location of the Search Bar in v2

### ISSUE THREAD

**Issue by AudreyKj** [facebook/docusaurus#4157]
I'm trying to change my search bar placement and noticed that the section [**Controlling the Location of the Search Bar** in V1 ](https://docusaurus.io/docs/en/search#docsNav) is missing in V2 (https://v2.docusaurus.io/docs/search/), there is no documentation about changing the placement of the search bar.

**Comment by slorber** [comment]
Related to https://github.com/facebook/docusaurus/discussions/4116

You are right, this is not supported for now, and you need to swizzle the theme navbar component to change the searchbar location.

We'll introduce a `{type: "searchBar"}` navigation item later

**Comment by AudreyKj** [comment]
thanks a lot for your quick reply!
