### ISSUE TITLE
Support React 17

### ISSUE THREAD

**Issue by radekmie** [facebook/docusaurus#4165]
## 🚀 Feature

Support for React 17. Please note that I'm not requesting a migration, but rather check, whether Docusaurus 2 works with React 17 and if so, update `peerDependencies` version respectively, most probably to `^17.0.0 || ^16.8.4`.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes.

## Motivation

None of the [breaking changes](https://github.com/facebook/react/blob/master/CHANGELOG.md#1700-october-20-2020) seem to affect Docusarus in an unexpected way, therefore I guess it should be quick and easy.

My goal is to update [`uniforms`](https://github.com/vazco/uniforms) repo to use React 17 and Docusaurus is the last incompatible package.

**Comment by slorber** [comment]
Yes definitively, but it's not so simple.

We use react-loadable as a core lib that does not support React 17.

![image](https://user-images.githubusercontent.com/749374/106883076-c4c64380-66df-11eb-8a79-428aa9cd5bf0.png)


As the lib is not very maintained, we should likely migrate to loadable-components, or create our own fork of react-loadable (probably the simplest solution)

**Comment by HonkingGoose** [comment]
Also seems related to #3617.

**Comment by lex111** [comment]
I don’t really understand how this issues is related to Docusaurus in your case, because your site is not place in separate package?

https://github.com/vazco/uniforms/blob/ec5030886f0af285657583e58654b29ef280c153/packages/uniforms/package.json#L27-L29

As for `react-loadable`, it implicitly supports React 17, doesn't it?

https://github.com/jamiebuilds/react-loadable/blob/6201c5837b212d6244c57f3748f2b1375096beeb/package.json#L45-L47

**Comment by radekmie** [comment]
@lex111 it's because we use Lerna to manage the repo and the website (using Docusaurs) has a playground, that imports the packages. To make it work, we either have to have the same versions everywhere or install non-local (npm) versions of the packages. In this case, we lose the functionality to develop the website using local packages completely.

**Comment by slorber** [comment]
> As for react-loadable, it implicitly supports React 17, doesn't it?

![image](https://user-images.githubusercontent.com/749374/107762113-ccfc2f80-6d2c-11eb-9854-50bd9c94a034.png)

It accepts any React as a dependency, but this is quite unsafe in practice.

componentWillMount should have been completely removed in React 17, but it seems the removal has been postponed to React 18, so my assumption was wrong and we are lucky this time! (cf my comment: https://github.com/facebook/docusaurus/pull/4218#issuecomment-778136966)

I think we can safely upgrade to React 17, but we likely won't be lucky to upgrade to React 18 without removing/fixing react-loadable

**Comment by radekmie** [comment]
@slorber: any chance for a release anytime soon?

**Comment by slorber** [comment]
@radekmie we'll release soon, maybe next week.

In the meantime the `@canary` npm dist tag will get you React 17.

(it's not so risky to use IMHO. If we release it's basically just putting a release tag on an existing canary release)
