### ISSUE TITLE
Couldn't Visit the page without its prefix

### ISSUE THREAD

**Issue by KishaniKandasamy** [facebook/docusaurus#4181]
## 🐛 Bug Report

My docs contains a downloads page . when routing to download page I couldn't  visit the  page without its docs prefix.I need **downloads only to be active** but here both doc and downloads   are in active.
I change the path in  docusaurus.config,js and try to solve this but It won't work as I expected.Can anyone help me? 
![105868307-03e5fc00-6031-11eb-81f8-ed02465e2ea1](https://user-images.githubusercontent.com/53715187/107042421-bfecb700-67e7-11eb-96f6-4ae550208856.png)

I change my docusaurus.config.js as
 "themeConfig": {
    "navbar": {
      "title": "Apache APISIX™",
      "style": 'primary',
      "logo": {
        "src": "img/logo.png"
      },
      "items": [
       
        {
          **"to": "/downloads",**
          "label": "Downloads",
          "position": "left"
        },
and change the route.js in .docusaurus  to 
{
  path: '/downloads',
  component: ComponentCreator('/docs/downloads','7eb'),
  exact: true,
},
but It won't work .

**Comment by HonkingGoose** [comment]
For anybody who wants to help, here is the source repository for the website: https://github.com/KishaniKandasamy/apisix-website

**Comment by slorber** [comment]
Thanks @HonkingGoose 

If it's a standalone page not in any sidebar, you'd rather make it a "markdown page":
https://v2.docusaurus.io/docs/next/creating-pages/#add-a-markdown-page

Please keep issues for bug reports, and use github discussions or Discord if you struggle to achieve your goal
