### ISSUE TITLE
Support for Code Tabs

### ISSUE THREAD

**Issue by vamsi3** [facebook/docusaurus#4184]
## 🚀 Feature

Support for Code Tabs primarily in docs which is similar to this from Docusaurus v1.

https://docusaurus.io/docs/en/doc-markdown#language-specific-code-tabs

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## Motivation

Many open-source projects involve using multiple languages in their documentation.

## Pitch

Even few years ago in Docusaurus v1, this feature was well requested by the community (#103 and corresponding PR #1063). I think the popularity of the feature remains the same, especially from a documentation viewpoint.

**Comment by lex111** [comment]
Please read this doc https://v2.docusaurus.io/docs/next/markdown-features/tabs

**Comment by YanDevDe** [comment]
@lex111 can you give us hint where we should read on this doc page? There is no mention how we can include code block (or markdown) inside of the tab on this page.

**Comment by lex111** [comment]
Isn't that what you need? https://docusaurus.io/docs/next/markdown-features/code-blocks#multi-language-support-code-blocks

**Comment by YanDevDe** [comment]
Yup! This was what I was searching for it! Thank you!

**Comment by lex111** [comment]
Searching by docs is your best friend, don't forget this.. I don't think it's hard to find it yourself. But if you have difficulties with this, you could create an issue (we want our docs to be as clear and accessible as possible).

**Comment by YanDevDe** [comment]
Actually I was searching for it and I try to avoid creating issues - only if I have to!

I would never imagined to find Tabs related in "Code-Blocks" because I was 100% focusing on "Tabs" documentation how I can use markdown inside of tabs - There is no mention about this. 

https://docusaurus.io/docs/next/markdown-features/tabs

I'll create issue later for this.

**Comment by lex111** [comment]
Ah, yes. That link is no longer relevant, we've reorganized our docs, so the content structure has changed. But in any case, we welcome the creation of issues related with docs!
