### ISSUE TITLE
Use the color-scheme CSS property

### ISSUE THREAD

**Issue by slorber** [facebook/docusaurus#4192]
## 💥 Proposal

There's a CSS property for color-scheme that I was not aware of and that could be useful for Docusaurus:
https://twitter.com/argyleink/status/1358060379000037377
https://drafts.csswg.org/css-color-adjust/#color-scheme-prop

**Comment by gurrrung** [comment]
As far as I have understood from the article, we just have to use the color-scheme `dark` for dark mode and color-scheme `light` for light mode? These should switch when the user switches dark to light or vice versa, right?

**Comment by slorber** [comment]
@gurrrung the first step is actually to find out how this CSS property can be useful in any way for Docusaurus.

I have no time currently investigate this, and have not really read the links yet.

Before rushing on implementing anything, the first step is to find out whether we want to use this CSS property or not. We may decide that it's useless for our case and just close this issue.

**Comment by lex111** [comment]
In fact, this is really not very useful for us (at least for the classic theme).

**Comment by slorber** [comment]
let's close this then, it was just an idea to explore
