### ISSUE TITLE
Private Project 

### ISSUE THREAD

**Issue by Tautorn** [facebook/Docusaurus#420]
I can use Docusaurus in a private project?

**Comment by richardzcode** [comment]
Docusaurus just generate static website for you. I don't think there is any problem with private project. Just be aware your GitHub pages are public even if project is private.

**Comment by JoelMarcey** [comment]
Hi @Tautorn. Exactly what @richardzcode said. You can use this on any GitHub project that is private. Just know that does in the `gh-pages` branch will be public even if your repo is private.

**Comment by JoelMarcey** [comment]
I am going to close this. Reopen if you have any questions. Thanks!

**Comment by Tautorn** [comment]
Thx so much!
