### ISSUE TITLE
I want to give my opinion on version 2

### ISSUE THREAD

**Issue by lokha** [facebook/docusaurus#4213]
good afternoon, I'll start by saying that your documentation is very good. and I chose you by comparing with many options  

i am using the first version of your documentation  

you are now actively developing version 2. but why then did I install the first version for myself?

I don't like the design of version 2. The first version was nicer to the eye. I'm talking specifically about the documentation pages  

in general, while you haven't finished the second version, it may not be too late to fix the design. It's hard for me to explain what exactly is wrong, I'm not a designer. in version 2, the fonts, text sizes, colors are different and as a result it is not read as pleasantly as it was in version 1  

sorry my bad english, i translated in translator

who agree with me, write +  
maybe I'm not the only one who thinks so, thank you all again. your service is great (version 1)

**Comment by slorber** [comment]
> good afternoon, I'll start by saying that your documentation is very good. and I chose you by comparing with many options

Thanks

> you are now actively developing version 2. but why then did I install the first version for myself?

How can I answer that 😅  we advise to use v2

![image](https://user-images.githubusercontent.com/749374/107622165-bdf77d80-6c57-11eb-83c7-4c1a8fd79241.png)

> I don't like the design of version 2. The first version was nicer to the eye. I'm talking specifically about the documentation pages

The v2 is fully customizable, so even if the default look-and-feel does not please you, you can achieve what you want anyway.

Look at the showcase for v2 site examples:
https://v2.docusaurus.io/showcase

With custom designs:
- https://reactnative.dev/
- https://vector.dev/
- https://developers.diem.com/
- https://questdb.io/

> in general, while you haven't finished the second version, it may not be too late to fix the design. It's hard for me to explain what exactly is wrong, I'm not a designer. in version 2, the fonts, text sizes, colors are different and as a result it is not read as pleasantly as it was in version 1

Changing everything about the current design will annoy many v2 users. We have way more v2 users than v1 users (https://www.npmtrends.com/docusaurus-vs-@docusaurus/core)

We'll definitively try to improve (I share some of your opinions about text readability), but it's hard to do changes if you don't have any concrete suggestions to make

I'm closing as I'm not sure about the value of leaving this issue open. Please discuss a specific detail you want to be changed if you have a more concrete idea regarding what we should do.

**Comment by lokha** [comment]
ok, so here's a suggestion: make the background darker like it did in version 1 and / or make the text color lighter. because when completely black text on a completely white background, it looks too contrast

for example, these themes look nicer to me than the standard one:  
https://infinum.github.io/eightshift-docs/docs/basics/basics  
https://support.hashnode.com/docs/mapping-domain/
