### ISSUE TITLE
Embedding animation (script) in document

### ISSUE THREAD

**Issue by carlskii** [facebook/docusaurus#4217]
Hi, I need to embed some animations into my documents. These are created in Tumult Hype and would normally embedded as scripts within a div. e.g.

```
<div id="venafiintegrations_hype_container" class="HYPE_document" style="margin:auto;position:relative;width:1500px;height:800px;overflow:hidden;">
		<script type="text/javascript" charset="utf-8" src="Venafi-Integrations.hyperesources/venafiintegrations_hype_generated_script.js?55179"></script>
	</div>
```

However this seems to break the MDX parsing. Is there a way to deal with this uses case using plugins ?

**Comment by slorber** [comment]
Hi,

We have github discussions and Discord for questions.

Yes it breaks MDX parsing, as documented you have to use JSX and curly braces. 

```
      <div id="venafiintegrations_hype_container" className="HYPE_document" style={{margin: 'auto', position: 'relative', width: '1500px', height: '800px', overflow: 'hidden'}}>
      </div>
```

Also I don't think React would allow you to add a script inline directly in a mdx doc like that, but you can use site config or `@docusaurus/Head` instead.

I don't know anything about Tumult Hype
