### ISSUE TITLE
@docusaurus/init@latest not compatible with Node LTS

### ISSUE THREAD

**Issue by jcayzac** [facebook/docusaurus#4227]
## 🐛 Bug Report

`@docusaurus/init@latest` has transitive dependencies on `chokidar@2` and `fsevents@1`, which are broken on Node 14+.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes.

## To Reproduce

1. `npx -y @docusaurus/init@latest init docusaurus-docs classic`

## Expected behavior

Project setup that is compatible with Node LTS.

## Actual Behavior

```
warning @docusaurus/core > webpack-dev-server > chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
warning @docusaurus/core > webpack-dev-server > chokidar > fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
warning @docusaurus/core > webpack > watchpack > watchpack-chokidar2 > chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
```

## Your Environment

- Docusaurus version used: `npx -y @docusaurus/init@latest -- --version` reports `2.0.0-alpha.70`.
- Environment name and version (e.g. Chrome 78.0.3904.108, Node.js 10.17.0): Node.js 14.0.0.
- Operating system and version (desktop or mobile): macOS 11.2.

## Reproducible Demo

The problem happens before running docusaurus or making a website.

**Comment by RDIL** [comment]
Nothing we can do about this, its all downstream dependencies.  You will need to file an issue in the WDS repository.

**Comment by slorber** [comment]
@RDIL will upgrading to Webpack 5 upgrade the deps? If that's the case I'd close it as "duplicate" of the Webpack 5 migration

In my experience despite this warning Docusaurus works fine on Node 14

**Comment by RDIL** [comment]
Yeah, it should work fine on Node 14, and the update should in theory address this.

**Comment by slorber** [comment]
thanks

so lets's close in favor of https://github.com/facebook/docusaurus/issues/4027

If this is not fixed after upgrading to Webpack 5, please re-open
