### ISSUE TITLE
yarn start not working

### ISSUE THREAD

**Issue by ChangeHow** [facebook/docusaurus#4245]
## 🐛 Bug Report

after installed all depencies for docusaurus@v2@latest and run `yarn start` in a few minutes, the progress of building client files still in zero-percent. like the screenshot below.

![image](https://user-images.githubusercontent.com/23733347/108322159-19011580-7200-11eb-89bc-4b64e3aea1a4.png)
but `yarn build` and `yarn serve` working well.

## To Reproduce

1. npx @docusaurus/init@latest init site classic
2. cd site
3. yarn start

## Expected behavior

I think `yarn start` will work like `yarn build` and `yarn serve` but it didn't.

## Actual Behavior

![image](https://user-images.githubusercontent.com/23733347/108322286-4221a600-7200-11eb-8cf6-b1fd5c5f4abc.png)

## Your Environment

- Public source code:
- Public site url: -
- Docusaurus version used: 2.0.0-alpha.70
- Environment name and version (e.g. Chrome 78.0.3904.108, Node.js 10.17.0):
  - Node@12.20.1
  - Yarn@1.22.10
- Operating system and version (desktop or mobile): Macbook pro M1 version

## Reproducible Demo

If possible, use https://new.docusaurus.io to create a CodeSandbox reproducible demo of the bug.

(Paste the link to an example repo, including a `docusaurus.config.js`, and exact instructions to reproduce the issue.)

**Comment by slorber** [comment]
Hi,

It is not clear to me what is not working exactly, you don't really explain.

Can you submit a repro of your issue,  including the Yarn lockfile, and explain what's not working exactly?

Maybe it's related to Macbook Pro M1? Could you try  the same on another computer?

**Comment by ChangeHow** [comment]
> Hi,
> 
> It is not clear to me what is not working exactly, you don't really explain.
> 
> Can you submit a repro of your issue, including the Yarn lockfile, and explain what's not working exactly?
> 
> Maybe it's related to Macbook Pro M1? Could you try the same on another computer?

Thank you for answer,

First of all,  i think i don't explain what i met exactly. After running `yarn start` in my site dir a few minutes, the pregress of building client files contain **0**, so i took this screenshot.

I just use latest docusaurus to initialized my website in my components-lib, after then(installed all the dependencies), i run `yarn start`, but my console seem to get stuck so i have to use `ctrl-c` to force terminating it.

I think it's maybe the bug for node running under **iTerm ARM**, so i turn it into Rosetta2, but it still on. And i tried downgrade version of docusaurus(i have tried ver.60 ver.50), but it's not working.

**Comment by ChangeHow** [comment]
That so funny,

It's seem repaired by itself when i try to re-initialize my project to get yarn-lock and output during initializing.

I think the problem i met maybe the listening port get took up or anything else.

It's maybe a useless issue.

**Comment by petrbroz** [comment]
FWIW I just ran into the same problem:

1. Initialized a new local project: `npx @docusaurus/init@latest init docusaurus-test classic`
2. Cd'd into the created folder: `cd docusaurus-test`
3. Built the project: `yarn build` (this step took approx. 30 seconds)
4. Started the project: `yarn start`

The thing is - the `yarn start` command also seems to include some compilation step, and in my case the compilation took almost 3 minutes. 3 minutes during which http://localhost:3000 is not accessible even though the `yarn start` command says it is. That's probably what the original bug report was about.

**Comment by slorber** [comment]
@petrbroz each issue of this kind is highly related to your env. If you don't share env similarities with original issue, it might not be related at all. We regularly have some issues reported due to using Windows WSL for example, but here the author is using a mc. The init project shouldn't take 3min to build anyway. Try installing it to another project, or another user session on your computer, or other things like that.

**Comment by petrbroz** [comment]
@slorber sorry, you're right. Let me submit this as a separate issue with more details.

**Comment by DonnieTD** [comment]
Just in case someone is in my situation:

If on nx using pnpm and not using the generator do

pnpm dlx create-docusaurus@latest site-name classic --typescript

Instead of generator or

npx create-docusaurus@latest site-name classic --typescript

First one hangs, second one is instant
