### ISSUE TITLE
'useThemeContext' in nested Component?

### ISSUE THREAD

**Issue by bennodev19** [facebook/docusaurus#4258]
## 🐛 Bug Report

Note: I am not sure whether this is a bug or not.. but I wanted to mention it at least.

As soon as I outsource a Component, which has some relation to the 'useThemeContext' hook.
-> the Component is no direct child of the Layout View..
I am getting this error.  (see below)
![grafik](https://user-images.githubusercontent.com/57860196/108605607-5f4ba580-73b5-11eb-95c2-2aed5a4b200b.png)
Technically seen the Error is correct, but I am only using this outsourced Components in the Layout View. Well docusaurus doesn't know.. 
![grafik](https://user-images.githubusercontent.com/57860196/108605644-bf424c00-73b5-11eb-8745-f4bde0dad9fd.png)
In this case the `SectionScroller` makes the problems, because it uses the 'CodeBlock' which internally uses the 'useThemeContext' Hook. -> Error

My current workaround is to create my own instance of the theme type..
but well this isn't a clean way.. 
```ts
import useDocusaurusContext from '@docusaurus/useDocusaurusContext';
import { useAgile } from '@agile-ts/react';
import core from '../../core';
import defaultTheme from 'prism-react-renderer/themes/palenight';

const usePrismTheme = () => {
  const { siteConfig } = useDocusaurusContext();
  const prismTheme = siteConfig.themeConfig.prism;
  const lightModeTheme = prismTheme.theme || defaultTheme;
  const darkModeTheme = prismTheme.darkTheme || lightModeTheme;
  const themeType = useAgile(core.ui.THEME_TYPE);

  return themeType === 'dark' ? darkModeTheme : lightModeTheme;
};

export default usePrismTheme;

```

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?
YES :D

## To Reproduce

Outsource a deeply nested Component which as some relation to the 'useThemeContext' hook..

## Expected behavior

no error

## Actual Behavior

error

## Your Environment

- Public source code: https://github.com/agile-ts/documentation/tree/newdessign
- Public site url: https://agile-ts.org
- Docusaurus version used: "^2.0.0-alpha.70"

## Reproducible Demo

If possible, use https://new.docusaurus.io to create a CodeSandbox reproducible demo of the bug.
(Not possible because this issue happens during the build.)

**Comment by slorber** [comment]
Not 100% sure to understand what you are trying to do, and what is an "outsourced component".
Do you have a branch with your failing attempt on your repository?

The theme context requires a theme provider to be set up at the top.

If you use this component around your "outsourced component", it may solve the issue:

```
import ThemeProvider from '@theme/ThemeProvider';
```

**Comment by bennodev19** [comment]
With outsourcing a Component I mean that the Component isn't built
in the Component it is used in.. to reduce redundant code.. 
![grafik](https://user-images.githubusercontent.com/57860196/108753826-83d68780-7545-11eb-81a7-d50d7185a403.png)
![grafik](https://user-images.githubusercontent.com/57860196/108754038-bc766100-7545-11eb-9ab8-f02aced14b3e.png)

I tried to reproduce the issue in a from scratch build docusaurus repo.. but there it works quite fine.. idk

So it currently only happens in my repo. 
You can reproduce it by cloning the agile-ts docs and running `yarn run install` and `yarn run build`
https://github.com/agile-ts/documentation/tree/use-theme-context-issue

Thank you

**Comment by slorber** [comment]
Ok I understand the problem.

Docusaurus tries to render everything you put in `src/pages` as standalone pages, including components from `src/pages/components`.

So basically, the StartCodingView leads to a standalone page at `/LandingPage/components/StartCodingView/`

See also: https://v2.docusaurus.io/docs/next/api/plugins/@docusaurus/plugin-content-pages

You should play with this pages plugin setting to ignore page creation for your  nested components (or move them outside the `src/pages` folder.

![image](https://user-images.githubusercontent.com/749374/108835482-d3619580-75cf-11eb-934b-e274799579fc.png)

**Comment by bennodev19** [comment]
ok thanks for the hint.. I will give it a try ^^
