### ISSUE TITLE
Allow use of base 64 encoded images with reference style in markdown

### ISSUE THREAD

**Issue by kierandg** [facebook/Docusaurus#427]
### Is this a bug report?

No, it is a feature request.

### Have you read the [Contributing Guidelines](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md)?

Yes

### Request description

Markdown should accept images in base64 for small image. It's useful when we don't want to upload the image to anywhere in the server.

```
![Image alt text][image-id]

[image-id]:
data:image/png;base64,iVBORw....5CYII=
```

**Comment by JoelMarcey** [comment]
Hi @kierandg Is there anything special that we would need to do here other than support reference style linking as documented here: https://github.com/facebook/Docusaurus/issues/257

**Comment by endiliey** [comment]
This issue is closed due to stale activity. Reference style linking has been supported as well.

If you think I might've closed it accidentally, please open up a new issue with new template.
