### ISSUE TITLE
Build broken with "TypeError: _interopRequireDefault is not a function"

### ISSUE THREAD

**Issue by reubenbijl** [facebook/docusaurus#4272]
## 🐛 Bug Report

Initial installation of docusaurus is unable to build

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## To Reproduce

Install docusaurus using the [installation instructions](https://v2.docusaurus.io/docs/installation)
1. npx @docusaurus/init@latest init my-website classic
2. cd my-website
3. yarn build

## Expected behavior
Build is successful

## Actual Behavior
Error
TypeError: _interopRequireDefault is not a function
(undefined) TypeError: _interopRequireDefault is not a function
    at Object.<anonymous> (main:36883:17)
    at __webpack_require__ (main:21:30)
    at Object.<anonymous> (main:17523:53)
    at __webpack_require__ (main:21:30)
    at Module.<anonymous> (main:54339:11)
    at __webpack_require__ (main:21:30)
    at main:85:18
    at main:88:10
    at Script.runInContext (vm.js:142:18)
    at Script.runInNewContext (vm.js:147:17)
error building locale=en

## Your Environment
- Docusaurus version used: 2.0 alpha 70
- Environment name and version yarn v1.22.4, node v14.8.0
- Operating system and version (desktop or mobile): macOS and BitBucket Pipeline with default docker container

**Comment by thiagoalves** [comment]
@reubenbijl I have the same situation here. The build fails inside a docker container but it works on the host machine

Have you managed to solve it?

**Comment by slorber** [comment]
Are you on alpha 70?

Wonder if it's not related to using symlinks? Reminds me another issue

**Comment by thiagoalves** [comment]
@slorber  Yes, alpha 70

I noticed that when I add `docusaurus2-dotenv` to the dependencies list I get the error.

This is my package.json:

```
{
  "name": "devportal",
  "version": "0.0.0",
  "private": true,
  "scripts": {
    "docusaurus": "docusaurus",
    "start": "docusaurus start",
    "build": "docusaurus build",
    "swizzle": "docusaurus swizzle",
    "deploy": "docusaurus deploy",
    "serve": "docusaurus serve",
    "clear": "docusaurus clear"
  },
  "dependencies": {
    "@docusaurus/core": "2.0.0-alpha.70",
    "@docusaurus/preset-classic": "2.0.0-alpha.70",
    "@mdx-js/react": "^1.6.21",
    "clsx": "^1.1.1",
    "core-js": "^3.8.3",
    "docusaurus-lunr-search": "^2.1.9",
    "docusaurus-plugin-sass": "^0.1.11",
    "docusaurus2-dotenv": "^1.4.0",
    "mobx": "^6.0.4",
    "react": "^16.8.4",
    "react-dom": "^16.8.4",
    "react-s-alert": "^1.4.1",
    "react-select": "^4.0.2",
    "styled-components": "^5.2.1",
    "swagger-i18n-extension": "^1.0.1",
    "swagger-ui-react": "^3.40.0"
  },
  "browserslist": {
    "production": [
      ">0.5%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  }
}

```

**Comment by slorber** [comment]
I don't know what is this dotenv plugin or what it does 😅

**Comment by thiagoalves** [comment]
It is mentioned here:

https://v2.docusaurus.io/community/resources#integrations

**Comment by slorber** [comment]
@thiagoalves accept almost any community link PR on this page, does not mean we approve or reviewed the code too deeply :)
I won't be able to tell how this plugin affects your Docusaurus unfortunately

**Comment by thiagoalves** [comment]
For the record: I have upgraded some packages and the problem seems to be gone:

    "@mdx-js/react": "^1.6.21" -> "^1.6.22",
    "docusaurus-lunr-search": "^2.1.9" ->  "^2.1.10"
    "core-js": "^3.8.3" -> "^3.9.0"
    "mobx": "^6.0.4" -> "^6.1.7"
    "react-select": "^4.0.2" -> "^4.1.0"
    "swagger-ui-react": "^3.40.0" -> "^3.43.0"
