### ISSUE TITLE
custom highlight.css url

### ISSUE THREAD

**Issue by wulucxy** [facebook/Docusaurus#428]
### Is this a bug report?

No， This is a feature

### Have you read the [Contributing Guidelines](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md)?

Yes

### Environment

(OS, Node, npm, yarn)

### Steps to Reproduce

**Our users mostly locate in China，they not not freely visit  cloudflare**
I want to get control of the hightlight.js url, I wish you can‘t give the options to developer self

Thanks for yours attention

### Expected Behavior

Just give the `highlight` config in `siteConfig.js` the full url options

**Comment by wulucxy** [comment]
@JoelMarcey Hi，I think this has a easy solution，but is crucial to the users in china，so please give the feedback soon，I appreciate for your feedback

**Comment by JoelMarcey** [comment]
HI @wulucxy Are you looking to add your own highlighting hook so you can register another language?

As in what is described here: https://docusaurus.io/docs/en/doc-markdown.html#registering-additional-languages

**Comment by wulucxy** [comment]
HI @JoelMarcey I don't think this is the solution, what I really want is full control of the `hightlight.css`, as the source code here
https://github.com/facebook/Docusaurus/blob/c6a9848a17b7ac27f43a58c6cecacf905fab0cbc/lib/core/Head.js#L67

the truth is：we will encounter these messages when try to get the url：
```
Request URL:http://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/styles/default.min.css
Request Method:GET
Status Code:307 Internal Redirect
Referrer Policy:no-referrer-when-downgrade
``` 
I think the host of cdn **cdnjs.cloudflare.com** can be customized，so the user in china can access fast。

**Comment by JoelMarcey** [comment]
@wulucxy I see. I think we could fix this really easily like you said. I wonder how many URLs should be customizable like this though. Is this the only one that is blocking you?

**Comment by wulucxy** [comment]
@JoelMarcey for me, yes!

**Comment by huang-x-h** [comment]
Hi @wulucxy @JoelMarcey i send a PR to add `highlight` config option support **string** type

```json
highlight: '/somepath/highlight.js'
```
