### ISSUE TITLE
Left Arrow and Right Arrow Hotkeys by Default

### ISSUE THREAD

**Issue by Zamiell** [facebook/docusaurus#4281]
## 🚀 Feature

"Left arrow" and "right arrow" should be hotkeys that are mapped to pressing the navigation buttons at the bottom of the page.

This would allow users to quickly and painlessly navigate through a Docusaurus site.

## Motivation

A common use case for a Docusaurus site is to flip through various documentation, looking for something specific. To accomplish this, it is useful to press "right arrow key" over and over, which is much faster and more accurate than manually clicking individual table of contents links on the left pane.

I foresee that many users will naturally expect this functionality to be in place, and be annoyed that it does not exist out of the box.

## Implementation

I've accomplished this in my own Docusaurus app with the following small script:

```javascript
document.onkeydown = function(e) {
  if (e.key === 'ArrowLeft') {
    const buttons = document.getElementsByClassName('pagination-nav__link');
    if (buttons.length >= 1) {
      buttons[0].click();
    }
  } else if (e.key === 'ArrowRight') {
    const buttons = document.getElementsByClassName('pagination-nav__link');
    if (buttons.length >= 2) {
      buttons[1].click();
    } else if (buttons.length >= 1) {
      buttons[0].click();
    }
  }
}
```

## Possible Downsides

If the page expands horizontally such that a horizontal scroll bar appears, users may attempt to use the arrow keys to horizontally scroll, and be annoyed that instead of performing the normal browser functionality, it instead navigates them away from the page entirely.

To rectify this, code can be put in place to conditionally enable the hotkeys only when no horizontal scroll bar is present.

**Comment by Itsaadarsh** [comment]
Yes, I totally agree with this can I start working on this feature?

**Comment by slorber** [comment]
> To rectify this, code can be put in place to conditionally enable the hotkeys only when no horizontal scroll bar is present.

That seems a bit hacky to me.

I'm not against this, but before rushing on implementation, we should study that building this is not an anti-pattern, particularly ensure it respects accessibility rules

Do you know any authoritative accessibility source that explains if such navigation is a good idea?

Any major site using a similar navigation pattern?

**Comment by Zamiell** [comment]
> Do you know any authoritative accessibility source that explains if such navigation is a good idea?

When you say "such navigation", which you referring to?
a) using left and right arrow keys to flip between pages
b) using left and right arrow keys to scroll the page horizontally

For A, scribd.com (a common document viewing website, [325th most popular website in the world](https://www.alexa.com/siteinfo/scribd.com)) uses arrow hotkeys to flip through pages. That is a pretty close analogy to what Docusarus is doing.

I also tried on amazon.com ([10th most popular website in the world](https://www.alexa.com/siteinfo/amazon.com)), which doesn't seem to have it, at least for scrolling through pictures of a product.

However, alibaba.com (the Chinese equivalent of Amazon, [118th most popular website in the world](https://www.alexa.com/siteinfo/alibaba.com)) does have exactly this functionality. So does newegg.com (popular website for buying computer parts, [444th most popular website in the world](https://www.alexa.com/siteinfo/newegg.com)).

Those are just a few websites that I tried at random, /shrug .

**Comment by Zamiell** [comment]
Another point to discuss here is that we should expect Docusaurus pages with a horizontal scroll bar to encompass a really tiny percentage of deployments, maybe <= 1%.

This is because by default, when typing up Markdown files and using Docusaurus to display them (e.g. the default use-case of the product), you would never normally get a horizontal scroll bar.

For example, the following things **would not** cause a horizontal scroll bar:
1. A long string - browsers automatically break these.
2. A picture - Docusarus automatically resizes this, at least when using the standard Markdown syntax, e.g. `![Poop](/img/poop.png)`

One legitimate reason for a website to have a horizontal scroll bar might be if they had a really wide image that they did not want to scale down. Which means that they would have to manually use something like the following:

```
<img src="/img/poop.png" width=9000>
```

This would be really ugly. Thinking about this more, a better way to design such a website would be to let Docusaurus auto-resize the image, but make it clickable such that it opens the big, unscaled image in a new tab or something.

Anyway, perhaps this condition is so rare that it shouldn't be considered.

**Comment by Mihonarium** [comment]
Arrows are already used to navigate across the tabs (and it's really convenient!). I think it could be somewhat confusing if the same hotkey changes the page depending on whether a tab is in focus. If the outline isn't shown, it's impossible to predict what will happen if you press a button, which can lead to unexpected behavior.

Maybe use something like Ctrl+Arrow?

**Comment by Josh-Cena** [comment]
Closing in favor of #3020. We should try to design a generic API
