### ISSUE TITLE
ReferenceError when Markdown file contains HTML with curly braces

### ISSUE THREAD

**Issue by Zhouzi** [facebook/docusaurus#4288]
## 🐛 Bug Report

I have automatically generated Markdown files (`.md`) that contain HTML. The page crashes if that HTML contains a pair of curly braces:

```
<p>This {html} code is in a .md file.</p>
```

Results in: `ReferenceError: html is not defined`

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes.

## To Reproduce

1. https://codesandbox.io/s/reverent-lederberg-f8jcl
2. Access the first page.
3. An error is thrown: ReferenceError: page is not defined

## Expected behavior

I was expecting to be able to access the page and read my content.

## Actual Behavior

Instead the page crashed with an error message.

<img width="578" alt="Capture d’écran 2021-02-24 à 17 25 06" src="https://user-images.githubusercontent.com/2291025/109031722-47319a00-76c5-11eb-8f38-4b1ac2b682af.png">

## Your Environment

- Public source code: https://codesandbox.io/s/reverent-lederberg-f8jcl
- Public site url: https://codesandbox.io/s/reverent-lederberg-f8jcl
- Docusaurus version used: 2.0.0-alpha.70
- Environment name and version: Chrome 88.0.4324.192, Node.js v10.23.0
- Operating system and version: macOS Catalina 10.15.6

## Reproducible Demo

https://codesandbox.io/s/reverent-lederberg-f8jcl

If you want to reproduce it on your own, here's how you can do it:

1. Create a new docusaurus project.
2. Edit a Markdown file and add HTML in it with something wrapped with curly braces, for example: `<p>Hey {there}!</p>`
3. Start the application and try accessing the page you edited.

---

Although I like the idea that Docusaurus is able to infer some nice defaults, it seems that Markdown has some incompatibilities with MDX. So perhaps it should not be parsed as MDX if the file extension is `.md`?

**Comment by Zhouzi** [comment]
I just stumbled upon the [feature request](https://docusaurus-2.netlify.app/feedback/p/support-both-md-and-mdx) and [RFC](https://github.com/facebook/docusaurus/issues/3018).

Feel free to close this issue if you think it's a duplicate.

**Comment by SebastienGllmt** [comment]
I don't think this was fixed by #3018 since even if I specify `format: 'md'` in my front matter I still get `Could not parse expression with acorn` (caused by the unescaped `{` in the markdown file)
