### ISSUE TITLE
Remove dead code in sitemap.js

### ISSUE THREAD

**Issue by JoelMarcey** [facebook/Docusaurus#429]
### Is this a bug report?

No

### Have you read the [Contributing Guidelines](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md)?

Yes

### Environment

N/A

### Steps to Reproduce

Look at https://github.com/facebook/Docusaurus/blob/master/lib/server/sitemap.js

There are three variables that are never used.

```
const blogFolder = path.resolve('../blog/');
const blogRootURL = siteConfig.url + '/blog';
const jestImage = siteConfig.url + siteConfig.headerIcon;
``` 

### Expected Behavior

Let's get rid of that dead code.

### Actual Behavior

N/A

### Reproducible Demo

N/A

**Comment by sufuf3** [comment]
May I take this?
I'm interested in this one.
Thank you.

**Comment by JoelMarcey** [comment]
@sufuf3 Hi. Absolutely. Thank you!

**Comment by sufuf3** [comment]
Thank you very much.
I sent a PR here #430.
Hope it is good for working. :)
