### ISSUE TITLE
`ssrTemplate` does not work with `yarn start`

### ISSUE THREAD

**Issue by roydukkey** [facebook/docusaurus#4290]
### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## To Reproduce

* Added `class="test"` on the HTML element of the SSR template

1. Does **_not_** apply custom template with `yarn start`
2. Does apply custom template with `yarn build && yarn serve`

## Expected behavior

I would expect the template to be used with both `yarn start` and `yarn serve`.

## Actual Behavior

Does **_not_** apply custom template with `yarn start`

## Your Environment

- Public source code: https://github.com/roydukkey/moist/tree/docusaurus/4290
- Docusaurus version used: 2.0.0-alpha.70
- Environment name and version Chrome  88.0.4324.182, Node.js v15.6.0
- Operating system and version (desktop or mobile): MacOS

## Reproducible Demo

https://github.com/roydukkey/moist/tree/docusaurus/4290

**Comment by slorber** [comment]
The SSR template is for SSR, ie `docusaurus build`. 

`yarn start` does not do serve-side rendering so it would be odd to be able to customize the HTML file with a config attribute named `ssrTemplate`.

`yarn start` is using another template for dev.

We may be able to factorize those 2 templates as a single template however, and add a config that permits to customize both yarn start and yarn dev at the same time.

Can you describe your usecase? What are you trying to do? Why do you want to change the dev template?

**Comment by roydukkey** [comment]
I was unaware. Maybe the docs could clear this up a little. Maybe they already do, but I've not been reading the docs in order, so this point might be covered in a doc I've not yet read. I was using this page primarily to come to the conclusions I had when I wrote this issue:

**https://v2.docusaurus.io/docs/docusaurus.config.js#ssrtemplate**
> ### ssrTemplate
> An HTML template written in [Eta's syntax](https://eta.js.org/docs/syntax#syntax-overview) that will be used to render your application. This can be used to set custom attributes on the `body` tags, additional `meta` tags, customize the `viewport`, etc. Please note that Docusaurus will rely on the template to be correctly structured in order to function properly, once you do customize it, you will have to make sure that your template is compliant with the requirements from `upstream`.

Also, my use case is not validate since I found it is covered by [`injectHtmlTags()`](https://v2.docusaurus.io/docs/lifecycle-apis#injecthtmltags), specifically being able to inject into `<head />`.

**Comment by slorber** [comment]
Great to know thanks

Will close for now, but we'll see if someone can come up with a need for this
