### ISSUE TITLE
Create ARCHITECTURE.md

### ISSUE THREAD

**Issue by slorber** [facebook/docusaurus#4301]
## 📚 Documentation

We should have a doc to help new contributors onboard and understand the Docusaurus internals.

We need this particularly for external contributors and MLH fellows.

Also asked here (+ basic architecture answer): https://github.com/facebook/docusaurus/discussions/4300

Also advised by this blog post: https://matklad.github.io/2021/02/06/ARCHITECTURE.md.html

**Comment by iamrubayet** [comment]
can i work on this ?

**Comment by slorber** [comment]
@iamrubayet it should rather be the job of the maintainer team to write it, as you probably don't know all the architecture details of Docusaurus as much as we do.

But if you feel you can tackle this and want to work on a first draft, why not, and we could complete this doc to make it more exhaustive
