### ISSUE TITLE
Algolia search modal displays wrong labels on mobile

### ISSUE THREAD

**Issue by sserrata** [facebook/docusaurus#4305]
## 🐛 Bug Report

The Algolia search modal is (initially) displaying the wrong grouping labels for search results. Clicking on the labels themselves somehow updates them to display the correct label. Please see screen recording for example.

https://user-images.githubusercontent.com/9343811/109354172-02cc0880-7843-11eb-8f2e-20389e978397.MP4

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes.

## To Reproduce

If possible, use https://new.docusaurus.io to create a CodeSandbox reproducible demo of the bug.

1. Navigate to v2.docusaurus.io using a mobile browser, e.g. Chrome, Safari, etc.
2. Type in the word "test" in the search bar.
3. Observe the grouping labels. The first result will have the correct group label but subsequent results/hits will not.
4. Click/touch the second and subsequent labels and observe how they are changed to display the correct label.

## Expected behavior

Expecting to see the correct label the first time the modal results are rendered.

## Actual Behavior

Modal results/hits labels are initially mismatched.

## Your Environment

- Public source code:
- Public site url: https://v2.docusaurus.io
- Docusaurus version used: latest/canary and alpha 70
- Environment name and version (e.g. Chrome 78.0.3904.108, Node.js 10.17.0): Chrome, Safari (mobile)
- Operating system and version (desktop or mobile): mobile (iOS)

## Reproducible Demo

If possible, use https://new.docusaurus.io to create a CodeSandbox reproducible demo of the bug.

(Paste the link to an example repo, including a `docusaurus.config.js`, and exact instructions to reproduce the issue.)

**Comment by sserrata** [comment]
Please note that this behavior is not reproducible using Chrome's built in mobile browser emulator.

**Comment by slorber** [comment]
@francoischalifour @shipow  it looks like a DocSearch bug, maybe there's a bad/missing React key somewhere?

**Comment by lex111** [comment]
I can't reproduce this anymore, apparently it's no longer relevant (we recently updated docsearch, maybe it helped).
