### ISSUE TITLE
Move Verifying Installation section to Installation doc

### ISSUE THREAD

**Issue by JoelMarcey** [facebook/Docusaurus#431]
### Is this a bug report?

No

### Have you read the [Contributing Guidelines](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md)?

Yes

### Environment

N/A

### Steps to Reproduce

N/A

### Expected Behavior

The section should be in https://docusaurus.io/docs/en/installation.html

The first paragraph in will need to be updated too.

### Actual Behavior

It is in https://docusaurus.io/docs/en/site-preparation.html#verifying-installation

### Reproducible Demo

1. Go to https://docusaurus.io/docs/en/site-preparation.html#verifying-installation
2. Read that section
3. If agreed that it should be part of the Installation doc instead, move it there.

**Comment by gedeagas** [comment]
Hello @JoelMarcey i just make a pr about this but i seem a bit lost on what needs to be updated in the first paragraph.

**Comment by JoelMarcey** [comment]
Hi @gedeagas 

The first paragraph in https://docusaurus.io/docs/en/site-preparation.html says:

> After installing Docusaurus, you now have a skeleton to work from for your specific website. With a few changes, you can verify that Docusaurus was installed correctly by running the site locally.

The second sentence there would be out of place, I think, if you are moving the verification of the install to the installation page. So maybe that just should be removed?

Actually you can take this paragraph from down below on that page:

> The website/blog-examples-from-docusaurus and docs-examples-from-docusaurus folders contain example blog and document markdown files. As shown below when you verify that the example site runs correctly, if you wish to run Docusaurus with these files, you need to rename the folders to website/blog and docs, respectively.

and move it to the top of  https://docusaurus.io/docs/en/site-preparation.html and have the first paragraph be something like:

> After installing Docusaurus, you now have a skeleton to work from for your specific website. You may have already renamed the example blog (`website/blog-examples-from-docusaurus` and document (`docs-examples-from-docusaurus`) directories when you [verified the installation](LINK TO THE NEW LOCATION). The following discusses the rest of the Docusaurus structure in order for you to prepare your site.

**Comment by gedeagas** [comment]
Ah, I got it now 😃
Thank you for your insight @JoelMarcey.

**Comment by JoelMarcey** [comment]
Fixed by https://github.com/facebook/Docusaurus/commit/c8781bedced205cd2a5c876af62623795d7aaf81 and https://github.com/facebook/Docusaurus/commit/9931ed86d28a3ea64c9878536a4d2f91765f1d26
