### ISSUE TITLE
Cannot differentiate `BlogListPage` and `BlogPostPage` for styling

### ISSUE THREAD

**Issue by roydukkey** [facebook/docusaurus#4322]
## 🚀 Feature

Add class names to individuate blog theme components.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## Motivation

Having a class name to differentiate blog list pages from post pages would allow styling the pages using the [global style methodology](https://v2.docusaurus.io/docs/styling-layout#global-styles).

## Pitch

Currently, global styling is not possible since there is not variancy between the structures of `BlogListPage` and `BlogPostPage`. Adding another class name (e.g. `blog-list-page`, `blog-post-page`), alongside the [`blog-wrapper`](https://github.com/facebook/docusaurus/search?q=blog-wrapper) class name, would allow for global styling. 

Furthermore, there doesn't seem to be another way to inject additional class names into these components except to [wrap them](https://v2.docusaurus.io/docs/using-themes#wrapping-theme-components). I don't feel wrapping the components is a good flow, just to add classes to target for styling, since a global styling methodology often tries to lessen its dependency on structure.

For the `docusaurus-theme-classic`, these are the proposed changes to the blog components:

- [ ] Add the `blog-list-page` class name to the `Layout` component for [`BlogListPage`](https://github.com/facebook/docusaurus/blob/3ebe8882442311924e12c8a79bb17a43b2f31edf/packages/docusaurus-theme-classic/src/theme/BlogListPage/index.tsx#L29)
- [ ] Add the `blog-post-page` class name to the `Layout` component for [`BlogPostPage`](https://github.com/facebook/docusaurus/blob/ab7951571ea8badb38661f66cf9d0ccdd1df777d/packages/docusaurus-theme-classic/src/theme/BlogPostPage/index.tsx#L27)
- [ ] Add the `blog-tags-list-page` class name to the `Layout` component for [`BlogTagsListPage`](https://github.com/facebook/docusaurus/blob/1734975f2f44814df9288ae4067c2fdc60c2fd55/packages/docusaurus-theme-classic/src/theme/BlogTagsListPage/index.tsx#L57)
- [ ] Add the `blog-tags-post-page` class name to the `Layout` component for [`BlogTagsPostsPage`](https://github.com/facebook/docusaurus/blob/1734975f2f44814df9288ae4067c2fdc60c2fd55/packages/docusaurus-theme-classic/src/theme/BlogTagsPostsPage/index.tsx#L46)

**Comment by slorber** [comment]
Make sense, all docusaurus pages should have a convenient way to target them with custom CSS.

We should have one wrapper class per "plugin" (like blog-wrapper), and unique classname per unique page types for better granularity.

Assigning this easy task to MLH fellows

**Comment by slorber** [comment]
FYI there's also a need to be able to target with CSS a specific doc/version/blog/page: https://github.com/facebook/docusaurus/issues/4280

Ie we probably want a classname like `docs-wrapper doc-item-page version-1.0.0 docId`?

**Comment by javidrashid** [comment]
@ShinteiMai  to work on this.
