### ISSUE TITLE
"yarn start" fails, while "yarn build" / "yarn serve" succeeds with new website

### ISSUE THREAD

**Issue by conradnewton** [facebook/docusaurus#4335]
## 🐛 Bug Report

When I attempt to start the developer server with the command `yarn start`, I get what looks like a success message, but opening the browser at `http://localhost:3000` gives a site not found message.

Nevertheless, everything else seems to be working. I can type `yarn build`, followed by `yarn serve`, and the preliminary website is visible as expected at `http://localhost:3000`.

If I edit a file and look for changes, I have to repeat the process with "yarn build" / "yarn serve", since at no point does "yarn start" produce a developer website.

I have followed [these instructions](https://v2.docusaurus.io/docs/installation).

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes.

## To Reproduce

If possible, use https://new.docusaurus.io to create a CodeSandbox reproducible demo of the bug.

I'm using docker to run the site, rather than installing the software directly on my computer, so reproducing  this issue should be simple.

1. docker run -it -p 3000:3000 node:alpine sh
2. npx @docusaurus/init@latest init my-website classic
3. cd my-website
4. yarn start 

## Expected behavior

I expected the developer version of the website to appear at `http://localhost:3000`.

Since there were no error messages up to this point, and I got green checkmarks for the client build, I had every reason to expect success.

## Actual Behavior

After "yarn start", opening the browser at `http://localhost:3000` gives a generic "Site not found" message.

I was of course concerned that docker had in some way broken the setup, but additional experiments indicated that everything else was working. Only "yarn start" was broken.

* If in the next step I run "yarn serve", I get a 404 message from docusaurus, in contrast to "Site not found"
* If I run "yarn build", new files are created in the "build" directory
* If I again run "yarn serve", the website is visible at `http://localhost:3000`
* I can edit a file and make changes, but they will only be visible after running "yarn build" / "yarn serve"
* Any additional attempts to run "yarn start" fails in the same way, with "Site not found"

## Your Environment

- Public source code: docker image node:alpine
- Public site url:
- Docusaurus version used: Version: 2.0.0-alpha.70
- Environment name and version: Chrome 83.0.4103.97-1, Node.js v15.5.1, yarn 1.22.5
- Operating system and version (desktop or mobile): Linux desktop, Debian testing

## Reproducible Demo

The CodeSandbox is not relevant, since I'm using Docker to create a new website, following generic docusaurus instructions.

But see the instructions in the section "To reproduce", which are easily reproducible.

**Comment by slorber** [comment]
Please try this outside of Docker.
If this still does not work we'll do something about it and re-open the issue, otherwise it's related to your usage of Docker for which we don't provide first-class support
