### ISSUE TITLE
Organize siteConfig.js options documentation page better

### ISSUE THREAD

**Issue by JoelMarcey** [facebook/Docusaurus#436]
Some ideas:

- [ ] Better categorization
- [X] Alphabetize
- [ ] Table format

### Is this a bug report?

No. It is more of an efficiency report.

### Have you read the [Contributing Guidelines](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md)?

Yes.

### Environment

N/A

### Steps to Reproduce

1. Go to https://docusaurus.io/docs/en/site-config.html
2. See how the options are kinda scattered all over
3.

### Expected Behavior

Better readability

### Actual Behavior

Random readability

### Reproducible Demo

https://docusaurus.io/docs/en/site-config.html

**Comment by InternetExplorer7** [comment]
Hi, can I take on the other 2/3 issues?

**Comment by yangshun** [comment]
@InternetExplorer7 How's your progress for this task? Let us know how we can help. If you are no longer available for this task, just let us know and we can free it up for someone else. Do keep us updated 😄

**Comment by johnotu** [comment]
I looked at the page but couldn't understand how "scattered" they are. Would sectioning them into tables or div groups fix it?

**Comment by sujono91** [comment]
@JoelMarcey @yangshun 
I'm interested to work on this categorization issue. My proposal (just an example):
```
Mandatory Fields
Header
headerIcon - ...
headerLinks - ..
```

```
Optional Fields
Media Social
facebookAppId - ..
facebookComments - ..
```

If u've any categorization proposal before, pls lmk. I'll try to categorize all of them and give a full proposal here 👍

**Comment by JoelMarcey** [comment]
@sujono91 We would love for you to take this issue if you are interested, thanks!

**Comment by tanhauhau** [comment]
Hi, how is the issue? i see it's a `good first issue`, can i take on it?

**Comment by JoelMarcey** [comment]
Hi @tanhauhau - sure. You can own this, thank you! I would make sure you keep in coordination with  https://github.com/facebook/Docusaurus/pull/946#issuecomment-428159560 as we are creating tabs for this page. But the content of the siteConfig Fields section can be modified as well.

We've added an `issue: claimed` label so that others will know not to start work on the issue. If you change your mind about the issue, no worries! Just let us know so that we can remove the label and free it up for someone else to claim.

We will check in with you periodically so that we can keep the task updated with the progress.
