### ISSUE TITLE
Look at supporting multiple syntax highlighters

### ISSUE THREAD

**Issue by JoelMarcey** [facebook/Docusaurus#438]
### Is this a bug report?

No

### Have you read the [Contributing Guidelines](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md)?

Yes

### Environment

N/A

### Steps to Reproduce

https://twitter.com/notbrent/status/961436860928049152

### Expected Behavior

JSX is supported

### Actual Behavior

JSX is not supported

### Reproducible Demo

N/A

**Comment by JoelMarcey** [comment]
cc @brentvatne

**Comment by brentvatne** [comment]
closing this related issue: https://github.com/facebook/Docusaurus/issues/388

**Comment by ahmadalfy** [comment]
@JoelMarcey  @yangshun  should we switch to Prism? I looked at [highlight.js](https://highlightjs.org/static/demo/) and couldn't find support for JSX.

**Comment by endiliey** [comment]
I have investigated this. One thing to note is that unlike highlight.js, prism.js doesn't support auto language detection. 

Since highlight.js couldn't support JSX, do we want to:
1. Support two highlighters - highlight.js and prism and let the user choose as a configuration option.
or
2. Still use highlight.js for everything but use prism.js for jsx ??

My mockup for now

**Highlight.js (before)**
<img width="523" alt="highlightjs" src="https://user-images.githubusercontent.com/17883920/41054844-20ef20ac-69f2-11e8-8f47-1718c63ab3c4.PNG">

**Prism.js (after)**
<img width="520" alt="prismjs" src="https://user-images.githubusercontent.com/17883920/41054857-2acf7680-69f2-11e8-83f6-122426cd8265.PNG">

**Comment by iRoachie** [comment]
What do you mean by auto-language detection? 

You mean when if the language is not explicitly set? e.g ```js

**Comment by endiliey** [comment]
@iRoachie yes

**Comment by iRoachie** [comment]
Is this a requirement? The highlighter github uses for markdown doesn't do auto-language detection either.

**Comment by endiliey** [comment]
I think it's not required 😄. Anyway, would you prefer to see option 1 or option 2 ?

**Comment by iRoachie** [comment]
Think for now option 2 might be better. Don't think we have tests to check which languages might break using prismjs outside of `jsx` as compared to highlightjs.

**Comment by endiliey** [comment]
Any thoughts @yangshun @JoelMarcey ?

**Comment by endiliey** [comment]
Something like this @JoelMarcey ?
```js
usePrism: ['js', 'jsx']
```

This is doable but one thing that i notice is if user use 'highlight.js' theme and use prism.js for certain language, their css might conflict. And highlight.js has so much themes.

Examples if i use GH Themes for prism.js out of https://github.com/PrismJS/prism-themes

```
usePrism: ['js', 'jsx'],
  highlight: {
    theme: 'github',
  }
```

<img width="507" alt="github theme" src="https://user-images.githubusercontent.com/17883920/41090760-9ba41d4a-6a77-11e8-806b-ee6d65d80f3a.PNG">

```
usePrism: ['js', 'jsx'],
  highlight: {
    theme: 'zenburn',
  }
```

<img width="516" alt="zenburn" src="https://user-images.githubusercontent.com/17883920/41090876-df4be546-6a77-11e8-8728-f44b374b5f57.PNG">

```
usePrism: ['js', 'jsx'],
  highlight: {
    theme: 'atom-one-dark',
  },
```

<img width="522" alt="lololer" src="https://user-images.githubusercontent.com/17883920/41090912-f310e7b6-6a77-11e8-9dae-ee2725255ff5.PNG">

Honestly it's much easier to implement option 1 😂

**Comment by endiliey** [comment]
Something like this @JoelMarcey ?
```js
usePrism: ['js', 'jsx']
```

Giving some examples:

```
usePrism: ['js', 'jsx'],
highlight: {
  theme: 'atom-one-dark',
}
```

<img width="515" alt="atom-one-dark" src="https://user-images.githubusercontent.com/17883920/41093552-35fd07e8-6a7e-11e8-8ff1-1dcfa52caa90.PNG">



```
usePrism: ['js', 'jsx'],
highlight: {
  theme: 'default',
}
```

<img width="512" alt="default" src="https://user-images.githubusercontent.com/17883920/41093559-397fe6ba-6a7e-11e8-8997-5401cfb10366.PNG">

```
usePrism: ['js', 'jsx'],
highlight: {
  theme: 'tomorrow-night-blue',
}
```

<img width="519" alt="tomorrow-night-blue" src="https://user-images.githubusercontent.com/17883920/41093567-40177f42-6a7e-11e8-8f13-c8027c885521.PNG">

If this is good, I'll submit a PR

**Comment by JoelMarcey** [comment]
@endiliey 👍 Yep, something similar to that. I wonder if option 1 is easier or more clean 😆 But I think this should be ok. Let me look at the PR.
