### ISSUE TITLE
Add fingerprint to compiled css/js files

### ISSUE THREAD

**Issue by tooooolong** [facebook/Docusaurus#439]
Case we have CDN front of our website, So main.css can not update automaticly.

Now, the css tag is:
```
<link rel="stylesheet" href="/css/main.css">
```
I think it should add fingerprint to static files.
Something like this:

```
<link rel="stylesheet" href="/css/main.build_hash.css">
```

**Comment by JoelMarcey** [comment]
Hi @tooooolong! How would one know whether a fingerprint should be used? Some sort of configuration option?

**Comment by tooooolong** [comment]
maybe something like this。

https://github.com/webpack/webpack/issues/86#issuecomment-179957661

this is a plugin for Webpack, it will add a hash to the static file name automatically.

**Comment by yangshun** [comment]
This is a good idea 👍

**Comment by gedeagas** [comment]
is anyone taking this @yangshun ? I can work on thing in the coming weeks

**Comment by yangshun** [comment]
Sure thing!

**Comment by gedeagas** [comment]
Hi, @yangshun can you check my code? https://github.com/facebook/Docusaurus/pull/694

**Comment by endiliey** [comment]
Implemented in v2
