### ISSUE TITLE
change Edit this Page button text, PLS :D

### ISSUE THREAD

**Issue by HondryTravis** [facebook/docusaurus#4393]
## 🚀 Feature
![image](https://user-images.githubusercontent.com/24218012/110760903-24d57a00-828a-11eb-9a78-9f04270b01ac.png)

how did i can change this text in simple chinese ??

**Comment by slorber** [comment]
It is possible with alpha71 and the i18n support to override any theme label, and we provide default translations for many languages so if you just configure Chinese hans/hant as default locale in i18n config Docusaurus will show translated labels

https://github.com/facebook/docusaurus/blob/master/packages/docusaurus-theme-classic/codeTranslations/zh-Hans.json#L33

**Comment by HondryTravis** [comment]
thanks a lot. :D 🐳  @slorber
