### ISSUE TITLE
Config validation errors do not say the expected types

### ISSUE THREAD

**Issue by orta** [facebook/docusaurus#4412]
## 🐛 Bug Report

In #4411  I used a config entry which didn't pass validation, but I _didn't_ know what the actual shape should be (I found a comment showing it somewhere else)

> ValidationError: "remarkPlugins[0]" does not match any of the allowed types

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## To Reproduce

You can use the steps in #4411 - but any incorrect config should suffice

## Expected behavior

If only one possible type, maybe something like:

```
> ValidationError: "remarkPlugins[0]" was not of the type string
> ValidationError: "remarkPlugins[0]" was not of the type number
> ValidationError: "remarkPlugins[0]" was not of the type string[]
> ValidationError: "remarkPlugins[0]" was not of the type [string, object] 
```

( I'm being lazy and using TS descriptions but that could be a good shorthand )

and for multiple options maybe the word "or" is enough:

```
> ValidationError: "remarkPlugins[0]" was not of the type string or number
```

## Actual Behavior

I know it failed, but I don't know what to do without going to the docs

## Your Environment

N/a

**Comment by slorber** [comment]
Make sense, we should improve obscure error messages when possible so that user does not need to look at the doc.

This is actually the default Joi error message that you get using the schema:

```
const MarkdownPluginsSchema = Joi.array()
  .items(
    Joi.array().ordered(Joi.function().required(), Joi.object().required()),
    Joi.function(),
    Joi.object(),
  )
  .default([]);
```

But there are ways to customize it with  `.message()` afaik.

Will assign to MLH fellows, should be an easy contribution :)

**Comment by slorber** [comment]
BTW, the `Joi.object()` type seems suspicious to me, is it a correct way to declare a remark plugin?

**Comment by orta** [comment]
I'd call it  _unlikely_ - because the examples in the mdx documentation (which I assume you pipe into) are only:

```
const fs = require('fs')
const mdx = require('@mdx-js/mdx')
const images = require('remark-images')
const emoji = require('remark-emoji')

mdx.sync(mdxText, {
  remarkPlugins: [
    images,
    [emoji, { padSpaceAfter: true }]
})

```
Maybe [string, {obj}]` isn't allowed either from the diocs

**Comment by javidrashid** [comment]
@ShinteiMai to  look in to this.

**Comment by Josh-Cena** [comment]
I'll close this in https://github.com/facebook/docusaurus/pull/6997. It would be quite hard to do it in a one-time effort, so if someone stumbled upon obscure validation error messages, feel free to submit new issues.
