### ISSUE TITLE
[v2.0.0-alpha.71] @docusaurus/init --use-npm fails

### ISSUE THREAD

**Issue by LeonMontealegre** [facebook/docusaurus#4417]
## 🐛 Bug Report

Initializing a docusaurus v2 repository using `npx @docusaurus/init@2.0.0-alpha.71 init NAME classic --use-npm` fails on `npm install` with an error about being unable to resolve the dependency tree.  

This comes along with the effect that if you install it without `--use-npm`, delete `yarn.lock` and `node_modules`, and attempt to `npm install`, the same error appears.

## To Reproduce

1. Open a terminal
2. `npx @docusaurus/init@2.0.0-alpha.71 init NAME classic --use-npm`
3. See error

## Expected behavior

Docusaurus should work with NPM alone and not exclusive to yarn

## Actual Behavior

N/A

## Your Environment

- Public source code: N/A
- Public site URL: N/A
- Docusaurus version used: 2.0.0-alpha.71
- Environment name and version (e.g. Chrome 78.0.3904.108, Node.js 10.17.0): Node v15.9.0, NPM v7.5.3
- Operating system and version (desktop or mobile): macOS Mojave

## Reproducible Demo

Easy enough to reproduce w/o a repository

## Error log

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! Found: react@17.0.1
npm ERR! node_modules/react
npm ERR!   react@"^17.0.1" from the root project
npm ERR!   peer react@"^16.8.4 || ^17.0.0" from @docusaurus/core@2.0.0-alpha.71
npm ERR!   node_modules/@docusaurus/core
npm ERR!     @docusaurus/core@"2.0.0-alpha.71" from the root project
npm ERR!     @docusaurus/core@"2.0.0-alpha.71" from @docusaurus/preset-classic@2.0.0-alpha.71
npm ERR!     node_modules/@docusaurus/preset-classic
npm ERR!       @docusaurus/preset-classic@"2.0.0-alpha.71" from the root project
npm ERR!     11 more (@docusaurus/plugin-content-blog, ...)
npm ERR!   22 more (react-dom, @docusaurus/preset-classic, @mdx-js/react, ...)
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^15.3.0 || ^16.0.0" from react-toggle@4.1.1
npm ERR! node_modules/@docusaurus/theme-classic/node_modules/react-toggle
npm ERR!   react-toggle@"^4.1.1" from @docusaurus/theme-classic@2.0.0-alpha.71
npm ERR!   node_modules/@docusaurus/theme-classic
npm ERR!     @docusaurus/theme-classic@"2.0.0-alpha.71" from @docusaurus/preset-classic@2.0.0-alpha.71
npm ERR!     node_modules/@docusaurus/preset-classic
npm ERR!       @docusaurus/preset-classic@"2.0.0-alpha.71" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

Full log: [https://pastebin.com/raw/UVGaWawz](https://pastebin.com/raw/UVGaWawz)

**Comment by slorber** [comment]
Can you provide the actual error log please?

**Comment by slorber** [comment]
Thanks @leandrooriente 

I guess we can close now thanks to https://github.com/facebook/docusaurus/pull/4436, let me know if you still see an issue
