### ISSUE TITLE
Hi! Do you need any translation to spanish?

### ISSUE THREAD

**Issue by ceparl** [facebook/Docusaurus#442]
### Is this a bug report?

(write your answer here)

### Have you read the [Contributing Guidelines](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md)?

(Write your answer here.)

### Environment

(OS, Node, npm, yarn)

### Steps to Reproduce

(Write your steps here:)

1.
2.
3.

### Expected Behavior

(Write what you thought would happen.)

### Actual Behavior

(Write what happened. Add screenshots, if applicable.)

### Reproducible Demo

(Paste the link to an example project and exact instructions to reproduce the issue.)

**Comment by JoelMarcey** [comment]
@ceparl Hi! I believe we would love translation of the Docusaurus site to Spanish. Are you interested in helping us there?

cc: @ericnakagawa

**Comment by ceparl** [comment]
Yes, I would love to contribute with you!

**Comment by ceparl** [comment]
Are you going to create a directory for the translations? or Can I do a PR of the files to be translated?

**Comment by JoelMarcey** [comment]
Let me chat with @ericnakagawa tomorrow morning on the best way to approach the translation since this will be our first translation of docusaurus.io. Then we will get back to you.

**Comment by ceparl** [comment]
Sure! Don't worry. I'll be waiting for your answer.

**Comment by JoelMarcey** [comment]
Hi @ceparl Do you have an account on Crowdin? Have you seen https://crowdin.com/project/docusaurus

**Comment by juanpicado** [comment]
@JoelMarcey the website seems to be 100% translated already 😕

**Comment by juanpicado** [comment]
@ericnakagawa  well, that's a different story. I wonder how can I help whether if I see something is good or bad? I have a bit experience with crowding. How can I approve something whether I considere is good? Can I?

**Comment by ericnakagawa** [comment]
@juanpicado Which other projects have you helped translate?

**Comment by juanpicado** [comment]
- babel-handbook (60%)
- verdaccio (wip, 25%)
- appium (the first website, it does not longer exist) 100%

**Comment by ceparl** [comment]
Hello again! 

I would like to help with the spanish translations for the Docusaurus project, but since last week I haven't had intente due to some inconveniences that my internet providers present. Therefore, I haven't been able to contribute. I just checked the project in Crowdin and the spanish translations appear to be 100%. So I can contribute to the translations from now on, but I need to know how I could do it if the transations to spanish appear to be 100% right now.

**Comment by JoelMarcey** [comment]
@ceparl Hi! I commented on your message you sent to me on Crowdin. We still need to enable the Spanish translation for Docusaurus, but one option is that you can always verify the translations are correct and we are actually at 100%.
