### ISSUE TITLE
[2.0.0-alpha.71] Docusaurus Node/SSR could not render static page with path=[PATH] because of error: Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by johnnyreilly** [facebook/docusaurus#4421]
Heya!

I've a fairly vanilla Docusaurus site that I'm using for blogging alone.  ~~I think (I'm not sure) that the problem may lie with the `@docusaurus/plugin-client-redirects`.~~ Actually I think not; I tried excluding that plugin and the issue still presented.

## 🐛 Bug Report

I think I've just encountered a bug with Docusaurus 2.0.0-alpha.71.  I upgraded from 70 and started to encounter error messages in the build of the nature of: 

```
Docusaurus Node/SSR could not render static page with path=/tags/fork-ts-checker-webpack-plugin because of error: Cannot read property 'replace' of undefined
```

and stack traces like

```
(undefined) TypeError: Cannot read property 'replace' of undefined
    at CodeBlock (main:8985:18)
    at d (main:72375:498)
    at $a (main:72378:16)
    at a.b.render (main:72383:476)
    at a.b.read (main:72383:18)
    at Object.renderToString (main:72393:364)
    at doRender (main:90314:385)
    at async serverEntry_render (main:90313:301)
```

You can see a PR here which solely upgrades from 70 to 71 which leads to the issue: https://github.com/johnnyreilly/blog.johnnyreilly.com/pull/15

See the failing build which happens as a consequence of the upgrade here: https://github.com/johnnyreilly/blog.johnnyreilly.com/pull/15/checks?check_run_id=2101336052

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes!

## To Reproduce

```
git clone https://github.com/johnnyreilly/blog.johnnyreilly.com.git
cd blog.johnnyreilly.com
git checkout feat/upgrade-deps
cd blog-website
yarn
yarn build
```

## Expected behavior

Compilation with warnings but no errors.

## Actual Behavior

Many errors of the nature:

```
Docusaurus Node/SSR could not render static page with path=/tags/windows-defender because of error: Cannot read property 'replace' of undefined
Docusaurus Node/SSR could not render static page with path=/tags/wkhtmltopdf because of error: Cannot read property 'replace' of undefined
```

## Your Environment

- Public source code: https://github.com/johnnyreilly/blog.johnnyreilly.com
- Public site url: https://github.com/johnnyreilly/blog.johnnyreilly.com
- Docusaurus version used: 2.0.0-alpha.71
- Environment name and version (e.g. Chrome 78.0.3904.108, Node.js 10.17.0): Node 15 / Node 14 (experienced in both)
- Operating system and version (desktop or mobile): Mac OS (but GitHub Actions experiences the same and is Linux)

## Reproducible Demo

See To Reproduce.

**Comment by lex111** [comment]
Thanks for the report, it will be fixed in #4428.

However, I should inform you that due to the specificities of JSX, the contents of `pre` will be rendered in one line (i.e. without expected line breaks). To avoid this, you will either need to use a triple backtick or the CodeBlock component. I don't know how to automate this for you, but to get the correct code blocks formatting you need to use one of these methods.

**Comment by johnnyreilly** [comment]
Ah fascinating - yeah it turns out there's some `<pre`s tucked away in some historic blogs. I'll have to fix these up

https://github.com/johnnyreilly/blog.johnnyreilly.com/search?q=pre&type=

**Comment by johnnyreilly** [comment]
Cleaned my `<pre`s  - this turns out to have been a helpful bug to me :smile:
