### ISSUE TITLE
Accessibility issue: navigation across links in the menu that isn't displayed

### ISSUE THREAD

**Issue by Mihonarium** [facebook/docusaurus#4423]
## 🐛 Bug Report

When navigating using Tab/Alt+Tab, after the usual navbar the focus navigates to the invisible links in "navbar-sidebar".

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes.

## To Reproduce

Open https://v2.docusaurus.io/docs/, press Tab 13+ times. Before getting to the sidebar, the focus goes across the menu links again, but this time you don't see the focus.

## Expected behavior

After you go across the navbar, you should go to the sidebar, skipping the invisible copy of the menu.

(Write what you thought would happen.)

## Your Environment

Windows 10, Chrome 88.0.4324.150, 1920x1080p display.

**Comment by lex111** [comment]
Thanks for the report, this one dropped from my radar somehow, but will be fixed in #4429.

**Comment by slorber** [comment]
Should be fixed by https://github.com/facebookincubator/infima/pull/97
