### ISSUE TITLE
[v2.0.0-alpha.71] cb.apply is not a function on npx init

### ISSUE THREAD

**Issue by ebanDev** [facebook/docusaurus#4426]
## 🐛 Bug Report

When I run the command `npx @docusaurus/init@latest init a-name classic`

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## To Reproduce

1. Open a terminal as root on debian
2. Run `npx @docusaurus/init@latest init snowden-summary classic`

## Expected behavior

Erf, it should work ? 😅

## Actual Behavior

I have this output
```
root@veil:/var/www/snowden-summary# npx @docusaurus/init@latest init snowden-summary classic 
npm ERR! cb.apply is not a function

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-03-13T17_07_27_640Z-debug.log
```

## Your Environment

- Public source code: X
- Public site url: X 
- Docusaurus version used: latest version (on npx)
- Environment name and version (e.g. Chrome 78.0.3904.108, Node.js 10.17.0): NodeJS v15.11.0; npx 10.2.2; yarn 2.4.1
- Operating system and version (desktop or mobile): Debian 10

**Comment by slorber** [comment]
Can you please provide a full error log?
Can you try with a node LTS version li'e 14.x?

**Comment by ebanDev** [comment]
Hi tried with node v14.16.0 and it works ! Thanks !

**Comment by slorber** [comment]
@ebanDev can you consistently reproduce this with Node 15?

We'll keep this open for now and wire Node 15 CI checks, we must be ready for it

**Comment by lex111** [comment]
Apparently this is a cache-related (or another "operating system bugs") issue, so it really can be closed for now https://stackoverflow.com/questions/63429304/npm-err-cb-apply-is-not-a-function
