### ISSUE TITLE
PWA logs warning in Chrome 89

### ISSUE THREAD

**Issue by SimenB** [facebook/docusaurus#4439]
## 🐛 Bug Report

Opening https://v2.docusaurus.io/ and looking in the console, you'll see

```
Site cannot be installed: Page does not work offline. Starting in Chrome 93, the installability criteria is changing, and this site will not be installable. See https://goo.gle/improved-pwa-offline-detection for more information.
```

Link for convenience: https://goo.gle/improved-pwa-offline-detection

(Note that this also applies to e.g. youtube.com, so I assume it'll affect most sites with a PWA?)

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yep!

## To Reproduce

1. https://v2.docusaurus.io/
1. Open console (possibly with "Update on reload" enabled)

## Expected behavior

No warnings

## Actual Behavior

Warning

## Your Environment

- Public source code: This very repo
- Public site url: https://v2.docusaurus.io/
- Docusaurus version used: alpha.71 I guess?
- Environment name and version (e.g. Chrome 78.0.3904.108, Node.js 10.17.0): Chrome 89.0.4389.90, Node N/A
- Operating system and version (desktop or mobile): macOS 11.2.3 desktop

## Reproducible Demo

https://v2.docusaurus.io/

**Comment by MatanBobi** [comment]
I see this one also..
I looked at the `fetch` handler we have and it looks like it looks for [matches in the cache](https://github.com/facebook/docusaurus/blob/02cd5d343b8a9cd9fe5bb0975448a830567ee96a/packages/docusaurus-plugin-pwa/src/sw.js#L115) but I couldn't find any place where we `add` to the cache, is that done automatically? I'm not too familiar with service worker's cache behavior..

**Comment by Josh-Cena** [comment]
Seems fixed. There're no longer warnings logged.
