### ISSUE TITLE
Search input bug (site)

### ISSUE THREAD

**Issue by kvolkovich-sc** [facebook/Docusaurus#445]
### Is this a bug report?

yes

### Have you read the [Contributing Guidelines](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md)?

yes

### Environment

MacOS High Sierra, Chrome 64 (Firefox ESR - same behavior)

### Steps to Reproduce

1. Go to https://docusaurus.io/
2. Focus "Search" input
3. Type some text

### Expected Behavior

Display search results correctly

### Actual Behavior

Display search results incorrectly

![docusaurus-bug](https://user-images.githubusercontent.com/24652543/36100421-42d61390-1017-11e8-9490-7f90de1a9620.gif)

**Comment by JoelMarcey** [comment]
@kvolkovich-sc Thank you for bringing this to our attention. I fixed the bug.

**Comment by JoelMarcey** [comment]
@maaz93 Hi. The [overflow commit])https://github.com/facebook/Docusaurus/commit/5e39b2e01f79cf235cf23753634e831dc55d6a72) seemed to cause this issue. I [reverted](https://github.com/facebook/Docusaurus/commit/69603c968ecb8bd1dafe506bb516b11232f01967) it for now.

Maybe we need to be more specific with the placement of the overflow? Such as only when we are in mobile mode (which is done through the `@media only` lines).

**Comment by JoelMarcey** [comment]
I am going to close this issue since it is fixed. But I still want to try to get the overflow working on mobile.
