### ISSUE TITLE
Scrolling causes a noticeable stutter on Docusaurus v2 websites

### ISSUE THREAD

**Issue by RA80533** [facebook/docusaurus#4454]
## 🐛 Bug Report

> Scrolling causes a noticeable stutter on Docusaurus v2 websites

## To Reproduce

1. Go to [the docs section on the Docusaurus v2 website](https://v2.docusaurus.io/docs/)
2. Scroll to the top of the page
3. Attempt to scroll further upwards

### [Docusaurus v1](https://docusaurus.io/docs/en/installation)

<img width="1324" alt="Screen Shot 2021-03-17 at 9 01 38 PM" src="https://user-images.githubusercontent.com/32469082/111558111-8010dc00-8764-11eb-8890-d5a2de1a5a46.png">

> Maximum CPU Usage: 22.0%

- **Timers**
  - 5 × `setTimeout`
- **Events**
  - 44 × `scroll`

### [Docusaurus v2](https://v2.docusaurus.io/docs/)

<img width="1324" alt="Screen Shot 2021-03-17 at 9 57 53 PM" src="https://user-images.githubusercontent.com/32469082/111562056-e2210f80-876b-11eb-87fa-2d88e7a1ddf5.png">

> Maximum CPU Usage: 96.1%

- **Events**
  - 160 × `wheel`
  - 42 × `scroll`
  - 7 × `message`
  - 3 × `mousemove`
  - 2 × `pointermove`
- **Observers**
  - 889 × `IntersectionObserver`

## Your Environment

- Public site url: https://v2.docusaurus.io
- Docusaurus version used: 2.0.0-alpha.72
- Environment name and version: Safari 14.0.3 (14610.4.3.1.6)
- Operating system and version: macOS 10.14.6

**Comment by armano2** [comment]
i'm going to work on this
