### ISSUE TITLE
Deduplicate npm libraries (shelljs/execa, del/mkdirp)

### ISSUE THREAD

**Issue by armano2** [facebook/docusaurus#4455]
After going trough code i noticed that currently this project relies on multiple packages that essentially do same thing

should we use `shelljs.exec` or `execa` for cli commands?

should we use `fs-extra` or `shelljs` for file manupulation eg. rm, cp etc. 
should we keep using libraries like: `del`, `mkdirp`?

**Comment by slorber** [comment]
I don't know what we should do but would be ok to have a single lib instead of many if possible.

However please don't refactor too much at once, it's hard for me to review everything and still find time to iterate on features/bugfixes
