### ISSUE TITLE
Provide a way to let plugins use a compatible version of Joi

### ISSUE THREAD

**Issue by weareoutman** [facebook/docusaurus#4456]
## 🚀 Feature

Provide a way to let plugins (such as [my plugin](https://github.com/easyops-cn/docusaurus-search-local)) be compatible across Docusaurus versions, which both use Joi to do validation of options.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

yes

## Motivation

Currently Joi disallows mixing different versions of joi schema, however, we cannot make sure  Docusaurus and plugins use the same version of Joi if they specifies their own dependencies. Like [this issue](https://github.com/easyops-cn/docusaurus-search-local/issues/31#issuecomment-799622258) happened after a new Docusaurus version released.

Users can do a dedupe to fix this problem, but it's pretty annoying since Docusaurus releases frequently.

Another workaround maybe specifying Joi as a peer dependency in plugins, but I think it cannot always work, because Docusaurus and plugins are peers, but their own dependencies are not.

## Pitch

(Please explain why this feature should be implemented and how it would be used.)

**Comment by slorber** [comment]
Hey, totally agree on this, it was on my todo list.

We'll expose this:

```
import { Joi } from "@docusaurus/utils-validation"
```

**Comment by slorber** [comment]
PR: https://github.com/facebook/docusaurus/pull/4459

You'll need to require min version alpha 73 once released
