### ISSUE TITLE
<Tabs> should be insensitive to ordering mismatches

### ISSUE THREAD

**Issue by slorber** [facebook/docusaurus#4465]
## 🐛 Bug Report

```jsx
<Tabs
  values={[
    {label: 'Android', value: 'android'},
    {label: 'iOS', value: 'ios'},
    {label: 'Web', value: 'web'},
  ]}>
  <TabItem value="web">Web</TabItem>
  <TabItem value="android">Android</TabItem>
  <TabItem value="ios">iOS</TabItem>
</Tabs>
```

When the `values` array is not in the exact same order as the `<TabItems>`, we end up with a really weird experience:

Clicking on Android focus the Web tab (ie it does not focus the tab you click on)

![image](https://user-images.githubusercontent.com/749374/111768586-68427080-88a8-11eb-8624-b615ba5542a5.png)

Reported here: https://github.com/facebook/react-native-website/pull/2548
This is likely a regression of older accessibility refactor using refs, we were not sensitive to this issue before.

I think we should make the tabs non-sensitive again, using `values` as the source of truth, and eventually add a warning so that users avoid ordering mismatch.

cc @lex111 @Simek

**Comment by armano2** [comment]
i can work on this

**Comment by slorber** [comment]
Thanks @armano2 

please don't delete your comments even if they become useless, it is confusing for me 😅  and even stale comments can be useful for history 

Note: if you want to improve tabs a bit more, I think it can be cool to fallback to first tab in case no default tab has been provided as props, currently it shows nothing which imho is weird
