### ISSUE TITLE
Staging environment

### ISSUE THREAD

**Issue by collabnix** [facebook/docusaurus#4469]
I have a developer website based on docusaurus. Would like to know what general practice do people follow for staging and production environment . Before pushing my changes to prod site, I want to showcase it to my management. Do suggest.

**Comment by slorber** [comment]
Hi, please remember issues are not for questions.

If you use a modern Jamstack / static hosting solution like Netlify or Vercel, each PR against master will have a "deploy preview" enabling you to review the changes online with a unique URL. Once you merge the PR to master, it will automatically deploy to production. This is the workflow I would recommend.

See for example https://github.com/facebook/docusaurus/pull/4409#issuecomment-797353869

![image](https://user-images.githubusercontent.com/749374/111819170-54b2fc00-88e0-11eb-9b20-7a022c7a292f.png)


It is also possible to set up one deploy URL per git branch.

Github Pages can only have a single URL per repo so it is not a good fit.

If you want to use a single git branch or don't want a modern Jamstack hosting solution, you'll have to figure out yourself how to host the staging site. There are thousands of way to host static files, using `docusaurus serve`, Apache, Nginx, Varnish...
