### ISSUE TITLE
[v2.0.0-alpha.72] - customCss - Error: true is not a PostCSS plugin

### ISSUE THREAD

**Issue by tecfella** [facebook/docusaurus#4474]
## 🐛 Bug Report

Custom themes are broken in v2

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

No

## To Reproduce

versions
```
"@docusaurus/core": "^2.0.0-alpha.72",
"@docusaurus/module-type-aliases": "^2.0.0-alpha.72",
"@docusaurus/preset-classic": "^2.0.0-alpha.72",
```

```
// ./docusuarus.config.js

theme: {
 customCss: require.resolve('./src/css/custom.css'),
},
```

build output
```
./src/css/custom.css
Error: true is not a PostCSS plugin
 @ ./.docusaurus/client-modules.js 1:649-739
 @ ./node_modules/@docusaurus/core/lib/client/client-lifecycles-dispatcher.js
 @ ./node_modules/@docusaurus/core/lib/client/App.js
 @ ./node_modules/@docusaurus/core/lib/client/clientEntry.js
 @ multi ./node_modules/@docusaurus/core/lib/client/clientEntry.js./node_modules/remark-admonitions/styles/infima.css
```

## Expected behavior

It would build

## Actual Behavior

does not build

(Write what happened. Add screenshots, if applicable.)

## Your Environment

windows

**Comment by lex111** [comment]
Shouldn't the value of this field be an array? Try below code and let us know.

```
customCss: [require.resolve('./src/css/custom.css')],
```

**Comment by tecfella** [comment]
Hi Thanks for getting back to me.

I have tried an array - it still gives the same error.

**Comment by lex111** [comment]
Hmm, could you provide reproducible repo?

**Comment by satanTime** [comment]
installing `postcss@8` explicitly solves this issue. No need in wrapping the resolve with an array.
```
"postcss": "8.2.8",
```

**Comment by slorber** [comment]
@tecfella do you have a monorepo? can you try postcss 8 as said above?

Also log the value you pass to `customCss`?

**Comment by satanTime** [comment]
If you want an example with the issue, unfortunately, it is not a min sample: https://github.com/ike18t/ng-mocks/pull/326, if to remove `postcss` from changes then you should get the error.

**Comment by tecfella** [comment]
I rebuilt my repo from scratch, found the missing piece

Turns out adding  the file `./babel.config.js`
```
module.exports = {  
  presets: [require.resolve('@docusaurus/core/lib/babel/preset')], 
}; 
```

Thank you all for your help and suggestions.

I spent ages thinking there was a problem processing css from rehype-katex and remark-math. All good!

**Comment by slorber** [comment]
oh really? This should definitively work without that file

**Comment by slorber** [comment]
beta.0 use postcss8 so going to close this
