### ISSUE TITLE
Use symbols to denote "swizzle safety" on CLI for run swizzle

### ISSUE THREAD

**Issue by HonkingGoose** [facebook/docusaurus#4509]
## 🚀 Feature

Use a symbol to denote swizzle component "safety" instead of relying on color alone.

See this picture to see the current Swizzle CLI output: https://user-images.githubusercontent.com/749374/112303335-7293ae80-8c9c-11eb-834b-114ae28fd5ab.png

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/masterYe/CONTRIBUTING.md#reporting-new-issues)?

Yes.

## Motivation

Using color alone to distinguish between properties is not accessible for people who have green/red color blindness, or don't see color at all (fully colorblind, or no vision at all).

## Pitch

Idea: prefix CLI output with the word: "safe/unsafe"?

This should be implemented because it helps colorblind/blind people to get the same information as sighted users.

**Comment by slorber** [comment]
make sense, will assign this to a MLH fellow
