### ISSUE TITLE
[Proposal] Expose `ogImage` property

### ISSUE THREAD

**Issue by miralemd** [facebook/Docusaurus#451]
Noticed that it's possible to get an `og:image`meta header in the generated website by setting a value for `ogImage` in `siteConfig.js`.

Would be nice to have this documented on [site-config.html](https://docusaurus.io/docs/en/site-config.html)

**Comment by JoelMarcey** [comment]
Hi @miralemd Are you willing to provide a pull request adding to the documentation? You would edit https://github.com/facebook/Docusaurus/blob/master/docs/api-site-config.md
