### ISSUE TITLE
[v2.0.0-alpha.72] Layout of doc pages without a sidebar looks awkward

### ISSUE THREAD

**Issue by MisterFISHUP** [facebook/docusaurus#4512]
## 🐛 Bug Report

The layout of a doc page without the sidebar looks awkward to me. The page content is deviated to the left too much, so as the right toc. In addition, the left and right paddings of the page look unbalanced, since there is almost no padding on the left but there is a large padding on the right. See screenshots below.

**Before (with sidebar), looks good:**
![Screenshot from 2021-03-24 17-35-26](https://user-images.githubusercontent.com/68397336/112355886-6294c280-8cce-11eb-9f1e-097801140fb4.png)

**After (without sidebar), looks awkward:**
![Screenshot from 2021-03-24 17-34-24](https://user-images.githubusercontent.com/68397336/112355998-793b1980-8cce-11eb-8fad-eb7afc7e9bed.png)

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes.

## To Reproduce

Create a new project with `npx @docusaurus/init@latest init my-website classic`. In `sidebars.js`, just remove a doc page or set the type to `ref` for that page.

## Expected behavior

The page content and the right toc should be in the right place. Either remove the sidebar without changing the layout of any other elements on the page, or completely remove the sidebar along with the space it occupied then add some left padding to the page content (and adjust the width/position of page content and right toc for the new layout if necessary).

## Your Environment

- Docusaurus version used: v2.0.0-alpha.72
- Environment: Node v14.16.0
- Operating system and version (desktop or mobile): ubuntu 20.04

**Comment by slorber** [comment]
@MisterFISHUP just wondering why did you close this issue?

I'd like to fix these layout issues and agree that it looks awkward

**Comment by MisterFISHUP** [comment]
Oh, my bad. Thanks for your time, I'll reopen this issue.

**Comment by slorber** [comment]
Thanks @MisterFISHUP 

@lex111 has centered better the content here https://github.com/facebook/docusaurus/pull/4621#issuecomment-821006630

Was wondering, what's your usecase for using docs without any sidebar? Why don't you use a page instead?
I'd like to add a warning to protect about that as it's quite often due to having forgotten to add a doc to the sidebar (we would be able to disable this warning through config or frontmatter?)

**Comment by MisterFISHUP** [comment]
@lex111 Thanks for fixing this problem.
@slorber You are not wrong, I ended up using a page instead of a doc page with no sidebar, but I still feel it's a work around in my case.
I use docs to write something like a book/a diary, and I would like to have a preface page. Chapters in this book will have urls `/book/chapter1`, `/book/chapter2`, etc, and I want the url of the preface page to be just `/book`. It's natural for me to put the preface md in the docs folder along with all the other pages in the book, and then just set the slug of preface to be `./`. The only problem was that this preface page without any sidebar looked awkward, and that's why I opened this issue.
I then used page for the preface to solve the layout problem. It worked well, but I feel it's a work around because:
1. It's conceptually better and fairly reasonable to have the preface and all other book pages in the same folder/in the docs folder
2. When using md as a normal page instead of a doc page, you lose the default doc page style. The heading `h1`, `h2`, etc are smaller, so are the margins/paddings. As a result, the layout of a normal md page looks very different from the one of a doc md page even you write the same markdown (smaller headings, sections are less separated, etc). So some extra css are needed to have a coherent layout.
3. When I put the preface page (`/book`) and some doc pages (ex: `/book/chapter1`) in the navbar, I had to add `activeBaseRegex: "book/?$"` for the preface page, which isn't a problem but this config is not necessary if a doc page is used.

You can find the real use case on my website [Daily Digest - COVID-19 IN FRANCE](https://covid-fr.misterfishup.com/en/), where `/book` illustrated above becomes `/digest`. (Sorry that the repo is currently private. It'll be public next week after I finish up some work.)

**Comment by slorber** [comment]
I see thanks @MisterFISHUP 

please add your site to the showcase, it is pretty nice with i18n and a custom design and some cool frontend dataviz

**Comment by MisterFISHUP** [comment]
@slorber Ok I'll do so. Thanks for your kind comment, it just made my day :)
