### ISSUE TITLE
[v2.0.0-alpha.72] Lack of space between headings and sticky nav bar

### ISSUE THREAD

**Issue by MisterFISHUP** [facebook/docusaurus#4513]
## 🐛 Bug Report

It's not really a bug but rather a small problem of layout. When clicking on a heading of some markdown page (in the right toc or page content), we jump to the heading, and if the nav bar hides on scroll (with `hideOnScroll: true` in config), the heading has a decent top padding/margin. But with sticky nav bar (which is the default setting), the top padding/margin somehow disappears: the heading is almost touching the nav bar, which doesn't look as good as the layout with non sticky nav bar. It looks a bit awkward to me in fact. See the screenshots below.

**When the nav bar is sticky (default setting), the clicked heading is almost touching the nav bar, i.e. the top-padding/margin is not enough:**
![Screenshot from 2021-03-24 19-03-27](https://user-images.githubusercontent.com/68397336/112363954-57459500-8cd6-11eb-99b7-371458db1310.png)

**When the nav bar hides on scroll with `hideOnScroll: true`, the heading has some good top-padding/margin:**
![Screenshot from 2021-03-24 19-16-26](https://user-images.githubusercontent.com/68397336/112363921-51e84a80-8cd6-11eb-99f5-520d86eb70d0.png)

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes,

## To Reproduce

It should be the case for any pages with sticky nav bar.

## Expected behavior

The heading should have some top padding/margin as in the case of non-sticky nav bar.

## Your Environment

- Docusaurus version used: v2.0.0-alpha.72
- Environment: Node 14.16.0
- Operating system and version (desktop or mobile): ubuntu 20.04

**Comment by sandyabhi** [comment]
Hi @MisterFISHUP I would like work on it

**Comment by MisterFISHUP** [comment]
> Hi @MisterFISHUP I would like to work on it

Awesome! Thanks!

**Comment by sandyabhi** [comment]
@MisterFISHUP can you tell the page name I didn't find this page

**Comment by MisterFISHUP** [comment]
The easiest way to solve this would be to add the following css globally:
```
a {
  scroll-margin-top: 1rem;
}
```
since a heading is always linked to some anchor tag inside the heading tag.
