### ISSUE TITLE
A very common reason is a wrong site baseUrl configuration.

### ISSUE THREAD

**Issue by gHashTag** [facebook/docusaurus#4519]
Your Docusaurus site did not load properly.
A very common reason is a wrong site baseUrl configuration.
Current configured baseUrl = / (default value)
We suggest trying baseUrl = /

My [baseUrl](https://github.com/gHashTag/jscamp/blob/877595d27c22bda42b62c7adea36257f40aa4693/docusaurus.config.js#L14)
```baseUrl = '/'```

![2021-03-26 16 30 53](https://user-images.githubusercontent.com/6774813/112625425-b6c7b000-8e50-11eb-9633-9c9140b56f14.jpg)

Behavior is different on different computers. Somewhere so, but somewhere normal.

What is the problem and how to fix it?

**Comment by slorber** [comment]
Can you provide a repro?
Is it open-source or available online? 
Can you show browser console logs? The css likely fails to load for some reason.

**Comment by gHashTag** [comment]
@slorber  https://github.com/gHashTag/jscamp

**Comment by slorber** [comment]
Thanks, I'll need more details to be able to help you

**Comment by gHashTag** [comment]
What else is needed?

**Comment by slorber** [comment]
> Can you provide a repro?
Is it open-source or available online?
Can you show browser console logs? The css likely fails to load for some reason.

It would help if you explain on which computer you have the problem and give details of the env browser, versions and everything. Please be exhaustive

**Comment by gHashTag** [comment]
The problem disappeared. I'm sorry. I close the task.
