### ISSUE TITLE
customize an alias like `@site`

### ISSUE THREAD

**Issue by xianjie-li** [facebook/docusaurus#4520]
## 🚀 Feature

when developing some small libraries, need to simulate user imports directly in the development environment.

config alias
```ts
{
      "my-library": ["src/index.ts"]
}
```

and use in doc page
```js
import { MyComponent } from 'my-library';


<MyComponent />
```

**Comment by slorber** [comment]
There is a `configureWebpack` hook, you can use it to add your custom webpack aliases
