### ISSUE TITLE
Inconsistent layout between Docs and Blog

### ISSUE THREAD

**Issue by Josh-Cena** [facebook/docusaurus#4523]
## 🐛 Bug Report

The container sizing is different in Docs and Blog.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes.

## To Reproduce

Build a site with both `Docs` and `Blog`.

## Expected behavior

The sidebar and the main container should have the same sizing in Docs or in Blog.

## Actual Behavior

The sidebar is wider in `Blog` than in `Docs` on my screen; in fact, they use completely different sizing approaches.

The Blog uses `col col--3` for sidebar and `col col--7` for main container, with inner margins for the page container.

![Blog sidebar sizing](https://user-images.githubusercontent.com/55398995/112707738-6b60e080-8ee8-11eb-9990-12f9aed34bb9.png)

The Docs has no page margins, and hard-codes the sidebar width as 300px.

![Docs sidebar sizing](https://user-images.githubusercontent.com/55398995/112708095-dd3a2980-8eea-11eb-9b47-0d3e1533f149.png)

The result is inconsistent formatting if one switches between the two pages.

## Your Environment

- Docusaurus version used: 2.0.0-alpha.72
- Environment name and version: Chrome 89.0.4389.90, Node.js 12.16.1
- My screen: 1440×900

## Reproducible Demo

The [Docusaurus page](https://docusaurus.io/blog) demonstrates this already.

**Comment by sandyabhi** [comment]
Hey @Josh-Cena I would like to work on it

**Comment by Josh-Cena** [comment]
> Hey @Josh-Cena I would like to work on it

@sandyabhi Sure 😂 I think some swizzling should be enough? I haven't looked into the layout-related code

**Comment by Josh-Cena** [comment]
I can see that the rationale is probably because the docs sidebar is collapsable, so a fixed-width container is used instead of a grid layout. I think we can use the same sidebar width for blog as well.

**Comment by lex111** [comment]
> The sidebar and the main container should have the same sizing in Docs or in Blog.

@Josh-Cena I don’t think so, sidebars of blog and docs are completely different, so they should not necessarily be identical by width. The blog layout uses Infima's built-in grid system, while docs layouts use custom one. This is okay, so I do not see any inconsistency here. Do you agree to this?

**Comment by Josh-Cena** [comment]
@lex111 I agree that they are different pages, but such close resemblance in their layouts makes it just look like a glitch right now... I mean, if one is three columns while the other has two columns, I will have no trouble in understanding that they are independent; but both being three columns, with nearly the same width, and with the main article typeset in the exact same way makes the nuanced difference more noticeable.

**Comment by lex111** [comment]
Technically, these two layouts are made in different ways, especially since sidebar in docs layout is pinned to the left side of window, so there is no feeling of inconsistency for me when compared with blog layout. Moreover, sidebar width in blog layout is dynamic, not fixed like in docs layout, so it is not reasonable to make it only one width of 300px -- it breaks built-in grid system.

**Comment by Josh-Cena** [comment]
I understand your concern here, but is there any reason we want to keep using the grid system for the blog sidebar, rather than treating it the same way as the docs sidebar? The docs and blog pages are 90% the same, with just the sidebar being different. This to me is really arbitrary...

**Comment by lex111** [comment]
Grid system also used in doc layout, but only in the part related to doc content. This is complex layout that purposely uses the sticky doc sidebar with fixed width. Therefore, we do not need to change anything in it.

**Comment by Josh-Cena** [comment]
I mean, the blog sidebar can have a fixed-width container as well—that makes it potentially collapsible, and just infinitely more unified with the docs page. That makes the site more consistent as a whole.

**Comment by lex111** [comment]
No, it is bad practice to explicitly set the column width in the grid container. Moreover, a collapsible sidebar is possible only if it is pinned to a side of window, otherwise it will look ugly. Just accept the fact that docs and blog layouts are different, so they may not be identical.

**Comment by Josh-Cena** [comment]
Okay, I see😅
