### ISSUE TITLE
Pipe + other character inside non-top-level <code> block renders as plain text

### ISSUE THREAD

**Issue by aszecsei** [facebook/docusaurus#4534]
## 🐛 Bug Report

When in a non-HTML context (that is, no top-level HTML tag exists), escaping a single pipe within a `<code>` tag works as expected, but adding any other characters causes the contents of the `<code>` tag to render as plain text (not as code).

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes.

## To Reproduce

https://codesandbox.io/s/docusaurus-issue-demo-zhgzo
https://zhgzo.sse.codesandbox.io/docs/#problem-table

Create a table with a `<code>` block containing two instances of the vertical pipe escape code (`&#124;`). The sandbox has various examples of what renders correctly and what doesn't.

## Expected behavior

I expect it to render as below:

| Code                      | Words       |
| ------------------------- | ----------- |
| `hello`                   | hello       |
| <code>&#124;</code>       | Single pipe |
| <code>&#124;&#124;</code> | Double pipe |

## Actual Behavior

It renders as below instead:

| Code                      | Words       |
| ------------------------- | ----------- |
| `hello`                   | hello       |
| <code>&#124;</code>       | Single pipe |
| \|\| | Double pipe |

## Your Environment

- Docusaurus version used: 2.0.0-alpha.72
- Environment name and version (e.g. Chrome 78.0.3904.108, Node.js 10.17.0): CodeSandbox + node 14, windows 10 + node 14
- Operating system and version (desktop or mobile): Desktop

## Reproducible Demo

https://codesandbox.io/s/docusaurus-issue-demo-zhgzo
https://zhgzo.sse.codesandbox.io/docs/#problem-table

**Comment by slorber** [comment]
Agree there seems to be something wrong.

The following should work consistently:

```md
<p>Code tag + double pipe inside paragraph tag: <code>||</code></p>

Code tag + double pipe: <code>||</code>
```

Using the MDX playground, it looks like MDX does output the code blocks in both cases:

https://mdxjs.com/playground/

![image](https://user-images.githubusercontent.com/749374/112956916-3b604a00-9141-11eb-9ff4-7e506a1ae69d.png)

So it may be a problem in Docusaurus integration.

Not sure which MDX version is used in this playground, maybe it's an older MDX bug that has been fixed?

**Comment by slorber** [comment]
please try the latest `@canary` release and tell us if the bug is fixed
