### ISSUE TITLE
Out-of-the-box syntax highlighting is broken for at least Java, PHP, & Ruby.

### ISSUE THREAD

**Issue by flossypurse** [facebook/docusaurus#4535]
## 🐛 Bug Report

Out-of-the-box syntax highlighting is broken for at least Java, PHP, & Ruby.

There may be others...

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

(Write your answer here.)

Yes.

## To Reproduce

If possible, use https://new.docusaurus.io to create a CodeSandbox reproducible demo of the bug.

Sandbox didn't work. Received a `docusaurus not found` error when I tried to save changes, even after logging in.

(Write your steps here:)

1. Do a fresh install of Docusuarus using the classic theme, i.e.:

`npx @docusaurus/init@latest init my-website classic`

2. Add java, php, or ruby code to a Markdown page, such as:

Java:
```java
import io.temporal.workflow.Workflow;
import io.temporal.workflow.WorkflowInterface;
import io.temporal.workflow.WorkflowMethod;
import org.slf4j.Logger;

public class GettingStarted {

    private static Logger logger = Workflow.getLogger(GettingStarted.class);

    @WorkflowInterface
    public interface HelloWorld {
        @WorkflowMethod
        void sayHello(String name);
    }

    public static class HelloWorldImpl implements HelloWorld {

        @Override
        public void sayHello(String name) {
            logger.info("Hello " + name + "!");
        }
    }
}
```

PHP:
```php
#[ActivityInterface("file_activities.")]
interface FileProcessingActivities
{
    public function upload(string $bucketName, string $localName, string $targetName);

    #[ActivityMethod("transcode_file")]
    public function download(string $bucketName, string $remoteName);

    public function processFile(): string;

    public function deleteLocalFile(string $fileName);
}
```

Ruby:
```ruby
class AsyncActivity < Temporal::Activity
  timeouts start_to_close: 120

  def execute
    logger.warn "run `bin/activity complete #{activity.async_token}` to complete activity"

    activity.async
  end
end
```

3. Run a local server to view the site.

## Expected behavior

Code examples specified with a code type should have code specific syntax highlighting for popular languages like PHP, Ruby, and Java.

## Actual Behavior

There is NO syntax highlighting for some langauges.
It works for some like Go and Javascript. But not all.
See screen shots:

Source:
![Screen Shot 2021-03-29 at 4 24 06 PM](https://user-images.githubusercontent.com/34380806/112907503-3486f800-90ab-11eb-98b5-6e8677609147.png)

Built site:
![Screen Shot 2021-03-29 at 4 24 53 PM](https://user-images.githubusercontent.com/34380806/112907554-4f596c80-90ab-11eb-9aaf-d906dabab2ec.png)

## Your Environment

- Public source code:
This is from a fresh install of YOUR source code.
But we use it in our docs site here:
https://github.com/temporalio/documentation

- Public site url:
I won't upgrade my public site until this is fixed.
But here ya go: https://docs.temporal.io/

- Docusaurus version used: 
In depth testing was done using:
@docusaurus/core v2.0.0-alpha.72
@docusaurus/preset-classic v2.0.0-alpha.72

But some testing revealed issues starting with 2.0.0-alpha.68
I am using 2.0.0-alpha.66 which works find
- Environment name and version (e.g. Chrome 78.0.3904.108, Node.js 10.17.0):
Node v15.2.1
Chrome Version 89.0.4389.90 (but tested across other browsers Safari & Firefox and same)
- Operating system and version (desktop or mobile):
Mac OS Big Sur v11.2.3

## Reproducible Demo

If possible, use https://new.docusaurus.io to create a CodeSandbox reproducible demo of the bug.

That did not work for me -
Just do a fresh install and see for yourself - takes 1 min.

**Comment by Josh-Cena** [comment]
According to the [docusaurus doc](https://docusaurus.io/docs/markdown-features/code-blocks#syntax-highlighting), 

> By default, Docusaurus comes with this subset of [commonly used languages](https://github.com/FormidableLabs/prism-react-renderer/blob/master/src/vendor/prism/includeLangs.js).

Which doesn't include Java, PHP, or Ruby. You have to manually include them in the config.

I have encountered the same thing, and I wonder why they didn't choose these languages to support out-of-the-box...

**Comment by flossypurse** [comment]
Ah, yes just figuring this out.
The thing is - those languages used to be included by default.
I was confused because we upgraded our site, and discovered that some of the languages stopped working...

Appreciate it @Josh-Cena Thank you!
