### ISSUE TITLE
AlgoliaSearchError: Invalid Application-ID or API key

### ISSUE THREAD

**Issue by rafaelnsantos** [facebook/Docusaurus#454]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md)?

Yes

### Environment

Github gh-pages
docusaurus: 1.0.6

### Steps to Reproduce

1. Open https://rafaelnsantos.github.io/unity-cloudsave/
2. Type in search box

### Expected Behavior

Show result box.

### Actual Behavior

Result box don't show.

This is the Request URL:
https://bh4d9od16a-3.algolianet.com/1/indexes/*/queries?x-algolia-agent=Algolia%20for%20vanilla%20JavaScript%203.21.0%3Bdocsearch.js%201.5.0&x-algolia-application-id=BH4D9OD16A&x-algolia-api-key=db51bcd5e513cfe52faa7ea59f2566b5

This is not my algolia-application-id, couldn't find where to set it.

### Reproducible Demo

https://rafaelnsantos.github.io/unity-cloudsave/

1. Open 
2. Type in search box

**Comment by rafaelnsantos** [comment]
This is the siteConfig https://github.com/rafaelnsantos/unity-cloudsave-site/blob/master/website/siteConfig.js#L68

I couldn't find how to set the id.

**Comment by JoelMarcey** [comment]
Hi @rafaelnsantos -- your setting looks correct. Maybe I am misunderstanding the issue here.

Did you get that `apiKey` directly from Algolia? i.e., did they email it to you? 

I see you have an Algolia config here for your site: https://github.com/algolia/docsearch-configs/blob/master/configs/unity_cloud_save.json

**Comment by rafaelnsantos** [comment]
Hi @JoelMarcey I'm using the apiKey from algolia dashboard, the email didn't have an apiKey.

The issue is the application-id in the request, I believe BH4D9OD16A is facebook's algolia application id.

Where can I change algolia application id?

**Comment by JoelMarcey** [comment]
We don't use the `application-id` in Docusaurus. e.g., no where in https://github.com/facebook/Docusaurus do we use `application-id`.

I checked a couple of other sites that use Docusaurus - https://docusaurus.io/en/users.html

They don't use `application-id` either.

Is this something you may want to ask support@algolia.com about?

**Comment by rafaelnsantos** [comment]
Thank you @JoelMarcey ! Solved talking to algolia support.

**Comment by JoelMarcey** [comment]
Great! I am glad you were able to resolve this.

**Comment by stonebk** [comment]
@rafaelnsantos what was your solution?

**Comment by s-pace** [comment]
👋 Are you running DocSearch yourself or are you using the hosted version of it?

When we host it for you, you do not need to mention your appId but once you are using it on your own, [you need to specify it](https://community.algolia.com/docsearch/documentation/docsearch-scraper/overview/).

**Comment by dsmmcken** [comment]
Comment for future searchers. If you are running your own agolia crawler you MUST set your own app ID from your agolia account.

appId: 'BH4D9OD16A', is tied to the docsearch free account appId, and is hardcoded as the default.

Set your appId in the docusaurus.config.js as

```
themeConfig: {
    agolia: {
        appId: 'your-app-id',
        apiKey: 'your-api-key',
    }
}
```

Might be worth a note on the https://v2.docusaurus.io/docs/search/#connecting-algolia section that appId must be set if you are running your own crawler.

**Comment by slorber** [comment]
@dsmmcken docs PR are welcome :)
