### ISSUE TITLE
Include code snippets

### ISSUE THREAD

**Issue by ibraheemdev** [facebook/docusaurus#4540]
## 🚀 Feature

I'm not sure if you can do this currently, but it would be nice if there was a way to include code snippets from a file:
```html
You can do X like so:

{{ include "foo.js" }}

// expands to

'''js
// the code from foo.js
'''
```

## Motivation

Many other static site generators include this feature, and having it would make migration easier. It would also allow you to test/compile those examples in CI to make sure the code is up to date.

Is this possible currently with react components?

**Comment by ibraheemdev** [comment]
Oh, I just saw that this is possible [from this example](https://github.com/facebook/docusaurus/blob/master/website/src/pages/examples/markdownPageExample.md#import-code-block-from-source-code-file). Maybe documentation should be added to the code blocks or files section?

**Comment by slorber** [comment]
Yes, I wanted to create some kind of recipes section but if you feel like adding this to code blocks is helpful, PR is welcome 😉
