### ISSUE TITLE
[Theme Bug]: in csharp/C# code, i lost my code color. : - (

### ISSUE THREAD

**Issue by HondryTravis** [facebook/docusaurus#4553]
## 🐛 Bug Report

in my code, i change this language type to cpp, this theme is right ,but i changed type to cs. it's just like this.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

(No)

## Actual Behavior

1. in vscode, i changed this language type to cs
![image](https://user-images.githubusercontent.com/24218012/113394406-c2742300-93ca-11eb-828f-3af96f0e5fe6.png)
2. in website
![image](https://user-images.githubusercontent.com/24218012/113394234-76c17980-93ca-11eb-8d9c-14d653bdb426.png)
3. change to cpp
![image](https://user-images.githubusercontent.com/24218012/113395328-3ebb3600-93cc-11eb-8565-4d0494b14f71.png)
4. in website
![image](https://user-images.githubusercontent.com/24218012/113395368-4da1e880-93cc-11eb-9895-3b7192182aaf.png)
this color is bad

(Write what happened. Add screenshots, if applicable.)

## Your Environment

- Public source code: https://github.com/HondryTravis/Blog/blob/master/packages/docs/thinking/design_patterns.md
- Public site url: https://github.com/HondryTravis/Blog/blob/master/packages/docs/thinking/design_patterns.md#c-实现
- Docusaurus version used: 2.0.0-alpha.72
- Environment name and version (e.g. Chrome 78.0.3904.108, Node.js 10.17.0):  edge:89.0.774.63, nodejs:v14.16.0
- Operating system and version (desktop or mobile):macos

## Reproducible Demo

https://hondrytravis.github.io/docs/thinking/design_patterns#c-实现

**Comment by slorber** [comment]
As documented, Docusaurus does not support all languages by default, and you have to provide additional config to enable more languages: 
https://docusaurus.io/docs/markdown-features/code-blocks#syntax-highlighting

**Comment by HondryTravis** [comment]
@slorber thinks a lot :D
