### ISSUE TITLE
Highlight menu item if selected

### ISSUE THREAD

**Issue by zanonnicola** [facebook/Docusaurus#456]
### Is this a bug report?

yes

### Have you read the [Contributing Guidelines](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md)?

yes

### Environment

MacOS
Node 9
Npm 5

### Steps to Reproduce

1. Open https://docusaurus.io/
2. Click on one of the nav item
3. The nav items doesn't change state
4. There's no visual clue that the page has changed in the navigation (aside from the URL)

### Expected Behavior

It should have an `active` class to reflect the current page on the navigation bar

### Actual Behavior

You can't really tell on which page you are because the nav item is not highlighted when selected. 

### Reproducible Demo

https://new.babeljs.io/

I was able to fix this via JS: https://github.com/babel/website/pull/1580 but it would be better if we had a better way to address this problem in Docusaurus directly.

<img width="1223" alt="screen shot 2018-02-16 at 19 39 04" src="https://user-images.githubusercontent.com/5839772/36323399-1a761af2-1351-11e8-812e-1e78b4bc78cc.png">

**Comment by JoelMarcey** [comment]
This is similar to https://github.com/facebook/Docusaurus/issues/178

**Comment by JoelMarcey** [comment]
@zanonnicola Thanks for raising this. I just looked at  babel/website#1580. We can probably do something similar to integrate into the Docusaurus core.

**Comment by JoelMarcey** [comment]
This was fixed in https://github.com/facebook/Docusaurus/pull/463. I hope that resolves the issue. Let me know if it does not.

See https://docusaurus.io/docs/en/installation.html for an example of the highlight.

**Comment by zanonnicola** [comment]
Awesome!! 🎉
