### ISSUE TITLE
Impossible to launch playground with alpha.72

### ISSUE THREAD

**Issue by christophemenager** [facebook/docusaurus#4566]
I am sorry not to follow the usual bug report template, but I think this one is very easy to reproduce.

## Repro steps
1. Go to https://docusaurus.io/ and click on "Playground"
2. In codesandebox, try to switch to v72 in package.json (for both dependencies, as described in the documentation)
3. The default node version of the sandebox in 10 but it appears v72 requires node 12
4. I did not manage to switch to node 12 and relaunch, see image below

![image](https://user-images.githubusercontent.com/17217868/113488807-a18df980-94c0-11eb-9e13-daf532a75926.png)

## Impact
Impossible for me to prepare an example of an other bug I was having with alpha 72, about translations

## Possible solution
Start the playground with node 12 and alpha 72 by default ?

**Comment by slorber** [comment]
Thanks, will be fixed in https://github.com/facebook/docusaurus/pull/4574
