### ISSUE TITLE
"Blog-only" configuration with alpha.72

### ISSUE THREAD

**Issue by christophemenager** [facebook/docusaurus#4567]
First of all, thanks for the amazing work on this project ! 👍 

Source code : https://github.com/christophemenager/christophem-blog
Blog in production : https://chrichri.netlify.app/

I am running a "blog only" version of docusaurus and I followed [the documentation here](https://docusaurus.io/docs/blog#blog-only-mode) without any issue, it works like a charm BUT : 

## The newly released i18n feature does not work (I followed the documentation about the setup precisely)
1. The default locale is perfectly fine
2. When trying to access www.my-personal-blog/en, I see a 404 error.  https://chrichri.netlify.app/en/

Ideas
I suspect it's because there is no` index.js` in a "blog-only" configuration and maybe docusaurus is trying to find such a file ? 

## The JSX in markdown does not work when importing a component declared in an other file

1. I created a custom component in `src/components/PhoneView.tsx` https://github.com/christophemenager/christophem-blog/blob/main/src/components/PhoneView.tsx
2. I imported it from an mdx file in `2021-04-05-scrollview-style.mdx` with `import {PhoneView} from '../src/components/PhoneView.tsx'` and use it in the blog post `<PhoneView />` https://github.com/christophemenager/christophem-blog/blob/main/blog/2021-04-05-scrollview-style.mdx
3. I see a blank screen after reloading the page, absolutely nothing appears 

Ideas
If I copy/paste the content of `PhoneView.tsx` directly in the blog post, it works. It's as if declaring a component in an other file than the mdx file was breaking something. 
I tried many thing :
1. Not using typescript but plain js 
2. Declaring my component file in an other location that src
3. Using absolute path for importing
4. Using default export

**Comment by slorber** [comment]
Thanks, this is indeed a bug due to a typo, that I just fixed in https://github.com/facebook/docusaurus/pull/4575

The build process was sensitive to the order in which the user provides the locales, and thought it had reached the last locale to build of the list. In the end, Docusaurus just builds your site in "fr" and never in "en"

Temporary workaround: put the default locale first in the list:

```
  i18n: {
    defaultLocale: 'fr',
    locales: ['fr', 'en'],
    localeConfigs: {
      en: {
        label: 'English',
      },
      fr: {
        label: 'Français',
      },
    },
  },
```
