### ISSUE TITLE
Cannot use @docusaurus/theme-live-codeblock with Yarn 2 (Berry)

### ISSUE THREAD

**Issue by hckhanh** [facebook/docusaurus#4584]
I get this error:

```
Module not found: prism-react-renderer tried to access react (a peer dependency) but it isn't provided by its ancestors; this makes the require call ambiguous and unsound.
```

Is there any way to workaround with this?

**Comment by slorber** [comment]
Can you provide more details about your env? That would be helpful when someone has time to investigate this.

Versions (docusaurus, yarn), OS... a publicly available repro is welcome

Is this error just a log or does it prevent the site to start/build?

**Comment by slorber** [comment]
no infos, closing
