### ISSUE TITLE
Strict frontmatter validation

### ISSUE THREAD

**Issue by slorber** [facebook/docusaurus#4591]
## 🚀 Feature

We should validate docs/blog/pages frontmatter against a Joi schema:

- prevent the user to use bad frontmatter
- display friendly error messages when this happens
- allow unknown frontmatter (user can assign additional metadata to each doc)
- unit-test this validation logic
- try to use the frontmatter TS types in the theme?

Some initial work has been done in https://github.com/facebook/docusaurus/pull/4590 for Docs and Blog, but is not exhaustive as it was not really the point of this PR.

Asking for help from the community to get this work completed in a more exhaustive and polished way.

Please claim this issue if you are willing to help.

**Comment by ChayceJRoss** [comment]
I'd be willing to help with this.
To be clear front matter is the content found at the top of the markdown files?
`---
title: Some Title
---`

I'm guessing the first step is to define the schema?

**Comment by Joshverge** [comment]
@slorber I'd like to help!

**Comment by slorber** [comment]
As we have 2 volunteers, I suggest:
- @ChayceJRoss works on docs: packages/docusaurus-plugin-content-docs/src/docFrontMatter.ts 
- @Joshverge works on blog: packages/docusaurus-plugin-content-blog/src/blogFrontMatter.ts 

Can you please review each-others and make sure both PRs have some kind of consistency and similar test structure?

Yes @ChayceJRoss those are the exhaustive list of frontmatter options to support

**Comment by jakehsiao** [comment]
I'd like to help too, where I can grab?

**Comment by slorber** [comment]
@jakehsiao we can't split more the work than it is already. 
If we don't have news from @ChayceJRoss and @Joshverge under 7 days we'll assign that to you.

**Comment by Joshverge** [comment]
@slorber maybe @jakehsiao could grab the work assigned to me? I haven't been able to make much progress since I'm a beginner at ts/js

**Comment by ywjr** [comment]
mysite   is  ok  on   alpha.7   ，  when  upgrade     to   alpha.73,    The following error occurred：

D:\doc\helpcenter\helpcenter>yarn upgrade @docusaurus/core@2.0.0-alpha.73 @docusaurus/preset-classic@2.0.0-alpha.73
yarn upgrade v1.22.5



:\doc\helpcenter\helpcenter>yarn start
yarn run v1.22.5
$ docusaurus start
Starting the development server...
ValidationError: "title" must be a string
    at Object.exports.process (D:\doc\helpcenter\helpcenter\node_modules\joi\lib\errors.js:184:16)
    at Object.internals.entry (D:\doc\helpcenter\helpcenter\node_modules\joi\lib\validator.js:150:26)
    at Object.exports.entry (D:\doc\helpcenter\helpcenter\node_modules\joi\lib\validator.js:27:30)
    at internals.Base.validate (D:\doc\helpcenter\helpcenter\node_modules\joi\lib\base.js:548:26)
    at Object.internals.assert (D:\doc\helpcenter\helpcenter\node_modules\joi\lib\index.js:225:27)
    at Object.attempt (D:\doc\helpcenter\helpcenter\node_modules\joi\lib\index.js:107:26)
    at Object.assertDocFrontMatter (D:\doc\helpcenter\helpcenter\node_modules\@docusaurus\plugin-content-docs\lib\docFrontMatter.js:22:28)
    at Object.processDocMetadata (D:\doc\helpcenter\helpcenter\node_modules\@docusaurus\plugin-content-docs\lib\docs.js:66:22)
    at processVersionDoc (D:\doc\helpcenter\helpcenter\node_modules\@docusaurus\plugin-content-docs\lib\index.js:89:35)
    at Array.map (<anonymous>)
    at loadVersionDocsBase (D:\doc\helpcenter\helpcenter\node_modules\@docusaurus\plugin-content-docs\lib\index.js:96:45)
    at async loadVersion (D:\doc\helpcenter\helpcenter\node_modules\@docusaurus\plugin-content-docs\lib\index.js:100:34)
    at async Promise.all (index 0)
    at async Object.loadContent (D:\doc\helpcenter\helpcenter\node_modules\@docusaurus\plugin-content-docs\lib\index.js:167:33)
    at async D:\doc\helpcenter\helpcenter\node_modules\@docusaurus\core\lib\server\plugins\index.js:53:46
    at async Promise.all (index 5)
error Command failed with exit code 1.

**Comment by ywjr** [comment]
Document title should be allowed to use Chinese or other languages

**Comment by slorber** [comment]
@ywjr can you give us the title that gets rejected exactly? Why do you think it's because of the Chinese language?

**Comment by ywjr** [comment]
After testing again, the title in the MD file cannot be empty. If it is empty, an error will appear.

 In addition, when the title field in the MD file is Chinese, there is no problem

**Comment by ywjr** [comment]
I don't think it's a bug, but it's suggested to give which document's title is empty. Thank you

**Comment by slorber** [comment]
Ah I see, so you had something like `title: ` right?
What was your motivation to have an empty title like that?

**Comment by ywjr** [comment]
yes  ，like  title：    ，    when   i   write  md  doc file  in  Chinese，   i    think  ​the font size of the title is too large  on  md  doc page ，   but I can't change it， so  i  make  title  empty 。the font size of the title, H1, H2, H3, etc. can be modified by the user?

**Comment by slorber** [comment]
@ywjr let's track the too strict validation of title/description here https://github.com/facebook/docusaurus/issues/4652

**Comment by nam-hle** [comment]
I see two our assignees can't arrange enough time to work. Can I take some job here? 😁

**Comment by ywjr** [comment]
Yeah, I'm looking forward to your help,





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "facebook/docusaurus"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月6日(星期四) 晚上8:15
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [facebook/docusaurus] Strict frontmatter validation (#4591)





 
I see two our assignees can't arrange enough time to work. Can I take some job here? 😁

**Comment by slorber** [comment]
please go ahead @nam-hle , as others didn't make any progress
