### ISSUE TITLE
upgrade breaks redoc from 2.0.0-rc.48 to 2.0.0-rc.51

### ISSUE THREAD

**Issue by beatrizoliveiira** [facebook/docusaurus#4592]
My site with docusaurus version 2.0.0-alpha.72 breaks with this update:

Failed to compile
```
/home/beatriz/projects/feedback/feedback-front/node_modules/@redocly/openapi-core/lib/resolve.js
Module not found: Can't resolve 'fs' in '/home/beatriz/projects/feedback/feedback-front/node_modules/@redocly/openapi-core/lib'
```

**Comment by slorber** [comment]
Please report issues properly, include all relevant details, and provide a sandbox repro.

We can't do anything with your issue description, as the problem can be anything. Maintainers will only invest time to help you if you invest time in describing your problem correctly in the first place.

**Comment by sibelius** [comment]
redoc needs fs node module not availabe on web, so we can fallback fs using a custom wepback

```jsx
// eslint-disable-next-line
module.exports = function (context, options) {
  return {
    name: 'custom-docusaurus-plugin',
    // eslint-disable-next-line
    configureWebpack(config, isServer, utils) {
      return {
        node: {
          fs: 'empty',
        },
        // webpack 5
        // resolve: {
        //   alias: {
        //     path: require.resolve('path-browserify'),
        //   },
        //   fallback: {
        //     fs: false,
        //     http: require.resolve('stream-http'),
        //     https: require.resolve('https-browserify'),
        //   },
        // },
      };
    },
  };
};
```

**Comment by slorber** [comment]
I see

You can use configureWebpack on the config itself as a shortcut

**Comment by sibelius** [comment]
is there an example somewhere?

**Comment by slorber** [comment]
Oh, can't find it in the doc 😅 maybe I just dreamed of this, will have to
double-check.
