### ISSUE TITLE
Fix Header base path 

### ISSUE THREAD

**Issue by giansalex** [facebook/Docusaurus#460]
I have a project `/project-name/en` but when i click on 'project header name' result in 404 Not found, because the link is  `/project-name/`.
Can i change this path or remove `en`  prefix.

**Comment by JoelMarcey** [comment]
Hi @giansalex Can you point me to your site or the code for your site? Are you using translations?
 Generally the front page of your site, with the default language, should not have the language associated with it.

**Comment by giansalex** [comment]
I built Docusaurus docs:
![docusaurus](https://user-images.githubusercontent.com/14926587/36753098-2940b1d4-1bd3-11e8-9289-7711aa8e8693.png)
but my project result don't have the pages in root directory, I used `publish-gh-pages`
https://github.com/giansalex/sunat-docs/tree/gh-pages

**Comment by JoelMarcey** [comment]
@giansalex Oh - I think I see what might be going on. In your [`siteConfig.js`](https://github.com/giansalex/sunat-docs/blob/master/website/siteConfig.js#L21) you have as the `url` as 

```
url: 'https://giansalex.github.io/sunat-docs' /* your website url */,
```

The `url` in this case should just be `https://gainsalex.github.io` - the top level.

I can see how that may be a confusing name for non-custom GitHub pages domains.

Let me know if that fixes the problem. If so, we will need to think about documenting that option better or providing a synonym option that might be better named.

**Comment by giansalex** [comment]
@JoelMarcey i made that [change](https://github.com/giansalex/sunat-docs/commit/ac91cc6826b2abbdf23f7afaf3d75d8b0dab5a5e), but i can't see the page in 

expected https://giansalex.github.io/sunat-docs/
current https://giansalex.github.io/sunat-docs/en/

I'll need to copy the pages from `en` directory to root directory (gh-pages branch).

**Comment by giansalex** [comment]
I had to copy the files from `/en/` to root site.

**Comment by JoelMarcey** [comment]
@giansalex You had to do that manually? You shouldn't have to do anything like that manually to get a site running by default. I suppose if you did some custom work outside the scope of what Docusaurus offers by default, maybe. But it you just ran `docusaurus-init` and tried to run the site out of the box, y you shouldn't have to move anything.

**Comment by giansalex** [comment]
`Docusaurus build`  don't copy files in root site,

![image](https://user-images.githubusercontent.com/14926587/38280943-af6bc734-376d-11e8-84d4-2ad5644d7905.png)

**Comment by JoelMarcey** [comment]
Oh - you are on Windows! We had a problem with this very issue on Windows that we fixed in a later version of Docusaurus. What version are you using now?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by giansalex** [comment]
Hello @JoelMarcey , i have docusaurus@1.0.1, it's the latest in npmjs, but in github release i see v1.0.9

**Comment by giansalex** [comment]
yes, i had in `package.json` v1.0.6, i update to 1.0.9 and it works
Thanks
