### ISSUE TITLE
JSON syntax error in the new Korean translation introduced at 2.0.0.alpha72

### ISSUE THREAD

**Issue by achimnol** [facebook/docusaurus#4605]
## 🐛 Bug Report

The default Korean translation added in 2.0 alpha72 has a JSON syntax error preventing successful builds.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes.

## To Reproduce

If possible, use https://new.docusaurus.io to create a CodeSandbox reproducible demo of the bug.

1. Just edit my package.json to use alpha72, upgraded from alpha71, with an website with i18n enabled, using Korean and English.
2. Run `yarn install` and `yarn upgrade`
3. Run `yarn start` or `yarn build`

## Expected behavior

The site should be built fine.

## Actual Behavior

```
SyntaxError: Unexpected token } in JSON at position 2841
    at JSON.parse (<anonymous>)
    at readDefaultCodeTranslationMessages (/Users/joongi/workspace/lablup-blog/node_modules/@docusaurus/utils/lib/index.js:495:25)
    at async Promise.all (index 3)
    at async Object.getPluginsDefaultCodeTranslationMessages (/Users/joongi/workspace/lablup-blog/node_modules/@docusaurus/core/lib/server/translations/translations.js:189:29)
    at async Object.load (/Users/joongi/workspace/lablup-blog/node_modules/@docusaurus/core/lib/server/index.js:189:76)
    at async start (/Users/joongi/workspace/lablup-blog/node_modules/@docusaurus/core/lib/commands/start.js:45:19)
error Command failed with exit code 1.
```

Adding `console.log(filePath)` in the line above `@docusaurus/utils/lib/index.js:495` reveals that
`@docusaurus/theme-classic/codeTranslations/ko.json` has the syntax error.
Opening the file with Vim shows an extraneous comma causing the syntax error:
![image](https://user-images.githubusercontent.com/555156/114506337-9bd8a680-9c6c-11eb-93ef-d041e6b47812.png)

Could I just send a simple PR to fix it?

## Your Environment

- Public source code: sorry, it's not available for public
- Public site url: https://blog.lablup.com
- Docusaurus version used: 2.0.0.alpha72
- Environment name and version (e.g. Chrome 78.0.3904.108, Node.js 10.17.0): Node.js 15.11.0
- Operating system and version (desktop or mobile): macOS

**Comment by achimnol** [comment]
I'm just wondering why this error did not happen during the reviews of #4390.
Is there some configuration that allows ignoring trailing commas in JSON?
Since I'm not a daily nodejs developer, there might be something I have missed.

**Comment by achimnol** [comment]
Okay, I found that [it's fixed in the master](https://github.com/facebook/docusaurus/commits/master/packages/docusaurus-theme-classic/codeTranslations/ko.json) after trying to fix it by forking.
Looking forward to the next alpha release.

**Comment by slorber** [comment]
yes it's fixed and added tests to make sure it does not happen again ;)

will release it soon
