### ISSUE TITLE
Pa11y fixes to Docusuarus

### ISSUE THREAD

**Issue by JoelMarcey** [facebook/Docusaurus#462]
### Is this a bug report?

Not technically, but would be good to fix.

### Have you read the [Contributing Guidelines](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md)?

Yes

### Environment

N/A

### Steps to Reproduce

1. npm install -g pa11y
2. pa11y https://docusaurus.io
3.

### Expected Behavior

No errors

### Actual Behavior

A bunch of errors 😄 

https://gist.github.com/JoelMarcey/d08263d2acf1819e07538f0a0c5ded93

### Reproducible Demo

N/A

**Comment by haraldur12** [comment]
I am working on it. How shall I be committing to it though ? Do I have to tackle all the errors first and then send the pull request or just send a pull request every time I have checked something ?

**Comment by JoelMarcey** [comment]
@haraldur12 Hi. We would be happy for you to work on this. As @Happy-Ferret said, you can send one big PR, with multiple commits. Or, maybe preferably, just send multiple PRs -- I tend to like smaller PRs since they are easier to deal with, review, and revert if necessary.

I am going to consider this issue claimed by you. If you do not want to do this any longer, let me know. Thanks.

**Comment by yangshun** [comment]
@haraldur12 Are you still working on this issue?

**Comment by amyrlam** [comment]
So, I started fixing some a couple of the `Error: Img element missing an alt attribute. Use the alt attribute to specify a short text alternative.` ones in WIP PR https://github.com/facebook/Docusaurus/pull/528. 

Then I was wondering if it would be good to add https://github.com/evcohen/eslint-plugin-jsx-a11y to keep it a11y compliant long term. 

There are definitely a lot of things to fix if you want to work on it together @haraldur12!

**Comment by yangshun** [comment]
@haraldur12 , @amyrlam will be working on fixing the rest of the a11y fixes. If you like to work on some of them, please comment here or we will assume that you are ok with us taking over.

**Comment by amyrlam** [comment]
> Iframe element requires a non-empty title attribute that identifies the frame. (WCAG2AA.Principle2.Guideline2_4.2_4_1.H64.1) 

Updated as WONTFIX. These two `Iframe` errors are from GitHub and Twitter social buttons / plugins. They are third party scripts that the page imports on load, which is why they're not in the Docusaurus codebase. Thanks yangshun for the help in figuring this out! 🙏

**Comment by JoelMarcey** [comment]
I am super excited these are getting fixed. Thanks!

**Comment by yangshun** [comment]
Yes I think this is sufficient. I'll close this task later!

**Comment by yangshun** [comment]
Closed via #529 and #542 . The remaining errors are not suitable to be fixed by external contributors.
