### ISSUE TITLE
Improve markdown infrastructure: global markdown config, new lifecycles...

### ISSUE THREAD

**Issue by slorber** [facebook/docusaurus#4625]
## 🚀 Feature

Problems to solve:
- The markdown config (remark/rehype plugins) is often duplicated between multiple plugins
- There's no central place to configure markdown/MDX for the whole site at once
- It's not possible to build markdown-enhancement Docusaurus plugins
- It's not possible to disable the default emoji plugin (https://github.com/facebook/docusaurus/discussions/5450)

We should allow users to configure default markdown config globally, change Docusaurus Markdown defaults, and make it possible to create markdown-related Docusaurus plugins.

A good example would be to create a "docusaurus-plugin-latex" so that scientists can more easily adopt Docusaurus without having to go through more complicated steps (see https://docs.theochu.com/docusaurus/latex/)

Related to https://github.com/facebook/docusaurus/issues/3018

**Comment by nilsocket** [comment]
I write notes of whatever I study in markdown files organized into folders.

I use [vscode-markdown-preview-enhanced](https://github.com/shd101wyy/vscode-markdown-preview-enhanced), which works perfectly for all my use-cases.

I need my content to be accessible, on other devices like mobile, for revision purposes.

I was thinking to host a local server which serves `.md` files.

As I'm not familiar with front-end development, it's confusing to configure and I don't understand much.

But the link which you have provided is fine for me. I will configure it.
Thanks a lot.

**Comment by Josh-Cena** [comment]
Going to close this in favor of #5568, #3018 and #6370. Those are smaller and more concrete proposals that seem more actionable.
