### ISSUE TITLE
Allow MDX imports to be above h1 heading

### ISSUE THREAD

**Issue by duanwilliam** [facebook/docusaurus#4635]
## 🚀 Feature

With the current frontmatter-less parsing, the h1 heading must be at the top of the file, excluding frontmatter, for it to be used as the title rather than the filename. It'd be useful if import nodes could be placed above the heading without compromising the h1 heading's function as the title.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

yes

## Motivation

It's just a quality of life feature that in my opinion would be useful

## Pitch

ES6 JS imports are always placed at the top of the file, and this should be permitted for the markdown files as well without unintended side effects. Keeping the imports at the top of the file, separate from all the other content (including the h1 heading title) also helps decouple the actual "page content" of the file and the "metadata" associated with it (frontmatter, imports, etc)

**Comment by slorber** [comment]
agree, using imports at the top of the file should be supported
