### ISSUE TITLE
Metadata not parsed for autogenerated categories when dirname is subdirectory

### ISSUE THREAD

**Issue by duanwilliam** [facebook/docusaurus#4638]
## 🐛 Bug Report

Using a `type: autogenerated` with dirName not `.` results in category metadata not being parsed.

The bug does _not_ appear when no sidebar file is specified, nor when `dirName` is set to `.`

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

yes

## To Reproduce

https://codesandbox.io/s/keen-wozniak-cpdp0?file=/docs/tutorial/extras/_category_.yml

1. Create a new Docusaurus site / CodeSandbox demo
2. Add a subfolder to the `docs` directory
3. add some categories to the subfolder
4. add metadata to `_category_.yml` (json didn't work either)
5. modify `sidebars.js` to contain a sidebar with the item `{type: 'autogenerated', dirName: '[subfolder name]'}`

## Expected behavior

Sidebar categories have their metadata parsed

## Actual Behavior

Category metadata isn't parsed.

https://codesandbox.io/s/keen-wozniak-cpdp0?file=/docs/tutorial/extras/_category_.yml

Expected:
![image](https://user-images.githubusercontent.com/38791932/115097499-78696200-9edf-11eb-85ae-303e19ed5976.png)

Actual:
![image](https://user-images.githubusercontent.com/38791932/115097605-0ba29780-9ee0-11eb-9a07-a4cd13313723.png)

## Your Environment

- CodeSandbox demo: https://codesandbox.io/s/keen-wozniak-cpdp0?file=/docs/tutorial/extras/_category_.yml
- Docusaurus version used: 2.0.0-alpha.73
## Reproducible Demo

https://codesandbox.io/s/keen-wozniak-cpdp0?file=/docs/tutorial/extras/_category_.yml

steps made to create:

```bash
mkdir docs/tutorial
mv -r docs/tutorial-basics docs/tutorial/basics
mv -r docs/tutorial-extras docs/tutorial/extras
```

- renamed `_category_.json` in `docs/tutorial/extras` to `_category_.yml` and updated to yaml syntax; sidebar position also changed, so it _should_ be above `basics`.
- in `sidebars.js`, changed `dirName` from `.` to `tutorial`
- link in `src/pages/index.js:19` changed to `/docs/tutorial/basics/create-a-page` for ease of access.

**Comment by geekodour** [comment]
Just tried this locally, it seems the `position` is also not taken up it seems so that leaves the ordering of items in the sidebar to be manually arranged by updating filenames.

**Comment by slorber** [comment]
Hey, I think there's a misconception on how this feature is supposed to work.

When you use `dirName: "tutorials"`, it won't read the category metadata file at all not create a category for the tutorials folder

It will just read the docs of that subfolder and also the sub-subfolders. If you want a category, you have to add it explicitly to the sidebar.

The reason for this is that this allows to create a single category that can source multiple autogenerated directories, and generate a flat list of sidebar items.

Here is the init template where we want a 100% flat structure. It will work and no category at all will be created (on purpose):

```js
module.exports = {
  tutorialSidebar: [
    "intro",
    { type: "autogenerated", dirName: "tutorial-basics" },
    { type: "autogenerated", dirName: "tutorial-extras" },
  ],
};
```


Now what you are looking for is probably something like this:

```js
module.exports = {
  tutorialSidebar: [
    "intro",
    {
      type: "category",
      label: "Tutorial - Basics",
      items: [{ type: "autogenerated", dirName: "tutorial-basics" }],
    },
    {
      type: "category",
      label: "Tutorial - Extras",
      items: [{ type: "autogenerated", dirName: "tutorial-extras" }],
    },
  ],
};
```

You can also mix and match so that basic tutorials are flat and extra tutorials are nested:

https://codesandbox.io/s/elated-heisenberg-6tu9g?file=/sidebars.js:0-261

```js
module.exports = {
  tutorialSidebar: [
    "intro",
    { type: "autogenerated", dirName: "tutorial-basics" },
    {
      type: "category",
      label: "Tutorial - Extras",
      items: [{ type: "autogenerated", dirName: "tutorial-extras" }],
    },
  ],
}; 
```

---

I think it's powerful to be able to source multiple distinct folders and "concat" the docs of those folders under a single list.

Does it make sense?

How can we document this better?

Should we create an option so that a category is created for the target auto-gen dir by default?

**Comment by duanwilliam** [comment]
I think the issue's more of that the autogenerated sidebar items _do_ recognize and create subcategories, except these _subcategories_ do not have metadata recognized unless `dirName='.'`. 

i.e. if I have a docs directory structure of 
```
docs
└── tutorials
    ├── basics
    │   ├── _category_.yml
    │   └── index.md
    └── extras
        ├── _category_.yml
        └── index.md
```
where the category metadata defines
```yml
# basics/_category_.yml
label: 'Tutorial - Basics'
position: 2

# extras_category.yml
label: 'Tutorial - Extras'
position: 1
```
, an autogenerated sidebar item with `dirName: '.'` gives a sidebar with the structure
```
tutorials
├── Tutorial - Extras
│   └── index.md
└── Tutorial - Basics
    └── index.md
```
If I don't want a wrapper `tutorials` category in my sidebar, I would expect `dirName: 'tutorials'` to yield a sidebar with the structure
```
Tutorial - Extras
└── index.md
Tutorial - Basics
└── index.md
```
whereas currently it yields
```
basics
└── index.md
extras
└── index.md
```

**Comment by slorber** [comment]
@duanwilliam  agree, something does not work as intended and Docusaurus fails to read the metadatas of subcategories of the autogenerated source dir. Will fix this.

**Comment by geekodour** [comment]
Thanks @slorber ! is it possible to use this directly from `master` now? sorry my npm foo is a bit weak :(

**Comment by slorber** [comment]
@geekodour you can use the canary release to get the code from master before we release it:

https://www.npmjs.com/package/@docusaurus/core

![image](https://user-images.githubusercontent.com/749374/116125196-7a90a500-a6c5-11eb-921f-e8b59b87c510.png)

**Comment by slorber** [comment]
released in alpha 74
