### ISSUE TITLE
How to add social media button in Docu v2.0? 

### ISSUE THREAD

**Issue by ajeetraina** [facebook/docusaurus#4639]
Any idea how to add social media button in Docusaurus v2. 0?

**Comment by slorber** [comment]
swizzle the theme components and change what you need to change

**Comment by ajeetraina** [comment]
Can you elaborate @slorber ??

**Comment by slorber** [comment]
@ajeetraina it is documented, have you read the doc?

**Comment by slorber** [comment]
Also, this is not an issue, please use discussions or Discord for questions
