### ISSUE TITLE
Markdown Footnotes Not Properly Numbered

### ISSUE THREAD

**Issue by ben-qnimble** [facebook/docusaurus#4647]
## 🐛 Bug Report

I can't find documentation on the Docusaurus website, but according to https://www.markdownguide.org/tools/docusaurus/, Docusaurus uses the [Remarkable](https://github.com/jonschlinkert/remarkable) markdown processor. And that processor supports footnotes, as shown in their [manual](https://pandoc.org/MANUAL.html#footnotes) and also in the  [The Markdown Guide](https://www.markdownguide.org/extended-syntax/#footnotes)

Both guides have an example for using footnotes: 

```
Here's a simple footnote,[^1] and here's a longer one.[^bignote]

[^1]: This is the first footnote.

[^bignote]: Here's one with multiple paragraphs and code.

    Indent paragraphs to include them in the footnote.

    `{ my code }`

    Add as many paragraphs as you like.
```

which yield two footnotes, 1 and 2. Where the markdown processor handles the numbering of the footnotes.

However, if you put the same code into Docusaurus, the footnotes section as expected -- labels are 1 and 2 respectively. But the superscript text with the link uses not the foot note number, but the text in between the [ ] when defining the foot note.  I believe the expected behavior would be for the footnote label in the main section and the footnote section to match and both be the footnote number.

As you can see in the image below, the link to the second footnote has the text 'bignote' instead of '2' even though it links to the footnote that is labelled '2'.

![image](https://user-images.githubusercontent.com/57039667/115317424-84585c80-a149-11eb-99b5-540f0bed7e1e.png)
shows the issue.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## To Reproduce

Create markdown page with
```
Here's a simple footnote,[^1] and here's a longer one.[^bignote]

[^1]: This is the first footnote.

[^bignote]: Here's one with multiple paragraphs and code.

    Indent paragraphs to include them in the footnote.

    `{ my code }`

    Add as many paragraphs as you like.
```

## Expected behavior

Second footnote in superscript should be labelled '2' and not 'bignote'

## Actual Behavior

See above.

## Your Environment

Clean fresh docusaurus checkout with alpha73

**Comment by slorber** [comment]
Hi,

We use MDX, and you can test your md syntax in the MDX playground here: https://mdxjs.com/playground/

![image](https://user-images.githubusercontent.com/749374/115403164-76a7e300-a1ec-11eb-8253-ce7e5217dabb.png)


It seems that this behavior is from MDX, so I believe you should report it here if it is for you the wrong behavior to have.

You can also track this issue in case you'd like to use a non-MDX parser once we support alternative parsers: https://github.com/facebook/docusaurus/issues/3018
