### ISSUE TITLE
Document Typescript Monorepo Usecase

### ISSUE THREAD

**Issue by dustinlacewell** [facebook/docusaurus#4648]
Monorepos are in vogue. So is TypeScript. It's going to be a common usecase to want to utilize components from a typescript component library in the same monorepo.

Please document this use-case. Currently, doing the steps at https://docusaurus.io/docs/typescript-support and utilizing https://github.com/atomicpages/docusaurus-plugin-module-alias and https://github.com/tleunen/babel-plugin-module-resolver is not currently enough to utilize such components in your Docusaurus pages.

**Comment by slorber** [comment]
Why isn't it good enough, what were the concrete problems that you faced? Do you have a repro?

Monorepos and TypeScript are both large subjects, it's unlikely we'll be able to document everything about those 2 topics but there might be some low-hanging fruits to document indeed.

**Comment by dustinlacewell** [comment]
In the journey to create a reproducable case I found that I was able to get it all working.

For anyone finding this issue in the future:

- `docusaurus-plugin-module-alias` is enough to get Docusaurus to compile from your monorepo libraries
- If your Typescript is sufficiently modern, you may need to add various babel plugins like `@babel/plugin-proposal-class-properties` but `@babel/plugin-module-resolver` should be unnecessary.
- You'll want to setup path aliases in your Docusaurus tsconfig.json so that your editor doesn't mind when you try to import your monorepo libraries.

**Comment by slorber** [comment]
Thanks. Don't hesitate to submit a doc PR if you think you can add anything useful
