### ISSUE TITLE
[proposed enhancement] Algolia - Allow appId in algolia configuration

### ISSUE THREAD

**Issue by atroncy** [facebook/Docusaurus#465]
### Is this a bug report?

No

### Have you read the [Contributing Guidelines](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md)?

Yes

### Environment

any env

### Steps to Reproduce

(Write your steps here:)

1. Add appId into algolia configuration inside siteConfig.js
2. appId is ignored during the creation of the docsearch client in lib/core/Site.js

### Expected Behavior

I should be able to add my own APP_ID.
According to [docsearch-scraper](https://github.com/algolia/docsearch-scraper#specify-appid), if you use your own scraper, you should specify to docsearch your APP_ID.
You may want to use your own scraper if you don't want to expose your site to the internet.

### Actual Behavior

It's not possible to add your own AppId.
It's take the default one being BH4D9OD16A.

**Comment by JoelMarcey** [comment]
Hi @atroncy. I do not think that should be too difficult to add. Should just be an `if` check into siteConfig.js to add to Algolia config.

**Comment by juanpicado** [comment]
Would it be something like this? or you were thinking about a different approach?

```
{this.props.config.algolia &&
            (this.props.config.algolia.algoliaOptions ? (
              <script
                dangerouslySetInnerHTML={{
                  __html: `
              var search = docsearch({
                ${this.props.config.algolia.appId ? `appId: ${this.props.config.algolia.appId}` : ''}
                apiKey: '${this.props.config.algolia.apiKey}',
                indexName: '${this.props.config.algolia.indexName}',
                inputSelector: '#search_input_react',
                algoliaOptions: ${JSON.stringify(
                  this.props.config.algolia.algoliaOptions
                )
                  .replace('VERSION', docsVersion)
                  .replace('LANGUAGE', this.props.language)}
              });
            `,
                }}
              />
            ) : (
              <script
                dangerouslySetInnerHTML={{
                  __html: `
              var search = docsearch({
                ${this.props.config.algolia.appId ? `appId: ${this.props.config.algolia.appId}` : ''}
                apiKey: '${this.props.config.algolia.apiKey}',
                indexName: '${this.props.config.algolia.indexName}',
                inputSelector: '#search_input_react'
              });
            `,
                }}
              />
            ))}
```

**Comment by atroncy** [comment]
hey thx for the answer
I just issued a new pr for this issue.
It's similar to your solution @juanpicado (with some quote around the props followed by a comma :) )

**Comment by juanpicado** [comment]
It looks good to me, I hope it get merged soon 💯

**Comment by JoelMarcey** [comment]
Closed by https://github.com/facebook/Docusaurus/pull/481 😄
