### ISSUE TITLE
Floating Image breaks code copy button

### ISSUE THREAD

**Issue by F43nd1r** [facebook/docusaurus#4656]
## 🐛 Bug Report

Floating Images will break the position of the code copy button, as seen here:
![Screenshot_20210421_143059](https://user-images.githubusercontent.com/10252708/115554462-c64ee300-a2ae-11eb-9e42-edc73d704a2a.png)
The copy button is positioned above the image, not in the top right corner of the code box.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes.

## To Reproduce

**Sandbox** https://4cicb.sse.codesandbox.io/docs/intro

Use the SideImage component with a code block inside.

```
export default function SideImage({children, src, alt}) {
    return (<div id={styles.container}><img id={styles.float} src={src} alt={alt}/>{children}</div>);
}
```
```
#container {
    width: 100%;
    overflow: hidden;
}
#float {
    float: right;
    width: 35%;
    margin-left: 1em;
}
```

## Expected behavior

Code copy button position should be always in the top right corner of the box, no matter its size.

## Actual Behavior

Code copy button is overlapping a float component on the right, see above.

## Your Environment

- Public source code: https://codesandbox.io/s/exciting-solomon-4cicb
- Public site url:https://4cicb.sse.codesandbox.io/docs/intro
- Docusaurus version used: 2.0.0-alpha.73
- Environment name and version: Firefox 88.0
- Operating system and version (desktop or mobile): desktop

## Reproducible Demo

https://codesandbox.io/s/exciting-solomon-4cicb

**Comment by slorber** [comment]
SideImage is not a Docusaurus component, and we can't provide support for code we didn't write in the first place.

In 2021 I don't think it's advised to use float. Maybe you can achieve the custom layout you want using flex, css grids, calc or something more modern.

We can clearly see on your layout that your "children" overflow over the image, which is the reason why it cause problems.

![image](https://user-images.githubusercontent.com/749374/115566928-fef4b980-a2ba-11eb-8598-604981e46178.png)

**Comment by F43nd1r** [comment]
> In 2021 I don't think it's advised to use float.

Floats are still good for exactly one thing: text (or other things) flowing around an image, which is what I'm trying to achieve here.

> We can clearly see on your layout that your "children" overflow over the image, which is the main cause of your problems.

Thank you. Problem solved by adding 
```
#container > :not(#float) {
    overflow: auto;
}
```
