### ISSUE TITLE
Offline Search Option

### ISSUE THREAD

**Issue by sheldonhull** [facebook/Docusaurus#466]
### Is this a bug report?
no

## Offline search functionality

Has anyone successfully implemented Lunr.js or another offline based search provider? I'm looking to create a offline static documentation site, and can't grant a web crawler the ability to index. I need to leverage something offline like Lunr, solr, or another option, but haven't done that before. Is this a possible enhancement, or anyone successfully done this and willing to share how to do it?

**Comment by JoelMarcey** [comment]
Hi @sheldonhull. I have not added an offline search provider. But I imagine you could follow https://lunrjs.com/guides/getting_started.html and do some stuff in siteConfig.js to add it. And then maybe mimic how we add Algolia to the header links bar for Lunr?

**Comment by sheldonhull** [comment]
Thanks! I ended up sticking with Mkdocs as I had an easier time using what was already built in. Just was a better fit for what I already knew how to use. You guys have a great project though, thanks for the hard work!

**Comment by wulucxy** [comment]
@sheldonhull do you have solved this problem? my website is only for company-internal network，so the recommend `Algolia DocSearch` is not suitable for me。

**Comment by njsokol** [comment]
This would be an awesome feature

**Comment by bram209** [comment]
I would love this feature as well

**Comment by danerich** [comment]
This would be a great addition!

**Comment by prudhvireddy123** [comment]
+1

**Comment by JoelMarcey** [comment]
@KerimG I wouldn't say never. It is on on our [v2 roadmap](https://github.com/facebook/Docusaurus/issues/789).

**Comment by prakhar-goel** [comment]
+1 for offline search using lunrjs or similar. We are using Docusaurus for internal company documentation and therefore cannot use default Algolia search. Ability to search through markdown files would be a great add on to the current version.

**Comment by ishanmihir19** [comment]
+1

**Comment by prudhvireddy123** [comment]
I have implemented, search with Elastic lunar and node js for one of our internal sites. I will share the code tonight. That may be helping.

**Comment by JoelMarcey** [comment]
Just as an FYI - @sbansal3096 is working on this as part of https://github.com/facebook/docusaurus/issues/776.

This is actually a duplicate issue.

Please follow #776 for updates.

**Comment by joetidee** [comment]
Algolia search system is a deal-breaker for us.

**Comment by lelouch77** [comment]
I create a offline search component using lunr.. Check it out ..
https://github.com/lelouch77/docusurus-lunr-search

**Comment by kamdjouduplex** [comment]
@lelouch77 thank you very much for this plugin, I succeed integrating it on my docusaurus v2 project in a minute.
good job!

**Comment by joan38** [comment]
Not working for me, I get a:
```
Error: Cannot find module 'docusaurus-lunr-search'
```

**Comment by GustavoAngulo** [comment]
@joan38 Did you find a fix for the `Cannot find module` error? CC: @lelouch77

**Comment by praveenn-vbi** [comment]
@joan38 @GustavoAngulo Seems there some issues including node module in plugin with new version of docusaurus, just change your `docusaurus.config.js` as follow.
const path = require('path');
module.exports = {
  // ...
    plugins: [path.resolve(__dirname, './node_modules/docusaurus-lunr-search/')],
}

**Comment by lelouch77** [comment]
@joan38 @GustavoAngulo Seems there some issues including node module in plugin with new version of docusaurus, just change your `docusaurus.config.js` as follow.
```
const path = require('path');
module.exports = {
  // ...
    plugins: [path.resolve(__dirname, './node_modules/docusaurus-lunr-search/')],
}
```
