### ISSUE TITLE
Title not showing correctly for blogs

### ISSUE THREAD

**Issue by yechs** [facebook/docusaurus#4666]
## 🐛 Bug Report

Title for blog page and each blog post are not shown.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

yes

## To Reproduce

Visit the official blog at https://docusaurus.io/blog and open any post (e.g. https://docusaurus.io/blog/2021/03/09/releasing-docusaurus-i18n).

In both cases, the titles are only shown as `Docusaurus`

## Expected behavior

I'm assuming that the title should be `Blog | Docusaurus` and `Releasing Docusaurus i18n | Docusaurus`. 
There is an [archived version](https://web.archive.org/web/20210403024156/https://docusaurus.io/blog/2021/03/09/releasing-docusaurus-i18n) of the blog post that shows the title correctly.

## Actual Behavior

In both cases, the titles are only shown as `Docusaurus`

## Your Environment

- Public source code: <the official docs>
- Public site url: https://docusaurus.io/blog
- Docusaurus version used: 2.0.0-alpha.73
- Environment name and version (e.g. Chrome 78.0.3904.108, Node.js 10.17.0): Chrome 89; Node v14.16.1
- Operating system and version (desktop or mobile): both desktop and mobile

## Reproducible Demo

Go to https://new.docusaurus.io and visit the blogs, the bug exists even under default settings.

**Comment by yechs** [comment]
This may be linked to #4665 but seems to exhibit a different scope of effect.

**Comment by slorber** [comment]
Not related, PR to fix will be here: https://github.com/facebook/docusaurus/pull/4667
