### ISSUE TITLE
Content type of the sitemap.xml is missing

### ISSUE THREAD

**Issue by lipis** [facebook/Docusaurus#467]
Should be: `application/xml`

https://stackoverflow.com/a/3272572/8418

**Comment by Glavin001** [comment]
@s-pace from Algolia also reported `sitemap.xml` is not compliant with https://www.sitemaps.org/protocol.html

See https://github.com/algolia/docsearch-configs/pull/312#issuecomment-364871456

**Comment by yangshun** [comment]
@rizafahmi It's yours!

I've added an "issue-claimed" label so that others will know not to start work on the issue. If you change your mind about the issue, no worries! Just let me know so that I can remove the label and free it up for someone else to claim.

I'll check in with you periodically so that we can keep the task updated with the progress.

**Comment by rizafahmi** [comment]
Thanks @yangshun !

**Comment by rizafahmi** [comment]
Hi @lipis can you please confirm that the content-type is not `application/xml`?

I tried it with curl & httpie, it's already `application/xml`.

```sh
http http://localhost:3000/sitemap.xml -h
HTTP/1.1 200 OK
Connection: keep-alive
Content-Length: 3060
Content-Type: application/xml; charset=utf-8
Date: Sun, 15 Apr 2018 14:48:38 GMT
ETag: W/"bf4-xyO2OFprLzDPuBKeUuyaw33D+Fk"
X-Powered-By: Express
```

**Comment by lipis** [comment]
![screen shot 2018-04-15 at 19 04 18](https://user-images.githubusercontent.com/125676/38781041-da071856-40df-11e8-8374-4164db6e4ff2.png)

Type: Document

And it renders it wrong in the browser..

Compare the two in the browser:

- https://docusaurus.io/sitemap.xml
- https://www.google.com/sitemap.xml

**Comment by JoelMarcey** [comment]
So we use a third party npm library for the sitemap. https://github.com/ekalinin/sitemap.js (or https://www.npmjs.com/package/sitemap).

https://github.com/facebook/Docusaurus/blob/master/lib/server/sitemap.js#L96 is where we set it. Maybe we are missing some options?

I do notice we are doing `<url><loc>...` if you view the source  (view-source:https://docusaurus.io/sitemap.xml)

instead of

`<sitemap><loc>...`

as in https://www.google.com/sitemap.xml

**Comment by s-pace** [comment]
👋 @JoelMarcey ,

Thanks for the details.

One of the main point is to be compliant with [the official standard](https://www.sitemaps.org/protocol.html). Definitely possible with [the npm package](https://www.npmjs.com/package/sitemap).

Happy to help if needed.

Cheers

**Comment by rizafahmi** [comment]
@lipis both docusaurus and google was document on my side.
<img width="820" alt="screen shot 2018-04-16 at 6 12 27 pm" src="https://user-images.githubusercontent.com/1147918/38805947-e8dec87a-41a1-11e8-90f3-00183a19c667.png">
<img width="895" alt="screen shot 2018-04-16 at 6 12 33 pm" src="https://user-images.githubusercontent.com/1147918/38805954-eb6bd0d8-41a1-11e8-9abf-6103d4927764.png">


But you're right about wrong rendering part. I'll check it out.

**Comment by lipis** [comment]
@rizafahmi My bad.. check the Response Headers the `content-type` is missing

<img width="448" alt="screen shot 2018-04-16 at 13 21 58" src="https://user-images.githubusercontent.com/125676/38806363-4900af26-4179-11e8-801a-72438338a073.png">

**Comment by rizafahmi** [comment]
ah. i see. Thanks for the clarification @lipis

**Comment by rizafahmi** [comment]
Sorry @lipis to bother you again. There is actually `content-type` on the response headers.

<img width="1190" alt="screen shot 2018-04-17 at 10 50 20 am" src="https://user-images.githubusercontent.com/1147918/38847823-cc93c3f0-422d-11e8-9036-97b012b5d455.png">

I did validate the sitemap over https://validator.w3.org and https://www.xml-sitemaps.com/validate-xml-sitemap.html and all says valid.
Tried to look up the code as well, seems nothing wrong with the code. To be precise, I don't know if there something wrong with the code.
I also tried to use sitemap package with plain express app and it's produce the same thing.

**Comment by JoelMarcey** [comment]
@s-pace Thanks for chiming in here. Hope all is well. Given what @rizafahmi says in the comment just above, do you think we what we have is already good and we do not need to make any changes?

**Comment by JoelMarcey** [comment]
@s-pace This is the link that is being debated whether is wrong or correct? https://docusaurus.io/sitemap.xml

This is a link that is assumed correct - https://www.google.com/sitemap.xml

**Comment by s-pace** [comment]
@JoelMarcey 

Works 💯. I have made an example:

- Copy the following CSS/JS snippets and add them to your page

```html
<!-- at the end of the HEAD -->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/docsearch.js@2/dist/cdn/docsearch.min.css" />

<!-- at the end of the BODY -->
<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/docsearch.js@2/dist/cdn/docsearch.min.js"></script>
<script type="text/javascript"> docsearch({
  apiKey: '46899d51aa254ffb4fd068f3ae64ed40',
  indexName: 'docusaurus_demo',
  inputSelector: '### REPLACE ME ####',
  algoliaOptions: { 'facetFilters': ["lang:$LANG", "version:$VERSION", "tags:$TAGS"] },
  debug: false // Set debug to true if you want to inspect the dropdown
});
</script>
```

- Add a search input in your page if you don't have any yet. Then update the inputSelector value in JS snippet to a CSS selector that targets your search input field.

- Replace `$LANG` with the lang you want to search on.
   The list of possible lang is hardcoded in the config.
   So as of today you have: `en`

- Replace `$VERSION` with the version you want to search on.
   The list of possible version is hardcoded in the config.
   So as of today you have: `latest`, `next`

- Replace $TAGS with the tags you want to search on.
   The list of possible tags is hardcoded in the config.
   So as of today you have: `blog`

  For example if you want to refine the search to the lang "en" and the version "latest" and the tags "blog" just specify:
```js
'facetFilters': ["lang:en", "version:latest", "tags:blog"]
```

- Optionally customize the look and feel by following [the DocSearch documentation](https://community.algolia.com/docsearch/documentation/)
- You can also check your configuration [in our github repo](https://github.com/algolia/docsearch-configs/blob/master/configs/docusaurus_demo.json).

Please open a pull request if want to leverage your configuration!

Feel free to get back to us if you have any issues or questions regarding the integration.

We'd also be happy to get your feedback and thoughts about DocSearch - so we can continue to improve it.

Have a nice day :)

**Comment by JoelMarcey** [comment]
@s-pace Thank you! 👍 I commented on the docsearch commit you made that I think you changed the wrong config file. Let me know if that was the case. If so, we can fix that 😄 

In the case of Docusaurus, we probably only need to add the `algoliaOptions` field since we already have the search box, etc. Does that seem right?

**Comment by s-pace** [comment]
@JoelMarcey 

Exactly! I use this index in order to show you how it would looks like. Let me know if I can merge it to the original one.

**Comment by JoelMarcey** [comment]
Thanks @s-pace - I commented on the config changes over at https://github.com/algolia/docsearch-configs/commit/db60b72c31f58a08b6ad07ce8277d7d363baf161 with a couple of questions. Assuming those are good, then I think we can merge it.

**Comment by endiliey** [comment]
Our sitemap is actually correct.
<img width="958" alt="sitemap" src="https://user-images.githubusercontent.com/17883920/40932617-85eab832-6861-11e8-8a18-a205c61fe74d.PNG">

The XML Viewer in chrome is wrong when we include alternate languages page on the sitemap.
Refer to https://github.com/ekalinin/sitemap.js/issues/37

I tried https://www.w3schools.com/xml/xml_validator.asp & it's actually valid.

**Comment by storemey01** [comment]
Hello i am facing same issue for xml. please check below link and help me to solve it

https://www.xml-sitemaps.com/validate-xml-sitemap.html?op=validate-xml-sitemap&go=1&sitemapurl=https%3A%2F%2Fwww.storemey.com%2Fsitemap_search.xml&submit=Validate+Sitemap
