### ISSUE TITLE
Dropdown Icon isn't centered anymore

### ISSUE THREAD

**Issue by bennodev19** [facebook/docusaurus#4671]
### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?
Yes

## To Reproduce

Create a Navbar dropdown in the docusaurus config.
https://docusaurus.io/docs/api/themes/configuration#navbar-dropdown

## Expected behavior

![grafik](https://user-images.githubusercontent.com/57860196/115761511-b284a900-a3a2-11eb-87e3-31f244f89d01.png)

## Actual Behavior

![grafik](https://user-images.githubusercontent.com/57860196/115761417-9aad2500-a3a2-11eb-9f17-fea5f30b4596.png)

## Your Environment

- Public source code: https://github.com/agile-ts/documentation
- Public site URL: https://agile-ts.org/
- Docusaurus version used: 2.0.0-alpha.73
- Environment name and version (e.g. Chrome 78.0.3904.108, Node.js 10.17.0): doesn't matter
- Operating system and version (desktop or mobile): doesn''t matter

**Comment by slorber** [comment]
it looks good on your prod website no?

**Comment by bennodev19** [comment]
yeah on the prod website I am still using the `2.0.0-alpha.72` so there you can't notice the issue.
However, after upgrading to the latest version ( `2.0.0-alpha.73`) the icons seem a bit off.
For example on the docusaurus website, the drop-down icons are a bit off too. (In my opinion)
![grafik](https://user-images.githubusercontent.com/57860196/115765973-ae0ebf00-a3a7-11eb-9c91-cb0963e28dbc.png)
