### ISSUE TITLE
Google Analytics is only activated in production - missing from documentation?

### ISSUE THREAD

**Issue by yiliansource** [facebook/docusaurus#4678]
## 📚 Documentation

From what I can see, the [google analytics plugin](https://docusaurus.io/docs/api/plugins/@docusaurus/plugin-google-analytics) that ships with `preset-classic` is only enabled in production mode. Maybe this could be added to the documention? I spent a while wondering why the analytics script wasn't loaded when running `yarn start`.

I definitely feel like this is good and intentional, but should still be hinted to on the plugin's documentation. Unless I'm missing it?

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes.

**Comment by HonkingGoose** [comment]
Does Google Analytics run in a production Docusaurus v2 site by default?

I'd like documentation on how to **opt-out/disable** Google Analytics as well.

**Comment by yiliansource** [comment]
It's only active if you specify a tracking ID I believe. But i could be wrong.

**Comment by slorber** [comment]
Yes I think trackingId is required and it's only enabled in production mode.

Any doc PR is welcome. I guess having an option to enable this in dev could also be useful?

**Comment by yiliansource** [comment]
> I guess having an option to enable this in dev could also be useful?

I'm not sure about that, as that could potentially mess up the resulting data, if you include both data from development and production audiences. I think the current behaviour is definitely correct.

I can try to spin up a PR later, if I have time.
