### ISSUE TITLE
The sidebar does not follow the order in Sidebars.js if some items in Sidebars.js are numbers

### ISSUE THREAD

**Issue by TheodoreChu** [facebook/docusaurus#4679]
## 🐛 Bug Report

The sidebar does not follow the order in `Sidebars.js` if some items in `Sidebars.js` are numbers.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## To Reproduce

1. In `Sidebars.js`, create a sidebar with string and a number as the headers (`Intro` is before `2021`): https://codesandbox.io/s/great-sunset-jztky?file=/sidebars.js:404-445
```js
  tutorialSidebar: {
    Intro: ["intro"],
    2021: ["2021"]
  }
```
2. Notice that the number appears before the string in the sidebar (a screenshot is below): https://jztky.sse.codesandbox.io/docs/intro

## Expected behavior

I expect the Sidebar to follow the order of the items in `Sidebars.js`.

## Actual Behavior

The sidebar does not follow the order in `Sidebars.js` if some items in `Sidebars.js` are numbers.

![image](https://user-images.githubusercontent.com/22967798/115972570-0a86f100-a504-11eb-9eeb-0aae8d5ef475.png)

## Your Environment

- Public source code: https://codesandbox.io/s/great-sunset-jztky?file=/sidebars.js:404-445
- Public site url: https://jztky.sse.codesandbox.io/docs/intro
- Docusaurus version used: `2.0.0-alpha.73`
- Environment name and version (e.g. Chrome 78.0.3904.108, Node.js 10.17.0): Docusaurus (code sandbox)
- Operating system and version (desktop or mobile): Desktop, Windows 10

## Reproducible Demo

- Public source code: https://codesandbox.io/s/great-sunset-jztky?file=/sidebars.js:404-445
- Public site url: https://jztky.sse.codesandbox.io/docs/intro

**Comment by slorber** [comment]
Unfortunately, I think this is std JavaScript:

![image](https://user-images.githubusercontent.com/749374/116126326-cd1e9100-a6c6-11eb-8492-6a57984b632a.png)

Numbers come first when iterating over object keys, as if they were array indices.

You can use a string '2021' instead, or use the array syntax.

I don't there there's any potential solution here, or you'll have to help me ;)

**Comment by TheodoreChu** [comment]
Thanks, @slorber, for taking a look at this.

> You can use a string '2021' as object key instead,

When I put '2021' in quotes, I still have 2021 come before Intro:

```js
  tutorialSidebar: {
    Intro: ["intro"],
    "2021": ["2021"]
  }
```

![image](https://user-images.githubusercontent.com/22967798/116168476-50d08180-a6b7-11eb-97d0-e09a1769656e.png)

Here's the link to the CodeSandox (it's the same as above): https://codesandbox.io/s/great-sunset-jztky?file=/sidebars.js:383-451

> use the array syntax so that you don't rely on object keys ordering.

Why array syntax are you referring to? I'm looking at https://docusaurus.io/docs/sidebar, and I'm not sure which syntax you are referring to 😅

**Comment by slorber** [comment]
You are right, it seems JS will try to coerce strings to numbers somehow 🤪 

It's better to discuss JS snippets directly, as I don't think this is related to Docusaurus, and we can see the problem here directly:

```js
Object.keys({
  Intro: ["intro"],
  "2021": ["2021"],
  "2021abc": ["2021"],
});
```

![image](https://user-images.githubusercontent.com/749374/116207000-b1a39c80-a73f-11eb-93b1-b5389523821c.png)

Doc: https://docusaurus.io/docs/sidebar#sidebar-object

You are using the shorthand syntax to declare categories, but you can use the expanded array syntax too:

```js
module.exports = {
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Intro',
      items: ['doc1'],
    },
    {
      type: 'category',
      label: '2021',
      items: ['2021'],
    },
  ],
};
```
