### ISSUE TITLE
when run "npm run build", index.html file only exists in build/xxx/en/ dir, but not copied to the root dir

### ISSUE THREAD

**Issue by loveky** [facebook/Docusaurus#468]
### Is this a bug report?

Not Sure

### Have you read the [Contributing Guidelines](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md)?

Yes

### Environment

Windows 7
Node 6.9.5
npm 3.10.10

### Steps to Reproduce

(Write your steps here:)

1. Follow the [installation](https://docusaurus.io/docs/en/installation.html) process
2. run `npm run build`
3. check the `build` directory

### Expected Behavior

Want to see my `index.html` file in `build/my-site-name/` directory. This behavior is documented at [HERE](https://github.com/facebook/Docusaurus/blob/master/docs/api-pages.md)

### Actual Behavior

the `index.html` only appears in `build/my-site-name/en` directory

### Reproducible Demo

Pleace check **Steps to Reproduce**

**Comment by JoelMarcey** [comment]
Hi @loveky! Interesting. I followed your process and I see an `index.html` file in the root `build/site` directory. Do you have a repo I can look at to try to reproduce exactly?

**Comment by Happy-Ferret** [comment]
Same issue here.

Repo: https://github.com/Anima-OS/dev-corner

**Comment by Happy-Ferret** [comment]
I just tried doing the same on another machine, using just the default example and can reproduce this behavior.

**Comment by Happy-Ferret** [comment]
I just checked again, this time using WSL (Windows Subsystem for Linux), because I had already suspected it might be due to a Windows specific bug.

Sure enough, there it generates the correct output.

**Comment by Happy-Ferret** [comment]
Curious. I spend some time debugging the issue via VS Code earlier this morning.

Changing 

<pre>writeFileAndCreateFolder(targetFile.replace('<b>/en/</b>', '/'), str);</pre>

on [line 466 in generate.js](https://github.com/facebook/Docusaurus/blob/48ee457ec98b728343196362d5d42c0dc3d1cff9/lib/server/generate.js#L466)

to

<pre>writeFileAndCreateFolder(targetFile.replace('<b>en</b>', '/'), str);</pre>

Seems to fix the issue.

Albeit that's clearly a hack and the proper way to fix this would probably just involve implementing the fix on [line 437](https://github.com/facebook/Docusaurus/blob/48ee457ec98b728343196362d5d42c0dc3d1cff9/lib/server/generate.js#L437).

Namely, ``TODO: use path functions``

**Comment by JoelMarcey** [comment]
@Happy-Ferret Hi. Would you mind integrating #490 into your local repo and see if it fixes this problem for you?
