### ISSUE TITLE
Change default language

### ISSUE THREAD

**Issue by gHashTag** [facebook/docusaurus#4681]
## 🚀 Feature

It would be great if it was possible to mince the language automatically depending on the language set by the user in the browser.

## Motivation

 Otherwise, there is a drain of the audience environment. Maybe I don’t know something, and it can be done now?

**Comment by slorber** [comment]
Docusaurus builds a static website. The page language is hard-coded in the final html file.

If you want to build a site for multiple languages, and change the default language, you can. 

Everything else is possible but it's out of the scope of Docusaurus. You can define server redirects on your host provider according to cookies and headers send by the user. It's not something that can be configured by Docusaurus in a generic way, as each host has its specificities
