### ISSUE TITLE
Not able to use 'remarkable-plantuml' in Docusurus V 2.0.0

### ISSUE THREAD

**Issue by Pacific003** [facebook/docusaurus#4694]
## 🐛 Bug Report

I have tried to install remarkable-plantuml for docusururs v 2.0.0 using this command 

`yarn add remarkable-plantuml`

then registered plugin in docusaurus.config with this below line

`plugins: [
    require.resolve('remarkable-plantuml')
  ]
`

After that i am getting error :

`
TypeError: Cannot read property 'ruler' of undefined
    at plantuml (/Users/admin/PV_Project/MCSDK_Doc/Xamarin/Getting-Started-Xamarin/node_modules/remarkable-plantuml/index.js:49:11)
`
## To Reproduce

1. Install remarkable-plantuml using this command  `yarn add remarkable-plantuml`
2. Register Plugin with Docusaurus using this code 
`
plugins: [
    require.resolve('remarkable-plantuml')
  ],
`

3. Run project

## Expected behavior

The project should run successfully and should be able to render PlantUML.

## Actual Behavior

Getting this error in terminal:
`
TypeError: Cannot read property 'ruler' of undefined
    at plantuml (/Users/admin/PV_Project/MCSDK_Doc/Xamarin/Getting-Started-Xamarin/node_modules/remarkable-plantuml/index.js:49:11)
`
<img width="1062" alt="Screenshot 2021-04-28 at 3 01 53 PM" src="https://user-images.githubusercontent.com/43989163/116381597-ae3d0d80-a832-11eb-93ea-59adfee10d0f.png">

## Your Environment

- Docusaurus version used: 2.0.0-alpha.72
- Environment name and version (e.g. Chrome 90.0.4430.85, Node.js v14.16.1):
- Operating system and version (Mac OS):

**Comment by slorber** [comment]
that plugin. looks unmaintained. 

It is likely not compatible anymore with the remark version in use inside Docusaurus. 

Your best chance is to fork the plugin and fix it yourself
