### ISSUE TITLE
Copy control in the getting-started tutorial copies confusing code

### ISSUE THREAD

**Issue by steveharman** [facebook/docusaurus#4698]
## 📚 Documentation

I'm working my way through the Getting Started guide and tried the "Configure the Sidebar" example from docs/tutorial-basics/create-a-document

Using the embedded "Copy" control I copied and pasted the example code into my `hello.md `document, but the code is _displayed_ in the resulting page, rather than affecting the position of my document in the sidebar.

Thanks to some input from another user it appears that the "+" symbols are there to indicate that the relevant lines should be added.  

Which is fine, but in that case the "Copy" control probably shouldn't also copy the plus symbols, as _new users_ like me working through the tutorial will Copy > Paste and expect the pasted code to have the desired effect.

I'm sure it's obvious to seasoned users, but that audience most likely won't be in the tutorial section!  :-)

Thanks.

<img width="1457" alt="docusaurus-2" src="https://user-images.githubusercontent.com/12557929/116528116-57d3db80-a8d3-11eb-9450-fe2e52e18dcc.png">

**Comment by slorber** [comment]
Hi,

The "copy" feature is something that all Docusaurus code blocks have, it's not just a feature of the tutorial, it's a generic feature.

Maybe in case of a "diff" code block showing + and - prefix, we could improve the logic and make it only copy the final code (removing the - lines and the + prefixes?

**Comment by steveharman** [comment]
Hi!  

Understood about the Copy function being on all code blocks, my point was more about the "gotcha" with the "+" symbols being copied when it's used.  Especially for us newcomers trying to learn Docusauraus.

For example the Docusaurus Blog tutorial has a similar looking code block and of course Copy function, but isn't a "diff" style so doesn't have the + symbols.  Using Copy on the Blog code block  works fine, but for people just getting started it was far from obvious why the Sidebar code block in my example didn't.  

eg; I copy one code block - it works.  I copy a different code block - it doesn't work.  this is more about the UX on the Sidebar example tripping up us newcomers.

Thanks

Steve

<img width="1009" alt="blogTut" src="https://user-images.githubusercontent.com/12557929/116535887-34f9f500-a8dc-11eb-9196-69d2154baf25.png">

**Comment by tom-sherman** [comment]
Is there really a need for diff syntax here? I agree that this can confuse people

The other snippets read just fine with highlighted lines, can that be used here?

**Comment by Josh-Cena** [comment]
Agreed that the diff syntax is counterintuitive with copying. Running a global search reveals 78 occurrences of this use:

![image](https://user-images.githubusercontent.com/55398995/117094657-f0b49c00-ad96-11eb-86ea-3b87847adc47.png)

Most of them can be replaced by line highlights, which has the additional merit of better syntax highlighting for the rest of the snippet. Should we go for that instead of patching the copy function?
