### ISSUE TITLE
[accessibility] Low color contrast of responsive sidebar button

### ISSUE THREAD

**Issue by vibhavsinha** [facebook/docusaurus#4700]
## 🐛 Bug Report

In mobile devices, when the sidebar is collapsed into a button on bottom-right, the background color of the button has very contrast with the white background.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## To Reproduce

Reduce the width of browser window here: https://docusaurus.io/docs or open in mobile

## Expected behavior

The sidebar button should be easily visible.

## Actual Behavior

It takes time for new users to find where the sidebar is. The color contrast on [WebAim](https://webaim.org/resources/contrastchecker/?fcolor=EBEDF0&bcolor=FFFFFF) is 1.17:1

*Image:*
----
<img width="545" alt="Screenshot 2021-04-29 at 21 28 18" src="https://user-images.githubusercontent.com/1254236/116581416-f000ad80-a931-11eb-84f1-56a4f77b4d7f.png">

---

It is especially difficult because bottom right is not the expected place for this button. Most users expect this to be on the top-left.

## Your Environment

Currently visible on docusaurus website: https://docusaurus.io/docs

Tried with version: 2.0.0-alpha73

## Reproducible Demo

https://docusaurus.io/docs

**Comment by vibhavsinha** [comment]
It appears there is a hover CSS rule that increases the contrast. But since, this is primary visible on touch devices, this rule is not doing much benefit.

**Comment by vibhavsinha** [comment]
This is my temporary workaround added in `src/css/custom.css`. I am not familiar with the CSS conventions of this project or `infima` to create a pull-request.

```
.button--secondary:not(.button--outline) {
  --ifm-button-background-color: var(--ifm-color-emphasis-800);
  color: var(--ifm-font-color-base-inverse);
}
```

The above two variables seems to be derived after applying dark mode condition, hence this works well in dark mode too.

**Comment by slorber** [comment]
We have a whole UX refactor to do for mobile (https://github.com/facebook/docusaurus/issues/2220)

This button may eventually just open the current page TOC, and the sidebar nav will be in the hamburger / drawer menu
