### ISSUE TITLE
error building locale=en TypeError: Cannot read property 'intercept' of undefined

### ISSUE THREAD

**Issue by satanTime** [facebook/docusaurus#4709]
## 🐛 Bug Report

Cannot build docs on `2.0.0-alpha.75`, `2.0.0-alpha.74` works well.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## To Reproduce

1. The issue is here https://github.com/ike18t/ng-mocks/pull/466
1. Clone the repo
1. Switch to branch `renovate/root/patch-docusaurus-monorepo`
1. execute `npm install`
1. execute `npm run build:docs`

## Expected behavior

The build should succeed.

## Actual Behavior

Fails with the next error

```
[en] Creating an optimized production build...
[info] [webpackbar] Compiling Client
error building locale=en
TypeError: Cannot read property 'intercept' of undefined
    at /Users/michael/projects/ng-mocks/node_modules/webpack/lib/ProgressPlugin.js:242:30
    at Array.forEach (<anonymous>)
    at /Users/michael/projects/ng-mocks/node_modules/webpack/lib/ProgressPlugin.js:239:24
    at Hook.eval [as call] (eval at create (/Users/michael/projects/ng-mocks/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:100:1)
    at Hook.CALL_DELEGATE [as _call] (/Users/michael/projects/ng-mocks/node_modules/tapable/lib/Hook.js:14:14)
    at Compiler.newCompilation (/Users/michael/projects/ng-mocks/node_modules/@docusaurus/core/node_modules/webpack/lib/Compiler.js:1031:26)
    at /Users/michael/projects/ng-mocks/node_modules/@docusaurus/core/node_modules/webpack/lib/Compiler.js:1073:29
    at Hook.eval [as callAsync] (eval at create (/Users/michael/projects/ng-mocks/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:4:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/Users/michael/projects/ng-mocks/node_modules/tapable/lib/Hook.js:18:14)
    at Compiler.compile (/Users/michael/projects/ng-mocks/node_modules/@docusaurus/core/node_modules/webpack/lib/Compiler.js:1068:28)
    at /Users/michael/projects/ng-mocks/node_modules/@docusaurus/core/node_modules/webpack/lib/Compiler.js:496:12
    at Compiler.readRecords (/Users/michael/projects/ng-mocks/node_modules/@docusaurus/core/node_modules/webpack/lib/Compiler.js:908:11)
    at /Users/michael/projects/ng-mocks/node_modules/@docusaurus/core/node_modules/webpack/lib/Compiler.js:493:11
    at Hook.eval [as callAsync] (eval at create (/Users/michael/projects/ng-mocks/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:4:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/Users/michael/projects/ng-mocks/node_modules/tapable/lib/Hook.js:18:14)
    at /Users/michael/projects/ng-mocks/node_modules/@docusaurus/core/node_modules/webpack/lib/Compiler.js:490:20
```

## Your Environment

- Public source code: https://github.com/ike18t/ng-mocks/pull/466
- Public site url:
- Docusaurus version used: `2.0.0-alpha.75`
- Environment name and version (e.g. Chrome 78.0.3904.108, Node.js 10.17.0): not relevant, fails on linux and macos
- Operating system and version (desktop or mobile): desktop

## Reproducible Demo

https://app.circleci.com/pipelines/github/ike18t/ng-mocks/269/workflows/e0a901b4-03ab-4288-a0b1-34398ecd8204/jobs/7723/parallel-runs/0/steps/0-110

**Comment by slorber** [comment]
Have you tried docusaurus clear?

**Comment by satanTime** [comment]
There is no cache on my CI and docs are build from scratch on every commit, but I'll try it in some hours.

**Comment by slorber** [comment]
I see

Not in front of a computer atm but found your setup a bit weird. Why do you
have docusaurus deps in 2 different packages

**Comment by satanTime** [comment]
The idea is to follow monorepo approach. There is one global package.json which has all the dependencies for all projects in the repo and they are installed on the root level.
`docs` are a project in the repo and the idea is that its `package.json` only describes desired dependencies and their versions (the same as in the global package.json), but all scripts use parent `node_modules`.

**Comment by wibed** [comment]
I am experiencing the same issue with 2.0.0-alpha.75 together with i18l

✔ Client
  

● Server █████████████████████████ cache (99%) shutdown IdleFileCachePlugin
 stored

error building locale=en
TypeError [ERR_INVALID_URL]: Invalid URL: #
    at new NodeError (node:internal/errors:278:15)
    at onParseError (node:internal/url:259:9)
    at new URL (node:internal/url:335:5)
    at new URL (node:internal/url:332:22)
    at Object.normalizeURL (/Users/work/Documents/workspace/web/homepage/service/home/node_modules/sitemap/dist/lib/utils.js:274:15)

**Comment by slorber** [comment]
@wibed I don't understand how your problem is related to the current issue. Please open another issue with a repro repository that I can inspect

**Comment by wibed** [comment]
@slorber indeed it does not.

Ive mistakenly took the error, based on the message, for a similar problem.

Ive been able to fix my issue, by rebuilding on the new .75 version bit by bit.

**Comment by slorber** [comment]
This is not a problem in Docusaurus, but it is a problem in your repo @satanTime 

After upgrading to alpha.75 (now on Webpack 5), you still end up with `node_modules/webpack` being Webpack 4, while Docusaurus needs Webpack 5. 

It is your responsibility to not mess-up with the dependencies and ensure that Docusarus is able to use the Webpack version it needs, and I think your setup mess-up with the dependencies. 

If you are not using npm/yarn workspaces and the hoisting features permitting multiple webpack versions to cohabit, you should then rather install docusaurus deps independently in the docs subfolder.

Eventually you could try to add "webpack@5" at the root of your monorepo, it might permit Docusaurus to build, but it might break other things of your repo... this is not a solution I'd recommend.

**Comment by satanTime** [comment]
Hi @slorber, thanks for the info... that is the thing I was afraid of. I tried webpack@5 in the global package.json but it didn't work out unfortunately.
I'll try play with it more. Thanks for your help.

PS. Frankly speaking, I don't understand benefit of having a single package.json with all the deps... maybe one day... thanks again.

**Comment by slorber** [comment]
> PS. Frankly speaking, I don't understand benefit of having a single package.json with all the deps... maybe one day... thanks again.

I don't know either 😅 you can't expect this strategy to remain sustainable over time particularly when your monorepo packages have different lifecycles and dependencies

**Comment by satanTime** [comment]
yes, exactly :) I remember reading `nx`creator's answer "You need time to understand why the global package.json works better", so I don't give up :) Although there were several bell rings and one more is here again.

**Comment by Caperious** [comment]
@satanTime How did u resolve the issue? Moved the docusaurus to its own repo?

**Comment by satanTime** [comment]
Hi @satanTime, not moving, but allowing it having own node_modules, before it had to be `peerDependencies`, not it is `dependencies`: https://github.com/ike18t/ng-mocks/commit/91f4ee70c014892e22365d4cbcfa160361806dec

Unfortunately, I wasn't able to make friends angular with webpack4 and docusaurus with webpack5 with a single package.json
