### ISSUE TITLE
webpack 5 Regressions Tracking Issue

### ISSUE THREAD

**Issue by RDIL** [facebook/docusaurus#4718]
This is just an issue to help both me and the maintainers keep track of bugs known to be a result of upgrading to webpack 5:

- ~#4713 Markdown loader performance issues~
- #4717 compilation never completes?
- ~#4709 locale `intercept` is undefined crash~

I will try to help where possible, to get this working smoothly again.

**Comment by slorber** [comment]
Thanks

Also my top priority to get rid of Webpack 5 issues asap, 1 already cleared ;)
