### ISSUE TITLE
Syntax error when using `docusaurus-init` on OSX 10.13.3?

### ISSUE THREAD

**Issue by kwailamchan** [facebook/Docusaurus#472]
Installing docusaurus on OSX (High Sierra, V10.13.3) by the commands

```
$ brew install yarn
$ yarn global add docusaurus-init 
$ docusaurus-init
```

Syntax error was shown as

```
/Users/<username>/.config/yarn/global/node_modules/docusaurus-init/initialize.js:16
let useYarn = false;
^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:413:25)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:475:10)
    at startup (node.js:117:18)
    at node.js:951:3
```

**Comment by JoelMarcey** [comment]
Hi @kwailamchan. What version of yarn are you using? Do you get the same error when running using `npm`?

**Comment by kwailamchan** [comment]
Hi @JoelMarcey Thanks for your response. Problem solved when node updated after reading your message.

```
node v8.9.4
npm v5.6.0
yarn v1.3.2
```

It worked good.

**Comment by JoelMarcey** [comment]
@kwailamchan What version of `node` were you running before you updated? Just curious.

**Comment by kwailamchan** [comment]
@JoelMarcey It was v4.1.0.

**Comment by alhajjabbass** [comment]
Hello, did you solve the error you were having ?

**Comment by kwailamchan** [comment]
@alhajjabbass upgraded node from v4.1.0 to v8.9.4, problem solved.

**Comment by alhajjabbass** [comment]
yep it's solved, thank you very much!

**Comment by JoelMarcey** [comment]
I documented the Node requirements at https://docusaurus.io/docs/en/installation.html so people can know this for the future.
