### ISSUE TITLE
JAVA code is not highlighted

### ISSUE THREAD

**Issue by stockiNail** [facebook/docusaurus#4720]
## 🐛 Bug Report

The JAVA code is highlighted.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

YES

## To Reproduce

https://codesandbox.io/s/blissful-colden-z454y?file=/docs/intro.md

1. Step 1Open sidebar
1. Step 2 Click tutorial
1. Step 3 Go to the bottom, where JAVA code has been added.

## Expected behavior

The JAVA code should be highlighted.

## Actual Behavior

The JAVA code should be highlighted.

Source code:

![DCbug1-src](https://user-images.githubusercontent.com/11741250/116897839-0494bc80-ac36-11eb-982b-ec85294ce0ba.png)

Result:

![DCbug1-run](https://user-images.githubusercontent.com/11741250/116897866-0b233400-ac36-11eb-839e-bf2a4828f161.png)

## Your Environment

- Public source code: https://github.com/pepstock-org/Charba-Wiki/tree/stock (branch stock)
- Docusaurus version used: 2.0.0-alpha.75
- Environment name and version: FF 88.0, Node.js v12.18.3

**Comment by slorber** [comment]
Agree something is weird, as Java is normally supported out of the box

We even have a Java snipped in ur website:
https://docusaurus.io/docs/next/markdown-features/code-blocks#multi-language-support-code-blocks

![image](https://user-images.githubusercontent.com/749374/116899879-66eebc80-ac38-11eb-9c03-1aeadcd55bdd.png)


Is this a new bug after upgrading to alpha 75? Was it working before?

**Comment by stockiNail** [comment]
@slorber I was using alpha-68 and it worked!

**Comment by stockiNail** [comment]
> We even have a Java snipped in ur website:
> https://docusaurus.io/docs/next/markdown-features/code-blocks#multi-language-support-code-blocks

yes, sounds working on the official doc, but not in code sandbox (and in my project).. :(

**Comment by slorber** [comment]
Can you try alpha 74? Alpha 75 is a big upgrade (Webpack 5) so it is more likely to have a few issues

**Comment by stockiNail** [comment]
`npm i @docusaurus/core@2.0.0-alpha.74 @docusaurus/preset-classic@2.0.0-alpha.74`

Nothing is changed. Furthercode, in sandbox, the Docusaurus version is alpha.73

**Comment by stockiNail** [comment]
I have created new sample project, by `npx @docusaurus/init@2.0.0-alpha.74 init my-website classic` and added the java code.

Same error, JAVA code is not highlighted.

**Comment by Josh-Cena** [comment]
There's the same issue here #4535 

> According to the [docusaurus doc](https://docusaurus.io/docs/markdown-features/code-blocks#syntax-highlighting),

> > By default, Docusaurus comes with this subset of [commonly used languages](https://github.com/FormidableLabs/prism-react-renderer/blob/master/src/vendor/prism/includeLangs.js).

> Which doesn't include Java, PHP, or Ruby. You have to manually include them in the config.

**Comment by stockiNail** [comment]
@Josh-Cena GREAT!!! Thank you! I don't why I was convinced to see the code highlighting in version alpha.68...

**Comment by Josh-Cena** [comment]
Yeah, don't know when they stopped supporting Java—probably when they started using Prism? I also remember using Java back in ~alpha.68

**Comment by slorber** [comment]
This is still weird for me: the Docusaurus site itself does not add any additional config and is able to highlight that Java code block here: 

https://docusaurus.io/docs/next/markdown-features/code-blocks#multi-language-support-code-blocks

But nevermind, indeed Java should be added to the list of additional languages as it's not in the default enabled languages of react-prism-renderer

**Comment by stockiNail** [comment]
I agree, it's very weird...
