### ISSUE TITLE
Inconsistent between the website documentation and the typing

### ISSUE THREAD

**Issue by nam-hle** [facebook/docusaurus#4722]
## 📚 Documentation

In user configuration [documentation](https://docusaurus.io/docs/docusaurus.config.js), the required fields are:
- title
- favicon
- url
- baseUrl

But when I go to `docusaurus/packages/docusaurus-types`, there are more required fields in `DocusaurusConfig` interface:
- noIndex
- baseUrlIssueBanner
- i18n
- onBrokenLinks
- onBrokenMarkdownLinks
- onDuplicateRoutes
- themeConfig

So it could make the user be confused somehow. Or maybe it's what the `docusaurus` developers do intentionally.

Btw, I'm willing to contribute to this field if possible :)

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes.

**Comment by slorber** [comment]
It's true and false at the same time.

Docusaurus does not need much configs to work, but it also apply some defaults in case some config attributes are not provided.

The exposed type is the "normalized" version of the config, after we have applied the default values.

Maybe we need to export 2 types instead (raw user config vs normalized config)?

Has this mismatch been a problem in practice for something you tried to achieve?

**Comment by nam-hle** [comment]
Hi @slorber, first of all, I have to say that I love the project priniciple so much. Thanks all.

> Maybe we need to export 2 types instead (raw user config vs normalized config)?

It is quite useful because we use the JS file for configuration. By providing the type reference as we did, other developers could check the typing without leaving the IDE. 

> Has this mismatch been a problem in practice for something concrete you tried to achieve?
No, it's not. I just found the project and try to dig the codebase in order to contribute some little efforts if possible 👯

**Comment by slorber** [comment]
Thanks :)

Do you use JSDoc annotations on config?

```js
/** @type {import('@docusaurus/types').DocusaurusConfig} */
module.exports = {
  title: "Docusaurus",
}
```
Should we have a type "DocusaurusConfigInput" or something? What would be a good name for such type?

The normalized type is already used and is used in much more places so I'd rather not rename it

**Comment by nam-hle** [comment]
> Do you use JSDoc annotations on config? Because afaik we don't support writing the config in TS (or maybe with TS-node?)
> 
> ```js
> /** @type {import('@docusaurus/types').DocusaurusConfig} */
> module.exports = {
>   title: "Docusaurus",
> }
> ```

Yes JS config should be the best at least for now. I used the JSDoc but there is neither errors nor warnings about missing required fields until the validator works. Maybe we can try a suitable way to improve the dev experience.

> Should we have a type "DocusaurusConfigInput" or something? What would be a good name for such type?

How about `DocusaurusUserConfig` to align with the normalized one? Or just simply `UserConfig`.

> The normalized type is already used and is used in much more places so I'd rather not rename it

Totally agree.
