### ISSUE TITLE
 image file name can be in Chinese or other languages

### ISSUE THREAD

**Issue by ywjr** [facebook/docusaurus#4730]
## when upgrade   docusaurus   to   v0.74  ,  The following error occurred：

SyntaxError: D:\doc\helpcenter\my-website\docs\新控制器空间\控制器硬件999999.md: The only valid numeric escape in strict mode is '\0'. (9:149)
 | <p><img src={require("!url-loader?limit=10000&name=assets/images/[name]-[hash].[ext]&fallback=file-loader!D:\doc\helpcenter\my-website\static\images\4\82\中文.png").default} /></p>

The possible reason is that the name of the picture is in Chinese, not in alphabet,
I suggest that the image name can be in Chinese or other languages

**Comment by Josh-Cena** [comment]
This is not a problem with the Chinese characters. The URL string contains characters like `\4` and `\8` which are parsed to be escape characters but unfortunately "The only valid numeric escape in strict mode is '\0'". You need to escape the backslashes like
```jsx
<img src={require("!url-loader?limit=10000&name=assets/images/[name]-[hash].[ext]&fallback=file-loader!D:\\doc\\helpcenter\\my-website\\static\\images\\4\\82\\中文.png").default} />
```

**Comment by ywjr** [comment]
-    i  write    ![](/images/4/82/中文.png)   in  md  file,  
-
-    the same  md  file and  image file    on docusaurus     V0.73    is ok  ,but  v0.74   is  error

**Comment by Josh-Cena** [comment]
Could you confirm that it's a CJK-caused issue by trying out my solution? That's the best we can do by looking at the error message.

> the same md file and image file on docusaurus V0.73 is ok ,but v0.74 is error

v2 is still in alpha so lots of breaking changes are introduced. Backward compatibility is not always ensured. However I also don't know which change exactly caused your problem

**Comment by ywjr** [comment]
on the version of v0.75, I did the following tests:

Test 1: if the image file name is in Chinese, an error will occur

Picture name:
```yml
中文.png
```

In the MD file:

```yml

![](/ Images /4/82/中文. PNG)

```

Test 2: everything else is the same, only the image file name is a letter, running normally

Picture name:

```yml

qqq.png

```

In the MD file:

```yml

![](/ images/4/82/qqq.png)

```

**Comment by Josh-Cena** [comment]
By my interpretation, this is **_not_** about the path in the MD file, but where you referenced it using `require`. If you are testing it on alpha75 where the error occurs, the best explanation may be because of Webpack 5.

Also, to help others find out what's wrong, you should probably follow the issues template and provide a way to reproduce.

**Comment by Josh-Cena** [comment]
I tested with my app by creating an image `static/img/图片.jpg` and referencing it in a blog page using

```jsx
<img src="/img/图片.jpg" />
```

No errors occurred.

**Comment by Josh-Cena** [comment]
I tested with my app by creating an image `static/img/图片.jpg` and referencing it in a blog page using

```jsx
<img src="/img/图片.jpg" />
```

No errors occurred on either alpha-74 or alpha-75. So it's not a problem with the CJK path itself. Please try escaping the backslashes.

**Comment by Josh-Cena** [comment]
I see the issue here. The error is reported after the image loader starts processing the URL:

```js
jsxNode.value = `<img ${node.alt ? `alt={"${escapeHtml(node.alt)}"} ` : ''}${
    node.url
      ? `src={require("${inlineMarkdownImageFileLoader}${pathUrl}").default}`
      : ''
  }${node.title ? ` title="${escapeHtml(node.title)}"` : ''} />`;
```

It seems the issue is platform dependent, so I can't offer further help on this other than possibly trying another directory name that doesn't start with a digit.

**Comment by ywjr** [comment]
1、 os 

版本	Windows 10 家庭中文版

版本号	20H2

安装日期	‎2021/‎4/‎4

操作系统内部版本	19042.928


体验	Windows Feature Experience Pack 120.2212.551.0


2、node  -v

v14.15.0

3、Docusaurus   v0.75

4、Test process

 - create  img   file    
```yml
static/img/图片.png
```
-   in  md file
```yml
![](/img/图片.png)
```
- result
![微信图片_20210505123621](https://user-images.githubusercontent.com/62584887/117098503-42622400-ada1-11eb-9ba8-502ec74f9dbb.png)

**Comment by slorber** [comment]
We have a function "posixPath" that is supposed to escape the slashes, but for some reasons there's a edge case that prevent escaping `\` when there are non-ASCI chars.

```js
export function posixPath(str: string): string {
  const isExtendedLengthPath = /^\\\\\?\\/.test(str);
  const hasNonAscii = /[^\u0000-\u0080]+/.test(str); // eslint-disable-line

  if (isExtendedLengthPath || hasNonAscii) {
    return str;
  }
  return str.replace(/\\/g, '/');
} 
```

It looks like the code was originally copied from a lib:
- https://github.com/sindresorhus/slash/blob/main/index.js
- https://github.com/sindresorhus/slash/pull/16

Will try to fix it in https://github.com/facebook/docusaurus/pull/4736, but not sure if removing this `hasNonAscii` check is safe

**Comment by ywjr** [comment]
My testing process and testing environment are as follows:


1. operating system: Windows 10 Chinese version


2、 node ： v14.15.0


3、docusaurus ： v2 0.75


4. Create a picture file with the name in Chinese as follows:


``` yml


Static/img /图片.jpg


···


5. In the MD file,


![](/img/图片.png)



6. when yarn start&nbsp; &nbsp;startup&nbsp; webpack&nbsp; ,There was an error in the result，&nbsp;&nbsp;








------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "facebook/docusaurus"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月6日(星期四) 晚上9:38
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [facebook/docusaurus]  image file name can be in Chinese or other languages (#4730)





 
We have a function "posixPath" that is supposed to escape the slashes, but for some reasons there's a edge case that prevent escaping \ when there are non-ASCI chars.
 export function posixPath(str: string): string {   const isExtendedLengthPath = /^\\\\\?\\/.test(str);   const hasNonAscii = /[^\u0000-\u0080]+/.test(str); // eslint-disable-line   if (isExtendedLengthPath || hasNonAscii) {     return str;   }   return str.replace(/\\/g, '/'); } 
 
It looks like the code was originally copied from a lib:
  
https://github.com/sindresorhus/slash/blob/main/index.js
 
sindresorhus/slash#16
  
Will try to fix it in #4736, but not sure if removing this hasNonAscii check is safe
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by ywjr** [comment]
My testing process and testing environment are as follows:


1. operating system: Windows 10 Chinese version


2、 node ： v14.15.0


3、docusaurus ： v2 0.75


4. Create a picture file with the name in Chinese as follows:


``` yml


Static/img /图片.png


···


5. In the MD file,


![](/img/图片.png)



6. when yarn start&nbsp; &nbsp;startup&nbsp; webpack&nbsp; ,There was an error in the result，&nbsp; 






7、 7. If I change the&nbsp; name of the picture file from Chinese to English, as follows:
```yml
static/img/test.jpg
```
in&nbsp; md file : ![](/img/test.jpg)
Running is OK

















------------------ 原始邮件 ------------------
发件人:                                                                                                                        "facebook/docusaurus"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月6日(星期四) 晚上9:38
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [facebook/docusaurus]  image file name can be in Chinese or other languages (#4730)





 
We have a function "posixPath" that is supposed to escape the slashes, but for some reasons there's a edge case that prevent escaping \ when there are non-ASCI chars.
 export function posixPath(str: string): string {   const isExtendedLengthPath = /^\\\\\?\\/.test(str);   const hasNonAscii = /[^\u0000-\u0080]+/.test(str); // eslint-disable-line   if (isExtendedLengthPath || hasNonAscii) {     return str;   }   return str.replace(/\\/g, '/'); } 
 
It looks like the code was originally copied from a lib:
  
https://github.com/sindresorhus/slash/blob/main/index.js
 
sindresorhus/slash#16
  
Will try to fix it in #4736, but not sure if removing this hasNonAscii check is safe

**Comment by ywjr** [comment]
sorry ,There's something wrong with my network connection. I can't connect to Canary right now


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "facebook/docusaurus"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月6日(星期四) 晚上10:49
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [facebook/docusaurus]  image file name can be in Chinese or other languages (#4730)





 
test in upcoming canary release and let me know if it works

**Comment by ywjr** [comment]
Version: 2.0.0-beta. 0 can support Chinese image names, thank you









------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "facebook/docusaurus"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月6日(星期四) 晚上10:49
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [facebook/docusaurus]  image file name can be in Chinese or other languages (#4730)





 
test in upcoming canary release and let me know if it works
