### ISSUE TITLE
facetFilters configuration not interpreted correctly with i18n

### ISSUE THREAD

**Issue by TomPeirs** [facebook/docusaurus#4732]
## 🐛 Bug Report

We localized our docusaurus website with the i18n feature.
Our website is has only 1 version so we don't need contextual search yet. -> I tried `contextualSearch: true,` this returns 0 results.
However the website is in 2 languages. So instead I decided to use `faceFilters` .

We have 3 docusaurus websites, but one algolia index.  our configuration looks good to me (very similar to docusaurus-v2 config except we have tags for the product):
https://github.com/algolia/docsearch-configs/blob/master/configs/boc-group.json

The algolia index is created based of the following URLs.
https://docs.boc-group.com/adonis/
https://docs.boc-group.com/adoit/
https://developer.boc-group.com/

Hence, **with the following configuration we get search results** of the appropriate product (e.g. adonis), **BUT in 2 languages**.
And we want to have only the language we are in.

```
    algolia: {
        apiKey: '3acb8d1e2dca055840337e29fa9be493',
        indexName: 'boc-group',
        searchParameters: {
            facetFilters: ['tags:adonis']
        },
```

SO.
We decided to add another facetfilter (because contextual search returns 0 results) --> 
```
        algolia: {
            apiKey: '3acb8d1e2dca055840337e29fa9be493',
            indexName: 'boc-group',
            searchParameters: {
                facetFilters: ["tags:adonis","language:en"]
            },
        },
```
unfortunatly **the above results in 0 results**

## To Reproduce

It's complicated to reproduce this in a sandbox due to the dependency with algolia.

## Expected behavior

I would expect to find searchresults for the language I am in.

## Actual Behavior

the search results return results in both languages.

## Your Environment

- Public source code: /
- Public site url: https://docs.boc-group.com/adonis/
- Docusaurus version used: Alpha.75
- Environment name and version (e.g. Chrome 78.0.3904.108, Node.js 10.17.0):
- Operating system and version (desktop or mobile): Windows 10  desktop

## Reproducible Demo

The sandbox has trouble compiling with algolia it seems
https://codesandbox.io/s/holy-rgb-rszwc?file=/docusaurus.config.js
```
./node_modules/@docusaurus/theme-search-algolia/src/theme/SearchPage/index.js
Module not found: Can't resolve '@theme/hooks/useSearchQuery' in '/sandbox/node_modules/@docusaurus/theme-search-algolia/src/theme/SearchPage'
```

**Comment by TomPeirs** [comment]
![image](https://user-images.githubusercontent.com/68061801/117301855-567a5400-ae7b-11eb-8783-195a7bae3492.png)

It appears or  I understand now that the index is wrong.
Unfortunatly the Docsearch only gave access rights to the Algolia analytics dashboard but not the index itself.

I now realize that production does not have the required filters because in production we have lunar search still, hence why the index is wrong.

This does mean that for first time users, their search will only work after 24 hours after deployment to production.
OR
 if you want a correct index before production, as you suggest, create a stage deployment with something like vercel where you include configure docsearch, index that (ask docsearch to accept your fork with your staging URL), in order to have a correct index before deploying to production.

**Comment by slorber** [comment]
Yes, it is required that you first deploy a Docusaurus site with the Algolia Docsearch plugin enabled, and then run a crawler on this site with the plugin enabled, so that the index is populated by the correct page metadatas
