### ISSUE TITLE
Bad DX for sites without sidebar file

### ISSUE THREAD

**Issue by slorber** [facebook/docusaurus#4752]
## 🐛 Bug Report

See https://github.com/facebook/docusaurus/discussions/4738

When using Docusaurus docs plugin (single or multi-instance) without `sidebarPath`, user gets a warning:

> The sidebar file of docs version [current] does not exist. It is optional, but should rather be provided at website/sidebars.json

- the error message is not very good, and does not even mention which docs plugin instance is concerned
- when using multi-instance, the default sidebarsPath value is always `sidebars.json` (for all docs instances) => not very good

Solution:
- We don't need a default `sidebarsPath` value
- We should allow `sidebarsPath: false` to disable sidebars for a plugin instance, without any warning
- We should allow `sidebarsPath: undefined` to have a fully auto-generated sidebar, without any warning
- We should warn if `sidebarsPath` is using a path to a sidebar file that does not exist

**Comment by lex111** [comment]
Closing this issue since it is has been resolved in #4775.
