### ISSUE TITLE
[FEATURE REQUEST] support hiding top right table of contents

### ISSUE THREAD

**Issue by Yiyiyimu** [facebook/docusaurus#4771]
## 🚀 Feature

Currently, the top right toc might take too much space in certain circumstances, so we kind of lack enough space to present out the real docs. Collapsing sidebar is very helpful, so I wonder if we could also collapse ( or hide maybe ) the top right toc

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## Motivation
As shown in our [website](http://apisix.incubator.apache.org/docs/apisix/admin-api/#route), after collapsing sidebars, there are still quite a lot blank spaces on the both sides of the page, so the table in the doc actually presents in a kind of awkward way (one sentence being broken into several lines). So I think it might be better if we could also hide the toc.
![image](https://user-images.githubusercontent.com/34589752/117877576-b8b7c800-b272-11eb-9dcc-ebd2ba3fd7fb.png)

## Pitch

(Please explain why this feature should be implemented and how it would be used.)

I think the PR #1817 which support collapsing sidebar would be a good reference

**Comment by slorber** [comment]
There is a `hide_table_of_contents` frontmatter

But I don't think it will increase the main space to display your tables, because it is not a good practice to make the main content take the full width of the page and we set a max width.

You would have to provide custom CSS if you want to increase the main content width

**Comment by Yiyiyimu** [comment]
Thanks for the suggestions!
