### ISSUE TITLE
# Headers in pasted URLs (external links) do not load the page at the specified header

### ISSUE THREAD

**Issue by bgree052** [facebook/docusaurus#4776]
## 🐛 Bug Report

When trying to load a page at a specific header via an external link or pasting in a URL with a # header argument, the page instead loads at the beginning rather than at the header specified. 

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## To Reproduce
1. Paste in this link in your browser and hit enter (https://docs.lunalabs.io/docs/playable/getting-started/step-by-step#2-create-your-playable-scene-in-unity)
2. Notice that the URL removes the header argument and instead loads at the beginning of the page

## Expected behaviour

I expected the page to load with # header still in the URL and at that specified header location on the page. 
**Note:** Links that are on pages that link to headers (both for headers on the same page, and to headers on other pages) work fine. 

## Actual Behaviour

The page instead loads at the beginning rather than at the header specified, and you can see the URL change before the page loads to remove the # header argument from it. 

A gif of this happening
![alt-text](https://i.imgur.com/1p5RF56.gif)

(A gif of the full page view of the problem occurring if you click [here](https://i.imgur.com/jnbM6Eq.gif))

## Your Environment

- Public source code: Not available publicly
- Public site url: https://docs.lunalabs.io/
- Docusaurus version used: 2.0.0-alpha.58
- Environment name and version: Chrome 90.0.4430.212, Babel 7.10.4, Node 14.0.19
- Operating system and version: Windows 10 Pro, Version 20H2

**Comment by slorber** [comment]
> Docusaurus version used: 2.0.0-alpha.58

Please upgrade to latest version, this bug may already be fixed

**Comment by bgree052** [comment]
> > Docusaurus version used: 2.0.0-alpha.58
> 
> Please upgrade to latest version, this bug may already be fixed

I have updated to the latest stable release and it has not fixed this issue.
