### ISSUE TITLE
[webpack 5] Yarn v2 can't resolve file loader in docs plugin

### ISSUE THREAD

**Issue by RDIL** [facebook/docusaurus#4778]
## 🐛 Bug Report

On webpack 5, Yarn 2 can't resolve file-loader when building docs.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## To Reproduce

Clone https://github.com/rdilweb/rdil.rocks and update the Docusaurus version in the `/docs` project - then `yarn && yarn build`.

## Expected behavior

Build passes.

## Actual Behavior

file-loader not found error.

## Your Environment

- Public source code: https://github.com/rdilweb/rdil.rocks
- Public site url: https://rdil.rocks/docs
- Docusaurus version used: alpha 75
- Environment name and version: Debian LTS, Node 14.16.1
- Operating system and version (desktop or mobile): Debian LTS

## Reproducible Demo

https://github.com/rdilweb/rdil.rocks

**Comment by slorber** [comment]
It's something I noticed during the Webpack 5 PR. 

Our Yarn2 e2e test did not use the latest version of Docusaurus. 
After I fixed it, Yarn2 failed due to this missing file-loader.
As a temporary solution, added the file-loader to the init template sites so it can build on Yarn2.

This should be fixed once we migrate to the new assets system: https://github.com/facebook/docusaurus/pull/4708

**Comment by HazyFish** [comment]
Any update on this? The PR has been inactive for 3 months now.

**Comment by slorber** [comment]
@HazyFish this PR is stuck until I figure out a proper way to solve this problem: https://github.com/webpack/webpack/issues/12900#issuecomment-830197195
(any help welcome)

Your issue does not look related to Yarn2/file-loader/url-loader but more about Webpack not polyfilling nodejs modules anymore.
https://blog.sindresorhus.com/webpack-5-headache-b6ac24973bf1

You can add the missing polyfills yourself if you need to: create a local docusaurus plugin that modify the existing Webpack configuration to add that polyfill

**Comment by hhaoao** [comment]
oh, Is there any progress on this issue?
I installed these two missing packages and it works fine.


https://github.com/testing-library/testing-library-docs/issues/928
>pnpm add url-loader @mdx-js/react
