### ISSUE TITLE
How can we change the <title> of the /en/users?

### ISSUE THREAD

**Issue by lipis** [facebook/Docusaurus#478]
Related: https://github.com/prettier/prettier/issues/4062

**Comment by JoelMarcey** [comment]
Hi @lipis - thanks for raising this issue. Just for clarity, you are ok with the URL structure for `users.html` - e.g., https://docusaurus.io/en/users.html - you just want want to be able to change the the title that people see in the browser, which in our case is 

```
<title>Docusaurus · Easy to Maintain Open Source Documentation Websites</title>
```

If so, I agree - the title for this page should be configurable. And I will label this as a possible bug and investigate.

**Comment by lipis** [comment]
https://prettier.io/en/users/ we don't want to use the .html extension.. so I believe it should be easily configurable

**Comment by JoelMarcey** [comment]
Hi @lipis - thanks for the response. Just so we are not conflating two issues here, I see to requests from you:

1. Change the `<title>` of the `users.html` page to be something different than the generic title it has now.
2. Allow URLs with no file/extension as discussed here in https://github.com/facebook/Docusaurus/issues/413

**Comment by lipis** [comment]
We just want to be able to add a title to the https://prettier.io/en/users/ 

Here is the actual issue: https://github.com/prettier/prettier/issues/4062
