### ISSUE TITLE
Update notifier not detecting latest version

### ISSUE THREAD

**Issue by loozhengyuan** [facebook/docusaurus#4782]
## 🐛 Bug Report

When running `docusaurus` commands on `2.0.0-beta.0`, the update notifier reads the last alpha version as the latest.

## Expected behavior

Expected update notifier to be detect the latest version.

## Actual Behavior

```console
$ docusaurus build

   ╭────────────────────────────────────────────────────────────────────────────────────────╮
   │                                                                                        │
   │                     Update available 2.0.0-beta.0 → 2.0.0-alpha.75                     │
   │                                                                                        │
   │   To upgrade Docusaurus packages with the latest version, run the following command:   │
   │         yarn upgrade @docusaurus/core@latest @docusaurus/preset-classic@latest         │
   │                                                                                        │
   ╰────────────────────────────────────────────────────────────────────────────────────────╯
```

## Your Environment

```console
$ docusaurus --version
2.0.0-beta.0
```

**Comment by slorber** [comment]
Thanks, was also reported this:

![image](https://user-images.githubusercontent.com/749374/118112803-ca6dac80-b3e5-11eb-88b4-541591e92023.png)

**Comment by slorber** [comment]
@loozhengyuan can you tell me from which version of Docusaurus you upgraded to the beta.0 ? 
Is the site open-source?
Is the message constantly displayed?

Might be related to:
- https://github.com/facebook/docusaurus/pull/4257
- https://github.com/yeoman/update-notifier/pull/192

**Comment by loozhengyuan** [comment]
@slorber I upgraded from alpha.72 to beta.0. Unfortunately, its an internal site so I am not able to share the repo. Interestingly, the message is no longer displayed now.
