### ISSUE TITLE
Docusaurus Node/SSR could not render static page because of error: Minified React error #130 after upgrading to v2 beta 0

### ISSUE THREAD

**Issue by charleskorn** [facebook/docusaurus#4783]
## 🐛 Bug Report

I'm trying to upgrade my site from 2.0.0-alpha.72 to 2.0.0-beta.0, and am getting a large number of errors like this one when running `yarn build` (which is `docusaurus build`):

```
Docusaurus Node/SSR could not render static page with path=/404.html because of error: Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=undefined&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
```

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## To Reproduce

1. Clone https://github.com/batect/batect.dev
2. Switch to branch `renovate/docusaurus-monorepo` (from https://github.com/batect/batect.dev/pull/252)
3. Run `yarn build`

## Expected behavior

Site builds without error, or shows a clearer error message telling me what's wrong and how to fix it (or at least pointing me in the right direction).

## Actual Behavior

`yarn build` fails with lots of errors like

```
Docusaurus Node/SSR could not render static page with path=/404.html because of error: Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=undefined&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
```

A full build log can be seen in [this GitHub Actions build](https://github.com/batect/batect.dev/pull/252/checks?check_run_id=2570416666#step:7:14).

`yarn start` launches the local dev version of the site without any errors.

## Your Environment

- Public source code: https://github.com/batect/batect.dev
- Public site url: https://batect.dev
- Docusaurus version used: 2.0.0-beta.0
- Environment name and version (e.g. Chrome 78.0.3904.108, Node.js 10.17.0): Node.js 16.1.0
- Operating system and version (desktop or mobile): macOS 11 and GitHub Actions Linux runner

## Reproducible Demo

1. Clone https://github.com/batect/batect.dev
2. Switch to branch `renovate/docusaurus-monorepo` (from https://github.com/batect/batect.dev/pull/252)

**Comment by slorber** [comment]
Your site has webpack + babel customizations and also using internal code like fileLoaderUtils. 

Regenerating the lockfile + del node modules + removing your extra babel configuration seems to fix it: https://github.com/batect/batect.dev/pull/256

We can't support you in such case and it is your responsibility to make sure your site customizations still work on upgrades. If you are not comfortable with that, you should not do such customizations in the first place and keep a simple Docusaurus site.

**Comment by charleskorn** [comment]
No worries, thanks for your help. Is there any way to get a more detailed error message from the build process so I can diagnose problems like these myself? There weren't any clues in that error message that I could see that could have led me towards checking the customisations I've added, and I wasn't getting an error when running in dev mode, as I mentioned in my original bug report.

**Comment by slorber** [comment]
I definitively get a console log error message when browsing your homepage.

Something like: exports is not defined
Which makes think of a potential transpilation issue related to Webpack or
babel.

We can't do anything to make those error messages more clear, and it
remains your responsability to debug those issues, even if it is time
consuming


Le jeu. 13 mai 2021 à 12:46, Charles Korn ***@***.***> a
écrit :

**Comment by tony** [comment]
I had to do this to fix the import/export issue

```
module.exports = {
  presets: [require.resolve('@docusaurus/core/lib/babel/preset')],
  plugins: ["@babel/plugin-transform-modules-commonjs"]
};
```
