### ISSUE TITLE
CodeBlock appearance stay dark when switching to light mode.

### ISSUE THREAD

**Issue by aryoxp** [facebook/docusaurus#4788]
### Have you read the [Contributing Guidelines on issues]

Yes

## To Reproduce

1. Start a new Docusaurus project and open on a page which has a code block on it or open the Docusaurus sandbox demo page at: https://codesandbox.io/s/docusaurus . The page will appear in dark theme mode.
2. Open Tutorial page from the menu which has a code block on it.
3. Switch the theme to light theme mode froom the navbar. The code block appearance stays in dark theme mode.

## Expected behavior
I am not sure if this is the correct behavior of the theme switching regarding the code block of Docusaurus v2. But I am expecting it is going to work as in Docusaurus official documentation site (https://docusaurus.io/docs/next/). When switching the theme from dark to light vice-versa, the code block appearance is switching properly.

Docusaurus online documentation light theme:

![Screen Shot 2021-05-14 at 12 22 24](https://user-images.githubusercontent.com/649791/118216791-22bcb100-b4af-11eb-8e28-23975465f9f4.png)

Docusaurus online documentation dark theme:

![Screen Shot 2021-05-14 at 12 22 56](https://user-images.githubusercontent.com/649791/118216806-28b29200-b4af-11eb-903c-c16e36b73c88.png)

## Actual Behavior

The code block appearance stays in dark theme mode, regardless the dark/light theme.

![Screen Shot 2021-05-14 at 12 09 29](https://user-images.githubusercontent.com/649791/118216651-df624280-b4ae-11eb-9ebd-512f203fed88.png)

![Screen Shot 2021-05-14 at 12 20 56](https://user-images.githubusercontent.com/649791/118216663-e2f5c980-b4ae-11eb-923c-a8f55c8b067b.png)

## Your Environment

- Public source code: N/A
- Public site url: N/A (local development)
- Docusaurus version used: 2.0.0-beta.0
- Environment name and version (e.g. Chrome 78.0.3904.108, Node.js 10.17.0):
- Operating system and version (desktop or mobile): macOS Catalina 10.15.7

## Reproducible Demo

1. Open https://codesandbox.io/s/docusaurus
2. Open the Tutorial page on Browser panel 
3. Switch theme to dark and light
4. The code blocks stay in dark appearance

**Comment by slorber** [comment]
https://docusaurus.io/docs/api/themes/configuration#theme

You can set distinct codeblock Prism themes for light/dark mode

Maybe we should also document it here?
https://docusaurus.io/docs/markdown-features/code-blocks#syntax-highlighting

Eventually, add a distinct dark theme in the init templates?

**Comment by aryoxp** [comment]
I see, it is my mistake for not reading and understanding the documentation thoroughly.
So it is related to the configuration of prism after all.
I wonder what else can we do with prism other than setting the theme?
```
  themeConfig: {
    prism: {
      theme: require('prism-react-renderer/themes/github'),
      darkTheme: require('prism-react-renderer/themes/dracula'),
      // how about other settings documentation/information?
      // possibly includes the default and possible values for each configuration setting.
    },
    // ...
  },
```
Do you think the documentation can also be improved by adding more information about what we can do with prism from the configuration file documented here?

https://docusaurus.io/docs/docusaurus.config.js

Thank you for the response. I think we can close this issue for now.

**Comment by slorber** [comment]
There's nothing more we can do than what is documented here afaik: https://docusaurus.io/docs/api/themes/configuration#codeblock

Also it's not a good idea for me to document on the config doc, because the config can use a custom theme that has totally different theme config object than the theme config object of the theme-classic. I would rather remove/reduce that themeConfig example in the docusaurus config doc, and ask the user to. visit the theme-classic themeConfig doc directly instead
