### ISSUE TITLE
Blog Index / Archive

### ISSUE THREAD

**Issue by hramos** [facebook/Docusaurus#479]
### Is this a bug report?

No, this is a feature request.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

No.

### Environment

[Docusaurus v1.0.3](http://facebook.github.io/react-native/blog/)

### Description of the feature

Docusaurus currently displays the 5 most recent blog posts on a sidebar. There is no archive or index page that displays all posts at a glance. Having such a page would make it useful when looking back through the archive of past blog posts.

An alternative might be to configure one's site to display a large number of posts in the "Recent Posts" sidebar. As it stands, that sidebar is not very useful as it typically displays the same posts that are already visible on the first page of the blog.

**Comment by JoelMarcey** [comment]
@hramos Did you know about https://docusaurus.io/docs/en/blog.html#changing-how-many-blog-posts-show-on-sidebar ? Would that help you?

We should probably document it also on https://docusaurus.io/docs/en/site-config.html too.

**Comment by hramos** [comment]
I knew about the number of posts being configurable, but wasn't aware ALL posts could be displayed. I think that might be sufficient for us.

**Comment by JoelMarcey** [comment]
Let me know - if it isn't sufficient, we can add this to our list of feature items to be implemented.

**Comment by hramos** [comment]
Just tried it out and I think it works really well for React Native.

**Comment by JoelMarcey** [comment]
Did document it here too - https://github.com/facebook/Docusaurus/commit/f0937909478217b2b48b79ac3fcac355d742247a
