### ISSUE TITLE
markdown links with one preceding pair of brackets are not rendered correctly

### ISSUE THREAD

**Issue by leonnicolas** [facebook/docusaurus#4801]
## 🐛 Bug Report

`[][link](#some-title)` is rendered to `[][link](#some-title)`

Links with an even number of preceding bracket pairs are rendered correctly.
Links with an odd number of preceding bracket pairs are not rendered correctly.

Pandoc, github, https://github.com/mity/md4c and docusaurus 1 render these links correctly.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## To Reproduce

1. clone the docusaurus repo or take any docusaurus 2 project
1. insert `[][link](#fast-track)` into `website/docs/introduction.md`
1. Run `yarn start`
2. Open the browser and navigate to `http://localhost:3000/docs/`
3. Notice the line with `[][link](#fast-track)`

## Expected behavior

I expected to see
[][link](#fast-track)

## Actual Behavior

I actually saw
`[][link](#fast-track)`

## Your Environment

- Docusaurus version used: v2.0.0-beta.0 or master

## Reproducible Demo

https://codesandbox.io/s/epic-bash-ok5qk?file=/docs/intro.md
and navigate to Tutorial Intro. The broken link is the next line after the title

**Comment by nam-hle** [comment]
Can you tell me why you need the empty brackets?

**Comment by leonnicolas** [comment]
Hi @nam-hle,
yes, I came across it when I was auto-generating markdown for a custom resource definition (CRD)  in Kubernetes.
Here is an example: https://github.com/prometheus-operator/prometheus-operator/blob/master/Documentation/api.md#alertmanagerlist
Notice the [][Altermanager](#somelink)

Generating a website with docusaurus from this markdown would not display the link to Alertmanager correctly.

**Comment by slorber** [comment]
@leonnicolas I agree that the way it is rendered is surprising.

However, I still don't understand why you want to use double brackets like that. What is your intent? 

Is it a bug in your auto-generation system and somehow you expect Docusaurus to handle it better than it currently does?

This is a behavior of MDX, our markdown+React parser, and unfortunately, I don't think we can fix it in the Docusaurus repo.
You can reproduce it here: https://mdxjs.com/playground/ and report it here if it's not already: https://github.com/mdx-js/mdx

And track this issue for when we upgrade MDX (as it might solve the issue):
https://github.com/facebook/docusaurus/issues/4029

**Comment by leonnicolas** [comment]
> However, I still don't understand why you want to use double brackets like that. What is your intent?
> 
> Is it a bug in your auto-generation system and somehow you expect Docusaurus to handle it better than it currently does?

It is not a bug in the auto-generation.
[][Altermanager](#somewhere) means you can specify a list of [Altertmanager](#somewhere). 
I think it is a golang thing and the Kubernetes community uses it in their docs a lot.
Apparently, they are not using docusaurus 2 for the generation of their websites.

> This is a behavior of MDX, our markdown+React parser, and unfortunately, I don't think we can fix it in the Docusaurus repo.
> You can reproduce it here: https://mdxjs.com/playground/ and report it here if it's not already: https://github.com/mdx-js/mdx

Thank you, I was not aware that you were using this parser. When I found https://github.com/facebook/docusaurus/blob/master/packages/docusaurus-utils/src/markdownParser.ts I though you were using dark magic to parse the markdown.

**Comment by slorber** [comment]
We are converting markdown to JSX in the mdx loader here if that helps: https://github.com/facebook/docusaurus/blob/master/packages/docusaurus-mdx-loader/src/index.js#L67

**Comment by slorber** [comment]
I understand your use case, however, I'm not. sure how we could easily fix it 😅 

Eventually, you could replace such patterns by using HTML entities: `&#91;&#93;[link](#fast-track)`

![image](https://user-images.githubusercontent.com/749374/118531741-73017080-b746-11eb-87e9-af8f7af17461.png)


This shouldn't be too hard to implement a custom remark plugin to pre-process the markdown inputs before mdx

**Comment by leonnicolas** [comment]
> And track this issue for when we upgrade MDX (as it might solve the issue):
> #4029

Yes, v2 of MDX will solve the Issue  [mdx-js/mdx#1559](https://github.com/mdx-js/mdx/issues/1559)
