### ISSUE TITLE
[v2] Integrated Feedback Widget

### ISSUE THREAD

**Issue by yiliansource** [facebook/docusaurus#4808]
## 🚀 Feature: Integrated Feedback Widget

> This is an adaptation of https://docusaurus.io/feedback/p/feedback-widget.

Finding out whether users actually deem the content on your site useful can be very helpful to gain insights into the quality and clarity of the actual content. Most documentation sites have integrated feedback widgets, and I (and according to the feedback page many others) think that this could be a valuable addition.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes!

## Motivation

I have been browsing around various documentation pages, trying to find out which features are currently lacking in Docusaurus, that could be deemed useful to developers. When I found the post on the feedback page (from 2 years ago!) I wanted to bring the idea back up. I apologize in advance if this is already implemented and was simply overlooked by me.

## Pitch

I believe this can be seamlessly integrated into a new package, which could potentially even ship with the default theme. Users would simply have to decide between a layout (with a default given) and a reporting method (more later) to activate the widget.

### Reporting

I will describe two possible methods that came to my mind. Since the site is completely static, there's no way for us to store data _on_ the site. Using a tool like [staticman](https://staticman.net/) _could_ work, but is too tedious to use in this case (in my opinion), since it forces you to continuously merge the reported data into your actual repository.

#### Google Sheets

Simple; use a public Google Sheet where the data is stored. Data can be queried to display the overall feedback on a single page and can be posted to update the data.

The huge disadvantage is that the sheet is public, no one prevents users from just opening the sheet themselves and mess around with it.

#### Google Analytics

Slightly more setup, but could be well worth it.

I found that the feedback widget on the React-Native Docusaurus page uses Google Analytics to report the feedback. Using the [Analytics Reporting API v4](https://developers.google.com/analytics/devguides/reporting/core/v4/quickstart/web-js) from Google, we could send and query data directly from Google Analytics. This could potentially even synergise together with the existing Google Analytics plugin.

### Layouts

Various layouts could be supported, since they all cover the same values (negative/(neutral)/positive). Examples:

| GitBook | React-Native | Unknown (taken from the feedback page) |
|:--:|:--:|:--:|
| ![image](https://user-images.githubusercontent.com/41469451/118614625-412cf000-b7c0-11eb-99a1-6113b4901864.png) | ![image](https://user-images.githubusercontent.com/41469451/118614686-50ac3900-b7c0-11eb-88d3-a414cddb6ad7.png) | ![image](https://user-images.githubusercontent.com/41469451/118614813-6cafda80-b7c0-11eb-8a38-3714144f73e9.png) |

---

I'd be happy to give developing this a try, even if it will not be officially integrated. I would love some feedback on the idea overall and the pitched implementation concepts!

**Comment by slorber** [comment]
Hi,

I have some opinions on how to provide such a feature.
I don't want it to be tightly coupled to a specific provider, and give maximum flexibility to the end-user.

So my idea is more to create some kind of component placeholders in the theme page layouts so that users can fill those placeholders with the content of their choice, including feedback widgets, a comment system or whatever.

For example, the ReactNative site could add this widget by providing an "AfterrDocContent" component.

Somehow, this is a bit similar to swizzling components, except those placeholders components are made for this on purpose, and would permit to reduce the amount of code the user has to maintain (ie copied from the theme) to add such feature

**Comment by slorber** [comment]
BTW, this feature request is part of what I'd like to work on for the beta phase, as explained here: https://docusaurus.io/blog/2021/05/12/announcing-docusaurus-two-beta#what-are-the-goals-of-the-beta

I think this belongs to "extending an existing theme"

**Comment by yiliansource** [comment]
Thanks for your input!

> I don't want it to be tightly coupled to a specific provider, and give maximum flexibility to the end-user.

This is always the ideal case. With provider in this case you mean using Sheets vs Analytics vs Custom Provider?

> So my idea is more to create some kind of component placeholders in the theme page layouts so that users can fill those placeholders with the content of their choice, including feedback widgets, a comment system or whatever.

That sounds great! So you can sort of "hook" into the layout of the theme, and place components wherever you like? I'm all for it!

**Comment by Josh-Cena** [comment]
Closing in favor of #5380. We won't provide any OOTB feedback widget, but we would make it very easy to implement in userland.
