### ISSUE TITLE
Can't deploy/build correctly my project

### ISSUE THREAD

**Issue by victornoleto** [facebook/docusaurus#4817]
Before starting the implementation with Docusaurus, I would like to see how the deployprocess works. So I created a simple project and then immediately deployed it as listed in the documentation.

```
npx @docusaurus/init@latest init temp classic
cd temp
npm run build
```
The process was executed correctly, generating the build folder. However when opening the **index.html** file in this folder with my browser (Google Chrome) I came across the following error:

```
Your Docusaurus site did not load properly.
A very common reason is a wrong site baseUrl configuration.
Current configured baseUrl = / (default value)
We suggest trying baseUrl = /C:/Users/Victor/Documents/dev/assine-online/temp/build/index.html/
````

I was surprised by the suggestion because it would mean that my project would be blocked from running from this directory and it is not what I want. I want a build that generates **a folder that can be easily placed on a server** or shared and run offline.

But I did what was suggested...

```
/** @type {import('@docusaurus/types').DocusaurusConfig} */
module.exports = {
    ...
    baseUrl: '/C:/Users/Victor/Documents/dev/assine-online/temp/build/index.html/',
    ...
}
````

...and did the build again:

```
npm run build
````

And the error persists...

```
Your Docusaurus site did not load properly.
A very common reason is a wrong site baseUrl configuration.
Current configured baseUrl = /C:/Users/Victor/Documents/dev/assine-online/temp/build/index.html/
 We suggest trying baseUrl = /C:/Users/Victor/Documents/dev/assine-online/temp/build/index.html/
````

I even tried to perform the build by removing the initial character ("/") from baseUrl, but then the error during the process happens:

```
Error: EINVAL: invalid argument, mkdir 'C:\Users\Victor\Documents\dev\assine-online\temp\build\C:\Users\Victor\Documents\dev\assine-online\temp\build\index.html\blog'
````

All my effort to learn about the tool will be in vain if I can't get around this problem. I would also like to know if there is any specific procedure to build on a project that decided to opt for **[Docs-only mode](https://docusaurus.io/docs/docs-introduction#docs-only-mode)**.

**Comment by victornoleto** [comment]
I didn't know that I must put the fold in a web server (like apache)...

**Comment by slorber** [comment]
We don't support opening the html files directly on the browser, you have to use a HTTP server.

We provide a `docusaurus serve` command to conveniently test a production build locally
