### ISSUE TITLE
Blogs: add index pages for each sub url level

### ISSUE THREAD

**Issue by Josh-Cena** [facebook/docusaurus#4823]
## 🚀 Feature

We should have index pages for year, month, and day URLs in the blogs.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yea

## Motivation

1. There has long been requests for blog archives. This feature request essentially calls for an out-of-box archive feature.
2. The URL logic for blogs is not the most optimal—when I see a URL like `https://docusaurus.io/blog/2021/05/12/announcing-docusaurus-two-beta`, I would naturally believe that the pages `https://docusaurus.io/blog/2021` or `https://docusaurus.io/blog/2021/05` should exist, but these are unfortunately 404s.

Combining these two motivations, a solution would be to put an index page at the `/blog/2021` and `/blog/2021/05` directories.

Just noticed that there's a Canny request for this as well: https://docusaurus.io/feedback/p/date-filter-using-url

## Pitch

When building the site, add an `index.html` file at each directory level. The content can be in a "blog feed" format, showing all blog posts within that range. For example, `/blog/2021/05/index.html` will show all blog posts written in May, 2021.

**Comment by Josh-Cena** [comment]
@slorber Is this worth consideration? (This will likely result in quite some UI refactoring) If not I'm going to close it anyways, since I solved my need with a custom plugin. See here for example: https://joshcena.com/blog/2021

**Comment by slorber** [comment]
Hey

This is definitively worth adding.

@johnnyreilly already has something similar on his blog: https://blog.johnnyreilly.com/2021/05/01/blog-archive-for-docusaurus/

I suggest having a `/blog/archive` page by default, displaying all the posts with just the title. 
And creating a page per year can also be a thing, maybe we can display more than the title there?
The archive page can allow linking to the yearly pages.

Is it really worth it to have a page per blog month? I wouldn't turn it on by default because very often people write less than a post per month.

> This will likely result in quite some UI refactoring

What do you mean? It's probably just creating a few extra pages in the blog plugin, and probably does not need to change much the existing logic?

> P.S. This implementation is not optimal since https://joshcena.com/zh-Hans/blog/2021 is not created simultaneously

Why isn't it created automatically? Not sure to understand how it's implemented.

> weirdly, if I direct back to en through the locale dropdown, I'm taken to https://blog/2021

I will have to check that, it's the 2nd time this kind of issue is reported already, there's likely an edge case to handle somewhere. Wonder if it's not related to trailing slash.

> How do I correctly make my plugin work with i18n?

I think what is missing is just the locale as baseUrl, you probably need to add in: `normalizeUrl([baseUrl, routeBasePath,"archive"])`: https://github.com/Josh-Cena/Personal-page/blob/master/src/plugins/plugin-blog-index/index.ts#L56

**Comment by Josh-Cena** [comment]
> Is it really worth it to have a page per blog month? I wouldn't turn it on by default because very often people write less than a post per month.

My proposal was mainly to fix the case where I have a page at `https://joshcena.com/blog/2021/02/27/hello` but then nothing on `https://joshcena.com/blog/2021/02`—at least for me, I would expect every level of the URL to be working. If the blog link could instead be like `https://joshcena.com/blog/2021-02-27-hello` there would be less confusion.

About the UI refactor, when I was swizzling the blog list page, I found it hard to add the links to the year/month index pages based on the existing page layout, so I ended up doing a lot of customizations. In order to expose an intuitive enough "entry link" to the archive pages we have to redesign the blog list page... (I also think the blog tags list page is too deeply hidden—you have to first visit the blog tag posts page by clicking on one tag, and then direct back.)

About the i18n, my implementation is all in `plugin-blog-index/index.ts`. I would check out the `baseUrl` issue, thanks:)

**Comment by slorber** [comment]
> I would expect every level of the URL to be working

I don't think this is a legit expectation, considering you can choose the slug you want and add/remove slashes as you want, it does not always make sense to have an index page for each slash you have in the URL. You could also have permalinks without any slash and still want a yearly index page.

> About the UI refactor, when I was swizzling the blog list page, I found it hard to add the links to the year/month index pages based on the existing page layout, so I ended up doing a lot of customizations. 

The `/blog/archive` page could be created, but not necessarily appear on the blog list anyway. In this case the user would have to link to this page, as @johnnyreilly did with a navbar item here: https://blog.johnnyreilly.com/

I suggest that just adding an extra link "See all blog posts" to the archive page on the blog sidebar can be enough, at the bottom of this list:

![image](https://user-images.githubusercontent.com/749374/127846306-7772a3b6-382e-4bff-83e3-1eb1c07b85e9.png)

And we don't particularly need to fully redesign the blog list page. It can be disruptive and annoying for existing users.

**Comment by slorber** [comment]
About the tags, I agree they are too deeply nested and not very accessible.

@sw-yx made the tags more accessible on the Temporal blog:

https://docs.temporal.io/blog/

![image](https://user-images.githubusercontent.com/749374/127846575-f06f111f-c36a-4d0a-b095-cf9ee4cced41.png)


This looks like a good idea to me and would be happy to add this by default for all users (even the featured posts is probably a nice option to propose)

**Comment by sw-yx** [comment]
haha yeah would make the sidebar a bit more useful than it is today

**Comment by Josh-Cena** [comment]
@slorber A quick note, adding `baseUrl` in `addRoute` did do the trick. Thanks!

Busy these weeks, but if no one will be working on this soon, I'd be willing to submit a PR myself

**Comment by johnnyreilly** [comment]
I did not realize that the Temporal blog was Docusaurus! Makes me think I should look into theming a bit - I've just been rolling with the defaults

**Comment by sw-yx** [comment]
heheh. you like? i havent even particularly invested much into theming as much as i wanted to, just made some basic design tweaks

**Comment by johnnyreilly** [comment]
I do like!  I don't suppose the website is open source?  Would be intrigued to examine the tweaks (with an eye on thievery :wink:)

**Comment by sw-yx** [comment]
@johnnyreilly https://github.com/temporalio/documentation/tree/master/src

**Comment by johnnyreilly** [comment]
Nice font: https://aeonik.co.uk/font/

**Comment by Josh-Cena** [comment]
Going to close this as wontfix, now that we have the archive page. I realized that with custom slugs this is probably not a good idea.
