### ISSUE TITLE
Ugly html code syntax

### ISSUE THREAD

**Issue by Andrew-web-coder** [facebook/docusaurus#4824]
## The issue

Ugly html code syntax and colors are different from the homepage

## To Reproduce

1. Open Docusaurus Playground 
2. Copy paste this snippet from https://github.com/facebook/docusaurus/blob/master/website/docusaurus.config.js
    ```
    prism: {
      theme: require("prism-react-renderer/themes/github"),
      darkTheme: require("prism-react-renderer/themes/dracula")
    },
    ```

3. Add some html code in docs

## Expected behavior

To have the same colors as here - https://docusaurus.io/docs/markdown-features/tabs

## Reproducible Demo

https://codesandbox.io/s/loving-heyrovsky-f76no?file=/docs/intro.md - open `docs -> intro` for sample html - it is ugly!!!

**Comment by Josh-Cena** [comment]
This is not just an HTML snippet issue, but a general problem for the prism `github` theme. The same thing happens for languages like bash—the `attr-name` highlight color doesn't look right.

**Comment by lex111** [comment]
Thanks for the report, this caused by new version of prism-react-renderer (see https://github.com/FormidableLabs/prism-react-renderer/pull/100 for more details), so we locked its version to 1.1.1.
