### ISSUE TITLE
[Docs] Publishing your Site: Update to Circle 2.0 Config

### ISSUE THREAD

**Issue by hramos** [facebook/Docusaurus#483]
The existing Publishing doc uses an example `circle.yml` config file based on Circle 1.0. Circle has announced they will [stop supporting Circle 1.0 this August](https://circleci.com/blog/sunsetting-1-0/), therefore the guide should be updated at some point to use a Circle 2.0 `config.yml` instead.

React Native uses Docusaurus and Circle 2.0, so it might serve as a good example to base the new docs on: https://github.com/facebook/react-native-website/blob/master/.circleci/config.yml

**Comment by ashleytqy** [comment]
Hi! I can help with this documentation?

**Comment by JoelMarcey** [comment]
@ashleytqy That would be awesome if you could submit a PR for this.

I believe It would fit in a section here: https://docusaurus.io/docs/en/publishing.html#automating-deployments-using-continuous-integration

So you would update: https://github.com/facebook/Docusaurus/blob/master/docs/getting-started-publishing.md

But please feel free to do what you think is best. 😄

**Comment by JoelMarcey** [comment]
@hramos Can you check https://docusaurus.io/docs/en/publishing.html#automating-deployments-using-continuous-integration to see if all looks good to you now?
