### ISSUE TITLE
 docusaurus: not found in node container

### ISSUE THREAD

**Issue by Casper-Mars** [facebook/docusaurus#4832]
## 🐛 Bug Report

Building inside node container  by using command `yarn run build` get an error.
This is the output:

```shell
Running with gitlab-runner 13.8.0 (775dd39d)
  on node xPDrhuj8
Preparing the "docker" executor
Using Docker executor with image node:latest ...
Pulling docker image node:latest ...
Using docker image sha256:7493e35c7ffa6042748fe654285b11f9922684cdace9fdf34de782f0cba75170 for node:latest with digest node@sha256:025d33d7797aaad52c0e3c96699814946093d4b50f792ec35cbd2f57278b94f2 ...
Preparing environment
00:00
Running on runner-xpdrhuj8-project-34-concurrent-0 via localhost.localdomain...
Getting source from Git repository
00:01
Fetching changes with git depth set to 50...
Reinitialized existing Git repository in /builds/concise/doc/.git/
Checking out bf5828fd as release...
Skipping Git submodules setup
Executing "step_script" stage of the job script
00:01
$ node -v
v16.2.0
$ yarn -v
1.22.5
$ make package
yarn run build
yarn run v1.22.5
$ docusaurus build
/bin/sh: 1: docusaurus: not found
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
make: *** [Makefile:14: package] Error 127
ERROR: Job failed: exit code 1

```

## To Reproduce

I don`t know how to reproduce since it is running on gitlab.

## Expected behavior

Build success.

## Actual Behavior

/bin/sh: 1: docusaurus: not found

## Your Environment

Image is `node:latest`

**Comment by Josh-Cena** [comment]
Mmm. Did you run `yarn install` in your docker?

**Comment by Casper-Mars** [comment]
yes.
It is working after I changed to `yarn install ` and `yarn run build` directly in `.gitlab-ci.yml` file.

**Comment by mdarif** [comment]
> yes. It is working after I changed to `yarn install ` and `yarn run build` directly in `.gitlab-ci.yml` file.

I have been facing the same issue but with `npm`, what exactly hav you changed in yml file in order to make it work?

**Comment by mdarif** [comment]
> > yes. It is working after I changed to `yarn install ` and `yarn run build` directly in `.gitlab-ci.yml` file.
> 
> I have been facing the same issue but with `npm`, what exactly hav you changed in yml file in order to make it work?

Ok, changing  `run: npm ci --frozen-lockfile` to:  `run: npm install --frozen-lockfile` in yml file works for me.
