### ISSUE TITLE
run docusaurus start ，http://localhost:3000/ is not available

### ISSUE THREAD

**Issue by camsong** [facebook/docusaurus#4842]
I got a problem in another project, to reproduced the error, I reinstalled  node and yarn, installed a green start docusaurus, but still got the error.

MacOS Big Sur version 11.3.1, X1

```
➜  my-website node -v
v16.2.0
➜  my-website yarn -v
1.22.10
```

```
npx @docusaurus/init@latest init my-website classic
```

```
cd my-website
yarn start
```
![image](https://user-images.githubusercontent.com/948896/119441817-57572500-bd59-11eb-91c2-7f700f826393.png)

![image](https://user-images.githubusercontent.com/948896/119441855-6a69f500-bd59-11eb-8382-633f503f034f.png)

Changed the port to `6666`, still got the error.

![image](https://user-images.githubusercontent.com/948896/119442405-5b377700-bd5a-11eb-9be9-3cb0ddc5bfb2.png)

![image](https://user-images.githubusercontent.com/948896/119442350-41962f80-bd5a-11eb-857c-d2635de03db5.png)

**Comment by lex111** [comment]
As I can see from last screenshot, 6666 is [unsafe port](https://superuser.com/questions/188058/which-ports-are-considered-unsafe-by-chrome), so try specifying a different, allowed port.

**Comment by camsong** [comment]
@lex111 `8080` still not work.
![image](https://user-images.githubusercontent.com/948896/119491554-a40a2280-bd90-11eb-8d12-fbcc9fa8ee0b.png)

**Comment by lex111** [comment]
@camsong make sure the following lines are in the `/etc/hosts` file on your system:

```
127.0.0.1   localhost
255.255.255.255 broadcasthost
::1 localhost
fe80::1%lo0 localhost
```

**Comment by camsong** [comment]
@lex111, thanks very much, it works now.
I just installed a host switch app 😣, it cleared the hosts file.

**Comment by OzakIOne** [comment]
> Hi there, I've encountered the same error here. I have edited the /etc/hosts file but still doesn't work.
> 
> I'm using mac os Sonoma Apple silicon M1

I've tried on a fresh docusaurus `--port 8585` and got no issue, can you share more details @MkLHX ?

**Comment by MkLHX** [comment]
@OzakIOne i found the solution.
The issue was provided by the drive sync.
When I put the project on a normal folder everything works well.
