### ISSUE TITLE
Java syntax highlighting doesn't work

### ISSUE THREAD

**Issue by stockiNail** [facebook/docusaurus#4845]
## 🐛 Bug Report

(A clear and concise description of what the bug is)

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

YES

## To Reproduce

To see that is not working, you can go to Docusaurus site (beta.0 or 1):

1. Go to https://docusaurus.io/docs/next/markdown-features/code-blocks#multi-language-support-code-blocks
2. Go down to see multiple language sample

## Expected behavior

The expected behavior is to have the syntax highlighting on java source code.
I have the same problem in my project. When I was in version alpha.74, it worked, now on beta.0 doesn't work.

The bad thing is falling back to alpha.74, it doesn't work anymore....

## Actual Behavior

![Screenshot 2021-05-25 121850](https://user-images.githubusercontent.com/11741250/119481797-689d3300-bd53-11eb-8e54-6a93a915d741.png)

## Your Environment

- Public source code: https://github.com/pepstock-org/Charba-Wiki
- Docusaurus version used: beta.0 and alpha.74
Environment name and version: FF 88.0.1, Node.js v12.18.3

**Comment by HonkingGoose** [comment]
You'll need to manually setup Java syntax highlighting.

Quote from the Docusaurus docs (emphasis mine):

> Some popular languages like **Java**, C#, or PHP are not enabled by default.

Read https://docusaurus.io/docs/markdown-features/code-blocks#syntax-highlighting to learn how to setup syntax highlighting. 😉

**Comment by stockiNail** [comment]
@HonkingGoose thank you but I have already done it (I have created another issue about that some days ago #4720).
As you can see, this is the config of my project:

https://github.com/pepstock-org/Charba-Wiki/blob/fa8ed9e34e19f11c0cb2e8ff455e384835efcf58/docusaurus.config.js#L25-L28

```
    prism: {
       additionalLanguages: ['java'],
       theme: require('prism-react-renderer/themes/github'),
    },
```

I have published [here](https://pepstock-org.github.io/Charba-Wiki/docs/intl/Locale) some days ago based on alpha.74 and works:

![Screenshot 2021-05-25 125303](https://user-images.githubusercontent.com/11741250/119486160-40640300-bd58-11eb-8f2e-c5acd03c4c30.png)

Now, after the upgrade to beta.0, this is the result:

![Screenshot 2021-05-25 125227](https://user-images.githubusercontent.com/11741250/119486314-68536680-bd58-11eb-9cfa-276dc951db4e.png)

**Comment by HonkingGoose** [comment]
> @HonkingGoose thank you but I have already done it (I have created another issue about that some days ago #4720).

Whoops, I did not see that you opened that prior issue, sorry! 😄

**Comment by stockiNail** [comment]
Created also a sandbox where https://codesandbox.io/s/eloquent-yonath-7spwh?file=/docs/intro.md
and it works here.... uhm....

**Comment by Josh-Cena** [comment]
Is the highlight only broken when using the `github` theme? It could be because of the latest `prism-react-renderer` update...

**Comment by lex111** [comment]
This is actually because the GitHub theme changed in `prism-react-renderer` (see https://github.com/FormidableLabs/prism-react-renderer/issues/115 for more details).


However you can again return to previous syntax highlighting -- for this in `src` directory of your website you need to create new file (eg. `github.js`) with [the following content](https://github.com/krsntn/prism-react-renderer/blob/9455b42592f12430898bd0a78b9555631d878e27/src/themes/github.js) , and then in `prism` field of config file specify path to this file, something like that:

```js
prism: require.resolve('./src/github.js')
```

**Comment by stockiNail** [comment]
@Josh-Cena @lex111 THANK YOUU! Let me test it and then I'm gonna close the issue.

**Comment by Josh-Cena** [comment]
Interesting because the Docusaurus site is also broken 😅 We may need to fix that

**Comment by stockiNail** [comment]
> 
> 
> Interesting because the Docusaurus site is also broken 😅 We may need to fix that

yes, for this reason I thought it was an issue.

**Comment by stockiNail** [comment]
> ```js
> prism: require.resolve('./src/github.js')
> ```

Does not work.

**Comment by lex111** [comment]
Forgot to mention that you need to use the CommonJS format, so just copy-paste [this gist](https://gist.github.com/lex111/e5d79c2f0ff55ffc59dc439873cfbb7c) to make things work.

**Comment by stockiNail** [comment]
@lex111 I tested with last gist you gave me and it WORKS!!! Thank you!

Only 1 thing, to correct your post. The config is the following (asssuming to store github theme in `./src/github.js`):

```javascript
  prism: {
    additionalLanguages: ['java'],
    theme: require('./src/github.js'),
  },
```

**Comment by kebetsi** [comment]
You only need to add `additionalLanguages: ['java']` to `themeConfig:prism` with docusaurus v3.5.2. There is an entry `theme: prismThemes.github,` by default.
