### ISSUE TITLE
Title doesn't get parsed from the front matter

### ISSUE THREAD

**Issue by Mihonarium** [facebook/docusaurus#4852]
## 🐛 Bug Report

I have a markdown file:

```---
title: "Title1"
sidebar_label: "Title2"
hide_title: true
---

# Title3

text
```

The sidebar renders correctly, but the Next/Previous buttons show Title3 instead of Title1. The page itself doesn't show the title at all and starts with the text. 

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes.

## To Reproduce

https://codesandbox.io/s/friendly-elion-dwu3y?file=/docs/manage-docs-versions.md

## Expected behavior

I had alpha-69 before and it worked correctly there. The markdown # Title3 should be shown on the page, Title1 should be shown on the paginated navigation.

## Actual Behavior

On beta-0, the markdown # title is being shown on the paginated navigation instead of the title specified in the front matter. The markdown

**Comment by slorber** [comment]
@Mihonarium so what I understand is that you expect `hide_title: true` to not hide `# Title 3` right? (like it used to be a few months ago?)

**Comment by Mihonarium** [comment]
@slorber right. With `title: "Title1"` present, I expected `# Title3` to be displayed as a regular markdown and not parsed at all.

I think if you make the `hide_title: true` unnecessary (or default) when there are duplicate titles, it's better to give users the ability (e.g., using `hide_title: false`) to override this and display duplicate titles if they want this for some reason.

**Comment by slorber** [comment]
> I think if you make the hide_title: true unnecessary (or default) when there are duplicate titles, it's better to give users the ability (e.g., using hide_title: false) to override this and display duplicate titles if they want them for some reason.

Why do you think that, do you have an usecase to show duplicate titles, considering it's not really a good practice?

**Comment by slorber** [comment]
@Mihonarium according to our doc and this issue: https://github.com/facebook/docusaurus/issues/4929

`sidebar_label` is supposed to be used in priority for next/previous buttons over `title`, so we should display Title2 in next/previous buttons and not Title1 as you expect.

It make sense to me, as the navigation is tightly related to the sidebar, and it was the historical behavior we had before. So I'm going to restore this.

Is this a problem for you? In which case I can introduce a new frontmatter like `pagination_label` to have better decorrelation between sidebar label and pagination label

**Comment by Mihonarium** [comment]
@slorber Yes, something like `pagination_label` makes sense then. 

Though we need Title1 to be in both the HTML (tab) title and the pagination, so it also would be easier if there's a setting that allows changing the priority from `sidebar_label` to `title`.

**Comment by slorber** [comment]
@Mihonarium Title1 will now always be used in page metadata (tab title).

`sidebar_label` is optional so if you want Title1 in pagination you can just omit it.

`sidebar_label` is a better fit for pagination buttons because we have less width for both sidebar + pagination buttons and the `sidebar_label` is generally a shorter text compared to `title` which is a longer text used primarily for SEO purpose.

> it also would be easier if there's a setting that allows changing the priority from sidebar_label to title

We could introduce a lot of ways to change priority orders of a lot of things in Docusaurus but I think it would be very confusing to have such APIs and add noise for most users.

Can you explain with real-world labels (not Title1) of a concrete use-case why you want 
page meta title and pagination labels to be the same, and why sidebar label is not a good fit for pagination labels?

If there's a real need, I'd rather have a `pagination_label` frontmatter rather than a `pagination_label_priority: title`: it is simpler to understand and way more explicit.

**Comment by Mihonarium** [comment]
We definitely need different titles in the pagination buttons and the sidebar, though I agree a `pagination_label` would be simpler.

At our [music recognition API documentation](https://docs.audd.io/), we use the sidebar as a menu a user can look at without a context and decide where they want to go, and the pagination buttons mostly have less text because the user is already in the context when they look at it.

For [this page](https://docs.audd.io/enterprise), we display "Enterprise endpoint" as the pagination button and the HTML/tab `<title>`, "Music recognition for mixes, long audio and video files" as the sidebar title, and "API Docs for the enterprise endpoint" as the H1 title displayed in the markdown. So the sidebar titles are longer than the ones we display as the tab titles and the pagination.

It's hard for us to conduct SEO experiments since we already hold the 1,0 average position for the "Music recognition API" query on Google, but it seems like the current combination is working.

**Comment by slorber** [comment]
Thanks

Not sure to understand why you have so different labels in page meta, sidebar, markdown heading, and pagination buttons though 😅 

I'll add the `pagination_label` frontmatter for better flexibility, make sure to double-check everything when you upgrade to the next beta.1 release
