### ISSUE TITLE
the search bar from algolia is not shown

### ISSUE THREAD

**Issue by KostyaTretyak** [facebook/docusaurus#4853]
## 🐛 Bug Report

The search bar does not appear

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## To Reproduce

1. Install new docusaurus site (for now - 2.0.0-beta.0):

```bash
npx @docusaurus/init@latest init my-website classic
```

2. Set config for algolia

```text
module.exports = {
  // ...
  themeConfig: {
    // ...
    algolia: {
      apiKey: 'YOUR_API_KEY',
      indexName: 'YOUR_INDEX_NAME',

      // Optional: see doc section below
      contextualSearch: true,

      // Optional: see doc section below
      appId: 'YOUR_APP_ID',

      // Optional: Algolia search parameters
      searchParameters: {},

      //... other Algolia params
    },
  },
};
```

3. Start the website:

```bash
yarn start
```

## Expected behavior

The search bar is displayed

## Actual Behavior

The search bar is not displayed

## Your Environment

- Docusaurus version used: 2.0.0-beta.0
- Environment name and version: Chrome Version 90.0.4430.212 (Official Build) (64-bit)
- Operating system and version: Ubuntu 20.04

## Reproducible Demo

https://codesandbox.io/s/naughty-ritchie-bcokx?file=/docusaurus.config.js

**Comment by lex111** [comment]
Most likely you have previously run site without Algolia config, so for the search to work, you need to remove files of previous build by running `yarn clear` command.

**Comment by KostyaTretyak** [comment]
@lex111, thank you! This instruction must be included in the documentation.
