### ISSUE TITLE
Replace hard-coded links/text with siteConfig variables

### ISSUE THREAD

**Issue by Happy-Ferret** [facebook/Docusaurus#488]
### Is this a bug report?

No.

It's a PR proposal/RFC.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

### Environment

(OS, Node, npm, yarn)

**OS:** Windows 8.1
**Node:** v6.10.3
**npm:** 3.10.10

### Steps to Reproduce

1. Create new project utilizing ``docusaurus-init``.
2. Set siteConfig properties such as ``copyright:`` or `` baseUrl:``.
3. Serve docs.
4. Check content of footer and help.html.
5. (alternatively) Look inside files such as ``website/pages/en/help.js`` or ``website/core/footer.js`` (among others).

### Expected Behavior

Copyright inside footer and help link should be set to properties set in ``siteConfig.js``.

### Actual Behavior

Copyright inside footer and help link are set to hard-coded defaults inside ``website/pages/en/help.js`` and ``website/core/footer.js``.

### Proposal

Replace the hard-coded links and text blocks with variables accessing siteConfig (i e ``this.props.config.copyright``) by default.

This way new users won't be confused when the properties exposed in ``siteConfig.js`` aren't set on their personal builds.

**Comment by JoelMarcey** [comment]
I think I would actually consider this on the border of feature request and bug 😄 

Would you like to submit a PR for this?

**Comment by JoelMarcey** [comment]
@Happy-Ferret All right. I consider this issue claimed then 😄

**Comment by Happy-Ferret** [comment]
Unless there's something I haven't considered (code style? Additional occurrences of hard-coded values one could easily get rid of?), I'll create the PR later today.

**Comment by Happy-Ferret** [comment]
FYI. My current implementation replaces the editUrl inside ``users.html``, too.
Figured we could just base this on ``siteConfig.repoUrl`` + ``/edit/master/website/siteConfig.js``.

Although in the future it might make sense to modify the siteConfig API and retarget ``editUrl:`` so it can be applied to more than just docs (I'm thinking an array would be nice).
