### ISSUE TITLE
Feature: ability to customize docs next/previous pagination button labels

### ISSUE THREAD

**Issue by dirslashls** [facebook/docusaurus#4895]
## 🚀 Feature

When transitioning from one category to another, the "Previous" and "Next" boxes should show the category name as well.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## Motivation

I have several categories (folders) of docs and each of them start with "Introduction". On each page, there are "Previous" and "Next" sections at the bottom that only show the title of the doc page. This feels awkward to see "Introduction" in the middle of documentation. Instead "XYZ: Introduction" where XYZ is the category name would be helpful. I don't expect this for all pages and only when there is a transition from one category to another (for previous or next as appropriate).

## Pitch

It would be good to be able to notice that there is a transition of categories.

**Comment by slorber** [comment]
`XYZ: Introduction` wouldn't be a good fit for many use-cases

What I suggest instead is to add a frontmatter `pagination_label` (or `navigation_label`?) in the same way we have `sidebar_label`

---

A possibility is to use

```
title: "XYZ: Introduction"
sidebar_label: "Introduction"
```

This way you would have `XYZ: Introduction` in your pagination, without having a confusing sidebar.

We use this pattern on Docusaurus site itself: https://docusaurus.io/docs/api/plugins, see how the title and sidebar label is different. 

---

Note adding the ability to link a category to a doc is a feature request that we plan to implement soon (https://github.com/facebook/docusaurus/issues/2643). 

If you could have the XYZ category link to an intro doc, would you still need this feature?

**Comment by dirslashls** [comment]
Thanks @slorber for the workaround. I ended up doing what you suggested. Just have to make sure the title is small enough to fit into the pagination buttons. Yes, #2643 will also help for my case as each category can then directly point to an intro page. Look forward to that feature and closing this out.
