### ISSUE TITLE
SideBar hide Menu

### ISSUE THREAD

**Issue by anasoid** [facebook/docusaurus#4909]
### Description

Sidebar hide the header menu, and i can't click on logo any more.

The problem is reproduced only when working with generated website, when working with" npm start" the problem is not reproduced.

the link to live website is https://jmc.anasoid.org/docs/developers/intro

The repo is https://github.com/anasoid/jmc.anasoid.org

## To Reproduce
goto https://jmc.anasoid.org/docs/developers/intro and try to click logo

## Actual Behavior

A part of header is hidden by sidebar.

## Your Environment

- Public source code: https://github.com/anasoid/jmc.anasoid.org and local using "npm run serve" not reproduced with "npm start"
- Public site URL: https://jmc.anasoid.org/docs/developers/intro
- Docusaurus version used: 2.0.0-beta.0
- Environment name and version : Last Firefox 89.0, Lst chrome  91.0.4472.77, node 14
- Operating system and version : Ubuntu 20.04.2 LTS

## Github action deploy
```
  gh-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - uses: webfactory/ssh-agent@v0.5.2
        with:
          ssh-private-key: ${{ secrets.GH_PAGES_DEPLOY }}
          
      - name: Release to GitHub Pages
        env:
          USE_SSH: true
          GIT_USER: git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "gh-actions"
          if [ -e yarn.lock ]; then
            yarn install --frozen-lockfile
          elif [ -e package-lock.json ]; then
            npm ci
          else
            npm i
          fi
          echo "#################DEPLOY##########################"
            DEPLOYMENT_BRANCH=gh-pages yarn run deploy
```

**Comment by anasoid** [comment]
I resolve issue with this commit https://github.com/anasoid/jmc.anasoid.org/commit/75902218a8ab9e9d9c5bd9989b7a9d4f1374383b.

The problem was introduced by "npm audit fix ", i revert to original version.

I add image to see the original problem as will be corrected on live website

![image](https://user-images.githubusercontent.com/10306838/120870148-100a3900-c590-11eb-9200-0aa39b440f41.png)

**Comment by lex111** [comment]
This is due to a bug in cssnano (which already fixed), reinstalling website dependencies resolves the problem.
