### ISSUE TITLE
Gap between navbar and the top of the window (see through gap)

### ISSUE THREAD

**Issue by JayKaku** [facebook/docusaurus#4920]
![image](https://user-images.githubusercontent.com/61429929/121020870-6a88dc80-c7be-11eb-8596-7903ec82f6ab.png)

The same issue exits on [Hydra](https://hydra.cc/) website from where I actually found the bug

**Comment by slorber** [comment]
I don't see this, please report your full env config

**Comment by JayKaku** [comment]
Mind sending the screen grab in dark mode of the documentation with an image behind ?  Fyi my env is as follows: 
Windows 10 Version 21H1, Windows 10 Home Single Language OS, Chrome Version 91.0.4472.77, Microsoft Edge
Version 91.0.864.41
I've tried in private mode on both the browsers.

**Comment by lex111** [comment]
Couldn't reproduce this using Chrome 91/Edge 91 on Windows 10. Are you sure this isn't affected by some extensions or something else? Perhaps something is added to the site markup, this can be checked through dev tools (screenshot with this is highly appreciated). Could you please record video with reproduce this bug?

**Comment by JayKaku** [comment]
I'll try to find out what extension might cause it I checked the dev tools the moment I was the gap the css seemed proper, anyway I'll try with other method and get back asap

**Comment by JayKaku** [comment]
I checked with another machine it's perfect.
