### ISSUE TITLE
Deploy to Kubernetes

### ISSUE THREAD

**Issue by felipecrs** [facebook/docusaurus#4921]
## 📚 Documentation

I'm having a really bad time at trying to deploy a docusaurus built website to Kubernetes, especially when using some trickeries. I wrote a `Dockerfile` like:

```Dockerfile
FROM node:lts AS build
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm install
COPY . ./
RUN npm run build

FROM node:lts
COPY --from=build --chown=node:node /app /app
USER node
ENV PATH="/app/node_modules/.bin:$PATH"
CMD cd /app && \
    exec docusaurus serve --build --port 80 --host 0.0.0.0
```

With a `docusaurus.config.js` like so:

```js
module.exports = {
  url: process.env.TARGET_URL ?? "http://localhost/",
  baseUrl: process.env.PREFIX ?? "/"
}
```

My goal is to be able to customize the `url` and `baseUrl` fields, so I can adjust them properly depending on where I'm deploying using Helm and Ingress.

But it never works: 

![image](https://user-images.githubusercontent.com/29582865/121049354-01897080-c78e-11eb-8065-3e9f5382f26e.png)

I even tried https://github.com/facebook/docusaurus/issues/3291#issuecomment-674929740 through:

```Dockerfile
CMD cd /app && \
    set -x && \
    exec docusaurus serve --dir "build/$(basename "${PREFIX}")" --build --port 80 --host 0.0.0.0
```

Which produces an output like so:

![image](https://user-images.githubusercontent.com/29582865/121049586-35649600-c78e-11eb-9a9d-c30f3bfcdf8b.png)

(disregard the port 81/80 mapping. I'm running in a SSH server and I'm forwarding the port 80 to my host's 81).

But the result is the same when I browse http://localhost:81/ui: 

![image](https://user-images.githubusercontent.com/29582865/121050154-b9b71900-c78e-11eb-8122-bfbc6068c248.png)

Once I can finally get this working, I can happily submit a PR for enhancing the docs. :)

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes.

**Comment by felipecrs** [comment]
Ok, I figured out what's wrong. The following works:

```Dockerfile
CMD set -x && \
    cd /app && \
    docusaurus build && \
    if [ -n "$PREFIX" ]; then \
        mv -f build build.old && \
        mkdir -p build && \
        mv -f build.old "build/$PREFIX"; \
    fi && \
    exec docusaurus serve --port 80 --host 0.0.0.0
```

But probably it would be better to fix the `serve` command to respect the `baseUrl` field.

**Comment by slorber** [comment]
Afaik the simple http server we use for serve does not provide any option to respect the baseUrl. If you want it to be served from `/baseUrl/`, yu have to put the static files in `website/build/baseUrl` somehow.

Related to https://github.com/facebook/docusaurus/issues/3291
There's probably a solution to make it support the baseUrl but it's not yet implemented

**Comment by lex111** [comment]
Closing since serve command now respects the base URL (see https://github.com/facebook/docusaurus/pull/4924).
