### ISSUE TITLE
Canonical/Alternate/og:url incorrect in docs-only mode with custom baseUrl

### ISSUE THREAD

**Issue by joe-bell** [facebook/docusaurus#4925]
### Prerequisites

- [x] I'm using the latest version of Docusaurus.
- [x] I have tried the `npm run clear` or `yarn clear` command.
- [x] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.

### Description

When using docs-only mode with a custom `baseUrl` the `canonical`/`alternate`/`og:url` paths are incorrect

```js
// docusarus.config.js
module.exports = {
  baseUrl: '/docs/',
  presets: [
    [
      "@docusaurus/preset-classic",
      {
        docs: {
          path: "docs",
          routeBasePath: "/",
        },
        blog: false,
      },
    ],
  ],
}
```

_returns_

```html
<head>
    <!--...other tags-->
    <link rel="canonical" href="<domain>/docs/docs/strategies" data-react-helmet="true">
    <link rel="alternate" href="<domain>/docs/docs/strategies" hreflang="en" data-react-helmet="true">
    <link rel="alternate" href="<domain>/docs/docs/strategies" hreflang="x-default" data-react-helmet="true">. 
    <meta property="og:url" content="<domain>/docs/docs/strategies" data-react-helmet="true">
    <!--...other tags-->
</head>
```

_despite_ all other baseUrl features working as expected.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## To Reproduce

Follow the configuration provided above.

## Expected behavior

Canonical/Alternate/og:url paths should be `<domain>/docs/*`

## Actual Behavior

Canonical/Alternate/og:url paths are `<domain>/docs/docs/*`

## Your Environment

- Public source code: N/A
- Public site URL: N/A
- Docusaurus version used: 2.0.0-beta.0
- Environment name and version (e.g. Chrome 78.0.3904.108, Node.js 10.17.0): N/A
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): N/A

## Reproducible Demo

See above configuration

**Comment by lex111** [comment]
I can't reproduce this bug, I created demo site with the configuration specified in this issue, but all meta tags have correct values (`<domain>/docs/*`) -> https://codesandbox.io/s/runtime-sky-wyiz5?file=/docusaurus.config.js
Can you provide reproducible repo?

**Comment by joe-bell** [comment]
Ah! So the `url` doesn't have to contain the `baseUrl`

Turns out the issue was my own fault...

```js
// docusarus.config.js
module.exports = {
  // just need to remove /docs
  url: '<domain>/docs'
  baseUrl: '/docs/',
}
```

Thanks @lex111 - your reproduction helped me a great deal to diagnose this

**Comment by slorber** [comment]
We'll now emit a warning when using a subpath in url (https://github.com/facebook/docusaurus/pull/4977)
