### ISSUE TITLE
iOS 15 Safari URL bar covers floating secondary nav button

### ISSUE THREAD

**Issue by jaredpalmer** [facebook/docusaurus#4927]

**Comment by lex111** [comment]
Actually, we will be completely change the mobile menu UI soon, after that floating button will be removed (see https://github.com/facebook/docusaurus/pull/4273#issuecomment-841811456 for GIF demo).

**Comment by slorber** [comment]
Can someone show a screenshot of this problem? 

Is this the kind of problem we have?

![image](https://user-images.githubusercontent.com/749374/121337206-94581580-c91c-11eb-8ad3-e017efa4305e.png)

**Comment by JonnyBurger** [comment]
Here's an image

![image](https://user-images.githubusercontent.com/1629785/122032939-623d2c80-cdd0-11eb-855f-438504b0ac15.png)

but it's not a dealbreaker as when you scroll, the scrollbar moves out of the way and it becomes visible again

![image](https://user-images.githubusercontent.com/1629785/122033124-8862cc80-cdd0-11eb-85ef-a3b331d73e7d.png)

**Comment by slorber** [comment]
Can someone confirm if it works for this PR? https://github.com/facebook/docusaurus/pull/4912

Preview to check: https://deploy-preview-4912--docusaurus-2.netlify.app/docs/

Unfortunately can't check that with Browserstack apparently...
