### ISSUE TITLE
Allow <AUTOGENERATED_TABLE_OF_CONTENTS> for h2 headings too

### ISSUE THREAD

**Issue by SleepWalker** [facebook/Docusaurus#493]
Currently if we want to have contents on top of document, we need to use `<AUTOGENERATED_TABLE_OF_CONTENTS>`. This tag works only with h3 headings and forces us to use backticks to mark the headers, we want to see in contents.

This format is very suitable for API-only docs where you have no hierarchy. But when you want contents for e.g. guide page where you have many sections and subsections you will have very few options for section formatting available:

[screenshot](https://user-images.githubusercontent.com/2536916/37254913-833e8dcc-254d-11e8-9c37-21e5f4448837.png)

New feature should:

* provide multi-level table of contents view
* allow to include h2 headings in link list (and, probably h4 too, but I'm not sure)

This feature may be implemented in two ways:

* we can extend current content view to look for h2 headings too
* we can create an alternative <AUTOGENERATED...> tag with completely different logic

As for me — I like the feature with backticks, which allows me to mark exactly what headings I want to have in table of contents. So I'd go the first way and extend current view with new multi-level layout of table of contents.

### Is this a bug report?

No

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

### Environment

N/A

### Steps to Reproduce

N/A

### Expected Behavior

N/A

### Actual Behavior

N/A

### Reproducible Demo

N/A

**Comment by SleepWalker** [comment]
Looks like `1.0.8` includes the thing I need: On page navigation sidebar. So I closing this issue

**Comment by JoelMarcey** [comment]
@SleepWalker I am glad the new feature may resolve the issue for you.
