### ISSUE TITLE
Versions dropdown is empty on mobile when there's only one version and "Next" option is disabled

### ISSUE THREAD

**Issue by Genarito** [facebook/docusaurus#4932]
### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.

### Description

I started a new project where I want to show a _Versions_ dropdown in the navbar but I don't want to show _Next_ option. So, I created my version, disabled the _Next_ option, and realized that on small screens the _Versions_ dropdown is empty (images below).

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes, I have.

## To Reproduce

1. Start a new project with `npx @docusaurus/init@latest init version-bug classic`
1. Create a new version with `yarn run docusaurus docs:version 1.1.0`
1. Add a _Versions_ dropdown to navbar in `docusaurus.config.js`:
```javascript
 navbar: {
      // ...
      items: [
        {
          type: 'docsVersionDropdown',
          position: 'right'
        }
      ],
    },
```
4. Remove _Next_ option in `docusaurus.config.js`:
```javascript
presets: [
    [
      '@docusaurus/preset-classic',
      {
        docs: {
          // ...
          /**
           * Skip the next release docs when versioning is enabled.
           * This will not generate HTML files in the production build for documents
           * in `/docs/next` directory, only versioned docs.
           */
          includeCurrentVersion: false,
        },
      // ...
      },
    ],
  ],
```

**Images**: [on desktop](https://imgur.com/c7YeSUX) (correct) | [on mobile](https://imgur.com/0WtOtpP) (wrong)

## Expected behavior

It should show a dropdown with the available version on small screens (mobile).

## Actual Behavior

It's showing an empty version dropdown on small screens.

## Your Environment

- Public source code: https://github.com/Genarito/docusaurus-bug
- Public site URL: https://cranky-williams-b18b20.netlify.app/
- Docusaurus version used: 2.0.0-beta.0
- Environment name and version (e.g. Chrome 78.0.3904.108, Node.js 10.17.0): all
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): -

## Reproducible Demo

There is a repo with all these changes done. You can found it [here](https://github.com/Genarito/docusaurus-bug)
Public site: https://cranky-williams-b18b20.netlify.app/

**Comment by slorber** [comment]
Hi

Understand that problem. 

Does it make sense to show a dropdwon when there is only one version?
Afaik the Desktop only shows a button, not a dropdown in this case, and it looks better to me.

Isn't the problem that we display "Versions" instead of a "1.0.0" button on mobile?

**Comment by Genarito** [comment]
Hi @slorber, 

Yes, you're right, the problem is that the version is not accessible from mobile. I agree that, when there is only one version, a button instead of a dropdown is more propitious

**Comment by slorber** [comment]
Fixed in: https://github.com/facebook/docusaurus/pull/4986

Please test it using the `@canary` npm dist tag once it's merged

**single version:**

![image](https://user-images.githubusercontent.com/749374/122208731-f926e900-cea3-11eb-9ff4-b6d8926cf4d9.png)

![image](https://user-images.githubusercontent.com/749374/122208716-ef9d8100-cea3-11eb-91e3-fee13ec16e85.png)

**multiple version:**

![image](https://user-images.githubusercontent.com/749374/122208902-32f7ef80-cea4-11eb-8c25-f3cd1c4d8732.png)

![image](https://user-images.githubusercontent.com/749374/122208951-3db28480-cea4-11eb-9fd5-040ae34e2e3d.png)

**Comment by Genarito** [comment]
Works perfectly! Thank you!
