### ISSUE TITLE
Footer content aligned slightly off compared to docs content (mobile viewport)

### ISSUE THREAD

**Issue by HonkingGoose** [facebook/docusaurus#4946]
### Prerequisites

- [x] I'm using the latest version of Docusaurus.
- [x] I have tried the `npm run clear` or `yarn clear` command.
- [x] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.

### Description

Items in footer are misaligned compared to main document content on mobile viewport width.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes.

## To Reproduce

1. Go to https://docusaurus.io/docs/
2. Open your browser development tools and go to the responsive design tool
3. Pick iPhone 6/7/8 mobile preview (Size of viewport: 375x667)
4. Scroll down to the footer (the black part of the bottom of the page)
5. See footer items not aligned on the same "vertical line" as the documentation content

## Expected behavior

Footer items aligned on the same "vertical line" as the docs content.

## Actual Behavior

Screenshot of the 375x667 viewport:

![375_by_667_viewport_mobile_firefox](https://user-images.githubusercontent.com/34918129/121584265-98298c00-ca31-11eb-97cd-448f258c98dd.png)

## Your Environment

- Public source code: Problem is with Docusaurus' own website code
- Public site URL: https://docusaurus.io/docs/
- Docusaurus version used: I think you deploy from the `master` branch?
- Environment name and version (e.g. Chrome 78.0.3904.108, Node.js 10.17.0): Firefox 89.0
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): Windows 10

## Reproducible Demo

See steps to reproduce.

**Comment by lex111** [comment]
Will be fixed in #4945 

![image](https://user-images.githubusercontent.com/4408379/121638769-30f0f380-ca94-11eb-90b2-064bad96787a.png)

**Comment by HonkingGoose** [comment]
@lex111 That was quick! Thank you! 😄
