### ISSUE TITLE
Sidebar Category Title / Non-collapsable primary categories.

### ISSUE THREAD

**Issue by Yorkemartin** [facebook/docusaurus#4966]
## 🚀 Feature

I'd love to see a title or non collapsable category for sidebar items, in the style that gitbook does https://docs.gitbook.com/

This helps break up ideas without removing all context. And it just looks cleaner than having dropdown arrows pointing all over the place in a non collapsed landing page

**Comment by slorber** [comment]
You can already make sidebar categories non-collapsible:
https://docusaurus.io/docs/sidebar#collapsible-categories

**Comment by Yorkemartin** [comment]
This feature makes every category non-collapsable. The feature I'm talking about makes only the top-level directory non-collapsible, so the user can see a few collapsed categories inside of several top-level directories 

In the below picture, the "Guides" "Reference" and "Concepts" sections would be non-collapsable, while the internal directories would be collapsed. 

<img width="248" alt="Screen Shot 2021-06-15 at 9 56 27 AM" src="https://user-images.githubusercontent.com/5619220/122085457-f5ba3180-cdbf-11eb-8fa2-3ccecd5409b5.png">

**Comment by slorber** [comment]
I see, so using a sidebar category.collapsible = false attribute make sense to override the default global setting with more granularity?

**Comment by Yorkemartin** [comment]
Exactly, I think it helps communicate the context of the top-level categories without adding too much visual complexity

**Comment by Josh-Cena** [comment]
@Yorkemartin I implemented this with #5203. Do you think it would be necessary for us to also have a "category title" item, just like in gitbook, or is a non-collapsable category good enough?
