### ISSUE TITLE
Unversioned docs are broken when setting the versioned default docs `routeBasePath` to root

### ISSUE THREAD

**Issue by rexwangcc** [facebook/docusaurus#4967]
### Prerequisites

- [x] I'm using the latest version of Docusaurus.
- [x] I have tried the `npm run clear` or `yarn clear` command.
- [x] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.

### Description

The documentation [here](https://docusaurus.io/docs/docs-multi-instance#versioned-and-unversioned-doc) mentioned that:

```
Sometimes, you want some documents to be versioned, while other documents are more "global", and it feels useless to version them.

We use this pattern on the Docusaurus website itself:

The /docs/* section is versioned
The /community/* section is unversioned
```

However, when I turn on the `docs-only` mode, i.e. set `routeBasePath` to `/` for my default docs, the unversioned docs starts to return `Page Not Found`.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yup

## To Reproduce

I was able to reproduce it with the docusaurus docs website too:

1. Clone the official docusaurus repo and `yarn install ` and `cd website && yarn start`
2. Make sure the `community` docs are accessible.
3. Update `docusaurus.config.js` to:
```diff
{
        debug: true, // force debug plugin usage
        docs: {
-         // routeBasePath: '/',
+          routeBasePath: '/',
          path: 'docs',
          sidebarPath: 'sidebars.js',
...
```
4. Add a `slug: /` frontmatter to any of the docs page under docs.
5. Now if you try to visit the `community` docs, it returns 404.

## Expected behavior

With the `docs-only` mode, unversioned docs should work too.

## Actual Behavior

With the `docs-only` mode, unversioned docs returns 404.

## Your Environment

- Public source code:
- Public site URL:
- Docusaurus version used: latest `master` branch of docusaurus repo
- Environment name and version (e.g. Chrome 78.0.3904.108, Node.js 10.17.0): `yarn 1.22.10`, `node v16.1.0`
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): macOS 10.15.7

## Reproducible Demo

If possible, use https://new.docusaurus.io to create a CodeSandbox reproducible demo of the bug.

(Paste the link to an example repo, including a `docusaurus.config.js`, and exact instructions to reproduce the issue.)

**Comment by rexwangcc** [comment]
I realized this is indeed a "duplicate" of https://github.com/facebook/docusaurus/issues/3810, but since the later is not resolved for a few months, I would keep it open for now and feel free to close this and move the discusssion to the other one.

**Comment by slorber** [comment]
> swapping didn't work for me

It should solve it.
Please show me your config and also your `.docusaurus/routes.js` generated file

**Comment by slorber** [comment]
As someone else reported swapping didn't work on the original issue, I think we can close this one and continue this discussion on the other issue. Still interested to have your config and routes file

**Comment by rexwangcc** [comment]
Sorry for the delayed reply, I'm going to comment on the other issue!
