### ISSUE TITLE
Navbar dropdown items should support type "doc"

### ISSUE THREAD

**Issue by fantua** [facebook/docusaurus#4996]
## 🚀 Feature
Relates to #4972 

```js
items: [
  {
    label: 'Flows',
    position: 'left',
    items: [
      {
        label: 'Library Flow',
        to: 'docs/library-flow/overview'
      },
    ],
  },
```
When navigating in previous version docs click on `Library Flow` switches to the latest docs. As a result, we lose the "version context". 

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## Motivation

Having versioned dropdown subitems could provide better users experience and improve navigation (not loosing version context)

## API Design

```js
items: [
  {
    label: 'Flows',
    position: 'left',
    items: [
      {
        type: 'doc',
        label: 'Library Flow',
        docId: 'app-flow',
      },
    ],
  },
```

Possible solution will be to use [getNavbarItemComponent](https://github.com/facebook/docusaurus/blob/073fdeae8eea3cf13e27fcc7f0a9fe5265fad84c/packages/docusaurus-theme-classic/src/theme/NavbarItem/index.tsx#L32) here:
https://github.com/facebook/docusaurus/blob/073fdeae8eea3cf13e27fcc7f0a9fe5265fad84c/packages/docusaurus-theme-classic/src/theme/NavbarItem/DefaultNavbarItem.tsx#L122-L129

## Have you tried building it?

No

**Comment by slorber** [comment]
Thanks, seems reasonable to support this (as well as all future navbar items that are simple links)

**Comment by felipecrs** [comment]
In my case, I would like to use a drop-down menu for different docs instances, like:

```js
items: [
        {
          label: "Docs",
          position: "left",
          items: [
            {
              type: "doc",
              docId: "index",
              label: "Repo A",
            },
            {
              type: "doc",
              docId: "index",
              docsPluginId: "repo-b",
              label: "repo-b",
            },
          ],
        },
        { to: "/blog", label: "Blog", position: "left" }
]
```

I'm not sure, is it included in this feature request?

**Comment by slorber** [comment]
@felipecrs `docsPluginId ` is supported by the doc type, so it will be supported as part of the current feature request
