### ISSUE TITLE
i18n multi locales

### ISSUE THREAD

**Issue by konabuta** [facebook/docusaurus#4998]
## 📚 Documentation

In [i18n tutorial document](https://docusaurus.io/docs/i18n/tutorial#start-your-site), it says
> Each locale is a distinct standalone single-page-application: it is not possible to start the Docusaurus sites in all locales at the same time.

I tried to build multi locale page and works in my github pages using `GIT_USER=<GITHUB_USERNAME> yarn deploy`.

Is it expected ?

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

(Write your answer here.)

**Comment by Josh-Cena** [comment]
You can only start your development server in one locale (with `yarn start`), but building would build for all the locales (with `yarn build`). I18n would be pretty useless if you can only ship one locale...

**Comment by slorber** [comment]
Yes, only `yarn start` has that limitation, but prod can definitively deploy all locales. 

If you feel we can clarify that in doc please open a doc PR
