### ISSUE TITLE
Any plan to support copy the example code?

### ISSUE THREAD

**Issue by wulucxy** [facebook/Docusaurus#500]
### Is this a bug report?

no, this is a feature?

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

![_abd5a8ee-21e1-4992-b9f1-cdba20413c47 1](https://user-images.githubusercontent.com/5326403/37351341-cea020f4-2715-11e8-8f2e-6d1e6ec4c434.png)

[Ant.d](https://ant.design/components/alert-cn/) is a high quality React component library, one of it's feature is you can copy the example code in the doc, like what shows above.

So，do you have any plan to get this done?

**Comment by yangshun** [comment]
This sounds useful! The new Babel site (https://new.babeljs.io/docs/en/learn) uses Docusaurus and has these copy buttons. We can see how it's done there.

**Comment by amyrlam** [comment]
👋Hi, I'd like to claim this issue!

**Comment by yangshun** [comment]
@amyrlam It's yours! 🎉

**Comment by yangshun** [comment]
@amyrlam In the current state, it's a bit hard to support adding it for Docusaurus users. Let's just add the copy functionality to Docusaurus 👍

**Comment by endiliey** [comment]
Closing due to stale activity. For anyone who wanted this. see

https://docusaurus.io/docs/en/doc-markdown#adding-copy-code-buttons
