### ISSUE TITLE
Docusaurus 2.0.0-beta.0, dynamic imports using backticks not working

### ISSUE THREAD

**Issue by goceee** [facebook/docusaurus#5008]
I recently installed the docusaurus starter project using `npx @docusaurus/init@latest init my-website classic` and i tried using dynamic imports with the loadable/component package using backticks to dynamically import different SVG files, but it is not working, when I add a static path without backticks it works.

I have the latest node and docusaurus. I also tried creating a repro with https://new.docusaurus.io and the same issue appears. 

Can anyone help with this?

Any suggestion is appreciated.

Thank you.

**Comment by slorber** [comment]
Hi

Please respect the issue template

> I also tried creating a repro with https://new.docusaurus.io and the same issue appears.

Then why not post the link to the sandbox repro
