### ISSUE TITLE
Past version warning is too restrictive

### ISSUE THREAD

**Issue by Yorkemartin** [facebook/docusaurus#5010]
Past version warning should be configurable. The protocol I am building docs for are immutable smart contracts deployed on ethereum, so calling them "maintained" or not will confuse users. I imagine others feel similarly - such as the comment below

Would it be also possible to allow disabling or customizing the banner of past versions?

![Capture d’écran 2020-12-16 à 16 01 16](https://user-images.githubusercontent.com/13604533/102365585-ff511100-3fb7-11eb-9249-9c72b78e9eaa.png)

The current message hints that past versions are not maintained anymore which can be wrong. In the case of FoalTS, past versions have a lifetime during which bugs and security holes are fixed even if no new features are added.

I currently use this (hacky) workaround:
```css
.alert.alert--warning.margin-bottom--md {
  display: none;
}
```

_Originally posted by @LoicPoullain in https://github.com/facebook/docusaurus/issues/3013#issuecomment-746441264_

**Comment by slorber** [comment]
agree we should make this configurable (it's not for now)

duplicate of https://github.com/facebook/docusaurus/issues/3013
