### ISSUE TITLE
Anchor links across pages are failing

### ISSUE THREAD

**Issue by teikjun** [facebook/docusaurus#5020]
### Prerequisites
- [x] I'm using the latest version of Docusaurus.
- [x] I have tried the `npm run clear` or `yarn clear` command.
- [x] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [x] I have tried creating a repro with https://new.docusaurus.io
- [x] I have read the console error message carefully (if applicable)

### Description

Anchor links that target headers in other pages are failing. Instead of sending users to the target header, users are sent to the top of the page.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## Steps to reproduce

1. Go to this link: https://docusaurus.io/docs/using-themes#writing-customized-docusaurus-themes
2. Click on `getThemePath()`
<img width="211" alt="image" src="https://user-images.githubusercontent.com/46853051/122680826-dbe77700-d223-11eb-85bb-679257da6da7.png">

## Expected behavior
Expected to go to the target header

## Actual behavior
Get sent to the top of the page
<img width="748" alt="image" src="https://user-images.githubusercontent.com/46853051/122680896-2a951100-d224-11eb-965e-736c3b9754fd.png">

## Your environment
- Docusaurus version used: 2.0.0-beta.1
- Environment name and version (e.g. Chrome 78.0.3904.108, Node.js 10.17.0): Firefox 89, Chrome 91

### Demo 1
1. Go to https://deploy-preview-4797--docusaurus-2.netlify.app/docs/using-themes#writing-customized-docusaurus-themes
2. Click on the `getThemePath()` link
### Demo 2
1. Go to https://deploy-preview-4811--docusaurus-2.netlify.app/docs/deployment#self-hosting
2. Click on the `docusaurus serve` link

## Root Causes
There are 2 root causes here - they correspond to the 2 demos above. 

### Root cause for Demo 1
PR #4797 is the earliest PR that has the bug, so I believe it is the root cause of the regression. Adding back the `!hash` condition (as shown below) resolves this bug, but I'm not sure if this is the right approach.

<img width="450" alt="image" src="https://user-images.githubusercontent.com/46853051/122682374-7b5c3800-d22b-11eb-9fb7-0a71e0f21be6.png">
@lex111 @slorber, could I get your advice on this? 🙏

### Root cause for Demo 2
Demo 2 is the state before PR #4797 was merged. Certain anchor links still fail. This is due to incorrect anchor link specified on the user side. I will open a PR to resolve this.

**Comment by lex111** [comment]
@teikjun thanks for the report, yes, you're right, we should ignore hash changes in that hook, my bad, will be fixed in #5023.
