### ISSUE TITLE
npm vulnerability notices

### ISSUE THREAD

**Issue by dbi1** [facebook/docusaurus#5051]
Hello,

npm warns of a pretty long list of vulnerable dependencies after it finishes installing docusaurus.

`npm audit fix ` does not solve the issue.

I'm using node version 14.17.1.

Is there a solution to this problem?

Thank you very much.

**Comment by slorber** [comment]
It's not always easy to have a clean empty list of npm audit vulnerabilities. 
New vulnerabilities are discovered regularly, and we can't always upgrade dependencies as easily as we want.
All vulnerabilities do not have the same level of risk for Docusaurus. Some of them are not affecting Docusaurus in practice and not worth fixing.

If you have a particular vulnerability that you think affects Docusaurus and could be a risk, please tell which vulnerability exactly and we'll see the potential impact it can have and try to fix it.

Note: if you discover a vulnerability in Docusaurus, FB has a bounty program: https://github.com/facebook/docusaurus/security/policy

I don't think it's worth opening an issue every time the npm audit log reports new vulnerabilities, as there always will be. Please let's discuss concrete vulnerabilities instead.
