### ISSUE TITLE
Document how to update docusaurus

### ISSUE THREAD

**Issue by JoelMarcey** [facebook/Docusaurus#506]
### Is this a bug report?

No. Documentation addition.

We want to explain:

`npm update`

and

`npm list docusuarus` to tell folks what version they currently have.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

### Environment

Docusaurus 1.0.9

### Steps to Reproduce

N/A

### Expected Behavior

N/A

### Actual Behavior

N/A

### Reproducible Demo

N/A

**Comment by longility** [comment]
I prefer `yarn outdated' and `yarn upgrade --latest'. What are your thoughts?

**Comment by JoelMarcey** [comment]
@longility Hi! I did document this here: https://docusaurus.io/docs/en/installation.html

If you want to send a PR with your suggestions, I would be willing to have a look.

**Comment by JoelMarcey** [comment]
Closing as this is documented - although we may consider changing it.
