### ISSUE TITLE
Sidebar disappear in mobile 2.0.0-beta.2

### ISSUE THREAD

**Issue by steelywing** [facebook/docusaurus#5060]
The sidebar is disappeared in mobile, version 2.0.0-beta.2. (See https://docusaurus.io/docs)

![image](https://user-images.githubusercontent.com/2720049/123401120-0dbc5d00-d5d9-11eb-97ef-d57d240b1609.png)

![image](https://user-images.githubusercontent.com/2720049/123401353-452b0980-d5d9-11eb-8fdc-caaab74d7bb0.png)

**Comment by slorber** [comment]
Thanks, we'll release this very soon in beta.3

**Comment by amino19** [comment]
@slorber : Can I take this issue to my end? (if assign)

**Comment by slorber** [comment]
Already fixed in master sorry
