### ISSUE TITLE
Scroll position is lost when navigating the page (Chrome)

### ISSUE THREAD

**Issue by Andrew-web-coder** [facebook/docusaurus#5076]
## Steps to reproduce

1. Step - Go to https://docusaurus.io/docs/2.0.0-beta.1/docs-introduction and scroll down half a page
1. Step - Click on the next docs in the sidebar, for example, https://docusaurus.io/docs/2.0.0-beta.1/create-doc and scroll down
1. Step - Click "Back" button, previous page will load, but it jump to the top.

## Expected behavior

Scroll position should stay the same. It works fine on FF.

## Actual behavior

Page suddenly jumps to the top. It worked fine before beta release.

**Comment by slorber** [comment]
Thanks for reporting

> It worked fine before beta release.

In which release did it work the last time for you?

**Comment by Andrew-web-coder** [comment]
I think I noticed this issue after upgrading from the last alpha to the latest.
