### ISSUE TITLE
Running Swizzle for all doesn't work

### ISSUE THREAD

**Issue by tjperry07** [facebook/docusaurus#5083]
### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io - Not able to run command on Code Sandbox.
- [X] I have read the console error message carefully (if applicable)

### Description
When running the command `npm run swizzle @docusaurus/theme-classic` it returns an error message.

```
> docusaurus swizzle "@docusaurus/theme-classic"

No component to swizzle.
```

This should be possible according to the docs.

<img width="855" alt="Screen Shot 2021-06-29 at 8 12 54 AM" src="https://user-images.githubusercontent.com/5667652/123803995-6da15500-d8b2-11eb-88bb-2d9d15542d96.png">

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## Steps to reproduce

1. Run `npm run swizzle @docusaurus/theme-classic`

## Expected behavior

All available components would be swizzled into src/theme.

## Actual behavior

Returned an error message in the console. 

```
> docusaurus swizzle "@docusaurus/theme-classic"

No component to swizzle.
```

## Your environment

- Docusaurus version used:  2.0.0-beta.2
- Environment name and version (e.g. Chrome 78.0.3904.108, Node.js 10.17.0):  Node v12.18.3
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): Mac OS BigSur 11.4

**Comment by slorber** [comment]
It works for me and others

Make sure you run this command in the site dir

Please provide a repro repo, or make sure you can reproduce on a newly initialized Docusaurus site

> All available components would be swizzled into src/theme.

This is not the expected behavior: we print a list of components available for swizzling:

![image](https://user-images.githubusercontent.com/749374/123808194-d0b1dc80-d8f0-11eb-9465-e0fa117cc010.png)

**Comment by Josh-Cena** [comment]
@slorber The "others" doesn't include me unfortunately :(

![image](https://user-images.githubusercontent.com/55398995/123808841-af1e1880-d923-11eb-8353-e9393c238f7d.png)

**Comment by slorber** [comment]
Ok I can reproduce.

Can you confirm that at least this command works for you?

`npm run swizzle @docusaurus/theme-classic Footer`

**Comment by Josh-Cena** [comment]
> Can you confirm that at least this command works for you?

> `npm run swizzle @docusaurus/theme-classic Footer`

Yes this one does

**Comment by slorber** [comment]
This should fix it: https://github.com/facebook/docusaurus/pull/5095

Please test this with canary https://docusaurus.io/community/canary and let me know if it does not work.
