### ISSUE TITLE
Freeze of page after navigating to any other page from the first page in beta2

### ISSUE THREAD

**Issue by achimnol** [facebook/docusaurus#5089]
I got a "freeze" of the webpage after navigating to any other page from the first page in beta2. The first page itself is fine.
Reproduced in Safari, Chrome, Firefox + `yarn serve` and `yarn start`. (even before deploying to netlify and/or applying any webserver-specific configs)
My website is a just simple single-page blog site with the default theme.
Downgrading to beta0 with resetting `node_modules` has resolved the issue.

Firefox has shown a warning that "this webpage is slowing down your computer" and a JS console log that says "maximum update depth exceeded" with the following log:
```
Warning: Maximum update depth exceeded. This can happen when a component calls setState inside useEffect, but useEffect either doesn't have a dependency array, or one of the dependencies changes on every render.
    in DocsPreferredVersionContextProviderUnsafe (created by DocsPreferredVersionContextProvider)
    in DocsPreferredVersionContextProvider (created by LayoutProviders)
    in UserPreferencesProvider (created by LayoutProviders)
    in AnnouncementBarProvider (created by LayoutProviders)
    in ThemeProvider (created by LayoutProviders)
    in LayoutProviders (created by Layout)
    in Layout (created by BlogListPage)
    in BlogListPage (created by LoadableComponent)
    in LoadableComponent (created by Context.Consumer)
    in Route (created by App)
    in Switch (created by App)
    in Route (created by PendingNavigation)
    in PendingNavigation (created by Context.Consumer)
    in withRouter(PendingNavigation) (created by App)
    in Root (created by App)
    in App
    in Router (created by BrowserRouter)
    in BrowserRouter 198 index.js:1
```
![image](https://user-images.githubusercontent.com/555156/123532610-c73a4000-d749-11eb-8646-6fda50c65b81.png)

_Originally posted by @achimnol in https://github.com/facebook/docusaurus/issues/5055#issuecomment-869097559_

**Comment by achimnol** [comment]
I'm using i18n (ko, en) and the blog plugin. Unfortunately the repository is not public since this is a company blog.

**Comment by slorber** [comment]
@achimnol is there a way to see the real blog live? 

I'm also ok to be granted access on the source (if possible)

Can you create a smaller repro by removing sensitive parts that your company can't share with me?

Can you send me a zip of the site built that fails? (or host it anywhere like Netlify?)

I need to see this error myself to be able to debug it more easily, the stack trace is not really helpful here unfortunately.

Can I see the config? 

You use blog only, no docs?

Are you using an announcement bar?

Have you swizzled any component? (what if you delete all of them?)

**Comment by slorber** [comment]
Hopefully was able to figure this out ;)

https://github.com/facebook/docusaurus/pull/5097

Let me know if this works (test with https://docusaurus.io/community/canary)
