### ISSUE TITLE
Document deployment to Azure Static Websites

### ISSUE THREAD

**Issue by patrickCode** [facebook/docusaurus#5091]
## 📚 Documentation

Azure static websites is one of the ideal places to deploy and host a Docusaurus site. The steps for doing so should be mentioned in the Deployment section of the docs.

I recently deployment our docusaurus site to Azure Static Websites, if this repo is taking contributions, I can raise a Pull Request.

**Comment by slorber** [comment]
The goal of our doc is not to be exhaustive about all the tools that can be used alongside Docusaurus.

If we add such section in our doc, will you still be there in 2 years to maintain it, or will it become stale and will our users open issue about it? 

I'm ok to add a section about azure static websites, but from now on we'd rather only add very small details and link to the official documentation, which is much more likely to be stay up-to-date.

Docusaurus is not more complicated to deploy than any other SSG so the official doc should be fine.

In my experience, the Azure platform is not the most straightforward one in term of UX compared to alternatives like Netlify.

Happy to have a PR, but mostly linking to the official doc instead
