### ISSUE TITLE
Performance issues when expanding and collapsing the lists

### ISSUE THREAD

**Issue by gearcoded** [facebook/docusaurus#5099]
### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [x] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [] I have tried creating a repro with https://new.docusaurus.io
- [] I have read the console error message carefully (if applicable)

### Description

When we collapse or expand the lists, it is processed with a slow speed.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes.

## Steps to reproduce

1. Open the link:
https://docs.dhtmlx.com/suite/
2. Try collapsing and expanding the entries in the left menu.
3. It is done with a slow speed.

## Expected behavior

The entries should be expanded and collapsed with a higher speed.

## Actual behavior

The entries are expanded and collapsed with a slower speed.

## Your environment

- Public source code:
https://github.com/DHTMLX/docs-suite
- Public site URL:
https://docs.dhtmlx.com/suite/
- Docusaurus version used:
2.0
- Environment name and version (e.g. Chrome 78.0.3904.108, Node.js 10.17.0):
91.0.4472.106
- Operating system and version (e.g. Ubuntu 20.04.2 LTS):
Xubuntu 18.04.5

## Reproducible demo

Demo:
https://docs.dhtmlx.com/suite/

Video:
https://files.dhtmlx.com/30d/755a3520f276b7a56857bc950354de17/vokoscreen-2021-06-30_16-56-23.mkv

**Comment by slorber** [comment]
Please use canary and test on your site to see if it improves anything: https://docusaurus.io/community/canary
