### ISSUE TITLE
The navigation menu and the search popup are not scrolled correctly with the mouse wheel in Chrome

### ISSUE THREAD

**Issue by gearcoded** [facebook/docusaurus#5101]
### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [] I have tried creating a repro with https://new.docusaurus.io
- [] I have read the console error message carefully (if applicable)

### Description

When I try to scroll the navigation and the search menus with the mouse wheel in Chrome/Chromium, it is not working correctly. 
It is strange, but it is working correctly in Vivaldi (Chromium engine). It is also working correctly in Firefox.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes.

## Steps to reproduce

1. Open the link in Chrome:
https://docs.dhtmlx.com/suite/
2. Open the entries in the left navigation menu.
3. Try scrolling the menu down with the mouse wheel.
4. The menu is not scrolled.
5. Type `i` in the search popup.
6. Try scrolling the popup with the mouse wheel.
7. The popup is not scrolled.

## Expected behavior

The navigation menu and the search popup should be scrolled.

## Actual behavior

The whole page is scrolled.

## Your environment

- Public source code:
https://github.com/DHTMLX/docs-suite
- Public site URL:
https://docs.dhtmlx.com/suite/
- Docusaurus version used:
2.0
- Environment name and version:
91.0.4472.106
- Operating system and version:
Xubuntu 18.04.5

## Reproducible demo

Demo:
https://docs.dhtmlx.com/suite/search/

Videos:
https://files.dhtmlx.com/30d/ff8eb5c7e6f665be329d6629a8c8fc3e/vokoscreen-2021-06-25_16-49-56.mkv
https://files.dhtmlx.com/30d/3b53b408fea61265ce46c5c49d882518/vokoscreen-2021-06-25_17-10-32.mkv

**Comment by slorber** [comment]
This looks like 2 distinct issues right?

## Search

I can't reproduce the issue where the search modal is displayed and where the background page scroll instead of the modal content, anyone else can?

## Sidebar

I can't reproduce either

---

Can you please test on another computer, other browsers, in private session, with all your browser plugins disabled etc?
 
`Chrome 78.0.3904.108` is also quite old, why aren't you using a more recent version? Still, it should work

**Comment by gearcoded** [comment]
@slorber, I tried it on a different operating system, Kubuntu 20.04, and it is also reproduced in Chrome.
I tried it on Windows in Chrome, and it is not reproduced there.

In all OSes, I have Chrome 91. It seems that the text in parentheses is confusing, so I will remove it.
