### ISSUE TITLE
bug on latest version @docusaurus/core@2.0.0-beta.3

### ISSUE THREAD

**Issue by sibelius** [facebook/docusaurus#5106]
### Prerequisites

- [x] I'm using the latest version of Docusaurus.
- [x] I have tried the `npm run clear` or `yarn clear` command.
- [x] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [x] I have tried creating a repro with https://new.docusaurus.io
- [x] I have read the console error message carefully (if applicable)

### Description

```jsx
app/node_modules/@docusaurus/core/bin/docusaurus.js:49
if (notifier.update && semver.gt(this.update.latest, this.update.current)) {
^

TypeError: Cannot read property 'latest' of undefined
at Object.<anonymous> (app/node_modules/@docusaurus/core/bin/docusaurus.js:49:46)
```

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

yes

## Steps to reproduce

upgrade to 2.0.0-beta.3 it was working on 2.0.0-beta.1

`docusaurus start`

## Expected behavior

do not break

## Actual behavior

shows an error

```jsx
app/node_modules/@docusaurus/core/bin/docusaurus.js:49
if (notifier.update && semver.gt(this.update.latest, this.update.current)) {
^

TypeError: Cannot read property 'latest' of undefined
at Object.<anonymous> (app/node_modules/@docusaurus/core/bin/docusaurus.js:49:46)
```

## Your environment

- Public source code: private
- Public site URL: private
- Docusaurus version used: 2.0.0-beta.3
- Environment name and version chrome, node 14
- Operating system and version: mac os x

"@docusaurus/core": "2.0.0-beta.3",
    "@docusaurus/preset-classic": "2.0.0-beta.3",

## Reproducible demo

I will work on it

**Comment by sibelius** [comment]
yarn --force

fixed

**Comment by Zamiell** [comment]
i got this same error, i resolved it by nuking my node_modules and package-lock.json files and then doing npm install again

**Comment by slorber** [comment]
weird, not sure why this happens, thanks for reporting

**Comment by rexwangcc** [comment]
Just another datapoint, ran into the same error when running `yarn start --locale XXX`, fixed it by:

```
rm -rf node_modules yarn.lock
yarn install
```
