### ISSUE TITLE
Fail to build the document if the headings contain JSX codes. (2.0.0-beta.2-2.0.0-beta.3)

### ISSUE THREAD

**Issue by cainmagi** [facebook/docusaurus#5108]
### Prerequisites

- [x] I'm using the latest version of Docusaurus.
- [x] I have tried the `npm run clear` or `yarn clear` command.
- [x] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io
- [x] I have read the console error message carefully (if applicable)

### Description

Docusaurus will fail to build (`yarn build`) if the heading contains JSX codes in the MDX files. However, in this case, `yarn start` still works perfectly.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes.

## Steps to reproduce

In some cases, we may want to use components in the headings. For example, the JSX component could be an icon.

```mdx
import { Icon, InlineIcon } from "@iconify/react";
import vsiSymbolClass from '@iconify-icons/codicon/symbol-class';

## <InlineIcon icon={vsiSymbolClass} width='1.35rem' style={{"verticalAlign": "bottom"}} />  Heading {#heading}

...
```

The yarn version is `1.22.10`.

## Expected behavior

The building should succeed and the JSX component should be rendered in the **navigation bar** on the right side, which means the navigation bar should be renderd like

```html
<a href="#heading" class="table-of-contents__link table-of-contents__link--active">
  <svg xmlns="http://www.w3.org/2000/svg" focusable="false" width="1.35rem" height="1.35rem" preserveAspectRatio="xMidYMid meet" viewBox="0 0 16 16" style="vertical-align: bottom;"><g fill="currentColor"><path d="M11.34 9.71h.71l2.67-2.67v-.71L13.38 5h-.7l-1.82 1.81h-5V5.56l1.86-1.85V3l-2-2H5L1 5v.71l2 2h.71l1.14-1.15v5.79l.5.5H10v.52l1.33 1.34h.71l2.67-2.67v-.71L13.37 10h-.7l-1.86 1.85h-5v-4H10v.48l1.34 1.38zm1.69-3.65l.63.63l-2 2l-.63-.63l2-2zm0 5l.63.63l-2 2l-.63-.63l2-2zM3.35 6.65l-1.29-1.3l3.29-3.29l1.3 1.29l-3.3 3.3z"></path></g></svg>
  "Heading"
</a>
```

## Actual behavior

The test command

```shell
yarn start
```

works perfectly.

However, if we run

```shell
yarn build
```

The building of the site would fail, and the following error would be thrown:

```
Docusaurus Node/SSR could not render static page with path "/docs/apis/host/LineHostBuffer" because of following error:

Error: Parse Error: <InlineIcon icon={vsiSymbolClass} width='1.35rem' style={{"verticalAlign": "bottom"}} />  Heading</a></li><li>...
...
```

This error is caused by the building of the navigation bar. In the debug mode, this part in the navigation bar is rendered as

```html
<a href="#heading" class="table-of-contents__link table-of-contents__link--active">
  <inlineicon icon="{vsiSymbolClass}" width="1.35rem" style="{{&quot;verticalAlign&quot;:" "bottom"}}="">  
    Heading
  </inlineicon>
</a>
```

It seems that the JSX component is not rendered correctly.

## Your environment

In the following public source codes, I have already removed the parts that may cause the bugs. If you want to check where the bug is caused, I provide an example [here](https://github.com/cainmagi/sync-stream/blob/a02a41e86a416940dfe8bc5e8acc071adbe26903/docs/apis/base/GroupedMessage.mdx#inlineicon-iconvsisymbolmethod-width135rem-styleverticalalign-bottom--serialize).

- Public source code: https://github.com/cainmagi/sync-stream/tree/docs
- Public site URL: https://cainmagi.github.io/sync-stream/
- Bug report (built with Docusaurus 2.0,0-beta.2): https://github.com/cainmagi/sync-stream/actions/runs/984563468
- Docusaurus version used: `2.0.0-beta.3`
- Environment name and version: Microsoft Edge 91.0.864.59, Node.js 15.14.0:
- Operating system and version Windows 10 21H1:

**Comment by slorber** [comment]
Headings do not support MDX / React components, as well as the TOC and the sidebar, that can only render simple texts.

It may be technically possible to do so but would be quite challenging and expensive to run.

I suggest opening a Canny feature request instead, but IMHO it's unlikely we implement this anytime soon because of the complexity and the little ROI

**Comment by RichieChoo** [comment]
Why heading not support? How to only  build client .

**Comment by cainmagi** [comment]
> Why heading not support? How to only build client .

If you are using `yarn start`, only the client is built. However, `docusaurus` seems to not support building the client-only version now.

I could understand why heading with JSX is not supported. Because the sidebar is only rendered by the simple Markdown engine, the MDX plugin is not supported when rendering the sidebar.
