### ISSUE TITLE
setting trailingSlash causes validation error

### ISSUE THREAD

**Issue by giggity-hub** [facebook/docusaurus#5125]
when the `docusaurus.config.js` field [trailingSlash](https://docusaurus.io/docs/docusaurus.config.js/#trailing-slash) is set a validation error occurs

### My docusaurus.config.js
```js
module.exports = {
  ...
  trailingSlash: true,
  ...
};
```
### Error Message
```
A validation error occured.
The validation system was added recently to Docusaurus as an attempt to avoid user configuration errors.
We may have made some mistakes.
If you think your configuration is valid and should keep working, please open a bug report.

Error: These field(s) ["trailingSlash",] are not recognized in docusaurus.config.js.
If you still want these fields to be in your configuration, put them in the 'customFields' attribute.
[StackTrace]
```

**Comment by slorber** [comment]
You are likely not using the latest docusaurus version (which we can't verify because you didn't respect the issue template)

**Comment by MichaelSp** [comment]
I can confirm this bug with version `2.0.0-beta.4`

**Comment by slorber** [comment]
@MichaelSp a repro is needed, because we have sites using that option without problem, and we even use it ourselves in production :)

**Comment by slorber** [comment]
note: beta.4 is not released yet, so if you use it you are probably doing something wrong

**Comment by MichaelSp** [comment]
Thanks for your comments. 

Turns out `2.0.0-beta.4` for me resolved to `2.0.0-beta.ff31de0ff`.
Tried it again with `canary` which is resolved to `2.0.0-beta.44225a3df` and there it worked like a charm 👍 🚀

**Comment by slorber** [comment]
Thanks, that's what I suspected, I guess we'll have to change our canary version name pattern so that this kind of resolution does not happen

**Comment by MichaelSp** [comment]
Your versioning is .... special.... :)

**Comment by slorber** [comment]
I don't know, what version name to pick for a canary release matching a git commit?

React package seems to do a similar thing (using - instead of .): https://www.npmjs.com/package/react
