### ISSUE TITLE
💥 Move TOC to the top when Navbar is hidden

### ISSUE THREAD

**Issue by silverqx** [facebook/docusaurus#5134]
When I set config like this:
```
themeConfig: {
    navbar: {
      hideOnScroll: true,
    },
},
```

~And I set `hide_table_of_contents: true` on a document page,~ And `Navbar` hides, I would also welcome to move `TOC` to the top of the page. 🙂

Currently, the `TOC` has this style:
```
top: calc(var(--ifm-navbar-height) + 1rem);
```

It is ok when `Navbar` is displayed, but when I scroll a little down and `Navbar` hides I would welcome this style:
```
top: 1rem;
```

I already tried it locally in the web browser and it looks better from my perspective. What do you think?

**Comment by slorber** [comment]
I'm not sure to understand what you mean.

Please include screenshots showing your problem and eventually mock-ups of what you suggest.
Plain text does not help to understand easily what this is about.

**Comment by silverqx** [comment]
@slorber Currently it looks like this when `Navbar` hides:
![TOC_current](https://user-images.githubusercontent.com/86900/125099280-25670b80-e0d8-11eb-84cf-5ff360a40b3c.jpg)

I'm proposing this:
![TOC_proposed](https://user-images.githubusercontent.com/86900/125099308-2d26b000-e0d8-11eb-9ceb-5e12cd4a5b3f.jpg)

**Comment by slorber** [comment]
I see, but if we use top: 1rem then when we scroll up the navbar would cover it partially:

![image](https://user-images.githubusercontent.com/749374/125100247-2c424e00-e0d9-11eb-9e98-3203ae13826a.png)

To avoid that, we would have to animate its position in the same way we animate the collapsible navbar. 
Is it really worth it, and wouldn't this be distracting? Do we really want to have a ton of animations on scroll with content that changes position?

Note also that when you click on a TOC item, the navbar collapses. This means that with a TOC translation animation, when clicking on a TOC item, the item you just clicked will be translated up. I'm not at all convinced it's a good UX to make the clickable item move on click.

---

I don't understand why you mention `hide_table_of_contents`, how is this even related?

**Comment by silverqx** [comment]
@slorber Sry I made a little mistake in the description about ~`hide_table_of_contents: true`~, that part is not true, I have crossed it out. I cross it out also here.

**Comment by silverqx** [comment]
> Note also that when you click on a TOC item, the navbar collapses.

This part is important and you are right, when I click on something I would expect to stay it on the same position, I did not consider this case.

Now I also think that it is not a good idea 😁

**Comment by silverqx** [comment]
Jumping navigation is lava 😂 @slorber

**Comment by lex111** [comment]
I once suggested lifting the TOC when the navbar is hidden, @silverqx  is that what you mean?

![image](https://user-images.githubusercontent.com/4408379/95030155-4bc5c980-06b6-11eb-9488-feaa56e0c734.gif)

**Comment by silverqx** [comment]
@lex111 Yeah that is exactly what I meant.

**Comment by silverqx** [comment]
@lex111 Did you also created PR? I would try it locally how it looks like

**Comment by silverqx** [comment]
I want to try that jumping especially.

**Comment by lex111** [comment]
Sure, https://github.com/facebook/docusaurus/pull/3536

I like it, but it's probably  going to be distraction for users.

**Comment by silverqx** [comment]
@lex111 thx
