### ISSUE TITLE
Docusaurus can't be initialized with pnpm

### ISSUE THREAD

**Issue by 3x071c** [facebook/docusaurus#5182]
### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [ ] I have tried the `npm run clear` or `yarn clear` command.
- [ ] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io
- [X] I have read the console error message carefully (if applicable)

### Description

Attempting to initialize a new docusaurus project fails with `Excess arguments` when using `pnpx`:
```sh
$ pnpx -y @docusaurus/init@latest init my-website classic
Packages: +39
+++++++++++++++++++++++++++++++++++++++
Packages are cloned from the content-addressable store to the virtual store.
  Content-addressable store is at: /home/<user>/.pnpm-store/v3
  Virtual store is at:             node_modules/.pnpm

/home/<user>/.pnpm-store/v3/tmp/_npx/50290/5:
+ @docusaurus/init 2.0.0-beta.3

Progress: resolved 39, reused 39, downloaded 0, added 39, done
Excess arguments.
```
`npx` works, as well as installing and using docusaurus with `pnpm` afterwards:
```sh
$ npx -y @docusaurus/init@latest init my-website classic --skip-install && cd my-website && pnpm i
```
`pnpx` belongs to [pnpm](https://pnpm.io), a relatively new package manager which avoids dependency trouble and high disk space usage by using hard links from a global store and not flattening `node_modules`. While I was able to work around this so easily it's almost not worth an issue (as seen above), it would be nice if docusaurus would be smooth to initialize for `pnpm` users as well.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## Steps to reproduce

1. Install `pnpm`: `npm i -g pnpm`
2. Follow instructions with pnpx: `pnpx -y @docusaurus/init@latest init my-website classic`

## Expected behavior

3. Success :)

## Actual behavior

3. Fail: `Excess arguments` :(

## Your environment

- Public source code: -
- Public site URL: -
- Docusaurus version used: 2.0.0-beta.3
- Environment name and version: Node.js 16.5.0
- Operating system and version: Arch GNU/Linux (rolling release)

## Reproducible demo

N/A

**Comment by slorber** [comment]
Is it 100% sure it's a Docusaurus bug?

Have you checked pnpm repo for issues? There are a few that looks related:
https://github.com/pnpm/pnpm/search?q=content-addressable&type=issues

If so, what's the usual way for making a package initializable with pnpm, that diverge from the other tools?

Are you sure your init command is correct and another syntax is not required for extra cli args with pnpx?

**Comment by 3x071c** [comment]
Don't really have time to look into this rn, sorry...
