### ISSUE TITLE
Can't deploy to github pages using 2FA account.

### ISSUE THREAD

**Issue by kimlimjustin** [facebook/docusaurus#5194]
### Prerequisites

- [x] I'm using the latest version of Docusaurus.
- [x] I have tried the `npm run clear` or `yarn clear` command.
- [x] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io
- [x] I have read the console error message carefully (if applicable)

### Description

When I try to deploy docusaurus website into GitHub pages, it says authentication failed, and I kept repeating that and I'm sure I typed my password correctly, and I tried to deploy it using another account, and it works fine! I assume it's because my GitHub account is 2FA protected.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## Steps to reproduce
I haven't tried to reproduce, because I need to create amounts of GitHub accounts to do so.

## Expected behavior

I expect it can works fine :)

## Actual behavior

It says authentication failed (invalid username or password), even though I'm sure I correctly typed it. 

## Your environment

- Public source code: https://github.com/kimlimjustin/xplorer
- Public site URL: https://kimlimjustin.github.io/xplorer
- Docusaurus version used: 2.0.0-beta.3
- Environment name and version (e.g. Chrome 78.0.3904.108, Node.js 10.17.0): Chrome Version 91.0.4472.164 (Official Build) (64-bit), Node js version 15.14.0
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): Ubuntu 21.04

## Reproducible demo

I'm really sorry I can't provide demo, because it's require GitHub account password.

**Comment by Josh-Cena** [comment]
I'm using 2FA and I deploy my site to GitHub pages with my account. You can try setting a personal access token.

**Comment by HonkingGoose** [comment]
@kimlimjustin I recommend you read the [GitHub docs, authenticating with the command line](https://docs.github.com/en/github/authenticating-to-github/keeping-your-account-and-data-secure/about-authentication-to-github#authenticating-with-the-command-line).

Relevant quote from linked document:

> You can work with all repositories on GitHub over HTTPS, even if you are behind a firewall or proxy. Every time you use Git to authenticate with GitHub, you'll be prompted to enter your credentials to authenticate with GitHub, unless you cache them with a credential helper. When Git prompts you for your password, enter your personal access token (PAT) instead. **Password-based authentication for Git is deprecated**, and using a PAT is more secure. For more information, see "Creating a personal access token."

**Comment by kimlimjustin** [comment]
Oh yeah, thanks for pointing it out @HonkingGoose @Josh-Cena !
