### ISSUE TITLE
Wrong Pagination links for symlinked folders  

### ISSUE THREAD

**Issue by lebalz** [facebook/docusaurus#5196]
I'm organizing multiple courses for different grades - they share sometimes the exact same material, but sometimes the material differs from course to course.

I use the `/docs` folder to place all the material in. Each course gets it's own version, e.g. `versioned_docs/version-courseA`. I then create symlinks to the material, that was presented in the concrete course (e.g. to enable the material about loops in js for course A, i would do `(cd "$versioned_docs/version-courseA" && /bin/ln -s "../../docs/js-loops" .)`).

Everything works as expected, expect the pagination: When using the pagination to go to the next page, and then wanting to go back again, it will not be anymore the versioned page for this course...

[Code Sandbox](https://codesandbox.io/s/gifted-darkness-mzxgp)

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io
- [X] I have read the console error message carefully (if applicable)

### Description

When having a symlinked folder in a versioned docs folder pointing to a folder in `/docs` (e.g. `versioned_docs/version-courseA/js-basics --> /docs/js-basics`), the pagination will not work when navigate over it. When clicking "Next" (or "Previous"), the following pagination is not in sync with the sidebar and points instead to the "Next" (and "Previous") Page of the `/docs` folder structure.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes.

## Steps to reproduce

1. Launch the [Code Sandbox](https://codesandbox.io/s/gifted-darkness-mzxgp)
2. navigate to e.g. "Course A" (you will land on page `courseA/intro`)
3. Click "Next" (Javascript Basics) - you will land on `/courseA/js-basics/basics`)
4. Notice: Even there should not be another "Next" Button (the Sidebar lists only the intro and the "JS Basics"), there is a "Next" button...
5. Click "Previous" and instead of landing on page `courseA/intro`, you land on `/intro`
Use https://new.docusaurus.io to create a CodeSandbox reproducible demo of the bug.

## Expected behavior

The pagination is in sync with the sidebar, even when having symlinked folders.

## Actual behavior

The links for the pagination are created before webpacker resolves the symlinks.

![pagination-symlinked-folders](https://user-images.githubusercontent.com/22354689/126374811-6ee10070-bfcb-43bd-ad61-35ad9622443a.gif)

## Your environment

[https://codesandbox.io/s/gifted-darkness-mzxgp](https://codesandbox.io/s/gifted-darkness-mzxgp)

## Reproducible demo

[https://codesandbox.io/s/gifted-darkness-mzxgp](https://codesandbox.io/s/gifted-darkness-mzxgp)

**Comment by slorber** [comment]
We don't support symlinks well currently, particularly when they are nested inside the docs folder.

Eventually, you can make the root docs folder a symlink, but that requires changing a Webpack setting (+ there is a webpack caching bug). See https://github.com/facebook/docusaurus/pull/5126

I'd suggest for now to:
- not use symlinks inside docs
- resolve a potential docs symlink to the real path directly in your symlink

---

AbouT use-case. I have no idea why you want to create a symlink such as `versioned_docs/version-courseA/js-basics --> /docs/js-basics`, it does not make sense to me and it's unlikely we support this kind of fancy feature in the future (even if we support symlinks better). What are your motivations?

> Notice: Even there should not be another "Next" Button (the Sidebar lists only the intro and the "JS Basics"), there is a "Next" button...

No, your sidebars file is using a single sidebar for a whole docs version, this means that all your courses are part of the same sidebar and you can then navigate from one course to another with pagination. 

If you don't want this to happen, use multiple sidebars (autogenerated or not).

You can also try to use multiple docs plugin instances, in which case each instance docs folder can be configured independently to the location of your choice (including symlinks if you configure webpack, or absolute paths, git submodules or whatever you use)

**Comment by slorber** [comment]
Note: On CodeSandbox, I see regular folders and am not even sure symlinks work (at least can't see them). Also suggest to try this outside of Codesandbox as sometimes there are caching issues and CodeSandbox still see old files.

See how your original sandbox and my fork gives a different result (didn't change anything):

This one (yours) look wrong according to your side content:

![image](https://user-images.githubusercontent.com/749374/126469182-720ceb76-00c2-4549-bf1c-5f79c1ae1147.png)

Mine looks better:

![image](https://user-images.githubusercontent.com/749374/126469231-b27ac170-41c5-4b25-9119-6b71a75d6a09.png)

**Comment by lebalz** [comment]
Thank you very much for your quick reply.

About my use case: you are right, it is not the standard of a documentation website. But there are no really suitable frameworks for parallel courses. But with versioning this could be adapted relatively "easy". I am aware that in the classic case older versions should not be changed if possible. For teaching, however, the "same version" should be made available at different times for individual courses. Therefore the hack with the symlinks...

Currently I already use different sidebars (`versioned_sidebars`) and that works, except for the pagination...

**Comment by lebalz** [comment]
> Note: On CodeSandbox, I see regular folders and am not even sure symlinks work (at least can't see them). Also suggest to try this outside of Codesandbox as sometimes there are caching issues and CodeSandbox still see old files.
> 
> See how your original sandbox and my fork gives a different result (didn't change anything):
> 
> This one (yours) look wrong according to your side content:
> 
> ![image](https://user-images.githubusercontent.com/749374/126469182-720ceb76-00c2-4549-bf1c-5f79c1ae1147.png)
> 
> Mine looks better:
> 
> ![image](https://user-images.githubusercontent.com/749374/126469231-b27ac170-41c5-4b25-9119-6b71a75d6a09.png)

Hmm, i'm not sure how code sandbox is managing this actually, but my sidebar shall look like my version... (since i wanted to make "js intro" available only to the courseA, but not to courseB, however the ground truth of all material lies in the `docs` folder... do you see the scenario?

The created symlinks should work and are looking as follows on my machine...

![image](https://user-images.githubusercontent.com/22354689/126470112-b91bd5a3-6593-4ba5-b622-8a990e59c143.png)

**Comment by slorber** [comment]
This folder contains a single file:

![image](https://user-images.githubusercontent.com/749374/126474269-8c29c7d4-a7f7-4f18-8f5d-2f3aa41c8934.png)

So it's very unexpected that you end up with a sidebar of 2 elements on path `/courseA`. It should only contain the file in this folder, this is the intended behavior.

**Comment by lebalz** [comment]
> This folder contains a single file:
> 
> ![image](https://user-images.githubusercontent.com/749374/126474269-8c29c7d4-a7f7-4f18-8f5d-2f3aa41c8934.png)
> 
> So it's very unexpected that you end up with a sidebar of 2 elements on path `/courseA`. It should only contain the file in this folder, this is the intended behavior.

Okay, sadly CodeSandbox does not copy symlinks when forking :(. To see the weird behavior you would need to execute the following command in the terminal of codesandbox:

```sh
(cd "versioned_docs/version-courseA" && /bin/ln -s "../../docs/js-loops" .)
```

Thanks again for your support.

**Comment by slorber** [comment]
I see, but even it's not something you should do and not likely that we'll want to support that either, so you'd rather use another option.

You can copy files around in your build process if needed
