### ISSUE TITLE
hardcoded https:// prefix 

### ISSUE THREAD

**Issue by Flashwalker** [facebook/docusaurus#5213]
Why is hardcoded https:// prefix for homepage?
What if i want local file:// as homepage?

**Comment by Josh-Cena** [comment]
I don't think you can use the Docusaurus site normally with the `file://` protocol—you have to serve it through HTTP.

**Comment by slorber** [comment]
Closing in favor of https://github.com/facebook/docusaurus/issues/3825

**Comment by Flashwalker** [comment]
Hey, I have no clue how my report got here Oo
