### ISSUE TITLE
still showing old admonitions after updating

### ISSUE THREAD

**Issue by pdimens** [facebook/docusaurus#5221]
### Prerequisites

- [x] I'm using the latest version of Docusaurus.
- [ ] I have tried the `npm run clear` or `yarn clear` command.
- [x] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io
- [ ] I have read the console error message carefully (if applicable)

### Description
I have tried to update my package's documentation from alpha-73 to beta-3 and the admonitions have not changed to the new style as visible on the docusaurus docs. An example can be seen [here](https://biojulia.net/PopGen.jl/docs/#using-popgen) The `package.json` for the docs are
```json
{
  "name": "pop-gen-jl",
  "version": "0.6.5",
  "private": true,
  "scripts": {
    "start": "docusaurus start",
    "build": "docusaurus build",
    "swizzle": "docusaurus swizzle",
    "deploy": "docusaurus deploy"
  },
  "dependencies": {
    "@docusaurus/core": "^2.0.0-beta.3",
    "@docusaurus/preset-classic": "^2.0.0-beta.3",
    "clsx": "^1.1.1",
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "rehype-katex": "^4.0.0",
    "remark-math": "^3.0.1"
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  }
}
```
I have deleted the `node_modules` directory as well as `yarn.lock` and performed `yarn.install`

## Expected behavior

![image](https://user-images.githubusercontent.com/19176506/127040014-27dc41a0-115b-49af-afc0-d22c5d945e76.png)

## Actual behavior

![image](https://user-images.githubusercontent.com/19176506/127040048-e6dd771c-4b0f-4912-87c3-f6dd8ed2af98.png)

## Your environment

- Public source code: https://github.com/BioJulia/PopGen.jl/blob/documentation/package.json
- Public site URL: https://biojulia.net/PopGen.jl/
- Docusaurus version used: `20.0.0-beta.3`
- Environment name and version: Node.js 16.5.0

**Comment by Josh-Cena** [comment]
The docusaurus site uses the real ***latest*** version—the canary release. See here: https://docusaurus.io/community/canary

**Comment by slorber** [comment]
Yes, it will be in beta.4 released soon :)
