### ISSUE TITLE
Long delay when running "docusaurus start"

### ISSUE THREAD

**Issue by petrbroz** [facebook/docusaurus#5231]
### Prerequisites

- [x] I'm using the latest version of Docusaurus.
- [x] I have tried the `npm run clear` or `yarn clear` command.
- [x] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- (not applicable) [ ] I have tried creating a repro with https://new.docusaurus.io
- (not applicable) [ ] I have read the console error message carefully (if applicable)

### Description

Every time I run `docusaurus start`, the compilation gets stuck (typically at 8% or 9%) for several minutes.

<img width="1037" alt="Screen Shot 2021-07-28 at 10 34 57 AM" src="https://user-images.githubusercontent.com/1470668/127291386-65b6e0ce-30e2-4053-98ed-03d112cad98b.png">

This happens with a simple project scaffolded using `npx @docusaurus/init@latest init my-website classic` without any changes. Other commands such as `docusaurus clear` or `docusaurus build` have no effect on this.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes.

## Steps to reproduce

1. Scaffold a new project using `npx @docusaurus/init@latest init my-website classic`
2. Run `yarn start` in the newly created folder

## Expected behavior

Browser navigates to http://localhost:3000 automatically (or the user does so manually), and the content is presented in a "reasonable amount of time".

or

The console output informs the user that the project is **not** yet running.

## Actual behavior

The compilation gets stuck for several minutes (in my case it's a little over 2 minutes), usually at 8% or 9%. Subsequent attempts to run `yarn start` or `docusaurus start` take the same time.

## Your environment

- Docusaurus version used: 2.0.0-beta.3
- Environment name and version: Node.js v14.17.0, yarn 1.21.1
- Operating system and version: macOS Big Sur 11.5 (20G71)

## Reproducible demo

N/A

**Comment by petrbroz** [comment]
Btw. I think this issue _might_ be related to https://github.com/facebook/docusaurus/issues/4245.

**Comment by slorber** [comment]
It's hard to tell what this could be unfortunately.

It might be a bug in a transitive lib that published a buggy version and you get unlucky to pick the buggy version in your lockfile. 

I suggest trying again to re-generate your lockfile.

I also suggest trying `yarn start` without `-- --locale cz` (`--` is useless with yarn and it might even create an issue?)

Maybe worth trying with a different version of nodejs?

**Comment by petrbroz** [comment]
Thank you Sébastien. Just to clarify, I was able to reproduce the issue even with the default "classic" project (`npx @docusaurus/init@latest init my-website classic`), with no i18n and no locale (simply running `yarn start`), as described in the _Steps to reproduce_ above. And I also tried re-creating the lockfile, but to no avail.

**Comment by petrbroz** [comment]
Alright, so I have no idea why or how, but if I now follow the steps described in _Steps to reproduce_ above, the compilation completes in under a second... The only thing that happened between now and then is - I restarted my MacBook Pro. So I'm guessing it must've been something in my system but unfortunately I have no idea what :/ Anyway, let me close this issue, and if this happens to someone in the future, let's see if they're on macOS as well (the user who reported https://github.com/facebook/docusaurus/issues/4245 was on macOS, too).

**Comment by slorber** [comment]
If it's faster now it may be because you have a non-empty Webpack 5 cache. 

Try `yarn clear && yarn start`, if it's slow again the issue might still be there.

If you re-generated the project, you might as well get lucky. The fix of a transitive dependency can have happened in the last hour, and you'd have to compare the lockfile before/after to be able to figure which dep was upgraded exactly 😅
