### ISSUE TITLE
The doc sidebar in the main menu is not available

### ISSUE THREAD

**Issue by TBurda** [facebook/docusaurus#5241]
### Prerequisites

- [x] I'm using the latest version of Docusaurus.
- [x] I have tried the `npm run clear` or `yarn clear` command.
- [x] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [x] I have tried creating a repro with https://new.docusaurus.io
- [x] I have read the console error message carefully (if applicable)

### Description

The document sidebar icon in the main menu is not available in mobile view in document-only mode.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## Steps to reproduce

1. Set up doc-only mode (https://docusaurus.io/docs/docs-introduction#docs-only-mode)
2. Open documentation in mobile view

## Expected behavior

![Expected behavior](https://user-images.githubusercontent.com/21170562/127471252-3f43e596-42b6-421c-aca4-9fc653e9d037.png)

## Actual behavior

![Actual behavior](https://user-images.githubusercontent.com/21170562/127471410-8fe449f4-22a2-460c-bb54-40266d5c78ab.png)

## Your environment

- Docusaurus version used: 2.0.0-beta.4
- Environment name and version: Google Chrome 92.0.4515.107, Node.js v14.16.1.
- Operating system and version: macOS Big Sur (11.5)

## Reproducible demo
https://codesandbox.io/s/confident-worker-vyu58

**Comment by lex111** [comment]
Actually, the sidebar icon is not displayed because you removed all navbar items. If you added at least one item to navbar field in the config file, this button will be displayed again.

**Comment by TBurda** [comment]
Thank you for your reply. Previously it was not necessary and sidebar worked properly. Is it not possible to keep this feature? For now I am adding a docs type item to the navbar.

**Comment by lex111** [comment]
> Previously it was not necessary and sidebar worked properly

I don't really know what you mean. If there are no navbar items, there is no point in showing the sidebar, because we will see something like this:

![image](https://user-images.githubusercontent.com/4408379/127493578-ec9498b3-4c7c-42c2-96f2-9c1a7102260b.png)

**Comment by Josh-Cena** [comment]
But the new mobile UX also makes the sidebar contain the doc sidebar right?

**Comment by TBurda** [comment]
Previously, navigation between pages in the documentation was available in mobile view under the button in the bottom right corner (https://codesandbox.io/s/beautiful-wu-uq1k2). In this case, after updating to version 2.0.0-beta4, there are no way to navigate between pages in the documentation.

**Comment by slorber** [comment]
Oh, this is a bit annoying 😅 

What behavior would you expect, considering the new mobile UX?

Because on the homepage it would display an empty panel, and then on docs page it would display the doc sidebar + a button to return to the empty panel. Wouldn't that be weird? 

Anyway, wasn't your existing experience already confusing, as users opening the hamburger menu got an empty panel already? Why don't you use navbar items in the first place? 

Maybe the hamburger menu should be "disabled" on the homepage, and become enabled on pages like docs which would show content in that menu?

**Comment by Josh-Cena** [comment]
@slorber the problem currently is that the hamburger is ***never*** shown, because its display is solely controlled by the length of navbar items. This simultaneously hides the doc sidebar away, which is unintended.

**Comment by lex111** [comment]
We should probably show sidebar button even if there are no sidedar items, so that we can see secondary menu. In that case we just won't render "Back to main menu" button.

**Comment by slorber** [comment]
Yes, but wouldn't it be weird to open that hamburger menu in the homepage and see an empty panel? Anyway, it was probably already the case before, but still a problem that would be nice to fix 😅

**Comment by Josh-Cena** [comment]
> but wouldn't it be weird to open that hamburger menu in the homepage and see an empty panel? 

This issue is in docs-only and I assume all the pages would have a sidebar associated, otherwise navigation would be hard.

**Comment by slorber** [comment]
I see, yes so it's probably not worth to try to solve the other use-case as it's quite unlikely to happen...

I guess we could force the display of the second panel in the navbar mobile sidebar
