### ISSUE TITLE
Quotes can be improved

### ISSUE THREAD

**Issue by Josh-Cena** [facebook/docusaurus#5244]
## 🚀 Feature

The Markdown blockquotes look somehow off now.

![image](https://user-images.githubusercontent.com/55398995/127495974-bb5534b8-f26e-420c-97d8-e2fbe85a54d6.png)

Most Markdown renderers would render blockquotes as gray and (usually) without background color. E.g., Typora:

![image](https://user-images.githubusercontent.com/55398995/127498280-73bf1fc8-f896-4138-89e0-f937388f90b6.png)

[Zhihu](https://www.zhihu.com), a Chinese forum (which I'm personally most familiar with):

![image](https://user-images.githubusercontent.com/55398995/127498117-19a77848-fcc3-4c98-93d4-8f7ad5b2c18e.png)

And GitHub:

> Some quote

VS Code has a background, but is gray nonetheless:

![image](https://user-images.githubusercontent.com/55398995/127496595-9713cda2-2784-41f2-841b-0c726ba5b2ad.png)

Quotes are usually considered semantically less important than actual content. Using yellow makes it "stand out too much", and also easily confuses with admonitions. 

I understand that we are:

1. Trying to reach consistency with v1;
2. Trying to improve accessibility compared to the previous light gray color,

But I'd still prefer a darkened-gray primary color instead of yellow so we are conforming to the norms, even if we decided to keep the background color (which I believe would be better to be gotten rid of—introduces extra visual distractions when sometimes quotes can be very long, like an entire article)

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

### Has this been requested on [Canny](https://docusaurus.io/feedback)?

No

## API Design

I propose two changes:

1. Change the color to a gray color (dark enough to maintain accessibility, of course)
2. Remove the background color

So that the quote:

1. Visually blends in with the main content;
2. Is differentiated from admonitions

**Comment by slorber** [comment]
For context, I asked to open this issue for further discussions and polling our community.

We did a quick redesign of quotes, because the existing design was highly inaccessible in terms of color contrasts.

Docusaurus v1 had similar quotes:

![image](https://user-images.githubusercontent.com/749374/127511774-24bfa00f-5a69-45a3-805d-724d169c5553.png)

We also saw some sites reproducing a similar design with custom CSS on v2:

https://reactnavigation.org/docs/getting-started

![image](https://user-images.githubusercontent.com/749374/127511860-ecb6c660-28c6-4338-b1de-e783bac6676e.png)

https://reactnative.dev/docs/0.63/getting-started

![image](https://user-images.githubusercontent.com/749374/127511916-8cac9695-4600-406c-9a66-d0ffc4bbb2bc.png)


It felt to be a good idea to keep using this design, as v1 users would have been used to it and it wouldn't be too disruptive for existing sites already using it.

I also think the current design remains quite easy to distinguish from admonition: 

![image](https://user-images.githubusercontent.com/749374/127512137-fe3835ff-65d9-4f61-b228-8c565d4adc5c.png)

---

Agree that maybe they are a bit too visible. 

Also your simpler design is the one visible on the CommonMark site: https://commonmark.org/help/

Likely opinionated and subject to debate so I suggest we run a little community poll to see what people prefer and do what most agree with by default.

Keep in mind that in any case you can easily make it look the way you want with custom CSS quite easily.

**Comment by slorber** [comment]
Also something to consider is nested quotes. I'm not sure current design is the best for that usecase.

See Nextra doc: https://nextra.vercel.app/features/mdx#blockquote

![image](https://user-images.githubusercontent.com/749374/127513613-e114a9d2-5722-4773-a29d-2fa060fe053a.png)

**Comment by Josh-Cena** [comment]
> Also something to consider is nested quotes. 

That's true. Nested quotes become too crowded with existing design:

![image](https://user-images.githubusercontent.com/55398995/127515182-809e6dda-fd4a-4814-82aa-da8691541128.png)

(The transparent colors are stacking up. Looks kinda funny🤪)

Actually, I would argue that the `<details>` comp is also crowded, but I have less to complain about that design

**Comment by slorber** [comment]
it doesn't look too bad to me 😅 

![image](https://user-images.githubusercontent.com/749374/127519219-a630b381-becb-4ff5-acb1-fe2900e1e2ef.png)

**Comment by Pal-Wrtites** [comment]
Is this issue still open? I am a beginner and would like to contribute in the area of documentation.

**Comment by Josh-Cena** [comment]
This is not a documentation issue, but rather whether the quote design in the code base should be improved. We are mostly asking for community opinions because aesthetics can vary

**Comment by mfridman** [comment]
We just upgraded from.

```
"@docusaurus/core": "^2.0.0-alpha.73",
"@docusaurus/preset-classic": "^2.0.0-alpha.73"
```

And were a bit disturbed by the yellow color for block quotes. Note that hyper links within blockquotes are not accessible.

**Before:**
<img width="513" alt="CleanShot 2021-08-05 at 17 06 28@2x" src="https://user-images.githubusercontent.com/6278244/128421421-48edd3d8-f6cc-48fe-b1e4-93654ce66c7e.png">

**After:**
Note the link is barely visible.

<img width="554" alt="CleanShot 2021-08-05 at 17 06 55@2x" src="https://user-images.githubusercontent.com/6278244/128421386-3c14d7ed-ed7b-46d9-8269-acb6391c9901.png">

Block quotes shouldn't be so intrusive as a default. Much prefer a more subtle blockquote which is how most existing system tream them

**Comment by mfridman** [comment]
Any chance someone could post a copy/paste solution for global css to override this styling (ideally to what it was before)?

**Comment by Josh-Cena** [comment]
> Any chance someone could post a copy/paste solution for global css to override this styling (ideally to what it was before)?

Didn't test myself, directly copied from a website that's on older version:

```css
blockquote {
    border-left: 6px solid #dadde1;
    border-left: 6px solid var(--ifm-color-emphasis-300);
    color: #6a737d;
    color: var(--ifm-blockquote-color);
    font-size: 100%;
    font-size: var(--ifm-blockquote-font-size);
    margin: 0 0 1rem;
    margin-bottom: var(--ifm-spacing-vertical);
    padding: 1rem;
    padding: var(--ifm-blockquote-padding-vertical) var(--ifm-blockquote-padding-horizontal);
}
```

**Comment by Josh-Cena** [comment]
> Any chance someone could post a copy/paste solution for global css to override this styling (ideally to what it was before)?

Try this in `custom.css`:

```css
blockquote {
  border-left: 6px solid #dadde1;
  background-color: transparent;
  color: #5b626b;
  font-size: 100%;
  margin: 0 0 1rem;
  padding: 1rem;
  box-shadow: none;
}
```

I darkened text color a bit (the older version was `#6a737d`) to improve readability

**Comment by mfridman** [comment]
Thank you for the example.

> This probably doesn't resolve the link color issue, though, because they are controlled by other Infima variables

Indeed the issue I was having was with link colors. I think we'll revert back to`^2.0.0-alpha.73` and hope this issue gets consideration.

**Comment by amelo1990** [comment]
> ## 🚀 Besonderheit
> Die Markdown-Blockquotes sehen jetzt irgendwie aus.
> 
> ![Bild](https://user-images.githubusercontent.com/55398995/127495974-bb5534b8-f26e-420c-97d8-e2fbe85a54d6.png)
> 
> Die meisten Markdown-Renderer rendern Blockquotes grau und (normalerweise) ohne Hintergrundfarbe. Beispiel: Typora:
> 
> ![Bild](https://user-images.githubusercontent.com/55398995/127498280-73bf1fc8-f896-4138-89e0-f937388f90b6.png)
> 
> [Zhihu](https://www.zhihu.com) , ein chinesisches Forum (mit dem ich persönlich am besten vertraut bin):
> 
> ![Bild](https://user-images.githubusercontent.com/55398995/127498117-19a77848-fcc3-4c98-93d4-8f7ad5b2c18e.png)
> 
> Und GitHub:
> 
> > Einige Zitate
> 
> VS Code hat einen Hintergrund, ist aber trotzdem grau:
> 
> ![Bild](https://user-images.githubusercontent.com/55398995/127496595-9713cda2-2784-41f2-841b-0c726ba5b2ad.png)
> 
> Quotes are usually considered semantically less important than actual content. Using yellow makes it "stand out too much", and also easily confuses with admonitions.
> 
> I understand that we are:
> 
> 1. Trying to reach consistency with v1;
> 2. Trying to improve accessibility compared to the previous light gray color,
> 
> But I'd still prefer a darkened-gray primary color instead of yellow so we are conforming to the norms, even if we decided to keep the background color (which I believe would be better to be gotten rid of—introduces extra visual distractions when sometimes quotes can be very long, like an entire article)
> 
> ### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?
> Yes
> 
> ### Has this been requested on [Canny](https://docusaurus.io/feedback)?
> No
> 
> ## API Design
> I propose two changes:
> 
> 1. Change the color to a gray color (dark enough to maintain accessibility, of course)
> 2. Remove the background color
> 
> So that the quote:
> 
> 1. Visually blends in with the main content;
> 2. Is differentiated from admonitions



> ## 🚀 Besonderheit
> Die Markdown-Blockquotes sehen jetzt irgendwie aus.
> 
> ![Bild](https://user-images.githubusercontent.com/55398995/127495974-bb5534b8-f26e-420c-97d8-e2fbe85a54d6.png)
> 
> Die meisten Markdown-Renderer rendern Blockquotes grau und (normalerweise) ohne Hintergrundfarbe. Beispiel: Typora:
> 
> ![Bild](https://user-images.githubusercontent.com/55398995/127498280-73bf1fc8-f896-4138-89e0-f937388f90b6.png)
> 
> [Zhihu](https://www.zhihu.com) , ein chinesisches Forum (mit dem ich persönlich am besten vertraut bin):
> 
> ![Bild](https://user-images.githubusercontent.com/55398995/127498117-19a77848-fcc3-4c98-93d4-8f7ad5b2c18e.png)
> 
> Und GitHub:
> 
> > Einige Zitate
> 
> VS Code hat einen Hintergrund, ist aber trotzdem grau:
> 
> ![Bild](https://user-images.githubusercontent.com/55398995/127496595-9713cda2-2784-41f2-841b-0c726ba5b2ad.png)
> 
> Zitate werden in der Regel als semantisch weniger wichtig angesehen als der eigentliche Inhalt. Die Verwendung von Gelb macht es "zu sehr auffällig" und verwechselt auch leicht mit Ermahnungen.
> 
> Ich verstehe, dass wir:
> 
> 1. Versuchen, Konsistenz mit v1 zu erreichen;
> 2. Der Versuch, die Zugänglichkeit im Vergleich zur vorherigen hellgrauen Farbe zu verbessern,
> 
> Aber ich würde immer noch eine abgedunkelte graue Grundfarbe anstelle von Gelb bevorzugen, damit wir uns an die Normen halten, auch wenn wir uns entschieden haben, die Hintergrundfarbe beizubehalten (die meiner Meinung nach besser beseitigt werden sollte – führt zu zusätzlichen visuellen Ablenkungen, wenn manchmal können Zitate sehr lang sein, wie ein ganzer Artikel)
> 
> ### Haben Sie die [Richtlinien für Beiträge zu Themen](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues) gelesen ?
> Jawohl
> 
> ### Wurde dies auf [Canny](https://docusaurus.io/feedback) angefordert ?
> Nein
> 
> ## API-Design
> Ich schlage zwei Änderungen vor:
> 
> 1. Ändern Sie die Farbe in eine graue Farbe (natürlich dunkel genug, um die Zugänglichkeit aufrechtzuerhalten)
> 2. Entfernen Sie die Hintergrundfarbe
> 
> Damit das Zitat:
> 
> 1. Passt sich optisch dem Hauptinhalt an;
> 2. Unterscheidet sich von Ermahnungen
Facebook

**Comment by slorber** [comment]
In https://github.com/facebookincubator/infima/pull/171 I'm reverting to something similar to what we had before, just improving the color contrasts for accessibility.

![image](https://user-images.githubusercontent.com/749374/131364983-ef5319d9-83ed-4c39-ac77-a49c9d844fd2.png)

![image](https://user-images.githubusercontent.com/749374/131365020-a0df084d-8c77-4bd9-9517-a142aec55407.png)


Going to merge and release this very soon, as I think we agree on this change already, but let me know if you have any issue with this updated design.
