### ISSUE TITLE
Update `swizzleAllowedComponents`

### ISSUE THREAD

**Issue by Josh-Cena** [facebook/docusaurus#5263]
## 🐛 Bug Report

The template doesn't really apply, but this issue is just a quick notice that the `swizzleAllowedComponents` in `theme-classic` hasn't been updated for long. A lot of small components should be swizzlable without the `--danger` flag.

Some components that almost certainly should be added:

- `BackToTopButton`;
- `Details`;
- `EditThisPage`;
- `IconExternalLink`;
- `IconLanguage`;
- ...

**Comment by slorber** [comment]
Yes, agree.

I'll update this list once I add the "slots/placeholders component" that I mentioned in another issue.

If you want to update it, feel free to submit a PR. As a general rule I'd say we should mark swizzle as not dangerous as long as the comp is purely UI-related, with a small and clean API (props/context usage) and does not contain complicated complex Docusaurus login. (DocSidebar should rather be moved to --danger for example)
