### ISSUE TITLE
Error building docs with blog when trailingSlash is false

### ISSUE THREAD

**Issue by FZambia** [facebook/docusaurus#5267]
## 🐛 Bug Report

When running `yarn build` for https://github.com/centrifugal/centrifugal.dev repo I get the following:

```
Unable to build website for locale "en".
Error: ENOENT: no such file or directory, open '/Users/fz/centrifugal.dev/build/blog/2020/02/10/million-connections-with-centrifugo/index.html'
error Command failed with exit code 1.
```

This happened after I turned on `trailingSlash: false` option which was previously `undefined`. There is really no such file on a disk since  `trailingSlash: false` generates only one file for a blog post in a path `/Users/fz/centrifugal.dev/build/blog/2020/02/10/million-connections-with-centrifugo.html`

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [ ] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io
- [ ] I have read the console error message carefully (if applicable)

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

No

## Steps to reproduce

```
git clone https://github.com/centrifugal/centrifugal.dev.git
cd centrifugal.dev
yarn install
yarn build
```

## Expected behavior

Docs successfully build

## Actual behavior

The mentioned error raised

## Your environment

- Docusaurus version used: 2.0.0-beta.9e615eff0
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): Macos Big Sur 11.2.3

**Comment by slorber** [comment]
Hey, investigated this and it's a bug in the third-party local search plugin that you are using. 

There's an existing issue, hopefully, it will be solved soon: https://github.com/easyops-cn/docusaurus-search-local/issues/100

BTW, are you migrating from MkDocs? Curious how has been your experience so far and what were your motivations, considering both tools try to solve a similar problem.

Also, we'd be happy to showcase your site here: https://docusaurus.io/showcase

**Comment by FZambia** [comment]
@slorber hello, thanks for a quick response – will follow the linked issue.

> BTW, are you migrating from MkDocs? Curious how has been your experience so far and what were your motivations, considering both tools try to solve a similar problem.

Initially I mostly liked the out-of-the-box typography and a more simple way to create/customize front page. And dark theme switcher of Docusaurus. On a later stage I really liked to possibility to write custom React components – this allowed me to quickly add inline [config converter in the migration guide](https://centrifugal.dev/docs/getting-started/migration_v3#v2-to-v3-config-converter). Also built-in first class support for blog – with mkdocs it's possible but without tags, pagination etc (at least it was not possible before). So mostly a very good experience so far.

> Also, we'd be happy to showcase your site here

Thanks, I'll try to add it after Centrifugo v3 release.

**Comment by slorber** [comment]
Thanks, that's valuable feedback for me. Don't hesitate to report here if you feel there are some things you liked in MkDocs but do not exist in Docusaurus.

**Comment by weareoutman** [comment]
@FZambia try `"@easyops-cn/docusaurus-search-local": "^0.19.0"`

**Comment by FZambia** [comment]
@weareoutman just successfully deployed with suggested version and `trailingSlash: false`. Many thanks!
