### ISSUE TITLE
Docusaurus Dev Server Header Linking

### ISSUE THREAD

**Issue by jquilliams-intellective** [facebook/docusaurus#5272]
### Prerequisites

- [x] I'm using the latest version of Docusaurus.
- [x] I have tried the `npm run clear` or `yarn clear` command.
- [x] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [x] I have tried creating a repro with https://new.docusaurus.io
- [x] I have read the console error message carefully (if applicable)

### Description

When using the Docusaurus Dev Server, links to headings in a different documents have some weird behavior: 

- Clicking links sends users to the specified heading, but images in document "push" the user's view away from the specified heading. 
- Typing header URLs in the address bar only lands the user at the top of the specified document, not at the heading. 

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## Steps to reproduce

Use https://new.docusaurus.io to create a CodeSandbox reproducible demo of the bug.

1. Navigate to a large .md document with multiple headings and images and where you have to scroll down. 
2. Copy the link to the heading of your choice
3. Create a link in a separate document pointing directly to that document's heading. After Docusaurus reloads, click the created link. 
4. Navigate to the homepage, to another portion of the same page, or another page entirely and paste the link to the heading in the address bar and hit 'Enter'

## Expected behavior

When linking a header from one document to another, it is expected for the browser to land directly on the document header specified, regardless of page or content within page. 

## Actual behavior

When clicking on the link, instead of it landing on the header within the specified document, the browser will land on outside the header. Sometimes with the specified header highlighted in the ToC. In files without images, the created link to the header will work as there are no images to load, therefore not offsetting the position within the document. 

However, when outside the document in question, attempting to go to the document's header via address bar will result in the user ending up at the beginning of the document. Unless within the document, then when the browser loads, the position within the document will be exactly where the user left. However, typing a different header link within the address bar and executing within the specified document will send the user to the new specified heading. 

The static build server is NOT affected by this issue; only the development server is affected. 

## Your environment

- Public source code: N/A
- Public site URL: N/A
- Docusaurus version used: 2.0.0-beta.4
- Environment name and version (e.g. Chrome 78.0.3904.108, Node.js 10.17.0): 
    - Edge version 92.0.902.62 (64-bit)
    - Firefox version 90.0.2 (64-bit)
    - Node.js 14.17.1
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): Win 10 Pro Version 21H1

## Reproducible demo

Use https://new.docusaurus.io to create a CodeSandbox reproducible demo of the bug.

https://codesandbox.io/s/crimson-hill-1eqnw

**Comment by slorber** [comment]
This is a long text for a small issue 😅 
You could just say that in dev, this link does not lead to the correct scroll position, using Docusaurus website as an example: http://localhost:3000/docs/#comparison-with-other-tools

Dev bugs related to anchors have been common in the past. Hopefully, we could make them work as in prod.

**Comment by Josh-Cena** [comment]
Closing in favor of #3081. This has been a really long-standing issue.
