### ISSUE TITLE
Make npm dist-tags point to the correct `latest`, `next` and `canary` releases

### ISSUE THREAD

**Issue by HonkingGoose** [facebook/docusaurus#5274]
## 💥 Proposal

Make npm dist-tags point to the correct `latest`, `next` and `canary` releases.

### Description of problem

Right now it's really difficult to tell a dependency management bot what versions of Docusaurus you care about. This is in part because of the way that the npm dist-tags are used.

Right now I must manually filter out "unstable" releases, with a regex, to get Renovate bot to give me the correct updates. This means that I cannot easily switch between versions. Sometimes I'd really like the latest `canary` but that conflicts with my regex that only gives me stable releases. Renovate supports a `followTag` option which you can use to point to a dist-tag, this won't work properly right now, with the way Docusaurus uses the dist-tags.

### How did I get this idea?

I had a discussion with the creator and one of the head maintainers of Renovate bot (@rarkins), talking about my problems with the Docusaurus versioning.

I've picked the most relevant highlights from https://github.com/renovatebot/renovate/discussions/10948, but please read the whole discussion to get the full picture.

### Highlights of discussion

_The head maintainer of Renovate bot said:_

> The docusaurus maintainers could make life easier in general using npm's dist-tags, although probably not to the point where you can easily switch between tags _and_ have Renovate know what you're doing.
> 
> Right now they have these:
> <img alt="image" width="308" src="https://user-images.githubusercontent.com/6311784/127285991-f6a1fd9c-ccea-4bac-a678-4f944ad0b5ec.png">
> 
> In theory they should have latest, next and canary pointing to stable, beta and canary respectively. Renovate could be used to follow such tags (`followTag`) feature but can't automatically switch that itself.

_I said:_

> Checking to see if I understand your idea, the `dist-tags` should be like this:
> 
> ```gfm
> dist-tags:
>   latest: "1.14.7"
>   next: "2.0.0-beta.3"
>   canary: "2.0.0-beta.a7618c775"
> ```
> 
> How much work would it be for them to make this change? I'm not sure if it's reasonable for me to ask for things like this???

_Head maintainer of Renovate bot:_

> Yes, that's how I'd recommend doing it. Without this, the semver spec has no real way to differentiate between the "semi-stable" beta versions and the canary ones.
> The amount of work depends on whether they have an automated system for publishing or not..

### Conclusion:

I hope I'm not asking for too much work/effort on your part with this proposal.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes.

**Comment by slorber** [comment]
Hey

I don't understand exactly what you are asking me to do.

BTW, the dist tags you mention are related to the v1 Docusaurus package (https://www.npmjs.com/package/docusaurus?activeTab=versions), not v2 which has only latest/canary (https://www.npmjs.com/package/@docusaurus/core?activeTab=versions). 

If v1 package was wrongly published with v2 versions, it's a mistake and only due to a legacy bad publish logic that we removed. To avoid confusion I'll try to remove the dist tags on v1 package.

**Comment by rarkins** [comment]
Hi, part of the confusion was probably me checking the `docusaurus` tags and forgetting about `@docusaurus/core`. The tagging in your screenshot above looks perfect to me. That way users could utilize Renovate's `followTag` functionality to decide to follow `canary` releases.

FYI by default Renovate shouldn't 
- upgrade from an existing stable version to an unstable
- upgrade past `latest` if it wasn't already

Things might get a little funky when `latest` is unstable from semver point of view, but we should make it work if it doesn't already.

Something about using commit hashes for versions is that they will at times fluctuate to sort less than OR greater than the current `latest`, e.g. `2.0.0-beta.1dce56d9a` would be less than `2.0.0-beta.4` in semver sort. Therefore to use `canary` and stay on it Renovate users should use `"followTag": "canary"` which removes all the above sorting and rules and simply raises a PR any time your current `package.json` version does not match the tag on npm.

**Comment by slorber** [comment]
Thanks

I've investigated the canary issues we have and can clearly see the problem. 

Replacing the existing version names by an auto-increasing name: https://github.com/facebook/docusaurus/pull/5285

Not sure there's anything to do for this issue so I'm going to close but happy to continue discussing how to improve things

**Comment by HonkingGoose** [comment]
I think this issue is done now! Thank you for the quick response and helpful comments! ❤️ 

Thank you @slorber for fixing the `canary` tag weirdness with #5285. This will help me out a lot the next time I really want a feature/bug-fix _now_, without waiting for a full-fat release. 😄
