### ISSUE TITLE
Syncing tab choices section is missing on latest version

### ISSUE THREAD

**Issue by faloi** [facebook/docusaurus#5278]
## 📚 Documentation

The **Syncing tab choices section** that [Code blocks](https://docusaurus.io/docs/markdown-features/code-blocks#syncing-tab-choices) section refers to is missing.

![section-missing](https://user-images.githubusercontent.com/1585835/128079816-37800459-b6b3-42cc-82a6-076e79b28e98.gif)

Searching within the pull requests of this repo, I've found that the section was actually there some time ago: [markdown-features.mdx](https://github.com/facebook/docusaurus/blob/c0c7a322e0940e9e878fc5e1b504a4d519bb8394/website/docs/markdown-features.mdx). Perhaps it was misplaced when moving to the new docs folder structure?

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes.

**Comment by lex111** [comment]
This section is now available on the Tabs page https://docusaurus.io/docs/next/markdown-features/tabs#syncing-tab-choices

Thank you for reporting this, the link will be fixed in https://github.com/facebook/docusaurus/pull/5283
