### ISSUE TITLE
TS2709: Cannot use namespace 'ThemedImageProps' as a type.

### ISSUE THREAD

**Issue by hhimanshu** [facebook/docusaurus#5282]
## 🐛 Bug Report
Hello, 
I am learning to use the project and went through https://docusaurus.io/docs/typescript-support. As I look in my IDE (Webstorm), I see error like the following

![image](https://user-images.githubusercontent.com/6589036/128098759-6bb03774-5b2f-4907-be36-3330b36b52cb.png)

The relevant codebase is at https://github.com/hhimanshu/docusaurus-101/blob/main/src/theme/Footer/index.tsx#L55

Could you please let me know if I am missing anything?

### Prerequisites

- [x] I'm using the latest version of Docusaurus.
- [ ] I have tried the `npm run clear` or `yarn clear` command.
- [ ] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io
- [ ] I have read the console error message carefully (if applicable)

### Description

(A clear and concise description of what the bug is.)

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

(Write your answer here.)

## Steps to reproduce

Use https://new.docusaurus.io to create a CodeSandbox reproducible demo of the bug.

(Write your steps here:)

- Clone the project
- yarn install
- Follow steps in https://docusaurus.io/docs/typescript-support
- Check in IDE

## Expected behavior

(Write what you thought would happen.)

## Actual behavior

(Write what happened. Add full console log messages and screenshots, if applicable.)

## Your environment

- Public source code: https://github.com/hhimanshu/docusaurus-101/
- Public site URL:
- Docusaurus version used: 2.0.0-beta.4
- Environment name and version (e.g. Chrome 78.0.3904.108, Node.js 10.17.0): v14.17.4
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): OSX 10.15.4

## Reproducible demo

Use https://new.docusaurus.io to create a CodeSandbox reproducible demo of the bug.

(Paste the link to an example repo, including a `docusaurus.config.js`, and exact instructions to reproduce the issue.)

**Comment by Josh-Cena** [comment]
Weird, I think you must be missing something there:

![image](https://user-images.githubusercontent.com/55398995/128099518-5fc37faf-fd73-4a8a-9fa5-a15e28c77358.png)

Maybe try `yarn build:packages` and `yarn install` first?

**Comment by slorber** [comment]
Agree with your solution @Josh-Cena , and tested it, it works fine. That would  be nice to make it useless to have this extra type file but not sure how to do that.

We should add this to our doc until we find a solution

**Comment by Josh-Cena** [comment]
@slorber Definitely. Also I'm trying to make TS dev easier with #5233

**Comment by slorber** [comment]
This should be solved by https://github.com/tsconfig/bases/pull/70

**Comment by hhimanshu** [comment]
Thank you @Josh-Cena , that made the difference

**Comment by slorber** [comment]
@hhimanshu another option is to use in tsconfig:

```json
{
  "compilerOptions": {
    "types": [
      "node",
      "@docusaurus/module-type-aliases",
      "@docusaurus/theme-classic"
    ]
  }
}
```

**Comment by hhimanshu** [comment]
@slorber , I can confirm that this change works as well. THANK YOU
