### ISSUE TITLE
You may need an appropriate loader to handle this file type

### ISSUE THREAD

**Issue by hhimanshu** [facebook/docusaurus#5286]
### Prerequisites

- [x] I'm using the latest version of Docusaurus.
- [ ] I have tried the `npm run clear` or `yarn clear` command.
- [ ] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io
- [ ] I have read the console error message carefully (if applicable)

### Description

I am following the example of https://docusaurus.io/docs/markdown-features/react#importing-markdown and it fails

## Steps to reproduce
1. Clone https://github.com/hhimanshu/docusaurus-101
2. yarn install and yarn start

## Expected behavior

The app should have loaded correctly as per documentation

## Actual behavior

The app fails with following error
```
Failed to compile
Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> <span>Hello {props.name}</span>
| 
| This is text some content from `_markdown-partial-example.mdx`.
This error occurred during the build time and cannot be dismissed.

```

## Your environment

- Public source code: https://github.com/hhimanshu/docusaurus-101
- Public site URL:
- Docusaurus version used:
- Environment name and version (e.g. Chrome 78.0.3904.108, Node.js 10.17.0):
- Operating system and version (e.g. Ubuntu 20.04.2 LTS):

## Reproducible demo

Use https://new.docusaurus.io to create a CodeSandbox reproducible demo of the bug.

(Paste the link to an example repo, including a `docusaurus.config.js`, and exact instructions to reproduce the issue.)

**Comment by slorber** [comment]
Which file are you importing where exactly?

Try putting both docs in the same folder.

You can't import a file at the root of your repo currently, it's a known
limitation that I'll try to solve.


Le mer. 4 août 2021 à 20:56, Harit Himanshu ***@***.***> a
écrit :

**Comment by hhimanshu** [comment]
Hey @slorber , the file I am trying to import is a relative import. See [here](https://github.com/hhimanshu/docusaurus-101/blob/main/blog/2021-08-03-my-thought-process.md#import-markdownmdx-files)

Ideally, I would like blogs to have folders like
```
blog/
       2021-08-01/
                           index.md
                           _partial.md
                          images/
                                      one.jpeg
                                      two.jpeg

      2021-08-04/
                           index.md
                           _partial-1.md
                          images/
                                      three.jpeg
                                      four.jpeg

```

But, I am not sure if this is a possibility

**Comment by cveilleux** [comment]
I don't know if it is related, but we have started having build failures in the last 4 hours:

```
Module parse failed: Unexpected token (6:128)
File was processed with these loaders:
 * ./node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
|  * This source code is licensed under the MIT license found in the
|  * LICENSE file in the root directory of this source tree.
>  */import React from'react';var ThemeContext=/*#__PURE__*/React.createContext(undefined);ThemeContext.displayName="ThemeContext"export default ThemeContext;
Client bundle compiled with errors therefore further build is impossible.
```

package.json:

```
  "dependencies": {
    "@docusaurus/core": "2.0.0-beta.4d06f26c1",
    "@docusaurus/preset-classic": "2.0.0-beta.4d06f26c1",
    "@mdx-js/react": "^1.6.21",
    "clsx": "^1.1.1",
    "react": "^17.0.1",
    "react-dom": "^17.0.1"
  },
```

I have a build that passed at 3pm today and is now failing at 6pm (same exact code-base).

**Comment by Josh-Cena** [comment]
@cveilleux Can verify. Even the CI here are failing:

https://github.com/facebook/docusaurus/pull/5284/checks?check_run_id=3247384304

Maybe you can open another issue as this looks like a different bug, but keeping it here is fine as well

**Comment by csestito** [comment]
Same as  #5287 I was able to narrow it down to @babel/plugin-transform-react-display-name. Adding the below snippet to my docusaurus config seems to fix it for me.
```
"resolutions": { "@babel/plugin-transform-react-display-name": "7.14.5" },
```

**Comment by lex111** [comment]
Apparently a bug was in our dependency babel core, so they just released new version, which should fix this issue.
Try to reinstall all dependencies completely, removing our `node_modules` directory beforehand.

**Comment by slorber** [comment]
@hhimanshu there are 2 bugs here.
- The first is a known limitation of Docusaurus that we'll fix. MD files must currently be in `docs`, `blog` or `src/pages` folder, unfortunately, other places do not work.
- Second is a temporary babel bug that we have since a few hours: https://github.com/facebook/docusaurus/issues/5287

**Comment by hhimanshu** [comment]
@slorber , I changed the location of `mdx` file AND also re-installed dependencies. I confirm that it work for me. 
[Here is the commit](https://github.com/hhimanshu/docusaurus-101/commit/02cf9d07124439ccf520be0b207bb193ac4b8e51)

![image](https://user-images.githubusercontent.com/6589036/128351788-df817e2f-64e1-4cb1-a53f-15510f7f798d.png)


THANK YOU for all your help, very much appreciate it

**Comment by slorber** [comment]
@hhimanshu with https://github.com/facebook/docusaurus/pull/5299 you should be able to put mdx files in `src/components` soon

**Comment by hhimanshu** [comment]
Fantastic, thank you @slorber.
