### ISSUE TITLE
ThemeContext.js You may need an additional loader to handle the result of these loaders

### ISSUE THREAD

**Issue by frontdog** [facebook/docusaurus#5291]
### Prerequisites

- [x] I'm using the latest version of Docusaurus.
- [x] I have tried the `npm run clear` or `yarn clear` command.
- [x] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [x] I have tried creating a repro with https://new.docusaurus.io
- [x] I have read the console error message carefully (if applicable)

### Description
```
Module parse failed: Unexpected token (6:130)
File was processed with these loaders:
 * ../../node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
|  * This source code is licensed under the MIT license found in the
|  * LICENSE file in the root directory of this source tree.
>  */import React from'react';const ThemeContext=/*#__PURE__*/React.createContext(undefined);ThemeContext.displayName="ThemeContext"export default ThemeContext;
```

**Comment by weisisheng** [comment]
Believe one and the same--> https://github.com/facebook/docusaurus/issues/5286

**Comment by junsulee75** [comment]
I was about to raise the same issue and happy to see someone opened already.
Just adding some of my observation too.

When creating new docusaurus doc, I saw this error running 'yarn start'. 
Latest version is 2.0.0-beta.4. 
As I had been using 2.0.0-beta.3 for my existing ones, tried that version for new but still the same error.
I don't think there is problem on 'node_modules/babel-loader/lib/index.jsnode_modules/babel-loader/lib/index.js'.
The file has not been changed.

From 'Unexpected token (6:130)', seeing the error code line, it's around right before 
'export default ThemeContext;'.
I suspect missing semi-colon (;) might matter.

**Comment by frontdog** [comment]
I copy the code of lib/theme/ThemeContext.js into lib-next/theme/ThemeContext.js and it works. So is something wrong to configuration of webpack？

**Comment by lex111** [comment]
Apparently a bug was in our dependency babel core, so they just released new version, which should fix this issue.
Try to reinstall all dependencies completely, removing your `node_modules` directory beforehand.
