### ISSUE TITLE
TOC item should not be highlighted if below the viewport 

### ISSUE THREAD

**Issue by pranabdas** [facebook/docusaurus#5318]
## 💥 Proposal

The first TOC item is highlighted/active even it is below the viewport. I think the first item should be highlighted once it is scrolled inside viewport.

<img width="1217" alt="TOC_active_link" src="https://user-images.githubusercontent.com/31024886/128619595-224dfee9-51a7-46ba-a497-4a98d7444662.png">

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

**Comment by slorber** [comment]
Thanks, added the TOC to our very long changelog page and can see those issues as well as a few others: 
- https://github.com/facebook/docusaurus/pull/5331
- https://deploy-preview-5331--docusaurus-2.netlify.app/community/changelog

**Comment by slorber** [comment]
fixed in https://github.com/facebook/docusaurus/pull/5361, try canary and let me know if this works fine

cc @sw-yx

**Comment by pranabdas** [comment]
@slorber yes, my issue is fixed. Thank you!
