### ISSUE TITLE
code block issue in rtl language

### ISSUE THREAD

**Issue by farshidinanloo** [facebook/docusaurus#5324]
### Prerequisites

- [x] I'm using the latest version of Docusaurus.
- [x] I have tried the `npm run clear` or `yarn clear` command.
- [x] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [x] I have tried creating a repro with https://new.docusaurus.io
- [x] I have read the console error message carefully (if applicable)

### Description

code block in rtl language have problem it doesnt scroll in mobile
[
![Capture](https://user-images.githubusercontent.com/46605967/128812960-0b00593f-49f8-4b8e-8a08-e2e68cac148a.PNG)
](url)

and when I use `float: left` for this part it fixed.
```
.codeBlockLines_node_modules-\@docusaurus-theme-classic-lib-next-theme-CodeBlock-styles-module{
  float: left
}
```
![1](https://user-images.githubusercontent.com/46605967/128813169-b988a75e-65f4-4cda-81af-2b0f0a9ac349.PNG)

and in custom.css when I changed it to `float: left `it again replace it with `float: right`

**Comment by slorber** [comment]
Hey

This site is using RTL support: https://datagit.ir/docs/python/beginner/data_types/string

And it seems to scroll correctly on mobile:

![image](https://user-images.githubusercontent.com/749374/128847504-c09729ee-6c01-49b4-af69-71a801303088.png)

>  I have tried creating a repro with https://new.docusaurus.io

You checked the box but didn't provide any link. I won't be able to help you unless you provide a repro, unfortunately.

**Comment by slorber** [comment]
Thanks, will be fixed by https://github.com/facebook/docusaurus/pull/5357

Can you add your RTL website to our showcase once ready? We don't have much RTL sites showcased and a new one is welcome
