### ISSUE TITLE
plugin-ideal-image: Multiple assets emit different content to the same filename 

### ISSUE THREAD

**Issue by Pierre-Gilles** [facebook/docusaurus#5326]
Thanks for building Docusaurus! 

## 🐛 Bug Report

I noticed a small bug when migrating from Docusaurus alpha to Docusaurus beta on the ideal-image plugin on this repo (https://github.com/GladysAssistant/v4-website) 

When I run `docusaurus start`, I get an error: 

```
✖ Client
  Compiled with some errors in 20.66s

Conflict: Multiple assets emit different content to the same filename assets/ideal-img/smart-plug.100.jpg
```

I don't get the error when building the website, only when developing locally.

The bug seems to come from this line: 

https://github.com/facebook/docusaurus/blob/master/packages/docusaurus-plugin-ideal-image/src/index.ts#L46

As seen here, a hash is added to the filename in production, but not in dev, so it creates a problem: if there is 2 images with the same name in the project (in different folders, quite common), then it throws this error.

It seems that the bug was already present before but Webpack 5 seems more strict and showed the error.

I can do a PR to try adding a hash to the image in development, do you think it's the correct way of fixing this?

Thanks for your time and for your answer! 🙏

**Comment by slorber** [comment]
Hey!

This is weird because I remember having fixed this (or something very similar) a few months ago 😅 

Yes using the hash in dev seems fine to me, you can send a PR

**Comment by Pierre-Gilles** [comment]
PR done here: https://github.com/facebook/docusaurus/pull/5334

Let me know if it needs more tests / or if it needs change ! :)
