### ISSUE TITLE
Text in Tabs is not searchable 

### ISSUE THREAD

**Issue by tmuskin** [facebook/docusaurus#5344]
### Description

Some pages are using [tabs](https://docusaurus.io/docs/next/markdown-features/tabs) to organize information. We are using docusaurus-lunr-search as our search engine. When we try searching for information that is in the tabs it does not show in the search results.  

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes. 

## Steps to reproduce

1. Go go [CodeSandbox](https://codesandbox.io/s/cranky-framework-yhp9z?file=/docs/tab_bug.md)
2. Try to search for anything that is underneath a tab section (there are tabs in the Tab Bug section under tutorial)

## Expected behavior

Information that is in tabs is searched for and comes up in the search results 

## Actual behavior

The tabs pages do not come up in the search results 

## Your environment

Search engine is generated using docusaurus-lunr-search
Tabs are created using [the documentation on tabs from Docusarus](https://docusaurus.io/docs/next/markdown-features/tabs)

## Reproducible demo

See [CodeSandbox](https://codesandbox.io/s/cranky-framework-yhp9z?file=/docs/tab_bug.md) and try to search for information that is underneath tabs.

**Comment by slorber** [comment]
Hi,

Lunr is not an official Docusaurus core plugin and we don't provide support for it.

What you can see is that all the tabs content is in the static HTML file (unless you use the lazy=true prop):

![image](https://user-images.githubusercontent.com/749374/129190748-088dfb15-1d7f-4821-b829-08f8e4a0d7ad.png)

This is the responsibility of the Lunr plugin to index correctly the content of hidden tabs, and you should report the issue on the plugin repo directly.

**Comment by tmuskin** [comment]
I reported it in the plugin repo [here](https://github.com/lelouch77/docusaurus-lunr-search/issues/66) and included the plugin to my repro.
