### ISSUE TITLE
a vulnerability is introduced in docusaurus

### ISSUE THREAD

**Issue by ayaka-kms** [facebook/docusaurus#5348]
Hi, a vulnerability https://snyk.io/vuln/SNYK-JS-AUTOLINKER-564438 is introduced in docusaurus@1.14.7  via:
●  docusaurus@1.14.7 ➔ markdown-toc@1.2.0 ➔ remarkable@1.7.4 ➔ autolinker@0.28.1

However, markdown-toc is a legacy package, which has not been maintained for about 4 years.
Is it possible to migrate markdown-toc to other package to remediate this vulnerability?

I noticed a migration record in other js repo for markdown-toc:

●  in **roboter**, version 3.0.4 ➔ 4.0.0, migrate **markdown-toc** to **remark** and **remark-toc** via [commit](https://github.com/thenativeweb/roboter/pull/74)

Thanks.

**Comment by slorber** [comment]
Hi

v1 is in low-maintenance mode and we only provide security fix being real security issues for our users.

In this case, there is an issue in a transitive dependency, but it's not affecting users in practice:
- The vulnerable code path is only used when using the Remarkable [linkify](https://github.com/jonschlinkert/remarkable#linkify-plugin) plugin, which we don't
- The vulnerability can only arise if you let users add malicious code in markdown headings, which you should review anyway

For those reasons, I'm closing and don't plan to work on fixing a warning that some audit tool may have reported you.

See also:
- Dan Abramov thinking about NPM Audit: https://overreacted.io/npm-audit-broken-by-design/
- Answers from Snyk members for a similar case we previously had: https://twitter.com/sebastienlorber/status/1394717461455544323


If you are willing to fix it yourself, I'd merge the PR (unless it's painful and time-consuming to review, risky...)
