### ISSUE TITLE
blogSidebarTitle: 'Recent posts' seems not translated

### ISSUE THREAD

**Issue by khoshrou** [facebook/docusaurus#5350]
Hi
I couldn't find a tag name for "Recent Posts" to translate, 
seems its not translated.
Is it translatable?

I have three locales: en, fa, ar

**Comment by slorber** [comment]
Thanks for reporting. 
I'm tracking remaining untranslatable labels here so I'm closing this issue: https://github.com/facebook/docusaurus/issues/4542
