### ISSUE TITLE
Blog: `postsPerPage` should accept `'ALL'`

### ISSUE THREAD

**Issue by Josh-Cena** [facebook/docusaurus#5353]
## 🚀 Feature

`postsPerPage` should accept `'ALL'`, similar to `blogSidebarCount`.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yep

### Has this been requested on [Canny](https://docusaurus.io/feedback)?

No

## Motivation

Sometimes we don't care about pagination, perf, etc., especially if we have swizzled the blog list page. Having an `'ALL'` field is better than setting `postsPerPage: 10000`.

I'd be willing to build this myself.

**Comment by slorber** [comment]
👍 why not, thanks for working on this

**Comment by lex111** [comment]
Just curious, in what cases precisely might this feature really be necessary? I never heard of blog without page navigation -- it's very strange, and very rare usecase. Maybe we should open this feature request on Canny first?

**Comment by Josh-Cena** [comment]
> Just curious, in what cases precisely might this feature really be necessary? I never heard of blog without page navigation -- it's very strange, and very rare usecase. Maybe we should open this feature request on Canny first?

For example, I have swizzled blog list page and made it a cascade view instead of paginated view. Since pagination is handled during content loading, there's no way for me to display all posts on one page just through the theme.

**Comment by slorber** [comment]
It make sense to me, I've seen a few times blogs without pagination presented with a card mosaic or other similar patterns. It probably makes more sense when there is a limited number of posts though. `ALL` is just a better way to avoid a "magic value" like 10000.
