### ISSUE TITLE
Received malformed response from registry for "docusaurus-preset-name". The registry may be down.

### ISSUE THREAD

**Issue by DannyS03** [facebook/docusaurus#5358]
### Prerequisites

- [x] I'm using the latest version of Docusaurus.
- [x] I have tried the `npm run clear` or `yarn clear` command.
- [x] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [x] I have tried creating a repro with https://new.docusaurus.io
- [x] I have read the console error message carefully (if applicable)

### Description

It seems this package has been removed? https://www.npmjs.com/package/docusaurus-preset-name
Cannot add (or use) docusaurus preset package. Seems like registry is not accessible or down.

Docs are still the same: https://docusaurus.io/docs/presets#using-presets

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## Steps to reproduce

Use https://new.docusaurus.io to create a CodeSandbox reproducible demo of the bug.

1. Run: `yarn add docusaurus-preset-name`

## Expected behavior

Package to install successfully (like before).

## Actual behavior

```
yarn add v1.22.11
[1/4] 🔍  Resolving packages...
error Received malformed response from registry for "docusaurus-preset-name". The registry may be down.
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```

```
[1/4] Resolving packages...
[2/4] Fetching packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/docusaurus-preset-name/-/docusaurus-preset-name-1.0.0.tgz: Request failed \"404 Not Found\"".
```

## Your environment

- Public source code: https://github.com/w3f/polkadot-wiki
- Public site URL: https://wiki.polkadot.network/
- Environment name and version (e.g. Chrome 78.0.3904.108, Node.js 10.17.0):
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): macOS Big Sur 11.2.3

**Comment by Josh-Cena** [comment]
lol now I see why people on Discord are asking about `docusaurus-preset-name` 🤦‍♂️

This is only supposed to be a dummy example, if you have initialized with `classic` template you should have `docusaurus-preset-classic` already

Maybe we should change the doc to avoid confusion

**Comment by slorber** [comment]
Fixed in https://github.com/facebook/docusaurus/pull/5372

FYI I'd like to simplify this preset thing. It's likely we'll ever have a single official preset that 99% of users will use so we should probably bias toward its usage
