### ISSUE TITLE
Open Graph tags missing required property of og:type

### ISSUE THREAD

**Issue by johnnyreilly** [facebook/docusaurus#5373]
### Prerequisites

- [x] I'm using the latest version of Docusaurus.
- [x] I have tried the `npm run clear` or `yarn clear` command.
- [x] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [x] I have tried creating a repro with https://new.docusaurus.io
- [x] I have read the console error message carefully (if applicable)

### Description

[Open Graph tags are amazing](https://ogp.me/) and I've been reading up on them.  There's four that are required:

> `og:title` - The title of your object as it should appear within the graph, e.g., "The Rock".
> `og:type` - The type of your object, e.g., "video.movie". Depending on the type you specify, other properties may also be required.
> `og:image` - An image URL which should represent your object within the graph.
> `og:url` - The canonical URL of your object that will be used as its permanent ID in the graph, e.g., "https://www.imdb.com/title/tt0117500/".

Docusaurus does not provide `og:type` at present.  It would be good if it did; perhaps with a value of `website` or `article`. eg:

```html
<meta property="og:type" content="article" />
```

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues)?

Yes

## Steps to reproduce

Look at the og tags on the docusaurus website: https://docusaurus.io/blog

## Expected behavior

To have an `og:type` tag

## Actual behavior

Does not have `og:type` tag

## Your environment

All environments

## Reproducible demo

Look at the og tags on the docusaurus website: https://docusaurus.io/blog

Given the work in https://github.com/facebook/docusaurus/pull/5355 @lex111 - I wondered if you might have thoughts on this too.

**Comment by lex111** [comment]
According to [this page](https://developers.facebook.com/docs/sharing/webmasters?locale=en#basic), og:type is additional type and provides default value (`website`) if it is not specified. We can probably use og:type `article` on blog pages, but is it really necessary?

**Comment by johnnyreilly** [comment]
The page linked to is how Facebook use the Open Graph tags; so whilst the lack of `og:type` shouldn't be an issue with Facebook, Open Graph metadata is consumed by many other platforms; Twitter, Google etc who may make different choices.

Even if we just supply the default value of:

```html
<meta property="og:type" content="website" />
```

it will then be explicitly specified and also opens the possibility for more customisation further down the line.

I've been slightly going down the rabbit hole of reading about all this stuff, I'd quite like the ability for us to do more in this space in future perhaps.  Not quite sure what that would look like, feels like a combination of `docusarus.config.js` and Frontmatter could be combined to provide even more amazing metadata!

**Comment by lex111** [comment]
This is a quote from OG protocol, so if `og:type` is not specified, `website` should be used as default value. Therefore for Google and others platforms, missing `og:type` should not be problem. 

> Any non-marked up webpage should be treated as og:type website.

**Comment by johnnyreilly** [comment]
Good find

**Comment by slorber** [comment]
PRs welcome to add that type

Was wondering what type is a doc page and shouldn't we add relevant structured data on docs too?

**Comment by johnnyreilly** [comment]
I've got something locally that's pretty generic - I'll put it up for comments. Should serve a number of purposes I think

**Comment by johnnyreilly** [comment]
See related PR: https://github.com/facebook/docusaurus/pull/5375

**Comment by Josh-Cena** [comment]
@johnnyreilly May I know what the state of this issue is? Is `og:type` actually necessary, or is adding the other meta tags sufficient?

**Comment by johnnyreilly** [comment]
I've actually forgotten where this ended up. I don't think any changes have been made - I haven't checked recently and I'm away from a machine right now

**Comment by sh0umik** [comment]
will it ever get fixed or merged ?

**Comment by Josh-Cena** [comment]
Based on the discussion above, we are still unsure whether it's required or even needed. If you want to send a PR to add it, I'm okay to merge it, but this is not prioritized.

@johnnyreilly Any thoughts?

**Comment by johnnyreilly** [comment]
Sorry I think this was resolved with my PR - will close
