### ISSUE TITLE
Custom routes trigger broken links on build

### ISSUE THREAD

**Issue by milesj** [facebook/docusaurus#5374]
### Prerequisites

- [x] I'm using the latest version of Docusaurus.
- [x] I have tried the `npm run clear` or `yarn clear` command.
- [x] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io
- [x] I have read the console error message carefully (if applicable)

### Description

I have a custom plugin that adds `/api/*` routes through `actions.addRoute()`. This whole flow works great. You can see the code here: https://github.com/milesj/docusaurus-plugin-typedoc-api/blob/master/packages/plugin/src/index.ts#L208

However, when running `yarn build`, all the `/api/*` routes fail on broken links, like so:

```
- On source page path = /api/pipeline/class/Context:
   -> linking to /api
   -> linking to /blog

- On source page path = /api/pipeline/class/Monitor:
   -> linking to /api
   -> linking to /blog

- On source page path = /api/pipeline/class/ParallelPipeline:
   -> linking to /api
   -> linking to /blog

- On source page path = /api/pipeline/class/PooledPipeline:
   -> linking to /api
   -> linking to /blog

- On source page path = /api/pipeline/class/Routine:
   -> linking to /api
   -> linking to /blog

- On source page path = /docs/tutorial-extras/manage-docs-versions:
   -> linking to /api
   -> linking to /blog

- On source page path = /docs/tutorial-extras/translate-your-site:
   -> linking to /api
   -> linking to /blog
```

I'm not sure how to resolve this or if this is just an oversight.

The routes _do_ appear in the `.docusaurus/routes.js` file, but not sure if that matters.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues)?

Yes

## Steps to reproduce

> Use https://new.docusaurus.io to create a CodeSandbox reproducible demo of the bug.

Creating a sandbox of this is too complicated. There are 2 ways to verify this though:

1. Clone and checkout this PR which attempts to integrate and test the plugin: https://github.com/milesj/boost/pull/157

```
git clone git@github.com:milesj/boost.git
cd boost
git checkout typedoc
yarn install && yarn run build
cd website
yarn run build
```

2. Install the `docusaurus-plugin-typedoc-api` package and install it in a project: https://www.npmjs.com/package/docusaurus-plugin-typedoc-api

## Expected behavior

The broken links check doesn't fail on custom routes.

## Actual behavior

The broken links check fails on custom routes. 

I can bypass it for now by changing the `onBrokenLinks` setting but this isn't ideal.

## Your environment

- Public source code: https://github.com/milesj/boost/pull/157
- Public site URL: N/A
- Docusaurus version used: 2.0.0-beta.4
- Environment name and version (e.g. Chrome 78.0.3904.108, Node.js 10.17.0): Any node/yarn version
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): MacOS/Ubuntu

**Comment by slorber** [comment]
Hi

Happy to see someone is working on such plugin.
In the long term I'd like to use something like that on the Docusaurus doc, but not sure the TS codebase is in good shape for that.
Feel free to reach on Discord if you need support.

Note we have an issue for TypeDoc support, it could be useful to advertise here: https://github.com/facebook/docusaurus/issues/3413

---

About your problem, that's surprising me because we use React-Router's `matchRoutes(routes,pathname)` API to detect broken links. I've seen you use `path: '/api', exact: false`, maybe worth trying `/api/*` too?

Will investigate soon, I definitively want to support and document such dynamic routes better:
- we have an usecase for the `/feedback` page (currently using a bad legacy redirect on the 404 page... https://docusaurus.io/feedback/p/collapse-expand-all-sections-button-in-sidebar)
- I'd like to showcase how to implement an authenticated part within the Docusaurus site

In the meantime, just use the `onBrokenLinks` temporarily

**Comment by milesj** [comment]
I'll toggle the setting for now.

FWIW, I also tried `/api/*` and it has the same problem.

**Comment by slorber** [comment]
@milesj I've migrated our Feedback page properly using a client-side dynamic route here, and didn't get any broken link reported:

https://github.com/facebook/docusaurus/pull/5389

The problematic part of your code is this:

![image](https://user-images.githubusercontent.com/749374/130121554-208f3042-8fe9-481a-a432-555ee49289cf.png)


This is why you have the FOUC on GitHub page on the index page, and also why Docusaurus doesn't know about this route. It only exists in the runtime of your client-side app, not on the Node.js side.

**Comment by milesj** [comment]
@slorber Aww, that makes sense. 

I'll try moving that to the plugin and attempt to resolve an "index". I ran into issues last time but maybe this plugin is in a better state now.

**Comment by milesj** [comment]
Got it working, thanks for checking.

I have some other things to discuss but I'll create new issues for them.

**Comment by slorber** [comment]
great, looks like it also fixed the 404 issue on https://boostlib.dev/api 👍

**Comment by monica-m-ps** [comment]
@milesj Hello. Can you please share how did you resolve this issue? I just ran into it and still getting broken links errors. I don't want to these errors.

```
- Broken anchor on source page path = /payments/snippets/_handle-errors:
   -> linking to /payments/api#section/Introduction/Errors
   -> linking to /payments/api#section/Introduction/HTTP-Responses
```

This is what the path looks like

```
[error message](/payments/api#section/Introduction/Errors)
```

**Comment by Josh-Cena** [comment]
@monica-m-ps Did you get a warning, or an error? The latest version added the ability to check broken anchor links but it defaults to warning only.

Either way, please stop commenting under closed and resolved issues. Open a new issue or discussion instead.
