### ISSUE TITLE
[2.0] RFC: docusaurus swizzle --wrap/copy

### ISSUE THREAD

**Issue by slorber** [facebook/docusaurus#5380]
## 🚀 Feature

We have a feature to wrap existing theme components:
https://docusaurus.io/docs/using-themes#wrapping-theme-components

```js
import OriginalFooter from "@theme-original/Footer";
import React from "react";

export default function Footer(props) {
  return (
    <>
      <div>Before footer</div>
      <OriginalFooter {...props} />
    </>
  );
}
```

It's a very useful pattern to use to customize your Docusaurus site.
It allows you to enhance a Docusaurus theme without having to copy (and maintain) theme code.

Unfortunately, this feature is not very visible and we don't encourage its usage, as the code above is only found in our doc, and the swizzle CLI command does not produce such code.

Some use-cases:

- Add a custom comp before/after (above/under) any existing theme component (like add comments to blog posts)
- Slightly modify the layout/behavior of an existing theme component (like, add line numbers to code blocks)
- Add custom MDX components

---

I suggest to do some changes:

- Add a `docusaurus swizzle --wrap` option to produce such code. It wouldn't require the usage of `--danger` because it's way safer than copying.
- For copying, require explicit usage of `--copy` option, keep `--danger` for unsafe components and suggest to prefer usage of `--wrap`
- No option: suggest use either `--wrap` or `--copy`, hint to prefer `--wrap`

---

Other changes to consider in the long term:

- Rename `docusaurus swizzle` to something more intuitive like `docusaurus theme`?
- Create much smaller theme components, so that users naturally have more before/after wrapping possibilities to suit their use-cases.

**Comment by Josh-Cena** [comment]
> Rename `docusaurus swizzle` to something more intuitive like `docusaurus theme`?

1. I like `swizzle` because it sounds funky :P
2. We probably want a verb here instead of a noun
3. Agree that `swizzle` is not intuitive enough

> Create much smaller theme components, so that users naturally have more before/after wrapping possibilities to suit their use-cases.

Agreed. I also think a more hierarchical component structure is better than crowding `src/theme` with all kinds of components, making navigation and understanding the components' usage easier.

No strong feelings about extending the CLI. I think we can make it fully interactive (just like `docusaurus-init`) so that running `docusaurus swizzle` will prompt you for wrap/copy, the theme, and the component, step by step.

**Comment by slorber** [comment]
I created a swizzle meta issue here: https://github.com/facebook/docusaurus/issues/6114

We can probably keep this one open to have more focused discussions on this specific topic

**Comment by Josh-Cena** [comment]
From what I imagine, `swizzle --wrap` would just be trivially a string interpolation :man_shrugging: 

```ts
fs.writeFileSync(`src/theme/${component}.js`, `
import React from 'react';
import ${component} from '@theme-original/${component}';

export default function Wrapped${component.replaceAll('/', '')}(props) {
  return (
    <>
      <${component} {...props} />
    </>
  );
}
```

Anything beyond that?

**Comment by roydukkey** [comment]
@Josh-Cena This will have issues with components that export anything other than a default. For example, wrapping the Heading component requires:

```ts
import Heading, { MainHeading as OriginalMainHeading } from '@theme-original/Heading';
import React, { Fragment } from 'react';

export default Heading;

export const MainHeading: typeof OriginalMainHeading = ({ ...props }) => <Fragment>
	<p>My additionalness.</p>
	<OriginalMainHeading {...props} />
</Fragment>;
```

I think the user experience would be better if components that support wrapping only ever export a default. So the Heading component might be separated into two.

**Comment by Josh-Cena** [comment]
Ah... Yes, thanks for reminding! That would be a bit more troublesome... I think we would refactor that as well

**Comment by Josh-Cena** [comment]
@slorber What do you think about turning on `'import/no-named-export'` inside `src/theme`, and enforce that every theme component only has one default export? This would make them work well with wrapping.

**Comment by slorber** [comment]
Did some tests and I believe it should technically be possible to support named exports with `export * from "@theme-original/Heading"`

Still, for our own codebase we only have very few named exports, I'll refactor that and apply the rule `'import/no-named-export'` @Josh-Cena. 

We can figure out later for third-party themes, there are probably not a lot of themes out there and it's not the most common customization pattern.


---

For some reasons I don't understand yet (maybe related to CJS/ESM modules config 🤷‍♂️ ), the following does not work while it should.

```jsx
import React from 'react';

export function MainHeading() {
  return <div>test2</div>;
}

export default function HeadingWrapper() {
  return <div>test</div>;
}
```

We'll have to figure this out.


---

Another problem is that when using `swizzle --eject` we might eject to components importing theme-common:

```js
import {useThemeConfig} from '@docusaurus/theme-common';
```

In such case the dependency must be explicitly added to the website. 

Maybe we should automate this and add a console warning to explain why it was added?


---


Another issue is the TypeScript story

When using `swizzle --wrap --typescript`, it's not so easy to decide what exactly should be the output.

Note that the theme does not expose types for `@theme-original` imports. 

And the `export type Props` convention that we use can't really be enforced everywhere (in particular third-party themes).

This output does not look so good to me, we should try to find something better?

```tsx
import React, {ComponentProps} from 'react';

import Heading from '@theme-original/Heading';
import type HeadingComponentType from '@theme/Heading';

export default function HeadingWrapper(
  props: ComponentProps<typeof HeadingComponentType>,
) {
  return <Heading {...props} />;
}
```

**Comment by Josh-Cena** [comment]
> In such case the dependency must be explicitly added to the website.

Not always needed? Extraneous dependencies are bad but don't prevent sites from building unless you are using PnP. Would still be nice to fix it though

**Comment by slorber** [comment]
> Not always needed? Extraneous dependencies are bad but don't prevent sites from building unless you are using PnP. Would still be nice to fix it though

Agree, this is not a blocker as it can be fixed manually anyway, just a think to keep in mind.

> I would want to move all docs hooks, at least, to theme-common since we already have docUtils.

Yes, that's my next plan to move much more things to theme-common, starting with those hooks. I'll start now but let me know if you want to split the work.

**Comment by Josh-Cena** [comment]
Great, you can go ahead 👍 I would be relaxing a little

**Comment by slorber** [comment]
> About TypeScript, I think we can just go with emitting no types for props? Or default to @theme/* since types are non-blocking and TS users usually know enough to fix the situation if needed?

May not be a blocker to get started.

But this means that we enable implicit any on the default config? 

I think it's better to be strict by default so that swizzle eject users can have type errors when we refactor a theme component's prop, without having to read the changelogs.

This can also prevent weird errors where we add a new prop, thinking it's harmless but the user is spreading props to an element that should not receive it.

Hopefully someday TS will allow a module to implement an interface:
https://github.com/microsoft/TypeScript/issues/38511
