### ISSUE TITLE
Convert Docusaurus to React 16

### ISSUE THREAD

**Issue by JoelMarcey** [facebook/Docusaurus#539]
### Is this a bug report?

No

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

### Environment

N/A

### Steps to Reproduce

N/A

### Expected Behavior

N/A

(Write what you thought would happen.)

### Actual Behavior

N/A

### Reproducible Demo

N/A

**Comment by gedeagas** [comment]
https://github.com/facebook/Docusaurus/pull/655 
Working on it 👍

**Comment by JoelMarcey** [comment]
I guess my tag of `Difficulty: Advanced` was just a tad off, huh? 😛
