### ISSUE TITLE
We renamed the `master` branch to `main`. Read about it here.

### ISSUE THREAD

**Issue by JoelMarcey** [facebook/docusaurus#5391]
# Renaming `master` branch to `main`

As a part of a broad effort to avoid problematic terminology in our software, we are renaming our default branch from `master` to `main`. We recognize that this is only a small step, but it is an opportunity to make our project and community more welcoming to historically marginalized communities.

## How does this impact my development process?

There should be very little impact. GitHub will surface the branch name change in your fork, if you have one. For new forks, you will automatically have `main` as the default branch.

We encourage the use of feature branches for local development. The only change in practice is changing which branch your feature branch is started from. When sending Pull Requests on GitHub, the target will default to our `main` branch, so there are no changes to make there.

## I have a lot of tools that depend on `master` being the upstream branch name. How can I fix that?

`master` has always been only a default value and a number of projects have used other names for their primary development branch for years. We encourage updating your tooling to instead dynamically determine the branch to use. [This article](https://aj.codes/post/branch-agnostic-git-aliases/) provides insight into how you can do that. Additionally, you can always set up a branch locally of any name to track our `main` branch.

## I'd like to do this for my own projects, do you have any documentation on how this works?

[GitHub has published a guide documenting their tooling.](https://github.com/github/renaming) We recommend reading that and the accompanying documentation.

If you're a Facebook employee looking to do this for a project you maintain, please reach out to the Open Source Team.

**Comment by slorber** [comment]
This can probably be closed now, nobody complained :)

**Comment by Josh-Cena** [comment]
No-one can possibly complain, since the conversation is locked😄Anyways, I don't think they have reasons to anyways
