### ISSUE TITLE
Add possibility to configure attribute "target" for navbar link

### ISSUE THREAD

**Issue by blazkovicz** [facebook/docusaurus#5395]
## 🚀 Feature

Add possibility to determine link target.

## Motivation

We have storybook, published with docs on the same domain (dynamic in pipeline, then static on master).
Docs navbar has link "storybook" with relative href, the problem is: application tries to open link with spa, but this link is external to application.

## API Design

The problem is solved with target="_blank" on described link.

**Comment by Josh-Cena** [comment]
This should already be the case that you can pass arbitrary props through navbar link config. We should have mentioned that in the documentation...

**Comment by slorber** [comment]
Yes, the following should work:


```js
    navbar: {
      items: [
        {
          to: '/storybook',
          label: 'Storybook',
          target: '_blank',
        },
  },
}
```

**Comment by lex111** [comment]
This feature is already implemented (see example above).

**Comment by blazkovicz** [comment]
Yes, the feature is supported, but undocumented. Why did you close the issue? Is there a task to update docs?
