### ISSUE TITLE
Need to use quotation marks for Locale name with "-" in i18 configuration

### ISSUE THREAD

**Issue by neaped** [facebook/docusaurus#5407]
## 📚 Documentation

https://docusaurus.io/zh-CN/docs/docusaurus.config.js#i18n

In existing Chinese docs, the i18 configuration has mistake.

```json
module.exports = {
  i18n: {
    defaultLocale: 'zh-cn',
    locales: ['en', 'zh-cn'],
    localeConfigs: {
      en: {
        label: 'English',
        direction: 'ltr',
      },
      zh-cn: {
        label: '中文（中国）',
        direction: 'ltr',
      },
    },
  },
};
```

The field `zh-cn` need to use quotation marks in `docusaurus.config.js`

```json
'zh-CN': {
  label: '中文（中国）'
}
```

I've made a PR  fix in Crowdin. 

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

**Comment by Josh-Cena** [comment]
This only exists in the Crowdin translation but not in the source, because the source uses `fr` as example: https://docusaurus.io/docs/next/i18n/tutorial

Still, good catch and glad that it probably wasn't me who made that translation mistake😁

**Comment by slorber** [comment]
Thanks, I've accepted your change on Crowdin
