### ISSUE TITLE
Numeric list does not add new lines for it's numbered parts.

### ISSUE THREAD

**Issue by blazkovicz** [facebook/docusaurus#5408]
### Prerequisites

- [x ] I'm using the latest version of Docusaurus.
- [ ] I have tried the `npm run clear` or `yarn clear` command.
- [ ] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io
- [ ] I have read the console error message carefully (if applicable)

### Description

Docusaurus promise to support markdown with numeric lists, but does not.

## Expected behavior

Each position of numeric list starts from new line.

## Actual behavior

Numeric list is inlined in one mash text passage.

## Reproducible demo

Open example and go from main menu to "Numeric list bug"
https://stackblitz.com/edit/github-mznvzm?file=docs/numeric-list-bug.md

**Comment by Josh-Cena** [comment]
Is `1)` even valid Markdown syntax? I thought the Markdown spec only defines `1. `?

**Comment by lex111** [comment]
In all likelihood, this is CommonMark syntax, which we do not currently support (see #3018 for more details). Therefore, use [the standardized Markdown syntax](https://spec-md.com/#sec-Lists) to define a list.

**Comment by slorber** [comment]
MDX playground does not support it, and we don't support things that MDX does not support (apart a few exceptions like admonitions for which we extend mdx): https://mdxjs.com/playground/

**Comment by blazkovicz** [comment]
let's see https://docusaurus.io/docs/markdown-features -> https://daringfireball.net/projects/markdown/syntax -> https://daringfireball.net/projects/markdown/syntax#list -> numbered lists

docs say, you support numbered lists

**Comment by Josh-Cena** [comment]
But the doc link you posted didn't say that `1)` is valid?

**Comment by blazkovicz** [comment]
My apologies, I misunderstood your answers at first and thought you said that numeric lists are not supported completely.

Syntax with period works. Thank you for your patience.
