### ISSUE TITLE
Task lists are rendered as disabled and with dashes

### ISSUE THREAD

**Issue by barrymcgee** [facebook/docusaurus#5409]
### Prerequisites

- [x] I'm using the latest version of Docusaurus.
- [x] I have tried the `npm run clear` or `yarn clear` command.
- [x] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [x] I have tried creating a repro with https://new.docusaurus.io
- [x] I have read the console error message carefully (if applicable)

### Description

Task list markdown syntax as follows does not render as it does on Github:

```
- [  ] task 1
- [  ] task 2
- [  ] task 3
``` 

I'd expect the above to render as a list of checkboxes without the preceding dash that can be clicked like so;

- [ ] task 1
- [ ] task 2
- [ ] task 3

Instead it renders like so;

![Screenshot 2021-08-23 at 14 47 19](https://user-images.githubusercontent.com/505570/130459493-f1f7c0d5-f7ff-4b9f-afc3-f383dfef9751.png)

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues)?

Yes

## Steps to reproduce

https://codesandbox.io/s/unruffled-shape-3m6td?file=/docs/intro.md

1. See the task list retains the dash before the checkboxes
2. Checkboxes cannot be clicked

## Expected behavior

- Preceding dash should be stripped
- Checkboxes should be clickable

## Actual behavior

(Write what happened. Add full console log messages and screenshots, if applicable.)

## Your environment

- Public source code:
- Public site URL:
- Docusaurus version used: 2.0.0-beta.4
- Environment name and version (e.g. Chrome 78.0.3904.108, Node.js 10.17.0): Version 92.0.4515.159 (Official Build) (x86_64)
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): macOS 11.5.2

## Reproducible demo

https://3m6td.sse.codesandbox.io/docs/intro

**Comment by slorber** [comment]
Hi

Task lists are not std common marks.
I'm surprised that our parser MDX has native support for this out of the box.

I don't think this is a bug, but this is definitively an UI improvement we could add by default.

In the meantime you can achieve this with custom site CSS:

```css
ul.contains-task-list {
    margin-left: 0;
    padding-left: 0;
    list-style-type: none;
}

**Comment by slorber** [comment]
>  I'd expect a list of checkboxes to be clickable at some point, otherwise it's pointless rendering a list of checkboxes at all.

I don't agree, rendering checkboxes that you can click still make sense to me if you want to create a task list that you edit through MD edits and Git commits. Note technically, checking a checkbox on GitHub is just a shortcut over editing the issue md content. In the case of Git, this shortcut is just technically harder to build in a non-opinionated way.

Also remember that when you look at a Github Issue with checkboxes and you have read-only permission, GitHub also render read-only checkboxes for you. Example:

- [x] Task 1
- [ ] Task 2

You shouldn't be able to click those checkboxes, similarly to the current Docusaurus behavior

> I initially expect these to persisted locally via localStorage or whatever but thinking about it more, you then hit the problem of when to purge etc which quickly becomes a significant overreach for a static site generator.

Local storage is something that totally doesn't make sense to me. It's persisted only for you, and only in a single browser. It's very unlikely we'll add anything based on Localstorage to Docusaurus mdx checkboxes by default, but you can build this yourself using MDX or a remark plugin if you really want that.

> As such, I think the best solution is not to render checkboxes at all. The markdown syntax that generates a task list on GitHub should render as plain text when using Docusaurus. </two cents>


This behavior is provided by our parser MDX (I think, it's not Docusaurus at least), I'm not even sure we can disable it. If you really want to disable it for some reason, you can probably build a custom remark plugin to do so.

Why would you want to render `[ ]` as plain text? Why use `[ ]` in the first place in this case.


I still think it's valuable to render non-clickable checkboxes in some cases. For example, I could add checkboxes to our Docusaurus v2 beta blog post for each task we mention:

https://docusaurus.io/blog/2021/05/12/announcing-docusaurus-two-beta#whats-next

Some of those tasks have been handled already and I could mark them as checked:

![image](https://user-images.githubusercontent.com/749374/131311262-0caa28fe-df08-4ca7-9b91-e1f9eace2658.png)

(I personally prefer a checkbox compared to strikethrough)


---

I don't think we are going to do anything with this issue, so closing it for now

**Comment by slorber** [comment]
Re-opening because still think we should render without the dash.

**Comment by SamarthAroraa** [comment]
Hi @slorber, 
I see that the unwanted behaviour (dashed checkboxes) is present in the original MDX parser library.
The most natural solution that occurred to me was to overwrite the CSS with our own CSS, 
```css
ul.contains-task-list {
    margin-left: 0;
    padding-left: 0;
    list-style-type: none;
}
```
as you mentioned in your comment. 
However, since I am a bit new to the project architecture and open source in general, I could not identify where to include this CSS to overwrite the default MDX behavior.
From my personal codebase exploration, it seems to be somewhere in the 
[Docusaurus MDX Loader](../tree/main/packages/docusaurus-mdx-loader) directory.

I apologize for the delay and any inconvenience caused. 
Hoping to get up to speed as soon as possible and freely contribute more to this awesome repository!

**Comment by slorber** [comment]
@SamarthAroraa thanks

It's a theming concern related to MDX, I would put it there: 

`docusaurus/packages/docusaurus-theme-classic/src/theme/MDXComponents/styles.css`

**Comment by akshitarora921** [comment]
Hi, I would like to help :).

**Comment by himanshu007-creator** [comment]
Hi @SamarthAroraa, can you please drop a "HI" confirming you are working in the issue, otherwise i can work on the issue
