### ISSUE TITLE
Translate shouldn't require a default message

### ISSUE THREAD

**Issue by azinit** [facebook/docusaurus#5439]
### Prerequisites

- [x] I'm using the latest version of Docusaurus. (latest stable, 2.0.0-beta.5)
- [x] I have tried the `npm run clear` or `yarn clear` command.
- [x] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [x] I have tried creating a repro with https://new.docusaurus.io
- [x] I have read the console error message carefully (if applicable)

### Description

**`TLDR:`** On my opinion, Translate component **should be able to process undefined children**, if we're sure that we have enough i18n dictionaries for it

But after `2.0.0-beta.0` this behavior has changed - there is appeared strange invariant check. that children always should be string

> Yeah, it shouldn't be ReactNode, but **we haven't to specify this children always**!

![image](https://user-images.githubusercontent.com/42924400/131260007-16fa682c-115a-47b1-b159-e2ddfb925f65.png)

![image](https://user-images.githubusercontent.com/42924400/131260216-e14dae26-36b5-4ae7-bfa7-debc13fd252c.png)

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues)?

Yes

## Steps to reproduce

~~Use https://new.docusaurus.io to create a CodeSandbox reproducible demo of the bug.~~
> Sorry, too much for my proposal

1. Not pass children in `<Translate />` component from `@docusaurus/Translate` (another words - `children === undefined`
![image](https://user-images.githubusercontent.com/42924400/131259616-47575daf-bd72-4d29-95ad-f9cc88a8025c.png)
1. Try to launch page with this

## Expected behavior

**Render without crashing**

There no need to specify default value for translation, if you have only two locales with two i18n-dictionaries

![image](https://user-images.githubusercontent.com/42924400/131259696-3ca26e03-ac53-494f-9087-c32abd272a88.png)

## Actual behavior

**Render with crashing**

> If I try to define as `<Translate id="...">FOO_BAR</Translate>` or `<>{translate(...)}</>` - this will work, but its crazy approach in this case :/

![image](https://user-images.githubusercontent.com/42924400/131259705-6e6a20b4-1672-49a5-858f-193bdf67b19b.png)

## Your environment

- Public source code: [REPO](https://github.com/feature-sliced/documentation/tree/master/website) | [Described code fragment](https://github.com/feature-sliced/documentation/blob/master/website/src/pages/_config.jsx#L17) | [i18n dictionaries for locales (only ru, en)](https://github.com/feature-sliced/documentation/tree/master/website/i18n)

- Public site URL: http://feature-sliced.design/
- Docusaurus version used: `2.0.0-beta.5`
- Environment name and version `Firefox 91.0.2 (64-bit), Node.js v12.18.0`:
- Operating system and version `Windows 10`:

## Reproducible demo

~~Use https://new.docusaurus.io to create a CodeSandbox reproducible demo of the bug.~~

> Sorry, too much for my proposal, u can see at point `public source code`

**Comment by slorber** [comment]
So, what I understand is that you want this to work despite not using default translation message in your code?

Then, what should be the behavior of the `docusaurus write` CLI command, that is supposed to extract these messages from your code? Should we extract the message ids instead, as the code does not contain any message?

**Comment by azinit** [comment]
*Thanks for quick response,*

*from @feature-sliced core-team*

---

> (1) you want this to work despite not using default translation message in your code?

Yeap, at the moment our team maintain only two locales (`ru`, `en`), with one default (`ru`)

And the main problem was that docs for default locale should be located out from i18n (usually in `/docs/**`)
But other locales placed in a completely different place (**"purely scattered at project"**)

Because of it - our idea was to place both locales closely with each other - for explicitness, discoverability and more easier maintaining

*(another point is that we should specify default value in JSX, bot other values we should specify at json-dictionaries - **"purely decoupled too"**)*

<img width="485" alt="image" src="https://user-images.githubusercontent.com/42924400/131308199-95e8249d-88d8-4708-9f74-549c54b48ab0.png">

> (2) Should we extract the message ids instead, as the code does not contain any message

Yeah, at least for us, it would be preffered behaviour

But **the final solution is yours**, because this is question yet about compatibility and `TMTOWTDI`

Our team's opinion, it's not very good practice to scatter i18n-logic between JSX-code and json-dictionaries
*(because of it - we don't specify translations on code)*

<img width="778" alt="image" src="https://user-images.githubusercontent.com/42924400/131309911-30066403-e43c-4031-a2db-c122f9b79def.png">

**Comment by slorber** [comment]
> And the main problem was that docs for default locale should be located out from i18n (usually in /docs/**)

That's not totally true.

The default translations you have in your code can be "examples" so that it's easier to understand what a good translation message can look like. You can still provide the real translations in `i18n/ru` and it would override the Russian translations found in code.

But I understand it may also not be ideal to have duplicate labels in 2 places and may be confusing for contributors.

> Yeah, at least for us, it would be preffered behaviour

Your use-case makes sense to me, and it shouldn't be too hard to add support for this.

**Comment by azinit** [comment]
> The default translations you have in your code can be "examples" so that it's easier to understand what a good translation message can look like. You can still provide the real translations in i18n/ru and it would override the Russian translations found in code.

Yeah, we are aware of this, but the same purpose ["to help translators with additional context" could be reached](https://docusaurus.io/docs/i18n/introduction#json-files) by `dictionaries[item-index].description` field, couldn't it?))

> But I understand it may also not be ideal to have duplicate labels in 2 places and may be confusing for contributors.

Exactly 👍 

> Your use-case makes sense to me, and it shouldn't be too hard to add support for this.

Thank you for understanding  🚀
