### ISSUE TITLE
Make `Tabs` collect values from `TabItem` children

### ISSUE THREAD

**Issue by Josh-Cena** [facebook/docusaurus#5441]
## 🚀 Feature

The values shouldn't be required in `Tabs`; rather, when they are not provided, the `Tabs` component should traverse its children and collect those information.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues)?

Yes

### Has this been requested on [Canny](https://docusaurus.io/feature-requests)?

No

## Motivation

There was a Discord conversation between @oojacoboo and I where both of us agreed that the current `Tabs` syntax has too much boilerplate & redundancy. Looking at designs from component libraries, it's better if we can move the data to the children instead of in a centralized location.

## API Design

Before:

```jsx
<Tabs
  defaultValue="apple"
  values={[
    {label: 'Apple', value: 'apple'},
    {label: 'Orange', value: 'orange'},
    {label: 'Banana', value: 'banana'},
  ]}>
  <TabItem value="apple">This is an apple 🍎</TabItem>
  <TabItem value="orange">This is an orange 🍊</TabItem>
  <TabItem value="banana">This is a banana 🍌</TabItem>
</Tabs>
```

After:

```jsx
<Tabs>
  <TabItem value="apple" label="Apple" default>This is an apple 🍎</TabItem>
  <TabItem value="orange" label="Orange">This is an orange 🍊</TabItem>
  <TabItem value="banana" label="Banana">This is a banana 🍌</TabItem>
</Tabs>
```

Afaic it won't break things, because we already assume that the children are all `TabItem` when we wrote this:

https://github.com/facebook/docusaurus/blob/f1ae06f47057d1a1da79b26e7a804b4e1e0b377b/packages/docusaurus-theme-classic/src/types.d.ts#L536

## Have you tried building it?

Not yet

**Comment by slorber** [comment]
Agree this can be more convenient to use.

We should just make sure to implement this in a retro-compatible way.
