### ISSUE TITLE
Add Typesense Search Component to Docs

### ISSUE THREAD

**Issue by jasonbosco** [facebook/docusaurus#5446]
## 💥 Proposal

This is a proposal to add another search component option for Docusaurus users on this docs page: https://docusaurus.io/docs/search. 

I've customized the [built-in Algolia Docusaurus](https://www.npmjs.com/package/@docusaurus/theme-search-algolia) search component to work with Typesense in [this plugin](https://github.com/typesense/docusaurus-theme-search-typesense) and I think it would be useful to include instructions for how to use this alternate search plugin, in the official docs. 

For context, [Typesense](https://github.com/typesense/typesense) is an open source alternative to Algolia that users can choose to self-host or use the managed SaaS version. Given that Docusaurus itself is open source, I think users would appreciate the ability to use another open source project to power their search as well. In addition, Typesense does not have any per-request or per-record limits / charges, which I know many Typesense users coming from Algolia find very helpful. 

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes.

**Comment by slorber** [comment]
Thanks for creating this plugin.

Unfortunately, we don't want to document usage ourselves for a few reasons:
- We are biased on purpose and have a long-term partnership with Algolia
- We are quite sure Algolia will still be in the game in the upcoming years and will keep providing us doc updates, support, and integration
- We don't want to document non-official third-party plugins that we don't create/use/maintain ourselves, unless there's a strong reason to do so. 

We don't provide doc for local search plugins too, and only provide a list of links here: https://docusaurus.io/community/resources#search

Once the first doc PR is merged, the complaints about outdated doc will be Docusaurus maintainer's burden, and we don't want that. Similarly, we'll likely replace some doc about deployment options with links to their official doc.

What I suggest:
- We do not write Typesense documentation on the Docusaurus website: instead we link to Typesense official doc,, that you have the burden to keep up-to-date
- Add your plugin to this list of links: https://docusaurus.io/community/resources#search
- Make it clear that Algolia is not the only possible choice in https://docusaurus.io/docs/search
- If Typesense becomes a successful Docusaurus theme, widely used, and with good long-term support, we could revisit this choice and document it officially. I'm also trying to get a `docusaurus-community` org on which we could move such plugins we plan to doc/maintain a bit more than regular third-party plugins.

I'm going to close this, and am happy to merge any doc PR that gives your plugin (and other local search ones) better visibility, as long as we don't have to write the doc for it ourselves (and particularly maintain over time), and it's just linking to the official doc.

As you already have a [doc for Docusaurus](https://typesense.org/docs/0.21.0/guide/docsearch.html#option-a-docusaurus-powered-sites), linking to it seems a good idea, and it's now your burden to keep this link alive and up-to-date.

**Comment by jasonbosco** [comment]
Thank you for the detailed response @slorber. 

I understand the reasoning behind not including detailed instructions in the Docusaurus docs, but just link to Typesense's doc for now. I'll create a PR to update the docs following your guidelines above.
