### ISSUE TITLE
Module '"@docusaurus/router"' has no exported member 'matchPath'

### ISSUE THREAD

**Issue by ocavue** [facebook/docusaurus#5463]
### Prerequisites

- [x] I'm using the latest version of Docusaurus.
- [x] I have tried the `npm run clear` or `yarn clear` command.
- [x] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io
- [x] I have read the console error message carefully (if applicable)

### Description

I'm using `docusaurus` in a TypeScript project. When we run `tsc -b` to build the project, we get this error:

```
> tsc -b

node_modules/.pnpm/@docusaurus+plugin-content-docs@2.0.0-beta.5_react-dom@17.0.2+react@17.0.2/node_modules/@docusaurus/plugin-content-docs/src/client/docsClientUtils.ts:8:9 - error TS2305: Module '"@docusaurus/router"' has no exported member 'matchPath'.

8 import {matchPath} from '@docusaurus/router';
          ~~~~~~~~~
```

`@docusaurus/plugin-content-docs` [imports](https://unpkg.com/@docusaurus/plugin-content-docs@2.0.0-beta.5/src/client/docsClientUtils.ts) `matchPath` from `@docusaurus/router`. But I couldn't find `@docusaurus/router` in my `node_modules` nor https://www.npmjs.com/. 

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues)?

yes

## Steps to reproduce

Use https://new.docusaurus.io to create a CodeSandbox reproducible demo of the bug.

(Write your steps here:)

1. Install `@docusaurus/plugin-content-docs@2.0.0-beta.5`
1. Use TypeScript to compile the project

## Expected behavior

 
No error.

If `@docusaurus/router` doesn't mean to be an NPM package, then maybe docusaurus should export `.d.ts` files instead of raw `.ts` files as types.

## Actual behavior

Got error.

## Your environment

- Public source code: N/A
- Public site URL: N/A 
- Docusaurus version used: `@docusaurus/plugin-content-docs@2.0.0-beta.5`
- Environment name and version (e.g. Chrome 78.0.3904.108, Node.js 10.17.0): Node.js v16.7.0, TypeScript 4.4.2, Pnpm 6.14.5
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): macOS 11.5

## Reproducible demo

N/A

**Comment by Josh-Cena** [comment]
`@docusaurus/router` is an exported member from `@docusaurus/core` (our extensive use of webpack aliases can be very confusing yeah). It is just a wrapper around `react-router-dom`. The module definition is from `@docusaurus/module-type-aliases`:

```ts
declare module '@docusaurus/router' {
  export * from 'react-router-dom';
}
```

On how to make Docusaurus work with TS: https://docusaurus.io/docs/next/typescript-support#setup

**Comment by ocavue** [comment]
When `tsc` handle `@docusaurus/plugin-content-docs`, it won't load definition from `@docusaurus/module-type-aliases`. `@docusaurus/module-type-aliases` is just a devDep of `@docusaurus/plugin-content-docs`.

**Comment by Josh-Cena** [comment]
I fixed a few TS bugs recently, but that doesn't include the one you are reporting. Initializing with `npx @docusaurus/init@canary init website classic --typescript` and running `tsc` gives no errors. Did you really install `@docusaurus/core`? You may also need to add `@types/react-router-dom` as devDep.

**Comment by slorber** [comment]
Can you double-check your TS integration, please? 

https://docusaurus.io/docs/typescript-support#setup

Things might have changed a bit recently, and you need to extend a config from `@tsconfig/docusaurus` (and the package should be up to date)

Also please provide your site public infos (URL, code) or at least some code samples. 

How do you run tsc. What's in your package.json etc...

I also see you use PNPM, we don't officially support it (no doc or CI e2e tests for it) but I guess it should work. Try NPM, Yarn 1 (or Yarn berry with node_modules linker) and see if it fixes the problem.

Having a repro for this kind of issue would be very helpful, otherwise, we are just trying to guess what could be wrong.

**Comment by ocavue** [comment]
@slorber @Josh-Cena After installing `@types/react-router-dom` and `@types/react-helmet` as the document said, we don't get this error anymore. Thank you for your help. 

I'm curious why don't put these two packages as dependencies of Docusaurus so that we users don't need to install them. I guess there is a reason and I just didn't think of it.

**Comment by Josh-Cena** [comment]
It should be. We tend to add `@types/*` dependencies in devDeps but I guess it makes more sense to put them in dependencies for `module-type-aliases` and `types` whose sole purpose is to provide typings

**Comment by slorber** [comment]
Should be fixed in next canary, please give confirmation :)
