### ISSUE TITLE
Add `npm install` after npx @docusaurus/init@latest init my-website classic

### ISSUE THREAD

**Issue by AnirudhPanda** [facebook/docusaurus#5466]
## 📚 Documentation

Beginners like me could run into problems like if we do not do `npm install` and move to `npm run start` it will give error.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

**Comment by AnirudhPanda** [comment]
> When you run `@docusaurus/init@latest init`, `npm install` should be automatically run for you. You need to pass the `--skip-install` in order for it to not happen.

It did not run `npm install` for me. I did it manually. I was getting `'docusaurus' is not recognized as an internal or external command, operable program or batch file.`

**Comment by AnirudhPanda** [comment]
> Weird, I don't know if it's worth showing but at least we have this in the code:
> 
> https://github.com/facebook/docusaurus/blob/402a5e1f883272f1d5e9da1db4d432e30a879b26/packages/docusaurus-init/src/index.ts#L238-L252
> 
> Did you not see "Installing dependencies with npm..." at all?

I did the process 3 times, didn't show me once.

I manually did `npm install`

**Comment by slorber** [comment]
Someone already reported this problem (using npm) but I couldn't reproduce it.

Was wondering if you can share details of your env?

Can you also show logs or screenshots of your terminal  while you run the init command?

Which command did you run exactly? Which Docusaurus version did it install? (copy here `package.json` please)

**Comment by AnirudhPanda** [comment]
> Someone already reported this problem (using npm) but I couldn't reproduce it.
> 
> Was wondering if you can share details of your env?
> 
> Can you also show logs or screenshots of your terminal while you run the init command?
> 
> Which command did you run exactly? Which Docusaurus version did it install? (copy here `package.json` please)

**FOLLOWING THE DOCUMENTATION**
First I ran:
`npx @docusaurus/init@latest init my-website classic`

then:
![fb](https://user-images.githubusercontent.com/66218496/131834775-d5b882e0-b426-46ee-b3aa-352194d2494e.PNG)

**Comment by Josh-Cena** [comment]
Environment means things like NPM version, OS version, etc. After completing initializing you should also have a `package.json` which contains the Docusaurus version (something ilke `2.0.0-beta.5`) that you can share

The output between `npx @docusaurus/init@latest init my-website classic` and `Happy building awesome websites!` can be useful (although I can guess what it looks like)

**Comment by AnirudhPanda** [comment]
**Node Version:**  v14.17.0
**NPM Version:** 7.16.0
**OS Version:**  Windows 10 (64 bit Operating System)

**package.json**

```
{
  "name": "my-website",
  "version": "0.0.0",
  "private": true,
  "scripts": {
    "docusaurus": "docusaurus",
    "start": "docusaurus start",
    "build": "docusaurus build",
    "swizzle": "docusaurus swizzle",
    "deploy": "docusaurus deploy",
    "clear": "docusaurus clear",
    "serve": "docusaurus serve",
    "write-translations": "docusaurus write-translations",
    "write-heading-ids": "docusaurus write-heading-ids"
  },
  "dependencies": {
    "@docusaurus/core": "2.0.0-beta.5",
    "@docusaurus/preset-classic": "2.0.0-beta.5",
    "@mdx-js/react": "^1.6.21",
    "@svgr/webpack": "^5.5.0",
    "clsx": "^1.1.1",
    "file-loader": "^6.2.0",
    "prism-react-renderer": "^1.2.1",
    "react": "^17.0.1",
    "react-dom": "^17.0.1",
    "url-loader": "^4.1.1"
  },
  "browserslist": {
    "production": [
      ">0.5%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  }
}
```

**Comment by slorber** [comment]
![image](https://user-images.githubusercontent.com/749374/131849713-d13457db-3c6e-4699-84bc-0c2295694d1c.png)


Can you please provide a screenshot that provides the whole console log, not just the end?

I'd lik to see the full log of the command, including the line showing the command you typed

**Comment by AnirudhPanda** [comment]
![fb1](https://user-images.githubusercontent.com/66218496/131850608-378bd89f-fc2b-47ad-ac89-b938e3be9696.PNG)



If I do `cd my-website` and then `yarn start` the following happens: (following what the terminal say)

![fb2](https://user-images.githubusercontent.com/66218496/131851321-f0407f30-e413-48b4-b317-f33c497d026f.PNG)

**Comment by Josh-Cena** [comment]
Okay, the problem is `FORCE_COLOR=true` env setting is not recognized by your console😅 You should have reported that earlier

Is it git bash? I thought anything using bash would recognize this syntax (my bash on Mac works)

**Comment by AnirudhPanda** [comment]
> Okay, the problem is `FORCE_COLOR=true` env setting is not recognized by your console😅 You should have reported that earlier
> 
> I guess it's the way `shelljs` delegates the executed command. Powershell seems to have a different way for handling env variables from bash. For now the fix would be to remove the `FORCE_COLOR` setting; CRA handles the installation in a very different way, while still preserving the colored output. This can be where we head towards:
> 
> https://github.com/facebook/create-react-app/blob/25f516f8de602187bea4e725b9d8fc1034d909a6/packages/create-react-app/createReactApp.js#L407

Oh! Thanks for claryfying

**Comment by slorber** [comment]
Great to have this figured out!

I'm not too familiar with those problems.

Maybe zx wrapper could be useful to simplify our script's code and log colored output by default? 
https://github.com/google/zx

@antonmedv any opinion?

**Comment by lex111** [comment]
Does this look like regression after merge #5233 when `FORCE_COLOR` was introduced? If so, in upcoming v5 let's remove it for now, and then find better solution.

**Comment by Josh-Cena** [comment]
@lex111 Sounds fair. If we can figure out a more elegant solution (using `spawn`, `zx`, etc.) before the next release it will be even better

**Comment by slorber** [comment]
Have to release beta.6 now and it's unlikely I'll do another one before holidays, unfortunately.

If you find a good solution @lex111 feel free to release it

**Comment by Josh-Cena** [comment]
At least we should get rid of `FORCE_COLOR` before releasing beta.6 so windows + yarn users aren't penalized with this regression

**Comment by antonmedv** [comment]
In zx FORCE_COLOR can be added this way:
```js
process.env.FORCE_COLOR = 'true'
await $`npm install`
```

But also requires FORCE_COLOR (or similar) to be on. 

The spawn has an option `stdio` which can be `inherit` or `piped`. Only in inherited stdout mode subprocess detects what colors are supported (as stdout is TTY). But not in piped.
The zx uses `piped` as this is the only option for collecting output to a variable.

**Comment by Josh-Cena** [comment]
> The spawn has an option `stdio` which can be `inherit` or `piped`. Only in inherited stdout mode subprocess detects what colors are supported (as stdout is TTY). But not in piped.

That's what CRA is using. So is my understanding correct that only by setting `stdio: 'inherit'` (and using spawn, of course) can we return back the control of coloring to the subprocess itself, instead of forcing coloring the output with environment / options? When I added `FORCE_COLOR` I worried a bit whether that would lead to ANSI colors applied to places where it shouldn't

**Comment by antonmedv** [comment]
> When I added FORCE_COLOR I worried a bit whether that would lead to ANSI colors applied being to places where it shouldn't

Yes, better to check, for example via https://github.com/chalk/supports-color, before setting it. (Actually nice idea, will think of implementing it in zx)

And yes, spawn with inherited stdio should work.
