### ISSUE TITLE
"Unused default message codes found" when localizing docusaurus 2.0.0-beta.6

### ISSUE THREAD

**Issue by MarkusEischeid** [facebook/docusaurus#5480]
### Prerequisites

- [x] I'm using the latest version of Docusaurus.
- [ ] I have tried the `npm run clear` or `yarn clear` command.
- [ ] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io
- [x] I have read the console error message carefully (if applicable)

### Description

When running `npm run write-translations -- --locale de` I get warning messages:

```
Unused default message codes found.
Please report this Docusaurus issue.
- theme.Playground.liveEditor
- theme.Playground.result
- theme.PwaReloadPopup.closeButtonAriaLabel
- theme.PwaReloadPopup.info
- theme.PwaReloadPopup.refreshButtonText
- theme.SearchBar.label
- theme.SearchPage.algoliaLabel
- theme.SearchPage.documentsFound.plurals
- theme.SearchPage.emptyResultsTitle
- theme.SearchPage.existingResultsTitle
- theme.SearchPage.fetchingNewResults
- theme.SearchPage.inputLabel
- theme.SearchPage.inputPlaceholder
- theme.SearchPage.noResultsText
```

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues)?

Yes I have.

## Steps to reproduce

- I created a new docusaurus project with `npx @docusaurus/init@latest init my-project classic`
- Then I modified `docusaurus.config.js` and added
```
    i18n: {
        defaultLocale: 'en',
        locales: ['en', 'de'],
      },
```
- Then I ran `npm run write-translations -- --locale de`

## Expected behavior

Successful creation of json files for localization without warnings.

## Actual behavior

Warning message:

```
Unused default message codes found.
Please report this Docusaurus issue.
- theme.Playground.liveEditor
- theme.Playground.result
- theme.PwaReloadPopup.closeButtonAriaLabel
- theme.PwaReloadPopup.info
- theme.PwaReloadPopup.refreshButtonText
- theme.SearchBar.label
- theme.SearchPage.algoliaLabel
- theme.SearchPage.documentsFound.plurals
- theme.SearchPage.emptyResultsTitle
- theme.SearchPage.existingResultsTitle
- theme.SearchPage.fetchingNewResults
- theme.SearchPage.inputLabel
- theme.SearchPage.inputPlaceholder
- theme.SearchPage.noResultsText
```

## Your environment

- Docusaurus version used: 2.0.0-beta.6
- Environment name and version: Node 14.16.0
- Operating system and version: Windows 10

## Reproducible demo

None

**Comment by slorber** [comment]
Thanks, that is indeed a bug, that we didn't notice on the Docusaurus website because it's using all the plugins (unlike a newly initialized site).

I think I'll just remove this warning in the future. For now you can simply ignore it.
