### ISSUE TITLE
Improve documentation on remark / rehype plugins

### ISSUE THREAD

**Issue by Josh-Cena** [facebook/docusaurus#5492]
## 📚 Documentation

Elaborate on when, why, and how the user should use remark plugins.

Currently this section is very underdeveloped: https://docusaurus.io/docs/markdown-features/plugins#configuring-plugins
Users would want to know about:

- The concepts of remark and rehype
- When to use a plugin (e.g. injecting components at certain places, transforming image links)
- How to develop a plugin (linking to the official remark doc, possibly, and the docusaurus plugins' source code as examples)

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

**Comment by SanjaySinghRajpoot** [comment]
I would like to work on this issue.

**Comment by Josh-Cena** [comment]
@SanjaySinghRajpoot Why not, appreciate it ;)
