### ISSUE TITLE
Expose settings to control the minification process(es)

### ISSUE THREAD

**Issue by stnor** [facebook/docusaurus#5493]
## 🚀 Feature
As a user I'd like to have more control over the minification process.

We have a Docusarus blog that we also use as a source to send email newsletters (about 500k). I've noticed that some screenshots are inlined as `img src="data:image/png;base64,..."`. I'm guessing this is based on file size.

As I do not want to have the images in the payload in each email, I'd like to not have them inlined.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues)?

Yes.

### Has this been requested on [Canny](https://docusaurus.io/feature-requests)?

No.

## Motivation

It's nice to have some control over the minification process to support different use cases.

## API Design

It would be nice to have some optional settings exposed for overriding the default behavior either in Docusaurus config or in the webpack config.

## Have you tried building it?

Someone suggested building a `remark plugin` which seems overly complicated to me, but I'll check it out.

**Comment by Josh-Cena** [comment]
> Someone suggested building a remark plugin

Context is a Discord discussion. However I misunderstood your use-case and now I realized that isn't really an option🤦‍♂️ In your case allowing webpack customization may be the only option

**Comment by stnor** [comment]
Found the hard coded value here:
https://github.com/facebook/docusaurus/blob/4f59f0782e7af8b5414994848abe6adb18f509f2/packages/docusaurus/src/webpack/utils.ts#L330

**Comment by RDIL** [comment]
Joining this discussion as requested in the Discord, and I agree that this would be a beneficial change.  Would require a decent amount of changes, as anywhere that this call to the URL loader creation would need to be changed to get the new value for the limit.  Maybe it could be an environment variable?  I believe CRA has it as one, not 100% sure on that though.

**Comment by stnor** [comment]
Based on our Discord chat, I'll see if it works with a environment variable to override the hard coded value and perhaps even whip up a PR as a short term solution.

Longer term it would probably be beneficial to be able to override the webpack config on a general level.

**Comment by RDIL** [comment]
You can override the webpack config with one of the plugin functions.

**Comment by Josh-Cena** [comment]
"On a general level" I'd say we can build plugins; also, there's a `webpack.jsLoader` config option which seems completely undocumented :P

**Comment by RDIL** [comment]
Undocumented function?  Nice!  We should start relying on that, as it will never break 👀

Obviously being sarcastic but might be worth looking into.

**Comment by lex111** [comment]
Images in blog content are handled by `inlineMarkdownImageFileLoader`, whose options cannot be overridden via `configureWebpack` for now. If it will be "regular loader", you could do something similar with the existing API:

```js
configureWebpack(_config, isServer) {
  _config.module.rules[0].use[0].options.limit = false;

  return {
    mergeStrategy: {
      'module.rules': 'prepend',
    },
    module: {
      rules: [_config.module.rules[0]],
    },
  };
},
```

Perhaps this will be possible after migrating to asset modules in PR #4708, although the CRA approach by changing env var still looks better and clearer than using `configureWebpack` which seems pretty hacky.

**Comment by stnor** [comment]
Should we change the default value from 10k to 2k while looking at this? It retrospect it seems high.

The web perf gods seem to suggest 2k is a good default:
https://www.modpagespeed.com/doc/reference-image-optimize#ImageInlineMaxBytes

**Comment by lex111** [comment]
To be honest, I wouldn't use the `limit` option at all, don't think it's much useful at the moment. But for now, let's go with config of it via env var.

**Comment by stnor** [comment]
Ok, if you want to leave the default at 10000 bytes, the PR is ready to merge: https://github.com/facebook/docusaurus/pull/5498 (pending review)

**Comment by lex111** [comment]
I see, thank you, but the new release will be in about two weeks. So you're fine with this?

**Comment by stnor** [comment]
Yeah. The PR solves my issue.

Again, I would advise to lower the inlining threshold to 2k or less, but this fix lets me do that via the env, so I'm happy with this.

**Comment by johnnyreilly** [comment]
I stumbled upon this when I was writing up how to use the 
docusaurus-image-cloudinary-remark-plugin:

https://johnnyreilly.com/2022/12/26/docusaurus-image-cloudinary-remark-plugin#introducing-remark-cloudinary-docusaurus

The workaround works... but it's not great developer experience. @slorber would you be open to having this configured more directly somehow? Perhaps using the `docusaurus.config.js`?
