### ISSUE TITLE
livecodeblock cannot use dynamic import

### ISSUE THREAD

**Issue by cht132** [facebook/docusaurus#5544]
CompileError: Transforming dynamic import expressions is not implemented. Use `transforms: { moduleImport: false }` to skip transformation and disable this error. (3:25)

livecodeblock:
```
let obj = import('js-base64');
```

**Comment by lex111** [comment]
`react-live` does not handle import expressions by default (as stated in error message), but there is workaround that may help you. See FAQ (https://github.com/FormidableLabs/react-live#faq-1) for more details (you will need to swizzle `Playground` component for that).
