### ISSUE TITLE
Blog date is no longer parsed correctly when blog has subfolders

### ISSUE THREAD

**Issue by kanoshin** [facebook/docusaurus#5554]
### Prerequisites

- [x] I'm using the latest version of Docusaurus.
- [x] I have tried the `npm run clear` or `yarn clear` command.
- [x] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io
- [x] I have read the console error message carefully (if applicable)

### Description

Our blog file structure contains subfolders for better organization. We have hundreds of blogposts from different internal teams so this is vital for us:
```
/blog
  /team-a
    YYYY-MM-DD-name.md
    YYYY-MM-DD-name.md
  /team-b
    YYYY-MM-DD-name.md
    YYYY-MM-DD-name.md
```

Starting from 2.0.0-beta.5 docusaurus-plugin-content-blog is no longer able to parse blog date for such folder organization. It changed in the following PR [#5309](https://github.com/facebook/docusaurus/pull/5309/files). I understand that our blog folder structure use case is not officially supported but please consider adding support for it. 

My understanding is that previously date was parsed from filename `path.basename(blogSourceFile)`, but now it is parsed from entire filepath to support blog folders like `2021-05-12-announcing-docusaurus-two-beta/index.md`.

I think it is relatively low effort to support parsing dates for all currently supported conventions + allow subfolders for better organization and I would be happy to contribute PR for that:
1. `2021-05-28-my-blog-post-title.md`
2. `2021-05-28-my-blog-post-title/index.md`
3. `team-a/2021-05-28-my-blog-post-title.md`
4. `team-a/2021-05-28-my-blog-post-title/index.md`

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues)?

Yes

## Steps to reproduce

Already explained above.

## Your environment

N/A

## Reproducible demo

N/A

**Comment by slorber** [comment]
Make sense, we'll try to restore former behavior

**Comment by Josh-Cena** [comment]
Hi @kanoshin I'm working on this. What URL do you think would `team-a/2021-05-28-my-blog-post-title.md` map to? Would it be:

1. `/team-a/2021/05/28/my-blog-post-title`
2. `/2021/05/28/team-a/my-blog-post-title` or
3. `/2021/05/28/my-blog-post-title`?

**Comment by slorber** [comment]
I wonder if the site using this blog subfolders pattern is public, we could inspect it and understand the usecases better (also see what URLs did your blog posts used to have before)

**Comment by Josh-Cena** [comment]
It's probably `/2021/05/28/team-a/my-blog-post-title` since that used to be the default
