### ISSUE TITLE
Markdown does not work inside JSX components

### ISSUE THREAD

**Issue by birdofpreyru** [facebook/docusaurus#5565]
### Description

I might be missing somehting, but according to MDX documentation it is legit to use Markdown syntax inside component and HTML tags, _i.e._ the markup like this `<div>This is **bold** word</div>` should result in **bold** being bold, and it does so in [MDX Playground](https://mdxjs.com/playground). It does not work in MDX docs rendered by Docusaurus 2, where the text wrapped inside comonent seems to be parsed as plain text, rather than Markdown.

I can't find in Docusaurus 2 documentation any mention this is not supposed to work, and I can't find related issue tickets in this repo either.

**Comment by lex111** [comment]
We use MDX v1, which does not support Markdown syntax inside JSX, it is easy to check on the appropriate playground https://mdx-git-renovate-babel-monorepo-mdx.vercel.app/playground

![image](https://user-images.githubusercontent.com/4408379/133460655-8c886090-0c98-463c-a68d-3447e42a33a4.png)

Closing in favor of https://github.com/facebook/docusaurus/issues/4029 (MDX v2 is currently not ready for production use).
