### ISSUE TITLE
deployment option to not overwrite files/folders

### ISSUE THREAD

**Issue by 6543** [facebook/docusaurus#5567]
## current state:
currently on deploy all old files are deleted.
but for example if you have files not managed by docusaurus on a specific path, they get deleted each deploy ...

## want
an option to specify path's like "README.md" or " charts/*" to ignore ...  would be nice ...

---
*background info: https://github.com/woodpecker-ci/woodpecker/pull/302#discussion_r707370720*

**Comment by Josh-Cena** [comment]
You are supposed to put those files under `static` so they get copied to the `build` folder. The built output should not be hand-modified.

**Comment by lex111** [comment]
@6543 as @Josh-Cena correctly pointed out, you either need to put your files in `static` directory or create custom deploy script (that's okay).
