### ISSUE TITLE
Use git tags for versioning

### ISSUE THREAD

**Issue by DanielMSchmidt** [facebook/Docusaurus#557]
### Is this a bug report?

No, a feature request.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

### Environment

Environment agnostic

### Steps to Reproduce

1. Add Docusaurus to your project
2. Release a new version and create a versioned documentation
3. Get "annoyed" by all the information that is stored twice, for each git tag and also in a seperate directory

### Expected Behavior

I would like to be enabled to use docusaurus in a mode that gets the git tags of this repository and gets the documentation at that point of time. I am aware that using this version we would opt-out of changing the docs after setting the tag (without changing the tag), but this might be okay for some use cases.

### Actual Behavior

Duplicately stored versions of the docs

### Reproducible Demo

I have no demo, just a PR against `wix/detox` mimicing this behaviour. I would like to move this upstream to this repository in a well-tested way. See this PR: https://github.com/wix/detox/pull/582

**Comment by defionscode** [comment]
I would really like this

**Comment by slorber** [comment]
Hey

Docusaurus encourage the usage of versioning on a single Git branch, but nothing prevents you from reverting to the old more usual behavior of having multiple Git branches for each version.

In fact, it's possible to use a hybrid (Git branches + versioned folders), and this is exactly what we do ourselves for Docusaurus v1:
- https://github.com/facebook/docusaurus/tree/docusaurus-v1
- https://v1.docusaurus.io/

Notice also that older v2 alpha/beta versions (that we do not update anymore) have been archived to standalone immutable static deployments, and remain accessible forever.

https://docusaurus.io/versions

![CleanShot 2022-11-17 at 11 42 20@2x](https://user-images.githubusercontent.com/749374/202425449-d378032b-66a3-41a0-9286-9388feed5940.png)

Docusaurus only encourage you to use a versioning pattern, but it does not lock you into it.
