### ISSUE TITLE
When using a python3 http.server or amazon s3 hosting, doc links can end up as 404

### ISSUE THREAD

**Issue by cmdcolin** [facebook/docusaurus#5570]
### Prerequisites

- [x] I'm using the latest version of Docusaurus.
- [x] I have tried the `npm run clear` or `yarn clear` command.
- [x] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [x] I have tried creating a repro with https://new.docusaurus.io
- [x] I have read the console error message carefully (if applicable)

### Description

If I use python3 http.server (for demo purposes) or amazon s3 (where i'm actually hosting this) then I run into issues with broken links in the documentation if I navigate to a page

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues)?

yes

## Steps to reproduce

Get latest version
Make a couple doc links
Start up basic http server
Specifically copy and paste into the URL http://localhost:8000/docs/intro#section-heading
URL is rewritten to http://localhost:8000/docs/intro/#section-heading automatically by browser
Then try to nav to ex1
Goes to broken link http://localhost:8000/docs/intro/ex1

## Expected behavior

I would expect the links to not be broken, but not sure how that would juggle with the various routing that needs to take place

## Actual behavior

Receive a 404

## Your environment

Some details here https://github.com/cmdcolin/docusaurus-nav-issue

Ubuntu 20, chrome 93 or firefox 92

I did not try docusaurus.new because I thought it may not support the basic http.server I was testing with here

**Comment by Josh-Cena** [comment]
Maybe you should specify `trailingSlash: false` in your `docusaurus.config.js`?

**Comment by cmdcolin** [comment]
Thanks for turning me onto this...I see now the trailing slash guide here too https://github.com/slorber/trailing-slash-guide

If I use trailingSlash:false it changes some behavior but it is still maybe not the behavior I'm looking for https://docusaurus.io/docs/deployment


For example, then I have

Nav to http://localhost:8000/
Click header bar for docs
Goes to
http://localhost:8000/docs/intro
Copying and pasting this into another tab leads to http://localhost:8000/docs/intro/ a 404

I am sure that this result is maybe expected from a basic server but this is a little surprising now to encounter this. I'm almost wondering if what I am expecting is docusaurus 1 style behavior? Where like docs/intro is a literal file that can be navigated to?

**Comment by cmdcolin** [comment]
I think probably the closest thing to the behavior I expect is

1) trailingSlashes: true (default)
2) Adding the post processing script here https://github.com/slorber/trailing-slash-guide/blob/main/docs/Solutions.md#post-process-your-static-site-generator-output-before-deployment

**Comment by cmdcolin** [comment]
I suppose we can probably close this for now, as it's likely taken care by factors external to docusaurus. Thanks much @John-Cena for letting me know about these options though!

**Comment by Josh-Cena** [comment]
Welcome :D

I'm also trying to document about these self-hosted servers https://github.com/slorber/trailing-slash-guide/pull/6 and maybe I should experiment with Python http.server / Java Tomcat as well (Haven't picked up much time recently with all the college app stuff going on)
