### ISSUE TITLE
Multiple Docusaurus documentation link broken

### ISSUE THREAD

**Issue by meows** [facebook/docusaurus#558]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

### Environment

(OS / Browser)

### Steps to Reproduce

1. Visit [docusaurus site prepation page in English](https://docusaurus.io/docs/en/site-preparation.html).
2. Click on the **[installing  Docusaurus](https://docusaurus.io/docs/en/instalaci%C3%B3n.html)** link in the first paragraph.
3. This link is reproducibly broken and should return a 404 page.
4. Other links in the main page should be similarly broken because they have the same endpoint misspelling.

### Expected Behavior

I expected the link to take me to this [this installation page](https://docusaurus.io/docs/en/installation.html).

### Actual Behavior

I received a custom 404 response after clicking the link. I notice that the link is slightly misspelled and possibly in Spanish.

### Addendum

Also found the [publish](https://docusaurus.io/docs/en/publishing.html) page to have broken links, or links not properly rendered from markdown.

**Comment by JoelMarcey** [comment]
@meows Thank you for noticing this. @yangshun noticed it as well. We turned off translations for now while we investigate why this is happening.
