### ISSUE TITLE
Custom styles applying to react-toggle classes interfere with other uses

### ISSUE THREAD

**Issue by ineffyble** [facebook/docusaurus#5586]
### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [ ] I have tried the `npm run clear` or `yarn clear` command.
- [ ] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io
- [ ] I have read the console error message carefully (if applicable)

### Description

Docusaurus has a modified version of react-toggle as part of the classic theme. This modified version uses the same CSS selectors as the original, meaning the styles apply to all instances of react-toggle on the page.

While the styling tweaks are not insurmountable, the issue is that the styles hardcode the toggle to "checked" when the dark theme is active.

This means that if I try and use react-toggle in a component on my Docusaurus site, toggling to the Dark theme will also visually move my other toggle, despite it not being activated.

The only solution is to add a custom class to your own toggle and create override styles to restore original behaviour.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues)?

Yes

## Steps to reproduce

Use https://new.docusaurus.io to create a CodeSandbox reproducible demo of the bug.

1. Add react-toggle to a Docusaurus project
1. Create a page with a custom instance of a `<Toggle>`
1. Use the Navbar theme toggle to change to dark theme

## Expected behavior

The custom toggle on the page would not be affected.

## Actual behavior

The custom toggle on the page moves to the right and appears checked.

## Your environment

- Docusaurus version used: 2.0.0-beta.6
- Environment name and version (e.g. Chrome 78.0.3904.108, Node.js 10.17.0): Chrome 93.0.4577.82, Node 16
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): MacOS 11.6

## Reproducible demo

![Screen Recording 2021-09-18 at 4 27 02 pm](https://user-images.githubusercontent.com/834880/133878765-5282bc49-a680-4f66-b5c8-debd18b59202.gif)

https://stackblitz.com/edit/github-p2xdx9?file=src/pages/index.js

(Paste the link to an example repo, including a `docusaurus.config.js`, and exact instructions to reproduce the issue.)

**Comment by lex111** [comment]
Our implementation of toggle intentionally has CSS classnames like in react-toggle. Wonder in what cases you need to use additional react-toggle instance?

**Comment by ineffyble** [comment]
Tweaking the style of those classnames is one thing, I would argue literally breaking them for any other usage is another.

As for cases, well, Docusaurus is a framework for websites. People building websites with interactive components, or indeed Docusaurus plugins, may want to use a toggle, either directly or as part of [one of the many packages that use it under the hood](https://www.npmjs.com/browse/depended/react-toggle).

In my case I'm writing a Docusaurus plugin to allow toggling between viewing rendered Markdown and PDF original documents for the page.

**Comment by lex111** [comment]
Fair enough, we left those class names to make it easier for people who were customizing react-toggle styles (if any), but now I realize it was wrong decision. For our own react-toggle implementation, we need to use isolated styles. Will be resolved in #5592.
