### ISSUE TITLE
dev server not hot reloading static file changes 

### ISSUE THREAD

**Issue by seanwuapps** [facebook/docusaurus#5587]
### Prerequisites

- [x] I'm using the latest version of Docusaurus.
- [x] I have tried the `npm run clear` or `yarn clear` command.
- [x] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [x] I have tried creating a repro with https://new.docusaurus.io
- [x] I have read the console error message carefully (if applicable)

### Description

dev server's HMR doesn't seem to pick up file changes inside the `static` folder

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues)?
yes

## Steps to reproduce
While the dev server is running
1. replace logo.svg or change its content
2. notice the browser does not reflect change without a manual refresh.

## Expected behavior

The browser automatically reflects static asset change. 

## Actual behavior
The browser does not auto reflect the change, have to do a manual page refresh.

## Your environment

- Public source code: https://stackblitz.com/edit/github-y6dgvo?file=static/img/logo.svg
- Public site URL: https://github-y6dgvo.stackblitz.io
- Docusaurus version used: 2.0.0-beta.6
- Environment name and version: Chrome 93.0.4577.82, Node.js 14.15.0
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): Windows 10

## Reproducible demo

https://stackblitz.com/edit/github-y6dgvo?file=static/img/logo.svg

**Comment by slorber** [comment]
Thanks, we'll handle this after the upgrade of https://github.com/facebook/docusaurus/pull/5420

We currently use an express middleware for the static folder which should probably removed

**Comment by lex111** [comment]
Fixed in #5420, will be available in next release.
