### ISSUE TITLE
🐛 DocusaurusConfig required types don't match documentation

### ISSUE THREAD

**Issue by bmiddha** [facebook/docusaurus#5588]
### Prerequisites

- [x] I'm using the latest version of Docusaurus.
- [x] I have tried the `npm run clear` or `yarn clear` command.
- [x] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [x] I have tried creating a repro with https://new.docusaurus.io
- [x] I have read the console error message carefully (if applicable)

### Description

TypeScript type definitions for `DocusaurusConfig` have required types which are labeled as optional in the documentation ([docusaurus.config.js API Reference](https://docusaurus.io/docs/docusaurus.config.js)).

![image](https://user-images.githubusercontent.com/5100938/133919959-04d466f1-b56a-46e6-bf37-de4bcbb7dad7.png)

According to the documentation, the only required keys in the config are `baseUrl`, `title`, and `url`. The types for the config also include the following as required types.

- `baseUrlIssueBanner`
- `trailingSlash`
- `i18n`
- `onBrokenLinks`
- `onBrokenMarkdownLinks`
- `onDuplicateRoutes`
- `noIndex`
- `themeConfig`

The documentation example also include using the js doc style to annotate types. This works fine on variable declarations but not on the `module.exports` line.

Example from code sandbox. (this is also consistent when running `tsc` to check types`)

Using `const` and then exporting: 

![image](https://user-images.githubusercontent.com/5100938/133919618-5f1a04e8-5f66-4fb2-82ca-21b61571f68f.png)

![image](https://user-images.githubusercontent.com/5100938/133919575-223c4d38-d5bf-4f58-9563-413b621fdab6.png)

Using `module.exports`:

![image](https://user-images.githubusercontent.com/5100938/133919583-959dc9c5-e907-4e29-8e6f-eaec9b4b83fa.png)

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues)?

Yes, I have.

## Steps to reproduce

Use https://new.docusaurus.io to create a CodeSandbox reproducible demo of the bug.

1. Change `docusaurus.config.js` to contain only the required keys from docs. It should have the following contents:
```
// @ts-check
/** @type { import('@docusaurus/types').DocusaurusConfig } */
const config = {
  url: "example.com",
  baseUrl: "/",
  title: "Example"
};

module.exports = config;

```
2. Install and run `tsc` to check types
```shell
npm i -g typescript
tsc --noEmit --allowJs --skipLibCheck docusaurus.config.js
```

## Expected behavior

Type checking for config file is consistent with documentation and passes with just `baseUrl`, `title`, and `url`.

## Actual behavior

Type checking fails with the following message when only the required keys (as per documentation):

```
docusaurus.config.js:3:7 - error TS2740: Type '{ url: string; baseUrl: string; title: string; }' is missing the following properties from type 'DocusaurusConfig': baseUrlIssueBanner, trailingSlash, i18n, onBrokenLinks, and 4 more.

3 const config = {
        ~~~~~~


Found 1 error.
```

## Reproducible demo

Use https://new.docusaurus.io to create a CodeSandbox reproducible demo of the bug.

<https://codesandbox.io/s/zen-bird-0pj9q?file=/docusaurus.config.js>

```js
// @ts-check
/** @type { import('@docusaurus/types').DocusaurusConfig } */
const config = {
  url: "example.com",
  baseUrl: "/",
  title: "Example"
};

module.exports = config;

```

![image](https://user-images.githubusercontent.com/5100938/133919432-d83ea41a-494a-4cf5-b03a-b6cc8fb99fdc.png)

**Comment by slorber** [comment]
Thanks, make sense to have an exposed type that match our required doc fields.

Didn't know that `// @ts-check` was required, we should probably add that by default

Note our doc add extra parenthesis for module exports jsdoc type to work.

```js
/** @type {import('@docusaurus/types').DocusaurusConfig} */
(module.exports = {
  title: 'Docusaurus',
  tagline: 'Build optimized websites quickly, focus on your content',
  organizationName: 'facebook',
});
```
