### ISSUE TITLE
On build, docusaurus creates a "Tags" page

### ISSUE THREAD

**Issue by mfaux** [facebook/docusaurus#5599]
## 🐛 Bug Report

On build, docusaurus creates a "Tags" page at:

```
tags\index.html
```

...which renders as:

![image](https://user-images.githubusercontent.com/1324114/134192939-56d7bfe3-df26-449d-932b-ffe60fb37172.png)

### Prerequisites

- [x] I'm using the latest version of Docusaurus.
- [ ] I have tried the `npm run clear` or `yarn clear` command.
- [ ] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io
- [ ] I have read the console error message carefully (if applicable)

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues)?

(Write your answer here.)

## Steps to reproduce

Navigate to the following page to see an example:

https://docusaurus.io/docs/tags

## Your environment

- Docusaurus version used: 2.0.0-beta.6

## Reproducible demo

Navigate to the following page to see an example:

https://docusaurus.io/docs/tags

**Comment by slorber** [comment]
Yes this is a new docs tags feature, but we should probably disable this when there are no tags 😅
