### ISSUE TITLE
Add unit testing framework

### ISSUE THREAD

**Issue by JoelMarcey** [facebook/Docusaurus#56]
.... maybe with Jest.

That way we can regression test changes, etc.

**Comment by yangshun** [comment]
Jest has been added. We can close this 😄

**Comment by JoelMarcey** [comment]
Good to close this - but I think we have more tests that we can add down the line. We should probably call those out separately.

**Comment by yangshun** [comment]
Sure, there's another issue tracking tests here - https://github.com/facebook/Docusaurus/issues/263

We might be able to add them to that issue
