### ISSUE TITLE
Fast track fails to start

### ISSUE THREAD

**Issue by Sebring** [facebook/docusaurus#5600]
### Prerequisites

- [x] I'm using the latest version of Docusaurus.
- [ ] I have tried the `npm run clear` or `yarn clear` command.
- [ ] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io
- [ ] I have read the console error message carefully (if applicable)

### Description

I was following the fast track
`npx @docusaurus/init@latest init my-website classic`
all good

Next step to start the server failed
```bash
$ npx docusaurus start
  √ gifsicle pre-build test passed successfully
  √ jpegtran pre-build test passed successfully
  √ optipng pre-build test passed successfully
Error: No siteConfig.js file found in website folder!
$
```

> Running `yarn` then `yarn start` did work.

## Steps to reproduce

1. `npx @docusaurus/init@latest init my-website classic`
1. `npx docusaurus start`

## Expected behavior

Dev server up and running.

## Actual behavior

`Error: No siteConfig.js file found in website folder!`

## Your environment

* Windows 10
* node -v // 14.17.4
*

**Comment by slorber** [comment]
You missed `cd my-website`
