### ISSUE TITLE
will sidebar support wildcard item?

### ISSUE THREAD

**Issue by honeytidy** [facebook/docusaurus#5607]
like this:
```
module.exports = {
  mySidebar: [
    {
      type: 'category',
      label: 'Getting Started',
      items: ['myfolder/*'],
    },
  ],
};
```
then all the subfile in myfolder will show on the sidebar.

**Comment by slorber** [comment]
You can use the "autogenerated" type for this use-case:

```
module.exports = {
  sidebar: [
    {
      type: 'autogenerated',
      dirName: 'myfolder',
    },
  ],
};
```

https://docusaurus.io/docs/sidebar#sidebar-item-autogenerated

sidebar generation logic is configurable through plugin options, but the default behavior should work fine
