### ISSUE TITLE
Wrong link showing up after building Docusaurus website

### ISSUE THREAD

**Issue by kimlimjustin** [facebook/docusaurus#5617]
### Prerequisites

- [x] I'm using the latest version of Docusaurus.
- [x] I have tried the `npm run clear` or `yarn clear` command.
- [x] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io
- [x] I have read the console error message carefully (if applicable)

### Description

The link of the `a` tag on the `index.jsx` file went wrong when building the docusaurus website but it's all okay when running the local development.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues)?

yes

## Steps to reproduce
I don't think I could host the production on code sandbox, could I? However, here's the code https://github.com/kimlimjustin/xplorer/blob/master/docs/src/pages/index.jsx

## Expected behavior
I hope the link is just okay (same as when development).

(Write what you thought would happen.)

## Actual behavior
The link is just broken.

https://user-images.githubusercontent.com/61906684/134792663-c74273e7-2034-4387-b88e-a98612c44651.mp4

## Your environment

- Public source code: https://github.com/kimlimjustin/xplorer
- Public site URL: https://xplorer.vercel.app
- Docusaurus version used: 2.0.0-beta.6
- Environment name and version (e.g. Chrome 78.0.3904.108, Node.js 10.17.0): Chrome Version: 94.0.4606.6`, Node.js: 14.15.0
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): Windows 11 Insider build

## Reproducible demo

Here's the source code: https://github.com/kimlimjustin/xplorer/blob/master/docs/src/pages/index.jsx

**Comment by kimlimjustin** [comment]
Btw, I tried replacing `<a>` tag with the `Link` tag but still the same problems. Here's the code
![image](https://user-images.githubusercontent.com/61906684/134793135-77399fa0-f568-495b-b049-89d22a86b0fd.png)

**Comment by Josh-Cena** [comment]
Try running `yarn clear`? Also your site builds super fast👀

**Comment by kimlimjustin** [comment]
> Try running `yarn clear`?

Yep, also removed all `node_modules` and `yarn.lock` and reinstall. Same bug.

**Comment by kimlimjustin** [comment]
https://user-images.githubusercontent.com/61906684/134805293-a680cad2-37fb-4685-a8a4-8f8ab103ce84.mp4

Here's the screen record.

**Comment by kimlimjustin** [comment]
> Can you reproduce this bug in a newly initialized Docusaurus site with the same config?

Yes if I copy the whole document of `index.jsx`.

> Often, adding extra paragraphs and divs around the problematic elements is a good-enough workaround.

It works, but it's just annoying since the link is on a paragraph and I have to fight against the CSS.

**Comment by slorber** [comment]
Finally I was able to find the cause, happy to get this solved!

https://github.com/facebook/docusaurus/pull/5629
