### ISSUE TITLE
Broken links on site after translation

### ISSUE THREAD

**Issue by yangshun** [facebook/Docusaurus#564]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

### Environment

(OS, Node, npm, yarn)

### Steps to Reproduce

1. Load https://docusaurus.io/docs/en/site-preparation.html. Try to click on the "installing Docusaurus" link. It leads to a 404.
2. Load https://docusaurus.io/docs/en/publishing.html. The markdown links are broken.

The links are being translated to Spanish on the English page and that caused the behavior above.

### Reproducible Demo

Access the URLs above.

**Comment by yangshun** [comment]
The translations were turned off in #565 so that as to not break the links. To reproduce the bug, turn on Espanol in `languages.js`.

**Comment by JoelMarcey** [comment]
@yangshun I am still trying to figure this out. Haven't made too much progress yet.

**Comment by yangshun** [comment]
Cool! I haven't really looked into it yet as I was busy with other work. I may only have time next weekend to look into it. I guess it's not really urgent to fix after we turned off Espanol.

**Comment by JoelMarcey** [comment]
We are working with Crowdin to try to fix this.
