### ISSUE TITLE
Copying code block content doesn't preserve newlines on Firefox

### ISSUE THREAD

**Issue by Martinsos** [facebook/docusaurus#5663]
### Prerequisites

- [x] I'm using the latest version of Docusaurus.
- [x] I have tried the `npm run clear` or `yarn clear` command.
- [x] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [x] I have tried creating a repro with https://new.docusaurus.io
- [x] I have read the console error message carefully (if applicable)

### Description

Open https://docusaurus.io/docs/markdown-features/code-blocks in Firefox, select piece of code from code block, press Ctrl+C to copy it, paste it anywhere (e.g. in text editor), and notice how newlines are lost.

On Chrome this problem doesn't exist and newlines are correctly preserved/captured.

If "copy" button (in the top-right corner) is used, newlines are preserved though, even on Firefox. But "copy" button requires copying the whole block of code, you can't copy just part of it.

I tried doing the same thing at https://mdxjs.com/, and there copying works ok, newlines are preserved on Firefox.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues)?

Yes

## Your environment

ArchLinux 5.14.7-arch1-1, Firefox 93.0 (64-bit).

**Comment by slorber** [comment]
Couldn't reproduce on Firefox 0.92 MacOS

**Comment by slorber** [comment]
oh I can reproduce indeed, it's the selection that can't copy lines, not the copy button that works everywhere.

**Comment by Martinsos** [comment]
> oh I can reproduce indeed, it's the selection that can't copy lines, not the copy button that works everywhere.

Exactly! The problem is, sometimes a block of code might be relatively big and somebody might need to copy just a part of it. We had this situation in our tutorial, where we guide people to copy the highlighted piece of the code, and then user reported this issue on firefox.
