### ISSUE TITLE
🐞Bug: The color generator doesn't work when an input string starts with `#`

### ISSUE THREAD

**Issue by Andrewnt219** [facebook/docusaurus#5665]
## 📚 Documentation

**Version**: 2.0.0-beta.6

**Description**: The color generator doesn't work when an input string starts with `#` (e.g. `#ccc`). It should handle both with or without the prefix `#`.

### Reproduce

1. Go to  [Styling Your File With Infima](https://docusaurus.io/docs/styling-layout#styling-your-site-with-infima)
2. In the primary color input, enter a color with the prefix `#`. For example, `#ccc`
3. The colors inside the result table are not updated

### Expected behavior

The result table should show all shades for the color `#ccc`

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## 🗝 Solution

It should be fixed by checking if the string already has the prefix `#` or not before manually assigning the prefix `#` to all `colorValue`. I'd gladly send a PR for this issue.

https://github.com/facebook/docusaurus/blob/33a85c71aa86a676cd4079936582e3f8de5d7a3e/website/src/components/ColorGenerator/index.tsx#L95-L100

**Comment by slorber** [comment]
Totally agree, already noticed it was quite annoying UX

**Comment by Andrewnt219** [comment]
Look like I'll have to work on Gitpid for now. Can you assign the issue to me?
