### ISSUE TITLE
Building on a Directory with Symlinks on Windows failing with TypeError

### ISSUE THREAD

**Issue by tavomaciel** [facebook/docusaurus#5679]
### Prerequisites

- [x] I'm using the latest version of Docusaurus.
- [x] I have tried the `npm run clear` or `yarn clear` command.
- [x] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [x] I have tried creating a repro with https://new.docusaurus.io
- [x] I have read the console error message carefully (if applicable)

### Description

It seems that https://github.com/facebook/docusaurus/issues/3272 is occurring again on symlink directories in Windows, but with a more cryptic error.

For context, I have symlink `~/dev` which links to `/c/Users/tavomaciel/Documents/Visual Studio 2017/Projects/`  (don't ask me why, historical reasons lol) where I create and manage my projects.

To my surprise building when my bash session is at any subdir below the symlink breaks completely. The devserver runs, and even serves the main page, but can't serve any of the subdocs: permaloading and no results. The console and the build all show the same error you can see below on the "Actual Behavior" section.

i.e. building at `~/dev/my-website` breaks, but `/c/Users/tavomaciel/Documents/Visual Studio 2017/Projects/my-website` works just fine.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues)?

Yes.

## Steps to reproduce

1. Enter in a symlinked dir, run `npm init docusaurus@latest my-website classic`
1. `cd my-website`
2. Run `npm run build`, it should fail.
3. Run `cd -P ..` so you leave the directory `my-website` but follow the symlink to the physical location
1. `cd my-website`
2. Run `npm run clear; npm run build`, it should succeed.

## Expected behavior

Running `npm run build` from a symlink should act exact the same as running the command from the actual directory.

## Actual behavior

`npm run build` fails if you're in a symlink in any level of your current pwd.
The errors read as following:

```
Docusaurus Node/SSR could not render static page with path "/docs/tutorial-extras/translate-your-site" because of following error:

TypeError: Cannot destructure property 'description' of 'metadata' as it is undefined.
    at DocItem (main:4915:219)
    at d (main:52023:498)
    at bb (main:52026:16)
    at a.b.render (main:52032:43)
    at a.b.read (main:52031:83)
    at Object.exports.renderToString (main:52042:138)
    at doRender (main:4462:356)
    at async serverEntry_render (main:4461:294) 
```
With the same error message emitted at every markdown file.

## Your environment

- Bash environment: Git Bash/Cygwin
- Docusaurus version used: `2.0.0-beta.6`
- Environment name and version (e.g. Chrome 78.0.3904.108, Node.js 10.17.0): `NPM 6.14.15`, `Node.js v14.18.0` 
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): `Windows 10 Pro Version 1903`

**Comment by softmarshmallow** [comment]
I'm having the same issue on Mac. How did you Resolved it?

**Comment by tavomaciel** [comment]
@softmarshmallow The new version after the fix worked fine for me.
But while that wasn't out, I just avoided working from the symlinked location.
