### ISSUE TITLE
front matter option "displayed_sidebar" & "hide_sidebar"

### ISSUE THREAD

**Issue by Josh-Cena** [facebook/docusaurus#5686]
### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues)?

Yes

### Has this been requested on [Canny](https://docusaurus.io/feature-requests)?

No

## Motivation

We have two item types: `doc` which creates both the sidebar association and the link, `ref` which creates just the link but not association (the sidebar will not show up on that page). We naturally want a third: `association` that creates the association but not the actual link.

Use-case: home pages of docs sites would use the sidebar as navigation, but itself shouldn't necessarily appear in that sidebar (typically we go back by clicking the logo or using a navbar link).

## API Design

A new sidebar item type `association` would be sufficient. It might still take all the props of `doc` or `ref` for uniformity (we won't throw during validation), but they don't do anything.

The `association` item can be declared anywhere in the sidebar, because it doesn't go into the rendered structure.

## Have you tried building it?

It would literally be just 20 lines of code in the doc metadata generation logic. But I'll be implementing this after the category index page thing (or at least after #5678)

**Comment by Josh-Cena** [comment]
> Who expressed this need exactly?

Me, plus three users on Discord.

> Why having a custom landing page isn't better?

It's hard to describe. Look at this page: https://docs.luxalgo.com/ The need is that: 
- On desktop, the doc sidebar shouldn't be shown;
- On mobile, the sidebar should be shown when clicking on the hamburger, instead of the main navbar (because... my client thinks that makes navigation less confusing).

Therefore, this page has to be part of the docs plugin (which I implemented by importing a React component into the MD page), or else it won't know about the docs sidebar. On the other hand, it should do absolutely nothing _with_ that sidebar—the only thing it should do is getting itself registered.

I don't see how this use-case can be realized without sufficient hacking (I hope I'm already one of the guys most familiar with the internal details). Currently I swizzled `DocSidebar` and hided any link with label "Home", but that's straight hack.

> Is `association` the best name? I'm already not a fan of `ref`, it's not very intuitive and we don't really understand that it is about a doc without reading the documentation.

`ref` is a bad name, particularly because the documentation is already unclear on this. But if we stress on the idea of "association", the corresponding item type should be easy to understand. For a normal user, it doesn't appear that a sidebar is an auxiliary (metadata) of the doc—they would think the docs _belong_ to a sidebar. We need to tweak that understanding.

**Comment by Josh-Cena** [comment]
> If you create an association, the sidebar should render on both mobile+desktop, not just mobile => does not solve your use-case

Yeah, my use-case may not be the best to illustrate this API.

So adding a doc in a sidebar creates a two-way binding: sidebar includes the doc link, doc page renders the sidebar. `ref` removes the doc-to-sidebar binding (doc page doesn't render sidebar), and `association` removes the sidebar-to-doc binding (sidebar won't include the link). I think this explanation is good enough for the documentation purpose, but `ref` itself is a bad name, yeah

> `frontMatter.sidebar_deskop = false` + `frontMatter.sidebar_mobile = 'sidebarName'`

I thought about that, but this means the sidebar keys are no-longer irrelevant on the user side. But it certainly makes sense 👍

> `{type: "doc", sidebar: "sidebarName"}`

Won't that create two sidebar associations, just like declaring the same doc in two sidebars? What's the use case?

**Comment by slorber** [comment]
> Now they do matter :P

yes 🤪

**Comment by Josh-Cena** [comment]
Actually, I think there are many other layout-related metadata that can accept `desktop` + `mobile` (`hide_table_of_contents` for example). This would be a good place to start

**Comment by slorber** [comment]
> The former will accept screen-size-based config

You mean `hide_sidebar: 640px` or `hide_sidebar: mobile`?

Can this make sense for any use-case?

```yml
---
sidebar: 
  mobile: sidebarA
  desktop: sidebarB
---
```
