### ISSUE TITLE
Blog: accept custom reading time options

### ISSUE THREAD

**Issue by Josh-Cena** [facebook/docusaurus#5693]
## 🚀 Feature

I'm working on the reading-time library renovation, and I plan to add much more options than what are currently available. (e.g. different reading speeds for CJK and Latin languages) It would be cool if we can expose these options to the end users.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues)?

Yes

### Has this been requested on [Canny](https://docusaurus.io/feature-requests)?

No

## Motivation

To make use of the customizability of `reading-time`—also, sometimes the default reading time is just not sensical enough. 

## API Design

A new plugin option `readingTimeOptions` which is directly passed to the `readingTime` function. Currently the options only include `wordsPerMinute` and `wordBound`, but there will be many more. cf https://github.com/ngryman/reading-time/pull/42#issuecomment-919900955

## Have you tried building it?

No

**Comment by Josh-Cena** [comment]
Actually I think injecting the locale is a bad idea. Users can write Chinese posts in an English locale or vice versa, and really we should just differentiate articles by their content, not by their locale.

Should be like this:

```ts
readingTime: ({content, defaultReadingTime}) => defaultReadingTime(content, {/* some options */}).minutes
```

**Comment by slorber** [comment]
> Actually I think injecting the locale is a bad idea. Users can write Chinese posts in an English locale or vice versa, and really we should just differentiate articles by their content, not by their locale.

So you would have to "guess" the locale based on content? 

> (e.g. different reading speeds for CJK and Latin languages)

How does the lib (or callback) know the reading speed difference if we don't provide it per language?

--- 

```js
readingTime: ({content, defaultReadingTime}) => defaultReadingTime(content, {/* some options */}).minutes
```

Injecting `defaultReadingTime` makes sense for the sidebar items generator so that people can "enhance" it with some extra logic. Do you have a similar use-case for enhancing the default reading time?

**Comment by slorber** [comment]
Makes sense, and we probably don't want to recommend a particular npm lib in our doc just to implement a fallback

What if the user wants to provide the reading time as frontMatter?

Does it make sense to keep it as `number` or maybe we should do the translation as a string on the Node.js side?

**Comment by Josh-Cena** [comment]
> What if the user wants to provide the reading time as frontMatter?

Yes, and maybe they want to tweak the options on a per-doc basis as well—we can support that by passing front matter into the callback. No problem.

> Does it make sense to keep it as `number` or maybe we should do the translation as a string on the Node.js side?

I prefer to keep it as number, at least for the callback (we _can_ do the translation in the plugin). We don't want the user to bear too much implementation burden.
