### ISSUE TITLE
Interpolate variables in the MDX

### ISSUE THREAD

**Issue by apostololeg** [facebook/docusaurus#5700]
_Thank you all for Docusaurus, it's really easy and understandable_ 🙌 

## 💥 Proposal

Following the https://github.com/facebook/docusaurus/issues/395#issuecomment-925703543 
we are really need ability to interpolate variables in MDX markup of *.md files.

For example:
```js
const data = "azaza";

// we wish this:
'''jsx
  const data = "{data}";
'''

// to become:
'''jsx
  const data = "azaza";
'''
```

**Comment by derekm** [comment]
For variables in code blocks, see here: https://github.com/mdx-js/mdx/issues/1095#issuecomment-967511279

**Comment by JasonZhLiang** [comment]
@slorber do you have a code example of that remark plugin to substitute the placeholder in MD files?

**Comment by slorber** [comment]
No official example I actually tried to share but I guess this could be an example:
https://github.com/angeloashmore/gatsby-remark-find-replace/blob/master/src/index.js

**Comment by JasonZhLiang** [comment]
@slorber thanks a lot, you save my day!
