### ISSUE TITLE
Version in header clashes with search box on mobile

### ISSUE THREAD

**Issue by SimenB** [facebook/Docusaurus#571]
### Is this a bug report?
 Yup

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?
 Yup

### Environment

N/A

### Steps to Reproduce

1. Navigate to docusaurus.io on mobile
2. See the issue in the header

### Expected Behavior

Not sure. Make search smaller until clicked?

### Actual Behavior

![image](https://user-images.githubusercontent.com/1404810/38820138-6a841ba0-419d-11e8-8307-40adf9bcb20e.png)

### Reproducible Demo

https://docusaurus.io/

**Comment by JoelMarcey** [comment]
That’s funny - I literally was just about to file this issue myself 😄. Saw it over the weekend.

Gotta work some CSS magic I guess.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
