### ISSUE TITLE
Cannot build after upgrade to 2.0.0-beta.7

### ISSUE THREAD

**Issue by yobyot** [facebook/docusaurus#5716]
### Prerequisites

- [X ] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X ] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io _cannot do, private content_
- [X ] I have read the console error message carefully (if applicable)

### Description

2.0.0-beta.7 breaks build with error message
```
Unable to build website for locale "en".
Error: This should not be reached (debug: got type comment)
```

Here's an image of the output:

<img width="1484" alt="break" src="https://user-images.githubusercontent.com/14332263/137532888-72409b0d-6a65-4c3f-9d86-b5f5f8b2e17d.png">

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues)?

_Have read._

## Steps to reproduce

Use https://new.docusaurus.io to create a CodeSandbox reproducible demo of the bug.

(Write your steps here:)

1. Step 1...
1. Step 2...
1. Step 3...

_Sorry, content in repo cannot be exported due to confidentiality restrictions._

## Expected behavior

_We made a minor change to content, just a Markdown table, and our build process terminated as you see here._

## Actual behavior

_See above. CI/CD pipeline in Azure DevOps terminates with a bash error exit code_

## Your environment

- Public source code:
- Public site URL:
- Docusaurus version used: _2.0.0-beta6 (ADO pulls latest by default)_
- Environment name and version (e.g. Chrome 78.0.3904.108, Node.js 10.17.0): _Chrome 94.0.4606.81_
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): _Ubuntu 18.04 LTS_ 

## Reproducible demo

_Sorry, cannot comply with this due to company confidentiality restructions. But I think it's a bug in beta7 that should I suspect you'll be seeing more of shortly. We just happened to try and build a couple of hours after beta7 was released._

Use https://new.docusaurus.io to create a CodeSandbox reproducible demo of the bug.

(Paste the link to an example repo, including a `docusaurus.config.js`, and exact instructions to reproduce the issue.)

**Comment by lex111** [comment]
According to your error stack, it has something to do with docusaurus-search-local https://github.com/cmfcmf/docusaurus-search-local. If you disable this plugin, the site will successfully built?

**Comment by lex111** [comment]
Actually, in the new version, we no longer remove HTML comments from final pages, and local search plugin does not know how to deal with this type of HTML elements. So I recommend you to inspect content of your Markdown files and remove possible HTML comments (`<!-- HTML comment -->`).

**Comment by Josh-Cena** [comment]
Fix proposed. Let's see how quickly it gets reviewed 👀

**Comment by slorber** [comment]
Thanks for finding the issue and submitting a fix 👍
