### ISSUE TITLE
NavbarLogo doesn't have width and height attribute 

### ISSUE THREAD

**Issue by sohamsshah** [facebook/docusaurus#5724]
### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io
- [X] I have read the console error message carefully (if applicable)

### Description

The `img` tag in the NavbarLogo attribute in docusaurus.config.js file to add Logo to Navbar doesn't have any option/prop to set the `height` and `width` of the logo. Because of this, the Lighthouse Report fails and suggests to add `width` and `height` to the logo image.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues)?

Yes, I have Read it.

## Steps to reproduce

1. Run Lighthouse test on any docusaurus powered website
1. See the diagnostics message that suggests to add `width` and `height` attribute
1. Also in `inspect` element, width and height attributes are missing.

## Expected behavior

There should be props for this in order to add height and width to image along with defaults.

## Screen Shot
![image](https://user-images.githubusercontent.com/47717492/137598357-fc8cae8e-fe25-459f-9d41-f90225181ba2.png)

## Your environment
- Docusaurus version used: latest
- Environment name and version (e.g. Chrome 78.0.3904.108, Node.js 10.17.0): Chrome 87
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): Windows 10

I am new to the community and willing to contribute towards this issue. Please let me know more insights upon this. Would like to take this up!

**Comment by Josh-Cena** [comment]
As a further request: can we make all images within a Markdown file have the `height` (and `width`, maybe) attribute as well? Is it possible to fetch this data when we convert them to `require` calls?

This ensures that there's no layout shift as the images load.
