### ISSUE TITLE
Dynamic tabs configuration doesn't work with 2.0.0-beta.7

### ISSUE THREAD

**Issue by camtheman256** [facebook/docusaurus#5729]
### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io
- [X] I have read the console error message carefully (if applicable)

### Description

Dynamic tab configuration causes Docusaurus to think my `<Tabs>` children are undefined, which breaks my build and crashes with client side rendering.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues)?

Yes.

## Steps to reproduce

https://codesandbox.io/s/github/mit-dormcon/website/broken-tabs should reproduce the issue, but I can't get the sandbox to work. Just updating to 2.0.0-beta.7 caused the issue.

## Expected behavior

I expected the tabs to render as they have in 2.0.0-beta.6. The correct behavior looks like: https://dormcon.mit.edu/about/archive.

## Actual behavior

Build crashes, and page doesn't render on client side either. Error message looks like:

```
Error: Docusaurus error: Bad <Tabs> child <undefined>: all children of the <Tabs> component should be <TabItem>, and every <TabItem> should have a unique "value" prop.
    at main:4922:7
    at main:51927:388
    at O (main:51926:230)
    at O (main:51927:44)
    at Object.P [as map] (main:51927:355)
    at TabsComponent (main:4920:249)
    at d (main:48443:498)
    at bb (main:48446:16)
    at a.b.render (main:48452:43)
    at a.b.read (main:48451:83)
```

The offending code is at https://github.com/mit-dormcon/website/blob/broken-tabs/docs/archive.mdx, which works at 2.0.0-beta.6 but not 2.0.0-beta.7.

## Your environment

- Public source code: https://github.com/mit-dormcon/website/tree/broken-tabs
- Public site URL: https://dormcon.mit.edu/about/archive
- Docusaurus version used: 2.0.0-beta.7 has the issue, live version is using 2.0.0-beta.6
- Environment name and version (e.g. Chrome 78.0.3904.108, Node.js 10.17.0): Node v14.8.1
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): Ubuntu 20.04.3 LTS

## Reproducible demo

https://codesandbox.io/s/github/mit-dormcon/website/broken-tabs

**Comment by Josh-Cena** [comment]
Oops, sorry, should be fixed by #5732.
