### ISSUE TITLE
Error reported by "useBaseUrl" during construction

### ISSUE THREAD

**Issue by zhgtt** [facebook/docusaurus#5736]
### Prerequisites

- [x] I'm using the latest version of Docusaurus.
- [x] I have tried the `npm run clear` or `yarn clear` command.
- [x] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [x] I have tried creating a repro with https://new.docusaurus.io
- [x] I have read the console error message carefully (if applicable)

### Description

- This error is always reported during construction
- used: `yarn build`

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues)?

(Write your answer here.)

## Expected behavior

(Write what you thought would happen.)

## Actual behavior

(Write what happened. Add full console log messages and screenshots, if applicable.)

## Screen Shot
![image](https://user-images.githubusercontent.com/39938981/137728331-30fe7439-b576-480b-8c63-1388dec3dac9.png)

## Your environment

- Docusaurus version used: latest
- Environment name and version (e.g. Chrome 78.0.3904.108, Node.js 10.17.0):
- Operating system and version (e.g. Ubuntu 20.04.2 LTS):

(Paste the link to an example repo, including a `docusaurus.config.js`, and exact instructions to reproduce the issue.)

**Comment by slorber** [comment]
Should be fixed in https://github.com/facebook/docusaurus/pull/5753, please try the latest canary after merge
