### ISSUE TITLE
Live Code Editor be Server Side Rendered

### ISSUE THREAD

**Issue by ntucker** [facebook/docusaurus#5747]
## 💥 Proposal

It would be nice for the Editor part of live editor to be server side rendered, that way it can be previewed before the editor loads as well as improving search engine optimization.

A preliminary investigation makes me unsure of why this even is, since there's an explicit part that keys the LiveEditor component based on whether it is server side or not.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

yes

**Comment by slorber** [comment]
Hmmm yes we should try to minimize layout shifts and render code in SSR.

Not sure it's possible for the preview, but at least it should be for the editor.

https://docusaurus.io/docs/next/markdown-features/code-blocks#interactive-code-editor

With JS:

![image](https://user-images.githubusercontent.com/749374/138077816-65342740-bfaa-43d1-a76a-05105f97e40b.png)


Without JS:

![image](https://user-images.githubusercontent.com/749374/138077740-98c0c351-c984-420d-9b65-744d50d205d6.png)



----



This line looks suspicious, maybe we should get rid of it:

![image](https://user-images.githubusercontent.com/749374/138077670-0cb02a5b-684b-40b6-8e39-c4e4a1249029.png)

**Comment by Josh-Cena** [comment]
> Code blocks that aren't live are evaluated during SSR

In a perfect world we could. I think we can render a normal code block (maybe another "dummy element" for the output) during SSR and only really "evaluate" the code block during CSR. Problem is, currently the "live code block" which looks deceptively like a code block is actually a completely different component that's part of a context provider, and rendering it inevitably means sending that context value to the renderer and producing side effects, making things a little more complicated that we may have expected

**Comment by Josh-Cena** [comment]
> Can you elaborate on the side effects?

You can check the comment for #4318 and the related issue for that. The code is here: 

https://github.com/facebook/docusaurus/blob/fd41239f4fc8bdc4c266265a6f35ac568676a062/packages/docusaurus-theme-live-codeblock/src/theme/Playground/index.js#L66-L85

The code-block-looking comp is actually `EditorWithHeader` provided by `react-live`, not the default one. So if you send the actual code in SSR, the context value would be updated when the SSR output arrives at the end user, and again after hydration. But I have a solution in mind with `BrowserOnly` and using its fallback

**Comment by Josh-Cena** [comment]
@ntucker In the current situation, I just rendered a static code block during SSR. Does that look better than rendering nothing?

**Comment by ljharb** [comment]
Literally anything looks better than rendering nothing, no?
