### ISSUE TITLE
Broken link in search.md to https://docsearch.algolia.com/docs/apply

### ISSUE THREAD

**Issue by humphd** [facebook/docusaurus#5764]
## 📚 Documentation

> The service is free in most cases: just [apply to the DocSearch program](https://docsearch.algolia.com/docs/apply).

The link to https://docsearch.algolia.com/docs/apply in https://github.com/facebook/docusaurus/blob/main/website/docs/search.md?plain=1#L28 is 404.

Based on [this fix](https://github.com/algolia/docsearch/pull/1058), I think it should be pointing to https://docsearch.algolia.com/apply/ (no `/docs/`).

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

**Comment by slorber** [comment]
Cc @shortcuts maybe add a redirect?
