### ISSUE TITLE
Twitter Cards do not work for og:image

### ISSUE THREAD

**Issue by deadcoder0904** [facebook/Docusaurus#578]
pnpm.js.org uses Docusaurus but on Twitter the social cards do not appear proper. 

Checkout [this issue](https://github.com/pnpm/pnpm.github.io/issues/10) which is closed with [this PR](https://github.com/pnpm/pnpm.github.io/commit/45be93a8c14ec486fec94426ab9dd6e652cc636c) which should work.

But as you can see on https://twitter.com/deadcoder0904/status/986310714011869184 the Twitter card isn't working

So I think it might be an issue

**Comment by JoelMarcey** [comment]
@zkochan -- Do you want to try this PR out on pnpm.js.org to see if this solves the problem?

Btw, I didn't know pnpm.js.org used Docusaurus. Thanks! Site looks good.

**Comment by zkochan** [comment]
@JoelMarcey, for some reason it didn't help. The new tag is present now on the pnpm site but the image did not appear when I shared it via twitter.

**Comment by JoelMarcey** [comment]
Hmmm... 😕 

I wonder if there is a caching issue going on?

The only other thing I can think of is that `og:image` is clobbering the `twitter:image` tag somehow, causing it not to work like before.

**Comment by zkochan** [comment]
Confimed, it is some caching on Twitter's side. I just tried to share a different URL: https://pnpm.js.org/en/
and it worked 

https://screenshots.firefox.com/9PWW5CAx05b6P0Dp/twitter.com

**Comment by JoelMarcey** [comment]
@zkochan Sweet! Looks like this PR might do it then?

Just as a double-check, it wasn't a Twitter caching issue before, right? The cards were indeed broken before this PR.

**Comment by zkochan** [comment]
@JoelMarcey I think it was a caching issue to begin with. The pnpm site was shared before I added `og:image`.

**Comment by JoelMarcey** [comment]
@zkochan Ha! Ok. Well, we added a new config option anyway, just in case you want just the Twitter image 😄
