### ISSUE TITLE
Update-notifier wants to downgrade from beta.9 to beta.7

### ISSUE THREAD

**Issue by massoudmaboudi** [facebook/docusaurus#5780]
### Prerequisites

- [x] I'm using the latest version of Docusaurus.
- [x] I have tried the `npm run clear` or `yarn clear` command.
- [x] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [x] I have tried creating a repro with https://new.docusaurus.io
- [x] I have read the console error message carefully (if applicable)

### Description

I updated from version 2.0.0-beta.6 to 2.0.0-beta.8 and now I receive this warning while `npm start`.
Even When I use `npm i @docusaurus/core@latest @docusaurus/plugin-ideal-image@latest @docusaurus/plugin-sitemap@latest @docusaurus/preset-classic@latest @docusaurus/module-type-aliases@latest`, still I receive this warning.

![image](https://user-images.githubusercontent.com/18216265/138588538-86016151-312f-4168-866b-e622629caeeb.png)

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues)?

Yes

**Comment by massoudmaboudi** [comment]
Still it doesn't work with beta 9

**Comment by slorber** [comment]
yes, didn't merge the PR for beta.9

We'll see on next release 🤷‍♂️
