### ISSUE TITLE
pnpm install fails due to @mdx-js/runtime requiring React 16

### ISSUE THREAD

**Issue by kaiyoma** [facebook/docusaurus#5803]
### Prerequisites

- [x] I'm using the latest version of Docusaurus.
- [ ] I have tried the `npm run clear` or `yarn clear` command.
- [x] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io
- [x] I have read the console error message carefully (if applicable)

### Description

Docusaurus can't be installed alongside React 17.

## Steps to reproduce

Try to install this with pnpm:

```
  "dependencies": {
    "@docusaurus/core": "2.0.0-beta.8",
    "@docusaurus/preset-classic": "2.0.0-beta.8",
    "@docusaurus/theme-classic": "2.0.0-beta.8",
    "react": "17.0.2",
    "react-dom": "17.0.2"
  },
```

## Expected behavior

Packages should install.

## Actual behavior

It seems some deep dependency of Docusaurus has a strict React 16 requirement:

```
 ERR_PNPM_INVALID_PEER_DEPENDENCY  ..\..\packages\cloudvision-docs > @docusaurus/core > @docusaurus/utils: @mdx-js/runtime@1.6.22 requires a peer of react@^16.13.1 but version 17.0.2 was installed.
```

## Your environment

- Docusaurus version used: 2.0.0-beta.8
- Environment name and version (e.g. Chrome 78.0.3904.108, Node.js 10.17.0): Node 14.15.5
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): Windows 10

**Comment by slorber** [comment]
Related to https://github.com/facebook/docusaurus/issues/5664, we should probably remove the mdx-runtime usage anyway and find another solution for RSS feed content (like reading generated html files, as suggested by Titus)

**Comment by taylorreece** [comment]
I don't know if it'll help, but in my `pnpmfile.js` I made react a dependency (not peer dependency) and that seemed to get me through a Docusaurus upgrade:

```js
module.exports = {
  hooks: {
    readPackage,
  },
};

function readPackage(packageJson, context) {
  if (packageName === "@mdx-js/runtime@1.6.22") {
    packageJson.dependencies = {
      ...packageJson.dependencies,
      react: "16.13.1",
    };
  }

  return packageJson;
}
```

**Comment by CxRes** [comment]
@taylorreece The pnpm developer does his documentation on Docusaurus 2.0. So I copied his setup of `.pnpmfile`, `.npmrc` and `package.json > dependencies` and did a fresh install (after removing lock file and `node_module`). All warnings vanish for reasons I do not understand!

**Comment by Josh-Cena** [comment]
Closing because we are no longer using the MDX runtime after #6454
