### ISSUE TITLE
Add titles to issue forms

### ISSUE THREAD

**Issue by Josh-Cena** [facebook/docusaurus#5837]
Right now, [GitHub issue forms](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms) don't allow setting uneditable Markdown. Before, we had issue titles like "🐛Bug report", which can't be ported to the issue forms. Let's keep track of that.

**Comment by Josh-Cena** [comment]
Very cool😀 Noticed there isn't a title though

**Comment by lex111** [comment]
Yep, this is not currently possible, but we can prefill the title with the issue type, something like this:

![image](https://user-images.githubusercontent.com/4408379/139537102-aa9403d6-498f-41ba-a194-500a0fae4ad4.png)

**Comment by Josh-Cena** [comment]
I'd rather not prefix the title... I think the current state is pretty good already, and the title is not critical since we also have labels. I would edit the issue to remind ourselves to keep track of this

**Comment by lex111** [comment]
Agreed, especially it's a beta feature, so things can change in the future, but you can give feedback on it, if you want https://github.com/github/feedback/discussions/categories/issues-feedback

**Comment by Josh-Cena** [comment]
I'm actually loving how it currently is :D It just takes time to get used to, but issues without Markdown titles actually allow us to re-triage them to other categories, and are easier to scan
