### ISSUE TITLE
i18n automatic locale detection - provide instructions on how

### ISSUE THREAD

**Issue by urish** [facebook/docusaurus#5838]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Description

The i18n page mentions:

> Automatic locale detection: opinionated, and best done on the server

However, the word *server* links to a page which has no relevancy to the topic - it doesn't explain how to do automatic locale detection. 

I'd love to see there a link to a page / code example that actually shows to achieve automatic locale detection with Docusaurus. I couldn't find such example online, but perhaps my google-fu isn't good enough :-)

### Self-service

- [ ] I'd be willing to address this documentation request myself.

**Comment by urish** [comment]
Also, thanks for creating and maintaining Docusaurus. It's a great product!

**Comment by Josh-Cena** [comment]
> However, the word server links to a page which has no relevancy to the topic - it doesn't explain how to do automatic locale detection.
>
> I'd love to see there a link to a page / code example that actually shows to achieve automatic locale detection with Docusaurus. I couldn't find such example online, but perhaps my google-fu isn't good enough :-)

It may be a bit unclear, but what we are trying to say is that it's out of scope of Docusaurus, so we won't even be providing writeup for how to do it. (That's the general direction we are trying to take: keep everything absolutely relevant to the APIs we have ourselves, and leave it to you to figure out how other features would work.)

The "server" links to "deployment", which is just to tell you that this can be configured on the end from which you are serving your site. Hosting providers like Netlify or GH pages may not let you do arbitrary server configuration, but if you have an Apache2 or Nginx server of your own, you should be able to detect locales on the server side, and serve different contents. We leave the choice to you.

If anyone has actually done this, we'd be happy to include an external link, but hardly anything more than that

**Comment by Josh-Cena** [comment]
Concerning the link though, it makes sense to me, but maybe not to everyone: Self-hosting, Netlify, Hostman... These are all server-hosting provider choices, some of which may allow you to configure which route to serve based on the browser's language. You should check your deployment provider's documentation to see if that's possible, e.g. here's what I found for Apache2: https://gist.github.com/markhowellsmead/0c414cea619727a3618b

**Comment by urish** [comment]
Thanks for the prompt response! I understand why you want to keep the scope limited.

> If anyone has actually done this, we'd be happy to include an external link, but hardly anything more than that

I might be able to write down some instructions if I figure it out. I use a combination of Vercel and Cloudflare, so I'm pretty optimistic I'll find a way.

**Comment by Josh-Cena** [comment]
Nice:D I do think it's possible with CF. In case you are going to write something, I suggest you do it in the discussions, and add a link in the docs to that thread, so that other people can followup with their own solutions / questions / etc.

**Comment by urish** [comment]
Thanks for the suggestion! I'll try and update here once I (hopefully) got something working and opened a discussion.

**Comment by urish** [comment]
There we go - https://github.com/facebook/docusaurus/discussions/5839

There's one point which I had a problem with. When the user explicitly sets the language (by choosing from the drop down menu), I don't want to override their choice. I worked around that by looking at some headers (details in the actual issue), but it would be useful if the frontend code would somehow communicate the fact that the user made an explicit choice (cookie or a query string parameter come to mind).

**Comment by Josh-Cena** [comment]
Considering the discussion is already up, I will close the issue for now. I'm working on an i18n doc rewrite, and I will remember to include the link

**Comment by AmazingAng** [comment]
> ### Have you read the Contributing Guidelines on issues?
> 
> - [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).
> 
> ### Description
> 
> The i18n page mentions:
> 
> > Automatic locale detection: opinionated, and best done on the server
> 
> However, the word *server* links to a page which has no relevancy to the topic - it doesn't explain how to do automatic locale detection. 
> 
> I'd love to see there a link to a page / code example that actually shows to achieve automatic locale detection with Docusaurus. I couldn't find such example online, but perhaps my google-fu isn't good enough :-)
> 
> ### Self-service
> 
> - [ ] I'd be willing to address this documentation request myself.

Hey, is there any instructions on how to do automatic on docusaurus now?

**Comment by slorber** [comment]
This is outside the scope of Docusaurus to do this, but I'd suggest to use an edge function/middleware for that.

You could check request headers (or cookies) and redirect `/xyz` to `/locale/xyz` if it makes sense for your use-case.

Modern hosts (Vercel, Netlify, Cloudflare...) should all support that (not possible with GitHub pages).

https://vercel.com/docs/concepts/functions/edge-middleware
https://docs.netlify.com/edge-functions/overview/

**Comment by AmazingAng** [comment]
> This is outside the scope of Docusaurus to do this, but I'd suggest to use an edge function/middleware for that.
> 
> You could check request headers (or cookies) and redirect `/xyz` to `/locale/xyz` if it makes sense for your use-case.
> 
> Modern hosts (Vercel, Netlify, Cloudflare...) should all support that (not possible with GitHub pages).
> 
> https://vercel.com/docs/concepts/functions/edge-middleware https://docs.netlify.com/edge-functions/overview/

Thanks for the reply! 
We are hosting the website (https://wtf.academy/) on vercel, so it should be easy to adopt the edge function. Where should we put the middleware, on the server or frontend?

**Comment by wceolin** [comment]
I came here trying to find a way to properly handle locale detection. I'm currently deploying my website to Cloudflare Pages and my solution kind works. However, I wanted to set a `cookie` when the user changes the locale using the default `localeDropdown`.

Maybe I didn't search properly but I couldn't find a way to get a callback or something like that to watch for locale changes. Right now, I'm adding an event listener to the dropdown.

I know this out of the scope of Docusaurus but it feels like it could be simpler without much effort. For example, we could have a `setCookie` option that would automatically set a cookie when the locale changes:

```js
{ type: "localeDropdown", position: "right", setCookie: true }
```

Or is there a similar alternative to accomplish this that doesn't involve adding a custom script to the `head` to have an event listener watching for clicks on the dropdown menu.

I can open a PR to implement `setCookie` if think that would be a good addition.
