### ISSUE TITLE
onClick not working for custom components

### ISSUE THREAD

**Issue by DanielMSchmidt** [facebook/docusaurus#584]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

### Environment

(OS, Node, npm, yarn)

- OS: OSX
- Node: 9.11.1
- npm: 5.6.0
- yarn: - 

### Steps to Reproduce

1. Clone [my demo repository](https://github.com/DanielMSchmidt/docusaurus-onclick)
2. Run `npm install` in the `website/` directory
3. Run `npm start` in the `website/` directory
4. Visit `http://localhost:3000`
5. You should see a link named "I was not clicked"

### Expected Behavior

I would expect the `onClick` callback to be executed when the text is clicked. As a result the text should change to "I was clicked" and the console output should show up.

### Actual Behavior

If you click the text there is no console output shown and the text does not change into "I was clicked". 

### Reproducible Demo

https://github.com/DanielMSchmidt/docusaurus-onclick

**Comment by zenflow** [comment]
With Docusaurus your components get converted into static HTML at build-time, they are never mounted in the browser.

**Comment by DanielMSchmidt** [comment]
Oh, where was the piece of documentation I missed here 🙈

**Comment by JoelMarcey** [comment]
@DanielMSchmidt, if you would like to send a PR to add some documentation around this, that would be great. Maybe a sentence or two at the beginning of https://docusaurus.io/docs/en/installation.html?

**Comment by DanielMSchmidt** [comment]
@JoelMarcey I would have thought https://docusaurus.io/docs/en/site-creation.html might be a better place, would that be ok for you?

**Comment by JoelMarcey** [comment]
@DanielMSchmidt Sure. That could be a decent place too. Let's see what content will go there and then we can make the final decision. Thanks!
