### ISSUE TITLE
Minimal support for IE11

### ISSUE THREAD

**Issue by zenflow** [facebook/Docusaurus#585]
### Is this a bug report?

It's a browser compatibility issue, so Yes?

I couldn't find any documentation on supported browsers. I assume that the *modern* major browsers are all supported but what about Internet Explorer which is still a major browser? I hope we can have minimal support for it, since our library targets the latest version of *all* major browsers and our users would expect our docs/examples site to have the same browser support.  

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes I have

### Environment

irrelevant, it's a problem in the built site running in IE11, doesn't matter where the site is built

### Steps to Reproduce

1. Visit https://docusaurus.io/ in the latest version of IE

### Expected Behavior

I would expect that maybe not everything looks quite right, but the site is functional / usable. 

### Actual Behavior

It's impossible to navigate the site because the menu items in the menu bar are all smooshed together in the top right corner and it's impossible to read them or click a particular one.
 
### Reproducible Demo

Visit https://docusaurus.io/ in IE11..
![image](https://user-images.githubusercontent.com/3198597/38955656-ad8d47e8-432b-11e8-85ae-b67b21fa9cdf.png)

**Comment by yangshun** [comment]
@zenflow Would you be able to fix it? Unfortunately we only have Macs :/

**Comment by ahmadalfy** [comment]
@yangshun I would love to claim and fix this.

**Comment by yangshun** [comment]
@ahmadalfy That's great! Go ahead. Feel free to rewrite the CSS for the nav bar as well 😄

**Comment by yangshun** [comment]
@ahmadalfy If possible, could you list down the IE11 issues you intend to fix as a comment here? We can then use this issue to track the fixes.

**Comment by ahmadalfy** [comment]
@yangshun these are the issues that I found:

- [x] Navigation collapse
- [ ] Shorthand font format with `-apple-system` making the value invalid to IE11 and hence ignoring the whole declaration
- [ ] `flex-basis` and `padding` with `box-sizing: border-box` doesn't work as expected and hence causing cause on the second row of the features (one block per line, [screenshot 1](https://imgur.com/a/vRDqP3j), [screenshot2](https://imgur.com/a/Mhov0Gn))
- [ ] Massive white space between content and footer (on [installation page](https://docusaurus.io/docs/en/installation.html) , [screenshot](https://imgur.com/a/5VA9VWt) )
- [ ] Showcase page having the footer on top overlapping everything on the page ([screenshot](https://imgur.com/a/eScNlu9))

**Comment by yangshun** [comment]
Oh gosh. Would love to see your fixes if you are up for it! 🥇

**Comment by ahmadalfy** [comment]
I am working on it.

**Comment by JoelMarcey** [comment]
@ahmadalfy Thank you for fixing these! ❤️

**Comment by ahmadalfy** [comment]
@JoelMarcey you're welcome! Thanks for the motivation you gave me at F8 ❤️

**Comment by ahmadalfy** [comment]
@yangshun the last issue (on installation page) is due to the image on the content. This is a really weird bug I don't think I have ever encountered it before. The image has `max-width: 100%` and it's width is reduced but *someway* its original height is occupying the space. I am not sure how 😭

Will investigate.

**Comment by endiliey** [comment]
We had a css revamp on 1.3.0 #757

I tried this today (we are on 1.3.2) on IE11, the experience is not that bad. Seems quite functional to me

![ie11](https://user-images.githubusercontent.com/17883920/42885826-9e384040-8ad4-11e8-9666-62c686735eff.gif)
