### ISSUE TITLE
Does it provide a variable to say whether it's on mobile(phone) or PC ？

### ISSUE THREAD

**Issue by Chasen-Zhang** [facebook/docusaurus#5850]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Description

Does it provide a variable to say whether it's on mobile or PC ？I didn't see this variable in the document

### Self-service

- [ ] I'd be willing to address this documentation request myself.

**Comment by Josh-Cena** [comment]
Please, don't use issues for questions. Please move to discussions.
