### ISSUE TITLE
[npm2yarn]: `npm init` => `yarn create`

### ISSUE THREAD

**Issue by christian-bromann** [facebook/docusaurus#5861]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

See demo here: https://du0ui.sse.codesandbox.io/docs/intro

If you use `@docusaurus/remark-plugin-npm2yarn` and your code snippet is set like this:

    ```sh npm2yarn
    npm init wdio ./foo
    ```

I would expect that it would transform the yarn version to `yarn create wdio ./foo`.

### Steps to reproduce

1. create a standard docusarus page
2. add `@docusaurus/remark-plugin-npm2yarn` plugin
3. add example as mention above

### Expected behavior

I would expect that it would transform the yarn version to `yarn create wdio ./foo`.

### Actual behavior

It displays `npm init wdio ./foo` and `yarn init wdio ./foo` which results in the attempt of creating a new yarn package rather than running the `create-wdio` starter package.

### Your environment

- Public source code:
- Public site URL:
- Docusaurus version used:
- Environment name and version (e.g. Chrome 89, Node.js 16.4):
- Operating system and version (e.g. Ubuntu 20.04.2 LTS):

### Reproducible demo

https://codesandbox.io/s/nice-fire-du0ui?file=/docusaurus.config.js

### Self-service

- [x] I'd be willing to fix this bug myself.

**Comment by Josh-Cena** [comment]
We are aware of this: https://github.com/facebook/docusaurus/pull/5635#issuecomment-937806707

However, we use a 3rd party dep under the hood which is currently unmaintained. I'm discussing with others about what's the best option. I would prefer forking `npm2yarn` considering it's quite lightweight.

**Comment by Josh-Cena** [comment]
Just realized this package was developed in the first place to be used by our plugin🤷‍♂️ https://github.com/facebook/docusaurus/pull/2428

In the future we should discourage this and make everything live on our own repo / our org. Saves a lot of trouble of maintenance

**Comment by slorber** [comment]
agree 👍

**Comment by mrienstra** [comment]
Re: unmaintained 3rd-party dep ([nebrelbug/npm-to-yarn](https://github.com/nebrelbug/npm-to-yarn)): how can this conversation be moved toward a resolution?

A) Move `npm-to-yarn` code inside of this repo
B) Fork `npm-to-yarn` and put under https://github.com/facebook organization umbrella
C) Fork `npm-to-yarn` and owned by...? Random or active contributor?

Sounds like maybe (A) and (B) have both already been rejected as solutions? If so, does anyone have strong feelings about exactly how (C) looks?

CC @endiliey @lex111 @yangshun @JoelMarcey @deltice

**Comment by armano2** [comment]
for time being i created fork, with all know issues for this library

**Comment by Josh-Cena** [comment]
> A) Move npm-to-yarn code inside of this repo
> B) Fork npm-to-yarn and put under https://github.com/facebook organization umbrella
> C) Fork npm-to-yarn and owned by...? Random or active contributor?

We have discussed this ourselves and indeed (A) and (B) are not in the interest of FB (I personally like (A) the most). @slorber said he would do the forking himself, but since @armano2 offered to take this over, I do think we would take that courtesy. I would see if Sebastien is happy with that, but he'll be occupied with #5830 at the moment.

We already have a lot of forked dependencies owned by Sebastien, so there are precedents.

**Comment by armano2** [comment]
i don't mind passing ownership, moving it to him... i just care about fixing issues :P

**Comment by slorber** [comment]
Thanks 👍 

Will maintain the fork under my own name (easier to transfer later to a potential docusaurus-core org that I'm asking for) and publish under `@docusaurus` org (also a security concern).
