### ISSUE TITLE
Navbar logo and favicon images are not showing up while serving locally for sites with baseUrl

### ISSUE THREAD

**Issue by pranabdas** [facebook/docusaurus#5863]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

After updating to docusarus beta 9, the navbar logo image (and favicon image) is not showing up while serving the site locally. This happens with sites having `baseUrl` (other than `/`). If I visit `http://localhost:3000/{baseUrl}/img/favicon.ico`, I see **404 Page Not Found**. However, things seems alright while building the site.

### Steps to reproduce

1. Create a brand new site: `npx @docusaurus/init@latest init my-site classic`
2. Set a `baseUrl` in `docusaurus.config.js`, say `/test/`
3. Fire up `npm  start`. This is what I see: 
<img width="505" alt="Screenshot 2021-11-03 at 9 26 27 PM" src="https://user-images.githubusercontent.com/31024886/140068689-659bbe8a-149a-43cf-a17e-f06615a2991e.png">

4. Visit `http://localhost:3000/test/img/favicon.ico`, it gives 404 error.
5. However, `npm run build` followed by `npm run serve` correctly shows the logo.

### Expected behavior

Should be able to see the logo and favicon images correctly while serving the site locally.

### Actual behavior

Logo and favicon images are not available in website path.

### Your environment

- Public source code: NA
- Public site URL: NA
- Docusaurus version used: 2.0.0-beta.9
- Environment name and version (e.g. Chrome 89, Node.js 16.4): Safari 15.1, Node.js 16.13.0
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): macOS 11.6.1

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by edvinasmuncelis** [comment]
I'm having exactly the same issue after upgrading to 2.0.0-beta.9

**Comment by slorber** [comment]
please test the latest canary, does it work for you?

**Comment by pranabdas** [comment]
@slorber it's working alright now. Thank you.

**Comment by honeytidy** [comment]
> @slorber it's working alright now. Thank you.
How do you fix the problem? I have the same problem.

**Comment by Josh-Cena** [comment]
@honeytidy Please use the canary release: https://docusaurus.io/community/canary

**Comment by Josh-Cena** [comment]
Hi, due to the number of duplicate reports on this issue I've reopened the original one. This has already been fixed and will be released soon. If you are experiencing the same, please either stay on `beta.8` or use the canary release.
