### ISSUE TITLE
Do we need to update Algolia configurations?

### ISSUE THREAD

**Issue by juzhiyuan** [facebook/docusaurus#5867]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Description

Hi, I received one mail from `algolia` recently, it says that we need to update algolia configuration in 3 months.

The mail title is `The DocSearch team have some exciting news for you!`

![image](https://user-images.githubusercontent.com/2106987/140247983-ab79b54a-ed22-470e-ab0a-c833983f7b00.png)

Documentation: https://docsearch.algolia.com/docs/migrating-from-legacy/

Do we need to do something?

### Self-service

- [ ] I'd be willing to address this documentation request myself.

**Comment by Josh-Cena** [comment]
Docusaurus already made the migration: https://github.com/facebook/docusaurus/pull/5632

So if you did receive the mail, you should :D

**Comment by juzhiyuan** [comment]
Thanks!

**Comment by slorber** [comment]
We'll publish a blog post about this soon, but just replacing the keys should be good enough for now

**Comment by juzhiyuan** [comment]
😄
