### ISSUE TITLE
[SECURITY] `coa` is compromised

### ISSUE THREAD

**Issue by Josh-Cena** [facebook/docusaurus#5872]
***The `coa` package is compromised. Do NOT run `install` on your computer before there's a fix. The CI checks on our repo are failing because of this.***

See the diff: https://my.diffend.io/npm/coa/2.0.2/2.0.4

And the issue: https://github.com/veged/coa/issues/99

**Comment by Josh-Cena** [comment]
The problematic versions are taken down. Quick action from NPM 👍

**Comment by slorber** [comment]
😓 is this going to happen evrey week now

**Comment by Josh-Cena** [comment]
> 😓 is this going to happen evrey week now

Until NPM requires 2FA for popular packages :D

FYI the two hacks are initiated by the exact same person

**Comment by josh-kaplan** [comment]
It does look like this one only impacted Windows users (https://github.com/veged/coa/issues/99)
