### ISSUE TITLE
build fair when using 'npm run build' or 'yarn run build'

### ISSUE THREAD

**Issue by TTFZippo** [facebook/docusaurus#5898]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [ ] I have tried the `npm run clear` or `yarn clear` command.
- [ ] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io.
- [ ] I have read the console error message carefully (if applicable).

### Description

Run the ` npm run build` command  and the termianl come out the bug `UnhandledPromiseRejectionWarning: DataCloneError: function destructLexErrorInfo`. It seems to be a error which is not been caught.

### Steps to reproduce

1. run `npm run build ` command
2. and the bug appeare

### Expected behavior

build successfully and get the dist folder.

### Actual behavior

![image](https://user-images.githubusercontent.com/63889094/140637578-114b3404-1723-44e9-a2ba-ede387d990a4.png)

### Your environment

- Docusaurus version: 2.0.0-beta.7
- Node.js:  v12.16.2
- Windows10

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by Josh-Cena** [comment]
You didn't provide a repo nor are you using the latest version. It's impossible for us to tell if it's a real bug or something bad you did yourself.
