### ISSUE TITLE
Use docs tags as SEO keywords (or vice-versa)

### ISSUE THREAD

**Issue by lucas-tortora** [facebook/docusaurus#5908]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Motivation

Since most of the time SEO keywords and tags will be about the same, it may be a good idea to use keywords as tags (or vice-versa), so users can get the benefit of both SEO keywords and blog style tags while only having to maintain half the frontmatter. 

### Self-service

- [X] I'd be willing to do some initial work on this proposal myself.

**Comment by Josh-Cena** [comment]
@lucas-tortora Sounds good to me. Can't wait to see this feature if you are willing to work on this yourself :D

FYI, there's a lot we can do to improve the SEO of docs. #5322 made blogs have rich results but we haven't ported much of that to docs. After #5691 we will also be in a good position to include authors and date information, but keywords seem safe to add at the moment.

**Comment by slorber** [comment]
@jdevalk any opinion on using `keyword` meta for Docusaurus blog/docs pages by default?

**Comment by jdevalk** [comment]
Yeah I have an opinion on that. meta keywords are quite useless 😀

**Comment by slorber** [comment]
Thanks :) let's close then unless someone can provide good reasons to support this
