### ISSUE TITLE
Predefined tag lists

### ISSUE THREAD

**Issue by Josh-Cena** [facebook/docusaurus#5912]
### Discussed in https://github.com/facebook/docusaurus/discussions/5911

<div type='discussions-op-text'>

<sup>Originally posted by **mambax** November  9, 2021</sup>
## Use Case
To our docs contribute now more than 40 people. They all love tags in docs and blogs. The issue arising is that we have the same tag multiple times, like

```
infra-as-code
infra as code
infrastructure as code
infrastructure-as-code
```

You can figure.

## Proposed idea
Allow a `tags.yml` to be assigned to each plugin/preset.

```
tags:
  - infrastructure-as-code
  - kubernetes
```

- If then users add tags to docs/blog that are not present in the list, the build fails (optionally, warns).
- If the file is not specified, the current approach would apply
- This would be similar to the [global authors](https://docusaurus.io/docs/blog#global-authors) approach where you have only 1 author file

Is something like that already present and I am just too blind to find it?
If not could you rate its complexity and if it would fit your feature set? I would like to contribute something but only if I can try by myself without asking for guidance every 2h 😊

</div>

**Comment by Josh-Cena** [comment]
@mambax I think this is a feature worth adding, and it would be easier to track if we add it to the issue queue. Are you willing to self-service?

**Comment by mambax** [comment]
Certainly, will do! 🤝

**Comment by mambax** [comment]
Did you mean like https://github.com/facebook/docusaurus/issues/5913?
