### ISSUE TITLE
Logo and favicon are gone when updating from v2-beta.8 to beta.9 with given baseUrl

### ISSUE THREAD

**Issue by gossi** [facebook/docusaurus#5929]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [ ] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io.
- [ ] I have read the console error message carefully (if applicable).

### Description

I've recently update from docusaurus v2 beta.8 to beta.9 and now neither my logo nor my favicon are showing up - and I think it has to do with a `baseUrl` other than `/`. Here is my relevant config:

```js
module.exports = {
  baseUrl: '/theemo/',
  favicon: 'img/favicon.svg',


  themeConfig: {
    navbar: {
      logo: {
        alt: 'Super Theemo',
        src: 'img/favicon.svg'
      }
    }
  }
}
```

My images are physically located in this folder: `/static/img/favicon.svg`

- In the build, they are available at: `localhost:port/img/favicon.svg`
- The generated url for them is `/theemo/img/favicon.svg`

Whatever I tried to change the paths in config for both logo and favicon, nothing worked.

I switched back to `beta.8` and come here for the bugreport.

### Steps to reproduce

Set a `baseUrl` other than `/` (see my config above for an example)

### Expected behavior

The images are found on the build website.

### Actual behavior

The images are not shown, wrong Urls.

### Your environment

- Docusaurus version used: `2.0.0@beta.9`

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by jaredcbaum** [comment]
All my images are broken locally for me

**Comment by Josh-Cena** [comment]
See #5863
