### ISSUE TITLE
Static images in doc only mode not served from `baseUrl` 

### ISSUE THREAD

**Issue by RyRy79261** [facebook/docusaurus#5961]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

Issue present in `2.0.0-beta.9` 
When in Doc only mode and using a base url, the static images are still being served from root and not from the base url 

### Steps to reproduce

Follow the docusaurus quick start

Set a baseUrl & targetUrl

Attempt to set the logo in docusaurus config, in themeConfig's logo section

### Expected behavior

Logo to load properly like in version `2.0.0-beta.6` 

### Actual behavior

No image is loaded as the URL is wrong

### Your environment

- Public source code:
- Public site URL:
- Docusaurus version used: 2.0.0-beta.9
- Environment name and version (e.g. Chrome 89, Node.js 16.4): Node 14.17, FireFox 94.0.1 (64-bit)
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): Manjaro Linux | Kernel Version: 5.10.70-1-MANJARO (64-bit)

### Reproducible demo

https://codesandbox.io/s/agitated-panka-ufb4k

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by Josh-Cena** [comment]
See #5863
