### ISSUE TITLE
Development server ignores baseUrl for static files

### ISSUE THREAD

**Issue by ernado** [facebook/docusaurus#5974]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

Development server serves static file from root instead of using baseUrl prefix.

### Steps to reproduce

1. Set `baseUrl` in `docusaurus.config.js` to `/docs/` from `/`
2. `docusaurus start`
3. `curl -I http://localhost:3000/docs/img/logo.svg`
4. Get 404
5. `curl -I http://localhost:3000/img/logo.svg`
6. Get 200

### Expected behavior

GET /docs/img/logo.svg 200 OK
GET /img/logo.svg 404 Not Found

### Actual behavior

GET /docs/img/logo.svg 404 Not Found
GET /img/logo.svg 200 OK

### Your environment

https://codesandbox.io/s/sleepy-snow-odixd?file=/docs/intro.md

`"@docusaurus/core": "2.0.0-beta.9",`

### Reproducible demo

https://codesandbox.io/s/sleepy-snow-odixd

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by Josh-Cena** [comment]
See #5863
