### ISSUE TITLE
About zero-width space(ZWSP)

### ISSUE THREAD

**Issue by JararvisQ** [facebook/docusaurus#5990]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [ ] I have tried the `npm run clear` or `yarn clear` command.
- [ ] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io.
- [ ] I have read the console error message carefully (if applicable).

### Description

I found this problem in PNPM docs, when I copy the content of the heading tag of the docs, there is a zero-width space at the end of the product of the heading tag.
![image](https://user-images.githubusercontent.com/33826386/142981521-7777de91-c4d6-42d7-bb6e-a1a742ea1189.png)

### Steps to reproduce

You can copy this text, and this is from pnpm docs. https://pnpm.io/npmrc#dependency-hoisting-settings

Dependency Hoisting Settings​

### Expected behavior

I don't know why this mechanism, so I hope there will never be ZWSP. 

### Actual behavior

There is a zero-width space at the end of the product of the heading tag.

### Your environment

- Environment name and version (e.g. Chrome 89, Node.js 16.4): Chrome 96.0.4664.45

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by Josh-Cena** [comment]
Indeed, #5708 added a zwsp to hide the hash link from crawlers. We have to put _some_ text there in order for the anchor link to work at all. Should anything actually be done? Is it causing much trouble?

**Comment by JararvisQ** [comment]
> Indeed, #5708 added a zwsp to hide the hash link from crawlers. We have to put _some_ text there in order for the anchor link to work at all. Should anything actually be done? Is it causing much trouble?

Oh, I saw #5708 and learn something. And the problem is that, If I don't copy the text from the docs to my editor, it may be difficult to find the ZWSP. And you can see the VSCode syntax highlighting.
![image](https://user-images.githubusercontent.com/33826386/142989550-ed76d1b0-4f83-43fc-b63a-5aad752fe8b1.png)
And these are two strings on the Chrome Developer tools.
![image](https://user-images.githubusercontent.com/33826386/142990036-21e41aa3-38c7-4ab2-99e5-b7285241294d.png)


I think I can push a PR to solve this problem.

**Comment by Josh-Cena** [comment]
If you think there's a better solution, that's nice :D The general rule is that we don't want a11y regressions or any behavior changes, but polishings are welcome!
