### ISSUE TITLE
markdown image reference can not find file in docs/assets -> 404

### ISSUE THREAD

**Issue by alex254** [facebook/Docusaurus#600]
### Is this a bug report?

yes

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

yes

### Environment

(OS, Node, npm, yarn)
Windows 10
Node v8.11.1
npm 5.6.0
yarn 1.6.0

### Steps to Reproduce

(Write your steps here:)
I ran into the problem a bit further down my own project; but initiated a new docusaurus project from the start to see if the problem still exists. And I get the same error...no changes were made to siteConfig.js

1. npm install --global docusaurus-init
2. docusaurus-init
3. rename examples -> /docs and /blog as in installation manual
4. add folder /assets to /docs
5. add a dummy dosomething.png (also .jpg) file to assets folder
6. add `![test](assets/dosomething.png)` to doc1.md
7. npm start
8. console error: GET http://localhost:3000/docs/assets/dosomething.png 404 (Not Found)

tried it in Chrome and Brave browser; same result.

### Expected Behavior

Expected: image is shown in browser

### Actual Behavior

console error: GET http://localhost:3000/docs/assets/dosomething.png 404 (Not Found)

### Reproducible Demo

https://github.com/iam-io/documentation/blob/master/docs/DOC_2_shoppable.md

Here you can see that github understand the link and shows the picture...however my npm build doesn't work.

**Comment by JoelMarcey** [comment]
Hi @alex254. Interesting, I assume you are using the latest version of Docusaurus (1.0.14 - which you can check by doing `npm outdated docusaurus` from the `website` directory).

I just tried this on OS X, and it worked fine.

So I am now led to believe that this may be a Windows support problem on our part.

What happens if you put the image in `website/static/img` and reference the image in markdown like ![test](/img/dosomething.png)

**Comment by JoelMarcey** [comment]
Or if you have a way to try your test on a Mac or Linux machine, that could be another way to verify as well.

**Comment by JoelMarcey** [comment]
@alex254 It is probably a bug with how we handle paths specifically for Windows, although I thought we fixed a bunch of that. I need to get my hands on a Windows machine to test. But that is my current working theory.

**Comment by alex254** [comment]
@JoelMarcey Ok, I'm going to continue with my project; thanks for the help! If you want to get the reproducable demo please use this commit: `https://github.com/iam-io/documentation/commit/10d5f232d0889f20e658e01202b8b54fa6af49ec`

**Comment by Themandunord** [comment]
Same issue on our project. @JoelMarcey will you still look at this ?

**Comment by endiliey** [comment]
This is related to Windows.

Tried on Linux
<img width="830" alt="linux" src="https://user-images.githubusercontent.com/17883920/40854439-10fe4782-6604-11e8-9f78-64b16fe3df65.PNG">

Tried on Windows
<img width="774" alt="windows" src="https://user-images.githubusercontent.com/17883920/40854448-17aed3b2-6604-11e8-88c9-f334bcd2854d.PNG">

**Comment by endiliey** [comment]
@Themandunord @alex254 appreciate it if you could test out #720 and see if it's working for you

**Comment by Themandunord** [comment]
@endiliey I can confirm that the issue is fixed when I reproduce your commit in my local environnent 😃
