### ISSUE TITLE
Support GitHub-style themed images

### ISSUE THREAD

**Issue by Josh-Cena** [facebook/docusaurus#6007]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Description

A remark plugin to turn GitHub themed images:

```md
![GitHub-Mark-Light](https://user-images.githubusercontent.com/3369400/139447912-e0f43f33-6d9f-45f8-be46-2df5bbc91289.png#gh-dark-mode-only)![GitHub-Mark-Dark](https://user-images.githubusercontent.com/3369400/139448065-39a229ba-4b06-434b-bc67-616e2ed80c8f.png#gh-light-mode-only)
```

![GitHub-Mark-Light](https://user-images.githubusercontent.com/3369400/139447912-e0f43f33-6d9f-45f8-be46-2df5bbc91289.png#gh-dark-mode-only)![GitHub-Mark-Dark](https://user-images.githubusercontent.com/3369400/139448065-39a229ba-4b06-434b-bc67-616e2ed80c8f.png#gh-light-mode-only)

<details>

<summary>How does it work?</summary>

GitHub just uses CSS to hide the images with a given anchor. So you can even have them separated:

Dark mode only:

![GitHub-Mark-Light](https://user-images.githubusercontent.com/3369400/139447912-e0f43f33-6d9f-45f8-be46-2df5bbc91289.png#gh-dark-mode-only)

Light mode only:

![GitHub-Mark-Dark](https://user-images.githubusercontent.com/3369400/139448065-39a229ba-4b06-434b-bc67-616e2ed80c8f.png#gh-light-mode-only)

I guess we don't have to implement this part, just use the existing theme image component

</details>

Into the `ThemedImage` JSX:

```jsx
<ThemedImage
  alt="GitHub Mark"
  sources={{
    light: useBaseUrl('/img/github-light.png'),
    dark: useBaseUrl('/img/github-dark.png'),
  }}
/>
```

### Has this been requested on Canny?

No

### Motivation

GitHub has added support for themed images: https://github.blog/changelog/2021-11-24-specify-theme-context-for-images-in-markdown/

We have tried hard in the past to support GitHub features, it's now time for us to support this one.

### API design

This will be done under the hood as part of `mdx-loader` and only exposed in the future as a preset option after #5999.

`ThemedImage` may be more natural and well-integrated with our theme approach, but we may also use plain CSS like GitHub does...?

### Self-service

- [X] I'd be willing to contribute this feature to Docusaurus myself.

**Comment by slorber** [comment]
Related to discussion: https://twitter.com/wooorm/status/1463877371140923398

I don't really like the `gh-` prefix 😅 

Maybe it should be part of the remark gfm plugin?

**Comment by Josh-Cena** [comment]
> I don't really like the `gh-` prefix 😅

Me neither, feels like it's not really extensible. But after all this doesn't have to be documented—it can just be a nice little feature for existing GitHub users.

> Maybe it should be part of the remark gfm plugin?

It's either we or no-one. GitHub themselves just used CSS (Titus mentioned that as well). Both images end up in the markup, with one hidden:

![image](https://user-images.githubusercontent.com/55398995/143460096-934bb2dc-db9f-46d9-b923-441e72a4451c.png)

So remark-gfm doesn't need to do anything special—they just need to ask users to implement the same CSS. (Un fact, what can they do? Themed images can't be purely HTML anyways) I'm fine with us using CSS to hide it as well, but adding a little remark plugin would make the `ThemedImage` component more useful than it currently is

**Comment by Josh-Cena** [comment]
I decided that nothing should be done. This could easily be achieved with CSS in userland.

**Comment by felipecrs** [comment]
Just in case someone stumbles upon this like I did, Docusaurus now supports it:

https://docusaurus.io/docs/next/markdown-features/assets#github-style-themed-images
