### ISSUE TITLE
String from linked Python file has leading whitespace removed

### ISSUE THREAD

**Issue by NathanFarmer** [facebook/docusaurus#6027]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [x] I have tried creating a repro with https://new.docusaurus.io.
- [ ] I have read the console error message carefully (if applicable).

### Description

When rendering a code block linked from a Python file, Docusaurus removes all leading whitespace from the specified lines.

This is similar to Issue #[2352](https://github.com/facebook/docusaurus/issues/2352) which was resolved by PR #[2371](https://github.com/facebook/docusaurus/pull/2371).

### Steps to reproduce

Add a markdown page with the following snippet:

````
```python file=./python_files/python_file.py#L2-L3
```
````

`python_file.py` will contain the indented code you intend to render (starting at line 1):

```
display_string = """
    this is a test
    test is only a test
"""
```

### Expected behavior

I expected Docusaurus to render the markdown like this:

```
    this is a test
    this is only a test
```

### Actual behavior

Instead this is what happened:

```
this is a test
    this is only a test
```

### Your environment

- Docusaurus version used: 2.0.0-beta9
- Environment name and version (e.g. Chrome 89, Node.js 16.4): Chrome Version 96.0.4664.55 (Official Build) (x86_64)
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): macOS Monterey 12.0.1

### Reproducible demo

[CodeSandbox](https://codesandbox.io/s/reverent-brook-jj97c?file=/src/pages/markdown-page.md)

The CodeSandbox keeps adding a blank line to this code block:

````
```python file=./python_files/python_file.py#L2-L3
```
````

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by Josh-Cena** [comment]
@NathanFarmer `file=` syntax isn't even something we support out-of-the-box. Could you actually provide a step-to-step reproduction instruction so I can investigate and help you solve it?

**Comment by Josh-Cena** [comment]
> I wasn't aware `file=` wasn't supported. That's how we integration test our docs.

Does that mean you have special setup (e.g. remark plugin, swizzled code block...) to support this use? Because when I open that playground, the code block is empty, which is expected.

> I created [this sandbox](https://codesandbox.io/s/reverent-brook-jj97c?file=/src/pages/markdown-page.md) which seems to be adding a blank line to the code block with the `file=` syntax whenever I save.

That's a code sandbox issue. Pretty sure they auto-format on save.

> Other than that I'm not sure what else to provide.

The best is a minimal reproduction step, but seems it's quite hard to describe with a playground (I appreciate your effort). If you have public source code it would be good. Otherwise, just a screenshot telling me how it's working right now can help me ensure that this syntax actually does work (which is purely magic to me)

**Comment by Josh-Cena** [comment]
@NathanFarmer I'll be closing this for housekeeping purposes as I'm sure it's not a Docusaurus problem. We have a guide section on how you import code snippets as plain text: https://docusaurus.io/docs/next/markdown-features/react#importing-code-snippets So make sure your external source is actually imported with correct indentation in the first place.
