### ISSUE TITLE
Quota has been exceeded in <AnnouncementBarProvider>

### ISSUE THREAD

**Issue by markcarroll** [facebook/docusaurus#6036]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

`AnnoucentmentBar` render crashes. `setItem` in StorageUtils appears to be failing, causing a crash and subsequent empty page. This happens every time on one machine.  The machine does have plenty of disk space and was working fine yesterday.  See below for details. 

### Steps to reproduce

Added announcement bar to site. Many days later a refresh triggered this error. Now I cannot get the site to render on this machine with the announcement bar turned on. 

### Expected behavior

Bar renders correctly. 

### Actual behavior

I have been testing a new web site with an announcement for several days now with no problems.  Did not touch any of the code related to the announcement today but just started getting this:

```
[Error] QuotaExceededError: The quota has been exceeded.
	setItem
	(anonymous function) (announcementBarUtils.js:21:115)
	invokePassiveEffectCreate (react-dom.development.js:23483)
	callCallback (react-dom.development.js:3946)
	dispatchEvent
	invokeGuardedCallbackDev (react-dom.development.js:3995)
	invokeGuardedCallback (react-dom.development.js:4057)
	flushPassiveEffectsImpl (react-dom.development.js:23570)
	unstable_runWithPriority (scheduler.development.js:469)
	performSyncWorkOnRoot (react-dom.development.js:22265)
	performSyncWorkOnRoot
	(anonymous function) (react-dom.development.js:11328)
	unstable_runWithPriority (scheduler.development.js:469)
	flushSyncCallbackQueueImpl (react-dom.development.js:11323)
	flushSyncCallbackQueue (react-dom.development.js:11310)
	unbatchedUpdates (react-dom.development.js:22434)
	legacyRenderSubtreeIntoContainer (react-dom.development.js:26016)
	(anonymous function) (clientEntry.js:19:235)
	promiseReactionJob

[Error] The above error occurred in the <AnnouncementBarProvider> component:

AnnouncementBarProvider
ThemeProvider
LayoutProviders
Layout
Dashboard
Component@
Component@
Component@
Component@
Component@
withRouter(PendingNavigation)
Root
BrowserContextProvider
DocusaurusContextProvider
App
Component@
Component@

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://reactjs.org/link/error-boundaries to learn more about error boundaries.
	logCapturedError (react-dom.development.js:20086)
	(anonymous function) (react-dom.development.js:20114)
	callCallback (react-dom.development.js:12319)
	commitUpdateQueue (react-dom.development.js:12340)
	commitLifeCycles (react-dom.development.js:20732)
	commitLayoutEffects (react-dom.development.js:23422)
	callCallback (react-dom.development.js:3946)
	dispatchEvent
	invokeGuardedCallbackDev (react-dom.development.js:3995)
	invokeGuardedCallback (react-dom.development.js:4057)
	commitRootImpl (react-dom.development.js:23147)
	commitRootImpl
	unstable_runWithPriority (scheduler.development.js:469)
	commitRoot (react-dom.development.js:22986)
	performSyncWorkOnRoot (react-dom.development.js:22325)
	performSyncWorkOnRoot
	(anonymous function) (react-dom.development.js:11328)
	unstable_runWithPriority (scheduler.development.js:469)
	flushSyncCallbackQueueImpl (react-dom.development.js:11323)
	flushSyncCallbackQueue (react-dom.development.js:11310)
	unbatchedUpdates (react-dom.development.js:22434)
	legacyRenderSubtreeIntoContainer (react-dom.development.js:26016)
	(anonymous function) (clientEntry.js:19:235)
	promiseReactionJob
```

I am not able to repro it on any other machine right now. It looks like it is erroring when the `AnnouncementBarUtils` try to call `setItem` on the local storage helper. Since I can't repro elsewhere this is not easy to get more info on, but given this looks like a promise rejection that is not being handled, it seems like this should be fixed anyway to make the storage helper a little more robust. 

### Your environment

- Public source code:
- Public site URL:
- Docusaurus version used: 2.0.0-beta.9
- Environment name and version (e.g. Chrome 89, Node.js 16.4): Node 16.13
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): MacOS 12.0.1

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by Josh-Cena** [comment]
So did I understand correctly that you are essentially wanting for an error boundary around the announcement bar?

Considering the error itself, have you tried: (a) running the website in private/Incognito / using another browser; (b) Inspecting the local storage usage (in Chrome this is the "Application" tab in the Dev tools; in Safari it's "Storage")? You didn't provide the site's public URL or your browser version so it's hard for me to inspect

**Comment by markcarroll** [comment]
Correct.  I am not able to repro anywhere else so it seems like the right request of the team is an error boundary around the storage APIs to protect for failure.  Having the entire site fail to load because of an error in the announcement bar seems a bit extreme.

**Comment by slorber** [comment]
Agree, fixed in https://github.com/facebook/docusaurus/pull/6040

We should assume localStorage is unreliable and site should keep working

A React error boundary wouldn't help much as the error is in a top-level provider component, not directly inside the announcementBar view

**Comment by Josh-Cena** [comment]
I assume this is fixed🤔

**Comment by markcarroll** [comment]
Yes, perfect. Thank you.
