### ISSUE TITLE
Can't include partials (files with leading undescores) in sidebar.js 

### ISSUE THREAD

**Issue by laduke** [facebook/docusaurus#6044]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

Hello,
If you have a markdown file with a leading underscore, and put it in sidebar.js, docusaurus can't find it anymore. 
I was using beta.0 and tried to update today. It worked before now it doesn't. I get that this is for the partials feature.

```js
    {
          type: "category",
          label: "My Category",
          items: [
            "autogen/beep/boop/_my_file",
          ]
        }
```
```
Loading of version failed for version "current"
Unable to build website for locale "en".
Error: Invalid sidebar file at "sidebars.js".
These sidebar document ids do not exist:
- "autogen/beep/boop/_my_file"
```

I found this PR #5543 about documenting it, but I'm not sure when exactly this changed, somewhere around beta 3 or 4. 

I have this other doxygen build system that builds some markdown files. It puts leading underscores on some of the filenames. It's not configurable to not do this. Then docusaurus builds the site. 

Totally understand if you don't want to "fix" this. Just curious if it's an option. 

### Steps to reproduce

https://codesandbox.io/s/agitated-visvesvaraya-fxfv8?file=/package.json

The codesandbox starts up with 2.0.0-beta.3, and it works. it finds _hello. 
I changed the package json to 2.0.0-beta.9 and it doesn't work. 

### Expected behavior

Successful build

### Actual behavior

<img width="423" alt="Screen Shot 2021-12-03 at 2 03 15 PM" src="https://user-images.githubusercontent.com/11598/144678707-b51925a4-c009-4734-bf5c-72c579536050.png">

### Your environment

- Public source code: https://codesandbox.io/s/agitated-visvesvaraya-fxfv8?file=/docs/_hello.md
- Public site URL:
- Docusaurus version used: 2.0.0-beta.9
- Environment name and version: Node.js 16.13.1
- Operating system and version: Big Sur  n/a

### Reproducible demo

https://codesandbox.io/s/agitated-visvesvaraya-fxfv8?file=/docs/_hello.md

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by Josh-Cena** [comment]
Have you tried configuring [the `exclude` option](https://docusaurus.io/docs/next/api/plugins/@docusaurus/plugin-content-docs#exclude)? You can remove `_*` from this list so they get processed & loaded.

**Comment by laduke** [comment]
Thanks. That works. Didn't find that config. 

```
          exclude: [
            // '**/_*.{js,jsx,ts,tsx,md,mdx}',
            '**/_*/**',
            '**/*.test.{js,jsx,ts,tsx}',
            '**/__tests__/**',
          ],

```
