### ISSUE TITLE
React is rendering cached view instead of updating with new state (GitHub Pages)

### ISSUE THREAD

**Issue by alzafacon** [facebook/docusaurus#6054]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [ ] I have tried the `npm run clear` or `yarn clear` command.
- [ ] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io.
- [x] I have read the console error message carefully (if applicable).

### Description

React view is not updated with React states that are different than at the time of build. 🤯 , I know. I have a clock that doesn't load with the correct time.

Locally the site works perfectly. The bug is related to the deployment.

I suspect the problem is as follows:
1. the static bundle generated by `yarn deploy` "freezes/caches" the html view (the view encodes the React state at the time of deploy, i.e. the time on the clock is the time of the build for deployment)
2. when accessed on a browser the "frozen/cached" view is loaded
3. React states are initialized (i.e. time) but the view shows the "frozen/cached" view not the view generated with the latest React states (i.e. latest time)

React seems to to think the initial React state (time) at time of page load correspond to the "frozen/cached" views so React does not re-render the view.

### Steps to reproduce

1. open https://alzafacon.com/
2. notice the time on the local clock is not correct (in fact, the time happens to be the time of the `yarn deploy` I did)
3. wait for the system time to advance by one minute (you can also trigger a state change by moving the slider)
4. notice the time is reflected correctly now

if you run the project locally this does not happen.

### Expected behavior

On first load (or on page refresh) the clock should reflect the React state of the component not of the cached static bundle.

### Actual behavior

The clock shows the wrong time until the state values change again

### Your environment

- Public source code: https://github.com/alzafacon/alzafacon.github.io
- Public site URL: alzafacon.github.io (github pages, will redirect to alzafacon.com)
- Docusaurus version used: 2.0.0-beta.9
- Environment name and version (e.g. Chrome 89, Node.js 16.4): Chrome 96
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): macOS

### Reproducible demo

alzafacon.github.io

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by Josh-Cena** [comment]
You need to remount the component during React hydration. Something like:

```ts
import React, { useState } from "react"
import useIsBrowser from '@docusaurus/useIsBrowser';
import { ZoomClock } from "./ZoomClock"
import { useInterval } from 'react-use'
import { DateTime } from "luxon"

export const WallClock = ({ size = 200, timeZone = 'local', label = "" }) => {
    const isBrowser = useIsBrowser()
    const [time, setTime] = useState(DateTime.now().setZone(timeZone))

    useInterval(() => {
        setTime(DateTime.now().setZone(timeZone))
    }, 1000)

    return (
        <ZoomClock
            size={size}
            hour={time.hour}
            minute={time.minute}
            label={label}
            key={String(isBrowser)}
        />
    )
}
```

Otherwise, the state is only updated when the `useInterval` callback is first fired.

**Comment by alzafacon** [comment]
aha, thank you so much! I used the hook to fix it.
so it's de hydration not "freeze/cache" 🤦 of course
