### ISSUE TITLE
Auto-scroll TOC to always display active link

### ISSUE THREAD

**Issue by TomPeirs** [facebook/docusaurus#6058]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

Hi, I created a video to explain my concern.

When having a long TOC, then a scrollbar appears.
When you scroll down inside the document, then you will see the active header in the TOC light up.
However, when you scroll long enough, then the scrollbar of the TOC itself does not move along.

https://user-images.githubusercontent.com/68061801/144857541-4d656e43-e151-4ae1-8855-ac1f65f70d85.mp4

### Steps to reproduce

1. Open https://docusaurus.io/docs/lifecycle-apis
2. Scroll scroll scroll.

### Expected behavior

I would expect that the scrollbar of the TOC follows the active/highlighted link.

### Actual behavior

The scrollbar stays in position, and we can't follow the highlighted TOC item.

### Your environment

I used the current docusaurus deployment to showcase the problem
https://docusaurus.io/docs/lifecycle-apis

### Reproducible demo

Thank you

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by Josh-Cena** [comment]
It's quite surprising that you expect it to move along. It's an interesting UI feature to add but it's certainly not a bug.

**Comment by slorber** [comment]
Agree this is a feature request, would also want this to be implemented

Also makes sense for the docs sidebar, as navigating with the pagination arrows (next/previous) or regular links may not reveal the item

**Comment by TomPeirs** [comment]
Hi, I just took a look at the preview. This seems to be working as expected :-)
