### ISSUE TITLE
Blog entries with duplicate title doesn't get published on the blog index page

### ISSUE THREAD

**Issue by stnor** [facebook/docusaurus#6059]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

When creating a new blog post with the same title as an old post, it picks the old post for the the blog index.html

### Steps to reproduce

1. npx create-docusaurus@latest website classic
2. cd website/blog
3. cp 2019-05-28-first-blog-post.md  2021-12-07-first-blog-post.md 
4. Change contents of new file to "This is the new blog post. Does it show on the index page?"
5. yarn start
6. Go to the blog index page. It will show the post from 2019-05-28 and not the new post.

### Expected behavior

The new post should be on the blog index page, not the old. The rss.xml is correct and shows the new post first.

### Actual behavior

<img width="1040" alt="Screenshot 2021-12-07 at 10 52 23" src="https://user-images.githubusercontent.com/561167/145006859-8c51a3b5-61c5-4a12-885e-bc597cc4f933.png">

### Your environment

- Public source code:
- Public site URL:
- Docusaurus version used:
- Environment name and version (e.g. Chrome 89, Node.js 16.4):
- Operating system and version (e.g. Ubuntu 20.04.2 LTS):

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by Josh-Cena** [comment]
What I see is that the two posts share the same date despite them being different:

![image](https://user-images.githubusercontent.com/55398995/145018323-fd3a1f89-ff69-419c-8bf4-2aed325a0f5c.png)

Can you confirm if that's the case for you? Also, if you change the `2021-12-07` post's file name to `2021-12-08` ***while dev server is running***, do you now see both of them updated to December 8th?

**Comment by Josh-Cena** [comment]
Bug located. On it soon 👍
