### ISSUE TITLE
Build failed: Unknown keyword formatMinimum

### ISSUE THREAD

**Issue by Xuanwo** [facebook/docusaurus#6073]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

It's more like a runtime-related issue, so I didn't create a repro.

We set up a website in https://github.com/datafuselabs/databend/tree/main/website/databend, and developers with Mac M1 failed to build this site.

Reported in https://github.com/datafuselabs/databend/issues/3283

### Steps to reproduce

- Using a macbook pro M1
- `git clone git@github.com:datafuselabs/databend.git`
- `cd databend/website/databend`
- `npm run build`

### Expected behavior

The site built successful.

### Actual behavior

```
[en] Creating an optimized production build...

✖ Client
  Compiled with some errors in 9.84s

● Server █████████████████████████ building (64%) 1/1 entries 2234/2234 dependencies 770/770 modules 0 active 
 



Error: Unknown keyword formatMinimum
Module build failed: Error: Unknown keyword formatMinimum
Client bundle compiled with errors therefore further build is impossible.
```

### Your environment

- Public source code: https://github.com/datafuselabs/databend/tree/main/website/databend
- Public site URL: https://databend.vercel.app
- Docusaurus version used: 2.0.0-beta.9
- Environment name and version (e.g. Chrome 89, Node.js 16.4):, node v17.2.0, npm 7.24.2
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): MacOS monterey 12.0.1

### Reproducible demo

https://github.com/datafuselabs/databend/tree/main/website/databend

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by Josh-Cena** [comment]
Hi, two of the maintainers are using Mac M1 (including me). Unfortunately I'm unable to reproduce the issue:

```
joshcena@Sidas-MacAir:databend$ node --version
v17.1.0
joshcena@Sidas-MacAir:databend$ npm --version
8.1.2
joshcena@Sidas-MacAir:databend$ yarn build
yarn run v1.22.10
$ docusaurus build

[en] Creating an optimized production build...

✔ Client
  

✔ Server
  Compiled successfully in 14.84s


Success! Generated static files in "build".

Use `npm run serve` command to test your build locally.

✨  Done in 19.78s.
```

**Comment by Xuanwo** [comment]
Oh, wired. Let's give it a try.

@zhang2014, can you use node v17.1 and yarn to run `yarn run build` for a test?

**Comment by Josh-Cena** [comment]
@zhang2014 After inspecting the error stack you posted in the original issue, I think the issue could be a version mismatch between `ajv-keywords`.

```js
joshcena@Sidas-MacAir:databend$ node -e "require('/Users/joshcena/Desktop/work/Tech/projects/databend/website/databend/node_modules/css-minimizer-webpack-plugin/node_modules/ajv-keywords/dist/index.js').get('formatMinimum')"
/Users/joshcena/Desktop/work/Tech/projects/databend/website/databend/node_modules/css-minimizer-webpack-plugin/node_modules/ajv-keywords/dist/index.js:25
        throw new Error("Unknown keyword " + keyword);
        ^

Error: Unknown keyword formatMinimum
    at Function.get (/Users/joshcena/Desktop/work/Tech/projects/databend/website/databend/node_modules/css-minimizer-webpack-plugin/node_modules/ajv-keywords/dist/index.js:25:15)
```

The error is coming from the Webpack loader `url-loader`, which depends on `schema-utils@3.1.1`, and the latter uses `ajv-keywords@3.5.2`. The `formatMinimum` keyword was removed from this package in v4: https://github.com/ajv-validator/ajv-keywords/releases/tag/v4.0.0. Typically, that shouldn't be an issue, because the right version should be supplied by the package manage; however, in your case, NPM seems to be aggressively flattening the dependency tree and causes a wrong version (`ajv-keywords@5.1.0`) to be used instead.

I was wrong when I said Yarn wasn't the issue; Yarn was _exactly_ the reason why I couldn't reproduce. This incident has demonstrated why Yarn is a better package manager :D Please test again with Yarn and check if that works.

**Comment by Xuanwo** [comment]
@Josh-Cena Thank you so much for your quick and accurate feedback, it's awesome!

**Comment by gorgos** [comment]
For anyone from Google, I just updated Npm to the latest version and it fixed the issue.

**Comment by KishanKumarNR** [comment]
Just moved those "ajv" from dependencies to 

->  "devDependencies": {
    "ajv": "^8.12.0",
    "ajv-keywords": "^5.1.0",
}

It works like a charm with npm itself.

{
  npm: '7.23.0',
  node: '14.15.0',
}
