### ISSUE TITLE
Use CSS to outline focused code blocks

### ISSUE THREAD

**Issue by mkrtchian** [facebook/docusaurus#6077]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [ ] I have tried the `npm run clear` or `yarn clear` command.
- [ ] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io.
- [ ] I have read the console error message carefully (if applicable).

### Description

When navigating with the keyboard in the documentation, the focus is going on code blocks `<pre>` tags because of the [tabindex on it](https://github.com/facebook/docusaurus/blob/43ac7d5da95a309073d8b7cb50b4b455c831647c/packages/docusaurus-theme-classic/src/theme/CodeBlock/index.tsx#L84).

With this behavior we have to tab twice for each code block: once for the code block itself (which is not an interactive element as notified by eslint), and once to be on the copy button which is normal.

On firefox it's even worse because the focused `<pre>` tag is not outlined, so I don't see the focus when it's there.

### Steps to reproduce

The behavior can be reproduced in the [documentation part of the docusaurus.io website, for example in installation](https://docusaurus.io/docs/installation#scaffold-project-website).

Just go there and navigate with the Tab button several times to notice that the tab is going to the code block and the copy button each time.

### Expected behavior

I expect the focus not to go to the `<pre>` tag.

### Actual behavior

The focus goes to the `<pre>` tag.

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by Josh-Cena** [comment]
Hi, this is intended behavior, added here: https://github.com/facebook/docusaurus/pull/3649

The rationale is that some code blocks are horizontally scrollable, so in order to scroll them they have to be focusable. However, I do acknowledge that the outline missing in FF is problematic. I guess we would manually add CSS to highlight the focus.

**Comment by mkrtchian** [comment]
Thank you for your answer. I didn't think about that, it's useful indeed.

Do you want me to rename this issue, or close it and open a new one for the outline issue ?

**Comment by christopherklint97** [comment]
Maybe I am misunderstanding the issue but I seem to get css on my code blocks when I use Tab. It is a white outline similar to the Copy button.
![docusaurus_test](https://user-images.githubusercontent.com/53100317/146417728-be8c8d09-a3a4-4800-82f7-3c23f74e4c48.gif)

**Comment by mkrtchian** [comment]
If you are using Google Chrome you will probably never have problems seeing the focused element when navigating with the keyboard, because Chrome is adding an additional visual outline independently from the CSS `outline` property.

Firefox (and probably other browsers) don't do that, so here as the CSS outline is not visible when the `pre` tag gets the focus, on Firefox there is no visual indication.

The outline is not visible on non-Chrome browsers because:
- [this `outline: 0;` property](https://github.com/facebook/docusaurus/blob/16ce7975514cced75d4b9eb836bfd6e970170b7c/packages/docusaurus-theme-classic/src/theme/hooks/styles.css#L9) applies to it (which is actually enough)
- the parent `div` of the `div` containing the `pre` tag has the same size as the `pre` tag, and [an `overflow: hidden;` property](https://github.com/facebook/docusaurus/blob/16ce7975514cced75d4b9eb836bfd6e970170b7c/packages/docusaurus-theme-classic/src/theme/CodeBlock/styles.module.css#L12) that makes anything that overflows (like an outline of a child) not visible even if it was not set to 0.

**Comment by christopherklint97** [comment]
Ah I see, thanks for the explanation! Are you currently working on this or can I start?

**Comment by mkrtchian** [comment]
You can start :wink:
