### ISSUE TITLE
Can't NPM Install with 2.0.0-beta.10

### ISSUE THREAD

**Issue by retiutut** [facebook/docusaurus#6079]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

Getting an error trying to update to Docusaurus 2.0.0-beta.10. 

### Steps to reproduce

Simply update dependency in package.json to 2.0.0-beta.10 for `core` and `preset-classic`.

**Replicated in CodeSandbox by changing package.json only.**

### Expected behavior

`npm install` without errors.

### Actual behavior

```
^CiMac:website Richard$ npm install
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: undefined@undefined
npm ERR! Found: @docusaurus/core@2.0.0-beta.10
npm ERR! node_modules/@docusaurus/core
npm ERR!   @docusaurus/core@"2.0.0-beta.10" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @docusaurus/core@"2.0.0-beta.9" from @docusaurus/preset-classic@2.0.0-beta.10
npm ERR! node_modules/@docusaurus/preset-classic
npm ERR!   @docusaurus/preset-classic@"2.0.0-beta.10" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /Users/Richard/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/Richard/.npm/_logs/2021-12-09T16_51_13_932Z-debug.log
```

### Your environment

- Public source code: n/a
- Public site URL: n/a
- Docusaurus version used: 2.0.0-beta.10
- Environment name and version (e.g. Chrome 89, Node.js 16.4): Node 16.11.1
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): Github Actions Ubuntu, Mac, and CodeSandbox

### Reproducible demo

https://codesandbox.io/s/currying-wood-6k246

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by ericvicenti** [comment]
I can confirm that the initial Docusaurus setup is broken right now with this issue.

On my computer I run `npx create-docusaurus@latest dcrs-test1 classic`

And the following is output:


```
Creating new Docusaurus project...

Installing dependencies with npm...
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: dcrs-test-1@0.0.0
npm ERR! Found: @docusaurus/core@2.0.0-beta.10
npm ERR! node_modules/@docusaurus/core
npm ERR!   @docusaurus/core@"2.0.0-beta.10" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @docusaurus/core@"2.0.0-beta.9" from @docusaurus/preset-classic@2.0.0-beta.10
npm ERR! node_modules/@docusaurus/preset-classic
npm ERR!   @docusaurus/preset-classic@"2.0.0-beta.10" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /Users/ericvicenti/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/ericvicenti/.npm/_logs/2021-12-09T18_32_53_120Z-debug.log


Successfully created "dcrs-test1".
<the success/intro message is here, even though there was an npm error on install>

**Comment by ericvicenti** [comment]
@slorber, not sure what is happening here. Maybe something didn't go smoothly with today's release?

**Comment by ericvicenti** [comment]
Oh I think this is the fix: https://github.com/facebook/docusaurus/pull/6078

**Comment by Josh-Cena** [comment]
Hi, we had been aware of this: https://github.com/facebook/docusaurus/pull/6047#issuecomment-989855782

We'll discuss what's the best fix for this, probably reverting the change and move the core back to hard dependency

**Comment by retiutut** [comment]
@slorber Thank you!
