### ISSUE TITLE
Rephrase the section on "docs-only" and "blog-only"

### ISSUE THREAD

**Issue by Josh-Cena** [facebook/docusaurus#6093]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Description

The "docs-only" and "blog-only" names are confusing, because they just change the routing path but don't prevent you from using other plugins. Moreover, the instructions are so brief that users tend to misunderstand what they are supposed to do at each step.

Here's what I wrote on Discord, we still need to rephrase it but this is hopefully more explicit:

---

You are looking for docs-only mode. I assume you have the following in your `docusaurus.config.js`:

```js
presets: [
  '@docusaurus/preset-classic',
  {
    docs: {/* ... */},
    blog: {/* ... */},
    // ...
  },
],
```

To enter docs-only mode, change it to like this:

```js
presets: [
  '@docusaurus/preset-classic',
  {
    docs: {
      routeBasePath: '/',
      // ...
    },
    blog: false,
    // ...
  },
],
```

Note that you don't necessarily have to give up on using blog; all that `routeBasePath: '/'` does is that instead of serving the docs through `https://example.com/docs/some-doc`, they are now at the site root: `https://example.com/some-doc`.
Don't forget to put some page at the root (`https://example.com/`) through adding the front matter:

```md
---
sidebar_position: 0
slug: /
---

# Home

This page will appear as the home page.
```

If you made a doc page the home page, remember to delete the default index page at `src/pages/index.js`. Otherwise, it's also fine to keep using that as the landing page.

### Self-service

- [X] I'd be willing to address this documentation request myself.

**Comment by himanshu007-creator** [comment]
Hi ! 
I would like to work on this issue, but would require some help here.

**Comment by Josh-Cena** [comment]
@himanshu007-creator sure, what help would you need? You can reach out to me on Discord, or you can just ask here.

**Comment by himanshu007-creator** [comment]
I understood the issue, what we are doing is at the root path "/" we are providing the docs and in case users want to change this they can by modifying the <code>,docusaurus.config.js</code> and rendering another page. Can you tell me in which file do I need to make changes?! @Josh-Cena

**Comment by Josh-Cena** [comment]
Yes, the two files to look at are:

https://github.com/facebook/docusaurus/blob/main/website/docs/blog.mdx

https://github.com/facebook/docusaurus/blob/main/website/docs/guides/docs/docs-introduction.md

**Comment by christopherklint97** [comment]
@himanshu007-creator how is it going with this issue? I would like to work on this 😄

**Comment by himanshu007-creator** [comment]
Hey @christopherklint97 , I am working on it, will let you know if things don't work out😀

**Comment by Josh-Cena** [comment]
@himanshu007-creator Hi, it has been 7 days since you claimed this issue. Please send a PR (it could be incomplete) or we would have to delegate it to @christopherklint97 so we can keep things rolling

**Comment by himanshu007-creator** [comment]
> @himanshu007-creator Hi, it has been 7 days since you claimed this issue. Please send a PR (it could be incomplete) or we would have to delegate it to @christopherklint97 so we can keep things rolling

I'll send a PR by today for sure
