### ISSUE TITLE
Simple version of footer

### ISSUE THREAD

**Issue by armano2** [facebook/docusaurus#6101]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Motivation

https://infima.dev/docs/components/footer

Currently only one of version of footer is supported, and for project that do not want/have many links, simplified version can be useful

![image](https://user-images.githubusercontent.com/625469/145738650-cf492a0a-e2f0-44c9-9468-59b37fb66fcb.png)
![image](https://user-images.githubusercontent.com/625469/145738659-dbe6e6d8-054f-49e6-91b3-0894b4cbfafd.png)

### Self-service

- [ ] I'd be willing to do some initial work on this proposal myself.

**Comment by Josh-Cena** [comment]
Let's accept two kinds of configuration:

```ts
type MultiColumnFooter = {
  links: Array<{
    title: string;
    items: FooterItem[];
  }>;
};

type SimpleFooter = {
  links: FooterItem[];
};
```

**Comment by slorber** [comment]
Yes, looks like a nice idea

What could be the design on mobile, or when items wrap on multiple lines?

**Comment by armano2** [comment]
infima defined mobile version already 
![image](https://user-images.githubusercontent.com/625469/146219262-b32ca841-0406-4623-bdd3-34c2b23658fb.png)

**Comment by christopherklint97** [comment]
Is it ok to start working on this?

**Comment by Josh-Cena** [comment]
@christopherklint97 Sure, go ahead as you please. But please do send a PR, since I noticed you've claimed quite a few
