### ISSUE TITLE
pagination_next / prev no longer working

### ISSUE THREAD

**Issue by sr-remsha** [facebook/docusaurus#6103]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

I have explicitly turned off pagination on every page. Still appeared after I moved to the latest version. 

### Steps to reproduce

pagination_next = null

pagination_prev = null

### Expected behavior

Pagination is off on every page

### Actual behavior

Pagination in on 

### Your environment

- Docusaurus version used: Version: 2.0.0-beta.13

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by Josh-Cena** [comment]
Can reproduce. I think this is caused by the recent navigation refactor in #5830. Will fix it as part of #5782
