### ISSUE TITLE
'Edit this page' link is broken in the init template

### ISSUE THREAD

**Issue by tinubaby** [facebook/docusaurus#6110]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [ ] I have read the console error message carefully (if applicable).

### Description

In https://tutorial.docusaurus.io/docs/intro  'Edit this page'  link is not redirecting to the GitHub repo. 
In all the pages of docusaurus --> tutorial , the same issue exists.

### Steps to reproduce

Step 1: GO to https://tutorial.docusaurus.io/docs/intro
Step 2: Click 'Edit this page'

### Expected behavior

Should open the github repo for that page.

### Actual behavior

404 Page not found error.

### Your environment

- Public source code:
- Public site URL:
- Docusaurus version used:
- Environment name and version (e.g. Chrome 89, Node.js 16.4):
- Operating system and version (e.g. Ubuntu 20.04.2 LTS):

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by Josh-Cena** [comment]
Please don't assume that the init template is functional in any way. It's only meant for a demo and we have _explicitly_ stated that `// please change it to your own demo` in the config file.

Could I know where you were pointed to this domain? AFAIK it's not advertised much and we mostly use this template for interactive playgrounds and `create-docusaurus`

**Comment by slorber** [comment]
![image](https://user-images.githubusercontent.com/749374/146360464-7143a7a5-c0c0-4282-83e3-5f6a35204726.png)

The tutorial is browsable online.

It's based on `examples/classic` deployed to Netlify

Not sure what's the best:
- find a way to use the create-docusaurus edit URLs?
- find a way to disable this

Can be a post-step in the generate example script?

**Comment by Josh-Cena** [comment]
What about pointing to the create-docusaurus folder? This has the additional benefit that if the user sees anything she would like to update in the init template she can easily do so.

**Comment by slorber** [comment]
Yes, that makes sense to me, we could always link to `create-docusaurus` (online tutorial, init, codesandbox...) so that people would be less confused and be able to edit the tutorial in case of any problem/suggestion
