### ISSUE TITLE
Remove project name in header bar on mobile

### ISSUE THREAD

**Issue by JoelMarcey** [facebook/Docusaurus#613]
### Is this a bug report?

No. Better user experience. See https://github.com/facebook/Docusaurus/pull/575 for discussion.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

### Environment

N/A

### Steps to Reproduce

1. Go to docusaurus.io on mobile

### Expected Behavior

Cleaner header nav with the search bar without project name

### Actual Behavior

Project name exists

(Write what happened. Add screenshots, if applicable.)

### Reproducible Demo

N/A

**Comment by yangshun** [comment]
This might be a problem for projects without a logo, like https://twitchtv.github.io/twirp/docs/intro.html

**Comment by JoelMarcey** [comment]
@yangshun That is a fair point actually. In that case, we could just stick with the title or nothing maybe?

**Comment by yangshun** [comment]
Sounds like a good idea. Hide the title if there's a logo, else do nothing 👍

**Comment by yangshun** [comment]
Claimed by @amyrlam
