### ISSUE TITLE
Admonition Theme Import - Module not found

### ISSUE THREAD

**Issue by cbaum86** [facebook/docusaurus#6163]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Description

On the [Admonitions page](https://docusaurus.io/docs/markdown-features/admonitions#usage-in-jsx) it states the component can be imported into a jsx file using:`import Admonition from '@theme/Admonitions';`.

However this is incorrect and causes a error:`Module not found: Error: Can't resolve '@theme/Admonitions' in '/sandbox/src/components'`

The import should be `import Admonition from '@theme/Admonition';` **without the 's'** and this works without error.

### Self-service

- [ ] I'd be willing to address this documentation request myself.

**Comment by Josh-Cena** [comment]
Oh, oops—thanks for catching that! Willing to make a PR yourself?
