### ISSUE TITLE
DeprecationWarning: 'onBeforeSetupMiddleware' option is deprecated. Please use the 'setupMiddlewares' option.

### ISSUE THREAD

**Issue by hasezoey** [facebook/docusaurus#6167]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [ ] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

Currently, when running `docusaurus start`, a deprecation warning comes up:

```txt
(node:71710) [DEP_WEBPACK_DEV_SERVER_ON_BEFORE_SETUP_MIDDLEWARE] DeprecationWarning: 'onBeforeSetupMiddleware' option is deprecated. Please use the 'setupMiddlewares' option.
```

this error comes only when using `start`, and not `build`

---

Note: i did not do the step `I have tried the npm run clear or yarn clear command.`, because no command like `yarn clear` exists (using yarn version `1.22.17`)

### Steps to reproduce

1. create example project (or clone `https://github.com/nodkz/mongodb-memory-server` and cd into `/website`)
2. install docusaurus `2.0.0-beta.14` (either by manually setting it in the package.json or using `yarn upgrade --latest @docusaurus/core @docusaurus/preset-classic`)
3. run `docusaurus start --no-open --poll`

### Expected behavior

to not have a deprecation warning

### Actual behavior

the mentioned deprecation warning

(its currently just a warning, not breaking anything)

### Your environment

- Public source code: https://github.com/nodkz/mongodb-memory-server/tree/master/website (modified to use mentioned version)
- Public site URL: https://nodkz.github.io/mongodb-memory-server/ (should not matter in this case)
- Docusaurus version used: `2.0.0-beta.14`
- Environment name and version: 17.2.0
- Operating system and version: Manjaro Linux 21.2(rc2?)

in case it matters, i also get some warnings when installing all packages:

```txt
info No lockfile found.
[1/4] Resolving packages...
warning @docusaurus/core > webpack-dev-server > url > querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
[2/4] Fetching packages...
[3/4] Linking dependencies...
warning "@docusaurus/core > react-dev-utils > fork-ts-checker-webpack-plugin@6.5.0" has unmet peer dependency "typescript@>= 2.7".
warning "@docusaurus/core > @docusaurus/utils > @mdx-js/runtime@1.6.22" has incorrect peer dependency "react@^16.13.1".
warning "@docusaurus/preset-classic > @docusaurus/theme-search-algolia > @docusaurus/theme-common@2.0.0-beta.14" has unmet peer dependency "prism-react-renderer@^1.2.1".
warning "@docusaurus/preset-classic > @docusaurus/theme-search-algolia > @docsearch/react@3.0.0-alpha.42" has unmet peer dependency "@types/react@>= 16.8.0 < 18.0.0".
warning "@docusaurus/preset-classic > @docusaurus/theme-search-algolia > @docsearch/react > @algolia/autocomplete-preset-algolia@1.5.0" has unmet peer dependency "@algolia/client-search@^4.9.1".
[4/4] Building fresh packages...
success Saved lockfile.
Done in 25.44s.
```

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by slorber** [comment]
Thanks, this seems like a recent change in Webpack: https://github.com/webpack/webpack-dev-server/pull/4068

Should be fixed in the next release with https://github.com/facebook/docusaurus/pull/6168

**Comment by Josh-Cena** [comment]
@hasezoey Also, do note that `yarn clear` does exist, it's just that your site is initialized so long ago that this script wasn't included in the template. You can add another `"clear": "docusaurus clear"` in your package.json's `scripts`.

**Comment by hasezoey** [comment]
> Also, do note that yarn clear does exist, it's just that your site is initialized so long ago that this script wasn't included in the template.

wouldnt that make it `yarn run clear` instead of just `yarn clear`? (from what i know the only script that can omit `run` is `test`, didnt try others, but i know that some others like `build` require subcommand `run`)

also, if i remember correctly the project where i noticed this issue in, got created with around `@docusaurus/core@2.0.0-alpha.40`

> You can add another "clear": "docusaurus clear" in your package.json's scripts.

thanks for this note, i did not know this subcommand existed in docusaurus, is there documentation somewhere on what exactly it does?

**Comment by Josh-Cena** [comment]
It's `yarn clear` and `npm run clear`, because npm demands all custom scripts to be invoked with `run` but yarn is smart enough to know which scripts are intrinsic and which are external so as long as there's no ambiguity you can drop the `run`. `yarn build` doesn't require `run` either.

> also, if i remember correctly the project where i noticed this issue in, got created with around `@docusaurus/core@2.0.0-alpha.40`

Yep, `docusaurus clear` was introduced somewhere after that. You can get the latest list of CLI commands here: https://docusaurus.io/docs/next/cli#docusaurus-cli-commands

**Comment by Chasen-Zhang** [comment]
but What is the final solution？

**Comment by Josh-Cena** [comment]
@Chasen-Zhang The deprecation is just a warning, not an error. Your error is unrelated, which is that localhost is not found. Did you modify your hosts file?

**Comment by Josh-Cena** [comment]
Also, to get rid of the warning, just upgrade to 2.0.0-beta.14

**Comment by slorber** [comment]
> Also, to get rid of the warning, just upgrade to 2.0.0-beta.14

Just double-checked and it will only be in the next beta.15 release (or canary)

For now you can just ignore this warning, it will disappear soon

**Comment by imransilvake** [comment]
Getting the same weird warnings on `yarn start`.

**Comment by S0f0s** [comment]
I get the same error when i run my app which just tries to authenticate users for login in through Azure AD. When i try to log-in through my app, the Microsoft popup login  window flashes for sec and then dies.

**Comment by Josh-Cena** [comment]
@S0f0s Your error is unrelated. If your login doesn't succeed it has nothing to do with Docusaurus.

Everyone, this message is just a WARNING. Webpack dev server doesn't do breaking changes across minor versions so nothing would actually break. The next release would get rid of this message. For now, you can either use canary, or bear with it.

**Comment by avavion** [comment]
hallo
