### ISSUE TITLE
Double next/prev arrow on blog post

### ISSUE THREAD

**Issue by TheZoker** [facebook/docusaurus#6171]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

In the latest release, there are two arrows on the next/prev element on the blog:
![image](https://user-images.githubusercontent.com/1368405/147157617-b4fb5d61-49b0-41df-84b1-0e3d4d4641dd.png)

This can also be reproduced here:
https://docusaurus.io/blog/2021/11/21/algolia-docsearch-migration

The arrow is once inserted as HTML element and once as :after element with the content attribute. 

### Steps to reproduce

See above

### Expected behavior

Only one arrow instead of two

### Actual behavior

Two arrows

### Your environment

- Public source code:
- Public site URL:
- Docusaurus version used:
- Environment name and version (e.g. Chrome 89, Node.js 16.4):
- Operating system and version (e.g. Ubuntu 20.04.2 LTS):

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by Josh-Cena** [comment]
The fix would be easy, but it would be related to our theme designing approach. @slorber should we make `DocPaginatorNavLink` a generic `PaginatorNavLink` component, or should we just make another `BlogPaginatorNavLink` component? I prefer the former

**Comment by slorber** [comment]
👍 for PaginatorNavLink

We should start to implement our own typesafe theme design system (+ storybook + Chromatic) instead of using Infima classes everywhere, and this component is a good first candidate as it is used in multiple places

See also https://github.com/facebook/docusaurus/issues/6116
