### ISSUE TITLE
`Bad character escape sequence` when the path of workspace contain non-English characters

### ISSUE THREAD

**Issue by AhmedElTabarani** [facebook/docusaurus#6180]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [ ] I have tried the `npm run clear` or `yarn clear` command.
- [ ] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

If the project path contain non-English characters it gives me `Bad character escape sequence`

![image](https://user-images.githubusercontent.com/69223584/147294175-99f5a0c4-cfe7-491b-b17d-7da6c2a4338a.png)

the path of the project is : ` F:\برمجة\PixelPlatform\`
there are non-English word `برمجة`, this make the issue happen

If i move the project to a path that contains English letters like :  ` F:\PixelPlatform\`
The problem will be solved

### Steps to reproduce

Just put the project in a folder has non-English characters

and run:
- npx create-docusaurus@latest PixelPlatform classic
- yarn install
- yarn start

### Expected behavior

Works!!

### Actual behavior

Got an error because the path contain non-English characters

### Your environment

- Docusaurus version used: 2.0.0-beta.14
- Environment name and version: Chrome 96.0.4664.110, Nodejs v15.5.0
- Operating system and version: Windows 10

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by Josh-Cena** [comment]
We had the same problem with Chinese paths. Paths on windows always seem messed up😅

**Comment by Josh-Cena** [comment]
Fixed by #6190. Please [test with the latest canary release](https://docusaurus.io/community/canary).

**Comment by AhmedElTabarani** [comment]
> Fixed by #6190. Please [test with the latest canary release](https://docusaurus.io/community/canary).

Sorry for the late reply, I just tested it and everything works 👍

**Comment by Josh-Cena** [comment]
Good to know!
