### ISSUE TITLE
CodeBlock in React pages 

### ISSUE THREAD

**Issue by Grafikart** [facebook/docusaurus#6185]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Description

It's possible to use block of code in markdown document but the documentation does not explain how to use the same feature in JSX page. Does docusaurus exposes a component for this kind of usage ?

It's possible to use the `<Highlight>` component from "prism-react-renderer" but we loose the styling and every configuration :(. If there is a component for this I'm willing to add this to the documentation myself

### Self-service

- [X] I'd be willing to address this documentation request myself.

**Comment by Josh-Cena** [comment]
There was a brief mention here: https://docusaurus.io/docs/markdown-features/react#importing-code-snippets

But yes, we can make it more explicitly documented

**Comment by slorber** [comment]
Yes, this should work:

```jsx
import CodeBlock from '@theme/CodeBlock';

export default function MyHomePage() {
  return (
    <CodeBlock className="language-bash">
      {"yarn install\nyarn start"}
    </CodeBlock>
  );
}
```

We still have some improvements left to do, as the original component was initially created for usage inside markdown.

For example we probably want a better language API:

```diff
-    <CodeBlock className="language-bash">
+    <CodeBlock language="bash">
```

**Comment by jcubic** [comment]
This doesn't work the whole code is in one line. I asked about this at the discussion page: [#9881](https://github.com/facebook/docusaurus/discussions/9881).
