### ISSUE TITLE
Feed generation warns: "Received `true` for a non-boolean attribute" when using {2,3} highlighting

### ISSUE THREAD

**Issue by KELEN** [facebook/docusaurus#6195]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [ ] I have tried the `npm run clear` or `yarn clear` command.
- [ ] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

the new version is 2.0.0-beta.14

````
```jsx {2,3}
const a = 123;

return {
  a: 1
}
```
````

```
Warning: Received `true` for a non-boolean attribute `{2,3}`.

If you want to write it to the DOM, pass a string instead: {2,3}="true" or {2,3}={value.toString()}.
    at code
    at D:\github\website\node_modules\@mdx-js\react\dist\cjs.js:153:30
```

### Steps to reproduce

when use highlight code，eg: {2, 3}

npm run build，throw warning

### Expected behavior

No warning show

### Actual behavior

Warning: Received `true` for a non-boolean attribute `{2,3}`.

### Your environment

- Public source code:
- Public site URL:
- Docusaurus version used:
- Environment name and version (e.g. Chrome 89, Node.js 16.4):
- Operating system and version (e.g. Ubuntu 20.04.2 LTS):

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by Josh-Cena** [comment]
I do remember seeing the warning some time back in our production builds, but at some point they are gone. Could you delete node_modules and lock file, re-install, and build to see if the issue persists?

**Comment by slorber** [comment]
😅 never seen this warning before, weird

**Comment by Josh-Cena** [comment]
Just realized I saw it not on the Docusaurus site build, but on my site...

https://app.circleci.com/pipelines/github/Josh-Cena/Josh-Cena.github.io/30/workflows/b0668fe3-97ae-4ef1-8e8d-1f431c3cbda8/jobs/28

**Comment by slorber** [comment]
Oh I see

Agree, I don't like too much the `{2,3}` notation, trying to emphasis the start/end comments more

**Comment by dsmmcken** [comment]
I get something similar, where I have a custom remark plugin preprocessing my code snippets to feed them to a testing framework. Some code blocks have an skip-testing annotation like:

````
```python skip-test
# untested example
```
````

and this warns with a similar error.

**Comment by Josh-Cena** [comment]
@dsmmcken This basically happens with any codeblock meta that's not `foo="bar"`. It's a really common pattern, but if there's no remark plugin to consume it, it ends up in the final MDX output, which is the case for our blog feeds feature, which uses `mdx/runtime`
