### ISSUE TITLE
React MSAL authentication support with Azure AD

### ISSUE THREAD

**Issue by ranjithsnair** [facebook/docusaurus#6205]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Motivation

We need a way to update ReactDOM.render to integrate MSAL authentication

### Self-service

- [ ] I'd be willing to do some initial work on this proposal myself.

**Comment by Josh-Cena** [comment]
As we've stated in the issue form:

> This is not for feature requests. If this involves new APIs or new behaviors, consider requesting the feature on https://docusaurus.io/feature-requests instead.
> We give you maximum freedom to write an elaborated proposal illustrating why you think the change is beneficial for us, and what steps we should take to turn this into reality.
> You should not use this to ditch the feature request or bug template; such action could make us identify the issue wrongly and close it without doing anything.

Your proposal is too brief and does not include anything to facilitate us to make it reality.
