### ISSUE TITLE
Add the Facebook Chat Plugin to Site

### ISSUE THREAD

**Issue by skgandikota** [facebook/docusaurus#6212]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Motivation

On using docusaurus for building a website, many clients have requested us to add Facebook chat , which helps them in handling clients with their existing subscription

To serve clients immediately as a work around I have added code block  directly to footer using `{  html: "<code-block>" }  `  and deployed the code in my clients website, its working as expected , feel free have a look [**igniteresearch**](https://igniteresearch.in/)

![image](https://user-images.githubusercontent.com/24265936/147589683-136481ec-eeeb-4752-8772-7e6616eac0be.png)
![image](https://user-images.githubusercontent.com/24265936/147589819-d7153411-157f-4987-bc40-22723aa5399c.png)

Now Planning to created same in standard format and followed "[plugin-google-analytics | Docusaurus](https://docusaurus.io/docs/api/plugins/@docusaurus/plugin-google-analytics)" documentation  and created initial package [@skgandikota/docusaurus-plugin-facebook-chat](https://www.npmjs.com/package/@skgandikota/docusaurus-plugin-facebook-chat)  & code is available in [github repo](https://github.com/skgandikota/docusaurus-plugin-facebook-chat). for some reason its not working - need help - so that I can accomplish the same and with this I can contribute my part to the docusaurus and help many like me 

### Self-service

- [X] I'd be willing to do some initial work on this proposal myself.

**Comment by slorber** [comment]
Hey

> for some reason its not working - need help 

How can we help if you don't tell exactly what is going wrong? 😅 

Do you see any error anywhere? (terminal, browser console, network...). 

I also don't understand why your plugin contains code that is related to Google Analytics: https://github.com/skgandikota/docusaurus-plugin-facebook-chat/blob/main/src/analytics.ts

Please assume I have no idea how this FB chat widget work. Please try to init a new docusaurus site, commit the initial state,  and then do the integration as you did for your customer in a 2nd commit. I would then be able to see how you did that integration and help you figure out how to create a plugin

**Comment by skgandikota** [comment]
Modified code a lot after previous message and [new code base is available here](https://github.com/skgandikota/docusaurus-plugin-facebookchat) . The required facebook chat code is injected properly now 
![image](https://user-images.githubusercontent.com/24265936/147642372-362bd950-dbb6-4734-81d9-453b03b24cbb.png)

but All request to facebook are blocked by CORS policy, when inject this way - but work when I load the script via footer 
![image](https://user-images.githubusercontent.com/24265936/147647741-c8b9df16-47df-4088-ad59-0f2b69c57790.png)

**Comment by Josh-Cena** [comment]
If it says CORS, then it means CORS. Is your implementation actually what's recommended?

**Comment by skgandikota** [comment]
Facebook recommended us to add below code to get the chat plugin - So I have injected script under headTags and div tag near the prebodyTag

```
<!-- Messenger Chat Plugin Code -->
    <div id="fb-root"></div>

    <!-- Your Chat Plugin code -->
    <div id="fb-customer-chat" class="fb-customerchat">
    </div>

    <script>
      var chatbox = document.getElementById('fb-customer-chat');
      chatbox.setAttribute("page_id", "1970159599725916");
      chatbox.setAttribute("attribution", "biz_inbox");
    </script>

    <!-- Your SDK code -->
    <script>
      window.fbAsyncInit = function() {
        FB.init({
          xfbml            : true,
          version          : 'v12.0'
        });
      };

      (function(d, s, id) {
        var js, fjs = d.getElementsByTagName(s)[0];
        if (d.getElementById(id)) return;
        js = d.createElement(s); js.id = id;
        js.src = 'https://connect.facebook.net/en_US/sdk/xfbml.customerchat.js';
        fjs.parentNode.insertBefore(js, fjs);
      }(document, 'script', 'facebook-jssdk'));
    </script> 
```

**Comment by Josh-Cena** [comment]
I find it pretty weird and I wonder you ended up with CORS instead of something worse. When the head tag is loaded, the body DOM isn't even mounted yet. `document.getElementById` in the head won't return you anything.

Also, you can try to use `clientModules` instead of injecting HTML tags. You can check out how our Google Analytics plugin is implemented.

**Comment by skgandikota** [comment]
Understood ! Will try as mentioned [here in Google Analytics plugin](https://github.com/facebook/docusaurus/blob/main/packages/docusaurus-plugin-google-analytics/src/index.ts)  and get back here - If hit a bottle-neck

**Comment by slorber** [comment]
Hey, it's really hard to understand this issue for me.

Previously, the chat widget was working here: https://igniteresearch.in/ why isn't it the case anymore? Please revert to a working state (and if possible provide us access to the source code or create a smaller repo) so that at least we can study your working solution.

Now if you want to turn this FB chat widget into a plugin, we should have 2 repos and live deployments to inspect:
- The one that works (https://igniteresearch.in/)
- The one that does not work (using your plugin)

Please structure your thought and create a summary for these 2 distinct deployments, including relevant code snippets, error messages, and links for each one of those.


If you have CORS issues, double-check if you shouldn't whitelist any domain on the FB interface. Some JS might fail to load because the requesting domain is simply not whitelisted in the configuration.

**Comment by skgandikota** [comment]
Apologizes  I might have frustrated both of you  by modifying code continuously and testing with a mono repo with not giving enough time to have a look at the issue

As said in the above chat - I have created following

1. Plugin Code Repository [docusaurus-plugin-facebookchat]( https://github.com/skgandikota/docusaurus-plugin-facebookchat )

2. Plugin Code Deployed Version Repo & URL :   [facebook-plugin-001](https://github.com/skgandikota/facebook-plugin-001)  & URL : https://skgandikota.github.io/facebook-plugin-001/

3. Injected Facebook Plugin Script to Footer Repo & URL : [facebook-plugin-002](https://github.com/skgandikota/facebook-plugin-002)  & URL : https://skgandikota.github.io/facebook-plugin-002/

4.  FaceBook Shared Plugin Code instruction which is used in the above  [plugin-code-email.pdf](https://github.com/facebook/docusaurus/files/7789074/plugin-code-email.pdf)

**My Requirement**  is to add Facebook Chat widget to the Website which is accomplished with work-around i.e. by injecting the Facebook Plugin Script to Footer Repo - [CLICK HERE FOR CODE CHANGE PERMALINK ](https://github.com/skgandikota/facebook-plugin-002/blob/3f1e27ddda8df146943aa5488c7f4e664f49a8d0/docusaurus.config.js#L72)


Now motivation is doing work in standard-way and also help the one like with minimal code change in cleaner way - So Created a repository [docusaurus-plugin-facebookchat]( https://github.com/skgandikota/docusaurus-plugin-facebookchat ) and [published package here  ](https://www.npmjs.com/package/@skgandikota/docusaurus-plugin-facebookchat)

utilized the above published package in the repo  [facebook-plugin-001](https://github.com/skgandikota/facebook-plugin-001)  and post deploy  noticed  request to facebook is blocked by CORS  and error message can be see in the console using URL : https://skgandikota.github.io/facebook-plugin-001/ and same snippet is pasted below 

![image](https://user-images.githubusercontent.com/24265936/147668213-5831e3dc-3357-4e7a-a660-e03e243b7e09.png)

**Comment by Josh-Cena** [comment]
@skgandikota Closing the issue for now. Please move the discussion to our Discord server because GitHub issues aren't for questions.

**Comment by Josh-Cena** [comment]
Regarding your latest errors, though I have no idea why you got CORS, I'm sure you got `setAttribute` on `null` because you are reading DOM in the head at which time the DOM isn't mounted yet. As I said, you either want to move the tags to post body, or just use client modules instead.

**Comment by slorber** [comment]
@skgandikota we don't know anything about FB SDK and this chat widget. What we can help you with is only to produce the right HTML, now it's your role to tell us exactly what HTML you want us to produce, and how Docusaurus prevents you to achieve this. Feel free to write HTML by hand it necessary to demonstrate the problem.


What I see is that your footer integration works, while putting tags in head does not seem to work. I have no idea why and I can't dedicate time to figure this out. What I only see is that it's recommended to add integration code after the body tag, not in head like you tried to do.

![image](https://user-images.githubusercontent.com/749374/147669617-b3696634-9085-426f-ab1e-acb68feeef16.png)

So, you probably need to try using `preBodyTags` for everything. Apparently you should be able to pass a whole html string there, like what you did for the footer.

![image](https://user-images.githubusercontent.com/749374/147669900-4fafe671-aa88-4454-b84a-0f09f41dddd9.png)


https://docusaurus.io/docs/next/api/plugin-methods/lifecycle-apis#injectHtmlTags

**Comment by Josh-Cena** [comment]
Yes, you _have to_ use `postBodyTags`, because HTML is loaded in a stream fashion. Tags that are loaded first can't see DOM that aren't mounted yet, so these integration scripts should be injected last.
