### ISSUE TITLE
sidebar_class_name not applied for index pages

### ISSUE THREAD

**Issue by lebalz** [facebook/docusaurus#6232]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Description

When using a category index page (e.g. `docs/how-to/index.md`) and providing front-matter meta data

```md
---
sidebar_class_name: green
---
```

i would expect, that this is applied to the category's `<li class="green">` element, but it is not.

Current **workaround**: `_category_.json` with
```json
// _category_.json
{
  "className": "green"
}
```

### Self-service

- [ ] I'd be willing to address this documentation request myself.

**Comment by Josh-Cena** [comment]
I think that's a reasonable expectation. Would investigate

**Comment by Josh-Cena** [comment]
Closing in favor of #6254
