### ISSUE TITLE
Build failed with esbuild 0.14: (0 , import_index.getInfimaActiveClassName) is not a function

### ISSUE THREAD

**Issue by Josh-Cena** [facebook/docusaurus#6235]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

Noticed this during #6230. Probably related to their breaking changes in 0.14 related to how CJS files are transpiled, because on SSR we transpile to CJS. Don't have the bandwidth to investigate this, but any 0.13 esbuild version seems to work fine.

### Steps to reproduce

1. `create-docusaurus`
2. `yarn add esbuild-loader` (version `2.18.0`; bundled with `esbuild@0.14.8`)
3. Modify `webpack.jsLoader` to use esbuild-loader
4. `yarn build`

### Expected behavior

Build successful

### Actual behavior

```
[ERROR] Docusaurus Node/SSR could not render static page with path /404.html because of following error:
TypeError: (0 , import_index.getInfimaActiveClassName) is not a function
    at DefaultNavbarItem (main:23302:108)
    at d (main:60432:498)
    at bb (main:60435:16)
    at a.b.render (main:60441:43)
    at a.b.read (main:60440:83)
    at Object.exports.renderToString (main:60451:138)
    at doRender (main:18285:41)
    at async render (main:18256:12)
```

### Your environment

- Public source code: Just use our website to investigate

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by slorber** [comment]
Could this be because of using a relative import?

```
import {getInfimaActiveClassName} from './index';
```

That looks like something we want to avoid in themes due to swizzling

**Comment by Josh-Cena** [comment]
@RDIL probably figured out the actual cause: https://github.com/evanw/esbuild/commit/665b06dd4b35c4074ddc5545e3606fba42af4ba6

**Comment by RDIL** [comment]
@Josh-Cena knew it

**Comment by Josh-Cena** [comment]
Closing because this is an external issue. See https://github.com/evanw/esbuild/issues/2037.
