### ISSUE TITLE
Blog returns wrong date when using YYYY/MM/DD format

### ISSUE THREAD

**Issue by rccttwd** [facebook/docusaurus#6241]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [ ] I have tried the `npm run clear` or `yarn clear` command.
- [ ] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io.
- [ ] I have read the console error message carefully (if applicable).

### Description

Typing in a date with YYYY/MM/DD format returns wrong date, which is displaying the previous date.

```
---
date: 2021/08/01
---
```

shown as:
July 31, 2021

### Steps to reproduce

![1](https://user-images.githubusercontent.com/92060735/147855262-93cc9fb9-47d3-4656-8cce-1d870de1557c.jpg)

### Expected behavior

N/A

### Actual behavior

N/A

### Your environment

- Public source code:
- Public site URL:
- Docusaurus version used:
- Environment name and version (e.g. Chrome 89, Node.js 16.4):
- Operating system and version (e.g. Ubuntu 20.04.2 LTS):

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by Josh-Cena** [comment]
Hi, fixed in #6244. Please [test with canary release](https://docusaurus.io/community/canary)

**Comment by markharrison** [comment]
> Hi, fixed in #6244. Please [test with canary release](https://docusaurus.io/community/canary)

Canary works for me.

But there is an issue if you want to use the date from the folder name.   Try a folder name of "2021-08-19-Hello" ... fails when you do  npm start  - you cannot access the main Blog screen (errors in the Browser console).   But works if you build the site.

**Comment by Josh-Cena** [comment]
Could you open another issue @markharrison? Your problem seems unrelated to the current one since you are actually using dates within file path.
