### ISSUE TITLE
Contributors svg not updating in readme. 

### ISSUE THREAD

**Issue by PatelN123** [facebook/docusaurus#6253]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [ ] I have tried the `npm run clear` or `yarn clear` command.
- [ ] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io.
- [ ] I have read the console error message carefully (if applicable).

### Description

The contributors widget (https://opencollective.com/Docusaurus/contributors.svg) doesn't seem to be updating. 

### Steps to reproduce

N/A

### Expected behavior

Image to update with new contributors

### Actual behavior

Frozen on the same image

### Your environment

N/A

### Self-service

- [X] I'd be willing to fix this bug myself.

**Comment by Josh-Cena** [comment]
As you already realized, this is provided by Open collective, not something we can fix on our side. See https://github.com/opencollective/opencollective/issues/3354. Fixing this means we have to host an image provider ourselves which is probably an overkill. GitHub contributors graph is always more up-to-date.
