### ISSUE TITLE
Autogenerated category with doc link: use doc frontmatter for category metadata

### ISSUE THREAD

**Issue by wenerme** [facebook/docusaurus#6254]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Description

when construct a category, if exiting README.md like found, use the doc's title and sidebar label for category

https://github.com/facebook/docusaurus/blob/9f0809ae2838c5877558a9d25ba7080e1b327405/packages/docusaurus-plugin-content-docs/src/sidebars/generator.ts#L235-L257

### Motivation

migrate old self gen behavior to newer auto gen, but the auto gen require defined category metadata, there are toooo many, just use the README.md or index.md as category's metadata if not found

### Self-service

- [X] I'd be willing to contribute this feature to Docusaurus myself.

**Comment by slorber** [comment]
What I understand is that you want to provide the `_category_.json` data as `README.md` frontmatter, to avoid having to create an extra `_category_.json` file right?

That makes perfect sense to me, we should do this
