### ISSUE TITLE
Cannot reference docs directory outside of docusaurus proj. `path : "../docs"`

### ISSUE THREAD

**Issue by softmarshmallow** [facebook/docusaurus#6256]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [x] I have tried the `npm run clear` or `yarn clear` command.
- [x] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [x] I have tried creating a repro with https://new.docusaurus.io.
- [x] I have read the console error message carefully (if applicable).

### Description

Works.
```
       docs: {
          routeBasePath: "/",
          path: "docs",
          sidebarPath: require.resolve("./sidebars.js"),
          editUrl: "https://github.com/gridaco/grida.co/edit/main/docs/",
        },
```

Won't work 
```
       docs: {
          routeBasePath: "/",
          path: "../docs",
          sidebarPath: require.resolve("./sidebars.js"),
          editUrl: "https://github.com/gridaco/grida.co/edit/main/docs/",
        },
```

### Steps to reproduce

Have exact same content under docs and docs-site/docs
which docs is a plain .md only directory and docs-site is a docusaurus project dir.

### Expected behavior

Docusaurus should be able to reference content root folder from outside of the project

### Actual behavior

Throws invalid hook call error. (not not found thought)

### Your environment

- Public source code: https://github.com/gridaco/grida.co
- Public site URL: https://grida.co/docs (this is a working version)

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by marcusnewton** [comment]
```
       docs: {
          routeBasePath: "/",
          path: "../docs",
          sidebarPath: require.resolve("./sidebars.js"),
          ...
        },
```

Just chiming in that this preset config does in fact work in my case.

> Throws invalid hook call error. 

Probably worth sharing the actual error message you are encountering.

**Comment by slorber** [comment]
This indeed works, and is actually what all v1 Docusaurus sites that migrated to v2 have by default, so we dogfooded this pretty well

One example: the React-Native website

https://github.com/facebook/react-native-website/blob/main/website/docusaurus.config.js#L50
https://github.com/facebook/react-native-website/tree/main/docs

I'm going to close here, as you don't even tell us what exactly doesn't work (no error message).

If you still think we have a bug, please create a smaller repro by initializing a new docusaurus site or using docusaurus.new

**Comment by Josh-Cena** [comment]
@slorber They indeed have a public repo and I had just completed my fight with git to clone the repo (bad Internet)😅 The repo is a bit complicated, would try to investigate

**Comment by Josh-Cena** [comment]
@softmarshmallow Your `web` package uses React v16 and my guess is that this version somehow ended up in our package. Don't even know how that's possible, probably due to how our Webpack resolves packages

**Comment by softmarshmallow** [comment]
@Josh-Cena 
In fact the repo itself is a monorepo, but docs-site is not included as workspace, so it will not be affected by webpac or other dependency.

You can try it by removing all other files leaving only `/docs-site` and `/docs` - It will throw the same error.

**Comment by Josh-Cena** [comment]
But in fact, I can't even reproduce it, because I just `yarn install`'ed in `docs-site` and it starts locally pretty well...
