### ISSUE TITLE
Symlink docs folder not working

### ISSUE THREAD

**Issue by softmarshmallow** [facebook/docusaurus#6257]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [x] I have tried the `npm run clear` or `yarn clear` command.
- [x] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io.
- [x] I have read the console error message carefully (if applicable).

### Description

See - https://github.com/gridaco/grida.co/tree/snapshot-docusaurus-symlink-docs-not-working

1. Have original content dir under docs
2. Have docusurus project with dir docs-site
3. Have symlink from docs-site/docs to docs (with cmd executed under docs-site, `ln -s ../docs .`
4. Run the project

Crashes.

When you remove symlink, copy whole folder instead, It works.

### Steps to reproduce

1. Clone https://github.com/gridaco/grida.co/tree/snapshot-docusaurus-symlink-docs-not-working
2. cd docs-site
3. yarn && yarn start
4. visit localhost:3001/docs/getting-started/intro
5. See the error: `Cannot destructure property 'description' of 'metadata' as it is undefined.`

To make it work.
1. Remove symlink
2. Copy docs folder from /docs to /docs-site/docs
3. yarn clear && yarn start
4. Now it works.

### Expected behavior

Symlink directory should work same as non symlink

### Actual behavior

```
Uncaught TypeError: Cannot destructure property 'description' of 'metadata' as it is undefined.
    at DocItem (index.js?c185:6)
    at renderWithHooks (react-dom.development.js?ac89:14985)
    at mountIndeterminateComponent (react-dom.development.js?ac89:17811)
    at beginWork (react-dom.development.js?ac89:19049)
    at HTMLUnknownElement.callCallback (react-dom.development.js?ac89:3945)
    at Object.invokeGuardedCallbackDev (react-dom.development.js?ac89:3994)
    at invokeGuardedCallback (react-dom.development.js?ac89:4056)
    at beginWork$1 (react-dom.development.js?ac89:23964)
    at performUnitOfWork (react-dom.development.js?ac89:22776)
    at workLoopSync (react-dom.development.js?ac89:22707)
```

### Your environment

- Public source code: https://github.com/gridaco/grida.co/tree/snapshot-docusaurus-symlink-docs-not-working
- Public site URL:
- Docusaurus version used:`^2.0.0-beta.14`
- Environment name and version (e.g. Chrome 89, Node.js 16.4):
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): MacOS Monterey 

### Reproducible demo

https://github.com/gridaco/grida.co/tree/snapshot-docusaurus-symlink-docs-not-working

### Self-service

- [ ] I'd be willing to fix this bug myself.

## Related
- https://github.com/facebook/docusaurus/pull/5684
- https://github.com/facebook/docusaurus/issues/5679

This is exactly same issue with https://github.com/facebook/docusaurus/issues/5679 But this seems to be not resolved.

**Comment by Josh-Cena** [comment]
I've managed to narrow it down. It's because the MDX loader created by the doc plugin only includes the symlinked directory, but Webpack loads from the original directory. This causes the MDX fallback loader to kick in on that folder. I don't know how this can be best solved...

**Comment by slorber** [comment]
yes @Josh-Cena, can't find where but it was also discussed in another issue about re-enabling this setting.

I'm fine with that 👍

**Comment by Josh-Cena** [comment]
Going to close as wontfix. If you want to support symlinked content directories, just use `resolve.symlinks: false`.
