### ISSUE TITLE
Unable to pull markdown files from Git repo

### ISSUE THREAD

**Issue by anarwal** [facebook/docusaurus#6258]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

I am trying to use [importing-markdown](https://docusaurus.io/docs/markdown-features/react#importing-markdown) functionality. I am pulling data from a different repo.

The site loads after clear and restarting server however the page never loads. Is there anything missing while reference markdown file from different repo?

### Steps to reproduce

Create a new markdown file and pull data from markdown in different repo.

```
import TestDocs from 'https://github.com/my-repo/docs.md';

<TestDocs />
```

### Expected behavior

Data from destination markdown available in your current markdown file as mentioned in docs.

### Actual behavior

Page never loads up.

### Your environment

- Operating system and version (e.g. Ubuntu 20.04.2 LTS): MacOS

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by Josh-Cena** [comment]
This is certainly out of scope: not even how React fundamentally functions. The `import` statement only accepts file paths, not URLs. You can try @RDIL's plugin: https://github.com/rdilweb/docusaurus-plugin-remote-content
