### ISSUE TITLE
`hidebar_hide` option to md meta

### ISSUE THREAD

**Issue by softmarshmallow** [facebook/docusaurus#6267]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Description

since autogenerate gens all available items under directory, I'de like to have option `sidebar_hide` like other api like `sidebar_position` or `sidebar_label`.

This is useful when hiding the README.md (only for github & collaborators) that should not appear on production docs site.

### Self-service

- [x] I'd be willing to contribute this feature to Docusaurus myself.

**Comment by Josh-Cena** [comment]
Hi! This will be part of #5782 where we allow you to display an arbitrary sidebar, or no sidebars at all.
