### ISSUE TITLE
Bookmarks or Favorites List

### ISSUE THREAD

**Issue by dtbj** [facebook/docusaurus#6273]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Description

I am talking about **bookmarks** like user can bookmark some of the docs page as well as blog page and if admin wants they can set allowbookmark:false in markdown formatter to disable for some particular page, that button should look like this image ![image](https://user-images.githubusercontent.com/87176273/148328541-2c99661c-c7c1-476a-a565-b8abfd144fd2.png) that button can be placed anywhere in sidebar top or bottom and user should be able to change position of that button using docusaurus.config.js file, next all the pages bookmarked by user can be stored in local storage with title and url, next there should be a page at domain/bookmarks where user can manage all of his bookmarks and delete if he wants there should be an import export option also on that page only, next this is optional that you can also allow users to change text of bookmarks with it's icon like it can be useful if bookmarks doesn't feel good for someone they can use something like mark as favorite page and they can also customize url like if they want the page to be on domain/favorites. So that's all about feature request it came in my mind and it can make docusaurus really unique coz there is no static documentation cms or react ui generator that have this thing.

If it's implemented into the core I will be grateful if not then also no issues, Docusaurus already helped me a lot to make my static website so instead of being thankful I won't cry that why they aren't implementing this.

Thanks

### Has this been requested on Canny?

Nope

### Motivation

It will be very useful for users who want to save some page of docs or blog to read later something like youtube watch later, I agree that desktop user's already have a bookmark option but in mobile devices you know managing bookmarks is not that easy and in desktop also sometimes it becomes mess to sort out bookmarks if this will be implemented this will really be helpful for different use cases.

### Have you tried building it?

No I haven't tried and I can't, I am beginner just learning basics.

### Self-service

- [ ] I'd be willing to contribute this feature to Docusaurus myself.

**Comment by slorber** [comment]
Hi

You are throwing various raw ideas in a wall of text here, and no real API design, prototype or mockup: 

![image](https://user-images.githubusercontent.com/749374/148368079-f68539de-ab53-4b04-82e8-87665bd8b36f.png)


If this is just a suggestion and you don't have a concrete design, add these suggestions to our Canny board: https://docusaurus.io/feature-requests

We'll eventually implement this if there's enough upvotes
