### ISSUE TITLE
Category docs at root of autogenerated sidebar ordered as regular sidebar items

### ISSUE THREAD

**Issue by duanwilliam** [facebook/docusaurus#6298]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io.
- [ ] I have read the console error message carefully (if applicable).

### Description

When using an autogenerated sidebar, if there is a category index doc at the root of the sidebar item tree, that index doc appears to be positioned in the sidebar by filename alphabetical order (the default ordering). The index doc also cannot be ordered by adding a number prefix; instead, it can only be ordered by adding `sidebar_position` frontmatter to the doc.

For instance, given a sidebar generated from the directory `docs` and the following files:
- `docs/index.md` with title `C`
- `docs/h.md` with title `D`
- `docs/g.md` with title `E`
- `docs/j.md` with title `F`
- `docs/0-k/foo.md` with category title `k`
- `docs/m/bar.md` with category title `m`

the resultant sidebar order is
- `docs/0-k/foo.md` with category title `k`
- `docs/g.md` with title `E`
- `docs/h.md` with title `D`
- `docs/index.md` with title `C`
- `docs/j.md` with title `F`
- `docs/m/bar.md` with category title `m`

### Steps to reproduce

_note: my computer's currently pretty slow so I couldn't test it thoroughly, so some steps may not be necessary_

1. `npx create-docusaurus@latest website-name`.
2. make the project docs-only (possibly not necessary)
3. add index doc at docs root (possible this applies for _any_ sidebar, so long as autogenerated index doc is at the sidebar root)
4. add various docs with adjacent filenames/titles (eg the example file structure provided above)
5. run the site and observe the sidebar

### Expected behavior

The autogenerated index doc being at the top of the sidebar by default if it is in the outermost "category" of the sidebar.
The index doc by default is at the top of the sidebar; or otherwise having some way outside of adding frontmatter / manually specifying the order in `_category_.yml` to order the index doc.

### Actual behavior

The index doc is ordered as a regular sidebar item.

### Your environment

- Docusaurus version used: `2.0.0-beta.14`
- Environment name and version (e.g. Chrome 89, Node.js 16.4): `node v14.15.4`
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): Windows 10 Build 19042

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by Josh-Cena** [comment]
Hi, do you think your issue is a duplicated of https://github.com/facebook/docusaurus/issues/6127?

**Comment by duanwilliam** [comment]
Thanks for the link, it certainly helped bring some extra context.
I think this issue is somewhat different since it seems to be a specific case of when the index doc is for the root of the sidebar (ie there is no parent category); in this situation there probably isn't much ambiguity/deviation in preferred usage for this (having the index doc be the topmost item of the whole sidebar). it's possible it could just not be worth the effort/reduced consistency though (and as mentioned, it _can_ be worked around by adding `sidebar_position` frontmatter, even if I'd prefer not to add frontmatter if possible through other means).
If number prefixes are stripped prior to searching for index docs, that could address this issue as well by just allowing the index doc to be number prefixed, but I don't currently know the order of processing.

**Comment by slorber** [comment]
Hey @duanwilliam , this issue is quite hard to decipher for me. There's a lot of text and I don't understand the relevance of all the details provided (like: do the doc titles matter??? 🤷‍♂️ )

---

This is what I understand:

For `docs/index.md` (where docs is **not** a category because it's the root) you want the `index.md` doc to appear first in the sidebar, despite not being the first alphabetical doc of the folder

Is that correct?

**Comment by slorber** [comment]
😅 why pretty much, what is incorrect for you here?

**Comment by duanwilliam** [comment]
it's all good, sums up the core issue + suggestion well

**Comment by slorber** [comment]
Thanks :) 

That makes sense to me, we should change this default behavior as putting index.md first can be quite convenient

**Comment by a8t** [comment]
Maybe this will help:

```
   async sidebarItemsGenerator({
            defaultSidebarItemsGenerator,
            ...args
          }) {
            const sidebarItems = await defaultSidebarItemsGenerator(args);

            return sidebarItems.map((sidebarItem) => {
              return sidebarItem.items.length > 0
                ? sidebarItem
                : {
                    type: "doc",
                    id: `${sidebarItem.label}/README`,
                  };
            });
          },
```

**Comment by Josh-Cena** [comment]
I don't like this. The logic is that "we pick a category index page by looking for `index.md`", not that `index.md` has something inherently different. If it's not behaving like a category index (i.e. linked by the category's title), it has to behave exactly like other ordinary items. Doing too much magic only annoys users—we want the behavior to be simple and specced, not applying lots of intuitions and special cases.

If you add number prefixes to every file, I believe it should work. Using front matter is also a viable solution. Closing as wontfix.

@a8t If that generator works for you, great; but I'd like to warn you that `label` may not be equivalent to the category's file path. Anyways, enhancing the generator is certainly viable as well.

**Comment by Josh-Cena** [comment]
It's the same reason why we don't filter docs in an autogenerated slice that have already been used as the parent directory's index page (https://github.com/facebook/docusaurus/issues/6127). We'd rather want to makes users be explicit about these docs that they need to filter.

**Comment by Zenahr** [comment]
@

> It's the same reason why we don't filter docs in an autogenerated slice that have already been used as the parent directory's index page (#6127). We'd rather want to makes users be explicit about these docs that they need to filter.

Apologize necroing... is this something that can be done "natively" or would users be required to create their custom `sidebarItemsGenerator` implementation to support this?

with "this" I mean having a default of not showing the `index.md`/`README.md` file in the sidebar and instead have it act as entry upon clicking the category label it lives in.
