### ISSUE TITLE
Categories consisting of a single category doc do not appear in autogenerated sidebar

### ISSUE THREAD

**Issue by duanwilliam** [facebook/docusaurus#6301]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

Suppose we have the following docs structure, with an autogenerated sidebar generated in `docs`

```
docs/
    ├── intro.md
    ├── category/
    │   ├── index.md
    │   └── nested-category/
    │       └── index.md
    ├── other-category/
    │   └── index.md
    └── another-category/
        └── another-nested/
            └── index.md
```

The resultant sidebar does not include any directory which only has a category doc for markdown files, eg in this example
```
[sidebar items]
    ├── intro
    ├── category (category doc)
    │   └── [there's nothing here, the category is empty]
    └── another-category (empty category)
        └── [there's nothing here, the category is empty]
```
![image](https://user-images.githubusercontent.com/38791932/148696612-1a28d2a3-d827-40c2-b310-997baa67aed4.png)

### Steps to reproduce

1. create basic site, eg `npx create-docusaurus@latest my-website` or https://docusaurus.new/
2. make a category doc with only an index doc in it inside an autogenerated slice
3. run the site and observe the sidebar

### Expected behavior

I would expect categories with only an index doc in them to still appear in the sidebar, ideally as regular category items, although empty category category docs, as long as they're at least in the sidebar, would still be workable.

A not uncommon use case that currently doesn't work due to this issue is for nesting each doc in its separate folder to keep all assets related to a given doc next to each other, e.g.

```
docs/
├── installation/
│   ├── index.md
│   ├── asset-1.png
│   └── asset-2.png
└── snippets/
    ├── index.md
    ├── snippet-1.js
    └── snippet-2.js
```

### Actual behavior

The categories with only an index doc do not appear in the sidebar at all.

### Your environment

- Docusaurus version used: `2.0.0-beta.14`

### Reproducible demo

https://stackblitz.com/edit/github-17efxz

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by Josh-Cena** [comment]
@duanwilliam Thanks for reporting these edge cases! Really helpful to help us improve. I'm not even sure how the UX should be designed in this case, maybe fall back to a regular doc instead of a category?

**Comment by duanwilliam** [comment]
that would be my preferred behavior for my personal use case at the very least; while just another user i doubt there is much use for sidebar category docs that are otherwise empty in any case

**Comment by mambax** [comment]
@duanwilliam I came across that today too and @Josh-Cena pointed me here. I have the same use case as you, I want to also group a document and its assets together in one directory but actually use the directory name as slug (without stating the slug explicitly).
The fallback to behave like a doc seems perfect. The doc entry becomes a category entry either when there is more than 1 document in the directory OR when its named differently than the `($directory|index|readme).mdx`.

**Comment by slorber** [comment]
Agree: `/x/index.md`with a single md file in it should lead to a doc, thanks for reporting this

It probably doesn't make sense to create a category + link in this case 🤷‍♂️ this would almost lead to the same UX but the UI would be slightly different

**Comment by duanwilliam** [comment]
hmm would things like sidebar item title from heading also apply for this case then, rather than inferring title from category path (that is, it acts fully as if the category is just a regular doc; this is also the behavior i'd prefer in any case)? and in this case then what would the behavior be if there is also category metadata that assigns conflicting values?
