### ISSUE TITLE
Versions label not rendered in the mobile view mode

### ISSUE THREAD

**Issue by sr-remsha** [facebook/docusaurus#6309]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

Versions labels are not rendered in the mobile view mode. 

### Steps to reproduce

Step 1: Define labels for versions in docusaurus.config.js
Step 2: Open website in the mobile view 
step 3: Click Menu icon in the top nav to see the "versions" text instead of labels. 

### Expected behavior

**Desired state:** I have a custom versions label defined in docusaurus.config.js.  The label title is displayed in the top navigation bar in the desktop browser mode. In the mobile mode, if you click the hamburger menu icon you see the label title.

### Actual behavior

**Current state:** I have a custom versions label defined in docusaurus.config.js.  The label title is displayed in the top navigation bar in the desktop browser mode. In the mobile mode, if you click the hamburger menu icon you see text "versions" instead of custom label title. 

### Your environment

- Public source code:
- Public site URL:
- Docusaurus version used:
- Environment name and version (e.g. Chrome 89, Node.js 16.4):
- Operating system and version (e.g. Ubuntu 20.04.2 LTS):

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by Josh-Cena** [comment]
Hi! Could you give more details? What navbar item type are you using? The `docsVersionDropdown` item will have `versions` as the label, but you can expand it to see all versions.

**Comment by sr-remsha** [comment]
![image](https://user-images.githubusercontent.com/46220620/148778786-8856e958-3363-4c68-9b5c-ea1212327d37.png)

there must be exact titles instead of "versions" text

![image](https://user-images.githubusercontent.com/46220620/148779028-eab6aca0-7608-40f0-8ed1-0370371bdea7.png)

**Comment by Josh-Cena** [comment]
Sorry, you are not showing the relevant part. What's the navbar item type? Are you using a swizzled `DocsVersionDropdown` component and have just upgraded from an old version? You may need to re-swizzle your component, because half a year ago, we have separated `DropdownNavbarItem` from `DefaultNavbarItem`.

**Comment by sr-remsha** [comment]
I am using DocsVersionDropdown without swizzle.

**Comment by Josh-Cena** [comment]
Do you have public site / source code? Last time we saw this, the person swizzled `NavbarItem`. It's impossible for us to further investigate without having anything to look at

**Comment by sr-remsha** [comment]
You may investigate [here](https://kb.timebase.info/)

**Comment by Josh-Cena** [comment]
Your setup is...weird. On desktop, the navbar shows "Enterprise" and "Community" as the links; on mobile, it shows two "Versions". Are "Enterprise" and "Community" two versions of your docs?

**Comment by Josh-Cena** [comment]
Okay, bug located, thanks for reporting! Have to say that this setup is a bit weird...

**Comment by Josh-Cena** [comment]
@sr-remsha Should be fixed in canary version
