### ISSUE TITLE
ValidationError for Copy Webpack Plugin when static folder doesn't exist

### ISSUE THREAD

**Issue by fantasy525** [facebook/docusaurus#6311]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

build error:ValidationError: Invalid options object. Copy Plugin has been initialized using an options object that does not match the API schema.
![image](https://user-images.githubusercontent.com/22516157/148904835-cd84fda9-f285-4f05-87c0-517ace2870e3.png)
CopyWebpackPlugin ,options.patterns should be a non-empty array,but got empty array

### Steps to reproduce

1.setup package.json "`@docusaurus/core": "^2.0.0-beta.14",`
2.docusaurus build

### Expected behavior

build success

### Actual behavior

[ERROR] Unable to build website for locale en.
[ERROR] ValidationError: Invalid options object. Copy Plugin has been initialized using an options object that does not match the API schema.
 - options.patterns should be a non-empty array.

### Your environment

- Public source code:
- Public site URL:
- Docusaurus version used:
- Environment name and version (e.g. Chrome 89, Node.js 16.4):
- Operating system and version (e.g. Ubuntu 20.04.2 LTS):

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by slorber** [comment]
Does it make sense to always require a static folder?

What is the intent to remove it @fantasy525 ? 

Maybe one would want to enforce all assets are co-located? (can be convenient for localizing them?) 🤷‍♂️

**Comment by TimonVS** [comment]
Just ran into the same problem. I don't mind having a `static` folder, but a better error message would be immensely helpful, as it took me at least 30 minutes to debug :)

**Comment by Josh-Cena** [comment]
@TimonVS So you in fact have a site built without a static folder?

@slorber What do you think is a more sensible fix? Giving an error message saying "expected a static folder to exist" or just do not create the copy webpack plugin if there isn't any static folder? Should we validate the existence of all static folders during config validation and mandate using `staticDirectories: []` if user wants none?

**Comment by slorber** [comment]
maybe we don't want the user have to think about this at all, and create missing dirs? 🤷‍♂️ 

https://github.com/jprichardson/node-fs-extra/blob/master/docs/ensureDir.md#ensuredirdiroptionscallback

Those that really don't want any static dir to be created could use `staticDirectories: []`

**Comment by TimonVS** [comment]
@Josh-Cena Yep, it works in dev mode, and it used to work in `2.0.0-beta.9`. In `beta.15` I get an error when building.

**Comment by Josh-Cena** [comment]
This will be fixed in #6725. The command would create an empty `static` directory if it doesn't exist. If you want to disable this directory generation, just use `staticDirectories: []`
