### ISSUE TITLE
Algolia Search duplicating results since 2.0.0-beta.9

### ISSUE THREAD

**Issue by gtnardy** [facebook/docusaurus#6312]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

Hello there, since the update 2.0.0-beta.9 (the one which required to update the Node.js) my search results started to appear duplicated in a weird way.

My docs: [https:://docs.nanos.world](https:://docs.nanos.world)

Example searching for `TranslateTo`:

![Screenshot_45](https://user-images.githubusercontent.com/6226807/148928021-804fc4ee-5081-4bfd-8c69-1e0a1a1b3998.png)

The first item points to the URL: `https://docs.nanos.world/docs/scripting-reference/classes/base-classes/actor#translateto`
The second item points weirdly to a "broken" URL: `https://docs/scripting-reference/classes/base-classes/actor#translateto`

Am I missing any breaking change that modified the way I should create links? Or any new special configuration? Or is it really a bug?

My **sitemap** (seems fine): [https://docs.nanos.world/sitemap.xml](https://docs.nanos.world/sitemap.xml)
My **docusaurus config** can be found at [https://github.com/nanos-world/docs/blob/master/docusaurus.config.js](https://github.com/nanos-world/docs/blob/master/docusaurus.config.js)
My **Algolia config** (copied from Docusaurus): [https://github.com/algolia/docsearch-configs/blob/master/configs/nanos.json](https://github.com/algolia/docsearch-configs/blob/master/configs/nanos.json)

### Steps to reproduce

Use Algolia and create headers with `###`.

### Expected behavior

The search should show only one result.

### Actual behavior

The search shows 2 results, one with a broken link.

### Your environment

- Public source code: [https://github.com/nanos-world/docs/](https://github.com/nanos-world/docs/)
- Public site URL: [https://docs.nanos.world](https://docs.nanos.world)
- Docusaurus version used: **2.0.0-beta.14** 
- Environment name and version (e.g. Chrome 89, Node.js 16.4): **Node.js 16.13.1**
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): **Clean build with both Windows 11 and Ubuntu 20.04**

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by slorber** [comment]
Yes this is strange and unexpected, as if your site's pages were indexed twice with different ids

Algolia DocSearch has a new system and dashboard feature, you should ask them to be granted access to be able to explore your index more easily with a UI and try to figure this out. See also https://docusaurus.io/blog/2021/11/21/algolia-docsearch-migration

Apparently, you are still on the old one and your config is here: https://github.com/algolia/docsearch-configs/blob/master/configs/nanos.json

@shortcuts do you have any idea? It looks like the pages are indexed with 2 different URLs, one have a duplicate slash `//`

![image](https://user-images.githubusercontent.com/749374/149149839-7bd5f788-2c3d-418d-afe7-6e77a6076332.png)

https://docs.nanos.world/docs/core-concepts/scripting/traces-and-raycasting
https://docs.nanos.world//docs/core-concepts/scripting/traces-and-raycasting

The sitemap does not contain such a duplicate URL 🤷‍♂️

**Comment by shortcuts** [comment]
Hey, I'm testing on the new infra (since the `nanos` index have also been migrated, check your emails :D), and can reproduce the same error.

Looking at our monitoring, we can indeed find accessible/crawlable URLs with double slashes, e.g. `https://docs.nanos.world//de/docs/scripting-reference/classes/player`

**Comment by slorber** [comment]
ok that seems related to docusaurus canonical urls bug with `trailingSlash: false`

https://github.com/facebook/docusaurus/issues/6315

Weird that this appears now, wonder what we changed recently leading to this bug 🤷‍♂️

**Comment by shortcuts** [comment]
> Docsearch / Algolia probably still needs a way to deduplicate this page for satefy

Users on the new infra can find a pattern to add to the `exclusionPatterns` parameter of the config. 

Example with `nanos`:
```js
exclusionPatterns: ['https://docs.nanos.world//*/**']
```

Will exclude all URLs with the `//` issue from being crawled.

**Comment by slorber** [comment]
Thanks, we'll fix the bug we have and see if it solves the problem.

It's worth trying to revert the site to beta.9 and see if the canonical URL issue is a recent bug or was there before 🤷‍♂️

**Comment by gtnardy** [comment]
Hello, just an update: I received an e-mail with an crawling errors which asked me to ignore the old one and use the new one, after that the search worked again without duplicating it! Seems a solution came from Algolia itself!


![image](https://user-images.githubusercontent.com/6226807/151563177-86b0c993-f6f8-4920-b938-4f94dcca79e4.png)
