### ISSUE TITLE
Minified React error #152

### ISSUE THREAD

**Issue by oojacoboo** [facebook/docusaurus#6337]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [ ] I have tried the `npm run clear` or `yarn clear` command.
- [ ] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io.
- [ ] I have read the console error message carefully (if applicable).

### Description

Getting the following errors on the latest version, `2.0.0-beta.14`.  I also tested down to `2.0.0-beta.11` and still got the same error.  Reverting to `2.0.0-beta.8` fixed the issue.

```
Docusaurus Node/SSR could not render static page with path "/" because of following error:

Error: Minified React error #152; visit https://reactjs.org/docs/error-decoder.html?invariant=152&args[]=ErrorBoundary for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at ab (main:153365:466)
    at d (main:153368:240)
    at bb (main:153369:16)
    at a.b.render (main:153375:43)
    at a.b.read (main:153374:83)
    at Object.exports.renderToString (main:153385:138)
    at doRender (main:15117:356)
    at async serverEntry_render (main:15116:284)



Error: Server-side rendering fails due to the error above.
Unable to build website for locale "en".

● Client █████████████████████████ cache (99%) shutdown IdleFileCachePlugin
 resolve build dependencies

● Server █████████████████████████ cache (99%) shutdown IdleFileCachePlugin
 resolve build dependencies

Error: Failed to compile with errors.
    at /../node_modules/@docusaurus/core/lib/webpack/utils.js:202:24
    at /../node_modules/webpack/lib/MultiCompiler.js:554:14
    at processQueueWorker (/../node_modules/webpack/lib/MultiCompiler.js:491:6)
    at processTicksAndRejections (internal/process/task_queues.js:75:11)
```

### Steps to reproduce

Using the repo [oojacoboo/graphqlite](https://github.com/oojacoboo/graphqlite/tree/custom-validator), you can clone, and `cd website && yarn install && docusaurus build`

### Expected behavior

No error

### Actual behavior

Error

### Your environment

- Public source code: https://github.com/oojacoboo/graphqlite/tree/custom-validator
- Public site URL:
- Docusaurus version used: 2.0.0-beta.14
- Environment name and version (e.g. Chrome 89, Node.js 16.4): 14.7.0
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): Mac OS 11.5.2

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by slorber** [comment]
should be fixed in https://github.com/facebook/docusaurus/pull/6338
