### ISSUE TITLE
Doc plugin option isCategoryIndex

### ISSUE THREAD

**Issue by Josh-Cena** [facebook/docusaurus#6379]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Description

A user-provided callback to determine if a file should be category index.

### Has this been requested on Canny?

https://docusaurus.canny.io/admin/feedback/feature-requests/p/allow-disabling-globally-the-category-index-link-convention?status=planned

### Motivation

We should be able to let users choose which files to be chosen as category index. This includes:

- Opting out of any (or all) of the three conventions
- Picking another file (e.g. `java/java-intro` as in #6255)

### API design

A new option: `isCategoryIndex` in the doc plugin options. It only receives the file path (should we pass front matter as well?). The default option would be like:

```js
const options = {
  isCategoryIndex({filePath}) {
    const breadCrumbs = filePath.split('/');
    if (breadCrumbs.at(-2) === breadCrumbs.at(-1).replace(/\.mdx?$/, '')) {
      return true;
    }
    return filePath.match(/(index|readme)\.mdx?$/i);
  }
}
```

And the user can be free to implement other ones:

```js
// strip parent folder name
const options = {
  isCategoryIndex({filePath, defaultIsCategoryIndex}) {
    const breadCrumbs = filePath.split('/');
    return defaultIsCategoryIndex(filePath.replace(breadCrumbs.at(-2) + '-', ''));
  }
}
```

```js
// disable convention
const options = {
  isCategoryIndex() {
    return false;
  }
}
```

### Have you tried building it?

Should be easy

### Self-service

- [X] I'd be willing to contribute this feature to Docusaurus myself.

**Comment by slorber** [comment]
👍 that looks fine


Do you think we should pursue injecting default functions? 

I have mixed feelings about this, we could as well expose some node utils in a new plugin public api
