### ISSUE TITLE
Pure HTML sidebar item

### ISSUE THREAD

**Issue by Josh-Cena** [facebook/docusaurus#6389]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Description

Sidebar items shouldn't always be links. We should allow thinks that are purely decorative.

### Has this been requested on Canny?

https://docusaurus.io/feature-requests/p/label-in-sidebar

### Motivation

We have several needs:

- Pure text titles;
- Sidebar dividers;
- Logos;
- Carbon ads?

While we can work around the first with a `collapsible: false` sidebar category, the other three are currently not achievable, and swizzling can be intractable as well. 

### API design

A new sidebar item `type: 'html'` which allows the developer to pass arbitrary HTML code.

```js
module.exports = {
  sidebar: [
    {
      type: 'html',
      value: '<div class="divider" />',
    },
    {
      type: 'html',
      value: '<span class="sidebar-heading">Section title</span>',
    },
  ],
};
```

### Have you tried building it?

No

### Self-service

- [X] I'd be willing to contribute this feature to Docusaurus myself.

**Comment by slorber** [comment]
👍  why not

It could probably be possible by enabling custom sidebar items, but providing raw HTML in the sidebars config can be more convenient
