### ISSUE TITLE
Algolia has changed the way to change the options

### ISSUE THREAD

**Issue by Y-lonelY** [facebook/docusaurus#6390]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Description

After i enable the search with [guide](https://docusaurus.io/docs/search), i found we can't change the index config with pr now, because 

> "This repository hosts configs for the legacy infrastructure of DocSearch. Configs are now automatically created at deploy time when your request have been processed, please check the Zendesk conversation created when you applied to see the status of your request."

And i have to config on the algolia's website, and it's hard to generate the **records**, so maybe a record's data structure or a data-generate tools is highly required~

Have a great day :D

### Self-service

- [ ] I'd be willing to address this documentation request myself.

**Comment by Josh-Cena** [comment]
Thanks for the info. @shortcuts is any docs update necessary?

**Comment by shortcuts** [comment]
Hey, applications are now deployed on the new infra, so we can indeed remove anything related to the legacy infra.

> It works by crawling the content of your website every 24 hours and putting all the content in an Algolia index. This content is then queried directly from your front-end using the Algolia API.

We now schedule a random time in the week but default, but the schedule is configurable from the web interface

> After applying, your site's DocSearch config should be created at:

This is not needed anymore, everything is in the web interface

> This configuration file can be updated by:
> opening a pull-requests in algolia/docsearch-configs
Not needed anymore. The web interface editor, which also allow you to trigger crawls (available at https://crawler.algolia.com/)

> It is highly recommended using a config similar to the Docusaurus 2 website config.

Template is now available here: https://docsearch.algolia.com/docs/templates

I think the rest is related to the frontend, but don't hesitate to DM me on Discord @Josh-Cena so I can help you :D

**Comment by shortcuts** [comment]
> i found we can't change the index config with pr now

For the `indexName` part in this issue, it's basically determined by the project submitted or the domain.

> And i have to config on the algolia's website, and it's hard to generate the records

If you have any issue with the indexing @Y-lonelY please let me know!
