### ISSUE TITLE
uniform anchor link

### ISSUE THREAD

**Issue by bulinc** [facebook/docusaurus#6392]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Description

we need uniform the url#hash( (i.e.https://bulinc.onrender.com/docs/cunhuo#ck20060301hsl014i) to scroll down to anchor id or component id.
in current version(Docusaurus version used:  2.0.0-beta.13),the url#hash is so special. I will explain the defference by the example(https://bulinc.onrender.com/docs/cunhuo),this page made by script and mdx.

in development, the green button  work well ,but anchor links  is no scrolling,this is defferent from uniform webpage feature which made by html and js.

 in production,  the anchor link is working ,and New problems  arise ,which goes on well in development, 
firstly,we visit the sitepage by url#hash( (i.e.https://bulinc.onrender.com/docs/cunhuo#ck20060301hsl014i) ,
secondly,we click other button, the rusult is not as expected because the anchor link as same as the first  operation; but the process work consistent with expectations( copyed the clicked button anchor link) in development or hmtl 、 bootscript.js and the same scripts.

suggest:
1.keep a uniform result in development and production, it is very imporent  to remember："Don't be too special in the implementation of basic functions, which will increase the learning cost of developers"
2.Create unique  component functions，if we can visit the sitepage by "url+special symbol+component id",for example ,(https://bulinc.onrender.com/docs/qykj-zz00) this page 's green button is component,if you click it,you will get the button's url#hash。but the scrolling function cannot be realized in current version.

### Has this been requested on Canny?

https://bulinc.onrender.com

### Motivation

This Feature which visit the website page by  anchor link  is very useful for lawer、 accountant、teacher and everybody who want to studying by mindmap or other Learning tools with hyperlink function。

### API design

no api

### Have you tried building it?

the code : https://github.com/bulinc/bulinc.github.io.git

### Self-service

- [X] I'd be willing to contribute this feature to Docusaurus myself.

**Comment by Josh-Cena** [comment]
Hey, the issue is a bit messy for me to understand. If you think you can explain it more clearly in Chinese, feel free to do so.

About anchor links in development, this is a known issue and we have documented the limitation.

**Comment by Josh-Cena** [comment]
Beware that the path fragment `url#hash` syntax is not a Docusaurus feature. If you want your custom component to be anchored with a hash, you can add an `id` to your component. E.g. `<div id="item-14">xxx</div>` will be directly targetable through the `#item-14` hash.

**Comment by bulinc** [comment]
太好了，我用中文解释下使用需求：
我使用的是 2.0.0-beta.13版本，期望是能够获取页面某条内容的超链接（例如法律文件内容的某个条款），为此，我用编写的Script以及组件两种方法来测试docusaurus中的实现，但结果与目标还有差距，试用结果如下：
1.用script实现的功能页面网址是：https://bulinc.onrender.com/docs/cunhuo ，其中的法律条款为绿色控制，点击可获取该条款的超链接（url#id格式)，这个超链接用于在思维导图等具有超链接功能的学习工具中使用。
在开发模式下，本地页面点击任意绿色控件，可以获取相应的超链接，不过这个超链接在新页面打开时无法滚动至相应条款。
在产品模式下，超链接的滚动功能正常了，上述网址的绿色控件也可以正常获取相应条款的超链接。
但是我们在新页面打开超链接后，再点击其他绿色控件时，无法获取新的超链接，点击的结果仍然是原来的超链接。
上述的script点击获取超链接功能和滚动至具体条款的功能，我用html+bootstrap.js以及相同的script测试的结果是可以正常使用。

2.用组件实现的功能页面网址是：https://bulinc.onrender.com/docs/qykj-zz00 ，点击绿色控件可获取该条款的超链接（url#id格式)，但是docusaurus目前没有提供跳转至某个组件的功能，所以只是实现了点击获取响应组件的超链接功能（目前设计的是url#id格式，这可能与跳转至标题功能一致），如果后续能够提供跳转至具体ID组件功能，建议考虑用其他符号区分。

建议：
1.统一开发模式与产品模式下的超链接功能。最好能够与html的超链接功能保持一致，如果在基础功能上与html标准的实现出现较大差异，这会增加开发人员的学习成本，不利于产品推广。

2.如果希望发挥组件的优势，建议创造跳转至具体组件的超链接新功能。

上述功能的潜在用户群体有：律师、会计师等所有喜欢用思维导图等学习、考试工具做笔记的群体。当超链接运用到学习工具中后，有利于知识整合、记忆、追溯到具体条款，也有助于扩大docusaurus产品的使用领域。

**Comment by Josh-Cena** [comment]
开发模式下，`#hash` 超链接经常不会工作，这个 bug 我们是知道的，但是是因为我们用的 webpack dev server 的问题，我们也没有办法解决；

`url#id` 的格式其实我们自己也有用，比如我们自己的 `APITable` 组件：https://docusaurus.io/docs/api/plugins/@docusaurus/plugin-content-docs#editLocalizedFiles
源码在这里：
https://github.com/facebook/docusaurus/blob/main/website/src/components/APITable/index.tsx#L35-L49

因为我们最终是渲染成一个 React 单页应用，所以如果是外部脚本，不保证能正常获取到 DOM 元素。我注意到你的每一个条款的 ID 都是 `hsl`，要注意，如果你想利用 `url#id` 做跳转，你要保证每个 ID 都是独一无二的。HTML 规范也是这么要求的。这个 `url#id` 跳转到对应元素不是 Docusaurus 的 feature，是你的浏览器自己提供的功能。

**Comment by bulinc** [comment]
在产品模式下，……
但是我们在新页面打开超链接后，再点击其他绿色控件时，无法获取新的超链接，点击的结果仍然是原来的超链接。
……
**（开发模式下，也是可以正常使用的）**

**Comment by Josh-Cena** [comment]
这里有一些资料可以参考：https://en.wikipedia.org/wiki/URI_fragment

> In an HTML web page, the agent will look for an anchor identified with an HTML tag that includes an `id=` or `name=` attribute equal to the fragment identifier.

如果你有两个元素 ID 一样，浏览器一般会定位到第一个元素

**Comment by bulinc** [comment]
您说的第二种实现方式--组件。是先指定了条款组件 ID 的默认值是hsl，然后在mdx内容文件中指定了每个条款的不同值，再用componentDidMount加载，具体可以看我提供的github源码。

您提供的实例对我很有帮助，我再学习下实例的具体实现过程。谢谢你。

**Comment by Josh-Cena** [comment]
如果你要用组件的话，仍然要确保 ID 独一无二。你可以用 children 的文本值作为 ID。

**Comment by Josh-Cena** [comment]
这个 issue 我就先关了，因为：

- 开发模式下 hash link 不能正常使用是已知问题，但很难解决，而且我们已经有其他 issue 追踪这个问题了；
- hash link 本身不是我们提供的功能，标题的 hash link 是一个很简单的实现，实际上还是浏览器的 feature。你可以自己实现组件，只要保证每个 ID 都独一无二即可。我在 Discord 上一直在线，如果有其他问题的话，欢迎在那里找我。
