### ISSUE TITLE
Documentation 中如何按需加载 Ant-Design 组件以及样式

### ISSUE THREAD

**Issue by bolawen** [facebook/docusaurus#6401]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Description

Documentation 中如何按需加载 Ant-Design 组件以及样式

### Self-service

- [ ] I'd be willing to address this documentation request myself.

**Comment by Josh-Cena** [comment]
你好，Docusaurus 是一个 React 单页应用，所以 React 页面的编写方法和其他框架一样。

https://docusaurus.io/zh-CN/docs/creating-pages#add-a-react-page

如果还有问题，请不要用 GitHub 提问。
