### ISSUE TITLE
css-loader 6.5.1 breaks inline images

### ISSUE THREAD

**Issue by sparanoid** [facebook/docusaurus#6408]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

This bug seems to be introduced since this https://github.com/facebook/docusaurus/commit/95955ecfb0f570c194c41ab7be948b79997573f4 commit (canary build 0.0.0-4414).

### Steps to reproduce

See demo: https://stackblitz.com/edit/github-nbaeqd-js3wpw?file=src%2Fcomponents%2FHomepageFeatures.js

First, create a component with CSS inline image:

```css
.demo {
	background-image: url('../../static/img/undraw_docusaurus_tree.svg');
}
```
```html
<div className={styles.demo}>Inspect me</div>
```

Then inspect the element in your browser

### Expected behavior

Inline SVG should be embedded correctly in Base64 format. As how previous versions did.

### Actual behavior

The image is now no longer embedded but generated with a hash filename:

![image](https://user-images.githubusercontent.com/96356/150179679-71a7cf0f-b2c9-414e-883e-a85f95b38175.png)

If you access this file in the browser you will get the following error:

![image](https://user-images.githubusercontent.com/96356/150178902-0d3e655b-d075-4fcb-97ee-c7f61f0069b8.png)

The actual content of this image is:

```js
export default __webpack_public_path__ + "assets/images/undraw_docusaurus_tree-1a17af96e3c13c3b6a5c862c0e13d742.svg";
```

### Your environment

- Public source code: No public repo. Please see the demo above
- Public site URL: N/A
- Docusaurus version used: 0.0.0-4414
- Environment name and version (e.g. Chrome 89, Node.js 16.4): Chrome Version 97.0.4692.71 (Official Build) (arm64). 
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): macOS 12.1 (21C52)

### Reproducible demo

https://stackblitz.com/edit/github-nbaeqd-js3wpw?file=src%2Fcomponents%2FHomepageFeatures.js

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by sparanoid** [comment]
Additonal info: I also find not only svg but also web fonts (and other media) are affected by this bug.

**Comment by slorber** [comment]
let me know if latest canary version works

**Comment by PatelN123** [comment]
Hey @slorber @Josh-Cena,

My issue: [here](https://github.com/facebook/docusaurus/issues/6418) still persists after this update. 
The code and preview is shown here: https://github.com/PatelN123/Digital-Support-Notes/pull/110

Not sure if this is still the same issue?

**Comment by Josh-Cena** [comment]
Your CSS is incorrect. Your background image is too big.

![image](https://user-images.githubusercontent.com/55398995/150523528-e341950b-f265-4865-9128-746b6305f238.png)

If you reduce your image width to 24px through CSS, you can see it displayed correctly.

**Comment by PatelN123** [comment]
Thanks, rookie mistake I guess
