### ISSUE TITLE
hide_table_of_contents string issue

### ISSUE THREAD

**Issue by PatelN123** [facebook/docusaurus#6409]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

![image](https://user-images.githubusercontent.com/79650289/150198791-7f9b3b75-4897-4150-a946-cb8e09f8e9d2.png)

Version: `0.0.0-4443`

It says it should be a string, the documentation says true/false
https://docusaurus.io/docs/next/api/plugins/@docusaurus/plugin-content-docs#:~:text=hide_table_of_contents%3A%20false

### Steps to reproduce

Use hide_table_of_contents on the latest docu canary version

### Expected behavior

Work as any other docu version works. 
Works fine here: https://notes.nayanpatel.net/backdropicons/

### Actual behavior

Logs an error, screenshot has been included

### Your environment

N/A

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by Josh-Cena** [comment]
Ooops, my bad, thanks for reporting this quickly!
