### ISSUE TITLE
Blog archive page is accesible for a site without blog

### ISSUE THREAD

**Issue by chilikasha** [facebook/docusaurus#6412]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [ ] I have tried the `npm run clear` or `yarn clear` command.
- [ ] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io.
- [ ] I have read the console error message carefully (if applicable).

### Description

Hi,
My site had blog enabled some months ago, but then I removed it. Blog folder is empty. Though I mentioned that Archive page is available. Not sure why.

### Steps to reproduce

1. Remove blog from config
2. Remove blog folder contents
3. Open `/blog` page -> "Page not found"
4. Open `/blog/archive`

### Expected behavior

Page not found

### Actual behavior

Archive page opens without any content.

### Your environment

- Docusaurus version used: 2.0.0-beta.14
- Environment name and version (e.g. Chrome 89, Node.js 16.4): node 14.7.6
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): macOS 11.6.2

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by Josh-Cena** [comment]
Hi, it's impossible for me to investigate without a repro. I can only conclude that it's because of cache, or that your hosting provider didn't clean the legacy files. This is, by principle, impossible to be Docusaurus' problem because without the plugin the route can't be generated.

**Comment by chilikasha** [comment]
hi @Josh-Cena , my repo is https://github.com/chilikasha/tinytools (it's public).
I also run `yarn run build` and I see that blog/archive folder is present with index.html file.
<img width="988" alt="Screenshot 2022-02-06 at 19 16 16" src="https://user-images.githubusercontent.com/3147449/152695322-6e697223-9d57-4e02-a1e1-0245589cbdf7.png">

**Comment by chilikasha** [comment]
ok, I think I fixed that by adding `blog: false` in config

**Comment by Josh-Cena** [comment]
Yes, removing the `blog` entry doesn't disable blog, only `blog: false` does

**Comment by slorber** [comment]
Maybe it would be more intuitive if deleting the blog folder just disabled the blog feature automatically? 🤷‍♂️ 

I like the idea of not having to change the default config to disable the blog
