### ISSUE TITLE
v1: algolia search result display issue

### ISSUE THREAD

**Issue by pa-eps** [facebook/docusaurus#6432]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io.
- [ ] I have read the console error message carefully (if applicable).

### Description

I am using Docusaurus v1.14.7. I've been using Algolia DocSearch for awhile now and recently received email about DocSearch being migrated to their new infrastructure. That means I need to update DocSearch configuration for my site. After updating the configuration, I noticed there's an issue with the way search result is being displayed.

I think this bug is from Algolia's new index or their docsearch UI. I'm not sure where to raise this bug. This issue seems to be affecting Docusaurus v1 site also. I expect others might have the same issue.

Here's a screenshot of what the search UI looks like from Docusaurus v1 site:

![image](https://user-images.githubusercontent.com/62254583/150563047-3a43e98d-8b6e-42a3-ac8c-82a137dd2e32.png)

I've highlighted the issue in the screenshot above. It seems the UI is concatenating everything from sidebars. It makes it very hard to understand where the search result is coming from compared to how it was before.

### Steps to reproduce

n/a

### Expected behavior

The search result UI to show results same way as it did before DocSearch migration.

### Actual behavior

Search result UI has a bug. It combines everything from sidebars into the search result's UI instead of only showing the sidebar category where the result was found.

### Your environment

- Public source code: https://github.com/facebook/docusaurus
- Public site URL: https://v1.docusaurus.io/docs/en/site-preparation
- Docusaurus version used: 1.14.7
- Environment name and version (e.g. Chrome 89, Node.js 16.4): Firefox 95.0.2
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): MacOS 12.0.1

### Reproducible demo

https://v1.docusaurus.io/docs/en/site-preparation

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by slorber** [comment]
@shortcuts do you have any why this happens?

**Comment by shortcuts** [comment]
I'd say there's an issue with the `lvl0` selector, we used xPath before but the equivalent might not properly work. Checking

**Comment by shortcuts** [comment]
Hey

I've fixed the `lvl0`, you should see proper results on Docusaurus v1. The doc is also updated: https://github.com/algolia/docsearch/commit/bfde46e140d368dcebb0f424f087a27b2ce7c04f

**Comment by Josh-Cena** [comment]
Thanks! I can see correct output now. Will close this if there are no further problems

**Comment by pa-eps** [comment]
> Hey
> 
> I've fixed the `lvl0`, you should see proper results on Docusaurus v1. The doc is also updated: [algolia/docsearch@bfde46e](https://github.com/algolia/docsearch/commit/bfde46e140d368dcebb0f424f087a27b2ce7c04f)

@shortcuts - Thanks for looking into it and the fix for Docusaurus website. As I mentioned earlier, I manage multiple sites that are based on Docusuaurus V1. How do I get this fixed for my sites? Should I be applying that change through Algolia Crawler configuration myself for each of the sites?

I'm still somewhat new to the whole setup/docsearch-migration. I'd appreciate if you could clarify. Thank you.

**Comment by shortcuts** [comment]
> How do I get this fixed for my sites? Should I be applying that change through Algolia Crawler configuration myself for each of the sites?

Hey, I'm out of office until next Monday so I can't apply changes myself on current Docusaurus v1 crawlers. The fastest would be if you could edit your configs directly from the web interface. 

cc @bodinsamuel

**Comment by pa-eps** [comment]
I was able to make that change. I believe other sites built using Docusuarus V1 will have to do the same.

1. Go to crawler.algolia.com
2. Open the crawler for your site
3. Go into Editor
4. Apply the change according to the one done in Docusaurus' website crawler here https://github.com/algolia/docsearch/commit/bfde46e140d368dcebb0f424f087a27b2ce7c04f
5. Save the configuration and initiate a new crawl by clicking the "Restart crawling"

@shortcuts - When you're back, please let me know if there is anything else I need to do or if I missed anything.
