### ISSUE TITLE
Docs-only mode with versioned multi-instance shows wrong path for latest docs in old version warning

### ISSUE THREAD

**Issue by artanderson** [facebook/docusaurus#6434]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [ ] I have read the console error message carefully (if applicable).

### Description

When using docs-only mode with a second, versioned docs plugin, the latest version path defaults to the routeBasePath of the default docs instance instead of the routeBasePath of the second docs instance. 

### Steps to reproduce

1. Setup site for docs-only mode (docs preset has `routeBasePath: '/'`)
2. Add second docs instance to plugins:
```
[
  '@docusaurus/plugin-content-docs',
  {
    id: 'test',
    path: 'test',
    routeBasePath: '/test',
    sidebarPath: require.resolve('./sidebarsTest.js'),
]
```
3. Run `yarn run docusaurus docs:version:test 1.x.x` to version new instances files
4. Update docs plugin 'test' to read:
```
[
  '@docusaurus/plugin-content-docs',
  {
    id: 'test',
    path: 'test',
    routeBasePath: '/test',
    sidebarPath: require.resolve('./sidebarsTest.js'),
    lastVersion: 'current',
    versions: {
      current: {
        label: '2.0.0',
      }
    }
  }
]
```
5. Add the following to the `navbar -> items`:
```
{
   type: 'docsVersionDropdown',
   docsPluginId: 'test',
},
```
6. Navigate to current versioned document in 'test'
7. Use navbar dropdown to switch to version 1.x.x
8. Warning appears at the top of the page with a link to the latest version (Next)  with a path of '/'

### Expected behavior

The warning at the top of the 1.x.x page should point to latest version (2.0.0) with path '/test'. 

Removing the docs-only mode produces expected results.

### Actual behavior

The warning appears at the top of the page with a link to the latest version (Next)  with a path of '/'

![image](https://user-images.githubusercontent.com/66699571/150592611-72ba9163-155a-470f-a5f2-b70443d67d8e.png)

### Your environment

- Docusaurus version used: 
  - 2.0.0-beta.13
  - 2.0.0-beta.14
- Environment name and version: 
  - Node.js 16.13.1 on local machine, Node.js 14.16.0 on test site
  - Chrome Version 97.0.4692.71 (Official Build) (x86_64) 
  - Safari Version 15.2 (17612.3.6.1.6)
- Operating system and version: 
  - macOS Monterey
  - Stackblitz 

### Reproducible demo

https://stackblitz.com/edit/github-ujptye?file=docusaurus.config.js

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by artanderson** [comment]
One other thing I've noticed on my local setup: if I run `yarn build` with the dev server running, the link will update to the correct path and description, but as soon as the client compiles again, it goes back to the incorrect state.

**Comment by Josh-Cena** [comment]
Thanks for reporting! This is because our route matching is done non-exactly, causing the path `/test/1.x.x` to match the default plugin with path `/`. I think we need to sort the routes here.

**Comment by Josh-Cena** [comment]
Hi! Very detailed bug report. Should be fixed by #6435. Please test with canary version https://docusaurus.io/community/canary

**Comment by artanderson** [comment]
Thanks, will do. Appreciate the quick fix!

**Comment by artanderson** [comment]
Latest canary release is working great, thanks again!
