### ISSUE TITLE
upgrading from 2.0.0-beta.6 to 2.0.0-beta.14 gives TypeError: presetClassic is not a function

### ISSUE THREAD

**Issue by jieru-hu** [facebook/docusaurus#6461]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

first of all, thanks for the wonderful project!

I tried to upgrade my project from beta.6 to beta.14, but I cannot seem to build

here is my [PR](https://github.com/facebookresearch/hydra/pull/1994) 
here is the  failed [netlify deployment](https://app.netlify.com/sites/hydra-preview/deploys/61ef142a64b1c600075d17bf) (linked in the  PR ) 

exceptions both on netlify and my local dev server
```
1:04:49 PM: [INFO] [en] Creating an optimized production build...
1:04:50 PM: [ERROR] Unable to build website for locale en.
1:04:50 PM: [ERROR] TypeError: presetClassic is not a function
1:04:50 PM:     at preset (/opt/build/repo/website/node_modules/docusaurus-plugin-internaldocs-fb/docusaurus-preset.js:24:20)
1:04:50 PM:     at /opt/build/repo/website/node_modules/@docusaurus/core/lib/server/presets/index.js:35:99
1:04:50 PM:     at Array.forEach (<anonymous>)
1:04:50 PM:     at loadPresets (/opt/build/repo/website/node_modules/@docusaurus/core/lib/server/presets/index.js:20:13)
1:04:50 PM:     at loadPluginConfigs (/opt/build/repo/website/node_modules/@docusaurus/core/lib/server/index.js:86:82)
1:04:50 PM:     at load (/opt/build/repo/website/node_modules/@docusaurus/core/lib/server/index.js:206:27)
1:04:50 PM:     at async buildLocale (/opt/build/repo/website/node_modules/@docusaurus/core/lib/commands/build.js:80:19)
1:04:50 PM:     at async tryToBuildLocale (/opt/build/repo/website/node_modules/@docusaurus/core/lib/commands/build.js:33:20)
1:04:50 PM:     at async mapAsyncSequencial (/opt/build/repo/website/node_modules/@docusaurus/utils/lib/index.js:262:24)
1:04:50 PM:     at async build (/opt/build/repo/website/node_modules/@docusaurus/core/lib/commands/build.js:68:25)
1:04:50 PM: error Command failed with exit code 1.
1:04:50 PM: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

in case it matters

```
$ node --version
v16.13.2
$ yarn --version
1.12.1

```

### Steps to reproduce

run `yarn build`

### Expected behavior

it should build

### Actual behavior

exceptions, cannot build

### Your environment

- Public source code: https://github.com/facebookresearch/hydra
- Public site URL: https://hydra.cc
- Docusaurus version used:  2.0.0-beta.14
- Environment name and version (e.g. Chrome 89, Node.js 16.4):
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): MAC OS Big Sur

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by Josh-Cena** [comment]
Hi! The problem is with `docusaurus-plugin-internaldocs-fb`. This plugin was made in the time when `preset-classic` was still in JS instead of TS, and when we migrated to TS, the way to import this preset has changed as well: from `require('@docusaurus/preset-classic')` to `__importDefault(require('@docusaurus/preset-classic'))`. Since it seems they are already distributing a transpiled code, fixing this would just need them to build their code again, test against the latest version, and re-publish. Could you get in touch with them?

For the time being, the best you can do is use [`patch-package`](https://www.npmjs.com/package/patch-package) to fix this package.

**Comment by jieru-hu** [comment]
thank you @Josh-Cena  for pointing out the issues. I ended up upgrading the internal plugin and the error has gone away!

**Comment by Josh-Cena** [comment]
Oh, great!
