### ISSUE TITLE
http://localhost:3000/boilerplate-doc/ not available

### ISSUE THREAD

**Issue by cod3rshotout** [facebook/docusaurus#6467]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [ ] I have tried the `npm run clear` or `yarn clear` command.
- [ ] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io.
- [ ] I have read the console error message carefully (if applicable).

### Description

I'm trying to run this site on my local pc:

https://gitlab.com/pages/docusaurus

but for some reason it show page not available.

This is my windows 11 file host:

127.0.0.1   localhost
255.255.255.255 broadcasthost
::1 localhost
fe80::1%lo0 localhost

### Steps to reproduce

Just clone this repo: https://gitlab.com/pages/docusaurus
run docker-compose up --build -d on windows
and then go to the url displayed in the log

### Expected behavior

The site must be available in the specified url

### Actual behavior

Page not load

![Immagine 2022-01-25 173005](https://user-images.githubusercontent.com/72454584/151018159-2332bed3-ed4c-4fab-b357-5f563eeddaf8.jpg)

### Your environment

- Public source code:
- Public site URL:
- Docusaurus version used:
- Environment name and version (e.g. Chrome 89, Node.js 16.4):
- Operating system and version (e.g. Ubuntu 20.04.2 LTS):

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by Josh-Cena** [comment]
Hey, your docker-compose file seems weird. It probably was not updated along the D2 migration. The mentions of `sidebars.json` and `siteConfig.js` are clearly pointing to the v1 files: https://gitlab.com/pages/docusaurus/-/blob/master/docker-compose.yml#L16-17

You can try `cd website && yarn start` to see if the Docusaurus service itself is able to run. I suspect the Docker app didn't even start successfully. In any case, this is certainly not a Docusaurus bug. Please don't use the GitHub issue tracker as a support forum.
