### ISSUE TITLE
Design of new sidebar is not aligned with rest of page

### ISSUE THREAD

**Issue by balloob** [facebook/Docusaurus#647]
### Is this a bug report?

Maybe?

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

### Environment

1.0.15

### Steps to Reproduce

Run Docusaurus 1.0.15

### Expected Behavior

Align the nav sidebar with the other elements on that line on the page.

Here is a quick mockup by adding `padding-top: 12px` to `.navGroups` when `min-width(736px)`

![screen shot 2018-05-07 at 9 40 35 am](https://user-images.githubusercontent.com/1444314/39704939-eb7f44c6-51da-11e8-8675-e9d8930a0b61.png)

### Actual Behavior

The new sidebar is not aligned with the title of the page, edit button and in-page nav.

![screen shot 2018-05-07 at 9 36 42 am](https://user-images.githubusercontent.com/1444314/39704879-c45e1ade-51da-11e8-8ae2-1d1944e1be7d.png)

### Reproducible Demo

See https://docusaurus.io/docs/en/installation.html

**Comment by ahmadalfy** [comment]
@yangshun I reverted my commits that affected the layout and it had no effect. Not sure what caused that.

**Comment by yangshun** [comment]
@ahmadalfy It's my changes that caused it. I can fix it today. If you would like to fix it instead please go ahead.

**Comment by ahmadalfy** [comment]
Yup, that's quite simple. Let me take care of that

**Comment by ahmadalfy** [comment]
@balloob check [here](https://deploy-preview-650--docusaurus-preview.netlify.com/docs/en/installation.html). I increased the space above.

**Comment by yangshun** [comment]
Closed by #650
