### ISSUE TITLE
Switching to 'Dark Mode' by itself when window.print() is called on Chrome

### ISSUE THREAD

**Issue by DogaGencerOSF** [facebook/docusaurus#6479]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

I'm using window.print() to print preview the docs I created. While doing tests, I noticed that when print preview is opened either with window.print() or ctrl+p, the docusaurus site is switched to the dark mode by itself in Chrome browser. I tested it on two different computers and the result is the same. The storage `theme` value remains in `light` but for some reason the site goes dark mode. 

This only happens if your system wide dark mode setting is on.

### Steps to reproduce

1. Turn OS dark mode setting on
2. Get into any docusaurus site (https://docusaurus.io/showcase) with Chrome browser
3. Press ctrl+p or write window.print() in console

### Expected behavior

The theme of the site should not change.

### Actual behavior

The theme of the site goes dark mode if it were set light to mode.

### Your environment

- Public source code:
- Public site URL:
- Docusaurus version used: 2.0.0-beta.15
- Environment name and version: Chrome: Version 97.0.4692.99, Node: 16.13.1
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): Windows 10 & Windows 11

### Reproducible demo

https://codesandbox.io/s/gifted-brahmagupta-juslb?file=/docs/intro.mdx

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by DogaGencerOSF** [comment]
here is my workaround for now if it helps with the development process: https://gist.github.com/DogaGencerOSF/2b70373a8ee10727e5e5ec2a881f5646

**Comment by Josh-Cena** [comment]
I'm still totally clueless whether we are doing something wrong or if this is browser behavior... Looks like Safari has the same behavior as well

**Comment by slorber** [comment]
I guess it's like opening the site in a new browser session, with localStorage empty 🤷‍♂️ 

Maybe we could add an option, or always force light mode in print?

Is there a use case for printing in dark mode?

**Comment by Josh-Cena** [comment]
> Is there a use case for printing in dark mode?

The problem _is_ that it forces you to print in dark mode, which sometimes messes things up because of incompatible colors.

The hypothesis about empty local storage makes a lot of sense. I think we should try to preserve the color mode when printing though, if that's ever possible.

@slorber You can try on different browsers: on Chrome, pressing <kbd>⌘</kbd> + <kbd>P</kbd> immediately changes the color to dark, but on Safari, the page stays light until you close the print popup. Bit unexpected.
