### ISSUE TITLE
"Edit doc" should more seamlessly integrate with translations

### ISSUE THREAD

**Issue by SimenB** [facebook/docusaurus#648]
### Is this a bug report?

No, feature request

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yup

### Environment

`docusaurus@1.0.14`, the rest N/A

### Steps to Reproduce

(Write your steps here:)

1. Have a translation on Crowdin
2. Open the translation in the app
3. Hit "Edit"

### Expected Behavior

The document should be opened up in Crowdin in the currently selected language so the user can edit it

### Actual Behavior

The English version (or whatever default language the website is in) of the doc is opened on GitHub

### Reproducible Demo

See e.g. Jest: https://facebook.github.io/jest/docs/es-ES/using-matchers.html

**Comment by slorber** [comment]
this is something we'll try to improve in v2 with https://github.com/facebook/docusaurus/issues/3152

**Comment by slorber** [comment]
we'll solve this only for v2, so let's close it as duplicate

**Comment by slorber** [comment]
Actually i think it's already supported in v1, as seen in ReasonML site: https://reasonml.github.io/docs/fr/what-and-why

**Comment by slorber** [comment]
For v2: https://github.com/facebook/docusaurus/pull/4121
