### ISSUE TITLE
Allow preset to nullify theme-provided components overriden by preset plugins

### ISSUE THREAD

**Issue by reutenkoivan** [facebook/docusaurus#6488]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [ ] I have tried the `npm run clear` or `yarn clear` command.
- [ ] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io.
- [ ] I have read the console error message carefully (if applicable).

### Description

If you are using "theme" parameter instead of "preset" it's not possible to include custom UI components registered by "getThemePath" method from plugins.

### Steps to reproduce

1. [clone this repository](https://github.com/reutenkoivan/docusaurus-bug-report.-loadPluginConfigs-priority)
2. `cd website`
3. `yarn`
4. `yarn build`
5. `yarn serve`
6. open [http://localhost:3000/](http://localhost:3000/)
7. You don't see search input

### Expected behavior

1. go to `<root>/website/node_modules/@docusaurus/core/lib/server/index.js`
2. change `return` from _**loadPluginConfigs**_ to 
```
return [
        ...presetThemes,
        ...presetPlugins,
        ...standaloneThemes,
        ...standalonePlugins,
    ]
 ```
3. `yarn build`
4. `yarn serve`
5. now you can see search input

### Actual behavior

it happening because in [this line](https://github.com/facebook/docusaurus/blob/main/packages/docusaurus/src/server/themes/index.ts#L33) alias from plugin overriding by alias from theme-classic.

```
// themePaths ==== [
//   '@docusaurus/core/lib/client/theme-fallback',
//   '@easyops-cn/docusaurus-search-local/dist/client/client/theme',
//   '@docusaurus/theme-classic/lib-next/theme'
// ]
```

```
// returns from "loadThemeAliases"
// {
// --- other aliases---
//   '@theme/SearchBar/EmptyTemplate': '@easyops-cn/docusaurus-search-local/dist/client/client/theme/SearchBar/EmptyTemplate.js',
//   '@theme/SearchBar/SearchBar': '@easyops-cn/docusaurus-search-local/dist/client/client/theme/SearchBar/SearchBar.jsx',
//   '@theme/SearchBar/SuggestionTemplate': '@easyops-cn/docusaurus-search-local/dist/client/client/theme/SearchBar/SuggestionTemplate.js',
//   '@theme/SearchBar/__mocks__/icons': '@easyops-cn/docusaurus-search-local/dist/client/client/theme/SearchBar/__mocks__/icons.js',
//   '@theme/SearchBar/fetchIndexes': '@easyops-cn/docusaurus-search-local/dist/client/client/theme/SearchBar/fetchIndexes.js',
//   '@theme/SearchBar/icons': '@easyops-cn/docusaurus-search-local/dist/client/client/theme/SearchBar/icons.js',
//   '@theme/SearchBar': '@docusaurus/theme-classic/lib-next/theme/SearchBar.js',  <--- Wrong alias
// --- other aliases---
// }
```

### Your environment

- Public source code:
- Public site URL:
- Docusaurus version used: 2.0.0-beta.15
- Environment name and version (e.g. Chrome 89, Node.js 16.4):
- Operating system and version (e.g. Ubuntu 20.04.2 LTS):

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by Josh-Cena** [comment]
Hey, this is surprising, but working as intended. We want plugin default themes to be overridable by external themes, so the best we can do is always give themes a higher precedence than plugins. If you want to provide themes in your plugin, don't bundle it in your preset with a theme you are trying to override.

I do think something can be done here, for example, the ability for a preset to nullify part of the theme a plugin provides—but of course, we will not tweak the theme loading order. This has already been documented/specced.

**Comment by slorber** [comment]
@weareoutman I suggest you present your Docusaurus search plugin as a theme instead of a plugin.

We have `docusaurus-theme-search-algolia`, and your plugin is similar so it would be better to do the same.

@reutenkoivan this should work


```js
  plugins: [
    [
      '@docusaurus/plugin-content-docs',
      {
        path: path.join(__dirname, 'docs'),
        routeBasePath: '/'
      },
    ],
  ],
  themes: [
    ['@docusaurus/theme-classic', {customCss: [require.resolve('./src/css/custom.css')]}],
    '@easyops-cn/docusaurus-search-local',
  ],
```

**Comment by weareoutman** [comment]
@slorber Thanks and I just updated our docs about using it as a theme.

**Comment by slorber** [comment]
Thanks 👍  I guess we can close now, unless someone reports another use-case

**Comment by kaushal0107** [comment]
@weareoutman Thanks for the Theme.
I configured it on my Docusaurus  setup from https://github.com/easyops-cn/docusaurus-search-local . 
But after Building I'm getting following error.
`search-index.json`
there is no such thing mentioned in the steps.
Please guide.

**Comment by srafaela** [comment]
> [@weareoutman](https://github.com/weareoutman) Thanks for the Theme. I configured it on my Docusaurus setup from https://github.com/easyops-cn/docusaurus-search-local . But after Building I'm getting following error. `search-index.json not found` there is no such thing mentioned in the steps. Please guide.

Did you ever find a solution for this?
