### ISSUE TITLE
Footer logo height and width not being set when href not present

### ISSUE THREAD

**Issue by kgajera** [facebook/docusaurus#6503]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [ ] I have tried the `npm run clear` or `yarn clear` command.
- [ ] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io.
- [ ] I have read the console error message carefully (if applicable).

### Description

The `height` and `width` props are not being set on the `FooterLogo` here: https://github.com/facebook/docusaurus/blob/main/packages/docusaurus-theme-classic/src/theme/Footer/index.tsx#L182

### Steps to reproduce

Can be reproduced with the following configuration:
```
footer: {
  logo: {
    alt: "Logo",
    src: "img/logo.png",
    height: 50,
    width: 50,
  }
}
```

### Expected behavior

Should use configured height and width even when the footer logo is not a link.

### Actual behavior

The `height` and `width` props are not being set on the `FooterLogo` here: https://github.com/facebook/docusaurus/blob/main/packages/docusaurus-theme-classic/src/theme/Footer/index.tsx#L182

### Your environment

- Public source code:
- Public site URL:
- Docusaurus version used: 2.0.0-beta.15
- Environment name and version (e.g. Chrome 89, Node.js 16.4):
- Operating system and version (e.g. Ubuntu 20.04.2 LTS):

### Self-service

- [X] I'd be willing to fix this bug myself.

**Comment by Josh-Cena** [comment]
Sure! PR welcome 👍
