### ISSUE TITLE
SimpleLinks component missing unique "key" prop error

### ISSUE THREAD

**Issue by kgajera** [facebook/docusaurus#6509]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [ ] I have tried the `npm run clear` or `yarn clear` command.
- [ ] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io.
- [ ] I have read the console error message carefully (if applicable).

### Description

Using the following footer configuration:
```      
footer: {
  links: [
    {  label: "Link 1", href: "https://example.com/1" },
    {  label: "Link 2", href: "https://example.com/2" },
  ]
}
```

Results in this error:

<img width="814" alt="Screen Shot 2022-01-29 at 10 49 17 AM" src="https://user-images.githubusercontent.com/1087679/151669334-451908d4-3099-4025-8c91-599af9ec9448.png">

The `key` prop should be set on the fragment: https://github.com/kgajera/docusaurus/blob/main/packages/docusaurus-theme-classic/src/theme/Footer/index.tsx#L109

### Steps to reproduce

https://codesandbox.io/s/async-fire-9ps36

### Expected behavior

No error

### Actual behavior

Error in browser console:
```
react.development.js?1b7e:220 Warning: Each child in a list should have a unique "key" prop.

Check the render method of `SimpleLinks`.
```

### Your environment

- Public source code:
- Public site URL:
- Docusaurus version used: 2.0.0-beta.15
- Environment name and version (e.g. Chrome 89, Node.js 16.4):
- Operating system and version (e.g. Ubuntu 20.04.2 LTS):

### Reproducible demo

https://codesandbox.io/s/async-fire-9ps36

### Self-service

- [X] I'd be willing to fix this bug myself.

**Comment by Josh-Cena** [comment]
PR welcome👍 Good catch
