### ISSUE TITLE
Blog sidebar is missing

### ISSUE THREAD

**Issue by yangshun** [facebook/Docusaurus#651]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines on issues]
Yes

### Environment

Chrome

### Steps to Reproduce

1. Load https://docusaurus.io/blog/

### Expected Behavior

See sidebar

### Actual Behavior

Sidebar is missing

### Reproducible Demo

Visit https://docusaurus.io/blog/

This broke in #646. @ahmadalfy would you be available to have a look?

**Comment by ahmadalfy** [comment]
Sure, apologies for that

**Comment by yangshun** [comment]
Not a problem, it hasn't been released to users, so it's all good. Thanks for the quick response!

**Comment by ahmadalfy** [comment]
When I reverted the change, I still see the same view. 

Just to confirm, this isn't the sidebar you are talking about right?

https://imgur.com/a/SBJYA0j

**Comment by ahmadalfy** [comment]
OK I found it, I wasn't seeing it because I thought it is deployed. Will fix that
