### ISSUE TITLE
Feeds are not generated

### ISSUE THREAD

**Issue by JanCizmar** [facebook/docusaurus#6523]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [ ] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

Right after I bootstrap project with 
```
npx create-docusaurus@latest
```
And run it or build it. It has links to feeds in the `<head>`. But when I access those I am getting "Not Found" message.

### Steps to reproduce

1. Bootstrap new docusarus project with 
```
npx create-docusaurus@latest docu-rss classic
```
2. Run it with `npm run start`
3. Inspect your DOM. Notice the links in head element
```
<link rel="alternate" type="application/atom+xml" href="/blog/atom.xml" title="My Site Atom Feed">
<link rel="alternate" type="application/rss+xml" href="/blog/rss.xml" title="My Site RSS Feed">
```
4. Go to https://localhost:3000/blog/rss.xml
5. See "Not found" message

### Expected behavior

The feeds are generated and accessible.

### Actual behavior

It shows "Not found" message even on Docusaurus production. "https://docusaurus.io/blog/rss.xm"

### Your environment

- Docusaurus version used: 2.0.0-beta.15

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by Josh-Cena** [comment]
Hi! It's showing on the Docusaurus site: https://docusaurus.io/blog/rss.xml

For your particular error, remember that the feeds are only generated in production: https://docusaurus.io/docs/api/plugins/@docusaurus/plugin-content-blog
