### ISSUE TITLE
reportError - node_modules/jest-worker

### ISSUE THREAD

**Issue by rafaelrdealmeida** [facebook/docusaurus#6533]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

Hi,

when building docusaurus 2.0.0-beta.15

I'm getting the following error:

```js
node:internal/event_target:777
  process.nextTick(() => { throw err; });
                           ^

DataCloneError: [object Object] could not be cloned.
    at reportError (/workspace/labri/website/node_modules/jest-worker/build/workers/threadChild.js:90:32)
    at reportClientError (/workspace/labri/website/node_modules/jest-worker/build/workers/threadChild.js:74:10)
Emitted 'error' event on Worker instance at:
    at Worker.[kOnErrorMessage] (node:internal/worker:289:10)
    at Worker.[kOnMessage] (node:internal/worker:300:37)
    at MessagePort.<anonymous> (node:internal/worker:201:57)
    at MessagePort.[nodejs.internal.kHybridDispatch] (node:internal/event_target:562:20)
    at MessagePort.exports.emitMessage (node:internal/per_context/messageport:23:28)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

any idea what is happening?

cheers

### Steps to reproduce

1. fork: https://gitlab.com/unesp-labri/sites/labri/-/tree/main
2.  cd website
3. yarn install
4. yarn run build

### Expected behavior

build do docusaurus 2.0.0-beta.15

### Actual behavior

![Captura de tela de 2022-02-01 15-38-32](https://user-images.githubusercontent.com/18035347/152031133-c8924501-18f6-4cf3-bb87-a5c4168108c4.png)

### Your environment

- Public source code: https://gitlab.com/unesp-labri/sites/labri/-/tree/main
- Public site URL: https://labriunesp.org/
- Docusaurus version used: 2.0.0-beta.15
- Environment name and version (e.g. Chrome 89, Node.js 16.4): Node.js 16.4
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): Ubuntu 20.04

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by Josh-Cena** [comment]
Hi! This error is coming from the mini CSS extract plugin. Your CSS contains invalid syntax—this line should be commented: https://gitlab.com/unesp-labri/sites/labri/-/blob/main/website/src/css/custom.css#L1. Commenting this line fixes the error.

Note also that you need to fix the breaking change: `import useTOCHighlight from '@theme/hooks/useTOCHighlight';` has been moved to `import {useTOCHighlight} from '@docusaurus/theme-common';` in beta.15. You may also want to note that the mini CSS extract plugin is still warning about invalid CSS syntax, which you have to fix yourself.

**Comment by Josh-Cena** [comment]
Also, you have two duplicate `plugins` fields: https://gitlab.com/unesp-labri/sites/labri/-/blob/main/website/docusaurus.config.js#L3 and https://gitlab.com/unesp-labri/sites/labri/-/blob/main/website/docusaurus.config.js#L147 which means the first one is overwritten. This causes the sass plugin to not be loaded at all.

**Comment by rafaelrdealmeida** [comment]
Hi @Josh-Cena, thanks for the feedback!

build the beta.15 works. But the `.md `files are not accessible. For example the page:

`https://labriunesp.org/docs/projetos/dados/diariosbr/intro`

displays the message:

```
This page crashed.
Failed to execute 'querySelectorAll' on 'Document': The provided selector is empty.


```
![Captura de tela de 2022-02-02 22-45-39](https://user-images.githubusercontent.com/18035347/152267806-a6cf978e-ce6c-41e0-9952-b7936fe3adbc.png)

 https://labriunesp.org/__docusaurus/debug

any idea what happens?

cheers

**Comment by Josh-Cena** [comment]
@rafaelrdealmeida I have noticed lots and lots of errors in your website. I suggest you actually read our docs, apply some React knowledge, and try to fix them. For example, in your `src/pages/index.js`, you have a `<head>` tag in the body, which is obviously not allowed. You have to use [`@docusaurus/Head`](https://docusaurus.io/docs/next/docusaurus-core#head).

For your error, it's because you didn't update your swizzled component. The `TOC` theme component now accepts an object instead of three parameters. See https://github.com/facebook/docusaurus/blob/main/packages/docusaurus-theme-common/src/utils/useTOCHighlight.ts. Next time, please ask in the Discord server. It's hard to track questions on GitHub.

**Comment by rafaelrdealmeida** [comment]
@Josh-Cena  thanks for the hints and help. I tweaked it and it worked!
