### ISSUE TITLE
docSidebar item is missing from config validation

### ISSUE THREAD

**Issue by homotechsual** [facebook/docusaurus#6597]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

It's not possible to use the `docSidebar` dropdown item as it fails validation.

### Steps to reproduce

Add the following JSON to your config (replacing the `sidebarId` as appropriate.

```json
{
  type: 'docSideBar',
  sidebarId: 'userSidebar',
  label: 'User',
  docsPluginId: 'default',
},
```

### Expected behavior

The config validates and works.

### Actual behavior

> [ERROR] ValidationError: Bad navbar item type docSideBar

### Your environment

- Public source code: N/A
- Public site URL: N/A
- Docusaurus version used: 2.0.0-beta15
- Environment name and version (e.g. Chrome 89, Node.js 16.4): NodeJS 17 (current) Edge (current)
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): Windows 11

### Reproducible demo

https://codesandbox.io/s/happy-hertz-9r5od

### Self-service

- [X] I'd be willing to fix this bug myself.

**Comment by homotechsual** [comment]
I can see docSidebar here: https://github.com/facebook/docusaurus/blob/aa446b7a9c0076e848708e9ea71b8c2e26698be0/packages/docusaurus-theme-classic/src/validateThemeConfig.ts#L89

I _think_ it's as simple as adding:

```ts
{
  is: itemWithType('docSidebar'),
  then: DocSidebarNavbarItemSchema,
},
```

```ts
const DropdownSubitemSchema = Joi.object({
  position: Joi.forbidden(),
}).when('.', {
  switch: [
    {
      is: itemWithType('docsVersion'),
      then: DocsVersionNavbarItemSchema,
    },
    {
      is: itemWithType('doc'),
      then: DocItemSchema,
    },
    {
      is: itemWithType(undefined),
      then: DefaultNavbarItemSchema,
    },
    {
      is: Joi.alternatives().try(
        itemWithType('dropdown'),
        itemWithType('docsVersionDropdown'),
        itemWithType('localeDropdown'),
        itemWithType('search'),
      ),
      then: Joi.forbidden().messages({
        'any.unknown': 'Nested dropdowns are not allowed',
      }),
    },
  ],
  otherwise: Joi.forbidden().messages({
    'any.unknown': 'Bad navbar item type {.type}',
  }),
});
```

**Comment by unavailable-name** [comment]
Can confirm, I also get this bug when trying to use a `docSidebar` in a `dropdown`

**Comment by slorber** [comment]
agree, this is a missing validation just for the dropdown

**Comment by slorber** [comment]
Do you want to send a PR or I fix it?

**Comment by homotechsual** [comment]
I'll send a PR - thanks for the confirmation :-)
