### ISSUE TITLE
Production build fails after upgrading from alpha to beta.15

### ISSUE THREAD

**Issue by AndreasGassmann** [facebook/docusaurus#6606]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

I updated Docusaurus from `2.0.0-alpha.72` to `2.0.0-beta.15`. Now, the production build fails and does not give any meaningful error message. The output is the following:

```
[INFO] [en] Creating an optimized production build...

✔ Client
  

● Server █████████████████████████ sealing (92%) asset processing 
 static-site-generator-webpack-plugin
 
 # Some console logs from one of our own components
 
 [ERROR] undefined
```

The pipeline can be checked here: https://github.com/airgap-it/airgap-docs/runs/5067750988?check_suite_focus=true

I am expecting that we have a problem in our project, but I would expect an error message to be shown. I also did not find a way to enable debug or verbose mode to pinpoint the source of the error.

I also tried with `--no-minify`, but the error stays the same.

### Steps to reproduce

1. Check out https://github.com/airgap-it/airgap-docs/pull/30
2. Do `npm install`
3. Do `npm run build`

### Expected behavior

The build should work, or an error message should be displayed.

### Actual behavior

The build fails and no error message is displayed.

### Your environment

- Public source code: https://github.com/airgap-it/airgap-docs/
- Public site URL: https://support.airgap.it
- Docusaurus version used: `2.0.0-beta.15`
- Environment name and version (e.g. Chrome 89, Node.js 16.4): Brave Version 1.34.80 Chromium: 97.0.4692.71 (Official Build) (arm64) / Node v16.13.0
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): MacOS Monterey, 12.0.1

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by Josh-Cena** [comment]
@AndreasGassmann Yes, we should provide better errors... Your error is `No secure random number generator found`, and it's not properly logged because this error is thrown as a string, not an error. If this is a package you control, I suggest you to throw an error instead.

**Comment by Josh-Cena** [comment]
At this stage, it doesn't look Docusaurus-related. Note that as you upgrade to beta, we have upgraded Webpack to v5, which doesn't polyfill Node modules including `crypto`, which may lead to your error.

**Comment by AndreasGassmann** [comment]
> At this stage, it doesn't look Docusaurus-related. Note that as you upgrade to beta, we have upgraded Webpack to v5, which doesn't polyfill Node modules including crypto, which may lead to your error.

Yes I think that's the issue and I'm trying to do that right now.

> Yes, we should provide better errors... Your error is No secure random number generator found, and it's not properly logged because this error is thrown as a string, not an error. If this is a package you control, I suggest you to throw an error instead.

How did you get that error message? Is there a flag somewhere to enable debug / verbose logs?

Thanks for your help so far, I think we can close this issue. It was more about a way to get more infos out of errors, not about the error itself.

**Comment by Josh-Cena** [comment]
Oh, I hacked `node_modules` and applied the changes in #6607 😆

Sure, I'll close. If you have more problems in your migration, you can either ask in our Discord server, or in GitHub discussions.
