### ISSUE TITLE
 Docusaurus Node/SSR could not render static page with path /blog/tags/JavaScript because of following error

### ISSUE THREAD

**Issue by 1084350607** [facebook/docusaurus#6608]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [x] I have tried the `npm run clear` or `yarn clear` command.
- [x] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io.
- [x] I have read the console error message carefully (if applicable).

### Description

It's normal when I use `npm run start`, but some errors occurred when I use 'npm run build':

Error here:

[ERROR] Docusaurus Node/SSR could not render static page with path /blog/tags/前端 because of following error:
ReferenceError: theme is not defined

### Steps to reproduce

clone project from 'https://github.com/1084350607/blog'

1. npm run build

### Expected behavior

build normally

### Actual behavior

build error

### Your environment

- Public source code: https://github.com/1084350607/blog
- Public site URL: www.siyuanwa.cn
- Docusaurus version used: 2.0.0-beat-15
- Environment name and version (e.g. Chrome 89, Node.js 16.4):  16.4
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): windows 10

### Self-service

- [x] I'd be willing to fix this bug myself.

**Comment by Josh-Cena** [comment]
Your swizzled component contains a bad line: https://github.com/1084350607/blog/blob/main/src/theme/BlogPostItem/index.tsx#L85

You deliberately `ts-ignore`d it, hence the silent error 😅 Replace that with `const { isDarkTheme } = useColorMode()`: https://docusaurus.io/docs/next/api/themes/configuration#use-color-mode

Please don't use the GitHub issue tracker as a support forum. It's very distracting and pollutes our repo history. Prefer any of our support channels (I'm always around on Discord)

**Comment by 1084350607** [comment]
Thanks so much!!
