### ISSUE TITLE
Show onPageNav on mobile devices

### ISSUE THREAD

**Issue by SleepWalker** [facebook/Docusaurus#662]
### Is this a bug report?

No

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

### Environment

-

### Steps to Reproduce

-

### Expected Behavior

The problem is, that when you are opening docs from mobile device it is very hard to navigate the document, because there is no ToC navigation at all.

I would like to suggest adding a control to toggle onPageNav in a way, which is already done for sidebar nav. We could place another icon in the `.docsNavContainer`  (on the right side), which will expand current page ToC, when pressed.

I can implement this feature, but I need to know, that this feature will be accepted, so that my time won't be wasted.

**Comment by yangshun** [comment]
Yes, it would a nice addition. Feel free to submit a PR for it.

**Comment by endiliey** [comment]
@SleepWalker are you going to work on this ?

**Comment by SleepWalker** [comment]
Yep, but I'm really busy this week :(

**Comment by endiliey** [comment]
I'll label it as claimed & check back on you next week, Would that be okay for you ?

**Comment by endiliey** [comment]
@SleepWalker I'll label it as claimed & check back with you next week, Would that be okay for you ? You can let me know if you have preferred timeline

**Comment by SleepWalker** [comment]
@endiliey that's okay

**Comment by SleepWalker** [comment]
@endiliey Here are some updates from me:

### ToC Hidden

![toc-hidden](https://user-images.githubusercontent.com/2536916/40998861-b80bb75c-6911-11e8-8ca2-0df4d8a1cda8.png)

### ToC Shown

![toc-shown](https://user-images.githubusercontent.com/2536916/40999432-85b2ac46-6913-11e8-895f-8987c983bfb7.png)

### Next steps

1. What do you think about an icon? Is it ok? If so, I can improve the 'close' state and draw the 'x' sign from dots, instead of '/'

2. I want to add ToC for tablets too. But there is no place for icons (like it was in `.navBreadcrumb` on mobile layout). What do you think about adding a sticky 'dock toggle button' like in atom?

![image](https://user-images.githubusercontent.com/2536916/40999100-91d6c968-6912-11e8-9080-4cd4a18dd344.png)

We can show ToC (onPageNav) and dock toggler on the left side by default on tablets. When you are clicking on left dock toggler, we will show sidebar (nav) and another one dock toggler on the right side, so that only one nav (sidebar nav or onPageNav) will be active at the same time.

There is also an alternative solution to use something like tabs, that will switch between ToC and nav

**Comment by endiliey** [comment]
@sleepwalker Wow, nice work.
The icon looks great to me, i am not an UI expert so I'll leave it to the expert @yangshun.

Do you have a mockup for 2nd?

I think it will be great to send a PR so we can play around with it & give feedback.
Anyway, thank you for the amazing work 😄

**Comment by SleepWalker** [comment]
For tablets I've decided to show onPageNav by default, but hide sideNav and leave the top bar with breadcrumbs from mobile:

![toc-ipad](https://user-images.githubusercontent.com/2536916/41059789-41d81380-69d6-11e8-8112-600edabdd073.png)

I'll submit PR soon
