### ISSUE TITLE
[bug] scroll-behavior: smooth not working together with TOC anchor nav in 2.0.0-beta.15

### ISSUE THREAD

**Issue by yangshun** [facebook/docusaurus#6620]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

#6317 breaks pages using `scroll-behavior: smooth` as both JS and CSS are trying to smoothly scroll the page. For sites like about.supabase.com which uses `scroll-behavior: smooth` (reasonable thing to add IMO), cliking on the the TOCs don't bring you to the right section of the page.

### Steps to reproduce

To repro:

1. Add scroll-behavior: smooth to the <html> element
1. Click on anchors in TOC
1. The page fails to scroll to the anchor

### Expected behavior

Scroll to the section you clicked on in the TOC.

### Actual behavior

Doesn't scroll to the section you clicked on in the TOC.

### Your environment

- Public source code: [supabase/supabase](https://github.com/supabase/supabase/tree/master/about)
- Public site URL: about.supabase.com
- Docusaurus version used: 2.0.0-beta.15
- Environment name and version (e.g. Chrome 89, Node.js 16.4): Chrome 97.0.4692.99
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): Windows

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by yangshun** [comment]
I think the correct way would be to `scrollIntoView()` only if the link is not visible. Something like

```js
function isInViewport(el) {
    const rect = el.getBoundingClientRect();
    return (
        rect.top >= 0 &&
        rect.left >= 0 &&
        rect.bottom <= (window.innerHeight || document.documentElement.clientHeight) &&
        rect.right <= (window.innerWidth || document.documentElement.clientWidth)

    );
}
if (!isInViewport(el)) {
    link.scrollIntoView({ block: 'nearest' });
}
```

**Comment by Josh-Cena** [comment]
At this point, I think we should both 1) make this configurable (but default to true because it's good for most users) and 2) apply the fix you proposed 🤔

**Comment by Josh-Cena** [comment]
Another thing to consider for someone working on the fix: when the page is pinch-zoomed, the TOC link still tries to scroll to itself, which results in a horizontal scroll. We should only scroll into view if the scroll is purely vertical. This would probably need the `visualViewport` API.
