### ISSUE TITLE
katex equations order issue in rtl

### ISSUE THREAD

**Issue by SadeghKrmi** [facebook/docusaurus#6621]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

Katex equations are not showing properly in rtl languages. for example vector in below, appears unordered as shown in below figure.

```
$$
\overline{x} = 
\begin{bmatrix}
   x_1 \\
   x_2 \\
   \vdots \\
   x_n
\end{bmatrix}
$$
```

![image](https://user-images.githubusercontent.com/5988663/152690273-3b22f787-f0b4-4982-bfe7-bca743fded22.png)

### Steps to reproduce

Step1: add i18n same as below

```
  i18n: {
    defaultLocale: 'fa',
    locales: ['fa'],
    localeConfigs: {
      fa: {
        direction: 'rtl',
      },
    },
  },
```

Step2: install katex based on 
https://docusaurus-i18n-staging.netlify.app/docs/markdown-features/math-equations

Step3: add new equation

```
$$
\overline{x} = 
\begin{bmatrix}
   x_1 \\
   x_2 \\
   \vdots \\
   x_n
\end{bmatrix}
$$
```

### Expected behavior

to show katex equations in ltr format

### Actual behavior

katex equations are unordered.

### Your environment

- Public source code:
- Public site URL:
- Docusaurus version used:
- Environment name and version (e.g. Chrome 89, Node.js 16.4):
- Operating system and version (e.g. Ubuntu 20.04.2 LTS):

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by Josh-Cena** [comment]
Hi, Docusaurus doesn't do anything special about math equations. Please report bugs to:

- [`remark-math` / `rehype-katex`](https://github.com/remarkjs/remark-math)
- [`KaTeX`](https://github.com/KaTeX/KaTeX)

**Comment by slorber** [comment]
Note: I don't even know what is wrong with the image you posted 🤷‍♂️ 

At least we'd need you to draw what the expected result is, visually because it's not so straightforward to guess how equations work in RTL for me

**Comment by SadeghKrmi** [comment]
@slorber 
The issue is that equation is not ordered properly. in rtl languages, equations are written in ltr :)
equation should be x=[...]

**Comment by slorber** [comment]
So you mean the equation should be the exact same in ltr or rtl?

**Comment by SadeghKrmi** [comment]
Yes, I mean the equation are not correct.
Please find the correct equation in below image.


![image](https://user-images.githubusercontent.com/5988663/153222178-4f5106c5-4dd9-40d0-a727-02d5c20be74b.png)

**Comment by Josh-Cena** [comment]
I could have sworn I saw a very, very similar issue a while back in the KaTeX repo, but now I can't find it... Let me try reproducing this in a bare HTML file to see if Infima has anything to do with this...

**Comment by Josh-Cena** [comment]
Yes, this is a KaTeX problem. Reproducible demo:

```html
<!DOCTYPE html>
<html dir="rtl">
  <head>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.15.2/dist/katex.min.css" integrity="sha384-MlJdn/WNKDGXveldHDdyRP1R4CTHr3FeuDNfhsLPYrq2t0UBkUdK2jyTnXPEK1NQ" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/katex@0.15.2/dist/katex.min.js" integrity="sha384-VQ8d8WVFw0yHhCk5E8I86oOhv48xLpnDZx5T9GogA/Y84DcCKWXDmSDfn13bzFZY" crossorigin="anonymous"></script>
  </head>
  <body>
    <div id="body"></div>
    <script>
      document.getElementById("body").innerHTML = katex.renderToString(`\\overline{x} =
\\begin{bmatrix}
   x_1 \\\\
   x_2 \\\\
   \\vdots \\\\
   x_n
\\end{bmatrix}`);
    </script>
  </body>
</html>
```

<img width="155" alt="image" src="https://user-images.githubusercontent.com/55398995/153224797-22a9ddd7-673b-404b-8edf-d55c9ec0fa07.png">

**Comment by Josh-Cena** [comment]
@SadeghKrmi Seems https://github.com/KaTeX/KaTeX/issues/343 hasn't gained enough attention. In the meantime, you can [write a rehype plugin](https://docusaurus.io/docs/next/markdown-features/plugins) that finds all `class="katex"` JSX and appends a `dir="ltr"`. (This may be a useful reference: https://github.com/johnnyreilly/blog.johnnyreilly.com/pull/165/commits/9dfb48c3df5bfb6a445bef81d42cff5eccb2798c) Note that I mentioned in https://github.com/KaTeX/KaTeX/issues/3550 that `dir="ltr"` isn't a terribly good fix, but should be good enough for you.

**Comment by slorber** [comment]
This looks like a good enough workaround 🤷‍♂️ but can't tell for sure it will work fine with all equations

Maybe providing some custom CSS is enough, considering all math code blocks seems to be wrapped in a parent container

```html
<!DOCTYPE html>
<html dir="rtl">
  <head>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.15.2/dist/katex.min.css" integrity="sha384-MlJdn/WNKDGXveldHDdyRP1R4CTHr3FeuDNfhsLPYrq2t0UBkUdK2jyTnXPEK1NQ" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/katex@0.15.2/dist/katex.min.js" integrity="sha384-VQ8d8WVFw0yHhCk5E8I86oOhv48xLpnDZx5T9GogA/Y84DcCKWXDmSDfn13bzFZY" crossorigin="anonymous"></script>
    <style>
      #equation {
        direction: ltr;
        display: flex;
        justify-content: end;
      }
    </style>
  </head>
  <body>
    <div id="body">
      <h1>test katex</h1>
      <div id="equation" dir="ltr"/>
    </div>
    <script>
      document.getElementById("equation").innerHTML = katex.renderToString(`\\overline{x} =
\\begin{bmatrix}
   x_1 \\\\
   x_2 \\\\
   \\vdots \\\\
   x_n
\\end{bmatrix}`);
    </script>
  </body>
</html>
```

<img width="509" alt="image" src="https://user-images.githubusercontent.com/749374/153229075-72d1e4b2-ad96-463e-8940-e3b1661f846d.png">

**Comment by Josh-Cena** [comment]
Oh hey, I did think about it! Note that every KaTeX equation is wrapped by `<span class="katex">`, so you don't need another container for that. However, I only added `direction: ltr;` and the text tokens were still inverted:

<img width="155" alt="image" src="https://user-images.githubusercontent.com/55398995/153229679-5126bd68-8665-4848-9de2-99c85e2ce5c0.png">

And yes, @SadeghKrmi adding this to `custom.css` would fix it:

```css
.katex {
  direction: ltr;
  display: flex;
  justify-content: end;
}
```

**Comment by SadeghKrmi** [comment]
@slorber @Josh-Cena Thanks for helping. the solution below only worked for me for the bigger equation (note **rtl** in css). 
Do you any explanation for this?
but for equation in the line, it is not working, do you have any idea? (I highlighted in Red)

This worked for me in custom.css for bigger equation.
```
.katex {
  direction: rtl;
}
```


do you have any idea how to fix this?

![image](https://user-images.githubusercontent.com/5988663/153247254-a36b6cad-b74f-46e6-b4e9-a61ba4bb144d.png)

**Comment by slorber** [comment]
@SadeghKrmi I don't know, you have to scope the CSS to not apply to inline equations.

Maybe this selector will work 🤷‍♂️ `.math.math-display .katex { ... }`

**Comment by SadeghKrmi** [comment]
after struggling with CSS (I am not a CSS expert at all), I found a workaround using flex. add below css in custom.css and it will work in Docusaurus rtl direction languages like Persian, Arabic, etc.,

```
.katex {
  direction: rtl;
  display: inline-flex;
  flex-direction: row-reverse; 
}
```
