### ISSUE TITLE
footer-links  should support target params to set _blank

### ISSUE THREAD

**Issue by caohuilin** [facebook/docusaurus#6626]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Description

https://docusaurus.io/docs/2.0.0-beta.14/api/themes/configuration#footer-links 

Footer links should support setting target to _blank to open links in new tab

### Motivation

Footer links should be opened with a new tab when they contain 3rd party links

### Self-service

- [ ] I'd be willing to contribute this feature to Docusaurus myself.

**Comment by Josh-Cena** [comment]
Hi, outbound links are already opened in new tabs. You can also pass arbitrary attributes to the link created.
