### ISSUE TITLE
Details can't use `alert--success` styling

### ISSUE THREAD

**Issue by csestito** [facebook/docusaurus#6632]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

Details uses the `alert` styling, and by default adds the `alert alert--info` className to the element as seen [here](https://github.com/facebook/docusaurus/blob/main/packages/docusaurus-theme-classic/src/theme/Details/index.tsx#:~:text=const%20InfimaClasses%20%3D%20%27alert%20alert%2D%2Dinfo%27%3B). When using the details component and adding `alert alert--success` to change the coloring of the alert, the default `alert--info` styles take over. The element in this case has `alert alert--info alert alert--success` in the className. While other alert styles such as `alert--danger` work, the `alert--success` falls victim to css. 

### Steps to reproduce

1. Use a details component with added className `alert alert--success`

This can be reproduced on docusaurus.io by adding those classNames to the details element on [this page ](https://docusaurus.io/docs/api/docusaurus-config). 

### Expected behavior

Details turns green

### Actual behavior

Details stays blue. 

It look like it's because of the ordering of the css for `alert--success` and `alert--info`, but root cause is the `alert--info` being added to the details by default. 

Happy to fix this, just want to understand if it is preferred to reorder css to avoid this issue, or refactor details component to take status' into account. 

### Your environment

- Public source code:
- Public site URL:
- Docusaurus version used:
- Environment name and version (e.g. Chrome 89, Node.js 16.4):
- Operating system and version (e.g. Ubuntu 20.04.2 LTS):

### Self-service

- [X] I'd be willing to fix this bug myself.

**Comment by Josh-Cena** [comment]
Hi! This is something about the CSS being called "cascading". When you have two class names that try to define the same property, the one that comes later in the style sheet "wins". And it happens that `alert--success` comes before `alert--info` in the style sheet, hence its style gets overwritten.

If you are unhappy with the default style, you should swizzle `Details` and disable its built-in style altogether, maybe using a prop to optionally apply the default style.

**Comment by slorber** [comment]
Interesting.

Curious, what's the concrete use-case to have such styling? 

Can you share actual doc pages or screenshots of real content?

---

Note our details/summary design is a bit too opinionated and we'll move back to something soberer

https://github.com/facebookincubator/infima/issues/197
https://github.com/facebook/docusaurus/discussions/5749 

Do you think it's valuable keep a way to style those details similarly to admonitions?

**Comment by slorber** [comment]
I understand thanks, that's worth reopening and maybe implement this.

> it would be nice to have a default of alert--primary

As I said we are looking to provide a soberer design by default si we'll probably not use that style but rather something that looks closer to how default details view work in html

**Comment by Josh-Cena** [comment]
So my understanding is that there's little to do with Docusaurus but more to do with Infima, and we will fix it by providing admotion-specific styles?

**Comment by slorber** [comment]
Yes

Those are not really admonitions, I'd rather just call them "details/summary styles" even if technically it would look quite similar and we can share some CSS

**Comment by Josh-Cena** [comment]
Closing in favor of https://github.com/facebookincubator/infima/issues/197. Cross-linked the two discussions so whoever is working on the details styling issue can get more context.
