### ISSUE TITLE
When i upgrading project to beta-15

### ISSUE THREAD

**Issue by KInGATiLLa** [facebook/docusaurus#6643]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

I have upgraded my project deps to latest beta version 15, previously it was beta version 14. It is working in beta version 14. But in beta version 15 it doesn't work. This error occurs on every docs ".md" pages.

### Steps to reproduce

1. Dependency update from beta 14 to beta 15.
2. npm start in current project
3. Above error occurs 
4. npm run clear
5. rm -rf node_modules/ package-lock.json build .docusaurus
6. npm start
7. Nothing could changed

### Expected behavior

It work fine with docs .md pages without error.

### Actual behavior

<img width="1154" alt="image" src="https://user-images.githubusercontent.com/17881842/153135833-a4def5bf-9687-4a0f-9deb-cc2f000c0256.png">

### Your environment

- Public source code:
- Public site URL:
- Docusaurus version used: beta-15
- Environment name and version (e.g. Chrome 89, Node.js 16.4): Chrome 98, Node.js 16.13.2
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): Mac Pro M1 monterey

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by Josh-Cena** [comment]
Hi, you probably have upgraded `@mdx-js/react` to v2 along the way. See https://github.com/facebook/docusaurus/issues/6520#issuecomment-1031636619. You should stay on MDX v1 as we are not compatible with v2 yet. See #4029.

**Comment by KInGATiLLa** [comment]
Ok i got it
