### ISSUE TITLE
Support swapping out routers (IPFS react router, HashRouter...)

### ISSUE THREAD

**Issue by OxMarco** [facebook/docusaurus#6645]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Description

I suggest that we explore ways to make Docusaurus deployment to IPFS possible.
At the moment, the main blocker is the `baseUrl` that cannot be precomputed before the website is deployed.

I tried using Piñata to deploy the *build* folder to IPFS and got an error
> We suggest trying baseUrl = /ipfs/QmUsHzX.....BdPd/

### Motivation

IPFS is a decentralised and very price competitive storage system

### Self-service

- [X] I'd be willing to contribute this feature to Docusaurus myself.

**Comment by Josh-Cena** [comment]
Hi, Docusaurus [uses the base URL to build your site and pre-generate certain static HTML](https://docusaurus.io/docs/next/advanced/routing#routes-become-html-files), so it would be non-trivial to support this use-case. Could you tell me:

- How does IPFS determine the base URL? Is it totally random, or is it a hash? Does it change per deployment, or is it only assigned once?
- If we support dynamic base URL that can be injected post-build, what kind of API do you envision so you can actually _inject_ the base URL into the built bundle, which is all HTML and minified JavaScript?

Note that as stated multiple times in the issue template, we expect the issue to be very detailed and well-thought, not a random feature request. Please use the Canny board for that.

**Comment by OxMarco** [comment]
Upon uploading content (in this case the *build* folder) to an IPFS node, the resulting URL is the hash of the uploaded files. Being an immutable filesystem, the hash works both as a pointer to the document and as an anti-tampering system. Deployment of the same exact file(s) will yield the same URL, as hashes are deterministic.

We could try to use [ipfs-react-router](https://www.npmjs.com/package/ipfs-react-router) module to take care of the base URL. Injecting the URL ex-post would not be doable as content on IPFS cannot be edited.

**Comment by Josh-Cena** [comment]
Note that we aren't using the React router `basename` feature yet and base URL is handled a bit hackily now, which has caused problems like #6462, #6315, and #6294. If we are to support an alternative router, we have to make sure `basename` is supported first. And that would probably be after we've migrated to React router v6.

**Comment by OxMarco** [comment]
Supporting swappable routers is probably a good way to support IPFS without introducing destructive changes to the codebase. I used the aforementioned react ipfs router in the past and it worked pretty well as a solution to deploying an app without knowing the URL beforehand.

**Comment by slorber** [comment]
Please assume I have 0 knowledge of IPFS (which is not totally untrue 😅)

Why do you want that? 
How would it work? 
Do you have examples of other open-source SSG SPAs being deployed to IPFS (Gatsby, Next, Jekyll, Eleventy, whatever...?) that we could inspect?

**Comment by OxMarco** [comment]
[IPFS](https://ipfs.io/) - *the interplanetary file system* - is a distributed network of independent nodes that offer data storage and replication for immutable data, it can be multimedia, PDFs or websites too. 
For static website generators like the ones you mention, the build folder containing compiled artefacts is uploaded to an IPFS node and then served to the open public using its hash, called CID, as URL (in the form of ipfs://CID, or accessible using a public HTTP gateway like `https://gateway.ipfs.io/ipfs/CID`). 

An example of apps deployed to IPFS is the [Uniswap frontend](https://github.com/Uniswap/interface)

**Comment by slorber** [comment]
Note, you can see by yourself if you disable JS that the Uniswap app is not a static app. It is entirely generated on the client side

<img width="1911" alt="image" src="https://user-images.githubusercontent.com/749374/153448176-2364301a-f9a9-41a5-adf6-fba373368cd8.png">

**Comment by OxMarco** [comment]
Business value of IPFS hosting is cheaper hosting price, redundancy and data immutability. Some people then use Cloudflare to connect a custom DNS to the IPFS route for better UX.

Uniswap frontend is a ReactJS app, it is dynamically generated as it interacts with the blockchain.

Considering your point it seems Docusaurus isn't fit for a content distribution system like IPFS

**Comment by mrkvn** [comment]
From what I researched, build for create-react-app does not work with IPFS too. But putting `"homepage": "./",` in package.json works. Thus, I think it's just about pathing.

So I did the same thing for build files for docusaurus. For example, I changed `"/assets/..."` to `"./assets/..."` and it worked. I'm not sure why putting `"homepage": "./",` in package.json does not make the build files to relative path though. So I had to do it manually.

**Comment by Josh-Cena** [comment]
@mrkvn There's a plugin to do this. See https://github.com/facebook/docusaurus/issues/3825#issuecomment-911593835

**Comment by mrkvn** [comment]
@Josh-Cena Thanks. That'd be a big help. I'll check it.

**Comment by mrkvn** [comment]
@Josh-Cena Looks like it's not there anymore. Page not found. :(

**Comment by mrkvn** [comment]
This helped. [#448 (comment)](https://github.com/facebook/docusaurus/issues/448#issuecomment-445389373)
