### ISSUE TITLE
Wrong rendering of code block inside numbered list

### ISSUE THREAD

**Issue by birdofpreyru** [facebook/docusaurus#6657]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [ ] I have tried the `npm run clear` or `yarn clear` command.
- [ ] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io.
- [ ] I have read the console error message carefully (if applicable).

### Description

The following MD markup:

```md
1)  Some text
    ```jsx
    console.log('Hello World!');
    ```
```
Should be rendered as this:

---
1)  Some text
    ```jsx
    console.log('Hello World!');
    ```
---

Instead, Docusaurus renders it with ` ```jsx ` and ` ``` ` printed at the beginning and the end of the code block, and it also does not indent the list item (neither the text, nor the code block).

Note, if `1)` is replaced by `- ` (_i.e._ bullet list with otherwise the same markup) the markup is rendered correctly (both the indent and the code block), also the code block in the numbered list is rendered fine if less than 4 leading whitespaces is used in the markup.

### Steps to reproduce

N/A

### Expected behavior

N/A

### Actual behavior

N/A

### Your environment

N/A

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by Josh-Cena** [comment]
Hey, Docusaurus uses MDX v1 as the Markdown renderer, so please ensure your syntax is valid MDX. Unfortunately, it is not:

1. `1)` is common mark syntax, and is not always supported. MDX v1 doesn't support this, but v2 does.
2. Indentation by four spaces means a code block.

You can test in the [MDX playground:](https://mdx-git-renovate-babel-monorepo-mdx.vercel.app/playground)

<img width="999" alt="image" src="https://user-images.githubusercontent.com/55398995/153523388-436e013d-bc68-494b-ac64-89a6b9227068.png">
