### ISSUE TITLE
Navigating to anchor link when images are loading results in page shift

### ISSUE THREAD

**Issue by jsprklst** [facebook/docusaurus#6685]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

When clicking on an Algolia search result anchor link of a page that has not yet been visited, the browser does not scroll to the correct position. It doesn't seem to take image size into account.

This PR solved the problem for external links, but doesn't work in this case: 
https://github.com/facebook/docusaurus/pull/6339

### Steps to reproduce

1. Go to https://docs.thinkwisesoftware.com/ in an incognito window
2. Click the Search input field or press Ctrl+K
3. Search for "browser"
4. Click on the "Browser configuration / Integrated security" link
5. Notice how the page does not scroll down far enough

### Expected behavior

The page should scroll down to the "Browser configuration" title/anchor.

### Actual behavior

The page does not scroll down far enough to the correct anchor.

### Your environment

- Public site URL: https://docs.thinkwisesoftware.com/
- Docusaurus version used: 2.0.0-beta.15
- Environment name and version (e.g. Chrome 89, Node.js 16.4): any browser
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): any OS

### Reproducible demo

<https://docs.thinkwisesoftware.com>

### Self-service

- [X] I'd be willing to fix this bug myself.

**Comment by Josh-Cena** [comment]
Yeah, seems the anchor link problem is still not properly resolved.

**Comment by slorber** [comment]
Yes 😰 

Not only search, other links too

For example this page has a link to "Table Reports":

https://docs.thinkwisesoftware.com/docs/sf/overview

<img width="1041" alt="image" src="https://user-images.githubusercontent.com/749374/154279196-ba1d8eef-a11b-4ffc-8fc6-747f73909891.png">


Looks definitively related to images. When images are cached the links lead to the correct anchors.

**Comment by Josh-Cena** [comment]
Hmmm, interesting... @jsprklst So you can't reproduce this on any other Docusaurus website? IIRC this had been a real problem that @slorber and I had both noticed a while ago.
