### ISSUE TITLE
Allow custom props through _category_.json

### ISSUE THREAD

**Issue by qiaofeng1227** [facebook/docusaurus#6690]
### Have you read the Contributing Guidelines on issues?

We used it docusaurus for our documentation. It's excellent.
I want to  customizae generated-index catalog, e.g. show filenames link of directory.
Is there a scheme that can be realized only by setting _category_.json?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Description

![image](https://user-images.githubusercontent.com/43192516/154227955-9784c118-bfe1-461d-8d18-5294fb818d52.png)

![image](https://user-images.githubusercontent.com/43192516/154228875-958ab6f7-33be-49d9-a5f1-1fa3d5268b4e.png)

### Motivation

dd

### Self-service

- [X] I'd be willing to contribute this feature to Docusaurus myself.

**Comment by Josh-Cena** [comment]
Hi, you can swizzle `DocCard` and use the category item's `customProps` to pass in your own description. However, I do realize that the sidebar generator currently doesn't pass the `customProps` attribute, so it would be a useful extension

**Comment by slorber** [comment]
@Josh-Cena if you have any customization idea for our own site (even just aesthetic ones), I think it can be useful to dogfood this on our own site, add some category customProps and swizzle the cards.

This can be used as an official example for others to look at

**Comment by taejs** [comment]
I'd like to look into this issue.
