### ISSUE TITLE
@docusaurus/lqip-loader` uses deprecated url module

### ISSUE THREAD

**Issue by SimenB** [facebook/docusaurus#6695]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

`querystring` is deprecated, but Docusaurus pulls it in transitively

### Steps to reproduce

1. `yarn add @docusaurus/core`
2. See `➤ YN0061: │ querystring@npm:0.2.0 is deprecated: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.`
3.
```sh-session
$ yarn why -R querystring
└─ docu-depr@workspace:.
   └─ @docusaurus/core@npm:2.0.0-beta.15 [15917] (via npm:^2.0.0-beta.15 [15917])
      └─ @slorber/static-site-generator-webpack-plugin@npm:4.0.1 (via npm:^4.0.0)
         └─ url@npm:0.11.0 (via npm:^0.11.0)
            └─ querystring@npm:0.2.0 (via npm:0.2.0)
```

### Expected behavior

No deprecation warning

### Actual behavior

See reproduction steps.

Should probably migrate away from the plugin entirely, from what I can tell it's an unmaintained fork of an unmaintained project (https://github.com/markdalgleish/static-site-generator-webpack-plugin/issues/142)

### Your environment

N/A

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by Josh-Cena** [comment]
Yeah, I've noticed that for a while as well. However, we've only recently acquired [our own organization](https://github.com/docusaurus) where we plan to store and maintain these forks, but right now neither of @slorber and I have member access, so we'd rather wait unless something actually breaks...

**Comment by SimenB** [comment]
This fix is literally to delete this line: https://github.com/slorber/static-site-generator-webpack-plugin/blob/de03472bbb93aca73d2dc1dc7ecc812b8b5f3605/package.json#L28

`url` is a builtin module, the version of npm is to distribute that outside the node runtime.

("legacy" API here https://nodejs.org/api/url.html)

**Comment by SimenB** [comment]
Fun fact, in node you always get the core module anyways, `node_modules` is ignored for builtins

**Comment by slorber** [comment]
Thanks, we'll handle this when we have the org properly setup

**Comment by slorber** [comment]
Fixed for Jest case in https://github.com/facebook/docusaurus/pull/6975

But apparently, there's another dependency to fix for ideal-image plugin users:

```
=> Found "querystring@0.2.0"
info Reasons this module exists
   - "_project_#@docusaurus#lqip-loader#node-vibrant#url" depends on it
   - Hoisted from "_project_#@docusaurus#lqip-loader#node-vibrant#url#querystring"
```

**Comment by slorber** [comment]
np 👍 

reopening as querystring is still used though 😅

**Comment by Josh-Cena** [comment]
`node-vibrant` isn't even used by us, simply removed that option in #6992
