### ISSUE TITLE
Autogenerated sidebar doesn't truly sort alphabetically

### ISSUE THREAD

**Issue by xyeLz** [facebook/docusaurus#6698]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [ ] I have tried the `npm run clear` or `yarn clear` command.
- [ ] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io.
- [ ] I have read the console error message carefully (if applicable).

### Description

I rely heavily on the autogenerated sidebar. I was under the impression that it sorted automatically unless otherwise specified in the frontmatter; however, this doesn't appear to always be the case.

### Steps to reproduce

On [my website](https://ccsp-isc2.pages.dev/), drop down the Concepts sidebar item. You will see that Legal and Training precede Auditing despite the fact that Auditing precedes it alphabetically.

### Expected behavior

I personally feel it should list every item alphabetically regardless of what the item actually is. It shouldn't matter whether it links to a page, links to a page and drops down other pages, or only drops down other pages. Ideally, this preference should be configurable in the config file so users can choose which they'd prefer.

### Actual behavior

It seems Docusaurus prefers pages over categories when sorting. That is, it will first alphabetically list any individual page links in the sidebar at the top. Then it will list the categories/dropdowns in alphabetical order.

### Your environment

- Public site URL: https://ccsp-isc2.pages.dev
- Docusaurus version used: 2.x

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by Josh-Cena** [comment]
Not very unreasonable expectation.
