### ISSUE TITLE
docusaurus serve: non-existent route displays default folder index view instead of 404 page

### ISSUE THREAD

**Issue by BigSharkLx** [facebook/docusaurus#6699]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

When I build the official example website project and then serve it, I visit http://localhost:3000/docs/ This page shows the directory and path of static resource access. I hope that a prompt similar to the page not found in the development environment will appear. Instead of displaying the doc of the entire website as a static resource directory

![截屏2022-02-17 下午12 59 08](https://user-images.githubusercontent.com/26083406/154408537-f854756d-3095-4c3c-b1a0-d0f9ca674cc4.png)

### Steps to reproduce

1. Build the official example website project
2. After yarn serve is successful, visit http://localhost:3000/docs/

### Expected behavior

It should be the same as the development environment, suggesting that the page cannot be found instead of displaying the address of the static resources of the docs folder
![截屏2022-02-17 下午1 06 25](https://user-images.githubusercontent.com/26083406/154409371-7a60c644-d17f-4bfa-9eed-991f93452845.png)

### Actual behavior

Display the address of static resources in the docs folder

### Your environment

- Public source code:
- Public site URL:
- Docusaurus version used:
- Environment name and version (e.g. Chrome 89, Node.js 16.4):
- Operating system and version (e.g. Ubuntu 20.04.2 LTS):

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by Josh-Cena** [comment]
Note that `docusaurus serve` only uses a very basic HTTP server and is not controlled much by Docusaurus. It's only meant for local deployment preview.
