### ISSUE TITLE
Links to headers break when using the full path

### ISSUE THREAD

**Issue by mtl-wgtwo** [facebook/docusaurus#6702]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

I have been trying to make links to sections, and the link generator fails in one case.  Here is a repro:

https://codesandbox.io/s/xenodochial-carlos-tx132x?file=/docs/tutorial-basics/create-a-document.md

The short summary is this:

```
- [link that doesn't work](docs/tutorial-basics/create-a-page#create-your-first-react-page)
```

This generates a link that looks like this (in my example): https://tx132x.sse.codesandbox.io/docs/tutorial-basics/docs/tutorial-basics/create-a-page#create-your-first-react-page

These cases work as expected:
```
- [link that works](#create-your-first-doc)
- [link that also works](docs/tutorial-basics/create-a-page)
- [relative links work](./create-a-page#create-your-first-react-page)
- [relative links up a dir](../intro#getting-started)

```

### Steps to reproduce

Repo is available as https://codesandbox.io/s/xenodochial-carlos-tx132x

Browse to https://tx132x.sse.codesandbox.io/docs/tutorial-basics/create-a-document

Note that the first link (`- [link that doesn't work](docs/tutorial-basics/create-a-page#create-your-first-react-page)`) does not work.

### Expected behavior

I expect that links to content + header using the full path (e.g. docs/tutorial-basics/create-a-page#create-your-first-react-page work like other header links).

### Actual behavior

![image](https://user-images.githubusercontent.com/40828984/154439096-ef4df6ff-6b88-44d4-b7cd-6acd29d1fb06.png)

The URL this is generated repeats the `docs/tutorial-basics`, resulting in the wrong location.: https://tx132x.sse.codesandbox.io/docs/tutorial-basics/docs/tutorial-basics/create-a-page#create-your-first-react-page

### Your environment

- Public source code: https://codesandbox.io/s/xenodochial-carlos-tx132x?file=/docs/tutorial-basics/create-a-document.md:59-380
- Public site URL: https://tx132x.sse.codesandbox.io/docs/tutorial-basics/create-a-document
- Docusaurus version used: whatever is in the sandbox now

This occurs in our own docusaurus site as well.

### Reproducible demo

https://tx132x.sse.codesandbox.io/docs/tutorial-basics/create-a-document

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by Josh-Cena** [comment]
Hi, it isn't Docusaurus behavior; it's your browser's behavior. We only turn it into an `<a href="...">` tag. This follows typical URL semantics that paths without a leading slash are relative and only those with a leading slash are absolute. 

If you are not familiar with web URLs, think of file paths. If you are currently in a folder with path `/Users/mtl-wgtwo/Desktop/docs`, and you do `cd docs/tutorial-basics`, you are taken _down_ relative to where you already are, i.e. into a folder called `/Users/mtl-wgtwo/Desktop/docs/docs/tutorial-basics`.

If you want to go to a path that's relative to your site's root instead of where you currently are, you need to add a leading slash.

```
- [link that works](/docs/tutorial-basics/create-a-page#create-your-first-react-page)
- ```

**Comment by mtl-wgtwo** [comment]
Huh, my bad.  I misinterpreted how this was working then.  I wonder why the link checker in the build process doesn't pick up all the places that do this incorrectly in the site I am converting from our old wiki.

Thanks for clarifying.

**Comment by Josh-Cena** [comment]
> I wonder why the link checker in the build process doesn't pick up all the places that do this incorrectly in the site I am converting from our old wiki.

Now that's interesting. I would need to investigate that.

**Comment by Josh-Cena** [comment]
@mtl-wgtwo Can't repro, the link checker is reporting an error for me:

```
Error: Docusaurus found broken links!

Please check the pages of your site in the list below, and make sure you don't reference any path that does not exist.
Note: it's possible to ignore broken links with the 'onBrokenLinks' Docusaurus configuration, and let the build pass.

Exhaustive list of all broken links found:

- On source page path = /foo/docs/tutorial-basics/create-a-document:
   -> linking to docs/tutorial-basics/create-a-page#create-your-first-react-page (resolved as: /foo/docs/tutorial-basics/docs/tutorial-basics/create-a-page)
```

**Comment by mtl-wgtwo** [comment]
This is in my local repository for an internal doc site that was converted from a Hugo site and a Gollum site.  I'd migrated everything with a relative leading path and fully built the site.  Not sure what was going on, but I'm fixing this now.

In the example above, `- [link that also works](docs/tutorial-basics/create-a-page)` was clearly incorrect, but passed at least the `yarn start` link checking.  This is what actually confused me because this was passing, but adding a header to the end made it fail the link checker.

**Comment by Josh-Cena** [comment]
`yarn start` doesn't do HTML link checking, only Markdown link checking (`./doc.md`). You would need to do a build to catch the broken HTML links.

**Comment by mtl-wgtwo** [comment]
I've built and deployed my site with the wrong sort of links.  I've fixed everything now, but if I reproduce this later, I'll file a new issue.
