### ISSUE TITLE
The first build of Circle CI failed

### ISSUE THREAD

**Issue by ysyfff** [facebook/Docusaurus#671]
1. Copy the text of Circle CI to my project in .circle/config.yml and push it to master.
2. Start building on Circle CI, but the result of building is failure .
The error message is as below:
![image](https://user-images.githubusercontent.com/2571290/40164298-b81c5f4c-59eb-11e8-9563-49ba14851ce3.png)
3.But after that, when I push something again to master, it builds successfully! That is odd.

If not use workflow, The first build will always be successful. So I add another text of Circle CI.

**Comment by endiliey** [comment]
It seems that based on #670 this error might be caused due to CircleCI outage. I'm closing this for now, feel free to reopen if issue persists
