### ISSUE TITLE
Click the picture to zoom in

### ISSUE THREAD

**Issue by zhgt-shaozi** [facebook/docusaurus#6713]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Description

I hope to provide a function that can click to enlarge the picture. Click the picture to zoom in.

### Motivation

I hope to provide a function that can click to enlarge the picture. Maybe many users will like this feature.

### Self-service

- [ ] I'd be willing to contribute this feature to Docusaurus myself.

**Comment by duanwilliam** [comment]
there already exists a community plugin that provides this feature: https://github.com/flexanalytics/plugin-image-zoom

**Comment by Josh-Cena** [comment]
Yes, this is trivial with an external plugin. Our website has zoomable pictures as well. This image is zoomable, simply with putting the image in a React component: https://docusaurus.io/docs/next/advanced/architecture
