### ISSUE TITLE
Possible Syntax Issue with Type-Only Imports

### ISSUE THREAD

**Issue by sserrata** [facebook/docusaurus#6719]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [ ] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

While debugging a community plugin ([docusaurus-openapi](https://github.com/cloud-annotations/docusaurus-openapi)) build issue I noticed that type-only imports are using this format:

```typescript
import React, {
  createContext,
  type ReactNode,  // "type" inside curly braces 
  useCallback,
  useContext,
  useEffect,
  useLayoutEffect,
  useMemo,
  useRef,
} from 'react';
```

As opposed to this:

```typescript
import React, {
  createContext,
  useCallback,
  useContext,
  useEffect,
  useLayoutEffect,
  useMemo,
  useRef,
} from 'react';
import type { ReactNode } from 'react';  // "type" outside curly braces
```

Running `tsc` results in `TS1005` errors like the following:

```bash
docusaurus-theme-openapi: ../../node_modules/@docusaurus/theme-common/lib/utils/scrollUtils.d.ts(7,22): error TS1005: ',' expected.
```

I am far from a typescript expert but examples on StackOverflow and [TypeScriptLang.org](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-8.html#type-only-imports-and-export) suggest that the latter might be the correct syntax for type-only imports.  I tested this theory by manually editing the import and was able to resolve at least one of these `TS1005` errors.

typescript version: 4.4.4
tsc version: 4.5.5

Here's the `tsconfig.json` I am using:

```json
{
  "extends": "../../tsconfig.base.json",
  "compilerOptions": {
    "lib": ["DOM", "ES2019"],
    "module": "esnext",
    "noEmit": true,
    "jsx": "react"
  },
  "include": ["src"]
}
```

Here is `tsconfig.base.json`:

```json
{
  "compilerOptions": {
    "target": "ES2019",
    "module": "commonjs",
    "lib": ["ESNext", "DOM"],
    "declaration": true,
    // "allowJs": true, // causing strange issue
    "skipLibCheck": true,
    "jsx": "react",
    "sourceMap": true,

    /* Strict Type-Checking Options */
    "strict": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "strictBindCallApply": true,
    "strictPropertyInitialization": true,
    "noImplicitThis": true,
    "alwaysStrict": true,

    /* Additional Checks */
    "noImplicitReturns": true,
    "noFallthroughCasesInSwitch": true,
    "forceConsistentCasingInFileNames": true,

    /* Module Resolution Options */
    "moduleResolution": "node",
    "allowSyntheticDefaultImports": true,
    "esModuleInterop": true,

    /* Advanced Options */
    "resolveJsonModule": true,
    "isolatedModules": true
  }
}
```

### Steps to reproduce

This is tricky, as I am working off a fork of a community plugin. I will try to reproduce with `docusaurus` repo and report back.

### Expected behavior

`tsc` should result in no errors

### Actual behavior

View workflow output: https://github.com/PaloAltoNetworks/docusaurus-openapi/runs/5253718924?check_suite_focus=true

### Your environment

- Public source code: https://github.com/PaloAltoNetworks/docusaurus-openapi/tree/panw-main
- Public site URL:
- Docusaurus version used: beta.15
- Environment name and version (e.g. Chrome 89, Node.js 16.4):
- Operating system and version (e.g. Ubuntu 20.04.2 LTS):

### Self-service

- [X] I'd be willing to fix this bug myself.

**Comment by Josh-Cena** [comment]
Hello, this is TS 4.5 syntax, which you can find here: https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-5.html#type-modifiers-on-import-names

> typescript version: 4.4.4
> tsc version: 4.5.5

I don't understand what you mean here. `tsc` is distributed _by_ the `typescript` package.

I can certainly understand that the TypeScript handbook doesn't always reflect the latest features (which I have talked with the community and the TypeScript team about!), and I can understand that not everyone spends time to read the release notes/blog posts, but this is certainly valid syntax :) Otherwise the Docusaurus codebase would have been broken long ago :)

**Comment by Josh-Cena** [comment]
Note that if you have a global `tsc` installation that doesn't line up with your repo's version, you should use `yarn tsc` instead of `tsc`, so you use the repo's version instead of your globally installed version.

**Comment by Josh-Cena** [comment]
Also, if you are debugging problems in a plugin and think you've discovered a bug, please open issues in their repo. Our issue tracker is not a support forum.
