### ISSUE TITLE
Page crashes when trying to use live code block

### ISSUE THREAD

**Issue by certainlyNotHeisenberg** [facebook/docusaurus#6724]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

When trying to use [live code blocks](https://docusaurus.io/docs/markdown-features/code-blocks#interactive-code-editor), I get this error (rendered on the client, not in terminal):

> This page crashed. "useColorMode()" is used outside of "Layout" component. Please see https://docusaurus.io/docs/api/themes/configuration#use-color-mode.

Note that I get no such error when just using code blocks. The error appears when I add `live` after the language meta tag.

I'm using version 2.0.0-beta.15.

### Steps to reproduce

To any Markdown docs page, add a live code block, like this example [from the documentation](https://docusaurus.io/docs/markdown-features/code-blocks#interactive-code-editor):

````
```jsx live
function Clock(props) {
  const [date, setDate] = useState(new Date());
  useEffect(() => {
    var timerID = setInterval(() => tick(), 1000);

    return function cleanup() {
      clearInterval(timerID);
    };
  });

  function tick() {
    setDate(new Date());
  }

  return (
    <div>
      <h2>It is {date.toLocaleTimeString()}.</h2>
    </div>
  );
}
```
````

This should produce the error described above. Now, remove `live` after the language meta tag. This should result in no error.

### Expected behavior

The live code block should work without error.

### Actual behavior

I get the error described above.

### Your environment

- Public source code:
- Public site URL:
- Docusaurus version used: 2.0.0-beta.15
- Environment name and version (e.g. Chrome 89, Node.js 16.4):
- Operating system and version (e.g. Ubuntu 20.04.2 LTS):

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by Josh-Cena** [comment]
@certainlyNotHeisenberg Since it succeeds in the Docusaurus site, I can guarantee that it is not a Docusaurus bug. Do you have a repro? Have you swizzled any component? Please don't use the GitHub issue tracker as a support forum—unless you can clearly outline how it's a Docusaurus defect, we will treat it as a question.

**Comment by certainlyNotHeisenberg** [comment]
@Josh-Cena My apologies. I figured it was a Docusaurus bug because when I added the example live code block to the CodeSandbox playground, that also crashed. But of course you make a good point that it's working on the documentation site! I have no idea why it'd be working there but not in the playground and not locally for me...

**Comment by slorber** [comment]
you are probably rendering a code block somewhere there is no layout component

it's hard to tell if we don't have a full repro and more infos

**Comment by Josh-Cena** [comment]
The only case that I can think of to make it fail in code sandbox without non-trivial effort is exporting a page from `src/pages` without wrapping it in `Layout`. Because any Markdown page should always be wrapped with `Layout`

**Comment by Manonicu** [comment]
how to solve?
any sample code?

**Comment by leovigna** [comment]
Was running into the same issue. I tested with the official docusaurus starter. 
* Installed with `npm` and it worked.
* Deleted `node_modules`, installed with `pnpm` broken `Hook useColorMode is called outside the <ColorModeProvider>` error

This leads me to believe it is an issue with webpack5 & pnpm.

**Comment by slorber** [comment]
Note in the future we may migrate theme-common to peerDependency and add it explicitly to all new sites

**Comment by norman-ags** [comment]
I'm also using pnpm and the [above solution](https://github.com/facebook/docusaurus/issues/6724#issuecomment-1188794031) didn't work. I fixed it by adding `@docusaurus/theme-common` in the package.json of my doc package in my monorepo

**Comment by baptisteArno** [comment]
> ```js
> module.exports = {
>     hooks: {
>         readPackage(pkg) {
>             if (pkg.name != 'my-website') {
>                 const deps = ["@algolia/client-search", "@docusaurus/core", "@docusaurus/preset-classic", "@docusaurus/theme-common", "@docusaurus/theme-live-codeblock"]
>                 deps.forEach((p) => delete pkg.dependencies[p])
>             }
>             return pkg
>         }
>     }
> }
> ```

I added this file, then ran `pnpm install` then deleted this file remove all node_modules folders and ran `pnpm install` again, now it works. So strange.

**Comment by NiuZhuang** [comment]
Many thanks. I tried below steps and it works as magic. 

1. add .npmrc as below
    ```
    public-hoist-pattern[]='@docusaurus/*'
    public-hoist-pattern[]=@mdx-js/react
    hoist=false
    ```
2. delete root node_modules
3. delete doc package's node_modules
4. `pnpm i`

**Comment by xllpiupiu** [comment]
> I'm also using pnpm and the [above solution](https://github.com/facebook/docusaurus/issues/6724#issuecomment-1188794031) didn't work. I fixed it by adding `@docusaurus/theme-common` in the package.json of my doc package in my monorepo

My monorepo is based on rush+pnpm，I added `@docusaurus/theme-common` to package.json, but report error: `Hook useDocsSidebar is called outside the <DocsSidebarProvider>` after `rushx swizzle @docusaurus/theme-classic DocBreadcrumbs --typescript`

**Comment by leovigna** [comment]
> > ```js
> > module.exports = {
> >     hooks: {
> >         readPackage(pkg) {
> >             if (pkg.name != 'my-website') {
> >                 const deps = ["@algolia/client-search", "@docusaurus/core", "@docusaurus/preset-classic", "@docusaurus/theme-common", "@docusaurus/theme-live-codeblock"]
> >                 deps.forEach((p) => delete pkg.dependencies[p])
> >             }
> >             return pkg
> >         }
> >     }
> > }
> > ```
> 
> I added this file, then ran `pnpm install` then deleted this file remove all node_modules folders and ran `pnpm install` again, now it works. So strange.

I think this is because the `.pnpmfile.cjs` affects the dependency resolution and therefore the lockfile https://pnpm.io/pnpmfile
I think you probably also have to add `@docusaurus/theme-common` to your package.json and I forgot to mention this.

**Comment by strmer15** [comment]
In my case, I actually had to add `@docusaurus/types` to the `dependencies` of my doc project - `@docusaurus/theme-common` was being duplicated by PNPM because `@docusaurus/utils` sometimes had the `@docusaurus/types` optional dependency provided and sometimes not. By providing it explicitly in my dependencies, it eliminated the duplicates and fixed my problem.

**Comment by didilinkin** [comment]
### Fix : pnpm => yarn
```js
// docusaurus.config.js
...
themes: ['@docusaurus/theme-live-codeblock'],
...
```

1.  `rm -rf node_modules`
2.  `package.json` - `dependencies` 
Add `"@mdx-js/react": "^1.6.21"`, Dont `@mdx-js/react`- 'version 2.0.0'

3. `yarn install` 

> 如果安装失败，多尝试几次 安装步骤，我尝试安装 4-5次 才成功
>
> If the installation fails, try several more installation steps, I tried to install 4-5 times before it succeeded

4. `yarn start`
5.  Success

**Comment by wanghsinche** [comment]
alright, after reading all related issues, I found only one feasible method...  https://github.com/facebook/docusaurus/issues/7880#issuecomment-1368025143       add @docusaurus/types to the dependencies of your doc project, then the issue caused by pnpm or rush can be solved...
