### ISSUE TITLE
Toggle not always in sync with color mode with multiple toggles

### ISSUE THREAD

**Issue by timocov** [facebook/docusaurus#6733]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

The theme control displays wrong state after changing the theme from burger menu.

### Reproducible demo

https://docusaurus.io/

### Steps to reproduce

1. Open https://docusaurus.io/ _with wide screen_ so theme control will be visible in the header
2. Enable Dark theme from the control
3. Resize the window so the burger menu would be visible and theme control disappears from the header
4. Open burger menu
5. Switch the theme to Light
6. Resize the window back to wide so you would see the theme control in the header

### Expected behavior

The theme control shows a state of currently applied theme accurately.

### Actual behavior

The theme control displays that the Dark theme is enabled, but this is not true. You can click on it and the first click will do nothing (only resets the state of the control) and the second click will change the theme. See attached gif (it is from different website, but you can easily reproduce it on any other website, including a new one from https://new.docusaurus.io/):

![docusaurus-bug](https://user-images.githubusercontent.com/3112183/154930638-032a804f-244b-451d-a855-662ae302c2f6.gif)

### Your environment

- Public source code: https://github.com/facebook/docusaurus
- Public site URL: https://docusaurus.io/
- Docusaurus version used: 2.0.0-beta.15
- Environment name and version (e.g. Chrome 89, Node.js 16.4): any
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): any

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by Josh-Cena** [comment]
This can be even more easily reproduced with the [color picker page](https://docusaurus.io/docs/next/styling-layout#styling-your-site-with-infima) where we have a button to toggle color mode. However, it seems it's only reproduced after a refresh, and before you interacted with the main toggle. I wonder if it has something to do with our memoization of the toggle.

![Test](https://user-images.githubusercontent.com/55398995/154941620-4aae82ab-5d40-4a53-938b-002ce2874bd0.gif)

**Comment by lex111** [comment]
Thanks for the report, should be fixed as part of the PR #6723.
