### ISSUE TITLE
Pngs and Jpgs are missing on deployment bundle, while SVGs are there.

### ISSUE THREAD

**Issue by dansofter** [facebook/docusaurus#6737]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [ ] I'm using the latest version of Docusaurus.
- [ ] I have tried the `npm run clear` or `yarn clear` command.
- [ ] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io.
- [ ] I have read the console error message carefully (if applicable).

### Description

Hi there,

I am using Vercel to host my docusaurus project.
The weird thing is that svgs are showing on Vercel, but pngs and jpgs are not showing.
I am using the same syntax to place svgs and pngs on markdown.

![Calamari Supply](/img/calamari-supply.png) // This is for png.
![overview](/img/DolphinPay.svg) // This is for SVG.

Can somebody help me?

### Steps to reproduce

Go to https://manta-docs.vercel.app/docs/Introduction

### Expected behavior

![image](https://user-images.githubusercontent.com/48925763/155047775-be8cd91b-014d-4cad-bd78-67b51e8f9894.png)

These should be images.

### Actual behavior

https://manta-docs.vercel.app/docs/Introduction

### Your environment

- Public source code: https://github.com/manta-network/docs
- Public site URL: https://manta-docs.vercel.app/
- Docusaurus version used: 2.0.0-beta.9
- Environment name and version (e.g. Chrome 89, Node.js 16.4): Node 16.13.2, Chrome 98.0.4758.102 
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): Windows 10

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by Josh-Cena** [comment]
Hi, your deployed site doesn't contain the broken images, and you didn't provide exact steps to reproduce for me.

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/55398995/155048216-71069b48-c354-4ee6-b0cf-bca969bef064.png">

It's clear that this is not a Docusaurus bug and very likely a user error. It's also clear that you didn't read through the issue template and understand that GitHub issue tracker is not for questions, since you didn't spend time demonstrating how it's a Docusaurus bug. If you have questions, reach out for me on Discord. I'll close this for housekeeping.

**Comment by slorber** [comment]
looks like this page is working with images 🤷‍♂️ 

https://manta-docs.vercel.app/docs/dolphin/DolphinPay

<img width="1886" alt="image" src="https://user-images.githubusercontent.com/749374/155300964-0d7c9848-aa51-4431-9a5c-dad71b49ebc1.png">

**Comment by Josh-Cena** [comment]
@slorber I contacted him in Discord. The problem is that they are using Git LFS which Vercel doesn't seem to support yet. I think they stopped using LFS? It indeed didn't work yesterday.

**Comment by dansofter** [comment]
> @slorber I contacted him in Discord. The problem is that they are using Git LFS which Vercel doesn't seem to support yet. I think they stopped using LFS? It indeed didn't work yesterday.

Thanks guys. It was because Vercel didn't pull images from git lfs during deployment.
I had to change the yarn install script on Vercel and it's resolved now.
