### ISSUE TITLE
[Dropdown] Not Working Properly

### ISSUE THREAD

**Issue by abhinav-22-tech** [facebook/docusaurus#6743]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [ ] I have tried the `npm run clear` or `yarn clear` command.
- [ ] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

The DropDown Menu of the header of the website does not work properly. When we click on `All versions` it shows the correct page but does not show `All versions` in the dropdown menu.

### Steps to reproduce

1. Initial Stage:

![image](https://user-images.githubusercontent.com/66718489/155284301-ded28757-e669-4665-904b-aa9925539ed4.png)

2. Hover on the Dropdown menu in the header and then click on `All versions`. It will not show `All versions` in the menu.

![image](https://user-images.githubusercontent.com/66718489/155284537-63ebf721-80ad-4965-9a77-1646d0ac326d.png)

### Expected behavior

![image](https://user-images.githubusercontent.com/66718489/155284740-ff6414b4-cceb-4efb-8782-0e0668d0abf5.png)

### Actual behavior

![image](https://user-images.githubusercontent.com/66718489/155284537-63ebf721-80ad-4965-9a77-1646d0ac326d.png)

### Your environment

- Public source code:
- Public site URL:  https://docusaurus.io/
- Docusaurus version used:
- Environment name and version (e.g. Chrome 89, Node.js 16.4): Google Chrome Version 98.0.4758.102 (Official Build) (64-bit)
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): Windows 10

### Self-service

- [X] I'd be willing to fix this bug myself.

**Comment by Josh-Cena** [comment]
I'm tempted to say that this is working as intended, because the "All versions" is technically not part of the versions dropdown, but an extra link. However, I do think we can spend some effort trying to match the link's route and display that instead.

**Comment by Josh-Cena** [comment]
Actually, this is working as intended. For a typical dropdown item, the label is always static and never changes based on the route; for the docs version dropdown, though, it is able to use the active version name as the label. However, this behavior is a special case and should not be extended to all dropdown items. The "current doc version" is always well-defined and which version name gets displayed never correlates to the route you are on.

**Comment by slorber** [comment]
We could technically have an official Docs Version page with dropdown support, but this is a brand new feature request, not implemented
