### ISSUE TITLE
throw er; // Unhandled 'error' event

### ISSUE THREAD

**Issue by snaveenpandi** [facebook/docusaurus#6757]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

Docusaurus versioning 2.0.0alpha16 to 2.0.0beta15 is working fine at local,if i build i got error ,help to resolved this issue

![Screenshot from 2022-02-25 12-08-49](https://user-images.githubusercontent.com/49641942/155714625-c04b7092-1acc-4afa-bdd2-c39f4224e61b.png)
e

### Steps to reproduce

1.i have docusaurus 2.0.0alpha16
2.i need to convert version 2.0.0beta15,
3.i have following migration setup,its working local,when i try to build i got error

### Expected behavior

build making as usual 

### Actual behavior

i have try to get build error removeDuplicateFontAtRules

### Your environment

- Public site URL:https://docs-dev.mirrorfly.com/
- Docusaurus version used:version 2(2.0.0beta15)
- Environment name and version (e.g. Chrome 98.0.4758.80 , Node.js 14.19):
- Operating system and version (e.g. Ubuntu 20.04.2 LTS):

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by Josh-Cena** [comment]
Hi, we need much more information than that. Where is your source code? How are you sure it's a Docusaurus error? What did you do to migrate? Have you looked through the changelog and migrated through any breaking changes? Your site itself is loading extraordinarily slowly, so I can't inspect anything.

**Comment by Josh-Cena** [comment]
The error doesn't seem related to Docusaurus at all, but is rather a `clean-css` error—maybe your CSS is not valid. Please don't use the GitHub issue tracker as a support forum.
