### ISSUE TITLE
Add guide to deploying with Cloudflare Pages

### ISSUE THREAD

**Issue by mg0716** [facebook/docusaurus#6778]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Description

Currently [Cloudflare Pages](https://pages.cloudflare.com) has a JAMstack deployment offering similar to Netlify and GitHub Pages. It's also already set up to handle Docusaurus sites.

Recently when deploying a Docusaurus site to Cloudflare Pages, I noticed there wasn't any guide available for it.

### Self-service

- [X] I'd be willing to address this documentation request myself.

**Comment by Josh-Cena** [comment]
Cloud flare pages is already documented here: https://docusaurus.io/docs/deployment#deploying-to-cloudflare-pages

We have also added this as our stance:

> For the same concern of up-to-datedness, we have stopped accepting PRs adding new hosting options. You can, however, publish your writeup on a separate site (e.g. your blog, or the provider's official website), and ask us to include a link to your writeup.

**Comment by mg0716** [comment]
Thanks @Josh-Cena and sorry for the bother. It was the last one in the list and I genuinely missed it.
