### ISSUE TITLE
Remove /docs from editUrl

### ISSUE THREAD

**Issue by HiddenCode1337** [facebook/docusaurus#6790]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

Setting routeBasePath to '/' removes /doc from url itself which fits my case.
Issue is it still does not remove /docs from editUrl hence Edit the Page breaks for me.
I'm currently using BitBucket. I've added separate documentation repository as a submodule to docs folder.
Everything else is working fine.

Is there any way this can be fixed ??

### Steps to reproduce

1. Create a docusaurus project.
2. Create a repository which contains all the docs only.
3. In your docusauris repo add git submodule name as docs and reference to the docs repo.
4. `npm run start`
5. In docusaurus.config.js set routeBasePath as '/' and add editUrl
6. Everything will work fine except the Edit This Page because it will add /docs in the url.

### Expected behavior

There should be an option to remove /docs from Edit URL as well or it should work based on routeBasePath or something

### Actual behavior

Cannot remove /docs from editUrl

### Your environment

- Public source code: Not Public
- Public site URL: https://doc-portal-41659.web.app
- Docusaurus version used: 2.0.0-beta.16
- Environment name and version (e.g. Chrome 89, Node.js 16.4): v16.13.1
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): macOS Monterey

### Self-service

- [X] I'd be willing to fix this bug myself.

**Comment by Josh-Cena** [comment]
Hi, if the string edit URL function does not suit your needs, you can use the function form.

```ts
type EditUrlFunction = (params: {
  version: string;
  versionDocsDirPath: string;
  docPath: string;
  permalink: string;
  locale: string;
}) => string | undefined;
```

**Comment by Zamiell** [comment]
Josh,

Given that the official docs have [a whole section on "Docs-only Mode"](https://docusaurus.io/docs/docs-introduction#docs-only-mode), I feel like this is going to be a super-common situation that people run into.

I feel like it should be pretty trivial to add some logic to Docusaurus to handle the case where the end-user adds in a `routeBasePath: '/'` and change the edit URL accordingly.

Failing that, can we at least document on the aforementioned section that if you add the `routeBasePath` field like is suggested, then your edit URLs will break?
