### ISSUE TITLE
URL encoded image paths should be resolvable

### ISSUE THREAD

**Issue by ryh** [facebook/docusaurus#6791]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

I was trying to build html from a public markdown repo, and Images in [docs/controls/border.md ](https://raw.githubusercontent.com/AvaloniaUI/Documentation/master/docs/controls/border.md) was `urlencode`d,
 But looks normal on github [preview](https://github.com/AvaloniaUI/Documentation/blob/master/docs/controls/border.md), and in markdown apps too.

`![](../../.gitbook/assets/image%20%282%29.png)
`
but the file itself on macOS file system was `image (2).png`
so Docusaurus  reports those  when `npm run docusaurus build` 

```
Error: Image .gitbook/assets/image%20%282%29.png used in docs/controls/border.md not found.
    at async Promise.all (index 0)
Error: Image .gitbook/assets/image%20%288%29.png used in docs/controls/border.md not found.
    at async Promise.all (index 0)
...
[ERROR] Client bundle compiled with errors therefore further build is impossible.

```
so docusaurus treat these urlencoded  filenames differently on purpose or not, will users have setting to tell docusaurus build  how to deal with urlencoded filenames?

### Steps to reproduce

1. change image file name to some with `space ( `etc.
2. using urlencoded url in markdown
3. build

### Expected behavior

build ok

### Actual behavior

```
Error: Image .gitbook/assets/image%20%282%29.png used in docs/controls/border.md not found.
    at async Promise.all (index 0)

...
[ERROR] Client bundle compiled with errors therefore further build is impossible.

```

### Your environment

- Public source code: https://github.com/AvaloniaUI/Documentation/blob/master/docs/controls/border.md
- Docusaurus version used:2.0.0-beta.16
- Environment name and version (e.g. Chrome 89, Node.js 16.4):node.js v16.14.0
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): macOS 12.2.1

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by ryh** [comment]
files did place in those path, I edited first filename to `![](../../.gitbook/assets/image (2).png)
` in border.md, and new error report about `image%20%282%29.png` was gone , but `image%20%288%29.png` for comparison still reported as expected 😂.

**Comment by Josh-Cena** [comment]
The fact that GitHub and Markdown renderers both understand this means we should as well. Thanks for reporting!
