### ISSUE TITLE
npx create-docusaurus does not check engines field

### ISSUE THREAD

**Issue by glalloue** [facebook/docusaurus#6843]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

I get Unexpected token '.' error when running docusaurus project creation and get the same error when using new.docusaurus or manual installation

### Steps to reproduce

1. Run
npx create-docusaurus@latest docusaurus-test classic
OR
npm init docusaurus@latest docusaurus-test classic

2. Logs display error

### Expected behavior

docusaurus installation success

### Actual behavior

Logs display :

npx : 42 installé(s) en 2.756s
file:///Users/lallouegeoffrey/.npm/_npx/34580/lib/node_modules/create-docusaurus/lib/index.js:36
    return PackageManagersList.find((packageManager) => process.env.npm_config_user_agent?.startsWith(packageManager));
                                                                                          ^

SyntaxError: Unexpected token '.'
    at Loader.moduleStrategy (internal/modules/esm/translators.js:140:18)

### Your environment

Node : v12.22.10
Npm : 6.14.16
MacOS 12.0.1

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by slorber** [comment]
@glalloue you need Node 14 to run Docusaurus

I don't know why but it seems this declaration in `create-docusaurus` doesn't print you a proper error message 🤷‍♂️ 


```json
  "engines": {
    "node": ">=14"
  }
```

**Comment by Josh-Cena** [comment]
Indeed, it seems `npx` / `yarn create` and friends don't respect the `engines` field...
