### ISSUE TITLE
onPageNav not showing on Safari

### ISSUE THREAD

**Issue by violabg** [facebook/Docusaurus#686]
### Environment

1.0.15

### Steps to Reproduce

(Write your steps here:)

1. open Safari (in my case 11.1) 
2. go to https://docusaurus.io/docs/en/site-creation.html

### Expected Behavior

you should see the onPageNav on the right

### Actual Behavior

there is no onPageNav on the right

### Reproducible Demo

https://docusaurus.io/docs/en/site-creation.html

it works on Chrome and Firefox

**Comment by violabg** [comment]
I found a solution: 

main.css, line 1442

it should be:

```css
@supports ((position: -webkit-sticky) or (position: sticky)) 
```

**Comment by endiliey** [comment]
Feel free to submit a PR ☺
