### ISSUE TITLE
GitHub Codespaces returns 502 when forwarding port

### ISSUE THREAD

**Issue by vedantmgoyal2009** [facebook/docusaurus#6865]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io.
- [x] I have read the console error message carefully (if applicable).

### Description

Docusaurus does not play well with GitHub Codespaces.

On running `npm run start`, the console output shows that the local server has been successfully started and the website is available at `http://localhost:3000/`.

![image](https://user-images.githubusercontent.com/83997633/157020011-6e32031b-b5b3-4af3-9f81-6cccc29940a6.png)

A port is also automatically forwarded but the website is not viewable at the forwarded port of codespaces.

![image](https://user-images.githubusercontent.com/83997633/157020196-b1fc5df9-b2fd-4f1b-88cd-e7df5c336ac4.png)

Also, it has to be noted that nothing shows up in "Running Process" section whereas I think a NodeJS process should appear there.

### Steps to reproduce

1. Run `npm run start`
2. A port `3000` is forwarded automatically but we can't view the website at the URL of the forwarded port.

### Expected behavior

The website should be viewable at the forwarded port.

### Actual behavior

On visiting the forwarded port, we get 502 Bad Gateway.

![image](https://user-images.githubusercontent.com/83997633/157018931-bab90df1-80a8-49f6-910a-a6efce1562fb.png)

### Your environment

- Public source code: `N/A`
- Public site URL: `N/A`
- Docusaurus version used: `2.0.0-beta.17`
- Environment name and version (e.g. Chrome 89, Node.js 16.4): `GitHub Codespaces with NodeJS version 17.6.0`
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): `Ubuntu 21.04 x86_64`

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by Josh-Cena** [comment]
Hi, since I (and I believe most other contributors) have zero knowledge of how GitHub codespaces work, could you outline basically how it works, and why it's a defect of Docusaurus? Stated in the issue template as the first self-checklist:

> - Is this clearly a Docusaurus defect?

502 bad gateway is a server error—it means the server is not properly set up to serve this request, but without more logs, we can't possibly know what went wrong or how we could go about fixing it.

Note that we don't support every form of virtual host out-of-the-box, and it is rather your responsibility to figure out how your host works or how to adapt your Docusaurus app, and only send an issue when you have narrowed it down to a clear place where we can improve on.

**Comment by vedantmgoyal2009** [comment]
If I remember correctly, it is most likely the conflict between the WebSocket[^1] (or the webpack dev server which you just mentioned) and the NGINX server that comes pre-installed on codespaces.

[^1]: I don't know anything about this, just saw it somewhere when I was playing around, debugging it and now can't even find it. If I will find it again, I would update the thread.

**Comment by Josh-Cena** [comment]
Yes, that's also my hypothesis. But until someone comes up and pinpoint where the WDS's web socket goes wrong, the issue remains unactionable.

**Comment by slorber** [comment]
Afaik some users have been successfully using Docusaurus with Codespaces.

Maybe @antonk52 or @kumaraditya303 can help?

Have you tried playing with the `--host` and `--port` CLI options?

`yarn start --host 0.0.0.0` may work? 🤷‍♂️

**Comment by antonk52** [comment]
I haven't tried codespaces. Cannot assist here. Sorry.

**Comment by vedantmgoyal2009** [comment]
Thanks, @slorber. `npm run start -- --host 0.0.0.0` worked like a charm. Thanks a lot🎉🎉🎉🎉🎉🎉🎉

**Comment by Josh-Cena** [comment]
Great! Closing then.

**Comment by vedantmgoyal2009** [comment]
Yeah! Maybe you can also pin it for future users.

**Comment by Josh-Cena** [comment]
I don't think it happens a lot, but if you want to insert one sentence in our documentation about configuring `--host`, PR welcome 👍
