### ISSUE TITLE
Prism is not defined after defining custom language

### ISSUE THREAD

**Issue by ConduciveMammal** [facebook/docusaurus#6872]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

After updating to `2.0.0-beta.17`, my custom language for Prism no longer works in production mode.

I now receive the message `Prism is not defined` coming from the file I created for the language.

```js
  themeConfig: {
    prism: {
      additionalLanguages: ['liquid'],
    },
}
```

`prism-include-languages.js`
```js
/**
 * Copyright (c) Facebook, Inc. and its affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */
import ExecutionEnvironment from '@docusaurus/ExecutionEnvironment';
import siteConfig from '@generated/docusaurus.config';

const prismIncludeLanguages = (PrismObject) => {
  if (ExecutionEnvironment.canUseDOM) {
    const {
      themeConfig: {prism: {additionalLanguages = []} = {}},
    } = siteConfig;
    window.Prism = PrismObject;
    additionalLanguages.forEach((lang) => {
      require(`prismjs/components/prism-${lang}`); // eslint-disable-line
    });
    require('/static/langs/prism-liquid.js');
    delete window.Prism;
  }
};

export default prismIncludeLanguages;
```

`prism-liquid.js` as provided by [Prism repo](https://github.com/PrismJS/prism/blob/master/components/prism-liquid.js)
```js
	Prism.languages.liquid = {
		'comment': {
			pattern: /(^\{%\s*comment\s*%\})[\s\S]+(?=\{%\s*endcomment\s*%\}$)/,
			lookbehind: true
		},
		'delimiter': {
			pattern: /^\{(?:\{\{|[%\{])-?|-?(?:\}\}|[%\}])\}$/,
			alias: 'punctuation'
		},
		'string': {
			pattern: /"[^"]*"|'[^']*'/,
			greedy: true
		},
		'keyword': /\b(?:as|assign|break|(?:end)?(?:capture|case|comment|for|form|if|paginate|raw|style|tablerow|unless)|continue|cycle|decrement|echo|else|elsif|in|include|increment|limit|liquid|offset|range|render|reversed|section|when|with)\b/,
		'object': /\b(?:address|all_country_option_tags|article|block|blog|cart|checkout|collection|color|country|country_option_tags|currency|current_page|current_tags|customer|customer_address|date|discount_allocation|discount_application|external_video|filter|filter_value|font|forloop|fulfillment|generic_file|gift_card|group|handle|image|line_item|link|linklist|localization|location|measurement|media|metafield|model|model_source|order|page|page_description|page_image|page_title|part|policy|product|product_option|recommendations|request|robots|routes|rule|script|search|selling_plan|selling_plan_allocation|selling_plan_group|shipping_method|shop|shop_locale|sitemap|store_availability|tax_line|template|theme|transaction|unit_price_measurement|user_agent|variant|video|video_source)\b/,
		'function': [
			{
				pattern: /(\|\s*)\w+/,
				lookbehind: true,
				alias: 'filter'
			},
			{
				// array functions
				pattern: /(\.\s*)(?:first|last|size)/,
				lookbehind: true
			}
		],
		'boolean': /\b(?:false|nil|true)\b/,
		'range': {
			pattern: /\.\./,
			alias: 'operator'
		},
		// https://github.com/Shopify/liquid/blob/698f5e0d967423e013f6169d9111bd969bd78337/lib/liquid/lexer.rb#L21
		'number': /\b\d+(?:\.\d+)?\b/,
		'operator': /[!=]=|<>|[<>]=?|[|?:=-]|\b(?:and|contains(?=\s)|or)\b/,
		'punctuation': /[.,\[\]()]/,
		'empty': {
			pattern: /\bempty\b/,
			alias: 'keyword'
		},
	};

	Prism.hooks.add('before-tokenize', function (env) {
		var liquidPattern = /\{%\s*comment\s*%\}[\s\S]*?\{%\s*endcomment\s*%\}|\{(?:%[\s\S]*?%|\{\{[\s\S]*?\}\}|\{[\s\S]*?\})\}/g;
		var insideRaw = false;

		Prism.languages['markup-templating'].buildPlaceholders(env, 'liquid', liquidPattern, function (match) {
			var tagMatch = /^\{%-?\s*(\w+)/.exec(match);
			if (tagMatch) {
				var tag = tagMatch[1];
				if (tag === 'raw' && !insideRaw) {
					insideRaw = true;
					return true;
				} else if (tag === 'endraw') {
					insideRaw = false;
					return true;
				}
			}

			return !insideRaw;
		});
	});

	Prism.hooks.add('after-tokenize', function (env) {
		Prism.languages['markup-templating'].tokenizePlaceholders(env, 'liquid');
	});
```

### Reproducible demo

https://codesandbox.io/s/prism-docusaurus-liquid-hznyib?file=/docs/intro.md

### Steps to reproduce

Add Liquid as a custom language and define it in the config.

### Expected behavior

To run with LIquid highlighting in production mode

### Actual behavior

Console message stating `Prism is not defined`.

<img width="662" alt="image" src="https://user-images.githubusercontent.com/18140157/157137539-46603242-7782-4288-8736-372b6db13d64.png">
<img width="850" alt="image" src="https://user-images.githubusercontent.com/18140157/157137716-6a2fb9a8-1bb6-447a-ad42-2a255e1f4d27.png">

### Your environment

- Public source code:
- Public site URL:
- Docusaurus version used:
- Environment name and version (e.g. Chrome 89, Node.js 16.4):
- Operating system and version (e.g. Ubuntu 20.04.2 LTS):

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by Josh-Cena** [comment]
Could you try removing the `delete window.Prism;` line?

**Comment by ConduciveMammal** [comment]
Ohh! Removing that line worked perfectly! Thanks very much.

The project was stale for a long time so it was a large update from .6 to .17 I believe, but yeah the highlighting worked fine prior to that.

**Comment by ConduciveMammal** [comment]
Also, can you tell me if `/static/langs` is the best directory to place custom languages?

**Comment by Josh-Cena** [comment]
> Also, can you tell me if `/static/langs` is the best directory to place custom languages?

Doesn't matter a lot—the specialty of `static` is that the content is copied to the build output, so if you don't need the source in your website's bundle, you can put it somewhere else so it's only included once. You can put it anywhere that Webpack can `require`, for example, `@site/src/langs/`.

**Comment by Josh-Cena** [comment]
I'll close this as wontfix and assume that the error itself is resolved with removing `delete window.Prism;`

**Comment by apfelbox** [comment]
The line is now 

```typescript
delete (globalThis as Global & {Prism?: typeof PrismNamespace}).Prism;
```

and is included in `@docusaurus/theme-classic`:

https://github.com/facebook/docusaurus/blob/main/packages/docusaurus-theme-classic/src/theme/prism-include-languages.ts#L32

How are you supposed to remove this file, without monkey patching in `node_modules`?

**Comment by slorber** [comment]
You can use patch-package for temporarily patching your favorite libs when needed

https://github.com/ds300/patch-package

Will catch-up later and try to figure out the problem

**Comment by apfelbox** [comment]
Great, thanks! 🙌

swizzling the file works for now, as immediate fix

**Comment by artyrcheek** [comment]
> Could you try removing the `delete window.Prism;` line? Also, was it working in previous versions?

Thanks that worked for me also 🙌🏻
