### ISSUE TITLE
[ERROR] Error: The docs folder does not exist for version "current". A docs folder is expected to be found at docs.

### ISSUE THREAD

**Issue by Chasen-Zhang** [facebook/docusaurus#6896]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [ ] I have tried the `npm run clear` or `yarn clear` command.
- [ ] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io.
- [ ] I have read the console error message carefully (if applicable).

### Description

npm start =>
[ERROR] Error: The docs folder does not exist for version "current". A docs folder is expected to be found at docs.
on the console

### Steps to reproduce

1.npm run start

### Expected behavior

no error

### Actual behavior

[ERROR] Error: The docs folder does not exist for version "current". A docs folder is expected to be found at docs.

### Your environment

- Public source code:
- Public site URL:
- Docusaurus version used:
- Environment name and version (e.g. Chrome 89, Node.js 16.4):
- Operating system and version (e.g. Ubuntu 20.04.2 LTS):

### Self-service

- [X] I'd be willing to fix this bug myself.

**Comment by Josh-Cena** [comment]
Sorry, without a repro, there's nothing we can help you with. We have continuously stressed in the issue template that PLEASE GIVE A REPRO and PLEASE DON'T USE GITHUB FOR SUPPORT. I'm closing this, and should you have further information to provide, feel free to reach out on Discord.
