### ISSUE TITLE
Bug: Migrate bin/index.mjs rewritten as index.js , causing CLI to fail

### ISSUE THREAD

**Issue by sambacha** [facebook/docusaurus#6897]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

Bug: Migrate bin/index.mjs rewritten as index.js , causing CLI to fail

### Steps to reproduce

install migrate

### Expected behavior

to run migrate

### Actual behavior

fails to load as esm module needs to be .mjs not .js

### Your environment

osx 10.15

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by Josh-Cena** [comment]
Thanks for the report! This has already been fixed. Could you try with `@docusaurus/migrate@canary`?

**Comment by slorber** [comment]
Oh I see, that's why I see it working for me :D

**Comment by Josh-Cena** [comment]
Going to close as resolved. The migration CLI isn't used a lot these days anyways
