### ISSUE TITLE
pagination permalink includes pagination link double slash 

### ISSUE THREAD

**Issue by heowc** [facebook/docusaurus#6917]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

I upgraded from beta-15 to beta-17 and found a bug during this. The expected PR is #6221.

If `basePageUrl` is `/`, double slash is inserted.

See link: https://github.com/facebook/docusaurus/pull/6221/files#diff-34c6928dee2cfb000cac2409e1279076a6a8b39cc7540cb53ba65bdbb42c6903R75

### Reproducible demo

https://heowc.dev/

### Steps to reproduce

check next page link

### Expected behavior

go to next page

### Actual behavior

go to `page/2`

### Your environment

- Public source code:
- Public site URL: 
- Docusaurus version used:
- Environment name and version (e.g. Chrome 89, Node.js 16.4):
- Operating system and version (e.g. Ubuntu 20.04.2 LTS):

### Self-service

- [X] I'd be willing to fix this bug myself.

**Comment by Josh-Cena** [comment]
Thanks for reporting! We have a utility method in `@docusaurus/utils` called `normalizeUrl`, so if you want to send a PR, just refactor the method to use that instead.

**Comment by heowc** [comment]
> Thanks for reporting! We have a utility method in `@docusaurus/utils` called `normalizeUrl`, so if you want to send a PR, just refactor the method to use that instead.

Thanks for the quick response. I have already prepared the relevant PR. 😄
