### ISSUE TITLE
Admonition Documentation wrong or misleading

### ISSUE THREAD

**Issue by LuciferUchiha** [facebook/docusaurus#6919]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

In the [documentation](https://docusaurus.io/docs/markdown-features/admonitions), it states that "basic markdown syntax" for admonitions is supported. For me, this would mean the following [syntax](https://python-markdown.github.io/extensions/admonition/) should work this is also how it works in plugins for vscode like [this](https://github.com/qjebbs/vscode-markdown-extended). However, when trying this out it didn't work. See below. Am I doing something wrong or is the documentation misleading?

<img width="1273" alt="image" src="https://user-images.githubusercontent.com/47121010/158434930-eff4d6bc-f81d-44e7-b875-461d336d5c49.png">

### Steps to reproduce

1. create new stackblitz
2. add the following to a markdown page 
```markdown
!!! note "Title"

    This is content

```

### Expected behavior

The admonition is not rendered.

### Actual behavior

The admonition should be rendered.

### Your environment

- Public source code: https://stackblitz.com/edit/github-uetkkd?file=docs%2Fintro.md
- Public site URL:
- Docusaurus version used: 
- Environment name and version (e.g. Chrome 89, Node.js 16.4):
- Operating system and version (e.g. Ubuntu 20.04.2 LTS):

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by duanwilliam** [comment]
as the documentation page states, Docusaurus uses colons (`:`), not exclamation points for admonitions. this syntax is also more compatible with the directive syntax which may become standardized in CommonMark (https://talk.commonmark.org/t/generic-directives-plugins-syntax/444)

**Comment by Josh-Cena** [comment]
Yes, I'm not sure where the confusion comes from or how we can improve the wording. The documentation states:

> In addition to the basic Markdown syntax, we use [remark-admonitions](https://github.com/elviswolcott/remark-admonitions) alongside MDX to add support for admonitions.

"In addition to the basic Markdown syntax" means admonitions are not basic Markdown syntax😅 There's nothing as "standard admonition", and as @duanwilliam pointed out, we are probably closer to the would-be standard than `!!!`.

Documentation is meant to be "followed", not to be "inferred". Anything that's not explicitly stated/specced should not be taken as guaranteed behavior.
