### ISSUE TITLE
Error on development when changing baseUrl

### ISSUE THREAD

**Issue by joshuaalpuerto** [facebook/Docusaurus#693]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

### Environment
Node: 8.9.1
Docusaurus: 1.1.1

(Docusaurus version via `npm outdated docusaurus` or `yarn outdated docusaurus`, OS, Node, npm, yarn)

### Steps to Reproduce

I followed the step on setting your landing page: [Docs landing Page](https://docusaurus.io/docs/en/site-creation.html#docs-landing-page). Which works well. However, the problem is when you change your `baseUrl` for deployment:
```js
const siteConfig = {
  title: '<Project title>' /* title for your website */,
  tagline: '<Project tagline>',
  url: 'https://<org>.github.io' /* your website url */,
  baseUrl: '/<project>/' /* base url for your project */,
  // For github.io type URLs, you would set the url and baseUrl like:
  //   url: 'https://facebook.github.io',
  //   baseUrl: '/test-site/',
```
It works on build, but when I try to `yarn start` it gives me an error:
<img width="276" alt="screen shot 2018-05-24 at 12 38 11 am" src="https://user-images.githubusercontent.com/7126484/40438484-c64283f4-5eea-11e8-93e4-fefa2239a3f8.png">

If I put back the `baseUrl: '/'` it will work.

**Workaround**: make `baseUrl: '/'` when updating the doc and put back the `baseUrl: '/project/'` url when done.

### Expected Behavior

It should redirect to my `doc` page  as expected without switching `baseUrl` for **development** and **production**

**Comment by endiliey** [comment]
@joshuaalpuerto: hi, do you have a repo we can clone to reproduce the issue?

**Comment by joshuaalpuerto** [comment]
@endiliey 
Sorry didn't provide a repro. Here is the repro, hope this help. 

https://github.com/joshuaalpuerto/repro-docusaurus

Cheers!

**Comment by joshuaalpuerto** [comment]
If someone can guide me. I would like to contribute :)

**Comment by endiliey** [comment]
`yarn start` or `npm start` basically use Express to serve the files.

You can check
https://github.com/facebook/Docusaurus/blob/master/lib/server/server.js

**Comment by joshuaalpuerto** [comment]
Thanks! I will take a look on this.

**Comment by endiliey** [comment]
hi @joshuaalpuerto, did you manage to resolve the issue ?
Sorry for the delayed response. I just got the chance to try your repo and I think there is no issue with the current server implementation.

When you change your `baseUrl` to `/project1/`, this means that instead of `localhost:3000`, you should access it at `localhost:3000/project1`

<img width="954" alt="doc" src="https://user-images.githubusercontent.com/17883920/40573389-69421e84-60f3-11e8-9e75-28bb42b69295.PNG">

**Comment by joshuaalpuerto** [comment]
@endiliey  No worries! I was able to take a look at it yesterday for a limited time. But you are correct, it is accessible by adding the `baseUrl`. But shouldn't be automatic when redirecting to to the docs page as per [documentation](https://docusaurus.io/docs/en/site-creation.html#docs-landing-page). Perhaps the `baseUrl` should be automatically added. What do you think?

**Comment by endiliey** [comment]
Actually this only happen when we use static `index.html`, you can try cloning Docusaurus repo, change `baseUrl` and `yarn start` will still work fine. 

I'm not the maintainer of this repo, but that might be a good idea
Quick implementation:
```js
const siteConfig = require(CWD + '/siteConfig.js')
const host = `http://localhost:${port}${siteConfig.baseUrl}`;
```
https://github.com/facebook/Docusaurus/blob/b7be85843af2a07ead183dd8a467ebcf83e9a3e3/lib/start-server.js#L65-L66

**Comment by joshuaalpuerto** [comment]
I will try this later and let you know! Thanks for your help!

**Comment by endiliey** [comment]
Guess we can close this now

**Comment by joshuaalpuerto** [comment]
[**UPDATE**]

Now the issue is when you type in `http://localhost:3000` you will not be redirected. Unless you type in the `host` and the `baseUrl` altogether `http://localhost:3000/project1`.

**Comment by endiliey** [comment]
I think that's the right behavior. If you are using non default `/` as `baseUrl`, e.g: `/project1/` then you should not access it without `baseUrl` or even manually type it.

**Comment by joshuaalpuerto** [comment]
thats what I actually meant when I said it should be automatically. Hmm, shouldn't it be base on your `baseUrl`?

**Comment by endiliey** [comment]
Feel free to submit a PR for it 😄 

Adding this for your reference on where to modify
https://github.com/facebook/Docusaurus/blob/b7be85843af2a07ead183dd8a467ebcf83e9a3e3/lib/server/server.js#L530-L533

**Comment by joshuaalpuerto** [comment]
Thanks! Im actually checking the `server.js` now. Then I'll get back once I figure this out. 😄

**Comment by joshuaalpuerto** [comment]
Hi @endiliey, 

I was able to make changes on [server.js](https://github.com/joshuaalpuerto/Docusaurus/blob/81cce43c7f591d00ed248cc35387ce168a5a896e/lib/server/server.js#L534-L535)

Adding `baseUrl`:

```js
app.get(/\/[^\.]*\/?$/, (req, res) => { 
     const siteConfig = require(CWD + '/siteConfig.js')
    let slash = req.path.toString().endsWith('/') ? '' : '/';
    const url = 'http://localhost:' + port + siteConfig.baseUrl + req.path + slash + 'index.html'
    request.get(
      url,
       ...
```

You can actually check my [repro](https://github.com/joshuaalpuerto/repro-docusaurus). I point the `docusaurus` package to my forked repo. Implement changes [needed](https://github.com/joshuaalpuerto/repro-docusaurus#update) and it works. You can type in `http://localhost:3000` and it will auto redirect to the `baseUrl` you change. Please let me know if this is something that I can PR. 😃 

Cheers!

**Comment by endiliey** [comment]
@joshuaalpuerto 
I don't own this repo but I believe that this repo is `PR Friendly` 👍 
Feel free to submit one. No PR is too small if it's useful.

I can give some advice though, that changes in your code might introduce a bug. What if my req.path is `baseUrl/xxxx`, it will become `baseUrl/baseUrl/xxx`

**Comment by joshuaalpuerto** [comment]
You're correct. I was able to test only my use-case.  I will keep on checking then. Thanks!

**Comment by endiliey** [comment]
Hi @joshuaalpuerto, any progress on this?

**Comment by joshuaalpuerto** [comment]
Hello @endiliey, I'm trying to understand the inner workings of the routes but I got busy this past days. However, I was able to try using `/project1/subproject/` for `baseUrl` and it seems working just fine.

**Comment by endiliey** [comment]
Alright @joshuaalpuerto . I'm closing this issue for now as it seems it's been working for you. Feel free to submit a PR on the improved redirect when you have the time.
