### ISSUE TITLE
Not able to override the H1 font size

### ISSUE THREAD

**Issue by asksazz** [facebook/docusaurus#6934]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

The H1 font size is too large for mobile devices. Is there a way to override it?

I tried overriding the below variable in custom.css

--ifm-h1-font-size: 2rem;

But this doesn't override it. 

### Steps to reproduce

Generic Behaviour. Not able to override the H1 font size

### Expected behavior

 Overriding the below property in custom.css should set H1 font-size to 2rem.

--ifm-h1-font-size: 2rem;

### Actual behavior

I tried overriding the below variable in custom.css

--ifm-h1-font-size: 2rem;

But this doesn't override it. 

### Your environment

- Public source code:
- Public site URL:
- Docusaurus version used:
- Environment name and version (e.g. Chrome 89, Node.js 16.4):
- Operating system and version (e.g. Ubuntu 20.04.2 LTS):

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by slorber** [comment]
This h1 css variable is not really useful because it is overridden locally by the docs and blog custom CSS

I'll make sure this kind of title customization is easier in the future

If you want to customize this heading now, there's no other choice than using a custom CSS selector or swizzling, and this CSS var won't work.

**Comment by Josh-Cena** [comment]
I think the recommended practice is to use `h1 { font-size: 1rem !important; }` anyways, it always works and it looks more robust
