### ISSUE TITLE
Custom HTML element disappears on refresh

### ISSUE THREAD

**Issue by dgateles** [facebook/docusaurus#6939]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [ ] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [x] I have tried creating a repro with https://new.docusaurus.io.
- [x] I have read the console error message carefully (if applicable).

### Description

The assets are being served in the project's static folder. When loading the documentation page, navigating through the side menu, the files are displayed normally (svg files). When reloading the page, the files are no longer found. Looking at the URL, at first the files are loaded from `/project/assets/icon.svg`. After reloading the page, the files are fetched from `/project/docs/assets/icon.svg` and consequently not found.

### Steps to reproduce

1. Defined in docusaurus.config.js - `staticDirectories: ['static']`
2. Add svg assets in `static/assets` folder
3. Fetched icons on mdx doc file
4. Pressed F5 on doc page, icons going to 404

### Expected behavior

Icons would appear normally

### Actual behavior

404 not found at fetched icons after page reload

### Your environment

- Public source code:
- Public site URL:
- Docusaurus version used:
- Environment name and version (e.g. Chrome 89, Node.js 16.4):
- Operating system and version (e.g. Ubuntu 20.04.2 LTS):

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by Josh-Cena** [comment]
Hi, can I have a repro, as well as your Docusaurus version? Our website uses every way to import an SVG, and I can't reproduce this anywhere. Have you checked our guides on serving static assets? https://docusaurus.io/docs/static-assets

**Comment by dgateles** [comment]
Hello!

Version: 2.0.0-beta.17
Here is: https://codesandbox.io/s/shy-surf-ov0bp9

**Comment by dgateles** [comment]
Video: http://cloud.movavi.com/show/02c4cd0d-a25f-4096-bbe7-bf992c787e4c

Check if has a heart.svg inside svg folder in your fork
The pre-start script is just to copy svg`s to static/svg folder, nothing more

**Comment by Josh-Cena** [comment]
Thanks! It's also showing up locally. I would check it out in detail tomorrow.
