### ISSUE TITLE
Unable to use tsx files in /pages

### ISSUE THREAD

**Issue by lanegoolsby** [facebook/docusaurus#6940]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

The router appears to crash when using TSX files in the /pages directory. This issue replicates even on a brand new project using `npx create-docusaurus@latest my-website classic --typescript`

The page displays this error message:

```
val[keyPath[(keyPath.length - 1)]] is undefined
```

If I rename the file to .js then it works as expected. It would appear that the file filter is not including `.tsx` files.

The content of the TSX file is below:
```
import Layout from '@theme/Layout';
import React from 'react';

export const Search: React.FC = props => {
    return (
        <>
            <Layout title={'Search'} description="Search"></Layout>
        </>
    );
}
```

### Steps to reproduce

1. Create /pages/search.tsx
2. Paste the contents from the description
3. Navigate to localhost:3000/search

### Expected behavior

The page should render

### Actual behavior

![image](https://user-images.githubusercontent.com/10758510/159072901-f06aacf4-c0c6-40ca-be7a-f605f28276d9.png)

From the browser console:
```
Uncaught TypeError: val[keyPath[(keyPath.length - 1)]] is undefined
    render ComponentCreator.js:57
    render ComponentCreator.js:57
    render ComponentCreator.js:57
    render index.js:262
    React 17
    <anonymous> clientEntry.js:22
```
```
The above error occurred in the <LoadableComponent> component:

LoadableComponent@webpack-internal:///./node_modules/react-loadable/lib/index.js:138:32
Route@webpack-internal:///./node_modules/react-router/esm/react-router.js:448:29
Switch@webpack-internal:///./node_modules/react-router/esm/react-router.js:650:29
Route@webpack-internal:///./node_modules/react-router/esm/react-router.js:448:29
PendingNavigation@webpack-internal:///./node_modules/@docusaurus/core/lib/client/PendingNavigation.js:18:180
C@webpack-internal:///./node_modules/react-router/esm/react-router.js:705:31
Root@webpack-internal:///./node_modules/@docusaurus/core/lib/client/theme-fallback/Root/index.js:17:35
BrowserContextProvider@webpack-internal:///./node_modules/@docusaurus/core/lib/client/exports/browserContext.js:19:136
DocusaurusContextProvider@webpack-internal:///./node_modules/@docusaurus/core/lib/client/exports/docusaurusContext.js:19:505
ErrorBoundary@webpack-internal:///./node_modules/@docusaurus/core/lib/client/exports/ErrorBoundary.js:13:96
App
Router@webpack-internal:///./node_modules/react-router/esm/react-router.js:79:30
BrowserRouter@webpack-internal:///./node_modules/react-router-dom/esm/react-router-dom.js:57:35
r@webpack-internal:///./node_modules/react-helmet-async/lib/index.module.js:16:7305

React will try to recreate this component tree from scratch using the error boundary you provided, ErrorBoundary.
```

### Your environment

- Public source code:
- Public site URL:
- Docusaurus version used:
- Environment name and version (e.g. Chrome 89, Node.js 16.4):
- Operating system and version (e.g. Ubuntu 20.04.2 LTS):

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by Josh-Cena** [comment]
Hi, your page exports a named export, while the pages plugin expects a default export. Try changing it to:

```tsx
export default function Search(props: Props) {
    return (
        <>
            <Layout title={'Search'} description="Search"></Layout>
        </>
    );
}
```

However, even with your repro steps, I can't get the same error. I get:

<img width="892" alt="image" src="https://user-images.githubusercontent.com/55398995/159100232-ebb39ceb-9d2c-461c-8c97-7b61eca7fcd5.png">

which seems a lot more reasonable. Could you provide a repro for which your error can be reproduced? That would help us improve the error message.

---

On an unrelated note, you are _strongly_ advised against using the `React.FC` type. See https://github.com/facebook/create-react-app/pull/8177#issue-353062710

**Comment by lanegoolsby** [comment]
> pages plugin expects a default export

This was the answer, its working as expected now.

> On an unrelated note, you are strongly advised against using the React.FC type.

😮  TIL, thanks for the tip!
