### ISSUE TITLE
Fix Dependabot transitive dependencies - Regular Expression Denial of Service in trim

### ISSUE THREAD

**Issue by wilson-mar** [facebook/docusaurus#6954]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

Please help us fix GitHub Dependabot message we got:
"cannot update trim to a non-vulnerable version"
The latest possible version that can be installed is 0.0.1 because of the following conflicting dependencies:

@docusaurus/core@2.0.0-beta.17 requires trim@0.0.1 via a transitive dependency on remark-parse@8.0.3
@cmfcmf/docusaurus-search-local@0.10.0 requires trim@0.0.1 via a transitive dependency on remark-parse@8.0.3
@docusaurus/preset-classic@2.0.0-beta.17 requires trim@0.0.1 via a transitive dependency on remark-parse@8.0.3
@docusaurus/theme-live-codeblock@2.0.0-beta.17 requires trim@0.0.1 via a transitive dependency on remark-parse@8.0.3
The earliest fixed version is 0.0.3.

### Reproducible demo

This issue isn't about the UI

### Steps to reproduce

Sorry, we're using Docusaurus in a private repo.

### Expected behavior

GitHub would stop issuing Dependabot alerts about this on our repo.

### Actual behavior

GitHub is issuing alert "Dependabot cannot update trim to a non-vulnerable version"

### Your environment

- Public source code:
- Public site URL:
- Docusaurus version used:
- Environment name and version (e.g. Chrome 89, Node.js 16.4):
- Operating system and version (e.g. Ubuntu 20.04.2 LTS):

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by Josh-Cena** [comment]
Please see https://github.com/facebook/docusaurus/issues/6394
