### ISSUE TITLE
Lazy load external images

### ISSUE THREAD

**Issue by rilwis** [facebook/docusaurus#6965]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [x] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

I see lazy load was merged into version beta 16. However, I'm using version beta 17 and see it doesn't work for external images from imgur.com.

### Reproducible demo

https://meta-box-docs-v2.netlify.app/custom-fields/

### Steps to reproduce

Just visit a page with many images, the images below the fold are loaded immediately.

### Expected behavior

The images below the fold should be lazy loaded.

### Actual behavior

The images below the fold are loaded immediately.

### Your environment

- Public source code: https://github.com/wpmetabox/docsv2/
- Public site URL: https://meta-box-docs-v2.netlify.app
- Docusaurus version used: 2.0.0-beta.17
- Environment name and version (e.g. Chrome 89, Node.js 16.4): Safari, Chrome and Firefox latest versions
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): MacOS

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by Josh-Cena** [comment]
I wouldn't call this a regression, because never have we transformed Markdown images that don't appear internal. I do believe this looks like a useful extension to make.
