### ISSUE TITLE
Default Docusaurus blog title size is really big on mobile

### ISSUE THREAD

**Issue by Pierre-Gilles** [facebook/docusaurus#7003]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

Hey! First thanks for Docusaurus 🙂

I'm using this project on [Gladys Assistant](https://gladysassistant.com/) and I'm really happy about it! 

I noticed that the blog titles are reaaaally big on mobile, and it doesn't look really clean by default.

On Docusaurus website ([here](https://docusaurus.io/blog/2018/04/30/How-I-Converted-Profilo-To-Docusaurus)), on an iPhone 12 : 

![IMG_0800](https://user-images.githubusercontent.com/7365207/160149664-5cc6017d-4f27-436f-a87b-c3ee0eecd001.PNG)

On one of our blog post ([here](https://gladysassistant.com/blog/gladys-assistant-4-8-with-calendar-in-scenes/)) : 

![IMG_0801](https://user-images.githubusercontent.com/7365207/160149993-6007012e-56b9-4099-9afb-fa1e6d4e5962.PNG)

Do you think we could change the default blog article title size ? 

I'm willing to do a PR if you think it's ok to change it :) 

Thanks for your answer ! 🙏

Edit: Sorry I realized I put this as bug, it's not really a bug! 

### Steps to reproduce

Go to this page on mobile : https://docusaurus.io/blog/2018/04/30/How-I-Converted-Profilo-To-Docusaurus

### Expected behavior

Small title

### Actual behavior

Big title

### Self-service

- [X] I'd be willing to fix this bug myself.

**Comment by Josh-Cena** [comment]
I agree with that 👍

**Comment by Pierre-Gilles** [comment]
Nice! I'll try doing a PR and will go back to you :)

**Comment by tisonkun** [comment]
@slorber @Pierre-Gilles May I ask if I can customize the size without hacking in to swizzle components?

**Comment by slorber** [comment]
> @slorber @Pierre-Gilles May I ask if I can customize the size without hacking into swizzle components?

This probably works:

```css
html.plugin-blog h2, 
html.plugin-blog.blog-post-page h1 {
    font-size: 1rem;
}
```

**Comment by tisonkun** [comment]
@slorber Thank you! It works now :)
