### ISSUE TITLE
Open respective tab item with URL query string

### ISSUE THREAD

**Issue by YOU54F** [facebook/docusaurus#7008]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Description

Can multi-language support code blocks, support anchors which allow the anchored code block to open?

https://docusaurus-five-rho.vercel.app/docs/markdown-features/code-blocks#multi-language-support-code-block

For example, I would like to be able to offer a user a link, either via the docusaurus side bar, or directly, that allows them to jump to a language specific block.

EG clicking Java https://docusaurus-five-rho.vercel.app/docs/markdown-features/code-blocks#java would navigate to that part of the page and make that tab visible.

![Screenshot 2022-03-25 at 20 55 52](https://user-images.githubusercontent.com/19932401/160199608-4d900b81-19b6-4af7-a304-20245fad1711.png)

- The anchor link from the side bar will only work if the anchor is visible
- Hotlinking via the full url plus anchor if in a code block, will not move to the code block even if the anchor is in a visible tab.

This might just be a limitation of my HTML scripting foo, as is possible, if so, please show me the way!

### Motivation

we support an open source project which has a significant feature set across multiple language implementations.

I would like to be able to connect this up with [syncing tab choices ](https://docusaurus-five-rho.vercel.app/docs/markdown-features/tabs#syncing-tab-choices) as it would enable readers to ensure they only see information that is relevant to them, in their preferred programming language.

### Have you tried building it?

Yes, 
See example from docusaurus master, only addition is https://github.com/YOU54F/docusaurus/commit/0e297b966a34e68c4d612a42b1ad3f634d923395 to insert anchors on each of the code block tabs.

Deployed here via vercel however the headers aren't showing 

https://docusaurus-you54f.vercel.app/docs/markdown-features/code-blocks

You can clone my master branch `g clone git@github.com:YOU54F/docusaurus.git`

`npm install && cd website && npm start`

Headers added and visible locally

![Screenshot 2022-03-25 at 21 47 59](https://user-images.githubusercontent.com/19932401/160207357-a99bbdf6-e810-4e39-be59-9700f8cdff54.png)

clicking from TOC will anchor to Javascript tab

![Screenshot 2022-03-25 at 21 48 05](https://user-images.githubusercontent.com/19932401/160207433-95db8bfa-7480-4e43-883f-93b41ec629d3.png)

If java tab is pre selected and therefore visible

![Screenshot 2022-03-25 at 21 48 14](https://user-images.githubusercontent.com/19932401/160207486-54442bab-ef38-4774-9764-b93886eb4a98.png)

clicking from TOC will anchor to Java tab

![Screenshot 2022-03-25 at 21 48 20](https://user-images.githubusercontent.com/19932401/160207521-b3c039ae-a9a1-4fe2-9579-0c2830e4c24d.png)

Hot linking to any of the code block anchors
 http://localhost:3000/docs/markdown-features/code-blocks#javascript even the visible javascript one will take the user to the top of the page. 
 

### Self-service

- [X] I'd be willing to contribute this feature to Docusaurus myself.

**Comment by Josh-Cena** [comment]
It's also here: https://docusaurus.canny.io/feature-requests/p/link-to-tab

I think implementing one would be relatively easy. In addition to reading local storage we would also read URL, probably search params instead of hash.

**Comment by Celtech** [comment]
Not to add noise, but I second this feature request, would be a nice addition!

**Comment by andrewkolos** [comment]
Hey. I'd like to clarify the ask here. I'll use a hypothetical, slightly modified version of the [Multi-Language Code Block](https://docusaurus-five-rho.vercel.app/docs/markdown-features/code-blocks#multi-language-support-code-blocks) example from the original post.

````tsx
import Tabs from '@theme/Tabs';
import TabItem from '@theme/TabItem';

<Tabs id="my-multi-language-code-block"> // Notice the new ID here.
<TabItem value="js" label="JavaScript">

```js
function helloWorld() {
  console.log('Hello, world!');
}
```

</TabItem>
<TabItem value="py" label="Python">

```py
def hello_world():
  print("Hello, world!")
```

</TabItem>
<TabItem value="java" label="Java">

```java
class HelloWorld {
  public static void main(String args[]) {
    System.out.println("Hello, World");
  }
}
```

</TabItem>
</Tabs>
````

Then, we could give an anchor link that shows the tab of our choice with something like: `https://docusaurus-five-rho.vercel.app/docs/markdown-features/code-blocks#my-multi-language-support-code-block&activeTabItem=py`. This page would navigate to `my-multi-language-code-block` with the Python tab shown. Is this what we are looking for?

I think this would work, but I can imagine scenarios were people would like to link a section heading just above a `Tabs` component while also showing a specific tab. This could result in a better UX in scenarios were the section text that precedes the `Tabs` is important for introducing it. However, I imagine a separate feature request Issue would be appropriate for this. I digress.

**Comment by lorensr** [comment]
Hi @YOU54F, great FR, appreciate you submitting! Wanted to check whether you're still up for submitting a PR for this?

**Comment by Josh-Cena** [comment]
If anyone wants to try their hands on this, feel free to.

The UX is a bit hard to design. For example, a user opens a URL with a query, and toggles the tabs. should the query be persisted? Should it be erased? Local storage and query—which takes priority? Do we need to automatically scroll to that tab like anchors do? If so, how would synced tab groups work?

**Comment by YOU54F** [comment]
Hey @lorensr / @Josh-Cena I would love to, as it would be such a valuable addition to our docs, but I am across a bit too much at the moment.

Saying that I would be happy working with you all, and having a good think about the design.

Do you guys just work across here or do you have a slack space,

**Comment by lorensr** [comment]
Re: UX, here are my personal prefs:

- User opens `/page?tab=javascript#heading`
- `JavaScript` tab group is opened (regardless of LocalStorage)
- If there isn't an existing LocalStorage tab choice saved, save it as `JavaScript`. If there is, don't overwrite it.

> Do we need to automatically scroll to that tab like anchors do? 

I wouldn't change the default browser behavior of setting scrollTop to `#heading` location. Unless that doesn't work for headings inside the tab? In which case I'd add code to enable that.

**Comment by lorensr** [comment]
> I'm mainly thinking about /page?tab=javascript—do we scroll to the first tab group on the page with a JavaScript option?

I'd say no, for flexibility's sake. If we autoscroll, then link creator can't link to the top of the page. Versus if we don't, then link creator can link to the relevant heading if they want to.

> Also note that there may be multiple tab groups on one page with the same choice name, but are not necessarily synced.

Perhaps:

`?tab=javascript`

Changes all tabs that have a `/javascript/i` value to that value.

`?tab=javascript&id=foo`

Changes all `<Tabs>` with `id=foo` or `groupId=foo`.

**Comment by lorensr** [comment]
On a separate note, I think it would be nice to:

Whenever a tab is clicked, if there's a way to identify it (by `<Tabs>` `id` or `groupId`), put in the URL (w/ history replace state so it doesn't affect history) so you can just grab the URL from the address bar, and it links to what you're looking at.

**Comment by Josh-Cena** [comment]
Yes, another big part of the UX that I'm unsure of is _when_ the querystring should be physically appended to the current location so it can be copied. I'm thinking about double-clicking but that's quite an implicit UX. Would appreciate it if anyone has an example of a site with this feature.

If no-one wants to take a shot, I'll probably work on this in July because I plan to use this ourselves for https://docusaurus.io/docs/deployment.

**Comment by lorensr** [comment]
I'd be happy with always adding on every single click. I don't remember any sites with this exact tab-maintenance feature, but plenty of apps edit the URL on each click so that you'll end up in the same state on reload or link copy/paste. A couple that come to mind are Gmail and Mint.

**Comment by slorber** [comment]
Also remember that we have to consider React hydration: on first page load, the correct tab must be selected even before React hydrates (ie you can't just useEffect, you also have to inline some JS to handle that, similarly to the dark mode)

What we don't want is to have the page load on a tab, and then switch to another tab 1sec later
