### ISSUE TITLE
Fail to copy static image during build

### ISSUE THREAD

**Issue by qrevel** [facebook/Docusaurus#701]
### Is this a bug report?

yes

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

yes

### Environment

Docusaurus: 1.1.3
Node: 10.1

### Steps to Reproduce

1. Use the same favicon file for both headerIcon and favicon

```
grep favicon website/siteConfig.js
  headerIcon: 'img/favicon.png',
  favicon: 'img/favicon.png',
```

2. Put the favicon file in the static directory

```
ls website/static/img
aws-icons   favicon     favicon.png
```

3.  Run the build: `yarn build`

4. Check file presence in build directory

```
ls website/build/img
aws-icons    favicon     language.svg
```

### Expected Behavior

The `favicon.png` should be there

### Actual Behavior

Everything is copied except this file.

It was working on `1.0.15`, the bug was introduced with `1.1` versions.

**Comment by ahmadalfy** [comment]
It will be useful if you can share the favicon image. It might be introduced due to [this PR](https://github.com/facebook/Docusaurus/pull/654)

**Comment by JoelMarcey** [comment]
I just ran `yarn build` on the Docusaurus site, and I see `favicon.ico` in my build. So I am curious if @ahmadalfy may be right on this.

**Comment by ahmadalfy** [comment]
What I am thinking of is that the file is an invalid image (like an icon using the `png` extension) and hence optipng fails to compress it and move it.

**Comment by qrevel** [comment]
You might be right, here is the icon:

![favicon](https://user-images.githubusercontent.com/11804101/40593184-b100ddce-621e-11e8-8c9a-30b5a5fe0b62.png)

**Comment by qrevel** [comment]
In addition, I think it has been edited with Preview on macOS.

**Comment by ahmadalfy** [comment]
Can you try to check the integrity of the image using [this tool](http://www.libpng.org/pub/png/apps/pngcheck.html)? I need to update the command line tools before running it ([check this guide](http://macappstore.org/pngcheck/))

**Comment by qrevel** [comment]
```pngcheck -vt website/static/img/favicon.png
File: website/static/img/favicon.png (15037 bytes)
  chunk IHDR at offset 0x0000c, length 13
    174 x 202 image, 32-bit RGB+alpha, non-interlaced
  chunk gAMA at offset 0x00025, length 4: 0.45455
  chunk cHRM at offset 0x00035, length 32
    White x = 0.3127 y = 0.329,  Red x = 0.64 y = 0.33
    Green x = 0.3 y = 0.6,  Blue x = 0.15 y = 0.06
  chunk iTXt at offset 0x00061, length 523, keyword: XML:com.adobe.xmp
    uncompressed, no language tag
    no translated keyword, 502 bytes of UTF-8 text
  chunk IDAT at offset 0x00278, length 14385
    zlib: deflated, 32K window, superfast compression
  chunk IEND at offset 0x03ab5, length 0
No errors detected in website/static/img/favicon.png (6 chunks, 89.3% compression).
```

**Comment by endiliey** [comment]
@ahmadalfy are you working on this ?

**Comment by ahmadalfy** [comment]
@endiliey yes will check, my apologies for the delay

**Comment by SleepWalker** [comment]
I've got the similar issue, while running build on Docker node jessie image, using yarn. There was a problem with `imagemin` can not build and, as a result the images won't converted (but silently. Probably in newer versions it is not silent anymore)

**Comment by endiliey** [comment]
This has been happening on my local (although randomly) as well. I thought it was a local issue but today I confirmed that it is not. In fact, Docusaurus itself is experiencing this.

Check https://circleci.com/gh/facebook/Docusaurus/2847

<img width="935" alt="jpegtran-promise" src="https://user-images.githubusercontent.com/17883920/43673714-0a9c866a-97fa-11e8-96e6-e1f5c6a99e4f.PNG">

The build succeed but along the line there is an unhandled promise. Causing `christopher-chedeau.jpg` and `ricky-vetter.jpg` to be missing.

<img width="940" alt="missing image" src="https://user-images.githubusercontent.com/17883920/43673726-46d0ef68-97fa-11e8-8826-841fc8ff70f1.PNG">

Wondering if you have an idea on this @ahmadalfy ?
Seems that https://github.com/imagemin/imagemin/issues/154 is related

cc @yangshun @JoelMarcey

**Comment by huchenme** [comment]
Can we not through those errors in console?
