### ISSUE TITLE
Build does not consistently respect Markdown front matter

### ISSUE THREAD

**Issue by erikvorhes** [facebook/docusaurus#7062]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

We recently began upgrading from 2.0.0-beta.4 to 2.0.0-beta.18 and on running `docusaurus build` encountered a bunch of `Docusaurus found broken links!` errors that weren't there before.

My investigation suggests that if a file name matches its directory name, the `id` value in Markdown front matter is ignored, and the file is built to `build/docs/${dirName}/index.html` instead of `build/docs/${dirName}/${markdownId}/index.html`.

### Reproducible demo

https://codesandbox.io/s/dawn-rain-ki5eu6?file=/docs/overview/overview.md

### Steps to reproduce

in the reproducible demo, the file `docs/overview/overview.md` has this front matter:

```
---
id: product-overview
title: Product Overview
---
```

In beta 18, this is built to `build/docs/overview/index.html`, thus disregarding the `id` value. A different Markdown file in the same directory, `docs/overview/build.md`, respects the `id` value in the front matter (`builds-correctly`) and is built to `build/docs/overview/builds-correctly/index.html`

### Expected behavior

Due to its front matter, `docs/overview/overview.md` should build to `build/overview/product-overview/index.html`.

### Actual behavior

`docs/overview/overview.md` builds to `build/overview/index.html`.

### Your environment

- Public source code: https://codesandbox.io/s/dawn-rain-ki5eu6
- Public site URL: https://ki5eu6.sse.codesandbox.io/
- Docusaurus version used: 2.0.0-beta.18

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by Josh-Cena** [comment]
Hi! This is a feature. Please see https://docusaurus.io/docs/sidebar/autogenerated#category-index-convention You can use the `slug` front matter to override the route generated, but please don't assume that the `id` front matter has a deterministic impact on the document's route.

**Comment by erikvorhes** [comment]
Ah! Thanks!

**Comment by erikvorhes** [comment]
@Josh-Cena -- any recommendation for how to handle https://docusaurus.io/docs/docs-markdown-features#referencing-other-documents if a file has a slug different from the file name? For example, I added a slug to `overview.md` and linked to the file here: https://codesandbox.io/s/dawn-rain-ki5eu6?file=/docs/overview/build.md -- but the generated page at https://ki5eu6.sse.codesandbox.io/docs/overview/builds-correctly has a link that points to https://ki5eu6.sse.codesandbox.io/docs/overview/ (which is now broken).

**Comment by Josh-Cena** [comment]
I can't reproduce this:

<img width="1339" alt="image" src="https://user-images.githubusercontent.com/55398995/160724464-f65d5167-193c-41cd-b7f0-46b9c1ef38b4.png">

Maybe you need to re-start when you've set the slug?
