### ISSUE TITLE
Specifying the Latest version in URL "Not Found"

### ISSUE THREAD

**Issue by legacydev** [facebook/docusaurus#7087]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [ ] I have tried the `npm run clear` or `yarn clear` command.
- [ ] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io.
- [ ] I have read the console error message carefully (if applicable).

### Description

I need to link to the latest version specifically for future proofing (release links, etc). Ex: https://docusaurus.io/docs/2.0.0-beta.18
However, this results in "Not found".

2.0.0-beta.18 does exist at https://docusaurus.io/docs.

I expect https://docusaurus.io/docs/2.0.0-beta.18 to resolve to https://docusaurus.io/docs

### Steps to reproduce

1. Go to https://docusaurus.io/docs/2.0.0-beta.18
2. See "Not Found" page

### Expected behavior

I expect https://docusaurus.io/docs/2.0.0-beta.18 to resolve to https://docusaurus.io/docs

### Actual behavior

It goes to "Not found" page

### Your environment

- Public site URL: https://docusaurus.io/docs
- Chrome 99

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by Josh-Cena** [comment]
Hi! Our docs plugin never sets up redirects, see also https://github.com/facebook/docusaurus/issues/3407. You need to set up any kind of redirect yourself, either server-side (through 304) or client-side (through the client-redirects plugin).

You can also try the [versions](https://docusaurus.io/docs/api/plugins/@docusaurus/plugin-content-docs#versions) option and configure `path: "2.0.0-beta.18"` for your latest version, so you never have an unversioned URL at all.

**Comment by slorber** [comment]
@Josh-Cena we discussed a "version aliases" feature in the past but it never got implemented.

That looks quite similar to the current use case and could be useful. 

Did a rough design here: https://github.com/facebook/docusaurus/issues/3285

**Comment by slorber** [comment]
@legacydev please explain your problem in a more concrete way, giving example URLs and expected content (or redirect, client or server) at each URL. It's hard to understand in text form.

> Server-side isn't really a viable option for us as we would have to submit a request through a different team each time we do a release

There are solutions with modern CDN hosts (Netlify, Vercel and even homemade...) so that redirects can be committed to Git and controlled directly by devs

**Comment by tisonkun** [comment]
@slorber Today I meet a requirement that exactly needs the version alias feature - for your information :)

**Comment by tisonkun** [comment]
@slorber and I maunally do the redirect as https://github.com/apache/pulsar-site/pull/288.

**Comment by slorber** [comment]
@tisonkun FYI the redirect is always done better server-side. 
If we ever build something it will be at most a client redirect and be less than ideal.

In my opinion your implemented solution is not ideal either, you'd better use a server redirect.

For example, using a _redirects file on Netlify it's as simple as adding one of those 3 declarations:

```
# Redirect from /docs/latest/* to /docs/2.3.0/* (always)
/docs/latest/*                 /docs/2.3.0/:splat           301!

# Redirect from /docs/* to /docs/2.3.0/*  (only if a static file can't be served at /docs/*)
/docs/*                 /docs/2.3.0/:splat           301

# Proxy from /docs/latest/* to /docs/2.3.0/* (ie the URL still contains /latest/ but the correct static file is served)
/docs/latest/*                 /docs/2.3.0/:splat           200
```

---

And the non-redirect alias can be achieved pretty simply with `cp -R build/docs/2.3.0 build/docs/latest` as a post-build step

Hope this helps

**Comment by tisonkun** [comment]
@slorber Thanks for your information! The Apache Pulsar website is hosted on an Apache Web Server (of course, lol) and I'm still learning how to configure server-side redirections programmatically...

**Comment by slorber** [comment]
😅 I can't tell you how to configure Apache Web Server unfortunately, it's been a while I haven't touched that and I don't really regret it 😄
