### ISSUE TITLE
Cannot add new language support

### ISSUE THREAD

**Issue by MasterYuan418** [facebook/docusaurus#7109]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [ ] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

![图片](https://user-images.githubusercontent.com/58651976/161459449-72db586c-765a-45df-bc9b-f59f58dc8300.png)
When I try to add a new language, the page doesn't load.

In `docusaurus.config.js`:
```js
      prism: {
        additionalLanguages: ["cs"],
        theme: lightCodeTheme,
        darkTheme: darkCodeTheme
      },
```
logs:
```
Uncaught Error: Cannot find module './prism-cs'
    webpackEmptyContext main.js:1371
    prismIncludeLanguages prism-include-languages.js:22
    prismIncludeLanguages prism-include-languages.js:19
    <anonymous> prism-include-languages.js:14
    node_modules main.js:727
    __webpack_require__ runtime~main.js:36
    fn runtime~main.js:329
    <anonymous> client-modules.js:1
    js main.js:23
    __webpack_require__ runtime~main.js:36
    fn runtime~main.js:329
    <anonymous> client-lifecycles-dispatcher.js:5
    node_modules main.js:103
    __webpack_require__ runtime~main.js:36
    fn runtime~main.js:329
    <anonymous> PendingNavigation.js:9
    node_modules main.js:71
    __webpack_require__ runtime~main.js:36
    fn runtime~main.js:329
    <anonymous> App.js:10
    node_modules main.js:55
    __webpack_require__ runtime~main.js:36
    fn runtime~main.js:329
    <anonymous> clientEntry.js:8
    node_modules main.js:111
    __webpack_require__ runtime~main.js:36
    __webpack_exec__ main.js:1790
    <anonymous> main.js:1791
    O runtime~main.js:80
    <anonymous> main.js:1792
    webpackJsonpCallback runtime~main.js:1319
    <anonymous> main.js:9
main.js:1371:10
```

### Steps to reproduce

1. Add new language support.
2. Save

### Expected behavior

The page is displayed normally.

### Actual behavior

white screen.

```
Uncaught Error: Cannot find module './prism-cs'
    webpackEmptyContext main.js:1371
    prismIncludeLanguages prism-include-languages.js:22
    prismIncludeLanguages prism-include-languages.js:19
    <anonymous> prism-include-languages.js:14
    node_modules main.js:727
    __webpack_require__ runtime~main.js:36
    fn runtime~main.js:329
    <anonymous> client-modules.js:1
    js main.js:23
    __webpack_require__ runtime~main.js:36
    fn runtime~main.js:329
    <anonymous> client-lifecycles-dispatcher.js:5
    node_modules main.js:103
    __webpack_require__ runtime~main.js:36
    fn runtime~main.js:329
    <anonymous> PendingNavigation.js:9
    node_modules main.js:71
    __webpack_require__ runtime~main.js:36
    fn runtime~main.js:329
    <anonymous> App.js:10
    node_modules main.js:55
    __webpack_require__ runtime~main.js:36
    fn runtime~main.js:329
    <anonymous> clientEntry.js:8
    node_modules main.js:111
    __webpack_require__ runtime~main.js:36
    __webpack_exec__ main.js:1790
    <anonymous> main.js:1791
    O runtime~main.js:80
    <anonymous> main.js:1792
    webpackJsonpCallback runtime~main.js:1319
    <anonymous> main.js:9
main.js:1371:10
```

### Your environment

- Public source code: 
- Public site URL: **Unable to publish this site**
- Docusaurus version used: 2.0.0-beta.18
- Environment name and version (e.g. Chrome 89, Node.js 16.4): Firefox 98.0.2, Node.js 14.15.1
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): Microsoft Windows 10(build 19043)

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by Josh-Cena** [comment]
Hi! The Prism component is called `prism-csharp`. The fact that `cs` maps to `csharp`  is another orthogonal behavior:

```js
Prism.languages.dotnet = Prism.languages.cs = Prism.languages.csharp;
```

, but `prism-cs` indeed doesn't exist on disk. Changing it to `additionalLanguages: ["csharp"],` should fix the problem.

**Comment by Josh-Cena** [comment]
@MasterYuan418 I've opened #7110 which should hopefully clear up some doubts. This isn't the first time this question comes up.
