### ISSUE TITLE
markdown h1 header render error on windows and macos

### ISSUE THREAD

**Issue by frank-lam** [facebook/docusaurus#7120]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

## bug
When I compile the same Markdown file locally on two different systems, Windows and MacOS, I get two different effects.

Macos uses the first level title in Markdown as the title of the current document, but Windows displays both. 

Personally, I think the preview method in MacOS is better.

Hopefully, officials can fix this problem by adding configuration, so as to avoid the preview differences between different systems.

## macos
![image](https://user-images.githubusercontent.com/19153458/161995863-7629d1cd-62ae-4444-8e0a-97d88296bc4a.png)
![image](https://user-images.githubusercontent.com/19153458/161995878-ef493fec-7bd5-4a49-854e-7627497b5e65.png)

## windows
![image](https://user-images.githubusercontent.com/19153458/161995946-f7df9cd5-b9b5-4b80-8f41-45ce741a3b26.png)
![image](https://user-images.githubusercontent.com/19153458/161995966-e07ddda3-921d-46b5-a0c6-3312394a2c8f.png)

### Steps to reproduce

NA

### Expected behavior

NA

### Actual behavior

NA

### Your environment

{
  "name": "notes.frankfeekr.cn",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "docusaurus": "docusaurus",
    "start": "docusaurus start",
    "build": "docusaurus build",
    "swizzle": "docusaurus swizzle",
    "deploy": "docusaurus deploy",
    "clear": "docusaurus clear",
    "serve": "docusaurus serve",
    "write-translations": "docusaurus write-translations",
    "write-heading-ids": "docusaurus write-heading-ids"
  },
  "dependencies": {
    "@docusaurus/core": "^2.0.0-beta.18",
    "@docusaurus/preset-classic": "^2.0.0-beta.18",
    "@easyops-cn/docusaurus-search-local": "0.23.0",
    "@mdx-js/react": "^1.6.22",
    "clsx": "^1.1.1",
    "plugin-image-zoom": "^1.1.0",
    "prism-react-renderer": "^1.3.1",
    "react": "^17.0.1",
    "react-dom": "^17.0.1"
  },
  "browserslist": {
    "production": [
      ">0.5%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  }
}

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by Josh-Cena** [comment]
Hi, please see https://github.com/facebook/docusaurus/issues/7044

You should change all your CRLF to LF for the time being.
