### ISSUE TITLE
SNS embed script does not work (Twitter, Facebook, Instagram etc.)

### ISSUE THREAD

**Issue by ryudenx** [facebook/docusaurus#7149]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

I want to display various SNS pages on the docusaurus page.
Generally, this requirement uses an embed script.
Each SNS provides it.

However, the copy&pasted embed script didn't work on the docusaurus page.

### Steps to reproduce

1. initialize
npx create-docusaurus@latest website classic
cd my-website
npm install

2. Paste the Twitter embed code into your new Markdown file (for example: test.md).

docs/test.md:
```
<blockquote class="twitter-tweet"><p lang="en" dir="ltr">Docusaurus is a new project from <a href="https://twitter.com/fbopensource?ref_src=twsrc%5Etfw">@fbOpenSource</a> team to easily manage your open source project&#39;s documentation. <a href="https://t.co/NuTdoDhe3B">https://t.co/NuTdoDhe3B</a></p>&mdash; Docusaurus (@docusaurus) <a href="https://twitter.com/docusaurus/status/941369886214778880?ref_src=twsrc%5Etfw">December 14, 2017</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
```
![image](https://user-images.githubusercontent.com/35442202/162668054-ecf57a34-a33b-4711-9eb7-c86ec4e8be2a.png)

3. run
npm run start

4. open intro page "/docs/intro"

5, Then open test page "/docs/test" from the sidebar

### Expected behavior

I want to see the Twitter formatted as below.

![image](https://user-images.githubusercontent.com/35442202/162666792-b91fcedb-a3f3-4f06-b6e6-2f39a7e30bfb.png)

### Actual behavior

First, the embed script is displayed as text.

![image](https://user-images.githubusercontent.com/35442202/162666856-22b83a98-5374-4551-a8c0-49bf8f2c68f2.png)

However, the embed script will display when user reload the page.

![image](https://user-images.githubusercontent.com/35442202/162670213-23366072-a398-45f5-9595-81aee4fe5d62.png)

![image](https://user-images.githubusercontent.com/35442202/162670118-82eea46b-eb69-4ca4-b524-5ad04ae06729.png)

--- 
In addition, the embed script of facebook and instagram fails to build.

facebook(meta) sample:
```
<iframe src="https://www.facebook.com/plugins/video.php?height=314&href=https%3A%2F%2Fwww.facebook.com%2FMetaJapan%2Fvideos%2F295050936078543%2F&show_text=false&width=560&t=0" width="560" height="314" style="border:none;overflow:hidden" scrolling="no" frameborder="0" allowfullscreen="true" allow="autoplay; clipboard-write; encrypted-media; picture-in-picture; web-share" allowFullScreen="true"></iframe>
```

facebook error:
```
[ERROR] Docusaurus server-side rendering could not render static page with path /docs/test.


Error: Minified React error #62; visit https://reactjs.org/docs/error-decoder.html?invariant=62 for the full message or use the non-minified 
dev environment for full errors and additional helpful warnings.
```

---

instagram sample :
```
<blockquote class="instagram-media" data-instgrm-captioned data-instgrm-permalink="https://www.instagram.com/p/CalfqOlLsA2/?utm_source=ig_embed&amp;utm_campaign=loading" data-instgrm-version="14" style=" background:#FFF; border:0; border-radius:3px; box-shadow:0 0 1px 0 rgba(0,0,0,0.5),0 1px 10px 0 rgba(0,0,0,0.15); margin: 1px; max-width:540px; min-width:326px; padding:0; width:99.375%; width:-webkit-calc(100% - 2px); width:calc(100% - 2px);"><div style="padding:16px;"> <a href="https://www.instagram.com/p/CalfqOlLsA2/?utm_source=ig_embed&amp;utm_campaign=loading" style=" background:#FFFFFF; line-height:0; padding:0 0; text-align:center; text-decoration:none; width:100%;" target="_blank"> <div style=" display: flex; flex-direction: row; align-items: center;"> <div style="background-color: #F4F4F4; border-radius: 50%; flex-grow: 0; height: 40px; margin-right: 14px; width: 40px;"></div> <div style="display: flex; flex-direction: column; flex-grow: 1; justify-content: center;"> <div style=" background-color: #F4F4F4; border-radius: 4px; flex-grow: 0; height: 14px; margin-bottom: 6px; width: 100px;"></div> <div style=" background-color: #F4F4F4; border-radius: 4px; flex-grow: 0; height: 14px; width: 60px;"></div></div></div><div style="padding: 19% 0;"></div> <div style="display:block; height:50px; margin:0 auto 12px; width:50px;"><svg width="50px" height="50px" viewBox="0 0 60 60" version="1.1" xmlns="https://www.w3.org/2000/svg" xmlns:xlink="https://www.w3.org/1999/xlink"><g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd"><g transform="translate(-511.000000, -20.000000)" fill="#000000"><g><path d="M556.869,30.41 C554.814,30.41 553.148,32.076 553.148,34.131 C553.148,36.186 554.814,37.852 556.869,37.852 C558.924,37.852 560.59,36.186 560.59,34.131 C560.59,32.076 558.924,30.41 556.869,30.41 M541,60.657 C535.114,60.657 530.342,55.887 530.342,50 C530.342,44.114 535.114,39.342 541,39.342 C546.887,39.342 551.658,44.114 551.658,50 C551.658,55.887 546.887,60.657 541,60.657 M541,33.886 C532.1,33.886 524.886,41.1 524.886,50 C524.886,58.899 532.1,66.113 541,66.113 C549.9,66.113 557.115,58.899 557.115,50 C557.115,41.1 549.9,33.886 541,33.886 M565.378,62.101 C565.244,65.022 564.756,66.606 564.346,67.663 C563.803,69.06 563.154,70.057 562.106,71.106 C561.058,72.155 560.06,72.803 558.662,73.347 C557.607,73.757 556.021,74.244 553.102,74.378 C549.944,74.521 548.997,74.552 541,74.552 C533.003,74.552 532.056,74.521 528.898,74.378 C525.979,74.244 524.393,73.757 523.338,73.347 C521.94,72.803 520.942,72.155 519.894,71.106 C518.846,70.057 518.197,69.06 517.654,67.663 C517.244,66.606 516.755,65.022 516.623,62.101 C516.479,58.943 516.448,57.996 516.448,50 C516.448,42.003 516.479,41.056 516.623,37.899 C516.755,34.978 517.244,33.391 517.654,32.338 C518.197,30.938 518.846,29.942 519.894,28.894 C520.942,27.846 521.94,27.196 523.338,26.654 C524.393,26.244 525.979,25.756 528.898,25.623 C532.057,25.479 533.004,25.448 541,25.448 C548.997,25.448 549.943,25.479 553.102,25.623 C556.021,25.756 557.607,26.244 558.662,26.654 C560.06,27.196 561.058,27.846 562.106,28.894 C563.154,29.942 563.803,30.938 564.346,32.338 C564.756,33.391 565.244,34.978 565.378,37.899 C565.522,41.056 565.552,42.003 565.552,50 C565.552,57.996 565.522,58.943 565.378,62.101 M570.82,37.631 C570.674,34.438 570.167,32.258 569.425,30.349 C568.659,28.377 567.633,26.702 565.965,25.035 C564.297,23.368 562.623,22.342 560.652,21.575 C558.743,20.834 556.562,20.326 553.369,20.18 C550.169,20.033 549.148,20 541,20 C532.853,20 531.831,20.033 528.631,20.18 C525.438,20.326 523.257,20.834 521.349,21.575 C519.376,22.342 517.703,23.368 516.035,25.035 C514.368,26.702 513.342,28.377 512.574,30.349 C511.834,32.258 511.326,34.438 511.181,37.631 C511.035,40.831 511,41.851 511,50 C511,58.147 511.035,59.17 511.181,62.369 C511.326,65.562 511.834,67.743 512.574,69.651 C513.342,71.625 514.368,73.296 516.035,74.965 C517.703,76.634 519.376,77.658 521.349,78.425 C523.257,79.167 525.438,79.673 528.631,79.82 C531.831,79.965 532.853,80.001 541,80.001 C549.148,80.001 550.169,79.965 553.369,79.82 C556.562,79.673 558.743,79.167 560.652,78.425 C562.623,77.658 564.297,76.634 565.965,74.965 C567.633,73.296 568.659,71.625 569.425,69.651 C570.167,67.743 570.674,65.562 570.82,62.369 C570.966,59.17 571,58.147 571,50 C571,41.851 570.966,40.831 570.82,37.631"></path></g></g></g></svg></div><div style="padding-top: 8px;"> <div style=" color:#3897f0; font-family:Arial,sans-serif; font-size:14px; font-style:normal; font-weight:550; line-height:18px;">この投稿をInstagramで見る</div></div><div style="padding: 12.5% 0;"></div> <div style="display: flex; flex-direction: row; margin-bottom: 14px; align-items: center;"><div> <div style="background-color: #F4F4F4; border-radius: 50%; height: 12.5px; width: 12.5px; transform: translateX(0px) translateY(7px);"></div> <div style="background-color: #F4F4F4; height: 12.5px; transform: rotate(-45deg) translateX(3px) translateY(1px); width: 12.5px; flex-grow: 0; margin-right: 14px; margin-left: 2px;"></div> <div style="background-color: #F4F4F4; border-radius: 50%; height: 12.5px; width: 12.5px; transform: translateX(9px) translateY(-18px);"></div></div><div style="margin-left: 8px;"> <div style=" background-color: #F4F4F4; border-radius: 50%; flex-grow: 0; height: 20px; width: 20px;"></div> <div style=" width: 0; height: 0; border-top: 2px solid transparent; border-left: 6px solid #f4f4f4; border-bottom: 2px solid transparent; transform: translateX(16px) translateY(-4px) rotate(30deg)"></div></div><div style="margin-left: auto;"> <div style=" width: 0px; border-top: 8px solid #F4F4F4; border-right: 8px solid transparent; transform: translateY(16px);"></div> <div style=" background-color: #F4F4F4; flex-grow: 0; height: 12px; width: 16px; transform: translateY(-4px);"></div> <div style=" width: 0; height: 0; border-top: 8px solid #F4F4F4; border-left: 8px solid transparent; transform: translateY(-4px) translateX(8px);"></div></div></div> <div style="display: flex; flex-direction: column; flex-grow: 1; justify-content: center; margin-bottom: 24px;"> <div style=" background-color: #F4F4F4; border-radius: 4px; flex-grow: 0; height: 14px; margin-bottom: 6px; width: 224px;"></div> <div style=" background-color: #F4F4F4; border-radius: 4px; flex-grow: 0; height: 14px; width: 144px;"></div></div></a><p style=" color:#c9c8cd; font-family:Arial,sans-serif; font-size:14px; line-height:17px; margin-bottom:0; margin-top:8px; overflow:hidden; padding:8px 0 7px; text-align:center; text-overflow:ellipsis; white-space:nowrap;"><a href="https://www.instagram.com/p/CalfqOlLsA2/?utm_source=ig_embed&amp;utm_campaign=loading" style=" color:#c9c8cd; font-family:Arial,sans-serif; font-size:14px; font-style:normal; font-weight:normal; line-height:17px; text-decoration:none;" target="_blank">渡辺直美　Naomi watanabe(@watanabenaomi703)がシェアした投稿</a></p></div></blockquote> <script async src="//www.instagram.com/embed.js"></script>

instagram error:
```
SyntaxError: C:\vscode\docusaurus-test\website\docs\test.md: Namespace tags are not supported by default. React's JSX doesn't support namespace tags. You can set `throwIfNamespace: false` to bypass this warning.
  44 |   return <MDXLayout {...layoutProps} {...props} components={components} mdxType="MDXLayout">
  45 |
> 46 |     <blockquote class="instagram-media" data-instgrm-captioned data-instgrm-permali
```
```

### Your environment

- Public source code: - 
- Public site URL: - 
- Docusaurus version used: 2.0.0-beta.18
- Environment name and version: Chrome 100.0.4896.75,  Node.js 16.14.2
- Operating system and version: Windows10, CentOS8.4

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by Josh-Cena** [comment]
Hi, Docusaurus uses MDX, which is JSX, not HTML. See https://docusaurus.io/docs/markdown-features/react

That means, you have to use `style={{}}` rather than `style="..."` for your Facebook embed. Ditto for Instagram. The Instagram one also pretty clearly outlines why it fails to compile at all.

If you want to use plain HTML in Markdown, you either have to use [`dangerouslySetInnerHTML`](https://reactjs.org/docs/dom-elements.html#dangerouslysetinnerhtml), or watch out for #3018.

As for the Twitter embed, my suspection is that it conflicts with SSR/hydration. Docusaurus is server-rendered, so you should NOT use `script` tags and let client-side script modify DOM, especially asynchronously, because it would almost certainly mess with React. This use-case will never be supported OOTB.

You may try wrapping it in `BrowserOnly`, and even [create your own `<TwitterEmbed />` component](https://docusaurus.io/docs/markdown-features/react#importing-components), leveraging the power of MDX.

Since this looks like a misunderstanding of how MDX works or even how Docusaurus works in general, I'll close this as a question.

@slorber Since I'm not very familiar with these use-cases, if you have more insight, feel free to respond later :D

**Comment by ryudenx** [comment]
Thank you for your reply.
I understand that this is not a bug, and the expected behavior.
It's inconvenient, but I think it can't be helped...

**Comment by Josh-Cena** [comment]
The iframe one should be the closest to success. If you fix the `style` problem it should work normally.

**Comment by slorber** [comment]
> First, the embed script is displayed as text.
> However, the embed script will display when user reload the page.

Note that the Twitter widget script may not work so well with single page applications, and maybe it does not try to convert quotes as Twitter widgets on navigation too.

I suggest you directly use a React integration that figured all this for you and ensure that embeds are correctly integrated with React and SPA navigation: https://saurabhnemade.github.io/react-twitter-embed/


Note that loading Twitter SDKs and things like that is not the most performant, and only works on the client.

There is a better way, that works with server-side-rendering too (ie the tweet shows correctly even if user disable JS). For example: https://github.com/transitive-bullshit/react-static-tweets
