### ISSUE TITLE
Publishing GH pages not picking up GIT_USER.

### ISSUE THREAD

**Issue by yansern** [facebook/Docusaurus#715]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

### Environment

Docusaurus 1.1.5 on macOS.

### Steps to Reproduce
I followed the instructions at https://docusaurus.io/docs/en/publishing.html and I executed:
```
GIT_USER=yansern
CURRENT_BRANCH=master
USE_SSH=true
yarn run publish-gh-pages
```
but all I got:
```
Password for 'https://undefined@github.com': 
```

### Expected Behavior

I would expect it to use `https://yansern@github.com` (and actually I was also expecting the SSH url not the HTTPS).

### Actual Behavior

It is using `https://undefined@github.com`.

**Comment by endiliey** [comment]
Did you configure your SSH already ? https://help.github.com/articles/connecting-to-github-with-ssh/

Alternatively, you can try 
```GIT_USER=yansern CURRENT_BRANCH=master USE_SSH=false yarn run publish-gh-pages```

**Comment by yansern** [comment]
@endiliey Yes, SSH is properly set up. I can clone repositories on GitHub using SSH urls.

The `USE_SSH=false` doesn't make a difference. `true` or `false` it still uses `https://undefined@github.com`.

**Comment by endiliey** [comment]
That is weird because mine works. You might want to put your repo here so someone can try to reproduce it

**Comment by yansern** [comment]
Okay, it seems that I have to use the `export` keyword in bash, then `publish-gh-pages` will pick it up properly.
```
export GIT_USER=yansern
export CURRENT_BRANCH=master
export USE_SSH=true
yarn run publish-gh-pages
```

**Comment by endiliey** [comment]
That's weird, are you executing it one by one ? I think it should be in one line.
But if it works now, we can close this issue 😂

**Comment by endiliey** [comment]
Hi @yansern, I believe it's working for you now.
I'm closing the issue for now, feel free to reopen if you need more assistance.

**Comment by stavalfi** [comment]
I have this problem too. it uses https url in azure by in my mac it uses ssh url.
