### ISSUE TITLE
`scroll-behavior:smooth` conflicts with back-to-top button

### ISSUE THREAD

**Issue by aozaki-kuro** [facebook/docusaurus#7155]
t### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

I was trying to enable smooth scroll behavior to the whole site by adding custom css
```css
html {
  scroll-behavior: smooth;
}
```
It seemed to be working but I have found out that clicking back-to-top button would cause the whole page to freeze.
No warnings or errors were thrown from the console.

I check the issues and found a similar issue https://github.com/facebook/docusaurus/issues/6620 , but it was with the toc, not the back-to-top button

Demo:

https://user-images.githubusercontent.com/28428951/162858958-3bedd769-0325-49cf-8e4b-5afd2106e21c.mov

### Reproducible demo

The commit in my repo
https://github.com/aozaki-kuro/tokomachi-wiki-neo/tree/5136a10221811cc044c78b20cf0c6bc92ad47855

The build with smooth scroll enabled: 
https://tokomachi-wiki-jhhqiqvnv-aozaki.vercel.app

### Steps to reproduce

1. Add custom css to `./src/css/custom.css`
```css
html {
  scroll-behavior: smooth;
}
```
2. `npm run build` & `npm run serve`
3. Scroll down and a little bit up to let the back-to-top button show up, click it and the whole page freeze.

### Expected behavior

Site smooth scroll behavior and back-to-top function no longer conflicts.
Maybe adding an option to disable the smooth scroll came with the back-to-top button would help?

### Actual behavior

After adding `scroll-behavior:smooth` the back-to-top button no longer works and cause the whole page to freeze. The video was included in the Description section.

No warnings or errors were thrown from the console.

### Your environment

- Public source code: https://github.com/aozaki-kuro/tokomachi-wiki-neo/
- Public site URL: https://toko.suisei.cc (The build with smooth scroll enabled: https://tokomachi-wiki-jhhqiqvnv-aozaki.vercel.app)
- Docusaurus version used: 2.0.0-beta.18
- Environment name and version (e.g. Chrome 89, Node.js 16.4): Microsoft Edge 100.0.1185.39, Node.js 16.14.2
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): macOS Monterey 12.3.1 (Apple Silicon)

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by Josh-Cena** [comment]
Hi, this is already fixed in https://github.com/facebook/docusaurus/pull/7057, just not released yet. You can try the [canary release](https://docusaurus.io/community/canary).

**Comment by aozaki-kuro** [comment]
Wow that's a good news and thanks for the fast response! I will try it out.
