### ISSUE TITLE
when i deployment project in nginx, refresh the page navbar active is disappear, but npm run serve is normal.

### ISSUE THREAD

**Issue by frank-lam** [facebook/docusaurus#7158]
when i deployment project in nginx, refresh the page navbar active is disappear, but npm run serve is normal.
`npm run start` and `npm run serve` it's normal.
Do I need any special configuration?

`navbar__link--active` class disappear below, when i refresh the page(F5)
```html
<a class="navbar__item navbar__link navbar__link--active" href="/docs/blog/readme" aria-current="page">xxx</a>
```

**Comment by Josh-Cena** [comment]
Have you configured the [right trailing slash](https://docusaurus.io/docs/deployment#trailing-slashes)?

PLEASE DON'T USE THE ISSUE TRACKER AS SUPPORT FORUM—this has been repeatedly emphasized in the issue template. Bypassing the issue template and obviously not paying any attention to it is the least considerate thing to do when engaging with an open-source project.
