### ISSUE TITLE
Links in Code Examples (via magic comments)

### ISSUE THREAD

**Issue by nathan-contino-mongo** [facebook/docusaurus#7170]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Description

Clickable links in code samples. The Firebase documentation uses a similar system for linking code snippets to configuration information: https://firebase.google.com/docs/web/setup#add-sdks-initialize

Example:
<img width="831" alt="Screen Shot 2022-04-13 at 10 50 53 AM" src="https://user-images.githubusercontent.com/54279145/163284713-98f59ac7-026c-4400-aabe-71c7e2b8846f.png">

The bottom of [this section of the doc](https://docusaurus.io/docs/markdown-features/code-blocks#highlighting-with-metadata-string) mentions that the magic comment system could extend in the future for additional markup use cases. I believe this is one potential use case for an extension of that system.

### Motivation

In many cases, it makes more sense to surface links through prose or an admonition before or after a code block. But sometimes this:

- takes up valuable vertical space on an already long page
- clutters up a page that already contains lots of admonitions
- creates confusion for users when examples are long and/or need multiple outward links

### API design

I'm not super familiar with the implementation for the magic comment system. But right now, that system uses the following syntax for highlights:

```
// highlight-start
highlighted text
// highlight-end
not highlighted text
// highlight-next-line
highlighted text
```

I imagine we could extend these magic comments to use an uncommon keyword for linking to a docusaurus ID, with a link name and reference as arguments provided in the markdown format:

```
// docs-link [Link to something](/absolute/path/to/{id})
```

### Have you tried building it?

no

### Self-service

- [ ] I'd be willing to contribute this feature to Docusaurus myself.

**Comment by Josh-Cena** [comment]
Sounds cool to me!

**Comment by slorber** [comment]
I plan to refactor CodeBlock already so this will become even simpler: swizzle `CodeBlock/Line` and transform the line to whatever you want (ie transform comment string to JSX)

Was wondering: do we have an need for this in our own doc? We could add it to dogfood and improve our doc DX, just need to figure a few good places to use this.

**Comment by Josh-Cena** [comment]
Oh... I just realized this will not be a normal magic comment either! Because the definition of a "magic comment" is something that adds metadata about the next line (e.g. `highlight`, `collapsible`), and it will be removed. So we can't even use the magic comment system here. @slorber We can close this as soon as you make that refactor 👍

**Comment by Josh-Cena** [comment]
Now that #7175 is merged, this should be able to be implemented in userland.

**Comment by nathan-contino-mongo** [comment]
Thank you @Josh-Cena
