### ISSUE TITLE
Allow configurable URL value for "next"

### ISSUE THREAD

**Issue by machikoyasuda** [facebook/Docusaurus#718]
### Is this a bug report?

✖️No

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

✅ Yes

### Feature request

Currently, Docusaurus hardcodes the URL param for the pre-release `master` branch as `next`. The version link in the header and the URLs use the word `next`. I'd like to be able to configure this field in `siteConfig.js`, because I'd like to be able to use the URL value `master` instead.

For example, instead of `localhost:3000/docs/next/installation.html`, I'd like to be able to use `master` instead: `localhost:3000/docs/master/installation.html`. This naming better aligns with the naming convention we already currently use in our docs and GitHub branch naming conventions.

### Proposal:

Add an optional `siteConfig.js` variable that would allow users to set a custom name, like `master`, instead of the default, `next`.

**Comment by machikoyasuda** [comment]
@JoelMarcey @yangshun If it's alright with y'all, I'd love to work on this 🤓

**Comment by JoelMarcey** [comment]
I would love a PR on this. Thanks! As long as it doesn't break existing functionality, then I think we could consider this.

**Comment by endiliey** [comment]
Hi @machikoyasuda 😁
Are you still working on this ? Will be happy to help if you encounter a problem

**Comment by machikoyasuda** [comment]
@endiliey I was able to get around this issue with Netlify redirects, so I'm not working on this anymore!

Someone else can claim if if interested, or close it :)

**Comment by endiliey** [comment]
I am closing this then. Trying to avoid extra feature (especially in siteConfig) before v2.

**Comment by machikoyasuda** [comment]
@endiliey Thank you for your vigilant maintainership <3
