### ISSUE TITLE
SVG broken in Docusaurus update

### ISSUE THREAD

**Issue by softshape** [facebook/docusaurus#7195]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

We're using the following SVG images on the helpdesk homepage -

![image](https://user-images.githubusercontent.com/107505/163744620-03cf164e-7ce9-46a2-9f7c-1e75aafeeda1.png)

Just updated Docusaurus to the latest version - yarn upgrade @docusaurus/core@latest @docusaurus/preset-classic@latest - and now they look like this -

![image](https://user-images.githubusercontent.com/107505/163744763-07026f85-ed72-4742-8075-c39f8268a525.png)

These SVG images in 'build' folder are exactly the same as their sources, so the SVG itself is not broken and if it's open in the browser alone, SVG looks correct. But in context of the Docusaurus homepage they look distorted.

What can be a problem?

### Steps to reproduce

Update to the latest Docusaurus

### Expected behavior

Correct image (see screenshot)

### Actual behavior

Distorted image (see screenshot)

### Self-service

- [X] I'd be willing to fix this bug myself.

**Comment by Josh-Cena** [comment]
Hi, please give a site so we can inspect this.

**Comment by softshape** [comment]
> Hi, please give a site so we can inspect this.

It's https://docs.mytko.ru

**Comment by Josh-Cena** [comment]
I can't reproduce this on a fresh website:

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/55398995/163747302-22ec7e02-4fe6-4632-a748-ba51c6ccb9d0.png">

Could you give your source as well, or try to reproduce this on a new website so we can know what's wrong?

**Comment by Josh-Cena** [comment]
I'll also need to know what you are upgrading the Docusaurus version from. My highest suspicion is incompatible SVGR version, if you are upgrading from a few versions ago. If you have `@svgr/loader` in your package.json, please remove it.

**Comment by softshape** [comment]
The problem found in the SVG classes. Each SVG used .fil0, .fil1, ... .fil4 classes inside with different fill colors, but before they were incapsluated. With this new Docusaurus they started to intersect and redefine each other. I've solved the problem adding namespace to each SVG. You can reproduce the problem, I guess, if you replace the icon with a tree to the truck SVG from my example. 

Anyway, the problem solved by editing SVG files.

**Comment by Josh-Cena** [comment]
That's interesting. I'd still be curious which change in Docusaurus caused it though. Which version are you upgrading from?

**Comment by softshape** [comment]
Which command would show the current installed Docusaurus version?

**Comment by Josh-Cena** [comment]
How are you upgrading? Typically, people edit their package.json file, as shown here: https://docusaurus.io/docs/installation#updating-your-docusaurus-version So you only need to compare the version number before/after the change.
