### ISSUE TITLE
Authors are not displayed in RSS feeds unless author email is specified

### ISSUE THREAD

**Issue by SebDanielsson** [facebook/docusaurus#7198]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

Authors are not displayed in RSS feeds unless author email is specified. For example some authors might be happy just entering their Twitter to the url field and do not want to share their email address.

### Steps to reproduce

Add a post with all author fields entered except email. Check the rss feed. Author field should be missing.

### Expected behavior

Author field should be shown regardless of whether there is an email entered or not.

### Actual behavior

Author field is missing from RSS.

### Your environment

- Public source code: https://github.com/SebDanielsson/hogwarts-docusaurus
- Public site URL: https://hogwarts.zone
- Docusaurus version used: Beta 18

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by Josh-Cena** [comment]
Hi, this is the requirement of RSS, and it's documented: https://docusaurus.io/docs/blog#:~:text=RSS%20feeds%20require%20the%20author%27s%20email%20to%20be%20set%20for%20the%20author%20to%20appear%20in%20the%20feed.

**Comment by Josh-Cena** [comment]
Actually, the RSS spec does not make it clear whether the link is mandated to be an email: https://validator.w3.org/feed/docs/rss2.html#ltauthorgtSubelementOfLtitemgt But the library, [feed](https://www.npmjs.com/package/feed), that we use does require `email` to be set. As an opinionated tool, I think the best practice here is to adhere to the proper semantics. You are welcome to add a fake email like the Twitter handle under the `email` field.
