### ISSUE TITLE
"Docs plugin enabled" detection no longer does anything

### ISSUE THREAD

**Issue by Josh-Cena** [facebook/docusaurus#7207]
Because `theme-common` has a direct dependency on `plugin-content-docs`, it is no longer possible to make a site without ever installing `content-docs` (previously discussed in #3360). Not really a big deal because the user can still install `theme-classic` and `plugin-content-blog` and pretend she never pulls in `content-docs` transitively, but it's still not desirable.

We have some checks in our codebase about whether docs is enabled:

https://github.com/facebook/docusaurus/blob/c8d6c7e38685598869863b59f9d05197f8558868/packages/docusaurus-theme-common/src/utils/docsUtils.tsx#L32-L33

https://github.com/facebook/docusaurus/blob/c8d6c7e38685598869863b59f9d05197f8558868/packages/docusaurus-theme-classic/src/theme/NavbarItem/index.tsx#L18-L38

Because we are now always directly importing these hooks from `@docusaurus/plugin-content-docs/client` instead of letting the docs plugin register theme aliases, these things always statically exist. We should either remove the checks, or dynamically import `content-docs/client` everywhere (better IMO in terms of bundle size)

**Comment by Josh-Cena** [comment]
This is my major dissatisfaction with the ongoing refactors. Everything gets intertwined and our architecture is getting more and more monolithic despite being allegedly "modular".

**Comment by Josh-Cena** [comment]
Yeah, I'm mainly talking about directly importing `@docusaurus/plugin-content-docs` in the theme, not the fact that the theme _provides_ the docs components.

The theme aliases somehow work like inversion of control. Instead of having direct dependency relationship, the alias allows them to communicate through a shared protocol where plugin provides the data and theme provides the components. There's no hard dependence in this relationship and unplugging anything naturally works.

I'm not asking to split the theme—just that importing from `@docusaurus/plugin-content-docs` in `theme-common` has made this coupling much tighter than before. Lazy-loading _could_ fix it.

> https://github.com/facebook/docusaurus/issues/3360 was about a different issue: a blog would not build if the user is using docs: false (despite package being installed => the plugin needed to be registered even if unused)

Ah, I understand now. Scratch the point about skipping installation of a package (maybe we still can in the future with optional peer dependencies, but we have been bitten by peer dependencies, so not in the near future). Bundle size is still a valid claim, though

**Comment by slorber** [comment]
> The theme aliases somehow work like inversion of control. Instead of having direct dependency relationship, the alias allows them to communicate through a shared protocol where plugin provides the data and theme provides the components. There's no hard dependence in this relationship and unplugging anything naturally works.

I understand that, but at the same time it can become quite tedious to maintain the "contract" between content plugin and theme this way. 

Remember most of these docs apis are internal and undocumented. Adding indirection only increase maintenance cost from us. 

These apis are not really meant to be overridden with aliases. If user is unhappy with a behavior, they can swizzle the component and provide a brand new implementation using documented apis like `useGlobalData`.

> I'm not asking to split the theme—just that importing from `@docusaurus/plugin-content-docs` in `theme-common` has made this coupling much tighter than before. Lazy-loading _could_ fix it.

I don't understand why it's worse to import it in theme-common compared to theme-classic? 

Maybe you are against both, and I can understand that.

IMHO coupling isn't always a bad thing. Here it's done on purpose to avoid the extra cost of an unnecessary indirection layer. Unless you can give a strong use-case for introducing back this indirection? (pragmatic use-case, not theoretical)

**Comment by Josh-Cena** [comment]
The use-case _is_ that now theme-common is explicitly dependent on content-docs instead of implicitly through theme aliases, and there's no way to rid `content-docs/client` from the client bundle now.

**Comment by slorber** [comment]
Then if a user reports using `theme-common` without using docs (unlikely 🤷‍♂️ ) and complains about bundle size, we can look into it by either introducing back indirection or ensuring tree-shaking works better. 

I don't think this is valuable to dedicate much time to this atm, but conceptually I agree.

**Comment by Josh-Cena** [comment]
Yes, that's basically the idea. Quite annoying (because it signals smelly architecture) but not high-priority. Just here to raise awareness and discuss some solutions.

**Comment by slorber** [comment]
I guess we can close this now that theme-common does not depend on content plugins anymore 

(at least it will be the case in v4 soon: see https://github.com/facebook/docusaurus/pull/10316)
