### ISSUE TITLE
Google tag manager not working

### ISSUE THREAD

**Issue by snaveenpandi** [facebook/docusaurus#7219]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

module.exports = {
  url: "https://www.mirrorfly.com",
  baseUrl: "/docs/",
  }
*GTM working file without base url 
* we have added base Url like above value **/docs**
*google tag manager not working
*my docusaurus version **2.0.0-alpha.69**

### Steps to reproduce

module.exports = {
  url: "https://www.mirrorfly.com",
  baseUrl: "/docs/",
  }
 *GTM working file without base url 
* we have added base Url like above value **/docs**
*google tag manager not working
*my docusaurus version **2.0.0-alpha.69**

### Expected behavior

google tag manager will working as usual 

### Actual behavior

![Screenshot from 2022-04-21 10-28-59](https://user-images.githubusercontent.com/49641942/164375439-59915810-93cb-492c-b07b-d08588cc0a0a.png)

### Your environment

- Public source code:
- Public site URL:https://www.mirrorfly.com/docs/
- Docusaurus version used:2.0.0-alpha.69

### Self-service

- [X] I'd be willing to fix this bug myself.

**Comment by Josh-Cena** [comment]
2.0.0-alpha.69 is too old—we don't provide support for it. Please upgrade to beta.18.

**Comment by snaveenpandi** [comment]
yes,if i upgrade version build not working properly
clean css library throw error @Josh-Cena 


![Screenshot from 2022-04-21 11-37-57](https://user-images.githubusercontent.com/49641942/164385594-28326443-821d-49bd-80ce-b9178bade0b9.png)

**Comment by Josh-Cena** [comment]
Sorry, without a repro, I can't debug this. Please provide the exact setup on which I can inspect the issue.

**Comment by Josh-Cena** [comment]
Closing because this issue is unactionable. Please don't use GitHub issue tracker as a support forum.
