### ISSUE TITLE
Google Analytics 4

### ISSUE THREAD

**Issue by slorber** [facebook/docusaurus#7221]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Motivation

Google  introduced Google Analytics 4 and is going to sunset its former analytics system in July 2023

https://blog.google/products/marketingplatform/analytics/prepare-for-future-with-google-analytics-4/

Analytics data will not be migrated to the new system

For sites that want to migrate to Analytics 4 and keep historical data, they can run both analytics side-by-side so when the former analytics system is shut down, they have enough historical data

For these reasons, we should not wait until the final deadline to support Google Analytics 4 in Docusaurus, and allow sites to seamlessly/incrementally migrate to Analytics 4.

### Self-service

- [ ] I'd be willing to do some initial work on this proposal myself.

**Comment by Josh-Cena** [comment]
I've been constantly confused by the Google Analytics system. I think I've asked in multiple places what it takes to support GA4, but to this day I don't know what it would be like 😅

**Comment by johnnyreilly** [comment]
I'm already using GA 4 with Docusaurus.... Does anything actually need to be done here?

**Comment by slorber** [comment]
@johnnyreilly you probably know better than us 😅 I didn't read the GA4 doc much.

We should probably document that anyway so that users can migrate incrementally.

**Comment by Josh-Cena** [comment]
Ah yes, last time John sent a PR to update our docs to not use the legacy GA tracking ID format. I still have little idea what's going on though...

**Comment by slorber** [comment]
So what I understand is that for GA4, we should simply keep using the gtag plugin but only update the trackingId to use a new one?

Will the Docusaurus google-analytics plugin remain useful in 1 year?

What happens if a Docusaurus user was already using gtag plugin with another tracking id (unlike you @johnnyreilly?), and wants a seamless transition


---

IE how will those sites be able to upgrade incrementally without losing the ability to check analytics this year?

https://github.com/facebook/jest/blob/main/website/docusaurus.config.js#L77 (using gtag)
https://github.com/facebook/react-native-website/blob/main/website/docusaurus.config.js#L95 (looks duplicate/weird 🤷‍♂️ )

---

Atm I'm not sure it's possible to run 2 instances of the gtag plugin

**Comment by johnnyreilly** [comment]
So I'm no expert but I'll share my experience. Consider my config:

```json
        googleAnalytics: {
          trackingID: 'UA-51754530-2',
          anonymizeIP: true,
        },
        gtag: {
          trackingID: 'G-226F0LR9KE',
          anonymizeIP: true,
        },
```

https://github.com/johnnyreilly/blog.johnnyreilly.com/blob/4e824dc2172efca72c075f1dbc3a39a92fd22064/blog-website/docusaurus.config.js#L30

I have `googleAnalytics` and `gtag` running side by side. Both are sending traffic. To my knowledge, Google analytics instances will not be migrated to GA4, you have to create a new instance. 

My expectation would be that people do what I've done, which is:

- set up a GA4 instance
- start sending traffic to it alongside the existing Google analytics instance if you have one
- know that Google analytics instances will stop working in future

**Comment by slorber** [comment]
> Is this a real scenario?


Jest:

```js
        gtag: {
          trackingID: 'UA-44373548-17',
        },
``` 

How does it start sending data to GA4 asap, but also keep sending data to the current instance so that it remains possible to use analytics in the year to come?

**Comment by johnnyreilly** [comment]
So my own scenario was that I *thought* I was sending data to GA4 for ages. I just thought it hadn't started showing up yet (they advise the first can take a couple of days to show)

Only later I discovered my config was wrong and it didn't work. But that's my own story - could be worth asking the Jest team if they're getting GA4 data using this approach - they may have more information to share!

**Comment by slorber** [comment]
I will have to check with @SimenB or Meta, not sure who manage Google Analytics access for Jest 🤪

**Comment by SimenB** [comment]
No clue. @rickhanlonii maybe knows?

**Comment by nikitavoloboev** [comment]
I can confirm that using [plugin-google-gtag](https://docusaurus.io/docs/api/plugins/@docusaurus/plugin-google-gtag) plugin (following instructions there) and putting this web stream starting from G-.. as id works well.

![CleanShot 2022-05-29 at 16 45 06@2x](https://user-images.githubusercontent.com/6391776/170875448-cd81ab67-68cd-434a-8b8e-863323f46da3.png)

**Comment by nikitavoloboev** [comment]
Actually it's strange. Perhaps it's not working. 

![CleanShot 2022-05-29 at 17 25 29@2x](https://user-images.githubusercontent.com/6391776/170877383-a48c1595-2ceb-47fc-aae0-a11ab40098be.png)

It says `No data received from your website yet` but I gave it the right id. Also in bottom it says that it knows there were users in last 30 minutes.

So no idea what I am doing wrong or if it's a bug with Docu or Google Analytics.

**Comment by nikitavoloboev** [comment]
Had to confirm after a while but it does seem that I only get real time data. There is no historical data being saved.

**Comment by slorber** [comment]
In https://github.com/facebook/docusaurus/pull/8470

I'm deprecating the google-analytics plugin.
Indeed it should become useless in July 2023

Migration instructions from Google: https://developers.google.com/analytics/devguides/migration/ua/analyticsjs-to-gtagjs

Note we are also adding a google-tag-manager plugin.

Both gtag and google-tag-manager have their specific use-cases. It would be hard to document this in depth and I'm not an expert but:
- If you are looking for a simple replacement for google-analytics, gtag is the plugin I'd recommend.
- If you also need more advanced things, like tracking conversions when running Google Ads, then you'd rather use the google-tag-manager

Refer to Google documentation to understand which tag system is for you:
https://support.google.com/tagmanager/answer/7582054?hl=en
(I can agree it's not always easy to figure out)

**Comment by slorber** [comment]
We deprecated our google-analytics plugin in Docusaurus v2.3: https://docusaurus.io/blog/releases/2.3

The most straightforward replacement is the gtag plugin.

Google says here that the "analytics" (used by our deprecated plugin) is a deprecated library:
https://developers.google.com/analytics/devguides/collection/analyticsjs

<img width="968" alt="CleanShot 2023-01-27 at 19 05 04@2x" src="https://user-images.githubusercontent.com/749374/215161470-b5fb96e3-f1ec-4c30-9fd2-3dfd0f46d045.png">

By default the Docusaurus plugins only record page view events. We did the analytics => gtag code conversion a long time ago already and provide the gtag plugin.

```js
// old analytics.js code
      window.ga(
        'set',
        'page',
        location.pathname + location.search + location.hash,
      );
      // Always refer to the variable on window in-case it gets
      // overridden elsewhere.
      window.ga('send', 'pageview');

// new gtag.js code
        window.gtag(
          'set',
          'page_path',
          location.pathname + location.search + location.hash,
        );
        window.gtag('event', 'page_view');
```

Unless you are `window.ga()` function yourself, the migration should be straightforward: you should just replace one plugin with another and keep the same tracking id (note: you should now use a GA4 id!).

If you use custom `window.ga()` calls on your site, make sure to migrate that code to the new `gtag` API following Google documentation: https://developers.google.com/analytics/devguides/migration/ua/analyticsjs-to-gtagjs

**Comment by slorber** [comment]
As part of the UA => GA4 transitions, our gtag plugin will now support multiple tracking ids.

This permits you to add your new GA4 property without stopping collecting analytics to your old UA property.

```js
{
  trackingID: ['G-E5CR2Q1XYZ', 'UA-141789XYZ-1'],
}
```

(the order of ids shouldn't matter)

This should be released in Docusaurus v3.2.1 soon

PR: https://github.com/facebook/docusaurus/pull/8620

**Comment by Josh-Cena** [comment]
> This should be released in Docusaurus v2.3.1 soon

We can discuss it further privately, but that PR was a feat PR, which means it should go into a minor bump. I suggest we batch all fix commits into an immediate patch update first, and wait for the regular release schedule for 2.4.0.

**Comment by slorber** [comment]
Just a reminder that you can now remove your Universal Analytics tracking id, as it's now useless.

We removed it from the Docusaurus site in https://github.com/facebook/docusaurus/pull/9384, and now we have one less 404 request + console error

**Comment by slorber** [comment]
In Docusaurus v4, the `@docusaurus/plugin-google-analytics` has been removed for the reasons explained above.

You can now use either:
- `@docusaurus/plugin-google-gtag` - or `presetOptions.gtag`
- `@docusaurus/plugin-google-tag-manager` - or `presetOptions.googleTagManager` 

See also:
- https://github.com/facebook/docusaurus/issues/10332
- https://github.com/facebook/docusaurus/pull/12081
