### ISSUE TITLE
ios v11.4.1 ReferenceError: Can't find variable: globalThis

### ISSUE THREAD

**Issue by crackAsmiles** [facebook/docusaurus#7237]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io.
- [ ] I have read the console error message carefully (if applicable).

### Description

It runs successfully on PC, but the navigation click is invalid in iPhone Ios system 11.4. Check the error log as“ReferenceError: Can't find variable: globalThis”

version 2.0.0-beta.18

### Steps to reproduce

  Can't find variable: globalThis

### Expected behavior

I can click the drop-down navigation success

### Actual behavior

ReferenceError: Can't find variable: globalThis 

### Your environment

- Public source code:
- Public site URL:
- Docusaurus version used:
- Environment name and version (e.g. Chrome 89, Node.js 16.4):
- Operating system and version (e.g. Ubuntu 20.04.2 LTS):

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by Josh-Cena** [comment]
Hi! Please see https://docusaurus.io/docs/browser-support. ios 11.4 is not included in the default browserslist range. Please try decreasing the range. (You may still hit other non-polyfillable things, but this is easily polyfillable)
