### ISSUE TITLE
Error in code-blocks zh-CN docs

### ISSUE THREAD

**Issue by Eating-Eating** [facebook/docusaurus#7261]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Description

https://docusaurus.io/zh-CN/docs/markdown-features/code-blocks#imports

In "ButtonExample" ,"SyntaxError: Unexpected token (4:31)" reported in code block by missing '=' .

Error :
![image](https://user-images.githubusercontent.com/47847099/165909180-4d0687b9-24c0-45d8-90ac-f7b1f140c88b.png)

Correct :
![image](https://user-images.githubusercontent.com/47847099/165909583-6eeeac92-ec15-443a-ac22-1fc902668dbf.png)

### Self-service

- [X] I'd be willing to address this documentation request myself.

**Comment by Josh-Cena** [comment]
Thanks for the report. The translation guideline is here: https://github.com/facebook/docusaurus/issues/3526 You can contribute the translation yourself on Crowdin.

**Comment by Eating-Eating** [comment]
> Thanks for the report. The translation guideline is here: #3526 You can contribute the translation yourself on Crowdin. It doesn't go through GitHub.

Code-block do not allow to be edited. And it seems not only zh-CN will represent this issue,all language have the same issue except English.

**Comment by Josh-Cena** [comment]
Are you on the right version? Duplicate strings will only be translatable in one place. But in my UI, it's not only translatable, but also translatable in a very absurdly wrong way😅

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/55398995/165913952-ea3476d5-d631-48c1-b16a-3d1b916711d3.png">

cc @slorber

**Comment by Josh-Cena** [comment]
I think I know what's wrong. Will try to repair it. Thanks for reporting @Eating-Eating! I don't really read the Chinese docs myself but lots of people do, so it's always good if people can update that often.

**Comment by Eating-Eating** [comment]
thanks, amazing efficiency!
