### ISSUE TITLE
Invalid URL in field "id" (in "itemListElement.item") in Search Console

### ISSUE THREAD

**Issue by metmarkosaric** [facebook/docusaurus#7303]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [ ] I have tried the `npm run clear` or `yarn clear` command.
- [ ] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io.
- [ ] I have read the console error message carefully (if applicable).

### Description

Hi! We just [upgraded](https://github.com/plausible/docs/pull/225/commits/dea82a254ef61086e40f1db5b2d2e38ecd3d6ed8) to `^2.0.0-beta.18` on [our docs](https://plausible.io/docs) and Google Search Console flagged this issue:

```

> Breadcrumbs structured data issues detected
> 
> Search Console has identified that your site is affected by 1 Breadcrumbs structured data issue(s):
> 
> Top Warnings
> 
> Warnings are suggestions for improvement. Some warnings can affect your appearance on Search; some might be reclassified as errors in the future. The following warnings were found on your site:
> 
> `Invalid URL in field "id" (in "itemListElement.item")`
> 
> We recommend that you fix these issues when possible to enable the best experience and coverage in Google Search.

```

Is this something we can fix ourselves? Thank you!

### Steps to reproduce

- Use the latest version
- Verify your docs site on Google Search Console
- Search Console might flag this as an issue for your site too

### Expected behavior

Hopefully no error flagged by Search Console

### Actual behavior

Nothing is broken. Everything looks fine from the user's perspective. This is more of a technical/SEO issue flagged by Google Search Console itself. Fixing it might help in terms of the way doc pages display in the search results.

### Your environment

- Public source code:
- Public site URL:
- Docusaurus version used:
- Environment name and version (e.g. Chrome 89, Node.js 16.4):
- Operating system and version (e.g. Ubuntu 20.04.2 LTS):

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by Josh-Cena** [comment]
Duplicate of #7241

**Comment by Josh-Cena** [comment]
If you read that thread, you'll see we actually _want_ to fix it, but I'm not aware of a way to😅 Would you be happy if I close this in favor of #6953, or do you want something to fix it right now? You can always address this in userland by making sure every breadcrumb item has an href.

**Comment by metmarkosaric** [comment]
ah sorry about that and thank you! was searching for `itemListElement.item` and didn't find anything. closing this

**Comment by Josh-Cena** [comment]
Yes, if you have a solid proposal about how we can fix this, feel free to share 👍

**Comment by metmarkosaric** [comment]
thanks! i'm not really sure how it can be fixed, sorry. i'm working in marketing and noticed this flagged by Search Console immediately after our latest docs upgrade while our devs told me it's not something they can fix

**Comment by Josh-Cena** [comment]
You can tell them to fix it by:

1. Making every category have an index page
2. Removing breadcrumbs
3. `yarn swizzle DocBreadcrumbs` and re-implementing the microdata markup

**Comment by metmarkosaric** [comment]
thanks, will share that!
