### ISSUE TITLE
Why the onPageNav can not be shown in BlogPostsLayout?

### ISSUE THREAD

**Issue by ysyfff** [facebook/Docusaurus#733]
Hi,I want to show onPageNav in my blog, but I do not know how even after reading your source code. 
And I don't figure out why it can't be shown in BlogPostsLayout with the siteConfig.onPageNav equals separate.
Can you help me?

**Comment by JoelMarcey** [comment]
Hi @ysyfff  - a pull request that just landed https://github.com/facebook/Docusaurus/pull/682 should fix this problem in the next release.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ysyfff** [comment]
Hi @JoelMarcey , thanks for telling this. You mean you have merged that code but not released. It makes sense.
