### ISSUE TITLE
Navbar dropdown instantly collapses when moving cursor off the label on Safari

### ISSUE THREAD

**Issue by Airmime** [facebook/docusaurus#7330]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [x] I have tried the `npm run clear` or `yarn clear` command.
- [ ] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io.
- [ ] I have read the console error message carefully (if applicable).

### Description

Hi,

After updating to version 2.0.0-beta.19, the dropdown docs version is not working properly on Safari.

The hover doesn't detect the block to display the version list.

![Demo](https://im2.ezgif.com/tmp/ezgif-2-e9db1a1658.gif)

Therefore, we cannot choose a version from the list.

Note that this problem does not seem to be present on Chrome.

### Reproducible demo

https://github.com/Airmime/minstyle.io-Website/tree/V2.0.1

### Steps to reproduce

1. Create new version.
2. Display the docsVersionDropdown.

### Expected behavior

Select a version from the dropdown.

### Actual behavior

Display the block under the dropdown and select the desired version.

### Your environment

- Public source code: https://github.com/Airmime/minstyle.io-Website/tree/V2.0.1
- Public site URL:
- Docusaurus version used: 2.0.0-beta.19
- Environment name and version (e.g. Chrome 89, Node.js 16.4): Safari 15.4
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): macOS 12.3.1

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by Josh-Cena** [comment]
Hi, I can't reproduce this on your site:

![Test](https://user-images.githubusercontent.com/55398995/166851658-6c7877f1-6c54-45ac-b979-a510bd502e47.gif)

Do you have a demo lying somewhere?

**Comment by Josh-Cena** [comment]
Ah, I can reproduce this now, will investigate

**Comment by Airmime** [comment]
Yes, it's very inconsistent.

No, it doesn't work if you let the fade-in animation end.

https://user-images.githubusercontent.com/13817797/167134932-07af8667-4c6a-4a02-83ca-1d414a74de4b.mov

I have the same problem on [docusaurus.io/](https://docusaurus.io/)

**Comment by lex111** [comment]
@Airmime please check it out [the demo site](https://deploy-preview-255--infima.netlify.app/demo/), are you still experiencing this issue with dropdown? 
![image](https://user-images.githubusercontent.com/4408379/167315728-fd8ac80d-544e-4574-a7e3-0a59e2f51b05.png)

**Comment by Airmime** [comment]
It looks better to me, I don't reproduce the problem 👍
