### ISSUE TITLE
Docusaurus showcase page styling broken

### ISSUE THREAD

**Issue by duanwilliam** [facebook/docusaurus#7331]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Description

#7306 broke showcase page css. presumably restoring the `showcaseList` and `checkboxList` class names in `website/src/pages/showcase.tsx` should fix it

before (https://deploy-preview-7310--docusaurus-2.netlify.app/showcase):
<img width="697" alt="image" src="https://user-images.githubusercontent.com/38791932/166851323-b3bc10ec-2ff2-4779-9232-a63c559e3ace.png">

after (https://deploy-preview-7306--docusaurus-2.netlify.app/showcase/ , and on live site):
<img width="638" alt="image" src="https://user-images.githubusercontent.com/38791932/166851066-bac39ef8-6893-413c-a853-4757a2d531b7.png">

### Self-service

- [ ] I'd be willing to address this documentation request myself.

**Comment by Josh-Cena** [comment]
Thanks for reporting! If you want to send a PR feel free to
