### ISSUE TITLE
Category with no items is being removed from the sidebar

### ISSUE THREAD

**Issue by kolos450** [facebook/docusaurus#7348]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

Sidebar items postprocessor nicely converted empty categories to normal links.
https://github.com/facebook/docusaurus/blob/9207cafec720d65aca58f104943562046d8f861b/packages/docusaurus-plugin-content-docs/src/sidebars/postProcessor.ts#L53

This behavior has been broken in 2.0.0-beta19 by the new draft documents feature.
The code below removes such items now.
https://github.com/facebook/docusaurus/blob/9207cafec720d65aca58f104943562046d8f861b/packages/docusaurus-plugin-content-docs/src/sidebars/processor.ts#L93

### Steps to reproduce

1. Create a new Docusaurus website, `npx create-docusaurus@latest website classic`.
2. Use the following `sidebars.js`:

   ```js
   const sidebars = {
     tutorialSidebar: [
       {
         type: 'doc',
         label: 'Intro',
         id: 'intro'
       },
       {
         type: 'category',
         label: 'Congrats',
         items: [],
         link: { type: 'doc', id: 'tutorial-basics/congratulations' }
       }
     ]
   };
   
   module.exports = sidebars;
   ```

### Expected behavior

Two items in the sidebar.

### Actual behavior

A single item in the sidebar.

### Your environment

- Docusaurus version used: 2.0.0-beta19

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by slorber** [comment]
it is expected that draft items are removed from prod build, and that empty categories are removed too

I don't understand the problem. The concept of "draft doc" is new.

Please create a repro or at least give markdown file contents

**Comment by kolos450** [comment]
> empty categories are removed too

No, empty categories were not removed but converted to links if their `link` property wasn't empty as of 2.0.0-beta18.

But in 2.0.0-beta19 this behavior was changed. I believe it's a typo, but such empty categories are considered drafts and removed now.
Please examine the following lines:
https://github.com/facebook/docusaurus/blob/9207cafec720d65aca58f104943562046d8f861b/packages/docusaurus-plugin-content-docs/src/sidebars/processor.ts#L93
`items` property is empty and `every` returns `true`.

> at least give markdown file contents

Markdown file contents play no role, the only change from the initial skeleton is sidebars.js file.

**Comment by Josh-Cena** [comment]
Thanks for the report @kolos450 you seems to have nailed the cause. Before I investigate this, PRs welcome!

**Comment by Josh-Cena** [comment]
Fixed in #7385. Please try the [canary version](https://docusaurus.io/community/canary).

**Comment by andrewnicols** [comment]
Thanks - confirmed working with Canary.

**Comment by webbertakken** [comment]
I can also confirm. Works like a charm on canary `0.0.0-5035`.

**Comment by slorber** [comment]
now released in beta.21
