### ISSUE TITLE
Cloudflare

### ISSUE THREAD

**Issue by Luchanso** [facebook/Docusaurus#736]
Hey guys, cloudflare cdn not work in russia 😢 
Could you put highlight.js styles into project?

![image](https://user-images.githubusercontent.com/2098777/41099175-5ddf63cc-6a66-11e8-8119-baf7d98fa6ef.png)

**Comment by MartinKolarik** [comment]
Alternatively, https://cdn.jsdelivr.net/npm/highlight.js@9.12.0/styles/ works everywhere including Russia and China (and jsDelivr is already used for docsearch too).

**Comment by Luchanso** [comment]
@MartinKolarik I thing all libs must be load from dev server, because docs can be using in private network without outside internet access

**Comment by MartinKolarik** [comment]
It depends. For public docs the CDN is better, for private probably not, but the URL [is actually configurable](https://docusaurus.io/docs/en/site-config) (search for `themeUrl`).

**Comment by Luchanso** [comment]
Yeah, you right 👍

**Comment by endiliey** [comment]
Thank you @MartinKolarik for pointing it out. Does it solve your problem @Luchanso ? Otherwise we can close this

**Comment by JoelMarcey** [comment]
![screenshot 2018-06-07 06 53 04](https://user-images.githubusercontent.com/3757713/41104086-77358af0-6a1f-11e8-8185-cde539fe7bbe.png)

Yep that should do it here, right? Closing. Please reopen if this doesn't solve your problem. Thanks!

**Comment by MartinKolarik** [comment]
If would be good if the default was something that works for everyone though.

**Comment by JoelMarcey** [comment]
I think the default works for most people, but that's why we have the configuration options in case it doesn't in cases we do not know about. Are you saying this won't work for you?

**Comment by incecumali** [comment]
How can I remove external source of https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/styles/default.min.css
I downloaded `default.min.css` and placed  under 'css' folder of Docusurus but external link of  Cloudflare still appears 
![external](https://user-images.githubusercontent.com/23002340/64418709-d1360f00-d09b-11e9-8d5e-98f0ca35d50b.png)
