### ISSUE TITLE
Document the ability to provide a custom layout

### ISSUE THREAD

**Issue by JoelMarcey** [facebook/Docusaurus#737]
### Is this a bug report?

No. See https://github.com/facebook/Docusaurus/pull/128 for implementation details.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

### Environment

N/A

### Steps to Reproduce

See https://github.com/facebook/Docusaurus/pull/128

### Expected Behavior

N/A

### Actual Behavior

N/A

### Reproducible Demo

N/A

**Comment by FarooqAR** [comment]
Can I take this issue?

**Comment by JoelMarcey** [comment]
@FarooqAR Absolutely. Thank you very much! When you send the PR, we will review.

**Comment by FarooqAR** [comment]
@JoelMarcey Hasn't [pr#763](https://github.com/facebook/Docusaurus/pull/763) already solved this issue?

**Comment by JoelMarcey** [comment]
Ah -- I didn't even see that PR. Sorry. I guess it has been taken.

If you have feedback on the PR, please let us know in the PR itself.

**Comment by endiliey** [comment]
Custom layout got removed because upon investigation it actually doesn't work :sob:

Let's leave custom layout on v2 implementation
