### ISSUE TITLE
Multilingual blog support language-exclusive article

### ISSUE THREAD

**Issue by robberphex** [facebook/docusaurus#7378]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Description

Could docusaurus support language-exclusive article?

For example, there are some article:
```
blog/
├── 2019-05-28-multilingual-blog-translated.md
├── 2019-05-29-multilingual-blog-untranslated.md
└── 2019-06-28-english-only-blog.md
i18n/zh-cn/docusaurus-plugin-content-blog/
├── 2019-05-28-multilingual-blog-translated.md
└── 2019-07-28-chinese-only-blog.md
```

* multilingual-blog-translated.md
  This kind of article exists at `blog/` and `i18n/zh-cn/docusaurus-plugin-content-blog/`, so this article could show on en and zh-cn site.
* multilingual-blog-untranslated.md
  This kind of article only exists at `blog/`, but this article should be displayed on en and zh-cn site.
* <langId>-only-blog.md
  This kind of article only exists at single folder, and only showed at corresponding site.
  For example, `chinese-only-blog.md` at `i18n/zh-cn/docusaurus-plugin-content-blog/`, only showed at zh-cn site. `english-only-blog.md` at `blog/`, only showed en site.

For distinguish language-exclusive article and multilingual article,  could we introduce a new option at frontmatter?

*And [there is an example project](https://github.com/robberphex/rblog/tree/9c73a72192f446decb3566a3a6590211e3c6a134).*

### Has this been requested on Canny?

No

### Motivation

To support multilingual content more natively.

### Self-service

- [ ] I'd be willing to contribute this feature to Docusaurus myself.

**Comment by Josh-Cena** [comment]
This is very likely a wontfix. It's both because of technical limitation and because the possible bad UX that this will bring.
