### ISSUE TITLE
Proposal: Add support for comments powered by Discourse

### ISSUE THREAD

**Issue by balloob** [facebook/Docusaurus#738]
For Home Assistant we use Discourse for commenting. [Discourse](https://www.discourse.org/) is open source forum software. The way it works is similar to how Facebook commenting works: you load a piece of JavaScript[1] and it will allow people to comment ([example](https://www.home-assistant.io/blog/2018/04/26/developer-site/)).

Would a pull request be accepted that adds support for configuring Discourse comments for Docusaurus blog posts?

I would structure it similarly to how the existing Docusaurus FB comments feature is done ([source](https://github.com/facebook/Docusaurus/pull/673/files#diff-5306f2fdb0f2ca91fc23a32bafa9e1a0R19)).

[1]: Code looks like this:

```js
  DiscourseEmbed = { discourseUrl: 'https://community.home-assistant.io/',
                     discourseEmbedUrl: 'URL OF PAGE THAT IS BEING EMBEDDED' };
  (function() {
    var d = document.createElement('script'); d.type = 'text/javascript'; d.async = true;
    d.src = DiscourseEmbed.discourseUrl + 'javascripts/embed.js';
    (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(d);
  })();
```

**Comment by JoelMarcey** [comment]
Hi @balloob Thanks for the feature request. We have add other issues discuss this too:

https://github.com/facebook/Docusaurus/issues/667
https://github.com/facebook/Docusaurus/issues/219

I would definitely be willing to review a PR. Does it prevent spam well?

**Comment by balloob** [comment]
People can host their own copy and set up user registration as they like. We have it set up with email verification as a requirement before posting and have not seen any spam.

**Comment by endiliey** [comment]
I will close this since we already have FB comment for v1. On v2 user can extends their own layout and write React component so this is up to the user
