### ISSUE TITLE
Sidebar categories don't autocollapse when navigating via paginator

### ISSUE THREAD

**Issue by pranabdas** [facebook/docusaurus#7387]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Motivation

When `autoCollapseCategories` is set to `true`, I think it would be consistent to collapse all the non-current sidebar categories leaving only one actively open category. This is what happens when we open a new sidebar category by clicking on the sidebar. However, if we trigger open a new category via `PaginatorNavLink` button, it does not trigger collapse for the previously opened categories.

For example, let's open <https://docusaurus.io/docs/typescript-support>, which is the last page of **Getting Started** category. Now clicking on the next category i.e., **Guides** in the sidebar would collapse the **Getting Started** and open **Guides**. Now, go back to previous page, scroll down to the bottom of the page, and click the Next button, it will open **Guides** category in the sidebar but also leave the **Getting Started** open.

### Self-service

- [x] I'd be willing to do some initial work on this proposal myself.

**Comment by Josh-Cena** [comment]
It's a bug. We should always leave only one category open.

The entire logic around this is a bit messy. I don't even fully know what's going on...
