### ISSUE TITLE
Powershell ISE Error - invalid argument "" for "-w, --terminal-width" flag: strconv.ParseInt: parsing "": invalid syntax

### ISSUE THREAD

**Issue by Hecter25** [facebook/docusaurus#7399]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [ ] I have tried the `npm run clear` or `yarn clear` command.
- [ ] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io.
- [ ] I have read the console error message carefully (if applicable).

### Description

Error when opening Powershell ISE - Any suggestions

Error: invalid argument "" for "-w, --terminal-width" flag: strconv.ParseInt: parsing "": invalid syntax
Usage:
  oh-my-posh prompt print [debug|primary|secondary|transient|right|tooltip|valid|error] [flags]

Flags:
      --command string         tooltip command
  -e, --error int              last exit code
      --eval                   output the prompt for eval
      --execution-time float   timing of the last command
  -h, --help                   help for print
  -p, --plain                  plain text output (no ANSI)
      --pswd string            current working directory (according to pwsh)
      --pwd string             current working directory
      --shell string           the shell to print for
      --shell-version string   the shell version
  -s, --stack-count int        number of locations on the stack
  -w, --terminal-width int     width of the terminal

Global Flags:
  -c, --config string   config (required)

### Steps to reproduce

Profile configuration

oh-my-posh init pwsh --config ~/.jandedobbeleer.omp.json | Invoke-Expression
Set-ExecutionPolicy -ExecutionPolicy Unrestricted
Import-Module Terminal-Icons

Works fine in Terminal and Powershell

### Expected behavior

Prompt in ISE would look like powershell/terminal

### Actual behavior

error on statup

### Your environment

- Operating system and version Windows 11

### Self-service

- [X] I'd be willing to fix this bug myself.

**Comment by Josh-Cena** [comment]
Sorry, that doesn't seem Docusaurus-related at all. Please come back with more details.

**Comment by Hecter25** [comment]
I'm sorry I posted this in completely the wrong place. Thanks for the quick response

Dexter Rechnitz
________________________________
