### ISSUE TITLE
Docusaurus for large documentation site - JavaScript heap out of memory

### ISSUE THREAD

**Issue by fawazahmed0** [facebook/docusaurus#7410]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [ ] I have tried the `npm run clear` or `yarn clear` command.
- [ ] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

Here is the link to [build log](https://github.com/fawazahmed0/quran-hadith-search/runs/6415526895?check_suite_focus=true#step:5:18)

Similar https://github.com/facebook/docusaurus/issues/1782 https://github.com/facebook/docusaurus/discussions/3132

The workaround is to use `export NODE_OPTIONS="--max-old-space-size=SOME_LARGE_NUM"` ,but in my case I am using github actions, which only support [14GB RAM max](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources)

### Steps to reproduce

Need a Large documentation site. Here is the link to my [repository](https://github.com/fawazahmed0/quran-hadith-search), which generated large documentation site during `build`

### Expected behavior

Should build

### Actual behavior

Build fails

### Self-service

- [X] I'd be willing to fix this bug myself.

**Comment by Josh-Cena** [comment]
Let's discuss in https://github.com/facebook/docusaurus/issues/4765 instead. We are aware of this issue, but without some benchmarking, this issue is unactionable, and complaining that "it doesn't work" doesn't add anything meaningful to the investigation.

**Comment by fawazahmed0** [comment]
I tried `esbuild-loader` , but that doesn't seem to work in my use case, I guess increasing ram is the only option for me. Thanks anyways.
