### ISSUE TITLE
(0 , _mdx_js_react__WEBPACK_IMPORTED_MODULE_2__.mdx) is not a function

### ISSUE THREAD

**Issue by Anonymous1231-dev** [facebook/docusaurus#7416]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io.
- [x] I have read the console error message carefully (if applicable).

### Description

When I tried to go to a page at `localhost:3000` after updating `yarn.lock` it gives me this:

```
(0 , _mdx_js_react__WEBPACK_IMPORTED_MODULE_2__.mdx) is not a function

```
I suspicious this is the problem in react, as the comment in #6520 

### Steps to reproduce

1. Using `yarn install ` to get dependies.
2. `yarn start`
3. Clicking at "About me"
4. Page crashed 😢

### Expected behavior

About page should be show like this:

![Screenshot_20220514_152843](https://user-images.githubusercontent.com/87801676/168415727-32987183-473f-4941-bee0-942f0b5e7c19.jpg)

### Actual behavior

![Screenshot_20220514_151934](https://user-images.githubusercontent.com/87801676/168415438-da3eef49-c9b0-4848-b182-1dcfbe7da466.jpg)

- The recording

https://user-images.githubusercontent.com/87801676/168415851-d0846326-0b2c-4de8-864a-87c1df832ca1.mp4

### Your environment

- Public source code: it is closed source
- Public site URL: 
- https://anonymous1231-dev.vercel.app (Currently it's working)
- https://anonymous1231-2xkn69l9d-anonymous1231-dev.vercel.app (deployment info)
- Docusaurus version used: beta.20
- Environment name and version (e.g. Chrome 89, Node.js 16.4): Chrome 101 , nodejs 17.9
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): Android 12 

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by Josh-Cena** [comment]
Please make sure you have `"@mdx-js/react": "^1.6.22"` in your package.json, instead of v2.

**Comment by Anonymous1231-dev** [comment]
But the version is true

```
~/my-website $ yarn list | grep @mdx-js/react
│  ├─ @mdx-js/react@^1.6.22
│  ├─ @mdx-js/react@1.6.22
├─ @mdx-js/react@2.1.1
```

**Comment by Josh-Cena** [comment]
> @mdx-js/react@2.1.1

What's that coming from, though...

**Comment by Anonymous1231-dev** [comment]
Oops 😬
