### ISSUE TITLE
The gtag plugin sends the previous document title

### ISSUE THREAD

**Issue by ori-shalom** [facebook/docusaurus#7420]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

The default Docusaurus gtag plugin reports wrong page titles to Google Analytics.
The gtag plugin adds a client module that uses `onRouteDidUpdate` event to send to GA the pathname and the page title.

https://github.com/facebook/docusaurus/blob/a2c993bf9ab4309fc5aa1906c887f944ebb850cb/packages/docusaurus-plugin-google-gtag/src/gtag.ts#L1-L33

The `title` element reported to GA is the title of the last visited page instead of the title of the current page.
I suspect the issue is the way the title is updated internally with `react-helmet-async` which causes it to be the old title at the time of the `onRouteDidUpdate` event.

## Reproduction

I created this reproduction of the issue by imitating the way the gtag plugin works by registering a client module with `onRouteDidUpdate` that logs to console the current location pathname, page title, and actual page h1 to see if the page content was updated at the time of the event.

https://stackblitz.com/edit/github-fab3de?file=docusaurus.config.js

You can navigate to different pages and see in the console that both the pathname and the page content are updated in time for the event while the title is still of the previous page.

### Logs:
```
{
  event: 'onRouteDidUpdate',
  pathname: '/docs/page2',
  title: 'Page 1 | issue #7420',
  docH1: 'Page 2'
}
{
  event: 'onRouteDidUpdate',
  pathname: '/docs/page3',
  title: 'Page 2 | issue #7420',
  docH1: 'Page 3'
}
```

### Reproducible demo

https://stackblitz.com/edit/github-fab3de?file=docusaurus.config.js

### Steps to reproduce

1. Navigate between different pages (page1, page2, page3)
2. Inspect the logs to see the title, pathname, and page h1 content.

### Expected behavior

It is expected that the reported title will be the actual title of the page.

### Actual behavior

The title reported is the title of the previously visited page.

### Your environment

- Public source code: https://stackblitz.com/edit/github-fab3de?file=docusaurus.config.js
- Public site URL: https://github-fab3de--3000.local.webcontainer.io/docs/page1
- Docusaurus version used: 2.0.0-beta.20
- Environment name and version: Chrome 101.0.4951.54, Node.js 16

### Self-service

- [x] I'd be willing to fix this bug myself.

A possible solution is replacing `react-helmet-async` with `react-helmet`.
If that's all that needs to be done and it won't break anything else then maybe I can issue a PR myself but I'm not familiar enough with the Docusaurus code base to know what else it could affect and I don't have a lot of time available to devote for this.

**Comment by Josh-Cena** [comment]
We migrated from `react-helmet` to `react-helmet-async` because the latter supports asynchronous rendering (which we may eventually need). I'm going to play with other solutions. Thanks for the report!

**Comment by ori-shalom** [comment]
I found a small workaround that works for me for now.
You can see it here commented out: https://stackblitz.com/edit/github-fab3de?file=plugin%2Fclient-module.js

1. Copy the gtag plugin and use it instead of the one in the presets.
2. In the plugin client module, use `setTimeout` without any actual timeout value to simply send the callback to the end of the call stack.

This works though I admit that using `setTimeout` this way is a bit hacky.

**Comment by Josh-Cena** [comment]
I'm also thinking about `setTimeout`. In general it should be avoided, but here I _believe_ the title update always happens at the next tick of re-rendering, so simply delaying it by one tick should work already 👍

Feel free to send a PR
