### ISSUE TITLE
prism-react-renderer 1.3.2 breaks rendering

### ISSUE THREAD

**Issue by slightc** [facebook/docusaurus#7429]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

prism-react-renderer 1.3.2 is not surpport

### Steps to reproduce

- create by create-docusaurus@latest
- install
- start
- then doc render error

### Expected behavior

render success

### Actual behavior

render doc error

### Your environment

- Public source code:
- Public site URL:
- Docusaurus version used:
- Environment name and version (e.g. Chrome 89, Node.js 16.4):
- Operating system and version (e.g. Ubuntu 20.04.2 LTS):

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by Josh-Cena** [comment]
Tracked in https://github.com/FormidableLabs/prism-react-renderer/issues/152. This doesn't seem like something we can help, unfortunately.
