### ISSUE TITLE
Code Block Wrapping Behavior is Inconsistent.

### ISSUE THREAD

**Issue by alexfornuto** [facebook/docusaurus#7449]
Copied from https://github.com/facebook/docusaurus/pull/7036

@Josh-Cena thanks for the reply. Example preview [here](https://deploy-preview-57--pomerium-docusaurus.netlify.app/docs/overview/releases#packages) shows the following example, two code blocks, each in a tab:

````
<Tabs>

<TabItem value="yum" label="Yum">

```abnf title="/etc/yum.repos.d/pomerium-pomerium.repo"
[pomerium-pomerium]
name=pomerium-pomerium
baseurl=https://dl.cloudsmith.io/public/pomerium/pomerium/rpm/el/$releasever/$basearch
repo_gpgcheck=1
enabled=1
gpgkey=https://dl.cloudsmith.io/public/pomerium/pomerium/gpg.6E388440B94E1407.key
gpgcheck=1
sslverify=1
pkg_gpgcheck=1
```

</TabItem>
<TabItem value="deb" label="Deb">

```bash
curl -1sLf 'https://dl.cloudsmith.io/public/pomerium/pomerium/gpg.6E388440B94E1407.key' | apt-key add -
echo "deb https://dl.cloudsmith.io/public/pomerium/pomerium/deb/debian buster main" > /etc/apt/sources.list.d/pomerium-pomerium.list
```

</TabItem>
</Tabs>
````

While other code blocks on the linked page display and use the wrap button, these do not behave as expected:

 - In the first tab the button is present but not functioning.
 - In the second tab the button is not present, despite the code block overflowing.

This example is using 2.0.0-beta.20

_Originally posted by @alexfornuto in https://github.com/facebook/docusaurus/issues/7036#issuecomment-1130234195_

**Comment by dpang314** [comment]
@alexfornuto The changes in the pull request should resolve the behavior you ran into in [your example ](https://rad-bienenstitch-2b77e5.netlify.app/tests/pages/long-code-block-tests)
