### ISSUE TITLE
Send page_view events to Google Analytics on query string mutations

### ISSUE THREAD

**Issue by lanegoolsby** [facebook/docusaurus#7451]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Motivation

I'd like to adjust the Google Analytics plugins to also include page_view events when the query string changes. 

We have written a custom search page and noticed that the query terms are not being sent to GA. I am 90% sure its because [this if statement](https://github.com/facebook/docusaurus/blob/ba0d94d02bc24cda0735f6db57930bb5b0bb7edf/packages/docusaurus-plugin-google-gtag/src/gtag.ts#L17) does not check the search parameter. 

I propose adjusting that if statement to as follows:
```
if (previousLocation && (location.pathname !== previousLocation.pathname || location.search !== previousLocation.search)) {
```

This will allow page_view events to be fired when transitioning from `/search?q=foo` to `/search?q=bar`. 

I already have this change made locally to both the `docusaurus-plugin-google-gtag` and `docusaurus-plugin-google-analytics` projects and am willing to submit a pull request if my proposal is satisfactory. 

### Self-service

- [X] I'd be willing to do some initial work on this proposal myself.

**Comment by Josh-Cena** [comment]
Do you have examples of other sites' practices? When we are implementing its behavior, we are not really aware of what the best practices or usual practices are.

**Comment by lanegoolsby** [comment]
I'm not sure I'd consider myself an expert, but I can say that this snippet works on another unrelated search component we wrote. 

```
    const executeSearch = (evt: React.KeyboardEvent<HTMLInputElement>) => {
        if (evt.type == 'click' || (evt.type === 'keypress' && evt.key === 'Enter')) {
            searchOptions.availableTargets.forEach(e => {
                if (e.checked) {
                   //ignore this
                    const url = e.buildUrl(searchString);
                    const newWindow = window.open(url);
                    if (!newWindow) {
                        setShowWarning(true);
                    }
                   // important part starts here
                    ReactGA.event({
                        category: 'Search',
                        action: 'Popup search',
                        label: e.displayName
                    });
                    ReactGA.pageview('/?q=' + searchString);
                }
            });
        }
    };
```
Google Analytics has smarts built in that looks for the query string (which is [configurable](https://www.optimizesmart.com/how-to-set-up-site-search-tracking-in-ga4/#2-configuration-custom-search-query-parameter-) but `q=` is a default). If it detects the query string in a page_view event then it automagically trims out the query term. But in order for that to happen the page view event needs to be sent.

PS - I'm trying to write some unit tests around [this](https://github.com/facebook/docusaurus/compare/main...lanegoolsby:add_query_to_ga) but am struggling with mocking `window.ga/window.gtag`. Do you have any examples I can use for inspiration?

**Comment by Josh-Cena** [comment]
I'm not really sure what the recommended practice for mocking `window.ga` is. The one immediately on top of my head is to run this test in jsdom environment (we have other code doing so, like `packages/docusaurus/src/client/__tests__/browserContext.test.tsx`), and just assign a mocked function to `window.ga`.

Tests are not really central—we have a lot of client code yet to be tested. But if there's a GA API specifically for sending the query, I think we can implement it right away.

**Comment by lanegoolsby** [comment]
There's not a specific API for the query per se. The code just needs to allow changes to the query string to pass through that if statement. Right now that if only checks for changes to the path name.
