### ISSUE TITLE
Static file serving shows "Page Not Found", but loading on page refresh

### ISSUE THREAD

**Issue by gkzsolt** [facebook/docusaurus#7454]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io.
- [ ] I have read the console error message carefully (if applicable).

### Description

I am serving some static files (docx, pdf or png images) by putting them to the `static/` folder and referencing them with a type: 'link' in `sidebars.js`:
```
    {
        type: 'category',
        label: 'Pictures',
        items: [
            {
                type: 'link',
                label: 'My Pic',
                href: 'mypic.png',
            },
      
        ]
    },
```
But clicking on the rendered `menu__link` gives a **Page Not Found**. By reloading the page, the document is loaded. Navigating back (with the browser) will not work again, one has to reload _that_ page to show. What happens here?

Docusaurus: 2.0.0-beta.20
Google Chrome:  101.0.4951.64
Ubuntu 20.04.4 LTS

### Steps to reproduce

1. Put a file into the static directory, e.g. `docusaurus_root/static/mypic.png`
2. Create a link in a manual sidebar in sidebars.js:
```
    {
        type: 'category',
        label: 'Pictures',
        items: [
            {
                type: 'link',
                label: 'My Pic',
                href: 'mypic.png',
            },
      
        ]
    },
```
3. Serve the site through docusaurus own server in development mode:
```
npm run serve
```
4. Try to load the file in a browser by clicking on the link rendered.
5. You will get a **Page Not Found** page.
6. Reload the page in the browser.
7. The file will load and it will be shown.

### Expected behavior

I expect the file to load by clicking on the rendered link.

### Actual behavior

You will get a **Page Not Found** page instead.

### Your environment

- Docusaurus version used: 2.0.0-beta.20
- Environment name and version: Chrome 101, Node.js 16.14.2
- Operating system and version: Ubuntu 20.04.2 LTS

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by Josh-Cena** [comment]
Try `href: 'pathname:///mypic.png',`?

Documentation: https://docusaurus.io/docs/advanced/routing#escaping-from-spa-redirects

**Comment by gkzsolt** [comment]
Thank you very much! That spared a lot of time and effort.
