### ISSUE TITLE
className prop is not passed to the MDXComponents

### ISSUE THREAD

**Issue by cieldon32** [facebook/docusaurus#7489]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [ ] I have tried the `npm run clear` or `yarn clear` command.
- [ ] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io.
- [ ] I have read the console error message carefully (if applicable).

### Description

I read the source: https://github.com/facebook/docusaurus/blob/main/packages/docusaurus-theme-classic/src/theme/MDXComponents/Img/index.tsx 
and others who supports props.className

and I use <img class="images" src="#" />,  it is not work

### Steps to reproduce

<img class="images" src="#" />
<pre class="test-hidden"> Invisibility won't work?? </pre>
<ul class="demo"></ul>

### Expected behavior

these className is in the tag

### Actual behavior

not work

### Your environment

- Public source code:
- Public site URL:
- Docusaurus version used:
- Environment name and version (e.g. Chrome 89, Node.js 16.4):
- Operating system and version (e.g. Ubuntu 20.04.2 LTS):

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by Josh-Cena** [comment]
Sorry, what do you expect to work, what doesn't work? Without a repro this is unactionable.
