### ISSUE TITLE
Styling issue with docs when accessed directly via URL or page is refreshed

### ISSUE THREAD

**Issue by franko1260** [facebook/docusaurus#7494]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

I have an issue where all docs render in a very small area of the page, rather than taking up the full space of the page that is available. This only occurs when you navigate directly to a doc, if you click the browser refresh button while on a doc or if you click the "Show me how" button on the home page (https://getagora.net/)

However if you navigate to the docs by clicking the "Training" button in the navigation bar, the issue is not reproduced.

I have gone through just about all the custom styling I've applied and cannot find anything that would cause the issue, I have tried numerous different versions of most dependencies, different versions of Node, building the app in a completely fresh Ubuntu environment (as you'll be able to see in the commit history) all to no avail.

### Reproducible demo

https://bitbucket.org/nuvosoftware/agora/src/main/agora-site/

### Steps to reproduce

1. Visit any of the docs directly (i.e. https://getagora.net/docs/intro) OR refresh the page while viewing any of the docs

NOTE: If you visit the docs via clicking the "Training" button in the navigation bar, the issue is not reproduced

### Expected behavior

I would expect the contents of the doc to span the width of the browser window (see attached)
![image](https://user-images.githubusercontent.com/16366632/170252212-6f26ea90-6491-408f-9fab-f71c831e5c73.png)

### Actual behavior

The contents of the doc is only presented in a very narrow area, rendering it unreadable
![image](https://user-images.githubusercontent.com/16366632/170252496-9cfe84d2-9bc6-4dd0-bc0a-89ceab86bfc9.png)

### Your environment

- Public source code: https://bitbucket.org/nuvosoftware/agora/src/main/agora-site/
- Public site URL: https://getagora.net/
- Docusaurus version used: 2.0.0-beta.20 (the issue has also been reproduced on 2.0.0-beta.12 and 2.0.0-beta.18)
- Environment name and version (e.g. Chrome 89, Node.js 16.4): Brave 1.39.111 (the issue has also been reproduced on Edge 101.0.1210.53), Node.js 14.13.1 (the issue has also been reproduced on Node.js 12.0.0)
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): Ubuntu 20.04.4 LTS

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by Josh-Cena** [comment]
Looks like an issue with Tailwind?

<img width="1439" alt="image" src="https://user-images.githubusercontent.com/55398995/170255636-ddb281be-5137-4503-bc0a-52696eaca2f9.png">

`m-auto` is pushing everything to the center.

**Comment by franko1260** [comment]
Doh! That shouldn’t be applying to any of the docs. This can be closed, clearly not a bug with docusaurus.
