### ISSUE TITLE
NavbarWrapper throws "Cannot read properties of null (reading 'clientHeight')"

### ISSUE THREAD

**Issue by canmingir** [facebook/docusaurus#7505]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

I am trying to build own custom navbar, but the wrapper always throws an error even with empty component like this

```
import React from "react";
import Navbar from "@theme-original/Navbar";

export default function NavbarWrapper(props) {
  return <></>;
}
```

When you go to to `/docs/intro`, it throws `Cannot read properties of null (reading 'clientHeight')`

https://codesandbox.io/s/restless-forest-9qmniw

### Steps to reproduce

1. Create NavbarWrapper with `npm run swizzle @docusaurus/theme-classic Navbar -- --wrap`
2. Remove default Navbar (You may just return `<></>`)
3. Go to `/docs/intro`

### Expected behavior

It should display the custom Navbar

### Actual behavior

it throws `Cannot read properties of null (reading 'clientHeight')`

### Your environment

- Public source code: https://github.com/NucleoidJS/nucleoid.com/tree/docusaurus
- Public site URL: [https://nucleoid.com](https://nucleoid.com/)
- Docusaurus version used: 2.0.0-beta.20
- Environment name and version (e.g. Chrome 89, Node.js 16.4): Chrome 101
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): Windows 10

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by Josh-Cena** [comment]
Yep, we are aware of that. So by creating this component, your intent is to disable the navbar? Could you illustrate your use-case?

We expect an element with a `.navbar` class name somewhere in the HTML tree, which we use to determine the navbar height and offset anchor scroll positions. It's not very elegant but it's portable and works well most of the time.

Some people customized the navbar and ran into this problem. My suggest is usually to add a dummy `<span class="navbar" />` somewhere in the tree with zero width and height. That could be a solution.

**Comment by Josh-Cena** [comment]
Beware you probably don't want to have block elements within the inline `span`. Changing it to a `div` is better. Also, `navbar` comes with its styles (although it's currently just a `display: flex`, so if you want to be safe, you can tuck it into some other layout component and force it to have zero-width-zero-height.

**Comment by canmingir** [comment]
Interesting, thanks for the info, is there any embedded version of docusaurus like running as a React component that can be include project like MUI?

**Comment by Josh-Cena** [comment]
For some reason, I use MUI here: https://joshcena.com/todo/ and it works... fine? I'm not really familiar with all this.

**Comment by slorber** [comment]
>  is there any embedded version of docusaurus like running as a React component that can be include project like MUI?

Sorry but I don't understand 🤪 

> For some reason, I use MUI here: [joshcena.com/todo](https://joshcena.com/todo/) and it works... fine? I'm not really familiar with all this.

There is FOUC, this is what is displayed before React hydration or if JS fails to load or take a long time.

<img width="1888" alt="CleanShot 2022-05-26 at 16 22 57@2x" src="https://user-images.githubusercontent.com/749374/170507505-adf64d06-88a8-4e34-9394-fa02a7adecb0.png">


On content it's not a big deal, but you probably want to avoid FOUC in your Docusaurus layout
