### ISSUE TITLE
Docusaurus is trying to interpolate code blocks as if they were JS template strings

### ISSUE THREAD

**Issue by alexandernst** [facebook/docusaurus#7509]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

I'm trying to document a few command lines for Mac, WIndows and Linux and I'm using the `Tabs` component.
When I try to insert a specific command, Docusaurus crashes.

This happens (I'm guessing) because docusaurus tries to interpolate the code block as if it was a JS template string. 

Specifically speaking, this works:

```
<Tabs>
  <TabItem value="foo" label="Foo" default>
 ` ` `bash
echo $Foo
` ` `
  </TabItem>
</Tabs>
```

But this doesn't work:

```
<Tabs>
  <TabItem value="foo" label="Foo" default>
` ` `bash
echo ${FOO[bar]}
` ` `
  </TabItem>
</Tabs>
```

I made a demo.

### Reproducible demo

https://codesandbox.io/s/nervous-fog-to8fx9?file=/docs/intro.md

### Steps to reproduce

1. Go to the "intro" documentation

### Expected behavior

The doc should be rendered

### Actual behavior

The page crashes

### Your environment

- Public source code: N/A
- Public site URL: N/A
- Docusaurus version used: 2.0.0-beta20
- Environment name and version (e.g. Chrome 89, Node.js 16.4): N/A
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): N/A

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by Josh-Cena** [comment]
Please see https://github.com/facebook/docusaurus/issues/6522 and https://docusaurus.io/docs/markdown-features/react#markdown-and-jsx-interoperability

You have to put an empty line between the triple backticks and the `TabItem` tag.
