### ISSUE TITLE
Add <meta /> "description" tag

### ISSUE THREAD

**Issue by skratchdot** [facebook/Docusaurus#751]
### Is this a bug report?

Yes (more of a feature request).

It was mentioned in a PR comment (https://github.com/facebook/Docusaurus/pull/745#issuecomment-396055556) that we are missing a `<meta name="description" content="" />` tag.

There are probably some other things about the `<head />` tag we could add and clean up.  Here is a good resource to review:
https://github.com/joshbuchea/HEAD

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

### Environment

(Docusaurus version via `npm outdated docusaurus` or `yarn outdated docusaurus`, OS, Node, npm, yarn)

### Steps to Reproduce

1. View a site generated with docusaurus
2. Confirm there is no `<meta name="description" content="" />` tag

### Expected Behavior

1. View a site generated with docusaurus
2. Confirm there is a `<meta name="description" content="" />` tag

### Actual Behavior

N/A

### Reproducible Demo

N/A

**Comment by endiliey** [comment]
Let's limit it to description tag for now.

**Comment by CamiloGarciaLaRotta** [comment]
Wondering if there is a way to add the status bar color meta tags:
```html
<!-- Android -->
<meta name="theme-color" content="#c5c5c5">
<!-- iOS -->
<meta name="apple-mobile-web-app-capable" content="yes">
<meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
```
