### ISSUE TITLE
Kent C. Dodds Twitter avatar not displayed properly on docusaurus website

### ISSUE THREAD

**Issue by DharsanB** [facebook/docusaurus#7511]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [ ] I have tried the `npm run clear` or `yarn clear` command.
- [ ] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io.
- [ ] I have read the console error message carefully (if applicable).

### Description

https://github.com/facebook/docusaurus/blob/main/website/src/data/tweets.tsx#L155 should be updated from https://pbs.twimg.com/profile_images/1444988463216922631/IDffhy4i_400x400.jpg to https://pbs.twimg.com/profile_images/1529905780542959616/Ibwrp7VJ_400x400.jpg

### Steps to reproduce

1. Go to https://docusaurus.io/
2. Go to Kent C. Dodds's tweet

### Expected behavior

His twitter icon should be displayed

### Actual behavior

Alternate text is displayed

### Your environment

- Public source code: https://github.com/facebook/docusaurus
- Public site URL: https://docusaurus.io/
- Docusaurus version used: Latest
- Environment name and version (e.g. Chrome 89, Node.js 16.4): Edge Version 101.0.1210.53 (Official build) (64-bit)
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): Windows 11 Pro

### Self-service

- [X] I'd be willing to fix this bug myself.

**Comment by Josh-Cena** [comment]
Thanks, please just send a PR right away

**Comment by DharsanB** [comment]
Have submitted on https://github.com/facebook/docusaurus/pull/7512
