### ISSUE TITLE
Add the option to use build cache in CI

### ISSUE THREAD

**Issue by mattrunyon** [facebook/docusaurus#7515]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Motivation

In the `2.0.0-alpha.20` release (changelog)[https://docusaurus.io/changelog/2.0.0-alpha.20], `cache-loader` was disabled for CI because of the assumption CI always starts from scratch. This assumption is not always valid.

Related PR that made this change is #1612

For example, you can cache `node_modules/.cache` in Github Actions which can then be restored and used as a cache from the previous build. Github actions will restore the cache from the main branch if the feature branch has no cache associated with it. This would allow for significantly reduced build times in CI environments where the cache can be restored after installing modules.

Since there is no support for incremental regeneration, then this might be the next best option. In our case it reduces build from 12 min to around 3 min if the cache is present.

I'm not sure how much overhead `cache-loader` added when no cache was present, but if it is significant then adding this behind a flag seems reasonable.

### Self-service

- [x] I'd be willing to do some initial work on this proposal myself.

**Comment by mattrunyon** [comment]
Nevermind, this appears to have been re-added at some point and just didn't make it into a change log

**Comment by Josh-Cena** [comment]
Webpack v5 automatically has persistent cache; we don't need to implement it ourselves anymore.

**Comment by slorber** [comment]
> Webpack v5 automatically has persistent cache; we don't need to implement it ourselves anymore.

Not 100% automatic for Webpack, but enabled by default for Docusaurus

We have a config to declare that we want to use a cache in both dev/prod and client/server (4 cache items per locale)

```js
cache: {
  type: 'filesystem',
  name: `${name}-${mode}-${props.i18n.currentLocale}`,
}
```

So in theory you just need to preserve the .cache folder across builds to get faster rebuilds

I'd like to document this better, among other things related to deployment, perf and scalability
