### ISSUE TITLE
Proposal: add engines to package.json website/template

### ISSUE THREAD

**Issue by johnnyreilly** [facebook/docusaurus#7517]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [ ] I have tried the `npm run clear` or `yarn clear` command.
- [ ] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io.
- [ ] I have read the console error message carefully (if applicable).

### Description

Hey all,

Sorry, not a bug but so minor I couldn't call it a feature.

Upgrading to beta 21 introduced a minimum node.js version of 16. This broke my build which was using 14. I was able to resolve this by adding:

```json
  "engines": {
    "node": ">=16"
  }
```
To my `package.json` which I wrote about here:

https://blog.johnnyreilly.com/2022/05/28/azure-static-web-apps-node-16-oryx

And you can see the PR here: https://github.com/johnnyreilly/blog.johnnyreilly.com/pull/228

Would it be good to add this `engines` property to the create templates? This would fix the issue for folk using Oryx based builds and would give an explicit steer as to what node version Docusaurus requires to build.

https://github.com/facebook/docusaurus/blob/main/packages/create-docusaurus/templates/classic/package.json

### Steps to reproduce

Run a build with node 14 installed

### Expected behavior

See description

### Actual behavior

See description

### Your environment

- Public source code:
- Public site URL:
- Docusaurus version used:
- Environment name and version (e.g. Chrome 89, Node.js 16.4): node 14
- Operating system and version (e.g. Ubuntu 20.04.2 LTS):

### Self-service

- [X] I'd be willing to fix this bug myself.

**Comment by Josh-Cena** [comment]
I'm open to adding this. This is the last time we bump our Node version before the official release, so we shouldn't worry about users having outdated `engines` field in their package.json anymore.
