### ISSUE TITLE
Allow plugins to tweak existing HTML tags

### ISSUE THREAD

**Issue by alexandernst** [facebook/docusaurus#7540]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Motivation

Modifying the base HTML is currently nearly impossible. There is the `injectHtmlTags` plugin API that allows tags to be added, but it doesn't allow anything else, like removing tags, or tweaking the tags based on the current route.

If the `ssrTemplate` config option could be a function, the base HTML could be modified in any way.

Alternatively, the plugins API could be expanded with an additional function that would allow plugins to tweak all the data that is going to be passed to [renderSSRTemplate](https://github.com/facebook/docusaurus/blob/624735bd92a82724e4fc18239d42e160726af506/packages/docusaurus/src/client/serverEntry.tsx#L129).

### Self-service

- [ ] I'd be willing to do some initial work on this proposal myself.

**Comment by Josh-Cena** [comment]
I think we should allow `injectHtmlTags` to remove tags somehow. `ssrTemplate` is not a very good API—it does not even work in development / CSR.

Could you outline your use-case? What tags do you want to remove or tweak?

**Comment by alexandernst** [comment]
I have a use case where I'd like to render a legacy html (in a particular route) that has it's own styles / scripts, but Docusaurus's styles are colliding. I'd like to remove all styles that Docusaurus in injecting in the <head> (only for that route).

**Comment by Josh-Cena** [comment]
I see. Do you want navbar / footer etc. (i.e. the default layout)? Do you have a site that I can view the effect?

This could be related to #6032, #1059

We can't do this by changing HTML tags, because the Infima styles are bundled, not as a separate tag, so you have to change `htmlWebpackPlugin` etc.'s settings instead. Offering an API for this would not be easy.

**Comment by alexandernst** [comment]
Ideally, a Page component should be able to return either:

* just the body jsx / mdx - which would render it inside the "body"; aka the current behavior of docusaurus

or

* the raw HTML / jsx - which would just passthrough the entire chunk (skipping the entire Layout / Head / Footer / sidebars / etc...).

For the second option to work, the Page's props should contain the data that is currently passed to the ssrTemplate (so the Page can choose what data to use)

**Comment by alexandernst** [comment]
> What do you mean by "raw JSX / HTML"? The pages plugin simply returns a React component

Sorry, bad wording. I was trying to say that a Page should, somehow, be able to choose if it wants to be rendered inside the [MDXPage component](https://github.com/facebook/docusaurus/blob/main/packages/docusaurus-theme-classic/src/theme/MDXPage/index.tsx) or if it wants to provide it's own "component", which would effectively allow a Page to render the entire DOM (thus being able to remove / add whatever styles / scripts or any other tags it wants).

> You _can_ put an HTML file in the static folder and have it copied over to the build output. e.g. https://docusaurus.io/docs/advanced/routing#escaping-from-spa-redirects

This won't work for the index.html. Furthermore, linking to a static html file would mean going from "beautiful URLs" to a URL ending with ".html". Not ideal.

> But again, this would make it part of the SPA. There's a lot more infrastructure existing on top of the page you are rendering—you do not have full control over the current route with the pages plugin!

I understand, but maybe Pages should be able to have a little bit more control over the entire DOM. Obviously Docusaurus is an SPA, which means that the core system (routes handling, transitions, and so on) should still be loaded, but other than that , imho Pages should be able to tweak the content of the DOM (styles, metatags, etc...).

**Comment by Josh-Cena** [comment]
> if it wants to provide it's own "component", which would effectively allow a Page to render the entire DOM

The React page essentially renders its own component—it's already the highest freedom a plugin can have.

But plugins cannot break out of the SPA app. Here's `App.tsx`:

```tsx
  <ErrorBoundary>
      <DocusaurusContextProvider>
        <BrowserContextProvider>
          <Root>
            <SiteMetadataDefaults />
            <SiteMetadata />
            <BaseUrlIssueBanner />
            <PendingNavigation location={normalizeLocation(location)}>
              {routeElement}
            </PendingNavigation>
          </Root>
        </BrowserContextProvider>
      </DocusaurusContextProvider>
    </ErrorBoundary>
```

At most, plugins can control `routeElement`, but the layers above that are all controlled by the core.

Infima's styles are a whole different story. It's not even injected as an HTML tag. It's bundled as part of the site's CSS assets. There's no plugin API to tweak that.

> linking to a static html file would mean going from "beautiful URLs" to a URL ending with ".html". Not ideal.

The HTML files aren't even part of `routes.js` (which registers the routes of the Docusaurus SPA), so how you link to them is entirely up to you. THey are served just like the rest of the HTML files, so if your server is happy with requesting a URL without .html (which they should—otherwise the rest of the Docusaurus site won't work at all!), these pages would always work.

**Comment by alexandernst** [comment]
🤔 Decided to step back for a few hours and rethink what am I asking exactly. Turns out I'm asking the wrong question (thus I'm not getting the answer I want).

The original case scenario was me trying to render a raw html piece of code, but failing to do it because of colliding styles. I think that the correct solution here would be to remove global css pollution, which is already https://github.com/facebook/docusaurus/issues/6032 so ¿I guess this issue should be closed?

**Comment by Josh-Cena** [comment]
Ah, if you think it can be deemed as a duplicate, I'm okay to close.

I don't think removing Infima's global style pollution is the only way to fix this though:

They are saying, if you have a React page

```ts
export default function Home() {
  return (
    <Layout>
      <code>Hey</code>
    </Layout>
  );
}
```

That `<code>` tag should _not_ be automatically styled, unless you explicitly opt-into the style somehow; for you, it seems more niche, and you'll probably be fine with jumping hoops to opt-out of Infima. So they are proposing you should jump hoops to get _into_ Infima styling, while you just want to get _out_.

But at any rate, this is not a very easy problem to solve😅 We'll probably just fix the two with the same mechanism.
