### ISSUE TITLE
CSS minification changes z-index

### ISSUE THREAD

**Issue by moklick** [facebook/docusaurus#7548]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Description

Hey Docusaurus Team,

thanks for your amazing work :)

    

We realized recently that docusaurus cleans up z-indices in our custom css that we are loading via `customCss: require.resolve('./src/css/custom.css')`. My question is: **How can I disable the z-index modification?** This might be a good feature but can lead to bugs when you are using other third party that bring their own css. We are using `'@docusaurus/preset-classic'`.

### Self-service

- [ ] I'd be willing to address this documentation request myself.

**Comment by Josh-Cena** [comment]
Please give a repro. Any minification that leads to the CSS semantics changing is a bug.

**Comment by moklick** [comment]
Hey @Josh-Cena 

thanks for the fast reply. 

We are setting the `z-index = 100` for the [navbar](https://github.com/wbkd/react-flow-docs/blob/main/src/css/custom.css#L107-L109). After building our site, it has a [`z-index` of 5](https://reactflow.dev/).

**Comment by Josh-Cena** [comment]
Thanks, we'll investigate. This shouldn't happen—probably it was aggressively merged...

Mind adding an `!important` and see if it helps?

**Comment by moklick** [comment]
I tried that. `!important` doesn't help here.

**Comment by Josh-Cena** [comment]
Mmmm, that's weird.

**Comment by moklick** [comment]
We are now using `USE_SIMPLE_CSS_MINIFIER=true npm run build` as a workaround.

**Comment by Josh-Cena** [comment]
OK, if `USE_SIMPLE_CSS_MINIFIER` fixes it, then it's definitely a minification bug.

**Comment by moklick** [comment]
https://docusaurus.io/docs/next/cli#options-1: "For advanced minification of CSS bundle, we use the [advanced cssnano preset](https://github.com/cssnano/cssnano/tree/master/packages/cssnano-preset-advanced)". The advanced cssnano preset uses the [z-index plugin](https://github.com/cssnano/cssnano/blob/master/packages/cssnano-preset-advanced/src/index.js#L6).

**Comment by Josh-Cena** [comment]
Ah, I see. I think we should find a way to configure it, then.

**Comment by dpang314** [comment]
I'd like to work on this. Just to confirm, are we disabling the zindex minifier by default?

It could be useful to make all the cssnano advanced preset options toggleable, as they could all be problematic in certain situations. I was thinking to add this option in the config. Should I go ahead with this too?

**Comment by Josh-Cena** [comment]
Let's make it disabled by default, for now 🤔 I prefer to remain opinionated on minification settings.

**Comment by dpang314** [comment]
Got it!

**Comment by sekoyo** [comment]
The minimizer is brutal, it is taking the CSS imported from a node_module and deciding a bunch of it is invalid and removing it (but it is valid CSS). I get lots of `Unexpected '}'` and even `Invalid selector '}@media (hover:hover)'` which is a valid selector. I noticed `css-minimizer-webpack-plugin` is a couple of major versions behind, perhaps updating could help

**Comment by slorber** [comment]
@sekoyo thanks for your feedback.

It would be better to create new proposals, or your comment will likely be lost/ignored over time because. It's not really related to z-index and this issue is closed for a while already.

css minimizer v6.0 was released yesterday but requires node 18.12 so it's not an option for Docusaurus v3 which supports v18.0 (but we can upgrade for v4).

can you give a try and see it css minimizer v5.x improves the situation for you?
