### ISSUE TITLE
Can't toggle between Versioning options in mobile and tablet view

### ISSUE THREAD

**Issue by bhuvanaks** [facebook/docusaurus#7553]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

The versioning option dropdown is present in the top navbar of the website. The view of this navbar changes in tablet and mobile view making it disappear and not giving the user option to shift between versions anymore

### Reproducible demo

https://docusaurus.io/docs/versioning

### Steps to reproduce

Any docusaurus site with versioning enabled

### Expected behavior

The dropdown should still appear for changing version in mobile/tablet view. This also applies for translation dropdown

### Actual behavior

<img width="1638" alt="Screen Shot 2022-06-02 at 4 37 53 PM" src="https://user-images.githubusercontent.com/95324778/171758331-96ee7f8d-68e2-46c9-aee5-e877c92e70de.png">
<img width="1668" alt="Screen Shot 2022-06-02 at 4 27 23 PM" src="https://user-images.githubusercontent.com/95324778/171758337-b91d8db1-bca5-441c-9d60-de19409d246d.png">
<img width="1673" alt="Screen Shot 2022-06-02 at 4 26 55 PM" src="https://user-images.githubusercontent.com/95324778/171758345-60f8018f-ba0e-4914-912f-d3e399146a61.png">

### Your environment

- Public source code: https://github.com/facebook/docusaurus
- Public site URL: https://docusaurus.io/docs/versioning
- Docusaurus version used: 2.0.0-beta.21
- Environment name and version (e.g. Chrome 89, Node.js 16.4): Any browser, Node v16.14.2
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): Any

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by Josh-Cena** [comment]
Hi! The versions dropdown is in the sidebar menu.

<img width="431" alt="image" src="https://user-images.githubusercontent.com/55398995/171772367-bf97fc1b-3269-4ea5-9fac-ec67027bb399.png">
