### ISSUE TITLE
Blog only mode doesn't work anymore - Error: Docusaurus plugin global data not found for "docusaurus-plugin-content-docs" plugin with id "default".

### ISSUE THREAD

**Issue by aamir1995** [facebook/docusaurus#7575]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [ ] I have tried the `npm run clear` or `yarn clear` command.
- [ ] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

Blog only mode which can be configured by setting `docs: false` in the config file causes an error:
![image](https://user-images.githubusercontent.com/10736453/172180496-6f010a23-ed9d-4236-8d7e-86c736c94ff1.png)

### Reproducible demo

https://stackblitz.com/edit/github-1v7i77?file=docusaurus.config.js

### Steps to reproduce

Create a new project
Set the `docs: false` in docusaurus.config.js
Start the server using `npm start`

### Expected behavior

Blog only mode should work as documented here: https://docusaurus.io/docs/blog#blog-only-mode

### Actual behavior

Issue already described in description

### Your environment

- Public source code: https://stackblitz.com/edit/github-1v7i77?file=docusaurus.config.js
- Public site URL: https://stackblitz.com/edit/github-1v7i77?file=docusaurus.config.js
- Docusaurus version used: beta.20 and beta.21
- Environment name and version (e.g. Chrome 89, Node.js 16.4):
- Operating system and version (e.g. Ubuntu 20.04.2 LTS):

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by Josh-Cena** [comment]
You need to remove
```js
{
            type: 'doc',
            docId: 'intro',
            position: 'left',
            label: 'Tutorial',
          },
```

**Comment by aamir1995** [comment]
ah, yes. not sure how I missed this but maybe worth adding to the docs? 
Thanks for the quick reply :100:

**Comment by slorber** [comment]
We should definitively improve NavbarItem related error messages, they are too generic in such case
