### ISSUE TITLE
Docusaurus website missing import

### ISSUE THREAD

**Issue by dpang314** [facebook/docusaurus#7589]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

When running `yarn build` on the Docusaurus website, `Component APITable was not imported, exported, or provided by MDXProvider as global scope` is printed twice to the console. The import for APITable is missing in both versions of the no-untranslated-text.md files.

### Steps to reproduce

1. Run `yarn build` in the [docusaurus repository](https://github.com/facebook/docusaurus)

### Expected behavior

I did not expect `Component APITable was not imported, exported, or provided by MDXProvider as global scope` to be printed.

### Actual behavior

`Component APITable was not imported, exported, or provided by MDXProvider as global scope` is printed to the console twice.

### Your environment

- Public source code: https://github.com/facebook/docusaurus
- Public site URL: https://docusaurus.io/
- Docusaurus version used: version in the GitHub repository as of [this commit](https://github.com/facebook/docusaurus/tree/79db7bcdcbfd39156fbc46b3e3875e156a665e1f)
- Environment name and version (e.g. Chrome 89, Node.js 16.4): Node.js 16.15
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): Ubuntu 20.04 LTS

### Self-service

- [X] I'd be willing to fix this bug myself.

**Comment by Josh-Cena** [comment]
Thanks, the errors are in `versioned_docs`, the two `api/misc/eslint-plugin/no-untranslated-text.md` files. If you want to fix that by adding the missing imports it would be great. I didn't fix it because it would automatically be fixed after bumping another two versions, and we seldom edit versioned files unless absolutely needed.
