### ISSUE TITLE
Explicit IDs for markdown headings fail to parse dots

### ISSUE THREAD

**Issue by FHannes** [facebook/docusaurus#7603]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

The documentation describes the ability to choose a specific id for a markdown heading: https://docusaurus.io/docs/markdown-features/toc#heading-ids

This works in some cases, but the parser fails when dots are included in the id, which is a valid character for ids in html pages. The id definition will just be considered to be part of the heading.

Example image:
![image](https://user-images.githubusercontent.com/915760/173186277-f7d57482-ec72-4ef5-9b76-f2173ff96d5a.png)

### Reproducible demo

https://codesandbox.io/s/docusaurus-explicit-id-bug-ffjjmv?file=/docs/intro.md

### Steps to reproduce

Define a markdown heading with an explicit id that contains dots. Eg:

### Expected behavior

I would expect a heading to be added with the text "Changes 2022.6.0" and the id "2022.6.0".

### Actual behavior

A heading is added with text "Changes 2022.6.0 {#2022.6.0}" and the id "changes-202260-202260".

### Your environment

- Docusaurus version used: 2.0.0-beta.21

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by Josh-Cena** [comment]
We seem to intentionally have a very restricted pattern. I don't know if this is working as intended or if we can safely extend the regex—I will need examples of how other Markdown parsers behave in this case. Heading IDs is a very common syntax.

**Comment by Josh-Cena** [comment]
These two both parse the custom ID correctly:

```js
const md = require("markdown-it")()
  .use(require("markdown-it-attrs"))
  .use(require("markdown-it-anchor"))
  .render("## a {#2022.1.1}");

console.log(md);

const md2 = require("remark")()
  .use(require("remark-heading-id"))
  .use(require("remark-rehype"))
  .use(require("rehype-stringify"))
  .processSync("## a {#2022.1.1}");

console.log(md2.toString());
```

I think it's fair for us to keep the behavior in line.
