### ISSUE TITLE
Support Roam-like Linking for Docs Folder

### ISSUE THREAD

**Issue by anaclumos** [facebook/docusaurus#7618]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Motivation

[Roam](https://roamresearch.com/), [Obsidian](https://obsidian.md/), [Logseq](https://logseq.com/), and [Foam](https://foambubble.github.io/foam/), provides a new paradigm of managing knowledge on a vast scale. These process accelerates interlinking knowledges and documentation to create a more complete picture of the product.

For example,

- Supporting Linkings with `[[Title]]`.
- Supporting Daily Research Notes.
- Providing Graph-view for how notes interconnect

### Self-service

- [ ] I'd be willing to do some initial work on this proposal myself.

**Comment by Josh-Cena** [comment]
Hi! Sorry, you seem to have used the wrong template. As stated in the template:

> Common reasons for proposals include:
>
> - Altering the infrastructure (e.g. swapping Webpack out with other bundlers);
> - Bumping a critical dependency's major version;
> - A significant improvement to a CLI command;
> - Significant refactor;
> - ...
>
> This is not for feature requests. If this involves new APIs or new behaviors, consider requesting the feature on https://docusaurus.io/feature-requests instead.

I think it's very clear that this is not a proposal but rather a feature request, and using the wrong template means you failed to provide all the details we need for a feature request, including API design, motivation, potential implementation ideas, etc. This makes it much harder for us to measure the ROI of implementing this.

For example,

> Supporting Daily Research Notes.

Assuming zero knowledge of these tools, we would not be able to know what exactly we need to implement to support this. Do we need new file types? Do we need new front matter? Do we need to change our doc metadata? Do we need to design new React components?

To see how many people are interested in one particular idea and make sure our effort can satisfy the greatest proportion of our audience, we require feature requests like this to be filed on Canny first, where people can vote and comment and we can sort by upvotes. In fact, we already have related requests on Canny, e.g.

- https://docusaurus.canny.io/feature-requests/p/backlinks-or-pages-that-link-here
- https://docusaurus.canny.io/feature-requests/p/page-reference-with-markdown-paths
- https://docusaurus.io/feature-requests/p/information-architecture-diagram-ia

Therefore, I'm going to close this as wontfix. This does not mean your feature request is rejected and we won't ever implement it—it's only a required part of the issue triaging system and keeping the open issues maximally approachable by the team. Thanks for taking interest in this!

**Comment by anaclumos** [comment]
Thank you for the detailed comment!
