### ISSUE TITLE
[QUESTION]: How to create Cards?

### ISSUE THREAD

**Issue by RudraSen2** [facebook/docusaurus#7636]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Description

This is just a question. I saw your Playground Component Cards on your [site](https://docusaurus.io/docs/playground). I also want the same on my docusaurus site but giving me errors like "Module not found: '@theme/IdealImage'". When I delete all Playground Cards Code, it starts working again. Can anyone tell me how to implement those cards on my site? I am a student and currently learning code. Any help appreciated.

### Self-service

- [ ] I'd be willing to address this documentation request myself.

**Comment by Josh-Cena** [comment]
`IdealImage` is provided by the [`ideal-image`](https://docusaurus.io/docs/api/plugins/@docusaurus/plugin-ideal-image) plugin. If you are not using this plugin just replace it with a normal `<img>` tag.

Please don't use the GH issue tracker for questions.
