### ISSUE TITLE
Impossible to center Markdown table

### ISSUE THREAD

**Issue by adam8451** [facebook/docusaurus#7640]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [ ] I have tried the `npm run clear` or `yarn clear` command.
- [ ] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io.
- [ ] I have read the console error message carefully (if applicable).

### Description

The absence of easy ability to center Markdown tables is a well-known problem. Some platforms disable certain HTML/CSS changes, which may understandably make centering practically impossible.

However, there should intuitively be a way to get around it on Docusaurus since the developer has full control of the environment.

### Reproducible demo

https://github.com/adam8451/docusaurus/commit/0582e7217903fb1b5e761b0561840f357358f956

### Steps to reproduce

1. Set up a basic Docusaurus website with https://docusaurus.io/docs#fast-track.
2. Create a Markdown table.
3. Attempt to center it with any workaround found on the web, e.g. https://granneman.com/webdev/coding/css/centertables

### Expected behavior

The table is centered.

### Actual behavior

The table stays left-aligned.

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by Josh-Cena** [comment]
Hi! Infima added `display: block` to all tables, so the table already takes full width of the page container. You need to add `display: table` for this to work.

This looks like a question, so I'm going to close it as such. It takes minimal effort to use inspect element to debug CSS.

**Comment by adam8451** [comment]
Works like a charm. Thanks, Josh!
