### ISSUE TITLE
KaTeX equations are not converted when within <table> tags

### ISSUE THREAD

**Issue by adam8451** [facebook/docusaurus#7641]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [ ] I have tried the `npm run clear` or `yarn clear` command.
- [ ] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io.
- [ ] I have read the console error message carefully (if applicable).

### Description

Some table functionalities are not available when written in vanilla Markdown. As a result, one might be enticed to manually build them within a `<table>` tag. However, doing so breaks the display of KaTeX formulas.

### Reproducible demo

https://github.com/adam8451/docusaurus/commit/ebd57a8b0d9acc65e643a838526d3c108a8f52b4

### Steps to reproduce

1. Set up a basic Docusaurus website with https://docusaurus.io/docs#fast-track.
2. Manually create a table with the `<table>` tag.
3. Write an equation, say `$a+b=c$`

### Expected behavior

KaTeX renders the equation into: $a+b=c$

### Actual behavior

Rendering does not happen, and the user sees the raw form: `$a+b=c$`

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by Josh-Cena** [comment]
Please see https://docusaurus.io/docs/markdown-features/react#markdown-and-jsx-interoperability

**Comment by adam8451** [comment]
Thanks @Josh-Cena for the pointer. Leaving spaces within the `<td>` tag as hinted by the ["Text immediately below a JSX tag will be seen as JSX text" workaround](https://docusaurus.io/docs/markdown-features/react#markdown-and-jsx-interoperability) breaks the generation of the table.

Does that mean that this functionality is not supported?

**Comment by Josh-Cena** [comment]
Then no. You would need to write the equation somewhere else, inspect element, copy the generated HTML in browser, and paste that span soup into your table.
