### ISSUE TITLE
deploy on github pages

### ISSUE THREAD

**Issue by kazumasamatsumoto** [facebook/docusaurus#7662]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

私は今日初めてdocusaurusをインストールしてデプロイをチャレンジしてみました。
が結果はこのURLのようになりました。

I tried to install and deploy docusaurus for the first time today.
The result is as shown in this URL.

https://kazumasamatsumoto.github.io/docusaurus-test3/

原因がわからず、CSSが有効になっていない理由はなぜでしょうか？

Can't figure out the cause and why CSS is not enabled?

### Reproducible demo

https://github.com/kazumasamatsumoto/docusaurus-test3

### Steps to reproduce

1. npx create-docusaurus@latest my-website classic
2. cd my-website
3. npm run start
4. Check operation in local environment
5. docusaurus.config.js add
https://github.com/kazumasamatsumoto/docusaurus-test3/blob/main/docusaurus.config.js#L19-L20
6. USE_SSH=true npm run deploy
7. check page
https://kazumasamatsumoto.github.io/docusaurus-test3/

### Expected behavior

I wanted it to look the same as it behaves locally.

### Actual behavior

![スクリーンショット 2022-06-23 12 12 36](https://user-images.githubusercontent.com/29771037/175199388-17aff5de-3a3f-4b7a-b393-ea234031f22a.png)
![スクリーンショット 2022-06-23 12 12 44](https://user-images.githubusercontent.com/29771037/175199402-41fceee8-9d3a-4b81-b3fd-0c9e6887a496.png)
![スクリーンショット 2022-06-23 12 12 53](https://user-images.githubusercontent.com/29771037/175199409-0ec16064-5066-44e5-81f3-a686a1a5a6bd.png)
![スクリーンショット 2022-06-23 12 13 02](https://user-images.githubusercontent.com/29771037/175199413-5bc2482e-68a8-4a88-b130-85f8335d37f7.png)

https://kazumasamatsumoto.github.io/docusaurus-test3/

If you look here, you will understand what I am trying to assert.

### Your environment

- Public source code:https://github.com/kazumasamatsumoto/docusaurus-test3
- Public site URL:https://kazumasamatsumoto.github.io/docusaurus-test3/
- Docusaurus version used:
```
"dependencies": {
    "@docusaurus/core": "2.0.0-beta.21",
    "@docusaurus/preset-classic": "2.0.0-beta.21",
    "@mdx-js/react": "^1.6.22",
    "clsx": "^1.1.1",
    "prism-react-renderer": "^1.3.3",
    "react": "^17.0.2",
    "react-dom": "^17.0.2"
  },
```
- Environment name and version 
```
Chrome: 102.0.5005.115（Official Build） （arm64）
my-website$ node -v
v16.15.1
```
- Operating system and version (e.g. Ubuntu 20.04.2 LTS):
```
MacOS version:12.3.1
```

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by Josh-Cena** [comment]
The error message is very clear:

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/55398995/175200237-f9bad859-191d-4c39-aeea-ac3bcdc8d870.png">

You need to change this: https://github.com/kazumasamatsumoto/docusaurus-test3/blob/618f65c78a063366209ee2fa13584311a6faee06/docusaurus.config.js#L12 to `baseUrl: "/docusaurus-test3/"`.

Please don't use the issue tracker as a support forum.

**Comment by kazumasamatsumoto** [comment]
Sorry about that.
I thought it was a bug and submitted an issue, but I guess I was wrong. My apologies.
Is there a support forum here? I was looking at the official page, but I couldn't find anything like that, so I submitted an issue.
I would appreciate it if you could let me know.

**Comment by Josh-Cena** [comment]
When you submit the issue, it's already stated in the form:

> **The GitHub issue tracker is not a support forum**. If you are not sure whether it could be your mistakes, ask in the [Discord server](https://discord.gg/docusaurus) or [GitHub discussions](https://github.com/facebook/docusaurus/discussions) first. The quickest way to verify whether it's a Docusaurus defect is through a **reproduction**, starting with a fresh installation and making changes until the bug is reproduced.
