### ISSUE TITLE
broken links on build

### ISSUE THREAD

**Issue by Arhell** [facebook/docusaurus#7679]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

When checking `yarn start` locally, everything works, I checked the links.
`yarn build` throws errors

Provided that `docusaurus.config.js` has `onBrokenLinks: 'throw'`
If you remove this value, then everything is fine, but the condition that this value would be.

### Reproducible demo

https://github.com/kubevela/kubevela.io/pull/771

### Steps to reproduce

update https://github.com/kubevela/kubevela.io/pull/771/files
https://github.com/kubevela/kubevela.io/runs/7039961689?check_suite_focus=true

### Expected behavior

There should be no errors if the links are not broken

### Actual behavior

https://github.com/kubevela/kubevela.io/runs/7039961689?check_suite_focus=true

### Your environment

- Public source code: https://github.com/kubevela/kubevela.io
- Public site URL:https://kubevela.io/
- Docusaurus version used: 2.0.0-alpha.75
- Environment name and version (e.g. Chrome 89, Node.js 16.4): 102 16+ node
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): Ubuntu

**Comment by Josh-Cena** [comment]
Hi! It's because in the latest version, we will not output slugs with duplicate last segment by default. See https://github.com/facebook/docusaurus/pull/5830. You can fix this by adding explicit slugs to those docs.
