### ISSUE TITLE
Support themes

### ISSUE THREAD

**Issue by ericnakagawa** [facebook/Docusaurus#77]

**Comment by neilsutcliffe** [comment]
I'm thinking this is a pretty good feature, however I would like to see this as part of a move to sass or less.

The current style sheet could be simplified a bit. 

The current method uses $variables to define custom colours, which is not really valid CSS. However I'm not sure if adding Sass is really something that Docusaurus needed. The current CSS solution whilst not technically correct is very lightweight.

But being able to overwrite base variables and extend the CSS with a file in the website folder (or choose in the config a set of preset styles) would be nice. 

Thoughts?

**Comment by neilsutcliffe** [comment]
https://github.com/Munter/express-compile-sass

Does this npm plugin seem acceptable. It would easy to drop in, although I'm not sure yet how to tie in the primary and secondary colours with it?
