### ISSUE TITLE
When the file name is the same as the parent folder name, the generated url is missing the file name.

### ISSUE THREAD

**Issue by Selflocking** [facebook/docusaurus#7725]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

Reproducible demo: https://codesandbox.io/s/busy-lake-7grh3p?file=/sidebars.js

For example a file like this
```
docs/
├── storage/
│   ├── storage.md
│   └── ...
```
The expectation is to access it via /docs/storage/storage
But in fact docusaurus generates  /docs/storage
![image](https://user-images.githubusercontent.com/53544726/177360087-c69f7ad8-cf08-4813-a935-19d0c370bd9f.png)

### Reproducible demo

https://codesandbox.io/s/busy-lake-7grh3p?file=/sidebars.js

### Steps to reproduce

When the file name is the same as the parent folder name, like:
```
docs/
├── storage/
│   ├── storage.md
│   └── ...
```

### Expected behavior

via /docs/storage/storage

### Actual behavior

/docs/storage

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by Josh-Cena** [comment]
Hi, this is a feature. See https://docusaurus.io/docs/next/sidebar/autogenerated#category-index-convention
