### ISSUE TITLE
custom template ?

### ISSUE THREAD

**Issue by lili21** [facebook/Docusaurus#773]
It's annoying that I have to do the samething every time after `docusaurus-init` - change the directory name, change the config.

**Comment by JoelMarcey** [comment]
I am sorry that you are annoyed. That is never our intention. 

We believe `docusaurus-init` is a good way to easily get started with one website. Run one script, change a couple of directories and you can see a site live and running. 

For multiple websites, maybe use the configuration you modified for the first website as the starting point for those.

As there is nothing actionable on this issue, I will close it.

If you have suggestions for improvement to either `docusaurus-init` or Docusaurus itself, please file an issue and we can label legitimate requests as `feature-requests` for future versions. 

Thank you.
