### ISSUE TITLE
react-live swizzle assumes "eject" option was selected

### ISSUE THREAD

**Issue by SheetJSDev** [facebook/docusaurus#7735]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Description

https://docusaurus.io/docs/markdown-features/code-blocks#imports

> If you need more imports available, swizzle the react-live scope:

The current command snippet is

```bash
# npm
npm run swizzle @docusaurus/theme-live-codeblock ReactLiveScope
# yarn
yarn run swizzle @docusaurus/theme-live-codeblock ReactLiveScope
```

On first run:

```
? Which swizzle action do you want to do? › - Use arrow-keys. Return to submit.
❯   Wrap (Unsafe)
    Eject (Unsafe)
    [Exit]
```

Comparing the generated code to the code snippet that follows, the docs assume that the user chooses to "Eject" rather than "Wrap".

To avoid confusion, the command snippets should include the flag to eject by default:

```
# use eject but keep unsafe warning
npm run swizzle @docusaurus/theme-live-codeblock ReactLiveScope -- --eject
```

Note: The unsafe warning can be suppressed with

```
# use eject and suppress 
npm run swizzle @docusaurus/theme-live-codeblock ReactLiveScope -- --eject --danger
```

but it may make more sense to add a warning.

### Self-service

- [X] I'd be willing to address this documentation request myself.

**Comment by Josh-Cena** [comment]
Yes, this doc was written before we had `--wrap`. Feel free to send a PR!
