### ISSUE TITLE
All links including menu, navbar, dropdown show underline on hover

### ISSUE THREAD

**Issue by pranabdas** [facebook/docusaurus#7748]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

In the new beta 2.0.0-beta.22, all links including buttons, sidebar menu, navbar, navbar dropdown menu are showing text underlined on hover. I guess this not intended.

### Steps to reproduce

You can check on the <https://docusaurus.io>

### Expected behavior

`text-decoration: underline` on link hover is not desired for every link.

### Actual behavior

<img width="325" alt="Screenshot 2022-07-09 at 9 30 50 AM" src="https://user-images.githubusercontent.com/31024886/178086631-e847a1e3-8640-4fd1-ab55-84298d1cfe64.png">

<img width="288" alt="Screenshot 2022-07-09 at 9 26 51 AM" src="https://user-images.githubusercontent.com/31024886/178086616-c2fdd7a2-0900-4b72-adc2-0482d5364cce.png">

<img width="234" alt="Screenshot 2022-07-09 at 9 26 21 AM" src="https://user-images.githubusercontent.com/31024886/178086646-6617d300-b2a9-4cf2-8f65-10cc239133ec.png">

### Your environment

- Public source code:
- Public site URL:
- Docusaurus version used:
- Environment name and version (e.g. Chrome 89, Node.js 16.4):
- Operating system and version (e.g. Ubuntu 20.04.2 LTS):

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by srmagura** [comment]
https://github.com/facebookincubator/infima/pull/267
