### ISSUE TITLE
postStart plugin lifecycle

### ISSUE THREAD

**Issue by gabrielcsapo** [facebook/docusaurus#7749]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Description

Implement postStart which is called when the dev server has finished starting. This is similar to postBuild but the dev server version.

### Motivation

Discussion is ongoing on what the functionality would be https://github.com/facebook/docusaurus/discussions/5616. Here is an implementation at postCompile https://github.com/facebook/docusaurus/pull/7737#issuecomment-1179482628.

https://docusaurus.io/docs/next/api/plugin-methods outlines that postStart is TBD.

<img width="771" alt="Screen Shot 2022-07-08 at 10 30 15 PM" src="https://user-images.githubusercontent.com/1854811/178093009-7528dcd6-209d-45cd-a01d-b59be2a82a2d.png">

### Self-service

- [X] I'd be willing to contribute this feature to Docusaurus myself.

**Comment by gabrielcsapo** [comment]
This seems like the best place to implement it, given that this is utilized by openBrowser which is called once. 

https://github.com/facebook/docusaurus/blob/main/packages/docusaurus/src/commands/start.ts#L238-L243

**Comment by gabrielcsapo** [comment]
I tried to implement the postStart hook as you suggested @Josh-Cena in https://github.com/facebook/docusaurus/pull/7751. Let me know if I can do anything else to help out. Really appreciate all the work you all do!

**Comment by slorber** [comment]
Closing issue related to closed PR: https://github.com/facebook/docusaurus/pull/7751

If someone come up with a strong use case for postStart we can revisit
