### ISSUE TITLE
export useBlogPost for swizzling

### ISSUE THREAD

**Issue by anaclumos** [facebook/docusaurus#7759]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Motivation

Hi, I have confirmed that `theme-common/src/contexts/blogPost` has a React Hook called `useBlogPost()` used for fetching various data for blog page. I would like to access this data for swizzling purposes. Can you make this function exported on the next upcoming release?

### Self-service

- [X] I'd be willing to do some initial work on this proposal myself.

**Comment by Josh-Cena** [comment]
All `theme-common` APIs are exported to be useful at all. This hook is exported:

https://github.com/facebook/docusaurus/blob/cd7da6113e0effb0caca034c94177cb2d0379fb4/packages/docusaurus-theme-classic/src/theme/BlogPostItem/index.tsx#L10

We made a new `/internal` subpath export. We will be documenting this soon.

**Comment by lachieh** [comment]
If anyone comes across this issue because you get an error like `Module '"@docusaurus/theme-common/internal"' has no exported member...`, then you'll want to make some quick changes. As of docusaurus@3.5, the blog and the docs internals have been moved to their respective plugins and be accessed from:

```ts
import { ... } from '@docusaurus/plugin-content-blog/client';
import { ... } from '@docusaurus/plugin-content-docs/client';
```
