### ISSUE TITLE
onBrokenMarkdownLinks errors for invalid links inside tilde codeblocks only

### ISSUE THREAD

**Issue by antonk52** [facebook/docusaurus#7800]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [ ] I have tried the `npm run clear` or `yarn clear` command.
- [ ] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io.
- [ ] I have read the console error message carefully (if applicable).

### Description

Docusaurus checks for broken links inside tilde code blocks when `onBrokenMarkdownLinks` is set to `throw`

### Steps to reproduce

1. create a new docusaurus site using `create-docusaurus`
2. make sure that docusaurus.config.js contains
    ```
    onBrokenLinks: 'throw',
    onBrokenMarkdownLinks: 'throw',
    ```
3. Add following content to `docs/intro.md`
    ````
    ```
    this is an [invalid link](./path/to/a/page/that/does/not/exist.md)
    ```
    ````
4. run `npx docusaurus build` to see the site build as expected
5. change the codeblock from step 3 to use ~ instead of \` ie
    ```
    ~~~
    this is an [invalid link](./path/to/a/page/that/does/not/exist.md)
    ~~~
    ```
7. run `npx docusaurus build` to see the build fail with an error
    ```
    Error: Docs markdown link couldn't be resolved: (./path/to/a/page/that/does/not/exist.md) in 
    "/Users/foo/bar/baz/docusaurus/packages/testsite/docs/intro.md" for version current
        at Array.forEach (<anonymous>)
    ```

### Expected behavior

Docusaurus either does not check links inside codeblock or checks them for both backtick and tilde codeblocks when `onBrokenMarkdownLinks` is set to `throw`

### Actual behavior

Docusaurus errors for broken markdown links only inside tilde codeblocks when `onBrokenMarkdownLinks` is set to `throw`

### Your environment

- Public source code: NA
- Public site URL: NA
- Docusaurus version used: Can reproduce with 2.0.0-beta.21 and 2.0.0-rc.1
- Environment name and version (e.g. Chrome 89, Node.js 16.4): Node.js 16.4
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): Macos

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by Josh-Cena** [comment]
Yep—we don't handle `~~~`. I'm surprised anyone actually uses them by default.

**Comment by antonk52** [comment]
If I remove the broken link from the tilde codeblock than the codeblock is rendered as you would expect. This makes me think that this is not an issue with mdxjs.

**Comment by Josh-Cena** [comment]
It's not—it's our own infra :) The fact that MDX accepts `~~~` means we should as well.

**Comment by yangdanny97** [comment]
> Yep—we don't handle `~~~`. I'm surprised anyone actually uses them by default.

It's useful in a weird edge case, making a code block of markdown source code that contains a code block delimited by triple backtick.

something like 

~~~
```
blah blah blah
```
~~~

**Comment by Josh-Cena** [comment]
In that case I would personally use four backticks...
