### ISSUE TITLE
Broken links to the documentation in NPM description

### ISSUE THREAD

**Issue by vinogradov** [facebook/Docusaurus#781]
https://www.npmjs.com/package/docusaurus-init

![image](https://user-images.githubusercontent.com/439939/41488103-399aba24-70fc-11e8-86ad-ec0c38341d45.png)

**Comment by JoelMarcey** [comment]
Thank you @vinogradov - it is correct in the [actual README](https://github.com/facebook/Docusaurus/blob/master/docusaurus-init/README.md) for `docusaurus-init`. Not sure why it didn't make it to npm. We will have to publish a new version of docusaurus-init to get the update to happen I think.

**Comment by yangshun** [comment]
@JoelMarcey I can help to publish but I'm not sure if I have permissions to publish this package.
