### ISSUE TITLE
Dark Mode 

### ISSUE THREAD

**Issue by franklinscripts** [facebook/docusaurus#7817]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Description

Try to improve on the dark mode as it helps those who don't like light versions because of eye issues

### Has this been requested on Canny?

Dont think soo!

### Motivation

FYI 
Try to improve on the dark mode as it helps those who don't like light versions because of eye issues

### Self-service

- [ ] I'd be willing to contribute this feature to Docusaurus myself.

**Comment by Josh-Cena** [comment]
Closing because this doesn't seem actionable. If you have concrete suggestions please open feature requests on Canny first, along with UI mockups and/or userland solution demos.
