### ISSUE TITLE
Category auto-generated index page should support custom category/link descriptions

### ISSUE THREAD

**Issue by Dr-Electron** [facebook/docusaurus#7818]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Description

If you use index pages and your sidebar contains a link it would be nice if you could either:  
- Add a description to the link by doing something like: 
{
    type: 'link',
    label: 'Facebook', // The link label       
    href: 'https://facebook.com', // The external URL       
    description: 'Some description'
},  

or  

- Fetch the data from the linked page if possible. This may be very specific to our use case but we link from one docs plugin to another in our Wiki as we can't always use relative links. So it would be nice if the index page could somehow get the frontmatter from the linked page.  

Wdyt?

### Has this been requested on Canny?

No. I can't login there because of some unknown error

### Motivation

We would like to work more with index pages but we use a lot of links in the sidebar and that just don't really look nice.

### Have you tried building it?

I didn't try to build it myself. Not sure what the best way would be yet. So maybe let's discuss first what would be possible.

### Self-service

- [ ] I'd be willing to contribute this feature to Docusaurus myself.

**Comment by slorber** [comment]
What I understand is that you want this to display in a better way

![CleanShot 2022-07-25 at 11 56 13](https://user-images.githubusercontent.com/749374/180750657-2c7c9ccb-0432-45b4-bae1-7bf1c66938c6.png)

That seems reasonable to add a sidebar link attribute to provide a link description


> Fetch the data from the linked page if possible. This may be very specific to our use case but we link from one docs plugin to another in our Wiki as we can't always use relative links. So it would be nice if the index page could somehow get the frontmatter from the linked page.


I doubt we'll want to implement this. Instead we should allow you to use top-level async/await in `sidebars.js`.

```js
        {
          type: 'link',
          href: 'https://facebook.com',
          label: await fetchLabel(),
        },
```

Unfortunately, this is blocked by https://github.com/sindresorhus/import-fresh/issues/22

**Comment by heysujal** [comment]
@slorber Hi, I want to work on this issue , but I am new to this project. 
Can you guide how can I go about implementing this ?

**Comment by slorber** [comment]
Hey @heysujal, this is a very simple issue but it requires being used to Docusaurus in the first place to understand what should be done. If it's not the case, I'd recommend becoming first familiar with Docusaurus and only then trying to contribute. We have an active discord channel in case you are looking for help.

**Comment by YashasviChaurasia** [comment]
@slorber I would like to work on this issue.
Thank you

**Comment by slorber** [comment]
go ahead then

**Comment by slorber** [comment]
Similarly, we want to support custom category descriptions

![CleanShot 2022-08-24 at 17 01 18@2x](https://user-images.githubusercontent.com/749374/186453176-9eb1b8b0-dce9-4e8e-858f-e11780b59e1c.png)

See https://github.com/facebook/docusaurus/discussions/7985

**Comment by alliyya** [comment]
Would be nice to also support custom icons too, or add that as an option in the front matter of docs in general.

**Comment by slorber** [comment]
> Would be nice to also support custom icons too, or add that as an option in the front matter of docs in general.

It would be weird to allow you to provide a custom icon as frontmatter. Custom icons are not only emojis like we used there, but can also be svgs, images, react components... The best way to provide custom icons atm is with swizzling, and we'll make this easier

**Comment by ZarakiKanzaki** [comment]
Hi @slorber ! I wanted to ask you a few questions. As far as I'm understanding the thread it seems there were multiple requests, the one that seems not to be completed is this following one, isn't it?


> Similarly, we want to support custom category descriptions
> 
> ![CleanShot 2022-08-24 at 17 01 18@2x](https://user-images.githubusercontent.com/749374/186453176-9eb1b8b0-dce9-4e8e-858f-e11780b59e1c.png)
> 
> See #7985

If so, I would love to contribute to this issue 😊

**Comment by slorber** [comment]
@ZarakiKanzaki we need a description on:
- category link in sidebars.js
- `_category_.json` files for autogenerated sidebars
- category items of type link (see https://github.com/facebook/docusaurus/issues/7818#issuecomment-1193840525)

Go ahead and open a PR then. As you can see people want to work on it but then go silent, so we don't claim issues anymore and just open the PR directly. Once the PR is open we can chat more about the details in it.

**Comment by ZarakiKanzaki** [comment]
> @ZarakiKanzaki we need a description on:
> 
> * category link in sidebars.js
> * `_category_.json` files for autogenerated sidebars
> * category items of type link (see [Category auto-generated index page should support custom category/link descriptions #7818 (comment)](https://github.com/facebook/docusaurus/issues/7818#issuecomment-1193840525))
> 
> Go ahead and open a PR then. As you can see people want to work on it but then go silent, so we don't claim issues anymore and just open the PR directly. Once the PR is open we can chat more about the details in it.

Thank you for your quick reply 😊  I'll try to open a PR asap

**Comment by Jaya-sys** [comment]
Hey can you assign this issue to me?

**Comment by ZarakiKanzaki** [comment]
> Go ahead and open a PR then. As you can see people want to work on it but then go silent, so we don't claim issues anymore and just open the PR directly. Once the PR is open we can chat more about the details in it.

@Jaya-sys  FYI

**Comment by slorber** [comment]
Something else to address likely in the same PR @ZarakiKanzaki: https://github.com/facebook/docusaurus/issues/7598

If a category has a link to a doc, and that category doesn't have a "description" attribute, we can use the linked doc's frontMatter.description as a fallback value

**Comment by pke** [comment]
@slorber would it also be possible to provide an image to the auto-generator from within the doc that is then displayed in the index box for each page in a fixed size?

**Comment by slorber** [comment]
@pke any example or mockup to share? 

How such image should be provided, and displayed?

**Comment by slorber** [comment]
@pke each docs sidebar item allows passing arbitrary data as a `customProps` attribute: https://docusaurus.io/docs/next/sidebar#passing-custom-props

This data is injected into the relevant sidebar item components as props too, so if you swizzle and theme component responsible for rendering a sidebar item, you can use that data here.

The components that render sidebar items include:
- the... sidebar items themselves
- the docs breadcrumb
- the category index page

I would suggest to assign `sidebarCategory.customProps.myImage` in your sidebar config, and then swizzle `DocCard` to display that custom image. `DocCard` is the component used on the category index page.

**Comment by slorber** [comment]
Basic support for category/link description through the sidebar file (not autogenerated) was added in https://github.com/facebook/docusaurus/pull/8236 and will be in Docusaurus v2.4

![image](https://user-images.githubusercontent.com/749374/225414602-70155240-a7e8-4369-8add-7b2d8788ed7d.png)

This issue remains open to add support for other cases.

Note: I think we should also allow description on doc/ref items? 

Also it looks like it's not possible to override docs `sidebar_label` by using a custom label on the sidebar file. I think the sidebar file should win over frontmatter for such label (and future description) because a doc can be referenced twice in a sidebar (although we highly recommend users to use refs for that case)

**Comment by KirtiKamal** [comment]
> Similarly, we want to support custom category descriptions
> 
> ![CleanShot 2022-08-24 at 17 01 18@2x](https://user-images.githubusercontent.com/749374/186453176-9eb1b8b0-dce9-4e8e-858f-e11780b59e1c.png)
> 
> See #7985

Hey i am new to opensource and  want to contribute to this what actually want to change in this. You want to remove that 4items with custom texts right?

**Comment by bharateshwq** [comment]
Hey, i would like to take up this issue.
The thread above looks a bit convoluted with ideas could you provide me a todo list if possible

**Comment by slorber** [comment]
If anyone want to contribute, the remaining part is to add a `description` field to `_category_.json`, and make it display it in the card.

https://stackblitz.com/edit/github-zbbjra?file=docs%2Ftutorial-basics%2F1-subcategory%2F_category_.json

Currently, this doesn't work and we get an error

![CleanShot 2024-06-20 at 12 35 44](https://github.com/facebook/docusaurus/assets/749374/013baff6-4a22-4688-b992-4086093b6b3b)

---

We don't claim issues here. The first to submit a decent draft PR will more likely to be merged.

**Comment by bharateshwq** [comment]
Hey @slorber I have fixed this issue
