### ISSUE TITLE
'Skip to content' not adjusting to mobile screens in devtools (brave)

### ISSUE THREAD

**Issue by HyunseungLee-Travis** [facebook/docusaurus#7821]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

Note: Exists in all docusaurus projects during development and after building.

In devtools, after changing the width of the screen, the 'skip to content' element still exists in screen.

This is the docusaurus template in CodeSandBox (It also exists in my repo and all the websites using docusaurus).

![afterwidth](https://user-images.githubusercontent.com/78584173/180577939-7008345d-1ca5-44f0-b34a-ea9fec59a555.png)

The element disappears after focusing.

This issue only exists in Brave Browser. All the major browsers tested works fine.

### Reproducible demo

https://docusaurus.sse.codesandbox.io/

### Steps to reproduce

1. Go to site using Brave Browser
2. Open devtools
3. Change width

### Expected behavior

The 'skip to content' element should not appear on screen unless it is focused.

### Actual behavior

In Brave Browser, the 'skip to content' element always appears when changing screen for the first time.

### Your environment

- Public source code: https://codesandbox.io/s/github/facebook/docusaurus/tree/main/examples/classic
- Public site URL: https://docusaurus.sse.codesandbox.io/
- Docusaurus version used: 2.0.0-rc.1
- Environment name and version (e.g. Chrome 89, Node.js 16.4): Brave Browser Latest Version

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by Josh-Cena** [comment]
If it only happens in Brave (and I don't use it) do you have basic idea about why it happens? I personally don't want to spend much time debugging it.

**Comment by slorber** [comment]
If it only happens when devtools are open, maybe we don't care much? 

Does it happen for brave mobile users? 
Does it happen if you reduce the window width manually without the devtools?

**Comment by HyunseungLee-Travis** [comment]
Maybe this is issue is targeted for specific people use brave, I guess.

It only happens when opening devtools (mobile screen).

It does not happen when manually changing the screen.

Maybe this is too minor.
