### ISSUE TITLE
Add autoprefixer into CSS pipeline

### ISSUE THREAD

**Issue by yangshun** [facebook/Docusaurus#784]
In the current CSS pipeline, we do:

- Variable substitution (via custom string replacement)
- Concatentation (via custom file concatenation)
- Minification (via cssnano)

We should do [autoprefixing](https://github.com/postcss/autoprefixer) as a final additional step.

**Comment by vaibhavsingh97** [comment]
@yangshun I am interested to solve this issue

**Comment by yangshun** [comment]
@vaibhavsingh97 Let's work on getting your existing PRs merged first before we move on to new issues 😄

**Comment by helloworld** [comment]
@yangshun going to claim this, since it's been a while since @vaibhavsingh97 was interested 😃

**Comment by yangshun** [comment]
@helloworld it's yours!

I've added an "issue-claimed" label so that others will know not to start work on the issue. If you change your mind about the issue, no worries! Just let me know so that I can remove the label and free it up for someone else to claim.

I'll check in with you periodically so that we can keep the task updated with the progress.
