### ISSUE TITLE
Algolia search widget locks up when used from a landing page

### ISSUE THREAD

**Issue by Zamiell** [facebook/docusaurus#7893]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

On my Docusaurus site, using specific keystrokes will lock up the page.

Steps to reproduce:

1) In an incognito window, surf to https://isaacscript.github.io/, so that the landing page is open.
2) Press / to open the search bar.
3) Type setCustom to start searching. After typing this, the first result should be setCustomStage.
4) Press Enter.
5) Instead of going to the correct page, we will travel from the landing page --> the features page. And then it will lock up, with the blue bar up top slowly moving towards the right. 

Note that the issue **does not occur when using the mouse to click on the first search result**. You must use the enter key to trigger the bug.

@shortcuts told me to open an issue here about this. They are able to locally reproduce the bug using the above steps. They say that the issue might be in Docusaurus-related code, because the search modal is reimplemented on the Docusaurus side, which leverages the main components under the hood.

(For posterity, the GitHub pages site in question was generated from [this commit](https://github.com/IsaacScript/isaacscript/tree/0fe82190447c17f586457d0d86e7ca93f0cf2071).)

### Your environment

- Public source code: https://github.com/IsaacScript/isaacscript
- Public site URL: https://isaacscript.github.io/
- Docusaurus version used: 2.0.1
- Environment name and version (e.g. Chrome 89, Node.js 16.4): Chrome 103.0.5060.134
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): Windows 10

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by shortcuts** [comment]
I'm not able to reproduce on other Docusaurus website. It also happens that we correctly navigates to the page after step 4, then gets redirected to https://isaacscript.github.io/main/features

**Comment by Zamiell** [comment]
The issue was actually on my side with some custom JavaScript that I had forgotten about. Sorry for the noise!

**Comment by Josh-Cena** [comment]
Great, glad there's nothing to be done here :P
