### ISSUE TITLE
Inconsistent resolving of paths to assets

### ISSUE THREAD

**Issue by chernodub** [facebook/docusaurus#7896]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

Hi Guys, huge thanks for your work! 🙌

So, we faced an issue when we were trying to build the website from different OSes (macOS and Linux). In short, paths to assets are resolved a bit inconsistently and sometimes fail. 
I was able to reproduce the issue when letter case of the path to my asset differs from the original. Let's say I have the asset `images/TEST.png`, so when addressing it as `![img](images/test.png)` in my `md` files:

* macOS (Monterey works just fine
* Linux fails with the following error:
	```bash
	Error: Image */images/test.svg used in *.md not found.
    at async Promise.all (index 0)
    
	client (webpack 5.74.0) compiled with 1 error
	```

### Reproducible demo

https://github.com/chernodub/docusaurus-inconsistent-asset-path-issue-repro

### Steps to reproduce

1. Create the website, using classic theme, latest Docusaurus CLI
2. Add asset, let's say `docs/tutorial-basics/images/Test.svg`
3. Add link to asset, like [here](https://github.com/chernodub/docusaurus-inconsistent-asset-path-issue-repro/commit/8560816af1b6d59c92f7ecb8a98020c80576af7e)
4. Change the link to asset to lowercase one
5. Build from macOS and Linux distros, see it working differently

p.s: For easier testing on Linux, I've also [added a dockerfile](https://github.com/chernodub/docusaurus-inconsistent-asset-path-issue-repro/commit/d59fc3a4e2ed5861a3216544f5a87c722fd1e13b) that has Node 16.16 (as far I know it's based on Alpine Linux)

### Expected behavior

Should work consistent on both systems, either fail or build successfully

### Actual behavior

Linux throws an error, while macos building it without issues

### Your environment

- Docusaurus version used: https://github.com/chernodub/docusaurus-inconsistent-asset-path-issue-repro/blob/main/package.json
- Environment name and version (e.g. Chrome 89, Node.js 16.4): 16.16 on both macOS and docker based on Alpine linux
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): macOS Monterey 12.4 and [LTS Alpine Linux](https://hub.docker.com/_/alpine)

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by Josh-Cena** [comment]
Hi, Linux file systems are case-sensitive; macOS is not. Docusaurus behavior is consistent with how the OS handles these files.

**Comment by chernodub** [comment]
That's fair reasoning @Josh-Cena. But I believe that may cause issues for people who're working on machines different from the ones that their cloud server uses (e.g CI pipeline set up by a DevOps team, for example). I've spent several hours trying to debug this :( 

Thanks for the answer anyway!

**Comment by Josh-Cena** [comment]
It's a constant headache for people working with _any_ tooling to realize the inconsistency between Linux and macOS. This is the same for Webpack, TypeScript, and everything else. For example, changing file casing on my Mac won't even be tracked by git, and then the build would fail in GitHub actions.
