### ISSUE TITLE
docusaurus-init fails in Hack/PHP projects: `Error: ENOTDIR: not a directory, scandir '.../vendor/bin/hh-autoload'`

### ISSUE THREAD

**Issue by fredemmott** [facebook/Docusaurus#790]
### Is this a bug report?

(write your answer here)
Yes

### Have you read the [Contributing Guidelines on issues]
Yes
### Environment

Docusaurus was *just* installed via `yarn global add docusaurus`. Yarn outdated command fails:

```
error An unexpected error occurred: "No lockfile in this directory. Run `yarn install` to generate one.".
```

Probably because this isn't a JS project.

### Steps to Reproduce

1. Install HHVM: https://docs.hhvm.com/hhvm/installation/introduction

```
$ git clone git@github.com:hhvm/hhast.git
$ cd hhast
$ wget https://getcomposer.org/composer.phar
$ hhvm composer.phar install
$ docusuarus-init
```

### Expected Behavior

Creation of a docusaurus skeleton

### Actual Behavior

Errors out. Ends with:

```
(node:2585) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
warning package.json: No license field
$ docusaurus-examples
Wrote docusaurus scripts to package.json file.

.gitignore already exists in /private/tmp/hhast/website. Creating an example gitignore file for you to copy from if desired.

fs.js:145
    throw err;
    ^

Error: ENOTDIR: not a directory, scandir '/private/tmp/hhast/vendor/bin/hh-autoload'
    at Object.fs.readdirSync (fs.js:895:3)
    at print (/private/tmp/hhast/website/node_modules/tree-node-cli/tree.js:82:21)
    at contents.forEach (/private/tmp/hhast/website/node_modules/tree-node-cli/tree.js:114:26)
    at Array.forEach (<anonymous>)
    at print (/private/tmp/hhast/website/node_modules/tree-node-cli/tree.js:112:12)
    at contents.forEach (/private/tmp/hhast/website/node_modules/tree-node-cli/tree.js:114:26)
    at Array.forEach (<anonymous>)
    at print (/private/tmp/hhast/website/node_modules/tree-node-cli/tree.js:112:12)
    at contents.forEach (/private/tmp/hhast/website/node_modules/tree-node-cli/tree.js:114:26)
    at Array.forEach (<anonymous>)
error An unexpected error occurred: "Command failed.
Exit code: 1
Command: sh
Arguments: -c docusaurus-examples
Directory: /private/tmp/hhast/website
Output:
".
info If you think this is a bug, please open a bug report with the information provided in "/private/tmp/hhast/website/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
````

yarn-error.log and full terminal log: https://gist.github.com/fredemmott/3755bca61cddc6718afc16ae83979f2f

### Reproducible Demo

Covered above. No `siteConfig.js` as this is a bug in docusuarus-init - it doesn't exist yet.

Reproduces with other hack projects, eg hhvm/hsl. Does not reproduce with `mkdir foo; cd foo; mkdir -p vendor/bin; touch vendor/bin/helloworld`

**Comment by yangshun** [comment]
@fredemmott I wasn't able to reproduce this issue. I cloned https://github.com/hhvm/hhast, did `docusaurus-init` and the `website` dir was generated. Do you have any symlinks in your dir?

It seems like it failed in the tree printing step but the directory skeleton generation step should have succeeded.

**Comment by fredemmott** [comment]
no symlinks except as created by composer/git - this does mean that vendor/bin/hh-autoload is a symlink.

If composer isn't ran (equivalent to not running npm install):
- vendor/bin/hh-autoload doesn't exist
- there are no symlinks
- docusaurus-init works fine

**Comment by yangshun** [comment]
I see. The tree printing library we're using doesn't support symlinks at the moment. But the skeleton should have been generated. Was the skeleton dir generated? Feel free to ping me on Work Chat to discuss about it, I'll be able to respond faster there 😄

**Comment by fredemmott** [comment]
https://github.com/hhvm/hh-apidoc/issues/29 is what led to this :)
