### ISSUE TITLE
npm-to-yarn appears to fail when using 'npx' instead of 'npm'

### ISSUE THREAD

**Issue by spenceradolph** [facebook/docusaurus#7908]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

The problem is actively in the official docs here https://docusaurus.io/docs/installation#updating-your-docusaurus-version

On the line that says `To check that the update occurred successfully, run:`

The `npm` and `yarn` tabs are visible and usable, but clicking between them doesn't change the command below it.
This is likely an issue with the npm-to-yarn package being used, but perhaps this section could simply be re-worked to just avoid the issue entirely.

### Reproducible demo

https://docusaurus.io/docs/installation#updating-your-docusaurus-version

### Steps to reproduce

1. Visit https://docusaurus.io/docs/installation#updating-your-docusaurus-version

### Expected behavior

Expected tabs between yarn and npm to work correctly.

### Actual behavior

The codeblock underneath the tabs stays on 'npx'

### Your environment

- n/a

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by spenceradolph** [comment]
It might be that https://github.com/nebrelbug/npm-to-yarn is being used as a dependency inside https://github.com/facebook/docusaurus/tree/main/packages/docusaurus-remark-plugin-npm2yarn.

The npm-to-yarn repo owner has their profile info stating the following...

"I'm currently serving a [2-year mission](https://newsroom.churchofjesuschrist.org/topic/missionary-program) for [The Church of Jesus Christ of Latter-day Saints](https://www.comeuntochrist.org/). During this time, I will not be working on any of my open-source projects."

@slorber indicated a possible fork in this unanswered discussion https://github.com/nebrelbug/npm-to-yarn/issues/21#issuecomment-952876967

**Comment by Josh-Cena** [comment]
Yep—two issues:

1. This is a dependency we don't control. It's being forked in #6005 but no news yet;
2. Actually, there's no trivial replacement of `npx` in Yarn (especially in Yarn v1; see https://github.com/yarnpkg/yarn/issues/3937). We are better off recommending `npx` to everyone—it works for both Yarn and npm!
