### ISSUE TITLE
vulnerabilities warning when I do npx create-docusaurus@latest

### ISSUE THREAD

**Issue by PackElend** [facebook/docusaurus#7909]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Description

`npx create-docusaurus@latest my-website classic`
tells me 
```
21 vulnerabilities (8 moderate, 13 high)

To address issues that do not require attention, run:
  npm audit fix
```
In [the ](https://discordapp.com/channels/398180168688074762/867060369087922187/1005569717240606762) it is said.
> Ignore the security warnings, it's just because of transitive dependencies
If that is all, it would be welcomed if that is mentioned in the installation procedure as well.

merci

### Self-service

- [ ] I'd be willing to address this documentation request myself.

**Comment by Josh-Cena** [comment]
It happens with every tool (e.g. happens with create-react-app as well), but I don't think we want to mention that. It's everything (a.k.a. npm + security audit registry + vulnerable dependency) but Docusaurus' fault. Thanks for the suggestion, but we can't deform our docs into a mishmash of records of other people's wrong deeds. Once we have an FAQ section (see #7670), I think we can add an FAQ entry; but not in the installation docs.

**Comment by PackElend** [comment]
FAQ sounds good to me.
Hoping that the FAQ and Glossary will be generated by a plugin/core function automatically 🤞
