### ISSUE TITLE
Improve performance for generate static site

### ISSUE THREAD

**Issue by yanzhiwei147** [facebook/Docusaurus#792]
### Is this a bug report?

NO

### Have you read the [Contributing Guidelines on issues]

YES

### Environment

```bash
➜  website git:(master) ✗ yarn outdated docusaurus
yarn outdated v1.7.0
warning package.json: No license field
warning No license field
✨  Done in 3.59s.
```

### Steps to Reproduce

1. In `docs` directory, run `find . -type f -name '*.md' | wc -l` to get the count of markdown files:

![snip20180621_3](https://user-images.githubusercontent.com/5554220/41709992-223f3c68-7577-11e8-92b0-857a384041d8.png)

2. Run `yarn build`, and it build static site to `build/project` directory. 

### Expected Behavior

Build static site as soon as possible quick. eg: 20s?

### Actual Behavior

So long time go over(9 min), it generate unfinished still.

![snip20180621_2](https://user-images.githubusercontent.com/5554220/41710185-9cdd714c-7577-11e8-8900-8978403ee02a.png)

### Reproducible Demo

So sorry, my project is a inner project, so i can't provide it. 

But we can use [the repo](https://github.com/DavidBadura/FakerMarkdownGenerator) to generate random `md` files.

**Comment by endiliey** [comment]
Wontfix in v1. Next major version should be faster (i think)

100 docs generated with my own script -> https://gist.github.com/endiliey/8970281b25b125747c27d8d2be9260f1

Here is how the markdown looks like
![random markdown](https://user-images.githubusercontent.com/17883920/57926265-6ccd2500-78dd-11e9-928c-bdbf6cdc8de4.gif)

Result:

![image](https://user-images.githubusercontent.com/17883920/57926281-748cc980-78dd-11e9-91da-8c3f732e1fa7.png)
