### ISSUE TITLE
Documentation site does not load properly when baseUrl is "/"

### ISSUE THREAD

**Issue by tony-b-4d** [facebook/docusaurus#7935]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

Hi, 

When baseUrl is set to "/", and I'm building the website on gh-pages, the CSS does not load properly and an error message suggests that I use /docs/ as baseURL.

### Steps to reproduce

This does not happen in a local environment. 

See this commit for more details
https://github.com/doc4d/docs/commit/aeb0799eff7b5b92c409839b18de3e607537c015

### Expected behavior

The site builds correctly

### Actual behavior

The site displays an error message 

![error](https://user-images.githubusercontent.com/80901494/183874095-370d036e-a557-4917-9cf8-f3d061b9f437.png)
 
I have to use /docs/ as baseURL to get the site to load properly, but I shouldn't have to (URLs become doc4d.github.io/docs/docs, not an efficient URL).

### Your environment

- Public source code:
- Public site URL:
- Docusaurus version used:
- Environment name and version (e.g. Chrome 89, Node.js 16.4):
- Operating system and version (e.g. Ubuntu 20.04.2 LTS):

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by slorber** [comment]
![CleanShot 2022-08-10 at 12 18 34@2x](https://user-images.githubusercontent.com/749374/183877843-27e1a8bf-c5be-4b92-aebc-5f9f21fa6259.png)

> I have to use /docs/ as baseURL to get the site to load properly, but I shouldn't have to 

Yes you should

The site is hosted on `/docs/` baseurl, so as documented in the gitHub deployment doc, and as the error message suggest, you raally have to use that baseUrl in your site config.

> (URLs become doc4d.github.io/docs/docs, not an efficient URL).

I don't know what you mean by "not efficient URL, but `/docs/docs` is a perfectly fine URL:
- GitHub pages uses `/repoName/` by default as a baseUrl (unless you use an [organization](https://docs.github.com/en/pages/getting-started-with-github-pages/about-github-pages#types-of-github-pages-sites)): you can name your repo something else than "docs" if you want something else
- Docusaurus docs use `/docs/` as prefix for all docs, but you can rename or replace it by `/`


Note: In theory, `/docs/docs` is perfectly valid. In practice we have a bug with `/docs/docs`, and so you should avoid that, see https://github.com/facebook/docusaurus/issues/6294


I'd advise you to name your github repo something else than "docs", or using a better host like Vercel/Netlify.
