### ISSUE TITLE
base url not support a path with host name

### ISSUE THREAD

**Issue by psaren** [facebook/docusaurus#7947]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

what i want is set `baseUrl: "http://cdn.my-website.com/my-website/doc-develop/"` 
to let js/css/png start with CDN hostname + path
what i need is ok
`http://cdn.my-website.com/my-website/doc-develop/assets/js/0e384e19.998cb3eb.js`
but i don't need the page link also start with `http://cdn.my-website.com/my-website/doc-develop/`
<img width="745" alt="image" src="https://user-images.githubusercontent.com/18643034/184278651-66f7422e-51a0-403e-846f-eb93e2d409dc.png">

### Steps to reproduce

1. config `baseUrl: "http://cdn.my-website.com/my-website/doc-develop/"` 
2. yarn build

### Expected behavior

page link not start with CDN hostname

### Actual behavior

<img width="745" alt="image" src="https://user-images.githubusercontent.com/18643034/184278651-66f7422e-51a0-403e-846f-eb93e2d409dc.png">

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by Josh-Cena** [comment]
`http://cdn.my-website.com/` is your `url`; `/my-website/doc-develop/` is your `baseUrl`. Please read https://docusaurus.io/docs/api/docusaurus-config

**Comment by Josh-Cena** [comment]
After re-reading it, I think what you want is a `cdnUrl` config. We are not against adding it, but we need a more detailed feature proposal instead of a bug report for a workaround that's apparently not working. Related:

- https://docusaurus.io/feature-requests/p/how-to-deploy-htmlassets-to-different-cdn
- https://github.com/facebook/docusaurus/discussions/4123

If you feel strongly feel free to follow up in either place or open a new issue with a detailed feature design as well as a strong use-case/motivation.

**Comment by slorber** [comment]
Why do you want to separate the hosting of static HTML files vs assets? 

Why do you want only your assets to be hosted on your CDN?

For maximum efficiency, you want to distribute your static HTML files and your assets from a CDN, and this is what you get for free with Netlify, Vercel, Cloudflare pages...

**Comment by iamphonghg** [comment]
Hi @slorber ,
My website is hosted on a shared server. Sometimes, js files and images of blogs and docs load extremely slow. Otherwise, my other web app use CDN service of AWS to store its js, css files and images and they load fast. That's why I want somehow to use CDN for my doc web.
