### ISSUE TITLE
Making getSlug available from outside of the packages

### ISSUE THREAD

**Issue by JPeer264** [facebook/docusaurus#7961]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Motivation

We are trying to generate slugs / paths inside a remark plugin and wanted to rely on the way how docusaurus are doing these. We came across this function: https://github.com/facebook/docusaurus/blob/bf1513a3e357025ab1cf4cdb4c09f21316b31cfd/packages/docusaurus-plugin-content-docs/src/slug.ts#L24-L31

Which seems to generate the correct slugs and paths based on the input. The thing is that this function is not exported in the package.json: https://github.com/facebook/docusaurus/blob/bf1513a3e357025ab1cf4cdb4c09f21316b31cfd/packages/docusaurus-plugin-content-docs/package.json#L7-L12

Would it be alright to also add the entire lib in the `package.json` to get access to internal (e.g. adding `"./lib/*": "./lib/*", ` to the `package.json`? Or move `getSlug` to `@docusaurus/utils`? 

### Self-service

- [X] I'd be willing to do some initial work on this proposal myself.

**Comment by Josh-Cena** [comment]
Seems reasonable to make the entire library's files available via wildcards. Do you want to send a PR adding a `"./lib/*": "./lib/*"`?

Important: This does not endorse these as public APIs. You are responsible for migrating any breakages between versions. You should probably not publish this as a package.

**Comment by JPeer264** [comment]
Sure I will create a PR. We are aware that this is still a internal function without any guarantee - but thanks for double checking :)
