### ISSUE TITLE
clientEntry preload cannot handle duplicate slashes in pathname

### ISSUE THREAD

**Issue by andrewnicols** [facebook/docusaurus#7965]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

We use Netlify for our builds and I've just been troubleshooting an issue whereby someone had linked to https://moodledev.io//general/releases - not the double forward slash.

When visiting this page the content briefly shows before disappearing.

Originally I thought that this was some kind of Netlify issue, and I looked into writing a rewrite rule to redirect users, but that doesn't seem to be easy/possible in Netlify. However, it occurs to me that this is possibly _also_ a Docusaurus bug.

I've tracked this back to the use of `window.location.pathname` in https://github.com/facebook/docusaurus/blob/main/packages/docusaurus/src/client/clientEntry.tsx#L34

In this case, the pathname is `//docs/releases`, which is not an exact match for any of the routes and therefore the Promise is rejected and the 404 page served.

The is of course a valid URL, and I feel that perhaps this kind of issue should either:
* just be served; or
* the duplicate slashes in the URL rewritten since they are meaningless anyway.

### Steps to reproduce

Visit a prodcution page (not served by `yarn serve`) and watch it serve initially, and then turn into a 404, examples include:
* https://docusaurus.io//docs/docusaurus-core
* https://docusaurus.io/docs//docusaurus-core
* https://moodledev.io//docs/releases

### Expected behavior

EIther correct the URL, or just serve the content

### Actual behavior

404

### Your environment

- Public source code: https://github.com/moodle/devdocs
- Public site URL: https://moodledev.io
- Docusaurus version used: latest
- Environment name and version Chrome 104
- Operating system and version MacOS

### Self-service

- [X] I'd be willing to fix this bug myself.

**Comment by Josh-Cena** [comment]
The server sends the correct HTML but the router does not recognize this location and hydrates it as a 404 page—that's pretty expected.

Why would you want it to work?

**Comment by Josh-Cena** [comment]
Duplicate slashes are not meaningless in the router—virtually all URLs can have different meanings to the router. You can even have different content for `/foo` and `/foo.html`, so any kind of rewrite can only be based on an informed guess. But I think this behavior (namely, duplicate slashes being tolerated) is not consistent between hosting providers?

**Comment by andrewnicols** [comment]
It's not unexpected for people to make small mistakes like adding an extra / in a URL and we should try hard _not_ to break in these situations.

I'd expect it to at least try and normalise the URL, especially since the correct HTML is indeed returned. If the HTML is returned then surely it should be possible to return the route for that page?

**Comment by andrewnicols** [comment]
Perhaps it would be possible for the server-rendered HTML to redirect to the correct pathname if it does not match (just pathname, not the canonical).

**Comment by slorber** [comment]
We are using React-Router

Why not request this behavior for all React apps using React-Router instead of here?

Doesn't it make sense for Remix apps too for example (based on React-Router)?

I'd rather not implement something too fancy that fights against the behavior of our lib. If you can convince React-Router authors that this behavior is worth implementing, we'll benefit from it by simply upgrading.

**Comment by slorber** [comment]
For now I'll close this issue

Now if you really want this, we can reopen if you do the homework:
- show us a file-system structure to adopt for serving static files under `//docs/xyz`
- deploy it to Netlify/Vercel/GitHub Pages and prove that it works consistently
- ask to add this to React-Router and if they don't want it, we can consider it for Docusaurus

**Comment by Josh-Cena** [comment]
FWIW, I always like changes that turn more errors into less errors.
