### ISSUE TITLE
trailingSlash: true breaks relative hyperlinks to static assets under /files

### ISSUE THREAD

**Issue by stnor** [facebook/docusaurus#7972]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io.
- [ ] I have read the console error message carefully (if applicable).

### Description

I added trailing slash to befriend Google SEO tools, and now it seems that a few links in the markup using <a href="/files/something.pdf"></a> (for example) gets a slash added too, which results in a 404.

Is this a bug or as intended?

A workaround was to specify an absolute URL for the asset.

### Steps to reproduce

1. Create MD page with an html a href="/files/my.pdf"... link
2. Set trailingSlash: true in the config.
3. click on the link.
4. A 404 error code due to the added trailing slash.

### Expected behavior

No added trailing slash for static files

### Actual behavior

The slash was added on the link.

### Your environment

- Public source code:
- Public site URL:
- Docusaurus version used:
- Environment name and version (e.g. Chrome 89, Node.js 16.4):
- Operating system and version (e.g. Ubuntu 20.04.2 LTS):

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by stnor** [comment]
It seems to be a dupe. I edited the issue a bit. Is it more clear now? If not, please let me know what's not clear.

**Comment by Josh-Cena** [comment]
Ah yes, seems to be a duplicate. Let's track it in #6282 then. I guess it won't hurt to special-case some patterns that look like extensions...

**Comment by stnor** [comment]
I'm on 2.0.1 btw.
