### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by nhuyvan** [facebook/docusaurus#7979]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [ ] I have tried the `npm run clear` or `yarn clear` command.
- [ ] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

I couldn't even run the `npx create-docusaurus@latest hello-world classic --typescript` to install, it kept failing, below is the output of the commands that I ran

```
D:\projects
λ npx create-docusaurus@latest hello-world classic --typescript
npm ERR! Unexpected token '.'

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\[...]\AppData\Local\npm-cache\_logs\2022-08-20T08_19_53_243Z-debug-0.log

D:\projects
λ node -v
v16.17.0

D:\projects
λ npm -v
8.15.0
```

When I catted the log file above, I got this

```
λ cat C:\Users\[...]\AppData\Local\npm-cache\_logs\2022-08-20T08_19_53_243Z-debug-0.log
[...]
29 timing npm:load:logFile Completed in 4ms
30 timing npm:load:timers Completed in 0ms
31 timing npm:load:configScope Completed in 0ms
32 timing npm:load Completed in 20ms
33 verbose stack D:\nvm\v16.17.0\node_modules\npm\node_modules\libnpmexec:1
33 verbose stack ../workspaces/libnpmexec
33 verbose stack ^
33 verbose stack
33 verbose stack SyntaxError: Unexpected token '.'
33 verbose stack     at Object.compileFunction (node:vm:360:18)
33 verbose stack     at wrapSafe (node:internal/modules/cjs/loader:1055:15)
33 verbose stack     at Module._compile (node:internal/modules/cjs/loader:1090:27)
33 verbose stack     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1180:10)
33 verbose stack     at Module.load (node:internal/modules/cjs/loader:1004:32)
33 verbose stack     at Function.Module._load (node:internal/modules/cjs/loader:839:12)
33 verbose stack     at Module.require (node:internal/modules/cjs/loader:1028:19)
33 verbose stack     at require (node:internal/modules/cjs/helpers:102:18)
33 verbose stack     at Object.<anonymous> (D:\nvm\v16.17.0\node_modules\npm\lib\commands\exec.js:1:17)
33 verbose stack     at Module._compile (node:internal/modules/cjs/loader:1126:14)
[...]
```

### Steps to reproduce

1. Run `npx create-docusaurus@latest hello-world classic --typescript`

### Expected behavior

Installation should succeed

### Actual behavior

Installation keeps failing with `Unexpected token '.'`

### Your environment

- Public source code:
- Public site URL:
- Docusaurus version used:
- Environment name and version (e.g. Chrome 89, Node.js 16.4): Node 16.17.0, npm 8.15.0
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): Windows 10

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by Josh-Cena** [comment]
That log doesn't point to our code at all. It seems you have a corrupted npm installation.

**Comment by jeacott1** [comment]
same issue. windows, with nvm managed node. everything else works fine.
