### ISSUE TITLE
[WARNING] Unused default message codes found.

### ISSUE THREAD

**Issue by anaclumos** [facebook/docusaurus#7983]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

I got this error while writing translations.

<img width="419" alt="image" src="https://user-images.githubusercontent.com/31657298/185845252-d7fbe7b6-cb2d-4f7d-bb06-a9de4e84e2e1.png">

### Steps to reproduce

https://github.com/anaclumos/www

```bash
yarn write-translations --locale ko
```

### Expected behavior

No error

### Actual behavior

[WARNING] Unused default message codes found.

### Your environment

- Public source code:
- Public site URL:
- Docusaurus version used:
- Environment name and version (e.g. Chrome 89, Node.js 16.4):
- Operating system and version (e.g. Ubuntu 20.04.2 LTS):

### Self-service

- [X] I'd be willing to fix this bug myself.

**Comment by Josh-Cena** [comment]
This is a technical limitation. This translation ID resides in `theme-common` and seems we are not analyzing it.

**Comment by slorber** [comment]
little bug due to the usage of package `"exports"` field and a Node.js exception being swallowed by a `catch {}` block

fixed in https://github.com/facebook/docusaurus/pull/7996

**Comment by anaclumos** [comment]
Incredible, huge kudos to you all! I show my massive respect to the docusaurus team!
