### ISSUE TITLE
Site config url + baseUrl are not normalized and sensitive to leading/trailing slash

### ISSUE THREAD

**Issue by aniaq** [facebook/docusaurus#7989]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [ ] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

Meta data "og:url" - url has double slashes in the prerendered HTML

`<meta data-rh="true" property="og:url" content="https://example.com//docs/courses/how-are-the-course-accessed-with-the-lifetime-membership/">`

It happens when slash is added at the end of the URL in docusaurus.config.js, in my case   
`url: 'https://example.com/'`

### Steps to reproduce

1. Set in config url to: `https://example.com/`
2. Build
3. Search HTML code for `og:url`

### Expected behavior

One slash in the URL  

### Actual behavior

Double slashes in the URL  

### Your environment

- Public source code: 
- Public site URL: docs.divi.space
- Docusaurus version used:  2.0.1
- Environment name and version (e.g. Chrome 89, Node.js 16.4):  node v16.17.0
- Operating system and version (e.g. Ubuntu 20.04.2 LTS):  macOS Monterey 12.2

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by noobyogi0010** [comment]
@Josh-Cena I would like to work on this issue if no has taken it up.

**Comment by Josh-Cena** [comment]
I'm still thinking about how we should do it. Maybe we should normalize the `url` and `baseUrl` during validation, instead of patching it everywhere.

**Comment by noobyogi0010** [comment]
I think so too.
It'll be better to cleanse the `url` and `baseurl` before patching it.

**Comment by slorber** [comment]
Yes we don't really make it failsafe on url/baseUrl config. 

Even if user is using baseurl without leading/trailing slash afaik it cause troubles. 

I'd be happy to normalize those:
- URL should not end with `/`
- baseUrl should start/end with `/`

I don't think our config should reject/warn, but maybe just fix the user config automatically?

**Comment by Josh-Cena** [comment]
Correct, I'm also a bit confused why our validation fails `baseUrl` without starting/ending `/` when it could normalize that quite easily.
