### ISSUE TITLE
Sidebar categories don't autocollapse correctly

### ISSUE THREAD

**Issue by dustinlacewell** [facebook/docusaurus#7994]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

I am able to get multiple categories to be open at once.

See here:

![](https://user-images.githubusercontent.com/53952/186334681-78a6f801-4314-4f6a-8a33-1f46bbc648da.gif)

### Steps to reproduce

I am honestly not sure. I'm not doing anything strange and it doesn't happen on the playground... 

### Expected behavior

Only one category should be expanded with `autoCollapseCategories` being true.

### Actual behavior

Sometimes it is possible to get multiple categories to be expanded as once.

### Your environment

- Docusaurus version used: 2.0.1

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by RodinGolodin** [comment]
`autoCollapseCategories` is actually not working at all, throwing a validation error: `[ERROR] ValidationError: "docs.sidebar" is not allowed`

**Comment by RodinGolodin** [comment]
Here's the fragment of `themeConfig` from my `docusaurus.config.js`:

```
themeConfig:
    /** @type {import('@docusaurus/preset-classic').ThemeConfig} */
    ({
      docs: {
        sidebar: {
          autoCollapseCategories: true,
        },
      },
```

**Comment by slorber** [comment]
> `autoCollapseCategories` is actually not working at all, throwing a validation error: `[ERROR] ValidationError: "docs.sidebar" is not allowed`

Most likely you try to add this to plugin options instead of themeConfig. We do use it on our own website as well as many other users so make sure you double-check where you add this attribute.

https://docusaurus.io/docs/sidebar#auto-collapse-sidebar-categories

Closing this issue because op didn't answer

**Comment by RodinGolodin** [comment]
The only reason it didn't work is because I was on Docusaurus 2.0.0. Running `yarn upgrade @docusaurus/core@latest @docusaurus/module-type-aliases@latest     ││                          @docusaurus/preset-classic@latest` fixed the problem.
