### ISSUE TITLE
Algolia DocSearch `contextualSearch` Attributes for faceting Documentation

### ISSUE THREAD

**Issue by fishcharlie** [facebook/docusaurus#8011]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Description

I recently had an issue where search results weren't displaying at all when using Algolia DocSearch. You can read about the full issue and my findings at: https://github.com/dynamoose/dynamoose/issues/1486.

Long story short tho, it worked when `contextualSearch: false` but not if it was true (and the default is true). I tracked the issue down to the fact that `Attributes for faceting` in Algolia dashboard settings only had `lang` & `type` set. Adding `docusaurus_tag` & `language` fixed the problem. But I couldn't find any documentation for this on the Docusaurus website.

Seems like the ideal case here would be for DocSearch to throw an error if you are trying to search for attributes that aren't in the `Attributes for faceting` section, but that is a different conversation.

I'm also unsure if those are the only two attributes I need to add to that section. Does Docusaurus ever use more attributes for faceting?

Seems like the documentation should include a full list of attributes it uses for faceting. I'd be happy to submit a PR for this, but I need guidance on what other attributes Docusaurus might use for faceting.

### Self-service

- [ ] I'd be willing to address this documentation request myself.

**Comment by Josh-Cena** [comment]
cc @shortcuts interested to hear your insights here

**Comment by shortcuts** [comment]
Hey!

_I'm giving generic context/answer here for anyone having trouble with similar issue_

>  I tracked the issue down to the fact that Attributes for faceting in Algolia dashboard settings only had lang & type set.

This meant that when we generated a config for your website and deployed it, it was either:
- (probable) not yet running on Docusaurus v2, hence the config not having [the minimal requirements](https://docsearch.algolia.com/docs/templates/#docusaurus-v2-template)
- (unlikely) we failed to detect that your website was built with Docusaurus v2 (if so we need to investigate why)
- (most certainly) it was in the really early batch of the [migration to the new infra](https://docsearch.algolia.com/docs/migrating-from-legacy) (~oct/nov 2021) which was missing crucial fixes that we implemented later on (really sorry if it's your case!)

In any case, I'd recommend you following the steps on this part of our documentation: https://docsearch.algolia.com/docs/crawler/#search-yield-no-results

> Seems like the ideal case here would be for DocSearch to throw an error if you are trying to search for attributes that aren't in the Attributes for faceting section, but that is a different conversation.

We usually don't make those kind of assumptions, plus its the kind of validation that could impact the general performance of a search engine. I can however understand, in the case of DocSearch, where you expect to have something that work out of the box, that it can be blurry to debug.

> I'm also unsure if those are the only two attributes I need to add to that section. Does Docusaurus ever use more attributes for faceting?

Everything that you can see [in the Docusaurus template we provide](https://docsearch.algolia.com/docs/templates/#docusaurus-v2-template) should be in your config, at least the `initialIndexSettings` part, the rest is up to you to edit.

**Comment by fishcharlie** [comment]
@shortcuts 

> I'm giving generic context/answer here for anyone having trouble with similar issue

Just want to point out that due to this projects guidelines, I made my initial post very specific to documentation updates. Not sure it has enough keywords or explanation for people who have the similar issues to find.

> (most certainly) it was in the really early batch of the [migration to the new infra](https://docsearch.algolia.com/docs/migrating-from-legacy) (~oct/nov 2021) which was missing crucial fixes that we implemented later on (really sorry if it's your case!)

Not sure how I can figure that out. The site is https://dynamoosejs.com. I don't think either of the other things applied.

I'm curious tho why I wasn't alerted about this. Seems like if critical fixes were implemented later on, you should have alerted impacted users and provided documentation to them to fix it.

> In any case, I'd recommend to follow those steps: https://docsearch.algolia.com/docs/crawler/#search-yield-no-results

This documentation is really poor. Here is why I say that. I actually found this documentation page during my investigation of this issue.

There were no errors in the developer tools. So that wasn't the issue.

`[Your Crawler config](https://docsearch.algolia.com/docs/record-extractor) matches your website structure`. Don't think this applies since I'm using docusaurus. But it isn't very clear, so maybe I'm wrong here?

`Your index settings are up to date (you'll see a banner in [the search preview](https://docsearch.algolia.com/docs/manage-your-crawls/#search-preview) if not)`. I **never** saw a banner in the search preview. So I didn't think this applied. The `we recommend you to delete your index from the Algolia dashboard before starting a new crawl` was interesting. But I was concerned about doing that because it has no steps about how to re-create it. Would docusaurus have handle it all seamlessly and automatically? Couldn't find any documentation there, so I determined it was too risky to do.

So I followed that entire section and it didn't help at all.

I ended up sending a support email (ticket number: 511885) about this issue to Algolia, and got some initial help, but said they don't provide technical support for this. So was forced to figure out the rest on my own.

> We usually don't make those kind of assumptions, plus its the kind of validation that could impact the general performance of a search engine. I can however understand, in the case of DocSearch, where you expect to have something that work out of the box, that it can be blurry to debug.

"blurry"? How about impossible? I understand the performance consideration. But right now you don't have any tools to debug this. Maybe consider adding requests to a queue and doing validation later on? And having a page where you can view errors that were found? Not sure. Seems like there are ways to workaround this tho while maintaining high performance.

---

I understand this is a free product, and open source. **However**, a lot of time gets wasted when documentation is awful, support doesn't help, there is no debugging tools, no error messages occur, and most of all the Docusaurus issues expect a reproducible example and you to investigate on your own. I understand the rational behind each of those things, but it leads to a situation where **ALL** of the cards are stacked against users here. So I ended up wasting hours on this.

What is done is done. Time was sunk into this. It's resolved now. But I think it's important to reflect on this process and the experiences users are having. This was a failure on many levels.

Improvements should be made. Let me know if I can assist with this. But it's really up to the Docusaurus & DocSearch teams to take the lead on this (hopefully mainly focus on documentation improvements).

**Comment by shortcuts** [comment]
> I'm curious tho why I wasn't alerted about this. Seems like if critical fixes were implemented later on, you should have alerted impacted users and provided documentation to them to fix it.

We updated the documentation, templates are here for guidance, once deployed, we don't maintain your config anymore unless you asked for help.

Sorry for your issue but out of the 5k DocSearch users, there can be 5k different reasons to make a config fail, we can't dedicate time to maintain all of them, and it's not the purpose of DocSearch. 

> But I was concerned about doing that because it has no steps about how to re-create it.

If steps are not stated it means you don't have to worry about it. When using open-source product, you need to trust the doc, even if it seems blurry to you. 

Anyway, the crawl does it for you. Feel free to read the Crawler docs if you want to know how it works. 

> I understand this is a free product, and open source. **However**, a lot of time gets wasted when documentation is awful

Keep in mind it's also a community project, we do that on our free time. Feedbacks are great but needs to be actionable.

Feel free to open issues/PRs with guidance on what seems wrongly documented to you!

**Comment by slorber** [comment]
@fishcharlie I understand that you are upset to lose hours, but that seems unfair to criticize our work like you did here.

We DO document the fact that you should have a config similar to the default one.

<img width="742" alt="CleanShot 2022-08-31 at 20 03 55@2x" src="https://user-images.githubusercontent.com/749374/187748922-1402d139-8e0b-4075-8c0c-1ed516ab48fd.png">

Isn't this message clear and visible enough? If you have any opinion, open a PR and improve it.

Did you compare your config VS the [Docusaurus recommended config](https://docsearch.algolia.com/docs/templates/#docusaurus-v2-template) in the first place? 

Did you run a diff between these 2 and investigate the differences? 

Did you even ask for help and provided your bad crawler config to anyone qualified to help you? 

You mention poor docs, but did you consider also poor issues, where maintainers have to read a long wall of text full of complaints just to try to understand your problem? That could have been figured out in 5 minutes if you just shared your crawler config. I'm not even sure the crawler config is actually the problem, I have to infer it from thousands of characters. The problem seems fixed, but you don't really thank anyone for the solution, and don't even explain what worked in the end, so that other community members can learn from your experience and avoid losing the very hours that you said we made you lose with poor docs.

For these reasons, I'm going to close this issue. I think you have solved your problem, so you probably know what we should write in our respective docs so that others don't lose as much time as you did. We are waiting for your PRs.

Thanks for the support @shortcuts
