### ISSUE TITLE
Vietnamese URL slug not good

### ISSUE THREAD

**Issue by Shenlong616** [facebook/docusaurus#8012]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [ ] I have tried the `npm run clear` or `yarn clear` command.
- [ ] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io.
- [ ] I have read the console error message carefully (if applicable).

### Description

# Test conditions

```
Bọn này hoà đồng thân thiện
```

## Tag
![image](https://user-images.githubusercontent.com/15698245/187008736-40c028bc-38a2-408b-852b-b963c3458a96.png)

```
/tags/bọn-nay-hoa-dồng-than-thiện
```

## ToC
![image](https://user-images.githubusercontent.com/15698245/187008801-293af6f7-aa47-4d44-a959-769167aece40.png)

```
/blog/2022/04/21/post#bọn-này-hoà-đồng-thân-thiện
```

### Steps to reproduce

undefined

### Expected behavior

undefined

### Actual behavior

undefined

### Your environment

- Public source code:
- Public site URL:
- Docusaurus version used:
- Environment name and version (e.g. Chrome 89, Node.js 16.4):
- Operating system and version (e.g. Ubuntu 20.04.2 LTS):

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by Josh-Cena** [comment]
Without a repro or any description of what's wrong we can't help you. I'm going to close this for now; feel free to follow up with more information about what's wrong and what you expect to see. The current behavior looks good enough to me.
