### ISSUE TITLE
One place for browse and submit community plugin and theme

### ISSUE THREAD

**Issue by Pana** [facebook/docusaurus#8023]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Description

Currently there is no a place where we can find awesome community plugin and themes, if there is one which will be very helpful

### Self-service

- [ ] I'd be willing to address this documentation request myself.

**Comment by Josh-Cena** [comment]
We already have this: https://docusaurus.io/community/resources and—it's already titled "awesome"!
