### ISSUE TITLE
When I use displayed_sidebar: null, useCurrentSidebarCategory will report an error because the context is not found.

### ISSUE THREAD

**Issue by harrytothemoon** [facebook/docusaurus#8034]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Description

Situation: 
Currently I need to take the data built manually from `sidebar.js` through the `useCurrentSidebarCategory` hook, pass the data in and render it into a directory, but I don't want this page to show both the self-built directory on the main page and sidebar on the left side.
At the moment it seems that as long as the keyword `displayed_sidebar` is used, the hook will not be able to capture the data, so I would like to ask if there is a better way for me to decide if this page sidebar is displayed or not, or if I need to hide it manually through custom CSS?

Note:
I have tried to use swizzle to customize `DocPage/layout`, but since it is unsafe, I have not considered this approach for the time being.

### Self-service

- [x] I'd be willing to address this documentation request myself.

**Comment by harrytothemoon** [comment]
Update: I am currently using swizzle's method to determine whether to render the sidebar by the path.

**Comment by slorber** [comment]
`useCurrentSidebarCategory()` fails fast if it is called on a doc that doesn't render any sidebar. It will throw instead on returning null by design, to prevent edge cases to be silently swallowed/ignored by developers.


This hook permits to know if the current page has a sidebar. It will return null if there's no available sidebar in the current doc context:

```jsx
import {useCurrentSidebarCategory} from '@docusaurus/theme-common';
import {useDocsSidebar} from '@docusaurus/theme-common/internal';

function MyComponent() {
 const sidebar = useDocsSidebar();
 if (!sidebar) {
   return null; // Render what you want here, handle the edge case explicitly
 }
 return <MyComponentReadingCurrentCategory/>
}

function MyComponentReadingCurrentCategory() {
  const category = useCurrentSidebarCategory();
  // Render what you want here
}
```
