### ISSUE TITLE
Migration of Docusaurus users to 1.3.0

### ISSUE THREAD

**Issue by yangshun** [facebook/Docusaurus#804]
Not a real task per se, using this to track the migration status of users to 1.3.0:

- [Docusaurus](https://docusaurus.io) [[merged](https://github.com/facebook/Docusaurus/pull/791)]
- [React Native](https://facebook.github.io/react-native/) [[merged](https://github.com/facebook/react-native-website/pull/422)]
- [Jest](https://facebook.github.io/jest/) [[merged](https://github.com/facebook/jest/pull/6510)]
- [Reason](https://reasonml.github.io/) [[merged](https://github.com/reasonml/reasonml.github.io/pull/398)]
- [Reason React](https://reasonml.github.io/reason-react/) [[merged](https://github.com/reasonml/reason-react/pull/251)]
- [Prettier](https://prettier.io/) [[merged](https://github.com/prettier/prettier/pull/4738)]
- [Metro](https://facebook.github.io/metro/) [[merged](https://github.com/facebook/metro/pull/186)]
- [Draft.js](https://draftjs.org/) [[merged](https://github.com/facebook/draft-js/pull/1797)]

Good news is that no major issue was found so far. The backward-incompatible CSS wasn't as much as I thought.

**Other potential users to help migrate:**

- [Babel](https://babeljs.io)
- [Sonar](https://fbsonar.com)

**Comment by endiliey** [comment]
@yangshun seems that no response for https://github.com/facebook/draft-js/pull/1797

**Comment by yangshun** [comment]
I'll ping the maintainer tomorrow and at the same time update to a newer Docusaurus version.

**Comment by yangshun** [comment]
All projects have been updated to >= Docusaurus 1.3.0. Closing this!
