### ISSUE TITLE
Can I use an external react component inside Docusaurus?

### ISSUE THREAD

**Issue by caiorasc** [facebook/Docusaurus#806]
### Is this a bug report?

No, this is a doubt

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

### Environment

yarn outdated v1.5.1, Windows 10, node v8.9.3

### Steps to Reproduce

I'm trying to use [redoc](https://github.com/Rebilly/ReDoc) as a react component, inside Docusaurus, but doesn't work
 
(Write your steps here:)

1. Follow the Docusaurus **Getting Started** tutorial
2. Go to `website` directory and install redoc `yarn add redoc`
3. Inside `pages` directory, create a new file called `docApi.js` and put the code below:
```javascript
const React = require('react');
import { RedocStandalone } from 'redoc';

class docApi extends React.Component {
    render() {
        return (
            <div>
                <RedocStandalone
                    specUrl="https://rebilly.github.io/ReDoc/openapi.yaml"
                    options={{
                        nativeScrollbars: true,
                        theme: { colors: { main: '#dd5522' } },
                    }}
                />
            </div>
        );
    }
}

module.exports = docApi;

```

4. Run the local webserver via `yarn start` and put `/docApi.html` on the url to see the error

### Expected Behavior

I expect something like site [rebilly redoc](https://rebilly.github.io/ReDoc/)

### Actual Behavior
I only see the static svg loading

### Reproducible Demo

[Reproducible Demo Repo](https://github.com/caiorasc/docusaurus-sample)

**Comment by endiliey** [comment]
Yes. But only in v2.

Coming soon

**Comment by franc0is** [comment]
For what it's worth, I just tried this in V2 and it works :-).

**Comment by caiorasc** [comment]
Thanks, I'll try the v2

**Comment by chase2981** [comment]
Could someone please tell me how to accomplish something like the following please? Essentially I can't have all my docs and my components be in the same directory cuz i have multiple apps in my project. Therefore I have a `flex-docs` folder, (which is essentially the docusaurus "website" folder) then I have a `flex-plugins` folder, a `flex-webchat-ui` folder, and a`flex-lib` folder. My problem is everything works all fine and dandy until I try to use any third party libs in the component that my mdx file is referencing. (See https://codesandbox.io/s/sharp-austin-m0z74?from-embed=&file=/flex-docs/docs/doc2.mdx for more details which mirrors my real setup) So it works in my real setup if the `Test` component is just plain with no imports, but as soon as I import any `styled-components` into the `Test` component, or any `@material-ui/core` components into my `Test` component, then all the sudden it starts throwing the following error. I don't get it. I made sure the react versions were the same and everything. I'm using docusaurus v2. (https://codesandbox.io/s/sharp-austin-m0z74?from-embed=&file=/flex-plugins/src/components/demo.jsx)

Any help would be greatly appreciated! I love your product. 

P.s. I found this thread by searching "docusaurus invoke component in another directory" btw.. Thnx in advance!

<img width="1792" alt="Screen Shot 2020-11-28 at 11 18 01 PM" src="https://user-images.githubusercontent.com/10983569/100534796-f8f92180-31cf-11eb-8491-eff90a37124a.png">

**Comment by slorber** [comment]
@chase2981 what you are looking for is likely a Yarn Workspace / Lerna monorepo. That's not really related to this issue not Docusaurus but is related to modularisation of your own js code.
