### ISSUE TITLE
Markdown filenames starting with `_` cannot be referenced in a sidebar

### ISSUE THREAD

**Issue by znat** [facebook/docusaurus#8069]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

In the docs folder (it might occur in pages too but haven't tried), filenames starting with `__` (e.g `__main__.md`) are not found by the sidebar and this creates an error.
```
Error: Bad sidebars file.
These sidebar document ids do not exist:
- path/to/__underscore__`,

Available document ids=
...
```

### Reproducible demo

https://stackblitz.com/edit/github-kmicbd?file=docs/__underscore__.md

### Steps to reproduce

1. add a `__main__.md` file in the docs folder
2. reference this file in a manual sidebar

### Expected behavior

Sidebar shows the file and links to it

### Actual behavior

Error preventing startup:

```
Error: Bad sidebars file.
These sidebar document ids do not exist:
- path/to/__underscore__`,

Available document ids=
...
```

### Your environment

- Public source code:
- Public site URL:
- Docusaurus version used: 2.1.0
- Environment name and version (e.g. Chrome 89, Node.js 16.4):
- Operating system and version MacOS

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by Josh-Cena** [comment]
Hi this is a feature. Files starting with an underscore is a partial and won't be included, see https://docusaurus.io/docs/markdown-features/react#importing-markdown

You can either configure that with the plugin's `exclude` option, or you can change your file name to something else, and then adjust everything else with front matter, like:

```yml
---
id: __main__
slug: __main__
title: __main__
---
```

**Comment by znat** [comment]
Oh thanks a lot, I missed that page.
My use case was integrating docs generated with `pydoc-markdown` so I can't go around `__main__` and `__init__` files.

**Comment by Josh-Cena** [comment]
Ahhh, then you need to change the `exclude` option. The default value can be found here: https://docusaurus.io/docs/api/plugins/@docusaurus/plugin-content-docs#ex-config
