### ISSUE TITLE
Title not centred vertically when no headerIcon

### ISSUE THREAD

**Issue by knowbody** [facebook/Docusaurus#808]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

### Environment

Docusaurus version 1.3.0

### Steps to Reproduce

1. Set `headerIcon` in `siteConfig.js` to be an empty string
2. Set some `title`

### Expected Behavior

In previous versions the title was centered vertically and the headerImage was not displayed

### Actual Behavior

The title is only vertically centered when there is an `headerIcon` specified in `siteConfig.js`, otherwise it look like:

![image](https://user-images.githubusercontent.com/3802023/41959791-493244a2-79ee-11e8-8559-90a2c44cd3f1.png)

### Reproducible Demo

Have a look at the [Rebolt](https://rebolt.callstack.com/) page.

**Comment by yangshun** [comment]
Shoots, that's embarrassing. Thanks for reporting it!

**Comment by knowbody** [comment]
@yangshun there is also a slight issue with the height of the logo in the footer, also visible on the Rebolt page. Maybe it could be fix at the same time as that's also CSS issue

**Comment by yangshun** [comment]
Gotcha, will investigate!

**Comment by knowbody** [comment]
Thank you!

**Comment by yangshun** [comment]
@knowbody The footer logo issue is a user-controlled style and should be fixed on your side. The `height` attribute could be removed in https://github.com/callstackincubator/rebolt/blob/master/website/core/Footer.js#L95.

**Comment by yangshun** [comment]
@knowbody I have a fix out at #811. We'll get it merged and release a 1.3.1 soon enough. When Rebolt docs is ready, it would be great if you could add your project to our [list of users](https://docusaurus.io/en/users)! Many thanks for using Docusaurus!

**Comment by knowbody** [comment]
Will do now. Thank you for maintaining it!

**Comment by yangshun** [comment]
@knowbody We have released 1.3.1 which should fix the issue.

**Comment by knowbody** [comment]
Thank you
