### ISSUE TITLE
Getting invalid hooks error when loading markdown outside of docusaurs's root folder

### ISSUE THREAD

**Issue by alexandrebodin** [facebook/docusaurus#8091]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

I don't think it is a Docusaurus problem itself but I'm missing some knowledge on internals to debug my situation. 

When trying to import a file outside of the docusaurus folder in a monorepo like 

```md
/```mdx-code-block 
import Contributingfrom "@site/../CONTRIBUTING.md"

<Contributing />
/```
```

I'm getting the basic invalid hook error

![Screenshot 2022-09-13 at 10 41 58](https://user-images.githubusercontent.com/6065744/189855358-31474d07-6a41-4d6c-b43b-c4a3d0d34fc3.png)

It is coming from the `useMDXComponents` hooks apparently. 

So I figured it was a dependency conflict with my monorepo. I can confirm it is a dependency problem by removing the packages to test this. 

All my react/react-dom versions are identical, so it looks like it is a problem with react being loaded twice problem.

Since I'm only loading a plain markdown file, I don't understand why that would start conflicting. Do you have some pointers/recommendations to fix this? 

### Steps to reproduce

I couldn't pinpoint the exact problem sadly and need some insights about how docusaurus might be import things

### Expected behavior

No hooks error when loading md files outside of docusaurus folder

### Actual behavior

Getting the invalid hook error.

### Your environment

- Docusaurus version used:2.1.0
- Environment name and version (e.g. Chrome 89, Node.js 16.4): node 18
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): mac os monterey

### Self-service

- [x] I'd be willing to fix this bug myself.

**Comment by Josh-Cena** [comment]
Do you have a repo for me to clone? These kinds of errors are almost always dependency management faults, and without a repro it's hard to investigate.

**Comment by alexandrebodin** [comment]
Sure I push a branch on our monorepo so you can have a look :) 
https://github.com/strapi/strapi/tree/chore/transactions. I pinpointed it into the helper-plugin package in packages/core. But couldn't find any real problem with the dependencies in there

**Comment by alexandrebodin** [comment]
Hi @Josh-Cena Would you have any pointers for me? Maybe some specific webpack config overwrites to force an alias for react to always be the same path 🤔

**Comment by pdillon** [comment]
I ran into a similar issue, but not with mdx. Not sure if this would work for you, but adding this to plugins in docusaurus.config.js worked for me:
```js
 plugins: [
    () => ({
      name: 'resolve-react',
      configureWebpack() {
        return {
          resolve: {
            alias: {
              // assuming root node_modules is up from "./packages/<your-docusaurus>
              react: path.resolve('../../node_modules/react'), 
            },
          },
        };
      },
    }),
    // ... other plugins
```

**Comment by slorber** [comment]
yes 👍 good solution

Wonder if we shouldn't add this in core to ensure Docusaurus users would at most use a single version of React

Although the path may vary depending on single repo vs more complex monorepo setups, it should be possible to find a solution and ref the React version Docusaurus is actually using

**Comment by alexandrebodin** [comment]
The proposed webpack config worked like a charm. Thanks for the tip 👍 

I'm going to go ahead and close this issue now. Thank you for your help

**Comment by sedghi** [comment]
@pdillon You saved my day, thanks!

**Comment by mrjacobbloom** [comment]
It took me a while to track this issue down , I hope you don't mind if I dump a few search keywords:

```
docusaurus monorepo react component directory dependency
Invalid hook call. Hooks can only be called inside of the body of a function component.
Cannot read properties of null (reading 'useContext') (reading 'useState') (reading 'useEffect')
```
