### ISSUE TITLE
Unhandled promise & cryptic error in build-files-test.js

### ISSUE THREAD

**Issue by endiliey** [facebook/Docusaurus#810]
### Is this a bug report?

No. Technical debt ? Maybe test bug.

I think maybe the jest matcher is actually failing
`(node:411) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: expect(string).toContain(value)`

https://github.com/facebook/Docusaurus/blob/c0aa98bd553f630ee51d4bd81642e7f518042f34/lib/__tests__/build-files.test.js#L90-L105

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

### Environment

Latest master branch of Docusaurus (https://github.com/facebook/Docusaurus)

### Steps to Reproduce

After installation ...
```
yarn test build-files
````

### Expected Behavior

Test pass successfully without unhandled promise rejection error warning / cryptic console log

### Actual Behavior

<img width="692" alt="asdd" src="https://user-images.githubusercontent.com/17883920/41964042-9fac7194-7a2b-11e8-8367-578a566374b2.PNG">

<img width="703" alt="adss" src="https://user-images.githubusercontent.com/17883920/41964033-99f91842-7a2b-11e8-9e35-0fdc96c93daf.PNG">

You can also check https://circleci.com/gh/facebook/Docusaurus/2581

### Reproducible Demo
https://github.com/facebook/Docusaurus

**Comment by helloworld** [comment]
@endiliey looks like this bug was fixed – should this issue be closed?

**Comment by yangshun** [comment]
Thanks @helloworld. Closed via #839
