### ISSUE TITLE
Getting "[ERROR] Error: Docusaurus found broken links!" when adding link to download files without extension.

### ISSUE THREAD

**Issue by lsanchezalvarez** [facebook/docusaurus#8112]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

When having md document like the following:

```md
- [file2](./files/file2)
- [withoutext](../static/downloads/gateway/withoutext)
```

The built fails with the log below, this doesn't allow to include download of files without extensions.  In my case it is a configuration file requiring specific name.
If the file is located in the static folder, the project builds but then the link doesn't work.

[ERROR] Unable to build website for locale en.
[ERROR] Error: Docusaurus found broken links!

Please check the pages of your site in the list below, and make sure you don't reference any path that does not exist.
Note: it's possible to ignore broken links with the 'onBrokenLinks' Docusaurus configuration, and let the build pass.

Exhaustive list of all broken links found:

- On source page path = /docs/intro:
   -> linking to ./files/file2 (resolved as: /docs/files/file2)

    at throwError (C:\Users\BRILS\GitHub\broken-link-error\node_modules\@docusaurus\logger\lib\index.js:76:11)
    at handleBrokenLinks (C:\Users\BRILS\GitHub\broken-link-error\node_modules\@docusaurus\core\lib\server\brokenLinks.js:153:47)
    at async buildLocale (C:\Users\BRILS\GitHub\broken-link-error\node_modules\@docusaurus\core\lib\commands\build.js:177:5)
    at async tryToBuildLocale (C:\Users\BRILS\GitHub\broken-link-error\node_modules\@docusaurus\core\lib\commands\build.js:38:20)
    at async mapAsyncSequential (C:\Users\BRILS\GitHub\broken-link-error\node_modules\@docusaurus\utils\lib\jsUtils.js:34:24)
    at async Command.build (C:\Users\BRILS\GitHub\broken-link-error\node_modules\@docusaurus\core\lib\commands\build.js:73:21)
[INFO] Docusaurus version: 2.1.0
Node version: v16.17.0

### Reproducible demo

https://github.com/lsanchezalvarez/broken-link-error

### Steps to reproduce

git clone https://github.com/lsanchezalvarez/broken-link-error.git
Then build the project with npm run build -> It wont build
Then change   onBrokenLinks: 'throw', to onBrokenLinks: 'log', in configuration -> The project will build 
Then run the project and from the intro page try to download each of the files offered. The files without extension will fail

### Expected behavior

Being able to download a file without extension.

### Actual behavior

I cannot either build the project or download file without extension.

### Your environment

- Public source code:
- Public site URL:
- Docusaurus version used:
- Environment name and version (e.g. Chrome 89, Node.js 16.4):
- Operating system and version (e.g. Ubuntu 20.04.2 LTS):

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by Josh-Cena** [comment]
Hi, this is working as expected. Relative file paths are not asset links and won't bundle your files into the build output. In order to do that, you have to use `require` or add it to the static folder and link to it using its final URL. See: https://docusaurus.io/docs/static-assets#referencing-your-static-asset. For example, these should work:

```md
- [Using absolute URL](/downloads/gateway/withoutext)
- <a href={require("./files/file2")}>Using relative path and require</a>
```

**Comment by lsanchezalvarez** [comment]
Joshua,
I am afraid that none of your suggestions work. Have you tried it with my project?
Cheers,
Luis

**Comment by slorber** [comment]
It's really hard for me to understand what you are trying to do:
- where do you want to put the script
- why you talk about a script without extension
- what should be the final script URL the user downloads from

You are not really supposed to use relative paths to link to the static folder assets: those assets are always published alongside your site at the root baseUrl

If you want to prevent Docusaurus from processing your link with an asset-like extension, you can use the `pathname://` escape hatch

```
[Withext.txt](pathname:///downloads/gateway/withext.txt)
```

The pathname will be added to the link as provided, not modified by Docusaurus in both cases (with/without extension)
