### ISSUE TITLE
How to exlude heading levels from the side TOC

### ISSUE THREAD

**Issue by ArthurFlageul** [facebook/docusaurus#8113]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Description

I'm trying to find out if I can edit the heading levels shown in the side TOC. I have found the page about the [TOCinline object](https://docusaurus.io/docs/markdown-features/toc#customizing-table-of-contents-generation), but that's a different use case.

If there is a way to do this, could we add docs about it?

### Self-service

- [X] I'd be willing to address this documentation request myself.

**Comment by Josh-Cena** [comment]
You can change the maximum and minimum, but you can't exclude levels in between (which sounds like a very confusing thing to do in the first place). Docs are here: https://docusaurus.io/docs/next/markdown-features/toc#table-of-contents-heading-level

Backporting docs changes is very tedious, but I'm going to do it in this case.

**Comment by ArthurFlageul** [comment]
Argh, I can't believe I didn't find this. Maybe an admonition at the top of both pages would help to offer a redirection to ppl that want to noodle with the main toc but landed on the TOCinline page. Either way, thanks a lot 👍
