### ISSUE TITLE
DocCardList not rendering properly

### ISSUE THREAD

**Issue by zriyansh** [facebook/docusaurus#8129]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

![Screenshot 2022-09-25 at 13 04 28](https://user-images.githubusercontent.com/52788043/192133320-e549b202-190e-4aa9-9996-38d06ba62b87.png)

The screenshot should be enough.

Note, I am not using default Docs, but  '@docusaurus/plugin-content-docs'. Is this the reason behind it? 

### Steps to reproduce

NA

### Expected behavior

The cards should be rendered fully, they look restricted for some reason. 

P.s I am a uni student, making a student website for my uni using d2.

### Actual behavior

na

### Your environment

- Public source code: private
- Public site URL: vssut.pages.dev
- Docusaurus version used: latest
- Environment name and version (e.g. Chrome 89, Node.js 16.4): node v18.9.0
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): macOS 13

### Self-service

- [X] I'd be willing to fix this bug myself.

**Comment by AnteeHub** [comment]
I am using devtools of Chrome to find what happens.  And I notice that you use some customer stylesheet rules in the page.Some css styles may cause it not rendering properly.

```css
article .card{
    max-width: 224px;
}
```

After I cancel the style, DocCardList render as default.

![image](https://user-images.githubusercontent.com/55703989/192182430-27812b7b-bb29-488d-8796-97d55a0fa3b2.png)
<img width="459" alt="image" src="https://user-images.githubusercontent.com/55703989/192182435-ef1a3f58-3746-4815-8e9c-6083ae4fdd59.png">

**Comment by zriyansh** [comment]
yes this actually solves the problem, thanks @AnteeHub, also, have you played around with Live CLodeBlock? Because again that's not working in my local setup. Would really appreciate if someone somewhere did use it.

**Comment by AnteeHub** [comment]
> yes this actually solves the problem, thanks @AnteeHub, also, have you played around with Live CLodeBlock? Because again that's not working in my local setup. Would really appreciate if someone somewhere did use it.

Not yet.I've seen this on the official tutorial only :( .Maybe asking the others in discussion channel would help you to get the the answer.

**Comment by Josh-Cena** [comment]
Thanks @AnteeHub!
