### ISSUE TITLE
Navigation bar does not work on old browser, polyfill issue

### ISSUE THREAD

**Issue by roddc** [facebook/docusaurus#8134]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io.
- [x] I have read the console error message carefully (if applicable).

### Description

I am running my Doc site on an old browser(chrome 70), but I got an error `Uncaught ReferenceError: globalThis is not defined`
I have added `chrome >= 70` to the `browserslist`, but it doesn't seems to polyfill `globalThis`, I have tried to add `globalThis` to the index.html,  and I got another polyfill error  `TypeError: Object.fromEntries is not a function` .

I have followed this [issue](https://github.com/facebook/docusaurus/issues/7237) and this [issue](https://github.com/facebook/docusaurus/issues/4748), but it doesn't work.

How do I config babel correctly?

### Steps to reproduce

1.  npx create-docusaurus@latest test classic --typescript
2.  add `chrome >=70` to `browserslist` in package.json
3.  npm run build & npm run serve
4. open website on Chrome 70

### Expected behavior

Navigation bar should work

### Actual behavior

 `Uncaught ReferenceError: globalThis is not defined`
`TypeError: Object.fromEntries is not a function`

### Your environment

- Public source code:
- Public site URL:
- Docusaurus version used: 2.1.0
- Environment name and version (e.g. Chrome 89, Node.js 16.4): Chrome 70
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): Andriod 9

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by slorber** [comment]
browserslist does not polyfill missing browsers api, it only affects syntax. If you want to lower the browser support you'll have to bring your own polyfills. 

globalThis is widely supported today and we don't plan to remove it. 
https://caniuse.com/?search=globalThis

Please simply upgrade your browser because there are likely other things we won't support (like some new CSS features)
