### ISSUE TITLE
Slug with explicit .html extension breaks build

### ISSUE THREAD

**Issue by rwwilden** [facebook/docusaurus#8139]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

I'm migrating a blog from Jekyll. It is necessary for me to keep the exact same url structure because there's external refs to these posts. So I have a

    slug: a/b.html

in every blog post frontmatter. On build, this fails with the following error:

    [ERROR] Unable to build website for locale en.
    [ERROR] Error: Expected output HTML file to be found at /home/projects/kkviyzpmp.github/build/blog/a/b.html/index.html.

Running the site works fine, error only happens on build.

### Reproducible demo

https://stackblitz.com/edit/github-iuz7vq?file=blog/2021-08-26-welcome/index.md

### Steps to reproduce

1. Set a slug in a blog post frontmatter: `/a/b.html`
2. Run `yarn build`

### Expected behavior

Build should succeed, especially since running the site poses no problems.

### Actual behavior

Build fails with the following error message:

    [ERROR] Unable to build website for locale en.
    [ERROR] Error: Expected output HTML file to be found at /home/projects/kkviyzpmp.github/build/blog/a/b.html/index.html.

### Your environment

On stackblitz playground.

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by Josh-Cena** [comment]
Could you try setting `trailingSlash: false`?

**Comment by rwwilden** [comment]
> Could you try setting `trailingSlash: false`?

That doesn't seem to have any effect. I get the exact same error.

However, I think I have a work-around. If I define the slug as `/a/b`, the build succeeds and the resulting url becomes `/a/b.html`. I left `trailingSlash` as `undefined` in this case.

Not sure if this is still a bug now or expected docusaurus behavior :)

**Comment by rwwilden** [comment]
Ok, if I put the slugs as `/a/b` and set `trailingSlash: false`, I end up with urls like `/a/b.html`, which is exactly what I want.

I do think that it's a bit unclear from just looking at the slug to understand what the end result will be, but this now seems more like a feature than a bug :)

**Comment by Josh-Cena** [comment]
Setting `slug: /a/b.html` is a hacky but not obscure technique to ensure canonical URL, SEO, etc. all work the same as before. I'll need to experiment what happens with `trailingSlash: true`, but it shouldn't be too surprising.

**Comment by rwwilden** [comment]
Hm, getting broken links now that weren't there before. And I don't really understand the error message. What's the `23` and `24`?

    Exhaustive list of all broken links found:

    - On source page path = /programming/cloudfoundry/2019/02/26/net-service-broker-03:
       -> linking to 23 (resolved as: /programming/cloudfoundry/2019/02/26/23)
       -> linking to 24 (resolved as: /programming/cloudfoundry/2019/02/26/24)

        at throwError (/home/rwwilden/projects/rwwilden.gitlab.io/node_modules/@docusaurus/logger/lib/index.js:76:11)
        at handleBrokenLinks (/home/rwwilden/projects/rwwilden.gitlab.io/node_modules/@docusaurus/core/lib/server/brokenLinks.js:153:47)
        at async buildLocale (/home/rwwilden/projects/rwwilden.gitlab.io/node_modules/@docusaurus/core/lib/commands/build.js:177:5)
        at async tryToBuildLocale (/home/rwwilden/projects/rwwilden.gitlab.io/node_modules/@docusaurus/core/lib/commands/build.js:38:20)
        at async mapAsyncSequential (/home/rwwilden/projects/rwwilden.gitlab.io/node_modules/@docusaurus/utils/lib/jsUtils.js:34:24)
        at async Command.build (/home/rwwilden/projects/rwwilden.gitlab.io/node_modules/@docusaurus/core/lib/commands/build.js:73:21)

**Comment by slorber** [comment]
@rwwilden please when. you have a stacktrace, post it in its entirety. You removed the stacktrace from the error message, preventing us to immediately understand what's the issue, needing to reproduce it locally to understand the problem.

The stacktrace is:

```
[ERROR] Unable to build website for locale en.
[ERROR] Error: Expected output HTML file to be found at /Users/sebastienlorber/Desktop/projects/docusaurus/website/build/blog/docu2.1.html/index.html.
    at readOutputHTMLFile (/Users/sebastienlorber/Desktop/projects/docusaurus/packages/docusaurus-utils/lib/emitUtils.js:75:15)
    at async /Users/sebastienlorber/Desktop/projects/docusaurus/packages/docusaurus-plugin-content-blog/lib/feed.js:41:25
    at async Promise.all (index 0)
    at async generateBlogFeed (/Users/sebastienlorber/Desktop/projects/docusaurus/packages/docusaurus-plugin-content-blog/lib/feed.js:39:5)
    at async createBlogFeedFiles (/Users/sebastienlorber/Desktop/projects/docusaurus/packages/docusaurus-plugin-content-blog/lib/feed.js:85:18)
    at async Object.postBuild (/Users/sebastienlorber/Desktop/projects/docusaurus/packages/docusaurus-plugin-content-blog/lib/index.js:315:13)
    at async /Users/sebastienlorber/Desktop/projects/docusaurus/packages/docusaurus/lib/commands/build.js:171:9
    at async Promise.all (index 1)
    at async buildLocale (/Users/sebastienlorber/Desktop/projects/docusaurus/packages/docusaurus/lib/commands/build.js:167:5)
    at async tryToBuildLocale (/Users/sebastienlorber/Desktop/projects/docusaurus/packages/docusaurus/lib/commands/build.js:38:20)
```

This makes it clear for us maintainers that the problem is in our blog feed: we added a `readOutputHTMLFile()` method to create the blog RSS feed HTML content, but it's not reading from the correct output file location.

When an URL already ends with `.html`, such as `/x/y/z.html`, we output `/x/y/z.html` and not `/x/y/z/index.html` => `readOutputHTMLFile` apparently doesn't support this logic

**Comment by Pranav2612000** [comment]
Hey @slorber I'll like to work on this. I've read the disclaimer and don't expect the PR to be assigned but just wanted to give up a heads up to prevent some one else from working on the same task. 

( I'll try create a PR quickly, but if you don't see a message in the next 12 hours, feel free to pick this up )

**Comment by Pranav2612000** [comment]
I've been able to setup the project and am able to reproduce this issue. Will send a PR soon.

**Comment by Pranav2612000** [comment]
I've created a PR which fixes this. Feel free to take a look when you get time
