### ISSUE TITLE
Bring back the facebook social button on blog posts

### ISSUE THREAD

**Issue by JoelMarcey** [facebook/Docusaurus#814]
### Is this a bug report?

No. It was just removed.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

### Environment

Docusaurus 1.3.0

### Steps to Reproduce

Go to https://docusaurus.io/blog/2018/04/30/How-I-Converted-Profilo-To-Docusaurus

### Expected Behavior

The button would be there.

![screenshot 2018-06-29 13 39 45](https://user-images.githubusercontent.com/3757713/42113912-ef342a00-7ba1-11e8-8c41-6eed4b3ea3c2.png)

### Actual Behavior

No button.

### Reproducible Demo

N/A

**Comment by JoelMarcey** [comment]
Not sure if it was removed with this: https://github.com/facebook/Docusaurus/pull/673, but that seems like something that could be related.

**Comment by endiliey** [comment]
It was still there on #673
It was down after #757

It should be
```js
className="fb-like"
```

According to https://developers.facebook.com/docs/plugins/like-button/

Instead of
```js
className="fbLike"
```
