### ISSUE TITLE
Watcher failure in 1.3.1

### ISSUE THREAD

**Issue by chenglou** [facebook/Docusaurus#818]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

### Environment

Docusaurus 1.3.1, macOS High Sierra, node 8.2.0, yarn 1.5.1

### Steps to Reproduce

(Write your steps here:)

1. New docusaurus project
2. have a non-trivial `baseUrl` (e.g. not a `/`) in `siteConfig.js`
3. Start the watcher

### Expected Behavior

Loads `localhost:3000/theBaseUrl`.

### Actual Behavior

Loads `localhost:3000`. This throws in the terminal, so newcomers might not understand to append /baseUrl to `localhost` manually.

### Reproducible Demo

Clone https://github.com/reasonml/reason-react, cd into `website` and `yarn upgrade docusaurus@1.3.1 && yarn start`

**This is new in docusaurus 1.3.1**

**Comment by endiliey** [comment]
Sorry, this is because the routing is stricter now in development server to use baseUrl correctly. 
I'll send a fix for this.
