### ISSUE TITLE
Module parse failed: Unexpected token (9:22)

### ISSUE THREAD

**Issue by coding-to-music** [facebook/docusaurus#8183]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

Hello
Here is my repo:

https://github.com/coding-to-music/docusaurus-classic-site

First do `npm install`

Then,

When I do `npm run build`

I get these messages:

```

> docusaurus-classic-site@0.0.0 build
> docusaurus build

[INFO] [en] Creating an optimized production build...

✖ Client
  Compiled with some errors in 43.82s

● Server █████████████████████████ building (65%) 1/1 entries 2345/2345 dependencies 763/763 modules 0 active


Module parse failed: Unexpected token (9:22)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|
| // Inspired by https://github.com/you-dont-need/You-Dont-Need-Lodash-Underscore#_sortby-and-_orderby
> export function sortBy<T>(
|   array: T[],
|   getter: (item: T) => string | number | boolean,
[ERROR] Client bundle compiled with errors therefore further build is impossible.
```

For the message: `Module parse failed: Unexpected token (9:22)`

I have no idea what file or code it is objecting to, it does not show what it is processing.

Is this lack of clarity from Webpack, or Docusaurus?

Also, for the message `You may need an appropriate loader to handle this file type`, is that related or a different error?

### Reproducible demo

https://github.com/coding-to-music/docusaurus-classic-site

### Steps to reproduce

Here is my repo:

https://github.com/coding-to-music/docusaurus-classic-site

First do `npm install`

Then,

then `npm run build --verbose`

### Expected behavior

Should do a build without errors

### Actual behavior

```

> docusaurus-classic-site@0.0.0 build
> docusaurus build

[INFO] [en] Creating an optimized production build...

✖ Client
  Compiled with some errors in 43.82s

● Server █████████████████████████ building (65%) 1/1 entries 2345/2345 dependencies 763/763 modules 0 active


Module parse failed: Unexpected token (9:22)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|
| // Inspired by https://github.com/you-dont-need/You-Dont-Need-Lodash-Underscore#_sortby-and-_orderby
> export function sortBy<T>(
|   array: T[],
|   getter: (item: T) => string | number | boolean,
[ERROR] Client bundle compiled with errors therefore further build is impossible.
```

### Your environment

- Public source code:
- Public site URL:
- Docusaurus version used:
- Environment name and version (e.g. Chrome 89, Node.js 16.4):
- Operating system and version (e.g. Ubuntu 20.04.2 LTS):
Ubuntu 20.04
npm info using npm@8.17.0
npm info using node@v16.14.2

### Self-service

- [X] I'd be willing to fix this bug myself.

**Comment by slorber** [comment]
Hey

Your repo is not brand new, so when did it start failing and what did you do exactly that triggered the failure? Have you tried reverting your changes one by one until it works again?

I see a huge commit where you steal a lot of our showcase code here and then it seems to fail deploying:
https://github.com/coding-to-music/docusaurus-classic-site/commit/c6e98bf881881954e341d58ec085326d1ce2e0eb#diff-68da1827297d0d40715290e46087052064de853a608bfa2a939ce2c31b16f350

Maybe this file should have an extension? 🤷‍♂️ Webpack doesn't understand requiring/importing files without extensions

<img width="708" alt="CleanShot 2022-10-07 at 12 01 48@2x" src="https://user-images.githubusercontent.com/749374/194528513-d761ad26-1704-438b-beff-c5fbb1141e92.png">

**Comment by coding-to-music** [comment]
Yes, it was building the showcase, then I attempted to edit the huge number of entries down to only a few, so I must have left a typo in that commit. I will work on it again - probably can be closed as not-a-bug it's operator-error lol. I can keep you posted on what I find if I do figure it out...

**Comment by coding-to-music** [comment]
Will update if I find what it was, thanks
