### ISSUE TITLE
Logo blinks too much when navigating through pages

### ISSUE THREAD

**Issue by anaclumos** [facebook/docusaurus#8188]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

The Logo blinks when navigating through different pages.

### Reproducible demo

docusaurus.io, cho.sh

### Steps to reproduce

Navigate through many links.

### Expected behavior

The logo should stay static.

### Actual behavior

The logo blinks quite often.

### Self-service

- [X] I'd be willing to fix this bug myself.

**Comment by slorber** [comment]
Agree 👍 

This is a known issue related to layout unmount/remount, already reported here: https://github.com/facebook/docusaurus/issues/4008

Duplicate and tracked here: https://github.com/facebook/docusaurus/issues/2891

A good workaround you can use today:
- define an explicit logo width/height
- add logo HTTP caching so that it doesn't have to be reloaded when navigating

**Comment by slorber** [comment]
This way:
https://github.com/facebook/docusaurus/blob/main/website/docusaurus.config.ts#L551

![CleanShot 2024-02-19 at 15 04 40](https://github.com/facebook/docusaurus/assets/749374/83a6e9b3-80e9-4d35-a744-89ad32e2def5)

**Comment by JasonFengGit** [comment]
Hi @slorber, adding specification of width and height could not resolve my issue here: https://github.com/electron/website/issues/539

Could you please advise me on how to add logo http caching? Thank you so much!

**Comment by slorber** [comment]
@JasonFengGit I don't believe it doesn't work. Show me the code of your attempt + a live deployment preview of it.

**Comment by JasonFengGit** [comment]
Hi, thanks for replying! I found a different work around by adding a width specification in custom css. https://github.com/electron/website/pull/543/files

**Comment by slorber** [comment]
That also works, but I believe adding a width/height to the image through config still works until proven otherwise
