### ISSUE TITLE
The announcementBar cannot be translated

### ISSUE THREAD

**Issue by Selflocking** [facebook/docusaurus#8196]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io.
- [x] I have read the console error message carefully (if applicable).

### Description

Run `yarn write-translations`, announcementBar does not appear on `i18n/en/`, so currently the announcementBar cannot be translated

### Reproducible demo

https://docusaurus.io/zh-CN/

### Steps to reproduce

yarn write-translations

### Expected behavior

the announcementBar can be translated

### Actual behavior

announcementBar does not appear on `i18n/en/`

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by Josh-Cena** [comment]
Duplicate of https://github.com/facebook/docusaurus/issues/4542. This is so far untranslatable because we allow raw HTML so if you outsource your translations to an external workflow you risk XSS. We need to see how to harden the security so only pure decorative markup is tolerated.
