### ISSUE TITLE
Link beside custom component does not render

### ISSUE THREAD

**Issue by aandis** [facebook/docusaurus#8201]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

A link beside a custom component isn't rendering correctly. Example - 

```javascript
import React from 'react';

export default function TestComp(props) {
  return <span>{props.children}</span>;
}
```

```md
<TestComp>This does not work!</TestComp> [This link does not work](example.com)
```

renders
![pic](https://user-images.githubusercontent.com/4983347/195013252-0bb53de0-14b3-4c89-b94c-728ddd6547b9.png)

https://stackblitz.com/edit/github-2yziua?file=docs/intro.md

### Reproducible demo

https://stackblitz.com/edit/github-2yziua?file=docs/intro.md

### Steps to reproduce

1. Add a custom component.
2. Render the component and write a link beside it

### Expected behavior

Link should render correctly

### Actual behavior

Link does not render correctly

### Your environment

- Public source code: https://stackblitz.com/edit/github-2yziua?file=docs%2Fintro.md,src%2Fcomponents%2FTestComp.jsx
- Public site URL: https://stackblitz.com/edit/github-2yziua?file=docs%2Fintro.md,src%2Fcomponents%2FTestComp.jsx
- Docusaurus version used: `2.1.0`
- Environment name and version (e.g. Chrome 89, Node.js 16.4): Chrome Version 104.0.5112.79
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): Ubuntu 20.04 LTS

### Self-service

- [X] I'd be willing to fix this bug myself.

**Comment by Josh-Cena** [comment]
Please see https://docusaurus.io/docs/markdown-features/react#markdown-and-jsx-interoperability, first example

**Comment by ChristianMurphy** [comment]
Also note the MDX 2 changes/improves markdown and JSX interop https://mdxjs.com/blog/v2/#improvements-to-the-mdx-format.
This syntax would/will be supported with https://github.com/facebook/docusaurus/issues/4029
