### ISSUE TITLE
docusaurus-plugin-client-redirects does not keep the query string.

### ISSUE THREAD

**Issue by F4r3n** [facebook/docusaurus#8206]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [ ] I have tried the `npm run clear` or `yarn clear` command.
- [ ] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io.
- [ ] I have read the console error message carefully (if applicable).

### Description

I am using docusaurus-plugin-client-redirects
https://github.com/facebook/docusaurus/tree/main/packages/docusaurus-plugin-client-redirects
The plugin creates new pages with this content:
```html
....
  <script>
    window.location.href = '<%= it.toUrl %>'
  </script>
```

But the new page does not receive the search params.
I would like something like that:
```html
....
  <script>
    window.location.href = '<%= it.toUrl %>' + window.location.search
  </script>
```

### Steps to reproduce

1. Use the plugin docusaurus-plugin-client-redirects
2. Go to a page with search params
3. The redirected page does not receive the search params

### Expected behavior

The new redirected page receive the search query.

### Actual behavior

The new redirected page does not receive the search query

### Your environment

- Docusaurus version used: 2.1.0

### Self-service

- [X] I'd be willing to fix this bug myself.

**Comment by tavarescarolina** [comment]
Hello, can I try to fix it?

**Comment by slorber** [comment]
yes @tavarescarolina , you don't need to claim it, just open a PR. First PR opened and the issue is for you
