### ISSUE TITLE
I cannot change docusaurus logo favicon.ico

### ISSUE THREAD

**Issue by AviandraPutri-Jubelio** [facebook/docusaurus#8211]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Description

Hi, please help,I don't understand why my logo didn't change to the new one after running "npm run build."

![image](https://user-images.githubusercontent.com/111033787/195825825-a12ba71c-b589-4edc-a1e7-e1ffc1a7e064.png)

![image](https://user-images.githubusercontent.com/111033787/195825896-959fe949-825e-4292-b6d4-6eda7cd731ec.png)

Even after I changed it to my company's logo, nothing has changed.

![image](https://user-images.githubusercontent.com/111033787/195826055-23ff9695-5e4c-497b-920c-4327a4fa694d.png)

### Self-service

- [ ] I'd be willing to address this documentation request myself.

**Comment by Dannyholt** [comment]
The image in your screenshot is the nav logo, not the favicon. To change the nav logo, see the link below.

https://docusaurus.io/docs/api/themes/configuration#navbar-logo
