### ISSUE TITLE
index.md doesn't work with other languages localy

### ISSUE THREAD

**Issue by NekkiNeks** [facebook/docusaurus#8218]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

I'm trying to create a simple directory/subdirectory/index.md structure, and its works if the name of folders is in english, but if im trying the same with other language (Russian) it doesn't work. The interesting part is that its working on stackblitz but doesn't work locally, even if i'am literally downloading the same project from stackblitz and running it. You can try this too i you download project from reproducible demo.

### Reproducible demo

https://stackblitz.com/edit/github-7bd7rs?file=docs/Директория/Поддиректория/index.md

### Steps to reproduce

- download project from stackblitz
- run npm install
- run npm start
- compare sidebar structure for two directories

### Expected behavior

Expected sidebar structure:

English: 
directory/Name of subdir

Russian:
Директория/название

### Actual behavior

Actual sidebar structure:

English: 
directory/Name of subdir

Russian:
Директория/поддиректория/название

### Your environment

- Public source code: https://stackblitz.com/edit/github-7bd7rs
- Public site URL: none
- Docusaurus version used: 2.1.0
- Environment name and version (e.g. Chrome 89, Node.js 16.4): node 16.16
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): Windows 10

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by Josh-Cena** [comment]
It's stlll actual because it's not published yet. Do note that it was closed a few days ago and there had been no release since.
