### ISSUE TITLE
Phrase emphasis is not working

### ISSUE THREAD

**Issue by nareshbhatia** [facebook/Docusaurus#822]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

### Environment

Docusaurus version 1.3.1

### Steps to Reproduce

Just add phrase emphasis in any document. For example:

    Some of these words *are emphasized*.
    Some of these words _are emphasized also_.

### Expected Behavior

Emphasized words are italicized.

### Actual Behavior

Emphasized words are not italicized. I can see that the emphasized words are enclosed in `<em>` tags, however styling for these tags is reset in [main.css](https://github.com/facebook/Docusaurus/blob/master/lib/static/css/main.css#L34) and never set to italic again.

### Reproducible Demo

Try using emphasized phrases in the default generated site.

**Comment by jamato-pfm** [comment]
I'm having the same issue across all documentation.

**Comment by jamato-pfm** [comment]
Same here.

**Comment by prakhar-goel** [comment]
Same here.

**Comment by yangshun** [comment]
@prakhar-goel Please provide steps for reproducing this issue and we can look into it 😄
