### ISSUE TITLE
404 on .html/ URLs

### ISSUE THREAD

**Issue by Gownta** [facebook/docusaurus#8228]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [ ] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

Adding `.html` to docusaurus webpage URLs works, but adding `.html/` 404s. Easily reproducible.

e.g. https://docusaurus.io/docs.html v https://docusaurus.io/docs.html/

### Steps to reproduce

1. Go to a public Docusaurus page, such as https://docusaurus.io/docs
2. Add .html to the URL, like https://docusaurus.io/docs.html, see that it works
3. Add .html/ to the URL, like https://docusaurus.io/docs.html/, see that it results in "Page Not Found"

These steps also repro with new.docusaurus.io

### Expected behavior

Best case expected behavior: .html/ succeeds, just like .html.
Acceptable behavior: .html fails, just like .html/.

This issue was discovered because .html-suffixed links (which work) were being redirected to .html/-suffixed links (which fail) once `trailingSlash: true` is added to docusaurus.config.js. Some people link to docusaurus using .html (ahh, [Hyrum's Law](https://www.hyrumslaw.com/)), which is why I think the fix should be "allow .html/ links to succeed". Note: I was not able to reproduce "links with .html get redirected to .html/ once trailingSlash:true is added to docusaurus.config.js" on new.docusaurus.io; however, I am able to reproduce this locally, Meta-internal.

### Actual behavior

![Screen Shot 2022-10-19 at 11 08 59 AM](https://user-images.githubusercontent.com/1771157/196770794-f8845e54-6149-48ed-82d4-e84ca007c9fc.png)

### Your environment

The main repro is on Docusaurus's own website: docusaurus.io

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by slorber** [comment]
This is a hosting concern.

The responsibility of Docusaurus is only to emit `build/myPath.html` or `build/myPath/index.html`. 

Not it is your responsibility to configure your host to serve this static deployment appropriately according to your need, and we can't do anything about it.

If the Docusaurus website answers 404, it is because we unchecked this Netlify hosting configuration (on purpose, we don't care about answering 200 in our case and it can lead to other issues, see deployment and trailing slash docs):

![CleanShot 2022-10-20 at 15 29 16@2x](https://user-images.githubusercontent.com/749374/196962407-f3f45f34-9389-4517-a27e-d4a8ac384b46.png)

Now it is definitively possible to support `.html` extensions without a 404 on a multitude of hosts, but it is your responsibily

**Comment by slorber** [comment]
https://docusaurus.io/docs/deployment#deploying-to-netlify

<img width="994" alt="CleanShot 2022-10-20 at 15 33 39@2x" src="https://user-images.githubusercontent.com/749374/196962986-172f6171-530a-491d-9862-c9246c2b97d0.png">

**Comment by slorber** [comment]
Note that we deploy Docusaurus deploy preview with `trailingSlash: isDeployPreview` (to dogfood both settings) so you can test the different behavior on any deploy preview easily vs prod site:

```bash
https://deploy-preview-8210--docusaurus-2.netlify.app/docs
https://deploy-preview-8210--docusaurus-2.netlify.app/docs.html
https://deploy-preview-8210--docusaurus-2.netlify.app/docs/
https://deploy-preview-8210--docusaurus-2.netlify.app/docs/index.html
https://deploy-preview-8210--docusaurus-2.netlify.app/docs.html/
```

---

You'll find more details in this repo: https://github.com/slorber/trailing-slash-guide

The TLDR is: each host provider is different, nothing is standardized to host a static deployment, and you should figure out a config that works for you with your host provider. Docusaurus trying to please most hosting providers at the same time is only a best effort but it's impossible to support all of them by default out of the box, particularly on such edge cases.

If your internal Docusaurus site uses something else than Netlify, then it can't be compared to the behavior of our own website. The behavior will likely always be a little different on edge-cases from one host to another. It is also not comparable with `docusaurus serve` which is a tiny node server ([serve](https://www.npmjs.com/package/serve)) we provide for convenience, and again it may behave differently compared to Netlify/Vercel/GitHub Pages/Apache/Nginx/internal tool.
