### ISSUE TITLE
Admonitions with backticks elicit <mdxAdmonitionTitle /> warnings

### ISSUE THREAD

**Issue by SheetJSDev** [facebook/docusaurus#8233]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

An admonition with backticks generates a warning e.g.

```
:::info Something `with` backticks

will elicit a warning

:::
```

Console warning:

```
Warning: The tag <mdxAdmonitionTitle> is unrecognized in this browser. If you meant to render a React component, start its name with an uppercase letter.
    at mdxAdmonitionTitle
    at eval (webpack-internal:///./node_modules/@mdx-js/react/dist/esm.js:154:30)
    at div
    at div
...
```

It does display what you would expect:

<img width="274" alt="docusaurus-backticks" src="https://user-images.githubusercontent.com/6070939/197080159-64bdf709-d7da-4033-b96f-d63aaf95ddd1.png">

### Steps to reproduce

Create a blank site (or use docusaurus.new)

Add the following to `/docs/intro.md`:

```
:::info Something `with` backticks

will elicit a warning

:::
```

Load the intro page

### Expected behavior

No warning

### Actual behavior

warning (see description)

### Your environment

Affects docusaurus.new CSB site on 2022-10-20 19:52 EDT

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by Djunnni** [comment]
can i try this?

**Comment by SheetJSDev** [comment]
```bash
cd /tmp
npx create-docusaurus@latest my-website classic
## create-docusaurus@2.1.0
cd my-website
cat <<EOF >> docs/intro.md

:::info Something \`with\` backticks

will elicit a warning

:::
EOF
npm start
```

Now open the web browser and navigate to http://localhost:3000/docs/intro .  Inspecting the console reveals the warning:

<img width="1295" alt="docusaurus8233warning" src="https://user-images.githubusercontent.com/6070939/197404161-cfb1269b-ec84-4278-b2ef-c0025a4974ea.png">

(note: this warning does not show up when building the production site)

package.json uses the following dependencies:

```json
{
  "@docusaurus/core": "2.1.0",
  "@docusaurus/preset-classic": "2.1.0",
  "@mdx-js/react": "^1.6.22",
  "clsx": "^1.2.1",
  "prism-react-renderer": "^1.3.5",
  "react": "^17.0.2",
  "react-dom": "^17.0.2"
}
```

**Comment by Djunnni** [comment]
thanks. i can try!

**Comment by Djunnni** [comment]
https://github.com/facebook/docusaurus/blob/e41133245ca4e6cee390da74ccfe305ccb2ddb25/packages/docusaurus-mdx-loader/src/remark/admonitions/index.ts#L141-L159
https://github.com/facebook/docusaurus/pull/7152#issuecomment-1145779682
 Temporary workaround, because it's complex in MDX v1 to emit.

maybe they will migrate mdx 2.0 then update this later
