### ISSUE TITLE
Crowdin Translation Download messes front matter

### ISSUE THREAD

**Issue by YazzyYaz** [facebook/docusaurus#8238]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io.
- [ ] I have read the console error message carefully (if applicable).

### Description

I am currently integrating Crowdin translations into my project's docs.

After running the following:
```sh
yarn run write-translations
yarn run crowdin upload
yarn run crowdin download
```

The translated sidebar_labels have a different formatting than the original docs.

For example, we expect the markdown format to be:
```md
---
sidebar_label : Aperçu
---
```
in the translated docs but instead we get:

```md
- - -
sidebar_label : Aperçu
- - -
```
Which messes up the rendering as can be seen here:
<img width="1134" alt="Screen Shot 2022-10-24 at 2 14 21 PM" src="https://user-images.githubusercontent.com/9094204/197523883-15af9f6b-f884-43a5-aeb7-54e79c43d8f1.png">

### Steps to reproduce

1. Follow the guidelines here: https://docusaurus.io/docs/i18n/crowdin
2. After generating translations, the sidebar_label surrounding dashes add an extra space between them, messing up the rendering.

### Expected behavior

```md
---
sidebar_label : Aperçu
---
```

### Actual behavior

```md
- - -
sidebar_label : Aperçu
- - -
```

### Your environment

- Public source code: https://github.com/celestiaorg/docs
- Public site URL: docs.celestia.org

It is not live, we are testing it on a branch with no code modifications, just testing the crowdin integration.

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by forresst** [comment]
I'm not sure of my answer, but already in the original version, you have to remove the space before `:` in the frontmatter

```diff
- sidebar_label : Overview
+ sidebar_label: Overview
```

In Crowdin, do the translation without putting the space before `:` : 
```txt
sidebar_label: Aperçu
``` 

From my experience, I think this will solve the problem

**Comment by Josh-Cena** [comment]
This is definitely not a Docusaurus issue since we aren't involved in the workflow. Please contact Crowdin for support—I'm curious to hear their feedback as well.

**Comment by slorber** [comment]
There are many little annoying issues on Crowdin side that you should become used to. Sometimes a translator add a bad `<xyz>` somewhere. Sometimes they have markdown parser issues. Sometimes weird things happens and you can often fix them by deleting (or temporary renaming) and then reuploading the problematic file.

Agree it's out of the Docusaurus scope, unfortunately, we can't improve this external SaaS

**Comment by YazzyYaz** [comment]
@Josh-Cena @slorber I was able to fix the issue with a script:
```sh
#!/bin/bash
cd i18n
find . -type f -name "*.md" -exec sed -i 's/- - -/---/g' {} +
find . -type f -name "*.mdx" -exec sed -i 's/- - -/---/g' {} +
```

And then call this script after you run `yarn crowdin:sync` and before you call the `yarn build` command. Resolved the issue.
