### ISSUE TITLE
search input placeholder

### ISSUE THREAD

**Issue by ggalli** [facebook/Docusaurus#824]
Is there a way to change the placeholder created by algolia input search?

**Comment by JoelMarcey** [comment]
I haven't tried it yet, but you might be able to add in `algoliaOptions`, something like:

```
const siteConfig = {
  ...
  algolia: {
    apiKey: 'my-api-key',
    indexName: 'my-index-name',
    algoliaOptions: {"placeholder:New text here"}
  },
  ...
};
```

Can you let us know if that works?

**Comment by ggalli** [comment]
it didn't work :(

**Comment by endiliey** [comment]
Seems to me that the placeholder is hardcoded in algolia docsearch

https://github.com/algolia/docsearch/blob/caad961c809e561f39efca8acdb0cfe5f0438ab9/src/lib/templates.js#L89

You can open a feature request issue in https://github.com/algolia/docsearch if you want. And it'll be available in Docusaurus. I'm closing this issue
