### ISSUE TITLE
License Inconsistency in project dependency

### ISSUE THREAD

**Issue by NickJLange** [facebook/docusaurus#8247]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

When running a Docusaurus@latest clean install, there is a dependency on fast-folder-size in npm whose license has a clause prohibiting anyone using the module residing / financing a country engaging in wars against other countries. This is inconsistent with the MIT license for Docusaurus and I suspect many using Docusaurus. Can the license in Docusaurus be harmonized or the code refactored to remove the dependency?

https://github.com/facebook/docusaurus/blob/main/yarn.lock
https://raw.githubusercontent.com/simoneb/fast-folder-size/master/LICENSE.md

Thank you
Nick

### Steps to reproduce

1. npm install docusaurus@latest

### Expected behavior

fast-folder-size is downloaded as a dependency

### Actual behavior

fast-folder-size is downloaded as a dependency

### Your environment

- Public source code: Non-Public
- Public site URL: N/A
- Docusaurus version used: @latest
- Environment name and version (e.g. Chrome 89, Node.js 16.4): Node.js 16.X
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): Linux @rhel7.9

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by Josh-Cena** [comment]
Hi! `fast-folder-size` is depended on by `tree-node-cli`, which is a dev-only package, so it shouldn't have user-facing impacts. (If you run `npm install`, you shouldn't install it at all.) Still, that license looks incredibly naïve and unenforcable—@slorber Do you think you could remove it from `tree-node-cli`?

**Comment by slorber** [comment]
This is annoying 😅 Opened an issue here: https://github.com/yangshun/tree-node-cli/issues/34

Note that @yangshun and I are maintaining tree-node-cli so we can update it too instead of simply removing it. I think it's a valuable tool for test snapshots and would like to use it more in the future.

**Comment by simoneb** [comment]
> that license looks incredibly naïve and unenforcable

I am the creator of that license and since I am also the author of that code, I'm free to decide how it's licensed. As for enforceablity, I can concur it's not easily enforced, but I'm glad somebody is noticing and if they can't be sure that the sub-products that code is used in cannot enforce the license themselves, they should rather not use it.
