### ISSUE TITLE
Add Syntax Preprocessors Layer

### ISSUE THREAD

**Issue by anaclumos** [facebook/docusaurus#8251]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Motivation

Would it be possible to add specific rules of nonstandard markdown syntax to be preprocessed when built?

## But Why would we?

This can allow much more diverse documentations that would've been previously impossible due to the technical limitations of Docusaurus. Examples include:

### 1. `{{안녕^hello}}`

This is a nonstandard md syntax used in the Eastern hemisphere for denoting pronunciations and side notes. This md syntax will convert to the following HTML:

```html
<ruby>안녕<rp>(</rp><rt>hello</rt><rp>)</rp></ruby>
```

which will print as

<ruby>안녕<rp>(</rp><rt>hello</rt><rp>)</rp></ruby>

### 2. `[[wikilinks]]`

This is a nonstandard md syntax. We can add a preprocessor that converts wikilinks to MD links when building.

### 3. `[alt](image "figcaption")`

This is also a nonstandard md syntax. When building, we can also add a preprocessor to convert them into HTML Figure-Figcaption.

```html
<figure>
  <img src="some-src" alt="alt" />
  <figcaption>figcaption value</figcaption>
</figure>
```

### Self-service

- [X] I'd be willing to do some initial work on this proposal myself.

**Comment by Josh-Cena** [comment]
Hi! These are already triviallly implementable with [custom Remark plugins](https://docusaurus.io/docs/2.0.1/markdown-features/plugins#creating-new-rehyperemark-plugins). You just need to write the parser and transformer yourself. Docusaurus is not going to implement custom Markdown syntax unless there proves to be great demand—which there doesn't seem to be. Please file this as a [Canny request](https://docusaurus.canny.io/) instead, detailing what you want—do you want a custom preprocessor API? (In which case we already have the Remark plugin API) Do you want a specific one of these syntaxes?

**Comment by slorber** [comment]
I'll try to implement wikilinks and backlinking someday but not sure it will go in Docusaurus core.

---

For image figcaptions, there's likely already existing remark plugins you could use.

For example https://github.com/Microflash/remark-figure-caption

It's not exactly what you want but may be good enough?

Eventually, you can add a "figure" MDX component to parse the image URL caption directly in the client component
