### ISSUE TITLE
remark-math && rehype-katex installation command wrong

### ISSUE THREAD

**Issue by Niko030303** [facebook/docusaurus#8252]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Description

When I use this command to install package, it pointed out "Unknown command: "installation""
```shell
npm installation --save markath@3 rehype-katex@5 hast-util-is-element@1.1.0
```

![image](https://user-images.githubusercontent.com/82041918/198228425-41cef171-f4d6-42d6-9e3f-9fff009d3f19.png)

### Self-service

- [X] I'd be willing to address this documentation request myself.

**Comment by slorber** [comment]
Thanks, it was a translation mistake on Crowdin

I marked as "hidden strings" all "npm install" instructions that should never be translated

**Comment by slorber** [comment]
https://docusaurus.io/zh-CN/docs/markdown-features/math-equations#configuration

Now fixed:

<img width="989" alt="CleanShot 2022-10-29 at 11 44 04@2x" src="https://user-images.githubusercontent.com/749374/198824800-233cf196-e3df-485a-9353-8b997c191c89.png">
