### ISSUE TITLE
Enhancing sitemap to help DocSearch scraping alternate links (i18n)

### ISSUE THREAD

**Issue by s-pace** [facebook/Docusaurus#826]
### Is this a bug report?

Feature Request: Help [algolia DocSearch](https://community.algolia.com/docsearch/) to better handle Docusaurus user's sitemaps.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes
### Environment

Latest version
### Steps to Reproduce

Access the sitemap of any website using the latest version of docusaurus:
<main_url>/sitemap.xml
### Expected Behavior

We would need:
- the sitemap's type to be a `sitemapindex` in order to use `alternate` URLs (from other languages) correctly.
- The sitemap to link to URLs without trailing `.html` since you want us to only scrap (and redirect to) URLs without it.

### Actual Behavior

Access any sitemap : <main_url>/sitemap.xml
Example for Docusaurus: https://docusaurus.io/sitemap.xml

The current [sitemap's type is `urlset`](https://www.sitemaps.org/protocol.html#mainContent). Every link has a trailing `.html`

cc @endiliey 
Let us know if you have any feedback.

Thanks

**Comment by endiliey** [comment]
@s-pace 
> the sitemap's type to be a sitemapindex in order to use alternate URLs (from other languages) correctly.
Do you have an example `sitemapindex` ? We use https://github.com/ekalinin/sitemap.js to generate our sitemap so I'll look into the sitemapindex one.

> The sitemap to link to URLs without trailing .html since you want us to only scrap (and redirect to) URLs without it.
We have a config for Docusaurus user to use `.html` or no `.html`. I will fix the sitemap to be consistent on the url.

**Comment by s-pace** [comment]
@endiliey Thank you for jumping on it so quickly.

> Do you have an example sitemapindex ? We use https://github.com/ekalinin/sitemap.js to generate our sitemap so I'll look into the sitemapindex one.

`sitemapindex` is set base on [this scrapy's definition](https://github.com/scrapy/scrapy/blob/master/scrapy/utils/sitemap.py#L20). Could be set by adding the correct tag.

> We have a config for Docusaurus user to use .html or no .html. I will fix the sitemap to be consistent on the url.

Makes sense. Both URLs are always available (having a 200 HTTP status). Example:

https://docusaurus.io/docs/es-ES/1.1.5/site-creation
https://docusaurus.io/docs/es-ES/1.1.5/site-creation.html

Could it be possible to make only one of them available?

**Comment by endiliey** [comment]
> sitemapindex is set base on this scrapy's definition. Could be set by adding the correct tag.
I'll look into this one.

> Makes sense. Both URLs are always available (having a 200 HTTP status). Example:
https://docusaurus.io/docs/es-ES/1.1.5/site-creation
https://docusaurus.io/docs/es-ES/1.1.5/site-creation.html
Could it be possible to make only one of them available?

I'm afraid that we'll have to preserve both urls for backward compatibility and I don't want to break someone's website 😢. Do you have any other suggestion ?

**Comment by s-pace** [comment]
Thanks for looking into this one. Let us know your feedback.

> I'm afraid that we'll have to preserve both urls for backward compatibility and I don't want to break someone's website 😢. Do you have any other suggestion ?

We will keep to put `".html$"` as a `stop_urls` then.

Just for sharing: you might want [to use canonical urls](https://support.google.com/webmasters/answer/139066?hl=en).

**Comment by endiliey** [comment]
@s-pace i'm thinking to put 301 redirect on the `.html` version to still preserve the backward compatibility

Wdyt ?

Cc @yangshun

**Comment by s-pace** [comment]
> @s-pace i'm thinking to put 301 redirect on the .html version to still preserve the backward compatibility

Should be fine indeed

**Comment by endiliey** [comment]
Hi @s-pace,

According to  google's recommended way to indicate alternate language (https://support.google.com/webmasters/answer/189077?hl=en&visit_id=1-636663918916415691-3337098161&rd=1)

The sitemap should be in the form of
```
<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"
  xmlns:xhtml="http://www.w3.org/1999/xhtml">
  <url>
    <loc>http://www.example.com/english/page.html</loc>
    <xhtml:link 
               rel="alternate"
               hreflang="de"
               href="http://www.example.com/deutsch/page.html"/>
    <xhtml:link 
               rel="alternate"
               hreflang="de-ch"
               href="http://www.example.com/schweiz-deutsch/page.html"/>
    <xhtml:link 
               rel="alternate"
               hreflang="en"
               href="http://www.example.com/english/page.html"/>
  </url>
  <url>
    <loc>http://www.example.com/deutsch/page.html</loc>
    <xhtml:link 
               rel="alternate"
               hreflang="de"
               href="http://www.example.com/deutsch/page.html"/>
    <xhtml:link 
               rel="alternate"
               hreflang="de-ch"
               href="http://www.example.com/schweiz-deutsch/page.html"/>
    <xhtml:link 
               rel="alternate"
               hreflang="en"
               href="http://www.example.com/english/page.html"/>
  </url>
  <url>
    <loc>http://www.example.com/schweiz-deutsch/page.html</loc>
    <xhtml:link 
               rel="alternate"
               hreflang="de"
               href="http://www.example.com/deutsch/page.html"/>
    <xhtml:link 
               rel="alternate"
               hreflang="de-ch"
               href="http://www.example.com/schweiz-deutsch/page.html"/>
    <xhtml:link 
               rel="alternate"
               hreflang="en"
               href="http://www.example.com/english/page.html"/>
  </url>
</urlset>
```

In addition, the sitemap has been in the form of `urlset` for quite a while, I'm quite hesitant to change it to `sitemapindex` type because that just means we are building lot of `sitemaps`. 
I will wait for @JoelMarcey @yangshun approval on whether we should switch to `sitemapindex` or keep it as it is. I personally feel that this is somewhat a breaking change especially in SEO though. Is it okay to keep the sitemap format as it is ?
