### ISSUE TITLE
Mermaid 9.2 falls over in Docusaurus 2.2

### ISSUE THREAD

**Issue by xenon8** [facebook/docusaurus#8274]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

We get the below error when following the [instructions here](https://docusaurus.io/docs/markdown-features/diagrams#configuration) to implement Mermaid with Docusaurus 2.2

_TypeError: Cannot read properties of undefined (reading 'mermaidAPI')_

The error occurs when loading a page with a Mermaid diagram on it.

After some investigation it would appear that Mermaid 9.2 was released today and this caused the issue.

To resolve it, when added this to the package.json:
`    "mermaid": "9.1.1",`

rather than

` "mermaid": "^9.1.1", `

I have reproduced the issue on a fresh site as well as our own

### Steps to reproduce

1. Create new site of docusaurus
2. add the Mermaid changes as per the documentation
3. make a page with mermaid in them (add the ticks):

mermaid
graph LR
  A[Build your site] --> B[Deploy your site]

4. install npm packages
5. start site
6. navigate to page

### Expected behavior

page loads

### Actual behavior

page crashes with:

_TypeError: Cannot read properties of undefined (reading 'mermaidAPI')_

### Your environment

- Docusaurus version used: 2.2.
- Environment name and version (e.g. Chrome 89, Node.js 16.4): Edge (106.0.1370.52 64bit); Node 16.15.0
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): Windows 10 21H2

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by slorber** [comment]
Thanks for reporting, can confirm something weird is happening.

See also:
- https://github.com/mermaid-js/mermaid/issues/3747
- https://github.com/facebook/docusaurus/pull/8282
