### ISSUE TITLE
 in  doc-only mode, i18n build error

### ISSUE THREAD

**Issue by SophiaBaby** [facebook/docusaurus#8276]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

when i in doc-only mode, set  
` routeBasePath: '/',`
and 
`--- 
slug: /
 ---`
build throwError

### Steps to reproduce

npm run build

### Expected behavior

npm run serve 
success

### Actual behavior

link error, cant see page

### Your environment

- Public source code:
- Public site URL:
- Docusaurus version used:
- Environment name and version (e.g. Chrome 89, Node.js 16.4):
- Operating system and version (e.g. Ubuntu 20.04.2 LTS):

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by SophiaBaby** [comment]
.

**Comment by nunestiago** [comment]
It's been sometime, but instead a "." leave your fix, I'm having same issue
