### ISSUE TITLE
A migration guide from Blogger to Docusaurus 

### ISSUE THREAD

**Issue by johnnyreilly** [facebook/docusaurus#8293]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Description

There isn't a guide for migrating from Blogger to Docusaurus in the docs. I've written one, based upon my own experiences of migrating:

https://blog.johnnyreilly.com/definitive-guide-to-migrating-from-blogger-to-docusaurus

It involves some automation, and I'm planning to maintain it on an ongoing basis. Would it be helpful to have a link to this in the Docusaurus docs?

### Self-service

- [X] I'd be willing to address this documentation request myself.

**Comment by slorber** [comment]
Great 👍

I think it could be added to https://docusaurus.io/community/resources#articles, we don't really have any other place otherwise

**Comment by johnnyreilly** [comment]
I shall PR!

**Comment by slorber** [comment]
fixed in https://github.com/facebook/docusaurus/pull/8313
