### ISSUE TITLE
Unlisted doc page accessible from auto generated category index

### ISSUE THREAD

**Issue by Mysterious-Dev** [facebook/docusaurus#8301]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Description

Even if a page is marked `unlisted` with front matter, she can be accessible (build site) from auto generated category index.

In the demo, `create-a-blog-post.md` is marked with `unlisted` front matter.

### Reproducible demo

https://stackblitz.com/edit/github-qvcv3j?terminal=build,serve

### Steps to reproduce

1. Mark page that is in subcategory with auto generated category index, with `unlisted` front matter
2. Build website & test it
3. Go to the auto generated category index
4. View the result

### Expected behavior

Page should not be accessible from auto generated category index.

### Actual behavior

The page marked `unlisted` is accessible.

### Your environment

- Docusaurus version used: 0.0.0-5363
- Environment name and version (e.g. Chrome 89, Node.js 16.4): Firefox 106 - NodeJS 18
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): Windows 11 22H2

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by slorber** [comment]
Thanks for reporting, indeed it's likely an edge case I forgot in https://github.com/facebook/docusaurus/pull/8004 😅
