### ISSUE TITLE
Cannot use hot reloading in Docker (continuation of #6722)

### ISSUE THREAD

**Issue by dirslashls** [facebook/docusaurus#8306]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

Issue #6722 has been fixed by passing the --poll CLI option as a watch option to WebPack. However, webpack expects the value to be passed either as a number or boolean. As a result, the cli option which ends up passing as a string errors out.

Just simply trying 

> docusaurus start --poll 1000

gives the following error

```log
[ERROR] ValidationError: Invalid configuration object. Webpack has been initialized using a configuration object that does not match the API schema.
 - configuration.watchOptions.poll should be one of these:
   number | boolean
   -> Enable polling mode for watching.
   Details:
    * configuration.watchOptions.poll should be a number.
      -> `number`: use polling with specified interval.
    * configuration.watchOptions.poll should be a boolean.
      -> `true`: use polling.
```

### Steps to reproduce

Locally run the following and see the error

> docusaurus start --poll 1000

### Expected behavior

Ideally the watching should take effect by polling.

### Actual behavior

The server doesn't start and errors out.

See https://github.com/webpack/webpack/issues/3048 which mentions similar issue of passing the option via env variable which is treated as a string.

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by slorber** [comment]
Thanks, can reproduce 👍 

Likely a tiny parsing issue before we apply the validation. 

---

Good first issue for an external contributor - please send a PR directly with a fix, don't claim the issue
