### ISSUE TITLE
Need tests in the new Docusaurus app or a how-to guide or tutorial for adding tests

### ISSUE THREAD

**Issue by jhsu802701** [facebook/Docusaurus#832]
### Is this a bug report?

No

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

I'd like to see functional tests provided in the new Docusaurus app or a tutorial or how-to guide on how to add tests to a Docusaurus app.  The tests would be for basic things like the content on the home page, the presence of links on the home page, and the contents on other pages throughout the site.  There should also be functional tests of the search engine provided.  Yes, we'll have to change the tests as we customize the site, but at least that means that the ball is already rolling, as the basic setup is already taken care of.

**Comment by endiliey** [comment]
This should be left to user.
