### ISSUE TITLE
docusaurus-theme-classic > Heading's className prop does nothing

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [facebook/docusaurus#8327]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

The `<Heading>` component in `docusaurus-theme-classic` can be given a `className` prop:

```tsx
<Heading as="h2" className="something">Hi!</Heading>
```

However, the component's manual `className=clsx(...)` prop ignores `props.className`:

https://github.com/facebook/docusaurus/blob/7ffa9f7689a925e61dc63a153cd64af06dbe79e2/packages/docusaurus-theme-classic/src/theme/Heading/index.tsx#L26-L33

This means any `className` added in user-land is ignored.

### Reproducible demo

https://github.com/typescript-eslint/typescript-eslint/pull/5951/files#diff-3b034ddb6525c7b93f97ced8a696c78c1837f072b9d1e70c46049675e0e09bf4R112-R116

### Steps to reproduce

1. Checkout that PR -> `yarn` -> `yarn start`
2. Change <div className="text--center"><Heading as="h2" id="title"> ... </Heading></div>` to `<Heading as="h2" className="text--center" id="title"> ... </Heading>
3. Observe that the site page does not center the heading text

### Expected behavior

The `className` should be added to the `clsx` in `Heading`.

### Actual behavior

The `className` is ignored.

### Your environment

- Public source code: https://github.com/typescript-eslint/typescript-eslint
- Public site URL: https://typescript-eslint.io
- Docusaurus version used: 2.2.0, but the code isn't changed in latest `main`
- Environment name and version (e.g. Chrome 89, Node.js 16.4): Chrome 107, Node 16.18
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): macOS Monterey

### Self-service

- [X] I'd be willing to fix this bug myself.

**Comment by slorber** [comment]
👍 ok to forward the Heading className prop

Good first issue for anyone willing to contribute - please submit a PR directly, and do not claim the issue

---

Note historically most components did not forward className in our theme, and it's an ongoing effort to add className forwarding everywhere it makes sense (and maybe later forwarding refs? although it's a more niche use-case).

For example, it's always useful when wrapping components:

```tsx
function HeadingWrapper(props) {
  return <Heading {...props} className={clsx("my-custom-className", props.className)}/>
}

```
