### ISSUE TITLE
Modern JS already guarantees Array#sort() is a stable sort

### ISSUE THREAD

**Issue by liwufei** [facebook/docusaurus#8330]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

npm WARN deprecated stable@0.1.8: Modern JS already guarantees Array#sort() is a stable sort, so this library is deprecated. See the compatibility table on MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#browser_compatibility

### Steps to reproduce

npx create-docusaurus@latest my-website classic

### Expected behavior

Remove stable package in favor of native stable sort

### Actual behavior

No WARN

### Your environment

- Public source code:
- Public site URL:
- Docusaurus version used: 2.2.0
- Environment name and version (e.g. Chrome 89, Node.js 16.4): Node.js 18.12.1
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): Ubuntu 22.04.1 LTS

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by seldomlee** [comment]
I encountered the same problem.how did you solve it?

**Comment by Josh-Cena** [comment]
@liwufei @seldomlee This package is transitively depended on through `@svgr/plugin-svgo`, and we can't remove that, so this issue does not depend on us. This is waiting on https://github.com/gregberge/svgr/issues/765, which will be fixed by https://github.com/gregberge/svgr/pull/798, and then when we update dependencies, it should be fixed.
