### ISSUE TITLE
getting error i followed all steps

### ISSUE THREAD

**Issue by viswa3760** [facebook/docusaurus#8355]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Description

I am unable to run docs and for me getting this error :The docs folder does not exist for version "v0.47". A docs folder is expected to be found at versioned_docs/version-v0.47.

### Self-service

- [X] I'd be willing to address this documentation request myself.

**Comment by slorber** [comment]
Please don't open low-quality issues on which we can't do anything

If you need support, Discord is a better place to ask questions. In any case you will have to present your problem in a better way if you want to receive help.
