### ISSUE TITLE
SCSS support

### ISSUE THREAD

**Issue by muuvmuuv** [facebook/Docusaurus#838]
## 🚀 Feature

I want to customize my docs with scss instead of using pure css.

## Have you read the [Contributing Guidelines on issues](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

yes

## Motivation

It is way easier to style the theme by not copy and past the whole class structure again and again.

## Pitch

Fasten the styling process

**Comment by caomicc** [comment]
Can I ask why this is labeled as wontfix? I'm unable to use sass-loader and node-sass, but I am able to with generic react apps. Is there a way I can add this to the docusaurus.config.js?

**Comment by yangshun** [comment]
@endiliey Why was this a wontfix?

@caomicc You can configure the webpack config using plugin lifecycle hooks. E.g. https://github.com/facebook/docusaurus/blob/master/packages/docusaurus-theme-live-codeblock/src/index.js

**Comment by endiliey** [comment]
its alrd doable in v2 through plugin system. Its also not going to be implemented in v1.

**Comment by endiliey** [comment]
Seems that i labeled it wrongly by mistake

**Comment by rlamana** [comment]
For those looking for a fast way to add sass support, just include this plugin to your `docusaurus.config.js`: https://www.npmjs.com/package/docusaurus-plugin-sass

Let's start taking advantage of how modular v2 is :)

**Comment by yangshun** [comment]
@rlamana add your plugin to the docs under styling?

**Comment by rlamana** [comment]
@yangshun Sure! I'll send a PR as soon as I can.
