### ISSUE TITLE
[ERROR] Docusaurus server-side rendering could not render static page with path /site/.

### ISSUE THREAD

**Issue by lacorda** [facebook/docusaurus#8391]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

I run `import MonacoEditor from' react-monaco-editor'` in `src/pages/site`; then `npm run build`, reporting an error: `[ERROR] Docusaurus server-side rendering could not render static page with path /site/.`

### Steps to reproduce

- run `import MonacoEditor from' react-monaco-editor'` in `src/pages/site`; 
- `npm run build`

reporting an error: `[ERROR] Docusaurus server-side rendering could not render static page with path /site/.`

### Expected behavior

-

### Actual behavior

-

### Your environment

- Public source code:
- Public site URL:
- Docusaurus version used:
- Environment name and version (e.g. Chrome 89, Node.js 16.4):
- Operating system and version (e.g. Ubuntu 20.04.2 LTS):

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by lacorda** [comment]
it's ok to use <BrowserOnly>

**Comment by fanmengwen** [comment]
how do you fix it
