### ISSUE TITLE
can't build using react-embed

### ISSUE THREAD

**Issue by sibelius** [facebook/docusaurus#8396]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

When trying to build my docusuarus website it breaks only on build

https://github.com/sibelius/zettelkasten/actions/runs/3578175316/jobs/6018027418

[ERROR] Docusaurus server-side rendering could not render static page with path /advice-for-developers.

related to https://github.com/streamich/react-embed/issues/892

### Reproducible demo

https://github.com/sibelius/zettelkasten

### Steps to reproduce

yarn
yarn build

### Expected behavior

it should build

### Actual behavior

it breaks

[ERROR] Docusaurus server-side rendering could not render static page with path

### Your environment

- Public source code: https://github.com/sibelius/zettelkasten
- Public site URL: https://sibelius.github.io/zettelkasten/
- Docusaurus version used: 2.2.0
- Environment name and version (e.g. Chrome 89, Node.js 16.4): chrome 89
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): mac m1

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by sibelius** [comment]
fixed here https://gist.github.com/sibelius/af24052edf88c3c824d0627d9248699a

**Comment by slorber** [comment]
yes that's the good workaround solution

You can also try this package otherwise: https://github.com/PaulieScanlon/mdx-embed
