### ISSUE TITLE
Highlighting is not really working

### ISSUE THREAD

**Issue by muuvmuuv** [facebook/Docusaurus#840]
## 🐛 Bug Report

Every code block with a language class do not render the language right becuase there is a space between them. Here is a image:

![bildschirmfoto 2018-07-08 um 22 43 05](https://user-images.githubusercontent.com/11534760/42423791-7c75d1e2-8300-11e8-97b5-2e463dc82972.png)

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

yes

## To Reproduce

1. clean install
2. add a `builder.code(`npm install --save-dev`, "bash");`

## Expected behavior

It should render the class like `language-bash` not `language- bash` (note the space).

(Write what you thought would happen.)

## Actual Behavior

see screenshot above

(Write what happened. Add screenshots, if applicable.)

## Reproducible Demo

https://github.com/unibeautify/unibeautify

(Paste the link to an example repo, including a `siteConfig.js`, and exact instructions to reproduce the issue.)

**Comment by yangshun** [comment]
@endiliey I think it's caused by https://github.com/facebook/Docusaurus/blob/master/lib/core/renderMarkdown.js#L27 having an extra space.

**Comment by endiliey** [comment]
Great catch. Will send a fix asap 😁
