### ISSUE TITLE
showLastUpdate Vietnamese translation typo

### ISSUE THREAD

**Issue by zerot69** [facebook/docusaurus#8422]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [ ] I have tried the `npm run clear` or `yarn clear` command.
- [ ] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io.
- [ ] I have read the console error message carefully (if applicable).

### Description

When using showLastUpdateAuthor and showLastUpdateTime in Vietnamese language, there is a typo when the word "bởi" (which means "by") duplicates twice.
![image](https://user-images.githubusercontent.com/55183414/206626940-4ca5b0a3-e3b9-4460-9697-86ce1b582950.png)
![image](https://user-images.githubusercontent.com/55183414/206632137-714c12b9-80fd-4a7e-9d3a-6e677c1b8b30.png)

### Steps to reproduce

In your `docusaurus.config.js`:

```
i18n: {
		defaultLocale: "vi",
		locales: ["vi"],
	},
presets: [
		[
			//...
			({
				docs: {
					showLastUpdateAuthor: true,
					showLastUpdateTime: true,
				}
			}),
		],
	],

```

### Expected behavior

It should be "Cập nhật lần cuối vào Date bởi Author"

### Actual behavior

Instead of "Cập nhật lần cuối vào Date bởi ~~bởi~~ Author"

### Your environment

- Public source code:
- Public site URL:
- Docusaurus version used:
- Environment name and version (e.g. Chrome 89, Node.js 16.4):
- Operating system and version (e.g. Ubuntu 20.04.2 LTS):

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by slorber** [comment]
Thanks, should be fixed in https://github.com/facebook/docusaurus/pull/8424

Can you confirm this sentence looks good?


> Cập nhật lần cuối vào {date} bởi {user}

**Comment by zerot69** [comment]
@slorber that looks good 👍

**Comment by slorber** [comment]
thanks 👍
