### ISSUE TITLE
Docs from git submodules causes breadcrumbs to not be clickable

### ISSUE THREAD

**Issue by r-colvin** [facebook/docusaurus#8427]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

It was discovered that if a git submodule is used to house documentation then the breadcrumbs at the top of a doc page are no longer clickable

An example can be seen here: https://baristaexpressen.com/baristaexpressen-recipes/Recipes/Filter/Square%20Mile%20Filter%20Blend (link accurate and correct at the time of ticket writing, though steps to reproduce are provided below)

![image](https://user-images.githubusercontent.com/18327771/206984710-a3efc03c-3012-4ec6-aed1-5e6da38c2ae4.png)

In this example, the docusaurus site is stored in a private repository in GitHub, as only I work with it. However the recipes themselves are stored in a second public repository which anyone can fork and contribute to (details on how this was setup is included below in *steps to reproduce*). As can be seen in the screenshot, the left menu is correct with the right folder structure (constructed via auto). The breadcrumbs at the top of the page are also correct, however they are not clickable, which they should be in a default installation (as shown if you bootstrap a default site)

### Reproducible demo

https://baristaexpressen.com

### Steps to reproduce

1. bootstrap a new site (npx create-docusaurus@latest breadcrumb_test classic )
2. ensure the folder that the site is in, is a git repo (git init) (there doesn't need to be a remote; this is just to ensure you can import a submodule)
    2.5: set the project to docs-only mode; (I don't think this is required; however that is how all my sites are setup)
3. create another git repo that contains some MD files in some folder structure (https://github.com/r-colvin/baristaexpressen-recipes for example)
4. inside the docs folder for your default site add the submodule (git submodule add <repo clone address>)
5. yarn start

you will see the sidebar
![image](https://user-images.githubusercontent.com/18327771/206990725-db62ce4e-945c-4894-90a1-eda919495b42.png)

http://localhost:3000/tutorial-extras/translate-your-site : breadcrumbs will work for these docs with are inside the projects main folder and repo
![image](https://user-images.githubusercontent.com/18327771/206990774-2452a705-8ee3-4c6e-8a31-c72baab7fcdf.png)

a page like: http://localhost:3000/baristaexpressen-recipes/Recipes/Filter/Square%20Mile%20Filter%20Blend : the breadcrumbs won't work for "Recipes" or "Filter", however the root of the folder, "baristaexpressen-recipes" is a clickable breadcrumb; thus folders which should be clickable breadcrumbs inside a submodule fail to generate the clickable link

![image](https://user-images.githubusercontent.com/18327771/206990834-9ecbfc1e-6b64-4bfd-a142-39c76f40fec2.png)

### Expected behavior

Breadcrumbs should be clickable as part of the site navigation

### Actual behavior

Breadcrumbs for documents stored inside submodules are not clickable

### Your environment

- Public source code:
- Public site URL:
- Docusaurus version used:
- Environment name and version (e.g. Chrome 89, Node.js 16.4):
- Operating system and version (e.g. Ubuntu 20.04.2 LTS):

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by r-colvin** [comment]
Some discussion, and debugging carried out can be found in the discord here: https://discord.com/channels/398180168688074762/867060369087922187/1051070286067417098

**Comment by slorber** [comment]
Hi @r-colvin 

Breadcrumb categories (and thus sidebar categories, those are the same) are not clickable by default, it's opt-in if you decide to configure a category generated index, link (or put an index.md if autogenerated sidebar)

On your repro here: https://github.com/r-colvin/baristaexpressen-recipes

I don't see any `_category_.json` or `sidebars.js` file that could turn that category into a clickable category, so I believe what you report as a submodules but is just a more general misunderstanding: you actually have to configure the category/breadcrumb to be clickable by using options.

I'm going to close assuming I'm right. If you still think it's a submodules bug please provide a better repro that we can inspect showing how you configured the categories to be clickable.

https://docusaurus.io/docs/next/sidebar/items#category-link

**Comment by r-colvin** [comment]
hi @slorber  thanks for the reply; I understand the core of what your saying and definitely its likely a misunderstanding on my side. 

if I add a `_category_.json` to *every* level of a folder structure, then indeed I get the behaviour I am expecting - the breadcrumbs are clickable, and each level generates a index-page with cards of each sub-folder (as per tutorial-basic for example). I have yet to look into sidebars, but I assume the behaviour will be as you describe. 

so, ok that this ticket is closed with no issue; _however_ I have looked several times now and don't find any documentation on the link between category.json/sidebar.js (if i am blind, please excuse me!)

**Comment by slorber** [comment]
Everything is explained here: https://docusaurus.io/docs/next/sidebar/autogenerated#autogenerated-sidebar-metadata

`_category_.json` allows you to assign category sidebar configuration when you are using auto-generated sidebars.

**Comment by Josh-Cena** [comment]
(Our docs is a bit long and winded on this, so you also want to read https://docusaurus.io/docs/next/sidebar/items#sidebar-item-category to get the full picture about how sidebars.js config works. See https://github.com/facebook/docusaurus/issues/7917)

**Comment by r-colvin** [comment]
@slorber / @Josh-Cena  cheers - now I read the docs back with fresh eyes and perspective, i can draw the line to what I was trying to achieve - on first, second and third readings though I had completely overlooked this with regards to the "breadcrumbs" or "Category Links" as called here

![image](https://user-images.githubusercontent.com/18327771/209398999-be497451-f730-44f3-8066-2bf24505487e.png)
