### ISSUE TITLE
Image error control

### ISSUE THREAD

**Issue by shawshankkumar** [facebook/docusaurus#8436]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Motivation

Greetings, 

I am not 100% sure if this should be in the proposal part or the bug part but I chose to use the proposal issue because the thing I am going to write about is not exactly a bug, it is expected, I just think it can be handled in a better way. 

So when you go to https://docusaurus.io/ and go to the Loved by many engineers part, tweets come up(The code has a component and it is mapped over by the data). I believe some twitter images are breaking for example this screenshot: 

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/74819565/207260299-075cc906-6ae4-44c3-90f3-2335edb95873.png">

Mael and Kent's pictures' URL is broken and hence the img tag shows the alt name. I believe it would be much better if it showed a default avatar instead. This can be done in a few easy steps and I am willing (and excited) to work on this. 

What are my next steps? I am open to suggestions!

Thanks.

### Self-service

- [X] I'd be willing to do some initial work on this proposal myself.

**Comment by slorber** [comment]
Yes that Twitter thing is a pain, as their image urls changes and they do not make it easy at all to get the image URL from an avatar (unlike GitHub

What I suggest we do instead:

- add a `githubUsername` prop: all users on that list should have a GitHub account and the URL always work: https://github.io/slorber.png
- read `twitterUsername` from the tweet URL prop, and use unavatar.io
- Image URL = `https://unavatar.io/twitter/<twitterUsername>?fallback=https://github.com/<githubUsername>.png`
- Example: https://unavatar.io/twitter/sebastienlorber?fallback=https://github.com/slorber.png

Do you want to contribute this?

**Comment by abhinandanwadwa** [comment]
Hey @slorber , I'd like to work on this issue!

**Comment by abhinandanwadwa** [comment]
@slorber I've created a PR for the issue!

**Comment by shawshankkumar** [comment]
> @slorber I've created a PR for the issue!

Hey @abhinandanwadwa since i initiated this, i would like to fix this and make a pr. Please follow the same process from the next time. @slorber I'll be making a pr soon, hope that's fine.

**Comment by slorber** [comment]
@shawshankkumar sorry but our policy is that if you want to claim an issue you have to submit a draft PR first

This is to prevent people from saying that they will work on something, and then they ghost us and nobody works on the issue due to the issue being claimed, which happened a lot in the past.

This also saves maintainer time. 

If you want to claim an issue, you have to demonstrate you really plan to work on it fast otherwise someone else will

**Comment by shawshankkumar** [comment]
> @shawshankkumar sorry but our policy is that if you want to claim an issue you have to submit a draft PR first
> 
> This is to prevent people from saying that they will work on something, and then they ghost us and nobody works on the issue due to the issue being claimed, which happened a lot in the past.
> 
> This also saves maintainer time.
> 
> If you want to claim an issue, you have to demonstrate you really plan to work on it fast otherwise someone else will

Oh Okay. i had the code ready for the first one and was working on the second. That suck 😞  But no worries. Thanks for your time.

**Comment by slorber** [comment]
sorry about that

the best way to contribute small issues such as this one is to directly open a PR with a fix proposal, demonstrating your intention to work on it. From there I can review your PR and suggest a possible better alternative if your approach is not good enough

**Comment by shawshankkumar** [comment]
That sounds great. I'll look for more!
