### ISSUE TITLE
proposal: button element css style set margin: 0 

### ISSUE THREAD

**Issue by Djunnni** [facebook/docusaurus#8439]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Motivation

hello.

in safari, margin-left and margin-right set 2px default. but chrome and firefox don't

and i check in some of button element in docusaurus and found some of button set margin: 0 manually

how about set default margin: 0 in button element? 

you can see how to i changed in PR #8426 

thanks

### Self-service

- [X] I'd be willing to do some initial work on this proposal myself.

**Comment by slorber** [comment]
see https://github.com/facebook/docusaurus/pull/8426#issuecomment-1351542107

this is not really the place to fix this, and should be handled in Infima instead alongside other global CSS resets

I'm still willing to accept scoped margin 0 applied locally with a CSS module className if you notice any important theme element being affected
