### ISSUE TITLE
Image import not working when using plugin-ideal-image

### ISSUE THREAD

**Issue by alewolf** [facebook/docusaurus#8452]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

When using `plugin-ideal-image` image imports don't work in `.mdx` files. 

```
# DS bug 1

Lorem ipsum

Regular way to import images (working)

 ![example](./example.png)

Using the standard ES import syntax (NOT working)

import myImageUrl from './example.png';

<img src={myImageUrl}  />;

Using the plugin-ideal-image import syntax (NOT working)

<Image img={require('./example.png')} />
```

Here's the repo with the reproducible bug: 

https://github.com/sweetcode-com/ds-bug-1

The demo page you'll find under the subfolder `/docs/tutorial-basics/ds-bug-1`

### Steps to reproduce

1. Install the repo
2. Open the page `/docs/tutorial-basics/ds-bug-1`

### Expected behavior

Images should be rendered, especially when using the `plugin-ideal-image` syntax. 

### Actual behavior

Image links are broken.

### Your environment

- Public source code: https://github.com/sweetcode-com/ds-bug-1
- Public site URL: na
- Docusaurus version used: 2.2.0
- Environment name and version (e.g. Chrome 89, Node.js 16.4):  Chrome 108.0.5359.98, node v.19.3.0
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): OS X 13.0.1

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by slorber** [comment]
Your repro doesn't import the Image component:

https://raw.githubusercontent.com/sweetcode-com/ds-bug-1/main/docs/tutorial-basics/ds-bug-1.mdx

```
# DS bug 1

Lorem ipsum

Regular way to import images (working)

 ![example](./example.png)

Using the standard ES import syntax (NOT working)

import myImageUrl from './example.png';

<img src={myImageUrl}  />;

Using the plugin-ideal-image import syntax (NOT working)

<Image img={require('./example.png')} />
```

And it is not documented to use a regular `<img>` tag either.

https://docusaurus.io/docs/api/plugins/@docusaurus/plugin-ideal-image

<img width="1030" alt="CleanShot 2022-12-16 at 12 46 06@2x" src="https://user-images.githubusercontent.com/749374/208091461-a8c06324-5b92-4ce8-8ef8-0eb4cdae17c3.png">


The following works for me:

```
# DS bug 1

Lorem ipsum

Regular way to import images (working)

![example](./example.png)

Using the standard ES import syntax (NOT working)

import Image from '@theme/IdealImage';

import myImageUrl from './example.png';

<Image img={myImageUrl} />

Using the plugin-ideal-image import syntax (NOT working)

<Image img={require('./example.png').default} />
```

It's not exactly what we document (require + default) so I'll keep it open until we investigate a bit more.

Our dev/prod setup is different also so that's worth trying both modes

**Comment by alewolf** [comment]
Oh. That I should have found out myself. Thanks!

While discussing `plugin-ideal-image`. Is there a way to add the custom style to the <Image img={myImageUrl} /> tag. 

Normal HTML `style` properties an react style properties don't work. 

I want to set a max width. Any idea how to achieve this?

**Comment by slorber** [comment]
I haven't tried but I guess passing a style or className should work. Worth giving it a try. 

You can create your own wrapper around our existing Image component if you want to change some defaults (or swizzle --wrap it)

**Comment by alewolf** [comment]
Ok. Thanks. I might just disable `plugin-ideal-image`, as I then can use your native image component that allows me do specify width.
