### ISSUE TITLE
Format init template based on user config

### ISSUE THREAD

**Issue by shramee** [facebook/docusaurus#8456]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

## Issue

`npx create-docusaurus@latest docs classic` doesn't include a `.prettierrc` but it does use [facebook/docusaurus/.prettierrc](https://github.com/facebook/docusaurus/blob/main/.prettierrc) from parent dir.

User's project `.prettierrc` can be different and results in lots of whitespace/syntax changes on editing any file.

### Polluted diff

<img width="731" alt="image" src="https://user-images.githubusercontent.com/11048263/208225257-b304c0de-7ff9-4591-925e-b997e0f99ac6.png">

### Diff after sourcing correct .prettierrc from [facebook/docusaurus/.prettierrc](https://github.com/facebook/docusaurus/blob/main/.prettierrc)

<img width="734" alt="image" src="https://user-images.githubusercontent.com/11048263/208225355-02fc07eb-6226-41f8-a383-3a0991d55495.png">

### 1. Include  [facebook/docusaurus/.prettierrc](https://github.com/facebook/docusaurus/blob/main/.prettierrc) in template
- Can do a PR for this with `.prettierrc` added in [create-docusaurus/templates/shared](https://github.com/facebook/docusaurus/tree/main/packages/create-docusaurus/templates/shared) - @shramee
### 2. Include instructions in docs to use [facebook/docusaurus/.prettierrc](https://github.com/facebook/docusaurus/blob/main/.prettierrc) for docusaurus dir
 - Happy do an initial draft - @shramee
### 3. Include instructions in docs to solve this in another way
 - To discuss

### Reproducible demo

https://github.com/shramee/starknet-hardhat-plugin/commit/caaca3b8a9eeb0f9f5eac0053e5d8b46b8ccd89a

### Steps to reproduce

1. Prepare a dummy project with [starknet-hardhat-plugin/.prettierrc](https://github.com/shramee/starknet-hardhat-plugin/blob/master/.prettierrc) in a git repo directory.
2. Init docusaurus `npx create-docusaurus@latest docs classic` inside your main directory.
3. Make a git commit (to track changes over the default docusaurus setup)
4. Make some changes to any file, say `docs/src/pages/index.js`.
5. Have `prettier` run (most devs have this set up to run on save)
6. See the polluted diff.

### Expected behavior

A beautiful diff showing only what's changed ❤️ 🌈 

<img width="734" alt="image" src="https://user-images.githubusercontent.com/11048263/208225355-02fc07eb-6226-41f8-a383-3a0991d55495.png">

### Actual behavior

A messed up diff with every line changed 💔 😢  

<img width="731" alt="image" src="https://user-images.githubusercontent.com/11048263/208225257-b304c0de-7ff9-4591-925e-b997e0f99ac6.png">

### Your environment

- Public source code: https://github.com/shramee/starknet-hardhat-plugin/tree/16fad57598f74b71262078e8283eaee30fbe74e9
- Public site URL: n.a.
- Docusaurus version used: 2.2.0
- Environment name and version (e.g. Chrome 89, Node.js 16.4): VSCode 1.74.0, Prettier v7, Node v16.14
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): macOS 12.4

### Self-service

- [x] I'd be willing to fix this bug myself.

**Comment by Josh-Cena** [comment]
Why would you commit and then format? After you've scaffolded the project, you should first format it before committing. A pre-commit hook can help you with that.

I haven't seen other scaffolding utilities doing auto-formatting based on user workspace's configuration. Do you have examples to share so we can align our behavior?

**Comment by shramee** [comment]
Aah, makes sense. My bad.
