### ISSUE TITLE
Tab sync using groupId not functioning

### ISSUE THREAD

**Issue by qdot** [facebook/docusaurus#8473]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

Tab sync does not seem to work, even when Tabs blocks have a similar groupId. This issue is present across latest Firefox and Chrome, and happens within the Docusaurus documentation itself.

### Reproducible demo

https://docusaurus.io/docs/markdown-features/tabs#syncing-tab-choices

### Steps to reproduce

1. Go to the docusaurus docs website, markdown-features/tabs section
2. Try clicking the examples in the Syncing Tab Choices portion

### Expected behavior

The tabs for windows/mac should change in sync.

### Actual behavior

The tabs are unaffected by selections of one another.

### Your environment

- Public source code: https://github.com/facebook/docusaurus/blob/main/website/docs/guides/markdown-features/markdown-features-tabs.mdx?plain=1#L136
- Public site URL: https://docusaurus.io/docs/markdown-features/tabs#syncing-tab-choices
- Docusaurus version used: 
- Environment name and version (e.g. Chrome 89, Node.js 16.4): Firefox 108, Chrome 108, Safari 16 17614 (All stock)
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): Windows 11 Pro

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by Josh-Cena** [comment]
Likely broken by #8225. Thanks for the report!

**Comment by 0916dhkim** [comment]
I opened a PR to fix this issue. Can you take a look?
