### ISSUE TITLE
Bug(core/build): Bracket in path make build command fail

### ISSUE THREAD

**Issue by Thomascogez** [facebook/docusaurus#8480]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

When a `docusaurus` project is inside a folder containing bracket (eg: /path/[bracket]/docusaurusProject) the build fail with the following error.

```sh
[ERROR] Error: EISDIR: illegal operation on a directory, open '/path/[bracket]/docusaurusProject/build'
[ERROR] Unable to build website for locale en.
[ERROR] Error: EISDIR: illegal operation on a directory, open '/path/[bracket]/docusaurusProject/build'
````

### Reproducible demo

https://github.com/Thomascogez/docusaurus-bracket-in-path-bug-repro

### Steps to reproduce

1 - run docusaurus `build` command
2 - Observe the following error:
```sh
[ERROR] Error: EISDIR: illegal operation on a directory, open '/path/[bracket]/docusaurusProject/build'
[ERROR] Unable to build website for locale en.
[ERROR] Error: EISDIR: illegal operation on a directory, open '/path/[bracket]/docusaurusProject/build'
````

### Expected behavior

The build should succeed.

### Actual behavior

The build fails with the following error:

```sh
[ERROR] Error: EISDIR: illegal operation on a directory, open '/Users/user/Documents/projectPath/docusaurus-bracket-in-path-bug-repro/[bracket]/build'
[ERROR] Unable to build website for locale en.
[ERROR] Error: EISDIR: illegal operation on a directory, open '/Users/user/Documents/projectPath/docusaurus-bracket-in-path-bug-repro/[bracket]/build'
```

### Your environment

- Docusaurus version used: 2.2.0
- Environment name and version (e.g. Chrome 89, Node.js 16.4): Node.js 19.1
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): macOS Ventura 13.0.1

### Self-service

- [X] I'd be willing to fix this bug myself.

**Comment by Josh-Cena** [comment]
Seems like the same problem as https://github.com/facebook/docusaurus/issues/8135: something is trying to interpolate the path as a regex/glob pattern.
