### ISSUE TITLE
useHistory with external URL

### ISSUE THREAD

**Issue by Cittjr** [facebook/docusaurus#8495]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

Hello,

i am using the plugin "easyops-cn/docusaurus-search-local", this plugin create an autocomplete and when click on an element the code call the `useHistory.push(url);`.

But when i specify an external url (example: https://www.google.com/) the router open "http://localhost:3000/https://www.google.com/" not only "https://www.google.com/".

I have test with a single page and this page doesnt open the external url.

### Steps to reproduce

1. Create a new page (pages/redirectTest.js)
2. Set this code in the page: 
```import React from 'react';
import Layout from '@theme/Layout';
import {useLocation} from '@docusaurus/router';
import { useHistory } from "@docusaurus/router";

  
export default function PageRoute() {
  // React router provides the current component's route, even in SSR
  const location = useLocation();
  const history = useHistory();
  
  history.push("https://www.google.com/");
  
  return (
    <span>
      We are currently on <code>{location.pathname}</code>
    </span>
  );
}
```
3. Launch the page

### Expected behavior

i want to open an external url with the method push of the history

### Actual behavior

The external url is not open, docusaurus detect the url for his system of route

### Your environment

- Public source code: None
- Public site URL: None
- Docusaurus version used: 2.2.0
- Environment name and version (e.g. Chrome 89, Node.js 16.4): Chrome last & Node v16.15.1
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): Windows

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by Josh-Cena** [comment]
This is working as intended—external URLs should not use `history.push`, but `window.location`.  This is why our Algolia plugin has a config to treat certain paths as external. See https://github.com/facebook/docusaurus/pull/5795
