### ISSUE TITLE
404 error page after click `remark plugins` and `rehype plugins`

### ISSUE THREAD

**Issue by victoriacheng15** [facebook/docusaurus#8522]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [ ] I have tried the `npm run clear` or `yarn clear` command.
- [ ] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io.
- [ ] I have read the console error message carefully (if applicable).

### Description

On the `docs/markdown-feature/plugins` (MDX Plugins) page, both `remark plugins` and `rehype plugins` links lead to 404 error page.

### Steps to reproduce

- go to docs/markdown-feature/plugins
- click remark/rehype plugins links

### Expected behavior

it should lead to the correct page about remark and rehype plugin pages 

### Actual behavior

both links leads to 404 error page

### Your environment

- Public source code:
- Public site URL:
- Docusaurus version used:
- Environment name and version (e.g. Chrome 89, Node.js 16.4):
- Operating system and version (e.g. Ubuntu 20.04.2 LTS):

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by juzhiyuan** [comment]
It seems that this has been fixed in https://github.com/facebook/docusaurus/commit/773529a3bc278ac1905ea8e1ef10aba332458f90#diff-b27f4fa0b6c29f06a64ce99b12edf3b497f2d98e3df3b80d91d8c18dec50c963, but the live site doesn't update? 🤔

**Comment by victoriacheng15** [comment]
Interesting! I checked the `deploy preview` and both links are correct, but not the live site (still has `mdx`). Not sure why it didn't update?

**Comment by Josh-Cena** [comment]
https://app.netlify.com/sites/docusaurus-2/deploys/63b8475e022cf10009a4e4c7 A Crowdin error prevents the site from building. Just need @slorber to trigger a rebuild.

**Comment by Josh-Cena** [comment]
It's now fixed.
