### ISSUE TITLE
unable to start docusaurus

### ISSUE THREAD

**Issue by mat2718** [facebook/docusaurus#8523]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io.
- [ ] I have read the console error message carefully (if applicable).

### Description

```
 yarn start 
yarn run v1.22.19
$ docusaurus start
node:internal/modules/cjs/loader:1039
  const err = new Error(message);
              ^

Error: Cannot find module './fp/_baseConvert'
Require stack:
- C:\Users\MATTH\OneDrive\Documents\GitHub\vision-camera-face-detector\docs\node_modules\lodash\fp.js
- C:\Users\MATTH\OneDrive\Documents\GitHub\vision-camera-face-detector\docs\node_modules\wait-on\lib\wait-on.js
- C:\Users\MATTH\OneDrive\Documents\GitHub\vision-camera-face-detector\docs\node_modules\@docusaurus\core\lib\webpack\plugins\WaitPlugin.js
- C:\Users\MATTH\OneDrive\Documents\GitHub\vision-camera-face-detector\docs\node_modules\@docusaurus\core\lib\webpack\server.js
- C:\Users\MATTH\OneDrive\Documents\GitHub\vision-camera-face-detector\docs\node_modules\@docusaurus\core\lib\commands\build.js
- C:\Users\MATTH\OneDrive\Documents\GitHub\vision-camera-face-detector\docs\node_modules\@docusaurus\core\lib\index.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1039:15)
    at Module._load (node:internal/modules/cjs/loader:885:27)
    at Module.require (node:internal/modules/cjs/loader:1105:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (C:\Users\MATTH\OneDrive\Documents\GitHub\vision-camera-face-detector\docs\node_modules\lodash\fp.js:2:18)
    at Module._compile (node:internal/modules/cjs/loader:1218:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1272:10)
    at Module.load (node:internal/modules/cjs/loader:1081:32)
    at Module._load (node:internal/modules/cjs/loader:922:12)
    at Module.require (node:internal/modules/cjs/loader:1105:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\MATTH\\OneDrive\\Documents\\GitHub\\vision-camera-face-detector\\docs\\node_modules\\lodash\\fp.js',
    'C:\\Users\\MATTH\\OneDrive\\Documents\\GitHub\\vision-camera-face-detector\\docs\\node_modules\\wait-on\\lib\\wait-on.js',
    'C:\\Users\\MATTH\\OneDrive\\Documents\\GitHub\\vision-camera-face-detector\\docs\\node_modules\\@docusaurus\\core\\lib\\webpack\\plugins\\WaitPlugin.js',
    'C:\\Users\\MATTH\\OneDrive\\Documents\\GitHub\\vision-camera-face-detector\\docs\\node_modules\\@docusaurus\\core\\lib\\webpack\\server.js',
    'C:\\Users\\MATTH\\OneDrive\\Documents\\GitHub\\vision-camera-face-detector\\docs\\node_modules\\@docusaurus\\core\\lib\\commands\\build.js',
    'C:\\Users\\MATTH\\OneDrive\\Documents\\GitHub\\vision-camera-face-detector\\docs\\node_modules\\@docusaurus\\core\\lib\\index.js'
  ]
}

Node.js v19.3.0
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### Steps to reproduce

follow typescript installation. 
run in created folder
yarn
yarn start

### Expected behavior

for it to work

### Actual behavior

MODULE_NOT_FOUND

### Your environment

- Public source code:
- Public site URL:
- Docusaurus version used:
- Environment name and version (e.g. Chrome 89, Node.js 16.4):
- Operating system and version (e.g. Ubuntu 20.04.2 LTS):

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by Josh-Cena** [comment]
Just re-confirming: you've tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing, and the error is still the same?

**Comment by mat2718** [comment]
Yes that is correct. I've also tried deleting the whole folder and rerunning the npx command and the problem persists

**Comment by mat2718** [comment]
hello!

turns out the file fp/_baseConvert is missing in the lodash library 4.17.21 but is present in lodash 4.17.15. the wait-on library is the library that has the loadash dependency. long story short i added a resolution to the package.json and set lodash to 4.17.15 and the server started right up

```json
"resolutions": {
    "lodash": "4.17.15"
  },
```

**Comment by Josh-Cena** [comment]
Thanks for looking into this. Weirdly, I do see `node_modules/lodash/fp/_baseConvert.js` in my node_modules, even with lodash `4.17.21`.
