### ISSUE TITLE
Improve the docs regarding deployment

### ISSUE THREAD

**Issue by steevehook** [facebook/Docusaurus#853]
## 📚 Documentation

The docs regarding deployment to gh-pages are ambigue. Always getting missing styles due to missing / when making requests for css or images. Thus making the website look quirky. 

Explain in more details the steps to push the website to gh-pages and perhaps how the publish-gh-pages script works and some screen shots plus a more detailed explanation of siteConfig props related to deployment would be highly appreciated

**Comment by theletterf** [comment]
+1

**Comment by endiliey** [comment]
We accept PR on this 😉 

Docs:
https://github.com/facebook/docusaurus/edit/master/docs/getting-started-publishing.md

Publish script:
https://github.com/facebook/Docusaurus/blob/master/lib/publish-gh-pages.js

**Comment by rizafahmi** [comment]
Can I claim this issue?

**Comment by yangshun** [comment]
@rizafahmi How's your progress for this task? Let us know how we can help. If you are no longer available for this task, just let us know and we can free it up for someone else. Do keep us updated 😄

**Comment by rizafahmi** [comment]
Hi @yangshun, I have some difficulties. **Just free it up**. If I can pull it through, I will reclaim if it's not already claimed.

**Comment by M4rk9696** [comment]
Can I claim this?

**Comment by JoelMarcey** [comment]
We've added an `issue: claimed` label so that others will know not to start work on the issue. If you change your mind about the issue, no worries! Just let us know so that we can remove the label and free it up for someone else to claim.

We will check in with you periodically so that we can keep the task updated with the progress.

**Comment by yangshun** [comment]
Closed by #1049
