### ISSUE TITLE
Same post shown twice in the blog list

### ISSUE THREAD

**Issue by Zwyx** [facebook/docusaurus#8536]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

I noticed one of my blog posts showing twice in the main blog list. One time rightfully, the other time taking the spot of another post. I managed to get a minimal setup to reproduce it:

![](https://github.com/Zwyx/docusaurus-bug-demo/raw/main/Screenshot1.png)

![image](https://user-images.githubusercontent.com/29386932/211576794-b996ccc0-b209-4e89-92a8-d0d51b8894f1.png)

### Reproducible demo

https://stackblitz.com/edit/github-bmgrpn

### Steps to reproduce

From a fresh Docusaurus install, empty the `blog` folder and create the two folders and files [that are in it now](https://stackblitz.com/edit/github-bmgrpn).

On the website, in the blog, there are two posts: Post 1 and Post 2. We can see them in the list of recent posts. However, Post 1 is not present in the main list, and Post 2 is present twice:

![](https://github.com/Zwyx/docusaurus-bug-demo/raw/main/Screenshot1.png)

We also notice this React error in the console:

```
react-dom.development.js?ac89:67 Warning: Encountered two children with the same key, `/blog/post2`. Keys should be unique so that components maintain their identity across updates.
```

> Note: it is still possible to build the site with `yarn build`, the error won't be present in the output.

Other observations:

- Renaming any of the two blog post folders (simply changing one character) fixes the issue (it looks like hashes colliding, so I tinkered in `docuHash` in `docusaurus-utils/src/hashUtils.ts` but it didn't do anything conclusive).

- Changing the 4th line of the Post 2 `index.mdx` file from `tags: [tag]` to `tags: []` makes now Post 1 being present twice instead of Post 2:

![](https://github.com/Zwyx/docusaurus-bug-demo/raw/main/Screenshot2.png)

### Expected behavior

No duplicate post.

### Actual behavior

See above.

### Your environment

- Public source code: https://stackblitz.com/edit/github-bmgrpn or https://github.com/Zwyx/docusaurus-bug-demo
- Public site URL: N/A — building the site works, it's only when running in dev mode that the issue appears
- Docusaurus version used: 2.2.0
- Environment name and version (e.g. Chrome 89, Node.js 16.4): Chrome 108, Node 18.
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): Ubuntu 22.04.1 LTS

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by Josh-Cena** [comment]
Nice construction—we have a hash collision! The culprit is in this function:

https://github.com/facebook/docusaurus/blob/e8a07633ba033dbe456839e45fdcef30cfb62c08/packages/docusaurus/src/server/routes.ts#L66-L88

Here are two inputs and outputs:

```
[Arguments] {
  '0': '@site/blog/2022-11-18-bye-medium/index.mdx?truncated=true',
  '1': 'content',
  '2': '/blog'
} => content---blogc-99-485
[Arguments] {
  '0': '@site/blog/2019-10-05-react-nfc/index.mdx?truncated=true',
  '1': 'content',
  '2': '/blog'
} => content---blogc-99-485
```

I think we need to have to append an incrementing suffix to avoid collision.
