### ISSUE TITLE
Docusaurus plugin global data not found for "docusaurus-plugin-content-docs" plugin with id "default".

### ISSUE THREAD

**Issue by aryzing** [facebook/docusaurus#8542]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

Seems that Docusarus at some point expect a plugin with an id of "default". If non is present, the following error message appears in the built app,

> This page crashed.
> Docusaurus plugin global data not found for "docusaurus-plugin-content-docs" plugin with id "default".

### Reproducible demo

https://stackblitz.com/edit/github-njjcoj?file=docusaurus.config.js%3AL34

### Steps to reproduce

Changing the id of the highlighted line to any value other than "default" prevents the app from running properly.

### Expected behavior

The app should work with any custom plugin id. If a `default` id is needed or treated in a special way, having this behaviour documented would be of great help.

### Actual behavior

The page builds and displays the error,

> This page crashed.
> Docusaurus plugin global data not found for "docusaurus-plugin-content-docs" plugin with id "default".

### Your environment

- Docusaurus version used: "@docusaurus/core": "2.2.0",

The environment is that provided by the stackblitz repro above.

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by Josh-Cena** [comment]
Hi! The `"default"` ID is referenced because the init template has a navbar item

```js
          {
            type: 'doc',
            docId: 'intro',
            position: 'left',
            label: 'Tutorial',
          },
```

Which implicitly link to the `default` plugin because no `pluginId` is provided. If you are doing any customizations, you should remove the boilerplate from the template. However, should you start with an entirely empty website (zero config/content), you should not run into this issue.
