### ISSUE TITLE
Document the possibility to namespace markdown docs

### ISSUE THREAD

**Issue by steevehook** [facebook/Docusaurus#855]
## 🚀 Feature

Currently the approach is to stuff every doc inside docs folder and if the docs grows on an on, it's a bit hard to find the needed doc. What I've seen works but it's nowhere documented is to omit the id from markdown document and have them placed inside directories. Then later reference them as `/dir/doc`

Document the possibility of structuring the docs across directories aka name spacing them. Currently if placing a document inside a folder then referencing it by id will break. However if placing it inside a directory and omitting the id it can be referenced such as `directory/document-name`

## Motivation
It is important to outline this because otherwise stuffing markdown documents inside root docs becomes a mess real quick for large documentations

## Pitch

This is not really a feature, yet an enhancement of better structuring. As far as I've seen it's already implemented it's just not documented yet.

Thanks for this awesome tool guys and sorry for throwing proposals at you 🗡

**Comment by endiliey** [comment]
Thank you for this.

> Currently if placing a document inside a folder then referencing it by id will break
Just wanted to point out that this is not true, if an id exist, it can be referenced as `directory/id`, it just seems that it is not documented so clearly. 

Example: `docs/make/adding-levels.md`
```
---
id: adding-levels
title: Adding Levels
---

A level is another JavaScript object:
```

Then it should be referenced as
`"make/adding-levels",`

Reference of use case: 
1. https://github.com/olistic/warriorjs/tree/master/docs
1. https://github.com/olistic/warriorjs/blob/master/website/sidebars.json

Will be great if anyone wanted to create a PR to document this clearly

**Comment by endiliey** [comment]
Thank you for this.

> Currently if placing a document inside a folder then referencing it by id will break

Just wanted to point out that this is not true, if an id exist, it can be referenced as `directory/id`, it just seems that it is not documented so clearly. 

Example: `docs/make/adding-levels.md`
```
---
id: adding-levels
title: Adding Levels
---

A level is another JavaScript object:
```

Then it should be referenced as
`"make/adding-levels",`

Reference of use case: 
1. https://github.com/olistic/warriorjs/tree/master/docs
1. https://github.com/olistic/warriorjs/blob/master/website/sidebars.json

Will be great if anyone wanted to create a PR to document this clearly. 
@steevehook want to create a PR for this ? 😉

**Comment by steevehook** [comment]
Sure, my pleasure to contribute man 😉
