### ISSUE TITLE
Markdown links doesn't work after any html tag

### ISSUE THREAD

**Issue by birvl97** [facebook/docusaurus#8558]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

Following md file:
```
<b>Something</b> [LINK](./some.md)
```

Will be rendered as plain text, insted of bold text with clickable link.

### Steps to reproduce

Open [sandbox](https://codesandbox.io/s/musing-hill-ppd2td?file=/docs/intro.md) and see at 17th line, line was changed from:
```
- [Node](link) ...
```

to:
```
- <b>node</b> [Node](link)
```

Instresting, if add some text before tag, e.g:
```
Something <b>bold</b> [Link]()
```
It will work fine, looks very similar with [issue](https://github.com/facebook/docusaurus/issues/4890), but this example works fine in https://mdxjs.com/playground/

### Expected behavior

Md should render properly. so I mean like this <b>Some</b> [LINK]()

### Actual behavior

Got md link rendered as plain text :cry

### Your environment

- Public source code:
- Public site URL:
- Docusaurus version used:
- Environment name and version (e.g. Chrome 89, Node.js 16.4):
- Operating system and version (e.g. Ubuntu 20.04.2 LTS):

### Self-service

- [X] I'd be willing to fix this bug myself.

**Comment by Josh-Cena** [comment]
Hi! Docusaurus uses MDX v1, so if you are experimenting, make sure to use the v1 playground: https://mdx-git-renovate-babel-monorepo-mdx.vercel.app/playground/

This is a documented limitation here: https://docusaurus.io/docs/markdown-features/react#markdown-and-jsx-interoperability Namely, "A paragraph starting with a JSX tag will be seen entirely as a JSX string". This will be fixed by the MDX v2 migration.
