### ISSUE TITLE
npm badge looks blocked

### ISSUE THREAD

**Issue by Gaslights** [facebook/docusaurus#8564]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [ ] I have tried the `npm run clear` or `yarn clear` command.
- [ ] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io.
- [ ] I have read the console error message carefully (if applicable).

### Description

ABc

### Steps to reproduce

Abc

### Expected behavior

HV

### Actual behavior

Expected

### Your environment

- Public source code:
- Public site URL:
- Docusaurus version used:
- Environment name and version (e.g. Chrome 89, Node.js 16.4):
- Operating system and version (e.g. Ubuntu 20.04.2 LTS):

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by Josh-Cena** [comment]
All badges are correctly displayed:

<img width="873" alt="image" src="https://user-images.githubusercontent.com/55398995/213558684-93fc0409-7e82-4a18-8bf0-56f8fd0e16af.png">

Until more information is provided, I'm going to close this as the template is outright disregarded.
