### ISSUE TITLE
List in a tab doesn't render

### ISSUE THREAD

**Issue by themr0c** [facebook/docusaurus#8575]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

Taking  the example as a source https://docusaurus.io/docs/markdown-features/tabs

I would like to display an unordered list item as content for a tab.

### Steps to reproduce

All tabs in this example don't render a list:

```
import Tabs from '@theme/Tabs';
import TabItem from '@theme/TabItem';

<Tabs>
  <TabItem value="apple" label="Apple" default>
    * This is an apple 🍎
  </TabItem>
  <TabItem value="orange" label="Orange">
  * This is an orange 🍊
  </TabItem>
  <TabItem value="banana" label="Banana">
      * This is a banana 🍌
  </TabItem>
</Tabs>
```

Adding an empty line, it is possible to render a code block:

```
import Tabs from '@theme/Tabs';
import TabItem from '@theme/TabItem';

<Tabs>
  <TabItem value="apple" label="Apple" default>

  ```
  This is an apple 🍎
  ```
  </TabItem>
  <TabItem value="orange" label="Orange">
  * This is an orange 🍊
  </TabItem>
  <TabItem value="banana" label="Banana">
      * This is a banana 🍌
  </TabItem>
</Tabs>
```

However, this method doesn't work to add an unordered list. 

Mimicking previous example:

```
import Tabs from '@theme/Tabs';
import TabItem from '@theme/TabItem';

<Tabs>
  <TabItem value="apple" label="Apple" default>

  * This is an apple 🍎

  </TabItem>
  <TabItem value="orange" label="Orange">
  * This is an orange 🍊
  </TabItem>
  <TabItem value="banana" label="Banana">
      * This is a banana 🍌
  </TabItem>
</Tabs>
```

### Expected behavior

I expect this example to produce tabs, with an unordered list item in the firts tab.

### Actual behavior

Instead, the build fails:

```
Compiled with problems:


ERROR in ./docs/bug.md

Module build failed (from ../node_modules/@docusaurus/mdx-loader/lib/index.js):
SyntaxError: [...]/docs/installing-podman/bug.md: Expected corresponding JSX closing tag for <li>. (14:2)

  12 | <li parentName="ul">
  13 | <p parentName="li">{`This is an apple 🍎`}</p>
> 14 |   </TabItem>
     |   ^
  15 |   <TabItem value="orange" label="Orange">
  16 |   * This is an orange 🍊
  17 |   </TabItem>
    at instantiate ([...]/node_modules/@babel/parser/lib/index.js:72:32)
    at constructor ([...]/node_modules/@babel/parser/lib/index.js:358:12)
    at Parser.raise ([...]/node_modules/@babel/parser/lib/index.js:3334:19)
    at Parser.jsxParseElementAt ([...]/node_modules/@babel/parser/lib/index.js:7983:16)
    at Parser.jsxParseElementAt ([...]/node_modules/@babel/parser/lib/index.js:7945:32)
    at Parser.jsxParseElementAt ([...]/node_modules/@babel/parser/lib/index.js:7945:32)
    at Parser.jsxParseElementAt ([...]/node_modules/@babel/parser/lib/index.js:7945:32)
    at Parser.jsxParseElementAt ([...]/node_modules/@babel/parser/lib/index.js:7945:32)
    at Parser.jsxParseElement ([...]/node_modules/@babel/parser/lib/index.js:8014:17)
    at Parser.parseExprAtom ([...]/node_modules/@babel/parser/lib/index.js:8028:19)
```

Same error using a `-` rather than a `*` as list delimiter.

Note: additionally, the automatic code reformatting in Code Sandbox doesn't enable to test the code block or the unordered list examples. The content indentation is removed, causing the code block example to fail.

### Your environment

- Public source code:
- Public site URL:
- Docusaurus version used:
- Environment name and version (e.g. Chrome 89, Node.js 16.4):
- Operating system and version (e.g. Ubuntu 20.04.2 LTS):

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by Josh-Cena** [comment]
This is a documented limitation here: https://docusaurus.io/docs/markdown-features/react#markdown-and-jsx-interoperability Namely, "Text immediately below a JSX tag will be seen as JSX text", and "Markdown text indented by four spaces will be seen as a code block". This will be fixed by the MDX v2 migration.
