### ISSUE TITLE
Feature request: Add contributors list for each doc

### ISSUE THREAD

**Issue by sunnylqm** [facebook/Docusaurus#858]
When cutting a version, use some git commands(`git blame --line-porcelain xxxx.md | grep -I "^author " | sort | uniq -c`) to get contributors info and add them to metadata or the header of each doc.

### Doc Title

`Contributors`: [foo](#)(60%), [bar](#)(40%)

...doc body...

I think this can encourage people to participate in improving docs.

**Comment by fiennyangeln** [comment]
Hi I'd like to work on this

**Comment by sunnylqm** [comment]
@fiennyangeln Here is my implementation which is quite rough https://github.com/reactnativecn/react-native-website/blob/production/cnwebsite/scripts/create-version.js  just for your reference

**Comment by fiennyangeln** [comment]
thanks 😄 @sunnylqm

**Comment by yangshun** [comment]
@fiennyangeln I'd recommend working on this feature in v2 instead with @endiliey. v2 code is now in the repository 😄
