### ISSUE TITLE
How do I use the component resolution md syntax in tsx to convert it to HTML?

### ISSUE THREAD

**Issue by 239573049** [facebook/docusaurus#8584]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Description

How do I use the component resolution md syntax in tsx to convert it to HTML?
I don't want to generate documents statically, I want to use some of the features of md to make it dynamic! So I need to render the MD-parsing html in tsx

### Self-service

- [X] I'd be willing to address this documentation request myself.

**Comment by slorber** [comment]
I don't understand what you want to do.

Docusaurus is using MDX to compile markdown to React components. You can "make it more dynamic" by embedding React components inside Markdown already, so not sure what you mean here that we do not provide already.

If you want to render markdown at runtime, you can embed your own React markdown renderer inside Docusaurus.

---

Note: this is a question, not an issue, so I'm closing it.
