### ISSUE TITLE
Working fine in the local but not building when I run npm run build

### ISSUE THREAD

**Issue by shiva-sandupatla** [facebook/docusaurus#8589]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

I have a created a simple react component to display a **"blockly"** block using **`"blockly"`** npm package.

Now i have imported it in `docs/intro.mdx` file to display block. 

It is displaying fine without any errors in the development, but when i try to build the project to use in production. It shows below error

```bash

✔ Client


✖ Server
  Compiled with some errors in 31.13s



Module not found: Error: Can't resolve 'canvas' in 'C:\Users\SHIVA\Desktop\My files\professional\BlockySite\temp\docs\my-website\node_modules\jsdom\lib\jsdom'
[WARNING] {"moduleIdentifier":"C:\\Users\\SHIVA\\Desktop\\My files\\professional\\BlockySite\\temp\\docs\\my-website\\node_modules\\jsdom\\node_modules\\ws\\lib\\buffer-util.js","moduleName":"./node_modules/jsdom/node_modules/ws/lib/buffer-util.js","loc":"117:23-44","message":"Module not found: Error: Can't resolve 'bufferutil' in 'C:\\Users\\SHIVA\\Desktop\\My files\\professional\\BlockySite\\temp\\docs\\my-website\\node_modules\\jsdom\\node_modules\\ws\\lib'","compilerPath":"server"}
[WARNING] {"moduleIdentifier":"C:\\Users\\SHIVA\\Desktop\\My files\\professional\\BlockySite\\temp\\docs\\my-website\\node_modules\\jsdom\\node_modules\\ws\\lib\\validation.js","moduleName":"./node_modules/jsdom/node_modules/ws/lib/validation.js","loc":"122:24-49","message":"Module not found: Error: Can't resolve 'utf-8-validate' in 'C:\\Users\\SHIVA\\Desktop\\My files\\professional\\BlockySite\\temp\\docs\\my-website\\node_modules\\jsdom\\node_modules\\ws\\lib'","compilerPath":"server"}
[ERROR] Unable to build website for locale en.
[ERROR] Error: Failed to compile with errors.
    at C:\Users\SHIVA\Desktop\My files\professional\BlockySite\temp\docs\my-website\node_modules\@docusaurus\core\lib\webpack\utils.js:180:24
    at C:\Users\SHIVA\Desktop\My files\professional\BlockySite\temp\docs\my-website\node_modules\webpack\lib\MultiCompiler.js:554:14
    at processQueueWorker (C:\Users\SHIVA\Desktop\My files\professional\BlockySite\temp\docs\my-website\node_modules\webpack\lib\MultiCompiler.js:491:6)
    at processTicksAndRejections (node:internal/process/task_queues:78:11)
[INFO] Docusaurus version: 2.2.0
Node version: v16.15.0

```

I have confirmed that this error is only happening in docusaurus by creating a simple react app with this component and building it. You can find [here](https://github.com/shiva-sandupatla/sample-react-app)

### Reproducible demo

https://github.com/shiva-sandupatla/sample-docusaurus-app

### Steps to reproduce

1. npm install
2. npm run build

### Expected behavior

It should build the project to use it in production, but not building the project

### Actual behavior

```bash

✔ Client


✖ Server
  Compiled with some errors in 31.13s



Module not found: Error: Can't resolve 'canvas' in 'C:\Users\SHIVA\Desktop\My files\professional\BlockySite\temp\docs\my-website\node_modules\jsdom\lib\jsdom'
[WARNING] {"moduleIdentifier":"C:\\Users\\SHIVA\\Desktop\\My files\\professional\\BlockySite\\temp\\docs\\my-website\\node_modules\\jsdom\\node_modules\\ws\\lib\\buffer-util.js","moduleName":"./node_modules/jsdom/node_modules/ws/lib/buffer-util.js","loc":"117:23-44","message":"Module not found: Error: Can't resolve 'bufferutil' in 'C:\\Users\\SHIVA\\Desktop\\My files\\professional\\BlockySite\\temp\\docs\\my-website\\node_modules\\jsdom\\node_modules\\ws\\lib'","compilerPath":"server"}
[WARNING] {"moduleIdentifier":"C:\\Users\\SHIVA\\Desktop\\My files\\professional\\BlockySite\\temp\\docs\\my-website\\node_modules\\jsdom\\node_modules\\ws\\lib\\validation.js","moduleName":"./node_modules/jsdom/node_modules/ws/lib/validation.js","loc":"122:24-49","message":"Module not found: Error: Can't resolve 'utf-8-validate' in 'C:\\Users\\SHIVA\\Desktop\\My files\\professional\\BlockySite\\temp\\docs\\my-website\\node_modules\\jsdom\\node_modules\\ws\\lib'","compilerPath":"server"}
[ERROR] Unable to build website for locale en.
[ERROR] Error: Failed to compile with errors.
    at C:\Users\SHIVA\Desktop\My files\professional\BlockySite\temp\docs\my-website\node_modules\@docusaurus\core\lib\webpack\utils.js:180:24
    at C:\Users\SHIVA\Desktop\My files\professional\BlockySite\temp\docs\my-website\node_modules\webpack\lib\MultiCompiler.js:554:14
    at processQueueWorker (C:\Users\SHIVA\Desktop\My files\professional\BlockySite\temp\docs\my-website\node_modules\webpack\lib\MultiCompiler.js:491:6)
    at processTicksAndRejections (node:internal/process/task_queues:78:11)
[INFO] Docusaurus version: 2.2.0
Node version: v16.15.0

```

### Your environment

- Project: https://github.com/shiva-sandupatla/sample-docusaurus-app
- Docusaurus version used: 2.2.0
- Environment name and version : Node version: v16.15.0
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): Windows 11

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by Josh-Cena** [comment]
Could you use two commits: one scaffolding the initial website and one with your own code that reproduces the bug?

**Comment by shiva-sandupatla** [comment]
@Josh-Cena, I didn't get your question. Can you ask more brefily?

**Comment by Josh-Cena** [comment]
Your repro only has one commit, which initializes the entire thing. This makes it very hard for us to quickly locate which parts are the init template and which parts are your code that reproduces the error. I'm asking you to keep one commit's content to the output of `create-docusaurus` and put all your changes in a separate commit, so I can easily read the diff.

**Comment by shiva-sandupatla** [comment]
Sure! I have updated my repo now with two commits, please checkout https://github.com/shiva-sandupatla/sample-docusaurus-app

**Comment by slorber** [comment]
Blockly is a quite visual, canvas-based client-side lib.
Docusaurus is a static-site-generator running your site on both browser + Node.js

Visual things usually do not play well with Node.js, and you should make sure this code only runs on the client with our `<BrowserOnly>` component: https://docusaurus.io/docs/next/docusaurus-core#browseronly-example-library

Maybe Blockly can render in Node.js too, but they don't mention it anywhere I looked so I doubt it's the case.

**Comment by shiva-sandupatla** [comment]
@slorber, Thanks for your reply. 

1. Your `<BrowserOnly>` component is present only in the **`Canary`** version, I am using Docusaurus version: **2.2.0**
2. To work "blockly" in Node.js they have another npm package `node-blockly`, maybe I can try this.

**Comment by Josh-Cena** [comment]
@shiva-sandupatla `<BrowserOnly>` has been existent since the early alpha stage and is definitely in 2.2.0.

**Comment by shiva-sandupatla** [comment]
@Josh-Cena, but the typescript is saying that there is no module found 👇🏻 

![image](https://user-images.githubusercontent.com/47274553/216119380-46076708-8803-410c-b61b-1971b8ed61c9.png)

**Comment by Josh-Cena** [comment]
Did you follow our TypeScript setup? You need to make sure `@docusaurus/module-type-aliases` are available ambiently.

**Comment by slorber** [comment]
Most likely your TS setup is not up to date with our recommendations, notably the usage of TS Config with `"extends": "@tsconfig/docusaurus/tsconfig.json",`

Your sample repo does not even include any TS file

**Comment by shiva-sandupatla** [comment]
@slorber and @Josh-Cena Thanks alot for replying.

> Your sample repo does not even include any TS config file

@slorber,  Thanks for  pointing this out. This demo app i have initialized with JS but for my main project I have used typescript.

Sorry for the misconception about `<BrowserOnly>` component. This can be resolved. 

But is this the probelm with `blockly` if so how can i fix it using this package only.

Hoping with a postivie response 

Thanks

**Comment by slorber** [comment]
We don't know how to use blockly and can't help you more than we already did, but the doc is pretty clear on the path you should follow:


```js
import BrowserOnly from '@docusaurus/BrowserOnly';

const MyComponent = (props) => {
  return (
    <BrowserOnly fallback={<div>Loading...</div>}>
      {() => {
        const blockly = require('blockly');
        return ... // return some JSX using blockly here
      }}
    </BrowserOnly>
  );
};
```

**Comment by shiva-sandupatla** [comment]
Sure! I'll use BrowserOnly component and let you know if i any further issues.


Once again thanks alot @slorber and@Josh-Cena for helping me out.

**Comment by ChrisOwen101** [comment]
@shiva-sandupatla Manage to get this working? I'm in exactly the same situation as you trying to get blockly playing nice with Docusaurus
