### ISSUE TITLE
Error when using a single TabItem component within parent Tabs component

### ISSUE THREAD

**Issue by farlowdw** [facebook/docusaurus#8591]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

Using a single `TabItem` component within a parent `Tabs` component causes a `Uncaught TypeError: children.map is not a function` error (this was not the case before the recent `2.3.0` release, as far as I can tell).

With the new release, if I visit `/docs/success` in the linked example repo, where two `TabItem` components are nested within a parent `Tabs` component, then everything works fine:

![ill-3](https://user-images.githubusercontent.com/73953353/215189049-c05f2b4f-75e3-4631-985f-5c57174c89bf.png)

If, however, I visit `/docs/fail`, where a single `TabItem` component is within a parent `Tabs` component, then the page crashes due to a `children.map is not a function` error:

![ill-4](https://user-images.githubusercontent.com/73953353/215189332-c74ea6e4-04c5-42ac-8151-b1e7b8bd25d6.png)

Inspecting the console makes it clear why this error is occurring:

![ill-2](https://user-images.githubusercontent.com/73953353/215189414-5350eaad-30e2-4829-84cc-7c3cc1abe1dd.png)

After looking at [the file containing the offending line of code](https://github.com/facebook/docusaurus/blob/9c860ce419ff90fc852a2b2d465c7ca5b07128c5/packages/docusaurus-theme-classic/src/theme/Tabs/index.tsx#L124), I decided to log `children` and the error became clear. 

With a single item:

![log-1](https://user-images.githubusercontent.com/73953353/215189777-b92c39c5-b7b1-44cf-8e7e-707d1df92eb9.png)

With two items:

![log-2](https://user-images.githubusercontent.com/73953353/215189814-7fb679d7-ca1b-49fe-bc14-4e784aef540e.png)

A very superficial hack "resolves" the problem (at least in terms of getting the page not to crash):

<img width="677" alt="ill-1" src="https://user-images.githubusercontent.com/73953353/215189987-a1ad9980-9ccd-4c8d-ba91-da22fcbd44fc.png">

### Reproducible demo

https://stackblitz.com/edit/github-wahvzn

### Steps to reproduce

1. Visit the [repro link](https://stackblitz.com/edit/github-wahvzn?file=docs/fail.md) and observe the failure by navigating to `/docs/fail`. Then observe the success by visiting `/docs/success`.

### Expected behavior

Continuity in terms of how `TabItem` components are rendered. Plurality should not matter. There are cases where it may be desirable to use a single `TabItem` within `Tabs` such as illustrating how to do things in different coding languages but only having time in the moment to do so for a single language.

### Actual behavior

A page should not crash due to the presence of only a single `TabItem` within `Tabs`. I can't imagine this was an intentional design decision (since this worked fine in previous versions).

### Your environment

Repro demo and source code (made using docusaurus.new): https://stackblitz.com/edit/github-wahvzn?file=docs/fail.md

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by Josh-Cena** [comment]
Thanks for the report. Just curious: are you actually going to use a single tab item in production? Or is this just an annoyance for local development?

**Comment by farlowdw** [comment]
@Josh-Cena Mostly the latter; however, I do have one project with a bunch of single tabs currently because I'm lazy and have only added content for Python instead of other languages, as referenced in the expected behavior for this bug -- when I mentioned "there are cases" I was really referencing that project with suboptimal tab use.

**Comment by dabeeeenster** [comment]
+1 for 1 tab in Prod. I'm using this here: https://docs.flagsmith.com/clients/server-side#logging and IMHO this would be the most appropriate formatting, even tho 1 tab element sounds a bit odd, it works here.
