### ISSUE TITLE
Using Tabs will break with React 18 and Docusaurus v2.3

### ISSUE THREAD

**Issue by anaclumos** [facebook/docusaurus#8592]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

It will break when using Docusaurus v2.3 and React 18 with Tabs, when `yarn build`ing.

```
[ERROR] Docusaurus server-side rendering could not render static page with path /docs/in
tro.


Error: Missing getServerSnapshot, which is required for server-rendered content. Will revert to client rendering.
[ERROR] Unable to build website for locale en.
[ERROR] Error: Failed to compile with errors.
    at /sandbox/node_modules/@docusaurus/core/lib/webpack/utils.js:180:24
    at /sandbox/node_modules/webpack/lib/MultiCompiler.js:554:14
    at processQueueWorker (/sandbox/node_modules/webpack/lib/MultiCompiler.js:491:6)
    at processTicksAndRejections (node:internal/process/task_queues:78:11)
[INFO] Docusaurus version: 2.3.0
Node version: v16.15.1
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### Reproducible demo

https://codesandbox.io/s/hungry-hodgkin-2z1jdc

### Steps to reproduce

1. Install a fresh Docusaurus 2.3
2. `yarn add react@18 react-dom@18`
3. Add the following:
	```
	import Tabs from '@theme/Tabs';
	import TabItem from '@theme/TabItem';
	
	<Tabs>  
	<TabItem value="option 1" label="option 1">
	
	1
	
	</TabItem>  
	<TabItem value="option 2" label="option 2">
	
	2
	
	</TabItem>  
	</Tabs>  
	```
4. `yarn dev` works. `yarn build` fails.
5. 

### Expected behavior

The build should not fail.

### Actual behavior

The build fails.

### Your environment

- Public source code: https://codesandbox.io/s/hungry-hodgkin-2z1jdc
- Public site URL: https://2z1jdc.sse.codesandbox.io/docs/intro
- Docusaurus version used: 2.3
- Environment name and version (e.g. Chrome 89, Node.js 16.4): Node v16.15.1
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): CodeSandBox

### Self-service

- [X] I'd be willing to fix this bug myself.

**Comment by Josh-Cena** [comment]
Thanks for the report. This is due to the use of `useSyncExternalStore`.

**Comment by slorber** [comment]
Not sure to understand why you want to use React 18 here @anaclumos , we don't officially support it so do we really want to qualify this as a bug? Similarly, if you decide to use Docusaurus 2.3 with React 0.13, things will break 🤷‍♂️ 

Technically there's probably a way to make it work under React 18 but is it really worth it to invest time solving this? 
You could stick to React 17 until we provide official React 18 support?

**Comment by slorber** [comment]
Fix was easy so we'll merge/release it, but I don't particularly recommend React 18 for now. Other similar things might break and we don't even build our own site under React 18 with our CI so we are less likely to notice when things break.

PR: https://github.com/facebook/docusaurus/pull/8618

**Comment by slorber** [comment]
please test the canary release and let me know if this doesn't work. On a newly initialized site it works 👍

**Comment by incepter** [comment]
Hey @slorber ; I just had the same issue and I was coming here to create it :-) Thanks for resolving it alredy

I honestly didn't pay attention to react version support, I have it in my monorepo more than year now I didn't have problems.

The reason for me to use react 18 is that it I use it practically everywhere I use React. Especially in the monorepo of my library. I think I can downgrade react specifically for the docs package (I didn't know about this), but I think waiting for the patch is worth it. 

Please let us know when it may get released ? Thanks again.

**Comment by Josh-Cena** [comment]
Re: why many use React v18, it's because of the nice hooks like `useId()`, which is necessary for a11y.

**Comment by anaclumos** [comment]
Just an FYI, I use React 18 for useId() and https://github.com/shuding/react-wrap-balancer
