### ISSUE TITLE
Error when toggle theme: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by baur** [facebook/docusaurus#8594]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

I got an error when theme toggling

### Steps to reproduce

1. `npx create-docusaurus@latest my-website classic`
2. Just toggle the theme dark <> light

### Expected behavior

no error on the console 

### Actual behavior

```
Uncaught RangeError: Maximum call stack size exceeded.
    at dispatchChangeEvent (storageUtils.ts?10b8:23:1)
    at Object.set (storageUtils.ts?10b8:131:1)
    at storeColorMode (colorMode.tsx?7cd1:47:1)
    at eval (colorMode.tsx?7cd1:72:1)
    at onChange (colorMode.tsx?7cd1:72:1)
    at dispatchChangeEvent (storageUtils.ts?10b8:23:1)
    at Object.set (storageUtils.ts?10b8:131:1)
    at storeColorMode (colorMode.tsx?7cd1:47:1)
    at eval (colorMode.tsx?7cd1:72:1)
    at onChange (colorMode.tsx?7cd1:72:1)
```

<img width="641" alt="image" src="https://user-images.githubusercontent.com/2898361/215248715-8a225e16-e0b3-45f2-9868-519817e94242.png">

### Your environment

- Docusaurus version used: 2.3.0
- Environment name and version (e.g. Chrome 89, Node.js 16.4): Node 18
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): Windwos11

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by Josh-Cena** [comment]
Looks like it's due to #8486
