### ISSUE TITLE
npm reports 9 moderate and 14 high security vulnerabilities after installing 2.3.0

### ISSUE THREAD

**Issue by micrology** [facebook/docusaurus#8596]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [ ] I have tried the `npm run clear` or `yarn clear` command.
- [ ] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io.
- [ ] I have read the console error message carefully (if applicable).

### Description

Running (as advised):
```
npm i @docusaurus/core@latest @docusaurus/preset-classic@latest @docusaurus/module-type-aliases@latest
```
results in 
```
23 vulnerabilities (9 moderate, 14 high)

To address issues that do not require attention, run:
  npm audit fix

Some issues need review, and may require choosing
a different dependency.

Run `npm audit` for details.
```
Running `npm audit fix` makes no difference.

### Steps to reproduce

`npm i @docusaurus/core@latest @docusaurus/preset-classic@latest @docusaurus/module-type-aliases@latest`

### Expected behavior

No (or at least only a few low or medium) vulnerabilities reported

### Actual behavior

23 vulnerabilities (9 moderate, 14 high)

### Your environment

zsh on mac os using npm 8.19.2

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by Josh-Cena** [comment]
Please see https://github.com/facebook/docusaurus/issues/6394
