### ISSUE TITLE
Linking to images in docs broken when there is baseUrl

### ISSUE THREAD

**Issue by cckellogg** [facebook/Docusaurus#861]
## 🐛 Bug Report

Document image links are broken when the site has a baseUrl. Instructions for linking to images within documents are here https://docusaurus.io/docs/en/next/doc-markdown#linking-to-images-and-other-assets. However, this does not work when the site has baseUrl other than "/".

## To Reproduce

1. Create an assets folder within the docs folder and add an image there
2. Add a new document and link to that image (https://docusaurus.io/docs/en/next/doc-markdown#linking-to-images-and-other-assets)
3. Add a baseUrl to the siteConfig (/test/)
4. yarn start

## Expected behavior

Then image should show up.

## Actual Behavior

The image does not render.

## Reproducible Demo

Here is an example project showing how the image link is broken when a baseUrl is provided in the siteConfig.

https://github.com/cckellogg/tmpscratch

**Comment by endiliey** [comment]
Thanks for reporting this. Seems like a misleading documentation

Actually we should refer it to `(assets/` and we will replace it to `{baseUrl}/docs/assets/`
https://github.com/facebook/Docusaurus/blob/22f3a85a494ddf46bc29964a7989335a7dba4a9a/lib/server/docs.js#L79-L83

The RAW Markdown is below:
<img width="534" alt="correct-documentation" src="https://user-images.githubusercontent.com/17883920/42989419-56603566-8c32-11e8-96c6-a473577f28f0.PNG">

It got transformed into `{baseUrl}/docs/assets/` in the website
https://github.com/facebook/Docusaurus/blob/master/docs/api-doc-markdown.md
<img width="532" alt="wrong-documentation" src="https://user-images.githubusercontent.com/17883920/42989454-6fb11756-8c32-11e8-939f-38e852fd80cd.PNG">

Suggested workaround:
1. Link your images by using `/test/docs/assets/`
or
2. Link your images by using `/assets/`
