### ISSUE TITLE
How to click on the title in the sidebar to expand and hide.

### ISSUE THREAD

**Issue by XzMitsui** [facebook/Docusaurus#862]
I am learning to use Doususaurus and create my own website, of course, including the sidebar of the document, but at the moment I want to click on the title in the sidebar and bind to the page under the title (I call this the directory and sub Directory) Titles can be expanded and hidden. I seriously watched the introduction to scripts in the official documentation, but I am sorry that I have not got a solution.

**Comment by endiliey** [comment]
This is something that is not implemented yet. 

Closing this issue due to not following the issue template provided. You can open a new feature request issue if needed. 😉

**Comment by XzMitsui** [comment]
@endiliey Thanks for your answer.
