### ISSUE TITLE
Layout moves around when switching tabs (scroll position issue)

### ISSUE THREAD

**Issue by Tobbe** [facebook/docusaurus#8625]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [ ] I have tried the `npm run clear` or `yarn clear` command.
- [ ] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [ ] I have read the console error message carefully (if applicable).

### Description

Tab groups that are linked causes the page to jump when switching tabs

See this Tape that I recorded
https://s.tape.sh/bjAyxKyo

Maybe this was introduce with this change: https://github.com/facebook/docusaurus/pull/8486
Something about `useScrollPositionBlocker()` that doesn't work properly anymore.
https://github.com/facebook/docusaurus/blob/32384b761c0a8c6270c726a6649648418e3262a0/packages/docusaurus-theme-common/src/utils/scrollUtils.tsx#L185

### Reproducible demo

https://stackblitz.com/edit/github-k5xct4?file=blog/2021-08-01-mdx-blog-post.mdx

### Steps to reproduce

1. Go to the Blog in the Stackblitz preview pane to the right
2. Scroll down to the MDX post, it has the tabs example
3. Switch tabs and see how scroll behaves. Try both the first and the second tab group

### Expected behavior

Scroll position should be maintained when switching tabs

### Actual behavior

Page layout jumps

### Your environment

- Public source code:
- Public site URL:
- Docusaurus version used:
- Environment name and version (e.g. Chrome 89, Node.js 16.4):
- Operating system and version (e.g. Ubuntu 20.04.2 LTS):

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by slorber** [comment]
Thanks for reporting, will be fixed in https://github.com/facebook/docusaurus/pull/8628 and included in 2.3.1 today

We restored the scroll position a bit too early before the other tabs had the opportunity to render. I fixed it by queuing the scroll restoration at the end of all the pending React re-renders
