### ISSUE TITLE
Link to codesandbox under playground doesn't work 

### ISSUE THREAD

**Issue by jonsveswe** [facebook/docusaurus#8636]
### Have you read the Contributing Guidelines on issues?

- [x] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Description

Hi. The link to codesandbox here: [playground](https://docusaurus.io/docs/playground) doesn't work. It gives error:

```
-1 - Error: UNKNOWN_ERROR - 500 - {"error":"Error","message":"authorize error: pitcher-host-container didn't respond in 5s"} (500)

Version: 0df28d8
Environment: production
Event: PITCHER:ERROR
State: CONNECTING
Branch: docusaurus
```

(Stackblitz works)

### Self-service

- [ ] I'd be willing to address this documentation request myself.

**Comment by jonsveswe** [comment]
Now it works.

**Comment by Josh-Cena** [comment]
I also think it works :)
