### ISSUE TITLE
Broken Links for Classes defined in an `index.ts` file

### ISSUE THREAD

**Issue by rbala19** [facebook/docusaurus#8644]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [x] I have tried the `npm run clear` or `yarn clear` command.
- [x] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

Currently running into the following build failure: 

```
[ERROR] Unable to build website for locale en.
[ERROR] Error: Docusaurus found broken links!

Please check the pages of your site in the list below, and make sure you don't reference any path that does not exist.
Note: it's possible to ignore broken links with the 'onBrokenLinks' Docusaurus configuration, and let the build pass.

Exhaustive list of all broken links found:

On source page path = /dir/telemetry/modules/
   -> linking to .Config (resolved as: /dir/telemetry/classes/.Telemetry)
```

Telemetry is a class defined in the index folder of the telemetry package. I am able to access it on the doc site by using the URL postfix `/dir/telemetry/classes/index.Telemetry`. However, when other pages reference this class, they remove the index prefix, as seen in the broken link above. 

### Steps to reproduce

1. Define an npm package with a `/src` directory. 
2. Define `index.ts` and define a class in that index file. 
3. Provide the `package/src` as the entrypoint to the docusaurus typedoc plugin. 
4. Run `docusaurus build`. 

### Expected behavior

The link to the class in the documentation should contain `index.{className}`

### Actual behavior

The link to the class in the documentation contains `.{className}`

### Your environment

- Public source code:
- Public site URL:
- Docusaurus version used: Docusaurus/core 2.3.1, docusaurus-plugin-typedoc 0.18.0
- Environment name and version (e.g. Chrome 89, Node.js 16.4): Node.js 16.18.1 Typescript 4.8.3
- Operating system and version (e.g. Ubuntu 20.04.2 LTS):

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by Josh-Cena** [comment]
Closing in favor of https://github.com/facebook/docusaurus/issues/8665
