### ISSUE TITLE
Add custom admonition types directly in config file

### ISSUE THREAD

**Issue by artt** [facebook/docusaurus#8647]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Description

Provide a way for users to add a new type of admonition via config without the need to swizzle out the component.

### Has this been requested on Canny?

No.

### Motivation

Users were able to do this with `remark-admonitions` plugin. Now it seems like new admonitions features are not added there (for example, nested admonitions do not work if you use `remark-admonitions`). Swizzling out `Admonition` component is unsafe.

Users should be able to add custom types in `docusaurus.config` directly.

### API design

```jsx
module.exports = {
  presets: [
    [
      '@docusaurus/preset-classic',
      {
        docs: {
          admonitions: {
            tag: ':::',
            keywords: ['note', 'tip', 'info', 'caution', 'danger'],
            customTypes: [
              typeA: {
                // className, icon, color, etc.
              }
            ]
          },
        },
      },
    ],
  ],
};
```

### Have you tried building it?

The issue just came up and I haven't had time to fix it yet. Not sure if this is the right place.

### Self-service

- [ ] I'd be willing to contribute this feature to Docusaurus myself.

**Comment by artt** [comment]
Oh that's cool. This is not in the [2.3.1 doc](https://docusaurus.io/docs/markdown-features/admonitions#customizing-rendering-behavior) so I assume it will be implemented in the next version?

Regarding unsafe swizzling, 2.3.1 still lists `Admonition` as unsafe:

<img width="505" alt="image" src="https://user-images.githubusercontent.com/1711188/219256357-6f2bdecb-8693-4329-876e-50de40d68a3d.png">

But then I saw that you can simply wrap the component and pass in the icon via `iconProp`. So all is good now. Thanks!

**Comment by slorber** [comment]
It should have been in v2 but due to a cherry-pick mistake, it has never been backported. We'll keep it for v3 now, and only add minor smaller fixes in v2.
