### ISSUE TITLE
Reference style links below the truncate marker are not resolved in blog list

### ISSUE THREAD

**Issue by mezpahlan** [facebook/docusaurus#8653]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

I like using reference style links in Markdown.

```
[text[[1]

[1]: path/to/my/content
```

Instead of

```
[text](path/to/my/content)
```

I also like writing blog posts in Docusaurus but if I add a reference style link whose reference is _below_ the truncate marker then the link won't be rendered in the blog list. It _is_ however resolved when viewing the full blog post. I kinda understand why this doesn't work (because the blog list doesn't receive any content below the truncate marker) but the site compiles just fine without any breakages or warnings.

![image](https://user-images.githubusercontent.com/4974178/218078134-5da0c4fd-1923-4de7-9ecc-4e81d77c7680.png)

I am able to workaround this by including the reference above the truncate marker, however I prefer to place all references at the end of the document.

Now that I know what is happening I don't mind so much but the behaviour was confusing at first. I couldn't see this documented anywhere and there are no error / warning messages in the console.

### Reproducible demo

https://stackblitz.com/edit/github-xwf35k?file=blog/2021-08-26-welcome/index.md

### Steps to reproduce

1. Create a blog post.
2. Add a truncate marker.
3. Add a reference style link above the truncate marker with the reference below the maker.
4. View the blog post list.

### Expected behavior

The link in the blog post list works or an error message is printed in the console reporting a broken link.

### Actual behavior

The link is not rendered in the blog list page and the site compiles without error / warning messages.

### Your environment

- Docusaurus version used: 2.3.1

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by Josh-Cena** [comment]
Hi, this is very much working as intended. We don't plan to add more complexity to the relatively simple truncate feature. The best solution I can think of is to add a warning in our docs that the portion above the truncate marker must be standalone renderable Markdown.

**Comment by mezpahlan** [comment]
That would be perfect, thanks.
