### ISSUE TITLE
Scripts added via `head` in md/mdx not loaded during an internal link traversal

### ISSUE THREAD

**Issue by SheetJSDev** [facebook/docusaurus#8654]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

Consider a per-page script that is loaded in an MD or MDX file, like

```html
<head>
  <script type="text/javascript" src="https://cdn.sheetjs.com/xlsx-latest/package/dist/xlsx.full.min.js"></script>
</head>
```

This is correctly loaded when accessing the page directly, but is not loaded when the page is accessed by clicking an internal link.  Live codeblocks that work normally will fail in a redirect flow.

### Reproducible demo

https://git.sheetjs.com/sheetjs/docs.sheetjs.com

#### Reproduction in the SheetJS docs site

1) open https://docs.sheetjs.com/docs/demos/hosting/dropbox in your web browser and observe that both live codeblocks work.

2) in a new browser window, access https://docs.sheetjs.com/docs/demos/hosting/ then click on the "Dropbox" link.  Observe that the first codeblock fails with

```
ReferenceError: Dropbox is not defined
```

#### Simple reproduction in a new site

0) open a terminal window (tested in `zsh`) and navigate to a temp directory (typically `/tmp` on linux or macos systems)

1) create a new project:

```bash
npx create-docusaurus@latest my-website classic
cd my-website
```

2) set up [`theme-live-codeblock`](https://docusaurus.io/docs/api/themes/@docusaurus/theme-live-codeblock) using the official instructions:

```bash
npm i --save @docusaurus/theme-live-codeblock
cat <<EOF >>docusaurus.config.js 
if(typeof config.plugins == "undefined") config.plugins = [];
config.plugins.push("@docusaurus/theme-live-codeblock");
EOF
```

3) load script and add a live codeblock to a page:

```bash
cat <<EOF >> docs/tutorial-extras/manage-docs-versions.md

<head>
  <script type="text/javascript" src="https://cdn.sheetjs.com/xlsx-latest/package/dist/xlsx.full.min.js"></script>
</head>

\`\`\`jsx live
function XLSXVersion() {
  const [version, setVersion] = React.useState("");
  React.useEffect(() => { setVersion(XLSX.version); }, []);
  return <div>{version}</div>
}
\`\`\`
EOF
```

4) build site and serve:

```bash
npm run build
npm run serve
```

5) open a web browser and access http://localhost:3000/docs/tutorial-extras/manage-docs-versions .  Scroll down to the bottom of the page to confirm the live codeblock worked (the result should be `0.19.2`)

6) open a new browser window and access http://localhost:3000/docs/category/tutorial---extras .   Scroll down and click on "Manage Docs Versions" in the page.  Scroll down and there will be a reference error in the live codeblock

```
ReferenceError: XLSX is not defined
```

### Expected behavior

The `script` children in the `head` tag should be loaded during the internal link traversal.

### Actual behavior

The link traversal does not load the scripts, as evidenced by the `ReferenceError` in the live codeblock and verified by visual inspection of the network pane of the devtools.

### Your environment

- Public source code: https://git.sheetjs.com/sheetjs/docs.sheetjs.com 
- Public site URL: https://docs.sheetjs.com/docs/demos/hosting/dropbox
- Docusaurus version used: latest

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by slorber** [comment]
What happens:
- On first load, the script tag gets loaded before React hydrates (that's how browsers work). React will only hydrate and make the live codeblock interactive once all the head scripts are loaded (unless you mark them as deferred)
- On navigation, the script tag is added but the React app is already hydrated and the live code block runs the code before the script finished loading. Browsers do not block everything for scripts that are appended after the first page load: if you want to block/wait you have to use JavaScript. You'll notice that if you navigate backward and then forward again now it works.

---
 

When you add a `<head><script>` tag that way, Docusaurus is only using [react-helmet-async](https://github.com/staylor/react-helmet-async) and is just doing what you ask it to do, add a script tag to head.

It is a quite low-level, generic solution, and does not involve any script loading orchestration. So this is not a bug, it's just your integration is not a good solution.

I would suggest one of these solutions:
- Don't use an external CDN URL, import a local JS file to make it part of the app page JS bundle. Docusaurus will load it before doing the page transition alongside the React code of that page
- Load the script globally: less performant but simple and just works
- Create your own preview system that waits for the appropriate scripts to be loaded before displaying the live previews.
