### ISSUE TITLE
High Severity CVE found in `cachable-request` <10.2.7

### ISSUE THREAD

**Issue by ajrice6713** [facebook/docusaurus#8661]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

A high-severity CVE has been found in cachable-request, which @docusaurus-core and @docusaurus-preset-classic depend on. 

Please see the [CVE notice](https://github.com/advisories/GHSA-8x6c-cv3v-vp6g) for more information, as this vulnerability leaves a DDOS vulnerability open. 

### Steps to reproduce

N/A

### Expected behavior

cachable-request version bumped to `v10.2.7` 

### Actual behavior

N/A

### Your environment

- Public source code:
- Public site URL:
- Docusaurus version used:
- Environment name and version (e.g. Chrome 89, Node.js 16.4):
- Operating system and version (e.g. Ubuntu 20.04.2 LTS):

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by Josh-Cena** [comment]
Could you give the dependency graph? `cachable-request` is not found in either our own repo or a newly scaffolded user site.

**Comment by ajrice6713** [comment]
Huh - even our [dependabot PR](https://github.com/Bandwidth/api-docs/security/dependabot/70) has been withdrawn for this CVE. Ive never seen that happen before 

Regardless - thanks for taking a look, looks like no action is needed here.
