### ISSUE TITLE
Use docusaurus in a Codespace

### ISSUE THREAD

**Issue by samruddhikhandale** [facebook/docusaurus#8666]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

I am looking forward to use `docusaurus` with a [GitHub Codespace](https://github.com/features/codespaces). In a codespace, the ports are forwarded to URLs like `https://${CODESPACE_NAME}-${PORT}.preview.app.github.dev/`, hence the current `npm start` doesn't work for me. 

I tried few ways to make this work, however, it looks like this isn't supported.

- `npm run start -- --host ${CODESPACE_NAME}-${PORT}preview.app.github.dev`
- `npm run start -- --host ${CODESPACE_NAME}-${PORT}.preview.app.github.dev --port ""`
- `HOST="${CODESPACE_NAME}-${PORT}.preview.app.github.dev/" PORT="" npm run start`

Would appreciate any help to get this working in a codespace, thanks!

### Steps to reproduce

NA

### Expected behavior

docusaurus works in a codespace

### Actual behavior

Error: listen EADDRNOTAVAIL: address not available

### Your environment

- Public source code:
- Public site URL:
- Docusaurus version used:
- Environment name and version (e.g. Chrome 89, Node.js 16.4):
- Operating system and version (e.g. Ubuntu 20.04.2 LTS):

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by slorber** [comment]
Sorry but this is not a bug report and our GitHub issues are not for questions.

Apparently, others have been successful using Codespace with Docusaurus so it must be possible, and you'd rather look for answers in existing issues: https://github.com/facebook/docusaurus/search?q=codespace&type=issues
