### ISSUE TITLE
@docusaurus/types's peerDeps are legacy react and react-dom

### ISSUE THREAD

**Issue by HomyeeKing** [facebook/docusaurus#8671]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [ ] I have tried the `npm run clear` or `yarn clear` command.
- [ ] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io.
- [ ] I have read the console error message carefully (if applicable).

### Description

@docusaurus/types's peerDeps are legacy react and react-dom

it's very easy to get error when install deps, by the way as a type package, it should  be have nothing to do with specific package version

### Steps to reproduce

xxx

### Expected behavior

xxx

### Actual behavior

xxx

### Your environment

- Public source code:
- Public site URL:
- Docusaurus version used:
- Environment name and version (e.g. Chrome 89, Node.js 16.4):
- Operating system and version (e.g. Ubuntu 20.04.2 LTS):

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by slorber** [comment]
> @docusaurus/types's peerDeps are legacy react and react-dom

I don't understand what you mean sorry.

Docusaurus is still on React 17. Please provide more info on what the problem is and how to reproduce it using a newly initialized project, and how it is blocking or annoying you exactly.
