### ISSUE TITLE
static json file not being served in build

### ISSUE THREAD

**Issue by bwgjoseph** [facebook/docusaurus#8676]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

I am using [docusaurus-json-schema-plugin](https://github.com/jy95/docusaurus-json-schema-plugin) and the json file stored in `static` directory is not being resolved (or loaded).

I have first reported the issue at https://github.com/jy95/docusaurus-json-schema-plugin/issues/17. Author suggested to report with `docusaurus` instead.

---

Below is a copy of what I reported

I created a page to display all my json-schema (i,e /schema), I used `schema.mdx` file to display it

![image](https://user-images.githubusercontent.com/37484538/219557827-026ced3c-67cf-4233-b4c7-ae6aff296313.png)

In each of the `mdx` file, it looks something like this but importing different json file

```mdx
import JSONSchemaViewer from "@theme/JSONSchemaViewer"
import schema from "@site/static/schema/geo.json"

<JSONSchemaViewer schema={schema} />
```

In local development, it works as expected.

![image](https://user-images.githubusercontent.com/37484538/219557687-499d43c5-ee33-4211-89d9-8fb4050bd05f.png)

But when I build and serve it, it doesn't load the content

![image](https://user-images.githubusercontent.com/37484538/219557465-ddd910bd-f42c-4959-a005-13822083c3d6.png)

Not sure if it matters but I'm using `javascript` setup of `docusaurus` instead of `typescript`. 

---

I've tried `require` as well

```js
import JSONSchemaViewer from "@theme/JSONSchemaViewer"
var schema = require('@site/static/schema/geo.json')

<JSONSchemaViewer schema={schema} />
```

```js
import JSONSchemaViewer from "@theme/JSONSchemaViewer"
const schema = require('@site/static/schema/geo.json').default

<JSONSchemaViewer schema={schema} />
```

### Steps to reproduce

1. install `docusaurus-json-schema-plugin`
2. create `geo.json` file in `/static/schema/`
```json
{
    "$id": "https://example.com/geographical-location.schema.json",
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "title": "Longitude and Latitude Values",
    "description": "A geographical coordinate.",
    "required": [ "latitude", "longitude" ],
    "type": "object",
    "properties": {
      "latitude": {
        "type": "number",
        "minimum": -90,
        "maximum": 90
      },
      "longitude": {
        "type": "number",
        "minimum": -180,
        "maximum": 180
      }
    }
  }
```

4. create `geo.mdx` with the following

```js
import JSONSchemaViewer from "@theme/JSONSchemaViewer"
// this
var schema = require('@site/static/schema/geo.json')
// or this
const schema = require('@site/static/schema/geo.json').default
// or this
import schema from "@site/static/schema/geo.json"

<JSONSchemaViewer schema={schema} />
```

### Expected behavior

Expects the json file to be loaded, and display the content

### Actual behavior

See description above

### Your environment

- Public source code: 
- Public site URL:
- Docusaurus version used: 2.3.1
- Environment name and version (e.g. Chrome 89, Node.js 16.4): Chrome 110
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): Windows 10

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by slorber** [comment]
Please invest your own time to create a repro and I'll look into it
