### ISSUE TITLE
Location of swCustom option for plugin-pwa

### ISSUE THREAD

**Issue by dtlhlbs** [facebook/docusaurus#8680]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Description

I'm trying to follow the example for plugin-pwa to add an `swCustom` option. I'm assuming this is a file path like the value for `swRegister`, but the docs don't clarify the expected value.

I've tried using all sorts of paths, but I get `Error: Can't resolve '/swCustom.js'`. Can you clarify where this file would be found by the plugin-pwa config?

At the moment I just have the option as 

```
        swCustom: '/swCustom.js'
```

### Self-service

- [ ] I'd be willing to address this documentation request myself.

**Comment by dtlhlbs** [comment]
Ok, somehow I missed the relative to the root path

Location of file: `/src/js/swCustom.js`
Plugin option config: `swCustom: '/src/js/swCustom.js'

**Comment by Josh-Cena** [comment]
I was just about to investigate :) Glad you figured it out.
