### ISSUE TITLE
Docusaurus doesn't respect the $PORT environment variable

### ISSUE THREAD

**Issue by seyoon20087** [facebook/docusaurus#8681]
**NOTE: If you believe this is a question please convert it to a discussion (rather than closing it), cf https://bit.ly/3YWp3GJ

### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

Docusaurus is not respecting the $PORT environment variable.

For example if I specify `env PORT=8000 yarn start` it will start on port 3000 and not on 8000.

### Reproducible demo

https://github.com/seyoon20087/docusaurus-reproduction-port-env-not-respecting

### Steps to reproduce

1. Clone that repository
2. Install dependencies (`yarn`)
3. Attempt to start the server at port 8000, using `env PORT=8000 yarn start`
4. The server will start at port 3000 and not 8000

### Expected behavior

I expected that the server should start in the port on the $PORT environment variable specified

### Actual behavior

The server will start on 3000 if I don't use `--port` option.
This is different from other frameworks (like Next.js), which they respect the $PORT environment variable.

For your reference here is the screenshot:
![image](https://user-images.githubusercontent.com/24852454/219854009-d33a3ba3-d118-4f30-8859-b17a325fb4e7.png)

### Your environment

- Public source code: https://github.com/seyoon20087/docusaurus-reproduction-port-env-not-respecting
- Public site URL: Not relevant
- Docusaurus version used: 2.3.1 -- note that this issue applies to any current Docusaurus version
- Environment name and version (e.g. Chrome 89, Node.js 16.4): Node.js 16.19.0
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): Gitpod (Ubuntu 20.04.5 container)

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by Pranav2612000** [comment]
@Josh-Cena are you interested in fixing this? I'll like to work on this

**Comment by pinakipb2** [comment]
Check -> https://docusaurus.io/docs/cli#docusaurus-cli-commands
```bash
yarn run start --port 8000
```
