### ISSUE TITLE
Same file and folder name not working with page links

### ISSUE THREAD

**Issue by deepaksood619** [facebook/docusaurus#8682]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

When the file name and folder name is same in docusaurus, then self link like `[About me](about-me/about-me)` in docs is not working, since link is going to `docs/about-me/about-me` but the url that is built is `docs/about-me`.

If I change the link to `[About me](about-me)` then link is working but then the link is not recognized in vscode+foam or obsidian.

And If I keep the folder name and file name different then folder doesn't become a page, and also breadcrubs doesn't work.

I have tried all the combinations of links of About me, ex -

```md
1. [About me](about-me/about-me)
2. [About me](./about-me)
3. [About me](./about-me/)
4. [About me](./about-me/about-me)
5. [About me](./about-me/about-me/)
6. etc
```

How to get links working in both docusaurus build-deploy and in obsidian too, with same folder and file name.

A solution should be that instead of only generating `about-me` it should generate `about-me/about-me` as web link

Ex - In this page https://deepaksood619.github.io/docs/databases/sql-databases/aaa-outline if I click memsql it goes to https://deepaksood619.github.io/docs/databases/sql-databases/memsql/memsql but it gives 404, but if I remove last memsql, it works i.e. https://deepaksood619.github.io/docs/databases/sql-databases/memsql/ , since both folder name and file name is memsql and memsql.md respectively. 

I am able to navigate via sidebar correctly and breadcrumb is working, but links doesn't work.

### Steps to reproduce

Create folder name and file name same, and add link to that page using `[About me](about-me/about-me)` the link after build should generate `about-me/about-me` instead of `about-me`

### Expected behavior

Both links i.e. local links and generated links should work

### Actual behavior

It only generates `about-me` link using which local navigation using obsidian or vs-code+foam doesn't work

### Your environment

- Public source code: https://github.com/deepaksood619/deepaksood619.github.io/blob/main/docs/databases/sql-databases/aaa-outline.md
- Public site URL: https://deepaksood619.github.io/docs/databases/sql-databases/aaa-outline
- Docusaurus version used: 2.3.1
- Environment name and version (e.g. Chrome 89, Node.js 16.4): node 19
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): ubuntu-latest, Ubuntu 22.10 for github actions, local - macbook

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by Josh-Cena** [comment]
Hi, this is a feature. Please see https://github.com/facebook/docusaurus/issues/7725. If you want to link to that file, use `[About me](./about-me/about-me.md)`.
