### ISSUE TITLE
Provide official TypeScript playgrounds in Documents

### ISSUE THREAD

**Issue by tats-u** [facebook/docusaurus#8685]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Description

I want to create TypeScript playgrounds on CodeSandbox or StackbBitz to reproduce issues on TypeScript, but there seems to be no one found.
The documents should clarify whether Docusaurus recommend to modify non-TypeScript starter by following the <https://docusaurus.io/docs/typescript-support> instruction or not.

This affects on a sentence of the bug template:

> I have tried creating a repro with https://new.docusaurus.io/.

### Self-service

- [ ] I'd be willing to address this documentation request myself.

**Comment by slorber** [comment]
> I want to create TypeScript playgrounds on CodeSandbox or StackbBitz to reproduce issues on TypeScript, but there seems to be no one found.

We can open any [Docusaurus example project](https://github.com/facebook/docusaurus/tree/main/examples) in both playgrounds easily with URLs. Is this what you are looking for?

- https://stackblitz.com/github/facebook/docusaurus/tree/main/examples/classic-typescript
- https://codesandbox.io/p/sandbox/github/facebook/docusaurus/tree/main/examples/classic-typescript


Do you want these links to appear on that page? https://docusaurus.io/docs/playground
That makes sense to me.

---

> The documents should clarify whether Docusaurus recommend to modify non-TypeScript starter by following the [docusaurus.io/docs/typescript-support](https://docusaurus.io/docs/typescript-support) instruction or not.

Not sure to understand what you mean here 😅 Which section should contain which extra text? Can you roughly draft the text we should add here?

---

Note these playgrounds usually have their own "shortcuts": for example StackBlitz permit to easily open any GitHub URL in StackBlitz by pretending `pr.new` to a GitHub URL: 
https://pr.new/github.com/facebook/docusaurus/tree/main/examples/classic-typescript

That's probably out of the scope of Docusaurus to document that, but still good to know it exists ;)

**Comment by tats-u** [comment]
@slorber 
> Is this what you are looking for?
> Do you want these links to appear on that page?

Exactly. Bingo.

Also, I'd be happy if you provide <docusaurus.new/ts>.

## Candidate:

### # 1

Add URLs below

> Choose one of the available options below.
>
> □ □ (current links for JS)
>
> If you prefer TypeScript, use the following options instead:
>
> □ □ (above URLs)

### # 2

Use tabs

> Choose one of the available options below.
>
> JavaScript  TypeScript
> ￣￣￣￣
> □ □ (current links for JS)

**Comment by slorber** [comment]
Thanks

I'd prefer to use directly visible buttons rather than less visible links inside tabs. A playground should be accessible in a single click IMHO

We already use buttons:

<img width="1001" alt="CleanShot 2023-02-23 at 16 53 05@2x" src="https://user-images.githubusercontent.com/749374/220960117-e05e8cc0-34d9-4f28-ac78-89be95859039.png">


> Also, I'd be happy if you provide:
> 
> * [docusaurus.new/ts](https://docusaurus.new/ts)
> * [docusaurus.new/codesandbox-ts](https://docusaurus.new/codesandbox-ts)
> * [docusaurus.new/stackblitz-ts](https://docusaurus.new/stackblitz-ts)
> 

We can provide that for sure, but how do you plan to use these URLs exactly?

**Comment by tats-u** [comment]
`[/-]ts` suffix is easy to remember and type, isn't it?
These URLs can be easily used to be not only directly typed but also linked from that page.

![image](https://user-images.githubusercontent.com/12870451/221398972-b9e11073-33f2-41f7-8438-68b2f1ddb38c.png)

Do you want a appearance like this if you don't want to use tab?

![image](https://user-images.githubusercontent.com/12870451/221398914-32d0c881-c569-4d43-be0d-83884135098c.png)

**Comment by tats-u** [comment]
@slorber 

> Not a perfect design 

I think so too because it is the best one in those without custom style sheets.

In the honest I wanted to get it done by myself but have to show my appreciation to you because you got it done on behalf of me.
Thank you so much.

**Comment by slorber** [comment]
NP

I did it myself because our Netlify serverless function stuff needed here is not really documented and it would have required explaining all this. Now if you want to improve the UX/design of this page even more, feel free to work on that ;)
