### ISSUE TITLE
Newly created project doesn't start

### ISSUE THREAD

**Issue by Tandashi** [facebook/docusaurus#8688]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

Creating a new project and then running it does not work as expected.

**Also**: I am not the only one with that Issue. Currently, **3+** people in the Discord also mentioned to have that exact problem.

PS: CodeSandback seems to work because it uses cached dependencies
(Using the `yarn.lock` and installing with `yarn install --force --pure-lockfile` works. Looks like a dependency issue)

### Steps to reproduce

```bash
npx create-docusaurus@latest my-website classic --typescript

# cd into the directory

npm run start
```

### Expected behavior

Seeing the template wiki without a problem

### Actual behavior

Seeing the following error
![image](https://user-images.githubusercontent.com/18377875/220181383-9a9cba13-91ec-424c-8f48-1dab989a6f85.png)

### Your environment

- Docusaurus version used: 2.3.1
- Environment: Latest Vivaldi (5.7.2921.53) & Nodejs 19.5.0 (also tested with 18.14.0)
- Operating system: MacOS Catalina

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by Josh-Cena** [comment]
Thanks for reporting. This is an upstream issue: https://github.com/babel/babel/issues/15444

**Comment by zph** [comment]
The resolution @Josh-Cena mentioned in meantime that works:

Set back the babel/generator version to 7.20.0 from 7.21.0 in package.json
```
{
  "name": "website",
  "version": "0.0.0",
  "private": true,
  "overrides": {
    "@babel/generator": "7.20.0"
  },
....
}
```

**Comment by CalvinWilkinson** [comment]
@zph Thanks for the workaround but I have been running into some issues, which are probably my fault.

I went into the JSON file and added the `overrides` section into the _**package.json**_ file. After that, I deleted the _**package-lock.json**_, deleted the _**node_modules**_ folder, and then ran the following commands.

1. `yarn install`
    > **Note** I also tried the command `yarn install --force --pure-lockfile`
3. `yarn start`

I still get the same issue.  I am sure that I am missing something but I don't know what it is.  
Could you possibly assistance me with this workaround?

**Comment by BizH** [comment]
@CalvinWilkinson - the `overrides` block works if you are using `npm`. If you are using `yarn`, use the `resolutions` block:

```
 "resolutions": {
    "@babel/generator": "7.20.0"
  },
```
