### ISSUE TITLE
Can't able to redirect link

### ISSUE THREAD

**Issue by Guddu0799** [facebook/docusaurus#8691]
### Have you read the Contributing Guidelines on issues?

- [x] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Description

Hello! 
The redirect link is not working for me. Please help

I tried with both code and it didn't worked. I don't know what mistake I am doing.

<img width="398" alt="image" src="https://user-images.githubusercontent.com/108795464/220376186-50f58fde-7c3a-4aad-abc6-31b203d108d9.png">

<img width="370" alt="image" src="https://user-images.githubusercontent.com/108795464/220376566-2a63b061-403f-461a-9723-655af991735e.png">

<img width="947" alt="image" src="https://user-images.githubusercontent.com/108795464/220375933-b53a0e85-cb29-488d-a483-910719208dca.png">

### Self-service

- [x] I'd be willing to address this documentation request myself.

**Comment by slorber** [comment]
show us a live site url where this doesn't work

most likely you didn't read that the client-side redirects plugin only works on production builds and not in the dev server

**Comment by Guddu0799** [comment]
Yes, you are right. I did not read this one. After reading it, I closed it. 😅

<img width="548" alt="image" src="https://user-images.githubusercontent.com/108795464/220719105-9b6b8227-c5f0-44ae-8f38-c3a26e445201.png">

Thanks for replying! If I have any issue regarding docusaurus, I'll ask. 🙏🏻
