### ISSUE TITLE
Improve docs navbar items error messages

### ISSUE THREAD

**Issue by slorber** [facebook/docusaurus#8696]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Motivation

The navbar error messages are not so great and some new users get confused when they encounter an error trying to modify a newly initialized Docusaurus project.

I think we should improve these error messages so that users understand what to do:

![image](https://user-images.githubusercontent.com/749374/220704671-273f6d4d-7b05-4cdb-b7e8-e0857597b3f3.png)

cf https://github.com/facebook/docusaurus/discussions/8692

Also we could introduce a new `docSidebar` navbar item that links to a given sidebar. This is less likely to lead users to encounter errors when trying Docusaurus for the first time because they are less likely to delete/rename a sidebar IMHO.

The init template has an `tutorialSidebar` autogenerated sidebar: https://github.com/facebook/docusaurus/blob/main/examples/classic/sidebars.js

I suggest moving the init template from:

```js
navbar: {
        items: [
          {
            type: 'doc',
            docId: 'intro',
            position: 'left',
            label: 'Tutorial',
          },
        ],
      },
```

to

```js
navbar: {
        items: [
          {
            type: 'docSidebar',
            sidebarName: 'tutorialSidebar',
            position: 'left',
            label: 'Tutorial',
          },
        ],
      },
```

----

Good first issue for an external contributor that feels comfortable taking this task.

You can claim the issue here, but please submit a first draft PR within 24h.
Otherwise, someone else can claim it again and submit a new PR.

### Self-service

- [ ] I'd be willing to do some initial work on this proposal myself.

**Comment by KhalfounMehdi** [comment]
how should the error message look like ?

**Comment by KhalfounMehdi** [comment]
I'd like to work on this

**Comment by slorber** [comment]
Thanks @KhalfounMehdi , go ahead and submit a PR, we'll discuss the exact wording on the PR directly

> how should the error message look like ?

I don't know the exact wording we should use but it should help user figure out that the problem is in the Docusaurus config file, in one of the `themeConfig.navbar.items` items. Try to do your best to make the error helpful to users.

Considering the error message is thrown in a quite generic hook (used in multiple places), there are a few options we could use to improve the DX:

- use the new JS error cause feature to enrich the initial error with extra contextual info: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error/cause
- maybe add a React error boundary around the failing navbar item, and do not crash the app in case of error but show a red square or something?

Using error cause can probably be done this way inside DocNavbarItem:

```js
function useNavbarItemDoc(docId, docsPluginId) {
  try {
    return useLayoutDoc(docId, docsPluginId);
  } catch (e) {
    throw new Error(
      "There's a problem in a navbar item blabla, your Docusaurus config themeConfig.navbar.items is probably wrong blabla...",
      { cause: e }
    );
  }
}
```

**Comment by tannerdolby** [comment]
👋 @slorber I've started tinkering on this locally based on your notes above, if there isn't a PR by another contributor up in the next few days I'm happy to submit one!

**Comment by slorber** [comment]
@tannerdolby feel free to work on it.

> You can claim the issue here, but please submit a first draft PR within 24h.
> Otherwise, someone else can claim it again and submit a new PR.

The first to open a draft PR showing they are actually working on this will be assigned the issue.

**Comment by slorber** [comment]
Just figured out we already have a `docSidebar` navbar item type and there's already a PR proposing to change the type in our templates here: https://github.com/facebook/docusaurus/pull/8712

Improving the error messages remain a thing we should do.

**Comment by tannerdolby** [comment]
@slorber Okay sounds good! Thanks for the heads up. I will submit a PR that focuses on improving the error messages.

**Comment by slorber** [comment]
Fixed by https://github.com/facebook/docusaurus/pull/8712 and https://github.com/facebook/docusaurus/pull/8735
