### ISSUE TITLE
Page bundles / nested navigation

### ISSUE THREAD

**Issue by theletterf** [facebook/Docusaurus#871]
## 🚀 Feature

I'd like Docusaurus to feature something like Hugo's page bundles:

https://gohugo.io/content-management/page-bundles/

As far as I can tell, Docusaurus only allows for a single level of documentation: all docs are in the same folder and there's no depth beyond that level. This prevents from creating complex documentation. For instance, in Docusaurus I cannot have something like...

```
- Index.md
  - /assets
  - /section
     - index.md
     - another page
     - /assets
     -/subsection
             - index.md
             - /assets
```
## Have you read the [Contributing Guidelines on issues](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes.

## Motivation

Docusaurus cannot scale beyond very simple documentation projects if it doesn't support this sort of nesting.

## Pitch

I'd like to be able to have a folder structure within /docs and have the build process go through it recursively, and build an overall ToC out of it.

**Comment by endiliey** [comment]
@theletterf
> As far as I can tell, Docusaurus only allows for a single level of documentation: all docs are in the same folder and there's no depth beyond that level. 

This is not true. You can actually nest your doc as deep as you like.
Example:
https://github.com/olistic/warriorjs/tree/master/docs

**Comment by theletterf** [comment]
Ha! Then it _is_ possible after all. Going to look into that. I couldn't find any reference on that in the docs...

**Comment by endiliey** [comment]
You have to set the navigation on your own. (e.g: headerlinks). If you need high level TOC document, you can build your own markdown docs as a high level TOC doc. Else, high level TOC in sidebar might be possible as well (see #868)

Either way, I think the main point is that you can nest your docs so I'm closing this.

**Comment by theletterf** [comment]
Thanks!

**Comment by JoelMarcey** [comment]
@theletterf I thought we had the nested docs information on docusaurus.io, but maybe we didn't add it. 

Would you like to submit a PR to add the information? Probably either in https://docusaurus.io/docs/en/site-creation or https://docusaurus.io/docs/en/site-preparation?

**Comment by theletterf** [comment]
Sure.

**Comment by areohbe** [comment]
Nesting works fine for `*.md` files, but I am unable to link to any static assets in a bundled directory.

I've tried in a assets subdirectory `docs/foo/assets/bar-example.png` and in the root directory `docs/foo/bar-example.png`.

Is this supported?
