### ISSUE TITLE
Docusarus.io documentation menus don't work on mobile Safari

### ISSUE THREAD

**Issue by voidmain** [facebook/docusaurus#8714]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [ ] I have tried the `npm run clear` or `yarn clear` command.
- [ ] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io.
- [ ] I have read the console error message carefully (if applicable).

### Description

The Docusaurus.io documentation menus often don't work in mobile Safari. The hamburger menu often doesn't respond to click events and the table of contents menu doesn't either. Refreshing the page doesn't help.

At some point, after navigating around the docs using standard anchor tags (like the Next links at the bottom), the mobile nav begins to work.

Safari is somewhat notorious for these types of "works sometimes" issues with JavaScript. My guess is that the JavaScript that is handling the menus has a branch that fails in certain situations and that causes it to fail. Eventually the JavaScript is loaded properly and begins working, but that's only after numerous page loads and navigation.

Next time this happens I can try attaching to the desktop debugger and see what's up.

### Steps to reproduce

1. Open Safari on iOS
2. Navigate to the Docusaurus.io website
3. Open the hamburger (this one always seems to work) and click docs
4. Click the hamburger menu again and see if it opens

### Expected behavior

The menus should always work.

### Actual behavior

The menus periodically don't work.

### Your environment

- iOS 16.2

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by slorber** [comment]
That would indeed help if you could record a video or screenshot or send us the terminal output.

Keep in mind that if you are under a very slow network, the hamburger menu won't work until the JS has finished loading because it is not (yet) progressively enhanced. Most of the time you probably don't see it, but under bad networks this is likely more common.

**Comment by slorber** [comment]
Closing until someone show a video of the problem

**Comment by KevinNitroG** [comment]
@slorber I guess he was referencing this issue. In my case, it does even not appear with docusaurus but also some other sites. I guess it’s iOS and safari issue

https://github.com/user-attachments/assets/110e3f73-2796-4890-a978-790c3c14285a

**Comment by slorber** [comment]
> [@slorber](https://github.com/slorber?rgh-link-date=2025-03-02T07%3A56%3A04.000Z) I guess he was referencing this issue. In my case, it does even not appear with docusaurus but also some other sites. I guess it’s iOS and safari issue
> 
>  IMG_0366.MOV

I'm not sure what I'm supposed to see in this video. Are you trying to click UI elements and it does nothing?

If that's the case, it's probably because React does not hydrate to make the page interactive. In practice this means that the page is just HTML + CSS, and may not execute any of its JS. This can happen when you have bad network connections, and various other situations (see [Everyone has JavaScript, right?](https://www.kryogenix.org/code/browser/everyonehasjs.html))

See also https://github.com/facebook/docusaurus/issues/3030

**Comment by KevinNitroG** [comment]
> > [@slorber](https://github.com/slorber?rgh-link-date=2025-03-03T14%3A41%3A12.000Z) I guess he was referencing this issue. In my case, it does even not appear with docusaurus but also some other sites. I guess it’s iOS and safari issue
> > IMG_0366.MOV
> 
> I'm not sure what I'm supposed to see in this video. Are you trying to click UI elements and it does nothing?

Yes I was

> If that's the case, it's probably because React does not hydrate to make the page interactive. In practice this means that the page is just HTML + CSS, and may not execute any of its JS. This can happen when you have bad network connections, and various other situations (see [Everyone has JavaScript, right?](https://www.kryogenix.org/code/browser/everyonehasjs.html))
> 
> See also [#3030](https://github.com/facebook/docusaurus/issues/3030)

I don't think I was having a bad network connection :( It happens not only with Docusaurus but also some other sites

**Comment by slorber** [comment]
That can be anything mentioned here, including any browser extension that messes up with Docusaurus: https://www.kryogenix.org/code/browser/everyonehasjs.html

You might also have disabled JS in your browser. If this happens for many websites, it's probably not a Docusaurus problem.
