### ISSUE TITLE
How to upload site to ipfs?

### ISSUE THREAD

**Issue by gHashTag** [facebook/docusaurus#8721]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

It is not possible to load the website in ipfs due to the inability to change the baseUrl in the application code and not in the configuration
![F14609D0-7BA7-4E39-BD43-592E575B3973](https://user-images.githubusercontent.com/6774813/222334495-711eac9a-5894-4855-b561-6573c2b901a7.png)

### Steps to reproduce

It is enough to follow [this guide](https://medium.com/m/global-identity-2?redirectUrl=https%3A%2F%2Fbetterprogramming.pub%2Fa-guide-to-hosting-websites-on-ipfs-d2efad40ed3)
The project folder will be the build folder after launching yarn build

### Expected behavior

Site works!!! Wow🎉🎉🎉

### Actual behavior

Oh shit, site dead

### Your environment

- Public source code: https://github.com/DAO-999-NFT/faraway-kingdom (`react-site` folder)
- Public site URL: none
- Docusaurus version used: `2.3.1`
- Environment name and version (e.g. Chrome 89, Node.js 16.4): It doesn't matter
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): macos Ventura 13.2.1

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by Josh-Cena** [comment]
Please see https://github.com/facebook/docusaurus/issues/6645
