### ISSUE TITLE
npm2yarn "couldn't auto-convert command" error message

### ISSUE THREAD

**Issue by brianlagunas** [facebook/docusaurus#8732]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

When using the `npm2yarn` plugin, if you specify the shorthand command `npm start`, the plugin will display an error `# couldn't auto-convert command` when the Yarn tab is selected.

![image](https://user-images.githubusercontent.com/835562/222855733-6c673520-862c-4828-8832-45a1c1ef3b9b.png)

![image](https://user-images.githubusercontent.com/835562/222855648-12efccba-f6eb-4f2e-aa8d-aa40b61f694b.png)

If you provide the full command `npm run start` then there are no errors displayed in the Yarn tab.

![image](https://user-images.githubusercontent.com/835562/222855740-e1ce6dc0-421c-4eee-a8d2-0e8f7d54e99b.png)

![image](https://user-images.githubusercontent.com/835562/222855711-f899a823-2250-49d2-a095-23207aabbc18.png)

### Reproducible demo

https://stackblitz.com/edit/github-7sb7wc?file=docs%2Fintro.md

### Steps to reproduce

1. Run the stackblitz repro
2. Click the "Docusaurus Tutorial - 5min" button to be taken to the "./docs/intro.md"
3. Overserve the npm2yarn code blocks.

### Expected behavior

I expected the Yarn tab to properly display `yarn start` with no errors

![image](https://user-images.githubusercontent.com/835562/222857562-4501ed98-aeba-4484-958a-57c25eb8e782.png)

### Actual behavior

An error is displayed `# couldn't auto-convert command`

![image](https://user-images.githubusercontent.com/835562/222857597-77228d06-8bda-49d0-bb08-431b600a0cb4.png)

### Your environment

- Public source code: see stackblitz
- Public site URL: see stackblitz
- Docusaurus version used: 2.3.1
- Environment name and version (e.g. Chrome 89, Node.js 16.4): Node.js 18.13.0
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): Windows

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by slorber** [comment]
Indeed this issue exist in 2.3.1, but it's already fixed in main and planned to be backported for 2.4

Fixed as part of https://github.com/facebook/docusaurus/pull/8690

<img width="315" alt="CleanShot 2023-03-08 at 18 23 40@2x" src="https://user-images.githubusercontent.com/749374/223785063-bbc79233-d2c1-4bad-8f59-66f2736ed984.png">

**Comment by mateotop** [comment]
If someone gets the same error today, maybe the initial command is incorrect.

For example, I use `pnpm` and forgot that sometimes `npm` and `pnpm` commands are different.  
 My mistake was that I used `npm create something` instead of `npm init something`.

So I just wrote the correct `npm` command, and it works for me.

**Comment by mateotop** [comment]
Here is a little visual explanation 

## 1. Code
```mdx
# Git issue explain 

:::danger [Error message]
`"couldn't auto-convert command" `
:::


## Explanation 

<details>
<summary>
    Alternative way of installation
</summary>

### ⚙️ Example of error 
Incorrect command 

\\ ```bash npm2yarn
\\ npm create docusaurus
\\ ```

### ✅ Solution 
The correct command 

\\ ```bash npm2yarn
\\ npm init docusaurus
\\ ```

</details>

```
## 2. Pictures
![image](https://github.com/facebook/docusaurus/assets/105502841/d64bc4d4-5ab7-4686-8776-58fe94fe1518)

## 3. Gifs
![git explain 3](https://github.com/facebook/docusaurus/assets/105502841/6c25d9fd-a2db-448b-8e4d-28fd38e2bd69)
