### ISSUE TITLE
Code blocks syntax highlighting specified in markdown ignored

### ISSUE THREAD

**Issue by bettiolo** [facebook/Docusaurus#874]
## 🐛 Bug Report

Language syntax specified in markdown code blocks is ignored, eg ` ```js ` and ` ```text ` render the same output.

Today's (27th July) revision `#75538395beb3bcd7591f586877d5971c51d4f5db` in master was supposed to contain the fix for the language highlighting. 

In fact the css bug of `language- <lang>` is fixed and now the CSS attribute is `language-<lang>` without the space. This was fixed by https://github.com/facebook/Docusaurus/issues/840

### Have you read the [Contributing Guidelines on issues]

Yes

## To Reproduce

Create a `.md` file with the following content:

````text

---
title: EXAMPLE
---

```text
function $initHighlight(block, cls) {
  try {
    if (cls.search(/\bno\-highlight\b/) != -1)
      return process(block, true, 0x0F) +
             ` class="${cls}"`;
  } catch (e) {
    /* handle exception */
  }
  for (var i = 0 / 2; i < classes.length; i++) {
    if (checkCondition(classes[i]) === undefined)
      console.log('undefined');
  }
}

export  $initHighlight;
```

```js
function $initHighlight(block, cls) {
  try {
    if (cls.search(/\bno\-highlight\b/) != -1)
      return process(block, true, 0x0F) +
             ` class="${cls}"`;
  } catch (e) {
    /* handle exception */
  }
  for (var i = 0 / 2; i < classes.length; i++) {
    if (checkCondition(classes[i]) === undefined)
      console.log('undefined');
  }
}

export  $initHighlight;
```

````

## Expected behavior

I would expect the output to be highlighted differently between `text` and `js` code blocks, like this:

```text
function $initHighlight(block, cls) {
  try {
    if (cls.search(/\bno\-highlight\b/) != -1)
      return process(block, true, 0x0F) +
             ` class="${cls}"`;
  } catch (e) {
    /* handle exception */
  }
  for (var i = 0 / 2; i < classes.length; i++) {
    if (checkCondition(classes[i]) === undefined)
      console.log('undefined');
  }
}

export  $initHighlight;
```

```js
function $initHighlight(block, cls) {
  try {
    if (cls.search(/\bno\-highlight\b/) != -1)
      return process(block, true, 0x0F) +
             ` class="${cls}"`;
  } catch (e) {
    /* handle exception */
  }
  for (var i = 0 / 2; i < classes.length; i++) {
    if (checkCondition(classes[i]) === undefined)
      console.log('undefined');
  }
}

export  $initHighlight;
```

## Actual Behavior

With fixed code in master, highlightjs seems to ignore language syntax specified in the code block:

<img width="977" alt="screen shot 2018-07-27 at 16 47 44" src="https://user-images.githubusercontent.com/1333608/43331448-d8ac4182-91bd-11e8-89d1-87d4261669da.png">

As you can see the CSS class name is fixed but ignored.

## Reproducible Demo

> Use node 8

```bash
git clone https://github.com/bettiolo/docusaurus-hl-bug.git
cd docusaurus-hl-bug/website
npm install
npm start
```
A browser will open and will show the bug:

<img width="694" alt="screen shot 2018-07-27 at 17 26 25" src="https://user-images.githubusercontent.com/1333608/43333339-37d7715a-91c2-11e8-9536-891ab7b38ce1.png">

**Comment by endiliey** [comment]
Hi @bettiolo,

There is actually no `text` language in highlight.js, so it triggers the auto language detector defined in 
https://github.com/facebook/Docusaurus/blob/75538395beb3bcd7591f586877d5971c51d4f5db/lib/core/renderMarkdown.js#L57-L58

and `javascript` was detected

You can check the [supported languages here](https://github.com/highlightjs/highlight.js/tree/master/src/languages)

**Comment by bettiolo** [comment]
@endiliey I don't believe that it is the case, to avoid highlighting you use `no-highlight` or the alias `text`: https://github.com/highlightjs/highlight.js/blob/898bcd268fb684a6b94e0e817d0ec715178038be/src/highlight.js#L39

https://github.com/highlightjs/highlight.js/blob/898bcd268fb684a6b94e0e817d0ec715178038be/src/highlight.js#L91

**Comment by bettiolo** [comment]
This should be reopen and addressed for the `no-highlight/text/plain` scenario

**Comment by endiliey** [comment]
@bettiolo 👍 

Just wanted to address that `text` or `no-highlight` or `plain` is in fact not a language in highlight.js. Language are: `javascript`, `basic`, `bash` anything defined [here](https://github.com/highlightjs/highlight.js/tree/master/src/languages)

See https://github.com/highlightjs/highlight.js/blob/master/README.md#getting-started
`no-highlight/text/plain` is just a way to indicate in your css class to disable highlighting

> To disable highlighting altogether use the nohighlight class:
```
<pre><code class="nohighlight">...</code></pre>
```

I mentioned before that there is no no text language in highlight.js. This is the logic
https://github.com/facebook/Docusaurus/blob/75538395beb3bcd7591f586877d5971c51d4f5db/lib/core/renderMarkdown.js#L49-L51

which fallbacks to this auto language detector
https://github.com/facebook/Docusaurus/blob/75538395beb3bcd7591f586877d5971c51d4f5db/lib/core/renderMarkdown.js#L57-L58

You can try out https://npm.runkit.com/highlightjs and see that there is no `text` language
<img width="460" alt="language" src="https://user-images.githubusercontent.com/17883920/43475978-f14a9dbe-9529-11e8-9874-14164c0bdd74.PNG">

Anyway, #875 helped on supporting `text` language for code block style without any highlighting
