### ISSUE TITLE
How deploy multi docusaurus with a domain in diferenent folder?

### ISSUE THREAD

**Issue by tianyingchun** [facebook/docusaurus#8741]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Description

How deploy multi docusaurus with a domain in diferenent folder?

- www.example.com (with `nginx`)
-  /docs/projectA (`docusaurus site`)
-  /docs/projectB (`docusaurus site`)
- 

### Self-service

- [ ] I'd be willing to address this documentation request myself.

**Comment by slorber** [comment]
issues are not for questions

I'm still willing to help you but it's really hard to understand what you want to do: please try to explain better?
