### ISSUE TITLE
docusaurus start doesn't respect 0.0.0.0 as --host specification

### ISSUE THREAD

**Issue by AaronForce1** [facebook/docusaurus#8742]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

Running `docusaurus start --host 0.0.0.0` only allows for docusaurus to start on `localhost` as opposed to `0.0.0.0` as specified. `docusaurus serve` does not have this issue.

```
$ ./node_modules/.bin/docusaurus start --host 0.0.0.0
[INFO] Starting the development server...
[SUCCESS] Docusaurus website is running at: http://localhost:3000/

✔ Client
  Compiled successfully in 7.08s

client (webpack 5.75.0) compiled successfully
```

### Steps to reproduce

1. `npx create-docusaurus@latest my-website classic`
2. `npm install`
3. ./node_modules/.bin/docusaurus start --host 0.0.0.0`

### Expected behavior

Should expose on 0.0.0.0 instead of localhost

### Actual behavior

Is only restricted to localhost

### Your environment

- Public source code:
- Public site URL:
- Docusaurus version used:
- Environment name and version (e.g. Chrome 89, Node.js 16.4):
- Operating system and version (e.g. Ubuntu 20.04.2 LTS):

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by sarpere** [comment]
Hi,
You may want to try 
`npx docusaurus start --host 0.0.0.0`

**Comment by slorber** [comment]
Works for me on a newly initialized site as shown here:

<img width="1497" alt="CleanShot 2023-03-08 at 17 56 28@2x" src="https://user-images.githubusercontent.com/749374/223778368-443a4761-4d28-4678-9f7a-3310aa9ffa37.png">


Please give clearer repro instructions, and more importantly the Docusaurus version that you are using. I'm assuming you might not be on the latest version so I'm going to close for now.
