### ISSUE TITLE
Search bar results link and SearchPage don't load new results after first view

### ISSUE THREAD

**Issue by dtlhlbs** [facebook/docusaurus#8755]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

The _See all n results_ link at the bottom of the search modal from the search bar doesn't load new search results if the SearchPage is already loaded.

### Steps to reproduce

1. Go to https://docusaurus.io/
2. Search for "Admonition" using search bar
3. Scroll to bottom of modal to the _See all n results_ link
4. Select results link and view all results
5. Open the search bar on the top right and search for "Blog"
6. Scroll to bottom of modal to the _See all n results_ link
7. Select results link and view all results

### Expected behavior

URL changes to https://docusaurus.io/search?q=blog
Results for "Blog" would be displayed on the search results page

### Actual behavior

URL changes to https://docusaurus.io/search?q=blog
Results for "Admonition" are still displayed

### Your environment

https://docusaurus.io

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by slorber** [comment]
Thanks, will be fixed in https://github.com/facebook/docusaurus/pull/8757
