### ISSUE TITLE
Deep linking of headings inside Tabs don't work

### ISSUE THREAD

**Issue by Zenahr** [facebook/docusaurus#8764]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [ ] I have tried the `npm run clear` or `yarn clear` command.
- [ ] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io.
- [ ] I have read the console error message carefully (if applicable).

### Description

Given a deep-link to a heading via HTML anchor tags, the browser should focus the heading even if it's inside Tabs. This does not happen.

### Steps to reproduce

Given markdown like:

```markdown
<Tabs groupId="network-config-scenario" queryString>
  <TabItem value="GSM">

## Configuring a GSM network connection

...

<TabItem />
<Tabs />
```

### Expected behavior

Given a deep-link to a heading via HTML anchor tags, the browser should focus the heading even if it's inside Tabs.

### Actual behavior

URI when selecting the `Configuring a GSM network connection` anchor:  <...URL...>#configuring-a-gsm-network-connection (.e.g `http://localhost:3000/documentation/Guides/Configuring/networking#configuring-a-gsm-network-connection`) doesn't focus the heading, but instead opens the page at the top of the document.

### Your environment

- Docusaurus version used: 2.3.1
- Environment name and version (e.g. Chrome 89, Node.js 16.4): Chrome, Version 110.0.5481.177 (Official Build) (64-bit)
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): Windows 10

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by slorber** [comment]
https://github.com/facebook/docusaurus/pull/946
https://github.com/facebook/docusaurus/issues/5343
https://github.com/facebook/docusaurus/issues/8591

Going to close because it's not a bug: you should not use heading in tabs because we don't support that.

Although this feature would be useful, it has to go through the regular process of a feature request, design phase, and implementation.
