### ISSUE TITLE
Sporadic Website did not load properly error

### ISSUE THREAD

**Issue by ArthurFlageul** [facebook/docusaurus#8768]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io.
- [ ] I have read the console error message carefully (if applicable).

### Description

Regularly, I get the following message in my [production deployment](https://docs.talon.one): `your Docusaurus site did not load properly`.

![image](https://user-images.githubusercontent.com/28596581/224929142-f793e443-548a-4903-bfb2-958a1da5fa0a.png)

It's sporadic and I cannot reproduce it on demand to diagnose the issue or log any error. Typically, I refresh the page and it works. Why would the configuration be an issue in this case, since it's set to the recommended value?

Any idea how I could fix this? 

<details>

<summary>My config file</summary>

<pre><code>const YAML = require('yaml')
const fs = require('fs')
const path = require('path')

module.exports = {
  title: 'Talon.One docs',
  tagline: 'Learn how to use Talon.One.',
  url: 'https://docs.talon.one',
  baseUrl: '/',
  onBrokenLinks: 'throw',
  onBrokenMarkdownLinks: 'throw',
  favicon: 'favicon.ico',
  trailingSlash: false,
  organizationName: 'talon-one',
  projectName: 'docs',
  themeConfig: {
    docs: {
      sidebar: {
        hideable: false,
        autoCollapseCategories: true,
      },
    },
    algolia: {
      appId: 'I...,
      apiKey: '1...,
      indexName: 'talon',
      contextualSearch: true,
      searchParameters: {},
      //... other Algolia params
    },
    prism: {
      additionalLanguages: ['java', 'csharp', 'ruby', 'php', 'scala'],
      //theme: require('prism-react-renderer/themes/github'),
    },
    hotjar: {
      siteId: '2...',
    },
    navbar: {
      title: 'Talon.One',
      logo: {
        alt: 'Talon.One logo',
        src: 'img/logo-without-text.svg',
      },
      items: [
        {
          label: 'Product docs',
          position: 'left',
          type: 'doc',
          docId: 'product/understanding-talonone',
          sidebarId: 'product',
        },
        {
          label: 'Developer docs',
          position: 'left',
          type: 'docSidebar', 
          sidebarId: 'dev',
        },
        {
          label: 'API reference',
          type: 'dropdown',
          position: 'left',
          items: [
            {
              label: 'Integration API',
              to: '/integration-api',
            },
            {
              label: 'Management API',
              to: '/management-api',
            },
            {
              label: 'Third-party API',
              to: '/third-party-api',
            },
          ],
        },
        {
          href: 'https://www.talon.one/developer-access',
          position: 'right',
          label: 'Get developer access',
          className: 'navbar-btn-primary',
	 id: 'navbar_developeraccessdocs_cta'
        },
        {
          to: '/docs/product/whats-new',
          label: "What's new",
          position: 'right',
        },
      ],
    },
    footer: {
      style: 'light',
      logo: {
        alt: 'Talon.One logo',
        src: 'img/logo-monochrome.svg',
        href: 'https://www.talon.one',
      },
      links: [
        {
          title: 'Product documentation',
          items: [
            {
              label: 'Getting started',
              to: '/docs/product/getting-started',
            },
            {
              label: 'Subscribe to the newsletter',
              to: '/subscribe',
            },
            {
              label: 'Tutorials',
              to: '/docs/product/tutorials/overview',
            },
            {
              label: 'Talon.One website',
              href: 'https://www.talon.one',
            },
            {
              label: 'Blog',
              href: 'https://www.talon.one/blog',
            },
          ],
        },
        {
          title: 'Dev documentation',
          items: [
            {
              label: 'Integration API docs',
              to: 'integration-api',
            },
            {
              label: 'Management API docs',
              to: 'management-api',
            },
            {
              label: 'Third party API docs',
              to: 'third-party-api',
            },
            {
              label: 'Getting started',
              to: 'docs/dev/home',
            },
            {
              label: 'Tutorials',
              to: 'docs/dev/tutorials/overview',
            },
          ],
        },
        {
          title: 'Support',
          items: [
            {
              href: 'mailto:support@talon.one',
              label: 'Contact the support team',
            },
            {
              href: 'mailto:docs@talon.one',
              label: 'Contact the docs team',
            },
            {
              label: 'API status',
              to: 'https://status.talon.one',
            },
          ],
        },
        {
          title: 'Legal',
          items: [
            {
              href: 'https://www.talon.one/legal/imprint',
              label: 'Imprint',
            },
            {
              href: 'https://www.talon.one/legal/privacy-policy',
              label: 'Privacy',
            },
            {
              href: 'https://www.talon.one/legal/terms',
              label: 'Terms',
            },
          ],
        },
      ],
      copyright: `© ${new Date().getFullYear()} Talon.One GmbH. All rights reserved`,
    },
  },
  customFields: {
    heroBanner: 'img/building-blocks.png',
  },
  plugins: [
    path.resolve(__dirname, 'plugins/docusaurus-plugin-hotjar'),
    'docusaurus-plugin-sass',
    [
      require.resolve('docusaurus-gtm-plugin'),
      {
        id: 'GTV',
      },
    ],
    [
      '@docusaurus/plugin-client-redirects',
      {
        redirects: [
          {
            to: '/docs/dev/tutorials/rolling-back-effects', // 23 may 2022
            from: '/docs/dev/tutorials/rolling-back-budgets',
          },
          {
            to: '/docs/product/tutorials/loyalty/loyalty-custom-event', // 17 june 2022
            from: '/docs/product/tutorials/loyalty/paid-loyalty-program',
          },
          {
            to: '/docs/dev/tutorials/overview', // 2 dec 2022
            from: '/docs/docs/dev/tutorials/creating-twilio-webhook',
          }
        ],
      },
    ],
  ],
  presets: [
    [
      '@docusaurus/preset-classic',
      {
        gtag: {
          trackingID: 'U529-1',
          anonymizeIP: true,
        },
        docs: {
          sidebarPath: require.resolve('./sidebars.js'),
          // editUrl: 'https://github.com/talon-one/developer-docs/blob/main/',
        },
        theme: {
          customCss: require.resolve('./src/css/custom.css'),
        },
      },
    ],
    [
      'redocusaurus',
      {
        specs: [
          {
            id: 'mapi',
            route: '/management-api',
            spec: 'https://gist.githubusercontent.com/talononebot/32c52c9963f7cbee/raw',
          },
          {
            id: 'iapi',
            route: '/integration-api',
            spec: 'https://gist.githubusercontent.com/talononebot/b58ed79dd2033100/raw',
          },
          {
            id: '3api',
            route: '/third-party-api',
            spec: 'https://gist.githubusercontent.com/talononebot/0bafaa5c5704d9600/raw',
          },
          {
            id: 'outbound-notif',
            route: '/outbound-notifications',
            spec: './static/oas/outbound-notifications.yml',
          },
        ],
        theme: {
          primaryColor: '#047cff',
          options: {
            // See CE-dsupported options at
            // https://redocly.com/docs/api-reference-docs/configuration/functionality/#configuration-options-for-reference-docs
            hideDownloadButton: false,
            // hideHostname: true, ## must stay off since 3rdAPI needs the hostanme
            maxDisplayedEnumValues: 10,
            requiredPropsFirst: true,
            hideSchemaTitles: true,
            disableSearch: true,
            scrollYOffset: 55, // determined by the left toc. Anything lower than 50 breaks it.
            pathInMiddlePanel: true,
          },
        },
      },
    ],
  ],
}</code></pre>

</details>

### Steps to reproduce

1. Open the website.

### Expected behavior

The website loads.

### Actual behavior

The website displays an error. Only a refresh fixes it.

### Your environment

- Public source code:
- Public site URL: https://docs.talon.one
- Docusaurus version used: 2.3.1
- Environment name and version (e.g. Chrome 89, Node.js 16.4):
- Operating system and version (e.g. Ubuntu 20.04.2 LTS):

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by slorber** [comment]
This kind of error can happen in case your CDN is partially failing.

Notable it happens if your html file could be served, but your CSS file could not be served.

If this is not reproducible it's very likely a temporary CDN failure, so I'm going to close for now.

**Comment by markcarroll** [comment]
@slorber I am hitting this too.  Seems to repro by going to a page in the docs section and from there navigating to another doc page. Then changing the URL in the browser to a completely different site (such as GitHub.com) and the hitting the back button.  This seems to be relatively reproducible.  We are running on AWS hosting from S3 via CloudFront.

**Comment by slorber** [comment]
@markcarroll share your production url, and eventually record a video of the problem.

Could be a trailing slash issue, but impossible to be sure with only 3 lines of text and not any ability to experience the problem myself

**Comment by JnaneshD05** [comment]
@slorber I am facing a similar issue on my site - https://api.commvault.com. Version 2.2.0 docusaurus. The error shows up for a millisecond and goes away. Any help is appreciated

**Comment by slorber** [comment]
@JnaneshD05 I don't know what happens exactly but it looks like you have CSS that refuses to load for some reason.

I can't really help you support 2.2, and it is unlikely a Docusaurus bug if you are the only v2.x user reporting this, so make sure to double-check your own site setup.

A temporary workaround would be to hide this banner with CSS yourself:

```css
#docusaurus-base-url-issue-banner-container {
  display: none;
}
```

But to be honest you have other weird things on your site, that you can see if you use DevTools with network throttling to "Fast 3G".

Notably the site icon and the dark/light mode icons that do not render as they should:

<img width="207" alt="CleanShot 2024-01-18 at 11 57 37@2x" src="https://github.com/facebook/docusaurus/assets/749374/edeeda54-dd2f-491f-9b4b-4b4cfd0cab6c">

<img width="63" alt="CleanShot 2024-01-18 at 11 59 21@2x" src="https://github.com/facebook/docusaurus/assets/749374/87a7a3f2-6ca5-48ec-8cf2-6f8eebb8a807">

---

I'd recommend to upgrade to v3.1, and eventually try removing all your swizzle/customizations. Then if the issue is still there I'll be able to take a look and support you to fix it.
