### ISSUE TITLE
Add simple example and import statement to logger API docs

### ISSUE THREAD

**Issue by Zenahr** [facebook/docusaurus#8787]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Description

Affecting: https://docusaurus.io/docs/api/misc/@docusaurus/logger

At the very least, having sample code on how to **import** the logger and at one logger call would be great (simple usage, besides the template literal method, e.g. `logger.green("some text")`). That way, readers wouldn't have to browse the Docusaurus source code just to know how to use the logger package.

The logger is useful not just for plugin authors, but also if you've got any complex React components you'd like some logging on for errors etc.

### Self-service

- [ ] I'd be willing to address this documentation request myself.

**Comment by ArslanYM** [comment]
Can i work on this?

**Comment by ArslanYM** [comment]
ok john cena

**Comment by Zenahr** [comment]
@ArslanYM if you're eager to contribute, feel free to take on my MR #8704 (I was going to work on this in a couple days, but if  you'd like you can continue it.)
