### ISSUE TITLE
Custom path to doc

### ISSUE THREAD

**Issue by Tom910** [facebook/Docusaurus#884]
## 🚀 Feature

Implement the ability to store documentation in different directories in the application

## Have you read the [Contributing Guidelines on issues](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yep

## Motivation

It is more convenient to store the documentation

## Pitch

```
root-directory
├── docs
│   ├── architecture
│   │   └── store.md
│   └── components
│       └── request.md // < is link to request-doc.md
├── website
└── packages
    └── request
        ├── index.js
        └── request-doc.md
```
in request.md
```
---
id: request
title: Request
mdLink: ./packages/request/request-doc.md
---
```
or maybe in sidebars.json
```
{
  "docs": {
    "Components": [ "./packages/request/request-doc.md" ]
  }
}
```

**Comment by endiliey** [comment]
While this will be great, on versioned and/or internationalized documentation, this can be confusing as where to point the docs.

I think it will be a much more convenient and easier to write a small script to copy the docs on `packages/request/request-doc.md` to `docs/components/request.md` before you build your website.

WDYT ? @Tom910

**Comment by JoelMarcey** [comment]
So you can choose the directory where the docs are stored (via `customDocsPath`) and have subdirectories within there. But you are asking for docs in multiple directories -- and, as @endiliey hinted at, would require a bit of a re-architecture of how we process the documentation.

> customDocsPath - By default, Docusaurus expects your documentation to be in a directory called docs. This directory is at the same level as the website directory (i.e., not inside the website directory). You can specify a custom path to your documentation with this field.

**Comment by Tom910** [comment]
thanks, ok i will copy files before build
