### ISSUE TITLE
Shouldn't `hide_table_of_contents` be in camelCase?

### ISSUE THREAD

**Issue by Zwyx** [facebook/docusaurus#8841]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [ ] I have tried the `npm run clear` or `yarn clear` command.
- [ ] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io.
- [ ] I have read the console error message carefully (if applicable).

### Description

It seems that camelCase is the norm for front matter properties. Shouldn't [`hide_table_of_contents`](https://docusaurus.io/docs/next/api/plugins/@docusaurus/plugin-content-pages#hide_table_of_contents) be in camelCase?

There is also [`toc_min_heading_level`](https://docusaurus.io/docs/next/api/plugins/@docusaurus/plugin-content-blog#toc_min_heading_level) and [`toc_max_heading_level`](https://docusaurus.io/docs/next/api/plugins/@docusaurus/plugin-content-blog#toc_max_heading_level).

### Steps to reproduce

N/A

### Expected behavior

N/A

### Actual behavior

N/A

### Your environment

N/A

### Self-service

- [X] I'd be willing to fix this bug myself.

**Comment by Josh-Cena** [comment]
Hi, almost all front matter keys are snake_case. The only exception I know is `wrapperClassName`, but that's a legacy case.

**Comment by Zwyx** [comment]
Oh wow... I just realised that all other keys are actually a single word :facepalm: except `wrapperClassName` which completely biased my judgement :smile:

Thanks for your reply and sorry about that!
