### ISSUE TITLE
SVG not correctly rendered after build

### ISSUE THREAD

**Issue by makinghappen** [facebook/docusaurus#8850]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

SVG image included into main page featurelist not correctly rendered after build

`const FeatureList = [
  {
    title: 'We believe in «future of work»',
    Svg: require('@site/static/img/dodao/Ill-cat-future.svg').default,
    description: (
      <>
        Our goal is to bring “real-world-business” to blockchain to reduce recruiting- and service fees and providing transparency, immutability, scalability and accessibility.
      </>
    ),
    url: '/docs/intro'
  },
]`
![Ill-cat-star](https://user-images.githubusercontent.com/100151762/228984653-65637237-df4d-4283-8510-c73da0103bc3.svg)
![Ill-note](https://user-images.githubusercontent.com/100151762/228984656-40ec5139-7e24-4fc1-bbb5-6999f3a5ed40.svg)

### Reproducible demo

[https://docs.dodao.dev](https://docs.dodao.dev)

### Steps to reproduce

1. add Ill-cat-star.svg to HomepageFeatures/index.js
2. npx docusaurus build
3. see image not correctly rendered after build

### Expected behavior

SVG must be rendered correctly

### Actual behavior

probably because of the compression it is corrupted

### Your environment

- Public source code: https://github.com/devopsdao/dodao-docusaurus
- Public site URL: https://docs.dodao.dev
- Docusaurus version used: 2.4.0
- Environment name and version (e.g. Chrome 89, Node.js 16.4): nodejs 16.8
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): debian 11

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by slorber** [comment]
What does "rendered correctly" means?

Does it happen to all svgs or just one in particular.

Does it happen in the prod build or in dev too.

---

Show me a minimal repro where the code already has the SVG not rendering correctly.

Your repro does not even contain the SVG you reference here.

> Module not found: Error: Can't resolve '@site/static/img/dodao/Ill-cat-future.svg' in '/home/devopsdao/dodao-docusaurus/src/components/HomepageFeatures'

https://stackblitz.com/~/github.com/devopsdao/dodao-docusaurus

**Comment by makinghappen** [comment]
here is how it renders, see https://docs.dodao.dev

![image](https://user-images.githubusercontent.com/100151762/230343633-4c7aadc0-f584-4d3e-bf6e-8dd7b55cd1bb.png)
it both renders so in dev and prod builds.

@slorber have pushed the version published on https://docs.dodao.dev to the github repository.

**Comment by slorber** [comment]
Great, so what's the problem exactly? Isn't this rendering as it should? 

Show me your actual render vs expected render side by side and highlights the problem.
