### ISSUE TITLE
There are redundant asset files after packaging

### ISSUE THREAD

**Issue by hijulien** [facebook/docusaurus#8851]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

This is my project folder
![image](https://user-images.githubusercontent.com/103170141/229002936-9c429a0f-6477-4247-bc14-5b11b89653aa.png)
![image](https://user-images.githubusercontent.com/103170141/229002969-68970ece-587b-4be7-ba2f-9c568b10dbc9.png)
After packaging, these resource files in the build folder are redundant
![image](https://user-images.githubusercontent.com/103170141/229003136-7ad2bb99-5819-4763-8fdf-885dc126ee37.png)

### Steps to reproduce

This is my project folder
![image](https://user-images.githubusercontent.com/103170141/229002936-9c429a0f-6477-4247-bc14-5b11b89653aa.png)
![image](https://user-images.githubusercontent.com/103170141/229002969-68970ece-587b-4be7-ba2f-9c568b10dbc9.png)
After packaging, these resource files in the build folder are redundant
![image](https://user-images.githubusercontent.com/103170141/229003136-7ad2bb99-5819-4763-8fdf-885dc126ee37.png)

### Expected behavior

These three folders should not exist

### Actual behavior

This is my project folder
![image](https://user-images.githubusercontent.com/103170141/229002936-9c429a0f-6477-4247-bc14-5b11b89653aa.png)
![image](https://user-images.githubusercontent.com/103170141/229002969-68970ece-587b-4be7-ba2f-9c568b10dbc9.png)
After packaging, these resource files in the build folder are redundant
![image](https://user-images.githubusercontent.com/103170141/229003136-7ad2bb99-5819-4763-8fdf-885dc126ee37.png)

### Your environment

- Public source code:
- Public site URL:
- Docusaurus version used:
- Environment name and version (e.g. Chrome 89, Node.js 16.4):
- Operating system and version (e.g. Ubuntu 20.04.2 LTS):
init env

### Self-service

- [X] I'd be willing to fix this bug myself.

**Comment by Josh-Cena** [comment]
Hi! The two invariants are: (1) static files are always copied to the output as-is. (2) imported files are always passed through loaders and emitted as separate assets.

If you import something from static folder, you will end up with two copies. One will be optimized/hashed/bundled, while the other is verbatim copied. They may not be equivalent. Generally, avoid putting things you will import in the static folder.

See #5362
