### ISSUE TITLE
Shipping ootb with severe vulnerabilities

### ISSUE THREAD

**Issue by s1nistr4** [facebook/docusaurus#8852]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

Docusaurus ootb is shipping with severe vulnerabilities reported by npm

Running `npm audit fix` doesn't seem to fix any of them

Here is a screenshot https://i.postimg.cc/gjdfzX09/Screenshot-20230330-231313.png

### Steps to reproduce

Run "npm init docusaurus" or run "npm upgrade" on any docusaurus project

### Expected behavior

For it to not have the vulnerabilities

### Actual behavior

vulnerabilities

### Your environment

- Public source code: n/a
- Public site URL: n/a
- Docusaurus version used: latest
- Environment name and version (e.g. Chrome 89, Node.js 16.4):  
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): Arch Linux, 

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by Josh-Cena** [comment]
Please see https://github.com/facebook/docusaurus/issues/6394
