### ISSUE TITLE
the docSidebar can't work.

### ISSUE THREAD

**Issue by MaHe666** [facebook/docusaurus#8855]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [ ] I have tried the `npm run clear` or `yarn clear` command.
- [ ] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io.
- [ ] I have read the console error message carefully (if applicable).

### Description

I tried to use docSidebar, but it doesn't work.

### Reproducible demo

https://github.com/MaHe666/docusaurus-mahe666-source/tree/main

### Steps to reproduce

1. add a docSidebar in a dropdown item
2. delete the dropdown item
3. make the type value of the first item docSidebar

### Expected behavior

It will be work in a normal way.

### Actual behavior

I just use it as the document wrote.

### Your environment

- Public source code:
- Public site URL:
- Docusaurus version used:
- Environment name and version (e.g. Chrome 89, Node.js 16.4):
- Operating system and version (e.g. Windows10 ):

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by MaHe666** [comment]
![image](https://user-images.githubusercontent.com/74131961/229159128-66191414-0c75-4d56-8369-fa9e1239fc74.png)
It doesn't work when I try _npm run start_.
I use Windows 10, and I use Chrome.
Maybe the reason is the Chinese word.
I've put the github repo in the ticket.
Is there anything else need me to supply?

**Comment by homotechsual** [comment]
So the issue is that sidebar ids don't support Chinese characters. Please try using latin-alphabet characters for the sidebar id and see if this works. In my testing it works up until I try to use Chinese characters as the machine-id for the sidebar.

**Comment by homotechsual** [comment]
> So the issue is that sidebar ids don't support Chinese characters. Please try using latin-alphabet characters for the sidebar id and see if this works. In my testing it works up until I try to use Chinese characters as the machine-id for the sidebar.

Ignore this - I hadn't rebuilt my test - this works for me.

**Comment by MaHe666** [comment]
I'm Sorry,maybe I didn't express it exactly.The error is "ValidationError: Bad navbar item type docSidebar"
I don't know how to make it work.

**Comment by Josh-Cena** [comment]
Hi, the big notifier above tells you that your version is far, far outdated. Please install the latest version 2.4.0.

**Comment by MaHe666** [comment]
I'm sorry, I ignored the notice.
