### ISSUE TITLE
Add support for Lua comment style for MagicComments

### ISSUE THREAD

**Issue by jcarrillo7** [facebook/docusaurus#8859]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

The current magic comment syntax for highlighting is great but it doesn't have support for Lua's comment style.
Lua uses `--` for short single line comments. Right now I resort to using to using the C/Python comment styles as a workaround but this makes copy/pasting/testing the code snippets a pain since I need to keep removing these invalid lines.

### Steps to reproduce

- Use lua language in CodeBlock
- use magic comments to highlight regions of code

### Expected behavior

Expected `-- highlight-start` and `-- highlight-end` to work in lua but it does not. 

### Actual behavior

Does not work

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by Josh-Cena** [comment]
Thanks, Haskell also uses this syntax, so we will get it in. However, it won't be turned on unless specifically in lua/Haskell code boxes to avoid ambiguity with the `--` operator in C-like languages.

**Comment by morsko1** [comment]
I can see that `-- ...` syntax is also used in SQL for single line comments. Along with `/* ... */` syntax for multi-line comments.
So, maybe it makes sense to handle this case as well.

**Comment by DeepakSR-12** [comment]
Hi @jcarrillo7 . I'd like to work on this issue. Can you please assign this to me?

**Comment by Josh-Cena** [comment]
@DeepakSR-12 Please check the issue more carefully. It already has a linked PR #8870.
