### ISSUE TITLE
Sidebar not Collapsed if we open more than one.

### ISSUE THREAD

**Issue by SHAX1PTb** [facebook/docusaurus#8863]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io.
- [ ] I have read the console error message carefully (if applicable).

### Description

When i open sidebar and proceed to open another one, its not closing the older one, when used useAutoExpandActiveCategory: true its still not closing older open sidebars.

### Steps to reproduce

useAutoExpandActiveCategory: true

### Expected behavior

close the sidebars when we open another sidebar

### Actual behavior

not closing sidebars when we open another sidebar.

### Your environment

- Public source code:
- Public site URL:
- Docusaurus version used:
- Environment name and version (e.g. Chrome 89, Node.js 16.4):
- Operating system and version (e.g. Ubuntu 20.04.2 LTS):

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by Josh-Cena** [comment]
Hi, the option is called `autoCollapseCategories`. Please follow https://docusaurus.io/docs/sidebar#auto-collapse-sidebar-categories.

If you have further questions, please provide a full reproducible demo, including your configuration and screen recordings.
