### ISSUE TITLE
Styling and layout - infima defaults fail tests

### ISSUE THREAD

**Issue by userdocs** [facebook/docusaurus#8884]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Description

Docs link: https://docusaurus.io/docs/styling-layout#styling-your-site-with-infima
Repo link: https://github.com/facebook/docusaurus/blob/main/website/docs/styling-layout.mdx

The defaults for the styling-your-site-with-infima tool to generate a colour palette are failing. As a reader It's difficult to know what the guide expects me to do as the tip suggests to avoid this.

![tip](https://user-images.githubusercontent.com/16525024/231440485-efc08de6-dfc7-46b6-98e6-c064625de916.png)

![defaults](https://user-images.githubusercontent.com/16525024/231439856-b41f7f0a-5e45-4c48-8551-d90a06dcab9d.png)

### Self-service

- [ ] I'd be willing to address this documentation request myself.

**Comment by Josh-Cena** [comment]
Hi! The tip says "AA ratio for the primary color". It has no requirement for the other colors—indeed, those colors may not be used on a white/black background at all, so it's up to you to ensure contrast.
