### ISSUE TITLE
Broken link to Prism includeLangs.js default list of languages

### ISSUE THREAD

**Issue by mhowes-veracode** [facebook/docusaurus#8910]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Description

On this page: https://docusaurus.io/docs/markdown-features/code-blocks

This link is broken: https://github.com/FormidableLabs/prism-react-renderer/blob/master/src/vendor/prism/includeLangs.js

### Self-service

- [ ] I'd be willing to address this documentation request myself.

**Comment by slorber** [comment]
Yes, will be fixed by https://github.com/facebook/docusaurus/pull/8904 👍
