### ISSUE TITLE
the redirect plugin doesn't accept to links with anchors

### ISSUE THREAD

**Issue by alewolf** [facebook/docusaurus#8917]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

The following configuration will throw an error during the build.

`[ERROR] ValidationError: "redirects[1].to" is not a valid pathname. Pathname should start with slash and not contain any domain or query string. `

```
redirects: [
          {
            from: [
              '/pricing',
              '/pricing/',
            ],
            to: '/plugins/pmw/#pricing-section',
          },
        ],
```

In my opinion anchors should be allowed. 

### Steps to reproduce

Paste this redirect configuration into docusaurus.config.js

```
redirects: [
          {
            from: [
              '/pricing',
              '/pricing/',
            ],
            to: '/plugins/pmw/#pricing-section',
          },
        ],
```

### Expected behavior

The build should accept `to` links with anchors. 

### Actual behavior

The following error is thrown: 

`[ERROR] ValidationError: "redirects[1].to" is not a valid pathname. Pathname should start with slash and not contain any domain or query string. `

### Your environment

- Docusaurus version used: 2.4.0
- Environment name and version (e.g. Chrome 89, Node.js 16.4): Chrome 112.0.5615.121
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): OS X 13.3.1

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by Josh-Cena** [comment]
Tracked in https://github.com/facebook/docusaurus/issues/6845
