### ISSUE TITLE
Unable to open sub categories in sidebar on Firefox Nightly (114)

### ISSUE THREAD

**Issue by cmdcolin** [facebook/docusaurus#8929]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

I saw an issue where 'sub-categories' were not able to be opened in firefox nightly (114.0a1 (2023-04-23))

I created a small reproduction

### Reproducible demo

https://cmdcolin.github.io/docusaurus-sidebar-no-open/

### Steps to reproduce

1. Open https://cmdcolin.github.io/docusaurus-sidebar-no-open/ (on Firefox Nightly 114 to trigger)
2. Open Tutorial category
3. Open wow category
4. Observe that wow does not open
5. Also observe the Tutorial category opening is 'instant' instead of animated (I personally like instant instead of animated, but that is not the default behavior, so the instant is probably a bug?)

### Expected behavior

The sidebar category should open

### Actual behavior

The sidebar category does not open

Here is a video of it first not working in firefox nightly and then working in firefox stable (112.0.1 ) 
Using ubuntu 23

[Screencast from 2023-04-25 16-19-15.webm](https://user-images.githubusercontent.com/6511937/234416792-42b4c80f-b164-41ac-ab0f-5d598015cad2.webm)

### Your environment

- Public source code: https://github.com/cmdcolin/docusaurus-sidebar-no-open
- Public site URL: https://cmdcolin.github.io/docusaurus-sidebar-no-open/
- Docusaurus version used: @docusaurus/core@2.4.0
- Environment name and version (e.g. Chrome 89, Node.js 16.4): Firefox Nightly 114
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): Ubuntu 23.04

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by cmdcolin** [comment]
could potentially be a firefox nightly bug but could also be worth looking into

**Comment by Josh-Cena** [comment]
![Test](https://user-images.githubusercontent.com/55398995/234428318-1c269163-3792-47ea-be50-a0bbf8be48c7.gif)

Unfortunately I can't reproduce... Mine is Firefox Nightly 114.0a1 (2023-04-25), macOS 13. This is either specific to Ubuntu or a transient thing. In any case, if it works in a stable browser version but doesn't work in a _later_ version, it's likely a nightly bug, because browser updates should never break existing sites. I can leave it open, but you would probably need to dig deeper into it yourself since I can't reproduce.

**Comment by cmdcolin** [comment]
Are there any or uncommon browser features or CSS that are being used to create the sidebar?  Something I can use to track down the issue?

**Comment by Josh-Cena** [comment]
Nothing comes to mind in particular. We do have some wacky logic for auto collapsing categories: https://github.com/facebook/docusaurus/blob/main/packages/docusaurus-theme-classic/src/theme/DocSidebarItem/Category/index.tsx But you don't have it enabled anyway. I don't have any idea 🤷‍♂️

**Comment by slorber** [comment]
This looks related to the collapsible prefers-reduced-motion bug this time @Josh-Cena 😄 

https://github.com/facebook/docusaurus/pull/8906

I can reproduce on your website with chrome + prefers-reduced-motion OS setting
