### ISSUE TITLE
Confused with getting started instructions

### ISSUE THREAD

**Issue by deevincentday** [facebook/Docusaurus#893]
## Getting Started Instructions need a bit more clarity.

I was following the instructions , I installed node and then Yarn
Then I was told to navigate to a github directory, I have not yet created a github repo.  It would be useful to include the creation of the repo in the instructions as not all writers are familiar with github.  

So part way through the installation I now have to break off the create my repo and a companion folder on my local hard disc.   It would have been smoother if I had been told to create the git repo and local folder before I started installing node and yarn.  It would have prepared the way and I would not have to stop to go and do this.  

This is exactly what I hate about open source, you have to install a mountain of stuff that you don't even understand before you can do anything and it is always complex.   I know windows installers probably do this in one wrapper but it would be so much easier if you could run an installer that installs everything you need.

**Comment by JoelMarcey** [comment]
Hi @deevincentday - sorry you are finding issues in the documentation for getting started. We are definitely willing to review and accept a pull request to clarify the documentation.

With respect to your issue:

- Once you install Node (yarn is optional), then you should be able to run the `npx docusaurus-init` script to get everything going. We have tried to make the installation of Docusaurus a one-liner in most cases. I suppose we could create a script that installs node for you if it is missing, maybe we can consider that.

- With respect to a repo -- you do not necessarily have to create a GitHub repo right away. You could run `npx docusaurus-init` anywhere locally. And have a local site to run. But if you plan to publish your site, GitHub is our recommended place to publish.

So with your workflow, you could do the following steps:

1. Install node
2. `mkdir test`
3. `cd test`
4. `npx docusaurus-init`
5. Verify and test your install https://docusaurus.io/docs/en/installation#verifying-installation
6. Then create a GitHub repo and push code out, if you want.
