### ISSUE TITLE
Mention docusaurus.community docs under Awesome Resources

### ISSUE THREAD

**Issue by thadguidry** [facebook/docusaurus#8939]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Description

@thadguidry -
> WHY is https://docusaurus.community/ not even given a passing mention under Awesome Resources or Support or somewhere else?

@homotechsual -
> homotechsual — 2023-4-27 at 9:10 PM
> Because I keep forgetting to PR it into that page 🤣
> Once I finish v2 of the plugin directory it might even move over to docusaurus.io for that part.

Now you have an issue to assign for yourself for a future PR.

### Self-service

- [x] I'd be willing to address this documentation request myself.

**Comment by slorber** [comment]
That would be faster to open this PR yourself directly 😅

**Comment by thadguidry** [comment]
Will do a PR and put under Awesome Resources.
