### ISSUE TITLE
Support for prism-react-renderer v2.0.2

### ISSUE THREAD

**Issue by laviniat1996** [facebook/docusaurus#8940]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Motivation

A new version for prism-react-renderer is available, after of long pause. Maybe it would be helpful for Docusaurus to support this new version.

### Self-service

- [ ] I'd be willing to do some initial work on this proposal myself.

**Comment by josephpage** [comment]
In fact, if you are using a Docusaurus configuration that is only little changed from the default, you can upgrade `prism-react-renderer` to `v2` in your package.json even if Docusaurus continues to use `v1` internally. To do this, you just need to change this lines in your `docusaurus.config.js` file:

```js
const lightCodeTheme = require('prism-react-renderer/themes/github');
const darkCodeTheme = require('prism-react-renderer/themes/dracula');
```

by the following:

```js
const lightCodeTheme = require('prism-react-renderer').themes.github;
const darkCodeTheme = require('prism-react-renderer').themes.dracula;
```

(remembering to adjust the themes names to match your wishes)
