### ISSUE TITLE
About useGlobalData

### ISSUE THREAD

**Issue by WJAir** [facebook/docusaurus#8942]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Description

I cannot get the tags list of the document through the useGlobalData API

### Self-service

- [ ] I'd be willing to address this documentation request myself.

**Comment by Josh-Cena** [comment]
Hi, the tags list is not available as global data—to reduce bundle size, the docs plugin only puts data actually used by the layout globally. Here are the types for the docs global data:

https://github.com/facebook/docusaurus/blob/9e0b62fe6c9d9b0cb5420c43c1eeffaa96707777/packages/docusaurus-plugin-content-docs/src/client/index.ts#L32-L68

Please use the discussions for questions.

**Comment by slorber** [comment]
This should answer your questions: https://github.com/facebook/docusaurus/discussions/8931
