### ISSUE TITLE
No markdown processing if list item starts with html tag

### ISSUE THREAD

**Issue by reliak** [facebook/docusaurus#8945]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [ ] I have read the console error message carefully (if applicable).

### Description

When a markdown list item starts with an html tag, the rest of the list item text is not processed by markdown.

### Steps to reproduce

Make a list:

```
Some list

- <kbd>G</kbd>: **G** key
- x<kbd>G</kbd>: **G** key
```

### Expected behavior

Markdown processing should be triggered for all of the above list items.

### Actual behavior

Markdown processing is only triggered for the second list item (which does not start with an html tag).

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by slorber** [comment]
Fixed by MDX 2 (upcoming Docusaurus v3): https://github.com/facebook/docusaurus/pull/8288


Try this in:
- mdx v1 playground: https://mdx-git-renovate-babel-monorepo-mdx.vercel.app/playground/ (not working)
- mdx v2 playground: https://mdxjs.com/playground/ (now works)
