### ISSUE TITLE
Add last updated time at bottom right corner for docs

### ISSUE THREAD

**Issue by codering** [facebook/Docusaurus#895]
## 🚀 Feature

Add last updated time at bottom right corner for docs like [vuepress](https://vuepress.vuejs.org/guide/#gitbook) do

## Have you read the [Contributing Guidelines on issues](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

**Comment by JoelMarcey** [comment]
Claimed by @sbansal3096
