### ISSUE TITLE
Initial 404 on several pages

### ISSUE THREAD

**Issue by serrgiofdezz** [facebook/docusaurus#8962]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

Hi,
Since I moved the Docusaurus page from GitHub to GitLab pages, I've found the following bug.

As soon as I access some pages from my website (e.g. https://wiki.bbjprojek.org/projects/rfi/, or https://wiki.bbjprojek.org/blog), they drop a 404 GET and for a second it shows "Page Not Found" but instantly shows the correct content, making the 404 GET preventing pages from showing in Google and making website appearing as "down".

I found that accessing the page from https://wiki.bbjprojek.org/blog.html doesn't throw 404, but https://wiki.bbjprojek.org/blog or  https://wiki.bbjprojek.org/ does...

What is the problem?

### Steps to reproduce

1. Access my blog section onmy website (https://wiki.bbjprojek.org/blog)

### Expected behavior

Show the content

### Actual behavior

Throwing 404 error, then showing the content

### Your environment

- Public source code: https://git.bbjprojek.org/wiki
- Public site URL: https://wiki.bbjprojek.org/
- Docusaurus version used: Latest
- Environment name and version (e.g. Chrome 89, Node.js 16.4): Chrome 109
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): Windows 7, Windows 11

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by slorber** [comment]
This is not a bug, please open a discussion next time if you have a question and look for support.

---

Docusaurus is only responsible for building static files, now how those files are served, and we have no control over the behavior of GitLab pages

I don't know how GitLab pages work, and what options you can use to customize the behavior of their HTTP server regarding static files.

Most likely the first thing I'd suggest is to tweak the `trailingSlash` param. 

With the current behavior I see, I would try `trailingSlash: true` .

**Comment by supersuryaansh** [comment]
@serrgiofdezz Did you fix this? I am facing the same issue , I have deployed on Cloudflare pages and DevKinsta static hosting and get the same issue of 404 error.

**Comment by serrgiofdezz** [comment]
> @serrgiofdezz Did you fix this? I am facing the same issue , I have deployed on Cloudflare pages and DevKinsta static hosting and get the same issue of 404 error.

If I’m not wrong, what I did to fix this error was just by adding `trailingSlash: true` on docusaurus config file.

**Comment by supersuryaansh** [comment]
@serrgiofdezz Thanks for the response I have tried that but same outcome

**Comment by supersuryaansh** [comment]
@serrgiofdezz I managed to fix it, I had in my config onBrokenlinks set to ignore, I turned it to throw and it gave me a bunch of broken links that I had. I had pages name capitalised and hence this issue. 

Fixing the capitalisation fixed this
