### ISSUE TITLE
APNGs do not animate after passing through OptiPNG

### ISSUE THREAD

**Issue by xeoneux** [facebook/Docusaurus#898]
## 🐛 Bug Report

If I add an APNG image, it stops animating after I build the docs.

Can we use a different `imagemin` plugin that supports APNG compression as well?

**Comment by endiliey** [comment]
Hi @xeoneux,

I'm not aware of any imagemin plugin that supports APNG compression. If you are aware of any, a PR will be appreciated.

**Comment by xeoneux** [comment]
@endiliey thanks! That's what I found out too.

Is there a way to disable the Image Compression while building the docs so that none of the images get compressed, using a flag or adding a key/value pair to `siteConfig.json`?

**Comment by yangshun** [comment]
Refer to this section on `docusaurus build` command - https://docusaurus.io/docs/en/commands#docusaurus-build

**Comment by xeoneux** [comment]
@yangshun thanks! :D

**Comment by endiliey** [comment]
Closing due to stale. Seems to be dependencies limitation as well. Feel free to submit a new issue with new template if you think this is really needed
