### ISSUE TITLE
Cannot read properties of undefined (reading '0') using asyncapi

### ISSUE THREAD

**Issue by Streeterxs** [facebook/docusaurus#8999]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

using docusaurus with asyncapi returns Error: Cannot read properties of undefined (reading '0') error.

asyncapi: https://github.com/asyncapi/asyncapi-react

### Reproducible demo

https://github.com/Streeterxs/test-docusaurus

### Steps to reproduce

1. yarn install
2. yarn start
3. visit /asyncapi route

### Expected behavior

should exihibit async api doc

### Actual behavior

returns Error: Cannot read properties of undefined (reading '0')

### Your environment

- Public source code:
- Public site URL:
- Docusaurus version used:
- Environment name and version (e.g. Chrome 89, Node.js 16.4):
- Operating system and version (e.g. Ubuntu 20.04.2 LTS):

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by slorber** [comment]
Hi

We are not responsible of `asyncapi-react`, it does not look particularly well maintained, using a very old version of "constate" and usage in their source code even feels wrong to me.

I would suggest asking for support of developers of that package, we can't help you on the Docusaurus site and it can't be considered as a bug. Try running the exact same code in CRA or Next.js, it's likely to fail similarly.
