### ISSUE TITLE
Is there any way to customize the homepage of the blog? Is there any way to get a list of all blogs?

### ISSUE THREAD

**Issue by shuashuai** [facebook/docusaurus#9009]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Motivation

 Version: 2.4.1
 
I want to customize the blog home page, but I can't find a way to override the default blog home page, and the custom home page needs to be able to get all the data of the blog list, and the data of the tags, but I can't find the relevant API, is there any other way here?

### Self-service

- [ ] I'd be willing to do some initial work on this proposal myself.

**Comment by Josh-Cena** [comment]
Hi, please don't use the issue tracker as a support forum. You will get a more detailed answer if you submit a discussion post, but the short answer is that you need to swizzle `BlogListPage` to customize the layout, although you won't be able to find the tags here.
