### ISSUE TITLE
Incorrect sitemap URLs when `baseURL` != `/`

### ISSUE THREAD

**Issue by shaform** [facebook/Docusaurus#901]
## 🐛 Bug Report

According to the [documentation](https://github.com/facebook/Docusaurus/blob/master/docs/api-site-config.md):

>  For github.io type URLS, you would combine the URL and baseUrl like:
>  url: 'https://reasonml.github.io',
>  baseUrl: '/reason-react/',

So we should set `url` as `https://reasonml.github.io` even though the root of the docs is `https://reasonml.github.io/reason-react/`.

But if we set it like that, the URLs in sitemaps would be:

- https://reasonml.github.io/examples

While it should be:

- https://reasonml.github.io/reason-react/examples

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

yes

## To Reproduce

1. Create a new website
2. Set `siteConfig.js` as

    ```
    url: 'https://reasonml.github.io',
    baseUrl: '/reason-react/', 
    ```

3. Take a look at the generated `sitemap.xml`.

## Expected behavior

The URLs should be like `https://reasonml.github.io/reason-react/examples`.

## Actual Behavior

The URLs would be like `https://reasonml.github.io/examples`.

## Reproducible Demo

The actual `reason-react` actually set `url` as `https://reasonml.github.io/reason-react`. See https://github.com/reasonml/reason-react/blob/1420cba22ad35eb8fd257a58957f1e4047c55034/website/siteConfig.js#L80.

So perhaps this is just a documentation error?

**Comment by endiliey** [comment]
@shaform 

Did you misconfuse two different websites ?

https://reasonml.github.io/reason-react/sitemap.xml
<img width="651" alt="/reason-react/" src="https://user-images.githubusercontent.com/17883920/44000883-8e254b82-9e5a-11e8-88f3-0a1d2a361700.PNG">

https://reasonml.github.io/sitemap.xml
<img width="432" alt="/" src="https://user-images.githubusercontent.com/17883920/44000894-add6df40-9e5a-11e8-816e-169c98e7227f.PNG">

**Comment by shaform** [comment]
Hi @endiliey, as the actual `reason-react` set `url` as `https://reasonml.github.io/reason-react` instead of `https://reasonml.github.io` as instructed by the documentation. Their sitemap.xml `https://reasonml.github.io/reason-react/sitemap.xml` is correct.

**Comment by endiliey** [comment]
@shaform 

Great catch. Thanks for reporting. This is a bug.
<img width="652" alt="react-native" src="https://user-images.githubusercontent.com/17883920/44001027-ce1afe6a-9e5c-11e8-8498-cf04e5207588.PNG">

Do you want to try sending a PR ?
We should add the baseUrl part

https://github.com/facebook/Docusaurus/blob/8f9f7a560236abdd403bbc1b7b0313dd99f65a2e/lib/server/sitemap.js#L62

https://github.com/facebook/Docusaurus/blob/8f9f7a560236abdd403bbc1b7b0313dd99f65a2e/lib/server/sitemap.js#L72

**Comment by shaform** [comment]
Sure, I'll try to come up with a PR today.

**Comment by endiliey** [comment]
This part
https://github.com/facebook/Docusaurus/blob/8f9f7a560236abdd403bbc1b7b0313dd99f65a2e/lib/server/sitemap.js#L86

should be

```js
hostname: siteConfig.url + siteConfig.baseUrl
```
<img width="950" alt="fixed" src="https://user-images.githubusercontent.com/17883920/44001124-7e441dde-9e5e-11e8-8325-a65d9e3f26a5.PNG">

Will wait for your PR 😃
