### ISSUE TITLE
Syntax Highlighting Off with Quotation Marks

### ISSUE THREAD

**Issue by kayx23** [facebook/docusaurus#9011]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

I simplified the command from my actual usage which does require this many of quotation marks:

![image](https://github.com/facebook/docusaurus/assets/39619599/372d90ce-8f75-44b7-8f8b-8b84446ac762)

![image](https://github.com/facebook/docusaurus/assets/39619599/45aee1de-07d1-4f2e-bbfa-1ab83d161e3d)

Colour mismatch

### Reproducible demo

https://stackblitz.com/edit/github-jhnhsf?file=docs%2Fintro.md

### Steps to reproduce

```
```bash
curl -i "http://127.0.0.1" -X PUT -d '
{
  "id": "quickstart",
  "sni": "test.com",
  "cert": "'"${server_cert}"'",
  "key": "'"${server_key}"'"
}'
```

### Expected behavior

Matching colour for opening and closing quotation marks and curly brackets

### Actual behavior

Not matching

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by Josh-Cena** [comment]
Hi! Docusaurus uses [Prism](https://github.com/PrismJS/prism) for syntax highlighting, so issues should be directed to them. Using the [playground](https://prismjs.com/test.html#language=bash&text=curl%20-i%20%22http%3A%2F%2F127.0.0.1%22%20-X%20PUT%20-d%20'%0A%7B%0A%20%20%22id%22%3A%20%22quickstart%22%2C%0A%20%20%22sni%22%3A%20%22test.com%22%2C%0A%20%20%22cert%22%3A%20%22'%22%24%7Bserver_cert%7D%22'%22%2C%0A%20%20%22key%22%3A%20%22'%22%24%7Bserver_key%7D%22'%22%0A%7D'), your code has the same issue.
