### ISSUE TITLE
Footer Legal Link: Privacy and Data policy pointing to same page

### ISSUE THREAD

**Issue by KarthickSakthi** [facebook/docusaurus#9015]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [ ] I have tried the `npm run clear` or `yarn clear` command.
- [ ] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io.
- [ ] I have read the console error message carefully (if applicable).

### Description

In Footer , The Links for **Privacy** and **Data policy**  in **Legal** Section Pointing to Same Page which Privacy policy pointing to!

Privacy  url in code: "https://opensource.fb.com/legal/privacy/"

Data policy url in code: "https://opensource.fb.com/legal/data-policy/"

Here, when I click the Data policy, it's getting redirected to Privacy page.
it's better Have on Link like **Privacy and Data policy** : "https://opensource.fb.com/legal/privacy/"

User will understand, both are in same page.
if they were different, Data policy link redirection is wrong

### Steps to reproduce

Go to Footer,
Check Legal Section
Click Privacy
Click Data policy

check their urls, they were pointing to same page Privacy

### Expected behavior

If both were really same,
 Remove Privacy and Data policy and make it a single link "Privacy and Data policy"
 
if not same,
 No to redirect the Data policy to privacy page, redirect the data-policy to its correct page

### Actual behavior

Privacy and Data policy both were pointing to Privacy page,
Data-policy redirected to Privacy page

### Your environment

-

### Self-service

- [X] I'd be willing to fix this bug myself.

**Comment by KarthickSakthi** [comment]
I am willing to contribute, 

But need confirmation, 
i) whether , if both Privacy and Data policy were same, will make it a single option
ii) if different, need Data policy's url! to add in code

**Comment by slorber** [comment]
Thanks for reporting.

Asked @zpao to see what we should do

**Comment by KarthickSakthi** [comment]
if Any decision Taken, please let me know!, I will contribute in this!
Thanks for the Response

**Comment by zpao** [comment]
I haven't gotten to update any sites (or fix the fb template) but the data policy is gone and the important non-redundant parts rolled into the privacy policy in the latest update last month. The old url redirects to the privacy policy.

Content was all prescribed by legal teams so we won't be changing any page titles, but on the docusaurus site we can just remove data policy from the footer.

**Comment by slorber** [comment]
Thanks @zpao 

FYI I was about to remove the FB template for Docusaurus v3. I think @antonk52 told me its usage had been discouraged internally for a while in favor of another internal solution.

--- 

@KarthickSakthi you can remove the data policy link 👍

**Comment by KarthickSakthi** [comment]
Thanks for the response @slorber , I will remove and give a PR
