### ISSUE TITLE
i18n crowdin download doesn't preserve the original folder/file hierarchy

### ISSUE THREAD

**Issue by YQisme** [facebook/docusaurus#9016]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [ ] I have tried the `npm run clear` or `yarn clear` command.
- [ ] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io.
- [ ] I have read the console error message carefully (if applicable).

### Description

https://docusaurus.io/docs/next/i18n/crowdin#create-the-crowdin-configuration
I used Placeholders `**/%original_file_name%`,but he original folder/file hierarchy was not preserved.

### Steps to reproduce

https://docusaurus.io/docs/next/i18n/crowdin#create-the-crowdin-configuration
Setting up crowdin.yml，then yarn crowdin upload and yarn crowdin download.

### Expected behavior

preserve the original folder/file hierarchy in current directory

### Actual behavior

Download all files to the current directory without any directory structure

### Your environment

- Public source code:
- Public site URL:
- Docusaurus version used:
- Environment name and version (e.g. Chrome 89, Node.js 16.4):
- Operating system and version (e.g. Ubuntu 20.04.2 LTS):

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by slorber** [comment]
Closing because this bug report is unactionable on my side. 

I believe it works, and you did a mistake. You did not provide a repro so we can't verify.

Also, the Crowdin CLI is a third-party software so even if there was a bug, this bug should be reported to Crowdin and not Docusaurus. We are just recommending you some Crowdin configurations but ultimately you need to read the Crowdin docs.

If you think our recommendations are wrong then submit a docs PR

**Comment by slorber** [comment]
As far as I know, we don't have that problem on our sites (Docusaurus, Jest...)

<img width="389" alt="CleanShot 2023-06-21 at 18 55 28@2x" src="https://github.com/facebook/docusaurus/assets/749374/2134c601-1864-4dea-aa22-81f489135d7e">


Have you tried to contact the Crowdin support team directly? They usually answer fast.

 Indeed this is unlikely a problem we can solve. 
Maybe try to use a different version of the npm CLI? 
We are using `@crowdin/cli@3.10.0`
Maybe try to download the translations manually from their UI?

**Comment by jliermann** [comment]
Thanks for the comment - this looks like some very bizarre bug in Crowdin CLI with globbing. I followed a community suggestion and explicitly defined all file locations in the configuration, thus avoiding `**`. It works then. As the folder structure rarely changes I can live with that.

```
  - source: "/docs/00_intro/*"
    translation: "/i18n/%two_letters_code%/docusaurus-plugin-content-docs/current/00_intro/%original_file_name%"
  - source: "/docs/10_domains/*"
    translation: "/i18n/%two_letters_code%/docusaurus-plugin-content-docs/current/10_domains/%original_file_name%"
```
etc.

Complete config is here:
https://github.com/NFDI4Chem/knowledge_base/blob/266-bilingual-knowledge-base-english-german/crowdin.yml

Maybe this is a viable workaround for other people, too.

**Comment by slorber** [comment]
How are you sure it's a problem in the CLI? 

Have you contacted them? 

Have you downloaded the files manually through the UI?

Have you checked this value in the UI?

![CleanShot 2023-06-22 at 18 12 17@2x](https://github.com/facebook/docusaurus/assets/749374/f2ea9309-3885-4149-9a13-9f8c443e015e)

**Comment by jliermann** [comment]
I assumed that it must be a CLI problem because the mapping works when files are uploaded and downloaded manually through the web interface. I think this parameter was also wrong when uploaded with the CLI.

I am also posting on the Crowdin community forum and will probably submit a bug report.

**Comment by slorber** [comment]
You should directly contact support@crowdin.com imho, they reply fast

**Comment by jliermann** [comment]
Hallo everybody, I just wanted to add that this seemed to be a [Windows-related bug](https://github.com/crowdin/crowdin-cli/issues/579) and was recently [fixed in the newest version of Crowdin-CLI](https://github.com/crowdin/crowdin-cli/releases/tag/3.15.0). :)
