### ISSUE TITLE
Can't render `mindmap` mermaid diagrams

### ISSUE THREAD

**Issue by jaimergp** [facebook/docusaurus#9032]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

It looks like the `mindmap` Mermaid diagram doesn't work with the current Docusaurus integrations. Other diagrams do work as expected.

### Reproducible demo

https://github.com/Quansight-Labs/cf-infra-docs

### Steps to reproduce

I followed the [instructions for Mermaid diagrams](https://docusaurus.io/docs/markdown-features/diagrams) and modified my Docusaurus configuration accordingly ([see this PR](https://github.com/Quansight-Labs/cf-infra-docs/pull/5)).

I would have expected the rendering to work out of the box after those changes, but it doesn't.

### Expected behavior

Get the same diagram as available in [mermaid.live](https://mermaid.live/edit#pako:eNp9VU1v2zAM_SuCD4O7VRmwY25ZCnQ9FCi23ZoeaIl2iFiSq48MXtH_PtrpEseOk0MQ8eOF75GU3jLlNGbLzJDVBpqNFcI7F_NcOatBls5XeHPTmYXIf2LjwsehNzyB2kGFokhUa7LVwNd9nj_LElGH6NTuZeQKkRO19KiowTD2Kh1lDzrxmNCGbxfS8kcgG9GCVTguAzTT45zXhCFOED2z0hBBNhDV9hx07WxJVfIQydkx7KKiuE3FGG-hyCc7YXTSUzZkLat1LUSRDBhTM47RLCV6SYbVC5cBguGy2iGLVYrO9BTCZWkMVQeKE0jwkUpQUe6hJt3HTPWrvPuqShmUpyaGa7T-YBHQ70lhmIXhUpqtVC7Z2JZA_nJgTYUq-1DxRQxM_DVOOM6gdCk2KY46bEyypC7LM6j9o9sLcmP8onbVhfGOacKxaGXcorTJFOivCnXIl8ZZis7PMvqPkX93MYhPAppmyOEMsm_1y4yzcHHOpZzzvNxwXsdZiAY0bha77hZzNteA5VmedU-EPPRf8qAAj3Ukbuu14rvdnS98Oo_5Hda0R98OZeQS-6wFJw2hqq3y5wPx_JqgPZnyB8sE6pq7PcB7JEv9_w9MYAoY2PL1g-Dj4WYd5q7-Jo_iiW8_lhXDyfHbw56CWD-cTP1FxMUcayk9DKB-oHe7dDrf9wMuVqpfhZN9TV7VeETObjOD3gBpfjfeOtsm46k2uMmW_FNjCamOm2xj3zm0a9Kv1qpsWUId8DZLDV8jeEfAy2uOVtTdnD8eHqP-TXr_ByLj9_Y)

### Actual behavior

You first see this warning:

![image](https://github.com/facebook/docusaurus/assets/2559438/73a777de-e662-48bf-b3c4-28181715baf2)

Clicking on Try Again gets you to a rendered page with a faulty diagram:

![image](https://github.com/facebook/docusaurus/assets/2559438/32c9874f-3962-48b7-8952-8639e8919bab)

Locally, you see this error message:

```
ERROR
Diagram is a promise. Use renderAsync.
    at Object.render (webpack-internal:///./node_modules/mermaid/dist/mermaid-ae477ddf.js:29923:13)
    at eval (webpack-internal:///./node_modules/@docusaurus/theme-mermaid/lib/client/index.js:44:58)
    at mountMemo (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:15846:19)
    at Object.useMemo (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:16219:16)
    at useMemo (webpack-internal:///./node_modules/react/cjs/react.development.js:1532:21)
    at useMermaidSvg (webpack-internal:///./node_modules/@docusaurus/theme-mermaid/lib/client/index.js:21:168)
    at MermaidDiagram (webpack-internal:///./node_modules/@docusaurus/theme-mermaid/lib/theme/Mermaid/index.js:14:139)
    at renderWithHooks (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:14985:18)
    at mountIndeterminateComponent (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:17811:13)
    at beginWork (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:19049:16)
ERROR
Diagram mindmap already registered.
    at registerDiagram (webpack-internal:///./node_modules/mermaid/dist/mermaid-ae477ddf.js:7474:11)
    at eval (webpack-internal:///./node_modules/mermaid/dist/mermaid-ae477ddf.js:29705:7)
```

It sounds like [this discussion](https://github.com/livebook-dev/livebook/discussions/1716), which led to [this commit](https://github.com/livebook-dev/livebook/commit/9aa72eb1d1ada255d197341d247a2456fe29cb9a). I assume something similar is needed here? I am not an expert in anything JavaScript, sorry 😬 

### Your environment

- Public source code: https://github.com/Quansight-Labs/cf-infra-docs
- Public site URL: https://cf-infra-docs.netlify.app/docs/reference/infrastructure/diagrams/
- Docusaurus version used: 2.4.1
- Environment name and version (e.g. Chrome 89, Node.js 16.4): 18.11.0
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): MacOS Ventura 13.3

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by Josh-Cena** [comment]
We use `mermaid.render`. Looks like we may need to use `renderAsync`. Not sure if this brings more issues elsewhere.

**Comment by slorber** [comment]
Can't find much ref to renderAsync in their docs 😅 

9.4 mentions mindmap needs renderAsync: https://github.com/mermaid-js/mermaid/releases/tag/v9.4.0

With v10.0 it seems that now Mermaid render always returns a promise:
- https://github.com/mermaid-js/mermaid/blob/develop/CHANGELOG.md#1000
- https://github.com/mermaid-js/mermaid/issues/3577

I guess we should upgrade to Mermaid v10 and handle the promise

**Comment by sharky98** [comment]
FYI, in my simple use case, this patch seems to do the trick. Basically, simply using `useState()` + `useEffect()` instead of `useMemo()` since it seems that `useMemo()` does not play nice with async.

```diff
diff --git a/lib/client/index.js b/lib/client/index.js
index 1c121a7adf027f62e1d57510f9d86eee62d313ea..9c0d384f2facfd36e50839c0c03d264243b4bded 100644
--- a/lib/client/index.js
+++ b/lib/client/index.js
@@ -4,7 +4,7 @@
  * This source code is licensed under the MIT license found in the
  * LICENSE file in the root directory of this source tree.
  */
-import { useMemo } from 'react';
+import { useEffect, useMemo, useState } from 'react';
 import { useColorMode, useThemeConfig } from '@docusaurus/theme-common';
 import mermaid from 'mermaid';
 // Stable className to allow users to easily target with CSS
@@ -26,7 +26,8 @@ export function useMermaidSvg(txt, mermaidConfigParam) {
      */
     const defaultMermaidConfig = useMermaidConfig();
     const mermaidConfig = mermaidConfigParam ?? defaultMermaidConfig;
-    return useMemo(() => {
+    const [svgResult, setSvgResult] = useState('');
+    useEffect(() => {
         /*
         Mermaid API is really weird :s
         It is a big mutable singleton with multiple config levels
@@ -55,6 +56,11 @@ export function useMermaidSvg(txt, mermaidConfigParam) {
         Not even documented: mermaid.render returns the svg string
         Using the documented form is un-necessary
          */
-        return mermaid.render(mermaidId, txt);
+        mermaid.render(mermaidId, txt)
+          .then((result) => {
+            setSvgResult(result.svg);
+          });
     }, [txt, mermaidConfig]);
+    
+    return svgResult;
 }
diff --git a/src/client/index.ts b/src/client/index.ts
index f8302085c44155f693aa2c68f4a6d109c5228e4b..3e069146167e4a504e30e337e19ad076fa57a0fa 100644
--- a/src/client/index.ts
+++ b/src/client/index.ts
@@ -5,7 +5,7 @@
  * LICENSE file in the root directory of this source tree.
  */
 
-import {useMemo} from 'react';
+import {useEffect,useMemo,useState } from 'react';
 import {useColorMode, useThemeConfig} from '@docusaurus/theme-common';
 import mermaid, {type MermaidConfig} from 'mermaid';
 import type {ThemeConfig} from '@docusaurus/theme-mermaid';
@@ -40,8 +40,9 @@ export function useMermaidSvg(
    */
   const defaultMermaidConfig = useMermaidConfig();
   const mermaidConfig = mermaidConfigParam ?? defaultMermaidConfig;
+  const [svgResult, setSvgResult] = useState('');
 
-  return useMemo(() => {
+  useEffect(() => {
     /*
     Mermaid API is really weird :s
     It is a big mutable singleton with multiple config levels
@@ -72,6 +73,11 @@ export function useMermaidSvg(
     Not even documented: mermaid.render returns the svg string
     Using the documented form is un-necessary
      */
-    return mermaid.render(mermaidId, txt);
+    mermaid.render(mermaidId, txt)
+      .then((result) => {
+        setSvgResult(result.svg);
+      });
   }, [txt, mermaidConfig]);
+  
+  return svgResult;
 }
```

**Comment by slorber** [comment]
Thanks @sharky98, that's a good solution yes, and indeed useMemo is not meant to read promises. 

A lightweight solution for that is my little package [react-async-hook](https://github.com/slorber/react-async-hook), but I'm hesitant to add it to Docusaurus just for this use-case.

I assume you also upgraded to v10 right?

**Comment by sharky98** [comment]
> I assume you also upgraded to v10 right?

Yes, I did add an overrides with `pnpm` to upgrade to `mermaid@10.2.3`. So far so good, I have added multiple diagrams per page. I also added a way for each node to be a link[^1].

The only issue I have (and I don't care in my use case), is that when loading a page, I have an error message while waiting for mermaid to build and provide the diagram to the component.

[^1]:by ejecting the `Mermaid` component and parsing the resulting SVG to create links where needed since this is not possible with mermaid mindmap.

**Comment by Acr0most** [comment]
It was kind of frustrating, maybe kind of fun, but more than weird to figure out how this bug occurs.
After some hours of debugging and a lot (really a lot) of coffee i found this crazy little part of code in the dev tools:

<img width="518" alt="image" src="https://github.com/facebook/docusaurus/assets/36692230/bb55a244-3d2a-46d0-bc3a-39f5e9690fe9">

if we check line +29871 there is a simple condition, checking if the word "then" occurs in our rendered diagram. This could work of course for some specific error cases. But if your diagram also includes some captions or text like "if you can see this diagram, **then** its working" or "Ro**then**burg" this line of code kills the render process and we are facing this issue.

I will check the mermaid code asap or create an issue to solve this crazy brainfuck.

As a small workaround remove all occurrences of "then" in your diagram definition. ;)

**Comment by Josh-Cena** [comment]
@Acr0most I don't think it has anything to do with what text your diagram contains. It's because a `mindmap` diagram is a promise, so it has a `then` property, and you can't render a promise synchronously.

**Comment by Acr0most** [comment]
For my diagram I'm facing exactly this issue und removing this code works. Think the error message doesn't match the reason behind.

**Comment by mcclowes** [comment]
I have the same issue for the timeline diagram

**Comment by slorber** [comment]
As part of the Mermaid v10 upgrade that I'd like to do for Docusaurus v3, we'll also get new features like Markdown support, requested here: https://github.com/facebook/docusaurus/issues/9296

**Comment by slorber** [comment]
New Mermaid 10.4 features will be supported as part of Docusaurus v3 thanks to this PR: https://github.com/facebook/docusaurus/pull/9305

- Mindmap: https://deploy-preview-9305--docusaurus-2.netlify.app/tests/pages/diagrams#mindmap
- Quadrant Chart: https://deploy-preview-9305--docusaurus-2.netlify.app/tests/pages/diagrams#quadrant-chart
- Flow charts with Markdown syntax: https://deploy-preview-9305--docusaurus-2.netlify.app/tests/pages/diagrams#with-markdown

**Comment by Olshansk** [comment]
@slorber I noticed that `timeline` is still unsupported. I'm planning to open up a new issues for it, but wanted to check if that's expected behaviour (or if I'm missing something) first?

**Comment by slorber** [comment]
@Olshansk I don't use Mermaid much myself, so I don't really know.

Is this a new Mermaid component? Can you show us a repro of a timeline not working?

**Comment by Olshansk** [comment]
> Is this a new Mermaid component?

It was introduced in [mermaid/releases/tag/v10.0.1](https://github.com/mermaid-js/mermaid/releases/tag/v10.0.1) on `Mar 1, 2023`.

>  Can you show us a repro of a timeline not working?

Rendered example: https://dev.poktroll.com/protocol/claim_and_proof_lifecycle#session-end
Sour Code: https://github.com/pokt-network/poktroll/blob/main/docusaurus/docs/protocol/claim_and_proof_lifecycle.md

_Note: There is a screenshot next to the syntax as a workaround. I'm inserting a screenshot for reference._

![Screenshot 2024-02-20 at 2 16 49 PM](https://github.com/facebook/docusaurus/assets/1892194/f79c11e5-afc8-4d2d-bff5-ac1781c868d9)

**Comment by slorber** [comment]
@Olshansk you shared your prod site source code, this is not a minimal repro.

Here's a minimal repro proof that Docusaurus can support Mermaid timelines:
https://stackblitz.com/edit/github-b3imwp?file=src%2Fpages%2Findex.md,docusaurus.config.ts

![CleanShot 2024-02-21 at 10 22 20](https://github.com/facebook/docusaurus/assets/749374/86bf181c-c1ad-4bc4-9c9d-054302599438)


If your site doesn't, then maybe you did something wrong, but I can't study it in depth to help you so a minimal repro is always preferable than a link to a large open source production site.

**Comment by Olshansk** [comment]
@slorber 

I read ` show us a repro` as ` show us a repo` so I apoligize for the complexity 🤦‍♂️ 

That being said, thank you for actually looking into it because that small typo was indeed the issue and now everything is 👌 

Thanks again!! 🙏
