### ISSUE TITLE
Broken link check is case-insensitive

### ISSUE THREAD

**Issue by birdofpreyru** [facebook/docusaurus#9057]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [ ] I have tried the `npm run clear` or `yarn clear` command.
- [ ] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io.
- [ ] I have read the console error message carefully (if applicable).

### Description

Hey. Not sure, is it a bug, or a feature, but currently the broken links check by Docusaurus is case-insensitive. It would be case-sensitive if [`routes` objects used for the match](https://github.com/facebook/docusaurus/blob/012b285805158b128e32074a9ef0cff417904e06/packages/docusaurus/src/server/brokenLinks.ts#L45-L53) had `sensitive: true` flags, but currently they don't have this field. The case-sensitivity matters if generated documentation is served from a service, like Google.Cloud Storage, which treats file URLs in case-sensitive manner.

### Steps to reproduce

N/A

### Expected behavior

N/A

### Actual behavior

N/A

### Your environment

- Public source code:
- Public site URL:
- Docusaurus version used:
- Environment name and version (e.g. Chrome 89, Node.js 16.4):
- Operating system and version (e.g. Ubuntu 20.04.2 LTS):

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by Josh-Cena** [comment]
Are you using Mac/Windows? Our route matching algorithm uses the file system API to decide if the respective file exists, and Mac/Windows is case-insensitive. You would get case-sensitive behavior on Linux (which I would assume most deployment systems are).

**Comment by birdofpreyru** [comment]
@Josh-Cena I am using Ubuntu 22.04.2 LTS, and having this issue, so I don't think `matchRoutes()` from `react-router-config` relies on the file system API to match; I guess it just directly compares given URL strings, and does not care if corresponding files exist on the disk.

**Comment by slorber** [comment]
Makes sense to me 👍 

We should match sensitively by default, but this might prevent existing sites from building so it's a breaking change.

Will try to do the change for v3 and provide a secret env variable in case it's annoying for some users (also useful until their bad links get fixed).

**Comment by slorber** [comment]
Note to myself: lost 1h investigating this and it's a bit more complicated.

`filterExistingFileLinks` filters the link ahead of the `matchRoutes` comparison call, because this function is case-insensitive on case-insensitive filesystems:

```js
async function isExistingFile(filePath: string) {
  try {
    return (await fs.stat(filePath)).isFile();
  } catch {
    return false;
  }
}
```

I'm not sure of the benefits of keeping `filterExistingFileLinks` anyway, it's kind of a useless double protection for regular SPA routes, so I'm in favor of removing it. But maybe some parts of it should be kept?

Need to study this more in-depth, but now is not the ideal time.

**Comment by caramelmelmel** [comment]
Hi @slorber will this be continued?

**Comment by slorber** [comment]
> Need to study this more in-depth, but now is not the ideal time.

Until v3 is released this issue is not a short term goal to fix

**Comment by slorber** [comment]
As part of the v3.1 broken anchor checker:
- https://github.com/facebook/docusaurus/pull/9528
- https://docusaurus.io/blog/releases/3.1#broken-anchors-checker)

We removed the weird `filterExistingFileLinks` function I mentioned above.

Now the broken link checking is case sensitive, see playground:
https://stackblitz.com/edit/github-efpqba?file=docusaurus.config.ts

![CleanShot 2024-02-13 at 13 32 06](https://github.com/facebook/docusaurus/assets/749374/b9abd4c0-49aa-48a9-a75a-e5a52f032675)
