### ISSUE TITLE
Facebook Like/Share Button

### ISSUE THREAD

**Issue by ucdstudent95618** [facebook/Docusaurus#906]
## 🐛 Bug Report

The Facebook button in the footer is not being displayed accurately. The "Sign up" text is being wrapped around in the div and the number of people liking the page is not visible.

![css_issue 2](https://user-images.githubusercontent.com/19369949/44277645-38b6bd80-a200-11e8-8711-68e6f5871b9a.png)

`<div><span class="hidden_elem" id="u_0_5">You and 553 others like this.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span id="u_0_6"><span>553 people like this.</span> <span><a href="/ad_campaign/landing.php?campaign_id=137675572948107&amp;partner_id=docusaurus.io&amp;placement=like_plugin&amp;extra_1=https%3A%2F%2Fdocusaurus.io%2F&amp;extra_2=US" target="_blank">Sign Up</a> to see what your friends like.</span></span></div>`

## To Reproduce

(Write your steps here:)

1. Go to Docusaurus home page
2. Scroll to the bottom 

## Expected behavior

Sign up button/Facebook div should have correct CSS.

**Comment by JoelMarcey** [comment]
@ucdstudent95618 Thanks for catching this. Would love a PR if you would like to fix it. I didn't see it since I was already logged into FB, I think.

**Comment by ucdstudent95618** [comment]
Yea I'll fix it

**Comment by ucdstudent95618** [comment]
and you're welcome! :)

**Comment by nancyk25** [comment]
Just fixed it. PR is[ here](https://github.com/facebook/Docusaurus/pull/924)

**Comment by ucdstudent95618** [comment]
I haven't had the chance to fix it. So check nancy's PR @JoelMarcey :)

**Comment by saranshkataria** [comment]
Is this up for grabs?

**Comment by endiliey** [comment]
@saranshkataria yup. Send a PR in
