### ISSUE TITLE
Bad link to prism-react-renderer's list of default languages

### ISSUE THREAD

**Issue by ljm42** [facebook/docusaurus#9062]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Description

On this page: 
https://docusaurus.io/docs/markdown-features/code-blocks#supported-languages

It says:
By default, Docusaurus comes with a subset of [commonly used languages](https://github.com/FormidableLabs/prism-react-renderer/blob/master/src/vendor/prism/includeLangs.js).

That link is broken

### Self-service

- [ ] I'd be willing to address this documentation request myself.

**Comment by heysujal** [comment]
I'd like to work on this
