### ISSUE TITLE
LaTeX not rendering in <details> block

### ISSUE THREAD

**Issue by Bolleman** [facebook/docusaurus#9076]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

I'm not sure if this is a bug, or just intentionally unsupported.   In any case, consider the following details block:

<details>
<summary>Mary can mow a lawn in four hours and Tom can mow the lawn in 5 hours. If Tom works for $2x$ hours alone, what fractional part of the lawn remains to be mowed?</summary>
  
If Tom can mow $\frac{2}{5}$ of the lawn in one hour...
</details>

In Docusaurus, the LaTeX is not being rendered, as shown below.

![image](https://github.com/facebook/docusaurus/assets/8999611/1da671a6-c806-4ef6-9655-8318f6c6bdce)

### Reproducible demo

https://stackblitz.com/edit/github-hsaoif?file=docs%2Fintro.md

### Steps to reproduce

1. Include LaTeX in details block, e.g.  

<details>
  <summary>Mary can mow a lawn in four hours and Tom can mow the lawn in 5 hours. If Tom works for $2x$ hours alone, what fractional part of the lawn remains to be mowed?</summary>
  
If Tom can mow $\frac{2}{5}$ of the lawn in one hour...
</details>

### Expected behavior

LaTeX would render as it does elsewhere in markdown file.

### Actual behavior

Displays as plain text, as shown.
![image](https://github.com/facebook/docusaurus/assets/8999611/1da671a6-c806-4ef6-9655-8318f6c6bdce)

### Your environment

N/A - repro on StackBlitz

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by Josh-Cena** [comment]
Please see https://docusaurus.io/docs/markdown-features/react#markdown-and-jsx-interoperability. Any children of `<summary>` is seen as plain JSX text. Note that your issue description shows that it doesn't work with the GitHub renderer either.

A possible solution is:

```md
<summary>

$math$

</summary>
```

**Comment by Bolleman** [comment]
Thanks for the quick response and tips Josh!  My apologies for not finding that article previously.  Using that article, I found a workaround by simply putting an empty line between the markdown and jsx, e.g. 

<details>
  <summary>

  Mary can mow a lawn $\boxed{2800}$ in four hours and Tom can mow the lawn in 5 hours. If Tom works for 2 hours alone, what fractional part of the lawn remains to be mowed?
  
  </summary>

$64^2 - 36^2$ can also be expressed as $(64+36)(64-36)$. This simplifies as $100 \cdot 28$, which equals $\boxed{2800}$. 

</details>
