### ISSUE TITLE
Markdown lists before admonitions (break?) admonition

### ISSUE THREAD

**Issue by thatrobotdev** [facebook/docusaurus#9078]
Hello! I've been messing around with Docusaurus and I found some behavior which I'm not sure is a bug or not, since it is not documented in https://docusaurus.io/docs/markdown-features/admonitions.

Whenever you finish a markdown list without a newline before an admonition (as shown below), it breaks the rendering.

```md
There's some important notes here:
- [You need to install Unity's Android SDK](https://docs.unity3d.com/Manual/android-sdksetup.html). Otherwise the option won't pop up.
- Although you *can* swap back and forth between Windows and Android, **you probably don't want to do this.** It changes files around, you probably want to maintain a scaled-back version of your world for Quest, and...
- It can take a **significant** amount of time to swap to the Android platform. Thankfully, if you maintain two separate projects, you only do this once. If your project is huge or has dozens of avatars, you'll probably want to just export the content you want as Prefabs or UnityPackages, and then create an empty Android project from scratch.
:::note Local Cache Server

You can reduce the time it takes to swap platforms by using Unity's Cache Server, which you can run locally. [Read more about the cache server here](https://docs.unity3d.com/Manual/CacheServer.html). Keep in mind this can take up a significant amount of disk space.
:::
```
![broken admonition](https://github.com/facebook/docusaurus/assets/18013689/709a71b5-8b9b-424a-875a-4d66285faccd)
```md
There's some important notes here:
- [You need to install Unity's Android SDK](https://docs.unity3d.com/Manual/android-sdksetup.html). Otherwise the option won't pop up.
- Although you *can* swap back and forth between Windows and Android, **you probably don't want to do this.** It changes files around, you probably want to maintain a scaled-back version of your world for Quest, and...
- It can take a **significant** amount of time to swap to the Android platform. Thankfully, if you maintain two separate projects, you only do this once. If your project is huge or has dozens of avatars, you'll probably want to just export the content you want as Prefabs or UnityPackages, and then create an empty Android project from scratch.

:::note Local Cache Server

You can reduce the time it takes to swap platforms by using Unity's Cache Server, which you can run locally. [Read more about the cache server here](https://docs.unity3d.com/Manual/CacheServer.html). Keep in mind this can take up a significant amount of disk space.
:::
```
![fixed admonition](https://github.com/facebook/docusaurus/assets/18013689/a7da8340-9626-4059-9bb3-7194f6f62533)

I think this is unintended behavior, [as the documentation only talks about invalid admonition syntax being a lack of newlines **inside** of the admonition](https://docusaurus.io/docs/markdown-features/admonitions#usage-with-prettier): "If you use [Prettier](https://prettier.io/) to format your Markdown files, Prettier might auto-format your code to invalid admonition syntax. To avoid this problem, add empty lines around the starting and ending directives. This is also why the examples we show here all have empty lines around the content."

Should this be fixed not to break admonitions? Should it be documented as invalid admonition syntax?

Thank you!

**Comment by Josh-Cena** [comment]
Hi, this is expected. We can only build upon existing Markdown semantics, so the handling of admonitions is slightly different from code blocks. Specifically, a code block fence like ` ``` ` forces the start of a new block, but a `:::`, assuming the admonition syntax is turned off, will be merged with the previous line as part of the same bullet point. However, we can only recognize `:::` when it's part of a **paragraph**, not part of a **bullet point**.

I don't think we need to document this, though. With the ambiguous nature of Markdown you would naturally face a lot of edge cases. The admonition syntax is best understood as "we only generate an admonition when `:::note` and `:::` appear as individual paragraphs or the beginning/end of a paragraph".
