### ISSUE TITLE
Internal Context Providers are not available (<DocsSidebarProvider />)

### ISSUE THREAD

**Issue by dayhaysoos** [facebook/docusaurus#9094]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

I am converting a docs site to a monorepo by switching to pnpm. Everything seemed to run fine when I was using `npm`, however, after switching to `pnpm`, I'm getting ReactContext errors. 

On our `/learn` path, I get this error:

<img width="1228" alt="Screenshot_2023-06-22_at_11 10 15_AM" src="https://github.com/facebook/docusaurus/assets/1852675/c07ac316-826e-4059-8e81-1d7327351fa5">

Some how the `<DocsSidebarProvider />` isn't being wrapped around the Docusaurus app.

Thank you in advanced!

### Reproducible demo

https://github.com/TBD54566975/developer.tbd.website/tree/pnpm

### Steps to reproduce

Step 1: `pnpm i`
Step 2: `pnpm build`

Or if you run `pnpm start` and navigate to the `/learn` URL, you'll see the ContextProvider error.

### Expected behavior

I expect that there should be no errors because the appropriate ContextProviders are in place.

### Actual behavior

Throwing error that says useDocsSidebar hook is being used outside of `<DocsSidebarProvider />`

<img width="1228" alt="Screenshot_2023-06-22_at_11 10 15_AM" src="https://github.com/facebook/docusaurus/assets/1852675/beafbaba-ff23-4d6d-b8b3-eb40537a1cdd">

### Your environment

- Public source code: https://github.com/TBD54566975/developer.tbd.website/tree/pnpm
- Public site URL: https://developer.tbd.website
- Docusaurus version used: 2.4.1
- Chrome 114, Node.js 16.4
- Operating system and version: MacOS Ventura 13.4

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by slorber** [comment]
You probably have some duplicate packages in your node modules.
Not sure it can be considered as a Docusaurus bug.

Did you also upgrade at the same time, or the only change was the package manager?

Can I see a failing PR or something that clearly shows a diff? (ok before, failing after)

**Comment by dayhaysoos** [comment]
Hey @slorber!

I did upgrade only to see if that would fix my issue. I went from 2.4.0 to 2.4.1.

I just created this PR: 

https://github.com/TBD54566975/developer.tbd.website/pull/564

`main` has the same folder structure but we're running `npm` commands directly in `site` and all of those are working just fine.

The `pnpm` branch is where the context errors are happening.

**Comment by slorber** [comment]
Your pnpm branch is working for me locally with start/build and pnpm 8.6.3

Try `docusaurus clear` and test again?

Netlify CI does show an error though but it's not the same that the one you reported `2:03:02 AM: [ERROR] Error: Cannot mix different versions of joi schemas`: https://app.netlify.com/sites/tbd-website-developer/deploys/6494e1064f21010008d33c92

Try also to clear the netlify cache and rebuild?

**Comment by slorber** [comment]
Apparently, you got it working on Netlify a few hours ago, so I assume the problem is fixed 🤷‍♂️ 
https://app.netlify.com/sites/tbd-website-developer/deploys/6494e19ed6e84b1663a769f3

Not sure we can do anything on the Docusaurus codebase anyway so I'm going to close

**Comment by dayhaysoos** [comment]
Hey @slorber,

I was gonna do some experimenting this morning before updating this issue, but here is what ended up being the fix:

https://github.com/facebook/docusaurus/issues/7880#issuecomment-1368025143

Perhaps removing @docusaurus/types from being an optional dependency would be the answer for pnpm users? Not sure if that might cause issues elsewhere, though.

**Comment by slorber** [comment]
Thanks

That looks related to a few issues we have (also this one: https://github.com/facebook/docusaurus/issues/9080)

Will need to investigate this a bit but that seems reasonable to include the types as direct deps (even for JS projects, considering we use JSDoc types in the site config)

**Comment by yoavniran** [comment]
came across this at: https://github.com/rpldy/react-uploady-docs
after upgrading from 3.0.0 to 3.1.1.
Strangely, it only happened when serving and navigating to a single page: `/docs/guides/` (generated directory index) and no other. 
Of course, build was breaking during server-side build.

fixed by removing `node_modules` and reinstalling (pnpm)

**Comment by slorber** [comment]
When this happens this is usually because there are competing versions of the same package in your repo.

Double-checking your dependencies, and regenerating your lockfile is usually a good idea.
