### ISSUE TITLE
Live Docusaurus website not up to date with repo

### ISSUE THREAD

**Issue by pixelastic** [facebook/Docusaurus#910]
## 🐛 Bug Report

Hello,

I was about to file a PR to fix an issue with the DocSearch documentation on https://docusaurus.io/docs/en/search#docsNav (replacing `lang` with `language`). Then I realized that this change had [already been fixed](https://github.com/facebook/Docusaurus/commit/aa1f82649cd69d555812d3dc398f66ef081d18c9#diff-234041e8f66e13c16cdf52912fa6f77b) in the repo, but is not visible on the live website.

Screenshot of the website:
![image](https://user-images.githubusercontent.com/283419/44451523-47ccaf80-a5f4-11e8-9486-feb59ec93fb3.png)

Current code:
![image](https://user-images.githubusercontent.com/283419/44451557-629f2400-a5f4-11e8-864c-9418ebf92e45.png)

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yep

## To Reproduce

1. Go to https://docusaurus.io/docs/en/search#docsNav
2. See that it does not contain the changes from https://github.com/facebook/docusaurus/edit/master/docs/guides-search.md

## Expected behavior

Live website should be in sync with markdown files in the repo

## Actual Behavior

Website content is not in sync with the markdown, resulting in clicking on "Edit" and seeing something different.

**Comment by yangshun** [comment]
It is in sync, just that it's at https://docusaurus.io/docs/en/next/search, which is the trunk version. You were looking at the latest released version. We should release a new version soon though.

**Comment by endiliey** [comment]
@yangshun i'll send a prerelease PR asap (maybe tonight) but I'll need your / joel help for the npm release.

Anyway, closing this.

**Comment by pixelastic** [comment]
Oh I see. I assumed that the documentation website was following a different lifecycle than the project itself (allowing to update the docs without forcing a new release of Docusaurus itself).

I'll close the issue then, waiting for the next release :)

Thanks
