### ISSUE TITLE
Need a way to remove the autogenerated right sidebar

### ISSUE THREAD

**Issue by NathanHennigh** [facebook/docusaurus#9126]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Description

I'm trying to disable/remove the docusaurus autogenerated sidebar on the right. From what I've found so far, there doesn't seem to be a way to.

### Self-service

- [ ] I'd be willing to address this documentation request myself.

**Comment by Josh-Cena** [comment]
Have you seen https://docusaurus.io/docs/api/plugins/@docusaurus/plugin-content-docs#hide_table_of_contents?

We can discuss this further in the discussions.

**Comment by sneko** [comment]
@Josh-Cena this is "per markdown file", but any option to remove it globally?

According to the code it seems I need to override `frontMatter.hide_table_of_contents` inside the context, but didn't figure out yet.

**Comment by Josh-Cena** [comment]
Yes, swizzling is one option (and not nearly a bad one). Another one is a `createFrontMatter` config API that we are planning for a minor version after V3, which allows you to inject front matter en masse.

**Comment by slorber** [comment]
createFrontMatter will come very soon, top priority for me: https://github.com/facebook/docusaurus/issues/5568

It's not a breaking change so I'll avoid delaying v3.0 launch for it, but it should be in v3.1 asap
