### ISSUE TITLE
Static content changes should not affect the build of all pages

### ISSUE THREAD

**Issue by peterpeterparker** [facebook/docusaurus#9127]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Description

Hi 👋

I have observed that modifying the content of a blog or docs page not only affects their respective files when built, but also leads to modifications in the outcome of all other static pages.

For instance, in a sample Docusaurus website, if I make a modification to `intro.md` by appending the text 'Hello' to its content, I would expect that only the `build/docs/intro/index.html` file would be modified after running npm run build. However, in reality, all other `build/**/*.html` files are also modified as a result.

I understand that this behavior is a consequence of the static site generation process, which aims to provide a consistent and cohesive website structure by rebuilding the entire site. However, it seems to be performed in a non-reproducible manner.

In other words, when only the content of a docs or blog page is modified, I would expect the assets and JavaScript resources to remain unchanged.

---

Reproducing the issue:

```
git clone https://github.com/peterpeterparker/docusha
cd docusha
npm ci
npm run build
node sha256.mjs

# manually make a content change in intro.md

npm run build
node sha256.mjs

# compare two last sha-xxxx files and notice all the changes
```

---

Example of comparison between two builds:

<img width="1536" alt="Capture d’écran 2023-07-07 à 08 30 18" src="https://github.com/facebook/docusaurus/assets/16886711/b61d220a-1d3a-4daa-a7bf-565dee60a8a6">

### Motivation

When files are uploaded to a server a CDN, unecessary changes have to be propagated.

### Self-service

- [ ] I'd be willing to contribute this feature to Docusaurus myself.

**Comment by Josh-Cena** [comment]
In what way is this worrying? I don't think it's actionable, but if you have ideas please advise.

**Comment by peterpeterparker** [comment]
> In what way is this worrying?

* Performance and costs when uploading file to a CDN or server as unrelated changes have to be deployed
* I guess it could maybe also has some impact on caching strategy since files that are fundamentally unchanged are actually modified

> if you have ideas please advise.

I unfortunatelly don't know how the build process of Docusaurus works, therefore I cannot really provide any advise.

Note:

I did not debug further to inspect what effectively changes. I am guessing that the root cause of the "issue" is some JavaScript file that gets modified and is populated to other static pages. If this assumption is correct, maybe there is a way to make such JavaScript files more build consistent.

**Comment by Josh-Cena** [comment]
If a file's hash changes, it means its content changes. If we don't change its file name it could actually cause problems with caching strategies. Consider this HTML:

```html
<script src="./bundle.js"></script>
```

If the content of `bundle.js` changes but not its file name, then aggressive caching will choose to serve the cached asset and result in the wrong script being executed on the current HTML. Therefore the HTML _has to_ change with the script URL.

> Performance and costs when uploading file to a CDN or server as unrelated changes have to be deployed

By my understanding, file uploading is far more efficient than building Docusaurus itself. In addition, most deployment options allow you directly build on the server and it won't be you controlling the bare-metal CDN. I don't think it's a tangible concern for most setups.

There are many discussions on this topic, such as https://github.com/facebook/docusaurus/discussions/6927, but the team's opinion is that it's too dangerous to be recommended. You can see https://github.com/facebook/docusaurus/discussions/7157 for a possible option. If you have further questions, you can use discussions for support, but rest assured that we would not add it as a default.

**Comment by peterpeterparker** [comment]
Obviously not totally agree on the analysis and outcome but, thanks for the answer. Anyway appreciated.

**Comment by slorber** [comment]
I'd like the JS chunks to be "more stable" but I don't know how and it's not at the top of my todolist. 

Your help is welcome if you want to investigate.

---

![image](https://github.com/facebook/docusaurus/assets/749374/11bfb880-0fa5-4d48-8f27-2a0b1154d4fc)


Note: you should NEVER cache aggressively the html files. Their content/hash is expected to change regularly because those files are the entry points and need to load other assets those URLs might change. If you loaded a stale cached html file, you'll find your browser trying to load assets that might not exist anymore. 

The goal to me is more to stabilize everything else than the HTML files. It's expected that html files change constantly: they all have to reference shared "js bundle registries" (mapping from chunkId to js file URL). It's possible that we stabilize a bit the html files in the process of stabilizing the rest though, but you still should not cache them anyway.
