### ISSUE TITLE
Autogenerated sidebar item from subfolder don't respect `index.md` at the subfolder root

### ISSUE THREAD

**Issue by fabriziocucci** [facebook/docusaurus#9153]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

It seems that autogenerated items for subfolders containing an `index.md` file don't show up as sections.

For instance, on the sample website from the the [5m tutorial](https://tutorial.docusaurus.io/docs/intro), I would have expected this:
```
const sidebars = {
  tutorialSidebar: [
    "intro",
    {type: 'autogenerated', dirName: 'tutorial-basics'},
    {type: 'autogenerated', dirName: 'tutorial-extras'},
  ],
}
```

to create two sections in the sidebar because they both contain a `_category_.json` file but everything is actually flattened at the root. Replacing both `_category_.json` with an `index.md` leads to the same results.

Is this expected? 

### Reproducible demo

[CodeSandbox](https://codesandbox.io/p/sandbox/peaceful-sutherland-p9txc2)

### Steps to reproduce

1. `npm init docusaurus@latest my-website classic`
2. Update `sidebars.js` from:
```
tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
```
to
```
const sidebars = {
  tutorialSidebar: [
    "intro",
    {type: 'autogenerated', dirName: 'tutorial-basics'},
    {type: 'autogenerated', dirName: 'tutorial-extras'},
  ],
}
```

### Expected behavior

I would expect two sections to appear in the sidebar since both subfolders contain a `_category_.json`.

<img width="322" alt="Screenshot 2023-07-18 at 09 59 36" src="https://github.com/facebook/docusaurus/assets/8156463/97898f25-c459-43a8-b839-bdd841903272">

### Actual behavior

The content of the two sections is actually flattened at the root.

<img width="311" alt="Screenshot 2023-07-18 at 10 01 44" src="https://github.com/facebook/docusaurus/assets/8156463/5a85d5c2-9115-4a6f-b947-d77fa12f08cc">

NOTE: replacing the `_category_.json` files with an `index.md` files leads to the same results.

### Your environment

- Docusaurus version used: 2.4.1

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by caramelmelmel** [comment]
Try this configuration:[https://docusaurus.io/docs/sidebar/autogenerated]( https://docusaurus.io/docs/sidebar/autogenerated) you can't simply replace with an index.md

**Comment by caramelmelmel** [comment]
you have to autogenerate using the docs dirname here in docusaurus

**Comment by fabriziocucci** [comment]
@caramelmelmel I'm using that configuration, check out the `Steps to reproduce` section.

More generally, assuming this structure:
```
docs/
  foo/
    index.md
    Bar.md
    Baz.md
```

I would expect this:
```
const sidebars = {
  mySidebar: [
    {type: 'autogenerated', dirName: 'foo'},
  ],
}
```

to translate in:
```
Foo ↓
  Bar
  Baz
```

**Comment by caramelmelmel** [comment]
no you cannot assume that index.md would directly translate to index.html here as docusaurus already automatically maps to docs in its route. Here's how you can do it
in `sidebars.js`:
```
/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
};

module.exports = sidebars;
```
Create this folder structure:
<img width="277" alt="Screenshot 2023-07-18 at 7 50 35 PM" src="https://github.com/facebook/docusaurus/assets/72269553/0b23ae8a-943a-4c98-8880-8ed5d4ee9b9b">

You will get:
<img width="296" alt="Screenshot 2023-07-18 at 7 51 14 PM" src="https://github.com/facebook/docusaurus/assets/72269553/45e5c8c2-e488-4356-af96-594e0e6e4909">

**Comment by caramelmelmel** [comment]
if you want to manipulate the keys you cannot just touch the docusaurus.config.js there are other repositories that use the component page routing from the config to perform something like this

**Comment by fabriziocucci** [comment]
Thanks @caramelmelmel, I think the use case I was trying to come across is not entirely clear, let me expand a bit.

Imagine you want to have some part of the sidebar being autogenerated and some part being manually managed:
```
docs/
  manual-doc/
    index.md
    manual1.md
    manual2.md
  auto-doc/
    index.md
    auto1.md
    auto2.md
```

The corresponding sidebar config I would think it should suffice is:
```
const sidebars = {
  tutorialSidebar: [
   {
      label: "Manual Doc",
      link: {type: 'doc', id: 'manual-doc/index'},
      type: "category",
      items: [ ... ],
    },
    {
      dirName: 'auto-doc',
      type: 'autogenerated',
    }
  ],
};
```

but that would lead to:
```
Manual Doc ↓
  Manual 1
  Manual 2
Auto Doc
Auto 1
Auto 2
```

reather than:
```
Manual Doc ↓
  Manual 1
  Manual 2
Auto Doc ↓
  Auto 1
  Auto 2
```

Taking your example, this:
```
const sidebars = {
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
};
```

would still not work as I would expect for:
```
docs/
  index.md  <-- this index will NOT generate a section
  foo/
    index.md <-- this index will generate a section
    Bar.md
    Baz.md
```

leading to:
```
Index
Foo ↓
  Bar
  Baz
```

rather than:
```
Index ↓
  Foo ↓
    Bar
    Baz
```

I guess, regardless by the underlying implementation, I don't fully understand why the `index.md` in a folder for which we are requesting an autogenerated sidebar should be treated differently from any other `index.md` in the descendant folders.

**Comment by caramelmelmel** [comment]
but as far as I know the auto and manual configurations cannot mix together

**Comment by caramelmelmel** [comment]
Instead, this could not be a bug. You might want to ask about this in Discord.

**Comment by fabriziocucci** [comment]
Posted on Discord but didn't have much traction.

My biggest concern still stands so I'll leave this open:

> I guess, regardless by the underlying implementation, I don't fully understand why the `index.md` in a folder for which we are requesting an autogenerated sidebar should be treated differently from any other `index.md` in the descendant folders.

I believe this ultimately makes mixing manual and autogenerated sidebars harder than it should be.

**Comment by Josh-Cena** [comment]
You generate an entire sidebar from a folder; you don't just generate one category. `index.md` within a folder becomes the category index page only if the folder becomes a category, but the root folder doesn't become a category—it becomes a "sidebar slice".

**Comment by fabriziocucci** [comment]
Thanks @Josh-Cena!

Out curiosity, would there be any downside to make the root folder become a category if there is an `index.md` inside it and just be a "sidebar slice" if not? I've the feeling this would improve the overall composability but I'm pretty sure if it wasn't designed to work this way, there is some gotcha I'm not considering.

**Comment by Josh-Cena** [comment]
I think a new sidebar item called `autogenerated-category` sounds good. @slorber WDYT?

**Comment by caramelmelmel** [comment]
@Josh-Cena I think an autogenerated-category (if I understand that this works by making a particular configuration to enable a subfolder in docs become an auto-generated category) should be for specific subfolders in this case then developers have the freedom to configure however they would like to

**Comment by caramelmelmel** [comment]
@slorber what I really think about including index.md in the subfolder is that the user is able to customise the introduction page however he or she likes instead of using a category.json so by providing the /index.md functionality, and then autogenerating the sub bars in a sidebar, based on the presence of this index.md helps to provide this functionality of customisation here.

**Comment by Josh-Cena** [comment]
Neither the presence of `index.md` nor `_category_.json` can affect whether a folder becomes a category or a sidebar slice—that would be a huge behavior inconsistency. These files are picked up when and only when the folder is actually destined to become a category.

**Comment by Josh-Cena** [comment]
I don't think there's anything wrong with Docusaurus' behavior—I agree with @slorber that we can try #5689 first, although I think `autogenerated-category` will still be very intuitive and convenient, but that would be another feature request :)

**Comment by fabriziocucci** [comment]
Thanks @slorber and @Josh-Cena for the comments.

@slorber, regarding:

> What you really want is something like this:
```
const sidebars = {
  tutorialSidebar: [
    "intro",
    {
      type: "category",
      label: "Tutorial basics",
      link: {type: 'doc', id: 'tutorial-basics/index'},
      items: [{type: 'autogenerated', dirName: 'tutorial-basics'},],
    },
    {
      type: "category",
      label: "Tutorial Extras",
      link: {type: 'doc', id: 'tutorial-extras/index'},
      items: [{type: 'autogenerated', dirName: 'tutorial-extras'},],
    }
  ],
}
```

I was going to say, that's not gonna fully work without a way to exclude `tutorial-basics/index` from the auto-generated items. I remember we tried this and, besides not being straightforward as you also pointed out, leads to a duplication of the index file that will then appear as both a category _and_ a document inside the category.

Being able to exclude files like in #5689 will definitely help, looking forward to it!

@Josh-Cena, regarding:

> Neither the presence of index.md nor _category_.json can affect whether a folder becomes a category or a sidebar slice—that would be a huge behavior inconsistency.

For some reason, from a user prospective without any clue about the implementation details, I had exactly this expectation! I agree that `autogenerated-category` would be more intuitive and convenient, not sure about the gain of having it separate from the already existing  `autogenerated` type when the mere convention of adding an `index.md` could do the trick (similarly to the [category index convention](https://docusaurus.io/docs/sidebar/autogenerated#category-index-convention)). Regardless, I'd love to see `autogenerated-category` come to life.

I appreciate you guys taking the time to even evaluate this, keep up the good work! 🙂

**Comment by slorber** [comment]
> I was going to say, that's not gonna fully work without a way to exclude tutorial-basics/index from the auto-generated items. I remember we tried this and, besides not being straightforward as you also pointed out, leads to a duplication of the index file that will then appear as both a category and a document inside the category.

```js
    {
      type: "category",
      label: "Tutorial basics",
      link: {type: 'doc', id: 'tutorial-basics/index'},
      items: [{type: 'autogenerated', dirName: 'tutorial-basics'},],
    },
```


As far as I remember (not 100% sure) we have logic so that if it's already a category link, index is excluded from the sidebar slice to prevent this.

---

We'll add the include/exclude feature first and eventually see if `autogenerated-category` is needed.

> not sure about the gain of having it separate from the already existing autogenerated type when the mere convention of adding an index.md could do the trick

If we implement this as a convention, then it becomes impossible to generate a sidebar slice including the index. By implementing your use case we might break another user use case, with no easy workaround to opt-out.

I'd rather keep the ability to be able to support both if possible, even if it makes the API slightly less intuitive.

**Comment by rodcloutier** [comment]
> As far as I remember (not 100% sure) we have logic so that if it's already a category link, index is excluded from the sidebar slice to prevent this.

It actually highlight both links at the same time (category and page) but it does not remove the actual index page from the page list in the category.

**Comment by robbieaverill** [comment]
Another side effect of this is that when you're viewing the index category page, the pagination's "next" link is the same page. The pagination next link becomes unusable here as it links to itself.

After following all of these threads, I decided to simply do an entire sidebar as autogenerated instead of trying to achieve this. It's too janky without being able to exclude the index file from the autogenerated child items.
