### ISSUE TITLE
Apostrophe in file name breaks registry.js

### ISSUE THREAD

**Issue by Sainan** [facebook/docusaurus#9159]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [ ] I have tried the `npm run clear` or `yarn clear` command.
- [ ] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [x] I have tried creating a repro with https://new.docusaurus.io. (Can repro on StackBlitz; CodeSandbox filters apostrophes.)
- [ ] I have read the console error message carefully (if applicable).

### Description

For example, creating a file called "Beginner's Guide.md" causes it to be written to registry.js verbatim:

![image](https://github.com/facebook/docusaurus/assets/63328889/5724a03d-fafc-4d1f-b633-f9d408dee377)

So, we obviously have a syntax error there.

![image](https://github.com/facebook/docusaurus/assets/63328889/6323c401-6688-42b2-8dc2-a46b77747113)

### Steps to reproduce

1. Create a file with an apostrophe in it's name, such as "Beginner's Guide.md"
2. Run `npm start`

### Expected behavior

The apostrophe would be escaped.

### Actual behavior

The apostrophe is written verbatim.

### Your environment

- Docusaurus version used: Whichever the latest one published to NPM is as of 2023-07-20

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by Sainan** [comment]
I guess workaround is using the file name like a slug and the "title" in the frontmatter for the actual title, but pretty meh issue to have to be working around.

**Comment by Josh-Cena** [comment]
You should generally avoid special characters in file paths, because even if this one is fixed, you may run into other issues with other tools that do a naïve string joining when running shell commands. Of course this is dangerous for them to do in the first place, but it can be easily mitigated.
