### ISSUE TITLE
Next and previous buttons wrap and stack on mobile

### ISSUE THREAD

**Issue by notjaril** [facebook/Docusaurus#918]
## 🚀 Feature

Changing the next and previous button styles so that they don't stack and wrap on smaller screens (either on desktop or mobile). 

![img_7537](https://user-images.githubusercontent.com/15959269/44671053-636bf780-a9f2-11e8-8a2e-aa12d1021a5a.jpg)

## Have you read the [Contributing Guidelines on issues](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## Motivation

The behavior happens when the text inside the buttons are long. This is especially noticeable on mobile, since it's easier to click on the wrong thing.

## Pitch

Modify button styles for mobile screen widths.

- Option 1: set both buttons to equal width on smaller screens, forcing the lengthy text to wrap within the button itself
- Option 2: set the next button to `float: left` on smaller screens and add `padding: 10px` so that there's consistency and clear separation between the two buttons

![option-comparison](https://user-images.githubusercontent.com/15959269/44672305-06724080-a9f6-11e8-8eeb-7acae5efce1a.png)

**Comment by JoelMarcey** [comment]
@notjaril Thanks for the bug report. Do you have any interest in submitting a PR to fix this?

**Comment by JoelMarcey** [comment]
@notjaril I like option 2 as well. 👍

**Comment by yangshun** [comment]
Option 2 is great 👍 Sometimes we have extremely longer unbreakable strings because they are function names though, for example: https://facebook.github.io/react-native/docs/0.56/touchableopacity

Not sure how we can deal with that.

**Comment by yangshun** [comment]
@notjaril it's yours!

I've added an "issue: claimed" label so that others will know not to start work on the issue. If you change your mind about the issue, no worries! Just let me know so that I can remove the label and free it up for someone else to claim.

I'll check in with you periodically so that we can keep the task updated with the progress.

**Comment by notjaril** [comment]
@yangshun I've noticed the extremely long strings as well. It should be okay, since the current CSS handles that case just fine by wrapping the text within the button anyway. 

![aug-27-2018 17-34-28](https://user-images.githubusercontent.com/15959269/44687638-b8723280-aa1f-11e8-8286-e9c7ee8b548b.gif)

**Comment by yangshun** [comment]
Yes, it wraps for text which have spaces in them. In the example I posted above, there are no spaces in them because they're code (function names/component names). In this case, we could use something like `text-overflow: ellipsis` for truncation.

**Comment by notjaril** [comment]
Oh I see what you're saying. Truncation is a good idea - though I just noticed that the arrows (← →) are part of the text, and the next arrow (→) would get cut off if the text were truncated.

I'm thinking we could make the arrows its own DOM element inline with the text, that way only the text gets truncated. Any thoughts on how to get around it? 

I'll think about this more and circle back.

**Comment by yangshun** [comment]
Cool. Yes we could move the → into its own span
