### ISSUE TITLE
Non-https URLs http://schema.org/Blog and BlogPosting in classic theme

### ISSUE THREAD

**Issue by gibfahn** [facebook/docusaurus#9181]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

My broken link checker is complaining about http links in the generated page. Looks like these are:

https://github.com/facebook/docusaurus/blob/983fb2d273d5af34da49ea98b307df7c42547b2c/packages/docusaurus-theme-classic/src/theme/BlogPostItem/Container/index.tsx#L30
https://github.com/facebook/docusaurus/blob/983fb2d273d5af34da49ea98b307df7c42547b2c/packages/docusaurus-theme-classic/src/theme/BlogLayout/index.tsx#L30
https://github.com/facebook/docusaurus/blob/983fb2d273d5af34da49ea98b307df7c42547b2c/packages/docusaurus-plugin-content-blog/src/__tests__/__fixtures__/website/build-snap/blog/index.html#L14

And were introduced in https://github.com/facebook/docusaurus/pull/5355

### Steps to reproduce

I believe this should reproduce with any site using the Blog theme.

### Expected behavior

HTTPS links instead

### Actual behavior

HTTP links

### Your environment

- Docusaurus version used: the links are still present on `main`

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by slorber** [comment]
Thanks, that seems reasonable to use https links consistently (some of them already are https btw)

Does anyone want to submit a PR?

**Comment by thedevwonder** [comment]
@slorber, I have created a PR [https://github.com/facebook/docusaurus/pull/9184](https://github.com/facebook/docusaurus/pull/9184)

**Comment by thedevwonder** [comment]
does the build-snap file gets created automatically when we build the test folder? @slorber 

referring: [docusaurus/packages/docusaurus-plugin-content-blog/src/__tests__/__fixtures__/website/build-snap/blog/index.html](https://github.com/facebook/docusaurus/blob/983fb2d273d5af34da49ea98b307df7c42547b2c/packages/docusaurus-plugin-content-blog/src/__tests__/__fixtures__/website/build-snap/blog/index.html#L14)

**Comment by Josh-Cena** [comment]
We had just been wondering about it in https://github.com/facebook/docusaurus/pull/9151 😄 Looks like the answer is no, so you would have to run a build yourself and copy the HTML output.

**Comment by thedevwonder** [comment]
I think the HTML build gets created by running jest packages/docusaurus-plugin-content-blog/src/__tests__/index.test.ts but I have been unsuccessful in doing that.

**Comment by Josh-Cena** [comment]
No, unfortunately—`build-snap` is the _input_, not the _output_ of the test ^^

**Comment by thedevwonder** [comment]
> No, unfortunately—`build-snap` is the _input_, not the _output_ of the test ^^

I see!

**Comment by gibfahn** [comment]
Thanks for the quick fix folks!
