### ISSUE TITLE
Use 0.0.0.0 for livereload address

### ISSUE THREAD

**Issue by tanc** [facebook/Docusaurus#919]
## 🚀 Feature

At the moment live reload is hardcoded to use localhost for its address which stops it working inside a docker container. This request is to change it to 0.0.0.0 to allow livereload to work when visited from the host machine.

## Have you read the [Contributing Guidelines on issues](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## Motivation

To enable Docusaurus to be containerised it would be handy to have livereload work from outside the container.

## Pitch

If a developer is able to view the output of livereload served from within a container then a Docusaurus instance can be packaged in a node based Docker container and a self contained environment can be given to other developers so they can write documentation without having node installed locally.

**Comment by maht0rz** [comment]
Guys any chance this will be implemented soon?
