### ISSUE TITLE
Blog feeds render nicely by default (XSLT stylesheet)

### ISSUE THREAD

**Issue by slorber** [facebook/docusaurus#9197]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Motivation

It is possible to style how an XML file is rendered by browsers thanks to XML XSLT stylesheets:

https://darekkay.com/blog/rss-styling/

https://x.com/stefanjudis/status/1672230720536756224

![image](https://github.com/facebook/docusaurus/assets/749374/08db4e25-c059-437c-9dcc-792ad77af69f)

```xml
<?xml version="1.0" encoding="utf-8"?>
<?xml-stylesheet href="/rss.xsl" type="text/xsl"?>
<feed xmlns="http://www.w3.org/2005/Atom"
      xmlns:media="http://search.yahoo.com/mrss/">
  ...
</feed>
```

I think it could be useful to have a beautiful XML output by default for XML-based feeds.

We could also add an icon in the blog sidebar to link to that feed, helping users know that a feed is available.

![image](https://github.com/facebook/docusaurus/assets/749374/91fee5cf-3b0c-4a59-9de9-dd49d4025094)

(this could become later a "blog sidebar item type", related to https://github.com/facebook/docusaurus/issues/7227)

---

Also, it can be the occasion to do some additional cleanup in the RSS feed item content:

<img width="1289" alt="CleanShot 2023-08-03 at 18 28 19@2x" src="https://github.com/facebook/docusaurus/assets/749374/3b7b0f33-9e57-486d-8730-431674380dee">

<img width="1420" alt="CleanShot 2023-08-03 at 18 29 59@2x" src="https://github.com/facebook/docusaurus/assets/749374/dd464fb9-8d32-4f95-91f7-f69c2c7e761e">

Are the className attributes set by the Docusaurus theme really needed to be in the feed item content? I doubt it leads to any significant styling difference from RSS readers considering they don't have the stylesheet.

### Self-service

- [ ] I'd be willing to do some initial work on this proposal myself.

**Comment by caramelmelmel** [comment]
@slorber can I take this issue? Is there any prerequisite knowledge to taking this issue?

**Comment by slorber** [comment]
You can submit a PR if you think you are able to work on it. It's up to you to figure out if you have the required skills.

**Comment by caramelmelmel** [comment]
@slorber Give me a week to investigate on this and then get back to you

**Comment by KirtiKamal** [comment]
@slorber what actually you want in this issue. can you please specify. I am new to opensource by knowing more about this issue i will be able to contribute to this issue

**Comment by slorber** [comment]
@KirtiKamal we already have a PR for this issue that I should review soon: https://github.com/facebook/docusaurus/pull/9252

If you don't understand what the issue is about, then try to find another to contribute to. We unfortunately don't have time to help you figure it out 😅

**Comment by jeacott1** [comment]
I'd like to see an entire docusaurus site available as xml - xslt-fo could be a nice way to finally generate some good looking pdf content.
