### ISSUE TITLE
The result of the search can not be displayed correctly on the full search page and get an error, but it can be displayed correctly in the dialog view

### ISSUE THREAD

**Issue by urfreespace** [facebook/docusaurus#9200]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

website: [https://pulsar.apache.org/](https://pulsar.apache.org/) 
error search display demo: https://pulsar.apache.org/search/?q=k8s

The result of the search can not be displayed correctly on the full search page and get an error, but it can be displayed correctly in the dialog view

Error detail:
```
Uncaught (in promise) Error: Uncaught, unspecified "error" event. ([object Object])
    at t.emit (1a4e3797.9530b31a.js:2:775)
    at d._dispatchAlgoliaError (1a4e3797.9530b31a.js:2:41011)
t.emit @ 1a4e3797.9530b31a.js:2
d._dispatchAlgoliaError @ 1a4e3797.9530b31a.js:2
Promise.catch (async)
d._search @ 1a4e3797.9530b31a.js:2
d.search @ 1a4e3797.9530b31a.js:2
(anonymous) @ 1a4e3797.9530b31a.js:2
(anonymous) @ main.9587d1e9.js:2
(anonymous) @ 1a4e3797.9530b31a.js:2
setTimeout (async)
(anonymous) @ 1a4e3797.9530b31a.js:2
zc @ main.9587d1e9.js:2
t.unstable_runWithPriority @ main.9587d1e9.js:2
Va @ main.9587d1e9.js:2
Ic @ main.9587d1e9.js:2
(anonymous) @ main.9587d1e9.js:2
D @ main.9587d1e9.js:2
y.port1.onmessage @ main.9587d1e9.js:2
```

<img width="1724" alt="image" src="https://github.com/facebook/docusaurus/assets/76024046/6939e8b8-8bfe-4477-b28e-45eea6566031">

### Reproducible demo

https://github.com/apache/pulsar-site

### Steps to reproduce

1. git clone `git@github.com:apache/pulsar-site.git`
2. yarn install
3. npm start
4. Go to http://localhost:3000/ and open Developer Tools
5. Click search input on the top navigation
6. Input any keyword, for example:`k8s`
7. scroll to the bottom of the search result list, click `See all 10 results`
8. See error

Live reproduction:
http://localhost:3000/search/?q=k8s

![search](https://github.com/facebook/docusaurus/assets/76024046/ab946d02-438c-45e7-a8b9-07dee124ba6a)

### Expected behavior

The result of the search can be displayed correctly on the full search page

### Actual behavior

website: https://pulsar.apache.org/
error search display demo: https://pulsar.apache.org/search/?q=k8s

The result of the search can not be displayed correctly on the full search page and get an error, but it can be displayed correctly in the dialog view

Error detail:
```
Uncaught (in promise) Error: Uncaught, unspecified "error" event. ([object Object])
    at t.emit (1a4e3797.9530b31a.js:2:775)
    at d._dispatchAlgoliaError (1a4e3797.9530b31a.js:2:41011)
t.emit @ 1a4e3797.9530b31a.js:2
d._dispatchAlgoliaError @ 1a4e3797.9530b31a.js:2
Promise.catch (async)
d._search @ 1a4e3797.9530b31a.js:2
d.search @ 1a4e3797.9530b31a.js:2
(anonymous) @ 1a4e3797.9530b31a.js:2
(anonymous) @ main.9587d1e9.js:2
(anonymous) @ 1a4e3797.9530b31a.js:2
setTimeout (async)
(anonymous) @ 1a4e3797.9530b31a.js:2
zc @ main.9587d1e9.js:2
t.unstable_runWithPriority @ main.9587d1e9.js:2
Va @ main.9587d1e9.js:2
Ic @ main.9587d1e9.js:2
(anonymous) @ main.9587d1e9.js:2
D @ main.9587d1e9.js:2
y.port1.onmessage @ main.9587d1e9.js:2
```

<img width="1724" alt="image" src="https://github.com/facebook/docusaurus/assets/76024046/6939e8b8-8bfe-4477-b28e-45eea6566031">

### Your environment

- Public source code: https://github.com/apache/pulsar-site
- Public site URL: https://pulsar.apache.org/
- Docusaurus version used: 2.4.0
- Environment name and version (e.g. Chrome 89, Node.js 16.4): Chrome Version 115.0.5790.170 (Official Build) (arm64) , Node.js v16.17.0
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): macOS 13.4.1

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by slorber** [comment]
Our Docusaurus code expects search hits to have a `_highlightResult.hierarchy` attribute available:

![CleanShot 2023-08-04 at 14 32 28@2x](https://github.com/facebook/docusaurus/assets/749374/27871b8e-b5a9-4cc9-901c-2fffc84e465c)

But in your case this attribute seems absent and the response is quite different:

![CleanShot 2023-08-04 at 14 32 55@2x](https://github.com/facebook/docusaurus/assets/749374/f67ffc03-3e5f-4e27-88d9-26e2e88a168e)

---

I'm going to close because IMHO it's very likely not a bug, but an algolia crawler configuration problem that does not match our official recommendations. 

You are free to use a different configuration if you want, but we can't provide support for that.

---

@shortcuts can probably confirm, but most likely your site doesn't have the appropriate Algolia config that we recommend in our docs:
- https://docusaurus.io/docs/search#algolia-index-configuration
- https://docsearch.algolia.com/docs/templates/#docusaurus-v2-template

Notably: `attributesToHighlight: ['hierarchy', 'content'],`

Please double-check your entire setup and reindex your site.

**Comment by shortcuts** [comment]
Hey, yes I'd suggest the same way to solve it, this is most likely a misconfiguration of the Crawler. Considering you have all other properties, updating the index settings should be enough

**Comment by urfreespace** [comment]
I checked our crawler configuration, seems it's right, pls see the below image, and I reindex the full index, but the problem is still happen @slorber  @shortcuts 

<img width="1053" alt="image" src="https://github.com/facebook/docusaurus/assets/76024046/5c815986-b3db-4bd4-a9bf-55e462ebbe86">

**Comment by shortcuts** [comment]
hey @urfreespace, those index settings are called `initialIndexSettings` because they are only applied when the index does not yet exist (a bit tricky to see, I agree)

to prevent having to do this manually, you can delete the index and then restart the crawl

**Comment by urfreespace** [comment]
working fine now, big thanks @shortcuts

**Comment by slorber** [comment]
> hey @urfreespace, those index settings are called `initialIndexSettings` because they are only applied when the index does not yet exist (a bit tricky to see, I agree)

Ah yes, this is easy to miss 😅 It's not the first time someone reports updating the config and getting no improvements. Now I understand and will be able to guide our users better. I guess it could be worth it to write a troubleshooting section in ours docs?

Can the index be updated manually instead of delete/recreate? I guess some will not like this idea and would prefer an incremental index upgrade?

**Comment by shortcuts** [comment]
> Can the index be updated manually instead of delete/recreate? I guess some will not like this idea and would prefer an incremental index upgrade?

Sure, you have access to a `configuration` tab in the dashboard: `https://dashboard.algolia.com/apps/$APP_ID/explorer/configuration/$INDEX_NAME/searchable-attributes` and `https://dashboard.algolia.com/apps/$APP_ID/explorer/configuration/$INDEX_NAME/facets`, are the two links the user would edit settings

**Comment by Bibazavr** [comment]
> hey @urfreespace, those index settings are called initialIndexSettings because they are only applied when the index does not yet exist (a bit tricky to see, I agree)

I guess, that need add into docs somewhere

**Comment by shortcuts** [comment]
is it documented on the Crawler documentation https://www.algolia.com/doc/tools/crawler/apis/configuration/initial-index-settings/ but indeed we should reference it in the DocSearch documentation

**Comment by slorber** [comment]
For anyone passing by, make sure that your Algolia index has those fields. If you don't see these fields, then you have an index config problem, and should probably check your crawler config and delete/recreate your index based on the newly updated/fixed config.

![image](https://github.com/facebook/docusaurus/assets/749374/b518cfe4-6b0c-480a-ab7b-be9f098f9cd3)

See also: https://github.com/facebook/docusaurus/discussions/10007#discussioncomment-9021352
