### ISSUE TITLE
Tabs Work on Dev Server, but Not in Built Version

### ISSUE THREAD

**Issue by nullromo** [facebook/docusaurus#9201]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [ ] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io.
- [ ] I have read the console error message carefully (if applicable).

### Description

When using `<Tabs>` and running the dev server (`npm run start`) the tabs work fine. However, when using the build version generated from `npm run build`, the tab buttons don't do anything when clicked. I just see the first tab only and can't click to any other tabs.

### Steps to reproduce

1. Create a page using `<Tabs>`. Here is an example:
```
<Tabs queryString='language'>
    <TabItem value='js' label='JavaScript'>
        <MyCodeBlock
            language='js'
            title='JavaScript'
            value={`my
    JS
    code
    here`}
        />
    </TabItem>
    <TabItem value='py' label='Python'>
        <MyCodeBlock
            language='python'
            title='Python'
            value={`my
    python
    code
    here`}
        />
    </TabItem>
</Tabs>
```

2. Run the dev server (`npm run start`) and go to the page. Click back and forth between the tabs. It works fine.
3. Run a build (`npm run build`).
4. Open up `build/index.html` in a web browser. The site is working great except you can't switch tabs.

### Expected behavior

I expect the dev server to work the same as the built version, and I expect the `<Tabs>` buttons to be clickable in the built version.

### Actual behavior

The buttons on top of the `<Tabs>` component simply do nothing. Their background gets highlighted when the mouse hovers over them, and the cursor changes to a hand, but that's it. Seems like it's just the CSS working and the buttons have no effect.

Potential related issue: #3030

### Your environment

- Docusaurus version used: ^2.4.0
- Environment name and version (e.g. Chrome 89, Node.js 16.4): Node.js v18.7.0, Chrome 115
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): WSL, Ubuntu 22.04 Jammy

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by Josh-Cena** [comment]
By "open up the HTML", do you mean using `file://`? Have you tried serving it via HTTP?

**Comment by nullromo** [comment]
The use-case for this is running `npm run build`, then zipping up the build folder as a documentation bundle. The recipient of this bundle would unzip the file and open up `index.html` in their web browser. The intent is to make the documentation available offline, as in my case I do not have the means to host it publicly on the internet.

Based on your suggestion, I tried `npx serve -s build` and the tabs seem to work in that context. So now I'm confused because I thought Docusaurus should generate a static site. Why do I need to host the site and/or what is wrong with just opening up the html file? Based on my understanding, there should be no server interaction when clicking between tabs. You don't need to load any extra files or content, and anyway all the content should be accessible locally from the folder if you opened up the `index.html` file. Isn't the server just serving all those files that you already have? So the server shouldn't be necessary.

Anyway, if `file://` is somehow the issue here, is there any better way to bundle up a Docusaurus project in a zip file? I found the docs about [PWA](https://docusaurus.io/docs/api/plugins/@docusaurus/plugin-pwa), but I didn't think that was necessary because I don't need the end-users to install my docs, just open them up and read them.

Sorry if my questions are too basic. I appreciate your response.

**Comment by Josh-Cena** [comment]
Unfortunately this is an unresolved issue: https://github.com/facebook/docusaurus/issues/3825

`file://` doesn't work because the asset references are all relative to the site URL, like `href="/base-url/some/path"`, so you end up not loading any JS. To fix this you would need to transform all URL references to be relative to the `build` directory.

**Comment by nullromo** [comment]
Note to anyone coming here: for simplicity's sake I just changed out my `<Tabs>` with `<details>` since it's natively supported in HTML and does not require JavaScript.

It looks slightly worse, but it's an acceptable workaround in my case.

### Before
![image](https://github.com/facebook/docusaurus/assets/8991581/62ec66cd-253c-4b30-bcd8-aeb6ceb0f266)

### After
![image](https://github.com/facebook/docusaurus/assets/8991581/f6e49c34-e667-429f-b10e-d9269368f354)
