### ISSUE TITLE
isCategoryIndex function does not propagate to URL generations

### ISSUE THREAD

**Issue by anaclumos** [facebook/docusaurus#9213]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

I have set up

```
isCategoryIndex() {
  return false
},
```

for my docusaurus.config.js. And I have a folder structure of

```
08
├── 01.md
├── 02.md
├── 03.md
├── 04.md
├── 05.md
├── 06.md
├── 07.md
└── 08.md
```

As a folder structure of `docs/2023/08`. As you can see, it's just a calendar notation. However, while `isCategoryIndex` disables the sidebar behavior of overriding 'August 8th' to August, it still creates the URL for `2023/08`. 

### Reproducible demo

https://github.com/anaclumos/heimdall/tree/da910b28b2ae2d6ecf77225db38035e57cdaa637 (Exact Commit)

### Steps to reproduce

https://github.com/anaclumos/heimdall/tree/da910b28b2ae2d6ecf77225db38035e57cdaa637 (Exact Commit)

### Expected behavior

The URL for `docs/2023/08/08.md` should be generated at `sitename/2023/08/08`, not `sitename/2023/08`

### Actual behavior

The URL generates at `sitename/2023/08`

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by Josh-Cena** [comment]
Hi, this is deliberate by design. See https://github.com/facebook/docusaurus/pull/6451#discussion_r792670630. You would want to use the `slug` front matter instead.

**Comment by anaclumos** [comment]
If `because category index pages are not coupled to the slug system and we'd better not give users the impression that they are`, would there be an exposed function for isSlugIndex or so? I am generating many pages (thousands) and want as minimum information as possible.

**Comment by Josh-Cena** [comment]
This would be possible with the `createFrontMatter` hook: https://github.com/facebook/docusaurus/issues/5568

**Comment by slorber** [comment]
Yes, solving your use-case would be quite complicated. And a breaking change too (it's always quite risky for our users to change the permalink generation algo).

Currently the process is:
- Read docs files, generate metadata including a permalink for each
- Generate the autogenerated sidebar from those docs

Providing an explicit `slug` remains an option, although not as convenient. 

And `createFrontMatter` would also give you the ability to generate with code your own `slug` front matter.

Another option would allow to allow providing a `isCategoryIndex` callback as a first-class docs plugin option, and default to the current behavior. This would be the default `isCategoryIndex` that is passed as param to the `defaultSidebarItemsGenerator`. Once we have `createFrontMatter`, I'm not sure it would be a super useful option.
