### ISSUE TITLE
Blog post with title of 7.0.0 not working

### ISSUE THREAD

**Issue by yangshun** [facebook/Docusaurus#922]
## 🐛 Bug Report

First reported at https://github.com/babel/website/issues/1780

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## To Reproduce

1. Go to https://babeljs.io/blog/2018/08/27/7.0.0
1. Click on blog title

Original issue: https://github.com/babel/website/issues/1780

## Expected behavior

Should navigate to itself.

## Actual Behavior

Navigates to a 404.

## Reproducible Demo

Go to https://babeljs.io/blog/2018/08/27/7.0.0

<img width="1552" alt="screen shot 2018-08-27 at 4 17 12 pm" src="https://user-images.githubusercontent.com/1315101/44691723-a9d24e00-aa14-11e8-9c98-48777ea508a8.png">

**Comment by notjaril** [comment]
It seems that all the links from https://babeljs.io/blog to that blog post (sidebar/read more/title) is working as it should. 

The only link that's broken is the one attached to the blog post's title (https://babeljs.io/blog/2018/08/27/7.0.0). Is it possible to manually change the postHeaderTitle link?

**Comment by endiliey** [comment]
#923 should fix this
