### ISSUE TITLE
There is no clearall Button in Show

### ISSUE THREAD

**Issue by biplavmz** [facebook/docusaurus#9224]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Description

<img width="882" alt="image" src="https://github.com/facebook/docusaurus/assets/68702055/a13115ac-12cc-4f98-830c-883045cec030">

there is no clear all button in the showcase page. as if user want to remove all the selected tags at once he should have clear all button to remove all tags at one click 

I would like to add this feature. 

### Motivation

if user want to remove all the selected tags at once he should have clear all button

### Self-service

- [X] I'd be willing to contribute this feature to Docusaurus myself.

**Comment by Josh-Cena** [comment]
I'm okay to have a "reset" button to clear all queries.

**Comment by pinakipb2** [comment]
Thanks @slorber for not considering my PR where I had to go through code to fixed it first.
Peace 🤘

**Comment by slorber** [comment]
@pinakipb2 sorry but please don't assume any malice behind this: I'm simply busy and didn't see there were 2 PRs

Also the author of the issue checked this so it's fair to give them priority unless they don't send a PR in the upcoming days:

<img width="440" alt="CleanShot 2023-08-17 at 10 51 39@2x" src="https://github.com/facebook/docusaurus/assets/749374/6c194fb4-8e6f-48bd-968a-29d358318791">

**Comment by pinakipb2** [comment]
No problem.
