### ISSUE TITLE
Customize sidebar top back button

### ISSUE THREAD

**Issue by houssemmimoun27** [facebook/docusaurus#9225]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Description

How to customize the sidebar top back button text ?

![Screenshot 2023-08-14 at 15 17 44](https://github.com/facebook/docusaurus/assets/93918596/f33c5e9a-b9ab-42f9-8711-5519c2e9ebd0)

### Self-service

- [ ] I'd be willing to address this documentation request myself.

**Comment by pinakipb2** [comment]
@houssemmimoun27 Try changing these files.

![image](https://github.com/facebook/docusaurus/assets/48859773/e6b7087e-9960-47af-a40c-a6d9eca01f7d)

**Comment by Josh-Cena** [comment]
Please don't use issues for questions. Please read https://docusaurus.io/docs/swizzling#do-i-need-to-swizzle.
