### ISSUE TITLE
CodeBlock breaks unpredictably as new lines are added

### ISSUE THREAD

**Issue by trigaten** [facebook/docusaurus#9240]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

This is quite an odd issue! Basically, I have a block of code like this:

```jsx
<CodeBlock
  language="jsx"
  title="/src/components/HelloCodeTitle.js"
  showLineNumbers>
  {`function HelloCodeTitle(props) {
  // there should be empty lines after this
  
  
  // there should be empty lines above this
  return <h1>Hello, {props.name}</h1>;
}`}
</CodeBlock>
```

Whenever I add a new line break between the two comments, I *usually* (90% of the time) get the following error:

```zsh
SyntaxError: /Users/sanderschulhoff/Documents/VSCode Projects/Learn_Prompting/docs/basics/instructions.mdx: Unexpected token, expected "}" (70:0)
  68 |   
  69 | <p>{`  // there should be empty lines above this
> 70 | return `}<h1>{`Hello, {props.name}`}</h1>{`;
     | ^
  71 | }\`}`}</p>
  72 | </CodeBlock>
  73 | <p>{`Here is the AI's response`}<sup parentName="p" {...{"id":"fnref-c"}}><a parentName="sup" {...{"href":"#fn-c","className":"footnote-ref"}}>{`c`}</a></sup>{`:`}</p>
client (webpack 5.88.2) compiled with 1 error
```

For some reason, it doesn't like me adding lines. The only way I can add a new line and get the docs to build properly is if I add a ton of new lines at once, then delete them one by one, until docusaurus is okay (I have no idea why). 

### Steps to reproduce

1. Get any docusaurus project
2. Build the docs with `npm start`
3. Add this snippet to any `.md` `docs` page:
```jsx
<CodeBlock
  language="jsx"
  title="/src/components/HelloCodeTitle.js"
  showLineNumbers>
  {`function HelloCodeTitle(props) {
  // there should be empty lines after this
  
  
  // there should be empty lines above this
  return <h1>Hello, {props.name}</h1>;
}`}
</CodeBlock>
```
4. Add spaces in between the comments until the build breaks!

### Your environment

<img width="205" alt="Screenshot 2023-08-17 at 4 41 53 PM" src="https://github.com/facebook/docusaurus/assets/42948753/f765df45-0139-445c-927b-6709b7b7f063">

npx version: 9.7.2
node version: v20.4.0

VSCode, a bash or zsh terminal

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by Josh-Cena** [comment]
Curious why you are using `CodeBlock` instead of this in MDX?

~~~md
```jsx title="/src/components/HelloCodeTitle.js" showLineNumbers
function HelloCodeTitle(props) {
  // there should be empty lines after this
  
  
  // there should be empty lines above this
  return <h1>Hello, {props.name}</h1>;
}
```
~~~

This is an MDX bug. You can test using https://mdx-git-renovate-babel-monorepo-mdx.vercel.app/playground. We don't control MDX parsing. This may be fixed in Docusaurus v3, which uses MDX v2, though.

**Comment by trigaten** [comment]
> There's no such element in JSX because JSX is always whitespace-insensitive. If you are authoring Markdown, you should just use normal code blocks.


Is there a good way to create my own custom code blocks that have custom titles/images like this:

<img width="795" alt="Screenshot 2023-08-17 at 7 17 22 PM" src="https://github.com/facebook/docusaurus/assets/42948753/890bf573-8f0b-4912-a57b-539d83632729">

**Comment by Josh-Cena** [comment]
The best option is to swizzle `CodeBlock`. See https://docusaurus.io/docs/swizzling. You can submit a discussion instead if you want to discuss it further.
