### ISSUE TITLE
unable to search or type the text input focus changes while typing 

### ISSUE THREAD

**Issue by biplavmz** [facebook/docusaurus#9248]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

unable to search or type the text input focus changes while typing 

https://github.com/facebook/docusaurus/assets/68702055/0fb90d78-1aa4-491e-8b7e-9a2da67674b0

### Steps to reproduce

go to the website and click on showcase and start typing on search for site name

### Expected behavior

able to write the text on enter or after  2sec 

### Actual behavior

able to write the text after  that search will happen

### Your environment

- Public source code:
- Public site URL:
- Docusaurus version used:
- Environment name and version (e.g. Chrome 89, Node.js 16.4):
- Operating system and version (e.g. Ubuntu 20.04.2 LTS):

### Self-service

- [X] I'd be willing to fix this bug myself.

**Comment by biplavmz** [comment]
hii @slorber @Josh-Cena  please look into this issue pls assign me this issue i would like to work on it.

**Comment by slorber** [comment]
@biplavmz please submit a PR, we don't assign small issues here. First draft PR will be the one I'm more likely to merge.

Hint: `<SearchBar>` should be moved outside `<ShowcaseCards>`
