### ISSUE TITLE
Create a basic README for new Docusaurus project

### ISSUE THREAD

**Issue by endiliey** [facebook/Docusaurus#925]
## 🚀 Feature

When running `docusaurus-init`, we should at least create a basic README.md in `website` folder.

## Have you read the [Contributing Guidelines on issues](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## Pitch

This will help anyone who contributes to a project using Docusaurus on how to quickly get started. The README created in `website/README.md` should contains something like this below. Be creative with the wordings :smiley: 

------------------------------------------------------------------------------------------------------------------

## 🚀 &nbsp; Introduction

This website was created with [Docusaurus](https://github.com/facebook/Docusaurus).

## 📟 &nbsp; Install and Usage

First of all, you will need to install all the dependencies for the website

```bash
$ yarn
```

Now just run your dev server

```bash
$ yarn start
```

That's it! Now you can make changes to the `docs` folder of the project directory.

Check [docusaurus.io](https://docusaurus.io) to see more about **Docusaurus**!

--------------------------------------------------------------------------------------------------------------------

Some examples:
-https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/template/README.md
-https://github.com/facebook/react-native-website
-(insert any other good oss project)>

**Comment by notjaril** [comment]
I can take this on :)
