### ISSUE TITLE
Docker for Docusaurus

### ISSUE THREAD

**Issue by endiliey** [facebook/Docusaurus#926]
## 🚀 Documentation

At least document on how to create a docker image for Docusaurus project or anything related to Docker.

## Have you read the [Contributing Guidelines on issues](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

**Comment by wszgxa** [comment]
Could I take this one?

**Comment by endiliey** [comment]
@wszgxa it's yours!

I've added an "issue-claimed" label so that others will know not to start work on the issue. If you change your mind about the issue, no worries! Just let me know so that I can remove the label and free it up for someone else to claim.

I'll check in with you periodically so that we can keep the task updated with the progress.

**Comment by yangshun** [comment]
Closed by #936
