### ISSUE TITLE
Error:  TypeError: Cannot set properties of undefined (setting 'minItems')

### ISSUE THREAD

**Issue by blacktop** [facebook/docusaurus#9271]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

My GitHub action started failing to build/deploy my site a week+ ago?
```
Run yarn build
yarn run v1.22.19
$ docusaurus build
[INFO] [en] Creating an optimized production build...
[ReDoc Compatibility mode]: Converting OpenAPI 2.0 to OpenAPI 3.0
TypeError: Cannot set properties of undefined (setting 'minItems')
    at C (/home/runner/work/ipsw/ipsw/www/node_modules/redoc/bundles/redoc.lib.js:2:33595)
    at T (/home/runner/work/ipsw/ipsw/www/node_modules/redoc/bundles/redoc.lib.js:2:43282)
    at /home/runner/work/ipsw/ipsw/www/node_modules/redoc/bundles/redoc.lib.js:2:52463
    at /home/runner/work/ipsw/ipsw/www/node_modules/redoc/bundles/redoc.lib.js:2:54330
Error:  Unable to build website for locale en.
Error:  TypeError: Cannot set properties of undefined (setting 'minItems')
    at C (/home/runner/work/ipsw/ipsw/www/node_modules/redoc/bundles/redoc.lib.js:2:33595)
    at T (/home/runner/work/ipsw/ipsw/www/node_modules/redoc/bundles/redoc.lib.js:2:43282)
    at /home/runner/work/ipsw/ipsw/www/node_modules/redoc/bundles/redoc.lib.js:2:52463
    at /home/runner/work/ipsw/ipsw/www/node_modules/redoc/bundles/redoc.lib.js:2:54330
[INFO] Docusaurus version: 2.4.1
Node version: v18.17.1
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Error: Process completed with exit code 1.
```
### Reproducible demo

https://github.com/blacktop/ipsw/actions/workflows/docs.yml

### Steps to reproduce

git clone https://github.com/blacktop/ipsw.git
cd ipsw/www
npm run build

### Expected behavior

builds/deploys without issue

### Actual behavior

I get the above error stack dump

### Your environment

- Public source code: https://github.com/blacktop/ipsw/tree/master/www
- Public site URL: https://blacktop.github.io/ipsw/
- Docusaurus version used: 2.4.1
- Environment name and version (e.g. Chrome 89, Node.js 16.4): GH ubuntu-latest runner
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): GH ubuntu runner

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by slorber** [comment]
Hey

That would have been helpful if you mentionned which commit exactly broke your build. 
After inspecting your repo, this is the one: https://github.com/blacktop/ipsw/commit/59eac04013d5f490e41fa58f28cb1ce263faf8e8

You are upgrading Redocusaurus, which is a third-party plugin that we don't maintain nor support. 
The stacktrace show the issue is related to OpenAPI / Redoc.

All that is not part of Docusaurus core, I don't know how Redoc or Redocusaurus work. I suggest reporting this bug to the apporopriate repo https://github.com/rohit-gohri/redocusaurus, and in the meantime reverting the upgrade.
