### ISSUE TITLE
Can't use math expressions using '|' in Markdown tables (remark-math/KaTeX/GFM)

### ISSUE THREAD

**Issue by dbxxx-oi** [facebook/docusaurus#9272]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

```plain
| $1$       | $2$       |
| --------- | --------- |
| $|3| = 3$ | $|4| = 4$ |
```

will be rendered like:

![image](https://github.com/facebook/docusaurus/assets/46753037/644a99eb-b045-4c8d-a132-b88b01619011)

The '|' inside the latex expression is mistaken for a separator for the sheet.

### Steps to reproduce

write
```plain
| $1$       | $2$       |
| --------- | --------- |
| $|3| = 3$ | $|4| = 4$ |
```
inside a doc.

### Expected behavior

The '|' in the latex expression is processed correctly.

### Actual behavior

The '|' in the latex expression is mistaken for a separator for the sheet.

### Your environment

- Public source code:
- Public site URL:
- Docusaurus version used:latest
- Environment name and version (e.g. Chrome 89, Node.js 16.4):Microsoft Edge, Node.js 18.12.1
- Operating system and version (e.g. Ubuntu 20.04.2 LTS):Windows 11

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by slorber** [comment]
Hey

This is already fixed for Docusaurus v3 with MDX v2. You'll have to escape the pipes with `\|` in math expressions.


```md
| $1$         | $2$         |
| ----------- | ----------- |
| $\|3\| = 3$ | $\|4\| = 4$ |
``` 

<img width="220" alt="CleanShot 2023-08-31 at 12 14 21@2x" src="https://github.com/facebook/docusaurus/assets/749374/d8888ea6-81e6-4cf7-8c2e-50ebe511a421">

I'm not sure there's a good way to do that under Docusaurus v2 (MDX v1). My suggestion would be to wait for Docusaurus v3, it should move to beta very soon.

**Comment by dbxxx-oi** [comment]
> Hey
> 
> This is already fixed for Docusaurus v3 with MDX v2. You'll have to escape the pipes with `\|` in math expressions.
> 
> ```
> | $1$         | $2$         |
> | ----------- | ----------- |
> | $\|3\| = 3$ | $\|4\| = 4$ |
> ```
> 
> <img alt="CleanShot 2023-08-31 at 12 14 21@2x" width="220" src="https://user-images.githubusercontent.com/749374/264613538-d8888ea6-81e6-4cf7-8c2e-50ebe511a421.png">
> I'm not sure there's a good way to do that under Docusaurus v2 (MDX v1). My suggestion would be to wait for Docusaurus v3, it should move to beta very soon.

That will be awesome! Thanks! But why is there double vertical line?

**Comment by slorber** [comment]
That's a good question 😅 any idea @wooorm ?

**Comment by slorber** [comment]
Hmmm, not sure if it's a bug 😅 
But it seems Katex receives the escaping char `\`

<img width="834" alt="CleanShot 2023-08-31 at 14 14 34@2x" src="https://github.com/facebook/docusaurus/assets/749374/55138460-7e24-40cb-b27b-4d6ced738bc6">

---

```mdx
$\|3\| = 3$

---

$|3| = 3$

---

| $1$                      | $2$                      |
| ------------------------ | ------------------------ |
| $\|3\| = 3$              | $\|4\| = 4$              |
| <code>$\|3\| = 3$</code> | <code>$\|4\| = 4$</code> |
```

<img width="301" alt="CleanShot 2023-08-31 at 14 21 01@2x" src="https://github.com/facebook/docusaurus/assets/749374/d9fd9641-071e-4312-887f-5996919c80fb">


---

Would you be ok to add remark-math to the MDX playground options @wooorm ? That could be useful to debug this kind of issues.

**Comment by wooorm** [comment]
It should work the same as code. Code doesn’t get two pipes.
Normally escapes don’t work in code. But in tables, GH supports it, and does not show the slash.
Same with math.

yeah, having math in the mdx playground is fine!

**Comment by slorber** [comment]
That's what the MDX playground reports with GFM + math turned on:

<img width="778" alt="CleanShot 2023-08-31 at 18 44 34@2x" src="https://github.com/facebook/docusaurus/assets/749374/43136766-e482-4444-b643-1d12dd54fd44">

To me, the `\|` is unexpected there, and it looks like a bug in https://github.com/micromark/micromark-extension-math right?

**Comment by dbxxx-oi** [comment]
Well, maybe using `\vert`  instead of `|` can be a solution?

**Comment by dbxxx-oi** [comment]
<https://katex.org/docs/supported> KaTeX will render `\|` as `\Vert`, which is double pipes, and this behavior is different from MathJax does, for MathJax will render `\|` as a single pipe. GitHub uses MathJax.

```plain
| $1$       | $2$       |
| --------- | --------- |
| $|3| = 3$ | $|4| = 4$ |
```

| $1$       | $2$       |
| --------- | --------- |
| $|3| = 3$ | $|4| = 4$ |

**Comment by Josh-Cena** [comment]
> Well, maybe using `\vert` instead of `|` can be a solution?

Yes, except maybe the former is more verbose, they are exactly equivalent.

`\|` becoming `\Vert` is consistent with LaTeX; I bet MathJax doesn't implement it this way because it would be too confusing in many JavaScript contexts (such as the case here!)

I don't think there's anything we can help, though—all parsing work is delegated to `remark-gfm` and `remark-math`.

So the issue here is this: anything inside math is literally preserved—there's no character escaping because `\` is a very meaningful thing in LaTeX. However, when tables get parsed, it doesn't understand anything about other Markdown syntax—it even extracts pipe characters from inline code spans. Therefore the two parsers are in conflict and I don't see a way to reconcile them without fundamentally changing how one of them works. Avoiding the pipe character altogether may be the best solution.

**Comment by Josh-Cena** [comment]
Markdown parsing is delegated entirely to MDX and its plugins. There's nothing we can act on here.

**Comment by dbxxx-oi** [comment]
> Markdown parsing is delegated entirely to MDX and its plugins. There's nothing we can act on here.

This question could be troublesome now, for MDX v2 doesn't allow `{}` and `<>` any more, so now writing KaTeX could be very hard. For example, `$\dfrac{4F}{2}$` can cause a compilation error.

Is there a solution? Thank you for your reply.

**Comment by Josh-Cena** [comment]
@dbxxx-oi Works for me in the [playground](https://mdxjs.com/playground/). Are you using the latest version of remark-math instead of what's shown in the docs?

**Comment by dbxxx-oi** [comment]
<https://github.com/mdx-js/mdx/issues/1462> It seems that it's not a mdx problem

**Comment by dbxxx-oi** [comment]
> @dbxxx-oi Works for me in the [playground](https://mdxjs.com/playground/). Are you using the latest version of remark-math instead of what's shown in the docs?

Thank you for your reply! No, I'm not using the latest version, sorry for that mistake. 

I updated remark-math to 6.0.0 and rehype-katex to 7.0.0, and rewrote docusaurus.config.js according to [this](https://docusaurus.io/docs/3.0.0-rc.0/markdown-features/math-equations#configuration).

This is my docusaurus.config.js:

```js
// @ts-check
// Note: type annotations allow type checking and IDEs autocompletion

const {themes} = require('prism-react-renderer');
const lightTheme = themes.github;
const darkTheme = themes.dracula;
import remarkMath from 'remark-math';
import rehypeKatex from 'rehype-katex';

const webpackAssetSourcePlugin = () => ({
	configureWebpack() {
		return {
			module: {
				rules: [{
					test: /\.ggb$/,
					use: [
						{
							loader: 'file-loader',
							options: {name: 'assets/ggb/[name]-[hash].[ext]'}
						}
					]
				}]
			}
		}
	}
});

export default {
	title: 'whk wiki',
	tagline: 'whk wiki 致力于产出优秀的文化课资源',
	favicon: 'img/favicon.ico',

	url: 'https://whk-wiki.github.io',
	baseUrl: '/',


	trailingSlash: false,
	onBrokenLinks: 'throw',
	onBrokenMarkdownLinks: 'warn',

	i18n: {
		defaultLocale: 'zh-Hans',
		locales: ['zh-Hans'],
	},

	presets: [
		[
			'classic',
			({
				docs: {
					routeBasePath: '/',
					sidebarPath: require.resolve('./sidebars.js'),
					// Please change this to your repo.
					// Remove this to remove the "edit this page" links.
					editUrl:
						'https://github.com/facebook/docusaurus/tree/main/packages/create-docusaurus/templates/shared/',
					remarkPlugins: [remarkMath],
					rehypePlugins: [rehypeKatex],
				},
				blog: false,
				theme: {
					customCss: require.resolve('./src/css/custom.css'),
				},
			}),
		],
	],

	stylesheets: [
		{
			href: 'https://cdn.jsdelivr.net/npm/katex@0.13.24/dist/katex.min.css',
			type: 'text/css',
			integrity:
				'sha384-odtC+0UGzzFL/6PNoE8rX/SPcQDXBJ+uRepguP4QkPCm2LBxH3FA3y+fKSiJ+AmM',
			crossorigin: 'anonymous',
		},
	],

	themeConfig:
		/** @type {import('@docusaurus/preset-classic').ThemeConfig} */
		({
			// Replace with your project's social card
			defaultMode: 'dark',
			image: 'img/docusaurus-social-card.jpg',
			navbar: {
				hideOnScroll: true,
				title: 'whk wiki',
				logo: {
					alt: 'whk wiki logo',
					src: 'img/logo.svg',
				},
				items: [
					{
						type: 'docSidebar',
						sidebarId: 'introSidebar',
						position: 'left',
						label: '开始',
					},
					{
						type: 'doc',
						docId: 'home/math',
						position: 'left',
						label: '数学',
					},
					{
						type: 'doc',
						docId: 'home/physics',
						position: 'left',
						label: '物理',
					},
					{
						type: 'doc',
						docId: 'home/chemistry',
						position: 'left',
						label: '化学',
					},
					{
						type: 'docSidebar',
						sidebarId: 'biologySidebar',
						position: 'left',
						label: '生物',
					},
					{
						href: 'https://github.com/whk-wiki/whk-wiki',
						label: 'GitHub',
						position: 'right',
					},
				],
			},
			docs: {
				sidebar: {
					autoCollapseCategories: true,
					hideable: true
				},
			},
			footer: {
				style: 'dark',
				copyright: `本文档由 Docusaurus 搭建．`,
			},
			prism: {
				theme: lightTheme,
				darkTheme: darkTheme,
			},
		}),

	plugins: [
		// @ts-ignore
		webpackAssetSourcePlugin
	],
};
```

But when I try to build, an error occured: 

> C:\Users\xbc\Desktop\programming\Projects\whk-wiki\docusaurus.config.js:7
> import remarkMath from 'remark-math';
> ^^^^^^
> SyntaxError: Cannot use import statement outside a module

I'm poor in react-js and I don't know too much on ES Modules. I've tried several solutions but they didn't work. Is there anyway to solve it? Appreciate to your reply again!

**Comment by Josh-Cena** [comment]
Try this:

```js
const {themes} = require('prism-react-renderer');
const lightTheme = themes.github;
const darkTheme = themes.dracula;

module.exports = async () => {
  const remarkMath = await import('remark-math');
  const rehypeKatex = await import('rehype-katex');
  return {
    // Your config object
  };
};
```

Further support should use the discussions board instead of this already-closed issue.

**Comment by slorber** [comment]
ES config file works now and simplify usage of remark plugins:

```js
import remarkMath from 'remark-math';
import rehypeKatex from 'rehype-katex';

export default {
  presets: [
    [
      '@docusaurus/preset-classic',
      {
        docs: {
          path: 'docs',
          remarkPlugins: [remarkMath],
          rehypePlugins: [rehypeKatex],
        },
      },
    ],
  ],
};
```

Not sure how newer versions of plugins will work with Docusaurus (this is third-party code and we can't guess future changes will always be compatible), but for us those versions work fine: `remark-math@5 rehype-katex@6`
