### ISSUE TITLE
Progressive Image Loading

### ISSUE THREAD

**Issue by endiliey** [facebook/docusaurus#928]
## Have you read the [Contributing Guidelines on issues](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## Motivation

To improve the user experience. When visiting a page, for example: https://docusaurus.io/en/users
We can see that by default browser will not display the image until it is fully downloaded. 

## Pitch

Note that Medium did this and they have a very nice image loading effect. 
First, load a small blurry image, and then transition to the large image. I found it pretty neat 

Look at this codepen for example of loading fortnite wallpaper
https://codepen.io/endiliey/pen/wEzoBJ

Current **baseline image loading** (which most website does)

![image](https://user-images.githubusercontent.com/17883920/44766748-867ede80-ab8d-11e8-95ec-8acec0596120.png)

**Progressive image loading**
![image](https://user-images.githubusercontent.com/17883920/44766776-9ac2db80-ab8d-11e8-9e5c-c47f560183f1.png)

**Comment by notjaril** [comment]
I’d like to take this on!

**Comment by endiliey** [comment]
@notjaril it's yours!

I'll check in with you periodically so that we can keep the task updated with the progress.

**Comment by endiliey** [comment]
You might want to check this out

https://github.com/Paul-Browne/lazyestload.js

**Comment by wszgxa** [comment]
Hi, @notjaril 

Do you still work on this one?

**Comment by yangshun** [comment]
@notjaril How's your progress for this task? Let us know how we can help. If you are no longer available for this task, just let us know and we can free it up for someone else. Do keep us updated 😄

**Comment by NishealJ** [comment]
Hi @notjaril, are your working on this?
@yangshun doubt, are we planning this only for users page?

**Comment by yangshun** [comment]
If we were to do it, it shouldn't be just for users page. But I don't think it's a high-priority for now.
