### ISSUE TITLE
Change location of /style.css & /main.js

### ISSUE THREAD

**Issue by anvme** [facebook/docusaurus#9284]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Description

It's possible to change the location of the /style.css & /main.js  ?
I want to move these megabytes to external storage and deliver it via CDN

### Motivation

Faster delivery of website content to the users.
CSS content change is rare.

### Self-service

- [ ] I'd be willing to contribute this feature to Docusaurus myself.

**Comment by anniepauline** [comment]
Hey !! Is It up for grabs?

**Comment by anvme** [comment]
> Hey !! Is It up for grabs?

What do you mean?

It will be nice to have an option to upload all /assets files to SFTP & S3 to specific location

**Comment by anvme** [comment]
As example
![Screenshot 2023-09-06 at 16 16 34-2](https://github.com/facebook/docusaurus/assets/56738034/de865a58-b5f2-4527-aa1b-ab6a3540467e)

**Comment by slorber** [comment]
This has already been discussed a few times already, like here: https://github.com/facebook/docusaurus/discussions/4123

We recommend that you put **everything** on a CDN, not just style.css and main.js.
Unless you come up with a very strong reason to not do that, nothing will be implemented
