### ISSUE TITLE
Blog link breaks

### ISSUE THREAD

**Issue by dhuber23b** [facebook/Docusaurus#929]
## 🐛 Bug Report

When you run the command:
yarn run publish-gh-pages
to publish your site, the blog page (assuming you have one set up) does not get the css.  As a result, the page looks ugly and unformatted.

The workaround, according to Joel Marcey, is to switch to the gh-pages branch and copy the file blog/index.html to blog.html.  

I am not entirely sure why this workaround works, but it does.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

No.

## To Reproduce

1. Setup a site that has a blog
2. publish the site
3. navigate to the blog page
4. observe that it is incorrectly formatted

## Expected behavior

correctly formatted blog

## Actual Behavior

incorrectly formatted blog

## Reproducible Demo

https://github.com/facebookresearch/sumo-challenge/tree/gh-pages

**Comment by endiliey** [comment]
Hi @dhuber23b,

I sent a PR on https://github.com/facebookresearch/sumo-challenge/pull/1 to update Docusaurus.
Can you merge that and we'll work from there ?

Thanks

**Comment by JoelMarcey** [comment]
@endiliey Is this still something we need to fix?

**Comment by endiliey** [comment]
Upon my investigation, it's actually caused by not having CNAME -> hence instead of https://sumochallenge.org/blog it became facebookresearch.github.io/sumo-challenge/blog so the CSS breaks due to wrong baseUrl.

But I haven't seen sumo-challenge publish the website yet to see the CNAME set takes effect in gh-pages
