### ISSUE TITLE
Docusaurus + Node.js 20.6 doesn't work

### ISSUE THREAD

**Issue by slorber** [facebook/docusaurus#9291]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [ ] I have tried the `npm run clear` or `yarn clear` command.
- [ ] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io.
- [ ] I have read the console error message carefully (if applicable).

### Description

Docusaurus doesn't work under Node.js 20.6.0

Very likely related to a Node.js bug: https://github.com/nodejs/node/issues/49497

That should be fixed soon. 

In the meantime I don't think there's anything we can do apart using a different Node.js version.

Going to close all the other related Docusaurus issues as duplicate. For now we have:
- https://github.com/facebook/docusaurus/issues/9286
- https://github.com/facebook/docusaurus/issues/9290
- https://github.com/facebook/docusaurus/issues/9278

### Steps to reproduce

Use Node.js 20.6 + Docusaurus

### Expected behavior

It works

### Actual behavior

It doesn't work

### Your environment

- Public source code:
- Public site URL:
- Docusaurus version used:
- Environment name and version (e.g. Chrome 89, Node.js 16.4):
- Operating system and version (e.g. Ubuntu 20.04.2 LTS):

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by jackblanc** [comment]
Same issue

**Comment by jarodreyes** [comment]
I'm also on node v20.6 and I am getting the following when I try `npx create-docusaurus@latest my-website classic`. Output:
`npm WARN deprecated stable@0.1.8: Modern JS already guarantees Array#sort() is a stable sort, so this library is deprecated. See the compatibility table on MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#browser_compatibility
(node:33254) Warning: Accessing non-existent property 'register' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
[ERROR] TypeError: common.register is not a function`

**Comment by natarajsundar** [comment]
This issue is resolved in Node 20.6.1, can be closed.

**Comment by Josh-Cena** [comment]
Can I get others to confirm? @homotechsual, @alewolf, @milesj?

**Comment by milesj** [comment]
Looks to be working 👍

**Comment by Josh-Cena** [comment]
Great, let's close unless someone else reports otherwise 👍

**Comment by alewolf** [comment]
I'll have to wait until Homebrew updates its tap to the newest version. I'll let you know once that's done.

**Comment by homotechsual** [comment]
All good now on 20.6.1

**Comment by milesj** [comment]
@alewolf Should try https://moonrepo.dev/proto

**Comment by Vrushank796** [comment]
Still getting the same error as #9278 in Node v20.15.0

**Comment by Hexi1997** [comment]
same question

**Comment by slorber** [comment]
We aren't going to do anything on your comments here unless you open a new dedicated issue with a repro.
