### ISSUE TITLE
[Bug]: Using the remark-directive plugin, custom directives cannot be used

### ISSUE THREAD

**Issue by guoqqqi** [facebook/docusaurus#9301]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

I use the `remark-directive` plugin and want to customize a directive to specify the rendering of part of the markdown file. I cannot obtain the information about the directive in my custom plugin. It is always rendered as  `<p />`

### Reproducible demo

https://github.com/guoqqqi/docusaurus-remark-plugin

### Steps to reproduce

1. Enable `@docusaurus/plugin-content-docs` plugin
2. Add `remark-directive` plugin and add it to the `docusaurus.config.js` file
3. Create a new custom remark plugin:
```
import { visit } from 'unist-util-visit';

export const pluginFiled = () => {
  const transformer = async (ast) => {
    visit(ast, (node) => {
      if (node.type === 'textDirective' ||
        node.type === 'leafDirective' ||
        node.type === 'containerDirective') {
        console.log('node: ', node);
        const isPluginField = node.name === 'plugin-field';
        if (!isPluginField) return;
      }
    });
  }

  return transformer;
};

```
4. Use this directive failed
```
:::plugin-field
123
:::
```

**I can't get `node.name` and the `textDirective`, `leafDirective` and `containerDirective` types are not found in the `node.type`**

### Expected behavior

I hope that my instruction information can be read in `node.type`

### Actual behavior

 I cannot obtain the information about the directive in my custom plugin. It is always rendered as  `<p />`

### Your environment

- Public source code:
- Public site URL:
- Docusaurus version used:
- Environment name and version (e.g. Chrome 89, Node.js v18.17.1):
- Operating system and version (e.g. Mac M1):

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by slorber** [comment]
Closing because a repro was provided but uses Docusaurus v2, which won't support remark directives.

Please upgrade to Docusaurus v3 (alpha). It's safe, I'm writing marketing material and upgrade guides for the official launch.

You can see in the mdx playground that it works by turning the "remark-directive" option on:

![CleanShot 2023-09-14 at 12 47 36](https://github.com/facebook/docusaurus/assets/749374/87bce9c3-52ee-4dc7-8aeb-41bc0fab4bbe)
