### ISSUE TITLE
The programming experience with IDEA is terrible

### ISSUE THREAD

**Issue by xiaoqian2006** [facebook/docusaurus#9306]
### Have you read the Contributing Guidelines on issues?

- [ ] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Motivation

<img width="757" alt="image" src="https://github.com/facebook/docusaurus/assets/40530007/d7495873-89c9-4f2d-a84e-9abf240908d0">

<img width="719" alt="image" src="https://github.com/facebook/docusaurus/assets/40530007/223df18e-4b51-4973-a6a1-431d812a196e">

Can you come up with an IDEA plugin so that these components can code hints normally on IDEA?

### Self-service

- [ ] I'd be willing to do some initial work on this proposal myself.

**Comment by slorber** [comment]
This is a known limitation but it is not related in any way to IDEA: we simply do not provide TypeScript definitions for wrapped components because we don't have a system to emit those.

Please don't be condescending. If you know how to fix it, your PR is welcome.
