### ISSUE TITLE
v3 doc: Prettier hasn't supported MDX v2 or v3 yet

### ISSUE THREAD

**Issue by tats-u** [facebook/docusaurus#9318]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Description

https://docusaurus.io/docs/next/markdown-features/admonitions#usage-with-prettier

Prettier hasn't supported MDX v2 yet.
https://github.com/prettier/prettier/issues/12209

We'll have to advise users to stop formatting MDX by Prettier for a while after upgrading Docusaurus to v3.

What page should we add this admonition?

### Self-service

- [x] I'd be willing to address this documentation request myself.

**Comment by tats-u** [comment]
> We handle a few exceptions in our own code, using comments:

This is just because the official documents doesn't use many React components in MDX. Such a cheap trick won't work for documents that use React components frequently. They'll have to pollute themselves with too many `prettier-ignore`'s to be ignored. If it's not a hassle for users to add `prettier-ignore` to every incompatible part, we won't have to tell them to stop using Prettier. It depends on whether it is painful for them or not but _is_ for some of them. What we should tell to users is just "If it's a pain, you may as well suspend using Prettier for MDX".


> Note: we are not the first to use MDX v2, and if you look at other systems like Nextra or Astro they don't mention Prettier not supporting MDX v2 officially in their docs.

We are the last to use MDX v1 as far as I know.
Many MDX v2 users have often claimed Prettier had "defects" in the MDX formatting feature in issues in Prettier. (the identity of the "defects" is just the mismatch of MDX versions)

**Comment by slorber** [comment]
Not sure what to do but if you want to submit a proposal PR please do and we'll discuss it from there.

I don't think Prettier works less well with MDX v2 that v1. 

And most sites will probably, like the Docusaurus site, not have extensive usage of inline React code inside MDX docs. Most Docusaurus sites still use the historical `.md` extension, and prettier will not format MDX elements very well with that extension anyway 😓 

And Prettier is not the only problem: our "i18n SaaS" Crowdin also has limited MDX support, with a workaround proposed here: https://docusaurus.io/docs/next/i18n/crowdin#mdx

---

Note we already recommend declaring complex JSX code outside of Markdown files here:

<img width="897" alt="CleanShot 2023-09-20 at 16 07 11@2x" src="https://github.com/facebook/docusaurus/assets/749374/eb53c115-e86a-481a-a2f0-aa5597c107ab">

I think we can still stand by this practice of avoiding inline React/JSX code if possible:
- when using versioning it leads to duplicate logic
- when using i18n/Crowdin it often leads to bad translated content output that doesn't compile (Crowdin bugs)
- when using Prettier it leads to bad formatting

That could be a good place to put an extra admonition?

**Comment by tats-u** [comment]
> Not sure what to do but if you want to submit a proposal PR please do and we'll discuss it from there.

I will. I'll recommend to Prettier + MDX users to try `prettier-ignore` first.

> And most sites will probably, like the Docusaurus site, not have extensive usage of inline React code inside MDX docs. Most Docusaurus sites still use the historical .md extension, and prettier will not format MDX elements very well with that extension anyway 😓

Now that you mention it, most documents for software don't have to use features beyond Markdown coverage too much.
