### ISSUE TITLE
Vulnerabilities

### ISSUE THREAD

**Issue by MeinLieblingsmensch** [facebook/Docusaurus#932]
## 🐛 Bug Report

NPM reports vulnerabilities upon installing Docusaurus, on Node v10.6.0 MacOS High Sierra

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## To Reproduce

1. npm install docusaurus -D

## Expected behavior

Install Docusaurus without issues

## Actual Behavior

NPM reports there are 7 new vulnerabilities 

as well as the following

`npm WARN deprecated browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
npm WARN deprecated coffee-script@1.12.7: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)
`

Upon running `'npm audit'`

<img width="921" alt="screen shot 2018-08-30 at 18 31 54" src="https://user-images.githubusercontent.com/33750251/44868699-734e3a80-ac83-11e8-9167-b3589e916588.png">

<img width="886" alt="screen shot 2018-08-30 at 18 32 09" src="https://user-images.githubusercontent.com/33750251/44868579-29fdeb00-ac83-11e8-8171-e56010b35ad5.png">

## Reproducible Demo

None, just install Docusaurus

**Comment by endiliey** [comment]
This is caused due to imagemin dependency on Docusaurus. I think the right place to file the issue is at https://github.com/imagemin
