### ISSUE TITLE
Trying to upgrade docusaurus from 2.2.0 to 2.4.3 gives me errors

### ISSUE THREAD

**Issue by ThibaultJanBeyer** [facebook/docusaurus#9334]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

As the title says, trying to up from 2.2.0 to 2.4.3 breaks when I try to build the project (on the server):

```
[ERROR] Unable to build website for locale en.
[ERROR] Error: Failed to compile with errors.
    at /Volumes/case/Playground/DragSelect/www/node_modules/@docusaurus/core/lib/webpack/utils.js:180:24
    at /Volumes/case/Playground/DragSelect/www/node_modules/webpack/lib/MultiCompiler.js:554:14
    at processQueueWorker (/Volumes/case/Playground/DragSelect/www/node_modules/webpack/lib/MultiCompiler.js:491:6)
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)
```

and previously some warnings:

```
[WARNING] {"moduleIdentifier":"/Volumes/case/Playground/DragSelect/www/node_modules/babel-loader/lib/index.js??ruleSet[1].rules[8].use[0]!/Volumes/case/Playground/DragSelect/www/node_modules/@docusaurus/mdx-loader/lib/index.js??ruleSet[1].rules[8].use[1]!/Volumes/case/Playground/DragSelect/www/node_modules/@docusaurus/plugin-content-docs/lib/markdown/index.js??ruleSet[1].rules[8].use[2]!/Volumes/case/Playground/DragSelect/www/docs/intro.mdx","moduleName":"./docs/intro.mdx","loc":"56:486-489","message":"export 'mdx' (imported as 'mdx') was not found in '@mdx-js/react' (possible exports: MDXContext, MDXProvider, useMDXComponents, withMDXComponents)","compilerPath":"server"}
```

The error messages seem cryptic to me.
If you want to try it out for yourself, the project is public and the branch I’m trying it on is this one: https://github.com/ThibaultJanBeyer/DragSelect/tree/refactor/typescript

Thank you!

### Reproducible demo

https://github.com/ThibaultJanBeyer/DragSelect/tree/refactor/typescript

### Steps to reproduce

1. `cd www`
2. `yarn`
3. `yarn build`

That should be it, you might want to build the dragselect one he depends on (?) which would be `cd dragselect` then `yarn` then `yarn build` before building the docusaurus which is within `www`.

### Expected behavior

It should build without any issues

### Actual behavior

Well the build breaks. And actually before with custom code 
```
const lightCodeTheme = require('prism-react-renderer/themes/github');
const darkCodeTheme = require('prism-react-renderer/themes/dracula');
```
like in your examples it broke saying it could not find those themes. So I just removed them…

### Your environment

- Public source code: https://github.com/ThibaultJanBeyer/DragSelect/tree/refactor/typescript
- Public site URL: https://github.com/ThibaultJanBeyer/DragSelect/tree/refactor/typescript
- Docusaurus version used: 2.4.3
- Environment name and version (e.g. Chrome 89, Node.js 16.4): v20.3.1
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): macOS 13.5.2 (22G91)

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by ThibaultJanBeyer** [comment]
Ok, I narrowed down the issue and it seems like the issue is not in Docusaurus from 2.2.0 to 2.4.3 but with updating `"@mdx-js/react": "^1.6.22",`  to `"@mdx-js/react": "^2.3.0",` 🤔

Putting it back to 1.x version solves the issue…

**Comment by ThibaultJanBeyer** [comment]
Will do that for now, I assume that mdx-js/react 2.x is just not yet supported with Docusaurus?

**Comment by slorber** [comment]
MDX v2 is a major deps upgrade and is supported by Docusaurus v3, now in beta.

You can't really bump major versions like that and expect things to work 😅 you have to read the MDX v2 changelog for that. Also MDX v2 requires a totally different implementation of all Remark plugins: the upgrade has to be handled internally in Docusaurus core that implements a few remark plugins.
