### ISSUE TITLE
Strict check for plugin version mismatch

### ISSUE THREAD

**Issue by chris48s** [facebook/docusaurus#9342]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Description

In https://github.com/facebook/docusaurus/blob/v2.4.3/packages/docusaurus/src/server/siteMetadata.ts#L75-L92 there is a check which logs an error if @docusaurus plugins are out of sync with @docusaurus/core

This logs a message, but it is not a hard error.

I would like the ability to run something like

- `docusaurus check` or
- `docusaurus build --strict`

which throws an exception or otherwise exits with a non-zero exit code if the plugin versions are mis-matched with core.

### Motivation

This would be useful as a CI check to help users correctly upgrade docusaurus packages using automated tools like dependabot.

### API design

I've suggested

- `docusaurus check` or
- `docusaurus build --strict`

but open to other ideas.. `--strict-plugins`?

### Have you tried building it?

I have not tried building this as a plugin. At the moment, my proposed workaround for this on a repo where we are using docusaurus is https://github.com/badges/shields/pull/9608/files but parsing the output like this will be brittle.

Maybe this could be a plugin, but it feels like something that conceptually lives in core. The comment in https://github.com/facebook/docusaurus/blob/v2.4.3/packages/docusaurus/src/server/siteMetadata.ts#L75-L92 suggests this would be reasonable.

### Self-service

- [ ] I'd be willing to contribute this feature to Docusaurus myself.

**Comment by slorber** [comment]
Thanks for reporting

I think instead we should throw by default in Docusaurus v3.

**Comment by JorensM** [comment]
@slorber May I work on this issue?

**Comment by JorensM** [comment]
@slorber Ok, I can do that.

**Comment by shubhankar-mern** [comment]
@slorber  @chris48s  if i get it correctly you want to add some function named docusaurus check/build in checkDocusaurusPackagesVersion and if the versions mismatch it should run(This function  throws an exception or otherwise exits with a non-zero exit code if the plugin versions are mis-matched with core.) Its currently logging the error.

**Comment by JorensM** [comment]
@slorber So can I start working on it? Or should I get assigned first?

@shubhankar-mern I believe what they want to do it throw an error if there is a version mismatch, as opposed to just logging the error.
