### ISSUE TITLE
Codeblock does not style properly

### ISSUE THREAD

**Issue by xiaohai-huang** [facebook/docusaurus#9347]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [ ] I have tried the `npm run clear` or `yarn clear` command.
- [ ] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

https://github.com/facebook/docusaurus/assets/56380096/ab311c1b-6ba8-4dd9-ada7-ebd663399a52

## Bad Format Codeblock

The codeblock does not style properly.

![image](https://github.com/facebook/docusaurus/assets/56380096/2c9ecaee-5a3d-4f37-b5e0-27f4dcf2481a)

## Normal Codeblock

After refreshing the page, all codeblocks become normal.

![image](https://github.com/facebook/docusaurus/assets/56380096/1e8734a4-9e21-4453-81d4-2f88b8a881e9)

### Reproducible demo

- [The page that contains the bug](https://xiaohai.wiki/docs/Web/JavaScript/this#default-binding)
- [docusaurus.config.js](https://github.com/xiaohai-huang/learning-notes/blob/master/docusaurus.config.js)

### Steps to reproduce

1. Visit a page that contains codeblock. e.g., [an example page](https://xiaohai.wiki/docs/Web/React)
2. The codeblock does not style properly if it is the first time to visit the site
3. After refreshing the page, the codeblock becomes normal

### Expected behavior

![image](https://github.com/facebook/docusaurus/assets/56380096/03e6cdda-23f3-4e67-9f05-e27e81f81060)

### Actual behavior

![image](https://github.com/facebook/docusaurus/assets/56380096/0847d565-3780-4ac9-8b2b-83b480d4f5a6)

### Your environment

- Public source code: [https://github.com/xiaohai-huang/learning-notes/blob/master/docs/Web/JavaScript/01-this.mdx](https://github.com/xiaohai-huang/learning-notes/blob/master/docs/Web/JavaScript/01-this.mdx)
- Public site URL: [https://xiaohai.wiki/docs/Web/JavaScript/this#default-binding](https://xiaohai.wiki/docs/Web/JavaScript/this#default-binding)
- Docusaurus version used: 2.4.3
- Environment name and version (e.g. Chrome 89, Node.js 16.4):
- Operating system and version (e.g. Ubuntu 20.04.2 LTS):

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by Chetax** [comment]
@xiaohai-huang  i want to work on this issue can you please elaborate it and assign me

**Comment by xiaohai-huang** [comment]
@Chetax I am unable to assign people. What else do you need to know about the issue? Have you tried to visit the page [https://xiaohai.wiki/docs/Web/React](https://xiaohai.wiki/docs/Web/React)?

**Comment by slorber** [comment]
Hmm, weird I can also see this behavior on this code block for example

````md
```js title='"use strict" in function definition (contents)' {2,8}
function foo() {
  "use strict";
  console.log(this.a);
}

var a = 2; // is declared in the global scope

foo(); // Uncaught TypeError: Cannot read properties of undefined (reading 'a')
```
````

https://xiaohai.wiki/docs/Web/JavaScript/this#default-binding

I wonder if it's not related to a React hydration issue, as we had some in v2. 

Maybe it will work better once you upgrade to Docusaurus v3 (I'll publish a blog post very soon to help you do so).

---

@Chetax it doesn't look like a good first issue. Also we don't assign issues here: you either know how to handle it and submit a draft PR, or you don't and find another issue to work on.

**Comment by Chetax** [comment]
@slorber  ok  i will  find another issue to work on.

**Comment by xiaohai-huang** [comment]
@slorber I have upgraded to "3.0.0-beta.0". The issue still exists. [3.0.0-beta.0 version of the page](https://deploy-preview-4--incomparable-twilight-9bfc1d.netlify.app/docs/Web/JavaScript/this#default-binding)

Here is how I upgrade my site. [PR](https://github.com/xiaohai-huang/learning-notes/pull/4)

![image](https://github.com/facebook/docusaurus/assets/56380096/e8fb182c-daf9-4ab9-b340-115065b2eb69)

![image](https://github.com/facebook/docusaurus/assets/56380096/af4d606a-6364-4dff-bbc2-0da82e55dd45)

**Comment by xiaohai-huang** [comment]
The issue occurs because I created a custom component called `JSEditor` with "react-simple-code-editor". After removing the component everything become normal.

![image](https://github.com/facebook/docusaurus/assets/56380096/805c6fdb-c719-4eaf-8e04-44997ba428a8)

**Comment by Josh-Cena** [comment]
Hmmm, then this does not seem like a Docusaurus bug. You can post further details below, but I would encourage you to debug yourself, and if you have questions, you can start a discussion thread instead.

**Comment by xiaohai-huang** [comment]
Solve this issue by following the instruction from [prism-react-renderer | Custom Language Support](https://github.com/FormidableLabs/prism-react-renderer#custom-language-support)

```js
import { Highlight, Prism } from "prism-react-renderer";

(typeof global !== "undefined" ? global : window).Prism = Prism
await import("prismjs/components/prism-applescript")
/** or **/
require("prismjs/components/prism-applescript")
```

**Comment by slorber** [comment]
Great
Your custom editor was likely causing React hydration issues on both Docusaurus v2 and v3. 

Now in v3 those errors are logged to the console so it's easier to identify them.

That's outside the scope of Docusaurus to fix them since it's not our code, but glad you fixed it 👍

**Comment by slorber** [comment]
@xiaohai-huang by chance can you give us feedback on how easy it was to upgrade to v3? 

Do we need to document or clarify anything that you struggled with?

**Comment by xiaohai-huang** [comment]
## Things that I struggled with

- __Prettier__ prevent me from modifying some changes. I have to add `{/* prettier-ignore */}`.
- I don't know which version to set for some packages. e.g., `@mdx-js/react`, `typescript`
- I don't know which version to set for `@tsconfig/docusaurus`.


Maybe you should add [remark-math >= 5 and rehype-katex >= 6](https://docusaurus.io/docs/3.0.0-beta.0/markdown-features/math-equations#configuration) to the upgrade guide as well.

**Comment by slorber** [comment]
> ## Things that I struggled with


Thanks for the feedback!


> * **Prettier** prevent me from modifying some changes. I have to add `{/* prettier-ignore */}`.

True. Actually Prettier does not "officially" support MDX v2 and might cause troubles sometimes. 

Related:
- https://github.com/prettier/prettier/issues/12209
- https://github.com/facebook/docusaurus/issues/9318

Unfortunately there's nothing we can do apart opting out with prettier ignore or disabling prettier entirely.

Note: I think it works fine most of the time and we shouldn't need to stop recommending the usage of prettier.

Also, it also had shortcomings with MDX v1.

> * I don't know which version to set for some packages. e.g., `@mdx-js/react`, `typescript`

We have documented it in https://docusaurus.io/blog/preparing-your-site-for-docusaurus-v3#try-docusaurus-v3-today

TS 5+ and MDX React 2.3+ should work fine. 

> * I don't know which version to set for `@tsconfig/docusaurus`.

Also documented: use `@docusaurus/tsconfig` now

https://docusaurus.io/blog/preparing-your-site-for-docusaurus-v3#typescript-base-config

> * I got some strange errors after the upgrade. Solved by doing `rm -rf node_modules yarn.lock package-lock.json`.

Any message to share? that would help 😅 

After an upgrade, `docusaurus clear` can help too.

> * MDX error message sometimes show the wrong position for the error. And I don't understand the error message see [here](https://github.com/xiaohai-huang/learning-notes/pull/4#discussion_r1341201653)

True, this is something I'll fix

Error messages are not always easy to understand but we referenced some of them in the blog post here:
https://docusaurus.io/blog/preparing-your-site-for-docusaurus-v3#common-mdx-problems


> Maybe you should add "[Make sure to use remark-math >= 5 and rehype-katex >= 6 for Docusaurus v3 (using MDX v2).](https://docusaurus.io/docs/3.0.0-beta.0/markdown-features/math-equations#configuration)" to the upgrade guide as well.

Thanks, will do 👍

**Comment by slorber** [comment]
Regarding the Math/katex upgrades, I think not possible now because this blog post is about preparing your v2 site, and is not full v3 upgrade guide. Apparently the newer math/katex versions are not compatible with mdx v1/Docusaurus v2 so this does not qualify as "preparatory work". We can only upgrade those plugins when doing the v3 upgrade, not ahead of time.

BTW @Josh-Cena you wrote this section about using newer version:
https://docusaurus.io/docs/markdown-features/math-equations#upgrading-rehype-katex-beyond-recommended-version

Have you been able to do that in practice? Because I couldn't make it work 😅 

https://stackblitz.com/edit/github-xqy2c4?file=docusaurus.config.js,docs%2Fintro.md,package.json
