### ISSUE TITLE
Navigating to an absolute link breaks my static site

### ISSUE THREAD

**Issue by icbrahimc** [facebook/docusaurus#9378]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

I think my website's routing is messed up. When I make a request to a non root page, the route page is highlighted in the sidebar and, in some cases, the content of the page doesn't load correctly. I've also noticed this behavior from clicking markdown links to other pages in my docs. Here's a video 

https://github.com/facebook/docusaurus/assets/9633847/63ca9a24-0e06-437b-b1e6-b24551f19b65

### Steps to reproduce

1. Navigate to https://developer.audioshake.ai/
2. Navigate to one of the sub menus such as https://developer.audioshake.ai/stem-separation/overview
3. Notice how the sidebar lights up

### Expected behavior

Docs and routing structure should work. The sidebar should only light up for active pages. Content should load correctly for the requested page

### Actual behavior

https://github.com/facebook/docusaurus/assets/9633847/6a893c45-d145-47cd-88aa-9a3ae7e0763b

### Your environment

- Public source code: n/a
- Public site URL: https://developer.audioshake.ai
- Docusaurus version used: 2.4.3
- Environment name and version (e.g. Chrome 89, Node.js 16.4): Node 18
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): MAC OS 

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by slorber** [comment]
It is impossible to help without access to the source code, or preferably a minimal repro using docusaurus.new. 

If you need support for your site please open a discussion: unless a minimal Docusaurus core repro is provided it's not a bug and can be your fault.

Very likely it is a hosting problem: your host is not configured correctly to serve a static deployment.
We can see that going to any url like https://developer.audioshake.ai/XYZ first serves the introduction page, and then it updates. This is not supposed to happen and shows a hosting problem.

**Comment by icbrahimc** [comment]
Thanks for the feedback. It was a hosting issue on our end. We're hosting our site via Amazon Cloudfront (which is not included in the docusaurus tutorial). However, I found a pretty helpful blogpost. Perhaps it should be parsed and shared on the official docs too? https://juffalow.com/blog/other/how-to-deploy-docusaurus-page-using-aws-s3-and-cloudfront.

Anyway, thanks again.

**Comment by slorber** [comment]
np

We don't want to include such instructions to our deployment page on purpose because if we do we have to ensure those instructions remain correct over time, and can only do so with a limited set of hosts. If Cloudfront creates an official doc page on how to host a Docusaurus or static site on its infrastructure, we can add a link to that, but we don't want to copy long instructions on our page, particularly when CloudFront is not even a really great solution to host Docusaurus and other static deployments in the first place 😅
