### ISSUE TITLE
The Long Katex formula would overflow the document page.

### ISSUE THREAD

**Issue by PrinOrange** [facebook/docusaurus#9383]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

When the inserted Katex formula is very long, the formula range will overflow the page.
This breaks the responsive look and feel of the page

![image](https://github.com/facebook/docusaurus/assets/73331790/f9688e11-253f-4c2b-be29-9bdbe4157c9f)

### Reproducible demo

https://leetcode.terminels.com/docs/notes/algorithm/recursion/fast-pow

### Steps to reproduce

1. Open an page and insert the long formula,such as 
```latex
$$
\text{power}(x, n) = \begin{cases}
1 & \text{if } n = 0 \\
\text{power}(x, \frac{n}{2}) \cdot \text{power}(x, \frac{n}{2}) & \text{if } n > 0 \text{ and } n \text{ is even} \\
x \cdot \text{power}(x, \frac{{n-1}}{2}) \cdot \text{power}(x, \frac{{n-1}}{2}) & \text{if } n > 0 \text{ and } n \text{ is odd}
\end{cases}
$$
```

### Expected behavior

It would be better to add scroll bars to the formula block instead of overflowing content and destroying the page.

### Actual behavior

 ![image](https://github.com/facebook/docusaurus/assets/73331790/f9688e11-253f-4c2b-be29-9bdbe4157c9f)

### Self-service

- [X] I'd be willing to fix this bug myself.

**Comment by Josh-Cena** [comment]
Hi! KaTeX is entirely delegated to third party plugins and we implemented none of its logic. It's only included in our docs for your convenience. To implement other designs, you can add custom CSS yourself.

**Comment by slorber** [comment]
couldn't we put the formula in a overflow-x auto container?

This should be easy to do and probably be considered a good workaround?

<img width="998" alt="CleanShot 2023-10-08 at 18 10 57@2x" src="https://github.com/facebook/docusaurus/assets/749374/8ab4ad17-17ce-42c0-9e02-930b36c08a90">
