### ISSUE TITLE
Add Docker Files

### ISSUE THREAD

**Issue by Durgesh4993** [facebook/docusaurus#9399]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Description

Sir can i add docker in Repository, which help to deploy applications quickly

### Self-service

- [X] I'd be willing to address this documentation request myself.

**Comment by Josh-Cena** [comment]
No, we are not interested, neither are you using the right template. The next issue like this will be closed without further explanation.
