### ISSUE TITLE
The init CLI should prompt for TS usage

### ISSUE THREAD

**Issue by slorber** [facebook/docusaurus#9401]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Motivation

Currently the only way to init a site with TypeScript is to use the following command:

```bash
npx create-docusaurus@latest my-website classic --typescript
```

---

My suggestion is we should support these commands:

```bash
npx create-docusaurus@latest my-website classic --javascript
npx create-docusaurus@latest my-website classic --typescript
```

If no language is provided, the CLI should be interactive and ask the user if they want to use TypeScript.

---

Related to https://github.com/facebook/docusaurus/issues/9402 (DX should be consistent)

**Comment by san70sh** [comment]
Hello @slorber, I would like to work on this issue if nobody picked it up.

**Comment by OzakIOne** [comment]
@san70sh Please send directly a PR, Docusaurus maintainers don't assign issue to people

**Comment by Rafael-Martins** [comment]
Hey @slorber I implemented a solution for this, lets discuss about it in the pr! :D

**Comment by Josh-Cena** [comment]
Should be fixed by https://github.com/facebook/docusaurus/pull/9442
