### ISSUE TITLE
The swizzle CLI should prompt for TS usage

### ISSUE THREAD

**Issue by slorber** [facebook/docusaurus#9402]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Motivation

When using the swizzle CLI, we can get TypeScript copies of the theme files, but this requires to provide the `--typescript` option ahead of time.

```bash
yarn workspace website swizzle // will always copy JS files

yarn workspace website swizzle --typescript // will copy TS files, if available
```

---

When running `yarn workspace website swizzle`, the CLI should more interactive and promp the user if they want to use TypeScript.

To disable the promp, a language should be provided explicitly:

```bash
yarn workspace website swizzle --javascript
yarn workspace website swizzle --typescript
```

---

Related to https://github.com/facebook/docusaurus/issues/9401 (DX should be consistent)

**Comment by mqshaikh8** [comment]
Is anyone working on this? I would love to work on this if no one took it yet
