### ISSUE TITLE
Labels for footnotes must not be as-is but converted to serial numbers

### ISSUE THREAD

**Issue by tats-u** [facebook/docusaurus#9404]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [ ] I have tried the `npm run clear` or `yarn clear` command.
- [ ] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io.
- [ ] I have read the console error message carefully (if applicable).

### Description

Footnotes consists of an ordered list, not a description list.
Therefore, reference labels for footnotes (word<sup>number</sup>) must be serial numbers.
Otherwise, as shown below, there is no correspondence between the numerical labels and the indices of the ordered list of the footnote.

### Reproducible demo

https://github.com/tats-u/docusaurus-bug-footnote/

### Steps to reproduce

1. Add a page in `docs` with the content:

```md
Foo[^2]

Bar[^qux]

Baz[^1]

[^2]: `[^2]`
[^qux]: `[^qux]`
[^1]: `[^1]`
```

### Expected behavior

Foo<sup>1</sup>

Bar<sup>2</sup>

Baz<sup>3</sup>

---

1. `[^2]`
2. `[^qux]`
3. `[^1]`

### Actual behavior

Foo<sup>2</sup>

Bar<sup>qux</sup>

Baz<sup>1</sup>

---

1. `[^2]`
2. `[^qux]`
3. `[^1]`

### Your environment

- Public source code: https://github.com/tats-u/docusaurus-bug-footnote/
- Public site URL: https://tats-u.github.io/docusaurus-bug-footnote/docs/intro/
- Docusaurus version used: 2.4.3
- Environment name and version (e.g. Chrome 89, Node.js 16.4): all
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): all

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by Josh-Cena** [comment]
Hi! This functionality is provided by MDX, so whatever they do we can't "fix" it. Have you tried Docusaurus v3?

**Comment by tats-u** [comment]
@Josh-Cena Fixed in v3. Could you reopen for 2.x? Or don't you have a plan to fix in v2?

**Comment by Josh-Cena** [comment]
No there's no plan to fix it—again, we don't control this implementation, so we can't "fix" it.

**Comment by tats-u** [comment]
You're right, I searched such process by VS Code and didn't find any ones that looked like that
