### ISSUE TITLE
Low version webview click on search button without response

### ISSUE THREAD

**Issue by tianyongchao** [facebook/docusaurus#9405]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [x] I have tried the `npm run clear` or `yarn clear` command.
- [x] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [x] I have tried creating a repro with https://new.docusaurus.io.
- [ ] I have read the console error message carefully (if applicable).

### Description

I used the search function in a lower version of Wevview and clicked the search button without any response. The mobile phone model is Huawei Honor 7X

### Steps to reproduce

I used the search function in a lower version of Wevview and clicked the search button without any response. The mobile phone model is Huawei Honor 7X

### Expected behavior

I used the search function in a lower version of Wevview and clicked the search button without any response. The mobile phone model is Huawei Honor 7X

### Actual behavior

I used the search function in a lower version of Wevview and clicked the search button without any response. The mobile phone model is Huawei Honor 7X

### Your environment

- Public source code:
- Public site URL:
- Docusaurus version used:
- Environment name and version (e.g. Chrome 89, Node.js 16.4):
- Operating system and version (e.g. Ubuntu 20.04.2 LTS):

### Self-service

- [X] I'd be willing to fix this bug myself.

**Comment by tianyongchao** [comment]
I used the search function in a lower version of Wevview and clicked the search button without any response. The mobile phone model is Huawei Honor 7X

**Comment by Josh-Cena** [comment]
This is not helpful for us to act on. What is the "search button" you are talking about? What specific version of webview are you using?

**Comment by slorber** [comment]
> lower version of Wevview 

What does this even mean 🤷‍♂️ Which version of what?

> clicked the search button without any response

As far as I know China's support for new browser features is lower than other countries, so maybe this is related to browser support that prevents React from hydrating correctly. 

In this case other things won't work, notably the theme switch and the category collapse buttons.

We can't really support "all lower versions of webviews" in the same way we don't support IE, so if search fails in some low-usage, specific environments, that's kind of expected

Closing unless very precise informations are provided about that environment.

> My model Honor 7x Video operation link [note.youdao.com/s/4yAn7gu1](https://note.youdao.com/s/4yAn7gu1)

Please provide screenshots or video streaming that I can watch online (you can post videos on youtube). I'm not sure I want to download a `.mov` from an untrusted source.

**Comment by tianyongchao** [comment]
My phone's webview information is Mozilla/5.0 (Linux; Android 10; MIX 3 Build/QKQ1.190828.002; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/83.0.4103.101 Mobile Safari/537.36
The online video link address is https://youtube.com/shorts/s3nDguTx5EM

**Comment by slorber** [comment]
Ok thanks

Are you a dev? Able to see webview console logs from your app?

Is search the only thing that doesn't work? Because I expect the sidebar collapse buttons `>` to also not work.

> Mozilla/5.0 (Linux; Android 10; MIX 3 Build/QKQ1.190828.002; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/83.0.4103.101 Mobile Safari/537.36

To be honest I struggle to understand how these user agent strings work these days, and still have no idea about the runtime it's using behind the hood 😅 But it looks old so I assume it's expected that it doesn't work.

**Comment by tianyongchao** [comment]
Yes, clicking on the sidebar did not respond. There are no errors reported in the webview.

When I was looking at the @ docusaurus source code, I found that it is in theme search algolia/lib/theme/SearchBar/index.js.

<DocSearchButton onClick={onOpen}/>It was found that the click event did not take effect. Then, customize the method on the page to immediately execute it. Expected result, the method was not executed.

**Comment by slorber** [comment]
> Yes, clicking on the sidebar did not respond. 

This means the whole app does not hydrate, it's not a search problem but very likely your webview runtime is too old. Unfortunately we don't plan to support older runtimes so please upgrade to something more up to date

**Comment by tianyongchao** [comment]
I did some validation
1. Create a new React project, my React is V18.2.0 and React-dom is 18.2.0
2. I wrote a button to add a click event
3. After I click the button, the event execution is successful
Video link: https://youtube.com/shorts/DcPeeGV_Pvg
I am using https://docusaurus.io/ The following verifications were conducted in the provided project
1. Bind a click event to page elements
2. After clicking on the element
3. No click event triggered
I think it's a problem with docusaurus not having a valid click event or JavaScript event when encapsulating code. Or do you have any better suggestions

**Comment by tianyongchao** [comment]
I did some validation
1. Create a new React project, my React is V18.2.0 and React-dom is 18.2.0
2. I wrote a button to add a click event
3. After I click the button, the event execution is successful
Video link: https://youtube.com/shorts/DcPeeGV_Pvg


I am using https://docusaurus.io/ The following verifications were conducted in the provided project
1. Bind a click event to page elements
2. After clicking on the element
3. No click event triggered
I think it's a problem with docusaurus not having a valid click event or JavaScript event when encapsulating code. Or do you have any better suggestions
