### ISSUE TITLE
`npx` => `yarn` is not correctly handled by npm2yarn

### ISSUE THREAD

**Issue by sudhz** [facebook/docusaurus#9410]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

If you use `@docusaurus/remark-plugin-npm2yarn` and your code snippet is set like this:

<pre><code>```sh npm2yarn
npm install --save-dev @electron-forge/cli
npx electron-forge import
```</code></pre>

Then it doesn't convert the second line to its yarn equivalent, which would be something like `yarn electron-forge import`.
Overall, I have noticed npx commands are ignored by npm2yarn, please someone look into this as it can create downstream issues like https://github.com/electron/website/issues/420

### Reproducible demo

_No response_

### Steps to reproduce

1. Create a Docusaurus page.
2. Add the `@docusaurus/remark-plugin-npm2yarn` plugin
3. Create an example like mentioned above

### Expected behavior

npm:
```
npm install --save-dev @electron-forge/cli
npx electron-forge import
```

yarn:
```
yarn add --dev @electron-forge/cli
yarn electron-forge import
```

### Actual behavior

npm:
```
npm install --save-dev @electron-forge/cli
npx electron-forge import
```

yarn:
```
yarn add --dev @electron-forge/cli
npx electron-forge import
```

### Your environment

- Public source code: https://github.com/electron/website
- Public site URL: https://www.electronjs.org/docs/latest/tutorial/quick-start#package-and-distribute-your-application
- Docusaurus version used: 2.4.3
- Environment name and version (e.g. Chrome 89, Node.js 16.4): Chrom Version 117.0.5938.88 (Official Build) (arm64)
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): MacOS 14.0 (23A344)


### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by Josh-Cena** [comment]
Hi! `npx` is able to download packages on-the-fly, so there's no equivalent in Yarn. Please see https://github.com/facebook/docusaurus/issues/7908 also.
