### ISSUE TITLE
Docusaurus build and push commands do not copy *.css files from subdirectories of website/static.

### ISSUE THREAD

**Issue by mvm3k** [facebook/Docusaurus#942]
## 🐛 Bug Report

yarn  run build and publish-gh-pages do not copy *.css files from our  website/static/api directory that contains Doxygen-generated API docs  into website/build. Is this intentional? All the other files, hundreds of them in a deep directory structure, are copied fine, but these two CSS files are ignored.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

yes

## To Reproduce

1. create a subdirectory of website/static, e.g., website/static/api 
1. put a few html and css files in there. Ideally run Doxygen to generate a documentation tree in static/api.
1. run the build command, the 

## Expected behavior

I expected all files in all subdirectories of website/static to be copied into the corresponding subdirectores of website/build. Is this a correct assumption? Should I put Doxygen-generated files under website/pages instead?

bash-3.2$ diff ~/api.files ~/build.files
26d25
< doxygen.css
54d52
< tabs.css

## Reproducible Demo

this is a private Facebookincubator repo at this time.

**Comment by JoelMarcey** [comment]
I am working with @mvm3k now on this.

**Comment by JoelMarcey** [comment]
After chatting with @mvm3k - I believe we just needed to use the `separateCSS` option for `siteConfig.js` as described here: https://docusaurus.io/docs/en/site-config#optional-fields

> `separateCss` - Directories inside which any css files will not be processed and concatenated to Docusaurus' styles. This is to support static html pages that may be separate from Docusaurus with completely separate styles.

@mvm3k is testing it now.

He made a good point that we should probably add something about Doxygen integration at a higher level of our docs where this setting could be crucial for Docusaurus.

**Comment by JoelMarcey** [comment]
This worked. 🎉 

We still have a bug where files starting with `_` are are not getting built/published. Will look into that.
