### ISSUE TITLE
Unlisted blog posts should not be display on the blog archive

### ISSUE THREAD

**Issue by slorber** [facebook/docusaurus#9432]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [ ] I have tried the `npm run clear` or `yarn clear` command.
- [ ] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io.
- [ ] I have read the console error message carefully (if applicable).

### Description

Unlisted blog posts should not appear on the blog archive page, because it makes them discoverable!

Missing implementation from original feature https://github.com/facebook/docusaurus/pull/8004

### Steps to reproduce

Unlisted post in production: https://docusaurus.io/tests/blog/unlisted-post

Shouldn't be displayed on this page https://docusaurus.io/tests/blog/archive

### Expected behavior

Shouldn't be displayed on this page https://docusaurus.io/tests/blog/archive

![CleanShot 2023-10-20 at 19 29 13@2x](https://github.com/facebook/docusaurus/assets/749374/4174c857-896b-4fb0-8d93-1b20375fcd83)

### Actual behavior

It is displayed on https://docusaurus.io/tests/blog/archive (but shouldn't)

### Self-service

- [X] I'd be willing to fix this bug myself.

**Comment by Muhammad-Tayyab-Bhutto** [comment]
@slorber kindly assign me this task. Thanks

**Comment by PrasannanjaneyuluPadavala-EN0195** [comment]
@slorber I can work on it

**Comment by slorber** [comment]
@Muhammad-Tayyab-Bhutto we don't assign issues. If you want to work on it, submit a draft PR in the next few days otherwise someone else will
