### ISSUE TITLE
CI Score Badge in README is missing

### ISSUE THREAD

**Issue by choeqq** [facebook/docusaurus#9465]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Description

The Icon on `CI Score` is missing:
<img width="352" alt="Screenshot 2023-10-28 at 14 06 55" src="https://github.com/facebook/docusaurus/assets/69403782/e45de352-a439-4284-9002-a24ab974642a">

The `src` if `CI Score` return us 500, when trying to access it's badge score:

<img width="1145" alt="Screenshot 2023-10-28 at 14 03 51" src="https://github.com/facebook/docusaurus/assets/69403782/478d0752-651a-4749-a36f-c7290264876d">

src URL: `https://meercode.io/badge/facebook/docusaurus?type=ci-score`

### Self-service

- [ ] I'd be willing to address this documentation request myself.

**Comment by ruchikamuddinagiri** [comment]
Hi, can I take this?

**Comment by slorber** [comment]
yes

**Comment by deniskirshenin** [comment]
Hi, I took a look at this issue and it seems that there is a problem with accessing Meercode server. I sent them email regarding this but didn't get any answer yet.

**Comment by choeqq** [comment]
Yes, that's why I didn't assign the issue to myself, I thought that somebody from the core team should take it 😉

**Comment by choeqq** [comment]
created a PR for `CI Score` removal: https://github.com/facebook/docusaurus/pull/9542
@Josh-Cena
