### ISSUE TITLE
Embeded videos not showing

### ISSUE THREAD

**Issue by bildungsroman** [facebook/Docusaurus#947]
## 🐛 Bug Report

I am migrating a documentation site from Jekyll to Docusaurus, and a lot of the .md files have html sprinkled in at the moment, generally related to displaying images and video files. The images are wrapped in `<figure>` tags (for styling), and those are working fine.

The problem is with the video files - this is what they look like:

```
<div>
  <video width="100%" height="100%" playsinline autoplay muted loop>
    <source src="video/2.mp4" type="video/mp4">
    <source src="video/2.webm" type="video/webm">
    <source src="video/2.ogg" type="video/ogg"> Your browser does not support the video tag.
  <video>
</div>
```
(I have to wrap the `<video>` tag in a `<div>` tag or it cuts off the rest of the content - another bug?)

At the moment, the page is just showing a blank space where the video should be. This format was working in Jekyll, so I'm not sure what's happening in Docusaurus' conversion of .md files that's breaking the display.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yup.

## To Reproduce

1. Add a `<video>` tag to any doc

## Expected behavior

Shows the video.

## Actual Behavior

Shows a blank space.

<img width="1371" alt="screen shot 2018-09-07 at 10 48 50 am" src="https://user-images.githubusercontent.com/5382821/45234795-a26c3980-b28b-11e8-85a9-4d03ae63cb2e.png">

## Reproducible Demo

The repo is private so I can't post it, but right now I've only brought in my .md files and haven't yet messed with the siteConfig.js, so it's something that should be reproducible in any configuration.

**Comment by wszgxa** [comment]
Hi, @bildungsroman 

I have tried it, the video will show liks this: 
![screen shot 2018-09-13 at 9 56 15 pm](https://user-images.githubusercontent.com/6060475/45492893-0a48e580-b7a0-11e8-86ab-cac74abc157c.png)

I guess you video source url is incorrect. You can try to move your video file to `/website/static/video`. Add a `/` before you video src url: 
``` html
<div>
  <video width="100%" height="100%" playsinline autoplay muted loop>
    <source src="/video/2.mp4" type="video/mp4">
    <source src="/video/2.webm" type="video/webm">
    <source src="/video/2.ogg" type="video/ogg"> Your browser does not support the video tag.
  <video>
</div>
```


But the video's style is not so good, I can create a PR for this.

**Comment by endiliey** [comment]
Great point by @wszgxa. Thank you for helping to look into this. Awesome 😄 

I shall close this issue because this is caused due to wrong source

**Comment by bildungsroman** [comment]
Thank you, @wszgxa!

**Comment by kuzdogan** [comment]
Took me a while to figure out that the `controls` props was missing in the `<video>` element here. Adding the code with correct closing tags:
```html
<div>
  <video width="100%" height="100%" playsinline autoplay muted controls>
    <source src="/videos/myvideo.mp4" type="video/mp4" />
  </video>
</div>
```
