### ISSUE TITLE
Unable to use 2 same TabItem values

### ISSUE THREAD

**Issue by monica-m-ps** [facebook/docusaurus#9474]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

I have a situation where I need to demonstrate the json code of two types, NoShow and Unscheduled.

````jsx
<Tabs groupId="codeGroup">
<TabItem value="json" label="NoShow">

```json
{  ...
    "MerchantInitiatedTransactionType": "NoShow",
}
```
</TabItem>

<TabItem value="json" label="Unscheduled">

```json
{  ...
    "MerchantInitiatedTransactionType": "Unscheduled",
}
```
</TabItem>
</Tabs>
````

I am unable to use json for both. I need to use the same language across both scenarios representing them in tabs.

### Steps to reproduce

1. In you markdown file, use the following code

````jsx
<Tabs groupId="codeGroup">
<TabItem value="json" label="NoShow">

```json
{  ...
    "MerchantInitiatedTransactionType": "NoShow",
}
```
</TabItem>

<TabItem value="json" label="Unscheduled">

```json
{  ...
    "MerchantInitiatedTransactionType": "Unscheduled",
}
```
</TabItem>
</Tabs>
````

### Expected behavior

Expected to have two tabs "NoShow" and "Unscheduled" with the json code.

### Actual behavior

Getting an error Error: 
`Docusaurus error: Duplicate values "json" found in <Tabs>. Every value needs to be unique.`

### Your environment

- Public source code:
- Public site URL: locally built
- Docusaurus version used: 2.0.x
- Environment name and version (e.g. Chrome 89, Node.js 16.4): Not relevant
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): MacOs, yet not relevant

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by Josh-Cena** [comment]
What is your intended effect? Show two tab items simultaneously?

**Comment by monica-m-ps** [comment]
I understand Docusaurus doesn't support it. But can you add it as an enhancement please? Because my case is valid here.

Yes I want to add two tabitems but of the same language

**Comment by Josh-Cena** [comment]
`value` is not for displaying the language. `value` is purely a unique identifier to identify the tab. Underlyingly, Docusaurus is going to record that "whenever I see a tab with the group `codeGroup`, I'm going to display the item with value `json`, regardless of its label". What do two identical values mean?

**Comment by Josh-Cena** [comment]
Are you reading our docs section "Multi-language support code blocks"? Would it help if the examples look like this?

````jsx
<Tabs>
<TabItem value="1" label="JavaScript">

```js
function helloWorld() {
  console.log('Hello, world!');
}
```

</TabItem>
<TabItem value="2" label="Python">

```py
def hello_world():
  print("Hello, world!")
```

</TabItem>
<TabItem value="3" label="Java">

```java
class HelloWorld {
  public static void main(String args[]) {
    System.out.println("Hello, World");
  }
}
```

</TabItem>
</Tabs>
````

**Comment by monica-m-ps** [comment]
Ok, got it. I can display both of them regardless of their `values`. This makes sense. Thanks! Closing this case
