### ISSUE TITLE
About image file name case!!!

### ISSUE THREAD

**Issue by WJAir** [facebook/docusaurus#9476]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [ ] I have tried the `npm run clear` or `yarn clear` command.
- [ ] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io.
- [ ] I have read the console error message carefully (if applicable).

### Description

I created an md document in docs using 'import pic from "./image/Web.png"'，But the image name is web.png，When I execute npm start and npm run build does not report errors，
![image](https://github.com/facebook/docusaurus/assets/97864692/b07a20f7-8b0b-494e-bbb5-3a18aeb043b6)

But when I reproduced the environment deployment failed
![image](https://github.com/facebook/docusaurus/assets/97864692/8d81b31d-5c8b-4287-99cb-0e679b33c041)

### Steps to reproduce

npm run start

npm run build

### Expected behavior

When start and build should report errors

### Actual behavior

Does not

### Your environment

- Public source code:
- Public site URL:
- Docusaurus version used:
- Environment name and version (e.g. Chrome 89, Node.js 16.4):
- Operating system and version (e.g. Ubuntu 20.04.2 LTS):

### Self-service

- [X] I'd be willing to fix this bug myself.

**Comment by WJAir** [comment]
I used Jenkins deployment

**Comment by WJAir** [comment]
I used Jenkins deployment

![image](https://github.com/facebook/docusaurus/assets/97864692/0e57e8cc-0904-4c30-b454-8b7e14dcd1d7)

**Comment by slorber** [comment]
Your local file system is probably case insensitive, while your Jenkins file system is likely case sensitive.
