### ISSUE TITLE
Meaningful name to represent 1000

### ISSUE THREAD

**Issue by at758** [facebook/Docusaurus#948]
## 💥 Proposal

Can we add a meaningful name to represent what 1000 is?

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Can we add a meaningful name for what 1000 is, its not super clear why the check (i++ < 1000) is needed and also this function seems to be doing a lot of things. Would be better to split this out into multiple functions

https://github.com/facebook/Docusaurus/blob/master/lib/server/readCategories.js#L89

**Comment by endiliey** [comment]
@JoelMarcey ?

**Comment by JoelMarcey** [comment]
I believe we chose this as an arbitrary number to limit the number of possible categories. 1000 seemed like a good upper limit before things just got unwieldy. 😄 

@deltice -- do you recall if 1000 had greater significance here?

**Comment by at758** [comment]
Thanks, @JoelMarcey would be helpful to add a comment there or have a name that is good enough to communicate this message along. 

`CATEGORY_COUNT_THRESHOLD` maybe?

**Comment by JoelMarcey** [comment]
Sure. We can do that. Would you like to submit a PR @at758 ?

**Comment by at758** [comment]
Sure I can do that.

**Comment by endiliey** [comment]
Upon seeing at the code closely, best if we re-write this. This is a matter of building categories from all the docs metadata.

Current implementation is inefficient.. quite surprised it's been there since initial commit.

Cc @yangshun

**Comment by deltice** [comment]
Yeah, I think this was just arbitrarily chosen and I may have forgotten about it as I continued working on the features. 😬 I don't believe there's any special about it.
