### ISSUE TITLE
v3 html sidebar links don't work

### ISSUE THREAD

**Issue by homotechsual** [facebook/docusaurus#9483]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

HTML type sidebar links aren't rendering on v3

### Reproducible demo

https://codesandbox.io/p/sandbox/magical-ben-cytfh8?file=%2Fsidebars.js%3A22%2C43

### Steps to reproduce

Create HTML sidebar item
Preview site

### Expected behavior

HTML sidebar item should appear

### Actual behavior

Does not render HTML item

### Your environment

- Public source code: https://codesandbox.io/p/sandbox/magical-ben-cytfh8?file=%2Fsidebars.js%3A22%2C43
- Public site URL: https://codesandbox.io/p/sandbox/magical-ben-cytfh8?file=%2Fsidebars.js%3A22%2C43
- Docusaurus version used: 3.0.0
- Environment name and version (e.g. Chrome 89, Node.js 16.4):
- Operating system and version (e.g. Ubuntu 20.04.2 LTS):

### Self-service

- [X] I'd be willing to fix this bug myself.

**Comment by slorber** [comment]
Thanks for reporting

Looks similar to https://github.com/facebook/docusaurus/discussions/9456#discussioncomment-7431441

**Comment by nickzelei** [comment]
Can't express how happy I am to find this bug report. Have been banging my head against the wall for the last 30m trying to figure out why my HTML items are not being included.
