### ISSUE TITLE
[Firefox] data attributes are broken / not targeted for styling when building the site using theme-classic

### ISSUE THREAD

**Issue by jprusik** [facebook/docusaurus#9493]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

tl;dr [Firefox does not yet support `:has`](https://developer.mozilla.org/en-US/docs/Web/CSS/:has#browser_compatibility) (at least not by default)

On Firefox, when I'm using the (default) `theme-classic` theme and locally serve the build files (`npm run build && npm run serve`), custom data attributes selectors are not styled as [described in the Docusaurus docs](https://docusaurus.io/docs/styling-layout#data-attributes). When I serve the site via the development server (`npm run start`), the custom data attributes selectors are styled properly. (I tested this in a fresh/new project)

Also affects the dark/light mode toggle on the live docusaurus site:
https://github.com/facebook/docusaurus/issues/9493#issuecomment-1789458137

After looking around, I tracked the issue down to the built CSS:

| custom.css | working generated CSS (dev server) | not working generated CSS (built) |
| --- | --- | --- |
| ![Screenshot 2023-11-01 at 12 51 30 PM](https://github.com/facebook/docusaurus/assets/1556494/95cb855f-418f-4e74-8b01-8ec64b7e869b) | ![Screenshot 2023-11-01 at 12 51 56 PM](https://github.com/facebook/docusaurus/assets/1556494/76febb53-4eac-4618-a092-731ccbf26a18) | ![Screenshot 2023-11-01 at 12 47 57 PM](https://github.com/facebook/docusaurus/assets/1556494/09db3dd4-136d-479c-9d7f-d73ee4fd9a61) |

After working with the built/optimized CSS, I was able to determine the rule was preventing the rest of the selectors in the combined rules from being evaluated:

![Screenshot 2023-11-01 at 12 59 55 PM](https://github.com/facebook/docusaurus/assets/1556494/3cfbef77-84c4-41c0-a572-eb80602915b8)

This belongs to the Navbar Search component and it appears the problematic rule was introduced in this PR:
https://github.com/facebook/docusaurus/pull/9385/files#diff-b05b40971ea5fe3fbfdb4aee1fa6f1f4989d591465acbf2d45c84200223c36a8R12-R14

As a workaround, I can eject the component (`docusaurus swizzle @docusaurus/theme-classic Navbar/Search --eject`) and remove the rule (in `src/theme/Navbar/Search/styles.module.css`) to restore the expected data attribute styling functionality, but it would be nice if this was not necessary.

Note: I did confirm the data-attributes were correctly being pulled from the query string and added to the document `html`:

![Screenshot 2023-11-01 at 12 49 44 PM](https://github.com/facebook/docusaurus/assets/1556494/d7f45078-0975-4ced-893a-dc0dababb012)

### Steps to reproduce

1. create a new instance of docusaurus (e.g. `npx create-docusaurus@latest del-test classic --typescript`)
2. add custom styling using custom data attribute selectors as [described in the Docusaurus docs](https://docusaurus.io/docs/styling-layout#data-attributes)

  e.g. 
  ```css
  .hidden,
  [data-bare='true'] .navbar {display:none;}
  [data-bare='true'] .footer {display:none;}
  [data-bare='true'] .theme-doc-sidebar-container {display:none;}
  [data-bare='true'] .pagination-nav {display:none;}
  [data-bare='true'] .theme-doc-markdown > header {display:none;}
  [data-hide-sidebar='true'] .theme-doc-sidebar-container {display:none;}
  [data-hide-pagination='true'] .pagination-nav {
    display: none;
  }
  ```
3. build and serve the site (`npm run build && npm run serve`)
4. add the data-attribute(s) to the query string - the styling rules will not be used

### Expected behavior

custom data attributes should be styled as [described in the Docusaurus docs](https://docusaurus.io/docs/styling-layout#data-attributes) when serving the built files and using the `theme-classic` theme

### Actual behavior

custom data attributes are not styled as [described in the Docusaurus docs](https://docusaurus.io/docs/styling-layout#data-attributes) when serving the built files and using the `theme-classic` theme

### Your environment

- Docusaurus version used: v3.0.0
- Environment name and version (e.g. Chrome 89, Node.js 16.4): Firefox, Node v18.18.2
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): Mac OS 14.0

### Self-service

- [X] I'd be willing to fix this bug myself.

**Comment by jprusik** [comment]
Additional find: It looks like the offending (search bar container) styles get pulled into the final built css even if the component isn't rendered? So even excluding the search bar component when not needed won't solve this, unless the CSS using `:has` is removed as well.

**Comment by slorber** [comment]
Thanks for investigating, this will be fixed in https://github.com/facebook/docusaurus/pull/9530
