### ISSUE TITLE
Duplicate logo in navbar on load in Firefox with v3

### ISSUE THREAD

**Issue by peterpeterparker** [facebook/docusaurus#9527]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

Hi,

When loading a docusaurus v3 website with Firefox, the logo gets duplicated in the navbar while the website is loading which makes the ui perception glitchy.

Screenshot:

<img width="1526" alt="Capture d’écran 2023-11-10 à 07 15 17" src="https://github.com/facebook/docusaurus/assets/16886711/4f426112-7ff7-4a9b-b663-72af0ab676c5">

Gif:

![Enregistrement de l’écran 2023-11-10 à 07 13 46](https://github.com/facebook/docusaurus/assets/16886711/32892868-bf25-45e7-8280-d5683690c874)

### Steps to reproduce

Open https://new.docusaurus.io/ in Firefox

### Expected behavior

No glitch

### Actual behavior

See description

### Your environment

- Public source code:
- Public site URL:
- Docusaurus version used:
- Environment name and version (e.g. Chrome 89, Node.js 16.4):
- Operating system and version (e.g. Ubuntu 20.04.2 LTS):

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by johanbook** [comment]
I am still seeing this issue in @docusaurus/core v3.7.0 on Firefox and Brave browsers for my company's docs site (https://developer.dreamdata.io/).

**Comment by slorber** [comment]
Not seeing this problem in Firefox

![Image](https://github.com/user-attachments/assets/55435af1-f8cd-4f15-b8dc-f80511bf545b)

You are probably using an old version of Firefox?

**Comment by daniel-odrinski** [comment]
Seeing this on Brave:
```
[Version 1.77.97 Chromium: 135.0.7049.84 (Official Build) (arm64)]
```

**Comment by daniel-odrinski** [comment]
@johanbook Please see above.

**Comment by slorber** [comment]
This `<body data-theme='light'` is not supposed to be there while the site has a dark theme.

![Image](https://github.com/user-attachments/assets/4372d693-ec0f-4716-9fef-a77990fdf82d)

Docusaurus doesn't set `data-theme` in the body tag, it sets it on the HTML tag. You probably have code that messes up with our theming implementation.

**Comment by abdelhamidbeji** [comment]
Just adding this here in case it helps someone later — we ran into the same issue.

In our case, it was caused by a search plugin [@cmfcmf/docusaurus-search-local](https://github.com/cmfcmf/docusaurus-search-local/blob/540d22421b5fac9d227dc2751bcfd1f2a24bfee9/packages/docusaurus-search-local/src/client/theme/SearchBar/index.tsx#L388), which injects the `data-theme` in the `body` element, causing the double logo issue and some flashing.

> Not seeing this problem in Firefox
> 
> ![Image](https://github.com/user-attachments/assets/55435af1-f8cd-4f15-b8dc-f80511bf545b)
> 
> You are probably using an old version of Firefox?

From that screenshot, it looks like the same plugin was being used there too.

We fixed it by switching to [@easyops-cn/docusaurus-search-local](https://github.com/easyops-cn/docusaurus-search-local), which is a fork of the original one.

Both plugins are referenced in the [Docusaurus official documentations.](https://docusaurus.io/community/resources#search)

**Comment by OfficialMutazAwad** [comment]
New reply to your ticket #12175

Title: Re: [facebook/docusaurus] Duplicate logo in navbar on load in Firefox with v3 (Issue #9527)

Message: Hello,we received your message and our support will reach out to you as soon as possible.

**Comment by slorber** [comment]
Thanks for finding the root cause @abdelhamidbeji 

Have you reported it to the original search lib? (cc @cmfcmf).
Afaik it only added proper support for Docusaurus v3 recently (https://github.com/cmfcmf/docusaurus-search-local/pull/252).

**Comment by abdelhamidbeji** [comment]
No, I haven’t reported it yet, but I see you’ve just tagged them.
We had a patch in place to make it work with v3, as we haven’t had the bandwidth to explore other libraries for a while.
We also tried the new version, but the issue still persists.

**Comment by cmfcmf** [comment]
Thanks for letting me know! This will be fixed by https://github.com/cmfcmf/docusaurus-search-local/pull/254.
