### ISSUE TITLE
Installation Guide doesn't specify local installation commands

### ISSUE THREAD

**Issue by rafaelmotaalves** [facebook/Docusaurus#957]
## 📚 Documentation

The [Installation Guide](https://docusaurus.io/docs/en/installation#installing-docusaurus), doesn't specify the commands to install Docusaurus locally in the created project, this makes it a little confusing.

Those commands would be: 

`npm install docusaurus-init --save` 
 
`yarn add docusaurus-init`

Should i make a PR to correct this?

**Comment by nathfreder** [comment]
I think it is already there.
https://docusaurus.io/docs/en/installation#installing-docusaurus

**Comment by nathfreder** [comment]
> ## 📚 Documentation
> The [Installation Guide](https://docusaurus.io/docs/en/installation#installing-docusaurus), doesn't specify the commands to install Docusaurus locally in the created project, this makes it a little confusing.
> 
> Those commands would be:
> 
> `npm install docusaurus-init --save`
> 
> `yarn add docusaurus-init`
> 
> Should i make a PR to correct this?

I think that it is already in there @rafaelmotaalves. You can see it at this link. 
https://docusaurus.io/docs/en/installation#installing-docusaurus

**Comment by yangshun** [comment]
When you do `docusaurus-init`, the generated files will include `docusaurus` in `package.json`. Only the person who initializes docusaurus will need to have `docusaurus-init`, to scaffold the project. From there on, other users just have to do `npm/yarn start`. Is there any confusion here?

Closing this issue as there doesn't seem to be anything wrong with the installation docs. feel free to reopen this if there's something I'm missing.

**Comment by rafaelmotaalves** [comment]
Got it, i was under the impression you would install it as a development dependency.
