### ISSUE TITLE
Access restriction by password protection

### ISSUE THREAD

**Issue by Azcatchi** [facebook/Docusaurus#958]
## 🚀 Feature

I want to make a wiki for my enterprise, but it would contain some sensitive information as well. I need some kind of restriction that only allows authenticated users to read the wiki contents. Could you please consider this request to allow us protecting our wiki ? Thanks in advance.

**Comment by yangshun** [comment]
@Azcatchi As Docusaurus generates static content, there's no way for Docusaurus to add auth restrictions. This has to be done on the web server layer which is beyond the scope of Docusaurus. I recommend that you look up the docs for adding auth to the web server you are using or put your contents behind a VPN.

Closing this issue as it's out of scope.

**Comment by TautvydasDerzinskas** [comment]
> @Azcatchi As Docusaurus generates static content, there's no way for Docusaurus to add auth restrictions. This has to be done on the web server layer which is beyond the scope of Docusaurus. I recommend that you look up the docs for adding auth to the web server you are using or put your contents behind a VPN.
> 
> Closing this issue as it's out of scope.

I think this answer is outdated. Docosaurus essentially is SPA, so password addition is not impossible.

**Comment by Josh-Cena** [comment]
> I think this answer is outdated. Docosaurus essentially is SPA, so password addition is not impossible.

Yes, it's indeed possible, but it's absolutely out of scope. You are welcome to swizzle `Root` and add your authentication layer.

**Comment by yangshun** [comment]
I'm referring to not using any external auth services for server-side password protection. That's still not possible.

**Comment by leanndemetro** [comment]
Hi there, not sure if this is what is being referred to, but you can easily create an Express Server with Basic Auth for your Docusaurus site and use the Express.static method to serve the build folder. 

Run npm run build and you will see a build folder is dynamically created in your project and then

You will need to add 

"type": "module", 

and the script

"start": "node --experimental-modules src/app.js",

to your package.json 

and create an app.js file within the src directory and add the code

import express from 'express';
import dotenv from 'dotenv';

dotenv.config();

const app = express();

app.use(express.json());

const authorize = ((req, res, next) => {

    const auth = {login: process.env.USERNAME, password: process.env.PASSWORD} // change this

    // parse login and password from headers
    const b64auth = (req.headers.authorization || '').split(' ')[1] || ''
    const [login, password] = Buffer.from(b64auth, 'base64').toString().split(':')
  
    // Verify login and password are set and correct
    if (login && password && login === auth.login && password === auth.password) {
      // Access granted...
      return next()
    }
  
    // Access denied...
    res.set('WWW-Authenticate', 'Basic realm="401"') // change this if desired
    res.status(401).send('Authentication required.') // custom message
});

app.use('/', authorize);
app.use('/', express.static('build'));

app.listen(3000);

Hope this helps!

**Comment by techbridgedev** [comment]
I tried @leanndemetro's solution, which does indeed create a login dialogue, but using the default username & password ("USERNAME" & "PASSWORD"), I couldn't log in. Am I missing something?

**Comment by massoudmaboudi** [comment]
You may check my articles that show how to add an authentication layer to your Docusuaurs website.

https://iammassoud.net/blog/docusaurus-authentication-roadmap

**Comment by techbridgedev** [comment]
> You may check my articles that show how to add an authentication layer to your Docusuaurs website.
> 
> https://iammassoud.net/blog/docusaurus-authentication-roadmap

Thank, Massoud. I followed the tutorial for authenticating with AWS Cognito & got it to work on my local setup, but the build step chokes with:

```
[ERROR] Unable to build website for locale en-us.

[ERROR] Error: The `docusaurus_tag` meta tag could not be found. Please make sure that your page is wrapped in the `<Layout>` component (from `@theme/Layout`). If it is, then this is a bug, please report it.
```

Any idea what may be going on? If I rename the theme directory temporarily I can complete a build, but of course, that stops the authentication components from being compiled. It does point to something in one of those swizzled components as being the culprit, though.

**Comment by massoudmaboudi** [comment]
> > You may check my articles that show how to add an authentication layer to your Docusuaurs website.
> > https://iammassoud.net/blog/docusaurus-authentication-roadmap
> 
> Thanks, Massoud. I followed the tutorial for authenticating with AWS Cognito & got it to work on my local setup, but the build step chokes with:
> 
> ```
> [ERROR] Unable to build website for locale en-us.
> 
> [ERROR] Error: The `docusaurus_tag` meta tag could not be found. Please make sure that your page is wrapped in the `<Layout>` component (from `@theme/Layout`). If it is, then this is a bug, please report it.
> ```
> 
> Any idea what may be going on? If I rename the theme directory temporarily I can complete a build, but of course, that stops the authentication components from being compiled. It does point to something in one of those swizzled components as being the culprit, though.

Maybe you can share your repo if it is public.
or
at least you can share your file hierarchy and the content of Root.js

**Comment by techbridgedev** [comment]
It a private repo, but here's the hierarchy:

```
.
└── App/
    ├── .docusaurus/
    ├── .vscode/
    ├── build/
    ├── dist/
    ├── docs/
    ├── node_modules/
    ├── src/
    │   ├── components/
    │   │   ├── Auth/
    │   │   │   └── index.js
    │   │   ├── Login/
    │   │   │   └── index.js
    │   │   └── * OTHER UNRELATED COMPONENTS
    │   ├── config/
    │   │   ├── amplify-config.js
    │   │   └── aws-exports.js
    │   ├── css/
    │   ├── pages/
    │   ├── partials/
    │   ├── theme/
    │   │   ├── Navbar/
    │   │   │   ├── Content/
    │   │   │   │   ├── index.js
    │   │   │   │   └── styles.module.css
    │   │   │   └── MobileSidebar/
    │   │   │       └── index.js
    │   │   └── Root.js
    │   └── utils/
    │       ├── constants.js
    │       └── utils.js
    ├── static/
    ├── .env.local
    ├── .gitignore
    ├── .markdownlint.json
    ├── babel.config.js
    ├── docusaurus.config.js
    ├── jsonconfig.json
    ├── package.json
    ├── README.md
    └── sidebars.js
```
    
    And here's Root.js:

   ```
      // src/theme/Root.js
      
      import React from 'react';
      
      import { Amplify } from 'aws-amplify';
      import { Authenticator } from '@aws-amplify/ui-react';
      
      import { configure } from '../config/amplify-config';
      import { AuthCheck } from '../components/Auth';
      
      const awsConfig = configure();
      Amplify.configure(awsConfig);
      
      export default function Root({ children }) {
        return (
          <Authenticator.Provider>
            <AuthCheck children={children} />
          </Authenticator.Provider>
        );
      }
   ```

**Comment by massoudmaboudi** [comment]
@techbridgedev 
The issue doesn't seem to be with the swizzled components since it is working as expected. 
Though, you have a few options:

- Just clone my example repo, fill up the env file, and try to build it. I tested it, it worked as expected. Then step by step add your new changes.
- If you want, you can add me to your repo so I can check as well.
- You may check the `docusaurus.config.js` and the code in `pages` folder too.

Overall, this issue can be from your search plugin as well.

**Comment by techbridgedev** [comment]
> 

@massoudmaboudi
I cloned the `feat-specific-route-protection` branch of the repo, added my `.env.local` file, and ran the build script, but it failed with a bunch of broken links all pointing to `/login`. I am able to serve the site via `npm run start` and can confirm that authentication works.

I haven't pushed my own changes to my experimental branch where I am testing authentication, but I could if you still want to be added to the repo to check it out.

I still need to look into the search plugin to see if that's responsible.

**Comment by massoudmaboudi** [comment]
@techbridgedev 
You are correct since I missed pushing a line to **/src/components/Auth/index.js line 28**.
Please check the commit below for the code change:
[commit](https://github.com/massoudmaboudi/docusaurus-auth-cognito/commit/403689be537a5ca87c996cb2866d843b460b0dc6#diff-0348f014214677e2414b8d58be9b90185f4d907732e34bb4f316fd159e7bb62a)

**Comment by techbridgedev** [comment]
> @techbridgedev
> You are correct since I missed pushing a line to /src/components/Auth/index.js line 28.
> Please check the commit below for the code change:

I've downloaded both branches after the above fix but still have the same build error. Do you want me to file an issue?

**Comment by massoudmaboudi** [comment]
@techbridgedev 
You can resolve the issue by setting `onBrokenLinks: 'warn'` instead of `onBrokenLinks: 'throw'` in `docusaurus.config.js`. but I suggest the below code-change.

There should be an explanation why Docusaurus is behaving like this, though, to improve the code and not to change the default setting of Docusaurus, I created a new commit and added the `/login` route under `src/pages`.

[link to the commit](https://github.com/massoudmaboudi/docusaurus-auth-cognito/commit/ec0f2f9f461c34b21741d15645b2175a7fdfa0d6)

By this change, you don't need to change `docusaurus.config.js`.

**Comment by baretta881** [comment]
``

**Comment by norahsakal** [comment]
> You may check my articles that show how to add an authentication layer to your Docusuaurs website.
> 
> https://iammassoud.net/blog/docusaurus-authentication-roadmap

I just followed your tutorial, the auth works great! 

Thank you so much for such a detailed walkthrough, truly appreciate it!

**Comment by OmerFarukOruc** [comment]
> Hi there, not sure if this is what is being referred to, but you can easily create an Express Server with Basic Auth for your Docusaurus site and use the Express.static method to serve the build folder.

I would like to ask if everything is good when deployed to Vercel and used that Auth?

**Comment by IRiViI** [comment]
I created a function protection system and it works great when going to: /someprotectedpage
However if someone goes to /notprotected and clicks on a button that leads to /someprotectepage it doesn't work anymore because of the one page aspect that will just ask for hashed .js files. I'm currently trying to track which hash files belongs to which page but that seems to be a whole rabbit hole on it's own.
How did you all solve this problem? 

I do have some other ideas like:
- Make people reload the page when going to protected pages (but that isn't backend secure)
- building a limited unprotected build and basically host 2 different version and give hashed bashed on login (but seems a bit of a hassle if you have different types of protected areas)

----------------
Edit:
Fixed it, I just read the .js files and create a mapping file based on the attributes in those files.

**Comment by slorber** [comment]
@IRiViI my recommendation would be to build 2 static sites that differ based on env variables/config:
- one for authenticated users
- one for anonymous users

Then you can use your CDN edge features to route the user to one deployment or the other, depending on cookies and other things like that.

**Comment by IRiViI** [comment]
Yeah thanks. I have something similar. The two builds are hosted by the same node server using cookie info. The current small issue that is a little bit annoying is that I have to redirect the user in order to download the other index.html. But other than that it works great.
