### ISSUE TITLE
Make it possible to add component above synthetic title

### ISSUE THREAD

**Issue by banool** [facebook/docusaurus#9588]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Description

When you the `title` field set in the front matter of a doc, this title will always appear before the content of the doc. This logic is defined in [DocItem/Layout](https://github.com/facebook/docusaurus/blob/683ba3d2a0a16a4346c0af26e349343163fa6df0/packages/docusaurus-theme-classic/src/theme/DocItem/Layout/index.tsx). The only things that appear above the title are `Unlisted` and `DocVersionBanner` (conditionally).

I would like to include my own component above the title, but I can't find a way to do that with swizzling safely. All of these components are considered unsafe to swizzle:
- `DocVersionBadge`
- `DocItem/Content`
- `DocItem/Layout`
- `Heading`

Could we make it possible to add components above the synthetic title in a doc?

This is with Docusaurus version 2.4.1.

### Motivation

I would like to add a badge that looks just like the version badge, but it says "BETA" with a yellow background. Ideally it would appear alongside a version badge if present (though that isn't relevant in my specific case). I have a draft component already that does pretty much this:
```
// This code oringates from DocVersionBadge in the @docusaurus/theme-classic package.

import React from 'react';
import clsx from 'clsx';

export default function DocBadge({
    text,
    className,
}: { text: string, className: string }): JSX.Element | null {
    return (
        <span
            className={clsx(
                className,
                'badge badge--secondary',
            )}>
            {text}
        </span>
    );
}
```

### API design

I'd love to add support for a custom value in the frontmatter, for example:
```
---
title: "My Doc"
beta: true
---
```

I would then have some swizzled component that reads this and updates the layout accordingly to add my component above the title.

Perhaps more simply, I want something like this:
```
---
title: "Indexer API"
beta: true
---

import DocsBadge from "@site/src/components/DocsBadge";

<DocsBadge text="BETA" someWayToTagThatThisShouldGoAboveTheTitle />

Lorem ipsum etc etc
```

### Have you tried building it?

I couldn't find a great way to make this happen without swizzling something considered unsafe.

### Self-service

- [ ] I'd be willing to contribute this feature to Docusaurus myself.

I'd be more than happy to take another crack at it with some guidance on a good way to make this happen.

**Comment by banool** [comment]
I understand there is behavior where if there is a h1 heading in the doc, it doesn't show the title from the frontmatter. Unfortunately this is not true if you try to put some component before it:
```
---
title: "My Doc"
beta: true
---

import DocsBadge from "@site/src/components/DocsBadge";

<DocsBadge text="BETA" />

# Real Title
```

In this case it will show My Doc as the large title, then the badge, and then Real Title after.

**Comment by banool** [comment]
I checked this discussion and couldn't find something suitable either: https://github.com/facebook/docusaurus/discussions/5468.

**Comment by slorber** [comment]
> I understand there is behavior where if there is a h1 heading in the doc, it doesn't show the title from the frontmatter. Unfortunately this is not true if you try to put some component before it:
> 
> ```
> ---
> title: "My Doc"
> beta: true
> ---
> 
> import DocsBadge from "@site/src/components/DocsBadge";
> 
> <DocsBadge text="BETA" />
> 
> # Real Title
> ```
> 
> In this case it will show My Doc as the large title, then the badge, and then Real Title after.

I believe this is fixed in v3, please upgrade and try again to achieve your customization.

<img width="1212" alt="CleanShot 2023-11-30 at 16 18 39@2x" src="https://github.com/facebook/docusaurus/assets/749374/f857502f-5da0-4255-b58d-fea72a834993">

---

As documented, you shouldn't be too afraid of swizzling unsafe components, and just keep in mind that you might have to update them on minor upgrades.

https://docusaurus.io/docs/swizzling#what-is-safe-to-swizzle

<img width="991" alt="CleanShot 2023-11-30 at 16 24 22@2x" src="https://github.com/facebook/docusaurus/assets/749374/28d43b28-24d4-4ce8-9d6e-f218c28bbabe">


It does not mean that there will be breaking changes in practice, and most components are quite stable, but we do not want to guarantee perfect retrocompatibility to avoid making it impossible for us to work on the theme between major versions.


Swizzling `DocItem/Content` seems perfectly reasonable to me for this usecase
