### ISSUE TITLE
improper/unexpected rendering in page using <CodeBlock> 

### ISSUE THREAD

**Issue by dovholuknf** [facebook/docusaurus#9591]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

[codesandbox.io link](https://codesandbox.io/p/devbox/adoring-leftpad-87qf4l?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clpkr7ymg000d356abfymyvtf%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clpkr7ymg0004356a4tz2eo0a%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clpkr7ymg000a356afa9bz9oh%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clpkr7ymg000c356a5o6eeuvh%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B64.22222222222223%252C35.77777777777777%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clpkr7ymg0004356a4tz2eo0a%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clpkr7ymg0003356avymwll0i%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clpkr7ymg0004356a4tz2eo0a%2522%252C%2522activeTabId%2522%253A%2522clpkr7ymg0003356avymwll0i%2522%257D%252C%2522clpkr7ymg000c356a5o6eeuvh%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clpkr7ymg000b356a44vll1e0%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A3000%252C%2522path%2522%253A%2522%252Ftest%2522%257D%255D%252C%2522id%2522%253A%2522clpkr7ymg000c356a5o6eeuvh%2522%252C%2522activeTabId%2522%253A%2522clpkr7ymg000b356a44vll1e0%2522%257D%252C%2522clpkr7ymg000a356afa9bz9oh%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clpkr7ymg0005356a34wloihj%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522docusaurus%2522%257D%252C%257B%2522id%2522%253A%2522clpkr7ymg0006356acxuc8tdf%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522start%2522%257D%252C%257B%2522id%2522%253A%2522clpkr7ymg0007356afv9f0l15%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522clear%2522%257D%252C%257B%2522id%2522%253A%2522clpkr7ymg0008356a6mlyd83u%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522serve%2522%257D%252C%257B%2522id%2522%253A%2522clpkr7ymg0009356aqlln27dt%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%257D%255D%252C%2522id%2522%253A%2522clpkr7ymg000a356afa9bz9oh%2522%252C%2522activeTabId%2522%253A%2522clpkr7ymg0005356a34wloihj%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

Adding <CodeBlock> to a page, inside a <div> with flex styling renders the codeblock incorrectly/unexpectedly.

**Demonstration**:
![codeblock-demo](https://github.com/facebook/docusaurus/assets/46322585/545eac99-5111-467c-b2bc-33e28db95a54)

### Steps to reproduce

* `npx create-docusaurus@latest my-website classic`
* create a page named 'test' (add src/pages/test/index.js) with contents:
```
import React from "react";
import CodeBlock from '@theme/CodeBlock'
import LayoutProvider from '@theme/Layout/Provider';

function App() {
    return (
        <LayoutProvider>
            <div style={{margin: "50px"}}>
                <CodeBlock language="jsx">
                    {`short line...
                    this is a long line that will be wider than the apple 14 max and google pixel 6 default resolution of ~400-440px
short line...`}
                </CodeBlock>
            </div>
            <div style={{display: "flex", margin: "50px"}}>
                <CodeBlock language="jsx">
                    {`short line...
                    this is a long line that will be wider than the apple 14 max and google pixel 6 default resolution of ~400-440px
short line...`}
                </CodeBlock>
            </div>
        </LayoutProvider>
    );
}
export default App;
```
* go to http://localhost:3000/test
* observe the first code block looks and acts 'correctly'. it has the two buttons (wrap/copy)
* observe the second block is not wrapped, text doesn't overflow, only one button is shown if you scroll all the way to the right

### Expected behavior

both CodeBlocks would render the same

### Actual behavior

second block is not wrapped, text doesn't overflow, only one button is shown if you scroll all the way to the right

### Your environment

- Public source code:
- Public site URL:
- Docusaurus version used:
- Environment name and version (e.g. Chrome 89, Node.js 16.4):
- Operating system and version (e.g. Ubuntu 20.04.2 LTS):

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by dovholuknf** [comment]
Dunno if it's technically "correct" but I found a simple workaround with a 100% wide div wrapping the code block
```
                <div style={{width: "100%"}}>
                <CodeBlock language="jsx">
```

**Comment by slorber** [comment]
It's not clear to me what's the point of adding display flex in the first place.

Of course your own CSS can impact our layout, isn't it expected? Flex impacts the layout of child elements.

**Comment by dovholuknf** [comment]
In this example, not much but I radically simplified the example, in the hopes of keeping it easy to test/reproduce but in my page I had numerous other divs that all needed layout for 'reasons'...

If the doc had any sort of indication as to how someone could add <CodeBlock> elements within a flex container, that'd satisfy my need. I naively expected the control to handle this situation. I was not prepared to see the `overflow` change and the button placement change.

I found just now I could specify the overflow in the flex div style,. That returns the scrolling of the code block as you'd expect, but the copy button is still all the way to the right and the wrap button doesn't even display.

**Comment by dovholuknf** [comment]
It was nothing super fancy... it was a two column layout type of thing like this 
![image](https://github.com/facebook/docusaurus/assets/46322585/6d7f6907-b47f-4ebc-9d0a-c545e982f5ba)

I want the code block to work exactly the same as all the other doc does on the site when using md/mdx and triple tick code fences with the docs plugin... So that when on a phone, these long code blocks "shrink" responsively and then show the two buttons.

So on that example shown above, when the horiztonal width is less than ~600px or so, overflow turns on and the element shrinks etc.

I expect it works fine when not in a "2 column layout" like this, but that wasn't my situation... 🤷

**Comment by dovholuknf** [comment]
That's incredibly helpful and incredibly appreciated. Very much so. This does exactly what I was hoping it would do. TIL about "the flex min-width issue"! Cheers

![codeblock](https://github.com/facebook/docusaurus/assets/46322585/deb35db0-39e9-4030-b781-3c270d4cba6b)
