### ISSUE TITLE
Highlightjs custom highlighting config ignored in production

### ISSUE THREAD

**Issue by chenglou** [facebook/Docusaurus#960]
### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## To Reproduce

1. In `siteConfig.js`, in the `highlight` field, add this:
    ```js
    hljs: function(hljs) {
      hljs.registerLanguage('reason', reasonHighlightJs)
    }
    ```
    where `reasonHighlightJs` is an existing callback that adds a new highlighter.
1. Run dev, see that the custom highlighting works

## Expected behavior

Run prod, see that the custom highlighting should be picked up

## Actual Behavior

Highlighting isn't picked up =(

## Reproducible Demo

Check out https://github.com/reasonml/reasonml.github.io/commit/2c7b36fed305b7fa6afa7999d65078a13e5d61d0 then `cd website && yarn && yarn start`, compare some resulting highlighting html against `yarn docusaurus-build` in the generated `docs` folder.

## Solution

This is caused by dev & prod not sharing the same code path. They have diverged quite a bit from what I'm seeing. I've patched this like so: https://github.com/chenglou/Docusaurus/commit/bade05e408bef8d94a6ba3281fdb3f6295c30284
As a matter of fact, `siteConfig.hightlight.hlgs` is never called anywhere in prod!
This patch works, but I'm not too sure this is the right way to go. The dev & prod flow should probably be much closer. There are likely other hidden bugs.

**Comment by endiliey** [comment]
> As a matter of fact, siteConfig.hightlight.hljs is never called anywhere in prod!

As far as I'm aware, the only place where we define the highlightjs is only on that file. I checked the git blame and it seems that it has been like this since the initial release.

> This patch works, but I'm not too sure this is the right way to go

I think the patch is the correct way to do it. I implemented it this way for v2, although it seems that I didn't port it back to v1 😆

**Comment by rishacha** [comment]
Hi, can I attempt this ?

**Comment by endiliey** [comment]
@rishacha sure, send a PR in 👍
