### ISSUE TITLE
Introduce alternative admonition title syntax

### ISSUE THREAD

**Issue by homotechsual** [facebook/docusaurus#9607]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Motivation

The current admonition title syntax is difficult for many markdown (and MDX) tools to lint, being recognised in VSCode as a link.

An alternative title syntax should be considered - perhaps alongside the existing one - similar to what Astro did in their Starlight docs system here:  https://github.com/withastro/starlight/pull/707

### Self-service

- [ ] I'd be willing to do some initial work on this proposal myself.

**Comment by slorber** [comment]
Actually we already support this.

You can use it as a workaround until support is improving in IDEs and tools if you want.

However afaik there's a limitation, and you can't pass JSX nodes as directive attributes.

```md
:::tip[Did <b style={{color: "red"}}>you</b> know?]

Content

:::

:::tip{title="Did <b style={{color: 'red'}}>you</b> know?"}

Content

:::
```

<img width="313" alt="CleanShot 2023-12-15 at 12 31 41@2x" src="https://github.com/facebook/docusaurus/assets/749374/377800b7-e58f-490a-85c0-d4e41c56b90d">

I'd prefer to keep it undocumented for now considering it's probably not the syntax we want to encourage users to adopt.

**Comment by slorber** [comment]
@wooorm is it planned to support JSX attributes in remark-directives, or it is not supported on purpose?

I tried this and it's not interpreted as a directive: `::hey{title=<>hey</>}`

<img width="481" alt="CleanShot 2023-12-15 at 12 36 12@2x" src="https://github.com/facebook/docusaurus/assets/749374/0259caa9-93ca-4312-b08a-95471075ce36">

**Comment by homotechsual** [comment]
Thanks @slorber for that - that's awesome!

**Comment by wooorm** [comment]
MDX is already the alternative to directives:

```mdx
<Tip title={<>Did <b style={{color: "red"}}>you</b> know?</>}>
  Content
</tip>

<Tip title="Did you know?">
  Content
</Tip>
```

**Comment by slorber** [comment]
Thanks 👍
