### ISSUE TITLE
Mobile Alignment Issue - Center Alignment Needed

### ISSUE THREAD

**Issue by charu1603** [facebook/docusaurus#9635]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [ ] I have tried the `npm run clear` or `yarn clear` command.
- [ ] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io.
- [ ] I have read the console error message carefully (if applicable).

### Description

I have identified an alignment issue on mobile devices where the content is not center-aligned as intended. Currently, the content appears off-center, impacting the overall user experience.

### Steps to reproduce

we can use 
text-align: center property for the mobile devices

### Expected behavior

![Screenshot (522)](https://github.com/facebook/docusaurus/assets/96014425/120ec5b6-5498-4549-ac68-4b6339bcbbb9)

### Actual behavior

![Screenshot (523)](https://github.com/facebook/docusaurus/assets/96014425/e898c7a0-40b5-4a70-96de-00234d6597ca)

### Your environment

- Public source code:
- Public site URL:
- Docusaurus version used:
- Environment name and version (e.g. Chrome 89, Node.js 16.4):
- Operating system and version (e.g. Ubuntu 20.04.2 LTS):

### Self-service

- [X] I'd be willing to fix this bug myself.

**Comment by Josh-Cena** [comment]
It's not center aligned because it's left-aligned😅 It's a design decision. If you don't like it, you can add the CSS rule to your own website.

**Comment by slorber** [comment]
Agree, this can't really be considered as a bug, and you can change the design on your own site if you want.

We should probably fully redesign Docusaurus someday, but for now this is the design we have decided to use. 

It will never be possible to create a design that please everyone anyway. The goal of Docusaurus is not to please everyone, but rather to be good enough and let you change what you don't like, which is possible here.
