### ISSUE TITLE
Bug Related To Client API Action Button

### ISSUE THREAD

**Issue by TartejBrothers** [facebook/docusaurus#9640]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Description

- This bug is related to website documentation. [Link to Exact Page](https://docusaurus.io/docs/docusaurus-core)
<img width="994" alt="image" src="https://github.com/facebook/docusaurus/assets/112921727/0099558f-190a-49d7-ae60-cbac5bcda6d3">

- Once we click the Client API action button, i.e. the Boom button, the webpage crashes.
![image](https://github.com/facebook/docusaurus/assets/112921727/a2bd7acd-a22e-4f01-bac3-02a78e861dd9)

### Self-service

- [ ] I'd be willing to address this documentation request myself.

**Comment by Josh-Cena** [comment]
That button is called "Boom!" because it crashes the page 😅 You are reading the documentation for error handling, what else would you expect it to do?

**Comment by TartejBrothers** [comment]
Oh, I was just going through pages, and clicked the boom button and thought it was a bug. My bad.
