### ISSUE TITLE
Using `exclude` makes partials appear as pages

### ISSUE THREAD

**Issue by anatolykopyl** [facebook/docusaurus#9641]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

When `docs.exclude` (@docusaurus/preset-classic) is defined, files starting with `_` are shown in the sidebar and can be navigated to.

The reproduction is a starter project, with 2 changes:
1. `docs/tutorial-basic/congratulations.md` renamed to `docs/tutorial-basic/_congratulations.md`
2. `docs.exclude` in `docusaurus.config.js` set to `["tutorial-extras/translate-your-site.md"]`

### Reproducible demo

https://codesandbox.io/p/devbox/docusaurus-exclude-repro-c2jgtf

### Steps to reproduce

1. Check that `docs/tutorial-basic/_congratulations.md` starts with an underscore
2. Start docusaurus
3. Navigate to `/docs/tutorial-basics/_congratulations`

### Expected behavior

The page `congratulations.md` shouldn't be visible.

### Actual behavior

The page `congratulations.md` is visible.

### Your environment

Codesandbox from docusaurus.new

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by slorber** [comment]
This is working as intended, the `exclude` option you provide overrides the default one we set, and lets you opt-out of the automatic exclusion in case you don't like our default value.

If you want to add additional exclude rules in addition to the existing one, you have to add back the existing ones

```
export default {
  presets: [
    [
      '@docusaurus/preset-classic',
      {
        docs: {
          exclude: [

            // Default excludes 
            '**/_*.{js,jsx,ts,tsx,md,mdx}',
            '**/_*/**',
            '**/*.test.{js,jsx,ts,tsx}',
            '**/__tests__/**',

            // Your extra excludes 
            '**/*.ignoreThis.md',

          ],
        },
      },
    ],
  ],
};
```
