### ISSUE TITLE
Expected corresponding JSX closing tag for <calculated> ( JSX incorrectly recognized )

### ISSUE THREAD

**Issue by Zzhiter** [facebook/docusaurus#9647]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

## I added new content and tried to compile the md file, but the compiler mistakenly recognized my "<calculated when request is sent>" text as a JSX element. Is this a BUG?

![image](https://github.com/facebook/docusaurus/assets/61727602/85971aaf-2e37-4802-b803-6da617480a94)

### Steps to reproduce

Add <calculated when request is sent> in the md file

### Expected behavior

Expected corresponding JSX closing tag for <calculated>. (40:103)

### Actual behavior

![image](https://github.com/facebook/docusaurus/assets/61727602/2768cee8-f8fb-44eb-a0e3-8ebe1ea6dee5)

### Your environment

- Public source code:
- Public site URL:
- Docusaurus version used:
- Environment name and version (e.g. Chrome 89, Node.js 16.4):
- Operating system and version (e.g. Ubuntu 20.04.2 LTS):

### Self-service

- [X] I'd be willing to fix this bug myself.

**Comment by Josh-Cena** [comment]
Please read https://docusaurus.io/blog/preparing-your-site-for-docusaurus-v3#bad-usage-of--1

**Comment by slorber** [comment]
Please respect our issue template and report bugs appropriately.

This is how MDX works, try in the playground it doesn't compile either: https://mdxjs.com/playground/

If you don't like this behavior you can also opt-in for our experimental CommonMark mode: https://docusaurus.io/docs/markdown-features#mdx-vs-commonmark
