### ISSUE TITLE
Sidebar title and doc title don't change after updating it in file (2)

### ISSUE THREAD

**Issue by testeratrsa** [facebook/Docusaurus#965]
## 🐛 Bug Report
yes

(A clear and concise description of what the bug is)
Sidebar title and doc title don't change after updating it in file

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

yes

## To Reproduce

We guys tried to update the title of a markdown file but we can't do it. For the previously(before 05 Sep 2018) created markdown files title are working fine but for newly(on 15 Sep 2018) created markdown file it has some issue with displaying the title.
our markdown file is presented folder inside a folder which for our understanding and convenience.

1. Syntax was given as markdown which has correct title structure 
1. Saved the markdown file and necessary changes were made in sidebar.json  
1. Restarted the server
1. title and sidebar appear as api/login

## Expected behaviour
Sidebar title and page title should be displayed as:-  
![image](https://user-images.githubusercontent.com/43332296/45609847-4d90a600-ba77-11e8-9928-68c64c597c40.png)

## Actual Behaviour

![image](https://user-images.githubusercontent.com/43332296/45609885-787afa00-ba77-11e8-8d82-0a71ba6d4bc5.png)

the syntax which was given is:-  
```
---
id: login
title: Login
sidebar_label: Login
---

```

Tried deleting the en.json file inside i18n and made the necessary changes in package.json as suggested in 
https://github.com/facebook/Docusaurus/issues/813

Still, the issue remains the same.

## Reproducible Demo

https://github.com/testeratrsa/rsadocusaurus/tree/master

**Comment by endiliey** [comment]
Should be fixed by https://github.com/facebook/Docusaurus/pull/917
Please upgrade your Docusaurus 😃

**Comment by testeratrsa** [comment]
I tried installing the newer version of Docusaurus (1.4.0) but still, I faced the same issue. 
So I copied the title syntax from other markdown files which is working fine. And pasted it in issue throwing markdown file 
Boom, Issue was solved. The syntax we have used have no differences. Why it did not work for the first time? and why it is worked for the second time? I don't get it.

**Comment by endiliey** [comment]
Could be caching issue. Hard to tell without any reproducible repo. I'm closing this.
