### ISSUE TITLE
Math equation appears twice

### ISSUE THREAD

**Issue by ArthurFlageul** [facebook/docusaurus#9650]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have a [repro](https://codesandbox.io/p/devbox/beautiful-tharp-rhcwy3?file=%2Fdocs%2Fintro.md)
- [x] I have read the console error message carefully (if applicable).

### Description

When using math directives, the output appears twice, once styled as an equeation and once unstyled.

![Screenshot 2023-12-20 at 12 10 26](https://github.com/facebook/docusaurus/assets/28596581/f6aa4ba7-28e3-4e09-ad95-60895b7ad56d)

### Steps to reproduce

I have installed:
- "rehype-katex": "7"
- "remark-math": "6"
-  "@docusaurus/core": "^3.0.1"

I use the following content:

```md
---
title: Test
---

${max\_connections} = 75 \times RAM + extra\_connection$
```

My config's presets object contains:

```ts
presets: [
    [
      "classic",
      {
        docs: {
          routeBasePath: "/",
          sidebarPath: "./sidebars.ts",
          remarkPlugins: [remarkMath],
          rehypePlugins: [rehypeKatex],
        },
        theme: {
          customCss: ["./src/css/custom.css", "./src/css/navbar.css"],
        },
```

### Expected behavior

Only the styled equation should be rendered.

I can update the docs if needed, should it be an installation/config issue.

### Actual behavior

I'm getting these elements:

```html
<span class="katex-mathml">...</span>
<span class="katex-hml">...</span>
```

### Your environment

- Public source code:
- Public site URL:
- Docusaurus version used: 3.0.1
- Environment name and version (e.g. Chrome 89, Node.js 16.4): Chrome 120
- Operating system and version (e.g. Ubuntu 20.04.2 LTS):

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by slorber** [comment]
Please create a docusaurus.new repro, this saves everyone a lot of time and makes it easier to help you.

**Comment by ArthurFlageul** [comment]
Sure, here you go: https://codesandbox.io/p/devbox/beautiful-tharp-rhcwy3?file=%2Fdocs%2Fintro.md

**Comment by slorber** [comment]
Thanks

Not sure why Codesandbox doesn't work very well for me lately, am I alone?

Here's a StackBlitz repro showing it works
https://stackblitz.com/edit/github-q5buam?file=docusaurus.config.js,docs%2Fintro.md

It's very likely because you didn't install the stylesheet, because the duplicate item should be hidden by CSS rules.

https://docusaurus.io/docs/next/markdown-features/math-equations#configuration

<img width="771" alt="CleanShot 2023-12-21 at 17 38 20@2x" src="https://github.com/facebook/docusaurus/assets/749374/1b077e7a-f018-4a8d-9575-b7c45031ba58">

**Comment by ArthurFlageul** [comment]
Ah thanks! Somehow I felt it wasn't necessary to add this since that rendered fine without. I'll touch up the docs to clarify this, if that's ok.

**Comment by ArthurFlageul** [comment]
In general, it's better practice to have a clear list of numbered steps. It's easier to read and to update. I'll open a PR, feel free to take or leave it 👍  I suppose the content is all there in the docs but it'd be nice to harmonize things and make them more readable. Happy to help on that front.
