### ISSUE TITLE
plugin-client-redirects: Support external URLs

### ISSUE THREAD

**Issue by matevz** [facebook/docusaurus#9651]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Description

We migrated a chapter describing the API from a plain markdown file into the project's source code API code comments. Then, we generated the API reference pages with the Solidity doc generator and host them on another domain (api.docs.oasis.io versus docs.oasis.io).

But, for backward compatibility, we always redirect any removed/renamed pages to a new URL using https://docusaurus.io/docs/api/plugins/@docusaurus/plugin-client-redirects. To make the redirect work in our case, we would need to use something like this:

```typescript
        {
            to: 'https://api.docs.oasis.io/sol/sapphire-contracts/',
            from: '/dapp/sapphire/precompiles',
        },
```
, but this yields

```
[ERROR] ValidationError: "redirects[44].to" is not a valid pathname. Pathname should start with slash and not contain any domain or query string.
```

It would be nice to have support for redirecting to external websites. For now, we just use a placeholder file with "This chapter has beem moved to..." content.

### Motivation

See above.

### Self-service

- [ ] I'd be willing to contribute this feature to Docusaurus myself.

**Comment by slorber** [comment]
Please respect our issue template, mention the docusaurus version used and always try on the latest version.

3.0 supports this: https://github.com/facebook/docusaurus/pull/9171
