### ISSUE TITLE
Playground links not working

### ISSUE THREAD

**Issue by rishabmahesh** [facebook/docusaurus#9680]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Description

I was trying out Docusaurus via the [Playground](https://docusaurus.io/docs/playground) links on [StackBlitz](https://stackblitz.com/github/facebook/docusaurus/tree/main/examples/classic-typescript?file=README.md), it is unable to start the app. It appears to be a dependencies issue

As seen on StackBlitz: -
<img width="1305" alt="image" src="https://github.com/facebook/docusaurus/assets/40491438/b6353d25-1805-4386-a761-bf518a45c777">

### Self-service

- [ ] I'd be willing to address this documentation request myself.

**Comment by OzakIOne** [comment]
This issue appears when you have a adblocker or similar activated, try to disable your adblocker or similar on stackblitz

**Comment by slorber** [comment]
hmm, I have an adblocker and it's not a problem, not sure it's related to this.

IMHO it's just a temporary failure due to network or npm. Try again and we'll reopen if you can reproduce consistently, including in other browsers or new chrome profiles with no extensions.

**Comment by levino** [comment]
I have the same.
