### ISSUE TITLE
headTags escapes quotes unnecessarily

### ISSUE THREAD

**Issue by timothymcmackin** [facebook/docusaurus#9686]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

I'm trying to add CSP headers to my site so I can load resources from google tag manager and other sites. I added this header tag to my site in `docusaurus.config.js`:

```
const config = {
  headTags: [
    {
      tagName: 'meta',
      attributes: {
        'http-equiv': 'Content-Security-Policy',
        content: `'self' 'unsafe-inline' https://*.googletagmanager.com;`,
      },
    },
  ],
}
```

When I build this site, the HTML tag escapes the quotes, like this:

```
<meta http-equiv="Content-Security-Policy" content="&#39;self&#39; &#39;unsafe-inline&#39; https://*.googletagmanager.com;">
```

These escaped quotes prevent the browser from loading scripts from GTM. I don't see any way to insert unsafeInnerHtml here, and I've tried different combinations of single quotes, double quotes, and backticks with no success. I've also tried escaping the single quotes. I also tried doing this in the themeConfig:

```
themeConfig: {
  metadata: [{ "http-equiv": "Content-Security-Policy", content: "default-src 'none'; img-src 'self' https://*.googletagmanager.com https://*.google-analytics.com data:;" }],
}
```

But this  themeConfig also produces escaped tags.

### Reproducible demo

https://github.com/timothymcmackin/quote-encoding-minimal-repro

### Steps to reproduce

1. Clone https://github.com/timothymcmackin/quote-encoding-minimal-repro
2. Run `npm install`
3. Run `npm build`
4. In the output index.html file, check the meta tag with the content-security-policy info and see that the quotes are escaped.
5. Run `npm run serve` and open the site in a browser
6. Note the console error "The Content-Security-Policy directive name ''self'' contains one or more invalid characters. Only ASCII alphanumeric characters or dashes '-' are allowed in directive names."

### Expected behavior

I expected the site to render my meta tag with the content that I put in it.

### Actual behavior

Site rendered my meta tag with escaped quotes that causes the console error I mentioned.

### Your environment

- Public source code: https://github.com/timothymcmackin/quote-encoding-minimal-repro
- Public site URL:
- Docusaurus version used: 3.0.1
- Environment name and version (e.g. Chrome 89, Node.js 16.4): Chrome 120.0.6099.129, Node 18.17.1
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): macos 14.2.1

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by minaelee** [comment]
If I add a policy directive to the content such as default-src, such as:
```        content: `default-src 'self' 'unsafe-inline' https://*.googletagmanager.com`,```

Then build and serve, I don't see any console error. Does that work for you?

**Comment by slorber** [comment]
I don't think the issue is the encoding, browsers can parse the encoded CSP in principle. 

The CSP is kind of fail-fast: if browsers don't understand it, an error will be raised so no error is a proof for me that browsers can parse it correctly.

In your case, your CSP clearly has a problem and does not pass validation of tools such as https://csp-evaluator.withgoogle.com/

See for example the usage of this meta in a standalone html file:

```html
<meta http-equiv="Content-Security-Policy" content="default-src &#39;self&#39; &#39;unsafe-inline-does-not-exist&#39; https://*.googletagmanager.com;">
```

Chrome reports the error:

> The source list for the Content Security Policy directive 'default-src' contains an invalid source: ''unsafe-inline-does-not-exist''. It will be ignored.

No error if I use `'unsafe-inline'`, so the browser is likely to parse it well.

---

If you still believe the encoding is the problem, please prove it by creating 2 html files:
- one with decoded CSP that works
- one with encoded CSP that fails
