### ISSUE TITLE
Clobbering CSS files for external pages

### ISSUE THREAD

**Issue by JoelMarcey** [facebook/Docusaurus#97]
If you have a page that you don't want to have the default design for the site, but it still has CSS files, and you put those CSS files in static, those files will possibly clobber the CSS files of the site.

To fix, maybe...

have a flag that tells Docusaurus which are the canonical CSS files that should be used when rendering. While the others will be ignored.

**Comment by endiliey** [comment]
`separateCss` https://docusaurus.io/docs/en/site-config.html#optional-fields
