### ISSUE TITLE
CLI: Option to choose which browser to open

### ISSUE THREAD

**Issue by muuvmuuv** [facebook/Docusaurus#971]
I'm using Firefox Developer Edition as my primary developing browser and when I do the `docusaurus-start` it opens my Firefox for private use only. 
It would be nice to have somewhere an option to set the browser/browser path of choice.

**Comment by yangshun** [comment]
Just tested using `process.env.BROWSER` in the CLI via

```
$ BROWSER=firefox npm start
```

and it indeed opened up in Firefox. Docusarus wouldn't need to implement this, instead we could add this tip to the documentation instead. This task is up for grabs!
