### ISSUE TITLE
Seeing warnings about unsupported file type: undefined for SVG images

### ISSUE THREAD

**Issue by dabeeeenster** [facebook/docusaurus#9715]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

When running `npm run build` after upgrading to docusaurus `3.1.0` I have started seeing the following WARNING errors in the console:

```
[WARNING] The image at "/Users/ben/flagsmith/flagsmith/docs/static/img/saas-architecture.svg" can't be read correctly. Please ensure it's a valid image.
unsupported file type: undefined (file: /Users/ben/flagsmith/flagsmith/docs/static/img/saas-architecture.svg)
[WARNING] The image at "/Users/ben/flagsmith/flagsmith/docs/static/img/self-hosted-architecture.svg" can't be read correctly. Please ensure it's a valid image.
unsupported file type: undefined (file: /Users/ben/flagsmith/flagsmith/docs/static/img/self-hosted-architecture.svg)
[WARNING] The image at "/Users/ben/flagsmith/flagsmith/docs/static/img/flagsmith-model.svg" can't be read correctly. Please ensure it's a valid image.
unsupported file type: undefined (file: /Users/ben/flagsmith/flagsmith/docs/static/img/flagsmith-model.svg)
[WARNING] The image at "/Users/ben/flagsmith/flagsmith/docs/static/img/self-hosted-architecture.svg" can't be read correctly. Please ensure it's a valid image.
unsupported file type: undefined (file: /Users/ben/flagsmith/flagsmith/docs/static/img/self-hosted-architecture.svg)
[WARNING] The image at "/Users/ben/flagsmith/flagsmith/docs/static/img/self-hosted-architecture.svg" can't be read correctly. Please ensure it's a valid image.
unsupported file type: undefined (file: /Users/ben/flagsmith/flagsmith/docs/static/img/self-hosted-architecture.svg)
[WARNING] The image at "/Users/ben/flagsmith/flagsmith/docs/static/img/flagsmith-model.svg" can't be read correctly. Please ensure it's a valid image.
unsupported file type: undefined (file: /Users/ben/flagsmith/flagsmith/docs/static/img/flagsmith-model.svg)
[WARNING] The image at "/Users/ben/flagsmith/flagsmith/docs/static/img/saas-architecture.svg" can't be read correctly. Please ensure it's a valid image.
unsupported file type: undefined (file: /Users/ben/flagsmith/flagsmith/docs/static/img/saas-architecture.svg)
[WARNING] The image at "/Users/ben/flagsmith/flagsmith/docs/static/img/sdk-remote-evaluation.svg" can't be read correctly. Please ensure it's a valid image.
unsupported file type: undefined (file: /Users/ben/flagsmith/flagsmith/docs/static/img/sdk-remote-evaluation.svg)
[WARNING] The image at "/Users/ben/flagsmith/flagsmith/docs/static/img/sdk-local-evaluation.svg" can't be read correctly. Please ensure it's a valid image.
unsupported file type: undefined (file: /Users/ben/flagsmith/flagsmith/docs/static/img/sdk-local-evaluation.svg)
[WARNING] The image at "/Users/ben/flagsmith/flagsmith/docs/static/img/self-hosted-architecture.svg" can't be read correctly. Please ensure it's a valid image.
unsupported file type: undefined (file: /Users/ben/flagsmith/flagsmith/docs/static/img/self-hosted-architecture.svg)
[WARNING] The image at "/Users/ben/flagsmith/flagsmith/docs/static/img/sdk-remote-evaluation.svg" can't be read correctly. Please ensure it's a valid image.
unsupported file type: undefined (file: /Users/ben/flagsmith/flagsmith/docs/static/img/sdk-remote-evaluation.svg)
[WARNING] The image at "/Users/ben/flagsmith/flagsmith/docs/static/img/sdk-local-evaluation.svg" can't be read correctly. Please ensure it's a valid image.
unsupported file type: undefined (file: /Users/ben/flagsmith/flagsmith/docs/static/img/sdk-local-evaluation.svg)
```

You can find the images referenced here: https://github.com/Flagsmith/flagsmith/tree/main/docs/static/img e.g. https://github.com/Flagsmith/flagsmith/blob/main/docs/static/img/self-hosted-architecture.svg 

These are optimised SVG images but they are valid and display fine in browsers. 

### Reproducible demo

https://github.com/Flagsmith/flagsmith/pull/3246

### Steps to reproduce

1. Run `npm run build`
2. See warning about SVGs

### Expected behavior

No warning should show as the images are valid

### Actual behavior

Receive warnings `[WARNING] The image at "/Users/ben/flagsmith/flagsmith/docs/static/img/saas-architecture.svg" can't be read correctly. Please ensure it's a valid image.`

### Your environment

- Public source code: https://github.com/Flagsmith/flagsmith/pull/3246
- Public site URL: https://docs.flagsmith.com/
- Docusaurus version used: 3.1.0
- Environment name and version (e.g. Chrome 89, Node.js 16.4): Node `v20.9.0`
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): MacOS 14.2.1 (23C71)

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by slorber** [comment]
Can you create 2 minimal runnable repros? 
- one should show that the warning was not there in 3.0.1
- the other should show the warning appearing in 3.1.0

I doubt it's the upgrade that led this warning to appear, because the new release doesn't contain any code change related to this. 

My believe is that this warning has likely always been there, when you reference svgs in markdown content.

I'd kindly ask you to invest time to qualify better this potential bug.

**Comment by dabeeeenster** [comment]
Ah yes you are correct @slorber ! It was my clearing the build cache that caused the warnings to reappear. I'm still not clear why they are being thrown however? I believe the SVG files are valid?

**Comment by slorber** [comment]
> Ah yes you are correct @slorber ! It was my clearing the build cache that caused the warnings to reappear. I'm still not clear why they are being thrown however? I believe the SVG files are valid?

That's likely a bug related to using svg files using markdown image syntax.

<img width="1367" alt="CleanShot 2024-01-08 at 19 16 37@2x" src="https://github.com/facebook/docusaurus/assets/749374/04106ac3-515a-4824-9ff0-e28591e38923">

We should probably find a way to read the dimensions of local svg files to apply them to the `<img>` tag, so that it doesn't produce layout shifts when the svgs load.

Hmm apparently our lib "image-size" is supposed to handle svgs as well, so it's probably a bug in this library.

https://github.com/image-size/image-size

Can you provide a sample SVG?
Can you try reading its dimensions with that lib?

- If it works with the lib but not with Docusaurus, then report the bug to the lib. We'll wait for a fix and upgrade the lib once a fix is available.
- If it works with the lib but not Docusaurus, then it's a Docusaurus bug.

**Comment by dabeeeenster** [comment]
OK yep https://gist.github.com/dabeeeenster/004e82c3e344707751f294c16d5ddf50 shows the error being thrown in that library - issue raised here https://gist.github.com/dabeeeenster/004e82c3e344707751f294c16d5ddf50

**Comment by damageboy** [comment]
FWIW, I have the same issue with editable svg's saved with draw.io.

For now my solution is to add a build step that is invoked before `yarn build`:

```shell
# finds all .svg files and passes them to xargs to paraellelize
# svgo-ing them in groups of 10 (this avoids paying nodejs JIT time for every file)
fd -e svg -0 | xargs -0 -P $(nproc) -n 10 svgo                                                                                                              ─╯
```

**Comment by Airkro** [comment]
Pin `image-size` to `v1.0.x` fix this:

```jsonc
// package.json
{
  "devDependencies": {
    "image-size": "~1.0.2"
  }
}
```

**Comment by xiaogaozi** [comment]
For anyone use Yarn to build Docusaurus, you can force Yarn use specific version of `image-size` by add following lines to `package.json`:

```json
{
  "resolutions": {
    "image-size": "~1.0.2"
  }
}
```

**Comment by o-l-a-v** [comment]
Overriding `image-size` version made no change for me.

* SVG exported from Draw.io, works in Docusaurus but throws warning.
  * \> 2MB
* Docusaurus v3.5.2
* Yarn v4.5.0

**Comment by Josh-Cena** [comment]
This is probably an issue with https://github.com/image-size/image-size/issues/410. I'm closing because there are several workarounds proposed already.

**Comment by Zenahr** [comment]
> For anyone who use Yarn to build Docusaurus, you can force Yarn use specific version of `image-size` by add following lines to `package.json`:
> 
> {
>   "resolutions": {
>     "image-size": "~1.0.2"
>   }
> }

This worked for me.

**Comment by Airkro** [comment]
> Pin `image-size` to `v1.0.x` fix this:

Docusaurus v3.8 use `image-size@2.x`, so this way won't work any more! Now we stuck.

**Comment by slorber** [comment]
Please show a minimal repro on v3.8 where you are stuck and I'll look at either providing your a decent alternative solution or doing changes in Docusaurus to make sure you are not stuck.

I'll see if the lib author is interested to receive a PR, but the more SVG cases we have the more unit tests we'll be able to write so that the solution works well.

See also https://github.com/image-size/image-size/issues/397#issuecomment-2983386365

**Comment by tuunit** [comment]
We face the same problem for our official docs:

https://github.com/oauth2-proxy/oauth2-proxy/tree/master/docs
