### ISSUE TITLE
Docusaurus v3 markdown links don't resolve correctly from index pages during build step when trailingSlash is set to false

### ISSUE THREAD

**Issue by maxweisel** [facebook/docusaurus#9720]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

Hey all,

I've got a fresh docusaurus v3 project with trailingSlash set to false in the config, and I noticed that when it resolves relative links from markdown files, it does it incorrectly if the file is a readme.md file within a folder (acting as an index).

In short if you have the following docs folder structure:

docs/test/readme.md
docs/cool-page.md

and test/readme.md contains the following markdown:
```markdown
[Cool page](../cool-page.md)
```

running build will generate the following error:
```
  Exhaustive list of all broken links found:
  - Broken link on source page path = test:
     -> linking to ../cool-page (resolved as: /cool-page)
```

Despite the error saying it was resolved as `/cool-page` it is in fact not.

Interestingly, if I switch the link to `./cool-page` (removing the `../`). It works correctly. My guess is that rather than using the path of the readme.md file when resolving a relative path, it's using the location of the folder that contains it (in this case it assumes the links are coming from a file at the path `./test` instead of a file at `./test/readme.md`.

Max

### Reproducible demo

https://codesandbox.io/p/devbox/interesting-fog-kyv8rr?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clr5g3yir00073b6geabnge1d%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clr5g3yir00023b6gn47zxluy%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clr5g3yir00043b6g712r4ksj%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clr5g3yir00063b6g6ng8pbnq%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B100%252C0%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clr5g3yir00023b6gn47zxluy%2522%253A%257B%2522id%2522%253A%2522clr5g3yir00023b6gn47zxluy%2522%252C%2522activeTabId%2522%253A%2522clr5gchou00h53b6h51qjfj8w%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clr5g3yir00013b6g0dm8qqq7%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fnode_modules%252F%2522%252C%2522id%2522%253A%2522clr5gchou00h53b6h51qjfj8w%2522%252C%2522mode%2522%253A%2522temporary%2522%257D%255D%257D%252C%2522clr5g3yir00063b6g6ng8pbnq%2522%253A%257B%2522id%2522%253A%2522clr5g3yir00063b6g6ng8pbnq%2522%252C%2522activeTabId%2522%253A%2522clr5g6rh4009b3b6h1u88q2v6%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A3000%252C%2522id%2522%253A%2522clr5g6rh4009b3b6h1u88q2v6%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%255D%257D%252C%2522clr5g3yir00043b6g712r4ksj%2522%253A%257B%2522id%2522%253A%2522clr5g3yir00043b6g712r4ksj%2522%252C%2522activeTabId%2522%253A%2522clr5g5shr00373b6hus6jzymd%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clr5g3yir00033b6gmqrczx2l%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%257D%252C%257B%2522id%2522%253A%2522clr5g5shr00373b6hus6jzymd%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clr5g5sl0011feeehhq91gsxr%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Afalse%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D

### Steps to reproduce

run `npm run build` on the playground

### Expected behavior

It builds correctly without errors

### Actual behavior

  Exhaustive list of all broken links found:
  - Broken link on source page path = test:
     -> linking to ../cool-page (resolved as: /cool-page)

### Your environment

- Public source code:
- Public site URL:
- Docusaurus version used: v3.1.0
- Environment name and version (e.g. Chrome 89, Node.js 16.4): Node 18
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): macOS Sonoma

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by slorber** [comment]
> Despite the error saying it was resolved as /cool-page it is in fact not.

There is nothing at `/cool-page`. For your link to work, it must be resolved as `/docs/cool-page`. 

And trailingSlash has an impact on relative link resolution.

---


I'm sorry but your sandbox does not match your text description, which makes things confusing. Please try again by having the text and the sandbox being in sync.

For example your sandbox is using a relative path link (which we [don't recommend](https://docusaurus.io/docs/3.0.1/markdown-features/links) because it's sensitive to trailingSlash setting changes)


```md
[Cool page](../test2/cool-page)
```

While your text is using a relative reference to a markdown file

```md
[Cool page](../cool-page.md) 
```

Those 2 are not the same at all, and will not resolve the same.

**Comment by maxweisel** [comment]
The bug works the same regardless of the location of the page being linked. However, I've updated my repro to match the bug /exactly/.

**Comment by slorber** [comment]
I'm not sure if you expect me to do something, your sandbox now includes many other broken links due to removing other md files.

```
[Cool page](../cool-page)

[Cool page](../cool-page.md)
```

The 1st doesn't work, and it's expected because `../cool-page` resolved from `/docs/test` resolves as `/cool-page`, a path that does not exist

The 2nd work because it's resolved as `/test/cool-page`, that exists.

**Comment by maxweisel** [comment]
Try this version: https://codesandbox.io/p/devbox/staging-bird-y8p2mr

**Comment by maxweisel** [comment]
Here you go. Here's a fixed repo that matches the bug report exactly, and doesn't have any missing files: https://codesandbox.io/p/devbox/runtime-pine-84xm8d

`/docs/test/readme.md` has a relative link of `../cool-page` which I would expect to link to `/docs/cool-page.md`. However, Docusaurus resolves it to `/cool-page`. I believe this is broken because I would expect relative links to be resolved based on the location of the file they're being linked from, at least when it comes to markdown files.

When browsing these markdown files in a raw github repo, the Readme is rendered and relative links like this work correctly. If I fix them to match Docusaurus, they will break on github.

I understand that docusaurus is going to serve this markdown file as `my-project.com/docs/test` and if it were to pass the raw link through unmodified, that `../cool-page` would resolve to "my-project.com/cool-page", in that case I would expect it to correct the link. VuePress, which we're currently trying to switch off of, does exactly this.

I can appreciate the point of switching this to using `trailingSlash: true` to fix. However, then the inverse breaks. If `/docs/cool-page.md` tries to link to `./test/` (with or without the trailing slash), docusaurus resolves it as `./docs/cool-page/test/` because for some reason it considers `cool-page` to be a directory now. (I've added this link to the repro as well, if you change the trailingSlash` setting to `true` you can repro it.

This essentially means, the `trailingSlash` setting is unusable with relative paths. If it's set to `true`, relative paths do not work at all as every page is considered a directory, and if you set it to `false` you cannot link from `readme` files anywhere in your project.

**Comment by slorber** [comment]
Can confirm the bug, related to resolving relative file paths when using an image.

Can reproduce this on our own website:

```md
[text](./installation.mdx)

[![alt](/img/slash-introducing.svg)](./installation.mdx)
```

Only the first link resolves.

Definitively a bug. Track https://github.com/facebook/docusaurus/issues/9048 for the root cause and the solution. We can keep this issue closed.

**Comment by maxweisel** [comment]
Is it possible to work around this bug with an absolute path? By switching to an absolute path, I still get the same error. I've also tried an absolute path with no .md extension.

Max
