### ISSUE TITLE
Update to sumo-challenge.org works locally but not when published

### ISSUE THREAD

**Issue by JoelMarcey** [facebook/Docusaurus#973]
## 🐛 Bug Report

The sumo-challenge folks want to update their current website. But they are having problems. Their latest site is in `master`, but they cannot publish it. https://sumochallenge.org is still the old site.

Running the new, updated Docusaurus site for it locally works fine. When published as-is, it breaks with a continuous redirect.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes.

## To Reproduce

(Write your steps here:)

1. Clone https://github.com/facebookresearch/sumo-challenge
1. `cd website`
1. `yarn start` (to run site locally)
1. Run the publish script to publish to `gh-pages`
1. See problem (you may be able to see it if you just do a `yarn build` and run the site form the `build` directory).

## Expected behavior

Site works both locally and when published.

## Actual Behavior

![screenshot 2018-09-19 12 22 39](https://user-images.githubusercontent.com/3757713/45776175-f3264f80-bc06-11e8-893e-4aebb393e09f.png)

## Reproducible Demo

Run reproduce steps above.

See various attempts and reverts here: https://github.com/facebookresearch/sumo-challenge/commits/gh-pages

> I thought the issue is that the publish is not producing an `index.html` at root because in `pages/en` there is an `index.html` file, not an `index.js` file. But I tried moving all the files in `pages/en` to `static`, but the same problem happened.

**Comment by endiliey** [comment]
Caused due to incorrect site setup/ config
