### ISSUE TITLE
Please place the Docs & Blogs page into /src/pages (or a similar location in the src directory so that they are fully editable)

### ISSUE THREAD

**Issue by pmeaney** [facebook/docusaurus#9739]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Motivation

To create a new "Page" (https://docusaurus.io/docs/creating-pages) -- Place a new page file into the /src/pages directory.

Ok, well then, how about placing the "Docs" and "Blogs" pages into /src/pages or some other place within the /src directory where developers can easily edit them?  Or some other location within /src -- so that those two main components of a site are easily accessible and can be fully customized.

For example-- I want to edit those two pages in order to remove all references to Infima (an unpopular framework with only 387 github stars as of today) and add in our own classes-- such as of an actually popular CSS Framework (bulma (47k+ stars), bootstrap5 (166k+ stars), tailwind (75k+ stars), etc).  Why would I want to use Infima? I don't-- it was forced on me for no understandable reason except to give its market share a boost.

Please-- Reduce the magic.  Don't hide major components of a framework from developers.  All aspects of my Docusaurus project should be customizable, so that devs can reduce your poor system design choices (such as forcing us to use an unknown, unpopular css framework by default).

**Comment by slorber** [comment]
https://github.com/facebook/docusaurus/discussions/9735#discussioncomment-8136703
