### ISSUE TITLE
Dear all ,please allow me to leave a comment about Nodejs community management because I was blocked by nodejs (just because I mentioned a bug that they all admit to)

### ISSUE THREAD

**Issue by introspection3** [facebook/docusaurus#9764]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Motivation

LINK: [https://github.com/nodejs/node/issues/51507](https://github.com/nodejs/node/issues/51507)

![image](https://github.com/facebook/docusaurus/assets/12368358/571f584a-8586-4830-a713-a3e5c7fcc2b9)
![image](https://github.com/facebook/docusaurus/assets/12368358/819c3bfe-178d-4bdc-907f-2d703ea874e6)

### Self-service

- [ ] I'd be willing to do some initial work on this proposal myself.

**Comment by slorber** [comment]
We don't care about you being blocked, and don't approve your behavior either.

Stop annoying maintainers for no reason. 

This is unrelated to Docusaurus.
