### ISSUE TITLE
duplicate route detection with autogenerated slugs

### ISSUE THREAD

**Issue by ArthurFlag** [facebook/docusaurus#9780]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [ ] I have read the console error message carefully (if applicable).

### Description

I'm trying to diagnose a duplicated route warning, and I'm not sure what the problem is, I suspect it's a bug.

### Reproducible demo

https://codesandbox.io/p/devbox/pensive-neumann-8hhhvs

### Steps to reproduce

1. Create a file structure with similar file names, but in different folders. So different ids.

   ![Screenshot 2024-01-23 at 13 21 22](https://github.com/facebook/docusaurus/assets/28596581/fedc4d5f-18df-4658-a8f6-5ffc5e0f633d)

2. Add them in a TOC with the autogenerated instruction:

```
 {
      type: "category",
      label: "service",
      link: {
        id: "tools/cli/service",   // This is like the one below but that's a file.
        type: "doc",
      },
      items: [
        {
          type: "autogenerated",
          dirName: "tools/cli/service", // That's a directory, not a file.
        },
      ],
    },
```

3. Build and get a duplicated route warning:

```
[WARNING] Duplicate routes found!
- Attempting to create page at /docs/tools/cli/service, but a page already exists at this route.
This could lead to non-deterministic routing behavior.
```

In my case, there is only 1 file, or page, living there ([see repro](https://codesandbox.io/p/devbox/examples-classic-b9y9z)) but I do have a folder with the same path. 

### Expected behavior

I shouldn't see a warning, since there is no _file_ path duplication.  Only one page will be rendered at that location.

### Actual behavior

I get a duplicated route warning.

### Your environment

- Docusaurus version used: 3.1
- Environment name and version (e.g. Chrome 89, Node.js 16.4):
- Operating system and version (e.g. Ubuntu 20.04.2 LTS):

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by Josh-Cena** [comment]
Hi, `service/service.md` will also become `/service`. If you want to make its slug be `service/service`, you have to use the `slug` front matter. I'll add a sentence to the doc.

**Comment by muuki88** [comment]
Hi :smile: 

I have a smiliar issue with the typescript api docs plugin. It generates `modules.md` by default. I have a folder called `modules` where this is being generated. I tried to be smart and implemented a custom `isCategoryIndex` function like this

```js
async sidebarItemsGenerator({ defaultSidebarItemsGenerator, ...args }) {
  return defaultSidebarItemsGenerator({
    ...args,
    // by default docusaurus treats a file named as the parent directory as the index file as well, which
    // collides with the modules.md generated by the typescript API docs.
    // see https://docusaurus.io/docs/sidebar/autogenerated#category-index-convention
    isCategoryIndex({ fileName, directories }) {
      const eligibleDocIndexNames = ['index', 'readme'];
      return eligibleDocIndexNames.includes(fileName.toLowerCase());
    }
  });
}
```

as described here in the docs: https://docusaurus.io/docs/sidebar/autogenerated#category-index-convention

The function is working and the categorization as well. However the warning still exists. Is the warning generated independently from the `isCategoryIndex` function?

**Comment by slorber** [comment]
@muuki88 we are not the implementor of the typedoc plugin and don't really know how it works internally.

Note that there are 2 things to be aware of:
- The category index convention defines if clicking the sidebar category links to the doc
- The category index convention does not affect the doc URL


If you want to alter the doc URL, you can use the `slug` front matter.

If the typedoc plugin does not enable you to inject a slug front matter, you can try to make an exception with the `parseFrontMatter` hook: https://docusaurus.io/docs/markdown-features#front-matter

**Comment by muuki88** [comment]
Hi @slorber 

Thanks for the quick and detailed reply :heart: Makes sense if both are still competing for the same URL. Seems I didn't fully  comprehend what the `isCategoryIndex` function does :see_no_evil: 

I'll move the discussion to the typedoc-plugin-markdown forum. Should be possible to customize either the `modules.md` filename or inject custom fontmatter meta data.

**Comment by slorber** [comment]
Sure 👍 

Note that `parseFrontMatter` is a core feature, so technically you can still use it to inject custom front matter in other plugins that use our mdx loader. I think that typedoc plugin is "reusing" our docs plugin so it qualifies too.
