### ISSUE TITLE
Generated Sidebar Pagination will not use doc Label but the File Name

### ISSUE THREAD

**Issue by LeonnardoVerol** [facebook/docusaurus#9781]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [ ] I have tried the `npm run clear` or `yarn clear` command.
- [ ] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

When generating pagination from the sidebar, the "Next" and "Previous" Cards will ignore the doc label and default to the file name. (when the doc has no H1 or Title property)

```
{
	type: 'doc',
	label: 'Quick Start',
	id: 'some_example_doc',
}
```

### Steps to reproduce

1. Create a doc without H1 or Title
2. Set the sidebar manually with the label property

### Expected behavior

The generated Pagination would use the label property from the sidebar and not the file name

### Actual behavior

The generated Pagination ignores the label property from the sidebar and uses the file name

### Your environment

- Docusaurus version used: 3.1.0
- Environment name and version (e.g. Chrome 89, Node.js 16.4): Chrome 120
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): Windows 11 Pro (Version	10.0.22631 Build 22631 )

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by Josh-Cena** [comment]
Yes, something is wrong here. https://github.com/facebook/docusaurus/blob/cd0e60841778216613cae75bfda3169397fb7f07/packages/docusaurus-plugin-content-docs/src/sidebars/utils.ts#L481-L491
Our doc navlink transform logic only takes into account the explicit `sidebar_label` front matter, but not the sidebar label acquired from the explicit sidebar label config. We need to fetch it from the `SidebarNavigationItem` we already calculated beforehand.

**Comment by ShubhamPatilsd** [comment]
our students from https://labs.codeday.org/ will be taking a shot at this issue in the coming week :) (they'll be making their first contributions to break into the world of open source)

**Comment by slorber** [comment]
> our students from [labs.codeday.org](https://labs.codeday.org) will be taking a shot at this issue in the coming week :) (they'll be making their first contributions to break into the world of open source)

You seem to copy-paste this message on a few issues (ex: https://github.com/facebook/docusaurus/issues/9904#issuecomment-1975267839), so I'm assuming it's a regular practice of your school.

This is no doubt well-intentioned, but in practice harmful for open-source projects.

Students should not try to "break into the world of open source" by contributing random fixes to random projects they don't even use. 

Make sure to watch this video and forward it to your students: https://www.youtube.com/watch?v=5nY_cy8zcO4

If your students want to contribute to Docusaurus, I'd suggest that they build their portfolio/blog on it and use it for at least a few months as regular Docusaurus users before even attempting to contribute to it. Their first contribution should rather be about a pain point they understand and encounter.

**Comment by tylermenezes** [comment]
Hi @slorber, I am in charge of CodeDay Labs and wanted to apologize for surprising you with this, and thank you for your feedback. We will obviously not assign any students if they are not welcome.

I've seen Theo's video before, and I think it's a valuable perspective. I've been an open source contributor and (small) maintainer for a decade and agree with many of the points for many people, especially in light of things like Hactoberfest, but I don't think it applies to everyone in all situations. We work with about 2,000 students a year who are studying CS at under-resourced colleges looking for a way to start to build real-world skills outside the classroom, but a lot of the OSS they already use is too complex for that many students to make contributions. We do make sure the students start out by understanding how the software is actually used by end-users and what impact the bug makes; ultimately about half of the students keep contributing to the same project afterward.

Anyway, thank you for sharing your perspective and I apologize again for the surprise message. We will not include any students in this project and will make sure this is communicated more clearly and as an ask to other projects in the future.

**Comment by Abdullah-03** [comment]
This should be the order of precedence, correct? Explicitly declared label should have higher priority over front matter.

```js
title: paginationLabel ?? sidebarConfigLabel ?? sidebarLabel ?? title
```

**Comment by Abdullah-03** [comment]
side bar label in front matter takes precedence.
