### ISSUE TITLE
Swizzle of MDXComponents/Img is not working under v3.1

### ISSUE THREAD

**Issue by hendrikhelmer** [facebook/docusaurus#9789]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

Since docusaurus v3 swizzle of the MDXComponents/Img does not work as bevor. The swizzle seems to not have any effect on the <img> used inside a mdx file and the original <img> tag gets rendered. When using docusaurus version 2.4.1 the swizzle works as expected but not in version v3.1.
When creating a new docusaurus project by "npx create-docusaurus@latest my-website classic" and swizzle the MDXComponents/Img by "yarn swizzle @docusaurus/theme-classic MDXComponents/Img" and than chosses "wrap" the component does not work. I have tested this with logging any manipulating the return of the component. For other compoents like "DocsVersionBanner" it still works like a charm.

### Reproducible demo

https://codesandbox.io/p/devbox/dank-darkness-mfcfy5?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clrrn3lp20007356e2yvcepz7%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clrrn3lp10002356e1n1fjcbh%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clrrn3lp10004356eceir5b0r%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clrrn3lp20006356ekrci2vv5%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clrrn3lp10002356e1n1fjcbh%2522%253A%257B%2522id%2522%253A%2522clrrn3lp10002356e1n1fjcbh%2522%252C%2522activeTabId%2522%253A%2522clrtg32yg00uo356d5oxne5ju%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clrrn3lp10001356eifc34fhd%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Ftheme%252FDocVersionBanner%252Findex.js%2522%252C%2522id%2522%253A%2522clrtg32yg00uo356d5oxne5ju%2522%252C%2522mode%2522%253A%2522temporary%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%257D%252C%2522clrrn3lp20006356ekrci2vv5%2522%253A%257B%2522id%2522%253A%2522clrrn3lp20006356ekrci2vv5%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A3000%252C%2522id%2522%253A%2522clrtg3lzm00xa356d33wgoikh%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clrtg3lzm00xa356d33wgoikh%2522%257D%252C%2522clrrn3lp10004356eceir5b0r%2522%253A%257B%2522id%2522%253A%2522clrrn3lp10004356eceir5b0r%2522%252C%2522activeTabId%2522%253A%2522clrtg03x200p3356dizln0a6d%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clrtg03x200p3356dizln0a6d%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clrtg03xz08nfeheh7g0vasaw%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D

### Steps to reproduce

1. Step: Create new docusaurus project by: npx create-docusaurus@latest my-website classic
2. Step: Swizzle the Img component by: yarn swizzle @docusaurus/theme-classic MDXComponents/Img
3. Step: Select wrap
4. Step: Manipulate the swizzled componed e.g. by adding a console.log() or changing the return value of the component
5. Step: Nothing will happen but the original img component gets rendered.

Alternativ:
Open the link from codesandbox provided above and navigate to the Introduction page. When inspecting the elements you can see that the swizzle did not work. Also the console.log is working for the swizzled "DocsVersionBanner" but not for the "Img".

### Expected behavior

The swizzled component should be used instead of the original one just like it does when swizzling for example the DocsVersionBanner.

### Actual behavior

The original <img> tag will be used.

### Your environment

- Public source code: codesandbox link from above
- Public site URL:
- Docusaurus version used: v3.1
- Environment name and version (e.g. Chrome 89, Node.js 16.4): Node.js 18
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): codesandbox

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by slorber** [comment]
Your issue is not super clear, so I'm going to clarify it.

You are using this tag in your Markdown content:

```md
## Heading

<img src={testImg} />
```

As far as I understand you expect `MDXComponents/Img` to be the component used to render it.

In practice it is not the case, right?

---

This is working as intended and is a MDX v2 breaking change, documented on our migration guide + the MDX docs/changelog.

We have documented this here:
https://docusaurus.io/docs/migration/v3#lower-case-mdxcomponent-mapping

<img width="993" alt="CleanShot 2024-01-25 at 19 41 26@2x" src="https://github.com/facebook/docusaurus/assets/749374/d57b80f1-7c45-4e31-b0de-219c8201674a">


If you provide a MDX component with key `img`, it will now only be used to render Markdown images (`![alt](src)`), and not anymore `<img>` tags.

However if you provided a mapping for `Img`, you would be able to write `<img src={testImg} />`

Upper-case and lower-case components are now treated differently by MDX, on purpose.

This is briefly documented [here](https://mdxjs.com/migrating/v2/) as a breaking change of MDX v2:

> We now “sandbox” components, for lack of a better name. It means that when you pass a component for h1, it does get used for # hi but not for <h1>hi</h1>

---

Note: technically if you care about restoring the former MDX behavior, you can do it by writing a remark plugin to process the lowercase tag and upper-casing it.

An example:

```ts
import type {Transformer} from 'unified';
import type {MdxJsxFlowElement} from 'mdast-util-mdx';

export default function plugin(): Transformer {
  return async (root) => {
    const {visit} = await import('unist-util-visit');
    visit(root, 'mdxJsxFlowElement', (node: MdxJsxFlowElement) => {
      if (node.name === 'img') {
        node.name = 'Img';
      }
    });
  };
}
```

This is not standard MDX v2+ anymore so it's now your responsibility to figure out if this is a good idea or not.

**Comment by t1m0thyj** [comment]
@slorber Thanks for providing guidance on how to migrate `img` components in Docusaurus v3.

> However if you provided a mapping for `Img`, you would be able to write `<img src={testImg} />`

By "providing a mapping", do you mean the following?
```
export default {
  ...MDXComponents,
  img: MyCustomImageComponent,
  Img: MyCustomImageComponent,
}
```

I expected this would register my custom image component for both Markdown images and the `img` tag. But it didn't work for the `img` tag until I added the Remark plugin that you suggested. So I have a workaround but am wondering if I'm missing something related to the mapping?

**Comment by slorber** [comment]
@t1m0thyj i explained above that indeed the remark plugin is required.

That lowercase mapping will only work with md image syntax, not img tags.

That's not Docusaurus, that's how MDX v2+ works
