### ISSUE TITLE
Live reload sidebars.json

### ISSUE THREAD

**Issue by huguestennier** [facebook/Docusaurus#981]
## 🐛 Bug Report

Live reload is working fine for `.md`s, but is it possible to make it work with `sidebars.json` ? 

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yep

## To Reproduce

1. Run `yarn start`
2. Update `sidebars.json`

## Expected behavior

I want the page to reload - not have to stop and run `yarn start` again each time i'm updating `sidebars.json`

## Actual Behavior

Nothing happens

**Comment by yangshun** [comment]
I agree this is something we should have, but I think making this work is not that easy. PRs are welcome!

**Comment by sibelius** [comment]
can we backport this to v1?
