### ISSUE TITLE
Links to feeds became detected as broken in `3.1.0`

### ISSUE THREAD

**Issue by Zwyx** [facebook/docusaurus#9813]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io.
- [ ] I have read the console error message carefully (if applicable).

### Description

My blog's home page contains links to the feed files:

```
[rss](/blog/rss.xml)   [atom](/blog/atom.xml)   [json](/blog/feed.json)
```

![image](https://github.com/facebook/docusaurus/assets/29386932/3d00fe46-938d-43fa-bc6c-d6fd82c95de8)

Until Docusaurus `3.0.0`, the site was built successfully, but starting in `3.1.0`, this error happens:

```
  [cause]: Error: Docusaurus found broken links!
 
  Exhaustive list of all broken links found:
  - Broken link on source page path = /:
     -> linking to /blog/rss.xml
     -> linking to /blog/atom.xml
     -> linking to /blog/feed.json
```

### Reproducible demo

https://github.com/Zwyx/zwyx.dev

### Steps to reproduce

In https://github.com/Zwyx/zwyx.dev, the branch `main` builds correctly, the branch `update-docusaurus` doesn't.

### Expected behavior

Links to feed files shouldn't be detected as broken.

### Actual behavior

Links to feed files are detected as broken.

### Your environment

- Public source code: https://github.com/Zwyx/zwyx.dev
- Public site URL: https://zwyx.dev
- Docusaurus version used: live site: `3.0.0`, `update-docusaurus` branch: `3.1.1`
- Environment name and version (e.g. Chrome 89, Node.js 16.4): N/A
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): N/A

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by slorber** [comment]
This is the same problem as the one described here: https://github.com/facebook/docusaurus/issues/9803

You do have broken links if you click on the RSS feed link (without middle click, do not open the feed in new tabs)

![CleanShot 2024-02-01 at 15 11 43](https://github.com/facebook/docusaurus/assets/749374/32a72391-2b5a-4685-9e2e-3d32c2b48a45)

You should use the `pathname://` protocol to link to any page or resource that is not an SPA route known by Docusaurus. Otherwise it won't work when navigating that link.

**Comment by Zwyx** [comment]
I can't believe I never noticed these links were broken :facepalm: I've always middle-clicked them...

Thank you very much and apologises for this silly mistake.

**Comment by slorber** [comment]
That's our fault, we should have told you 😄
