### ISSUE TITLE
How get tags of docs

### ISSUE THREAD

**Issue by starryskyhk** [facebook/docusaurus#9814]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Description

Hi Team,
I want to create a docs tags page. but I don't know how to get docs pages.
And I would like to see tags in the docs file. like blog

### Motivation

I think many people need docs tags feeature

### Self-service

- [X] I'd be willing to contribute this feature to Docusaurus myself.

**Comment by slorber** [comment]
Docs tags are already supported, and documented: https://docusaurus.io/docs/create-doc#doc-tags

Feature requests are not for vague wishes: you have to respect our template and create a real proposal, requiring you to spend time on it. This issue is low-effort on your side so I'm closing.
