### ISSUE TITLE
<CodeBlock /> with mermaid

### ISSUE THREAD

**Issue by Its-Just-Nans** [facebook/docusaurus#9815]
## Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

## Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

Hello,

With a normal mermaid config, this code is not rendering the mermaid graph (see repro link below)

```
import CodeBlock from '@theme/CodeBlock';
<CodeBlock language="mermaid">
{`graph TD;
    A-->B;
    A-->C;
    B-->D;
    C-->D;
`}
</CodeBlock>
```

The actual mermaid graph example:

```mermaid
graph TD;
    A-->B;
    A-->C;
    B-->D;
    C-->D;
```

https://docusaurus.io/docs/markdown-features/diagrams

Docs says

`Diagrams can be rendered using [Mermaid](https://mermaid-js.github.io/mermaid/) in a code block.`

but apparently not in <CodeBlock/> :/

## Reproducible demo

https://codesandbox.io/p/devbox/divine-framework-99ytrv

## Steps to reproduce

copy this in a docusaurus with mermaid

```
import CodeBlock from '@theme/CodeBlock';

<CodeBlock language="mermaid">
{`graph TD;
    A-->B;
    A-->C;
    B-->D;
    C-->D;
`}
</CodeBlock>
```

## Expected behavior

Render the graph using mermaid

## Actual behavior

It shows a basic code block like

```
graph TD;
    A-->B;
    A-->C;
    B-->D;
    C-->D;
```

## Self-service

- [ ] I'd be willing to fix this bug myself. (I don't know docusaurus so much)

**Comment by slorber** [comment]
> Diagrams can be rendered using [Mermaid](https://mermaid-js.github.io/mermaid/) in a code block.

This is written in the Markdown features section, which implicitly means "markdown code block", not `<CodeBlock/>`.


`<CodeBlock>` is a component to render a code block, which Mermaid diagrams are not, because we don't display a syntax highlighted version of the diagram spec, but the actual diagram instead.

The component you are looking for is more likely this one, which takes a diagram spec a children, and renders an actual diagram.

```jsx
import Mermaid from '@theme/Mermaid';
```

**Comment by Its-Just-Nans** [comment]
@slorber More likely from `value` props : https://github.com/facebook/docusaurus/blob/c1ac06768bd3cb997c11931209a97e8c9574c11d/packages/docusaurus-theme-mermaid/src/theme/Mermaid/index.tsx#L43C10-L43C25

Made a PR for docs : https://github.com/facebook/docusaurus/pull/9816
