### ISSUE TITLE
`### Error` cannot render correctly

### ISSUE THREAD

**Issue by impossible98** [facebook/docusaurus#9817]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [ ] I have tried the `npm run clear` or `yarn clear` command.
- [ ] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io.
- [ ] I have read the console error message carefully (if applicable).

### Description

`### Error` cannot render correctly

I write `### Error` in markdown, it cannot render correctly in html

preview: https://gostd.impossible98.win/syscall/js#error

### Steps to reproduce

None

### Expected behavior

None

### Actual behavior

None

### Your environment

- Public source code:
- Public site URL:
- Docusaurus version used:
- Environment name and version (e.g. Chrome 89, Node.js 16.4):
- Operating system and version (e.g. Ubuntu 20.04.2 LTS):

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by Josh-Cena** [comment]
What isn't correct?

**Comment by impossible98** [comment]
> What isn't correct?

error maybe extension,sorry
