### ISSUE TITLE
Code block with language tabs

### ISSUE THREAD

**Issue by hsluoyz** [facebook/Docusaurus#982]
## 🚀 Feature

Code block with language tabs

## Have you read the [Contributing Guidelines on issues](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## Motivation

[My project](https://casbin.org/) is a library. It supports four languages: Golang, Java, PHP and Node.js. So I need to show code in multiple languages in my documentation.

## Pitch

I already noticed the discussion here: https://github.com/facebook/Docusaurus/issues/103. But it seems to be a little hacky. I still want to know if there's any official decision on this feature or other third-party recommendations? Thanks.

**Comment by endiliey** [comment]
There is the problem of syntax though. How do we divine code block with language tabs ? :o

**Comment by hsluoyz** [comment]
A way to do it is to extend the markdown grammar to support it. Like said [here](https://github.com/facebook/Docusaurus/issues/103#issuecomment-398252765), the text of the code block should be self-contained in the markdown instead of using external files. Then maybe we need to patch the markdown parser to support this new grammar. Javascript is then used to render it.

However, modifying markdown grammer is not always good. Another way is to put a placeholder like a reserved label ``<docusaurus-code-block-1>`` in markdown. Then define the code block #1 and its text in external files. The markdown parser won't need to be changed. Javascript can replace the label with actual code block controls in the HTML layer.

**Comment by hsluoyz** [comment]
Hi, any update on this issue? @endiliey  @yangshun 

GitBook and readthedocs already support this feature:

1. GitBook: https://github.com/GitbookIO/plugin-codetabs

![image](https://user-images.githubusercontent.com/3787410/47021726-94fd7580-d18e-11e8-810d-d50b1e73a5c6.png)


2. readthedocs: https://sphinxcontrib-contentui.readthedocs.io/en/latest/tabs.html

![image](https://user-images.githubusercontent.com/3787410/47021758-a34b9180-d18e-11e8-8dd6-439cdca83fb8.png)

**Comment by JoelMarcey** [comment]
@hsluoyz - we have a [pull request in review](https://github.com/facebook/Docusaurus/pull/946) that can add tabbing to a docs page. I imagine we could repurpose the final version of that to do something similar to what is being asked for here.

**Comment by JoelMarcey** [comment]
@hsluoyz Also see #103 - as part of that, we are looking to adding code tabs too.

**Comment by hsluoyz** [comment]
@JoelMarcey  Thanks!

Never thought the PR will be so fast! We are really looking forward to this feature! I will test it first when the feature is ready :)

**Comment by endiliey** [comment]
#1063 might be a better option.

**Comment by hsluoyz** [comment]
Thanks for the status update! This PR is really amazing! Cannot wait to try it :) @fiennyangeln @endiliey

**Comment by amimas** [comment]
I believe tabbed code block is now supported on latest version

**Comment by hsluoyz** [comment]
I will try it ASAP, close it now.
