### ISSUE TITLE
Hide redundant year in dates shown in the Archive page

### ISSUE THREAD

**Issue by ilg-ul** [facebook/docusaurus#9830]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Description

In the Archive page, when listing the the post titles grouped by years, there is not need to show the year again, since it is redundant.

![hide-year](https://github.com/facebook/docusaurus/assets/362732/39792b83-fe29-4bfa-a009-2e1db8ad2c95)

### Has this been requested on Canny?

No.

### Motivation

Mainly for aesthetic reasons, since the year is already shown as a section title, and repeating it in each subsequent entry is redundant.

### API design

To control this new feature add a  `hidePostYearInArchive` option.

### Have you tried building it?

The functionality is implemented in https://github.com/cronica-it/docusaurus-chronology/commit/0da5a7d311590827beb77f501cf9a3f1300882d7.

### Self-service

- [X] I'd be willing to contribute this feature to Docusaurus myself.

**Comment by slorber** [comment]
👍 looks like a good change

Not sure about the proposed solution though, adding an option does not seem to be ideal considering it's a reasonable default and user can swizzle.

IMHO we should move this function to theme-common instead of having a `blogPost.metadata.formattedDate`.

```js
function formatBlogPostDate(
  locale: string,
  date: Date,
  calendar: string,
): string {
  try {
    return new Intl.DateTimeFormat(locale, {
      day: 'numeric',
      month: 'long',
      year: 'numeric',
      timeZone: 'UTC',
      calendar,
    }).format(date);
  } catch (err) {
    logger.error`Can't format blog post date "${String(date)}"`;
    throw err;
  }
}
```

**Comment by ilg-ul** [comment]
> adding an option does not seem to be ideal considering it's a reasonable default and user can swizzle

I'm not sure I understand your proposal, do you mean to make the default hide the year? 

If so, that's fine with me, I used options everywhere exactly because I wanted to preserve compatibility with the current behaviour, but this might not be the best solution.

**Comment by slorber** [comment]
Yes, the year is already displayed above so it's fine to not add it again on every single line IMHO.

If the formatting of the date is in the React code (instead of Node), users who do not like this change could revert with swizzle, so it's not risky to ship.

**Comment by ilg-ul** [comment]
> it's fine to not add it again on every single line

Ok, agree.

> ... formatting of the date is in the React code ...

I guess this is possible, but probably requires another hook to accommodate for special formatting cases.

In my case, when using event dates with partial content, for example only the year, the formatted date is empty, and the post title should be rendered at the beginning of the line; similarly, event dates with year and month only (no day), should have only the month name shown before the title.

So, regardless of the solution, if it can accommodate custom front matter properties like my event dates, it'll probably be ok.

**Comment by slorber** [comment]
IMHO we'd rather first introduce the ability to have "social icons" next to the author's name, similar to what many blogs do:

https://web.dev/blog/array-with

![CleanShot 2024-02-09 at 12 10 56](https://github.com/facebook/docusaurus/assets/749374/15b50e0e-40d9-4bc2-aeb7-ba9ac41c8791)

This would enable us to be able to click on the author's name to access the author page and see a paginated list of posts for each author.

Some other examples of sites having author pages:
- https://www.smashingmagazine.com/author/geoff-graham/
- https://css-tricks.com/author/chriscoyier/

**Comment by slorber** [comment]
> I guess this is possible, but probably requires another hook to accommodate for special formatting cases.

If the formatting is done on the React code, someone that wants to format the date differently can simply swizzle our code.

We'd likely expose a `theme-common` blog date formatting helper, that we would use in date components. However, the user remain free to swizzle and use their own code to format the dates if they don't like the defaults we provide.

If you swizzle the archive page, you can render the blog posts the way you want (including dates), and also re-order them and group them the way you want, using official metadata or custom front matter. So technically nothing is impossible as long as you have access to the data you need here, which is already the case.

**Comment by slorber** [comment]
Thank @OzakIOne :)

Now you can swizzle the blog archive component and choose how to format the date yourself

**Comment by ilg-ul** [comment]
Thank you both, @OzakIOne and @slorber !

> Now you can swizzle the blog archive component and choose how to format the date yourself

Sure. I'll wait for the other issues to be closed (especially the lastUpdateTime for blogs and Authors pages), and then I'll try to rework my site. If I'll no longer need the fork, I'll consider it a success.
