### ISSUE TITLE
Error when importing Docusaurus Swizzle component into Netlify CMS

### ISSUE THREAD

**Issue by niravbhuva99** [facebook/docusaurus#9833]
### Have you read the Contributing Guidelines on issues?

- [x] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Prerequisites

- [ ] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

## Description

I am encountering an error when attempting to import a Docusaurus Swizzle component into Netlify CMS. For each Docusaurus client API component used within the Swizzle component, Webpack throws an error.

### Swizzle Component

![Screenshot of Swizzle component](https://github.com/facebook/docusaurus/assets/91559189/bd7fa3f6-391e-44ab-a114-813d1e9a473f)

### Error Example

When including a Docusaurus component such as `Link` within the Swizzle component, Webpack throws the following error:

![Webpack error](https://github.com/facebook/docusaurus/assets/91559189/b7e25a39-d5a9-4ceb-bc96-5d738df54a57)

### Dependencies Structure

Here is the structure of the `node_modules` directory for Docusaurus and its dependencies:

![Screenshot 2024-02-08 at 11 06 26](https://github.com/facebook/docusaurus/assets/91559189/3e28c8d3-741a-4804-b65f-1c168fc4893b)

## Steps to Reproduce:
1. Create a Docusaurus app.
2. Add Netlify CMS to the Docusaurus app.
4. Import Docusaurus components such as `Link` into the Swizzle component.
5. Run Webpack to compile the project.

### Expected behavior

the project should compile successfully without any errors from Webpack. Specifically, Webpack should be able to resolve and import Docusaurus components such as `Link` within the Swizzle component without encountering any issues.

### Actual behavior

![Screenshot 2024-02-08 at 11 00 00](https://github.com/facebook/docusaurus/assets/91559189/25261946-9e83-423f-a665-4ae8ac737936)

### Your environment

- Public source code: No
- Public site URL:No
- Docusaurus version used:2.4.1

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by slorber** [comment]
Please provide a minimal docusaurus.new repro, and use the latest version of Docusaurus. If you do that and can see a bug, we'll reopen.
