### ISSUE TITLE
MDX fails building website when using a <code> inside of a <TabItem> element

### ISSUE THREAD

**Issue by GeekCornerGH** [facebook/docusaurus#9835]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

MDX will fail building website when using a <code> inside of a <TabItem> element

### Steps to reproduce

1. Create a MDX file (or use [mine](https://github.com/GeekCornerGH/docs/blob/2025331636c17a5d439eaa06ecaee455b24a3cda/i18n/en/docusaurus-plugin-content-docs/version-Helios/p1.mdx) for example) where a <code> block exists inside of a <Tab> element.
2. Upgrade it to Docusaurus v3
3. Build your docusaurus website
4. See it crash 

### Expected behavior

Build would pass

### Actual behavior

```
Error:  Client bundle compiled with errors therefore further build is impossible.
Error: MDX compilation failed for file "/home/runner/work/docs/docs/versioned_docs/version-Helios/p1.mdx"
Cause: Expected the closing tag `</code>` either after the end of `strikethrough` (187:45) or another opening tag after the start of `strikethrough` (186:[44](https://github.com/GeekCornerGH/docs/actions/runs/7827811239/job/21356406238#step:8:45))
Details:
{
  "column": 89,
  "message": "Expected the closing tag `</code>` either after the end of `strikethrough` (187:[45](https://github.com/GeekCornerGH/docs/actions/runs/7827811239/job/21356406238#step:8:46)) or another opening tag after the start of `strikethrough` (186:44)",
  "line": 186,
  "name": "186:89-186:96",
  "place": {
    "start": {
      "line": 186,
      "column": 89,
      "offset": 8892,
      "_index": 2,
      "_bufferIndex": 88
    },
    "end": {
      "line": 186,
      "column": 96,
      "offset": 8899,
      "_index": 2,
      "_bufferIndex": 95
    }
  },
  "reason": "Expected the closing tag `</code>` either after the end of `strikethrough` (187:45) or another opening tag after the start of `strikethrough` (186:44)",
  "ruleId": "end-tag-mismatch",
  "source": "mdast-util-mdx-jsx"
}
 ELIFECYCLE  Command failed with exit code 1.
 ```
[Whole log](https://github.com/GeekCornerGH/docs/actions/runs/7827991819/job/21356951248)

### Your environment

- Public source code: https://github.com/geekcornergh/docs
- Public site URL: https://docs.geekcorner.eu.org
- Docusaurus version used: Working version: 2.4.3, trying to upgrade to 3.1.1
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): GitHub Actions with ubuntu-latest

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by OzakIOne** [comment]
Can you create a minimal repro on stackblitz or codesandbox using https://docusaurus.new/ and fix your issue description it would help us a lot to resolve your error

**Comment by slorber** [comment]
It is not a Docusaurus issue, but a behavior of dependencies we rely on. 

The following does not compile with MDX v3 + GFM plugin:

```mdx
### Changer le dossier de données du launcher

<TabItem value="linux" label="Linux"><code>~/.helioslauncher</code></TabItem>
<TabItem value="linux" label="Linux"><code>~/.helioslauncher</code></TabItem>
```

![CleanShot 2024-02-08 at 15 48 57](https://github.com/facebook/docusaurus/assets/749374/df57de7b-ab55-42c2-abe2-949056ee1f56)

If you think there's a bug, you should report it to the MDX or GFM plugin directly. I'm not sure there is a bug in those dependencies either though. Adding a line break between the 2 tags makes it compile.

Note that `~` has a special meaning for GFM and enables `~strikethrough~`: ~strikethrough~

**Comment by GeekCornerGH** [comment]
Thank you for the help, I wasn't expecting it to be a special character, thanks for the help
