### ISSUE TITLE
MDX v3.0.1 fails to import <details>

### ISSUE THREAD

**Issue by rainecheck** [facebook/docusaurus#9844]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

> Error: Docusaurus server-side rendering could not render static page with path /docs/tutorial-basics/markdown-features because of error: Expected component `Details` to be defined: you likely forgot to import, pass, or provide it.

Error occurs with fresh Docusaurus install, with update to MDX v3.0.1 and a `<details>` block inserted into an MDX file.
`yarn start` succeeds until you browse to the MDX page in question, where it crashes with the full error text.

### Reproducible demo

https://codesandbox.io/p/sandbox/small-moon-glqp55

### Steps to reproduce

`yarn && yarn clear && yarn build`

### Expected behavior

<details> block rendered successfully.

### Actual behavior

```
Uncaught runtime errors:
ERROR
Expected component `Details` to be defined: you likely forgot to import, pass, or provide it.
_missingMdxReference@webpack-internal:///./docs/tutorial-basics/markdown-features.mdx:277:9
_createMdxContent@webpack-internal:///./docs/tutorial-basics/markdown-features.mdx:110:37
MDXContent@webpack-internal:///./docs/tutorial-basics/markdown-features.mdx:274:8
renderWithHooks@webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:16305:27
mountIndeterminateComponent@webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:20069:13
beginWork@webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:21582:16
callCallback@webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:4164:14
invokeGuardedCallbackDev@webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:4213:16
invokeGuardedCallback@webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:4277:31
beginWork$1@webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:27446:28
performUnitOfWork@webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:26552:12
workLoopSync@webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:26461:22
renderRootSync@webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:26429:7
performSyncWorkOnRoot@webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:26080:34
flushSyncCallbacks@webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:12042:22
ensureRootIsScheduled/<@webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:25646:13
ERROR
Expected component `Details` to be defined: you likely forgot to import, pass, or provide it.
_missingMdxReference@webpack-internal:///./docs/tutorial-basics/markdown-features.mdx:277:9
_createMdxContent@webpack-internal:///./docs/tutorial-basics/markdown-features.mdx:110:37
MDXContent@webpack-internal:///./docs/tutorial-basics/markdown-features.mdx:274:8
renderWithHooks@webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:16305:27
mountIndeterminateComponent@webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:20069:13
beginWork@webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:21582:16
callCallback@webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:4164:14
invokeGuardedCallbackDev@webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:4213:16
invokeGuardedCallback@webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:4277:31
beginWork$1@webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:27446:28
performUnitOfWork@webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:26552:12
workLoopSync@webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:26461:22
renderRootSync@webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:26429:7
performSyncWorkOnRoot@webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:26080:34
flushSyncCallbacks@webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:12042:22
ensureRootIsScheduled/<@webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:25646:13
ERROR
Expected component `Details` to be defined: you likely forgot to import, pass, or provide it.
_missingMdxReference@webpack-internal:///./docs/tutorial-basics/markdown-features.mdx:277:9
_createMdxContent@webpack-internal:///./docs/tutorial-basics/markdown-features.mdx:110:37
MDXContent@webpack-internal:///./docs/tutorial-basics/markdown-features.mdx:274:8
renderWithHooks@webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:16305:27
mountIndeterminateComponent@webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:20069:13
beginWork@webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:21582:16
callCallback@webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:4164:14
invokeGuardedCallbackDev@webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:4213:16
invokeGuardedCallback@webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:4277:31
beginWork$1@webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:27446:28
performUnitOfWork@webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:26552:12
workLoopSync@webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:26461:22
renderRootSync@webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:26429:7
recoverFromConcurrentError@webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:25845:34
performSyncWorkOnRoot@webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:26091:20
flushSyncCallbacks@webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:12042:22
ensureRootIsScheduled/<@webpack-internal:/
```

### Your environment

- Public source code: https://codesandbox.io/p/sandbox/small-moon-glqp55
- Public site URL: https://codesandbox.io/p/sandbox/small-moon-glqp55
- Docusaurus version used: 3.1.1
- Environment name and version (e.g. Chrome 89, Node.js 16.4): docusaurus.new
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): docusaurus.new

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by OzakIOne** [comment]
![image](https://github.com/facebook/docusaurus/assets/29860391/0a0091fa-9781-4068-8118-c455ba393f8d)

Can't access the sandbox

**Comment by slorber** [comment]
Closing until an accessible runnable repro is provided

Also please be clear, are you using 3.0.1 or 3.1.1? Your bug report mentions 2 distinct versions.

---

Here's a runnable repro showing it works fine:

https://stackblitz.com/edit/github-mpdvw3?file=docs%2Ftutorial-basics%2Fmarkdown-features.mdx

```mdx
---
sidebar_position: 4
---

# Markdown Features

<details>test1</details>

<details>test2</details>

<details>
  <summary>summary test 3</summary>

test 3

</details>

<Details>test4</Details>

<Details>
  <summary>summary test 5</summary>

test5

</Details>
```

![CleanShot 2024-02-13 at 13 06 01](https://github.com/facebook/docusaurus/assets/749374/fd717fb1-ab41-4b03-8b1e-895d9073c70b)

**Comment by rainecheck** [comment]
Code sandbox should now be publicly accessible, apologies.
Docusaurus is at 3.1.1, @mdx-js/react is at 3.0.1.
Works fine with mdx-js at 3.0.0, but breaks at 3.0.1.

> Closing until an accessible runnable repro is provided
> 
> Also please be clear, are you using 3.0.1 or 3.1.1? Your bug report mentions 2 distinct versions.

**Comment by OzakIOne** [comment]
I've take a look at the problem, from what I've understood

No error initially with version 3.0.0, if you try to upgrade to 3.0.1 without clearing docusaurus and yarn cache you'll get an error, if you clear the cache and build again, no more error

**Comment by slorber** [comment]
This issue is very likely because you have twice the `@mdx-js/react` dependency in your `node_modules`. Similarly to React, having duplicates will lead to troubles 😅 .

We can see in the codesandbox repro:

```
"@mdx-js/react@^3.0.0":
  version "3.0.0"
  resolved "https://registry.yarnpkg.com/@mdx-js/react/-/react-3.0.0.tgz#eaccaa8d6a7736b19080aff5a70448a7ba692271"
  integrity sha512-nDctevR9KyYFyV+m+/+S4cpzCWHqj+iHDHq3QrsWezcC+B17uZdIWgCguESUkwFhM3n/56KxWVE3V6EokrmONQ==
  dependencies:
    "@types/mdx" "^2.0.0"

"@mdx-js/react@^3.0.1":
  version "3.0.1"
  resolved "https://registry.yarnpkg.com/@mdx-js/react/-/react-3.0.1.tgz#997a19b3a5b783d936c75ae7c47cfe62f967f746"
  integrity sha512-9ZrPIU4MGf6et1m1ov3zKf+q9+deetI51zprKB1D/z3NOb+rUxxtEl3mCjW5wTGh6VhRdwPueh1oRzi6ezkA8A==
  dependencies:
    "@types/mdx" "^2.0.0"
```

I'd suggest to try running some package manager deduplication util, or regenerating the lockfile from scratch. This is not really something we can solve within the Docusaurus codebase afaik, so I'll close this issue unless you find out I'm wrong.

**Comment by rainecheck** [comment]
Looks like this has been resolved behind the scenes, at least in my repos. After a fresh clean/`yarn`, whatever dependency was clashing has resolved itself in such a way that you get the error until you update from mdx 3.0.0 to 3.0.1.

**Comment by mcclowes** [comment]
Seeing this too

**Comment by slorber** [comment]
please provide a minimal repro @mcclowes
