### ISSUE TITLE
Content aligning breaks at IE v.11

### ISSUE THREAD

**Issue by sanzhardanybayev** [facebook/docusaurus#985]
## 🐛 Bug Report

When you open **Documentation page** , layout breaks.
![image](https://user-images.githubusercontent.com/13291424/46094383-97962c00-c1db-11e8-9bed-df21a88c936c.png)

**Comment by sanzhardanybayev** [comment]
Kind of stupid bug, as who the hell uses IE in 2018? 😂 Especially developers 👨‍💻👩‍💻

**Comment by fiennyangeln** [comment]
does this still exist? I dont have IE11, but I try to reproduce it using browserstack with the option below:
`OS: Windows, OS_version: 10, browser: IE, browser_version:11.0` and this is how it looks like.

<img width="1680" alt="screen shot 2018-12-15 at 12 47 27 pm" src="https://user-images.githubusercontent.com/24544912/50039142-eb404500-0067-11e9-99d0-6ea581681752.png">

**Comment by spyke01** [comment]
It's still occurring, it appears that it stems from the mainContainer overflowing from the docMainWrapper (the max width of docMainWrapper is not being affecting the children).
![image](https://user-images.githubusercontent.com/5248448/59804135-17f14580-92b3-11e9-8ce3-0ccc25aac213.png)
