### ISSUE TITLE
Doesn't support protocol-relative URL's

### ISSUE THREAD

**Issue by TheKnarf** [facebook/docusaurus#9855]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

`0.801 Error: "//localhost/" does not look like a valid URL. Make sure it has a protocol; for example, "https://example.com".`

There is no reason why Docusaurus shouldn't support protocol-relative URL's. They are valid in `<a>`-tags. 

### Steps to reproduce

1. Create a new Docusaurus project
2. Update `url` in `docusaurus.config.ts` to be '//localhost/'
3. Run the build and see it fail

### Expected behavior

For protocol-relative URL's to work, since they work in the browser.

### Actual behavior

It refuses to build.

### Your environment

- Public source code: N/A
- Public site URL: N/A
- Docusaurus version used: 3.1.1
- Environment name and version (e.g. Chrome 89, Node.js 16.4): Arc 1.30.0
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): macOS Sonoma 14.3

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by slorber** [comment]
There are good reasons for Docusaurus to ask you to provide a `config.url` protocol.

Notably important SEO meta tags (such as the canonical url and hreflang) require to have fully qualified URLs including a specific protocol.

I've mentioned this here:
https://github.com/facebook/docusaurus/issues/3825#issuecomment-1165572115

We don't use that URL for linking for for SEO. If you don't care about SEO you should still be able to build your site with an `https://`, and yet access your site with `http`
