### ISSUE TITLE
Layout moves around when switching tabs (scroll position issue)

### ISSUE THREAD

**Issue by Vic-Dev** [facebook/docusaurus#9858]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [ ] I have tried the `npm run clear` or `yarn clear` command.
- [ ] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [ ] I have read the console error message carefully (if applicable).

### Description

Same issue as before seems to have re-occurred in latest docusaurus. I copied the [previous example](https://github.com/facebook/docusaurus/issues/8625) and updated the docusaurus package, and the scroll is jumping around again.

### Reproducible demo

https://stackblitz.com/edit/github-k5xct4-kjy427?file=package.json

### Steps to reproduce

Same as the [previous example](https://github.com/facebook/docusaurus/issues/8625):

1. Go to the Blog in the Stackblitz preview pane to the right
2. Scroll down to the MDX post, it has the tabs example
3. Switch tabs and see how scroll behaves. Try both the first and the second tab group

### Expected behavior

Scroll position should be maintained when switching tabs

### Actual behavior

Page layout jumps

### Your environment

- Public source code:
- Public site URL:
- Docusaurus version used:
- Environment name and version (e.g. Chrome 89, Node.js 16.4):
- Operating system and version (e.g. Ubuntu 20.04.2 LTS):

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by slorber** [comment]
The behavior I see on the repro is indeed the one we want, so it is not a bug to me.

> see how scroll behaves

> Scroll position should be maintained when switching tabs

> Page layout jumps

Those descriptions are ambiguous. Please record a video of what you see and we'll be able to be sure if it's the behvior we want to implement.


---

See also: https://github.com/facebook/docusaurus/pull/5618

| behavior we want | behavior we don't want |
|-----|-----------|
![grouped-tabs-demo-before](https://user-images.githubusercontent.com/22929669/134792838-d80eed1a-33c8-43dd-9280-22d20f1b10d6.gif)  |   ![grouped-tabs-demo-after](https://user-images.githubusercontent.com/22929669/134792844-452b37fe-a3bd-4893-b801-a4423115d104.gif)   |
