### ISSUE TITLE
Scripts in head don't load from component on production

### ISSUE THREAD

**Issue by jcubic** [facebook/docusaurus#9860]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

Scripts don't load when using conditional rendering of script inside Head from component:

```jsx
export default function Run() {
  const prod = process.env.NODE_ENV === "production";
  return (
    <>
      <Head>
        <link rel="preconnect" href="https://cdn.jsdelivr.net" />
        {prod && (
          <>
            <script src="https://code.jquery.com/jquery-3.7.1.min.js"></script>
            <script src="/js/run.js"></script>
          </>
        )}
        <script src="/js/run2.js"></script>
      </Head>
      <div id="run">
        <div>html rendered</div>
      </div>
    </>
  );
}
```

The same code renders when using in pages but fail to run when inside components

### Reproducible demo

https://codesandbox.io/p/devbox/morning-bush-9dzlc6?file=%2Fsrc%2Fcomponents%2FRun%2Findex.tsx%3A4%2C16-4%2C53

### Steps to reproduce

1. Create a new component
2. Add Head with scripts inside conditional loading when `NODE_ENV === "production"`
3. Include that component in page
4. The script doesn't load when using `npm run build` + `npm run serve`

### Expected behavior

I expect both scripts to load

### Actual behavior

Only script outside of `NODE_ENV === "production"` are loaded

### Your environment

- Environment name and version (e.g. Chrome 89, Node.js 16.4): Brave 1.62.165 Chromium: 121.0.6167.184 
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): Fedora 39
 

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by slorber** [comment]
react-helmet / react-helmet-async (what we use for `<Head>` does not support fragments:
- https://github.com/staylor/react-helmet-async/issues/76
- https://github.com/nfl/react-helmet/issues/342

This is an issue with the dependency we use. It is unlikely we'll ever solve this.

---

In the future (React 19?) this feature should be built-in in React, and will likely support fragments. 

- https://react.dev/blog/2024/02/15/react-labs-what-we-have-been-working-on-february-2024#:~:text=server%2Dside%20logic.-,Document%20Metadata,-%3A%20we%20added%20built
- https://react.dev/reference/react-dom/components/link

Until then you'll have to deal with the limitations of the react-helmet-async lib we use. This is not the only limitation, and you can't either use a custom React component as a `<Head>` children for example.

**Comment by jcubic** [comment]
Good to know that there is a workaround.
