### ISSUE TITLE
 The htmlLang setting in the localeConfigs of i18n is invalid, and the source code remains as en

### ISSUE THREAD

**Issue by yinsel** [facebook/docusaurus#9862]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

I don't need internationalization, but I need to change`<html lang="en">`to`<html lang="zh CN">`

My configuration:

```typescript
//other...
i18n: {
    defaultLocale: 'zh-Hans',
    locales: ['zh-Hans'],
    localeConfigs: {
      'zh-Hans': {
        label: 'Chinese',
        htmlLang: 'zh_CN'
      },
    },
  },
//other...
```

### Steps to reproduce

I have used the installation tutorial in the official documentation and have tried multiple times.

### Expected behavior

View web page source code: `<html lang="zh_CN">`

### Actual behavior

View web page source code: `<html lang="en">`

### Your environment

nodejs v20.10.0

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by OzakIOne** [comment]
I've setup a repro and I get `<html lang="zh_CN">` or maybe I'm missing something ?

[Link](https://stackblitz.com/edit/github-yrabub?file=docusaurus.config.js)

![image](https://github.com/facebook/docusaurus/assets/29860391/308953a5-2d2d-41f6-9e54-5fd0948092f4)

Same result when testing locally

![image](https://github.com/facebook/docusaurus/assets/29860391/d46eecbe-d3be-4157-be7a-f4dd7ace2b77)

**Comment by slorber** [comment]
Thanks

Can confirm it works on the repro, so @yinsel please show us a runnable repro where we can see this bug in action. Most likely you did a mistake, so until a repro is provided I'm closing this issue.

---

Note the lang attribute is supposed to be a BCP47 locale:
https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/lang#language_tag_syntax

`zh CN` or `zh_CN` are not valid BCP47 codes, only `zh` or `zh-CN` is.

**Comment by yinsel** [comment]
> I've setup a repro and I get `<html lang="zh_CN">` or maybe I'm missing something ?
> 
> [Link](https://stackblitz.com/edit/github-yrabub?file=docusaurus.config.js)
> 
> ![image](https://private-user-images.githubusercontent.com/29860391/305715357-308953a5-2d2d-41f6-9e54-5fd0948092f4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgyNjcwNzMsIm5iZiI6MTcwODI2Njc3MywicGF0aCI6Ii8yOTg2MDM5MS8zMDU3MTUzNTctMzA4OTUzYTUtMmQyZC00MWY2LTllNTQtNWZkMDk0ODA5MmY0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE4VDE0MzI1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJiMTgwNmUzNzViZWJlOGZhMjM0NDMwZTc4MzViMzAzYmMzMmI1MWI4MDg2OGI3OWU3YTk2NmIxZjk2MzhlNTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KrQGzIDOmOgl0G_JzTnjfh1QMmt2XM442eIMPlcBLRE)
> 
> Same result when testing locally
> 
> ![image](https://private-user-images.githubusercontent.com/29860391/305715848-d46eecbe-d3be-4157-be7a-f4dd7ace2b77.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgyNjcwNzMsIm5iZiI6MTcwODI2Njc3MywicGF0aCI6Ii8yOTg2MDM5MS8zMDU3MTU4NDgtZDQ2ZWVjYmUtZDNiZS00MTU3LWJlN2EtZjRkZDdhY2UyYjc3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE4VDE0MzI1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTViMzZkZmZkZWE0NWFmNmM4NWNlYjE2NjdiNDljNmM1NTJiYjA4YTdhOWYxNzliYWE2MjNiN2Y2MjMwMzdlNzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kuRvY6LU_HmUyQov5eSZag3ubN4QANjMn5DUeBaNU30)

You are right, but when using the right mouse button to view the webpage source code, it is'<html lang="en">', and after JS processing, it is correct when pressing' F12 'to view the elements. I raised this question because I found that even though the page is in Chinese, Edge still prompts me to translate it into Chinese. Perhaps this is also a small bug or a point that needs optimization?

![image](https://github.com/facebook/docusaurus/assets/91541985/548b3e1c-d133-4ac9-9361-c63c23383a1a)

![image](https://github.com/facebook/docusaurus/assets/91541985/0bb43ed0-5a39-4c74-94f4-896e5656dd6d)

**Comment by slorber** [comment]
@yinsel are you using `docusaurus start` or `docusaurus build`?

The dev server init template hardcodes `en` as a language:

```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="generator" content="Docusaurus">
    <title><%= htmlWebpackPlugin.options.title %></title>
    <%= htmlWebpackPlugin.options.headTags %>
    <%= htmlWebpackPlugin.tags.headTags %>
  </head>
  <body>
    <%= htmlWebpackPlugin.options.preBodyTags %>
    <div id="__docusaurus"></div>
    <%= htmlWebpackPlugin.tags.bodyTags %>
    <%= htmlWebpackPlugin.options.postBodyTags %>
  </body>
</html>

```

This is later updated by the JS code.
It has never been a big deal so far. 
The prod build should not have langauge `en`.

If this annoys you locally, you'd rather ask Edge to never prompt you to translate content of `localhost:3000`

**Comment by yinsel** [comment]
> Thanks
> 
> Can confirm it works on the repro, so @yinsel please show us a runnable repro where we can see this bug in action. Most likely you did a mistake, so until a repro is provided I'm closing this issue.
> 
> Note the lang attribute is supposed to be a BCP47 locale: https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/lang#language_tag_syntax
> 
> `zh CN` or `zh_CN` are not valid BCP47 codes, only `zh` or `zh-CN` is.

> I've setup a repro and I get `<html lang="zh_CN">` or maybe I'm missing something ?
> 
> [Link](https://stackblitz.com/edit/github-yrabub?file=docusaurus.config.js)
> 
> ![image](https://private-user-images.githubusercontent.com/29860391/305715357-308953a5-2d2d-41f6-9e54-5fd0948092f4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgyNjcwNzMsIm5iZiI6MTcwODI2Njc3MywicGF0aCI6Ii8yOTg2MDM5MS8zMDU3MTUzNTctMzA4OTUzYTUtMmQyZC00MWY2LTllNTQtNWZkMDk0ODA5MmY0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE4VDE0MzI1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJiMTgwNmUzNzViZWJlOGZhMjM0NDMwZTc4MzViMzAzYmMzMmI1MWI4MDg2OGI3OWU3YTk2NmIxZjk2MzhlNTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KrQGzIDOmOgl0G_JzTnjfh1QMmt2XM442eIMPlcBLRE)
> 
> Same result when testing locally
> 
> ![image](https://private-user-images.githubusercontent.com/29860391/305715848-d46eecbe-d3be-4157-be7a-f4dd7ace2b77.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgyNjcwNzMsIm5iZiI6MTcwODI2Njc3MywicGF0aCI6Ii8yOTg2MDM5MS8zMDU3MTU4NDgtZDQ2ZWVjYmUtZDNiZS00MTU3LWJlN2EtZjRkZDdhY2UyYjc3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE4VDE0MzI1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTViMzZkZmZkZWE0NWFmNmM4NWNlYjE2NjdiNDljNmM1NTJiYjA4YTdhOWYxNzliYWE2MjNiN2Y2MjMwMzdlNzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kuRvY6LU_HmUyQov5eSZag3ubN4QANjMn5DUeBaNU30)

You are right, but when using the right mouse button to view the webpage source code, it is`<html lang="en">`, and after JS processing, it is correct when pressing`F12`to view the elements. I raised this question because I found that even though the page is in Chinese, Edge still prompts me to translate it into Chinese. Perhaps this is also a small bug or a point that needs optimization?

![image](https://github.com/facebook/docusaurus/assets/91541985/548b3e1c-d133-4ac9-9361-c63c23383a1a)

![image](https://github.com/facebook/docusaurus/assets/91541985/0bb43ed0-5a39-4c74-94f4-896e5656dd6d)



> Thanks
> 
> Can confirm it works on the repro, so @yinsel please show us a runnable repro where we can see this bug in action. Most likely you did a mistake, so until a repro is provided I'm closing this issue.
> 
> Note the lang attribute is supposed to be a BCP47 locale: https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/lang#language_tag_syntax
> 
> `zh CN` or `zh_CN` are not valid BCP47 codes, only `zh` or `zh-CN` is.

I made a mistake. When using the right mouse button to view the source code of a webpage, it appears to be `<HTML lang="en">`, but after JS processing, when pressing `F12` to view the elements, it appears to be correct. I raised this question because I found that even though the page is in Chinese, Edge still prompts me to translate it into Chinese. Perhaps this is also a small bug or a point that needs optimization?

> 您使用的是 or 吗？`docusaurus start``docusaurus build`
> 
> 开发服务器初始化模板硬编码为一种语言：`en`
> 
> ```
> <!DOCTYPE html>
> <html lang="en">
>   <head>
>     <meta charset="utf-8">
>     <meta name="generator" content="Docusaurus">
>     <title><%= htmlWebpackPlugin.options.title %></title>
>     <%= htmlWebpackPlugin.options.headTags %>
>     <%= htmlWebpackPlugin.tags.headTags %>
>   </head>
>   <body>
>     <%= htmlWebpackPlugin.options.preBodyTags %>
>     <div id="__docusaurus"></div>
>     <%= htmlWebpackPlugin.tags.bodyTags %>
>     <%= htmlWebpackPlugin.options.postBodyTags %>
>   </body>
> </html>
> ```
> 
> 稍后由 JS 代码更新。到目前为止，这从来都不是什么大问题。 prod build 不应有 langauge 。`en`
> 
> 如果这在本地惹恼了您，您宁愿要求 Edge 永远不要提示您翻译`localhost:3000`



> @yinsel are you using `docusaurus start` or `docusaurus build`?
> 
> The dev server init template hardcodes `en` as a language:
> 
> ```
> <!DOCTYPE html>
> <html lang="en">
>   <head>
>     <meta charset="utf-8">
>     <meta name="generator" content="Docusaurus">
>     <title><%= htmlWebpackPlugin.options.title %></title>
>     <%= htmlWebpackPlugin.options.headTags %>
>     <%= htmlWebpackPlugin.tags.headTags %>
>   </head>
>   <body>
>     <%= htmlWebpackPlugin.options.preBodyTags %>
>     <div id="__docusaurus"></div>
>     <%= htmlWebpackPlugin.tags.bodyTags %>
>     <%= htmlWebpackPlugin.options.postBodyTags %>
>   </body>
> </html>
> ```
> 
> This is later updated by the JS code. It has never been a big deal so far. The prod build should not have langauge `en`.
> 
> If this annoys you locally, you'd rather ask Edge to never prompt you to translate content of `localhost:3000`


Thank you for your reply!
