### ISSUE TITLE
Add Elasticsearch

### ISSUE THREAD

**Issue by MoogyG** [facebook/Docusaurus#987]
## 🚀 Feature

Is it planned to add elasticsearch as an Algolia alternative ?

It would make the product full featured for internal IT documentation!

**Comment by yacinehmito** [comment]
You can actually use Algolia's DocSearch internally. [See their docs](https://community.algolia.com/docsearch/run-your-own.html).

**Comment by MoogyG** [comment]
@yacinehmito this is not full self hosted, just the crawler. API calls are still made to Algolia servers.

**Comment by endiliey** [comment]
I'm going to mark this as duplicate of #776 

We allow switching the SearchBar component easily in next major version. All that's left that needs to be done is creating a Search component in React that utilizes elasticsearch
