### ISSUE TITLE
LastUpdateTime and LastUpdateAuthor are not displayed in some documents

### ISSUE THREAD

**Issue by yinsel** [facebook/docusaurus#9879]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io.
- [ ] I have read the console error message carefully (if applicable).

### Description

LastUpdateTime and showLastUpdateAuthor are not displayed in some documents.I have already opened up and hosted it on Cloudflare, and I can provide the link. The "blog" folder and "docs" folder were renamed by me as "知识库" and "博客", but I changed them back when building using Github workflow. Maybe it's related to me changing the name of the folder, but I don't quite understand why intro.md is displayed but other documents are not.

![image](https://github.com/facebook/docusaurus/assets/91541985/c834ec04-1fbb-498c-9923-4dcac42767ef)

![image](https://github.com/facebook/docusaurus/assets/91541985/dece3b62-77e1-4b08-b00d-693d8faf5b29)

### Reproducible demo

https://github.com/yinsel/docusaurus-demo     https://docusaurus-demo.yinsel.top/

### Steps to reproduce

Built according to the official building instructions.

### Expected behavior

Display last update time and author

### Actual behavior

No display of last update time and author

### Your environment

github action

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by yinsel** [comment]
The reason is that renaming the folder resulted in the modification time not being recorded in the git, which means that the docs and blog folders cannot be modified. Is there any way to modify them? The reason why I made multiple modifications and the build failed is that there is no docs folder.

**Comment by slorber** [comment]
I don't understand your question sorry

We read the last update date from Git, and your repro has no docs folder so it can't work:
https://github.com/yinsel/docusaurus-demo/tree/main/docs/

If we can't read from git, you can still provide that last update data through front matter:
https://docusaurus.io/docs/next/api/plugins/@docusaurus/plugin-content-docs#last_update
