### ISSUE TITLE
onBrokenAnchors reports spurious broken anchors for every page

### ISSUE THREAD

**Issue by Zamiell** [facebook/docusaurus#9880]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

Steps to reproduce:

```
git clone https://github.com/hanabi/hanabi.github.io.git
cd hanabi.github.io
git checkout 6f882595d54f26a2a99cb9d70f9a4e35b88c01d0
yarn
docusaurus build
```

Then you will get the following output:

```
[WARNING] Docusaurus found broken anchors!

Please check the pages of your site in the list below, and make sure you don't reference any anchor that does not exist.
Note: it's possible to ignore broken anchors with the 'onBrokenAnchors' Docusaurus configuration, and let the build pass.

Exhaustive list of all broken anchors found:
- Broken anchor on source page path = /about:
   -> linking to #other-quick-links (resolved as: /about#other-quick-links)
   -> linking to #hotkeys (resolved as: /about#hotkeys)
   -> linking to #contributing (resolved as: /about#contributing)
```

However, no such link exists in the about.mdx file, so Docusaurus is drunk.

### Your environment

- Public source code: https://github.com/hanabi/hanabi.github.io
- Public site URL: https://hanabi.github.io/
- Docusaurus version used: 3.1.1
- Environment name and version (e.g. Chrome 89, Node.js 16.4): Node 20.10.0
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): Windows 10

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by OzakIOne** [comment]
Hello, I've tried to replicate your project locally however, by following your instructions, I have an error related to python, I don't know how to fix this error neither why you need python.

Could you provide a smaller source code with the strict minimum required to run Docusaurus so that we can debug knowing the error can't come from an external dependency

**Comment by slorber** [comment]
It looks like your site has a weird behavior regarding heading anchors: the `#` heading icon is not showing on hover and the HTML structure is different too.

This is very likely the reason.

![CleanShot 2024-02-23 at 12 17 34](https://github.com/facebook/docusaurus/assets/749374/b861cb5e-8e4d-4db1-8051-23f5ad923100)


![CleanShot 2024-02-23 at 12 15 40](https://github.com/facebook/docusaurus/assets/749374/20d352af-16c4-4581-a242-ae313268492f)


I don't understand how you modified your site, but it is not the standard behavior so you probably did something.

If you have a custom theme heading component, make sure to use the new documented hook in it:

```js
export default function Heading({as: As, id, ...props}: Props): JSX.Element {
  useBrokenLinks().collectAnchor(id);
  <As id={id} {...props}/>;		
}
```

https://docusaurus.io/docs/docusaurus-core#useBrokenLinks

**Comment by Zamiell** [comment]
I'll work on a more minimal reproduction, thanks.

**Comment by polly-bold** [comment]
I am having the same issue. Upon building the site, I get a huge number of broken anchor false positives. We haven't done anything out of the ordinary. Unfortunately, upgrading to docusaurus 3.2 didn't work, either. Did you find anything that resolved this for you @Zamiell ?

**Comment by Zamiell** [comment]
iirc i had some other dep that got upgraded which caused this to happen

**Comment by slorber** [comment]
Similar answer to https://github.com/facebook/docusaurus/issues/9721#issuecomment-2049301009, we need more info to troubleshoot such problem.

Yes, third-party plugins can also be the cause of such false positives. In which case it's helpful to share which plugins you are using so that we can inspect their code.

**Comment by erenkan** [comment]
Another use case that causes this issue occurs when you use  before the titles. On the main blog page, the anchors cannot find the related links, which results in an error.

```markdown
- [Section One](#section-one)
- [Section Two](#section-two)

<!-- truncate -->

## Section One

Content for section one.

## Section Two

Content for section two.
```

**Comment by slorber** [comment]
@erenkan this is another bug reported here: https://github.com/facebook/docusaurus/issues/10287
