### ISSUE TITLE
[Bug]: `Invalid name=docusaurus-plugin-vercel-analytics version number=0.0.0-5831.`

### ISSUE THREAD

**Issue by SilianZ** [facebook/docusaurus#9882]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [ ] I have tried the `npm run clear` or `yarn clear` command.
- [ ] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io.
- [ ] I have read the console error message carefully (if applicable).

### Description

```
Error: Invalid name=docusaurus-plugin-vercel-analytics version number=0.0.0-5831.
All official @docusaurus/* packages should have the exact same version as @docusaurus/core (number=3.1.1).
Maybe you want to check, or regenerate your yarn.lock or package-lock.json file?
```

```json
  "dependencies": {
    "@docusaurus/core": "^3.1.1",
    "@docusaurus/plugin-vercel-analytics": "^0.0.0-5831",
    "@docusaurus/preset-classic": "^3.1.1",
    "@mdx-js/react": "^3.0.0",
    "asciinema-player": "^3.0.0-rc.1",
    "clsx": "^1.2.1",
    "docusaurus-mdx-checker": "^3.0.0",
    "prettier": "^3.0.3",
    "prism-react-renderer": "^2.1.0",
    "react": "^18.2.0",
    "react-dom": "^18.2.0"
  },
```

### Steps to reproduce

1. Run `npm start`.

### Expected behavior

Runs normally.

### Actual behavior

An error occurred.

### Your environment

- Public source code: https://github.com/SilianZ/akari-site
- Docusaurus version used: 3.1.1

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by slorber** [comment]
This is not released yet 😅 

> Error: Invalid name=docusaurus-plugin-vercel-analytics version number=0.0.0-5831.
All official @docusaurus/* packages should have the exact same version as @docusaurus/core (number=3.1.1).
Maybe you want to check, or regenerate your yarn.lock or package-lock.json file?

This is not a bug: you should read the message and follow the instructions. It is not allowed to mix 3.1.1 and a canary version, you should either choose one or the other.
