### ISSUE TITLE
Dark mode not sticking on Brave Browser

### ISSUE THREAD

**Issue by cmo-pomerium** [facebook/docusaurus#9887]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [ ] I have tried the `npm run clear` or `yarn clear` command.
- [ ] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io.
- [ ] I have read the console error message carefully (if applicable).

### Description

Dark mode is not being "remembered" by Docusaurus when I use Brave Browser upon page refresh.

### Steps to reproduce

I discovered this while on Pomerium's docusaurus, but it's the same on https://docusaurus.io/docs

Step 1: Toggle dark mode.
Step 2: refresh the page (I use F5)
Step 3: See the page is no longer dark mode. 

### Expected behavior

It used to retain dark mode unless I completely clear cache/cookies.

### Actual behavior

I refresh the page and it's now light mode.

For what it's worth, this seems to be Brave Browser only. I tested on Chrome and that's fine. Additionally, if I set to dark mode and click around documentation, it retains dark mode until refresh (or I enter docs again).

### Your environment

- Public source code:
- Public site URL:
- Docusaurus version used: Latest
- Environment name and version (e.g. Chrome 89, Node.js 16.4): Brave: [Version 1.63.161 Chromium: 122.0.6261.57 (Official Build) (64-bit)](https://brave.com/latest/)
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): Microsoft Windows 10 Pro, Version 10.0.19045 Build 19045

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by slorber** [comment]
I downloaded Brave on macOS and it works perfectly fine on both our site, and on https://www.pomerium.com/docs

If it doesn't work, it is either a Brave Ubuntu bug (unlikely), or you turned on some privacy/security setting that prevents us from using localStorage, or you use browser extensions that prevent it. If you don't know how to fix it, I'd suggest reinstalling Brave from scratch and disabling all extensions.

Ask a colleague to test under Brave and you'll see it works fine for them.
