### ISSUE TITLE
Issues with npm run build with custom calendar component

### ISSUE THREAD

**Issue by goanpeca** [facebook/docusaurus#9895]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

Hello, thanks for this awesome project.

We are trying to embed a react component inside a MDX page. This component is being used and works for the development server. However for `npm run build` we are getting the following stack trace and we are not sure what might be causing it.

### Reproducible demo

Thanks!

### Steps to reproduce

The PR with the issues is located at  https://github.com/conda-forge/staged-recipes/pull/25576

The deployed site with netlify can be seen at https://app.netlify.com/sites/conda-dot-org/deploys/65de4d369d291500086dff86

The config file is located at  https://github.com/conda-incubator/conda-dot-org/pull/176/files#diff-a038096cbdea434999e1dce5ab497212f1fe18204dde1a027ce3bdd663261a2a

### Expected behavior

`npm run build` Correctly runs

### Actual behavior

```
 Server █████████████████████████ cache (99%) shutdown IdleFileCachePlugin
 resolving


Error: Unable to build website for locale en.
    at tryToBuildLocale (/Users/gpenacastellanos/Desktop/develop/conda-forge/conda-dot-org/node_modules/@docusaurus/core/lib/commands/build.js:55:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  [cause]: Error: Failed to compile due to Webpack errors.
  Error: Docusaurus server-side rendering could not render static page with path /community/calendar because of error: Cannot read properties of null (reading 'registered')
      at /Users/gpenacastellanos/Desktop/develop/conda-forge/conda-dot-org/node_modules/@docusaurus/core/lib/webpack/utils.js:207:24
      at /Users/gpenacastellanos/Desktop/develop/conda-forge/conda-dot-org/node_modules/webpack/lib/MultiCompiler.js:580:14
      at processQueueWorker (/Users/gpenacastellanos/Desktop/develop/conda-forge/conda-dot-org/node_modules/webpack/lib/MultiCompiler.js:517:6)
      at process.processTicksAndRejections (node:internal/process/task_queues:77:11)
}

[INFO] Docusaurus version: 3.1.1
Node version: v20.9.0
```

### Self-service

- [X] I'd be willing to fix this bug myself.

**Comment by slorber** [comment]
Your lib does not support server-side rendering, so you need to tell Docusaurus to not attempt to server-render it. This means bypassing static html generation of that particular calendar component.

Read docs:
- https://docusaurus.io/docs/docusaurus-core#browseronly
- https://docusaurus.io/docs/advanced/ssg#browseronly

This basically does what this other user suggests in the calendar lib:
https://github.com/ericz1803/react-google-calendar/issues/60#issuecomment-1736444567

**Comment by goanpeca** [comment]
Thanks for the quick answer! :)
