### ISSUE TITLE
[feature request] manual deploy

### ISSUE THREAD

**Issue by rickyvetter** [facebook/Docusaurus#99]
I definitely see the advantage of setting up CI deploys, but it would be really nice to be able to run `docusaurus-publish --manual` or `docusaurus-publish --local` and deploy from your own machine with your github identity. I think this would lower the barrier greatly for getting a site up and getting it running.

**Comment by endiliey** [comment]
Seems that https://docusaurus.io/docs/en/publishing.html#using-github-pages have mentioned how to manually publish without CI

```
GIT_USER=<GIT_USER> \
  CURRENT_BRANCH=master \
  USE_SSH=true \
  yarn run publish-gh-pages # or `npm run publish-gh-pages`
```
