### ISSUE TITLE
Customizable Head.js

### ISSUE THREAD

**Issue by pbares** [facebook/Docusaurus#990]
## 🚀 Feature

Currently, we can [customize the site footer](https://docusaurus.io/docs/en/custom-pages.html#customizing-your-site-footer). Would it be possible to also customize [the site header](https://github.com/facebook/Docusaurus/blob/master/v1/lib/core/Head.js)?  

## Have you read the [Contributing Guidelines on issues](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## Motivation

The main purpose is to edit/add our own the metadata tags. For instance, if we want the `docsearch:version` tag to be inserted, we must use docusaurus versioning system. 
(From Head.js)
```
...
{this.props.version && (
     <meta name="docsearch:version" content={this.props.version} />
)}
...
```
However, due to [some limitations](https://docusaurus.io/blog/2018/09/11/Towards-Docusaurus-2#versioning), I prefer to use git to version my documentation.  Without this metatag, algolia search won't work. Here's an extract of a conversation I had with an engineer from Algolia:

> Furthermore the docsearch meta data for the version is missing, could you fixed it please? The language meta data is correctly set in your DOM. The search is not working because the search-UI filter on these versions that are missing.
> 
> Look this example for the docusaurus website:
> 
> // Here a screenshot of Chrome dev tool showing the metadata tags of docusaurus website. 
> 
> Once these issue are fixed, your index will be correctly populated and your search will work properly.

Here's my current workaround. In Footer.js:
```
class Footer extends React.Component {
  render() {
    const algoliaCodeInjection = {
      __html: `
        const meta = document.createElement('meta');
        meta.setAttribute('name', 'docsearch:version');
        meta.setAttribute('content', '${this.props.config.documentationVersion}'); // the current version 
        document.head.appendChild(meta);
      `
    }

    return (
      <footer className="nav-footer" id="footer">
        <script dangerouslySetInnerHTML={algoliaCodeInjection} />
        ....
     )
}
```
  

## Pitch

To fix it, I suggest to do like for the site footer. Move the Head.js file next to Footer.js, import it with (Site.js):
```
const Head = require('${process.cwd()}/core/Head.js');
const Footer = require(`${process.cwd()}/core/Footer.js`);
```

**Comment by endiliey** [comment]
Implemented in v2. We use react-helmet on v2.

Read more about it at https://docusaurus.io/blog/2018/09/11/Towards-Docusaurus-2

**Comment by pbares** [comment]
Wow I miss that one, thanks !

**Comment by endiliey** [comment]
By the way could you elaborate more on the limitation ?
