### ISSUE TITLE
Got 404 for all translations on: https://docusaurus.io

### ISSUE THREAD

**Issue by hsluoyz** [facebook/Docusaurus#991]
I want to see how Docusaurus implements its own translation as a reference, but what I found is that all translations of official website: https://docusaurus.io is down, all 404. For example: https://docusaurus.io/docs/zh-CN/installation

![image](https://user-images.githubusercontent.com/3787410/46198133-50747c00-c33e-11e8-89ab-9a1853a40d6e.png)

**Comment by endiliey** [comment]
````js
Configuration file '/home/circleci/docusaurus/v1/website/../crowdin.yaml' does not exist
```

Seems that this is caused by `v1` and `v2` separation

cc @yangshun

**Comment by endiliey** [comment]
Shall be fixed after this https://circleci.com/gh/facebook/Docusaurus/3297 is done

**Comment by hsluoyz** [comment]
I conformed that it's fixed. Thanks!

**Comment by endiliey** [comment]
Thanks for reporting. Completely missed it.
