### ISSUE TITLE
Slightly too much padding around the docsearch logo

### ISSUE THREAD

**Issue by Haroenv** [facebook/Docusaurus#992]
## 🐛 Bug Report

The DocSearch logo has slightly too much padding around it, especially by the bottom. 

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

yes

## To Reproduce

(Write your steps here:)

1. go to any docsearch page
1. make sure it has #989 deployed
1. see it's overly spaced

## Expected behavior

a balanced padding underneath the Algolia / DocSearch logo

## Actual Behavior

https://user-images.githubusercontent.com/3149997/46176510-54b48100-c2cd-11e8-80c5-3987c71a3cd0.gif
## Reproducible Demo

irrelevant here

**Comment by alkshendra** [comment]
This issue is fixed in #989, missed to mention it in my PR

**Comment by Haroenv** [comment]
I trust you did that :) 🚀
