### ISSUE TITLE
Please Block the "Bruce's Wiki" at show case since contain the Malicious links

### ISSUE THREAD

**Issue by Orca-github** [facebook/docusaurus#9921]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [ ] I have tried the `npm run clear` or `yarn clear` command.
- [ ] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io.
- [ ] I have read the console error message carefully (if applicable).

### Description

Hello everyone,

I'm reaching out to report a concern regarding a personal website's link: https://wiki.bruceworld.top/. It appears that this link redirects users to a potentially harmful website: [www.toromclick.com](http://www.toromclick.com/). I noticed this link being displayed on the [Docusaurus showcase](https://docusaurus.io/showcase?tags=personal) as a personal project.

Your attention to this matter is greatly appreciated. Thank you.
 
<img width="1863" alt="dd" src="https://github.com/facebook/docusaurus/assets/57779256/8e1929d5-a830-4069-8842-dc1631a240d7">

### Steps to reproduce

N/A

### Expected behavior

N/A

### Actual behavior

N/A

### Your environment

- Public source code:
- Public site URL:
- Docusaurus version used:
- Environment name and version (e.g. Chrome 89, Node.js 16.4):
- Operating system and version (e.g. Ubuntu 20.04.2 LTS):

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by OzakIOne** [comment]
It seems the URL has changed to [wiki.brucesong.xyz](https://wiki.brucesong.xyz/)

Indeed toromclick seems to be a "malicious" url (my ublock origin configuration block it because of easylist)
<img width="430" alt="image" src="https://github.com/facebook/docusaurus/assets/29860391/23ab838d-909f-4e61-a362-1a2171fe8a57">

**Comment by slorber** [comment]
Feel free to update the showcase entry @OzakIOne 👍
