### ISSUE TITLE
Place screenshots in the themes documentation page in the site

### ISSUE THREAD

**Issue by somecodingwitch** [facebook/docusaurus#9927]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Motivation

Theme screenshots in https://docusaurus.io/docs/api/themes would be better for fast visualization of each theme when browsing the documentation.

### Self-service

- [ ] I'd be willing to do some initial work on this proposal myself.

**Comment by scarletquasar** [comment]
> Can you expand on your idea, please?
> 
> Which kind of screenshot would you use exactly for each theme on this page?
> 
> Can you draw a mockup of how the page should look like to be more useful?

Not very detailed, just screenshots of demo sites that are using the themes listed in the documentation to quick view directly in the site

**Comment by Zenahr** [comment]
@scarletquasar The naming "themes" is a bit misleading. There are no themes like the ones you see on Wordpress and etc for Docusaurus yet.

**Comment by Josh-Cena** [comment]
Yeah, I think you are probably having a misconception like @Zenahr is saying. I don't think our current documentation would be better with screenshots—they add significant bloat to our repo size while everything is already readily visible on the website.
