### ISSUE TITLE
Spaces are no longer valid in links

### ISSUE THREAD

**Issue by Sainan** [facebook/docusaurus#9935]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [ ] I have tried the `npm run clear` or `yarn clear` command.
- [ ] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io.
- [ ] I have read the console error message carefully (if applicable).

### Description

We recently upgraded from Docusaurus 2 to 3.1.1 and this is one of our links that broke: `[constexpr attribute](Constexpr Attribute.md)`

It seems the space within the parentheses is no longer valid now. However, it is valid when I either use `%20` or angle brackets: `(<Constexpr Attribute.md>)`

This doesn't seem to be documented as an intentional breaking change from 3, so probably an unintentional break?

### Steps to reproduce

1. Create two markdown files, one with a space in the name.
2. Try to link the markdown file with the space in the name.

### Expected behavior

It would make a link.

### Actual behavior

The markdown link is not interpreted, instead dumped into the build as plain text.

### Your environment

- Docusaurus version used: 3.1.1

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by Josh-Cena** [comment]
Your original syntax was not a valid Markdown link. You can try here: https://mdxjs.com/playground/

<img width="1245" alt="image" src="https://github.com/facebook/docusaurus/assets/55398995/8c920658-ed35-49f0-b22e-a45a742fdff5">

It was a bug that Docusaurus mapped it to a valid Markdown link.

**Comment by Sainan** [comment]
Fair on not being valid Markdown. Still an undocumented breaking change. 😕

**Comment by slorber** [comment]
A bugfix is not a breaking change

You have to read the full Changelog to read about bugfixes, documenting all of them would be overwhelming.

**Comment by Sainan** [comment]
It is when it was a bug people were relying on.
