### ISSUE TITLE
An error occurred when importing a global component. The component cannot be found

### ISSUE THREAD

**Issue by bolawen** [facebook/docusaurus#9948]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io.
- [ ] I have read the console error message carefully (if applicable).

### Description

After upgrading to version 3.1.1, I reinstalled the dependencies and found that the global components were not available and must be imported into the corresponding file, which was not needed before because MDXComponents had been registered.
<img width="1412" alt="image" src="https://github.com/facebook/docusaurus/assets/57985761/181ebded-7589-41fb-9921-c65a1798912c">
<img width="832" alt="image" src="https://github.com/facebook/docusaurus/assets/57985761/cc713ebf-801b-4719-88ea-ecbf7deba918">
<img width="1160" alt="image" src="https://github.com/facebook/docusaurus/assets/57985761/fc5f21b5-247c-441b-acb7-fb5d00385f50">

### Steps to reproduce

1. After upgrading to version 3.1.1, delete all dependencies and run npm install again
2. Register a component in "src/theme/MDXComponents.js"
3. Use the component anywhere
4. An error message is displayed indicating that the component cannot be found

### Expected behavior

As before, the global components have been registered, so there is no need to import them when they are used

### Actual behavior

Have registered the global component, so in the use of the component still need to introduce, this unfriendly, then the global component of what is the point?

### Your environment

- Public source code:
- Public site URL:
- Docusaurus version used:
- Environment name and version (e.g. Chrome 89, Node.js 18.8):
- Operating system and version (e.g. Ubuntu 20.04.2 LTS):

### Self-service

- [X] I'd be willing to fix this bug myself.

**Comment by slorber** [comment]
We use MDXComponents on our website, like many other users, and it works fine.

Please create a https://docusaurus.new/stackblitz repro showing the bug in action. Until a clear repro is provided, we'll consider there's no bug.
