### ISSUE TITLE
Use pure examples in github action deployment examples

### ISSUE THREAD

**Issue by nickswiss** [facebook/docusaurus#9955]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Description

The documentation for github acions deployment is using third party packages that help, but obfiscate from the pure commands required to perform a deploy. 
The third party github actions - namely `peaceiris/actions-gh-pages@v3` and `webfactory/ssh-agent` are not from verified creators or certified from github. I would much prefer commands required absent of any third party libraries and the commands required assuming only docusaurus library is installed on the run doing the deployment. I do not think this needs to be removed as in most cases it can be used, but for organizations with finer security requirements of the actions they are using, these documents are not great examples and some pure examples would help.

### Self-service

- [ ] I'd be willing to address this documentation request myself.

**Comment by slorber** [comment]
The `peaceiris/actions-gh-pages` action is being replaced by an official one as part of a PR currently under review: https://github.com/facebook/docusaurus/pull/9937

Regarding the other one, if you have a concrete alternative to suggest to the documented workflow, please open a doc PR directly.
