### ISSUE TITLE
Can't find component when using NX and NPM Workspaces

### ISSUE THREAD

**Issue by oliveirarafa** [facebook/docusaurus#9964]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

I have a docusaurus app inside my monorepo but I can't make my site find a component library from my monorepo.

I think it might be due to hoisting the dependencies, but couldn't make it work. 

I tried to remove my site from the monorepo and the site worked fine.

### Steps to reproduce

1. Create a monorepo
2. Create a library inside the monorepo
3. Try to import the library inside the monorepo

### Expected behavior

My docusaurus app should be able to find my component library.

### Actual behavior

My docusaurus app cannot find my component library.

### Your environment

- Docusaurus version used: 3.1.1
- Environment name and version (e.g. Chrome 89, Node.js 16.4): node 20.11.0
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): Arch

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by slorber** [comment]
This issue is too abstract for us to act on.

If you want to receive help, please invest your time to create a proper minimal repro setup we can easily run, preferably using [docusaurus.new/stackblitz](https://docusaurus.new/stackblitz)

**Comment by oliveirarafa** [comment]
> This issue is too abstract for us to act on.
> 
> If you want to receive help, please invest your time to create a proper minimal repro setup we can easily run, preferably using [docusaurus.new/stackblitz](https://docusaurus.new/stackblitz)

No problem, @slorber. The problem is that MDX can't find components if i'm using a monorepo. Probably because of the hoisting of the dependencies. Anyway, I decided to shift from this so I can't, as of now, create a stackblitz repo. Maybe in the future. Thank you.
