### ISSUE TITLE
The mdx-code-block is not compatible with Windows.

### ISSUE THREAD

**Issue by wyy0512** [facebook/docusaurus#9988]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [ ] I have tried the `npm run clear` or `yarn clear` command.
- [ ] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io.
- [ ] I have read the console error message carefully (if applicable).

### Description

Placing JSX in mdx-code-block works fine on Linux, but when developing on Windows, it directly displays the code block instead.

### Steps to reproduce

Placing a piece of JSX inside mdx-code-block and running it in a Windows environment can reproduce the issue.

### Expected behavior

The card list has been rendered.
![image](https://github.com/facebook/docusaurus/assets/47966563/824e32a8-993f-4704-be86-95040555bed2)

### Actual behavior

The code block is presented.
![image](https://github.com/facebook/docusaurus/assets/47966563/c84802e1-bb6d-4d7c-9c02-c13c78ecd723)

### Your environment

- Public source code:
- Public site URL:
- Docusaurus version used: 3.1.1
- Environment name and version (e.g. Chrome 89, Node.js 16.4):chrome, Node.js 20.9.0
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): Windows 10

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by Josh-Cena** [comment]
@OzakIOne I think it's because of `\r\n`. Have you turned on CRLF?

**Comment by Josh-Cena** [comment]
That said, it should be fixed by https://github.com/facebook/docusaurus/pull/9897
