### ISSUE TITLE
Using partial props in links causes false positive `onBrokenLinks`

### ISSUE THREAD

**Issue by anatolykopyl** [facebook/docusaurus#9989]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [ ] I have tried the `npm run clear` or `yarn clear` command.
- [ ] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

If a link inside of a partial uses some value from `props`, then the link checking marks it as broken.

### Steps to reproduce

1. Create a partial
2. Create a link that looks like this in the partial:

```jsx
<a href={`/examples/${props.examplePath}`}>example</a>
```

### Expected behavior

There is no error during build

### Actual behavior

An error occurs during build.

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by Josh-Cena** [comment]
What happens if you change this to:

```mdx
import Link from "@docusaurus/Link";

<Link to={`/examples/${props.examplePath}`}>example</Link>
```

**Comment by slorber** [comment]
Proof that it works, this builds fine: https://stackblitz.com/edit/github-oz38cy?file=docs%2F_partial.mdx,docs%2Fintro.md

`<a>` are just regular links that are not even checked by the broken link checker

---

Please always provide a repro next time. Otherwise you put the burden on me to prove that the bug doesn't exist.
