### ISSUE TITLE
The MDX compiler encounters an error when a listitem element appears directly before the closing </tab> tag without proper indentation

### ISSUE THREAD

**Issue by hieplq** [facebook/docusaurus#9998]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

I encounter an error when running either `npx docusaurus-mdx-checker` or `npm run build`

> Details: Expected the closing tag `</TabItem>` either after the end of `listItem` (103:44) or another opening tag after the start of `listItem` (99:1)

The MDX parser cannot handle instances where a 'list item' (without indentation) precedes a </TabItem> element.

```
import Tabs from '@theme/Tabs';
import TabItem from '@theme/TabItem';

<Tabs>
  <TabItem value="banana" label="Banana">
    This is a banana 🍌

- list item one
  </TabItem>
</Tabs>
```

To fix the issue with the MDX parser, you can either add three spaces before 'list item' or append additional text after it.

indent list item
```
<Tabs>
  <TabItem value="banana" label="Banana">
    This is a banana 🍌

   - list item one
  </TabItem>
</Tabs>
```

append other element
```
<Tabs>
  <TabItem value="banana" label="Banana">
    This is a banana 🍌

- list item one

to fix issue
  </TabItem>
</Tabs>
```

### Reproducible demo
https://codesandbox.io/p/devbox/dazzling-austin-9q9kgn?file=%2Fdocs%2Ftab.md

### Steps to reproduce

1. create a .MD document 
2. add code
```
import Tabs from '@theme/Tabs';
import TabItem from '@theme/TabItem';

# Tutorial Intro

<Tabs>
  <TabItem value="banana" label="Banana">
- fdfd
  </TabItem>
</Tabs>
```
3. save file and see error output

### Expected behavior

compile without error and page can load

### Actual behavior

```
Compiled with problems:
×
ERROR in ./docs/tab.md
Module build failed (from ./node_modules/@docusaurus/mdx-loader/lib/index.js):
Error: MDX compilation failed for file "/workspace/docs/tab.md"
Cause: Expected the closing tag `</TabItem>` either after the end of `listItem` (9:13) or another opening tag after the start of `listItem` (8:1)
Details:
{
  "column": 3,
  "message": "Expected the closing tag `</TabItem>` either after the end of `listItem` (9:13) or another opening tag after the start of `listItem` (8:1)",
  "line": 9,
  "name": "9:3-9:13",
  "place": {
    "start": {
      "line": 9,
      "column": 3,
      "offset": 147,
      "_index": 2,
      "_bufferIndex": 0
    },
    "end": {
      "line": 9,
      "column": 13,
      "offset": 157,
      "_index": 3,
      "_bufferIndex": -1
    }
  },
  "reason": "Expected the closing tag `</TabItem>` either after the end of `listItem` (9:13) or another opening tag after the start of `listItem` (8:1)",
  "ruleId": "end-tag-mismatch",
  "source": "mdast-util-mdx-jsx"
}

    at Object.mdxLoader (/workspace/node_modules/@docusaurus/mdx-loader/lib/loader.js:130:25)
```

### Your environment

- Public source code: on demo
- Public site URL: on demo
- Docusaurus version used: 3.1.1
- Environment name and version (e.g. Chrome 89, Node.js 16.4): firefox 124.0.1 (64-bit); node.js 20.12.0
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): debian 11

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by slorber** [comment]
This is not a bug in Docusaurus, it is how MDX behaves

![CleanShot 2024-03-29 at 12 21 12@2x](https://github.com/facebook/docusaurus/assets/749374/1a597a72-1829-4230-9de6-55f25d07f27a)

We don't plan to diverge from the MDX behavior. If you have improvement suggestions for MDX, you should report them to the MDX repo, but I doubt they will consider it a bug.
